### ISSUE TITLE
Add support for FTP downloads

### ISSUE THREAD

**Issue by dangra** [scrapy/scrapy#10]
We should add support for following FTP links like:
 ftp://www.example.com/somedir/somefile.xml

I suppose Requests will only use the URL attribute (and perhaps some data in meta, if it's needed). 

As for Responses, they will contain the file contents in the body, as one would expect.
here should be a flag to enable/disable passive FTP, perhaps even per spider.

**Comment by Curita** [comment]
Merged on #329
