### ISSUE TITLE
How to get request/response meta info when errback is called?

### ISSUE THREAD

**Issue by wlnirvana** [scrapy/scrapy#1003]
I wonder if it's possible to get the `meta` and `response.url` when `errback` is called. Here is my code:

```python
class CdDvdSpider(scrapy.Spider):
    ...
    ...

    def make_requests_from_url(self, url):
        return Request(url, dont_filter=True, meta={'foo': 'foo'},
                       callback=self.parse, errback=self.error_handler)

    def error_handler(self, response):    # FIXME: argument is not response
        # print response.url
        # print response.meta['foo']
        pass
```

What I got is:
```sh.session
exceptions.AttributeError: Failure instance has no attribute 'meta'
```

I found a related post [here](http://stackoverflow.com/a/18453647/2160440) on SO. It seems the latest Scrapy (0.24.4 as of this post) still doesn't provide relevant API. If this is true, is it possible to add this feature?

**Comment by nramirezuy** [comment]
Here is an example: 
https://github.com/scrapy/scrapy/blob/master/tests/test_spidermiddleware_httperror.py#L37

I'm not quite sure why this isn't documented properly; but you should use `dir(failure)` or in your case `dir(response)` and see what you have available. In some cases is it possible to not have a response; for example if it fails before reaching the downloader.

**Comment by alexgarel** [comment]
Another trick I use to get meta is to use a specific lambda in my code.

    class CdDvdSpider(scrapy.Spider):
        ...
        ...

        def make_requests_from_url(self, url):
            meta = {'foo': 'foo'}
            return Request(url, dont_filter=True, meta=meta,
                           callback=self.parse,
                           errback=lamda self,
                           err: self.error_handler(err, meta))

        def error_handler(self, err, meta):    # FIXME: argument is not response
            print err.response.url
            print meta['foo']

**Comment by kmike** [comment]
@alexgarel your method is reasonable, but it won't work with [persistent job queues](http://doc.scrapy.org/en/latest/topics/jobs.html).

**Comment by wlnirvana** [comment]
@nramirezuy Great. Thanks a lot.

**Comment by vionemc** [comment]
The solution is use `response.request.meta`

**Comment by ayonliu** [comment]
@nramirezuy Thanks, save my day!

**Comment by EgoWumpus** [comment]
Is there a way to do this if the failure error is an `IgnoreRequest`? That exception doesn't have a response object. Is there a way to ask the spider what request it was handling?

**Comment by baby5** [comment]
in 1.5.1 you can get meta in this way
```python
def errback(self, failure):
    print(failure.request.meta)
```
this is not in doc
