### ISSUE TITLE
loader.add_json?

### ISSUE THREAD

**Issue by pawelmhm** [scrapy/scrapy#1005]
Just an idea. 

I'm dealing with lots of json so very often I have to write code like this:

```python
loader = SomeLoader()
data = json.loads(response.body)
data_i_need = data["some_key"]
loader.add_value("something", data_i_need.get("some_other_key"))
loader.add_value("another_value", data_i_need.get('something_else"))
```
this can go on for many lines and can be repetitve.

Would be really nice to have all this done in loader, so that I could write

```python
loader = SomeLoader(json=response.body, json_key="some_key")
loader.add_json("something", "some_other_key")
```
don't know how difficult to implement this would be, just suggesting this as possible improvement.

**Comment by pawelmhm** [comment]
sample implementation - very basic, not allowing for getting nested keys and without tests: https://github.com/pawelmhm/scrapy/commit/2f9ad3f440c06fdef03962609de06bf120017a67

**Comment by nramirezuy** [comment]
This is something we are using in a project with another purpose but I think it will fit here: https://gist.github.com/nramirezuy/e61e3e0a5eadbd37eebc

However I think we should use something more standard; I saw something called json path, but not sure how standard it is.

**Comment by pawelmhm** [comment]
I was looking for some standard specification, but didn't find anything good, we could just pass list to loader, and loader will figure out proper item getter for example,
for example given json like this: {"foo":{"bar":["alfa", "omega"]}}
and list of keys like this ["foo", "bar", 0], loader will add value
"alfa".  Implemented this here, will double check this and create PR: https://github.com/pawelmhm/scrapy/commit/bdbca0db86e7ed3acc57e6ea99111918b7025838

**Comment by nramirezuy** [comment]
@pawelmhm There is other guy working on a processor using jmespath. https://github.com/scrapy/scrapy/pull/1016

I motivated this processor thing because I believe that to have a `add_json` on `ItemLoader`; we need to first have a json method on Selector, and to accomplish this we will probably need a new `Response` type too.
