### ISSUE TITLE
Non-ascii field names

### ISSUE THREAD

**Issue by Vanuan** [scrapy/scrapy#1008]
In Python 2 variable names are limited by ascii character set.
CSV Scrapy exporter uses Item's field names as an csv title row.
I want to use unicode characters for csv title row.
Can I do that without writing my own exporter?

**Comment by aufziehvogel** [comment]
I think, the easiest way is - I often see this as the easiest way, so maybe I am wrong - to extend the existing class like this (untested, for reference):

```python
class UnicodeCsvItemExporter(CsvItemExporter):
    def __init__(self, file, include_headers_line=True, join_multivalued=',', headers={}, **kwargs):
        super(UnicodeCsvItemExporter, self).__init__(file, include_headers_line, join_multivalued, **kwargs)

        self.header_mapping = headers

    def _write_headers_and_set_fields_to_export(self, item):
        if self.include_headers_line:
            if not self.fields_to_export:
                self.fields_to_export = item.fields.keys()
            # Maybe list(...) is required here to give writerow a list and not a lazy iterable
            self.csv_writer.writerow(map(lambda x: self.header_mapping[x], self.fields_to_export))

**Comment by nramirezuy** [comment]
@Vanuan Extend [this method](https://github.com/scrapy/scrapy/blob/master/scrapy/contrib/exporter/__init__.py#L191) to pull the header name from the [item.Field](doc.scrapy.org/en/latest/topics/items.html#item-fields).
