### ISSUE TITLE
Small Issue on the Extensions page of the documentation

### ISSUE THREAD

**Issue by SudShekhar** [scrapy/scrapy#1009]
Hi,
 In the Sample Extension code given on the extensions page (http://doc.scrapy.org/en/latest/topics/extensions.html), we are setting  `self.item_count = 0`  whereas (I think) it should be `self.items_scraped =0` as items_scrapped is the counter

**Comment by nramirezuy** [comment]
I think the code is right; can you paste the line and some context to be sure?

**Comment by SudShekhar** [comment]
IMO the code aims to display the "scrapped .. items " message each time we have crawled a certain number of items (equal to MYEXT_ITEMCOUNT in the settings and stored as item_count in the class).

In the current code, after the first match between items_scraped and item_count, we set item_count to 0 (hence the equal condition remains false from here on) and message is logged only once.

```python
 def item_scraped(self, item, spider):
        self.items_scraped += 1
        if self.items_scraped == self.item_count:  #set to 0 after the first match
            spider.log("scraped %d items, resetting counter" % self.items_scraped)
            self.item_count = 0
```
This is why I think we should be settings items_scraped = 0, so that we get the reset message each time we have scraped the required number of items.

I am interepreting the line stating the aim of the code like this:  "This extension will log a message every time a specific number of items are scraped ". If we interpret the meaning as reporting a message the first time we see a specific number of items, the current code is correct.

**Comment by nramirezuy** [comment]
@SudShekhar Do you want to submit a PR? I can merge it

**Comment by SudShekhar** [comment]
I would love to! Will submit it soon.

**Comment by dufferzafar** [comment]
Since the PR #1001 has been merged, I think this issue should be closed.
