### ISSUE TITLE
Expanding default list of processors?

### ISSUE THREAD

**Issue by Granitas** [scrapy/scrapy#1010]
Processors for Item Loaders are really powerful and quite unavoidable. However the default set seems be rather barebones.
I have few suggestions from few processors I use quite often to fix that, them being:
StripChars(chars) - strips away leading/following chars.
TakeNth(position) - Like TakeFirst() but for nth element.
OnlyDigits() - gets rid of everything that is not a digit.
OnlyChars() - gets rid of digits and punctuation characters(string.punctuation).  

Could any of those fit in scrapy processors?

edit: see pull request for my attempt: https://github.com/scrapy/scrapy/pull/1012

**Comment by nramirezuy** [comment]
It's a good idea to provide some more. If you can make a PR with what you got; it probably will get more attention.

**Comment by dfockler** [comment]
I would really love a replace input processor like `Replace(find, replace)`, doing replacement in the regexes can get a little unruly.

**Comment by SudShekhar** [comment]
I would be glad to assist if any help is required creating these.

**Comment by aufziehvogel** [comment]
`OnlyEnglish` is a bit an odd name in my eyes when `OnlyAscii` shows more clearly what the method seems to be doing. Maybe `OnlyAsciiStrings` would be even better to show that it does not filter non-ascii characters, but drop all strings containing non-ascii chars. On the other hand, `OnlyAscii` fits into your naming scheme with `OnlyDigits` and `OnlyChars`.

Apart from this, I'd also suggest parsing methods like ParseInt, which transforms '123,456.78' into `123456.78` (or other separators according to constructor settings).

**Comment by Granitas** [comment]
Thanks for the feedback @aufziehvogel . I've implemented your suggested changes and a bit more (see https://github.com/scrapy/scrapy/pull/1012)

**Comment by redapple** [comment]
The discussion has moved to https://github.com/scrapy/scrapy/pull/1045
