### ISSUE TITLE
No doc for the ExtensionManager

### ISSUE THREAD

**Issue by hitalex** [scrapy/scrapy#1024]
There is no doc for `scrapy.extension.ExtensionManager`. 

Besides, by looking at the code, `ExtensionManager` is derived from `MiddlewareManager` and both of them do not provide any useful information, except `self.middlewares`.

I think the `ExtensionManager` should provide access to all the initiated extension objects by name, perhaps.

**Comment by nramirezuy** [comment]
That is because it is an internal API, isn't meant to be documented. Can I ask how are you using this `ExtensionManager`?

**Comment by hitalex** [comment]
In some cases, I want to access the  extension objects initiated by Scrapy, since the extensions may record some stats.

**Comment by nramirezuy** [comment]
We have a [`StatsCollector`](http://doc.scrapy.org/en/latest/topics/api.html#stats-collector-api) instance that you can access via `crawler.stats`

**Comment by hitalex** [comment]
I have tried that approach, but it didn't work out. 
To be more specific, I want to record the number of request scheduled, so I bind the `request_scheduled` signal to a method in my stats class.

    class ItemStatsCollector(StatsCollector):
        def __init__(self, stats):
            super(ItemStatsCollector, self).__init__(stats)
            self.stats = stats
    
        @classmethod
        def from_crawler(cls, crawler):
            ext = cls(crawler.stats)
            crawler.signals.connect(ext.request_scheduled, signal=signals.request_scheduled)
            return ext
        
        def request_scheduled(self, request, spider):
            self.stats.inc_value('request_scheduled')

In my spider class, after I ran the spider, I find that `self.crawler.stats.get_value('request_scheduled')` never change. Is this a correct approach?

**Comment by nramirezuy** [comment]
There is no need to inherit from `StatsCollector`. Also this `ItemStatsCollector` is set somewhere? 
http://doc.scrapy.org/en/latest/topics/extensions.html#loading-activating-extensions

**Comment by hitalex** [comment]
I set the `ItemStatsCollector` in the `setting.py`: `STATS_CLASS`: http://doc.scrapy.org/en/latest/topics/settings.html#std:setting-STATS_CLASS

**Comment by Gallaecio** [comment]
@hitalex Have you checked if the stats collector at `crawler.stats` is an instance of your class. Because, if so, a lack of documentation of ExtensionManager is not the issue here.

**Comment by Gallaecio** [comment]
Closing due to a lack of feedback.
