### ISSUE TITLE
How to get the number of requests in queue in scrapy?

### ISSUE THREAD

**Issue by hitalex** [scrapy/scrapy#1026]
I am using scrapy to crawl some websites. How to get the number of requests in queue in scrapy?

I have posted this question in stackoverflow: http://stackoverflow.com/questions/28169756/how-to-get-the-number-of-requests-in-queue-in-scrapy

**Comment by nramirezuy** [comment]
We don't answer support questions on github; but we do on [scrapy-users](https://groups.google.com/forum/#!forum/scrapy-users).

`Scheduler` save stats per input and output, that will give you an idea.

**Comment by nramirezuy** [comment]
We don't answer support questions on github; but we do on [scrapy-users](https://groups.google.com/forum/#!forum/scrapy-users).

`Scheduler` save stats per input and output, that will give you an idea.
