### ISSUE TITLE
Remove deploy command

### ISSUE THREAD

**Issue by pablohoffman** [scrapy/scrapy#1027]
`scrapy deploy` command was deprecated a while ago and is no longer maintained. Its functionality has been moved to `scrapy-deploy` (for scrapyd) and `shub deploy` (for scrapinghub).

So I think we should remove `deploy` command, specially for 1.0.

**Comment by nyov** [comment]
As stated in #1093, we should then have another `scrapyd-client` package, so users don't need to install scrapyd locally to deploy to a remote scrapyd instance.

This begs the question, if it really makes sense to scrub it from `scrapy` in the first place?

**Comment by rdowinton** [comment]
@nyov good point :) I think the case for removing from `scrapy` is so we have the deploy functionality in one place (scrapyd-client) rather than maintaining the same functionality in two separate tools.

**Comment by nyov** [comment]
Yeah it looks like the best solution in the end. Somewhat like the json-rpc feature got it's own package.
