### ISSUE TITLE
Adding more flexible crawl configuration (expanding start_url)?

### ISSUE THREAD

**Issue by yangmillstheory** [scrapy/scrapy#1030]
I'm working on a scrapy project where a "rabbit client" and "crawl worker" work together to consume scrape requests from a queue. These requests have more configuration than a start_url - it could be something like url and a set of xpaths, or a domain-specific configuration, like site-specific product ID (from which we programmatically build the url) and optional identifiers like color, style, and size to further specify the item one wants to scrape. 

I ended up rolling my own generic abstract base classes to support this. These classes expose an interface that provide for crawl configuration validation and deserialization.

I'm wondering if it would be desirable to have built-in support for more specific "crawl configurations" like this within the framework? If that's the case, I'd be more than happy to have a design discussion and hash out the details. 

I'm looking for specifically for replies from project maintainers/contributors to see whether or not this is feasible - I don't want to waste anyone's time, including mine. If it is, I'd love to tackle it myself with some design guidance, to make sure I'm working with the framework instead of against it.

**Comment by nramirezuy** [comment]
This is currently possible by using `start_requests` and `Request.meta`. So at the end it will rely on how clean is your implementation, I'm pretty sure there will be people using it if is easy to learn/use.

**Comment by yangmillstheory** [comment]
Thank you for the reply; I'm very interested in contributing! 

Part of the implementation does override `start_requests` uses `Request.meta` to carry the crawl configuration along, so that's encouraging. 

I think I can start with reading the existing code, then trying to work my way in - but are there any user requirements that we definitely know we want to cover with this idea (would welcome any discussion here)?

For this new "configured" approach, I ended up writing a few classes, and it seems like they could be a part of this new work:

* `CrawlConfig` (encapsulates the notion of `start_url`)
* `CrawlSeries` (expands upon the notion of `start_urls`)
* `ConfiguredSpider` (has-one `CrawlConfig`, has-one `CrawlSeries`)
* `ConfiguredRequest` (subclasses `Request`, has-one `CrawlConfig`)

**Comment by kmike** [comment]
@yangmillstheory could you please give an usage example? I don't quite understand the use cases.

We also have [CrawlSpider](http://doc.scrapy.org/en/latest/topics/spiders.html?#crawlspider-example) which looks related.

**Comment by nramirezuy** [comment]
I was about to ask for the same. Usage examples :smile:

**Comment by yangmillstheory** [comment]
OK, I'll get back in a little bit about potential use cases. I want to make sure I'm not duplicating effort or existing work.

**Comment by yangmillstheory** [comment]
I guess the best examples of use cases is in the project I wrote. The focus is to search for a particular product on a domain, then scrape the product. There are N domains, and one spider implementation for each of these.

For example, I have a spider that targets an e-commerce site. This site defines unique product identifiers (call it PIN, Product Identifier Number), and we can programmatically generate product detail urls from them. In addition, some products have additional qualifiers, like color, style, or size. Additionally, we can also search the site by a different product identifier field, say UPC. The spider ends up having a crawl queue that replaces `start_urls`, that internally looks like:

    {"pin": 12345, "color": "Black"}, {"upc": 56789, "size": "Small"}, {"url": "http://www.example.com"}, ...

These objects are modeled by some implementation of `CrawlConfig`. Part of the contract of `CrawlConfig` is a `start_url` `@property` that's typically generated from the configuration data, so in that sense, a list of such objects (a `CrawlSeries`) extends the notion of `start_urls`. From the data in these objects, we can model a targeted crawl, through the site that scrapes the objects (each with optional configuration like style, color, and size). 

There's another spider that ingests a URL and a set of xpaths, so the crawl queue would look like:

    {"url": url1, "item_name_xpath": xpath1_1, "sale_price_xpath": xpath1_2}, , {"url": url100, "item_name_xpath": xpath100_1, "sale_price_xpath": xpath100_2}...

The reason I needed to structure my application in this way was due to the fact that the urls weren't consistently available, sometimes I had to work with product identifiers from a given site (plus additional product attributes), and sometimes all I had were xpaths that a client provided; the item fields were the same, but the url's and xpaths were all different.

Is this a reasonable example? You can imagine that for crawls through other sites, I'd have a different crawl configuration structure that would reflect the site's implementation (which would implement the abstract base class `CrawlConfig`), but they'd all have a `start_url` property that's a function of the crawl configuration data. The corresponding `ConfiguredSpider`'s responsibility is just to know how to parse the individual pages, but it also knows how to interpret its own `CrawlConfig` - in the first example, for instance, it'd know that if a `color`, `style`, or `size` key exists in the configuration data, it'd need to do some additional work.

Is this case too limited? I think this approach definitely worked for me and seems like it will continue to work as I add more spiders. However, is it general enough to be useful to others, and does something like this already exist in the framework, but I just missed it?

**Comment by kmike** [comment]
@yangmillstheory I still don't quite understand it, sorry :) Is it something like the following?
```
import scrapy

class MySpider(scrapy.Spider):
    search_requests = [
        {"pin": 12345, "color": "Black"}, 
        {"upc": 56789, "size": "Small"}, 
        {"url": "http://www.example.com"},
    ]
    def start_requests(self):
        for params in self.search_requests:
           url = self.get_search_url(params)
           yield scrapy.Request(
               url=url,
               callback=self.parse,
               meta={'original_params': params}   # just in case
           )
    
    def get_search_url(self, params):
        if 'pin' in params:
            url = "http://example.com/%s" % params["pin"]
        # ...
        return url
    
    def parse(self, response):
        # ... 
```

**Comment by yangmillstheory** [comment]
No worries, thanks for your time. 

Yep - that's basically it. It's that simple, actually.

I think the value the proposed code would add would be to enforce a link between a `ConfiguredSpider` class, and a `CrawlConfig` class - each abstract classes with specific implementations. Each `ConfiguredSpider` must have one `CrawlConfig`. 

There's something called a `ConfiguredRequest` too, which ensures that the `CrawlConfig` is always sent in `Request.meta`.

**Comment by kmike** [comment]
@yangmillstheory thanks for the explanation! 

For some people the code with explicit `start_requests` will be easier to follow, others may prefer a nice DSL which your ConfiguratedSpider & CrawlConfig & ConfiguredRequest provides. I don't see a clear win of abstracting out the code in the example. IMHO we already have a bit too much features in Scrapy; even some of the exsiting features could live fine as separate projects. 

I think the best way to move forward is to create a standalone pypi package with your spider configuration mini-framework and add a link to it to the [wiki](https://github.com/scrapy/scrapy/wiki).

**Comment by yangmillstheory** [comment]
Alright, sounds good. I might try to make it into a PyPi package. Feel free to close. Keep up the great work!

**Comment by kmike** [comment]
Thanks! I'll leave it to someone else to close; maybe other developers have a different opinion  (@nramirezuy?)

**Comment by nramirezuy** [comment]
I also think is a little bit too much, looks a bit confusing too me. Maybe I'm just to used to @kimke example. 

I'll wait until you have something to link, so we can add you to the wiki :smile:

**Comment by kmike** [comment]
I'm closing this ticket because there is nothing to for us here.
