### ISSUE TITLE
image pipeline - background converted to black

### ISSUE THREAD

**Issue by pawelmhm** [scrapy/scrapy#1037]
I have somewhat unusual bug related to Scrapy Images pipeline, it all happens here https://github.com/scrapy/scrapy/blob/master/scrapy/contrib/pipeline/images.py#L92 in convert_image method. 

I have following image with white background: http://images.vitaminimages.com/hb/vf/productimages/HB/370/021837_A.png background is converted to black for some strange reason. This happens because image is .png with mode 'P' and we are not adding background explicitly for this mode even though this is possible. 

```python
In [24]: from PIL import Image

In [25]: image = Image.open('021837_A.png')

In [26]: image.mode
Out[26]: 'P'

In [27]: im = image.convert('RGB')

In [28]: im.save('demo', 'JPEG')
# you will get image with black background in 'demo' file

```

Above code is what Image pipeline is doing. It does this if it detects that image mode is not 'RGBA'. Black background is added by PIL in conversion. 

But it seems that there is no problem in just converting image to this 'RGBA' mode and then adding background for it regardless of image mode. 

```python
In [54]: background = Image.new('RGBA', image.size, (255,255,255))

In [55]: img = image.convert('RGBA')

In [56]: background.paste(img, img)

In [57]: background.save('demo_other', 'JPEG')
# nice white background as expected 
```

It would be nice to add white background always when this is possible for .png images. If user is downloading lots of images he prefers to have all of them with some specific background and not other.

**Comment by nyov** [comment]
Actually the linked image has a transparent background:
````
composite -compose Dst_Over -tile pattern:checkerboard <(wget -q 'http://images.vitaminimages.com/hb/vf/productimages/HB/370/021837_A.png' -O -) alpha_checkered.jpg
```
![alpha_checkered](https://cloud.githubusercontent.com/assets/438293/6555351/0d1daae4-c65d-11e4-87ce-472c5b93bb5c.jpg)


I wouldn't want downloaded images silently converted from transparency to some static background color. That's an irreversible conversion.

If the code currently _does_ add some background color to originally transparent images, it's wrong in my opinion.
Maybe your viewer just discards the alpha mask? For example old ImageMagick versions had a bug that would show the transparent parts as black.
