### ISSUE TITLE
Add option to the parse command to attach metadata to requests

### ISSUE THREAD

**Issue by kutschkem** [scrapy/scrapy#1046]
The scrapy parse command is a wonderful tool for debugging spiders. However in my project I pass information in the requests meta attribute that is expected by the parse commands. It would be nice if it was possible to include this data in the parse command, so that testing is possible without modifying the code to not expect the meta information (and risking to forget to change everything back afterwards).

proposed syntax would be something like:

scrapy parse --spider myspider -c parse -m meta1=a -m meta2=b <url>

which would create dictionary entries { meta1:a, meta2:b } in the meta attribute of the Request.

**Comment by Digenis** [comment]
I don't think it's worth fixing, at least not this way.

Here is a workaround that can serve many use cases:
```python
def nonmeta_parse_somepage(self, response):
    enriched_meta = {...}  # defaults
    return self.parse_somepage(response.replace(meta=dict(meta, **enriched_meta))
```
```shell
scrapy parse --spider myspider -c nonmeta_parse
```
I prefer this because in the command line you can't specify any type beside strings.

Note that to discuss **usage** of the above snippet you may want to use the mailing list instead.
Here we rather talk about the significance of the problem
and the usefulness of the proposed solution.

**Comment by redapple** [comment]
I can see the use-case of adding meta do the generated request from `scrapy parse`.
The `-m` command line arguments would work for me, so that you have some flexibity on the input data. One could also use JSON strings to add more than strings.
I'd be happy to review a PR for this.

**Comment by IAlwaysBeCoding** [comment]
With all due respect @Digenis way of solving this is a horrible way to solve this problem. Here is why:

Say you are scraping an ecommerce website, in this ecommerce site you want to do a good job at testing all of the possible properties a product detail page might have. 

Now, if you are going to be testing 40 different product detail urls, with about 4 different variations possible for each product detail url. Are you going to hard code 40*4 hand unique methods into your spider and pollute it? Of course not, is like writing unit tests inside your classes. 

What @Digenis is saying to do makes 0 sense, why hard code a function that will test hard code values that you will be changing for every new test.

You want to be able to pass meta attributes through the `parse` command to test this out , not hard code it into your spider class. 

@redapple let me work on a PR for this with some tests over the next week. I really need this for my own personal use and would love to see it on Scrapy for others to use.

**Comment by kmike** [comment]
@IAlwaysBeCoding @Digenis showed a work-around which solves a problem and doesn't require modifying Scrapy. I agree that having a built-in support for it is better (👍 for sending a PR!), but @Digenis's suggestion is in no way "horrible" or "makes 0 sense". For example, his suggestion which works even with older Scrapy versions. I know you didn't mean to offend anyone, but please try to limit such strong language a bit - we all benefit if discussions are technical, without these extra emotions to handle :)

**Comment by kmike** [comment]
Closing it in favor of https://github.com/scrapy/scrapy/issues/2883.

**Comment by jimmytuc** [comment]
thanks for this
