### ISSUE TITLE
how to run tests

### ISSUE THREAD

**Issue by nyov** [scrapy/scrapy#1057]
What happened to [`bin/runtests.sh|bat`](http://doc.scrapy.org/en/latest/contributing.html#running-tests) and how do we run tests standalone now (documentation)?

How about a `Makefile` for tests and `extras/coverage-report.sh`?

**Comment by nyov** [comment]
An idea on this in #1058,
though I don't know what the documentation should say.
And if we should bring back a trivial batch file for windows?

**Comment by kmike** [comment]
It is documented here: http://doc.scrapy.org/en/master/contributing.html#tests

I'm not sure about coverage reports - many tests start separate Scrapy processes.

**Comment by nyov** [comment]
Oh ffs, I looked at the wrong version. I forgot latest != master, whoops.
I'll revise the PR.

**Comment by kmike** [comment]
master vs latest is a common point of confusion; we tried to improve it (https://github.com/scrapy/scrapy/pull/1029), but apparently it is still confusing.

**Comment by nyov** [comment]
I must have been sleepy, as I _used_ to know to look at master and not latest.
Though if `latest` could be renamed or symlinked to `stable` in the URL that might be helpful.
Oh dang, it seems stable exists and is linking to master. Huh. Maybe `released` instead of `latest`?

Anyway, any comments on my PR here ? That'd be nice. ;)
I always forget setuptools install commands, so I'd like to add some 'build' and 'install' targets to this proposed Makefile, but I'd need some help to get those right.
