### ISSUE TITLE
Sort items

### ISSUE THREAD

**Issue by Vanuan** [scrapy/scrapy#1059]
Is there an option to sort Item by field while exporting?

Currently, when you crawl, you get random order of scraped elements.

**Comment by dfockler** [comment]
Scrapy seems to process and export each item as it gets generated within the system, so there isn't really a way to compare one item against all the other items until the spider is finished running. It should be pretty easy, although not as convenient, to sort after all the items are finished being exported to a file.

**Comment by Vanuan** [comment]
I suppose, there is no any post-crawl hooks? :)

**Comment by dfockler** [comment]
Not really, you'd have to write it yourself in an extension to check when it finished using the spider_closed signal. Here's the [docs for extensions](http://doc.scrapy.org/en/latest/topics/extensions.html)

**Comment by barraponto** [comment]
@Vanuan If you do it, please publish it :)

**Comment by nyov** [comment]
I once wrote a spider to build a git object store from crawled items (wiki pages), that had to be done after all the links were crawled to generate a correct git history.

That was done firing on the `close_spider()` signal (your "post-crawl hook"), and I used a [heap queue](https://docs.python.org/2/library/heapq.html) to store all the stuff in memory until then (and have them sorted in-memory while crawling).
Not very efficient memory-wise, but the sort algorithm can obviously be done using on-disk queues if necessary, I think [queuelib](https://github.com/scrapy/queuelib) could work for that.

**Comment by nramirezuy** [comment]
:cop: Are we making this a proposal? @Vanuan Please make a PR if you are going further. If you have more questions please make use of [scrapy-users](https://groups.google.com/forum/#!forum/scrapy-userhttps://groups.google.com/forum/#!forum/scrapy-users)
