### ISSUE TITLE
Error when HTML tag have ":" character

### ISSUE THREAD

**Issue by mokrea** [scrapy/scrapy#1062]
When i try use the contains(@xml:lang,"en") the result is null

the tag:
< meta text="teste" xml:lang="pt" />
< meta text="test" xml:lang="en" />

the code:
response.xpath("//meta[contains(@xml:lang='en')/@text").extract() 

don't work

**Comment by nramirezuy** [comment]
@mokrea 
You have to register the name spaces or remove them.
Please ask for help on [scrapy-users](https://groups.google.com/forum/#!forum/scrapy-users) since this isn't a bug.
