### ISSUE TITLE
Relocate scrapy.contrib and remove scrapy.contrib_exp

### ISSUE THREAD

**Issue by kmike** [scrapy/scrapy#1063]
What do you think about getting rid of contrib and contrib_exp? Most of contrib is enabled by default anyways, it is not really contrib.

For example, we can do the following:

1. [scrapy.contrib.downloadermiddleware](https://github.com/scrapy/scrapy/tree/master/scrapy/contrib/downloadermiddleware) -> scrapy.downloadermiddleware;
2. [scrapy.contrib.exporter](https://github.com/scrapy/scrapy/tree/master/scrapy/contrib/exporter) -> scrapy.exporter;
3. [scrapy.contrib.linkextractors](https://github.com/scrapy/scrapy/tree/master/scrapy/contrib/linkextractors) -> scrapy.linkextractors;
4. [scrapy.contrib.loader](https://github.com/scrapy/scrapy/tree/master/scrapy/contrib/loader) -> scrapy.loader;
5. [scrapy.contrib.pipeline](https://github.com/scrapy/scrapy/tree/master/scrapy/contrib/pipeline) -> scrapy.pipeline;
6. [scrapy.contrib.spidermiddleware](https://github.com/scrapy/scrapy/tree/master/scrapy/contrib/spidermiddleware) -> scrapy.spidermiddleware;
7. [scrapy.contrib.spiders](https://github.com/scrapy/scrapy/tree/master/scrapy/contrib/spiders) -> scrapy.spiders;
8. files from [scrapy.contrib](https://github.com/scrapy/scrapy/tree/master/scrapy/contrib) top-level folder -> scrapy.extensions;
9. [contrib_exp](https://github.com/scrapy/scrapy/tree/master/scrapy/contrib_exp) - should we just remove it, or move contrib_exp.iterators to scrapy.util.iterators and contrib_exp.downloadermiddleware to scrapy.downloadermiddleware?

Also, @dangra or @pablohoffman said something about moving scrapy.core to scrapy.http or to a separate scrapy-core package.

I think we should also move scrapy.contrib.djangoitem to a separate repo, something like scrapy-django.

We are also inconsistent in singular-plural names (pipeline and loader, but spiders and linkextractors). I'm not sure if it worths fixing, but maybe it worths.

**Comment by nramirezuy** [comment]
If we are doing this change, would be nice to have it done for 1.0

**Comment by kmike** [comment]
In a meeting with @pablohoffman, @dangra, @redapple and @Curita we agreed on the following:

1. relocate scrapy.contrib;
2. don't do the scrapy.core / scrapy.http relocation;
3. remove contrib_exp;
4. move djangoitem to a separate project named scrapy-djangoitem;
5. keep backwards compatibility (what to do with contrib_exp?);
6. use plural names consistently (of course, when it makes sense).

As @nramirezuy said, it would be nice to have this in Scrapy 1.0 release.

**Comment by nramirezuy** [comment]
`what to do with contrib_exp?`
What do you think about creating a new repository where people can send Pull Requests with scrapy related  "experimental" features, we can review merge (just to regulate minimal standards). If a person seems committed we can give access to commit directly. 
We can add some sort of polling for the features already merged; if it gets up voted or we really like it we have two options move it to scrapy or to it's own repository.

**Comment by kmike** [comment]
Such repositories of "experimental" features quickly become a graveyard of broken code. Nobody is in charge of fixing issues (compatibility with the main repo, just bugs, Python versions support), and code of an inappropriate quality often gets merged. It was tried in past (some examples: scipy sandbox, nltk_contrib), and the results were not good.

See also a discussion of a similar idea (scikit-learn-contrib repo) in scikit-learn mailing list: http://sourceforge.net/p/scikit-learn/mailman/scikit-learn-general/thread/CA%2BA4wOknNexY6Y5rayW9ORg4%2Bo_inVpGG49WaGMxFR%2BndsUWSQ%40mail.gmail.com/#msg33106049

Why not just create individual packages? For example, @darkrho's scrapy-inline-requests is now a strong contender to become a part of Scrapy, and there was no need for a centralized repo of experimental features.

**Comment by umrashrf** [comment]
My two cents worth of idea: Create scrapylabs github account and have good packages under it. Like github.com/senchalabs.

**Comment by nyov** [comment]
I might second @umrashrf here. I understand there are already the scrapy and scrapinghub groups to manage for core developers, but another focal point for good community packages, where maybe it'd be easier to get group access, might make sense.
Thats in part why I ran with my own fork of scrapylib for some custom stuff; because related packages have to be hunted down all over and I wanted them more conveniently in a place to go to and keep them updated together, when time permits.

OTOH if we get through a useful Addons-Implementation, maybe there wouldn't be a need for one new repo per package, and keeping "`ext`'s" in a single repo akin to scraylib would be useful for focussing maintenance. (More devs looking at others code, instead of one dev feeling devoted to their repo and ignoring the rest.)
That then would be why I pushed for the mongo-pipeline merge into scrapylib.
It could even be useful to keep them together for common packaging code, even if it would build multiple (pypi) packages from the same repo.

So this is a bit of a pickle, I can't say for sure which would be nicer. Less repos to fork and keep tabs on, or drawing harder lines between projects and smaller but dedicated histories?

**Comment by nyov** [comment]
After some more thought, I wouldn't rule out having a single "contrib" repository. Even git ships with some good stuff in a contrib folder.

And it might make sense to think about splitting scrapylib in this context:
Some of the code in it is scrapinghub-API only, which should stay in there or be renamed to shublib or similar; the more generic rest (magicfields, etc) would be better in a contrib repo under the /scrapy/ group namespace.

So despite @kmike's reluctance for this, I could envision going with a(nother) single repo for contrib/exp/ext here. No-one would necessarily need to maintain it; sure there's bound to be some old or broken code over time. But it could also be a place to direct new contributors (or gsoc entrents) for easy cleanup tasks, learning the ropes by bringing code up to date with current spec, showing their abilities.

If the decision would be for such a single repo to follow in `contrib_exp`'s footsteps, I'd volunteer the name I used for my codedump: `scrapyext` (kind of a misnomer for extensions) for scrapy as `scrapylib` is for scrapinghub now -- or put `scrapylib` under scrapy and `shublib` for shub.
The repo layout then should follow scrapylib style: every folder in it being a self-standing module (and I would convert lone files to `folder/__init__.py` style to make that obvious).

p.s. Thanks for not doing a scrapy.core or scrapy.http. And sorry for :wall-of-text:

**Comment by nyov** [comment]
Is anyone working on the relocation stuff? Does that have to be backwards-compatible (keeping stubs in `contrib`?

**Comment by kmike** [comment]
AFAIK @nyov nobody is working on it. It seems an outstanding question is what to do with contrib_exp.iterators.xmliter_lxml - the options are

1. add it to scrapy.utils.iterators;
2. add it to scrapy.utils.iterators and remove the other xml iterator;
3. remove contrib_exp.iterators.xmliter_lxml.

> Does that have to be backwards-compatible (keeping stubs in contrib?)

Yes.

**Comment by Curita** [comment]
Just checking, is there anyone working on this ticket right now? I can help if there's no one interested. /cc @nyov, @nramirezuy

**Comment by Curita** [comment]
About what to do with contrib_exp.iterators.xmliter_lxml we decided on 2) on last meeting.

**Comment by nyov** [comment]
Sorry, but no, I didn't work at it.

**Comment by nyov** [comment]
Okay, I did contrib_exp. That was easy.
Could someone do the `scrapy-djangoitem` project?

**Comment by SudShekhar** [comment]
Can I work on the `scrapy-djangoitem` project, if it hasn't been taken yet?

**Comment by pablohoffman** [comment]
@SudShekhar @Curita was going to do it so I leave her to comment on that. The repo is created already: https://github.com/scrapy/scrapy-djangoitem

**Comment by Curita** [comment]
Sorry I forgot to reply to this issue, I've already started working on it. Thanks @SudShekhar for offering your help! I'll let you know if I need someone else to jump in.

**Comment by Curita** [comment]
Closed by #1181
