### ISSUE TITLE
allow spiders to return dicts instead of Items

### ISSUE THREAD

**Issue by kmike** [scrapy/scrapy#1064]
In many cases the requirement to define and yield Items from a spider is an unnecessary complication. 

An example from Scrapy tutorial:
```
import scrapy

class DmozItem(scrapy.Item):
    title = scrapy.Field()
    link = scrapy.Field()
    desc = scrapy.Field()

class DmozSpider(scrapy.Spider):
    name = "dmoz"
    allowed_domains = ["dmoz.org"]
    start_urls = [
        "http://www.dmoz.org/Computers/Programming/Languages/Python/Books/",
        "http://www.dmoz.org/Computers/Programming/Languages/Python/Resources/"
    ]

    def parse(self, response):
        for sel in response.xpath('//ul/li'):
            item = DmozItem()
            item['title'] = sel.xpath('a/text()').extract()
            item['link'] = sel.xpath('a/@href').extract()
            item['desc'] = sel.xpath('text()').extract()
            yield item
```

It can be made simpler with dicts instead of Items:

```
import scrapy

class DmozSpider(scrapy.Spider):
    name = "dmoz"
    allowed_domains = ["dmoz.org"]
    start_urls = [
        "http://www.dmoz.org/Computers/Programming/Languages/Python/Books/",
        "http://www.dmoz.org/Computers/Programming/Languages/Python/Resources/"
    ]

    def parse(self, response):
        for sel in response.xpath('//ul/li'):
            yield {
                'title': sel.xpath('a/text()').extract(),
                'link': sel.xpath('a/@href').extract(),
                'desc': sel.xpath('text()').extract(),
            }
```

The version with dicts gives a developer less concepts to learn, and it is easier to explain.

When field metadata is not used and data is exported to JSON/XML yielding Python dicts should be enough. Even when you export to CSV dicts could be enough - columns can be set explicitly by an user.

This should also prevent tickets like https://github.com/scrapy/scrapy/issues/968.

**Comment by dfockler** [comment]
+1 Although a good part about items that could be implemented using dicts, is the input and output processing per field or on every field.

**Comment by shirk3y** [comment]
Why not to go further? Spider callback could return `str`/`unicode` as request url, `Request` as request, `dict`/`Item` as item and `list` that each element would be treated separately with previous rules.

This may simplify crawling-rules logic and write code instead:

    class MySpider(CrawlSpider):
        start_urls = ['http://www.scrapinghub.com']

        def crawl(self, response):
            yield response.css('ul.menu > li > a').urls(allow='\.html$')
            yield response.css('a.next').urls()

**Comment by nramirezuy** [comment]
We can use `SpiderMiddlewares` for this, it wont need any changes to the core to be implemented.
I would love to disable this in well defined projects.

**Comment by kmike** [comment]
@shirk3y interesting idea, but it has only a limited utility - unicode/str/Link as a Request only works if you use a default callback, so it doesn't look that useful for scrapy.Spider because usually there are several callbacks. Actually I don't like that there is a default callback in scrapy.Spider - using a default calback makes code less clear, and typing savings are small.

I'm not an user of CrawlSpider myself, so can't comment of it; your example looks quite clean. If this feature is useful only for CrawlSpider then maybe it makes more sense not to add itto the core - it can be handled by a crawl spider itself.

@nramirezuy the problem with replacing dicts with Items in a middleware is that some components will get Items, and some will get dicts even if user sends only dicts. That's why I think it is good to support for dicts directly, without dict->item middleware hacks. To disable dicts one can write another middleware. I think it is good to have dicts as a well-defined and supported Scrapy feature, not just as a shortcut to define dynamic Item classes.

**Comment by nramirezuy** [comment]
Well then; [places to fix/change](https://gist.github.com/nramirezuy/12c63098ab74b6764046).

**Comment by eliasdorneles** [comment]
+1, will be nice to be able to yield dicts!
Less concepts for the newbie user. ;)

**Comment by shaneaevans** [comment]
:+1:  It will make it easier for newcomers and make Scrapy more suitable for small projects. This also means anyting that acts like a dict would be suitable as an item.

@nramirezuy - For well defined projects maybe it would make sense to add a pipeline that requires items to be of a certain type, in addition to any other validation you have.

**Comment by pablohoffman** [comment]
:+1:
