### ISSUE TITLE
Error downloading, twisted.python.failure.Failure, exceptions.ValueError

### ISSUE THREAD

**Issue by StagnantIce** [scrapy/scrapy#1069]
Please, try

scrapy fetch https://www.mediamarkt.ru

2015-03-07 15:00:40+0300 [mediamarkt_ru] ERROR: Error downloading <GET https://www.mediamarkt.ru>: [<twisted.python.failure.Failure <type 'exceptions.ValueError'>>]

**Comment by shirk3y** [comment]
When I raised this exception, I see that site sends malformed headers (they don't contain colon):
    
Headers fetched by `curl -v`:

    < Content-Security-Policy-Report-Only: default-src 'self'; font-src 'self' data: s3-eu-west-1.amazonaws.com;
    < frame-src 'self' mediamarktru.api.sociaplus.com googleads.g.doubleclick.net www.google.ru www.google.com;
    < img-src 'self' data: *.mmr.ms static-hetzner.mediasaturnrussia.ru stats.g.doubleclick.net *.maps.yandex.net mediamarktru.api.sociaplus.com mc.yandex.ru;
    < style-src 'unsafe-inline' 'self' mediamarktru.api.sociaplus.com;
    < script-src 'self' 'unsafe-inline' 'unsafe-eval' 'a856a8955f0fdd82d40710c8ce539ced=1a87fc52e5a49fd33fc945519ea2af37' blob: code.jquery.com api-maps.yandex.ru www.googleadservices.com mc.yandex.ru www.google-analytics.com stats.g.doubleclick.net googleads.g.doubleclick.net top-fwz1.mail.ru mediamarktru.api.sociaplus.com eu-sonar.sociomantic.com mediamarktru.api.sociaplus.com www.googletagmanager.com dev.visualwebsiteoptimizer.com static.criteo.net bn.adblender.ru cdn.admitad.com ad.adriver.ru;
    < report-uri /csp-report

Exception:

    twisted/web/_newclient.py", line 277, in lineReceived
            name, value = header.split(':', 1)
        exceptions.ValueError: need more than 1 value to unpack

This is `Twisted` issue, so it should be fixed there.

**Comment by StagnantIce** [comment]
Thank you for your comment!

                    try:
                        name, value = header.split(':', 1)
                        value = value.strip()
                        self.headerReceived(name, value)
                    except ValueError:
                        pass

Now works fine

**Comment by Vlek** [comment]
This is an issue with Twisted that they supposedly fixed: https://twistedmatrix.com/trac/attachment/ticket/8101/8101patch.diff

I have an up-to-date Twisted installation and this patch wasn't applied, so I manually updated mine. Hpoe that helps anyone with the same issue.
