### ISSUE TITLE
Javascript web page not rendering in splash

### ISSUE THREAD

**Issue by bgt-prabhakard** [scrapy/scrapy#1072]
I am using scrapy script to load URL using "yield".

MyUrl = "www.example.com"
request = Request(MyUrl, callback=self.mydetail)
yield request
def jobdetail(self, response):
    item['Description'] = response.xpath(".//table[@class='list']//text()").extract()
    return item

The URL seems to take minimum 5 seconds to load in browser because of javascript. So I want Scrapy to render javascript. I tried splash with scrapy but getting output as empty. I tried DOWNLOAD_DELAY also but not working.

**Comment by nramirezuy** [comment]
This is the scrapy repository we don't attend [`splash`](https://github.com/scrapinghub/splash) or [`scrapy-splash`](https://github.com/scrapinghub/scrapy-splash) issues.

If you have doubts please use [`scrapy-users`](https://groups.google.com/forum/#!forum/scrapy-users) or #scrapy on freenode.
