### ISSUE TITLE
Document interaction between priority and CONCURRENT_ITEMS

### ISSUE THREAD

**Issue by alexgarel** [scrapy/scrapy#1076]
I wanted to use request priority to crawl a site based on a cookie session. I had to submit a search form and navigate through search results. Because current search was held in the cookie session, I had to first navigate first search submission, then the second.
So I wanted to do such a thing (simplifying): 

    class MySpider(BaseSpider):

        self.start_urls = ['http://example.com/search']

        def parse(self, response):
            for data in DATA:
                yield FormRequest.from_response(
                    formdata=data, callback=self.parse_result, priority=-10)

        def parse_result(self, response):
            hxs = HtmlXPathSelector(response)
            # handle items
            # compute next_page_url
            if next_page_url:
                yield Request(next_page_url, dont_filter=True, priority=10)

I was expecting Scrapy to

1. take first form request, yielded by parse
2. call parse_result
3. then process yielded next_page requests of higher priority, till exhausted
4. then take next form request

It do not happens like that. Indeed, the form request are all processed before the other requests.

Indeed, I think this happens because Scrapy merges requests yielded by ``parse()``
into a single deferred using ``scrapy.utils.defer.parallel``.
This merge is controlled by ``CONCURRENT_ITEMS`` settings (defaults to 100).

I think this particularity should be mentioned in priority documentation here, isn't it ?

Note : I also know I can change the cookie to have separate sessions for my searches. And yes it's the way I'd go for that particular problem.

**Comment by nramirezuy** [comment]
I think the problem is:
Priorities are handled by the scheduler, but downloads are handled by the downloader. Then you have a slot on the downloader handling all the requests to that domain. By default the downloader is set to 8 requests so it asks for them, the scheduler returns what is at the top. Due to the asyc architecture we use in scrapy is totally possible that there were no "next_page requests" by the time the downloader asked for requests.

**Comment by alexgarel** [comment]
Yes your summary is exact. Is it the case to document it in some way ?

**Comment by nramirezuy** [comment]
@kmike Can help you with this. I'm not good at documenting :tongue: 

But if you want to open a PR by your own we'll be glad to review it.

**Comment by alexgarel** [comment]
I'll try :-)

**Comment by nramirezuy** [comment]
Ok, then let's keep discussing on the PR-
