### ISSUE TITLE
0.24.5 release notes are truncated

### ISSUE THREAD

**Issue by kmike** [scrapy/scrapy#1084]
It seems the longer lines are truncated in 0.24.5 [release notes](https://github.com/scrapy/scrapy/blob/master/docs/news.rst) - check "S3DownloadHandler..", "Tentative attention message...", "Patches Twisted issue..." and "SgmlLinkExtractor..."  lines. 

It is easy to fix, but I wonder why it happened. //cc @dangra

**Comment by dangra** [comment]
fixed. I guess it was a copy/paste problem on my side. thanks.
