### ISSUE TITLE
ImportError: No module named twisted

### ISSUE THREAD

**Issue by karan10** [scrapy/scrapy#1088]
I installed the Scrapy by following http://doc.scrapy.org/en/latest/topics/ubuntu.html#topics-ubuntu. The installation went perfectly. But when I run
```
scrapy startproject myproject
```
I got the following error
```
Traceback (most recent call last):
  File "/home/karan/coding/bin/scrapy", line 7, in <module>
    from scrapy.cmdline import execute
  File "/home/karan/coding/local/lib/python2.7/site-packages/scrapy/__init__.py", line 50, in <module>
    from twisted import version as _txv
ImportError: No module named twisted
```

**Comment by karan10** [comment]
installing packages twisted, w3lib, lxml and re-installing scrapy outside virtual environment using command ```sudo apt-get install python-scrapy``` did the work.

**Comment by kmike** [comment]
It seems you had other Scrapy version installed because if Scrapy is installed from PPA the scrapy binary shouldn't be in `/home/karan/coding/bin/scrapy`.

**Comment by karan10** [comment]
@pablohoffman @Curita I am working on gsoc project 'simplified scrapy add-ons'. I have submitted my proposal on google-melange for feedback. I read [this] (http://doc.scrapy.org/en/latest/topics/extensions.html) , and have few questions, how the order to the extensions are assigned? Is there any rules for the ordering number? Other than settings which files needs edit for adding a new extensions. Also please communicate me the appropriate medium for discussion or timings for IRC chat.

**Comment by Curita** [comment]
@karan10 I've just commented your proposal in Melange, please check it. Let's try to keep the discussion in Github, but we should use a proper issue related to your idea to discuss it (this one is a support issue for installing Scrapy, that should be closed because you already fix it).

I recommend you to engage in the discussion of #591, that's the issue discussing [sep-021](https://github.com/scrapy/scrapy/blob/master/sep/sep-021.rst)'s implementation.

**Comment by siriusdely** [comment]
following the [installation guide](https://doc.scrapy.org/en/latest/intro/install.html), i did `pip install Scrapy` **(with capital S)**

but after that, following the [tutorial](https://doc.scrapy.org/en/latest/intro/tutorial.html), I tried to create a project using `scrapy startproject myproject`, and then ended up with similar error with the one in this thread.

so after that, I tried `Scrapy startproject myproject` **(with capital S)**, and then everything is working fine.
