### ISSUE TITLE
i have been getting this errore although im trying to make same as scrapy website has provided an exapmle , can you anybody please tell me what am i doing wrong please ?

### ISSUE THREAD

**Issue by zzeenn** [scrapy/scrapy#1090]
![screenshot 2015-03-21 19 36 14](https://cloud.githubusercontent.com/assets/11486841/6765365/d07e29c4-d002-11e4-8fe1-f80de44ee731.png)

**Comment by kmike** [comment]
An obvious question - is there DmozItem class in tutorial/items.py ?

Also could you try renaming your spider module from "test.py" to something else? There is a "test" module in standard library, it may cause some issues.

**Comment by zzeenn** [comment]
yup i did the booth , but still im getting the sane error :(

**Comment by zzeenn** [comment]
from scrapy.tutorial items import DmozItem... how can i fix this error man please help ?

**Comment by kmike** [comment]
There is no "scrapy.tutorial.items" module, so you can't import DmozItem from there. 

I've just followed tutorial docs, and they work for me. Try following tutorial from the beginning, and check https://github.com/scrapy/dirbot which contains the finished tutorial code - this code should be correct. 

For further questions [scrapy-users](https://groups.google.com/forum/?fromgroups#!forum/scrapy-users) may be a better place.
