### ISSUE TITLE
Add scrapyd-client package

### ISSUE THREAD

**Issue by rdowinton** [scrapy/scrapy#1093]
We need to add scrapyd-client package for users so they won't need to install the full scrapyd package to deploy their code.

**Comment by nyov** [comment]
I agree. But does it even make sense to remove the command from scrapy then in the first place?

**Comment by nramirezuy** [comment]
Well thats a job for scrapyd :)

**Comment by pablohoffman** [comment]
This ticket should have been created in `scrapyd` repo.

**Comment by rdowinton** [comment]
@pablohoffman created here: https://github.com/scrapy/scrapyd/issues/85
