### ISSUE TITLE
Add deployment section to documentation

### ISSUE THREAD

**Issue by rdowinton** [scrapy/scrapy#1094]
We need to add a deployment section to the documentation covering scrapyd-deploy.

**Comment by nyov** [comment]
What about https://scrapyd.readthedocs.org/en/latest/deploy.html ?
This is where the scrapy docs links to right now. I'd think that's enough, but if you have any additions, please share.

**Comment by rdowinton** [comment]
@nyov I agree there's enough there for scrapyd, but we also wanted to mention `shub` for deploying to Scrapinghub, and perhaps condense what's in the scrapyd deployment docs to give a brief overview with a link to the main docs if the reader wants to learn more.

**Comment by nyov** [comment]
That makes sense, though it will probably make for some duplicate documentation that needs to be updated in sync for both projects afterwards, three if shub has it's own.
I'm not sure where it would fit in the current docs, maybe as a dedicated page under "Solving specific problems". I'll have to leave that to someone else anyway, as I have no knowledge of shub's apis.

**Comment by nramirezuy** [comment]
@rdowinton 
Scrapy, a fast high-level web crawling and screen scraping framework for Python.
Scrapyd, a service daemon to run Scrapy spiders.

Scrapy isn't responsible to be deployed anywhere, we can add it to [here](https://github.com/scrapy/scrapy/wiki#projects-tools-and-libraries-using-scrapy) and give this more visibility on the documentation.

**Comment by rdowinton** [comment]
@nramirezuy while it isn't responsible to be deployed anywhere, it would be good to point readers in the right direction towards the docs. As previously mentioned, we don't want to maintain duplicate documentation, so the page is more to tell them where to look. I think people are less likely to look at the projects/tools/library section than the main documentation, so I would imagine having something in the docs will provide more visibility. I've created a PR which will better demonstrate what I mean: https://github.com/scrapy/scrapy/pull/1124

**Comment by nramirezuy** [comment]
I would prefer a FAQ over it's own section.
[What is the recommended way to deploy a Scrapy crawler in production?](http://doc.scrapy.org/en/master/faq.html#what-is-the-recommended-way-to-deploy-a-scrapy-crawler-in-production)
There is no actual recommended way since it will always depend on your needs. But this doesn't mean can't offer you different flavors:
- [Cron](https://help.ubuntu.com/community/CronHowto)/[Schedule Task](http://windows.microsoft.com/en-us/windows/schedule-task) OS daemons to run tasks at desired time.
- [Scrapyd](http://scrapyd.readthedocs.org/en/latest/) is an open source project which offers an daemon for deploying and running Scrapy spiders.
- [Scrapinghub](http://scrapinghub.com/) started as a payed version of [Scrapyd](http://scrapyd.readthedocs.org/en/latest/) but now it offers a lot more features.

**Comment by kmike** [comment]
I don't have an opinion about FAQ vs a dedicated docs section, but I like @nramirezuy's list. It makes it more clear how are scrapyd and scrapy cloud related.

There are some other projects to deploy scrapy, e.g. https://github.com/dmclain/scrapy-heroku or https://github.com/TeamHG-Memex/scrapy-dockerhub. I have zero experience with them though. We shouldn't mention them in docs directly, but maybe it worths noting scrapyd is not the only way to run spiders.

https://github.com/scrapinghub/scrapyrt can be also seen as a deployment solution.

"Production" and "deployment" terms are unclear, by the way. E.g. I created a spider, executed it locally and got the data I need - what does "production" and "deployment" means here? Is it starting spiders on a schedule, or some kind of monitoring, or creating an HTTP API for a spider, or storing data in a shared DB, or crawling in parallel using many virtual servers, or what? I think it should be explained more precisely. Just "production" or "deployment" are meaningless. It is clear what "deploy a web site" means - make it reliably available to many other people, that's a point of building a web site. For spiders the end result is data, and you don't need anything besides Scrapy itself to get it.

**Comment by kmike** [comment]
I think deployment docs should explain common tasks which Scrapy doesn't solve and suggest solutions. Start/stop Scrapy spiders using HTTP API? scrapyd. Scrape a single URL using a Scrapy spider, on-demand with an HTTP API? scrapyrt. Monitor scraping progress, etc? scrapy-jsonrpc (?). Distribute load? crawl-frontier or scrape-redis. Many of this combined? Scrapy Cloud. Start spiders periodically? crontab. Etc. There is no a single "production" or "deployment" task.

**Comment by rdowinton** [comment]
@nramirezuy I think having the FAQ is a good idea, but perhaps we could have both? The FAQ would cover deploying to Scrapinghub or a remote server, and the page could cover different ways to run Scrapy as @kmike suggested, such as Scrapyd, ScrapyRT, scrapy-jsonrpc, cron jobs etc. The FAQ would explain how you can deploy. Thoughts?

**Comment by pablohoffman** [comment]
I merged #1124 and rewrote it a bit. This is a start. Thoughts?

I didn't want to include much information that could be found elsewhere, just the basics and point people to the respective doc of the different alternatives. Do you think it's worth adding a section about cron?. Calling cron a way to "deploy" spiders sounds a bit like an abuse of terminology to me, but I understand the motivation. Also, with scraypd, you also need to use cron to run spiders periodically.

I believe scrapy-dockerhub development will be moved to scrapyd 2.0, @shirk3y can confirm.

**Comment by kmike** [comment]
Should we close this issue?

**Comment by kmike** [comment]
I'm closing it for now - there is a deploymen section in docs.
