### ISSUE TITLE
Scrapy 0.26? Proposing a new stable release prior GSoC.

### ISSUE THREAD

**Issue by nyov** [scrapy/scrapy#1096]
It's been a while since the last stable release.
In fact it's been before the last GSoC project.

While it seems from the various issues I read now and then, that there is a new distant milestone for a "1.0" release, I think it's bad to ignore the here and now.
I'm not even sure if it's wise to put such a goal, where "everything" has to be "ready". It'll forever stay in the future and might take away from finishing more immediate developments.
Lots of projects have failed in the past to hang in for the long haul, after starting on or announcing a refactored "version 2" codebase, where frustration led to complete abandonment in the end.

There have been many bigger changes since 0.24 now than there were after 0.22, at least that is my feeling. I've been waiting for a new release since the last GSoC and finalization of SEP-19. My spiders still run on 0.24 stable mostly, and without a new stable version I couldn't really invest time to get to know all the great changes in 0.25/master yet.

If at all possible with current people's workloads, I would root for a small feature freeze now and finalizing a new stable release with all that's done by now, to have a good and common starting point for GSoC 2015, before that whirlwind starts hogging all ressources (I assume), if it hits scrapy ;)

**Comment by kmike** [comment]
Hey @nyov,

I agree with all your statements :) Scrapy 1.0 is very close to your Scrapy 0.26. There are no plans to break backwards compatibility or do a v2-style rewrite; spiders written for Scrapy 0.24 should work in Scrapy 1.0. The idea is to cleanup what we have now - improve the documentation and address some pain points in user API. 

It is not a far future - check the tickets for 1.0 milestone: https://github.com/scrapy/scrapy/milestones/Scrapy%201.0. Most planned features are either minor or implemented or already have pull requests in a good shape (switch to Python logging, items-as-dicts). We want to make a release in next few weeks.

**Comment by nyov** [comment]
Ah. Okay so the next release is really going to be 1.0 and pretty close.
Alright I'm out of the loop :)

Since my concerns are addressed then, I'll close and check out the remaining tickets.
Thanks.

**Comment by kmike** [comment]
Thanks @nyov - your feedback is welcome!
