### ISSUE TITLE
Tutorial uses deprecated `sel` shortcut

### ISSUE THREAD

**Issue by pbronez** [scrapy/scrapy#1107]
I'm working through the [Scrapy Tutorial](http://doc.scrapy.org/en/0.24/intro/tutorial.html) for the first time. The [Extracting Data section](http://doc.scrapy.org/en/0.24/intro/tutorial.html#extracting-the-data) uses `sel` extensively for selection (e.g. `sel.xpath('//ul/li')`)

When I run these commands in the scrapy shell, I get warning:

    <string>:1: ScrapyDeprecationWarning: "sel" shortcut is deprecated. Use "response.xpath()", "response.css()" or "response.selector" instead

If `sel` is deprecated, then the tutorial shouldn't use it.

    > scrapy --version
    Scrapy 0.24.4 - project: tutorial

**Comment by pbronez** [comment]
Is `response.xpath()` a universally acceptable substitute for `sel.xpath()`? If so, I can do a quick PR for this.

**Comment by kmike** [comment]
@pbronez a good catch. Yes, response.xpath() is a universally acceptable substitute for sel.xpath() in Scrapy shell.

**Comment by kmike** [comment]
This example should stay as-is though:
```
for sel in response.xpath('//ul/li')
    title = sel.xpath('a/text()').extract()
    link = sel.xpath('a/@href').extract()
    desc = sel.xpath('text()').extract()
    print title, link, desc
```

**Comment by pbronez** [comment]
That makes sense -  in that example, `response.xpath('//ul/li')` yields an list of `Selector` objects, and then you drill down further with additional calls to `.xpath()`

So the change since the Tutorial was written is that `sel` is no longer an alias for `response` before it is assigned to something else?

**Comment by kmike** [comment]
sel is not an alias for response; the change is that scrapy.Response got some Selector methods, and this made adding 'sel' object to Scrapy shell redundant.

**Comment by kmike** [comment]
sel is Selector(response); response.xpath now creates a Selector(response) internally and calls its xpath method.

**Comment by pbronez** [comment]
ok, that makes sense. Thanks!

**Comment by kmike** [comment]
The [docs](http://doc.scrapy.org/en/latest/intro/tutorial.html#extracting-the-data) are regenerated. Thanks Peter!
