### ISSUE TITLE
Item memory leak

### ISSUE THREAD

**Issue by nramirezuy** [scrapy/scrapy#1111]
[Here](https://gist.github.com/nramirezuy/cf6e0a41d3c7217f10a7) is a gist with outputs and how to reproduce, it is using memory_profiler.

I think it is related to http://bugs.python.org/issue9417.

Also would be nice to remove or add a note in [this](http://scrapy.readthedocs.org/en/latest/topics/practices.html#dynamic-creation-of-item-classes) doc.

**Comment by kmike** [comment]
@nramirezuy the note about dynamic items creation is removed in https://github.com/scrapy/scrapy/pull/1081

**Comment by kmike** [comment]
Items-as-dicts PR is merged, and "Dynamic Creation of Item Classes" section is removed from docs.
Do you think we should fix 0.24.x docs?

**Comment by nramirezuy** [comment]
We should probably add a `Warning` to that note. Saying something like "If you are going to make use of this feature be sure you are caching your classes and reusing them otherwise you can run into memory issues" and add a link to this ticket.

**Comment by kmike** [comment]
If somebody will submit a PR against 0.24 branch we can merge it, but this is not a problem in Scrapy 1.x, so I'm closing this ticket.
