### ISSUE TITLE
how to save scraped item in csv 

### ISSUE THREAD

**Issue by zzeenn** [scrapy/scrapy#1114]
i just scraped someitem from a website its all workedd very well , but wen i saved a CSV file and got  a csv file in my project , so i opened it and i got nothing in that csv file just a blank page has opned , am i missing any comand or packeg ?
![living social](https://cloud.githubusercontent.com/assets/11486841/6880357/c684e822-d552-11e4-8c24-218f9a6108e7.png)

**Comment by thiagof** [comment]
You already should be aware of the settings variables

```
FEED_FORMAT = 'csv'
FEED_URI = 'file.csv'
```

And the command line argument

```
scrapy crawl spider-name -o file.csv
```


But your Stats INFO doesn't show any `item_count`, which means your spider is not return an `Item` or an error occurred.

**Comment by kmike** [comment]
@thiagof is right. 

For general questions about how to use Scrapy [scrapy-users](https://groups.google.com/forum/?fromgroups#!forum/scrapy-users) is a better place, so I'm closing this ticker.
