### ISSUE TITLE
Error in installation

### ISSUE THREAD

**Issue by WandyLau** [scrapy/scrapy#1119]
I installed the Scrapy-0.25.1 in crunch bang. The first time I start it. There is an error message said:

in crawler.py 22 line , global name: SignalMadnager (which should be SignalManager) undefined. After I changed the source code then everything goes fine. But I can not see the same error in the github code. So it is a typo ?

**Comment by nyov** [comment]
git blame on the repo says this line hasn't changed in years, here.
```
1e12c92b (Pablo Hoffman 2012-03-06 08:59:20 -0200  22)         self.signals = SignalManager(self)
```

Where is your source / package from?

**Comment by nyov** [comment]
git blame on the repo says this line hasn't changed in years, here.
```
1e12c92b (Pablo Hoffman 2012-03-06 08:59:20 -0200  22)         self.signals = SignalManager(self)
```

Where is your source / package from?

**Comment by WandyLau** [comment]
My os is crunch bang and python 2.7.3. I installed it with command

##### pip install scrapy

I installed the newest version. I guess the package has some relationship with debian os.

**Comment by nyov** [comment]
I don't know why you would get a 0.25.1 version there, that doesn't even exists yet.
The latest stable release on pypi shows 0.24.5,
so you must have pulled that elsewhere I think, no idea. It doesn't look like a git version, or it would look something like 0.25.0-298-g5846d61

**Comment by WandyLau** [comment]
Below is the screenshot. 
![scrapy1](https://cloud.githubusercontent.com/assets/2303377/6932599/174d700a-d84e-11e4-95fa-9f5e21c18203.png)

It is not right?

**Comment by MojoJolo** [comment]
@pablohoffman ^ looks like he got a wrong version of Scrapy using `pip install scrapy`. I'm not sure if that's possible.

**Comment by kmike** [comment]
0.25.1 is what you can get by installing from github master branch using pip (without deb package).
 
I'm not sure what can we do here. The package must be modified or imported from a wrong location. +1 to @MojoJolo - let's close this ticket.
