### ISSUE TITLE
Exception handler for scrapy pipelines

### ISSUE THREAD

**Issue by fguilpain** [scrapy/scrapy#113]
Hello, 

I'm currently working with scrapy for web crawling and I would like to monitor pipelines with an hook which catch every exceptions, when I looked in documentation, I found out that there is already something similar item_dropped() but it catch only DropItem exceptions, it would be useful to have something more generic which catch every kind of exception.

Dangra already helped me, please take a look on his modification : http://paste.pocoo.org/show/579565/

Thanks for your attention.

**Comment by Gallaecio** [comment]
@dangra Should we close this?

**Comment by felipeboffnunes** [comment]
@Gallaecio probably yes
