### ISSUE TITLE
Alternative way to pass arguments to callback

### ISSUE THREAD

**Issue by kmike** [scrapy/scrapy#1138]
Currently to pass data between callbacks users need to use request.meta. Example from docs (simplified):

``` py
def parse_page1(self, response):
    item = MyItem(main_url=response.url)
    request = scrapy.Request("http://www.example.com/some_page.html",
                             callback=self.parse_page2)
    request.meta['item'] = item
    return request

def parse_page2(self, response):
    item = response.meta['item']
    item['other_url'] = response.url
    return item
```

While it works fine, there are some issues:
1. it seems understanding request.meta is a common struggle for beginners;
2. we're mixing parameters for Scrapy components with user data.

What about providing an alternative way?

``` py
def parse_page1(self, response):
    item = MyItem(main_url=response.url)
    return scrapy.Request("http://www.example.com/some_page.html",
                             callback=self.parse_page2,
                             kwargs={'item': item})

def parse_page2(self, response, item):
    item['other_url'] = response.url
    return item
```

Advantages:
1. If you're writing some extraction code without Scrapy (e.g. requests+lxml), then likely parsing functions have arguments. So this change makes code more natural/straightforward. 
2. Optional arguments or arguments with default values are easier to handle - just provide a default value using Python syntax.
3. User state is separated from Scrapy internals better.
4. Less code.
5. One can see which data callback needs just by looking at callback definition.
6. This way it is easier to add extra data to meta without a risk of breaking Scrapy extensions. There should be fewer bugs with missing `meta.copy()`.
7. In case of missing argument callback will fail earlier.

The implementation could add `__kwargs` field to request.meta and pass `**meta.get('__kwargs', {})` to the callback. Alternatively, we could put keyword arguments in another dict similar to meta. It will allow to separate them better. Also, rules for passing kwargs may be different from rules for passing meta (e.g. maybe meta should be preserved/copied in some cases, but not kwargs, I'm not sure).

**Comment by umrashrf** [comment]
Nice :+1:

**Comment by nramirezuy** [comment]
I don't really like the kwargs parameter added to requests and losing the ability of rapidly recognizing callbacks on a spider.

```python
from functools import wraps
from scrapy.spider import Spider
from scrapy.utils.python import get_func_args

def callback_args(f):
    args = get_func_args(f)[2:]
    @wraps(f)
    def wrapper(spider, response):
        return f(spider, response, 
            **{k:response.meta[k] for k in args if k in response.meta})
    return wrapper

class Dummy(Spider):
    name = 'dummy'

    def parse(self, response):
        return Request('http://example.com', callback=self.parse_2, 
            meta={'message': 'I\'m working fine, bros :D'})
    
    @callback_args
    def parse_2(self, response, msg):
         print 'MSG:', msg
```

**Comment by kmike** [comment]
1. `callback_args` doesn't solve (3) User state is separated from Scrapy internals better;
2. IMHO it is less straightforward / more magical;
3. you can't use **kwargs in a callback; 
4. just by looking at `parse` method you can't figure out which parameters are passed to the callback as arguments and which meta keys are meant for other Scrapy components.

> losing the ability of rapidly recognizing callbacks on a spider

What do you mean?

**Comment by dangra** [comment]
It remembers me of when the callback was a _Deferred_ instance. I can understand the motivation and don't see any drawbacks except we have to think on adding the `errback` arguments too.

**Comment by nramirezuy** [comment]
@kmike Right now all the callbacks have just `(self, response)`; when you approach a `Spider` from another dev you can do a quick pane recognizing those ones, but is minimal and not relevant.

What do you think about:
```python
    return Request("http://www.example.com/some_page.html",
                             callback=(self.parse_page2, {'item': item}))

    return Request("http://www.example.com/some_page.html",
                             callback=(self.parse_page2, (item, )))

    return Request("http://www.example.com/some_page.html",
                             callback=(self.parse_page2, (item, ), {'random': random()}))
```

**Comment by kmike** [comment]
> @kmike Right now all the callbacks have just (self, response); when you approach a Spider from another dev you can do a quick pane recognizing those ones, but is minimal and not relevant.

All the callbacks are `def foo(self, response)`, but not all `def foo(self, response)` are callbacks, so I don't think this matters. `parse_foo` names could be a stronger indicator, but it is also only a convention.

As for syntax, I like `kwargs={}` more (less nested braces + consistent argument types - callback is always a callable), but that's bike-shedding; `callback=(self.parse_page2, {'item': item})` could also work. Not sure it worths it to care about *args.

`callback=(self.parse_page2, {'item': item})` looks similar to `callback=partial(self.parse_page2, item=item)`.

**Comment by kmike** [comment]
functools.partial is an interesting option because unlike lambda it can be pickled. My gut feeling tells that explicit kwargs support in Request is a better option, but functools.partial is equally powerful.

**Comment by ArturGaspar** [comment]
@kmike functools.partial can be pickled, but instance methods cannot. Pickling e.g. `Request(callback=partial(self.parse_page, extra_arg=25))` will fail with "can't pickle instancemethod objects".
This is why `scrapy.utils.reqser` exists, not?

**Comment by kmike** [comment]
@ArturGaspar you're right! 
I should check my sources better :)
So functools.partial is not an option.

**Comment by bamdadd** [comment]
how about partialmethod? https://docs.python.org/2/library/functools.html

**Comment by kmike** [comment]
@bamdadd could you please show an example - how will [partialmethod](https://docs.python.org/3.5/library/functools.html#functools.partialmethod) help?

**Comment by jhirniak** [comment]
I came across this issue while searching for passing arguments to callbacks. @kmike proposal seems interesting as it leads to more readable code.

I see that the thread basically dried, almost 2 years, ago, receiving only short hydration 210 days ago (in engineering world, exactly 7 months ago).

Hence, my question, is there any progress/traction on this? Or has this thread became a zombie haunting the issue page? Would be good to status page to be updated or feature implemented 🎱 ;).

**Comment by redapple** [comment]
hello @jhirniak , there's not progress as far as I know.

what do you mean by ?
> Would be good for either the status page to be updated

There's no immediate or short term plan from scrapy "core" devs to implement this feature.
Contributions from the community are always welcome.

**Comment by jhirniak** [comment]
@redapple, thanks, I'll give it a go, if I find some time later.

> what do you mean by ?
> > Would be good for either the status page to be updated

What I meant was: "the status was open, so long that it could be decided not just to be implemented, hence it would be good to close it". From what you wrote, I understand why it was left open.

**Comment by aminebenichou** [comment]
hi bro I want to callback a function without putting the url
thanks in advance

**Comment by MaxValue** [comment]
Hi all! I'm gonna bump this, because I'm interested in a solution and want to raise awareness of this.

So from what I gather the current suggestion is still the one @kmike posted in the beginning. Can we implement this? It does make sense to me.

**Comment by MaxValue** [comment]
@aminebenichou I think what you mean is making a request without specifying the callback function. As far as I know, the only way is to have a function inside your spider named `parse` this will get called by default. If that was your question, this is actually the wrong thread. You can find this info [in the documentation](https://docs.scrapy.org/en/latest/topics/request-response.html#scrapy.http.Request).

**Comment by kmike** [comment]
Hey @MaxValue! I think the original idea still stands, and has some support from Scrapy core developers (unless @dangra changed his opinion, it has +2 which is enough to merge a good implementation). I think it is better to be implemented by having a different Request attribute, not by storing data in meta['__kwargs']. I don't have time to work on it in near future myself; a pull request is welcome.

**Comment by Pechi77** [comment]
I get `TypeError: __init__() got an unexpected keyword argument 'kwargs'`

which version of scrapy supports kwargs

**Comment by MaxValue** [comment]
1. I guess you are trying to pass arguments to the spider via the command line. The correct mechanism would be [spider arguments](https://docs.scrapy.org/en/latest/intro/tutorial.html#using-spider-arguments).
2. [**cb_kwargs** was introduced in 1.7](https://docs.scrapy.org/en/latest/topics/request-response.html?highlight=cb_kwargs#passing-additional-data-to-callback-functions)

Maybe you should read the documentation first?
