### ISSUE TITLE
relaxing scrapy.Item dependence on Field?

### ISSUE THREAD

**Issue by nyov** [scrapy/scrapy#1141]
Since supporting simple dicts as items, I was wondering if it wouldn't be okay to also relax `Item`'s dependence on `Field`, which is just a dict?
That would make subclassing `Item` slightly easier when it's not necessary to pull in `scrapy.item.Field`.

```diff
diff --git a/scrapy/item.py b/scrapy/item.py
index 9998010..9cb73f1 100644
--- a/scrapy/item.py
+++ b/scrapy/item.py
@@ -27,7 +27,7 @@ class ItemMeta(ABCMeta):
         fields = {}
         new_attrs = {}
         for n, v in six.iteritems(attrs):
-            if isinstance(v, Field):
+            if isinstance(v, (Field, dict)):
                 fields[n] = v
             else:
                 new_attrs[n] = v
```

**Comment by nramirezuy** [comment]
Can you explain how it makes sub classing slightly easier? Just by avoiding the import? or there is something else I'm missing.

**Comment by kmike** [comment]
I have the same question as @nramirezuy.

**Comment by nyov** [comment]
No, you're right. It's just about avoiding the import, and in defining fields like
```py
class MyItem(scrapy.Item):
	type = {type:str, 'required':True, 'default':u'simple'}
	...
```
Maybe it's not really worth changing.
