### ISSUE TITLE
Bug with Scrapy 0.25.0-298-g5846d61 and Slybot 0.9-r1039+201503231448~2f25

### ISSUE THREAD

**Issue by OlgaCh** [scrapy/scrapy#1142]
After upgrade on dash both deploy and spiders scheduling stopped to work and failed with the message:

>Traceback (most recent call last):
> File "/usr/lib/pymodules/python2.7/hworker/bot/runner.py", line 77, in main
 >  run_scrapy(settings)
 >  File "/usr/lib/pymodules/python2.7/hworker/bot/runner.py", line 87, in run_scrapy
 >    execute(settings=settings)
 >  File "/usr/lib/pymodules/python2.7/scrapy/cmdline.py", line 142, in execute
 >    cmd.crawler_process = CrawlerProcess(settings)
 >  File "/usr/lib/pymodules/python2.7/scrapy/crawler.py", line 123, in __init__
 >    super(CrawlerProcess, self).__init__(settings)
 >  File "/usr/lib/pymodules/python2.7/scrapy/crawler.py", line 77, in __init__
 >    self.spiders = smcls.from_settings(settings.frozencopy())
 >  File "/tmp/eggs-RzTd6X/__main__.egg/enclarity/spidermanager.py", line 21, in from_settings
 >    o = super(EnclaritySpiderManager, cls).from_settings(settings)
 >  File "/usr/lib/pymodules/python2.7/slybot/spidermanager.py", line 34, in from_settings
  >   return cls(datadir, spider_cls, settings=settings)
 >  File "/usr/lib/pymodules/python2.7/slybot/spidermanager.py", line 22, in __init__
  >   settings.set('PLUGINS', load_plugins(settings))
  > File "/usr/lib/pymodules/python2.7/scrapy/settings/__init__.py", line 92, in set
  >   self._assert_mutability()
 >  File "/usr/lib/pymodules/python2.7/scrapy/settings/__init__.py", line 115, in _assert_mutability
  >   raise TypeError("Trying to modify an immutable Settings object")
 > TypeError: Trying to modify an immutable Settings object

Dash link: https://dash.scrapinghub.com/p/580/job/1013/5/#/log/line/0

**Comment by kmike** [comment]
It seems you're using an outdated version of slybot which doesn't have Scrapy 0.25+support. See https://github.com/scrapy/slybot/pull/85.

**Comment by kmike** [comment]
Aha, you're using https://github.com/scrapinghub/portia/blob/master/slybot/slybot/spidermanager.py
