### ISSUE TITLE
Invalid XML parsing

### ISSUE THREAD

**Issue by nashuiliang** [scrapy/scrapy#1183]
When the XML document has invalid characters, it causes a problem that the result is not completely.
Example:  `response.body` has `\0x01` , `\0x0a` ....
Have a solution?

**Comment by dangra** [comment]
hi @chuangchuang,  what library are you using to query the XML DOM? In general you should be using `response.body_as_unicode()` instead of `response.body`. 

please provide an url or full body If you are seeing the problem while using scrapy selectors. thx

**Comment by redapple** [comment]
@nashuiliang , I am closing the issue as you have not provided sample input requested by @dangra .

If you are still experiencing the issue, please provide enough information to reproduce the bug.
Please refer to http://doc.scrapy.org/en/stable/contributing.html#reporting-bugs
Thanks.
