### ISSUE TITLE
Documentation is inconsistent regarding versions: 0.24 is "latest", 0.25 is "stable".

### ISSUE THREAD

**Issue by djacobs-verisys** [scrapy/scrapy#1186]
http://scrapy.org/ lists the "latest version" as **0.24**.

http://scrapy.org/doc/ lists the "latest version" as **0.24**.

http://doc.scrapy.org/en/latest/ contains documentation for version **0.24**.

http://doc.scrapy.org/en/stable/ contains documentation for version **0.25**.

I am confused by the inconsistency. What is the difference between "latest version" and "stable version" and why do they refer to different versions? This seems like a documentation bug.

**Comment by kmike** [comment]
There is also http://doc.scrapy.org/en/master/ :) Thanks for the report.

I guess displaying of 'stable' docs was added after we set up the account at readthedocs.org.

**Comment by kmike** [comment]
See also: https://github.com/scrapy/scrapy/issues/589

**Comment by redapple** [comment]
@kmike , I believe this is fixed?

**Comment by kmike** [comment]
yes, it seems so.
