### ISSUE TITLE
position() mod 3 = 0

### ISSUE THREAD

**Issue by aaron315** [scrapy/scrapy#1193]
in Python 2.7.8 (default, Aug  1 2014, 10:01:11) 
Scrapy==0.24.5
>>> len(resp.xpath("//div[@class='pic_text'][position() mod 3 = 0]"))
0
>>> len(resp.xpath("//div[@class='pic_text'][position() mod 1 = 0]"))
10
>>> len(resp.xpath("//div[@class='pic_text']"))
10

**Comment by aaron315** [comment]
>>>len(resp.xpath("//div[@class='pic_text'][position() mod 3 = 0]"))
should return 4,why 0
thanks

**Comment by jdemaeyer** [comment]
Hi aaron,

the behaviour you see is correct (also, this is an xpath question, not a Scrapy question ;)). `position()` refers to the position within the child axis of the selected element (that is all direct children of the div's parent), not the position within the list of divs. See the second answer here: https://stackoverflow.com/questions/4117953/get-second-element-text-with-xpath

You can either update your xpath with `descendant` or do the selection in python: `resp.xpath(//div[@class='pic_text'])[::3]`. Note that out of elements 1, 2, 3, 4, 5, 6, 7, 8, 9, this will give you elements 1, 4, 7, whereas `position() mod 3 = 0` will give you elements 3, 6, 9 (b/c like most counters in xpath, `position()` starts at 1).

Cheers

**Comment by aaron315** [comment]
thanks,
Originally, the xpath is stored in the configuration file
