### ISSUE TITLE
Flatten documentation files

### ISSUE THREAD

**Issue by pablohoffman** [scrapy/scrapy#1200]
Hot on the heels of contrib-removal (and modules relocation) comes another thought: do we really need the `topics/` and `intro/` folders separation in scrapy docs?. Wouldn't it be better to flatten the doc files?

**Comment by eliasdorneles** [comment]
I'm in favor of keeping the current structure for mainly two reasons: changing it will break not only internal links (which we could fix) but also existing external links that reflect the structure (like `http://scrapy.readthedocs.org/en/latest/intro/overview.html` or `http://scrapy.readthedocs.org/en/latest/topics/loaders.html`).

There is no straightforward way to deprecate this kind of thing, I don't think it's worth the hassle for whatever benefit we'd get from flattening.

**Comment by kmike** [comment]
I agree with @eliasdorneles - with modules relocation we're simplifying import paths which users use while not breaking anything; with doc files relocation we don't simplify anything for the user, but break existing links to the docs.

**Comment by eliasdorneles** [comment]
I think we've already agreed on this one, closing.
