### ISSUE TITLE
ItemMeta overrides fields, instead of merging it

### ISSUE THREAD

**Issue by MojoJolo** [scrapy/scrapy#1217]
Looks like this update (https://github.com/scrapy/scrapy/pull/353) breaks the `Item` for the project I'm working on right now.

It now overrides fields, instead of merging it. @michalmo pointed it out to me after the item fields are having a key error.

Inheriting `DictItem` rather than `Item` fixed the problem though.

**Comment by nramirezuy** [comment]
@MojoJolo can you give me a test case?

**Comment by MojoJolo** [comment]
Hopefully this is sufficient as a test case without revealing the project itself.

```python
class Person(Item):

    fields = {'_ignore': Field()}
    for f in set(['name', 'id', 'url', 'age', 'address']):
        fields[f] = Field()

    version_fields = ['id']
```

That class inheriting `Item` will result in `KeyError` even though the fields are instantiated using `Field()`. Changing `Item` to `DictItem` solves it.

**Comment by nramirezuy** [comment]
@MojoJolo #1228 should fix it.

**Comment by MojoJolo** [comment]
The fix was merged already. Closing this issue. @nramirezuy
