### ISSUE TITLE
Problem with tutorial and DEFAULT_ITEM_CLASS

### ISSUE THREAD

**Issue by nekopa** [scrapy/scrapy#1222]
This is my first time reporting an issue on Github so I apologise if I am breaking any etiquette. I just installed scrapy (on a Vagrant Ubuntu64 box ) and was running through the tutorial but kept getting errors at the section for starting up the scrapy shell. After a *lot* of searching I found someone who had a similar problem (but on one of their own spiders) and it boiled down to the fact that in the first section of the tutorial you have us create in the items.py a DmozItem, but in the settings.py there is this:

DEFAULT_ITEM_CLASS = 'tutorial.items.TutorialItem'

After I changed TutorialItem to DmozItem the shell worked perfectly. 

I don't know if I missed a step somewhere in the tutorial or if this is unusual behaviour, but I just wanted to give you a heads up.

**Comment by Curita** [comment]
Hi @nekopa, thanks for reporting!

I'm going to guess `scrapy shell` raised an issue because the path for DEFAULT_ITEM_CLASS didn't exist. I think Scrapy 0.10 was the last release that overwrote DEFAULT_ITEM_CLASS in settings.py while creating a new project. 

Can you tell us which Scrapy version are you using and what was the traceback from the error in `scrapy shell` so we can confirm this?

**Comment by nekopa** [comment]
Hi @Curita,
I am using scrapy 0.24.6, install via apt-get using your sources (the default packages were out of date).

Here is the traceback:

Traceback (most recent call last):
  File "/usr/bin/scrapy", line 9, in <module> load_entry_point('Scrapy==0.24.6', 'console_scripts', 'scrapy')()
  File "/usr/local/lib/python2.7/dist-packages/scrapy/cmdline.py", line 143, in execute _run_print_help(parser, _run_command, cmd, args, opts)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/cmdline.py", line 89, in _run_print_help func(*a, **kw)   
  File "/usr/local/lib/python2.7/dist-packages/scrapy/cmdline.py", line 150, in _run_command cmd.run(args, opts)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/commands/shell.py", line 49, in run shell = Shell(crawler, update_vars=self.update_vars, code=opts.code)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/shell.py", line 35, in __init__ self.item_class = load_object(crawler.settings['DEFAULT_ITEM_CLASS'])
  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/misc.py", line 47, in load_object raise NameError("Module '%s' doesn't define any object named '%s'" % (module
, name)) NameError: Module 'tutorial.items' doesn't define any object named 'TutorialItem'

I quickly ran the startproject command again and it seems like it creates inside items.py an item with the format <Projectname>Item and sets up that item as the DEFAULT_ITEM_CLASS in settings.py.

But in the tutorial you instruct us to edit items.py to say:

import scrapy

class DmozItem(scrapy.Item):
    title = scrapy.Field()
    link = scrapy.Field()
    desc = scrapy.Field() 

So I guess the fix would be to either leave the items.py file with the autogenerated 
class TutorialItem(scrapy.Item):

Or add a step to the tutorial to edit settings.py to change the DEFAULT_CLASS_ITEM to 

DEFAULT_CLASS_ITEM = 'tutorial.items.DmozItem'

My suggestion would be the second option, as I can see that it is probably a good idea to look into items.py and settings.py when adding classes.

(Just for added info, I had problems trying to google the exact error, but I finally found this:

http://blog.florian-hopf.de/2014/07/scrapy-and-elasticsearch.html (a similar error to mine)

and specifically this comment:

Seb Charrot20. Oktober 2014 um 12:42
Mandeepak,

I was having the same issue. I believe the path to the ElasticSearchPipeline is wrong, it should be:

'scrapyelasticsearch.scrapyelasticsearch.ElasticSearchPipeline'

Because scrapyelasticsearch is the package, scrapyelasticsearch is the module (i.e. file name) and ElasticSearchPipeline is the class name.

Changing this in my settings.py file helped refer to the correct file. However I then experienced a ton of other syntax errors which I'm working on resolving now!

Let me know if that works for you.

Seb

Led me to the solution.

Thanks, 

Lee

**Comment by Curita** [comment]
@nekopa, can you check if DEFAULT_ITEM_CLASS is set in settings.py when you create a project from scratch? It shouldn't in the version you're using since it was removed before 0.14 release (fbafb295e8f32bf71287).

**Comment by nekopa** [comment]
You're right, I did a fresh install of scrapy and now it doesn't create the DEFAULT_ITEM_CLASS.

I think it must have been with the version of scrapy from Debian apt-get, which I think install scrapy version 0.12. Is there anyway of letting people know not to use apt-get for scrapy, or having the version there updated?

Thanks for your help, I look forward to getting on with the tutorial now. :)

**Comment by kmike** [comment]
@nekopa there is a note in docs about Scrapy versions provided by Ubuntu (but not for Debian) - see http://doc.scrapy.org/en/latest/intro/install.html#ubuntu-9-10-or-above.

**Comment by nekopa** [comment]
Thank you for the link. I did a fresh install using an Ubuntu LTS VM using the instructions on this page, but ended up with errors (in the cryptography package) until I installed these packages:

sudo apt-get install build-essential libssl-dev libffi-dev python-dev,

Now everything seems to be running fine.
