### ISSUE TITLE
Where the tracebacks at?

### ISSUE THREAD

**Issue by nramirezuy** [scrapy/scrapy#1229]
run the spider with `scrapy runspider`, it also happens on `parse` and `crawl`.
https://gist.github.com/nramirezuy/65faa56c7eab1e117d77

**Comment by dangra** [comment]
boto trying to read ec2 metadata :(

**Comment by nramirezuy** [comment]
@dangra I added a test without boto installed and have no pipelines enabled.

**Comment by kmike** [comment]
It seems the switch to Python logging made https://github.com/scrapy/scrapy/issues/1054 more visible.

**Comment by kmike** [comment]
Is it a duplicate of https://github.com/scrapy/scrapy/issues/1099?

**Comment by nramirezuy** [comment]
I'm not reporting the boto error, thats already reported on #1099. I'm reporting the missing traceback from the spider.
