### ISSUE TITLE
Scrapy does not use a non-zero exit code when a scrape fails

### ISSUE THREAD

**Issue by iandees** [scrapy/scrapy#1231]
When invoking a Scrapy spider with e.g. `scrapy crawl spidername -o output.csv` and the spider fails for some reason (in our case, timeout to the HTTP server), the exit code is zero, giving subsequent steps in a shell script no way to check if the scrape completed successfully.

See my example here:
https://gist.github.com/iandees/74f51fefeb758b57f5e7

**Comment by kmike** [comment]
For me the existing behaviour makes sense. Errors with remote resources are inevitable - you can't control remote servers. Say you crawled 100 pages and 1 of them failed - should it be reported in exit code? What if you're extracting links from a webpage, and some of them are broken - is it an error with your script? Even if all requests failed it may still be the expected result. 

What logic do you propose for setting a status code?

An allowed % of errors is task-specific; I think hardcoding some value ("if 10% requests failed return a non-zero status code") is a bad idea. To check if a crawl was successful or not (according to what you consider successful) one can check spider stats.

**Comment by iandees** [comment]
The usecase here is that we're scraping webpages and expect the scrape to complete without error before moving on to the next step. I can see your point, and the existing behavior probably makes sense for the general case.

Having said that, can you recommend some way to catch any connection or scraping errors and gracefully exit with a non-zero exit code? I was thinking about listening for the [`spider_error` signal](http://doc.scrapy.org/en/latest/topics/signals.html#spider-error) and calling `sys.exit(1)`, but I imagine that leaves all sorts of stuff in an "unclean" state.

**Comment by nramirezuy** [comment]
@iandees you can create a [custom command](http://doc.scrapy.org/en/master/topics/commands.html#custom-project-commands). There is an extension that already closes the spider by listening that signal ([doc](http://doc.scrapy.org/en/master/topics/extensions.html#scrapy.extensions.closespider.scrapy.extensions.closespider.CloseSpider), [source](https://github.com/scrapy/scrapy/blob/master/scrapy/extensions/closespider.py#L29)).

```diff
diff --git a/scrapy/commands/crawl.py b/scrapy/commands/crawl.py
index b7fea7b..c8089a7 100644
--- a/scrapy/commands/crawl.py
+++ b/scrapy/commands/crawl.py
@@ -55,4 +55,7 @@ class Command(ScrapyCommand):
         spname = args[0]
 
         self.crawler_process.crawl(spname, **opts.spargs)
+        crawler = list(self.crawler_process.crawlers)[0]
         self.crawler_process.start()
+        stats = crawler.stats # here you can get the stats and evaluate your spider
+        self.exitcode = 1
(scrapy)~/Devel/scrapy
```

But I agree it would be nice to propagate a exit code from the spider.

**Comment by Digenis** [comment]
Currently, when the crawling doesn't even start (say, because of an exception in some `__init__` or `__new__` method) the exit code is set to 1, allowing for `scrapy crawl stuff || handle error` expressions in the shell.

**Comment by iandees** [comment]
I ended up using your examples to override the crawl command with this:

```python
from scrapy.commands.crawl import Command as ExistingCrawlCommand
from scrapy.exceptions import UsageError


class Command(ExistingCrawlCommand):
    def run(self, args, opts):
        if len(args) < 1:
            raise UsageError()
        elif len(args) > 1:
            raise UsageError("running 'scrapy crawl' with more than one spider is no longer supported")
        spname = args[0]

        crawler = self.crawler_process.create_crawler()
        spider = crawler.spiders.create(spname, **opts.spargs)
        crawler.crawl(spider)
        self.crawler_process.start()

        exception_count = crawler.stats.get_value('downloader/exception_count')
        if exception_count:
            self.exitcode = 1
```

So far this serves my needs, so I'm going to close this.

**Comment by debosmit** [comment]
In our case, an exception is being thrown by an external API call in the `start_requests` method. The spider is being invoked using a `subprocess.check_call` that uses the `scrapy crawl spname` command. The exception is not bubbling up to the crawler process that invokes it, resulting in a 0 exit code. Do you guys have any thoughts about how this issue? Can you point me to where I can look?

**Comment by fgregg** [comment]
for future folks who come across this issue, @iandees's recipe no longer works as of January 2025. here's something that does.

```python
import argparse

import scrapy.signals as signals
from scrapy.commands.crawl import Command as ExistingCrawlCommand
from scrapy.signalmanager import dispatcher


class Command(ExistingCrawlCommand):

    def failing_exit_code_on_error(self, *args, **kwargs):
        self.exitcode = 1

    def run(self, args: list[str], opts: argparse.Namespace) -> None:

        dispatcher.connect(self.failing_exit_code_on_error, signal=signals.spider_error)
        dispatcher.connect(self.failing_exit_code_on_error, signal=signals.item_error)

        super().run(args, opts)
```

**Comment by dkmvs** [comment]
> for future folks who come across this issue, [@iandees](https://github.com/iandees)'s recipe no longer works as of January 2025. here's something that does.
> 
> ```python import argparse
> 
> import scrapy.signals as signals
> from scrapy.commands.crawl import Command as ExistingCrawlCommand
> from scrapy.signalmanager import dispatcher
> 
> 
> class Command(ExistingCrawlCommand):
> 
>     def failing_exit_code_on_error(self, *args, **kwargs):
>         self.exitcode = 1
> 
>     def run(self, args: list[str], opts: argparse.Namespace) -> None:
> 
>         dispatcher.connect(self.failing_exit_code_on_error, signal=signals.spider_error)
>         dispatcher.connect(self.failing_exit_code_on_error, signal=signals.item_error)
> 
>         super().run(args, opts)
> ```

Just a heads-up – this solution doesn't always seem to work. For example, if your spider throws a `twisted.internet.error.DNSLookupError`, the exit code will be `0`. If you want to reproduce this error, make sure you run your spider in an environment that is not connected to the Internet.

That said, I've combined @fgregg's and @iandees's solutions to create this workaround:


```python
import argparse

import scrapy.signals as signals
from scrapy.commands.crawl import Command as ExistingCrawlCommand
from scrapy.signalmanager import dispatcher


class Command(ExistingCrawlCommand):

    def failing_exit_code_on_error(self, *args, **kwargs):
        crawler = kwargs.get("sender")

        exception_count = crawler.stats.get_value("downloader/exception_count")
        if exception_count:
            self.exitcode = 1

    def run(self, args: list[str], opts: argparse.Namespace) -> None:
        dispatcher.connect(
            self.failing_exit_code_on_error, signal=signals.spider_closed
        )
        super().run(args, opts)
```
