### ISSUE TITLE
Unstructured Information in "Scrapy at Glance" Page

### ISSUE THREAD

**Issue by preetis19** [scrapy/scrapy#1238]
In the Documentation page "Scrapy at Glance" (link : http://doc.scrapy.org/en/0.24/intro/overview.html)
incomplete information is given for running the spider. 
 I being a new user started executing it from there itself and later I came to know that to start a project we should follow this link : http://doc.scrapy.org/en/0.24/intro/tutorial.html

**Comment by kmike** [comment]
Hi @preetis19,

Could you please clarify what didn't work in overview?
Scrapy project is not required to run Scrapy spider.

**Comment by preetis19** [comment]
Hi @kmike ,
I tried to execute the command "scrapy runspider stackoverflow_spider.py -o top-stackoverflow-questions.json" , directly, without creating any project to store the python script for spider.

It gave an error ofcourse, and since being new to Scrapy, it took me alot of time to realise that it wasn't working because we first need to create a project using "startproject" command and define the spider there.

**Comment by dangra** [comment]
@preetis19 creating a project is not needed with `runspider` command, that's the whole point of the that command.

Can you share more details about the error?

**Comment by preetis19** [comment]
@kmike  @dangra  I'm sorry, the link for Scrapy at Glance is http://doc.scrapy.org/en/0.24/intro/overview.html , I gave the wrong link with wrong command.

the command is "scrapy crawl mininova -o scraped_data.json" .

Now the crawl commands needs the project to be created which is not mentioned on the page.

**Comment by dangra** [comment]
0.24 is outdated and shouldn't be there, not sure how it built.

From where did you get that link to 0.24?

![screenshot from 2015-05-15 13-48-49](https://cloud.githubusercontent.com/assets/37369/7657551/2969ed4e-fb09-11e4-9ca6-b7ff6f7b80e8.png)

**Comment by dangra** [comment]
0.24 is not listed in the bottom pane of RTD (it shows in red color because it is outdated)

![screenshot from 2015-05-15 13-50-26](https://cloud.githubusercontent.com/assets/37369/7657588/7c99eeb0-fb09-11e4-8c0d-ad4b8d1700b3.png)

**Comment by preetis19** [comment]
@dangra ok,
but even the latest document "http://doc.scrapy.org/en/latest/intro/overview.html" , has the same content as that of 0.24.

**Comment by kmike** [comment]
@preetis19 you're right, this overview should have used `scrapy runspider`. It also had other issues; @eliasdorneles has rewritten the overview, so this is not a problem in scrapy master. The release is not too far away, but I'm fine with merging a PR which fixes an error 0.24 overview.

In readthedocs "latest" (somewhat confusingly) means "latest released version", so it doesn't correspond to the latest code.

**Comment by eliasdorneles** [comment]
So, can we close this now? =)
