### ISSUE TITLE
Telnet problem 

### ISSUE THREAD

**Issue by 1a1a11a** [scrapy/scrapy#1245]
I am trying to use telnet for scrapy, and I type in:  
    telnet localhost 6023 

and I have the following results coming from terminal: 

Trying ::1...
telnet: connect to address ::1: Connection refused
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.

Then it stucks here, can anyone help me? 

OS: OSX Yosemite 
Scrapy: 0.24 
python: 2.7.9

**Comment by dangra** [comment]
Github issues are for project bugs and new feature development, for advise you will have better luck by  asking in forums: https://groups.google.com/forum/#!forum/scrapy-users
