### ISSUE TITLE
How to get img src ?

### ISSUE THREAD

**Issue by oxzilla** [scrapy/scrapy#1246]
Hello,

I have some problem about get img src from this page .

http://shoponline.tescolotus.com/en-GB/Product/BrowseProducts?taxonomyId=Cat00001808

Please kindly advice.

Tim

**Comment by nramirezuy** [comment]
This place is just for bug reports or feature requests.
For help you can make a thread on [scrapy-users](https://groups.google.com/forum/#!forum/scrapy-users).
