### ISSUE TITLE
Add denied_domains for original Spider

### ISSUE THREAD

**Issue by BrieflyX** [scrapy/scrapy#1247]
This is allow & deny domains for LinkExtractor, but if we just use Spider class. It just provides an variable 'allowed_domains', no 'denied_domains' to forbid crawling some sites.....

**Comment by nramirezuy** [comment]
I don't quite get you. You can add any attribute you like to your spider.
If you need help please refer to [scrapy-users](https://groups.google.com/forum/#!forum/scrapy-users)
