### ISSUE TITLE
High CPU

### ISSUE THREAD

**Issue by ErikvdVen** [scrapy/scrapy#1251]
Scrapy uses a lot of CPU on our server, 40% is the minimum (when running 1 spider) and most of the time it goes up to 99% (running multiple spiders at the same time). We're using a DigitalOcean droplet with 1 CPU. 

Is this normal? I tried already several things:
- add sleep(0.1) to Pipelines
- disabling Pipelines
- Using Scrapyd with job persistance.
- set the amount of jobs per cpu with settings like below.
scrapy.cfg:

````
[scrapyd]    
max_proc = 0    
max_proc_per_cpu = 2
Which didn't help either. These are my stats when running a spider:
````

Nothing helps. These are my stats when I run one scraper:

````
  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
 3221 scrapy    20   0  836724  75568   8432 R 40.5  7.4   1:04.31 python
 3231 scrapy    20   0  836724  75568   8432 S  1.0  7.4   0:01.40 python
 3234 scrapy    20   0  836724  75568   8432 S  1.0  7.4   0:01.42 python
 3235 scrapy    20   0  836724  75568   8432 S  1.0  7.4   0:01.44 python
 3228 scrapy    20   0  836724  75568   8432 S  0.7  7.4   0:01.43 python
````

I found out that if I set the variable ```CONCURRENT_REQUESTS = 1``` the CPU stays below the 40% when running 1 spider, but it takes 3 times as long to finish. 

I also tried to turn off every extension, middleware and pipeline, but that didn't reduce the CPU load either. Any ideas?

**Comment by kmike** [comment]
Have you profiled your spiders?

**Comment by kmike** [comment]
Often the CPU bottleneck is HTML parsing using lxml library.

**Comment by ErikvdVen** [comment]
Haven't profiled it yet. Just tried it, but ```python -m cProfile westwing.py``` returns like a thousand rows, and I cannot see all of them in my terminal. Any ideas? Does scrapy has a profile function itself?

And I will have a look at the lxml

**Comment by kmike** [comment]
check http://jiffyclub.github.io/snakeviz/ - highly recommended :)

**Comment by ErikvdVen** [comment]
Alright, thanks. i will try that!

**Comment by ErikvdVen** [comment]
Ok, I tried snakeviz, didn't understand very much of it haha. Tried the documentation and figured out Pipelines popped up a couple of times. So I tried to enable and disable some Pipelines and check the CPU usage while running the scraper. I noticed that when enabling the image pipeline (scrapy.contrib.pipeline.images.ImagesPipeline) it uses double as much CPU for a couple of seconds. From max 48% with image pipeline disabled, to 85% with image pipeline enabled. But still it uses more than 40% cpu for one scraper. When I disable all `l.add_value` and `l.add_css` rows, so no items are processed the CPU load is max 20%

**Comment by nramirezuy** [comment]
@ErikvdVen can you tell us how many requests per second are you doing on server and your mac?

**Comment by kirankoduru** [comment]
@ErikvdVen have you used the [trackref](http://scrapy.readthedocs.org/en/latest/topics/leaks.html#debugging-memory-leaks-with-trackref) feature from scrapy?

**Comment by ErikvdVen** [comment]
@nramirezuy Do you mean http requests? Server: 154 packets per second (tops). On my mac more than 400 packages per second if I'm right.

**Comment by ErikvdVen** [comment]
@kirankoduru Yes I did, but I do see objects decreasing, so it looks like it deletes the old objects as it supposed to. I don't see any disturbing high numbers.

**Comment by nramirezuy** [comment]
packets == scrapy requests? I was asking about this log line `Crawled 100 pages (at 20 pages/min), scraped 97 items (at 17 items/min)`.
Well there you go smaller CPU is processing 154p while on your bigger CPU you are processing 400p per second. If you don't limit it scrapy will use all the CPU it can, to limit this you can [`Autothrottle`](http://doc.scrapy.org/en/master/topics/autothrottle.html) for example.

**Comment by ErikvdVen** [comment]
Thanks a lot!!! Guess it's working:

I added these settings:
```
AUTOTHROTTLE_ENABLED = True
AUTOTHROTTLE_START_DELAY = 0.1
AUTOTHROTTLE_MAX_DELAY = 0.5
```

Result:
![cpu](https://cloud.githubusercontent.com/assets/5047027/7864251/47b1215c-0561-11e5-8862-81f5de05d654.png)

**Comment by nramirezuy** [comment]
@ErikvdVen yw, if you have anymore doubts you can reach us on [`scrapy-users`](https://groups.google.com/forum/#!forum/scrapy-users) or `#scrapy` IRC.
