### ISSUE TITLE
newlines in attributes

### ISSUE THREAD

**Issue by VascoVisser** [scrapy/scrapy#1252]
I noticed that when a website spits out HTML with newlines in tag attributes scrapy's xpath selector doesn't match attributes anymore. I.e., something like
``` 
<div class="the_class

"> .. </div>
```
won't match xpath query `"//div[@class='the_class']" `.

What I do now to work around this is:
`selector = scrapy.Selector(text=response.body.replace('\n', ''))`
This seems to work just fine, but maybe there is a better way to go about handling this?

**Comment by nramirezuy** [comment]
@VascoVisser can you tell me which python and lxml version are you using?

**Comment by VascoVisser** [comment]
lxml==3.4.4
Python 2.7.9

I am using `contains(@class, 'the_class')` now to select these tags.

**Comment by dangra** [comment]
This is not a bug in selectors but how xpath matching works and in the end an issue for lxml library.
Using `contains()` is the expected solution.
