### ISSUE TITLE
Backward incompatibility for relocated paths in settings

### ISSUE THREAD

**Issue by Curita** [scrapy/scrapy#1265]
Reported by @dangra

This issue manifests when mixing old paths and new ones for extensions and middlewares (this can happen for example while using a newer version of Scrapy in a project that hasn't updated to the new paths yet). Since paths aren't normalized, the same component can be loaded twice.

Take these settings for example:

```python
# scrapy/settings/default_settings.py
EXTENSIONS_BASE = {
    'scrapy.extensions.debug.StackTraceDump': 100,  # new path
} 
```
```python
# myproject/settings.py
EXTENSIONS = {
    'scrapy.contrib.debug.StackTraceDump': 200,  # old path
}
```

While merging both dictionaries to build the list of components, the same StackTraceDump class is going to be loaded twice since it appears in two different keys.

**Comment by nramirezuy** [comment]
```python
>>> from scrapy.extensions.debug import StackTraceDump
>>> from scrapy.contrib.debug import StackTraceDump as _StackTraceDump
>>> StackTraceDump is _StackTraceDump
True
```

**Comment by Curita** [comment]
@nramirezuy Yes, it's the same class, but with those settings is going to be loaded twice because of how MiddlewareManager and build_component_list work, none of them check for duplicates.
