### ISSUE TITLE
What, where is CrawlSpider?

### ISSUE THREAD

**Issue by rrshaban** [scrapy/scrapy#1281]
The [docs](https://scrapy.readthedocs.org/en/latest/topics/spiders.html#scrapy.contrib.spiders.CrawlSpider) define `class scrapy.contrib.spiders.CrawlSpider`

But in Scrapy, updated to the latest version, I'm getting nothing. What's the deal?
```
>>> import scrapy
>>> scrapy.contrib.spiders
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'contrib'
```

**Comment by kmike** [comment]
Hey @rrshaban,

Python doesn't auto-import submodules/subpackages - use 
```from scrapy.contrib.spiders import CrawlSpider```

**Comment by rrshaban** [comment]
oh wow haha @kmike thanks, what an oversight of mine
