### ISSUE TITLE
Files Pipeline fails on URLs with "?"/get attributes

### ISSUE THREAD

**Issue by mrwonko** [scrapy/scrapy#1287]
The Files Pipeline does not strip get parameters from the extension and then fails to write the file, at least on Windows/NTFS where "?" is disallowed in filenames.

e.g. `files_urls = [ "http://foo.bar/baz.txt?fizz" ]` tries to create `<hash>.txt?fizz`, raising an IOError.

**Comment by otobrglez** [comment]
@mrwonko && @jschnurr what is the state of this bug? I see that fix was not merged into master. I ran into this issue Today,... Cheers!

**Comment by kmike** [comment]
Hey @otobrglez,

There is a PR https://github.com/scrapy/scrapy/pull/1548 which has merge+1 vote; we have a policy that two Scrapy commiters must approve a pull request before merging it to master, so currently it waits for another Scrapy commiter to approve and merge it.

**Comment by otobrglez** [comment]
Hey @kmike! 👋 Is there a way I can help to speed this up?

**Comment by kmike** [comment]
@otobrglez it will help if you check that PR works for you and add a comment with the results to #1548.
