### ISSUE TITLE
Use scrapy.mail.MailSender is not able to quit after send mail in a stand alone script.

### ISSUE THREAD

**Issue by lyjbupt** [scrapy/scrapy#1296]
Example code as below, please help me out :)

from twisted.internet import reactor
from scrapy.mail import MailSender

def f():
    pass

mailer = MailSender(smtphost='xxx.yyy.com', mailfrom=noreply@yyy.com')
mailer.send(to=["foobar@yyy.com"], subject="Some subject", body="Some body")

reactor.callLater(1,f)
reactor.run()

**Comment by nramirezuy** [comment]
For support please use [scrapy-users](https://groups.google.com/forum/#!forum/scrapy-users). Github issues are for bug reports or feature requests.
