### ISSUE TITLE
Settings documentation useless

### ISSUE THREAD

**Issue by surfer190** [scrapy/scrapy#1300]
Please look at this documentation from the layman's point of view.

 `docs/topics/settings.rst`

Does it answer the following:
1. How do I set settings values?
2. How do I retrieve settings values?

The documentation assumes that the user is a regular python user.

**Comment by eliasdorneles** [comment]
Hm, the section "Populating the settings" does try to show how to set settings values. Have you had a problem trying to follow that?

I agree that the section on "How to access settings" deserves some improvements (would be nice an example for a spider), accessing settings can be tricky depending on what exactly you're after. Any particular issue/suggestion?

**Comment by surfer190** [comment]
Yes I would add:

'From scrapy.conf import settings'

I scoured the Internet and found you needed that import statement in the spider

Assess is then:

'Settings['my-var']'

**Comment by kmike** [comment]
> I agree that the section on "How to access settings" deserves some improvements (would be nice an example for a spider), accessing settings can be tricky depending on what exactly you're after. Any particular issue/suggestion?

+1 to add a Spider example and mention item pipelines. The current example is also not realistic - from_crawler method should create extension instance, not just print option value, like e.g. [here](http://doc.scrapy.org/en/master/topics/item-pipeline.html#write-items-to-mongodb).

> from scrapy.conf import settings

This is not a correct way to access settings - you'll get only default values.

**Comment by surfer190** [comment]
@eliasdorneles the "populating the settings" gives 4 ways to set settings, yet an example for the most generic way imo isn't shown in an example.

Adding key value pairs to `settings.py`

A method for settings for different environments eg. staging and production is not given.

@kmike the `from scrapy.conf import settings` is the only example that worked that I could find. What is the best practise for accessing settings in a spider?

Do we have to do this? Why isn't it just automatically accessible when you import `scrapy`?:

```
 @classmethod
    def from_crawler(cls, crawler):
        settings = crawler.settings
```

**Comment by eliasdorneles** [comment]
@surfer190 To access the settings in a spider you can just use `self.settings`, you don't need to import anything.

Scrapy doesn't have a special feature for accessing settings for different environments.
However, you can do your own thing: you can change `settings.py` into a directory module, with the following contents:

```
settings/
    __init__.py   <- here you decide to load settings from staging.py or production.py
    base.py   <- here you put the settings that are common to all environments
    production.py  <- production settings go here
    staging.py  <- staging settings go here
```

In `production.py` and `staging.py` you'd put this at the top:

```
from .base import *
# specific environment settings go here
```

To implement the decision to load local or production, you can use an environment variable:

```
import os
if os.getenv('STAGING')
    from .staging import *
else:
    from .production import *
```

**Comment by surfer190** [comment]
@eliasdorneles It seems that it is not as easy as you say.

I'm getting `AssertionError: Spider not bounded to any crawler`

So you have to assign a `crawler` to the `spider`

**Comment by eliasdorneles** [comment]
@surfer190 hmm, which Scrapy version are you using?
I checked this works in the latest Scrapy stable version (0.24.6).

**Comment by curita** [comment]
I think @eliasdorneles handled in #1302 all mentioned issues with that doc section - @surfer190, could you review the new documentation in http://scrapy.readthedocs.org/en/master/topics/settings.html and tell us if you find anything missing?
