### ISSUE TITLE
provide an option to disable scrapy.utils.log.TopLevelFormatter

### ISSUE THREAD

**Issue by kmike** [scrapy/scrapy#1309]
Long names in logs (e.g. `[scrapy.core.scraper]` instead of generic `[scrapy]`) are useful because
- they show where the log message came from - this makes debugging easier;
- it has an educational value - users become aware of various Scrapy components;
- to filter out a specific kind of messages (or make them more verbose) user can set a custom log level just for one logger, but to do that user needs to know logger full name.

My preference is to even use full names by default, but an option to enable them is also fine.
Thoughts?

**Comment by curita** [comment]
+1 to use full names by default, not sure if there is any value in keeping just the top level logger besides replicating the old behaviour. I'm ok with deleting TopLevelFormatter entirely.

**Comment by nramirezuy** [comment]
I like `TopLevelFormatter`, long names can be too long. Besides after some time you know from where the log lines come from.
