### ISSUE TITLE
ImportError:cryptography.hazmat.bindings.openssl.binding

### ISSUE THREAD

**Issue by adammfrank** [scrapy/scrapy#1314]
OS: Ubuntu 14.04.2
Python: 2.7.6, 2.7.8, 2.7.9, 2.7.10 (same result on each)
After updating Scrapy from 0.24 to 1.0 today, I can no longer get anything to run.  Everything I run, even for the tutorial, throws the error:
ImportError:cryptography.hazmat.bindings.openssl.binding

**Comment by kmike** [comment]
Are you using deb packages?

It is not directly related to Scrapy 1.0 vs Scrapy 0.24 - likely you also updated PyOpenSSL and/or cryptography packages along with Scrapy, and they stopped working for some reason.

**Comment by adammfrank** [comment]
I updated scrapy via pip. Would this have updated the other packages as well?

**Comment by kmike** [comment]
Yes, `pip install -U foo` upgrades `foo` dependencies by default. PyOpenSSL 14.x+ uses cffi-based cryptography package, maybe this is a cause of your issue - cffi needs libffi (or libffi-dev) system package, this is a new non-Python dependency. 

Could you please post the full traceback? Full tracebacks are verbose, but it is usually hard to say what is the problem without looking at them.

**Comment by adammfrank** [comment]
ogs-stl-07@ogs-stl-07-laptop:~/Documents/tutorial2$ scrapy crawl dmoz
2015-06-24 09:29:48 [scrapy] INFO: Scrapy 1.0.0 started (bot: tutorial2)
2015-06-24 09:29:48 [scrapy] INFO: Optional features available: ssl, http11
2015-06-24 09:29:48 [scrapy] INFO: Overridden settings: {'NEWSPIDER_MODULE': 'tutorial2.spiders', 'SPIDER_MODULES': ['tutorial2.spiders'], 'BOT_NAME': 'tutorial2'}
Traceback (most recent call last):
  File "/usr/local/bin/scrapy", line 11, in <module>
    sys.exit(execute())
  File "/usr/local/lib/python2.7/dist-packages/scrapy/cmdline.py", line 143, in execute
    _run_print_help(parser, _run_command, cmd, args, opts)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/cmdline.py", line 89, in _run_print_help
    func(*a, **kw)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/cmdline.py", line 150, in _run_command
    cmd.run(args, opts)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/commands/crawl.py", line 57, in run
    self.crawler_process.crawl(spname, **opts.spargs)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/crawler.py", line 150, in crawl
    crawler = self._create_crawler(crawler_or_spidercls)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/crawler.py", line 166, in _create_crawler
    return Crawler(spidercls, self.settings)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/crawler.py", line 46, in __init__
    self.extensions = ExtensionManager.from_crawler(self)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 56, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 32, in from_settings
    mwcls = load_object(clspath)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/misc.py", line 44, in load_object
    mod = import_module(module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/extensions/memusage.py", line 16, in <module>
    from scrapy.mail import MailSender
  File "/usr/local/lib/python2.7/dist-packages/scrapy/mail.py", line 22, in <module>
    from twisted.internet import defer, reactor, ssl
  File "/usr/lib/python2.7/dist-packages/twisted/internet/ssl.py", line 25, in <module>
    from OpenSSL import SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/rand.py", line 11, in <module>
    from OpenSSL._util import (
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
ImportError: No module named cryptography.hazmat.bindings.openssl.binding


Fortunately, I have access to a different computer and it works fine on that one.  The computer I was using has all kinds of other problems, so I'm glad for the excuse to switch.  This issue doesn't matter to me any more, but I can keep working with you if you are interested in trying to fix it.

**Comment by smwise** [comment]
FWIW, I ran into the same problem and it was just the missing Python cryptography package. The pyOpenSSL install failed the first time and running pip install -U foo didn't retry the requirements. Ran into it with the scrapy install too. I use Linux Mint 17.2 which is based on Ubuntu 14.04. Sounds like a pip thing but might be good to know about here too.

**Comment by psychok7** [comment]
Upgrading pip and reinstalling everything solved my issue as well

**Comment by jyap808** [comment]
Yep, can confirm this issue. Upgrading pip worked.

Fixed with:
```
$ sudo  pip install --upgrade pip
$ sudo  pip install --upgrade Scrapy
```

**Comment by argo76** [comment]
Had this error on raspberry pi 1b. I upgraded pip and this output/errors. I don't even know where to start solving this one.

` sudo pip install imapclient
Requirement already satisfied (use --upgrade to upgrade): imapclient in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): mock==1.3.0 in /usr/local/lib/python2.7/dist-packages (from imapclient)
Requirement already satisfied (use --upgrade to upgrade): backports.ssl>=0.0.9 in /usr/local/lib/python2.7/dist-packages (from imapclient)
Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python2.7/dist-packages (from imapclient)
Requirement already satisfied (use --upgrade to upgrade): pyopenssl>=0.15.1 in /usr/local/lib/python2.7/dist-packages (from imapclient)
Collecting pbr>=0.11 (from mock==1.3.0->imapclient)
  Downloading pbr-1.10.0-py2.py3-none-any.whl (96kB)
    100% |████████████████████████████████| 102kB 404kB/s 
Collecting funcsigs; python_version < "3.3" (from mock==1.3.0->imapclient)
  Downloading funcsigs-1.0.2-py2.py3-none-any.whl
Collecting cryptography>=1.3.4 (from pyopenssl>=0.15.1->imapclient)
  Downloading cryptography-1.5.tar.gz (400kB)
    100% |████████████████████████████████| 409kB 130kB/s 
Collecting idna>=2.0 (from cryptography>=1.3.4->pyopenssl>=0.15.1->imapclient)
  Downloading idna-2.1-py2.py3-none-any.whl (54kB)
    100% |████████████████████████████████| 61kB 417kB/s 
Collecting pyasn1>=0.1.8 (from cryptography>=1.3.4->pyopenssl>=0.15.1->imapclient)
  Downloading pyasn1-0.1.9-py2.py3-none-any.whl
Collecting setuptools>=11.3 (from cryptography>=1.3.4->pyopenssl>=0.15.1->imapclient)
  Downloading setuptools-27.1.2-py2.py3-none-any.whl (464kB)
    100% |████████████████████████████████| 471kB 118kB/s 
Collecting enum34 (from cryptography>=1.3.4->pyopenssl>=0.15.1->imapclient)
  Downloading enum34-1.1.6-py2-none-any.whl
Collecting ipaddress (from cryptography>=1.3.4->pyopenssl>=0.15.1->imapclient)
  Downloading ipaddress-1.0.17-py2-none-any.whl
Collecting cffi>=1.4.1 (from cryptography>=1.3.4->pyopenssl>=0.15.1->imapclient)
  Downloading cffi-1.8.2.tar.gz (403kB)
    100% |████████████████████████████████| 409kB 131kB/s 
Collecting pycparser (from cffi>=1.4.1->cryptography>=1.3.4->pyopenssl>=0.15.1->imapclient)
  Downloading pycparser-2.14.tar.gz (223kB)
    100% |████████████████████████████████| 225kB 223kB/s 
Building wheels for collected packages: cryptography, cffi, pycparser
  Running setup.py bdist_wheel for cryptography ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-mrHEt3/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpPk9n_Hpip-wheel- --python-tag cp27:
  c/_cffi_backend.c:2:20: fatal error: Python.h: No such file or directory
   #include <Python.h>
                      ^
  compilation terminated.
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-mrHEt3/cryptography/setup.py", line 334, in <module>
      **keywords_with_side_effects(sys.argv)
    File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
      _setup_distribution = dist = klass(attrs)
    File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 262, in __init__
      self.fetch_build_eggs(attrs['setup_requires'])
    File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 287, in fetch_build_eggs
      replace_conflicting=True,
    File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 631, in resolve
      dist = best[req.key] = env.best_match(req, ws, installer)
    File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 874, in best_match
      return self.obtain(req, installer)
    File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 886, in obtain
      return installer(requirement)
    File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 338, in fetch_build_egg
      return cmd.easy_install(req)
    File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 636, in easy_install
      return self.install_item(spec, dist.location, tmpdir, deps)
    File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 666, in install_item
      dists = self.install_eggs(spec, download, tmpdir)
    File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 856, in install_eggs
      return self.build_and_install(setup_script, setup_base)
    File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1078, in build_and_install
      self.run_setup(setup_script, setup_base, args)
    File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1066, in run_setup
      raise DistutilsError("Setup script exited with %s" % (v.args[0],))
  distutils.errors.DistutilsError: Setup script exited with error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for cryptography
  Running setup.py clean for cryptography
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-mrHEt3/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" clean --all:
  c/_cffi_backend.c:2:20: fatal error: Python.h: No such file or directory
   #include <Python.h>
                      ^
  compilation terminated.
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-mrHEt3/cryptography/setup.py", line 334, in <module>
      **keywords_with_side_effects(sys.argv)
    File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
      _setup_distribution = dist = klass(attrs)
    File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 262, in __init__
      self.fetch_build_eggs(attrs['setup_requires'])
    File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 287, in fetch_build_eggs
      replace_conflicting=True,
    File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 631, in resolve
      dist = best[req.key] = env.best_match(req, ws, installer)
    File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 874, in best_match
      return self.obtain(req, installer)
    File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 886, in obtain
      return installer(requirement)
    File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 338, in fetch_build_egg
      return cmd.easy_install(req)
    File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 636, in easy_install
      return self.install_item(spec, dist.location, tmpdir, deps)
    File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 666, in install_item
      dists = self.install_eggs(spec, download, tmpdir)
    File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 856, in install_eggs
      return self.build_and_install(setup_script, setup_base)
    File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1078, in build_and_install
      self.run_setup(setup_script, setup_base, args)
    File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1066, in run_setup
      raise DistutilsError("Setup script exited with %s" % (v.args[0],))
  distutils.errors.DistutilsError: Setup script exited with error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed cleaning build dir for cryptography
  Running setup.py bdist_wheel for cffi ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-mrHEt3/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmp3TzpV1pip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-armv6l-2.7
  creating build/lib.linux-armv6l-2.7/cffi
  copying cffi/__init__.py -> build/lib.linux-armv6l-2.7/cffi
  copying cffi/vengine_gen.py -> build/lib.linux-armv6l-2.7/cffi
  copying cffi/vengine_cpy.py -> build/lib.linux-armv6l-2.7/cffi
  copying cffi/verifier.py -> build/lib.linux-armv6l-2.7/cffi
  copying cffi/setuptools_ext.py -> build/lib.linux-armv6l-2.7/cffi
  copying cffi/model.py -> build/lib.linux-armv6l-2.7/cffi
  copying cffi/recompiler.py -> build/lib.linux-armv6l-2.7/cffi
  copying cffi/cparser.py -> build/lib.linux-armv6l-2.7/cffi
  copying cffi/commontypes.py -> build/lib.linux-armv6l-2.7/cffi
  copying cffi/lock.py -> build/lib.linux-armv6l-2.7/cffi
  copying cffi/api.py -> build/lib.linux-armv6l-2.7/cffi
  copying cffi/ffiplatform.py -> build/lib.linux-armv6l-2.7/cffi
  copying cffi/backend_ctypes.py -> build/lib.linux-armv6l-2.7/cffi
  copying cffi/cffi_opcode.py -> build/lib.linux-armv6l-2.7/cffi
  copying cffi/_cffi_include.h -> build/lib.linux-armv6l-2.7/cffi
  copying cffi/parse_c_type.h -> build/lib.linux-armv6l-2.7/cffi
  copying cffi/_embedding.h -> build/lib.linux-armv6l-2.7/cffi
  running build_ext
  building '_cffi_backend' extension
  creating build/temp.linux-armv6l-2.7
  creating build/temp.linux-armv6l-2.7/c
  arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DUSE__THREAD -I/usr/include/python2.7 -c c/_cffi_backend.c -o build/temp.linux-armv6l-2.7/c/_cffi_backend.o
  c/_cffi_backend.c:2:20: fatal error: Python.h: No such file or directory
   #include <Python.h>
                      ^
  compilation terminated.
  error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for cffi
  Running setup.py clean for cffi
  Running setup.py bdist_wheel for pycparser ... done
  Stored in directory: /root/.cache/pip/wheels/9b/f4/2e/d03e949a551719a1ffcb659f2c63d8444f4df12e994ce52112
Successfully built pycparser
Failed to build cryptography cffi
Installing collected packages: pbr, funcsigs, idna, pyasn1, setuptools, enum34, ipaddress, pycparser, cffi, cryptography
  Found existing installation: pyasn1 0.1.7
    Uninstalling pyasn1-0.1.7:
      Successfully uninstalled pyasn1-0.1.7
  Found existing installation: setuptools 5.5.1
    Uninstalling setuptools-5.5.1:
      Successfully uninstalled setuptools-5.5.1
  Running setup.py install for cffi ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-mrHEt3/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-8TSC02-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-armv6l-2.7
    creating build/lib.linux-armv6l-2.7/cffi
    copying cffi/__init__.py -> build/lib.linux-armv6l-2.7/cffi
    copying cffi/vengine_gen.py -> build/lib.linux-armv6l-2.7/cffi
    copying cffi/vengine_cpy.py -> build/lib.linux-armv6l-2.7/cffi
    copying cffi/verifier.py -> build/lib.linux-armv6l-2.7/cffi
    copying cffi/setuptools_ext.py -> build/lib.linux-armv6l-2.7/cffi
    copying cffi/model.py -> build/lib.linux-armv6l-2.7/cffi
    copying cffi/recompiler.py -> build/lib.linux-armv6l-2.7/cffi
    copying cffi/cparser.py -> build/lib.linux-armv6l-2.7/cffi
    copying cffi/commontypes.py -> build/lib.linux-armv6l-2.7/cffi
    copying cffi/lock.py -> build/lib.linux-armv6l-2.7/cffi
    copying cffi/api.py -> build/lib.linux-armv6l-2.7/cffi
    copying cffi/ffiplatform.py -> build/lib.linux-armv6l-2.7/cffi
    copying cffi/backend_ctypes.py -> build/lib.linux-armv6l-2.7/cffi
    copying cffi/cffi_opcode.py -> build/lib.linux-armv6l-2.7/cffi
    copying cffi/_cffi_include.h -> build/lib.linux-armv6l-2.7/cffi
    copying cffi/parse_c_type.h -> build/lib.linux-armv6l-2.7/cffi
    copying cffi/_embedding.h -> build/lib.linux-armv6l-2.7/cffi
    running build_ext
    building '_cffi_backend' extension
    creating build/temp.linux-armv6l-2.7
    creating build/temp.linux-armv6l-2.7/c
    arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DUSE__THREAD -I/usr/include/python2.7 -c c/_cffi_backend.c -o build/temp.linux-armv6l-2.7/c/_cffi_backend.o
    c/_cffi_backend.c:2:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-mrHEt3/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-8TSC02-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-mrHEt3/cffi/
`

**Comment by faerietree** [comment]
Try installing python-dev or -devel (which contains the include for python2).

**Comment by gmegidish** [comment]
I ran into the same problem. Here's what solved it for me:

/opt/eff.org/certbot/venv/local/bin/pip install cryptography interface
