### ISSUE TITLE
tox fails with "Could not open requirements file"

### ISSUE THREAD

**Issue by olafdietsche** [scrapy/scrapy#1337]
Following instructions at [Running tests](https://pip.pypa.io/en/stable/development.html#running-tests), I just ran 

    tox

in the top level scrapy directory. Unfortunately, it failed with 

>Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
>ERROR: could not install deps [-rrequirements.txt, boto, Pillow, leveldb, service_identity, -rtests/requirements.txt]

even though both `requirements.txt` and `tests/requirements.txt` are accessible.

I worked around this by manually installing the dependencies with `pip install ...` and removing the `deps` entry from the tox.ini file. After that, tox ran successfully with only 3 tests failing 

>============== 3 failed, 1134 passed, 3 skipped in 204.43 seconds ==============

This is the current master branch at commit 2a7dc31f4cab7b13aacb632bdc78c50af754e76f.

**Comment by curita** [comment]
Thanks for the report!

I was able to reproduce this error in windows with a `tox` version older than `1.7`. Can I ask you to see if upgrading your tox version fixes the issue (`pip install -U tox` if installed with pip)?

**Comment by olafdietsche** [comment]
This fixed it, thank you very much.

On Ubuntu 14.04, I was using the standard tox package, version 1.6.0.
`pip install --upgrade tox` installed a more recent version. `tox --version` gives now 

>2.1.1 imported from /usr/local/lib/python2.7/dist-packages/tox/__init__.pyc

Now tox runs successfully with none failing 

>================== 1127 passed, 13 skipped in 298.90 seconds ===================

So, this seems to be a tox issue and not scrapy's fault.
