### ISSUE TITLE
Impossible to create exe file when using py2exe

### ISSUE THREAD

**Issue by LEDfan** [scrapy/scrapy#1338]
Hi, thanks for this project! Works good, except one thing :smiley: 

I have a scrapy project which I want to run as `exe` and create an installer of it by using the `inno setup` tool. I'm using this  `setup.py`:

````
import sys
from scrapy import *
from zope.interface import *
from distutils.core import setup
import py2exe

base = None
if sys.platform == "win32":
    base = "Win32GUI"

setup(
    name = "Random123",
    version = "0.1",
    description = "My GUI application!",
    options = {
        "py2exe": {
            "packages": ["pkg_resources", "os", "twisted", "scrapy", "test", 'zope', 'zope.interface', 'pkgutil', 'lxml',
                         'lxml.etree', 'lxml._elementpath', 'multipart', 'email.mime.multipart', 'email.mime.text',
                         ],
            "includes": ["pkg_resources", "os", "twisted", "scrapy", "test", 'zope', 'zope.interface', 'pkgutil', 'lxml',
                         'lxml._elementpath', 'multipart', 'email.mime.multipart', 'email.mime.text',
                         ],
            "skip_archive": True
        },
    },
    console=['run.py'],
)
````

If you would try to run this via `python setup.py py2exe` it will work. However when you try to run the `dist/run.exe` file it will fail. Python will tell that some module is trying to compile some C++ files by using `cffi`. This modules is https://github.com/pyca/cryptography . This is used by scrapy (twisted) for creating `SSL` connections, right?

I was able to solve this by removing SSL support from scrapy/twisted, but this is of course not a permanent solution. For now I don't need to scrape HTTPS site, but maybe in the future.

The relevant issue is https://github.com/pyca/cryptography/issues/2039

Do you maybe have a solution for this?

**Comment by Granitas** [comment]
By the looks of it, it's an issue with the cryptography package. Related Issue: https://github.com/pyca/cryptography/issues/2039 .

**Comment by LEDfan** [comment]
@Granitas that's what I was trying to tell :smiley:. 

However it looks like the issue is solved in cryptography (master branch). I tried to crawl `https://github.com` (as test) and it works perfectly.
