### ISSUE TITLE
arg 'settings' is not used in func 'update_settings'

### ISSUE THREAD

**Issue by xinghun854** [scrapy/scrapy#1339]
version: 1.1.0dev1

scrapy/spiders/__init__.py 
79	    def update_settings(cls, settings):
80	        settings.setdict(cls.custom_settings or {}, priority='spider')

arg 'settings' is not used in func 'update_settings', is that right or wrong?

**Comment by jdemaeyer** [comment]
It's the very first object used ;)
```python
    def update_settings(cls, settings):
        settings.setdict(cls.custom_settings or {}, priority='spider')
        ^^^^^^^^
```

**Comment by xinghun854** [comment]
;)
I think I must be drunk a moment ago.
