### ISSUE TITLE
custom_settings isn't reflected in the "Overridden settings:" log message

### ISSUE THREAD

**Issue by nautilus28** [scrapy/scrapy#1343]
Hi,

I would like to notice that custom_settings per spider does not work properly. Global settings updated nothing when I added custom_settings in spiders, and unittests for that are missing too.

Regards,
Canh

**Comment by kmike** [comment]
Do you have an exampe? Which settings don't work?

**Comment by barraponto** [comment]
This one works just fine:
https://github.com/barraponto/fosshackers/blob/master/fosshackers/spiders/djangopatcherscrawl.py

**Comment by nautilus28** [comment]
in my project settings.py I placed DOWNLOAD_TIMEOUT = 60 and in ./spiders/simple_spider.py


class SimpleSpider(scrapy.Spider):
 
    name = 'simple'
    custom_settings = {
        'DOWNLOAD_TIMEOUT': 30,
        'CONCURRENT_REQUESTS_PER_DOMAIN': 4
    }

    def start_requests(self):
        yield Request('http://www.google.com/', callback='parse')


and Scrapy logs say INFO: Overridden settings: {'DOWNLOAD_TIMEOUT': 60} when I ran the simple spider. It looks like that DOWNLOAD_TIMEOUT was not updated.

**Comment by curita** [comment]
Hi @nautilus28 ! That log message gets printed before settings are updated with `custom_settings` :/ You can verify it by adding this `print` to the parse method in your spider:

```python
def parse(self, response):
    ...
    print 'DOWNLOAD_TIMEOUT: {}'.format(self.settings.getint('DOWNLOAD_TIMEOUT'))
```

**Comment by curita** [comment]
If that's not it, make sure you're using Scrapy 1.0.

**Comment by barraponto** [comment]
Shouldn't scrapy print that message later then?

**Comment by curita** [comment]
Yes, I agree. I'll update the issue title to reflect the actual problem.

**Comment by nramirezuy** [comment]
@curita  I solved this by just using an [`Extension`](https://gist.github.com/nramirezuy/5aba864e0c36986f548f), maybe it helps :smile:

**Comment by nautilus28** [comment]
I place CONCURRENT_REQUESTS_PER_DOMAIN = 2 in custom_settings, but this does not shown in the log message. Then how can I make sure that custom_settings do really work?

**Comment by ngoanhtan** [comment]
@nautilus28 : just see in debug log. It should alway have 1-2 request in same time.Or you can override open_spider/close_spider method for count it.

**Comment by nautilus28** [comment]
@ngoanhtan the CONCURRENT_REQUESTS_PER_DOMAIN setting does not shown in debug log, and overriding open_spider/close_spider does not help.

**Comment by jdemaeyer** [comment]
This doesn't solve the underlying issue, but you can issue your own log entry from within the spider if you really need to see the settings value:

```python
self.logger.debug('Concurrent requests per domain: %d', self.settings['CONCURRENT_REQUESTS_PER_DOMAIN'])
```

You could place it in the Spider's `closed` method if it's sufficient to log it after the crawling process, or in the `parse` method (though, depending on your spider, it will probably be logged multiple times in that case).
