### ISSUE TITLE
logging level issues in 1.0.1

### ISSUE THREAD

**Issue by ileodo** [scrapy/scrapy#1347]
Under the following setting up:

in setting.py:
`LOG_ENABLED = False`

in script to start the crawler:

```
configure_logging()
process = CrawlerProcess(get_project_settings())
process.crawl('retriever')
process.start()
```

in crawler:

```
logging.debug("PC get page [%s]:- %s" % (item['id'], item['url']))
```

There are still a lot of logging info.
even:

```
2015-07-09 23:29:20 [scrapy] DEBUG: Scraped from <200 http://www.example.com>
```

Is is a bug?

**Comment by kmike** [comment]
I think it is a documentation bug. Check http://doc.scrapy.org/en/latest/topics/practices.html#run-from-script - you need to run `configure_logging()` only for CrawlerRunner, not for CrawlerProcess. But [configure_logging](http://doc.scrapy.org/en/latest/topics/logging.html#scrapy.utils.log.configure_logging) docstring says 

> configure_logging is automatically called when using Scrapy commands, but needs to be called explicitly when running custom scripts. In that case, its usage is not required but it’s recommended.

**Comment by SiddharthaAnand** [comment]
@kmike Can I work on this issue?

**Comment by Gallaecio** [comment]
@SiddharthaAnand Have you changed your might?

**Comment by anuja-kelkar** [comment]
@kmike Can I work on this?

**Comment by Gallaecio** [comment]
@anuja-kelkar Please, go ahead.

**Comment by Vandenn** [comment]
Logging is currently behaving as expected when `LOG_ENABLED` is set to `False` using the following script in a Python 3.6 environment. Should this issue be closed? Kindly correct me if I'm making a wrong assumption about this.
```
import scrapy
from scrapy.crawler import CrawlerProcess


class MySpider(scrapy.Spider):
    name = 'spider'

process = CrawlerProcess({
    'LOG_ENABLED': False
})

process.crawl(MySpider)
process.start()
```

**Comment by Gallaecio** [comment]
@Vandenn You are right, that’s why @kmike said it’s a documentation problem. The original poster, @ileodo, is calling `configure_logging()`, which the current documentation suggest, but that should not be used with `CrawlerProcess`, only with `CrawlerRunner`.

**Comment by Vandenn** [comment]
@Gallaecio Thanks for the clarification. I'll open a PR soon that updates the documentation of `scrapy.utils.log.configure_logging` to specify that the function should only be used with `CrawlerRunner`.
