### ISSUE TITLE
How soon would Scrapy support python3.3+?

### ISSUE THREAD

**Issue by wolfgangersmith** [scrapy/scrapy#1356]
Scrapy is my favourite web crawler,

I wanted to know an approximate timeframe if possible for when scrapy would be able to support python3.3+

There are an increasing amount of opensource projects which do not support python2.7 so this made me wonder.

Thanks

**Comment by nyov** [comment]
At the earliest, once all twisted dependencies are ported to py3 (or someone writes asyncio replacements :D).
We might see some updates after GSoC, work on [the porting effort](http://gsoc2015.scrapinghub.com/ideas/#python3-support) is [ongoing](http://blog.scrapinghub.com/2015/06/25/google-summer-of-code-2015/).

**Comment by stonebig** [comment]
A new round of consessions (to purity) have been included in Python 3.5, so that Twisted can fully migrate to Python 3.5. 

Continuum IO has already a partial port of Twisted to Python 3.4 (not 3.3), if you're in a hurry:
http://docs.continuum.io/anaconda/pkg-docs.html

**Comment by curita** [comment]
We had some difficulties along the way, sadly python3 support isn't an ongoing GSoC project anymore :(

At Scrapinghub we were planning on making a sprint in EuroPython week to push for making it happen,  hopefully a considerable progress results out of it. In any case, it's something we want to see as soon as possible. I know this is a big timeframe, but we'll expect to see it done sometime in this year (but don't quote me on that :wink:).

Of course, any pull request extending python3 support is welcomed, we try to see all of them through to get them merged.

I'm keeping this issue open a little more in case you have any more related questions, but please don't duplicate what has been said in #263, I'm going to close this issue later in favor of that one.

**Comment by curita** [comment]
Python3 port discussion is happening in #263.
