### ISSUE TITLE
UnicodeEncodeError on LinkExtractor's extract_links

### ISSUE THREAD

**Issue by nautilus28** [scrapy/scrapy#1360]
I recently upgraded scrapy to version 1.0.1. When I tried:
scrapy shell http://baywindows.com/my-very-gay-straight-cruise-123436

In [1]: from scrapy.linkextractors import LinkExtractor

In [2]: link_extractor = LinkExtractor()

In [3]: link_extractor.extract_links(response)

I got this exception: UnicodeEncodeError: 'charmap' codec can't encode characters in position 9-18: character maps to <undefined>

Is it a bug or Scrapy version 1.0.1 has a few changes that I was not aware of?

thanks in advance,
Canh

**Comment by nyov** [comment]
```python-traceback
---------------------------------------------------------------------------
UnicodeEncodeError                        Traceback (most recent call last)
<ipython-input-3-5f4eda83c46f> in <module>()
----> 1 link_extractor.extract_links(response)

/[scrapy]/scrapy/linkextractors/lxmlhtml.pyc in extract_links(self, response)
    106         all_links = []
    107         for doc in docs:
--> 108             links = self._extract_links(doc, response.url, response.encoding, base_url)
    109             all_links.extend(self._process_links(links))
    110         return unique_list(all_links)

/[scrapy]/scrapy/linkextractors/__init__.pyc in _extract_links(self, *args, **kwargs)
    101 
    102     def _extract_links(self, *args, **kwargs):
--> 103         return self.link_extractor._extract_links(*args, **kwargs)
    104 
    105 # Top-level imports

/[scrapy]/scrapy/linkextractors/lxmlhtml.pyc in _extract_links(self, selector, response_url, response_encoding, base_url)
     55                 continue
     56             if isinstance(url, unicode):
---> 57                 url = url.encode(response_encoding)
     58             # to fix relative links after process_value
     59             url = urljoin(response_url, url)

/usr/lib/python2.7/encodings/cp1252.pyc in encode(self, input, errors)
     10 
     11     def encode(self,input,errors='strict'):
---> 12         return codecs.charmap_encode(input,errors,encoding_table)
     13 
     14     def decode(self,input,errors='strict'):

UnicodeEncodeError: 'charmap' codec can't encode characters in position 9-18: character maps to <undefined>

```
This is because the page is (mis)detected as "latin-1/western/windows" but apparently should be utf8 or something else.

```python
In [4]: response.encoding
Out[4]: 'cp1252'
```

Visiting the page in browser, will show you stuff like "[...] erformanceâ€•a [...]".

The page obviously doesn't care to send the correct encoding along. So the fault is solely with the website (Not a bug).
You should force-override the page encoding, or try to do more outlandish encoding detection (like BeautifulSoup tries very hard to fix bad pages with UnicodeDammit and such).

**Comment by nautilus28** [comment]
Thanks @nyov

**Comment by Whadup** [comment]
how can I force-orverride the page encoding? Particularly, when using CrawlSpiders?

**Comment by redapple** [comment]
@Whadup , what is your use-case? what are you experiencing? Consider asking troubleshooting questions on [scrapy-users mailing list](https://groups.google.com/d/forum/scrapy-users) of [StackOverflow with tag "scrapy"](https://stackoverflow.com/questions/tagged/scrapy)

**Comment by Whadup** [comment]
I'm trying to download a page that claims to be iso-8859-1, but contains characters that are not 8859-1 characters. scrapy tries to encode it as win1252, judging from the stacktrace, and crashes immediately. I believe the page actually uses utf-8 and want to force downloading and decoding as utf-8 in order for the LinkExtractor not to crash and the CrawlSpider to work successfully.

```
  File "python2/lib/python2.7/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "python2/lib/python2.7/site-packages/scrapy/spidermiddlewares/offsite.py", line 28, in process_spider_output
    for x in result:
  File "python2/lib/python2.7/site-packages/scrapy/spidermiddlewares/referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "python2/lib/python2.7/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "python2/lib/python2.7/site-packages/scrapy/spidermiddlewares/depth.py", line 54, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "python2/lib/python2.7/site-packages/scrapy/spiders/crawl.py", line 73, in _parse_response
    for request_or_item in self._requests_to_follow(response):
  File "python2/lib/python2.7/site-packages/scrapy/spiders/crawl.py", line 52, in _requests_to_follow
    links = [l for l in rule.link_extractor.extract_links(response) if l not in seen]
  File "/Users/pfahler/anaconda3/envs/python2/lib/python2.7/site-packages/scrapy/linkextractors/lxmlhtml.py", line 108, in extract_links
    links = self._extract_links(doc, response.url, response.encoding, base_url)
  File "python2/lib/python2.7/site-packages/scrapy/linkextractors/__init__.py", line 103, in _extract_links
    return self.link_extractor._extract_links(*args, **kwargs)
  File "python2/lib/python2.7/site-packages/scrapy/linkextractors/lxmlhtml.py", line 57, in _extract_links
    url = url.encode(response_encoding)
  File "python2/lib/python2.7/encodings/cp1252.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
```

**Comment by redapple** [comment]
If you want to change the encoding of the response before it gets processed by `CrawlSpider` rules, you probably need to override your spider's [`parse` method](https://github.com/scrapy/scrapy/blob/master/scrapy/spiders/crawl.py#L42)
Something like this:
```
class YourSpider(CrawlSpider):
    ...
    def parse(self, response):
        return super(YourSpider, self).parse(
            response.replace(encoding='UTF-8')
        )
```

I've worked on link extraction encoding issues in #1949, so if you could send me (by email if you don't want to disclose it here) some URLs where link extraction chokes, I'd be happy to look into it more.
