### ISSUE TITLE
ImagesPipeline not updating the 'images' attribute in item

### ISSUE THREAD

**Issue by ritesh-gopal** [scrapy/scrapy#1368]
I am using Scrapy 0.25 with Portia to scrape sites. 
I enabled the ImagesPipeline in my project

After deploying to scrapyd, I have been able to save the images to my specified directory. 

According to the documentation, the ImagesPipeline will update the 'item' with an attribute 'images' indicating the file name of the saved image. The issue is that when I inspect my items scraped from the scrapyd UI, there is no 'images' attribute.So there is no way to link the downloaded images to my items.

**Comment by perfect1** [comment]
I'm having this issue as well. It seems to work correctly in version 0.24.4, but not 1.0.1.

**Comment by Gallaecio** [comment]
@ritesh-gopal, @perfect1 Do you still suffer these issues using the latest Scrapy version?

**Comment by Gallaecio** [comment]
Closing due to a lack of feedback.
