### ISSUE TITLE
How to tell Scrapy to stop following pages in the middle of the program?

### ISSUE THREAD

**Issue by wolfgangersmith** [scrapy/scrapy#1376]
Okay, Basically

Scrapy has to follow 10 pages & each page has ---> 100 links

While scraping data from each link (Request Object created per link)  I compute the TIMESTAMP and if it's "too old" (according to a program-pre-defined variable) It must STOP following links(pages). However it must NOT stop the program, but rather STOP following links and finish up scraping the "Request" objects it had previously created untill that point, and in doing so it will eventually come to a halt (it runs out links to scrape)

Is there anyway i can do this in scrapy?

I tried raising a CloseSpider Exception, but scrapy would not complete scraping all the "Request" objects it had already created.

**Comment by starrify** [comment]
> ... but rather STOP following links and finish up scraping the "Request" objects it had previously created untill that point

Are you using the `BaseSpider` or `CrawlSpider` or anything else? You could actually have it controlled through your own logics. Sample code:

```Python
class SampleSpider(scrapy.Spider):
    """Just a sample spider."""

    start_requests = [your_10_pages_here]
    _stop_following_links = False

    def parse(self, response):
        """Parses initial responses."""
        for link in self._get_links(response):
            if self._stop_following_links:
                break
            else:
                yield scrapy.Request(
                    url=link,
                    callback=self.parse_followed
                )

    def parse_followed(self, response):
        """Parses followed responses."""
        if self._timestamp_too_old(response):
            self._stop_following_links = True
        else:
            # Process it
            pass
```

---

Also, personally I think this post is a question, not an issue report, and thus shall be closed here. Or, please let us know what you think is an issue of `scrapy`. 

You could always ask for help on `scrapy` in the [community](http://scrapy.org/community/), by posting your questions onto the mailling list, the IRC channel, or StackOverflow.

**Comment by stejesh** [comment]
@starrify

Your solution does solve the problem partially, However, Scrapy would continue to follow the pages (based on the regex rule). what if there are 1000+ pages to follow?  (scrapy would not scrape links in each page however)

The efficient solution would tell scrapy to stop following any pages as well (perhaps by modifying the regex rule in LinkExtractor)

Do you have any suggestions for this?

**Comment by starrify** [comment]
@stejesh 

> Scrapy would continue to follow the pages (based on the regex rule)

You seems to be using the `CrawlSpider`. I asked about that and you didn't answer. How could the problems be solved if you don't provide necessary information to ones who are trying to help? :(

If you do use `CrawlSpider`, them I'm afraid there is no current supported approaches for your need. You may choose to avoid using the `CrawlSpider` (then the suggestion above would help), or, simply set the `_follow_links` attribute of your spider instance to `False`, see https://github.com/scrapy/scrapy/blob/master/scrapy/spiders/crawl.py#L72

Please do notice that `_follow_links` is an internal attribute and is not documented. It could be changed or removed in any `scrapy` updates without prior notice. Use it at your own risk and use with care.

**Comment by stejesh** [comment]
Apologies,

Given that this is a fair use-case, i hope `_follow_links` or something similar would form a part of the `CrawlSpider`

**Comment by starrify** [comment]
As there is an setting key `CRAWLSPIDER_FOLLOW_LINKS`, a `CrawlSpider` instance must be using some internal variable to store the value. Thus personally I think `_follow_links` won't get excluded and won't be even changed for backward compatibility.

The warning is given since I don't know whether you're doing something of great importance. If I have the need myself I think I'll go ahead and use `_follow_links`. :)

**Comment by eliasdorneles** [comment]
This channel is meant for issues in Scrapy, in the future please use the [community channels](http://scrapy.org/community/) for user questions (Stackoverflow or mailing-list).

**Comment by bharath-kumarn** [comment]
How to stop scrapy spider after certain number of requests/pages?
