### ISSUE TITLE
response.body contains no HTML

### ISSUE THREAD

**Issue by darshanime** [scrapy/scrapy#1377]
My target site issues a redirect which when I stop forcefully causes the `response` object to come back blank without any HTML. Also, on another site, it contains the flash screen (used to denote Loading of results). 
Is there a way to simulate the page loading and then pull the HTML into the `response` object?

**Comment by starrify** [comment]
> My target site issues a redirect

Responses with HTTP status code 301 or 302 may have an empty body. However such responses shall have been handled by the [RedirectMiddleware](http://doc.scrapy.org/en/latest/topics/downloader-middleware.html#module-scrapy.downloadermiddlewares.redirect) which is enabled by default. Have you disabled it?

> Is there a way to simulate the page loading

Please elaborate and show others what exactly is the "page loading" you want. Maybe a sample site and some sample codes?

> ..and then pull the HTML into the `response` object?

You could use the [`Response.replace`](http://doc.scrapy.org/en/latest/topics/request-response.html#scrapy.http.Response.replace) method to replace the body of an existing `Response` instance, e.g. `new_response = old_response.replace(body=new_HTML)`

---

Also, personally I think this post is a question, not an issue report, and thus shall be closed here. Or, please let us know what you think is an issue of `scrapy`. 

You could always ask for help on `scrapy` in the [community](http://scrapy.org/community/), by posting your questions onto the mailling list, the IRC channel, or StackOverflow.

**Comment by nyov** [comment]
> You could use the Response.replace method to replace the body of an existing Response instance

...or build a custom new response
```py
from scrapy.http import HtmlResponse

response = HtmlResponse(response.url,
	encoding='utf-8',
	body=body.decode('utf-8'),
)
```

Agree with @starrify, please don't abuse the issue tracker for support questions.

**Comment by darshanime** [comment]
Yes, I fully understand my misuse of the Issue Tracker and I apologize. Will close this issue after your comments on this :

I am trying to scrape : `https://housing.com/in/rent/search?f=eyJsb2N0IjoicG9seSIsInBvbHkiOnsiaWQiOiIxY2E5OWMzM2UzZDhiOTg3Y2NmMSIsImJ1ZmZlciI6ZmFsc2V9LCJwYWdlX251bSI6M30%3D`

My spider is simply :

```python
import scrapy


class HousingSpider(scrapy.Spider):
    name = "housing"
    allowed_domains = ["housing.com"]
    start_urls = (
        'https://housing.com/in/rent/search?f=eyJsb2N0IjoicG9seSIsInBvbHkiOnsiaWQiOiIxY2E5OWMzM2UzZDhiOTg3Y2NmMSIsImJ1ZmZlciI6ZmFsc2V9LCJwYWdlX251bSI6M30%3D',
    )
    custom_settings = {'USER_AGENT' : 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36'}

    def parse(self, response):
        filename = 'try_one.html'
        with open(filename, 'wb') as f:
            f.write(response.body)
```

The HTML in the file gives a flash screen, not the loaded page I expect.

**Comment by nyov** [comment]
You are trying to get a javscript-only page. At least there is really nothing much to see on that link without javascript. Disable it to see what scrapy sees.
The loaded page you expect requires a DOM and javascript execution to be built/rendered.


> Is there a way to simulate the page loading and then pull the HTML into the `response` object?

In that case, you may use any of these:
[Splash][1] + [ScrapyJS][2] or [phantomjs][3] / [SlimerJS][4] or [Selenium][5] with [webdrivers][6], either standalone or as middlewares in scrapy. There may be more alternatives that I am not aware of.
Take your pick.


[1]: https://github.com/scrapinghub/splash
[2]: https://github.com/scrapinghub/scrapyjs
[3]: http://phantomjs.org/
[4]: https://slimerjs.org/
[5]: http://docs.seleniumhq.org/download/
[6]: https://selenium-python.readthedocs.org/en/latest/api.html

**Comment by darshanime** [comment]
Thank you for your guidance and patience. Closing.

**Comment by HaiQW** [comment]
A very useful guidance, thank you~
