### ISSUE TITLE
Using OrderedDict instead of  Dict in items.py

### ISSUE THREAD

**Issue by chiragmatkar** [scrapy/scrapy#1378]
Can we get order list of items in output in same order as we populate the Dict ?

**Comment by nyov** [comment]
You can use a normal dict, and therefore also an OrderedDict, for your items since scrapy 1.0

But please don't abuse the issue tracker for support questions.

**Comment by chiragmatkar** [comment]
Hi,

I actually added an enhancement request to automatically get the items list
in order we specify.



On Fri, Jul 24, 2015 at 7:04 AM, nyov <notifications@github.com> wrote:

> You can use a normal dict, and therefore also an OrderedDict, for your
> items since scrapy 1.0
>
> But please don't abuse the issue tracker for support questions.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scrapy/scrapy/issues/1378#issuecomment-124288316>.
>



-- 

Thanks and Regards,
Chirag Matkar

**Comment by pablohoffman** [comment]
This is a support question, please use the mailing list (scrapy-users).
