### ISSUE TITLE
Recursive POST requests from RedirectMiddleware

### ISSUE THREAD

**Issue by rverbitsky** [scrapy/scrapy#1387]
Hello, dear Scrapy maintainers!

Today I've got crazy recursive POST redirects from FormRequest's with server responded 301.

Changing 

``` python
redirected = request.replace(url=redirected_url)
```

to

``` python
redirected = request.replace(url=redirected_url, method='GET')
```

in RedirectMiddleware solve's this problem.

Is this a bug?

**Comment by nyov** [comment]
Supposedly your server does not accept POSTing that form and you should create your `FormRequest` with `method=GET` in the first place?

The only issue I see would be if you have RedirectMiddleware enabled and it doesn't stop redirecting after the set redirect limit.

**Comment by Gallaecio** [comment]
@rverbitsky Do you remember if using `GET` from the start solved your issue?

**Comment by Gallaecio** [comment]
Closing due to a lack of feedback.
