### ISSUE TITLE
rename "anon" Slot classes in the code

### ISSUE THREAD

**Issue by nyov** [scrapy/scrapy#1392]
I wonder what people would say to this change?

```patch
diff --git a/scrapy/core/downloader/__init__.py b/scrapy/core/downloader/__init__.py
index 9654718..743a891 100644
--- a/scrapy/core/downloader/__init__.py
+++ b/scrapy/core/downloader/__init__.py
@@ -15,7 +15,7 @@ from .middleware import DownloaderMiddlewareManager
 from .handlers import DownloadHandlers
 
 
-class Slot(object):
+class DownloadSlot(object):
     """Downloader slot"""
 
     def __init__(self, concurrency, delay, randomize_delay):
@@ -48,7 +48,7 @@ class Slot(object):
 
     def __str__(self):
         return (
-            "<downloader.Slot concurrency=%r delay=%0.2f randomize_delay=%r "
+            "<downloader.DownloadSlot concurrency=%r delay=%0.2f randomize_delay=%r "
             "len(active)=%d len(queue)=%d len(transferring)=%d lastseen=%s>" % (
                 self.concurrency, self.delay, self.randomize_delay,
                 len(self.active), len(self.queue), len(self.transferring),
@@ -105,7 +105,7 @@ class Downloader(object):
         if key not in self.slots:
             conc = self.ip_concurrency if self.ip_concurrency else self.domain_concurrency
             conc, delay = _get_concurrency_delay(conc, spider, self.settings)
-            self.slots[key] = Slot(conc, delay, self.randomize_delay)
+            self.slots[key] = DownloadSlot(conc, delay, self.randomize_delay)
 
         return key, self.slots[key]
 
diff --git a/scrapy/core/engine.py b/scrapy/core/engine.py
index 992327b..6e1a47b 100644
--- a/scrapy/core/engine.py
+++ b/scrapy/core/engine.py
@@ -21,7 +21,7 @@ from scrapy.utils.log import logformatter_adapter, failure_to_exc_info
 logger = logging.getLogger(__name__)
 
 
-class Slot(object):
+class EngineSlot(object):
 
     def __init__(self, start_requests, close_if_idle, nextcall, scheduler):
         self.closing = False
@@ -231,7 +231,7 @@ class ExecutionEngine(object):
         nextcall = CallLaterOnce(self._next_request, spider)
         scheduler = self.scheduler_cls.from_crawler(self.crawler)
         start_requests = yield self.scraper.spidermw.process_start_requests(start_requests, spider)
-        slot = Slot(start_requests, close_if_idle, nextcall, scheduler)
+        slot = EngineSlot(start_requests, close_if_idle, nextcall, scheduler)
         self.slot = slot
         self.spider = spider
         yield scheduler.open(spider)
diff --git a/scrapy/core/scraper.py b/scrapy/core/scraper.py
index 244499b..3082342 100644
--- a/scrapy/core/scraper.py
+++ b/scrapy/core/scraper.py
@@ -20,7 +20,7 @@ from scrapy.core.spidermw import SpiderMiddlewareManager
 logger = logging.getLogger(__name__)
 
 
-class Slot(object):
+class ScraperSlot(object):
     """Scraper slot (one per running spider)"""
 
     MIN_RESPONSE_SIZE = 1024
@@ -76,7 +76,7 @@ class Scraper(object):
     @defer.inlineCallbacks
     def open_spider(self, spider):
         """Open the given spider for scraping and allocate resources for it"""
-        self.slot = Slot()
+        self.slot = ScraperSlot()
         yield self.itemproc.open_spider(spider)
 
     def close_spider(self, spider):

```

**Comment by kmike** [comment]
I'm fine with this idea. I tried to fix it for DownloaderSlot by adding `__repr__` method (it says 'downloader.Slot' which is different from other slots), but it helps only for code inspected in shell, not when you browse code in an editor.

To make this change it'd be good to deprecate old classes (see [create_deprecated_class](https://github.com/scrapy/scrapy/blob/9d9d4238aa8c0b6009aca689b8c23cb8bdab8fa7/scrapy/utils/deprecate.py#L15)) and remove "downloader." prefix from DownloaderSlot `__repr__`. `__repr__` methods for other Slot classes are also welcome.

**Comment by nramirezuy** [comment]
Most slot classes should be removed. For example [this one](https://github.com/scrapy/scrapy/blob/master/scrapy/core/engine.py#L24) there will never be 2 instances of that class.

**Comment by dangra** [comment]
I can't see value on renaming these classes, they are for internal use and not part of public API,  in general I tend to prefer shorter names for _private_ classes used only within same module.

**Comment by nyov** [comment]
@dangra, that implies knowledge of the fact that they are considered private. I mean they are not excluded from the modules export list, have no docs that would say so, or a name that would imply such, to me. I wasn't truly aware of that fact.
Aside from that, I tend to do a lot of `git grep` to have an overview of and get through a code base, as I don't use an IDE often enough.
Seeing a lot of `Slot` definitions stuck out since I couldn't easily determine which would be which, from a context-less grep result.
OTOH I can see the aesthetic in having the short names (my engineer side likes). Maybe it just needs more pointing out that these are private, and only ever used inside another proxy class ("belongs to")?

**Comment by nyov** [comment]
Thanks @redapple. I think I'll close this though.
Unless there is merit in what @nramirezuy said about removing some of them?
Feel free to reopen, in that case.
