### ISSUE TITLE
Scrapy and RotatingFileHandler

### ISSUE THREAD

**Issue by zelenij** [scrapy/scrapy#1406]
Wouldn't it be nice if one could configure scrapy to use RotatingFileHandler instead of just FileHandler for logging?  With something like regularly running process it makes sense, doesn't it? :)

**Comment by nyov** [comment]
That is why scrapy now uses standard python logging facilities, so you can easily build it yourself.

scrapy just provides the basics, this would be too much 'contrib' to include in scrapy itself IMO.
For example people using DB-loggers won't ever have need for this.

I tend to go with a syslog solution and care about the logging output to file or DB and message tagging at the syslog level. Then I can just use standard logrotate for this.

**Comment by nramirezuy** [comment]
@zelenij we are not interested on maintaining something like that; but if you make it happen let us know so we can promote it when similar questions happen (:
