### ISSUE TITLE
allow specifying max_active_size for scraper.slot

### ISSUE THREAD

**Issue by vincentlaucy** [scrapy/scrapy#1410]
It's seems to me that such behaviour is undocumented - scraper will be in back out state once there is over 5M requests, as in https://github.com/scrapy/scrapy/blob/342cb622f1ea93268477da557099010bbd72529a/scrapy/core/scraper.py#L29

where the default value is always used.
https://github.com/scrapy/scrapy/blob/342cb622f1ea93268477da557099010bbd72529a/scrapy/core/scraper.py#L79

I am reaching a deadlock scenario that I have over 5M requests in the slot, then since enqueue request will check for backout, new request can never be completed.

I can submit a PR if it make sense to extract to settings, say SCRAPER_SLOT_MAX_ACTIVE_SIZE

**Comment by john156** [comment]
:+1:

**Comment by Gallaecio** [comment]
@vincentlaucy Did changing this value fixed your deadlock? Do you remember whether it really a deadlock or just a severe slow down?

**Comment by Gallaecio** [comment]
Closing due to a lack of feedback.
