### ISSUE TITLE
Scrapy --lsprof has no tests

### ISSUE THREAD

**Issue by kmike** [scrapy/scrapy#1417]
We should add some tests for `--lsprof` command-line option.

**Comment by Preetwinder** [comment]
Please provide some clarification-
Currently, the `--profile` option has a single test in the CmdlineTest testcase in the file - test_cmdline/\_\_init\_\_.py. 
Should `--lsprof` also have a single test in the same testcase or, it should have a seperate testcase?

**Comment by kmike** [comment]
Hey @Preetwinder,

I don't know; maybe it is better even to remove `--lsprof` option. Sorry for a confusing ticket. 

If we decide to keep it then even a single test would be an improvement. But to test it properly we'll have to write some tests for https://github.com/scrapy/scrapy/blob/master/scrapy/xlib/lsprofcalltree.py: unlike `--prof` this option doesn't just call stdlib profiler.

**Comment by kmike** [comment]
We've removed --lsprof command.
