### ISSUE TITLE
unable to pull some urls

### ISSUE THREAD

**Issue by rbaral** [scrapy/scrapy#1418]
Hi,

I tried the example spider with the url https://scholar.google.com and it didn't work.

I just had copied the spider file and removed unwanted things (for me). Mine version of spider file is as shown below:

import scrapy
class ScholarlySpider(scrapy.Spider):
    name = "scholar"
    allowed_domains = ["scholar.google.com"]
    baseURL="https://scholar.google.com"
    start_urls = [baseURL]

    def parse(self, response):
            #nothing specific in this method right now
            print response

Mine items.py looks like this:

import scrapy
class ScholarlycrawlItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    title = scrapy.Field()
    link = scrapy.Field()
    desc = scrapy.Field()

I have other files - pipelines.py and settings.py as the default one when creating the new scrapy project.

Sorry, I couldn't figure out how to format the code section in this bug tracking system, but I hope it is still clear as I dont have that much code section. The screenshot of the program execution is included in three images - error1 - error3.jpg because I couldnot grab the whole screen in a single image.

Thanks.

![error1](https://cloud.githubusercontent.com/assets/2064066/9179133/72cb34c2-3f68-11e5-914b-fa005fe289ba.png)
![error2](https://cloud.githubusercontent.com/assets/2064066/9179134/72cfce88-3f68-11e5-8e40-be5bbb1b8c82.png)
![error3](https://cloud.githubusercontent.com/assets/2064066/9179135/72d07b26-3f68-11e5-9c57-46d9485ddf4c.png)

**Comment by kmike** [comment]
Hey @rbaral,

Could you please try installing `service_identity` Python package and try again? Does it fix your issue?

**Comment by rbaral** [comment]
Hi kmike,

Thanks for the prompt response. After installing service_identity that issue has been resolved.

Thanks.

**Comment by kmike** [comment]
Thanks for checking it!

/cc @dangra what about adding service_identity to Scrapy install_requires?

**Comment by dangra** [comment]
> what about adding service_identity to Scrapy install_requires?

@kmike It's about time to do so and deal with the debian packaging problems somewhere else.
