### ISSUE TITLE
Simplify Python 3 badge

### ISSUE THREAD

**Issue by pablohoffman** [scrapy/scrapy#1454]
We've recently added a badge to highlight progress on Python 3 port. I suggest to simplify the Python 3 support badge to just show a percentage. If you look at the other badges we have in the scrapy project you'll see that the value of them is usually simple (a number, percentage, or short text).

![screenshot_1_1440102203](https://cloud.githubusercontent.com/assets/185212/9450266/1523fb80-4a7e-11e5-851f-b062e46b6ce1.png)

Showing just the percentage 54% would not only be more consistent with the rest but also easier to understand (what's "633 / 1153" anyway? which even comes before the percentage!)

**Comment by kmike** [comment]
I've changed it (see http://static.scrapy.org/py3progress/badge.svg); it seems github needs some time to update.

**Comment by pablohoffman** [comment]
thanks @kmike !

**Comment by kirankoduru** [comment]
Hey @kmike !  Can you take a look at this issue? Seems like the README still doesn't render it the progress PY3 badge.

**Comment by kmike** [comment]
Argh, https://shields.io/ we were using to generate the badge is down again.

**Comment by kmike** [comment]
@pablohoffman what do you think about removing the badge for now?
