### ISSUE TITLE
disable codecov/project check

### ISSUE THREAD

**Issue by kmike** [scrapy/scrapy#1457]
It checks that coverage is not decreased. But if coverage is not 100% yet and some covered lines are deleted then coverage decreases; we shouldn't mark a PR failed in this case. Deleting code is a good thing :)

**Comment by nramirezuy** [comment]
The way that bot comments on the PR's annoyed me already :angry:

**Comment by dangra** [comment]
I turned off project coverage and increased PR coverage to 100%

![image](https://cloud.githubusercontent.com/assets/37369/9501069/57b09102-4bff-11e5-99d7-302bed3c6f3b.png)

**Comment by kmike** [comment]
sounds good to me

**Comment by kmike** [comment]
I like that the bot is begging people to write more tests:)

**Comment by dangra** [comment]
> I like that the bot is begging people to write more tests:)

so do I.
