### ISSUE TITLE
Error when running 'scrapy' in command line

### ISSUE THREAD

**Issue by rosspalmer** [scrapy/scrapy#1460]
Hello!

I have trying installing scrapy using both the 'pip' method and installing directly from the source code and keep running into the same error.

When I attempt to run any 'scrapy' based command in the terminal I receive the following output:

    bash: /usr/bin/scrapy: No such file or directory

This error is very much correct as all python packages on my machine would be stored in the directory below and I have confirmed that the scrapy modules are indeed present.

    /usr/local/bin/

Any ideas on how to resolve this issue? I am running Ubuntu 14.04 LTS

**Comment by dangra** [comment]
do you mean `/usr/local/bin/scrapy` exists after installing with pip?

If so, add `/usr/local/bin` to PATH environment variable or create symlink from /usr/bin/ like:

    ln -s /usr/local/bin/scrapy /usr/bin/

**Comment by rosspalmer** [comment]
worked! thank you for the quick response

**Comment by aiedonline** [comment]
hi, create link in my case is very good. Thanks.
