### ISSUE TITLE
Unsupported URL scheme : no handler available for that scheme

### ISSUE THREAD

**Issue by aldarund** [scrapy/scrapy#1463]
I have a lot of errors like this in the error log ( im using sentry ) and  they are just pollute the log.
Unsupported URL scheme 'mailto': no handler available for that scheme
Unsupported URL scheme 'about': no handler available for that scheme

etc.

So the log just become very polluted with this errors because there really a lot of them. Is 

My spider:

     class ExternalLinkSpider(CrawlSpider):
       name = 'external_link_spider'
       allowed_domains = ['']
       start_urls = ['']

       rules = (Rule(LxmlLinkExtractor(allow=()), callback='parse_obj', follow=True),)
  
       def parse_obj(self, response):
         if not isinstance(response, HtmlResponse):
            return
         for link in LxmlLinkExtractor(allow=(), deny=self.allowed_domains).extract_links(response):
            if not link.nofollow:
                yield LinkCrawlItem(domain=link.url)

If there somethin wrong with my spider that could be fixed to stop producing this error, please advice.

**Comment by gautham-nxt-gen-soft** [comment]
Hey guys I'm new to web crawling.Sorry for disturbing you guys.
I came to know that scrapy is the fastest web framework module for web 
crawling.
I thought that you guys would be doing that in multithreading but I 
heard that you guys never use threading.How could this be possible?can 
anyone give a short explanation to me...Please

**Comment by nramirezuy** [comment]
@aldarund well you can start by fixed the rule to just grab http and https links.

@gautham-nxt-gen-soft we use twisted. 

Guys for support please use [scrapy-users](https://groups.google.com/forum/#!forum/scrapy-users) or IRC #scrapy

**Comment by vengadam2001** [comment]
> I have a lot of errors like this in the error log ( im using sentry ) and they are just pollute the log.
> Unsupported URL scheme 'mailto': no handler available for that scheme
> Unsupported URL scheme 'about': no handler available for that scheme
> 
> etc.
> 
> So the log just become very polluted with this errors because there really a lot of them. Is
> 
> My spider:
> 
> ```
>  class ExternalLinkSpider(CrawlSpider):
>    name = 'external_link_spider'
>    allowed_domains = ['']
>    start_urls = ['']
> 
>    rules = (Rule(LxmlLinkExtractor(allow=()), callback='parse_obj', follow=True),)
> 
>    def parse_obj(self, response):
>      if not isinstance(response, HtmlResponse):
>         return
>      for link in LxmlLinkExtractor(allow=(), deny=self.allowed_domains).extract_links(response):
>         if not link.nofollow:
>             yield LinkCrawlItem(domain=link.url)
> ```
> 
> If there somethin wrong with my spider that could be fixed to stop producing this error, please advice.
even I too face the same error but if i add other data(texts) to the pipeline then i am getting this error .
