### ISSUE TITLE
Versioning of dependencies in recent releases

### ISSUE THREAD

**Issue by idella** [scrapy/scrapy#1465]
I do packaging @ gentoo and I am quite confused / unclear on setting the dependencies for this package given the content of setup.py and tox.ini

First; python implementations supported.
From setup.py
        'Programming Language :: Python',
        'Programming Language :: Python :: 2',
        'Programming Language :: Python :: 2.7',

from tox.ini
[tox]
envlist = py27
[testenv:py33]
basepython = python3.3

Second; Runtime / test phase deps
from setup.py
    install_requires=[
        'Twisted>=10.0.0',

from tox.ini
    pyOpenSSL==0.13
    lxml==2.3.2
    Twisted==11.1.0
which comes under [testenv:precise]
precise (ubunutu) has little to do with packaging for gentoo. However if it actually requires Twisted==11.1.0 for the tests, gentoo has a real problem.  Twisted==11.1.0 is so old it was dropped from portage some time ago.  I still don't have leveldb installed and the testsuite runs and passes all except the tests listed in /issues/1464.

Ideally a setup.py has a listing of tests_require like install_requires. I am guessing this was not done due to the mass conflict of versioning of dependencies between the various python versions. Currently the ebuilds of scrapy have only python 2.7 support and given all the above, to add python3 support would require a new ebuild of the same package due only to the disparate versioning of dependencies.

Quite simply, if runtime deps have conflicting versions against deps of the testsuite, it breaks portage in the form of a qa violation.  The deps ought match those listed in setup.py and any other source file listing them.

**Comment by kmike** [comment]
Hey @idella,

> Quite simply, if runtime deps have conflicting versions against deps of the testsuite, it breaks portage in the form of a qa violation. The deps ought match those listed in setup.py and any other source file listing them.

We run tests against 3 main environments: an environment with package versions available in Ubuntu Precise, an environment with latest available package versions in Python 2.x and Python 3.x. The point of running these tests is to check that we're compatible with Ubuntu package versions and with latest package versions. I don't see any conflict here. I'm not familiar with Gentoo practices, but for Gentoo it makes most sense to run tests against package versions available in Gentoo; there is no point of running 'precise' tests if the goal is to check that Scrapy works in Gentoo.

**Comment by idella** [comment]
While I follow your reasoning or logic there, we still have a mismatch. It makes sense to simply discard the entry re precise from consideration in preparing the ebuild.  I am more interested in getting a fix to 
/scrapy/issues/1464

**Comment by kmike** [comment]
> Also you never commented on the setup.py only listing support or python2 then making a text suite with a tox.ini all prepped for python3

Sorry, I missed this question. Currently Scrapy doesn't support Python 3; when it will Scrapy will likely have a different set of dependencies for Python 3 - it won't support older Twisted versions, and it may require extra packages like txtulip. 

We're running Python 3 tests because Python 3 porting is an ongoing effort - many parts of Scrapy are ported, but Scrapy is not usable yet for users as a framework.

**Comment by idella** [comment]
thought to thx

**Comment by kmike** [comment]
@idella - sorry, I'm a bit lost: what are you proposing to change?

**Comment by idella** [comment]
@kmike no making no proposals.  Just confirming that  Python 3 porting is an ongoing effort so it doesn't declare support for python 3 so I've left scrapy as supported by only python2 in our ebuilds.

**Comment by kmike** [comment]
@idella thanks for the heads up and for working on an ebuild!
