### ISSUE TITLE
Support for returning deferreds in middlewares

### ISSUE THREAD

**Issue by ArturGaspar** [scrapy/scrapy#1471]
Is there a reason why middlewares cannot return deferreds?
It could be used to fix the limitation mentioned in the [documentation of RobotsTxtMiddleware](http://doc.scrapy.org/en/master/topics/downloader-middleware.html#scrapy.downloadermiddlewares.robotstxt.RobotsTxtMiddleware).

The change is simple enough I could make a pull request for it myself, but I thought I would ask first if there is any reason for it to be the way it is.

**Comment by nramirezuy** [comment]
@ArturGaspar if you can do a PR for that it would be amazing!
