### ISSUE TITLE
Dependency issues on OSX 10.10.5

### ISSUE THREAD

**Issue by sebiwi** [scrapy/scrapy#1482]
Hi, I installed scrapy using pip and virtualenv.

Everything seems to go fine, but as I try to do anything I get this error:

```
Traceback (most recent call last):
  File "/Users/seb/stuff/scrapy/scrapy/bin/scrapy", line 7, in <module>
    from scrapy.cmdline import execute
  File "/Users/seb/stuff/scrapy/scrapy/lib/python2.7/site-packages/scrapy/__init__.py", line 48, in <module>
    from scrapy.spiders import Spider
  File "/Users/seb/stuff/scrapy/scrapy/lib/python2.7/site-packages/scrapy/spiders/__init__.py", line 10, in <module>
    from scrapy.http import Request
  File "/Users/seb/stuff/scrapy/scrapy/lib/python2.7/site-packages/scrapy/http/__init__.py", line 11, in <module>
    from scrapy.http.request.form import FormRequest
  File "/Users/seb/stuff/scrapy/scrapy/lib/python2.7/site-packages/scrapy/http/request/form.py", line 9, in <module>
    import lxml.html
  File "/Users/seb/stuff/scrapy/scrapy/lib/python2.7/site-packages/lxml/html/__init__.py", line 42, in <module>
    from lxml import etree
ImportError: dlopen(/Users/seb/stuff/scrapy/scrapy/lib/python2.7/site-packages/lxml/etree.so, 2): Library not loaded: libxml2.2.dylib
  Referenced from: /Users/seb/stuff/scrapy/scrapy/lib/python2.7/site-packages/lxml/etree.so
  Reason: Incompatible library version: etree.so requires version 12.0.0 or later, but libxml2.2.dylib provides version 10.0.0
```

I tried updating lxml using pip, but I already have the latest version. Why is this happening?

**Comment by eLRuLL** [comment]
@sebiwi could you pass a complete log?

**Comment by darkrho** [comment]
@sebiwi try using anaconda/miniconda for a hassle-free installation and package management: http://conda.pydata.org/miniconda.html

**Comment by kmike** [comment]
@sebiwi there are also updated install instructions for OS X in Scrapy master: check http://doc.scrapy.org/en/master/intro/install.html#mac-os-x.

**Comment by rylanchiu** [comment]
@curita Actually, I have read this post before and I have a version of python installed additionally. Right now I removed a line of code in the ~/.bash_profile:  PATH="/Library/Frameworks/Python.framework/Versions/3.5/bin:${PATH}"export PATH

and try to run the python script again. Now the error shifted to : 
ImportError                               Traceback (most recent call last)
<ipython-input-4-934a058a3d8d> in <module>()
      1 from twisted.internet import reactor
----> 2 from scrapy.crawler import Crawler
      3 from scrapy.settings import Settings
      4 from scrapy import log
      5 from testspiders.spiders.followall import FollowAllSpider

/Users/lcc/.virtualenvs/virtual/lib/python2.7/site-packages/scrapy/__init__.py in <module>()
     25 
     26 # Apply monkey patches to fix issues in external libraries
---> 27 from . import _monkeypatches
     28 del _monkeypatches
     29 

ImportError: cannot import name _monkeypatches

It seems that my bash-profile cause the issue. All of the code of bash-profile is as below:

export PATH=/usr/local/bin:/usr/local/sbin:$PATH

export PATH=$HOME/anaconda/bin:$PATH

export PATH=/usr/local/bin:$PATH

export JAVA_HOME=`/usr/libexec/java_home -v 1.8`

export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/Devel
source /usr/local/bin/virtualenvwrapper.sh

**Comment by bryan0** [comment]
I believe this error occurs when using pyenv or conda with python 2.7.
I tried using different minor versions as well and could not get it to work.
Just using brew python should work, but if you need more control over your python versions then Scrapy is not compatible for some reason.
