### ISSUE TITLE
deprecate Spider.make_requests_from_url

### ISSUE THREAD

**Issue by kmike** [scrapy/scrapy#1495]
Hey,

`Spider.make_requests_from_url` is a shortcut for a single use case: sending initial requests from a spider with start_urls attribute. It saves a single line of code (`for url in start_urls`) in one specific use case, but yet we have to document it, users have to read about it and understand what it is for. 

The name suggests it is more general - but we can't yield Link objects and get requests created by `make_requests_from_url`, it does nothing for CrawlSpider (I'd expect URLs to be passed through this method), and it is ignored for SitemapSpider. This is inconsistent.

What about deprecating `make_requests_from_url` and removing it from docs? IMHO it will make API simpler, this hook does nothing useful now, and if we ever want a general 'process URL and get a Request' method we'd have to use another name for backwards compatibility anyways.

**Comment by nramirezuy** [comment]
I agree; this method isn't that useful. Also now you even have a shorter import for `Request` if you wanna be lazy (:

**Comment by chekunkov** [comment]
+1
