### ISSUE TITLE
Question: lxml or scrapy selector

### ISSUE THREAD

**Issue by mirzadelic** [scrapy/scrapy#1502]
Should i use lxml library or scrapy.selector.Selector ?
lxml is fast, but how it is compared to scrapy.selector.Selector?

**Comment by nramirezuy** [comment]
Selectors use lxml in the back; also have some caching  which helps if you are parsing in different components.

This is a support questions; please use [scrapy-users](https://groups.google.com/forum/#!forum/scrapy-users) for this.
