### ISSUE TITLE
debian shell completions aren't installed via pip

### ISSUE THREAD

**Issue by jschilling1** [scrapy/scrapy#1506]
it'd be nice if zsh completion worked for pip installation in ubuntu

**Comment by kmike** [comment]
I'm not sure it is possible to install completions directly using pip. But if you know how to do this a pull request is welcome!

**Comment by sathve** [comment]
https://github.com/scrapy/scrapy/pull/3709

**Comment by Gallaecio** [comment]
@jschilling1  Is #3709 what you had in mind when you opened this issue?

To me it looks a bit out of the scope of Scrapy.

**Comment by Gallaecio** [comment]
Closing due to a lack of feedback.
