### ISSUE TITLE
Document scrapy.utils.url.canonicalize_url

### ISSUE THREAD

**Issue by mgedmin** [scrapy/scrapy#1515]
http://doc.scrapy.org/en/1.0/topics/link-extractors.html#module-scrapy.linkextractors.lxmlhtml says
![ekrano nuotrauka is 2015-09-29 11-04-14](https://cloud.githubusercontent.com/assets/159967/10158307/d8ec6250-6699-11e5-8660-d03e74b02db0.png)

It is unclear to me what "canonicalize" means.  This ought to be documented somewhere.

I initially tried to submit a pull request (#1514) to fix this, but it turns out to be more complicated than I expected.

**Comment by redapple** [comment]
This function has been moved to `w3lib.url` and [is documented there](https://w3lib.readthedocs.io/en/latest/w3lib.html#w3lib.url.canonicalize_url).

**Comment by mgedmin** [comment]
Thank you!
