### ISSUE TITLE
signals docs are confusing

### ISSUE THREAD

**Issue by kmike** [scrapy/scrapy#1521]
It seems it is not explained how to connect a callback to a singnal anywhere in Scrapy docs.

http://doc.scrapy.org/en/latest/topics/signals.html tells:

> You can connect to signals (or send your own) through the [Signals API](http://doc.scrapy.org/en/latest/topics/api.html#topics-api-signals).

But if you follow this link you get docs for scrapy.signalmanager.SignalManager - that's fine, but it is not explained where to get a SignalManager instance from.

There is an example in Extension docs (http://doc.scrapy.org/en/latest/topics/extensions.html#sample-extension), but

a) this is just an example;
b) it is not explained that crawler.signals is a SignalManager instance;
c) this example is neither in Signals docs nor in SignalManager docs.

There is also a bit of information here: http://doc.scrapy.org/en/latest/topics/api.html#scrapy.crawler.Crawler.signals, but

a) it is not linked to neither from Signal docs nor from SignalManager, so you can't find it if you don't know about it already;
b) it is not explained that crawler.signals is the only way to access signals.

So in the end users may get some luck connecting signals if they start from Crawler docs, but almost no luck if they start from Signals docs.

**Comment by darshanime** [comment]
Hey !
This is an excellent opportunity to get to know the signals API better. Expect a PR soon :)
