### ISSUE TITLE
Is there a way to yield all of my requests and save the responses so I can iterate through all of the responses at once.

### ISSUE THREAD

**Issue by sirskitzo** [scrapy/scrapy#1525]
This script finds all of the links on a website that match a certain keyword. If a URL is a match, I would like to yield a request and save the responses for each url. Once all of them have been crawled, I would then like to iterate through a dict, or list, of the responses and find the email and phone number that is used the most time throughout a website. I think I have it setup as I like, but the output is yielding an empty response each time.

Here is my attempt (Four methods; the remaining ones are just helpers): http://pastebin.com/wLb9FguG

This code works, but the response item is always from the previous website for some reason. I can't figure it out.

**Comment by kmike** [comment]
Could you please use stackoverflow.com (there is 'Scrapy' tag) or scrapy-users google group to ask usage questions?

**Comment by sirskitzo** [comment]
Thanks, I didn't know the best website for community support.
