### ISSUE TITLE
make Scrapy 1.1 release

### ISSUE THREAD

**Issue by kmike** [scrapy/scrapy#1529]
What about making a "boring" Scrapy 1.1 release, without much new features? User-facing improvements are small (deferreds in downloader middlewares, small scrapy shell improvements, AUTOTHROTTLE_TARGET_CONCURRENCY, docs improvements, loader.nested_xpath/nested_css, this kind of things), but internal changes are big: parsel, Python 3 porting progress. This makes backporting fixes to 1.0.x harder. By making 1.1 release we’ll be able to forget about 1.0.x codebase and let all the internal changes settle down.

**Comment by pablohoffman** [comment]
sounds good!. Make sure we release to conda as well @rolando

**Comment by eliasdorneles** [comment]
+1 to release often and in small steps. :+1:

**Comment by Digenis** [comment]
Will deprecated code keep being removed on every second release?
If so, maintainers of scrapy projects will have to spend more time testing updates
because skipping a release while upgrading
can change informative deprecation warnings into errors and failure to run.

I think the new release is a good chance for #1385.

**Comment by kmike** [comment]
@Digenis I think there is no need for aggressive removals of deprecated code. We definitely shouldn't remove code and modules deprecated in 0.24 during 1.1 release.

**Comment by kmike** [comment]
Backwards incompatible changes in master:

* https://github.com/scrapy/scrapy/issues/1550
* https://github.com/scrapy/scrapy/pull/1149
* https://github.com/scrapy/scrapy/pull/1289 (and https://github.com/scrapy/scrapy/pull/1530)

They are not that bad, but may break something for users.

**Comment by Digenis** [comment]
Although it's probably implied by the docs, since 1.1's release number is odd, it's an unstable release, right?
Is the API stability plan the same?
I see some outdate statements in the doc (eg "scrapy hasn't reached 1.0")

**Comment by kmike** [comment]
@Digenis that's a good question. Our options:

1. Release Scrapy 1.1 without these backwards incompatible changes, follow semver (create a branch, cherry-pick commits);
2. Declare 1.1 'unstable' (but I don't see a point of doint that);
3. Decide that these incompatibilities are in fact bug fixes and release 1.1 as-is (maybe without #1149).

What do you think?

"scrapy hasn't reached 1.0" is outdated (see https://github.com/scrapy/scrapy/pull/1541)

**Comment by redapple** [comment]
I'd go for 3. without #1149

**Comment by kmike** [comment]
i'm with @redapple on that

**Comment by curita** [comment]
I like option 3 too, I'm still unsure about #1149, but it's probably safer and less controversial to leave it to 2.0.

We have to document that we ditched the [old/even kernel versioning approach](https://en.wikipedia.org/wiki/Software_versioning#Odd-numbered_versions_for_development_releases) before releasing 1.1. If we're considering all the other tickets mentioned above as bugs we're sort of following semver now, we could mentioned it in the docs as well.

**Comment by chekunkov** [comment]
I'd go for 3 with:
- #1550 (#1498) 

IMO bringing other listed changes in minor update is bad idea as it can break Scrapy users production code. We can accumulate such changes and release major versions more often instead of preserving this magic `1.` at the begging and bringing incompatibilities in almost every minor release. BTW Scrapy instability is well known issue and it raises a lot of complaints. If it was more or less acceptable with `0.*` versions - now it wouldn't be so easy to explain why we are breaking backwards compatibility again.

**Comment by redapple** [comment]
https://github.com/scrapy/scrapy/pull/1533 doesn't seem that dangerous to include with proper notice

**Comment by kmike** [comment]
yeah, #1533 can be seen as a bug fix because a function worked not as documented

**Comment by rolando** [comment]
Btw, we are using `build_component_list` --which is very handy-- to build another kind of pipeline for our  project. So #1149 breaks our code and given we are using Scrapy Cloud, we are a bit worried about how to deal with that backwards incompatible so that all our jobs don't stop working overnight.

**Comment by chekunkov** [comment]
> yeah, #1533 can be seen as a bug fix because a function worked not as documented

ok, sounds reasonable

**Comment by kmike** [comment]
It is impossible to make releases which don’t break user code because users may rely on undocumented behaviour, on bugs, on private functions, this is too restrictive. I agree that we should think hard about backwards compatibility and keep such changes at minimum, doing deprecation cycles when necessary. 

I’d say we should keep settings changes out of release, do a deprecation cycle for 400 responses, fix a regression with local file names and then make a release.

**Comment by redapple** [comment]
@rolando , I think this is for Scrapy Cloud to worry, not to upgrade automatically. And that you have choice to upgrade or not. I'll raise that loud enough.

**Comment by bosbyj** [comment]
I sincerely hope that Scrapy 1.1 will have basic support for Python3.

**Comment by kmike** [comment]
@bosbyj good news is that two important modules are ported in Twisted trunk recently, we were not able to download pages via HTTP without these modules (i.e. port scrapy.core.downloader.handlers.http11). Bad news is that necessary Twisted changes are not yet released, and that we haven't made necessary Scrapy changes to use the updated Twisted code. So I'm not sure Scrapy will be usable in Python 3 in 1.1. release, but there is one less blocker in Twisted, so I think it is likely we'll have a basic Python 3 support (i.e. you can write a spider, crawl a website and use most of Scrapy components) by the end of the year.

Some parts of Scrapy are already usable in Python 3 - e.g. we extracted scrapy selectors to https://github.com/scrapy/parsel library which fully supports Python 3.

**Comment by redapple** [comment]
[Scrapy 1.1.0](https://pypi.python.org/pypi/Scrapy/1.1.0) has been released!

[Release notes](http://doc.scrapy.org/en/1.1/news.html).
