### ISSUE TITLE
remove --lsprof option and bundled lsprofcalltree.py library

### ISSUE THREAD

**Issue by kmike** [scrapy/scrapy#1531]
What about removing `--lsprof` option and the bundled [lsprofcalltree.py](https://github.com/scrapy/scrapy/blob/master/scrapy/xlib/lsprofcalltree.py) library? They are untested (see https://github.com/scrapy/scrapy/issues/1417), undocumented, don't work in Python 3, and there are easier to setup profiler UIs than KCacheGrind (e.g. https://github.com/jiffyclub/snakeviz) which work with .prof files directly.

I think we don't even have to deprecate it because removing this feature can't break user code.

**Comment by eliasdorneles** [comment]
:+1:
