### ISSUE TITLE
PY3 enable test_commands.ParseCommandTest

### ISSUE THREAD

**Issue by kmike** [scrapy/scrapy#1536]
Tests for 'parse' command are disabled in Python 3 because they require HTTP download handler in Python 3. See also: https://github.com/scrapy/scrapy/pull/1535, https://github.com/scrapy/scrapy/pull/1455.

**Comment by redapple** [comment]
@kmike , I believe tests for `parse` do now pass in Python (cf. https://github.com/scrapy/scrapy/pull/1678)

**Comment by kmike** [comment]
Ouch, I forgot about this ticket; tests are already enabled - see https://github.com/scrapy/scrapy/pull/1711.
