### ISSUE TITLE
Get "[scrapy] DEBUG: Redirecting (301)" ERROR, HOW TO FIX?

### ISSUE THREAD

**Issue by hellojammy** [scrapy/scrapy#1538]
2015-10-13 00:29:12 [scrapy] DEBUG: Redirecting (301) to < GET http://www.guokr.com/search/article/?&page=1&wd=china > from < GET http://guokr.com/search/article/?&page=1&wd=china >

You see, it was redirecting from one url to another url ,and they are the same!!  WHY??

I use a CustomUserAgentMiddleware to change the user-agent

**Comment by dangra** [comment]
it is not the same url, one has `www.` prefix in hostname. Please, use the forums when looking for help like this. Github Issue tracker is for bugs and new features.

**Comment by hellojammy** [comment]
thanks, it works. i will looking for help use forums next time.
