### ISSUE TITLE
ImportError: No module named scrapy

### ISSUE THREAD

**Issue by rylanchiu** [scrapy/scrapy#1540]
I installed the newest version of scrapy. But when I open the ipython and import the scrapy, an error occurs: ImportError: No module named scrapy. It seems that the scrapy can not be found. How can I solve this problem? Thank you very much!

**Comment by kmike** [comment]
I think this likely means you've installed Scrapy for one inetrpreter/environment, but trying to use it from another. To debug this issue print `sys.path` and check that Scrapy can be found there. It is also a good idea to use virtualenvs (note that both Scrapy and IPython should be installed in a virtualenv in this case). 

It doesn't look like a Scrapy issue, so I'm closing this ticket. Please use stackoverflow (with 'Scrapy' tag) or scrapy-users google group for support questions, and reopen this ticket if you think it is a Scrapy bug. Scrapy installation docs can be found here: http://doc.scrapy.org/en/master/intro/install.html

**Comment by rylanchiu** [comment]
I have read other's solutions and try to do it again. But another error occurs:

ImportError: cannot import name _monkeypatches

**Comment by rylanchiu** [comment]
Here is the code I try:

from twisted.internet import reactor
from scrapy.crawler import Crawler
from scrapy.settings import Settings
from scrapy import log
from testspiders.spiders.followall import FollowAllSpider

spider = FollowAllSpider(domain='scrapinghub.com')
crawler = Crawler(Settings())
crawler.configure()
crawler.crawl(spider)
crawler.start()
log.start()
reactor.run()

**Comment by rylanchiu** [comment]
And after I update jupyter in the virtualenv, the error shift to :  

ImportError: dlopen(/Users/lcc/news/lib/python2.7/site-packages/lxml/etree.so, 2): Library not loaded: libxml2.2.dylib
  Referenced from: /Users/lcc/news/lib/python2.7/site-packages/lxml/etree.so
  Reason: Incompatible library version: etree.so requires version 12.0.0 or later, but libxml2.2.dylib provides version 10.0.0

**Comment by kmike** [comment]
What is your OS?

**Comment by rylanchiu** [comment]
OS X 10.10.5

**Comment by rylanchiu** [comment]
I notice something tricky above. When I try to install lxml, it can be search in ./lib/python2.7/site-packages , but the lxml is required in Users/lcc/news/lib/python2.7/site-packages when running code. 
Actually there is a python installed by os x previously, while I also install one. Is it a reason? Thank you very much!

**Comment by curita** [comment]
Hi @rylanchiu, sorry to hear about the installation problems, seeing at that error message it looks like lxml was built with an older `libxml2` library. That's what most of StackOverflow questions regarding this problem seem to point out:
* https://stackoverflow.com/questions/13355984/get-errors-when-import-lxml-etree-to-python
* http://stackoverflow.com/questions/18486145/libxml2-2-dylib-reference-in-python-program
* http://stackoverflow.com/questions/23172384/lxml-runtime-error-reason-incompatible-library-version-etree-so-requires-vers

I *think* installing Scrapy following the new OS X installation section in the docs (http://doc.scrapy.org/en/master/intro/install.html#mac-os-x) should fix this problem, but if that's not the case let us know in #1482 so we can update it with a workaround for this issue!

**Comment by Mutnauq92** [comment]
> I installed the newest version of scrapy. But when I open the ipython and import the scrapy, an error occurs: ImportError: No module named scrapy. It seems that the scrapy can not be found. How can I solve this problem? Thank you very much!

On my machine I just chose the latest python interpreter in vs code and it solved the issue. I hope that helps
