### ISSUE TITLE
pip install Scrapy, no scrapy in Scripts

### ISSUE THREAD

**Issue by stcalica** [scrapy/scrapy#1542]
Having a problem doing this command: 

`python scrapy startproject foo `

get this error: 

`python: can't open file 'scrapy': [Errno 2] No such file or directory`

I looked in C:\Python27\Scripts and could not find scrapy file. Pip is not installing it right I believe. 

I uninstalled and installed and upgraded. Nothing works. 
I am on Windows 7 64-bit using python 2.7 

`C:\Users\kacalica>pip install scrapy
Requirement already satisfied (use --upgrade to upgrade): scrapy in c:\python27\
lib\site-packages
Requirement already satisfied (use --upgrade to upgrade): cssselect>=0.9 in c:\p
ython27\lib\site-packages (from scrapy)
Requirement already satisfied (use --upgrade to upgrade): queuelib in c:\python2
7\lib\site-packages (from scrapy)
Requirement already satisfied (use --upgrade to upgrade): pyOpenSSL in c:\python
27\lib\site-packages (from scrapy)
Requirement already satisfied (use --upgrade to upgrade): lxml in c:\python27\li
b\site-packages (from scrapy)
Requirement already satisfied (use --upgrade to upgrade): six>=1.5.2 in c:\pytho
n27\lib\site-packages (from scrapy)
Requirement already satisfied (use --upgrade to upgrade): w3lib>=1.2 in c:\pytho
n27\lib\site-packages (from scrapy)
Requirement already satisfied (use --upgrade to upgrade): Twisted>=10.0.0 in c:\
python27\lib\site-packages (from scrapy)
Requirement already satisfied (use --upgrade to upgrade): cryptography>=0.7 in c
:\python27\lib\site-packages (from pyOpenSSL->scrapy)
Requirement already satisfied (use --upgrade to upgrade): zope.interface>=3.6.0
in c:\python27\lib\site-packages (from Twisted>=10.0.0->scrapy)
Requirement already satisfied (use --upgrade to upgrade): setuptools in c:\pytho
n27\lib\site-packages (from cryptography>=0.7->pyOpenSSL->scrapy)
Requirement already satisfied (use --upgrade to upgrade): enum34 in c:\python27\
lib\site-packages (from cryptography>=0.7->pyOpenSSL->scrapy)
Requirement already satisfied (use --upgrade to upgrade): ipaddress in c:\python
27\lib\site-packages (from cryptography>=0.7->pyOpenSSL->scrapy)
Requirement already satisfied (use --upgrade to upgrade): pyasn1>=0.1.8 in c:\py
thon27\lib\site-packages (from cryptography>=0.7->pyOpenSSL->scrapy)
Requirement already satisfied (use --upgrade to upgrade): idna>=2.0 in c:\python
27\lib\site-packages (from cryptography>=0.7->pyOpenSSL->scrapy)
Requirement already satisfied (use --upgrade to upgrade): cffi>=1.1.0 in c:\pyth
on27\lib\site-packages (from cryptography>=0.7->pyOpenSSL->scrapy)
Requirement already satisfied (use --upgrade to upgrade): pycparser in c:\python
27\lib\site-packages (from cffi>=1.1.0->cryptography>=0.7->pyOpenSSL->scrapy)

C:\Users\kacalica>pip install -U scrapy
Collecting scrapy
  Using cached Scrapy-1.0.3-py2-none-any.whl
c:\python27\lib\site-packages\pip\_vendor\requests\packages\urllib3\util\ssl_.py
:90: InsecurePlatformWarning: A true SSLContext object is not available. This pr
events urllib3 from configuring SSL appropriately and may cause certain SSL conn
ections to fail. For more information, see https://urllib3.readthedocs.org/en/la
test/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Requirement already up-to-date: cssselect>=0.9 in c:\python27\lib\site-packages
(from scrapy)
Requirement already up-to-date: queuelib in c:\python27\lib\site-packages (from
scrapy)
Requirement already up-to-date: pyOpenSSL in c:\python27\lib\site-packages (from
 scrapy)
Requirement already up-to-date: w3lib>=1.8.0 in c:\python27\lib\site-packages (f
rom scrapy)
Requirement already up-to-date: lxml in c:\python27\lib\site-packages (from scra
py)
Requirement already up-to-date: Twisted>=10.0.0 in c:\python27\lib\site-packages
 (from scrapy)
Requirement already up-to-date: six>=1.5.2 in c:\python27\lib\site-packages (fro
m scrapy)
Requirement already up-to-date: service-identity in c:\python27\lib\site-package
s (from scrapy)
Requirement already up-to-date: cryptography>=0.7 in c:\python27\lib\site-packag
es (from pyOpenSSL->scrapy)
Requirement already up-to-date: zope.interface>=3.6.0 in c:\python27\lib\site-pa
ckages (from Twisted>=10.0.0->scrapy)
Requirement already up-to-date: characteristic>=14.0.0 in c:\python27\lib\site-p
ackages (from service-identity->scrapy)
Requirement already up-to-date: pyasn1-modules in c:\python27\lib\site-packages
(from service-identity->scrapy)
Requirement already up-to-date: pyasn1 in c:\python27\lib\site-packages (from se
rvice-identity->scrapy)
Collecting setuptools (from cryptography>=0.7->pyOpenSSL->scrapy)
  Downloading setuptools-18.4-py2.py3-none-any.whl (462kB)
    100% |################################| 462kB 999kB/s
Requirement already up-to-date: enum34 in c:\python27\lib\site-packages (from cr
yptography>=0.7->pyOpenSSL->scrapy)
Requirement already up-to-date: ipaddress in c:\python27\lib\site-packages (from
 cryptography>=0.7->pyOpenSSL->scrapy)
Requirement already up-to-date: idna>=2.0 in c:\python27\lib\site-packages (from
 cryptography>=0.7->pyOpenSSL->scrapy)
Requirement already up-to-date: cffi>=1.1.0 in c:\python27\lib\site-packages (fr
om cryptography>=0.7->pyOpenSSL->scrapy)
Requirement already up-to-date: pycparser in c:\python27\lib\site-packages (from
 cffi>=1.1.0->cryptography>=0.7->pyOpenSSL->scrapy)
Installing collected packages: scrapy, setuptools
  Found existing installation: Scrapy 0.25.1
    Uninstalling Scrapy-0.25.1:
      Successfully uninstalled Scrapy-0.25.1
  Found existing installation: setuptools 18.3.2
    Uninstalling setuptools-18.3.2:
      Successfully uninstalled setuptools-18.3.2
Successfully installed scrapy-1.0.3 setuptools-18.4

C:\Users\kacalica>python scrapy startproject foo
python: can't open file 'scrapy': [Errno 2] No such file or directory`

**Comment by kmike** [comment]
I don't know much about Windows, but can you try it without `python`, just `scrapy startproject foo`?

**Comment by stcalica** [comment]
wow it works! i feel like so dumb! 
Does pip add it to the path? I need to look that up, that was really cool actually. 
Thank you i'll close my issue.

**Comment by kmike** [comment]
Glad to hear it works! It should be setuptools who takes care of it; see https://github.com/scrapy/scrapy/pull/836.
