### ISSUE TITLE
scraping https via proxy: remove custom proxy headers after tunnel connection

### ISSUE THREAD

**Issue by hugojanruiter** [scrapy/scrapy#1543]
When using a proxy service for crawling an https site, the Proxy-authorization header gets removed after the initial HTTP CONNECT method to prevent it being forwarded to the target site in https://github.com/scrapy/scrapy/blob/master/scrapy/core/downloader/handlers/http11.py line 206:

```
if isinstance(agent, self._TunnelingAgent):
            headers.removeHeader('Proxy-Authorization')
```

Some proxy-services (eg. proxymesh.com) allow custom headers to be set (proxymesh: http://proxymesh.com/blog/pages/proxy-server-headers.html#request). If these headers will not be removed after the HTTP CONNECT they will be sent encrypted and the proxy service cannot remove them anymore and they are forwarded to the target site. To prevent these headers from being forwarded to the target site, it would be nice to have an option to remove these as well, similar to the Proxy-Authorization header. 

I am not sure what the best way would be, but maybe via request.meta (eg. 'dont_forward_headers_list')? Any suggestions?

**Comment by ryanchou1991** [comment]
+1 I have met the same issue. Does anybody could help us out this issue? I though it would be the general problem with scrapy by using the proxy to scrapy the https sites.

And also, If someone would like to inject some custom headers into https request. It would need to refactor the `download/handler/http11.py` implementations.

**Comment by Gallaecio** [comment]
Closing this in favor of https://github.com/scrapy/scrapy/issues/3329
