### ISSUE TITLE
scrapy startproject tutorial fails in Jupyter with "SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by datakid** [scrapy/scrapy#1546]
For some reason I could only get start project to work in cli, not in jupyter?

**Comment by kmike** [comment]
Could you please paste a traceback?

**Comment by kmike** [comment]
Note that you can't use most of Scrapy in a Jupyter notebook because Scrapy is based on Twisted and uses its own event loop. It is possible to make them work together better; it was one of GSoC [ideas](http://gsoc2015.scrapinghub.com/ideas/#iphyton-ide).

**Comment by redapple** [comment]
@datakid , are you still having the issue?
If so, please provide a traceback as @kmike requested.
Thanks.

**Comment by datakid** [comment]
Nope, all good now. Can't remember how I solved it - sorry. I think it was a post-upgrade issue that a reboot fixed?

**Comment by redapple** [comment]
Ok. I'm closing this issue for now.
Re-open if you stumble on it again.
Thanks.

**Comment by biigdata** [comment]
I had the same issue. The problem was that I was running the code in the Python interpreter, and this returns the SyntaxError. It this should be run as a shell command instead, so "!" need to be added before the command in Jupyter.
