### ISSUE TITLE
Failed to get a link the text of which matches my rules

### ISSUE THREAD

**Issue by hellojammy** [scrapy/scrapy#1547]
### My code : 

```
class SpiderLtuSpider(CrawlSpider):
    name = "spider_ltu"
    start_urls = []

    def __init__(self):
        self.start_urls.append("http://chuansong.me/account/lengtoo?start=0")
        self.rules = [ Rule(sle(allow=("http://chuansong.me/n/\d*.*", ), restrict_xpaths=('//a[@class="question_link"]'), ), callback='parse_article', ),]

```

### I want to get the link,  the text of which matches the regular expression(e.g.'Text*'). The first and the third one blow are what I want, and the second one should be excluded.
```
<a class="question_link" href="/n/1818306" target="_blank">Test_Ok hello</a> 
<a class="question_link" href="/n/1818306" target="_blank">AAA</a>
<a class="question_link" href="/n/1818306" target="_blank">Test ok</a>
```
### And I want to match the rules by the XPath `restrict_xpaths`. Would you please correct the code ? Thank you!

**Comment by nramirezuy** [comment]
Well you are misusing `CrawlSpider` rules are compiled on `__init__` and you are overriding it.

We try to keep Github just for real bugs. So for further support you can find me on the IRC channel, or you can try any of the other [ways of communication](http://doc.scrapy.org/en/latest/contributing.html#reporting-bugs).

**Comment by hellojammy** [comment]
thank you fro your helping.
