### ISSUE TITLE
use scrapy with celery producing incorrect log

### ISSUE THREAD

**Issue by night1008** [scrapy/scrapy#1549]
hello, I use scrapy with celery, and I have already config the scrapy and celery log level, for example, --loglevel=error, but it always produce the debug log to stdout or file, I look the source code, it come from the scrapy/scrapy/logformatter.py, it's not my want.Can you tell me what it happend?

**Comment by night1008** [comment]
Thanks for your reply!
The unexpected log in scrapy is all DEBUG level extist in scrapy/logformatter.py
LogFormatter.
My purpose is just that record the error or other log level what I want to logfile using spider with celery.
I user the ```logging.Logger.manager.loggerDict```, print all loggers.
Before invoke scrapy spider, it logs once, but after that, it logs twice, also in spider.
```
@task.task(bind=True)
def run_spider(self, **custom_config):
    logging.error('===== before spider')  
    process = CrawlerProcess(setting)
    process.crawl(Spider)
    process.start()
    logging.error('===== after spider')    
```
As above code, it will print '===== before spider' once and '===== after spider' twice.

**Comment by FlyingGlass** [comment]
i meet the same issue, how to set log level or close log when using spider with celery

**Comment by Gallaecio** [comment]
Use `CrawlRunner` instead. See https://docs.scrapy.org/en/latest/topics/practices.html#run-scrapy-from-a-script
