### ISSUE TITLE
How to create custom Scrapy Item Exporter?

### ISSUE THREAD

**Issue by bnussey** [scrapy/scrapy#1552]
I'm trying to create a custom Scrapy Item Exporter based off JsonLinesItemExporter so I can slightly alter the structure it produces.

I have read the documentation here http://doc.scrapy.org/en/latest/topics/exporters.html but it doesn't state how to create a custom exporter, where to store it or how to link it to your Pipeline.

I have identified how to go custom with the Feed Exporters but this is not going to suit my requirements, as I want to call this exporter from my Pipeline.

Here is the code I've come up with which has been stored in a file in the root of the project called `exporters.py`

	from scrapy.contrib.exporter import JsonLinesItemExporter

	class FanItemExporter(JsonLinesItemExporter):

	def __init__(self, file, **kwargs):
		self._configure(kwargs, dont_fail=True)
		self.file = file
		self.encoder = ScrapyJSONEncoder(**kwargs)
		self.first_item = True

	def start_exporting(self):
		self.file.write("""{
	'product': [""")

	def finish_exporting(self):
		self.file.write("]}")

	def export_item(self, item):
		if self.first_item:
			self.first_item = False
		else:
			self.file.write(',\n')
		itemdict = dict(self._get_serialized_fields(item))
		self.file.write(self.encoder.encode(itemdict))

I have simply tried calling this from my pipeline by using FanItemExporter and trying variations of the import but it's not resulting in anything.

**Comment by eliasdorneles** [comment]
So, these issues are meant for bugs about Scrapy.
Please use the community channels to ask for help about how to use Scrapy (mailing list: http://groups.google.com/group/scrapy-users Stackoverflow scrapy tag: http://stackoverflow.com/questions/tagged/scrapy)

About your question, exporters should not contain spider specific code -- if you want to aggregate all results in one object with a `product` list, you should process it in an ItemPipeline or a SpiderMiddleware and yield the data as you really want.
