### ISSUE TITLE
Crawl each host only N times

### ISSUE THREAD

**Issue by herkyl** [scrapy/scrapy#1553]
I'm using CrawlSpider to crawl the entire web looking for sites that use a certain script tag. I would like to limit the amount of requests Scrapy makes per host. Right now when I get stuck on something like FourSquare, Scrapy easily makes thousands of requests on the same host.

**Comment by eliasdorneles** [comment]
Please don't use the GitHub issues for help about how using Scrapy, the [community channels](http://scrapy.org/community/) work better for that, try asking in [Stackoverflow](http://stackoverflow.com/questions/tagged/scrapy) or in [scrapy-users](http://groups.google.com/group/scrapy-users) mailing list.

Scrapy doesn't have a built-in solution for your problem, you might be able to get away implementing a spider middleware that track requests domain and filter after arriving at a certain count.
You also may want consider looking into Frontera: http://frontera.readthedocs.org
