### ISSUE TITLE
`tox` tests fail

### ISSUE THREAD

**Issue by darshanime** [scrapy/scrapy#1556]
I tried running the tests for Scrapy using `$ tox` but I get a compilation error. [Here](https://gist.github.com/darshanime/7f6514961df666a95f05) is the log.

**Comment by jdemaeyer** [comment]
Hey @darshanime,

you need to install the header files of the `libffi` library (which is not a Python but a C package). Depending on your OS, there should be a `libffi-dev` or similar package available in your package manager. See also [here](https://github.com/SimonSapin/cairocffi/issues/14).

**Comment by darshanime** [comment]
Thanks for the tip @jdemaeyer, that almost solved my problem. 
I am able to run the tests, but all fail. 
`ImportError: cannot import name _monkeypatches`.

**Comment by jdemaeyer** [comment]
Hm, maybe [this](https://github.com/scrapy/scrapy/issues/1342) helps?

**Comment by jdemaeyer** [comment]
Could you verify that there is a file `scrapy/_monkeypatches.py` in the directory that you run `tox` from?

**Comment by darshanime** [comment]
Yup, there. 
`find . | grep _monkeypatches.py` at the root level dir gives me :
```python
./scrapy/_monkeypatches.pyc
./scrapy/_monkeypatches.py
./tests/test_urlparse_monkeypatches.pyc
./tests/test_urlparse_monkeypatches.py
./.tox/py27/lib/python2.7/site-packages/scrapy/_monkeypatches.pyc
./.tox/py27/lib/python2.7/site-packages/scrapy/_monkeypatches.py
```
I `cd`ed into `scrapy` and `tox`ed again, still the same error.

**Comment by jdemaeyer** [comment]
Hm, I don't have enough expertise with tox. It seems to me that it somehow doesn't use the repository `scrapy` module but the system-wide one. Could you please run `scrapy version` somewhere outside of the git repository? (Or, if that doesn't work, start a Python shell and run `import scrapy; print scrapy.version_info`)

**Comment by darshanime** [comment]
Scrapy 1.0.1 either ways.
Even if it uses the system wide module, shouldn't the tests pass ?
Also, how can I make it explicitly test the scrapy repository I just cloned ?

**Comment by kmike** [comment]
hey @darshanime - could you please pasten the updated log, after fixing libffi issue?

**Comment by kmike** [comment]
A similar issue: https://github.com/scrapy/scrapy/issues/1540

**Comment by jdemaeyer** [comment]
> Even if it uses the system wide module, shouldn't the tests pass ?

Yeah it should if you have 1.0.1. I just thought maybe you're having an old system-wide install (anaconda ships 0.24.x iirc) that it somehow uses.

> Also, how can I make it explicitly test the scrapy repository I just cloned ?

You shouldn't have to (it probably does).

I'm outta ideas here, sorry :/

**Comment by darshanime** [comment]
@jdemaeyer thanks for your help !

@kmike Here is the new [log](https://gist.github.com/darshanime/2c40da1408265c260b41)

**Comment by kmike** [comment]
The first log error is 
```
ERROR collecting scrapy/__init__.py
....
from operator import _compare_digest as compare_digest
ImportError: cannot import name _compare_digest
```

So it seems it is `scrapy.__init__.py` which can't be imported; `scrapy._monkeypatches` may be just a noise. Google reveals [this](http://stackoverflow.com/questions/26535043/python-flask-error-importerror-cannot-import-name-compare-digest) SO thread; it says this can happen if you've got a broken Python version with hmac module half-installed: you have Python 2.7.6, but hmac module from 2.7.7+. I'm not sure how can it happen, probably site-packages of several Python versions are in PYTHONPATH at the same time.

**Comment by darshanime** [comment]
@kmike, @jdemaeyer  got it working finally. 

I think this could be an error in the conda package management system. I created a fresh `conda` virtual environment, installed scrapy and ran the tests; same error. 
Then I created another virtual environment with my native python installation (not the Anaconda install) and used `virtualenv` to do it instead of `conda`. 

`virtualenv -p /usr/bin/python2.7 venv`

Installed scrapy in this, ran the tests; no error.

**Comment by kmike** [comment]
//cc @rolando (he's working on an official conda package for Scrapy)

**Comment by darshanime** [comment]
I also posted in the conda mailing group [here](https://groups.google.com/a/continuum.io/forum/#!topic/conda/YFvEKXrdY88).

**Comment by rolando** [comment]
@darshanime Could you share the output of `conda info`? Did you try updating conda and python? If not, try running: `conda update conda` and `conda update python`. Then you could try creating a new conda env.

**Comment by darshanime** [comment]
@rolando 
I ran `conda update conda` and `conda update python`, then created a virtualenv and ran `python setup.py install`.
I can now import scrapy successfully but cannot run the command line operations :
`$ python -c 'import scrapy` works, but :
`$ scrapy` gives me :

```python
(scrapy-dev)~/projects/scrapy$ scrapy
Traceback (most recent call last):
  File "/home/radar/anaconda/envs/scrapy-dev/bin/scrapy", line 9, in <module>
    load_entry_point('Scrapy==1.1.0.dev1', 'console_scripts', 'scrapy')()
  File "/home/radar/anaconda/envs/scrapy-dev/lib/python2.7/site-packages/Scrapy-1.1.0.dev1-py2.7.egg/scrapy/cmdline.py", line 122, in execute
    cmds = _get_commands_dict(settings, inproject)
  File "/home/radar/anaconda/envs/scrapy-dev/lib/python2.7/site-packages/Scrapy-1.1.0.dev1-py2.7.egg/scrapy/cmdline.py", line 46, in _get_commands_dict
    cmds = _get_commands_from_module('scrapy.commands', inproject)
  File "/home/radar/anaconda/envs/scrapy-dev/lib/python2.7/site-packages/Scrapy-1.1.0.dev1-py2.7.egg/scrapy/cmdline.py", line 29, in _get_commands_from_module
    for cmd in _iter_command_classes(module):
  File "/home/radar/anaconda/envs/scrapy-dev/lib/python2.7/site-packages/Scrapy-1.1.0.dev1-py2.7.egg/scrapy/cmdline.py", line 20, in _iter_command_classes
    for module in walk_modules(module_name):
  File "/home/radar/anaconda/envs/scrapy-dev/lib/python2.7/site-packages/Scrapy-1.1.0.dev1-py2.7.egg/scrapy/utils/misc.py", line 71, in walk_modules
    submod = import_module(fullpath)
  File "/home/radar/anaconda/envs/scrapy-dev/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/radar/anaconda/envs/scrapy-dev/lib/python2.7/site-packages/Scrapy-1.1.0.dev1-py2.7.egg/scrapy/commands/version.py", line 6, in <module>
    import OpenSSL
  File "build/bdist.linux-x86_64/egg/OpenSSL/__init__.py", line 8, in <module>
  File "build/bdist.linux-x86_64/egg/OpenSSL/rand.py", line 11, in <module>
  File "build/bdist.linux-x86_64/egg/OpenSSL/_util.py", line 6, in <module>
  File "/home/radar/anaconda/envs/scrapy-dev/lib/python2.7/site-packages/cryptography-1.0.2-py2.7-linux-x86_64.egg/cryptography/hazmat/bindings/openssl/binding.py", line 13, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: /home/radar/anaconda/envs/scrapy-dev/lib/python2.7/site-packages/cryptography-1.0.2-py2.7-linux-x86_64.egg/cryptography/hazmat/bindings/_openssl.so: undefined symbol: EC_GFp_nistp224_method
```
Here is `conda info` :
```python
(scrapy-dev)~/projects/scrapy$ conda info
Current conda install:

             platform : linux-64
        conda version : 3.18.3
  conda-build version : 1.8.2
       python version : 2.7.10.final.0
     requests version : 2.8.1
     root environment : /home/radar/anaconda  (writable)
  default environment : /home/radar/anaconda/envs/scrapy-dev
     envs directories : /home/radar/anaconda/envs
        package cache : /home/radar/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

**Comment by rolando** [comment]
@darshanime The `OpenSSL` lines in your traceback are a bit suspicious. Did you used `pip` to install scrapy and its dependencies? Installing packages that require compilation in `conda` via `pip` can cause problems sometimes.

Try: `conda create -n scrapy-env -c scrapinghub scrapy`

It will create a new conda environment `scrapy-env` (change the name if already exists) and install `scrapy` from the `scrapinghub` channel.

**Comment by darshanime** [comment]
@rolando, I did what you asked. Scrapy is installing fine but the tests are failing. Same error as earlier.
