### ISSUE TITLE
ImportError: No module named crawler

### ISSUE THREAD

**Issue by k287** [scrapy/scrapy#1557]
Hi,

I've written a python script were I'm trying to invoke scrapy but I keep getting an import error. 

I'm following this guide http://doc.scrapy.org/en/latest/topics/practices.html

The script is stored in the projects folder. 

Script:

"from scrapy.crawler import Crawler
from scrapy.crawler import CrawlerProcess
from scrapy.utils.project import get_project_settings

process = CrawlerProcess(get_project_settings())
process.crawl('linksspider', domain='scrapinghub.com')
process.start()"

Traceback:
Traceback (most recent call last):
  File "scrapy.py", line 3, in <module>
    from scrapy.crawler import Crawler
  File "......", line 3, in <module>
    from scrapy.crawler import Crawler
ImportError: No module named crawler

I can't find the answer on google/SA/Github.

Can anyone help?

Thanks

**Comment by kmike** [comment]
Do you have Scrapy installed, and if so what Scrapy version are you using? Check install instructions at at http://doc.scrapy.org/en/master/intro/install.html.

**Comment by k287** [comment]
I have version 1.0.3. I've been using scrapy by calling it from the terminal so it's definitely installed.

2015-10-26 23:37:18 [scrapy] INFO: Scrapy 1.0.3 started (bot: scrapybot)
2015-10-26 23:37:18 [scrapy] INFO: Optional features available: ssl, http11, boto
2015-10-26 23:37:18 [scrapy] INFO: Overridden settings: {}
Scrapy 1.0.3


sudo pip install scrapy
Requirement already satisfied (use --upgrade to upgrade): scrapy in /home/..../.local/lib/python2.7/site-packages
Cleaning up...

**Comment by kmike** [comment]
It is not a good practice to install Scrapy with sudo. Are you running your script with sudo as well? If not, you may be using another Python interpreter which doesn't have Scrapy available. Could you please paste the whole traceback?

**Comment by k287** [comment]
I wasn't running it with sudo. 

I've run 
sudo pip uninstall scrapy
Proceed (y/n)? y
  Successfully uninstalled Scrapy

However when I run pip install scrapy I get this error 

arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/libxml2 -I/tmp/pip-build-3ukllt/lxml/src/lxml/includes -I/usr/include/python2.7 -c src/lxml/lxml.etree.c -o build/temp.linux-armv7l-2.7/src/lxml/lxml.etree.o -w

arm-linux-gnueabihf-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-armv7l-2.7/src/lxml/lxml.etree.o -lxslt -lexslt -lxml2 -lz -lm -o build/lib.linux-armv7l-2.7/lxml/etree.so

/usr/bin/ld: cannot find -lz

collect2: error: ld returned 1 exit status

error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-3ukllt/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-ghr_bl-record/install-record.txt --single-version-externally-managed --compile --user failed with error code 1 in /tmp/pip-build-3ukllt/lxml
Storing debug log for failure in /home/matt/.pip/pip.log


Thanks

**Comment by k287** [comment]
Got it 
sudo apt-get install libz-dev
 
Then I had to run this after another error 

sudo apt-get install libssl-dev

**Comment by curita** [comment]
Hm, naming your script `scrapy.py` isn't the most sensible choice, it should be clashing with our scrapy, could you rename it (and delete its *.pyc file) and check again?

**Comment by kmike** [comment]
A good catch @curita, that's definitely one of the issues. 
@k287 packages required for Ubuntu/Debian are documented here: http://doc.scrapy.org/en/master/intro/install.html#ubuntu-9-10-or-above - do you think there is something missing? Or maybe we can improve this chapter to make it more clear how to install Scrapy - do you have any suggestions?

**Comment by k287** [comment]
It was because it was called scrapy.py. 

One last question then I'm done. In the following script how do you retrieve the items returned from the spider via the item pipeline?

from scrapy.crawler import CrawlerProcess
from scrapy.utils.project import get_project_settings
process = CrawlerProcess(get_project_settings())

# 'followall' is the name of one of the spiders of the project.
process.crawl('testspider', 'scrapinghub.com')
process.start() # the script will block here until the crawling is finished

Thanks again.

**Comment by jdemaeyer** [comment]
@k287 The preferred way to retrieve/process scraped items is to simply [create your own pipeline](http://doc.scrapy.org/en/latest/topics/item-pipeline.html) where you process the item. If for some reason you cannot or don't want to do that, you can hook to the [`item_scraped` signal](http://doc.scrapy.org/en/latest/topics/signals.html#scrapy.signals.item_scraped):
```python
from scrapy.signals import item_scraped

def my_callback_function(item, response, spider):
    # Processing here...
    pass

from scrapy.crawler import CrawlerProcess
from scrapy.utils.project import get_project_settings
process = CrawlerProcess(get_project_settings())

process.crawl('testspider', 'scrapinghub.com')

for crawler in process.crawlers:
    crawler.signals.connect(my_callback_function, item_scraped)

process.start() # the script will block here until the crawling is finished
```

Please keep in mind that this is not a support forum and these questions really should go to the [users mailing list](http://groups.google.com/group/scrapy-users) or [StackOverflow](http://stackoverflow.com/questions/tagged/scrapy). :)

**Comment by kmike** [comment]
There is also a discussion and examples in https://github.com/scrapy/scrapy/issues/1395. A standard approach is to do work in a pipeline, or (even better) just save the result to csv/json/jsonlines and process it in another script.

**Comment by Lovepankie** [comment]
Rename the script to something_else.py rather than calling it scrapy
