### ISSUE TITLE
AttributeError: 'Settings' object has no attribute 'update_settings'

### ISSUE THREAD

**Issue by k287** [scrapy/scrapy#1558]
Hi,

I'm trying to run a custom scrapy spider from a python script, however I can't figure out how to do this from the scrapy docs.

This page appears to be out of date otherwise it's in need of a few examples http://doc.scrapy.org/en/latest/topics/api.html?highlight=api

from spiders.scrapehomepagelinksspider import scrapehomepagelinksspider 
from scrapy.utils.project import get_project_settings
from scrapy.crawler import Crawler
from scrapy.xlib.pydispatch import dispatcher
from scrapy import signals
from twisted.internet import reactor

def stop_reactor():
    reactor.stop()

dispatcher.connect(stop_reactor, signal=signals.spider_closed)
settings = get_project_settings()
spider = scrapehomepagelinksspider('www.yahoo.com')
crawler = Crawler(settings)
crawler.crawl(spider)

links = reactor.run()
print links

Error

python scrapy1.py
Traceback (most recent call last):
  File "scrapy1.py", line 26, in <module>
    crawler = Crawler(settings)
  File "/home/matt/.local/lib/python2.7/site-packages/scrapy/crawler.py", line 32, in __init__
    self.spidercls.update_settings(self.settings)
AttributeError: 'Settings' object has no attribute 'update_settings'

Thanks

**Comment by jdemaeyer** [comment]
Hey @k287, please refer to [users mailing list](http://groups.google.com/group/scrapy-users) or [StackOverflow](http://stackoverflow.com/questions/tagged/scrapy) for these questions.

The signature for initialising crawlers is `Crawler(spidercls, settings)`, [see docs](http://doc.scrapy.org/en/latest/topics/api.html#scrapy.crawler.Crawler). I haven't looked too closely at your code but the lines in the middle should look more like this:
```python
dispatcher.connect(stop_reactor, signal=signals.spider_closed)
settings = get_project_settings()
crawler = Crawler(scrapehomepagelinksspider, settings)
crawler.crawl('www.yahoo.com')
```

**Comment by kmike** [comment]
As @jdemaeyer noted, the provided code example is not valid, so I'm closing this issue.
