### ISSUE TITLE
Access settings from feed storages

### ISSUE THREAD

**Issue by jersub** [scrapy/scrapy#1567]
Hi,

Feed storages should be able to access settings the new way.

For instance, `S3FeedStorage` uses both `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` from the settings. Currently they're gotten from `scrapy.conf` but this is now deprecated: this cause the build of PR #1559 to fail.

What about adding settings to the constructor of storages?

**Comment by kmike** [comment]
Sounds reasonable, +1.

An alternative is making them full-blown extensions with `from_crawler` method; I don't know what is better.

**Comment by jersub** [comment]
I haven't thought about extensions @kmike. It sounds like a better idea since it would provide additional flexibility i.e. connecting to signals. For instance, one would want to flush the file and push it as a part to S3 once the spider idle.

**Comment by jschilling1** [comment]
i reported a similar issue https://github.com/scrapy/scrapy/issues/1507

**Comment by kmike** [comment]
Fixed by #3348.
