### ISSUE TITLE
'module' object has no attribute 'Filed'

### ISSUE THREAD

**Issue by rylanchiu** [scrapy/scrapy#1573]
I am following the tutorial and when I ran the  scrapy crawl lyric_spider, there is an error:

AttributeError: 'module' object has no attribute 'Filed'

This is my items.py code:
import scrapy 
class LyricItem(scrapy.Item):
    singer = scrapy.Field()
    title = scrapy.Filed()
    publish_date = scrapy.Filed()
    word = scrapy.Filed()

And this is my lyric_spider:
import scrapy
from scrapy.spiders import CrawlSpider, Rule
from scrapy.linkextractor import LinkExtractor
from scrapy.selector import HtmlXPathSelector
from lyric.items import LyricItem

class LyricSpider(scrapy.Spider):
    name = "lyric_spider"
    allowed_domains = ["littleoslo.com"]
    start_urls = [
        "http://www.littleoslo.com/lyc/home/category/style/rap/"
    ]
    rules = (
        Rule(LinkExtractor(allow = (r'page/\d+')), follow = True),
    )
    
    
    
    def parse(self, response):
        for href in response.css("div > div > a::attr('href')"):
            url = response.urljoin(href.extract())
            yield scrapy.Request(url, callback = self.parse_dir_contents)
    
    def parse_dir_contents(self, response):
        for sel in response.xpath('//div/h3/a'):
            item = LyricItem()
            link = sel.xpath('@href').extract()
            yield item
       

And my directory is exactly as the tutorial and the version of scrapy is 1.0.3
Anyone can help me? Thanks a lot!!!

**Comment by kmike** [comment]
The proper name class name is 'Field', not 'Filed'.

**Comment by rylanchiu** [comment]
Found it already, very stupid mistake, thanks a lot. 
By the way, could you please help me with this? 
https://github.com/scrapy/scrapy/issues/1571
Tons of thanks!
