### ISSUE TITLE
Streaming request with subprocess calls in pipeline

### ISSUE THREAD

**Issue by ssbb** [scrapy/scrapy#1577]
Hi! 

I want to download first 100-200kb of file for each scraped item (normal size is much bigger) and run subprocess call. Now I have this logic (inside celery): downloading X bytes of file (with requests/urllib), call `ffprobe` via subprocess, stop if file can be parsed. If not - get more X bytes and check again... Loop here.

So what you think if I will move this logic to Scrapy pipeline? I will have blocks?

**Comment by nramirezuy** [comment]
@ssbb well it kinda depends on a lot of things. The simplest way would be to try it out based on the items per minute you have with and without the pipeline and seeing if is fast enough.

So, these issues are meant for bugs about Scrapy.
Please use the community channels to ask for help about how to use Scrapy (mailing list: http://groups.google.com/group/scrapy-users Stackoverflow scrapy tag: http://stackoverflow.com/questions/tagged/scrapy)
