### ISSUE TITLE
Implement a deprecation cycle for HTTP 400 responses handling

### ISSUE THREAD

**Issue by kmike** [scrapy/scrapy#1578]
https://github.com/scrapy/scrapy/pull/1289 (and https://github.com/scrapy/scrapy/pull/1530) are backwards-incompatible. Should we revert this change and implement it in a backwards-compatible way, with a deprecation cycle?

* revert default RETRY_HTTP_CODES to old value; 
* add RETRY_HTTP_CODES with new values to generated settings.py;
* raise a warning if users don’t have RETRY_HTTP_CODES in their settings.py files, saying the default value will change in future releases.

See also: https://github.com/scrapy/scrapy/issues/1529

**Comment by kmike** [comment]
I'm on fence on it now. With the proposed deprecation cycle users won't be able to e.g. use `CrawlerProcess()` without warnings. Isn't cure worse than a disease? According to the original docs, 400 status code was in RETRY_HTTP_CODES because some servers return 400 when they are overloaded. So after this change Scrapy won't retry request to some broken servers when they are overloaded, this is what backwards incompatible in this change. This change looks more like a bug fix to me.

**Comment by redapple** [comment]
@kmike , as per our dicsussion last week, I believe we can close this issue,
as long as not retrying HTTP 400 is properly announced in the 1.1 release notes.
