### ISSUE TITLE
Multiple crawls with the same crawler

### ISSUE THREAD

**Issue by jdemaeyer** [scrapy/scrapy#1587]
While we don't support using the same crawler for multiple spiders, it is currently possible to run the same crawler (with the same spider) twice, possibly with different spider arguments. I.e., this works:

``` python
crawler = Crawler(myspidercls)
crawler.crawl(my_sparg='blah')
crawler.crawl(my_sparg='other_blah')
```

This is done in some of our tests ([1](https://github.com/scrapy/scrapy/blob/master/tests/test_crawl.py#L63), [2](https://github.com/scrapy/scrapy/blob/master/tests/test_crawl.py#L132), [3](https://github.com/scrapy/scrapy/blob/master/tests/test_downloader_handlers.py#L299)). Are these tests legacy code or is support for multiple crawls part of the public API (see also [this discussion](https://github.com/scrapy/scrapy/pull/1580#issuecomment-154209093))?

**Comment by nramirezuy** [comment]
@jdemaeyer pretty sure is legacy code. We should remove those tests to avoid confusion.

**Comment by wRAR** [comment]
I think we can deprecate running crawl() for the second time after the first one finishes (they can't be run concurrently already).

As for tests I'm sure it's just a shortcut, not something written explicitly.
