### ISSUE TITLE
How to package scrapy program

### ISSUE THREAD

**Issue by LinkZhang** [scrapy/scrapy#1589]
I used scrapy to write a spider,now I want to run in server,so I use pyinstaller to package it.I add a setup.py
````python
from scrapy import cmdline
cmdline.execute("scrapy crawl Spiderl".split())
````
use
````shell
pyinstaller -F setup.py
````
succeed get a exe,but run it get a error "Unknown command: crawl". the document said "crawl must run in the root of project directory". So how can I package a scrapy-program with out copy the source code of project to server

**Comment by LinkZhang** [comment]
I get an answer for http://doc.scrapy.org/en/1.0/topics/practices.html#run-from-script and package it use the same command but get an error:"ImportError: No module named spiderloader"
````python
from scrapy.crawler import CrawlerProcess

from FishCrawl.spiders.FishSpider import FishSpider



spider = FishSpider()
process = CrawlerProcess({
    'USER_AGENT': 'Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1)'
})

process.crawl(spider)
process.start()
````

**Comment by kmike** [comment]
@LinkZhang could you please paste a full traceback?

**Comment by redapple** [comment]
@LinkZhang , are you still having this issue?
If yes, can you provide a full traceback as @kmike requested?
Thanks.

**Comment by LinkZhang** [comment]
@kmike @redapple sorry, I used requests+lxml to rewrite this crawl.

**Comment by Digenis** [comment]
@LinkZhang, the issue tracker is used for reporting bugs or requesting features in order to improve scrapy itself, not support. Even if you use-case was unique, this issue is not only for support.
The developers responded because they are willing to fix this for everyone having this issue,
so please don't close it just because you are no longer interested in scrapy+pyinstaller.
If you still have your project's code laying around, you are still invited to contribute by posting the traceback and providing more information like your environment, OS or any parts of the code you can share etc.

**Comment by WuQianyong** [comment]
@Digenis  I have same issue  of scrapy+pyinstaller,my environment is  python3.5 +windows10 +scarpy1.2.1

This is my code of run my spiders:
```




# import sys
from vsatZJLX.spiders.eastZJLXspider import zjlxgg

from vsatZJLX.spiders.eastZJLX_HY_spider import zjlx_hy_spider
from vsatZJLX.spiders.eastZJLX_DP_spider import Zjlx_dp_spider
from scrapy.utils.project import get_project_settings
import os
import time
import scrapy
from scrapy.crawler import CrawlerProcess
import  logging
import datetime



LOG_FILE=os.getcwd()+"\\vsatZJLX\\LOG_FILE\\" + time.strftime("%Y%m%d%H%M%S",time.localtime())+'.log'

def main():
    process=CrawlerProcess()
    process.settings=get_project_settings()
    process.crawl(zjlxgg)                                               # my first spider
    process.crawl(zjlx_hy_spider)                                   # second spider
    process.crawl(Zjlx_dp_spider)                                  #third spider
    process.start()

def main_log():
    nowDate_last = datetime.date.today() - datetime.timedelta(days=2)
    delDay = str(nowDate_last).replace("-","")
    # print(os.getcwd())
    if (os.access(os.getcwd() + '\\vsatZJLX\\LOG_FILE', os.F_OK ) == True or os.path.isdir(os.getcwd() + '\\vsatZJLX\\LOG_FILE') == True):
        for ss in os.walk(os.getcwd() + "\\vsatZJLX\\LOG_FILE"):
            i = 0

            for aa in ss:
                if i == 2:
                    for bb in aa:
                        ss = bb.replace(".log", "")
                        # print(ss)
                        if ss < delDay:
                            os.remove(os.getcwd() + "\\vsatZJLX\\Log_File\\" + ss + ".log")
                            # print('remove file')
                            # print(ss)
                i = i + 1
      


if __name__=="__main__":
    logging.basicConfig(level=logging.INFO,
              format='%(asctime)s %(name)-12s %(levelname)-8s %(message)s',
              datefmt='%m-%d %H:%M:%S',
              filename=LOG_FILE,


              filemode='w')

    try:
        start_time=time.strftime("%Y-%m-%d %H:%M:%S",time.localtime())
        main()
        main_log()
        end_time=time.strftime("%Y-%m-%d %H:%M:%S",time.localtime())

    except:
        logging.exception("Unknow errors")
        
Please you help me 



























```

**Comment by redapple** [comment]
@WuQianyong , python3.5 +windows10 +scarpy1.2.1 is not currently supported (Twisted does not support Python 3 on Windows, and lxml sometimes fails installing on Windows)
You can still provide a traceback of the packaging command you use in order to confirm or infirm this.

**Comment by TheGlow666** [comment]
I have exaclty the same problem. Running Windows10, Python 2.7, latest scrapy and getting this error when trying to run bundled spider: "ImportError: No module named spiderloader"

**Comment by redapple** [comment]
@TheGlow666 , how did you install Scrapy? (note: the recommended for Windows is Anaconda)
Do other scrapy commands work? (like `scrapy version -v` or `scrapy startproject`)

**Comment by TheGlow666** [comment]
I installed scrapy via Anaconda. Yes other commands work. Also same error on Windows8

**Comment by LeslieM95** [comment]
I made it! PyInstaller packages scrapy spider on Windows7 successfully.

**Comment by Caleb-Wade** [comment]
@LeslieM95 Excuse me, Could you tell me how di you make it on Windows7. I failed in python3.4 +windows7 +scarpy1.4.0. I tried lots of methods, but none of them worked. Even I wrote --hidden-import to add missing packages in my bundled exe. I really felt confused. Pls help me ,thanks.

**Comment by ArunAug** [comment]
I have faced the same issue, adding that scrapy package in to the disc folder solves the issue for me.
but while creating single executable using --onefile it still shows 
 "ImportError: No module named spiderloader" error ?

Can anyone has any update on this ? thanks

**Comment by GeorgeA92** [comment]
According to recent stackoverflow question [How to create a single executable file in windows 10 with scrapy and pyinstaller?](https://stackoverflow.com/questions/55331478/how-to-create-a-single-executable-file-in-windows-10-with-scrapy-and-pyinstaller/)
The `ImportError: No module named spiderloader` error can be solved by adding 40+ hidden imports of scrapy submodules.

**Comment by ArunAug** [comment]
Fixed.
https://stackoverflow.com/questions/55331478/how-to-create-a-single-executable-file-in-windows-10-with-scrapy-and-pyinstaller/55410079#55410079
