### ISSUE TITLE
Document LOG_UNSERIALIZABLE_REQUESTS setting

### ISSUE THREAD

**Issue by curita** [scrapy/scrapy#1592]
It's implemented in [scrapy/core/scheduler.py#L31](https://github.com/scrapy/scrapy/blob/master/scrapy/core/scheduler.py#L31) and not mentioned anywhere in docs. I think it's really useful, could be mentioned at least in http://scrapy.readthedocs.org/en/latest/topics/jobs.html#request-serialization.

Since it isn't documented we could take the chance and rename it as well, this kind of settings are usually named `<something>_DEBUG`.

**Comment by darshanime** [comment]
Hi !

How about adding this comment [here](http://scrapy.readthedocs.org/en/latest/topics/jobs.html#request-serialization) :
`If you wish to log the requests that couldn't be serialized, you can enable the `**`LOG_UNSERIALIZABLE_REQUESTS`** `by setting it to True in the project's settings page. It is` **`False`**` by default.`

How about renaming this setting to `UNSERIALIZABLE_REQUESTS_DEBUG` in the spirit of settings like `AUTOTHROTTLE_DEBUG`,`COOKIES_DEBUG` ?

**Comment by curita** [comment]
@darshanime both suggestions sound good to me :) I'd add that we should mention this setting in the builtin settings list here: http://scrapy.readthedocs.org/en/latest/topics/settings.html#built-in-settings-reference as well.

Could you help us with a pull request with those changes? I'll gladly review it when you submit it.

**Comment by darshanime** [comment]
Sure.

**Comment by nramirezuy** [comment]
Isn't this option a `SCHEDULER_DEBUG`?

**Comment by nramirezuy** [comment]
I would also change it to log once and save stats. Similar to dedupe filter.
