### ISSUE TITLE
Fix REDIRECT_PRIORITY_ADJUST docs

### ISSUE THREAD

**Issue by curita** [scrapy/scrapy#1593]
Not sure about it, but what's explained here: http://scrapy.readthedocs.org/en/latest/topics/settings.html#redirect-priority-adjust about priorities seems wrong, priorities in requests work the other way around (higher priority executes first), so a negative adjust would meant to decrease the original request priority to execute the redirect later.

By all means if this isn't the case, some note about why it seems to contradict what it is said about priorities in http://scrapy.readthedocs.org/en/latest/topics/request-response.html#request-objects would be helpful, got really confused there :(

**Comment by nramirezuy** [comment]
@curita Is a negative priority adjust of `+2` :sheep: (the text is wrong)

I guess this one is missing on the docs [`RETRY_PRIORITY_ADJUST`](https://github.com/scrapy/scrapy/blob/master/scrapy/settings/default_settings.py#L222).

**Comment by redapple** [comment]
@curita , @nramirezuy , would #1727 work?
