### ISSUE TITLE
scrapy not printing out stacktrace on exception

### ISSUE THREAD

**Issue by somghosh** [scrapy/scrapy#1602]
Is there a special mechanism to force scrapy to print out all python exception/stacktrace. (i put the question here as well: http://stackoverflow.com/questions/33725800/scrapy-not-printing-out-stacktrace-on-exception)

I made a simple mistake of getting a list attribute wrong resulting in AttributeError which did not show up in full in the logs
What showed up was :

	2015-11-15 22:13:50 [scrapy] INFO: Dumping Scrapy stats:
	{'downloader/request_bytes': 264,
	 'downloader/request_count': 1,
	 'downloader/request_method_count/GET': 1,
	 'downloader/response_bytes': 40342,
	 'downloader/response_count': 1,
	 'downloader/response_status_count/200': 1,
	 'finish_reason': 'finished',
	 'finish_time': datetime.datetime(2015, 11, 15, 22, 13, 50, 860480),
	 'log_count/CRITICAL': 1,
	 'log_count/DEBUG': 1,
	 'log_count/INFO': 1,
	 'response_received_count': 1,
	 'scheduler/dequeued': 1,
	 'scheduler/dequeued/memory': 1,
	 'scheduler/enqueued': 1,
	 'scheduler/enqueued/memory': 1,
	 'spider_exceptions/AttributeError': 1,
	 'start_time': datetime.datetime(2015, 11, 15, 22, 13, 49, 222371)}

So it showed the AttributeError count of 1, but didnt tell me where and how, I had to manually place ipdb.set_trace() in code to find out where it got an error. Scrapy by itself continued to carry out other threads without printing anything

	ipdb>
	AttributeError: "'list' object has no attribute 'match'"
	> /Users/username/Programming/regent/regentscraper/spiders/regent_spider.py(139)request_listing_detail_pages_from_listing_id_list()
	    138             volatile_props = ListingScanVolatilePropertiesItem()
	--> 139             volatile_props['position_in_search'] = list_of_listing_ids.match(listing_id) + rank_of_first_item_in_page
	    140

### scrapy settings

    # -*- coding: utf-8 -*-
    
    # Scrapy settings for regentscraper project
    #
    # For simplicity, this file contains only settings considered important or
    # commonly used. You can find more settings consulting the documentation:
    #
    #     http://doc.scrapy.org/en/latest/topics/settings.html
    #     http://scrapy.readthedocs.org/en/latest/topics/downloader-middleware.html
    #     http://scrapy.readthedocs.org/en/latest/topics/spider-middleware.html
    
    import sys
    import os
    import django
    sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__name__), os.pardir)))
    
    print sys.path
    
    os.environ['DJANGO_SETTINGS_MODULE'] = 'regent.settings'
    django.setup()  #new for Django 1.8
    
    
    
    BOT_NAME = 'regentscraper'
    
    SPIDER_MODULES = ['regentscraper.spiders']
    NEWSPIDER_MODULE = 'regentscraper.spiders'
    
    
    ITEM_PIPELINES = {
       'regentscraper.pipelines.ListingScanPipeline': 300,
    }

**Comment by nramirezuy** [comment]
@somghosh do you have errback implemented?

**Comment by jdemaeyer** [comment]
Update from the StackOverflow question:
> I have pinpointed it to the following line in settings file (I need it because I am using Django 1.8) - django.setup() #new for Django 1.8 --- removing this line starts logging the tracebacks - not sure why

So I guess it's related to how Django sets up its logging? [See Django's default logging configuration.](https://docs.djangoproject.com/en/1.8/topics/logging/#django-s-default-logging-configuration)

**Comment by redapple** [comment]
@somghosh , I'm closing this issue as it looks to be a Django issue/misconfiguration.
Feel free to re-open if you disagree.
