### ISSUE TITLE
Deprecating `from_settings()` constructors

### ISSUE THREAD

**Issue by jdemaeyer** [scrapy/scrapy#1613]
Outsourcing a discussion from #1605 here: Should `from_settings()` constructors in pipelines/extensions/middlewares be deprecated?

With the exception of spider loaders, Scrapy only instantiates components when the crawler object is already available. `from_settings()` constructors are not really documented, besides for the spider loader API and the [MailSender extension](http://doc.scrapy.org/en/latest/topics/email.html?highlight=from_settings), and their support is inconsistent (e.g. spiders cannot provide `from_settings()` constructors).

Are there use cases where middlewares etc. need to be instantiated with settings, but without a crawler?

**Comment by kmike** [comment]
I think consistency is less of an issue now, as we now have a single helper to create Scrapy components; it can be good to check from_crawler usages and replace them with create_instance. MailSender may get from_crawler support in https://github.com/scrapy/scrapy/pull/3346. `from_settings` doesn't look that useful to me, but at the same time there is no much incentive to remove it - it looks easy to support, and dropping it would require thinking hard about backwards compatibility.

**Comment by kmike** [comment]
I'm closing this issue, because it is not clear what to do here. If someone disagrees, feel free to reopen!
