### ISSUE TITLE
Scrapy 1.0: How to run crawler in Celery?

### ISSUE THREAD

**Issue by imWildCat** [scrapy/scrapy#1647]
I've posted a question on StackOverFlow but there is no answer:
http://stackoverflow.com/questions/34065315/scrapy-1-0-how-to-run-crawler-in-celery

> I tried the sample from document http://doc.scrapy.org/en/stable/topics/practices.html, but there would be an error ReactorNotRestartable while running it a second time.

```python
settings = get_project_settings()

runner = CrawlerRunner(settings=settings)

@defer.inlineCallbacks
def crawl():
    yield runner.crawl(LatestNewsSpider)
    reactor.stop()

def run_spider():
    crawl()
    reactor.run()
```

**Comment by kmike** [comment]
Hey @imWildCat - it looks like the question is already answered at stackoverflow.
Why do you want to run Scrapy in Celery?
