### ISSUE TITLE
parcing fail

### ISSUE THREAD

**Issue by Anlight** [scrapy/scrapy#1648]
It does not collect data from the title

toster.py:
from scrapy.contrib.spiders import CrawlSpider, Rule
from scrapy.contrib.linkextractors import LinkExtractor
from toster.items import DjangoItem

class DjangoSpider(CrawlSpider):
    name = "django"
    allowed_domains = ["www.toster.ru"]
    start_urls = [
        'http://www.toster.ru/tag/django/questions',
    ]

    rules = [
    	Rule(LinkExtractor(
    		allow=['/tag/django/questions\?page=\d']),
    		callback='parse_item',
    		follow=True)
    ]

    def parse_item(self, response):
        
        selector_list = response.css('div.thing')

        for selector in selector_list:
        	item = DjangoItem()
        	item['title'] = selector.xpath('div/h2/a/text()').extract()
        	# item['url'] = selector.xpath('a/@href').extract()

        	yield item

item:

from scrapy import Field, Item

class DjangoItem(Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    title = Field()
    # url = Field()

**Comment by kmike** [comment]
Hey @Anlight,

Please use http://stackoverflow.com (with tag [scrapy](http://stackoverflow.com/questions/tagged/scrapy)) or scrapy-users Google group (less popular) for support questions.
