### ISSUE TITLE
response.xpath may not work  in scrapy shell

### ISSUE THREAD

**Issue by yuiopt** [scrapy/scrapy#1650]
scrapy shell http://huaban.com/favorite/photography/

tested xpath :
response.xpath('//div[@id="page"]/div[@class="wrapper"]')
but got an empty list

![image](https://cloud.githubusercontent.com/assets/9608805/12029220/6121df2e-ae20-11e5-81ef-acd069415208.png)

**Comment by redapple** [comment]
It looks to me that these HTML elements are generated by some Javascript code, and Scrapy does not interpret Javascript (you can still parse the Javascript data using something like [js2xml](https://pypi.python.org/pypi/js2xml) though).
Not a Scrapy bug, better suited for the [scrapy-users mailing list](https://groups.google.com/forum/#!forum/scrapy-users) or StackOverflow with tag "scrapy"

**Comment by yuiopt** [comment]
Ok,Thank you very much,I'll try js2xml instead
