### ISSUE TITLE
CLOSESPIDER_PAGECOUNT don't work as should

### ISSUE THREAD

**Issue by aktywnitu** [scrapy/scrapy#1651]
I use scrapy 1.0.3 and can't discover how works CLOSESPIDER extesnion.
For command:
scrapy crawl domain_links --set=CLOSESPIDER_PAGECOUNT=1
is correctly one requst, but for two pages count:
scrapy crawl domain_links --set CLOSESPIDER_PAGECOUNT=2
is infinity of requests.

So please explain me how it works in simple example.

This is my spider code:

```
class DomainLinksSpider(CrawlSpider):
    name = "domain_links"
    #allowed_domains = ["www.example.org"]
    start_urls = [ "www.example.org/",]

    rules = (

        # Extract links matching 'item.php' and parse them with the spider's method parse_item
        Rule(LinkExtractor(allow_domains="www.example.org"), callback='parse_page'),
    )

    def parse_page(self, response):
        print '<<<',response.url
        items = []
        item = PathsSpiderItem()

        selected_links = response.selector.xpath('//a[@href]')

        for link in LinkExtractor(allow_domains="www.example.org", unique=True).extract_links(response):
            item = PathsSpiderItem()
            item['url'] = link.url
            items.append(item)
        return items
```

**Comment by aktywnitu** [comment]
For CONCURRENT_REQUESTS = 1, CLOSESPIDER_PAGECOUNT settings works.
So guys, it will be better to add this info to CloseSpider documentation.

**Comment by GeorgeA92** [comment]
As this part of Closespider extension already covered in docs as result of https://github.com/scrapy/scrapy/pull/4836 - I propose to close this
