### ISSUE TITLE
Segfault on a fresh scrapy installation

### ISSUE THREAD

**Issue by DenJohX** [scrapy/scrapy#1653]
I'm on a Debian Testing machine, using a fresh virtualenv and a fresh install of scrapy it seems to install without errors, but it cannot be started  just ends in a segmentation fault.

    $ pip install scrapy
    
    Downloading/unpacking scrapy
      Downloading Scrapy-1.0.3-py2-none-any.whl (290kB): 290kB downloaded
    Downloading/unpacking cssselect>=0.9 (from scrapy)
      Downloading cssselect-0.9.1.tar.gz
      Running setup.py (path:/tmp/pip-build-wx54VN/cssselect/setup.py) egg_info for package cssselect
        
        no previously-included directories found matching 'docs/_build'
    Downloading/unpacking queuelib (from scrapy)
      Downloading queuelib-1.4.2-py2.py3-none-any.whl
    Downloading/unpacking pyOpenSSL (from scrapy)
      Downloading pyOpenSSL-0.15.1-py2.py3-none-any.whl (102kB): 102kB downloaded
    Downloading/unpacking w3lib>=1.8.0 (from scrapy)
      Downloading w3lib-1.13.0-py2.py3-none-any.whl
    Downloading/unpacking lxml (from scrapy)
      Downloading lxml-3.5.0.tar.gz (3.8MB): 3.8MB downloaded
      Running setup.py (path:/tmp/pip-build-wx54VN/lxml/setup.py) egg_info for package lxml
        Building lxml version 3.5.0.
        Building without Cython.
        Using build configuration of libxslt 1.1.28
        
        warning: no previously-included files found matching '*.py'
    Downloading/unpacking Twisted>=10.0.0 (from scrapy)
      Downloading Twisted-15.5.0.tar.bz2 (3.1MB): 3.1MB downloaded
      Running setup.py (path:/tmp/pip-build-wx54VN/Twisted/setup.py) egg_info for package Twisted
        
    Downloading/unpacking six>=1.5.2 (from scrapy)
      Downloading six-1.10.0-py2.py3-none-any.whl
    Downloading/unpacking service-identity (from scrapy)
      Downloading service_identity-14.0.0-py2.py3-none-any.whl
    Downloading/unpacking cryptography>=0.7 (from pyOpenSSL->scrapy)
      Downloading cryptography-1.1.2.tar.gz (349kB): 349kB downloaded
      Running setup.py (path:/tmp/pip-build-wx54VN/cryptography/setup.py) egg_info for package cryptography
        
        no previously-included directories found matching 'docs/_build'
        warning: no previously-included files matching '*' found under directory 'vectors'
    Downloading/unpacking zope.interface>=3.6.0 (from Twisted>=10.0.0->scrapy)
      Downloading zope.interface-4.1.3.tar.gz (141kB): 141kB downloaded
      Running setup.py (path:/tmp/pip-build-wx54VN/zope.interface/setup.py) egg_info for package zope.interface
        
        warning: no previously-included files matching '*.dll' found anywhere in distribution
        warning: no previously-included files matching '*.pyc' found anywhere in distribution
        warning: no previously-included files matching '*.pyo' found anywhere in distribution
        warning: no previously-included files matching '*.so' found anywhere in distribution
        warning: no previously-included files matching 'coverage.xml' found anywhere in distribution
        no previously-included directories found matching 'docs/_build'
    Downloading/unpacking characteristic>=14.0.0 (from service-identity->scrapy)
      Downloading characteristic-14.3.0-py2.py3-none-any.whl
    Downloading/unpacking pyasn1-modules (from service-identity->scrapy)
      Downloading pyasn1_modules-0.0.8-py2.py3-none-any.whl
    Downloading/unpacking pyasn1 (from service-identity->scrapy)
      Downloading pyasn1-0.1.9-py2.py3-none-any.whl
    Downloading/unpacking idna>=2.0 (from cryptography>=0.7->pyOpenSSL->scrapy)
      Downloading idna-2.0-py2.py3-none-any.whl (61kB): 61kB downloaded
    Requirement already satisfied (use --upgrade to upgrade): setuptools in /home/dennis/.virtualenvs/scraper/lib/python2.7/site-packages (from cryptography>=0.7->pyOpenSSL->scrapy)
    Downloading/unpacking enum34 (from cryptography>=0.7->pyOpenSSL->scrapy)
      Downloading enum34-1.1.2.tar.gz (46kB): 46kB downloaded
      Running setup.py (path:/tmp/pip-build-wx54VN/enum34/setup.py) egg_info for package enum34
        
    Downloading/unpacking ipaddress (from cryptography>=0.7->pyOpenSSL->scrapy)
      Downloading ipaddress-1.0.16-py27-none-any.whl
    Downloading/unpacking cffi>=1.1.0 (from cryptography>=0.7->pyOpenSSL->scrapy)
      Downloading cffi-1.4.2.tar.gz (365kB): 365kB downloaded
      Running setup.py (path:/tmp/pip-build-wx54VN/cffi/setup.py) egg_info for package cffi
        
    Downloading/unpacking pycparser (from cffi>=1.1.0->cryptography>=0.7->pyOpenSSL->scrapy)
      Downloading pycparser-2.14.tar.gz (223kB): 223kB downloaded
      Running setup.py (path:/tmp/pip-build-wx54VN/pycparser/setup.py) egg_info for package pycparser
        
        warning: no previously-included files matching 'yacctab.*' found under directory 'tests'
        warning: no previously-included files matching 'lextab.*' found under directory 'tests'
        warning: no previously-included files matching 'yacctab.*' found under directory 'examples'
        warning: no previously-included files matching 'lextab.*' found under directory 'examples'
    Installing collected packages: scrapy, cssselect, queuelib, pyOpenSSL, w3lib, lxml, Twisted, six, service-identity, cryptography, zope.interface, characteristic, pyasn1-modules, pyasn1, idna, enum34, ipaddress, cffi, pycparser
      Running setup.py install for cssselect
        
        no previously-included directories found matching 'docs/_build'
      Running setup.py install for lxml
        Building lxml version 3.5.0.
        Building without Cython.
        Using build configuration of libxslt 1.1.28
        building 'lxml.etree' extension
        x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/libxml2 -Isrc/lxml/includes -I/usr/include/python2.7 -c src/lxml/lxml.etree.c -o build/temp.linux-x86_64-2.7/src/lxml/lxml.etree.o -w
        x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/src/lxml/lxml.etree.o -lxslt -lexslt -lxml2 -lz -lm -o build/lib.linux-x86_64-2.7/lxml/etree.so
        building 'lxml.objectify' extension
        x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/libxml2 -Isrc/lxml/includes -I/usr/include/python2.7 -c src/lxml/lxml.objectify.c -o build/temp.linux-x86_64-2.7/src/lxml/lxml.objectify.o -w
        x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/src/lxml/lxml.objectify.o -lxslt -lexslt -lxml2 -lz -lm -o build/lib.linux-x86_64-2.7/lxml/objectify.so
        
      Running setup.py install for Twisted
        
        x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c conftest.c -o conftest.o
        building 'twisted.test.raiser' extension
        x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c twisted/test/raiser.c -o build/temp.linux-x86_64-2.7/twisted/test/raiser.o
        x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/twisted/test/raiser.o -o build/lib.linux-x86_64-2.7/twisted/test/raiser.so
        building 'twisted.python._sendmsg' extension
        x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c twisted/python/_sendmsg.c -o build/temp.linux-x86_64-2.7/twisted/python/_sendmsg.o
        x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/twisted/python/_sendmsg.o -o build/lib.linux-x86_64-2.7/twisted/python/_sendmsg.so
        building 'twisted.runner.portmap' extension
        x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c twisted/runner/portmap.c -o build/temp.linux-x86_64-2.7/twisted/runner/portmap.o
        x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/twisted/runner/portmap.o -o build/lib.linux-x86_64-2.7/twisted/runner/portmap.so
        changing mode of build/scripts-2.7/mailmail from 644 to 755
        changing mode of build/scripts-2.7/twistd from 644 to 755
        changing mode of build/scripts-2.7/manhole from 644 to 755
        changing mode of build/scripts-2.7/tap2rpm from 644 to 755
        changing mode of build/scripts-2.7/ckeygen from 644 to 755
        changing mode of build/scripts-2.7/trial from 644 to 755
        changing mode of build/scripts-2.7/tap2deb from 644 to 755
        changing mode of build/scripts-2.7/pyhtmlizer from 644 to 755
        changing mode of build/scripts-2.7/tkconch from 644 to 755
        changing mode of build/scripts-2.7/conch from 644 to 755
        changing mode of build/scripts-2.7/cftp from 644 to 755
        changing mode of /home/dennis/.virtualenvs/scraper/bin/mailmail to 755
        changing mode of /home/dennis/.virtualenvs/scraper/bin/twistd to 755
        changing mode of /home/dennis/.virtualenvs/scraper/bin/manhole to 755
        changing mode of /home/dennis/.virtualenvs/scraper/bin/tap2rpm to 755
        changing mode of /home/dennis/.virtualenvs/scraper/bin/ckeygen to 755
        changing mode of /home/dennis/.virtualenvs/scraper/bin/trial to 755
        changing mode of /home/dennis/.virtualenvs/scraper/bin/tap2deb to 755
        changing mode of /home/dennis/.virtualenvs/scraper/bin/pyhtmlizer to 755
        changing mode of /home/dennis/.virtualenvs/scraper/bin/tkconch to 755
        changing mode of /home/dennis/.virtualenvs/scraper/bin/conch to 755
        changing mode of /home/dennis/.virtualenvs/scraper/bin/cftp to 755
      Running setup.py install for cryptography
        c/_cffi_backend.c: In function ‘allocate_with_allocator’:
        c/_cffi_backend.c:3025:26: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
             PyObject *my_alloc = allocator[0];
                                  ^
        c/_cffi_backend.c:3026:25: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
             PyObject *my_free = allocator[1];
                                 ^
        c/_cffi_backend.c:3027:40: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
             PyObject *dont_clear_after_alloc = allocator[2];
                                                ^
        c/_cffi_backend.c: In function ‘b_newp’:
        c/_cffi_backend.c:3175:34: warning: passing argument 3 of ‘direct_newp’ from incompatible pointer type [-Wincompatible-pointer-types]
             return direct_newp(ct, init, default_allocator);
                                          ^
        c/_cffi_backend.c:3069:18: note: expected ‘PyObject * const (*)[3] {aka struct _object * const (*)[3]}’ but argument is of type ‘PyObject * const* {aka struct _object * const*}’
         static PyObject *direct_newp(CTypeDescrObject *ct, PyObject *init,
                          ^
        In file included from c/cffi1_module.c:14:0,
                         from c/_cffi_backend.c:6413:
        c/ffi_obj.c: In function ‘ffi_new’:
        c/ffi_obj.c:356:39: warning: passing argument 4 of ‘_ffi_new’ from incompatible pointer type [-Wincompatible-pointer-types]
             return _ffi_new(self, args, kwds, default_allocator);
                                               ^
        c/ffi_obj.c:337:18: note: expected ‘PyObject * const (*)[3] {aka struct _object * const (*)[3]}’ but argument is of type ‘PyObject * const* {aka struct _object * const*}’
         static PyObject *_ffi_new(FFIObject *self, PyObject *args, PyObject *kwds,
                          ^
        c/ffi_obj.c: In function ‘_ffi_new_with_allocator’:
        c/ffi_obj.c:364:21: warning: passing argument 4 of ‘_ffi_new’ from incompatible pointer type [-Wincompatible-pointer-types]
                             &PyTuple_GET_ITEM(allocator, 1));
                             ^
        c/ffi_obj.c:337:18: note: expected ‘PyObject * const (*)[3] {aka struct _object * const (*)[3]}’ but argument is of type ‘PyObject ** {aka struct _object **}’
         static PyObject *_ffi_new(FFIObject *self, PyObject *args, PyObject *kwds,
                          ^
        
        Installed /tmp/pip-build-wx54VN/cryptography/.eggs/cffi-1.4.2-py2.7-linux-x86_64.egg
        Searching for pycparser
        Reading https://pypi.python.org/simple/pycparser/
        Best match: pycparser 2.14
        Downloading https://pypi.python.org/packages/source/p/pycparser/pycparser-2.14.tar.gz#md5=a2bc8d28c923b4fe2b2c3b4b51a4f935
        Processing pycparser-2.14.tar.gz
        Writing /tmp/easy_install-oVdWII/pycparser-2.14/setup.cfg
        Running pycparser-2.14/setup.py -q bdist_egg --dist-dir /tmp/easy_install-oVdWII/pycparser-2.14/egg-dist-tmp-AhItwA
        warning: no previously-included files matching 'yacctab.*' found under directory 'tests'
        warning: no previously-included files matching 'lextab.*' found under directory 'tests'
        warning: no previously-included files matching 'yacctab.*' found under directory 'examples'
        warning: no previously-included files matching 'lextab.*' found under directory 'examples'
        zip_safe flag not set; analyzing archive contents...
        Moving pycparser-2.14-py2.7.egg to /tmp/pip-build-wx54VN/cryptography/.eggs
        
        Installed /tmp/pip-build-wx54VN/cryptography/.eggs/pycparser-2.14-py2.7.egg
        
        no previously-included directories found matching 'docs/_build'
        warning: no previously-included files matching '*' found under directory 'vectors'
        generating cffi module 'build/temp.linux-x86_64-2.7/_padding.c'
        generating cffi module 'build/temp.linux-x86_64-2.7/_constant_time.c'
        generating cffi module 'build/temp.linux-x86_64-2.7/_openssl.c'
        building '_openssl' extension
        x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/_openssl.c -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_openssl.o
        x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_openssl.o -lssl -lcrypto -o build/lib.linux-x86_64-2.7/cryptography/hazmat/bindings/_openssl.so
        building '_constant_time' extension
        x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/_constant_time.c -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_constant_time.o
        x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_constant_time.o -o build/lib.linux-x86_64-2.7/cryptography/hazmat/bindings/_constant_time.so
        building '_padding' extension
        x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/_padding.c -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_padding.o
        x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_padding.o -o build/lib.linux-x86_64-2.7/cryptography/hazmat/bindings/_padding.so
      Running setup.py install for zope.interface
        
        warning: no previously-included files matching '*.dll' found anywhere in distribution
        warning: no previously-included files matching '*.pyc' found anywhere in distribution
        warning: no previously-included files matching '*.pyo' found anywhere in distribution
        warning: no previously-included files matching '*.so' found anywhere in distribution
        warning: no previously-included files matching 'coverage.xml' found anywhere in distribution
        no previously-included directories found matching 'docs/_build'
        building 'zope.interface._zope_interface_coptimizations' extension
        x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c src/zope/interface/_zope_interface_coptimizations.c -o build/temp.linux-x86_64-2.7/src/zope/interface/_zope_interface_coptimizations.o
        x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/src/zope/interface/_zope_interface_coptimizations.o -o build/lib.linux-x86_64-2.7/zope/interface/_zope_interface_coptimizations.so
        Skipping installation of /home/dennis/.virtualenvs/scraper/lib/python2.7/site-packages/zope/__init__.py (namespace package)
        Installing /home/dennis/.virtualenvs/scraper/lib/python2.7/site-packages/zope.interface-4.1.3-py2.7-nspkg.pth
      Running setup.py install for enum34
        
      Running setup.py install for cffi
        building '_cffi_backend' extension
        x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DUSE__THREAD -I/usr/include/python2.7 -c c/_cffi_backend.c -o build/temp.linux-x86_64-2.7/c/_cffi_backend.o
        c/_cffi_backend.c: In function ‘allocate_with_allocator’:
        c/_cffi_backend.c:3025:26: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
             PyObject *my_alloc = allocator[0];
                                  ^
        c/_cffi_backend.c:3026:25: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
             PyObject *my_free = allocator[1];
                                 ^
        c/_cffi_backend.c:3027:40: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
             PyObject *dont_clear_after_alloc = allocator[2];
                                                ^
        c/_cffi_backend.c: In function ‘b_newp’:
        c/_cffi_backend.c:3175:34: warning: passing argument 3 of ‘direct_newp’ from incompatible pointer type [-Wincompatible-pointer-types]
             return direct_newp(ct, init, default_allocator);
                                          ^
        c/_cffi_backend.c:3069:18: note: expected ‘PyObject * const (*)[3] {aka struct _object * const (*)[3]}’ but argument is of type ‘PyObject * const* {aka struct _object * const*}’
         static PyObject *direct_newp(CTypeDescrObject *ct, PyObject *init,
                          ^
        In file included from c/cffi1_module.c:14:0,
                         from c/_cffi_backend.c:6413:
        c/ffi_obj.c: In function ‘ffi_new’:
        c/ffi_obj.c:356:39: warning: passing argument 4 of ‘_ffi_new’ from incompatible pointer type [-Wincompatible-pointer-types]
             return _ffi_new(self, args, kwds, default_allocator);
                                               ^
        c/ffi_obj.c:337:18: note: expected ‘PyObject * const (*)[3] {aka struct _object * const (*)[3]}’ but argument is of type ‘PyObject * const* {aka struct _object * const*}’
         static PyObject *_ffi_new(FFIObject *self, PyObject *args, PyObject *kwds,
                          ^
        c/ffi_obj.c: In function ‘_ffi_new_with_allocator’:
        c/ffi_obj.c:364:21: warning: passing argument 4 of ‘_ffi_new’ from incompatible pointer type [-Wincompatible-pointer-types]
                             &PyTuple_GET_ITEM(allocator, 1));
                             ^
        c/ffi_obj.c:337:18: note: expected ‘PyObject * const (*)[3] {aka struct _object * const (*)[3]}’ but argument is of type ‘PyObject ** {aka struct _object **}’
         static PyObject *_ffi_new(FFIObject *self, PyObject *args, PyObject *kwds,
                          ^
        x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protetor-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/c/_cffi_backend.o -lffi -o build/lib.linux-x86_64-2.7/_cffi_backend.so
        
      Running setup.py install for pycparser
        
        warning: no previously-included files matching 'yacctab.*' found under directory 'tests'
        warning: no previously-included files matching 'lextab.*' found under directory 'tests'
        warning: no previously-included files matching 'yacctab.*' found under directory 'examples'
        warning: no previously-included files matching 'lextab.*' found under directory 'examples'
        Build the lexing/parsing tables
    Successfully installed scrapy cssselect queuelib pyOpenSSL w3lib lxml Twisted six service-identity cryptography zope.interface characteristic pyasn1-modules pyasn1 idna enum34 ipaddress cffi pycparser
    Cleaning up...

Aside from the lots of warnings, it seems to compile ok with no errors, but it cannot be started.

    $ scrapy
    [1]    13574 segmentation fault  scrapy

 in a python console:

    Python 2.7.11 (default, Dec  9 2015, 00:29:25) 
    [GCC 5.3.1 20151205] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import scrapy
    [1]    14681 segmentation fault  python

By the warnings the problem seems to be with ffi and cryptography packages but I'm not sure as all of them installs just fine. 

Any ideas on how to solve this?
Thanks.

**Comment by manojpandey** [comment]
Try doing:

    sudo apt-get remove --purge python-dev python-pip libxml2-dev libxslt1-dev zlib1g-dev libffi-dev libssl-dev

    sudo apt-get update

    sudo apt-get install python-dev python-pip libxml2-dev libxslt1-dev zlib1g-dev libffi-dev libssl-dev

**Comment by akul08** [comment]
Please refer the official docs for installation.
http://doc.scrapy.org/en/1.0/intro/install.html#ubuntu-9-10-or-above
You need to install the following libraries.
    `sudo apt-get install python-dev python-pip libxml2-dev libxslt1-dev zlib1g-dev libffi-dev libssl-dev`
Then:
    `pip install scrapy`

**Comment by DenJohX** [comment]
@akul08 I have installed all of those required development packages.

@manojpandey purging and reinstalling does not work either.

Is there a way to debug the compiled library?

**Comment by DenJohX** [comment]
The problem was with gcc, as explained [in this thread](https://bitbucket.org/cffi/cffi/issues/240/cffi-crash-on-debian-unstable-with-gcc-5) and seems to be affecting both ffi and cryptography, and its solved on this [bug report](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=69037).

As it will be solved in gcc 5.4 and its not yet in Debian, I solved this downgrading gcc from testing (5.3.1-1) to stable (4.9.2-2). Now its working fine.

Thanks for the help, please mark this as solved.

**Comment by kmike** [comment]
@DenJohX thanks for reporting and debugging it!
