### ISSUE TITLE
XMLFeedSpider encoding issue

### ISSUE THREAD

**Issue by busla** [scrapy/scrapy#1665]
Scrapy version: 1.04

My spider (from the XMLFeedSpider example in the docs) doesn´t seem to read the defined itertag since it contains the iso-8859-1 letter "Þ"
http://www.w3schools.com/charsets/ref_html_8859.asp

I´ve tried my code on a different url with english xml tags and it works fine.

```python
# -*- coding: utf-8 -*-

import scrapy

from scrapy.spiders import XMLFeedSpider
from althingi_scraper.items import PartyItem

class PartySpider(XMLFeedSpider):
    name = 'party'
    allowed_domains = ['http://www.althingi.is']
    #session = '145'  

    start_urls = [
        #'http://www.althingi.is/altext/xml/thingflokkar/?lthing=%s' % session,        
        'http://www.althingi.is/altext/xml/thingflokkar/'
    ]   

    itertag = 'þingflokkar'

    def parse_node(self, response, node):        
        item = PartyItem()
        item['party_id'] = node.xpath('@id').extract()
        item['name'] = node.xpath('heiti').extract()
        #item['short_abbr'] = node.xpath('stuttskammstöfun').extract()
        #item['long_abbr'] = node.xpath('löngskammstöfun').extract()
        
        return item
```

Any thoughts?

**Comment by busla** [comment]
Using xml as an iterator solved it. I´ll keep the issue open since this might be an issue with iternode.

**Comment by redapple** [comment]
@busla , I just submitted a PR for this, using your document as a test sample.

I was able to make your spider work with this minor change to your code:
```
    itertag = u'þingflokkur'
```
using a Unicode string and using the repeating element tag, not the parent element.

Are you able to check your spider with this suggested fix?

**Comment by busla** [comment]
This works :-) Wow, thanks for the PR. 

Tested this on all seven spiders that are scraping xml dom with different Icelandic characters.

I worked around the issue earlier by replacing all Icelandic letters in the dom the DOM in `adapt_response()` before handing it over to parse_node, but that was messy.

When do you think your PR will be committed to master? Seems like a nasty bug.

**Comment by redapple** [comment]
@busla , fix is now in the master branch (no official release with the fix yet)

**Comment by busla** [comment]
Great job! Thanks for the fix :-)
