### ISSUE TITLE
extract_nth()

### ISSUE THREAD

**Issue by joshuakeough** [scrapy/scrapy#1672]
It would be extremely useful an extract_nth() method to add flexibility to the extract_first() method when extracting text with selectors.

**Comment by kmike** [comment]
Hey @joshuakeough,

We discussed this possibility in the original ticket (https://github.com/scrapy/scrapy/issues/568), but decided that selecting nth result inside xpath or css expression is more efficient than slicing the result afterwards, and we should encourage it by providing only extract_first. But I'd be happy to listen counter-arguments and be convinced that extract_nth is a good idea :)

**Comment by redapple** [comment]
I prefer recommending using XPath's `[N]` predicates or CSS selectors pseudo-classes ([`:nth-...`](https://www.w3.org/TR/css3-selectors/#structural-pseudos)), using https://github.com/scrapy/parsel/pull/24 if necessary

In any case, I believe the discussion should be moved to https://github.com/scrapy/parsel

**Comment by joshuakeough** [comment]
Thank you, I realized the XPath predicates and CSS selectors work best.
