### ISSUE TITLE
Spider status Collection Issue

### ISSUE THREAD

**Issue by agramesh** [scrapy/scrapy#1673]
Hi
- Before I was use scrapy version "Scrapy v 0.24" and use the below method for collect the spider status 

```
    def insertStats(self,spider,spider_stats):
        d = self.dbpool.runInteraction(self.stats_spider_closed, spider, spider_stats)
        return d

    def stats_spider_closed(self,conn, spider, spider_stats):
```
- But now i updated to Scrapy v 1.0 , and now i receive the error like this, how can resolve it.

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/xlib/pydispatch/robustapply.py", line 57, in robustApply
    return receiver(*arguments, **named)
TypeError: insertStats() takes exactly 3 arguments (2 given)
```

**Comment by sornalingam** [comment]
def insertStats(self,spider):
        d = self.dbpool.runInteraction(self.stats_spider_closed, spider)
        return d

def stats_spider_closed(self,conn, spider):

#get the crawler instance from Spiders
#From the crawler instance get the stats using get_stats()
# It will return you the spdier_stats 

        crawler = spider.crawler
        spider_stats = c.crawler.get_stats()

I think you can use the crawler object to get the stats. I have added the code above

**Comment by agramesh** [comment]
working fine.
