### ISSUE TITLE
django.setup() used for django_item causes a massive memory leak in Scrapy

### ISSUE THREAD

**Issue by jschilling1** [scrapy/scrapy#1685]
I need to call django.setup() to use django_item, when i do, Scrapy's memory usage keeps growing with the number of returned items.

My actual spider returns about 100 pages per html, but 1000 makes it grow to a gigabyte in minutes for the purposes of this.
    def parse(self, response):
        return ({'url': 'http://localhost/=%s' % randint(1, 9999999)} for i in xrange(1000))

Disabling 'debug_toolbar' in INSTALLED_APPS fixes this problem.
I'd really like to know how its affecting Scrapy. It took me a while to track it down django, guppy and trackrefs didn't point to a specific problem except a unicode() and dict() object count build up.

**Comment by trifle** [comment]
This seems like a django issue rather than a scrapy one.

Did you run with DEBUG=True? That will make django cache all ORM queries, hence inflating memory.
See https://docs.djangoproject.com/en/1.9/ref/settings/#debug

> It is also important to remember that when running with DEBUG turned on, Django will remember every SQL query it executes. This is useful when you’re debugging, but it’ll rapidly consume memory on a production server.

**Comment by jschilling1** [comment]
Debug=True makes it worse, but the leak is very substantial either way.  I use django item with item_model.save(commit=False) which to my understanding should prevent queries in the first place.

**Comment by Gallaecio** [comment]
@jschilling1 Did this ever got fixed?

**Comment by Gallaecio** [comment]
Closing due to a lack of feedback.
