### ISSUE TITLE
Codecov review checks 

### ISSUE THREAD

**Issue by nramirezuy** [scrapy/scrapy#1695]
Some of the checks are not showing. Ex: https://github.com/scrapy/scrapy/pull/1692 https://github.com/scrapy/scrapy/pull/1654
Does anyone knows what is this about?

**Comment by lopuhin** [comment]
maybe they are not showing when the left (start) revision is a merge?

**Comment by kmike** [comment]
@nramirezuy could you please fire an issue here: https://github.com/codecov/support/issues?

**Comment by lopuhin** [comment]
Ah, no, now I understand - the checks were performed when the start revision was different - these PRs contain commits that were merged in another PR. So github updated the start revisions in UI, but these checks were not actually performed. Sorry for the mess

**Comment by redapple** [comment]
I believe we can close this one now.
