### ISSUE TITLE
Https11TestCase.test_timeout_download_from_spider fails to cleanup

### ISSUE THREAD

**Issue by lopuhin** [scrapy/scrapy#1696]
From https://github.com/scrapy/scrapy/pull/1678#issuecomment-172482929

Currently skipped https test ``test_timeout_download_from_spider`` fails to cleanup (both on py2 and py3), not sure if is some test artifact or real issue, and how to dig it out:
```
_______________________________________________________________ Https11TestCase.test_timeout_download_from_spider ________________________________________________________________
NOTE: Incompatible Exception Representation, displaying natively:

DirtyReactorAggregateError: Reactor was unclean.
Selectables:
<<class 'twisted.internet.tcp.Client'> to ('localhost', 58185) at 10d488750>
```

**Comment by redapple** [comment]
This was fixed in https://github.com/scrapy/scrapy/pull/1804
