### ISSUE TITLE
Elegent way to access constants in settings.py from spider class definition

### ISSUE THREAD

**Issue by wlnirvana** [scrapy/scrapy#1697]
I would like to access settings.py from spider to do some customization like the following:
```python
class BarSpider(scrapy.Spider):
    name = "bar"
    allowed_domains = ["bar.com"]
    start_urls = (
        'http://www.bar.com/',
    )

    def __init__(self, *args, **kwargs):
        super(BarSpider, self).__init__(*args, **kwargs)
        print self.settings
        self.foo = settings.get('foo')

    def parse(self, response):
        pass
```
Is this possible?

**Comment by kmike** [comment]
Yes, this is possible, but not elegant. You can use [self.settings](http://doc.scrapy.org/en/latest/topics/spiders.html#scrapy.spiders.Spider.settings) attribute, but not in `__init__` - e.g. you can use it in `start_requests`. Alternatively, you can override Spider.from_crawler method.

**Comment by wlnirvana** [comment]
Using `start_requests` seems easy and elegent enough. Thank you very much!

**Comment by nramirezuy** [comment]
@wlnirvana you can use [`from_crawler`](https://github.com/scrapy/scrapy/blob/master/scrapy/spiders/__init__.py#L49) you just need to call `super` at the beginning of you override.
