### ISSUE TITLE
Add support for Google AppEngine

### ISSUE THREAD

**Issue by bhagyas** [scrapy/scrapy#1702]
Scrapy should be runnable on AppEngine.

**Comment by redapple** [comment]
Third party libraries need to be ["pure Python"](https://cloud.google.com/appengine/docs/python/tools/libraries27#vendoring)
Scrapy [depends on a few Python libraries itself](https://github.com/scrapy/scrapy/blob/master/requirements.txt).
[`lxml` is installed as far as I can read](https://cloud.google.com/appengine/docs/python/tools/libraries27#runtime-libraries) ;
for the other dependencies, I guess it should work.

Have you tried yourself to run scrapy on Google AppEngine?
If it does not work, can you provide some console logs with errors?

**Comment by eliasdorneles** [comment]
I tried it some years ago -- as far as I know, Twisted doesn't run in Google AppEngine, because it needs access to low-level OS stuff (threads, sockets) that the AppEngine doesn't provide.

**Comment by kmike** [comment]
https://cloud.google.com/appengine/docs/python/sockets/ - here they say 

> Async IO (such as Twisted in Python) is not supported.

I'm not sure what can we do.
