### ISSUE TITLE
Python 3.3 tests are unstable

### ISSUE THREAD

**Issue by kmike** [scrapy/scrapy#1707]
They often fail on first try - bench command takes too long to execute.

**Comment by lopuhin** [comment]
Summary: at least two failed builds so far (https://travis-ci.org/scrapy/scrapy/builds/103687420 and https://travis-ci.org/scrapy/scrapy/builds/103806098), output from failed build https://gist.github.com/kmike/282dc84facc492dff885

**Comment by kmike** [comment]
https://travis-ci.org/scrapy/scrapy/builds/103825700 also failed with a similar error (bench test failed, bt other passed)

**Comment by lopuhin** [comment]
Maybe we should disable this test while this is not fixed, to avoid spoiling PR checks?

**Comment by lopuhin** [comment]
Or increase the time limit? Locally this test takes 7 seconds on python 3.4 and 5 seconds on python 2.7, and the time limit is 15.

**Comment by kmike** [comment]
I think it is just `scrapy bench` command which is broken in Python 3, and tests are not good enough to detect it. See https://github.com/scrapy/scrapy/pull/1708, it could fix the issue.

**Comment by kmike** [comment]
Tests for #1708 passed 2/2 times

**Comment by kmike** [comment]
I'm closing it, #1708 seems to help. E.g. https://travis-ci.org/scrapy/scrapy/builds/103861004 failed (it was before #1708 is merged into master), but all builds after merge were successful (?).

**Comment by lopuhin** [comment]
Super, thanks @kmike !

**Comment by kmike** [comment]
Ouch, it happened again in master.

**Comment by lopuhin** [comment]
Do you mean this build? https://travis-ci.org/scrapy/scrapy/jobs/103861010

**Comment by kmike** [comment]
No, this one: https://travis-ci.org/scrapy/scrapy/builds/104060481 - I've restarted it. It failed with the same error (scrapy parse command takes too long). 

I think it makes sense to add an option to `scrapy bench` command to specify how much load to put, and use a faster benchmark in tests. There is no need to run it for 5-10 seconds, something like 0.1s is more than enough.

That said, it'd be nice to check why is scrapy bench slower in Python 3.x.

**Comment by kmike** [comment]
For me scrapy bench takes roughly the same time in Python 2 and Python 3 (12..13s) - after all, they use the same close spider timeout (10s). In Python 2.x spider handles about 1k pages before timeout fires, in Python 3 it handles about 650 pages.

If modified to stop after 500 pages, in 2.x script takes 6s and in 3.x script takes 10s. 

Some differences:

* In 3.x LinkExtractor.extract_links is much slower: it takes 4.5s cumulative, vs 1.6s in Python 2. Likely that's because of `canonicalize_url` - it is also much slower, 4.5s vs 1.1s in Python 2.
* In Python 3.x str.encode is called over 1M times, but total overhead is not that big (0.3s).
* urllib.parse.quote is called 500K times and takes 2s in Python 3, while urllib.quote is called only 150K times and takes 0.14s. I don't have an explanation for it.

**Comment by redapple** [comment]
Happened here too https://travis-ci.org/scrapy/scrapy/jobs/104203367

**Comment by jschilling1** [comment]
A follow up to what @kmike was pointing out about performance,  cached runs of my spiders show python 3 to be ~10% slower than python 2. What's more surprising and unfortunate is that python 3 memory usage is only slightly better and in fact sometimes higher for some spiders.  I was expecting an improvement since python 3 uses less memory for ascii only unicode objects, and i've seen this in other text intensive scripts.

**Comment by redapple** [comment]
I think we can close this. I don't recall seeing this issue lately.

**Comment by kmike** [comment]
+1 to @redapple.
