### ISSUE TITLE
Pickle and marshal output doesn't work for multiple items

### ISSUE THREAD

**Issue by eliasdorneles** [scrapy/scrapy#1713]
So, I was trying to add a test for Pickle output and found out that it doesn't really work for more than one item.

Try running the following spider with `scrapy runspider samplespider.py -o output.pickle`:

```
import scrapy

class SampleSpider(scrapy.Spider):
    name = 'sample'
    start_urls = ['http://example.com']

    def parse(self, response):
        yield {'key1': '10', 'key2': '20'}
        yield {'key1': '11', 'key2': '21'}
        yield {'key1': '12', 'key2': '22'}
```

It writes an output.pickle file alright, but if you try to read the output, you get only the first item:

```
>>> import pickle
>>> pickle.load(open('output.pickle'))
{'key2': '20', 'key1': '10'}
```

The pickle itself seems to have the data:

```
$ cat output.pickle 
�}q(Ukey2qU20qUkey1qU10qu.�}q(Ukey2qU21qUkey1qU11qu.�}q(Ukey2qU22qUkey1qU12qu.
```

It's just not usable.

And it happens the same with the marchal output, try doing `scrapy runspider samplespider.py -o output.marshal` and then:

```
>>> import marshal
>>> marshal.load(open('output.marshal'))
{'key2': '20', 'key1': '10'}
```

Am I missing something?
Is anyone actually using these features? :)

**Comment by kmike** [comment]
If I'm not mistaken, one can open a file and then call `pickle.load()` or `marshal.load()` multiple times to load all items. This is somewhat simlilar to JSON lines, but you can export rich picklable Python objects (e.g. class instances or Python functions). 

Not that I'd use this feature myself :) +0.0001 to deprecate it. Or maybe we should just document it properly.

**Comment by eliasdorneles** [comment]
Right, it works like you've described.
+1 to document it properly, at least. :)
Sorry for the false alarm!
