### ISSUE TITLE
Support S3 downloader handler on Python3

### ISSUE THREAD

**Issue by redapple** [scrapy/scrapy#1718]
Continuation of https://github.com/scrapy/scrapy/pull/1716#discussion_r50683511

**Comment by lopuhin** [comment]
Hm, at first sight signing headers looks broken on Python 3 (as explained here for example https://github.com/boto/boto/issues/2524#issuecomment-52251333)

**Comment by lopuhin** [comment]
It is possible to work around the bug in an ugly way (https://github.com/lopuhin/scrapy/commit/90bf6859d3fdf5f8e6dcd76824434789eeb3e65c), but it seems the only thing we need from boto is request signing - maybe we could use ``boto.utils.canonical_string`` directly for it?

**Comment by lopuhin** [comment]
After discussion in #1749 we decided to try using ``boto3`` (in fact, all we need is ``botocore``), it mostly works (https://github.com/lopuhin/scrapy/commit/0e78d466d8ee060ad95a7030b3fe594d48e19d16), only two problems so far:
- ``botocore`` discards the Date passed from the outside, and sets the date itself. This makes testing hard.
- ``botocore`` does not follow behavior described here http://s3.amazonaws.com/awsdocs/S3/20060301/s3-dg-20060301.pdf: "In this case, the x-amz-date takes precedence over the Date header" - it leaves both headers in the ``string_to_sign``. It is easy to override this from the outside, but perhaps it's better to first understand which behavior is more correct. This is tested in ``test_request_signing5``

**Comment by lopuhin** [comment]
Submitted https://github.com/boto/botocore/issues/786 on the second issue (and it seems to be impossible to override this from the outside without hacks).

**Comment by redapple** [comment]
Needs backporting to 1.1 branch

**Comment by redapple** [comment]
Backported in https://github.com/scrapy/scrapy/pull/1792

**Comment by wilfre** [comment]
;
