### ISSUE TITLE
Provide TextResponse.text attribute

### ISSUE THREAD

**Issue by kmike** [scrapy/scrapy#1729]
What about adding `response.text` property as a shortcut for `response.body_as_unicode()`, like `requests` library does it? TextResponse and its subclasses will have it.

**Comment by eliasdorneles** [comment]
woo, I like this one :)

I like `response.json()` too, also from `requests` -- would it make sense to have it in TextResponse?

**Comment by lopuhin** [comment]
yes, ``response.body`` sounds really nice and logical

**Comment by kmike** [comment]
@eliasdorneles I don't know, maybe we need this method only in JsonResponse (which we don't have now). JsonResponse may also provide .jmes method to query json data.

**Comment by kmike** [comment]
Or maybe having it in a base class (like .css and .xpath for TextResponse) is fine :)
