### ISSUE TITLE
Reactor conflict

### ISSUE THREAD

**Issue by konstruilo** [scrapy/scrapy#1745]
I'm launching scrapy manually from separate thread using twisted reactor. So the situation is: when one reactor is already running and scrapy tries to launch another one in crawler.start - that all crashes.

Would you mind to add some checks for existing and running reactor? Thanx.

**Comment by kmike** [comment]
Hey @konstruilo! How are you using it? Crawler object doesn't have 'start' method. The recommended way to run scrapy in existing reactor is to use CrawlerRunner (http://doc.scrapy.org/en/latest/topics/api.html#scrapy.crawler.CrawlerRunner).

**Comment by kmike** [comment]
See also examples here: http://doc.scrapy.org/en/latest/topics/practices.html#run-scrapy-from-a-script

**Comment by konstruilo** [comment]
@kmike Now I'm starting with CrawlerProcess.
Thanks! Will try CrawlerRunner
