### ISSUE TITLE
scrapy/xlib/pydispatch no longer in master

### ISSUE THREAD

**Issue by lagenar** [scrapy/scrapy#1762]
Hi there, I'm not sure if this is an issue or a design change. I just updated to the latest scrapy and my project has failed because it doesn't find the module scrapy.xlib.pydispatch. It was working fine some days ago and it looks like the code was removed from the release.

**Comment by lagenar** [comment]
I investigated a bit further and it seems the problem is that the release Scrapy 1.1.0rc1 doesn't include that package while the previous release (Scrapy 1.0.5) does.
Is this something expected? it will break some working code referencing that package like in my case.

**Comment by eliasdorneles** [comment]
Hey, @lagenar, thanks for the report, it seems we missed this in the release notes.

The code was previously using a bundled pydispatch library, but now it uses [PyDispatcher](https://pypi.python.org/pypi/PyDispatcher) which is Python 3 compatible.

In case your project was using pydispatch imports to connect signals, you can add a `from_crawler` method to your spider to do that:

```
@classmethod
def from_crawler(cls, crawler, *args, **kwargs):
    spider = super(MySpider, cls).from_crawler(crawler, *args, **kwargs)
    crawler.signals.connect(spider.spider_opened, signals.spider_opened)
    return spider
```

**Comment by eliasdorneles** [comment]
@dangra @kmike do you think it's worth to add a fallback for these imports with a DeprecationWarning or should we just document this in the release notes (since it isn't part of the core API)?

**Comment by dangra** [comment]
@eliasdorneles I'm afraid yes, we should add a fallback with a big deprecation warning.

**Comment by kmike** [comment]
+1

**Comment by eliasdorneles** [comment]
Okay, cool, will send a PR later.

**Comment by eliasdorneles** [comment]
PR: https://github.com/scrapy/scrapy/pull/1765
