### ISSUE TITLE
Public default ACL policy for storing on S3 with ImagesPipeline and FilesPipeline

### ISSUE THREAD

**Issue by lopuhin** [scrapy/scrapy#1778]
The policy here https://github.com/scrapy/scrapy/blob/41588397c04356f2b0c393b61ed68271a08d6ccd/scrapy/pipelines/files.py#L83 is public-read - this means that even though the bucket is private, uploaded item will be public and accessible if you know the URL (at least that is what I get from direct tests, and I don't see where it could be overridden).
Probably this should be changed to ``private``, and noted as a backwards incompatible security fix.

**Comment by redapple** [comment]
Fixed in https://github.com/scrapy/scrapy/issues/1796
