### ISSUE TITLE
Allow setting temp file location for S3 and FTP feed storage

### ISSUE THREAD

**Issue by redapple** [scrapy/scrapy#1779]
Triggered by [this question on StackOverflow](https://stackoverflow.com/questions/35417865)

Current `BlockingFeedStorage` uses `TemporaryFile(prefix='feed-')`. There could be a setting to set a different folder than the default one.

**Comment by aron-bordin** [comment]
Hi @redapple 

I'm learning about scrapy and I'd like to take this issue.

How can I name this new setting ? And how should it behave ? I'm thinking about a setting that defaults to 'auto' (use the temp file), or you can set the path name (the BlockingFeedStorage raise some exception if this folder does not exitst). What do you think about it?

**Comment by redapple** [comment]
Closed via https://github.com/scrapy/scrapy/issues/1847
