### ISSUE TITLE
Scrapy/scrapy startproject failed

### ISSUE THREAD

**Issue by vincent6987** [scrapy/scrapy#1780]
failed to startproject, here is the error info:

File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/string.py", line 125, in substitute
    return self.pattern.sub(convert, self.template)
TypeError: cannot use a string pattern on a bytes-like object

**Comment by kmike** [comment]
Hey @vincent6987,

What Scrapy version are you using?

**Comment by vincent6987** [comment]
The version is v1.0.5.  I installed from pip today.

I faced another error before this, I changed 'itervalues()' to 'values()', then this error hadn't appeared any more.

File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/scrapy/cmdline.py", line 21, in _iter_command_classes
    for obj in vars(module).itervalues():
AttributeError: 'dict' object has no attribute 'itervalues'

**Comment by kmike** [comment]
Scrapy 1.0.5 doesn't support Python 3, and you're using Python 3.5. We've released scrapy 1.1rc1 which has basic Python 3 support - can you try it instead (`pip install "scrapy >= 1.1rc1"`)? It has some know problems, but overall should be usable. We're going to release 1.1rc2 during this week to address some of the problems in rc1; you can also install Scrapy from github to get these recent fixes before 1.1rc2 release.

**Comment by kmike** [comment]
I'm closing this issue because the error is expected in Scrapy 1.0.5.

**Comment by taktikal17** [comment]
Thanks @kmike 

It works like a charm!! :100:
