### ISSUE TITLE
Encoding issues

### ISSUE THREAD

**Issue by psychok7** [scrapy/scrapy#1781]
I am fairly new to scrapy and i am trying to crawl a page but the final item is not showing correctly all characters.

The site header:

`<meta http-equiv="Content-Type" content="text/html; charset=utf-8">`

I try:
`scrapy shell "https://olx.pt/anuncio/t4-excelente-preo-centro-almada-IDyKPJd.html#c49d3d94cf;promoted"`

My response:

``` 
response.encoding: 'utf-8'
response._headers_encoding: 'utf-8'

```

What am i doing wrong?

**Comment by kmike** [comment]
Sorry, what is not displayed correctly? I've just tried your example: encoding is detected properly, and the result looks fine.

**Comment by psychok7** [comment]
@kmike if you try what do you get?

`scrapy shell "https://olx.pt/anuncio/escritrio-em-lea-da-palmeira-IDv0opO.html#c49d3d94cf"` 
`response.css('.brkword.lheight28::text').extract()[0].encode('utf8')`

I get `Escrit\xc3\xb3rio em le\xc3\xa7a da palmeira` and it should be `Escritório em leça da palmeira`

**Comment by kmike** [comment]
@psychok7 I think you're confused by the way Python 2 displays non-ascii strings. `Escrit\xc3\xb3rio em le\xc3\xa7a da palmeira` *is* `Escritório em leça da palmeira` - try printing it:

```
print(response.css('.brkword.lheight28::text').extract()[0])
```

**Comment by psychok7** [comment]
@kmike oh i see.. but how do i force it to output it the "proper" way to the json file when i `-o items.json` ?

**Comment by psychok7** [comment]
I think i figured it out thanks to http://stackoverflow.com/a/9195158/977622
```
JSON exporter writes unicode symbols escaped (e.g. \u03a4) by default, because not all streams can handle unicode. It has option to write them as unicode ensure_ascii=False (see docs for json.dumps) . But I can't find way to pass this option to standard feed exporter.
```
thanks anyways
