### ISSUE TITLE
Alternatives to Lxml as XML processing engine

### ISSUE THREAD

**Issue by gerosalesc** [scrapy/scrapy#1784]
This has been troubling me for some time now but I would like this project to support a more powerful XML/HTML processing engine as an alternative to Lxml. The only contender for lxml in Python: [Zorba](https://github.com/28msec/zorba). But why?

- Zorba supports [XQuery technology as well as JSONiq](http://zorba.28.io/documentation/latest/zorba/xml_json/).
- Zorba has [Python bindings](http://docs.zorba.io.s3-website-us-east-1.amazonaws.com/3.0.0/python/). I know they are not precisely the best bindings ever but at least they exist.
- I think XPath 1.0 is very limited for more complex structures.
- Lxml extensions are ok but not that much when compared to XQuery capabilities by default.
- Zorba can be hosted as a [service](https://github.com/28msec/28/blob/master/getting-started.md).

**Comment by kmike** [comment]
Currently you can grab response.body or response.text of an XML response and use any XML processing library with it. Could you please elaborate, what are you proposing?

**Comment by gerosalesc** [comment]
@kmike that's correct, that is what pretty much what I had to do to process my html results using Zorba, but I would like it to be included by default in Scrapy's Selector for it to be used the same way

`Selector(response=response).xquery('...').extract()`

or 

`response.selector.xquery('...').extract()`

**Comment by redapple** [comment]
@gerosalesc , I belive it's a discussion for [parsel](https://github.com/scrapy/parsel)

**Comment by gerosalesc** [comment]
@redapple Oh shame on me to be outdated with the architecture of the project... I totally agree I should move this, thanks.

**Comment by gerosalesc** [comment]
@redapple Oh shame on me to be outdated with the architecture of the project... I totally agree I should move this, thanks.

**Comment by redapple** [comment]
don't be ashamed @gerosalesc , it's rather new (and not even used in official release yet)

**Comment by gerosalesc** [comment]
It's done, closed in favor of [this issue](https://github.com/scrapy/parsel/issues/29)

**Comment by gerosalesc** [comment]
@redapple  ok, then They are actually great news. Decoupling is most of the time a good idea.

**Comment by aimer12** [comment]
i met troubles in the process  trying to install lxml  on windows, and i am not the only one.why can Scrapy provite alternative to other lib

**Comment by redapple** [comment]
@aimer12 , sorry for the late reply.

Scrapy relies on lxml and/or Selector with XPath support in a few places (link extraction, forms).
Ideally, these can be decoupled from Scrapy (if someone volunteers, it could happen sooner than later)

I'm sorry to hear you are having trouble installing lxml on Windows. What we've been told that works reasonably well is to [use Conda/Miniconda](http://doc.scrapy.org/en/latest/intro/install.html#anaconda).
In any case, please post your trouble to [StackOverflow](https://stackoverflow.com/questions/tagged/scrapy) if you don't find a satisfying answer there.
Or try [scrapy-users](https://groups.google.com/forum/#!forum/scrapy-users) mailing list.

**Comment by gerosalesc** [comment]
For everyone coming here I have moved this Issue to the [Parsel library](https://github.com/scrapy/parsel/issues/29). Any contributions welcome :).
