### ISSUE TITLE
Running multiple spiders in the same process with 'CrawlerRunner'

### ISSUE THREAD

**Issue by xyniceboy** [scrapy/scrapy#1785]
how to execute "Running multiple spiders in the same process with 'CrawlerRunner'" linked by http://doc.scrapy.org/en/latest/topics/practices.html#running-multiple-spiders-in-the-same-process. thanks.

**Comment by kmike** [comment]
Hey @xyniceboy,

The first CrawlerRunner example shows that - have you tried it?
I'm closing this ticket; please use stackoverflow for support questions (use 'scrapy' tag for your question).
