### ISSUE TITLE
Can't pass custom settings to middleware in scrapy `crawl`

### ISSUE THREAD

**Issue by GilJ** [scrapy/scrapy#1788]
We have written some custom downloader middleware to which we want to pass a custom setting; the layout is basically the following:

```python
from scrapy.utils.project import get_project_settings

class CustomMiddleware(object):
    def __init__(self):
        settings = get_project_settings()
        custom_setting = settings.get('CUSTOM_SETTING')
    [...]
```

And we launch our crawler with

> scrapy crawl CrawlerName -s CUSTOM_SETTING=1

However, the custom setting is not set in our downloader middleware. It is available in our item pipeline.

Are we accessing the settings wrong, or should we pass another flag? I did not find anything in the documentation.

**Comment by redapple** [comment]
To pass settings with command line tool, you need to use `-s CUSTOM_SETTING=value
See http://doc.scrapy.org/en/latest/topics/settings.html#command-line-options`

**Comment by kmike** [comment]
To do that use `from_crawler` method - see http://doc.scrapy.org/en/latest/topics/extensions.html#writing-your-own-extension. I think this is a documentation bug - it is not clear that Scrapy middlewares have the same features as extensions. Accessing settings is a common use case, I think we should provide examples in middleware docs, even if they are redundant.

**Comment by GilJ** [comment]
I'm sorry, that was a typo. We do pass with `-s`, I've updated my issue accordingly.

@kmike Thanks, I'll take a look at that

**Comment by GilJ** [comment]
Thanks for the quick responses, this fixed our issue.
