### ISSUE TITLE
Document from_crawler for Scrapy middlewares

### ISSUE THREAD

**Issue by redapple** [scrapy/scrapy#1789]
See motivation https://github.com/scrapy/scrapy/issues/1788

From @kmike 

>  is not clear that Scrapy middlewares have the same features as extensions. Accessing settings is a common use case, I think we should provide examples in middleware docs, even if they are redundant.

**Comment by eliasdorneles** [comment]
Just a heads up, @lfmattossch is working on this -- thanks Luiz!
