### ISSUE TITLE
install lxml trouble

### ISSUE THREAD

**Issue by aimer12** [scrapy/scrapy#1819]
there are many troubles installing lxml on window, because of its needs of visual studio .why i should install a software to install a lib for python. maybe it's better to provise an alternitive for other parse enginee. maybe beautifulsoup.

**Comment by redapple** [comment]
@aimer12 , you're right, lxml can cause quite some trouble to get installed properly on Windows.
On Windows, we recommend that you look into [Continuum Analytics Python distribution called Anaconda](https://www.continuum.io/why-anaconda)
Installation docs for scrapy have a section on this: http://doc.scrapy.org/en/1.0/intro/install.html#anaconda

**Comment by redapple** [comment]
@aimer12 , you do have a point about dependency to `lxml`. Refactoring to be able to use another html/xml parsing library would be great. It's not planned yet though.
We already moved Scrapy selectors to a [seperate package, `parsel`](https://pypi.python.org/pypi/parsel) but it's still a dependency.

**Comment by lopuhin** [comment]
If you are on Python 2.7, then another option is to use a more-or-less recent pip (>= 1.4) and run ``pip install lxml==3.4.4`` - this will use already compiled wheels from PyPI. The most recent lxml (3.5.0) does not have wheels on PyPI, and according to this https://bugs.launchpad.net/lxml/+bug/1176147 they are not a solved problem yet.

**Comment by lopuhin** [comment]
Also ``easy_install lxml`` works too, and even manages to find a wheel for the most recent lxml version.

**Comment by aimer12** [comment]
@redapple  thank you very much for your advice, i will seriously think about it.

**Comment by aimer12** [comment]
@lopuhin  thank you very much for your advice, it works!

**Comment by aimer12** [comment]
@redapple ^ ^ i didn't notice the !note , i could have read doc more  carefully.

**Comment by nolanjian** [comment]
hi, I wanna say I had install lxml on my window7, but still not work.
`import scrapy` fall
here is my traceback:
`Traceback (most recent call last):
  File "d:\python\python35-32\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\python\python35-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Python\Python35-32\Scripts\scrapy.exe\__main__.py", line 5, in <modul
e>
  File "d:\python\python35-32\lib\site-packages\scrapy\__init__.py", line 34, in
 <module>
    from scrapy.spiders import Spider
  File "d:\python\python35-32\lib\site-packages\scrapy\spiders\__init__.py", lin
e 10, in <module>
    from scrapy.http import Request
  File "d:\python\python35-32\lib\site-packages\scrapy\http\__init__.py", line 1
1, in <module>
    from scrapy.http.request.form import FormRequest
  File "d:\python\python35-32\lib\site-packages\scrapy\http\request\form.py", li
ne 9, in <module>
    import lxml.html
  File "d:\python\python35-32\lib\site-packages\lxml\html\__init__.py", line 54,
 in <module>
    from .. import etree
ImportError: DLL load failed: The specified module could not be found.`

Is there any way to solve this?
thx.

**Comment by nolanjian** [comment]
And, I use Python3.5.2, 
@redapple @aimer12 @lopuhin 
Any way can solve this? I think it maybe lxml's problem....
thx.

**Comment by deriegle** [comment]
@nolanjian You can try reinstalling lxml, but make sure you're using the correct 32-bit or 64bit version for your computer & operating system. Uninstall lxml and download the correct version again and try importing scrapy again.

**Comment by cathalgarvey** [comment]
Hi folks, this is a bit stale now, and it was never an issue with Scrapy but rather with an upstream dependency's releases for Windows. I'm going to close it, but feel free to chip in here again with solutions or workarounds for other suffering Windows users.
