### ISSUE TITLE
Needed a possibility to pass start_urls parameter in constructor

### ISSUE THREAD

**Issue by Felix-neko** [scrapy/scrapy#1823]
I have a `Spider` that should get its `start_urls` from an external source: file system, database, etc.
It will be extremely useful to pass it directly in constructor. Especially if I want to parse some similar sites on different URLs.

**Comment by kmike** [comment]
@Felix-neko I'm not sure I understood you correctly, but `start_urls` is just a shortcut for common case; you can implement `start_requests` method with custom logic (see examples http://doc.scrapy.org/en/latest/topics/spiders.html#scrapy-spider), or you can change `start_urls` in spider constructor without overriding `start_requests`.

**Comment by nyov** [comment]
You can of course override your Spider's `__init__()` method to pass any urls from elsewhere.
This is rather a support question though, please see http://scrapy.org/community/ for help channels.

As a quick starter, here's an example:
```py
class MySpider(scrapy.Spider):

    name = "myspider"

    def __init__(self, *args, **kwargs):
        urls = kwargs.pop('urls', []) 
        if urls:
            self.start_urls = urls.split(',')
        self.logger.info(self.start_urls)
        super(MySpider, self).__init__(*args, **kwargs)
```
run it as  `scrapy crawl myspider -a "urls=http://localhost/test/,http://localhost"`

**Comment by Felix-neko** [comment]
Well, I want something like that:

    process = CrawlerProcess({
        'FEED_FORMAT': 'json',
        'FEED_URI': 'habra_info.json',
        'LOG_ENABLED': False,
    })

    habra_hub_links_data = json.load(open("habra_hub_links.json", 'r'))
    habra_hub_urls = [item["hub_url"] for item in habra_hub_links_data]

    spider = HabraSpider(start_urls=habra_hub_urls)
    process.crawl(spider)
    process.start()

**Comment by Digenis** [comment]
@Felix-neko, you would need something like #1048
to make your 2nd example work as is.

**Comment by Felix-neko** [comment]
So, what should I do? Install `scrapy` from that fork?

**Comment by kmike** [comment]
@Felix-neko it should already work; in your example [CrawlerProcess](http://doc.scrapy.org/en/latest/topics/api.html#scrapy.crawler.CrawlerProcess) API is used incorrectly: process.crawl expects Spider class, not a spider instance. This works for me:

```py
import scrapy
from scrapy.crawler import CrawlerProcess

class HabraSpider(scrapy.Spider):
    name = 'habra'
    
    def parse(self, response):
        print(response.url)
        
process = CrawlerProcess()
process.crawl(HabraSpider, start_urls=["http://example.com", "http://example.org"])
process.start()
```

**Comment by Felix-neko** [comment]
process.crawl(HabraSpider, start_urls=["http://example.com", "http://example.org"])

Ага, вот где собака-то зарыта! Я этому `process.crawl` передавал не класс, а уже готовый объект. И была такая тема, что конструктор `__init__` у него вызывался дважды. Один раз с параметрами, а другой раз безо всяких параметров. Если возможно, проверьте, нет ли в том какого глюка.

Как бы там ни было, добра тебе, умный человек, держи няшку: http://cs627329.vk.me/v627329033/11961/U4Cy6RDXxNc.jpg

^__^

**Comment by kmike** [comment]
спасибо :P

**Comment by ayushmankoul** [comment]
Hello @kmike whenever we generate spider using command scrapy genspider spider_name url_name(including https in it).We encounter starts_urls  inside spider with https (two times)

`import scrapy
class ScrapyNameSpider(scrapy.Spider):
    name = 'scrapy_name'
    allowed_domains = ['https://github.com/scrapy/scrapy/issues/2711']
    start_urls = ['http://https://github.com/scrapy/scrapy/issues/2711/']
`
   ` def parse(self, response):
        pass`
We can alter the code for start_urls inside scrapy package so we can omit this thing from happening.Please let me know if this thing is worth giving time and also help me where to look for the file.

**Comment by SwapnilSoni1999** [comment]
> @Felix-neko it should already work; in your example [CrawlerProcess](http://doc.scrapy.org/en/latest/topics/api.html#scrapy.crawler.CrawlerProcess) API is used incorrectly: process.crawl expects Spider class, not a spider instance. This works for me:
> 
> ```python
> import scrapy
> from scrapy.crawler import CrawlerProcess
> 
> class HabraSpider(scrapy.Spider):
>     name = 'habra'
> 
>     def parse(self, response):
>         print(response.url)
> 
> process = CrawlerProcess()
> process.crawl(HabraSpider, start_urls=["http://example.com", "http://example.org"])
> process.start()
> ```

omg thanks alot <3

**Comment by MFax** [comment]
Hi,

is there a way to also use these passed start_urls in the LinkExtractor? So that I can extract all the internal links from the websites I pass? 

Thanks in advance
