### ISSUE TITLE
pip install scrapy error

### ISSUE THREAD

**Issue by codelegant** [scrapy/scrapy#1824]
I use pip to install scrapy, then a error occured
`Command ""c:\program files\python35\python.exe" -u -c "import setuptools, tokeniz
e;__file__='C:\\Users\\PROGRA~2\\AppData\\Local\\Temp\\pip-build-i9vpky2z\\lxml\\
setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('
\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\PROGRA~2\AppData\Loca
l\Temp\pip-1l5qv44w-record\install-record.txt --single-version-externally-managed
 --compile" failed with error code 1 in C:\Users\PROGRA~2\AppData\Local\Temp\pip-
build-i9vpky2z\lxml                                                              `

**Comment by kmike** [comment]
Hi @codelegant,

Scrapy installs lxml, and this fails in your case. I'm closing it in favor of https://github.com/scrapy/scrapy/issues/1819.
