### ISSUE TITLE
why RFPDupeFilter.request_seen gets called 3 times for one page crawling?

### ISSUE THREAD

**Issue by seaguest** [scrapy/scrapy#1830]
Hello,

To avoid crawling duplicated URLs, I store all crawled URLs in database, and then check if one URL requested is already in DB or not.

Here is my filter class:

``` py
class CustomFilter(RFPDupeFilter):
    """A dupe filter that considers specific ids in the url"""
    db = DBManager(settings[ 'MONGODB_VISITED_URLS' ])

    def request_seen(self, request):
        if self.db.exist("url", request.url):
            return True
        else:
            visitedUrl = VisitedURL()
            visitedUrl['url'] = request.url
            visitedUrl['orgDupURL'] = None
            self.db.insert(visitedUrl)
            return False
```

However I found request_seen method gets called 3 times for one page crawling, here are stack trace for the 3 calls in order:

------------------------------ 1
request_seen [filter.py:18] 
enqueue_request [scheduler.py:51]  
schedule [engine.py:189]  
crawl [engine.py:183]  
_process_spidermw_output [scraper.py:183]  
<genexpr> [defer.py:63] 
_oneWorkUnit [task.py:491]  
_tick [task.py:645] 
runUntilCurrent [base.py:825]  
mainLoop [base.py:1203] 
run [base.py:1194]  
start [crawler.py:251]  
<module> [start.py:15]  
run [pydevd.py:931] 
<module> [pydevd.py:1524]   

------------------------------ 2
request_seen [filter.py:18] 
enqueue_request [scheduler.py:51]  
schedule [engine.py:189]  
crawl [engine.py:183]  
_handle_downloader_output [engine.py:155]  
_runCallbacks [defer.py:588]  
_startRunCallbacks [defer.py:501]  
callback [defer.py:393] 
_runCallbacks [defer.py:588]  
_startRunCallbacks [defer.py:501]  
callback [defer.py:393] 
connectionLost [http11.py:320]  
_bodyDataFinished_CONNECTED [_newclient.py:1161]  
dispatcher [_newclient.py:916]  
connectionLost [_newclient.py:537]  
_disconnectParser [_newclient.py:1513]  
_finishResponse_WAITING [_newclient.py:1487]  
dispatcher [_newclient.py:916]  
_finished [_newclient.py:440]  
dataReceived [http.py:1478] 
rawDataReceived [_newclient.py:299] 
dataReceived [basic.py:578] 
dataReceived [_newclient.py:385]  
dataReceived [_newclient.py:1533]  
dataReceived [endpoints.py:102] 
_dataReceived [tcp.py:215]  
doRead [tcp.py:209] 
_doReadOrWrite [posixbase.py:597]  
callWithContext [context.py:81] 
callWithContext [context.py:118]  
callWithContext [log.py:84] 
callWithLogger [log.py:101] 
doPoll [epollreactor.py:396]  
mainLoop [base.py:1206] 
run [base.py:1194]  
start [crawler.py:251]  
<module> [start.py:15]  
run [pydevd.py:931] 
<module> [pydevd.py:1524]   

------------------------------ 3
request_seen [filter.py:18] 
enqueue_request [scheduler.py:51]  
schedule [engine.py:189]  
crawl [engine.py:183]  
_handle_downloader_output [engine.py:155]  
_runCallbacks [defer.py:588]  
_startRunCallbacks [defer.py:501]  
callback [defer.py:393] 
_runCallbacks [defer.py:588]  
_startRunCallbacks [defer.py:501]  
callback [defer.py:393] 
connectionLost [http11.py:320]  
_bodyDataFinished_CONNECTED [_newclient.py:1161]  
dispatcher [_newclient.py:916]  
connectionLost [_newclient.py:537]  
_disconnectParser [_newclient.py:1513]  
_finishResponse_WAITING [_newclient.py:1487]  
dispatcher [_newclient.py:916]  
_finished [_newclient.py:440]  
dataReceived [http.py:1478] 
rawDataReceived [_newclient.py:299] 
dataReceived [basic.py:578] 
dataReceived [_newclient.py:385]  
dataReceived [_newclient.py:1533]  
dataReceived [endpoints.py:102] 
dataReceived [policies.py:120]  
_flushReceiveBIO [tls.py:392]  
dataReceived [tls.py:422]  
_dataReceived [tcp.py:215]  
doRead [tcp.py:209] 
_doReadOrWrite [posixbase.py:597]  
callWithContext [context.py:81] 
callWithContext [context.py:118]  
callWithContext [log.py:84] 
callWithLogger [log.py:101] 
doPoll [epollreactor.py:396]  
mainLoop [base.py:1206] 
run [base.py:1194]  
start [crawler.py:251]  
<module> [start.py:15]  
run [pydevd.py:931] 
<module> [pydevd.py:1524]   

I thought that this method should be called only once for one page, why it gets called 3 times?
this brought me a problem, seems the DB access gets a pb, the result are not reflected, in the end I have 3 record in DB.

I will look into the pb, but I would still need to understand why this method gets 3 calls, did I make something wrong?

thanks and best regards

**Comment by kmike** [comment]
Hey @seaguest,

dupefilter should be called once per enqueued URL, not once per received response. Are you sure these 3 calls are for a single scrapy.Request?

Also, are you sure changes are applied in your mongo instance immediately? I.e. if you write to mongo, then read immediately, is it guaranteed that the just written result is returned?

**Comment by seaguest** [comment]
Hello kmike,

Thanks for your reply!

After some further investigation, I found something more strange, for one URL I tested, at the first time (nothing recorded in DB), request_seen gets calleds 3 times, the second time I tested it gets called only once, however when I tested another URL it get called only twice at the first time, then 1 call for the second.

here is my spider:
https://github.com/seaguest/EventSpider/blob/master/eventSpider/spiders/douban/doubanSpider.py

regarding the DB result, indeed it gets reflected in DB(I checked with robomongo), but in the spider the newly added record is not get reflected, thus it gets stored several times. maybe this is due to spider cache or something else, I am checking.

**Comment by kmike** [comment]
> regarding the DB result, indeed it gets reflected in DB(I checked with robomongo), but in the spider the newly added record is not get reflected, thus it gets stored several times. maybe this is due to spider cache or something else, I am checking.

It looks like a stale read issue; scrapy has nothing to do with that. The difference could be that the time between write and read is much shorter in a spider, or maybe robomongo uses different defaults for write acknowledgements.

**Comment by seaguest** [comment]
The DB write issue I have found now, it is because when I requested 
"http://www.douban.com/event/26260280"
in the response it gets changed to 
"https://www.douban.com/event/26260280"

I'll fix that pb.

BTW, do you have any idea why request_seen get called several times?

**Comment by kmike** [comment]
> BTW, do you have any idea why request_seen get called several times?

Well, the point of request_seen is to be called multiple times; it should return False on first call and True on all subsequent calls, so that multiple requests to the same URL are not scheduled. Could you please clarify your question?

**Comment by seaguest** [comment]
ok, the situation is getting worse now.

The DB write and read is correct now, the problem is still during one page crawling, the request_seen has been called twice, the first time returns false, the second time returns true which makes the spider ignore the request.

**Comment by kmike** [comment]
> The DB write and read is correct now, the problem is still during one page crawling, the request_seen has been called twice, the first time returns false, the second time returns true which makes the spider ignore the request.

Sorry, I still don't get it. That's the point of duplicate filters to filter out duplicate requests. If there are two requests to the same URL duplication filter makes Scrapy to send only the first request. Duplication filter is not tied to one page crawl in any way. What are you trying to acheive?

**Comment by seaguest** [comment]
I am doing a test for my spider, I shoot on one page. in theory the request_seen should be called only once for every request.
but in my case, when I target one URL, the request_seen gets called twice, which is not correct.
here is my spider:
https://github.com/seaguest/EventSpider/blob/master/eventSpider/spiders/douban/doubanSpider.py

And I found, if I don't target only one URL, the spider gets working correctly, maybe the way I deal with one page crawling is wrong.

**Comment by dl942702882** [comment]
i meet the same problem, as my total request number is 15000, strangely i found that the duplicate request fingerprints values is about 30000, i guess it's a problem with scrapy.
ps : i use scrapy with scrapy_splash and scrapy_redis

**Comment by Gallaecio** [comment]
@seaguest @dl942702882 Can any of you provide a [minimal example code](https://stackoverflow.com/help/mcve) to reproduce the issue?
