### ISSUE TITLE
mutiple spiders  affect each other

### ISSUE THREAD

**Issue by aohan237** [scrapy/scrapy#1839]
i have two spiders in one project,and only run one spider at a time but the varis shows in another spider when one spider runs .
IE.
class spider1(scrapy.spider): 
name='spiderone'
print 'hello'
def parse:
class spider2(scrapy.spider): 
name='spidertwo'
def parse:
when i run spidertwo,it will print 'hello'. but why? I only run one spider at a time

I'm really confused about it. how to deal with mutiple spiders ...the official dont show.

thanks a lot!!! from a scrapy beginner

**Comment by redapple** [comment]
@aohan237 ,
can I ask you to submit this to [scrapy-users](https://groups.google.com/forum/#!forum/scrapy-users) or [StackOverflow](https://stackoverflow.com/questions/tagged/scrapy)?

Ideally, GitHub issues should have a reproducible use-case showing a defect.
See http://doc.scrapy.org/en/latest/contributing.html#reporting-bugs
