### ISSUE TITLE
 Is it possible to modify the response content through Scrapy Selector?

### ISSUE THREAD

**Issue by seaguest** [scrapy/scrapy#1841]
I am using Scrapy to deep copy some content on one page, to crawl the content and download the images in that content and update the image original value accordingly.

For example I have:

    <div class="A">
    	<img original="example1.com/1/1.png"></img>
    </div>

I need to download the image and update the new image original value（for example to mysite.com/1/1.png）, then save the content.

what I will have finally is:

    <div class="A">
    	<img original="mysite.com/1/1.png"></img>
    </div>

and image on my disk.

Is it possible to modify the value through Selector?

Or must I download the image first and update the "original" value separately? any better solution?

**Comment by Digenis** [comment]
Selector, as it's name suggests, is only for selecting parts of the markup.
It can't be used for modifying.
You may have wanted to open this ticket in the [parsel](https://github.com/scrapy/parsel/) project
but it's probably more fit for the [scrapy-users mailing list](https://groups.google.com/forum/#!forum/scrapy-users)

**Comment by redapple** [comment]
Closing in favor of https://github.com/scrapy/parsel/issues/36
