### ISSUE TITLE
how to use headers in crawlspider?CRAWLERA use in crawlspider?

### ISSUE THREAD

**Issue by aohan237** [scrapy/scrapy#1843]
i  buy your CRAWLERA PLANS,but the offcial doc said dont to override the parse function,but how to transfer  the  CRAWLERA headers  to  the crawlspider

thanks a lot

**Comment by redapple** [comment]
@aohan237 , I'm closing this in favor of your message on the mailing list https://groups.google.com/d/msg/scrapy-users/dB8Avs8tX-E/ggFEqyo0GAAJ
