### ISSUE TITLE
How could I pass parameter to ImagesPipeline from my spider?

### ISSUE THREAD

**Issue by seaguest** [scrapy/scrapy#1844]
Hello,

I want to download all images on one page and save them in some folder whose name depends on the original request URL.

For example, I want to scrape example.com/123.html

I want to download all images on that page and put them under ./123 folder.
Is it possible ?

How could I pass parameter to ImagesPipeline from my spider?

**Comment by djunzu** [comment]
First, I suggest you post questions like "how to" or "is it possible" in [StackOverflow](http://stackoverflow.com/) or [scrapy-users mailing list](https://groups.google.com/forum/#!forum/scrapy-users).

Currently the place where images are saved is hard coded: [full/\<sha1(request.url)\>.jpg](https://github.com/scrapy/scrapy/blob/master/scrapy/pipelines/images.py#L143). You would need to modify this function to accomplish that.

**Comment by seaguest** [comment]
finally I decide to use the original path, only change the domain section to save the image.
