### ISSUE TITLE
EXPIRES in Files/ImagesPipeline should be a instance attribute and not a class attribute

### ISSUE THREAD

**Issue by djunzu** [scrapy/scrapy#1850]
Currently `EXPIRES` in `FilesPipeline` and `ImagesPipeline` is defined as a class attribute. When running more than one spider with `CrawlerProcess` it is impossible to have different expires values for different spiders. Changing the `EXPIRES` attribute to an instance attribute solves the problem.

(I would do a pull request, but I have no idea how to properly update the tests.)

**Comment by kmike** [comment]
+1: e.g. [here](https://github.com/scrapy/scrapy/blob/ebef6d7c6dd8922210db8a4a44f48fe27ee0cd16/scrapy/pipelines/files.py#L232) pipeline object should be created first, and EXPIRES attribute (as well as other attributes) should be set on it. It looks like a bug.

I think test can be simple - create a new FilesPipeline / ImagesPipeline using from_crawler method, passing settings with custom EXPIRES, and check that class attribute is not changed.

**Comment by kmike** [comment]
Also, we're usually putting option default values in `settings/default_settings.py`, not in class attributes.

**Comment by djunzu** [comment]
When I said "I have no idea how to properly update the tests", I wanted to say: I have no idea how to use the test framework! :)
But I don't want to manually fix it every time I upgrade Scrapy, so I have tried to write a fix.
