### ISSUE TITLE
Can't get attribute value which attribute name start with #?

### ISSUE THREAD

**Issue by cage1618** [scrapy/scrapy#1858]
for example, the page source is bellow:
`<img src="http://www1.pcbaby.com.cn/images/blank.gif" #src="http://img0.pcbaby.com.cn/pcbaby/1603/10/2799244_yunzaoqi0310-11.jpg"  />`

But I get next in scrapy:
`<img src="http://www1.pcbaby.com.cn/images/blank.gif" />`

I can't get the attribute "#src" in scrapy.

How can I get that? please help me! Hope your reply! thanks!

**Comment by kmike** [comment]
It looks like an lxml issue. I can't get the value of this attribute either.

**Comment by Digenis** [comment]
Actually it is stripped from the parsel document, parsed as xml or html.
In xml it is an invalid attribute name ([xml attribute namestartchar](https://www.w3.org/TR/REC-xml/#NT-NameStartChar))
but in html it is allowed ([html attribute name](https://www.w3.org/TR/html-markup/syntax.html#attribute-name))

**Comment by kmike** [comment]
Yeah, I mean I can't get value using lxml.html parsing functions which parsel uses.

**Comment by cage1618** [comment]
How can I resolve this issue?

**Comment by kmike** [comment]
I think that unfortunately the path of a least resistance is to write a regex for `response.body_as_unicode()`. It looks like when body is parsed by lxml this attribute is gone.

It also makes sense to move this ticket to https://github.com/scrapy/parsel.

**Comment by redapple** [comment]
`lxml/libxml2` has trouble with this input, but `html5lib` and `beautifulsoup` can cope (although with some specificities on the XPath expression to use)

Plain lxml:

```
$ ipython
Python 2.7.9 (default, Apr  2 2015, 15:33:21) 

In [1]: t = '''<html><body><img src="http://www1.pcbaby.com.cn/images/blank.gif" #src="http://img0.pcbaby.com.cn/pcbaby/1603/10/2799244_yunzaoqi0310-11.jpg" /></body></html>'''

In [2]: import lxml.html

In [3]: lxml_doc = lxml.html.fromstring(t)

In [4]: lxml_doc.xpath('//img/@*')
Out[4]: ['http://www1.pcbaby.com.cn/images/blank.gif']

```

Let's try with `html5lib`

```
In [6]: from lxml.html import tostring, html5parser

In [7]: html5_doc = html5parser.document_fromstring(t)
/home/paul/.virtualenvs/scrapy10/local/lib/python2.7/site-packages/html5lib/ihatexml.py:254: DataLossWarning: Coercing non-XML name
  warnings.warn("Coercing non-XML name", DataLossWarning)

In [8]: html5_doc.xpath('//img/@*')
Out[8]: []

In [9]: html5_doc.xpath('//@*')
Out[9]: 
['http://www1.pcbaby.com.cn/images/blank.gif',
 'http://img0.pcbaby.com.cn/pcbaby/1603/10/2799244_yunzaoqi0310-11.jpg']

In [15]: tostring(html5_doc)
Out[15]: '<html:html xmlns:html="http://www.w3.org/1999/xhtml"><html:head></html:head><html:body><html:img src="http://www1.pcbaby.com.cn/images/blank.gif" U00023src="http://img0.pcbaby.com.cn/pcbaby/1603/10/2799244_yunzaoqi0310-11.jpg"></html:img></html:body></html:html>'

```
It seems `html5lib` has the attribute accessible using "U00023src", not "#src".
And you need to pass namespace

```
In [16]: html5_doc.xpath('//html:img/@*', namespaces={"html": "http://www.w3.org/1999/xhtml"})
Out[16]: 
['http://www1.pcbaby.com.cn/images/blank.gif',
 'http://img0.pcbaby.com.cn/pcbaby/1603/10/2799244_yunzaoqi0310-11.jpg']

In [17]: html5_doc.xpath('//html:img/@U00023src', namespaces={"html": "http://www.w3.org/1999/xhtml"})
Out[17]: ['http://img0.pcbaby.com.cn/pcbaby/1603/10/2799244_yunzaoqi0310-11.jpg']
```


Let's try with beautifulsoup parser

```
In [18]: from lxml.html import soupparser

In [19]: bs_doc = soupparser.fromstring(t)
/home/paul/.virtualenvs/scrapy10/local/lib/python2.7/site-packages/bs4/__init__.py:166: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

To get rid of this warning, change this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "html.parser")

  markup_type=markup_type))

In [20]: bs_doc.xpath('//img/@*')
Out[20]: 
['http://img0.pcbaby.com.cn/pcbaby/1603/10/2799244_yunzaoqi0310-11.jpg',
 'http://www1.pcbaby.com.cn/images/blank.gif']

In [21]: bs_doc.xpath('//img/@#src')
---------------------------------------------------------------------------
XPathEvalError                            Traceback (most recent call last)
<ipython-input-21-2d48dd3d4138> in <module>()
----> 1 bs_doc.xpath('//img/@#src')

src/lxml/lxml.etree.pyx in lxml.etree._Element.xpath (src/lxml/lxml.etree.c:61854)()

src/lxml/xpath.pxi in lxml.etree.XPathElementEvaluator.__call__ (src/lxml/lxml.etree.c:178516)()

src/lxml/xpath.pxi in lxml.etree._XPathEvaluatorBase._handle_result (src/lxml/lxml.etree.c:177421)()

XPathEvalError: Invalid expression

In [22]: bs_doc.xpath('//img/@*[name()="#src"]')
Out[22]: ['http://img0.pcbaby.com.cn/pcbaby/1603/10/2799244_yunzaoqi0310-11.jpg']
```

**Comment by redapple** [comment]
@cage1618 , I'm closing this issue as it's not technically scrapy-related, and you can parse the raw response.body_as_unicode() with lxml, html5lib and beautifulsoup.

Please open an issue in https://github.com/scrapy/parsel, for example to be able to choose which parser to use (instead of the default one)

**Comment by cage1618** [comment]
ok, thank you very much!

**Comment by xinyuan73** [comment]
I have the same question, but I found #src changed to src2：
>>> response.xpath('//*[@id="JfocusPic"]/div[2]/ul/li/a/img').extract()
[u'<img width="360" height="270" alt="\u534e\u4e3aMate8/3GB+32GB\u7248 \u524d\u89c6" src="http://www.pconline.com.cn/blank.gif">', u'<img width="360" height="270" alt="\u534e\u4e3aMate8/3GB+32GB\u7248 45\u5ea6\u524d\u89c6" src2="http://img.pconline.com.cn/images/product/5807/580761/45.jpg" src="http://www.pconline.com.cn/blank.gif">', u'<img width="360" height="270" alt="\u534e\u4e3aMate8/3GB+32GB\u7248 \u4fa7\u89c6" src2="http://img.pconline.com.cn/images/product/5807/580761/c.jpg" src="http://www.pconline.com.cn/blank.gif">', u'<img width="360" height="270" alt="\u534e\u4e3aMate8/3GB+32GB\u7248 \u540e\u89c6" src2="http://img.pconline.com.cn/images/product/5807/580761/h.jpg" src="http://www.pconline.com.cn/blank.gif">']

so I try:
response.xpath('//*[@id="JfocusPic"]/div[2]/ul/li/a/img/@src2').extract()
[u'http://img.pconline.com.cn/images/product/5807/580761/45.jpg', u'http://img.pconline.com.cn/images/product/5807/580761/c.jpg', u'http://img.pconline.com.cn/images/product/5807/580761/h.jpg']

It worked well
