### ISSUE TITLE
Trouble executing code on spider close

### ISSUE THREAD

**Issue by johtso** [scrapy/scrapy#1862]
I have a `CrawlSpider` that needs to batch up it's items and send them off in groups once the crawl has completely finished.

I initially saw the `closed` method that can be defined on a scraper which is supposed to be called with the `reason`. I found that this didn't work. The base scraper `close` is called, but when that calls my class's `closed` method it goes into some Twisted deferred code and never seems to be executed.

I tried the hacky solution of just overriding `close` instead, but yielding `Item`s from there doesn't seem to work.

I then tried solving the problem at the pipeline level.

I added this to my pipeline, but again, the method doesn't seem to be called:
```
    @classmethod
    def from_crawler(cls, crawler):
        pipeline = cls()
        crawler.signals.connect(pipeline.spider_closed, signals.spider_closed)

    def spider_closed(self, *args, **kwargs):
        print args, kwargs
        1/0
```

Am I misunderstanding something / doing something wrong?

**Comment by Digenis** [comment]
Think of `from_crawler` as an "alternative `__new__`" method,
it has to return the initialized class.
Search this method in the documentation
to see how you can use it correctly.

This issue is not a bug and you can close it.

**Comment by johtso** [comment]
@Digenis ah, oops! Thanks for pointing out that mistake.

Do you have any idea what might be going on with the `Spider.closed` approach?

**Comment by Digenis** [comment]
You shouldn't use Spider.closed to yield items.
You would need to access the pipeline from the attached scraper
but even if this works, nothing guarantees that in some other scrapy version
pipelines will be teared down before the spider.
Better connect a spider_idle signal handler.

What you are looking for should be suggested in the missing feature #740.
#740 has 2 incomplete attempts to implement (#1051, #1443)
that haven't yet implemented items yielding.

**Comment by johtso** [comment]
Ah okay, thanks for the detailed explanation!

Listening for the close signal in my pipeline seems to be working well.
