### ISSUE TITLE
Move from boto2/botocore to boto3

### ISSUE THREAD

**Issue by jersub** [scrapy/scrapy#1866]
Hi all,

Scrapy moved to a hybrid use of both `boto2`/`botocore` since PR #1761. I feel maintaining two AWS libraries would be difficult on the long term, and testing would be even more painful. I see no point for keeping `boto2` support (apart for some needed backward compatibility) since `botocore` supports Python 2.7 as well (see https://botocore.readthedocs.org/en/latest/).

Besides, I see some benefits for using `boto3` instead of `botocore`. It supports Python 2.7 as well, see https://github.com/boto/boto3/blob/develop/tox.ini. Actually it stands at a higher level and would allow us to fix bug #960 in few lines of code (cf. multipart upload, see http://boto3.readthedocs.org/en/latest/reference/customizations/s3.html#module-boto3.s3.transfer).

Anyway issue #1790 (i.e. S3 testing) would have to be handled at the same time.

**Comment by lopuhin** [comment]
+1 for using ``boto3`` for S3 file uploads. I started with signing s3 requests, and there ``botocore`` felt more convenient than ``boto3`` (and even still too high-level). But for file uploads ``boto3`` indeed looks much better.

**Comment by wRAR** [comment]
As boto support will be unused after dropping Python 2, it may be a good idea to decide if we should replace it with boto3 support, remove boto support code and boto/botocore conditionals or keep that for someone who will implement boto3 support.

**Comment by Gallaecio** [comment]
Since we do not have to choose one or another, I wonder if we should not just close this issue, and allow contributors to introduce `boto3` as a dependency if they wish to fix issues or introduce enbhancements.

**Comment by wRAR** [comment]
I think it's time to close this.
