### ISSUE TITLE
Allow to add custom metadata to Response

### ISSUE THREAD

**Issue by kmike** [scrapy/scrapy#1877]
Currently it is not possible to attach a custom attribute to Response in a middleware because `replace` method won't keep it. There are workarounds (e.g. putting objects to response.flags), but they are ugly.

What do you think about adding an attribute to Response where user can put anything, similar to Request.meta?

**Comment by kmike** [comment]
Almost the same issue: https://github.com/scrapy/scrapy/issues/1453

**Comment by kmike** [comment]
One workaround is to create custom Response subclasses and use ``response.replace(cls=MyCustomResponse)`` in a middleware.

**Comment by joeharrison714** [comment]
I'd like to try to implement this, does anyone have any newer thoughts about it that could lead me in the right direction?
