### ISSUE TITLE
Scrapy installation in Ubuntu: pkg_resources.DistributionNotFound: attrs

### ISSUE THREAD

**Issue by nikhilgeo** [scrapy/scrapy#1885]
I installed scrapy by following the tutorial here, the installation was success but once I try to setup a project by it shows

```
nikhil@nikhil:~$ scrapy startproject tutorial
Traceback (most recent call last):
  File "/usr/local/bin/scrapy", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 444, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 725, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: attrs
nikhil@nikhil:~$ pkg_resources.DistributionNotFound: attrs
pkg_resources.DistributionNotFound:: command not found
```
Any idea about how to solve this error ..? I couldn't find any useful pointers via Google.

**Comment by kmike** [comment]
This error may happen when some software is installed without installing all its dependencies. How did you install Scrapy? Which parts of tutotial did you follow?

This shouldn't happen if you use pip and virtualenv. Likely problem will go away if you reinstall Scrapy. I'm not sure what depends on `attrs` package. Installing Python packages to dist-packages is a bad practice which leads to all kinds of issues; we should discourage that.

**Comment by nikhilgeo** [comment]
Hi kmike,
I installed using the below command.

`sudo pip install Scrapy
`

**Comment by kmike** [comment]
@nikhilgeo could you try installing Scrapy in virtualenv? 

Argh, it is at least 6th time someone installs scrapy using sudo and it fails (https://github.com/scrapy/scrapy/issues/1557, https://github.com/scrapy/scrapy/issues/1314, https://github.com/scrapy/scrapy/issues/1342, https://github.com/scrapy/scrapy/issues/1452, https://github.com/scrapy/scrapy/issues/1865). I think we should really make it clear in http://doc.scrapy.org/en/latest/intro/install.html that even on Linux it is better to use virtualenv or conda, and that instaling Scrapy using sudo is not a good idea for various reasons (ancient pip versions, conflicts with other packages, incomplete installs).

**Comment by nikhilgeo** [comment]
Hi I tried the virtualenv, still I'm hitting the wall, below are the steps I followed:
```
pip install virtualenv
cd my_project_folder
virtualenv -p /usr/bin/python3 venv
source venv/bin/activate
pip install scrapy
scrapy startproject tutorial

AttributeError: 'dict' object has no attribute 'itervalues'
```
I did the above again without using python3, my default python version is 2.7 and scrapy worked this time...I don't understand what is the issue with python3, but this is enough for me to get started....Thanks @kmike for the pointers

**Comment by redapple** [comment]
To work with Python3, you need at least scrapy 1.1 RC3.
In your Py3 virtualenv, can you try this?
`pip install scrapy==1.1.0rc3`?

**Comment by nikhilgeo** [comment]
Oh yeah it worked for Python3..!!
Thanks @redapple
