### ISSUE TITLE
Installation on shared hosting, is it possible

### ISSUE THREAD

**Issue by Spereicle** [scrapy/scrapy#1886]
Regrets - Novice to python.

Is it possible to install Scrapy in a shared hosting environment with shell access.

'pip install scrapy' does run -- and results in various warnings and errors, including:

error: could not create '/usr/local/lib/python2.7/dist-packages/scrapy': Permission denied

Can the package be placed in my user account area?

The complete log is attached.

Thanks, and sorry for the rather basic questions.
[pip_scrapy.txt](https://github.com/scrapy/scrapy/files/192505/pip_scrapy.txt)

**Comment by djunzu** [comment]
Hi.

I suggest you post questions like "how to" or "is it possible" in [StackOverflow](http://stackoverflow.com/) or [scrapy-users mailing list](https://groups.google.com/forum/#!forum/scrapy-users). You will have more lucky getting a concrete answer there!

As it is a shared hosting, you have no write access to the system (like /usr/...). If you have write permission to your home, you could install Scrapy using `python setup.py install --user`: it will get placed in your home. But again, you will get a better answer in the above places.
