### ISSUE TITLE
Why engine fetch requests from scheduler first other than the start_urls generated ones?

### ISSUE THREAD

**Issue by cockcrow** [scrapy/scrapy#1888]
From [HERE](https://github.com/scrapy/scrapy/blob/master/scrapy/core/engine.py#L121) I found that Scrapy engine fetch requests from scheduler before the `start_urls` generated ones.
In my usage, I enqueued thousands of start urls (which from various domains) to the queue and the crawling goes not so fast (maybe networking issues). The problems comes up with me was that the spider itself extracts links and follows them, then Scrapy will fetch the requests from scheduler. It makes the concurrency lower.

I would like to learn about the design purpose of this mechanism.
BRs.

**Comment by redapple** [comment]
If you want help understanding a feature or a component, please consider posting your question on the [scrapy-users mailing-list](https://groups.google.com/forum/#!forum/scrapy-users) instead.

This issue tracker is (mainly) for [reporting bugs](http://doc.scrapy.org/en/latest/contributing.html#reporting-bugs).

**Comment by cockcrow** [comment]
Migrated to [https://groups.google.com/forum/#!topic/scrapy-users/NkrFHn_3cmE](https://groups.google.com/forum/#!topic/scrapy-users/NkrFHn_3cmE)
And thanks for help.
