### ISSUE TITLE
Add dont_cache flag

### ISSUE THREAD

**Issue by shaneaevans** [scrapy/scrapy#19]
Reported by binarybug on Trac http://dev.scrapy.org/ticket/325

If a website is using a session to maintain the client's state than resuming a crawl doesn't work when cache is enabled. If we can instruct scrapy not to cache some requests than resuming a crawl would create a session when those requests are encountered and subsequent requests wouldn't fail e.g.

```python
yield Request(' http://www.example.com', meta={'dont_cache': True}) 
```

**Comment by kmike** [comment]
Fixed by #821.
