### ISSUE TITLE
CrawlerProcess doesn't load Item Pipeline component

### ISSUE THREAD

**Issue by zouge** [scrapy/scrapy#1904]
If I using `scrapy crawl spider_name` , everything is fun. BUT When I using CrawlerProcess to wrote my spider,  I found  CrawlerProcess doesn't load Item Pipeline component !

**Comment by redapple** [comment]
@zouge, do you have sample code reproducing the issue?

**Comment by swizzard** [comment]
@zouge if you're using `CrawlerProcess` outside the 'normal' command-line process, you have to load in your settings yourself:

	from scrapy.crawler import CrawlerProcess
	from scrapy.settings import Settings
	
	from my_project import settings as my_settings
	
	crawler_settings = Settings()
	crawler_settings.setmodule(my_settings)
	process = CrawlerProcess(settings=crawler_settings)

**Comment by zouge** [comment]
@swizzard  thanks, it's work .

**Comment by kmike** [comment]
@zouge there is also `get_project_settings` function; and example from [docs](http://doc.scrapy.org/en/latest/topics/practices.html#run-scrapy-from-a-script):

```py
from scrapy.crawler import CrawlerProcess
from scrapy.utils.project import get_project_settings

process = CrawlerProcess(get_project_settings())

# 'followall' is the name of one of the spiders of the project.
process.crawl('followall', domain='scrapinghub.com')
process.start() # the script will block here until the crawling is finished
```

**Comment by kmike** [comment]
Hey @gun20,

I'm not sure what the issue is, as in logs there are "I am processing ..." messages, as well as "Opening Spider: .." messages, so the pipeline is clearly called.

**Comment by gun20** [comment]
Do you have perhaps a code that uses the multiprocess library or something that is not using CrawlerProcess? Maybe a code to run with CrawlerRunner?

**Comment by kmike** [comment]
@gun20 sorry, I don't quite understand your questions. What are you trying to achieve? The code you pasted seems to work fine according to the log you've pasted. For general support there are better channels, like https://stackoverflow.com (use tag "scrapy"); we're using this issue tracker for Scrapy bugs and enhancement proposals.

**Comment by gun20** [comment]
The problem is that the process.crawl() does not fetch any item - but when i run the command from command prompt it does all correctly. So I'm trying to understand what's wrong with this:

```
def runspider(name):
    configure_logging(install_root_handler=False)
    logging.basicConfig(
        #filename='log/%s.log' % name,
        filename = "C:\\Users\\1020949\\Documents\\spidertest\\logs\\stdout.log",
        format='%(levelname)s %(asctime)s: %(message)s',
        level=logging.DEBUG
    )
    process = CrawlerProcess(get_project_settings())
    try:
        logging.info('runspider start spider:%s' % name)
        #process.stop()
        process.crawl(name)
        #process.start()
    except Exception as e:
        logging.exception('runspider spider:%s exception:%s' % (name, e))

    logging.debug('finish this spider:%s\n\n' % name) 
```

if "process_start()" is uncomment i get the error "ReactornotRestartable"
Like this, the script runs but no item is saved.

**Comment by kmike** [comment]
`process.start()` must be called once; if you're calling it several times, you'll get ReactornotRestartable error. So if you want to use CrawlerProcess, you should structure your code in a way there is a single CrawlerProcess instance, and `process.start` is called once.

**Comment by 1315groop** [comment]
Have `Enabled item pipelines:[]` when running under celery:
`@register()
class SomeBy(Task):

    def run(self, *args, **kwargs):
        logger.info("started")
        c = CrawlerProcess(get_project_settings())
        c.crawl(SomeSpider)
        c.start()
        logger.info("ended")`

**Comment by Gallaecio** [comment]
@1315groop I’m sure, if you check the return value of `get_project_settings()`, that it will be empty.

`get_project_settings()` only works if the current working directory is a Scrapy project. You must either change the current working directory accordingly before calling `get_project_settings()` or pass the settings in a different way (e.g. a manually-defined dictionary of settings). See https://stackoverflow.com/q/31662797/939364

**Comment by chengyangliu47** [comment]
> crawler_settings

Every time someone solved my tiny bug I fell that I am understood, thank you so much!

**Comment by rawheel** [comment]
> @zouge if you're using `CrawlerProcess` outside the 'normal' command-line process, you have to load in your settings yourself:
> 
> ```
> from scrapy.crawler import CrawlerProcess
> from scrapy.settings import Settings
> 
> from my_project import settings as my_settings
> 
> crawler_settings = Settings()
> crawler_settings.setmodule(my_settings)
> process = CrawlerProcess(settings=crawler_settings)
> ```

It worked, thanks I spent hrs on this issue
