### ISSUE TITLE
'Selector' object has no attribute 're_first'

### ISSUE THREAD

**Issue by VinGarcia** [scrapy/scrapy#1907]
I was trying to use the re_first() described on the Selector documentation page:
  http://doc.scrapy.org/en/latest/topics/selectors.html

I am testing it on scrapy shell, and I got the error:
```python
from scrapy.selector import Selector
>>> body = '<html><body><span>good</span></body></html>'
>>> Selector(text=body).re_first
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: 'Selector' object has no attribute 're_first'
```

What am I missing?

**Comment by redapple** [comment]
`.re_first()` is available [on `SelectorList`](https://parsel.readthedocs.org/en/latest/usage.html#parsel.selector.SelectorList.re_first)

`SelectorList` is what you get when applying `.xpath()` or `.css()` on a `Selector` (or `SelectorList` when you chain XPath/CSS calls)

**Comment by kmike** [comment]
I think it makes sense to add .re and .re_first for Selector. In this case we should make sure that body is parsed lazily - it shouldn't be parsed when only .re methods are used.

**Comment by VinGarcia** [comment]
Thank you guys. I agree with @kmike it is an expected behavior I think. It also makes more sense in my real use case which is something like this:

```python
>>> sel_str='select#chapter.form-control option[value]'
>>> for sel in response.css(sel_str):
...   # sel.extract() == "<option value="96">67. Atomic Physics</option>"
...   print sel.re_first('>([0-9]{2})\.')
Traceback (most recent call last):
  File "<console>", line 2, in <module>
AttributeError: 'Selector' object has no attribute 're_first'
```

I found a workaround using `.re()`, but not very clean

**Comment by Tethik** [comment]
+1 to implement this. Although I'm guessing this issue now belongs to the parsel repo. Will recreate this issue there and see if I can make a PR to do this.

**Comment by kmike** [comment]
@Tethik yeah, parsel is a right repo now 👍

**Comment by kmike** [comment]
Moved to https://github.com/scrapy/parsel/issues/52.
