### ISSUE TITLE
Scrapy==0.24.1 not compatible with w3lib==1.14.1

### ISSUE THREAD

**Issue by tom-aa** [scrapy/scrapy#1917]
When I install Scrapy 0.24.1, it will automatically install w3lib 1.14.1, and this will made scrapy failed:
(w3lib 1.13 works fine)
error log:
  File "/usr/local/lib/python2.7/dist-packages/scrapy/http/request/__init__.py", line 26, in __init__
    self._set_url(url)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/http/request/__init__.py", line 52, in _set_url
    self._url = escape_ajax(safe_url_string(url))
  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/url.py", line 102, in escape_ajax
    defrag, frag = urlparse.urldefrag(url)
AttributeError: 'function' object has no attribute 'urldefrag'

**Comment by redapple** [comment]
hi @tom-aa , thanks for reporting.
There's an issue on w3lib about this already : https://github.com/scrapy/w3lib/issues/54
There's a fix for it to be merged asap: https://github.com/scrapy/w3lib/pull/55
we aim to fix this in w3lib 1.14.2 this week.

**Comment by redapple** [comment]
@tom-aa , w3lib 1.14.2 is out and available on PyPI.
could try it?

**Comment by redapple** [comment]
See https://github.com/scrapy/w3lib/releases/tag/v1.14.2
