### ISSUE TITLE
Failed installing scrapy

### ISSUE THREAD

**Issue by AFAgarap** [scrapy/scrapy#1922]
`sudo pip3 install scrapy`

When I'm installing scrapy in my computer, this is the error I'm getting:

Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-xfj07fck/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-h3d3uz53-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-xfj07fck/cffi/

--
Screenshots
--
![deepinscreenshot20160411234951](https://cloud.githubusercontent.com/assets/11130276/14433328/80c2e06c-ffd3-11e5-87eb-83d71a9e0447.png)
![deepinscreenshot20160411235007](https://cloud.githubusercontent.com/assets/11130276/14433329/80d4ccaa-ffd3-11e5-8d2e-205421dd1bda.png)
![deepinscreenshot20160411235035](https://cloud.githubusercontent.com/assets/11130276/14433330/80e2bef0-ffd3-11e5-9c21-6d75b240fb69.png)
--
My computer runs on Deepin Linux OS (15.1).
I already tried upgrading `setuptools`: `sudo pip3 install --upgrade setuptools`. Still getting the same error. Thank you in advance for helping!

**Comment by redapple** [comment]
@AFAgarap ,
you need a few dev headers packages installed on your machine to install Scrapy.

Here's an example Dockerfile using Ubuntu 14.04: https://gist.github.com/redapple/cd9c31eeab8c4d5ea9eef7b200c3d4d0

Deepin looks Debian-based, so you should be good with:

```
apt-get install -y \
    python3 \
    python-dev \
    python3-dev
```
for `cryptography` dependency:
```
apt-get install -y \
    build-essential \
    libssl-dev \
    libffi-dev
```

for `lxml`
```
apt-get install -y \
    libxml2-dev \
    libxslt-dev
```

**Comment by AFAgarap** [comment]
![deepinscreenshot20160412233734](https://cloud.githubusercontent.com/assets/11130276/14465970/8c510ffa-0107-11e6-9998-ea404377b5f4.png)

--
Thank you for your kind response. I did what you suggested, and scrappy was successfully installed into my computer system. Cheers! :)

**Comment by redapple** [comment]
Thanks for the heads up!
Happy scraping

**Comment by AFAgarap** [comment]
Thank you! :)

**Comment by khawajaosama** [comment]
Thanks <3
