### ISSUE TITLE
Process died, reason None

### ISSUE THREAD

**Issue by berkantaydin** [scrapy/scrapy#1929]
My spider working 12 hours after stop - endless crawling - then scrapyd said
`Process died: exitstatus=None  project='default' ...`
How can solve this ? Please, i need more verbose. Is this a memory issue ?

**Comment by redapple** [comment]
@berkantaydin , this is more for https://github.com/scrapy/scrapyd or [scrapy-users mailing list](https://groups.google.com/forum/#!forum/scrapy-users) 
You'd have to provide more information on your setup though.
It's kinda hard to help you with this single `Process died` lines

**Comment by berkantaydin** [comment]
thank you, i guess its a memory problem and i will use disk now.
