### ISSUE TITLE
Another IOError: "Not a gzipped file"

### ISSUE THREAD

**Issue by vkrest** [scrapy/scrapy#193]
Take a look at 'httpcompression' middleware and 'sitemap' middleware.
If you will try to download some gzipped file then 'httpcompression' middleware will decompress it first.
See it here:
https://github.com/scrapy/scrapy/blob/master/scrapy/contrib/downloadermiddleware/httpcompression.py#L36

Then 'sitemap' will try to decompress it again and will rise the IOError here:
https://github.com/scrapy/scrapy/blob/master/scrapy/contrib/spiders/sitemap.py#L57

In my point of view we have to leave only one place for decompression and it will be reasonable if it will be 'httpcompression'.

**Comment by askerlee** [comment]
Hi guys, I still get this error while downloading amazon sitemap .gz files. I checked the http headers and found Amazon keeps "Content-Encoding: x-gzip" and has changed "Content-Type" to "application/octet-stream". Then the condition "content_encoding and not is_gzipped" in httpcompression middleware is True and this file is decompressed. Later sitemap.py finds the suffix is ".gz" and then calls gunzip again, causing the program to abort.

I changed sitemap.py a little bit to ignore the decompression exception. Now it's fine.
