### ISSUE TITLE
SSL errors crawling https sites using proxies

### ISSUE THREAD

**Issue by lhuaizhong** [scrapy/scrapy#1936]
I'm unable to scrape below https sites through https supported proxies, have tried version 1.0.5 and 1.1.0rc3. I'm using proxymesh, but https://www.python.org and others work well.

(env-scrapy-1.1) D:\work>scrapy version -v
Scrapy    : 1.1.0rc3
lxml      : 3.6.0.0
libxml2   : 2.9.0
Twisted   : 16.1.1
Python    : 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)]
pyOpenSSL : 16.0.0 (OpenSSL 1.0.2g  1 Mar 2016)
Platform  : Windows-10-10.0.10586

`2016-04-18 12:56:25 [scrapy] DEBUG: Gave up retrying <GET https://xxx.xxx.xxx/> (failed 3 times): [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', 'SSL23_GET_SERVER_HELLO', 'sslv3 alert handshake failure')]>]
2016-04-18 12:56:25 [scrapy] ERROR: Error downloading <GET https://xxx.xxx.xxx/>: [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', 'SSL23_GET_SERVER_HELLO', 'sslv3 alert handshake failure')]>]`

=======================

D:\work>scrapy version -v
Scrapy    : 1.0.5
lxml      : 3.5.0.0
libxml2   : 2.9.3
Twisted   : 15.5.0
Python    : 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)]
pyOpenSSL : 0.15.1 (OpenSSL 1.0.2f  28 Jan 2016)
Platform  : Windows-10-10.0.10586

`2016-04-18 12:58:29 [scrapy] ERROR: Error downloading <GET https://xxx.xxx.xxx/>: [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', 'SSL23_GET_SERVER_HELLO', 'sslv3 alert handshake failure')]>]`

The https://github.com/scrapy/scrapy/issues/1429#issuecomment-131782133 doesn't work as well.

May anyone help? thanks a lot in advance.

**Comment by redapple** [comment]
@lhuaizhong , please provide the websites you are trying to connect to.

**Comment by lhuaizhong** [comment]
@redapple, have sent you in email, thanks.

**Comment by redapple** [comment]
@lhuaizhong , it looks related to SNI not being sent in TLS `ClientHello` when using `TunnelingAgent` vs. regular `Agent`.

**Comment by redapple** [comment]
@lhuaizhong , I may be onto something with https://github.com/scrapy/scrapy/issues/1938 , but I haven't tested much yet.

**Comment by lhuaizhong** [comment]
@redapple , I upgraded scrapy to 1.1.0rc3, using your patch in file http11.py, it works well right now.

Thanks Paul!
