### ISSUE TITLE
It's can not be real time updated, when I use request.meta pass a dict argument to a callback 

### ISSUE THREAD

**Issue by authen29** [scrapy/scrapy#1937]
This is the part of codes:
```py
def detail_page_request(self, response):
      ct_item = response.meta.get('ct_item')
      ct_item['title'] = title
      req = Request(url, headers=self.headers, meta={'ct_item':ct_item, })
      return req
      
def parse(self, response):
      ct_item = response.meta.get("ct_item")
     print ct_item
     
```
I get the ct_item not updated by the code:`ct_item['title'] = title`

**Comment by redapple** [comment]
@authen29 , your code snippet is not self-contained and your issue description is not clear.
Please provide a [minimal, complete, verifiable example](http://doc.scrapy.org/en/master/contributing.html#reporting-bugs) showing the issue
