### ISSUE TITLE
ssl handshake failure (openssl bug in Ubuntu 12.04)

### ISSUE THREAD

**Issue by pablohoffman** [scrapy/scrapy#194]
Due to this openssl bug:
https://bugs.launchpad.net/ubuntu/+source/openssl/+bug/965371

Scrapy is failing to retrieve some pages via https such as this one:
https://www.onekingslane.com/login

More information about client/server version compatibility can be found here:
http://docs.python.org/dev/library/ssl.html#ssl.wrap_socket

Other pages that talk about this issue:
http://askubuntu.com/questions/116020/python-https-requests-urllib2-to-some-sites-fail-on-ubuntu-12-04-without-proxy

The error goes like this:
    2012-11-15 16:22:57-0200 [default] ERROR: Error downloading <GET https://www.onekingslane.com/login>: [('SSL routines', 'SSL23_READ', 'ssl handshake failure')]

**Comment by kadnan** [comment]
@birdsarah  Can you please in which routine should I test it and how?

**Comment by birdsarah** [comment]
@kadnan - sorry this is so long ago I don't remember the details and I don't have a 12.04 system to test against anymore since 14.04 became the Ubuntu LTS version :(
