### ISSUE TITLE
Doc Issue - Installing on Fedora 23 (possibly other rhel based as well)

### ISSUE THREAD

**Issue by XakV** [scrapy/scrapy#1946]
Hello - this is a paste of how I got scrapy to successfully install on Fedora 23. It may be of use to other RHEL based distros as well. It's a bit tricky now that Python3 is the default.

(sorry about the cut and paste - it's late)
Pre-Reqs;

python-devel, python-rpm-macros, libffi-devel, redhat-rpm-config, openssl-devel, libxml2-devel, libxml-devel, python-lxml, python-libxml2, python-cffi, glib2-devel gnet2-devel libxslt-devel

and then finally

python2 -m pip install --user --upgrade pip 

(in a virtualenv)

I might've missed something, but hope this helps.

**Comment by kmike** [comment]
@gr3yman nice! Would you mind sending a PR with these install instructions (https://github.com/scrapinghub/splash/blob/master/docs/install.rst)?

**Comment by kmike** [comment]
@gr3yman nice! Would you mind sending a PR with this package list (https://github.com/scrapy/scrapy/blob/master/docs/intro/install.rst)?

**Comment by gr3yman** [comment]
Sure thing..

**Comment by Gallaecio** [comment]
Following the current installation steps from the documentation should work for any Linux distribution, and for both Python 2 and Python 3.
