### ISSUE TITLE
Scrapy 1.1.0rc3 error on fetch command

### ISSUE THREAD

**Issue by rafaelcapucho** [scrapy/scrapy#1953]
Hello,

When I run the `fetch` command I get errors:
https://paste.ee/r/35fj7

The spider is fine considering that I can run the `crawl` command normally.

Using Py 3.5.1

**Comment by redapple** [comment]
@rafaelcapucho , can you paste relevant parts of your spider?
I'm able to reproduce the exception if I override the `__init__` method without support of variable number of arguments, 
i.e., with the following, `scrapy fetch --spider httpbin https://httpbin.org/get` fails:

```
class HttpbinSpider(scrapy.Spider):
    name = "httpbin"
    allowed_domains = ["httpbin.org"]
    start_urls = (
        'https://httpbin.org/get',
    )

    def __init__(self):
        self.something = 42

    def parse(self, response):
        self.logger.info("HttpbinSpider.parse(%r)" %  response)
```

vs. this which works:

```
class HttpbinSpider(scrapy.Spider):
    name = "httpbin"
    allowed_domains = ["httpbin.org"]
    start_urls = (
        'https://httpbin.org/get',
    )

    def __init__(self, *args, **kwargs):
        super(HttpbinSpider, self).__init__(*args, **kwargs)
        self.something = 42

    def parse(self, response):
        self.logger.info("HttpbinSpider.parse(%r)" %  response)
```

Note: same happens with Scrapy 1.0.5. It's not related to Scrapy 1.1

**Comment by rafaelcapucho** [comment]
@redapple This is the relevant part of my spider: https://paste.ee/p/0Amww

I made the changes you suggested and It is working properly now:

```
    def __init__(self, *args, **kwargs):
        CrawlSpider.__init__(self, *args, **kwargs)
        logging.config.fileConfig('python.conf', disable_existing_loggers=False)
        self.emit = logging.getLogger('worker')
```
Thank you for your help!

**Comment by redapple** [comment]
Perfect @rafaelcapucho !
Happy scraping
