### ISSUE TITLE
disable 'stable' version on readthedocs.org

### ISSUE THREAD

**Issue by kmike** [scrapy/scrapy#1956]
Currently 'latest' points to 1.0, 'stable' points to 1.1 and 'master' points to 1.2. I.e. latest is the oldest, and stable is not released yet. 

What do you think about removing 'stable' from the list of doc versions? I can do it.

**Comment by redapple** [comment]
do you know why is "stable" pointing to 1.1?

**Comment by kmike** [comment]
A good question. Likely it picks latest numeric branch on github (origin/1.1). It is possible to override that. But I'm not sure what version to choose.

**Comment by redapple** [comment]
I'm ok with removing "stable".
I believe it's confusing: for regular users, why would "latest" and "stable" be different?

**Comment by Digenis** [comment]
I just noticed that the django project has exactly the same issue with readthedocs.
Could it be that some change in readthedocs itself broke it?

**Comment by kmike** [comment]
@Digenis a good point: I think this issue is relevant: https://github.com/rtfd/readthedocs.org/issues/1881

**Comment by kmike** [comment]
I've made 'stable' protected for now; it means it is not listed in versions, but links still work.

**Comment by redapple** [comment]
"latest" now points to 1.1 branch

**Comment by kmike** [comment]
Versions at https://doc.scrapy.org/ look good for me now.
