### ISSUE TITLE
update Requirements section in README

### ISSUE THREAD

**Issue by kmike** [scrapy/scrapy#1961]
It says Python 2.7 is required, but Scrapy 1.1+ supports Python 3.3+ as well. I think we should update it as a part of 1.1 release, but not earlier - it may confuse users.

**Comment by mgachhui** [comment]
Does this just mean adding a line for Python 2.2+ in the branches 1.1 and master, or do you have more details in mind?

**Comment by kmike** [comment]
I think we should just wirte "Python 2.7 or Python 3.3+" instead of "Python 2.7" in README (master branch and 1.1 branch), nothing fancy.

**Comment by nyov** [comment]
Looks good to merge.

**Comment by kmike** [comment]
I'm fine with merging it to 1.1 branch. It is better to wait for a 1.1 release before merging it to master - README on scrapy github page is rendered from master branch, and it is confusing when user visits scrapy github page, sees "python 3 is supported", installs scrapy via `pip install scrapy` and Python 3 doesn't work.

**Comment by redapple** [comment]
Similarly, we received feedback that the current (latest) FAQ (1.0 branch) should also say that Python 3 is supported from 1.1+, albeit with beta status and requiring `pip install` with specific version.
What do you think @kmike @nyov ?

**Comment by mgachhui** [comment]
How about adding a page in the wiki about using Python 3? Then the readme can link to that page. Currently, I believe there isn't a single source of information in this regard.

**Comment by kmike** [comment]
@redapple @mgachhui I think we should release 1.1 ASAP; it will have Python 3 support and all such problems will fade away.

**Comment by redapple** [comment]
maybe sneak in a fix for https://github.com/scrapy/scrapy/issues/1976

**Comment by nyov** [comment]
Well, it seems it would be simplest to just add a version specifier to the README text, then it could be merged regardless and would be true now and for all time.

```diff
-Requirements
-============
+Environment
+===========
 
 * Python 2.7
+* Python 3.3+ since Scrapy 1.1 (with beta status in 1.1)
 * Works on Linux, Windows, Mac OSX, BSD
 
 Install
```
Updating the 1.0 FAQ seems sensible, though I don't think it necessary to update history. Once 1.1 is released (and shouldn't that be any day now? ;) it will be the "latest" `docs` version people will (should) visit, and find that info there?

**Comment by redapple** [comment]
@kmike , I assume you are ok with releasing current 1.1 branch (perhaps with #1979) as v1.1.0. Correct?

**Comment by kmike** [comment]
@redapple yep!

**Comment by nyov** [comment]
Well the stars seem to be aligning. hubstorage just got python3 support, which blocked [scrapylib efforts](https://github.com/scrapinghub/scrapylib/pull/71). With scrapylib also close to supporting Py3, this'll be great. Can't wait for it... :drumrolls:

**Comment by redapple** [comment]
Done.
* `1.1` branch: https://github.com/scrapy/scrapy/pull/1972
* `master` branch: https://github.com/scrapy/scrapy/commit/aecc23d24a801f8b7c50497bc37a0c0a2e37e173
