### ISSUE TITLE
The encoding problem in outputing data to file

### ISSUE THREAD

**Issue by wi-cuckoo** [scrapy/scrapy#1963]
Here I got an upset problem. When I use _-o file_ option, I find the text in file just display as below:
`{"title": "Docker \u5b9e\u6218\u7cfb\u5217 \u2014 \u8fd0\u884c\u7b2c\u4e00\u4e2a\u5bb9\u5668", "short_desc": "\u5f53\u4f60\u5bf9\u4e00\u4e9b\u6982\u5ff5\u7406\u89e3\u4e0d\u6df1\u7684\u65f6\u5019\uff0c\u5b9e\u8df5\u662f\u6700\u597d\u7684\u89e3\u51b3\u529e\u6cd5\n\n", "time": "07 Apr 2015"},`

while I run `file outputfile` command in terminal, it shows `blog.json: ASCII text, with very long lines`. I can't understand, really confused. I just want the file display with my local language. And I know write utf-8 string to file will work correctly. So I added `encode('utf-8')` before assigning to Item['key'], but still no any change. Please help me, thx

**Comment by wi-cuckoo** [comment]
encoding problem

**Comment by redapple** [comment]
If I paste your item content into a file,

```
$ cat test.json 
{"title": "Docker \u5b9e\u6218\u7cfb\u5217 \u2014 \u8fd0\u884c\u7b2c\u4e00\u4e2a\u5bb9\u5668", "short_desc": "\u5f53\u4f60\u5bf9\u4e00\u4e9b\u6982\u5ff5\u7406\u89e3\u4e0d\u6df1\u7684\u65f6\u5019\uff0c\u5b9e\u8df5\u662f\u6700\u597d\u7684\u89e3\u51b3\u529e\u6cd5\n\n", "time": "07 Apr 2015"}

```

and use `jq` to display it, it works fine:

```
$ cat test.json | jq .
{
  "title": "Docker 实战系列 — 运行第一个容器",
  "short_desc": "当你对一些概念理解不深的时候，实践是最好的解决办法\n\n",
  "time": "07 Apr 2015"
}
```

`\u5217` escape sequence is one way to represent Unicode characters in JSON

**Comment by redapple** [comment]
Scrapy JSON exporter uses the default `ensure_ascii=True` argument, so it outputs Unicode characters as `\uXXXX` sequences.

Setting `ensure_ascii=False` would output Unicode strings that you would need to encode when writing to file.

Let's read the JSON string back:
```
>>> import json
>>> # use "raw" string to interpret \u correctly
>>> test = r'''{"title": "Docker \u5b9e\u6218\u7cfb\u5217 \u2014 \u8fd0\u884c\u7b2c\u4e00\u4e2a\u5bb9\u5668", "short_desc": "\u5f53\u4f60\u5bf9\u4e00\u4e9b\u6982\u5ff5\u7406\u89e3\u4e0d\u6df1\u7684\u65f6\u5019\uff0c\u5b9e\u8df5\u662f\u6700\u597d\u7684\u89e3\u51b3\u529e\u6cd5\n\n", "time": "07 Apr 2015"}'''
>>> json.loads(test)
{u'time': u'07 Apr 2015', u'short_desc': u'\u5f53\u4f60\u5bf9\u4e00\u4e9b\u6982\u5ff5\u7406\u89e3\u4e0d\u6df1\u7684\u65f6\u5019\uff0c\u5b9e\u8df5\u662f\u6700\u597d\u7684\u89e3\u51b3\u529e\u6cd5\n\n', u'title': u'Docker \u5b9e\u6218\u7cfb\u5217 \u2014 \u8fd0\u884c\u7b2c\u4e00\u4e2a\u5bb9\u5668'}
```

The input with `\uXXXX` sequences is valid json for Python (as it should), and `loads()` produces a valid Python `dict`.

Now let's serialize to JSON again:

```
>>> # dumping the dict back to JSON, with default ensure_ascii=True
>>> json.dumps(json.loads(test))
'{"time": "07 Apr 2015", "short_desc": "\\u5f53\\u4f60\\u5bf9\\u4e00\\u4e9b\\u6982\\u5ff5\\u7406\\u89e3\\u4e0d\\u6df1\\u7684\\u65f6\\u5019\\uff0c\\u5b9e\\u8df5\\u662f\\u6700\\u597d\\u7684\\u89e3\\u51b3\\u529e\\u6cd5\\n\\n", "title": "Docker \\u5b9e\\u6218\\u7cfb\\u5217 \\u2014 \\u8fd0\\u884c\\u7b2c\\u4e00\\u4e2a\\u5bb9\\u5668"}'
```

Now with `ensure_ascii=False`
```
>>> # now dumping with ensure_ascii=False, you get a Unicode string
>>> json.dumps(json.loads(test), ensure_ascii=False)
u'{"time": "07 Apr 2015", "short_desc": "\u5f53\u4f60\u5bf9\u4e00\u4e9b\u6982\u5ff5\u7406\u89e3\u4e0d\u6df1\u7684\u65f6\u5019\uff0c\u5b9e\u8df5\u662f\u6700\u597d\u7684\u89e3\u51b3\u529e\u6cd5\\n\\n", "title": "Docker \u5b9e\u6218\u7cfb\u5217 \u2014 \u8fd0\u884c\u7b2c\u4e00\u4e2a\u5bb9\u5668"}'
```

Let's print to see the difference:

```
>>> print json.dumps(json.loads(test))
{"time": "07 Apr 2015", "short_desc": "\u5f53\u4f60\u5bf9\u4e00\u4e9b\u6982\u5ff5\u7406\u89e3\u4e0d\u6df1\u7684\u65f6\u5019\uff0c\u5b9e\u8df5\u662f\u6700\u597d\u7684\u89e3\u51b3\u529e\u6cd5\n\n", "title": "Docker \u5b9e\u6218\u7cfb\u5217 \u2014 \u8fd0\u884c\u7b2c\u4e00\u4e2a\u5bb9\u5668"}
>>> print json.dumps(json.loads(test), ensure_ascii=False)
{"time": "07 Apr 2015", "short_desc": "当你对一些概念理解不深的时候，实践是最好的解决办法\n\n", "title": "Docker 实战系列 — 运行第一个容器"}

```

**Comment by wi-cuckoo** [comment]
Oh, very appreciate your explanation. It's really helpful, Thanks. Now I try to export as csv format and looks good.

**Comment by wi-cuckoo** [comment]
Oh, very appreciate your explanation. It's really helpful, Thanks. Now I try to export as csv format and looks good.

**Comment by redapple** [comment]
If you ever want to write JSON items as UTF-8, you can do it like this:

1. define a custom item exporter, e.g. in an `exporters.py` file in your project

```
$ cat myproject/exporters.py 
from scrapy.exporters import JsonItemExporter


class Utf8JsonItemExporter(JsonItemExporter):

    def __init__(self, file, **kwargs):
        super(Utf8JsonItemExporter, self).__init__(
            file, ensure_ascii=False, **kwargs)
```

2. replace the default JSON item exporter in your `settings.py`

```
FEED_EXPORTERS = {
    'json': 'myproject.exporters.Utf8JsonItemExporter',
}
```

**Comment by djunzu** [comment]
Let me suggest that this excellent explanation should go to the docs!

**Comment by wi-cuckoo** [comment]
I don't think overwriting the JsonItemExporter class is a simple solution. If we can add an option in __-o file__ , like --encoding='utf-8', this would be more elegant. Well, only personal idea.

**Comment by samibrahmi** [comment]
I'll join wi-cuckoo with his proposition because it will me more appreciated.

**Comment by redapple** [comment]
@wi-cuckoo , @samibrahmi ,
I'm closing this issue in favor of https://github.com/scrapy/scrapy/issues/1965
