### ISSUE TITLE
Add option to set JSON output encoding

### ISSUE THREAD

**Issue by redapple** [scrapy/scrapy#1965]
Some users may prefer UTF-8 encoding of characters when using JSON output, instead of the the default `\UXXXX` espace sequences. See https://github.com/scrapy/scrapy/issues/1963#issuecomment-215943619.

The option to turn off `ensure_ascii` and/or output encoding for `JsonItemExporter` could be interesting.

**Comment by mgachhui** [comment]
The options method @wi-cuckoo mentioned in #1963 seems doable. What if we extend the crawler by adding an encoding option as -e? As far as I can tell, it'll make sense for XML and CSV as well, in addition to JSON.

**Comment by kmike** [comment]
Fixed by https://github.com/scrapy/scrapy/pull/2034.
