### ISSUE TITLE
response.css can't find elements that is there

### ISSUE THREAD

**Issue by rafaelcapucho** [scrapy/scrapy#1968]
Hello,

When running
`scrapy shell https://www.belezanaweb.com.br/homens/`

And executing a simple:
```
In [2]: response.css('div.item').extract()
Out[2]: []
```

The item is over there:
![rsz_2screenshot_at_2016-05-06_014842](https://cloud.githubusercontent.com/assets/163367/15064667/7188e6a6-1346-11e6-8a7b-f496c9d42c42.png)

It isn't load using JS because it is visible in curl:
`curl https://www.belezanaweb.com.br/homens/ | less`:

![screenshot at 2016-05-06 01 53 45](https://cloud.githubusercontent.com/assets/163367/15064678/99449ff0-1346-11e6-8cb5-c44bbfa973a5.png)

Could it be a parser bug?  Running on Scrapy1.1.0rc4
Thank you

**Comment by rafaelcapucho** [comment]
The target HTML have some errors, like some unclosed `div` tags:

![error](https://cloud.githubusercontent.com/assets/163367/15065257/2663858a-134d-11e6-9245-4466e41f44d5.png)

I download the pure html, fixed the tags and now scrapy `response.css` is processing fine. There are any configuration in the scrapy parser to **ignore or auto close** those unclosed tags?

Thank you

**Comment by eLRuLL** [comment]
this is a lxml problem for unclosed tags, but it could be fixed using something like `BeautifulSoup`:

```
In [10]: from BeautifulSoup import BeautifulSoup
In [11]: soup = BeautifulSoup(response.body)
In [12]: from scrapy import Selector
In [13]: sel = Selector(text=soup.prettify())
In [14]: sel.css('div.item')
Out[14]: 
[<Selector xpath=u"descendant-or-self::div[@class and contains(concat(' ', normalize-space(@class), ' '), ' item ')]" data=u'<div class="item js-item item-variacao" '>,
 <Selector xpath=u"descendant-or-self::div[@class and contains(concat(' ', normalize-space(@class), ' '), ' item ')]" data=u'<div class="item js-item item-variacao" '>,
 <Selector xpath=u"descendant-or-self::div[@class and contains(concat(' ', normalize-space(@class), ' '), ' item ')]" data=u'<div class="item js-item " data-layer=\'{'>,
...
```

**Comment by rafaelcapucho** [comment]
@eLRuLL Thank you, but I'm getting errors when executing your code: https://paste.ee/r/8YSJG

I'm running in the scrapy1.1.0rc4 and Python 3.5.1

I change `from BeautifulSoup import BeautifulSoup` to `from bs4 import BeautifulSoup`.

Any Ideas? Thank you

**Comment by rafaelcapucho** [comment]
The problem was with my `lxml`, when running with:

`soup = BeautifulSoup(response.body)`

The lxml was assumed and cause error, if I do the process that described with:

`soup = BeautifulSoup(response.body, 'html.parser')`

All work fine, thank you

**Comment by eLRuLL** [comment]
Great @rafaelcapucho , happy to help!
