### ISSUE TITLE
User timeout caused connection failure

### ISSUE THREAD

**Issue by night1008** [scrapy/scrapy#1969]
Hello, when I send requests at the same time(with dont_filter=True, because some will be error, and the 'DOWNLOAD_TIMEOUT': 60), 
some requests appear the info as following:
`Retrying <GET http://www.xxx> (failed 1 times): User timeout caused connection failure: Getting http://www.xxx took longer than 1800 seconds..`
It doesn't appear other error, and some log that
`have crawled XX pages, and XX items.`
I know the log from https://github.com/scrapy/scrapy/blob/master/scrapy/core/downloader/webclient.py
but I don't know why.
Can someone help me?

**Comment by nyov** [comment]
I'm not sure I understand the problem correctly.
A "user timeout" error occurs when the remote server does not respond in the given time (webserver down, etc.).
Are you saying if you send the same request twice (without a dupefilter), one of them will instantly fail with a timeout error of '1800' seconds?
Do you have a log or some more info?

**Comment by night1008** [comment]
Thanks for your replying!
I guess I use scrapy with cralwera, and the config of download timeout, see
[crawlera](http://doc.scrapinghub.com/crawlera.html)
`CRAWLERA_DOWNLOAD_TIMEOUT	timeout for requests (default: 1800)`
it maybe the cause of my problem.
@nyov

**Comment by nyov** [comment]
Yes, if you are using Crawlera with [scrapy-crawlera](https://github.com/scrapy-plugins/scrapy-crawlera), then there is a `CRAWLERA_DOWNLOAD_TIMEOUT` that defaults to 1800 seconds. It seems to override the standard `DOWNLOAD_TIMEOUT` setting when enabled.

But what is your problem, here? Do you want to change the timeout? Do you think there is a bug with the timeout? Or something else?

You can change the timeout by setting `CRAWLERA_DOWNLOAD_TIMEOUT = 60` in your settings (or `CRAWLERA_DOWNLOAD_TIMEOUT = DOWNLOAD_TIMEOUT`).
I think setting `request.meta['download_timeout'] = 60` on a specific request should also work.

**Comment by nyov** [comment]
The error message `Retrying <GET http://www.xxx> (failed 1 times): User timeout caused connection failure: Getting http://www.xxx took longer than 1800 seconds..`
says:
1. [Downloader](https://github.com/scrapy/scrapy/blob/3735eb8e5f62a52c5630ede765b443cb1313ff96/scrapy/core/downloader/handlers/http11.py#L301): "I timed out trying to fetch http://www.xxx in 1800 seconds, sorry"
2. [RetryMiddleware](https://github.com/scrapy/scrapy/blob/3735eb8e5f62a52c5630ede765b443cb1313ff96/scrapy/downloadermiddlewares/retry.py#L65): "I am retrying the Request that failed with Error `I timed out trying to fetch http://www.xxx in 1800 seconds, sorry`"

**Comment by night1008** [comment]
nice!
It should not be a bug.
Mainly, I am not carefully see the doc of crawlera.
I want to change the `CRAWLERA_DOWNLOAD_TIMEOUT` to try again.
Thanks you very much !!!

**Comment by kmike** [comment]
Thanks @nyov for the help!
