### ISSUE TITLE
problem of scrapy runspider spider -a 

### ISSUE THREAD

**Issue by wangjian2014** [scrapy/scrapy#1970]
# The content of my scrapy script is like 

#coding:utf-8
import sys
import scrapy
import json
import logging
from scrapy.mail import MailSender
import time
import datetime
class StackOverflowSpider(scrapy.Spider):
    name = 'stackoverflow'
    start_urls = ['http://www.baidu.com']

    def __init__(self,systemName,date1):
        print 'date1 is '+date1
        dateNow = datetime.datetime.now().strftime("%Y-%m-%d-%H-%M-%S")
        self.file = open('errorlog/'+systemName+'_'+dateNow+'_error.log', 'a')
        self.systemName=systemName
        self.date1=date1
        date2=''
        self.date2=date2

    def parse(self, response):

# I want to use shell script to run this spider.The content of my shell script(date-who-script) is like

#!/bin/bash
datebegin="2016-05-04 11:00:00"
scrapy runspider sn_yunji_email_with_inputparam.py -a systemName='EPPSOAAS' -a date1=$datebegin

When I run this shell script like ./date-who-script,it can't run.But if I change $datebegin to datebegin,it can run.But the value of date1 is 'datebegin',not "2016-05-04 11:00:00".
I think the symbol of $ is not recognized by scrapy.
how can I post the value of variable datebegin to scrapy? thank you very much!

**Comment by kmike** [comment]
I think this is not a Scrapy issue, your shell script is incorrect. Try adding quotes around $datebegin - otherwise it is expanded to `date1=2016-05-04 11:00:00`, i.e. date1 value is `2016-05-04` and there is an extra `11:00:00` argument.
