### ISSUE TITLE
Minor issue in comments of custom deprecation handler

### ISSUE THREAD

**Issue by umrashrf** [scrapy/scrapy#1971]
I made some tests and I found out [this comment](https://github.com/scrapy/scrapy/blob/master/scrapy/utils/deprecate.py#L44-L47) is not completely true. 

> Also, if some code uses ``issubclass(sub, OldName)`` or ``isinstance(sub(), OldName)`` checks they'll still return True if sub is a subclass of NewName instead of OldName.

I think this is always the case even without using ```create_deprecated_class```. Can someone else check and confirm if that's right?

**Comment by kmike** [comment]
@umrashrf could you please clarify what is always the case?

```py
class OldName(SomeClass):
    pass

class NewName(SomeClass):
    pass

obj = NewName()
```

Here `issubclass(NewName, OldName)` is False, and `isinstance(obj, OldName)` is False as well.

**Comment by umrashrf** [comment]
I tested again and it seems to be working as expected :/ No wonder I was sleeping while creating this issue.

```python
>>> class OldName(object):
...     pass
... 
>>> class NewName(object):
...     pass
... 
>>> class SubC(NewName):
...     pass
... 
>>> issubclass(SubC, OldName)
False
>>> isinstance(SubC(), OldName)
False
>>> 
>>> from scrapy.utils.deprecate import create_deprecated_class
>>> OldName = create_deprecated_class('OldName', NewName)
>>> 
>>> issubclass(SubC, OldName)
True
>>> isinstance(SubC(), OldName)
True
```
