### ISSUE TITLE
Delay after every 5 minutes

### ISSUE THREAD

**Issue by pawneetdev** [scrapy/scrapy#1978]
DOWNLOAD_DELAY gives delay between each request. I want to give a delay of 10 seconds after every 5 minutes.

**Comment by redapple** [comment]
@pawneetdev , I believe your request is better suited as a topic for the [mailing-list](https://groups.google.com/forum/#!forum/scrapy-users) or StackOverflow.

Scrapy doesn't have a built-in way to throttle requests the way you want, but the scrapy community may have ideas on how to implement this.

**Comment by pawneetdev** [comment]
Ok thanks
