### ISSUE TITLE
while crawling website like https://www.netflix.com,getting Forbidden by robots.txt: <GET https://www.netflix.com/>

### ISSUE THREAD

**Issue by dgrene** [scrapy/scrapy#1993]
while crawling website like https://www.netflix.com, getting Forbidden by robots.txt: <GET https://www.netflix.com/>

ERROR: No response downloaded for: https://www.netflix.com/

**Comment by kmike** [comment]
Scrapy respects robots.txt by default, and this website forbids your request. This is indicated by a log message - it is not a scrapy bug. There is an option to disable robots.txt handling if you really know what you're doing: http://doc.scrapy.org/en/latest/topics/settings.html#robotstxt-obey
