### ISSUE TITLE
Restarting a scrapy instance or call parse method manually

### ISSUE THREAD

**Issue by pawneetdev** [scrapy/scrapy#1996]
I want to call the parse method manually or restart scrapy after the scraping is complete. Is it possible? I found nothing related to that in scrapy documentation. Also, can I run call it infinitely until a condition is satisfied?

**Comment by redapple** [comment]
@pawneetdev , see [my answer on StackOverflow](http://stackoverflow.com/a/37318392/2572383)

Please note that scrapy issue tracker here on GitHub is intended for [bug reports](http://doc.scrapy.org/en/latest/contributing.html#reporting-bugs) ideally (although it is also used for discussions sometimes)

Your "how-to" question is better suited for the [mailing list](https://groups.google.com/forum/#!forum/scrapy-users) or StackOverflow (where you posted rightfully)
