### ISSUE TITLE
IGNORED_EXTENSIONS not working because of url_has_any_extension implementation

### ISSUE THREAD

**Issue by knaveofdiamonds** [scrapy/scrapy#1997]
The `scrapy.linkextractors.IGNORED_EXTENSIONS` were not being ignored for me in my scraper run. Digging into it, this seems to be because posixpath returns the extension with the '.', but the extensions are defined without the '.'

For example, this test fails:

    def test_url_has_any_extension(self):
        self.assertTrue(url_has_any_extension('http://www.example.com/image.jpg', ['jpg']))

What is the correct solution here - to add stripping the '.' in `url_has_any_extension` or to add the '.' before all the extensions in `IGNORED_EXTENSIONS`? (Happy to do the work for a patch, but not sure which way to go).

**Comment by kmike** [comment]
@knaveofdiamonds are you sure there is a bug in Scrapy? Dot is added to extension [here](https://github.com/scrapy/scrapy/blob/d3ced85ec350e8c195760a8ce975a18ca42f29a0/scrapy/linkextractors/__init__.py#L70), and there are passing [tests](https://github.com/scrapy/scrapy/blob/d3ced85ec350e8c195760a8ce975a18ca42f29a0/tests/test_linkextractors.py#L235) for this feature. One can argue that `url_has_any_extension` API is not obviuos, but changing it would be backwards incompatible now, and this function is internal and undocumented.

**Comment by knaveofdiamonds** [comment]
@kmike - ah, ok. I'm working on an inherited codebase that doesn't use the `LinkExtractors` directly, so this was obviously just a misunderstanding of the API/using something non-public. I'll close this issue - agree with backwards incompatible change reasons.
