### ISSUE TITLE
TextResponse doesn't initialize when it needed

### ISSUE THREAD

**Issue by matveinazaruk** [scrapy/scrapy#2000]
When I perform rest request ('POST' with body and headers), I got a response with text body. But type of response in callback is `Response`, but expected - `TextResponse`.

**Comment by redapple** [comment]
@matveinazaruk , do you have a reproducible example for this behavior?

**Comment by redapple** [comment]
Fixed in https://github.com/scrapy/scrapy/issues/2001
Thanks again @matveinazaruk !
