### ISSUE TITLE
Are there plans to add Web ARChive support?

### ISSUE THREAD

**Issue by robsonpeixoto** [scrapy/scrapy#2002]
From Wikipedia, the free encyclopedia

> The Web ARChive (WARC) archive format specifies a method for combining multiple digital resources into an aggregate archive file together with related information. The WARC format is a revision of the Internet Archive's ARC File Format[5] that has traditionally been used to store "web crawls" as sequences of content blocks harvested from the World Wide Web. The WARC format generalizes the older format to better support the harvesting, access, and exchange needs of archiving organizations. Besides the primary content currently recorded, the revision accommodates related secondary content, such as assigned metadata, abbreviated duplicate detection events, and later-date transformations.[6]
> 
> WARC is now recognised by most national library systems as the standard to follow for web archival.[7]
> 

https://en.wikipedia.org/wiki/Web_ARChive

**Comment by kmike** [comment]
No plans I'm aware of. 

Does it have to be in Scrapy core? Currently in Scrapy it is user who defines what information to extract and store. It looks like WARC support is a matter of creating a function which converts scrapy Response to a WARC record; it can be done as a separate package. I'm not very familiar with WARC though; are there fields which are hard to get with Scrapy, maybe some low-level information? Alternatively, one can send all Scrapy network traffic through proxy, and this proxy may record WARC (see e.g. https://github.com/ikreymer/warcprox).

**Comment by robsonpeixoto** [comment]
Thanks @kmike. I'll study more about WARC and scrapy Response.
Thanks the the tip about warcprox.
