### ISSUE TITLE
Could not find suitable distribution for Requirement.parse('Scrapy==1.1.0')

### ISSUE THREAD

**Issue by robsonpeixoto** [scrapy/scrapy#2003]
When I execute the `python setup.py develop` I got the error:

```
Searching for Scrapy==1.1.0
Reading https://pypi.python.org/simple/Scrapy/
No local packages or download links found for Scrapy==1.1.0
error: Could not find suitable distribution for Requirement.parse('Scrapy==1.1.0')
```

**Comment by robsonpeixoto** [comment]
But `pip install -e` works

**Comment by robsonpeixoto** [comment]
I checked the address https://pypi.python.org/simple/Scrapy/ and the file `Scrapy-1.1.0.tar.gz` does not exists.

**Comment by redapple** [comment]
hi @robsonpeixoto, indeed there's only a wheel distribution. 
there was a problem uploading the source distribution from Travis CI.
Recent pip version should be able to use the wheel version.
`pip install scrapy` should be fine, that's what I use.
Otherwise, you could use https://github.com/scrapy/scrapy/archive/1.1.0.tar.gz

**Comment by kmike** [comment]
@redapple do you know if restarting Travis job will help? We should have a tarball on pypi.

**Comment by redapple** [comment]
@kmike , I did try rebuild on Travis.
Got an error on the wheel upload (already there) so src upload did not happen

https://s3.amazonaws.com/archive.travis-ci.org/jobs/129470985/log.txt
```
Uploading distributions to https://pypi.python.org/pypi
Uploading Scrapy-1.1.0-py2.py3-none-any.whl
HTTPError: 400 Client Error: A file named "Scrapy-1.1.0-py2.py3-none-any.whl" already exists for  Scrapy-1.1.0. To fix problems with that file you should create a new release. for url: https://pypi.python.org/pypi
running upload_docs...
```

**Comment by robsonpeixoto** [comment]
Why not upload manually the tarball?

**Comment by redapple** [comment]
@kmike, @daniel, can one of you do it? I don't have permission on pypi for
scrapy (+ I'm away for 2 weeks)

**Comment by redapple** [comment]
(sorry, that was for @dangra)

**Comment by dangra** [comment]
Hi Guys, the tar.gz is in pypi now. 

```pip install --no-use-wheel Scrapy==1.1.0``` succeed for me. please confirm.

**Comment by kmike** [comment]
Works for me, thanks @robsonpeixoto for the report and @dangra for the fix!
