### ISSUE TITLE
Customable self-adaptive delay?

### ISSUE THREAD

**Issue by wlnirvana** [scrapy/scrapy#2012]
My crawler frequently got recaptcha page after about 15mins scraping. I am considering to implement a recaptcha page detection, and when it is detected enforce a delay on all subsequent requests to wait for my IP to be unblocked.

**Comment by korsunowk** [comment]
Hi. This delay can live more that 1 day. I recommended you write every 15 new captha or get captcha_id + captha_img for programming detect right captcha code

**Comment by redapple** [comment]
@wlnirvana , sorry for the late comment. Your use-case is probably worth discussing in [scrapy-users mailing list](https://groups.google.com/d/forum/scrapy-users).
You can have a look at [how `Autothrottle` is implemented](https://github.com/scrapy/scrapy/blob/1.1/scrapy/extensions/throttle.py), adapting slot delays.
I'm closing the issue for now as it's not an issue with scrapy, more of a discussion on how to do it with the framework.
