### ISSUE TITLE
Request from Pipeline

### ISSUE THREAD

**Issue by gdomod** [scrapy/scrapy#2016]
Hi there,

i want to send the item data to another webservice. how can i use scrapy.Request to send the item to other website

```
req = scrapy.Request(
                    url, method='POST',
                    body=json.dumps(dict(item)),
                    headers={'content-type': 'application/json'},
                    priority=1000,
                    callback=self.callback)
```

the request is correct but scrapy.Request didnt fire the request
with yield req, or return req

**Comment by eLRuLL** [comment]
this looks better suited for StackOverflow, not a real issue or feature for Scrapy

**Comment by Digenis** [comment]
There's a relevant discussion on #1940.
Perhaps a better API could be extended to also work in other places,
not only spider callbacks.

**Comment by clouds56** [comment]
I think @gdomod is talking about "how to fire a `scarpy.Request` from a `Pipeline`"
consider this scenario:
1. parsed a page and get some `links`
2. send the every `link in links` to some Pipeline, which filter links from some external services
3. would like to crawl filtered `links`

this stackoverflow [link](https://stackoverflow.com/questions/38467052/scrapy-make-http-request-in-pipeline) gives a workaround using custom Pipeline.

While I hope there's more simple way to achieve the goal like this.

```python
import scrapy
import json

class LinkPipeline(object):
    # after some other pipelines
    def process_item(self, item, spider):
        if not external_filter(item['link']):
            yield scrapy.Request(item['link'], callback=spider.parse)
        yield item

class MySpider(scrapy.Spider):
    name = 'station'
    start_urls = ['http://...']

    def parse(self, response):
        links = response.css('a').xpath('@href').extract()
        for link in links:
            yield {'link': link}
```

**Comment by Gallaecio** [comment]
I’m not sure we need this feature. It seems like in most cases the code can be in the spider itself, and when that’s not desired (i.e. for code reuse) a spider middleware should do the job.

**Comment by wRAR** [comment]
https://docs.scrapy.org/en/latest/topics/item-pipeline.html#take-screenshot-of-item
