### ISSUE TITLE
Scrapy runs and does not create new html files for site it is scraping.

### ISSUE THREAD

**Issue by Karla-Isabel-Sandoval** [scrapy/scrapy#2020]
Scrapy runs and does not create new html files for the site it is scraping.
It runs successfully with a (200) message and is able to reach Telnet.
Scrapy is no longer producing new html files and or a separate resource file as suggested here [](http://doc.scrapy.org/en/latest/intro/tutorial.html#our-first-spider).

**I am confused as to why my `scrapy crawl $myprojectname` is not fetching any new  html data?**

```
2016-05-31 11:32:48 [scrapy] INFO: Spider opened
2016-05-31 11:32:48 [scrapy] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2016-05-31 11:32:48 [scrapy] DEBUG: Telnet console listening on 127.1.5.1:****
DEBUG: Crawled (200)
'log_count/DEBUG': 4,
 'log_count/INFO': 7,
 'offsite/domains': 1,
 'offsite/filtered': 25,
 'request_depth_max': 1,
 'response_received_count': 2,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'start_time': datetime.datetime(2016, 5, 31, 9, 32, 48, 773501)}
2016-05-31 11:32:50 [scrapy] INFO: Spider closed (finished)
```

Results from the crawl above are not in order and the console listening number has been changed for privacy.

**Comment by djunzu** [comment]
Let me suggest that you should post your question in [StackOverflow](http://stackoverflow.com/) or [scrapy-users mailing list](https://groups.google.com/forum/#!forum/scrapy-users). It is easier to find help for this kind of problem there.

**Comment by redapple** [comment]
@Karla-Isabel-Sandoval ,
it's really hard to help you without the context nor the spider code.
As @djunzu suggest, you'll find more help for these "why is my spider not working?" questions on the [mailing list](https://groups.google.com/forum/#!forum/scrapy-users) or [stackoverflow](https://stackoverflow.com/questions/tagged/scrapy).
Please note that GitHub issues should be [complete, reproducible, specific bug reports](http://doc.scrapy.org/en/latest/contributing.html#reporting-bugs) (except if it's a design discussion)
