### ISSUE TITLE
Command line: allow multiple output pipelines

### ISSUE THREAD

**Issue by eltermann** [scrapy/scrapy#2025]
So, for reasons, I have a spider that yields 3 kinds of items, let's say TypeOneItem, TypeTwoItem and TypeTreeItem.

I'd like to do something like this:

```bash
$ scrapy crawl myspider --criteria1="isinstance(TypeOneItem)" -t1 csv -o1 items_of_type1.csv --criteria2="isinstance(TypeTwoItem)" -o2 items_of_type2.json --criteria3="isinstance(TypeTreeItem)" -t3 xml -o3 items_of_type3.xml
```

Of course, the names of arguments and fields could be different, but that is the idea.

Any thoughs?

**Comment by Digenis** [comment]
Does the criteria and output files change all the time
to justify configuring them in the command line
instead of reusing feed exporter code in a pipeline?

**Comment by eltermann** [comment]
No, they does not change all the time. It would suffice something like:

```bash
$ scrapy crawl myspider -t csv -o items_of_type1.csv -o items_of_type2.csv -o items_of_type3.csv
```

The question is: will scrapy know which file to use for each yielded item?

**Comment by Digenis** [comment]
First of all, according to the code, you can't pass multiple `-o` options
https://github.com/scrapy/scrapy/blob/d3ced85ec350e8c195760a8ce975a18ca42f29a0/scrapy/commands/crawl.py#L22
Look at http://doc.scrapy.org/en/latest/topics/exporters.html#using-item-exporters
to see how to define a pipeline that uses existing exporters. You can customize it for your use case.

I think it's better to see this issue as a support question for now
and ask for more help in the mailing list if you have trouble implementing the exporter.
I don't think that's you'll find that scrapy requires a patch while at it.
