### ISSUE TITLE
Will enabling ajaxcrawl miss some web contents?

### ISSUE THREAD

**Issue by ibowen** [scrapy/scrapy#2028]
Hello Scrapy, when I enabled ajaxcrawl in setting.py, some contents on non-ajax pages were lost. What could it be the problem? Is it possible to switch the ajaxcrawl in spider? 
## My code:

https://github.com/ibowen/crowdfunding/blob/master/seedinvest_crawl/seedinvest_crawl/spiders/seedinvest.py
## Scrapy View of enabling ajaxcrawl:

![enabling](https://cloud.githubusercontent.com/assets/12148218/15803205/10698864-2a87-11e6-904e-271eebd71ab8.jpg)
## Scrapy View of unenabling ajaxcrawl:

![unenabling](https://cloud.githubusercontent.com/assets/12148218/15803206/106aabc2-2a87-11e6-80df-04d1fbb9b21f.jpg)

**Comment by pawelmhm** [comment]
Seems like you're right. This page shows different content for ajax crawlable. 

https://www.seedinvest.com/offerings?_escaped_fragment_= differs from this https://www.seedinvest.com/offerings 

minimal example to reproduce this:


```python
from scrapy import Spider


class SeedinvestSpider(Spider):
    name = "seedinvest"
    allowed_domains = ["seedinvest.com"]
    start_urls = (
        'https://www.seedinvest.com/offerings',
    )
    custom_settings = {
        "AJAXCRAWL_ENABLED": False
    }

    def parse(self, response):
        urls = response.xpath('//*[starts-with(@id, "deal-thumbnail-")]/div/a[1]/@href').extract()
        print(len(urls))
        # ajax crawlable will have 59 links, normal page 60 links
        assert (len(urls)) == 59
```

but it does not look like bug in Scrapy, it seems to be more about this website braking the rules and showing different results.

**Comment by ibowen** [comment]
Thanks, you are right, I solved it by changing the xpath.
