### ISSUE TITLE
Document 'download_latency' key in requests' meta dict

### ISSUE THREAD

**Issue by redapple** [scrapy/scrapy#2033]
`request.meta['download_latency']` can be useful for analysing a spider or a website, but it's not documented (see #2021).

**Comment by kmike** [comment]
I think it may be undocumented because it is not like other request.meta values. All other documented request.meta values allow to control how Scrapy processes request (i.e. user should write to them), but download_latency is a value user reads read from, not writes to.

**Comment by redapple** [comment]
@kmike , ok, do you agree it should be mentioned in the docs?

**Comment by kmike** [comment]
Yes, I think we should mention it, but I'm not sure I like that meta is used for so many things. I still think we should fix at least https://github.com/scrapy/scrapy/issues/1138
