### ISSUE TITLE
LOG_UNSERIALIZABLE_REQUESTS messages should be WARNINGs, not ERRORs

### ISSUE THREAD

**Issue by kmike** [scrapy/scrapy#2035]
Currently if LOG_UNSERIALIZABLE_REQUESTS is True and request can't be serialized users get

> ERROR: Unable to serialize request: ...

messages in log (see [here](https://github.com/scrapy/scrapy/blob/d3ced85ec350e8c195760a8ce975a18ca42f29a0/scrapy/core/scheduler.py#L81)). I think they are confusing because spider still works. What do you think about changing log level to WARNING?

**Comment by eliasdorneles** [comment]
+1

**Comment by nyov** [comment]
+1
