### ISSUE TITLE
Some logging should indicate spider

### ISSUE THREAD

**Issue by rgtk** [scrapy/scrapy#2037]
Logs such as: `INFO: Dumping Scrapy stats`, `INFO: Closing spider (shutdown)`, `INFO: Crawled...`. should indicate from which spider log was issued. It is must-have to debug and analyze logs for crawler that have multiple spiders.

**Comment by kmike** [comment]
Yeah, I think we should fix it. It was reported before: https://github.com/scrapy/scrapy/issues/1576; let's keep a single ticket.
