### ISSUE TITLE
add "flags" kwarg to Scrapy Request

### ISSUE THREAD

**Issue by pawelmhm** [scrapy/scrapy#2047]
Scrapy [response.flags](http://doc.scrapy.org/en/latest/topics/request-response.html#scrapy.http.Response.flags) are really useful and underappreciated feature. It would be useful to add a way to pass flags argument to Request at initialization, e.g.

``` python

def some_callback(self, response):
      yield Request('http://example.com', flags={"issued from": "some_callback", "going to": "somewhere")
```

and then in log output you will have:

```
[scrapy.core.engine] Crawled (200) <GET http://example.com>  ['issued_from": "some_callback', "going to": "somewhere"]
```

This is useful because it allows you to have some heplful debugging metadata directly in logs. If you want to debug some spider problem you will have some metadata directly in logs and you dont have to start debugger in some callback and investigate response meta or some other stuff.

**Comment by kmike** [comment]
Fixed by #2082, though flags is a list, like in responses.
