### ISSUE TITLE
utils.is_gzipped returns false on application/x-gzip;charset=utf-8

### ISSUE THREAD

**Issue by Tethik** [scrapy/scrapy#2049]
I had a site return the following header, which caused SitemapSpider to not parse a sitemap xml that was gzipped. 
```
Content-Type: application/x-gzip;charset=utf-8
```
Looking into the code it seems that the function [utils.is_gzipped](https://github.com/scrapy/scrapy/blob/master/scrapy/utils/gz.py#L54) does not take into account cases where the Content-Type header would include charset.

**Comment by eliasdorneles** [comment]
Fixed in #2050!
@Tethik @robsonpeixoto @redapple thanks fellows!
