### ISSUE TITLE
if response.status == 403,I want to autochange ip_proxy. how i do ?

### ISSUE THREAD

**Issue by kimg1234** [scrapy/scrapy#2051]
'class ProxyMiddleware(object):
    def process_request(self, request, spider):
        proxy = random.choice(PROXIES)
        if proxy['user_pass'] is not None:
            request.meta['proxy'] = "http://%s" % proxy['ip_port']
            encoded_user_pass = base64.encodestring(proxy['user_pass'])
            request.headers['Proxy-Authorization'] = 'Basic ' + encoded_user_pass            
	    print "**************ProxyMiddleware have pass************" + proxy['ip_port']
        else:
	    print "**************ProxyMiddleware no pass************" + proxy['ip_port']
            request.meta['proxy'] = "http://%s" % proxy['ip_port']
'

**Comment by kimg1234** [comment]
I mean, how to call another middleware in the middleware

**Comment by podolskyi** [comment]
My solution.

- enable [retry](http://doc.scrapy.org/en/latest/topics/downloader-middleware.html?highlight=retry#retry-enabled) 
- add 403 to RETRY_HTTP_CODES 
- sample ProxyMiddleware:

Main idea, change proxy address in each requests.
`


        def process_request(self, request, spider):
            if not getattr(spider, 'use_proxy', None):
                return

            # Don't overwrite with a random one (server-side state for IP)
            if 'proxy' in request.meta and not request.meta.get('retry_times', 0):
                return

            proxy_address = random.choice(self.proxy_list)

            request.meta['proxy'] = proxy_address

            return request


`

**Comment by kimg1234** [comment]
@podolskyi  thanks~

**Comment by redapple** [comment]
@kimg1234 , I believe @podolskyi 's comment answers your question.
Please note that this type of "how-to" question is more suited for the [scrapy-users mailing list](https://groups.google.com/forum/#!forum/scrapy-users) or [StackOverflow](stackoverflow.com).

**Comment by kimg1234** [comment]
@redapple ok,thanks
In fact , my code is the definition of download middleware, when httpcode=403 , the router automatically reconnect short net
[mycode](https://github.com/kimg1234/zhihuCollec/blob/master/zhihu/middlewares.py)
