### ISSUE TITLE
Depth First Order scraping works in an unexpected way

### ISSUE THREAD

**Issue by flagist0** [scrapy/scrapy#2068]
[Scrapy FAQ](http://doc.scrapy.org/en/latest/faq.html#does-scrapy-crawl-in-breadth-first-or-depth-first-order) points out that to enable DFO you have to set `DEPTH_PRIORITY` to 1.
But it works the opposite way. If I understand it correctly, the problem is [here](https://github.com/scrapy/scrapy/blob/80c296e091d83e91d391bed5c3cf54d55a472fcf/scrapy/spidermiddlewares/depth.py#L36):
`request.priority -= depth * self.prio`.
Request's priority is *decreased* by its depth, putting it to the end of the queue.
So to enable DFO you have to replace '-=' with '+=' or to set `DEPTH_PRIORITY` to -1 (which is counter-intuitive).

**Comment by kmike** [comment]
Docs say:

> If you do want to crawl in true **BFO** order, you can do it by setting the following settings: DEPTH_PRIORITY = 1 ...

**Comment by flagist0** [comment]
Yes, sorry, my mistake.
