### ISSUE TITLE
Scrapy installation error

### ISSUE THREAD

**Issue by kiral26** [scrapy/scrapy#2070]
Hi,

I'm installing Scrapy on Windows, and got this error when trying to do pip install Scrapy:

 build\temp.win-amd64-2.7\Release\_openssl.c(429) : fatal error C1083: Cannot
 open include file: 'openssl/opensslv.h': No such file or directory

I've checked that I got the file mentioned in "C:\OpenSSL-Win64\include\openssl", and I've added to path C:\openssl-win64\include\ in user variable. But I'm still getting the error. Can someone please help out, thanks!

**Comment by redapple** [comment]
@kiral26 , can you paste the whole console log for the commands you typed to install scrapy?
This looks related to installing PyOpenSSL (dependency of Scrapy and Twisted), which depends on [`cryptography`](https://cryptography.io/)
`cryptography` has a specific section on [installing it on Windows](https://cryptography.io/en/latest/installation/#on-windows).

**Comment by kiral26** [comment]
@redapple Thanks for the response! Here's what I'm seeing:

pip install Scrapy
Collecting Scrapy
  Using cached Scrapy-1.1.0-py2.py3-none-any.whl
Collecting service-identity (from Scrapy)
  Using cached service_identity-16.0.0-py2.py3-none-any.whl
Collecting cssselect>=0.9 (from Scrapy)
  Using cached cssselect-0.9.2-py2.py3-none-any.whl
Collecting queuelib (from Scrapy)
  Using cached queuelib-1.4.2-py2.py3-none-any.whl
Collecting lxml (from Scrapy)
  Using cached lxml-3.6.0-cp27-none-win_amd64.whl
Collecting pyOpenSSL (from Scrapy)
  Using cached pyOpenSSL-16.0.0-py2.py3-none-any.whl
Collecting w3lib>=1.14.2 (from Scrapy)
  Using cached w3lib-1.14.2-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): six>=1.5.2 in c:\python27\lib\site-packages (from Scrapy)
Collecting parsel>=0.9.3 (from Scrapy)
  Using cached parsel-1.0.2-py2.py3-none-any.whl
Collecting PyDispatcher>=2.0.5 (from Scrapy)
  Using cached PyDispatcher-2.0.5.tar.gz
Collecting Twisted>=10.0.0 (from Scrapy)
  Using cached Twisted-16.2.0-cp27-none-win_amd64.whl
Collecting pyasn1-modules (from service-identity->Scrapy)
  Using cached pyasn1_modules-0.0.8-py2.py3-none-any.whl
Collecting attrs (from service-identity->Scrapy)
  Using cached attrs-16.0.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): pyasn1 in c:\python27\lib\site-packages (from service-identity->Scrapy)
Collecting cryptography>=1.3 (from pyOpenSSL->Scrapy)
  Using cached cryptography-1.4.tar.gz
Collecting zope.interface>=3.6.0 (from Twisted>=10.0.0->Scrapy)
  Using cached zope.interface-4.2.0.tar.gz
Requirement already satisfied (use --upgrade to upgrade): idna>=2.0 in c:\python27\lib\site-packages (from cryptography>=1.3->pyOpenSSL->Scrapy)
Requirement already satisfied (use --upgrade to upgrade): setuptools>=11.3 in c:\python27\lib\site-packages (from cryptography>=1.3->pyOpenSSL->Scrapy)
Requirement already satisfied (use --upgrade to upgrade): enum34 in c:\python27\lib\site-packages (from cryptography>=1.3->pyOpenSSL->Scrapy)
Requirement already satisfied (use --upgrade to upgrade): ipaddress in c:\python27\lib\site-packages (from cryptography>=1.3->pyOpenSSL->Scrapy)
Requirement already satisfied (use --upgrade to upgrade): cffi>=1.4.1 in c:\python27\lib\site-packages (from cryptography>=1.3->pyOpenSSL->Scrapy)
Requirement already satisfied (use --upgrade to upgrade): pycparser in c:\python27\lib\site-packages (from cffi>=1.4.1->cryptography>=1.3->pyOpenSSL->Scrapy)
Installing collected packages: cryptography, pyOpenSSL, pyasn1-modules, attrs, service-identity, cssselect, queuelib, lxml, w3lib, parsel, PyDispatcher, zope.interface, Twisted, Scrapy
  Running setup.py install for cryptography
    Complete output from command c:\python27\python.exe -c "import setuptools, tokenize;__file__='c:\\users\\kiral~1\\appdata\\local\\temp\\pip-build-jhbpvk\\cryptography\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\kiral~1\appdata\local\temp\pip-dawxbf-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-2.7
    creating build\lib.win-amd64-2.7\cryptography
    copying src\cryptography\exceptions.py -> build\lib.win-amd64-2.7\cryptography
    copying src\cryptography\fernet.py -> build\lib.win-amd64-2.7\cryptography
    copying src\cryptography\utils.py -> build\lib.win-amd64-2.7\cryptography
    copying src\cryptography\__about__.py -> build\lib.win-amd64-2.7\cryptography
    copying src\cryptography\__init__.py -> build\lib.win-amd64-2.7\cryptography
    creating build\lib.win-amd64-2.7\cryptography\hazmat
    copying src\cryptography\hazmat\__init__.py -> build\lib.win-amd64-2.7\cryptography\hazmat
    creating build\lib.win-amd64-2.7\cryptography\x509
    copying src\cryptography\x509\base.py -> build\lib.win-amd64-2.7\cryptography\x509
    copying src\cryptography\x509\extensions.py -> build\lib.win-amd64-2.7\cryptography\x509
    copying src\cryptography\x509\general_name.py -> build\lib.win-amd64-2.7\cryptography\x509
    copying src\cryptography\x509\name.py -> build\lib.win-amd64-2.7\cryptography\x509
    copying src\cryptography\x509\oid.py -> build\lib.win-amd64-2.7\cryptography\x509
    copying src\cryptography\x509\__init__.py -> build\lib.win-amd64-2.7\cryptography\x509
    creating build\lib.win-amd64-2.7\cryptography\hazmat\backends
    copying src\cryptography\hazmat\backends\interfaces.py -> build\lib.win-amd64-2.7\cryptography\hazmat\backends
    copying src\cryptography\hazmat\backends\multibackend.py -> build\lib.win-amd64-2.7\cryptography\hazmat\backends
    copying src\cryptography\hazmat\backends\__init__.py -> build\lib.win-amd64-2.7\cryptography\hazmat\backends
    creating build\lib.win-amd64-2.7\cryptography\hazmat\bindings
    copying src\cryptography\hazmat\bindings\__init__.py -> build\lib.win-amd64-2.7\cryptography\hazmat\bindings
    creating build\lib.win-amd64-2.7\cryptography\hazmat\primitives
    copying src\cryptography\hazmat\primitives\cmac.py -> build\lib.win-amd64-2.7\cryptography\hazmat\primitives
    copying src\cryptography\hazmat\primitives\constant_time.py -> build\lib.win-amd64-2.7\cryptography\hazmat\primitives
    copying src\cryptography\hazmat\primitives\hashes.py -> build\lib.win-amd64-2.7\cryptography\hazmat\primitives
    copying src\cryptography\hazmat\primitives\hmac.py -> build\lib.win-amd64-2.7\cryptography\hazmat\primitives
    copying src\cryptography\hazmat\primitives\keywrap.py -> build\lib.win-amd64-2.7\cryptography\hazmat\primitives
    copying src\cryptography\hazmat\primitives\padding.py -> build\lib.win-amd64-2.7\cryptography\hazmat\primitives
    copying src\cryptography\hazmat\primitives\serialization.py -> build\lib.win-amd64-2.7\cryptography\hazmat\primitives
    copying src\cryptography\hazmat\primitives\__init__.py -> build\lib.win-amd64-2.7\cryptography\hazmat\primitives
    creating build\lib.win-amd64-2.7\cryptography\hazmat\backends\commoncrypto
    copying src\cryptography\hazmat\backends\commoncrypto\backend.py -> build\lib.win-amd64-2.7\cryptography\hazmat\backends\commoncrypto
    copying src\cryptography\hazmat\backends\commoncrypto\ciphers.py -> build\lib.win-amd64-2.7\cryptography\hazmat\backends\commoncrypto
    copying src\cryptography\hazmat\backends\commoncrypto\hashes.py -> build\lib.win-amd64-2.7\cryptography\hazmat\backends\commoncrypto
    copying src\cryptography\hazmat\backends\commoncrypto\hmac.py -> build\lib.win-amd64-2.7\cryptography\hazmat\backends\commoncrypto
    copying src\cryptography\hazmat\backends\commoncrypto\__init__.py -> build\lib.win-amd64-2.7\cryptography\hazmat\backends\commoncrypto
    creating build\lib.win-amd64-2.7\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\backend.py -> build\lib.win-amd64-2.7\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\ciphers.py -> build\lib.win-amd64-2.7\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\cmac.py -> build\lib.win-amd64-2.7\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\decode_asn1.py -> build\lib.win-amd64-2.7\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\dsa.py -> build\lib.win-amd64-2.7\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\ec.py -> build\lib.win-amd64-2.7\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\encode_asn1.py -> build\lib.win-amd64-2.7\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\hashes.py -> build\lib.win-amd64-2.7\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\hmac.py -> build\lib.win-amd64-2.7\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\rsa.py -> build\lib.win-amd64-2.7\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\utils.py -> build\lib.win-amd64-2.7\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\x509.py -> build\lib.win-amd64-2.7\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\__init__.py -> build\lib.win-amd64-2.7\cryptography\hazmat\backends\openssl
    creating build\lib.win-amd64-2.7\cryptography\hazmat\bindings\commoncrypto
    copying src\cryptography\hazmat\bindings\commoncrypto\binding.py -> build\lib.win-amd64-2.7\cryptography\hazmat\bindings\commoncrypto
    copying src\cryptography\hazmat\bindings\commoncrypto\__init__.py -> build\lib.win-amd64-2.7\cryptography\hazmat\bindings\commoncrypto
    creating build\lib.win-amd64-2.7\cryptography\hazmat\bindings\openssl
    copying src\cryptography\hazmat\bindings\openssl\binding.py -> build\lib.win-amd64-2.7\cryptography\hazmat\bindings\openssl
    copying src\cryptography\hazmat\bindings\openssl\_conditional.py -> build\lib.win-amd64-2.7\cryptography\hazmat\bindings\openssl
    copying src\cryptography\hazmat\bindings\openssl\__init__.py -> build\lib.win-amd64-2.7\cryptography\hazmat\bindings\openssl
    creating build\lib.win-amd64-2.7\cryptography\hazmat\primitives\asymmetric
    copying src\cryptography\hazmat\primitives\asymmetric\dh.py -> build\lib.win-amd64-2.7\cryptography\hazmat\primitives\asymmetric
    copying src\cryptography\hazmat\primitives\asymmetric\dsa.py -> build\lib.win-amd64-2.7\cryptography\hazmat\primitives\asymmetric
    copying src\cryptography\hazmat\primitives\asymmetric\ec.py -> build\lib.win-amd64-2.7\cryptography\hazmat\primitives\asymmetric
    copying src\cryptography\hazmat\primitives\asymmetric\padding.py -> build\lib.win-amd64-2.7\cryptography\hazmat\primitives\asymmetric
    copying src\cryptography\hazmat\primitives\asymmetric\rsa.py -> build\lib.win-amd64-2.7\cryptography\hazmat\primitives\asymmetric
    copying src\cryptography\hazmat\primitives\asymmetric\utils.py -> build\lib.win-amd64-2.7\cryptography\hazmat\primitives\asymmetric
    copying src\cryptography\hazmat\primitives\asymmetric\__init__.py -> build\lib.win-amd64-2.7\cryptography\hazmat\primitives\asymmetric
    creating build\lib.win-amd64-2.7\cryptography\hazmat\primitives\ciphers
    copying src\cryptography\hazmat\primitives\ciphers\algorithms.py -> build\lib.win-amd64-2.7\cryptography\hazmat\primitives\ciphers
    copying src\cryptography\hazmat\primitives\ciphers\base.py -> build\lib.win-amd64-2.7\cryptography\hazmat\primitives\ciphers
    copying src\cryptography\hazmat\primitives\ciphers\modes.py -> build\lib.win-amd64-2.7\cryptography\hazmat\primitives\ciphers
    copying src\cryptography\hazmat\primitives\ciphers\__init__.py -> build\lib.win-amd64-2.7\cryptography\hazmat\primitives\ciphers
    creating build\lib.win-amd64-2.7\cryptography\hazmat\primitives\interfaces
    copying src\cryptography\hazmat\primitives\interfaces\__init__.py -> build\lib.win-amd64-2.7\cryptography\hazmat\primitives\interfaces
    creating build\lib.win-amd64-2.7\cryptography\hazmat\primitives\kdf
    copying src\cryptography\hazmat\primitives\kdf\concatkdf.py -> build\lib.win-amd64-2.7\cryptography\hazmat\primitives\kdf
    copying src\cryptography\hazmat\primitives\kdf\hkdf.py -> build\lib.win-amd64-2.7\cryptography\hazmat\primitives\kdf
    copying src\cryptography\hazmat\primitives\kdf\kbkdf.py -> build\lib.win-amd64-2.7\cryptography\hazmat\primitives\kdf
    copying src\cryptography\hazmat\primitives\kdf\pbkdf2.py -> build\lib.win-amd64-2.7\cryptography\hazmat\primitives\kdf
    copying src\cryptography\hazmat\primitives\kdf\x963kdf.py -> build\lib.win-amd64-2.7\cryptography\hazmat\primitives\kdf
    copying src\cryptography\hazmat\primitives\kdf\__init__.py -> build\lib.win-amd64-2.7\cryptography\hazmat\primitives\kdf
    creating build\lib.win-amd64-2.7\cryptography\hazmat\primitives\twofactor
    copying src\cryptography\hazmat\primitives\twofactor\hotp.py -> build\lib.win-amd64-2.7\cryptography\hazmat\primitives\twofactor
    copying src\cryptography\hazmat\primitives\twofactor\totp.py -> build\lib.win-amd64-2.7\cryptography\hazmat\primitives\twofactor
    copying src\cryptography\hazmat\primitives\twofactor\utils.py -> build\lib.win-amd64-2.7\cryptography\hazmat\primitives\twofactor
    copying src\cryptography\hazmat\primitives\twofactor\__init__.py -> build\lib.win-amd64-2.7\cryptography\hazmat\primitives\twofactor
    running egg_info
    writing requirements to src\cryptography.egg-info\requires.txt
    writing src\cryptography.egg-info\PKG-INFO
    writing top-level names to src\cryptography.egg-info\top_level.txt
    writing dependency_links to src\cryptography.egg-info\dependency_links.txt
    writing entry points to src\cryptography.egg-info\entry_points.txt
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'src\cryptography.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    no previously-included directories found matching 'docs\_build'
    warning: no previously-included files matching '*' found under directory 'vectors'
    writing manifest file 'src\cryptography.egg-info\SOURCES.txt'
    running build_ext
    generating cffi module 'build\\temp.win-amd64-2.7\\Release\\_padding.c'
    creating build\temp.win-amd64-2.7
    creating build\temp.win-amd64-2.7\Release
    generating cffi module 'build\\temp.win-amd64-2.7\\Release\\_constant_time.c'
    generating cffi module 'build\\temp.win-amd64-2.7\\Release\\_openssl.c'
    building '_openssl' extension
    creating build\temp.win-amd64-2.7\Release\build
    creating build\temp.win-amd64-2.7\Release\build\temp.win-amd64-2.7
    creating build\temp.win-amd64-2.7\Release\build\temp.win-amd64-2.7\Release
    C:\Users\kiral\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Ic:\python27\include -Ic:\python27\PC /Tcbuild\temp.win-amd64-2.7\Release\_openssl.c /Fobuild\temp.win-amd64-2.7\Release\build\temp.win-amd64-2.7\Release\_openssl.obj
    _openssl.c
    build\temp.win-amd64-2.7\Release\_openssl.c(429) : fatal error C1083: Cannot open include file: 'openssl/opensslv.h': No such file or directory
error: command 'C:\\Users\\kiral\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\cl.exe' failed with exit status 2
    ----------------------------------------
Command "c:\python27\python.exe -c "import setuptools, tokenize;__file__='c:\\users\\kiral~1\\appdata\\local\\temp\\pip-build-jhbpvk\\cryptography\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\kiral~1\appdata\local\temp\pip-dawxbf-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\kiral~1\appdata\local\temp\pip-build-jhbpvk\cryptography
You are using pip version 7.1.2, however version 8.1.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

**Comment by redapple** [comment]
```
Collecting cryptography>=1.3 (from pyOpenSSL->Scrapy)
  Using cached cryptography-1.4.tar.gz
```
so it seems that you're not installing cryptography using [their wheel distribution](https://cryptography.io/en/latest/installation/#on-windows).
[This issue from `cryptography`](https://github.com/pyca/cryptography/issues/762) makes me think [you may not have a recent enough pip version](https://github.com/pyca/cryptography/issues/762#issuecomment-119237226):
> If you are getting an error claiming it can't find vcvarsall or a compiler please verify that your version of pip is the latest. Versions of pip older than 1.5 do not install wheels by default.

what version of `pip` are you using?

**Comment by kiral26** [comment]
pip 7.1.2

**Comment by redapple** [comment]
can you try upgrading `pip` and running `pip install --only-binary cryptography` to force the wheel install?

**Comment by redapple** [comment]
also with `--no-cache-dir `

**Comment by kiral26** [comment]
Fantastic, it's resolved! Scrapy 1.1.0 running. Thanks alot! You're the man.

**Comment by redapple** [comment]
what did the trick?

**Comment by kiral26** [comment]
upgraded pip and reinstalled cryptography
