### ISSUE TITLE
In Scrapy 1.1.0 --output as xml appending to existing file when spider re-executed resulting in invalid xml file with duplicate declaration

### ISSUE THREAD

**Issue by mobcdi** [scrapy/scrapy#2071]
## Issue

Scrapy is smart enough not to create duplicate file store copies when spider is re-run but appends output to xml file if `--output myxmlfile.xml` specified in command creating invalid xml file with 2nd declaration statement for each spider run after the xml file is created
## Possible Solution:

If xml file exists overwrite the contents not append to existing file or add option to allow user specify overwrite or append. (While the logfile is appended when a spider is re-run its structure isn't important to valid interpretation by 3rd party tools as is the case with xml files.
## To reproduce:

Run a spider via the command prompt and include option `--output myxmlfile.xml` and log the output to a file `--logfile mylogfile` when spider completes validate the xml using http://codebeautify.org/xmlvalidate and notice the xml is valid.
If you have set-up your spider to use the files pipeline and store a copy of every page indexed you can count  the number of files created in your FILES_STORE and note for later.

Re-run the spider command and notice the xml file increases in size, re-validate the xml and you should receive a similar validation message. 

> Error on->  Line :2 Column :155535 (or how ever many characters your line is before it encounters the 2nd declaration statement)
> Message :XML declaration allowed only at the start of the document
> Error on->  Line :3 Column :1
> Message :Extra content at the end of the document 

Check the FILES_STORE and note that you don't have any increase in number of files stored on disk. Check the log file for references `File (uptodate):` and note the crawler is smart enough to know the page was already created on disk so didn't create a duplicate but when exporting the items to xml it appends the duplicates to the existing file.

**Comment by redapple** [comment]
Related: https://github.com/scrapy/scrapy/issues/547

**Comment by kmike** [comment]
Also related: https://github.com/scrapy/scrapy/pull/2532

**Comment by wRAR** [comment]
> or add option to allow user specify overwrite or append

Done in 2.4.
