### ISSUE TITLE
Add tar.gz to ignored extensions in linkextractor 

### ISSUE THREAD

**Issue by alicenara** [scrapy/scrapy#2074]
I don't know if this goes here e_e but I've had problems when trying to parse a tar.gz as an html (now I check the extension) and I want to propose to include this type of file as an ignored one in scrapy/scrapy/linkextractors/**init**.py
(btw I have modified this file and I've added "tar.gz" and "gz" because I had the feeling "tar.gz" didn't work) 

Thanks :D

**Comment by redapple** [comment]
Related: https://github.com/scrapy/scrapy/pull/2067

Maybe this list should be a setting instead

**Comment by kmike** [comment]
I'm not sure it should be a setting (this way we'll be tying LinkExtractor to Scrapy projects), but it should be more obvious how to extend the default extensions list.

**Comment by anatolykazantsev** [comment]
Can it be an another parameter for the constructor of FilteringLinkExtractor class, e.g deny_extensions_append. It doesn't look good though. Or similar method.

But it's not harder than getting IGNORED_EXTENSIONS, adding custom extensions and then passing to the constructor. Maybe it just needs to be documented with an example.

**Comment by catap** [comment]
@redapple it isn't related to your pull request and let me explain why.

Inside `FilteringLinkExtractor` we have:
```
        if self.deny_extensions and url_has_any_extension(parsed_url, self.deny_extensions):
            return False
```

if we check `url_has_any_extension` definition we will fined that it simple:
```
def url_has_any_extension(url, extensions):
    return posixpath.splitext(parse_url(url).path)[1].lower() in extensions
```

but it returns always the last extention. So, it returns from URL `'http://google.gom/bla.tar.gz'` only `'g'`.

So, just adding `.tar.gz` into `IGNORED_EXTENSIONS` or to `LinkExtractor` instance over `deny_extensions` won't work ass expected.

@alicenara if it still relevant for you the easy and I guess only possible way to do it is adding `'.tar.gz$'` into `deny` argument of `LinkExtractor`.
