### ISSUE TITLE
how to discard timeouted request 

### ISSUE THREAD

**Issue by zymtech** [scrapy/scrapy#2075]
Hello,
    I am new to scrapy , hope to find some help here. I was using scrapy with unstable proxies,spider always close early than expected for network problem. So, how to ignore all kinds of errors and let spider goes on. I have tried adding errback function to handle httperror, decreasing CONCURRENT_REQUESTS setting and increasing the DOWNLOAD_TIMEOUT setting,etc, it didn't work eventually. So, can anybody tell me how to handle errors like "user timeout caused connection failure"?
    THANKS :)   .

**Comment by djunzu** [comment]
This is not a [complete, reproducible, specific bug report](http://doc.scrapy.org/en/1.1/contributing.html#reporting-bugs) or a feature request.

I suggest you post questions like "how to" or "is it possible" in [StackOverflow](http://stackoverflow.com/) or [scrapy-users mailing list](https://groups.google.com/forum/#!forum/scrapy-users). It is easier to find help for problems like this there.
