### ISSUE TITLE
Ubuntu official repository - installation failed (not able to find python-support)

### ISSUE THREAD

**Issue by inkrement** [scrapy/scrapy#2076]
I used the [manual](http://doc.scrapy.org/en/latest/topics/ubuntu.html) to install scrapy on ubuntu 16.04, but it failed because it was not able to install python-support (>= 0.90.0). Other sources report that this package is not part of the new ubuntu xenial anymore.

Quick&Dirty-Workaround:
```
wget http://launchpadlibrarian.net/109052632/python-support_1.0.15_all.deb
sudo dpkg -i python-support_1.0.15_all.deb
sudo apt-get update && sudo apt-get install scrapy
```

 * http://askubuntu.com/questions/766169/why-no-more-python-support-in-16-04
 * https://launchpad.net/ubuntu/xenial/amd64/python-support/1.0.15

**Comment by korsunowk** [comment]
# Install dependencies

apt-get install -y libffi-dev
apt-get install libssl-dev
apt-get install  python-pip

# Install scrapy

pip install scrapy

**Comment by micahra** [comment]
If all else fails, a fresh virtualenv might help

**Comment by gitressa** [comment]
Having tried and failed installing Scrapy with apt-get on Ubuntu 16.04, I finally managed to install it using Anaconda.

**Install Anaconda**
Just follow these instructions: https://www.digitalocean.com/community/tutorials/how-to-install-the-anaconda-python-distribution-on-ubuntu-16-04

**Install Scrapy**
Run this command from within a virtual environment:
`conda install -c conda-forge scrapy`
From: https://doc.scrapy.org/en/latest/intro/install.html
