### ISSUE TITLE
Broad crawl possible memory leak

### ISSUE THREAD

**Issue by rampage644** [scrapy/scrapy#2077]
Hi,

I was doing broad crawl and noticed constantly increasing memory consumption for a spider. Pruning my spider to most simple form doesn't help me here (memory still increases constantly).
I also noticed that others spiders (with much smaller crawl rates, `CONCURRENT_REQUESTS = 16`) don't have such problem.

So i was wondering if I misuse `scrapy` or there is a problem. Brief issue search didn't show anything, so I went ahead and created experimental spider for tests: https://github.com/rampage644/experimental

 1. First, I'd like to know if someone has experienced memory problems with high rate crawl or another memory problem.
 1. Second, I'd like to figure out why this simple spider leaks and can we do anything about that?

**Comment by rampage644** [comment]
I have read all doc resources regarding leaks.
Watching for `prefs()` output shows there always `CONCURRENT_REQUESTS` requests objects are alive and they're always refreshing (so they don't collect anywhere).

**Comment by lopuhin** [comment]
@rampage644 could you describe the memory growth you are seeing: for example, how much memory the spider consumes after X requests, how it grows, and the crawl rate you are getting? This will help when reproducing the issue.

**Comment by rampage644** [comment]
@lopuhin, I'm using 100 `CONCURRENT_REQUESTS` setting and able to 1200 rpm with 1 unit.
On startup `top` shows 60M rss size, in 30 minutes it grows up to 300M

**Comment by lopuhin** [comment]
@rampage644 thanks! Does it continue to grow after that? I think 300M is pretty normal for a spider.

**Comment by rampage644** [comment]
@lopuhin It will continue to grow until it gets killed :)

**Comment by rampage644** [comment]
It does ~1M requests before 950M limit is exhausted.

**Comment by kmike** [comment]
@rampage644 I tried a simplified version of your spider:

```py
# -*- coding: utf-8 -*-
import scrapy
from os.path import join, dirname
import experimental

class RequestsSpider(scrapy.Spider):
    name = "requests"

    def start_requests(self):
        filename = join(dirname(experimental.__file__), self.crawler.settings.get('SEEDS',))
        with open(filename, 'rt') as f:
            for line in f:
                url = line.strip()
                try:
                    yield scrapy.Request(url)
                except:
                    self.logger.error('Problem link: {}'.format(url))

    def parse(self, response):
        yield {'url': response.url}
```

and tried to run it with different settings:

* as-is;
* without a dupefilter;
* with disk queues enabled.

After ~25 minutes the results are:

```
19.1   0.1  974M  126M  2215 kmike        0 S   4:33.42     0  101K python3 /home/kmike/.envs/scraping/bin/scrapy crawl requests -s JOBDIR=./.job
21.0   0.1  967M  115M  2096 kmike        0 R   4:12.70     0     0 python3 /home/kmike/.envs/scraping/bin/scrapy crawl requests                      
16.7   0.1  962M  110M  2156 kmike        0 S   4:14.90     0     0 python3 /home/kmike/.envs/scraping/bin/scrapy crawl requests -s DUPEFILTER_CLASS=s
```

Speed is a bit less than in your case, probably because of network limitations. Surprisingly, with disk queues it uses more memory, though not much. I don't have an explanation for it. I'll keep the spiders running for some time.

**Comment by rampage644** [comment]
@kmike Thanks for digging in!

This is the exact version of spider i'm using (forgot to prune it back after some changes).
I've measured `Dupefilter` object memory usage and it was ~250 MB per 2M links. My understanding is that it has impact on memory usage but it's not a major one (at least)
In my experiments I'm seeing `len(engine.slot.scheduler.dqs) == 0` and `len(engine.slot.scheduler.mqs) == 0` (possibly because there is and inherent _queue_ -> generator). So queue should't have memory impact also.

**Comment by rampage644** [comment]
What i want to know in first place is: Am i writing spider correctly? Should i dig deeper to find the real reason behind the _leak_ (if it's present)?

**Comment by kmike** [comment]
Yeah, the spider looks correct. 

For me your example exited at ~180K links, and unfortunately I haven't noted how much memory it used in the end. I took a look earlier, and it was 160-220MB range, depending on options.

Maybe a new https://docs.python.org/3/library/tracemalloc.html module can help with debugging it? 

It could be the case it is not really a leak, but e.g. an inefficiency in garbage collector, but it's better to check that.

**Comment by lopuhin** [comment]
I tried to reproduce, the spider also existed after getting 172k items, and the memory was slowly growing up to 300M at the end, so it looks like the memory is indeed leaking somewhere.

**Comment by rampage644** [comment]
@lopuhin @kmike 
200k urls is my error - i've removed initial seed file for 2M links. Spider uses 200k seed file. That's why you're all seeing 172-180k links.

I have another idea in my mind: could it be possible stacktraces are stored somewhere? There are lot's of errors due to bad links: dns resolution, timeouts, etc.

**Comment by rampage644** [comment]
I've done some more experiments t pin down what is causing a leak:

 1. First I removed all links that caused error messages in log (because of downloader errors). Good news are that memory footprint was reduced from 440MB to 300MB at peak (according to stats). Bad news are it's still there. (Error entries in log count reduced from 20k to 2k).

 2. Second. Long in the past i noticed that sometimes `Requests` objects are stuck somewhere (according to `prefs()` output and `live_refs` info). There is a pattern here. `pprint.pprint(map(lambda x: (x[0], time.time()-x[1]), sorted(rqs.items(), key=operator.itemgetter(1))))` prints requests objects sorted by their creation time. Once `Requests` object start staying alive a group of them with pretty same time (>60s) appear in a tracking dict. That could happen multiple time, i.e. multiple groups.

 3. Third finding: While working on some focused crawl spider and trying to use guppy it shows nothing interesting: str, tuples, dict. But here i get bunch of `twisted` objects staying in memory (maybe they are present in other spiders, but here there are much more of them):
```
>>> hpy.heap()                                                                                                                                                                                                                                                                                                                
Partition of a set of 1286140 objects. Total size = 176360928 bytes.                                                                                                                                                                                                                                                          
 Index  Count   %     Size   % Cumulative  % Kind (class / dict of class)                                                                                                                                                                                                                                                     
     0 456074  35 29027064  16  29027064  16 str                                                                                                                                                                                                                                                                              
     1 261200  20 20719536  12  49746600  28 tuple                                                                                                                                                                                                                                                                            
     2 205542  16 16970096  10  66716696  38 list                                                                                                                                                                                                                                                                             
     3  17046   1 16640016   9  83356712  47 dict (no owner)                                                                                                                                                                                                                                                                  
     4  14746   1 15453808   9  98810520  56 dict of twisted.internet.base.DelayedCall                                                                                                                                                                                                                                        
     5   8403   1  8277960   5 107088480  61 dict of twisted.internet.defer.Deferred                                                                                                                                                                                                                                          
     6   7685   1  8053880   5 115142360  65 dict of twisted.internet.tcp.Client                                                                                                                                                                                                                                              
     7   7685   1  8053880   5 123196240  70 dict of twisted.internet.tcp.Connector                                                                                                                                                                                                                                           
     8   7677   1  8045496   5 131241736  74 dict of twisted.web._newclient.HTTP11ClientProtocol                                                                                                                                                                                                                              
     9  51931   4  4154480   2 135396216  77 types.MethodType               
```

I'm going to try @kmike advice  regarding `tracemalloc` module.

**Comment by lopuhin** [comment]
@rampage644 perhaps the contents of strings and tuples could reveal which requests are these? I think you can get them with something like ``h = hpy.heap(); h[0].byid``

**Comment by rampage644** [comment]
@lopuhin: What info do you want to get about requests? I', getting request object itself with `live_refs[scrapy.http.request.Request]` as well as creation time.

**Comment by rampage644** [comment]
My point was that there are always a bunch of `str`, `tuple`, `dict`. But group of `twisted` objects now consume ~30% of memory

**Comment by rampage644** [comment]
And one more observation: here is what i get once i have `Requests` begin to stuck:
```
>>> hpy.heap()
Partition of a set of 581174 objects. Total size = 114102600 bytes.
 Index  Count   %     Size   % Cumulative  % Kind (class / dict of class)
     0  20868   4 21869664  19  21869664  19 dict of scrapy.core.downloader.Slot
     1   8775   2 12298536  11  34168200  30 dict (no owner)
     2 136730  24 10510400   9  44678600  39 str
     3  42528   7  9866496   9  54545096  48 __builtin__.set
     4  78147  13  6229768   5  60774864  53 tuple
     5   5278   1  5531344   5  66306208  58 dict of twisted.internet.base.DelayedCall
     6  39515   7  4329752   4  70635960  62 list
     7   3926   1  3947024   3  74582984  65 dict of twisted.internet.defer.Deferred
     8   3736   1  3915328   3  78498312  69 dict of twisted.internet.tcp.Client
     9   3736   1  3915328   3  82413640  72 dict of twisted.internet.tcp.Connector
<1033 more rows. Type e.g. '_.more' to view.>
>>> prefs()
Live References

HtmlResponse                        3   oldest: 5s ago
Request                           365   oldest: 22s ago
RequestsSpider                      1   oldest: 768s ago
```

**Comment by lopuhin** [comment]
@rampage644 I meant that probably these ``str``, ``tuple`` and ``dict`` objects are also parts of requests that you are tracking, and by looking at the values themselves it would be possible to know which requests are these. But probably it's just ~all scheduled requests, so at that point it won't give any new information.

**Comment by rampage644** [comment]
Closing as no progress since too long :)
Hope it will be reopened eventually.

**Comment by kmike** [comment]
Ok, thanks for the update :)

**Comment by sandeepsingh** [comment]
Hi, 
I am doing broad crawl in BFO order upto depth 5 limit. Machine spec: 32 core, 104 GB Ram. 
The issue is the spider's memory keep on growing and eventually crashes. Memory size increased upto 60GB for once spider instance. 

Please help how to resolve this issue. 

Thanks

**Comment by kmike** [comment]
@sandeepsingh there could be many issues, but I think it is unlikely your problem is related to this ticket. There could be much simpler reasons - see https://doc.scrapy.org/en/latest/topics/leaks.html. I think that in your case the most likely reason is a request queue size, which can be very large for a BFO crawl. You need to enable disk queue and make sure no state is kept alive for a long time (request.meta is an usual suspect).

**Comment by mredaelli** [comment]
Thanks to @rampage644 I found out that my spider started going OOM because of a sudden increase in logging.

I am a bit surprised, though: what is the behaviour of logging in scrapinghub? Is the output stored in RAM? If so, why?
