### ISSUE TITLE
what's wrong with my css selector?

### ISSUE THREAD

**Issue by woshichuanqilz** [scrapy/scrapy#2078]
I use `selectorgadget` in Chrome to get the `css selector` of the *related question* in this [stackoverflow link](http://stackoverflow.com/questions/38065355/google-chrome-showing-black-edges-when-playing-video)
And I get the res like this 

![06~28_12-23-31.bmp](http://7xpvdr.com1.z0.glb.clouddn.com/06~28_12-23-31.bmp)

And I test in the scrapy shell but I get nothing
![06~28_12-21-18.bmp](http://7xpvdr.com1.z0.glb.clouddn.com/06~28_12-21-18.bmp)

How to fix this question ? 

**update:**
And so is this question 
![06~28_12-49-45.bmp](http://7xpvdr.com1.z0.glb.clouddn.com/06~28_12-49-45.bmp)

![06~28_12-50-34.bmp](http://7xpvdr.com1.z0.glb.clouddn.com/06~28_12-50-34.bmp)

But some css selector worked like : `.user-details a`

**Comment by redapple** [comment]
@woshichuanqilz , scrapy GitHub issues is not the proper place for "how to" questions, it's intended for architecture discussions or [reporting bugs](http://doc.scrapy.org/en/latest/contributing.html#reporting-bugs) including a _Minimal, Complete, and Verifiable example_
A better place is [StackOverflow](https://stackoverflow.com/questions/tagged/scrapy) itself or [scrapy-users mailing list](https://groups.google.com/forum/#!forum/scrapy-users)
Please report your trouble there instead. Thanks.

**Comment by woshichuanqilz** [comment]
@redapple sry for my mistake.
