### ISSUE TITLE
S3FilesStore should not disable SSL

### ISSUE THREAD

**Issue by wearpants** [scrapy/scrapy#2083]
Per [comment in source](https://github.com/scrapy/scrapy/blame/master/scrapy/pipelines/files.py#L121), the S3 storage backend for media pipelines silently strips SSL from the connection to S3, ostensibly because of this [python core bug](http://bugs.python.org/issue5103), which oddly enough was fixed 3 years before the code in scrapy was written.

This issue has been resolved in all modern versions of Python (2.7+/3.0+) for quite some time. Can this workaround be removed?

**Comment by nyov** [comment]
Yes, indeed. It's being worked on. See #2085.

**Comment by wRAR** [comment]
boto2 code was removed in #4776.
