### ISSUE TITLE
Tutorial paths out of date

### ISSUE THREAD

**Issue by znorris** [scrapy/scrapy#2090]
The x-paths and css paths in the [tutorial](https://github.com/scrapy/scrapy/blob/master/docs/intro/tutorial.rst) no longer work for dmoz.org and need to be updated.

I'll try to get a PR in for them once I have it sorted out.

**Comment by redapple** [comment]
Hi @znorris , thanks for reporting.
yeah, it's true...
A couple of related PRs already: https://github.com/scrapy/scrapy/pull/2032 , https://github.com/scrapy/dirbot/pull/20

**Comment by UltraBob** [comment]
It is possible that I should have done my work on the existing pull request at #2032, but I'm new to this process.  I added a new one at #2130 for this issue.

**Comment by kmike** [comment]
We've rewritten the tutorial using http://toscrape.com website instead of DMOZ; it should prevent it from breaking in future.
