### ISSUE TITLE
ImportError after Scrapy was installed

### ISSUE THREAD

**Issue by euler16** [scrapy/scrapy#2105]
I installed scrapy on Ubuntu 15.04 using pip install scrapy
but when I ran python on terminal and did import scrapy
the terminal reported ImportError

**Comment by redapple** [comment]
hi @euler16 , can you paste the whole traceback from your console?

**Comment by euler16** [comment]
![screenshot from 2016-07-08 19 36 47](https://cloud.githubusercontent.com/assets/18003525/16690017/60ca5aa0-4543-11e6-9b6e-cccc76419a0b.png)

**Comment by redapple** [comment]
It seems you installed scrapy under Python 3 (`/usr/local/lib/python3.4/`), but `python` in your shell launches the Python 2 interpreter

**Comment by redapple** [comment]
can you try this?

```
~$ python3
>>> import scrapy
```

**Comment by euler16** [comment]
thanks Sir @redapple  it worked .... how to install it for Python2

**Comment by redapple** [comment]
@euler16 , I don't know why `sudo pip install scrapy` installs it for Python 3 on your system.

We usually recommend using virtualenvs (for example using [`virtualenvwrapper`](https://virtualenvwrapper.readthedocs.io/en/latest/install.html)) to have parallel installations of scrapy in Python 2 and Python 3
e.g.:

```
~$ mkvirtualenv --python=/usr/bin/python3 scrapy.py3
(scrapy.py3) ~$ pip install scrapy
```
and then using `workon scrapy.py3` when you want to run with Python 3

```
~$ mkvirtualenv --python=/usr/bin/python2 scrapy.py2
(scrapy.py2) ~$ pip install scrapy
```
and `workon scrapy.py2` to use Python 2
