### ISSUE TITLE
scrapy don't detect an html element but it is visible on source page

### ISSUE THREAD

**Issue by mayouf** [scrapy/scrapy#2109]
Hello,

Cuuld someone help with a website where the informations appears in the source page and the browser but get vanish as soon as I use "scrapy shell" or "scrapy crawl".
I am not banned for sure and the whole page appears correctly but not the div containing the data I need.
Here is picture of the below link (french website property auction) with a regular browser like mozilla : 
http://www.licitor.com/ventes-judiciaires-immobilieres/tgi-fontainebleau/mercredi-15-juin-2016.html

![issue licitor 1](https://cloud.githubusercontent.com/assets/5865600/16708596/271cda82-45fa-11e6-89ef-69e8c752a7d7.png)

I encircled the data I target, BUT let us do it with the **view(response)** from **scrapy shell**:

**scrapy shell http://www.licitor.com/ventes-judiciaires-immobilieres/tgi-fontainebleau/mercredi-15-juin-2016.html**

![screenshot from 2016-07-09 17 30 13](https://cloud.githubusercontent.com/assets/5865600/16708631/d9ca002e-45fa-11e6-9f1a-625baa99100f.png)

and here is the result: a whole div disappeared !!!

I have some error in my terminal:

![screenshot from 2016-07-09 17 32 52](https://cloud.githubusercontent.com/assets/5865600/16708671/0d1c7668-45fc-11e6-84c0-0189b0860991.png)

To give you more information, I first tried on a scrapy project and I had to add **DOWNLOAD_HANDLERS: {'s3': None}** in my settings in order to get rid of an ERROR message...it did not work also, then by debugging I just tried with the shell and I noticed the response body was missing a part of the HTML.

I am running on ubuntu 14 and I have anaconda installed on it with scrapy 1.03.

Where do I miss the point please people ?

Thanks in advance for your help, I spent the whole afternoon on it !!

**Comment by kmike** [comment]
Hey @mayouf,

The difference is likely caused either by JavaScript or by different request headers. We are using github issue tracker for Scrapy bug reports; for support questions please use http://stackoverflow.com (with 'Scrapy' tag).
