### ISSUE TITLE
Files download fails with scrapy media_pipeline

### ISSUE THREAD

**Issue by sergei-sh** [scrapy/scrapy#2110]
When trying to download a number of large files with one instance of MediaPipeline, it stops downloading at some moment.

http://stackoverflow.com/questions/38270780/large-files-download-fails-with-scrapy-media-pipeline

**Comment by Gallaecio** [comment]
According to the logs of the StackOverflow question, the issue was indeed a timeout exceeding the 1800 timeout set by you.
