### ISSUE TITLE
item['LINK'] = response.request.url returns wrong/duplicate links

### ISSUE THREAD

**Issue by yssvic** [scrapy/scrapy#2116]
Hello, 

I run scrapy v1.1.0

I need some parts of the url to create some ids. Lately I have been noticing that response.request.url is returning a different url that the one that is used to scrape. 

In my code I use the item['LINK'] = response.request.url but that is putting in the wrong link on some scrapers like 2/10 approximately. 

Is there a better way to fetch the url? The one that is displayed in the debug scrapy output is correct. 

Thank you. 

This one outputted in the debug window is correct: 
2016-07-12 13:25:34 [scrapy] DEBUG: Scraped from <200 XXX >

The one I fetch with response.request.url is different and wrong.

**Comment by redapple** [comment]
What you get in `2016-07-12 13:25:34 [scrapy] DEBUG: Scraped from <200 XXX >` is `response.url`.
Can you test and let us know if it works for you 10/10?

**Comment by yssvic** [comment]
Hi thanks for the reply, I output the json I create right after the DEBUG message and that link that is in item['LINK'] = response.request.url  or item['LINK'] = response.url is 'sometimes 1 or 2 times out of 10' not the same as displayed in the DEBUG: Scraped from <200 link> right above it

What can I do? 

Cheers

**Comment by redapple** [comment]
@yssvic , very hard to say without playing with your spider.
what gets printed out comes [from the response object's `url` attribute](https://github.com/scrapy/scrapy/blob/master/scrapy/http/response/__init__.py#L61)
Could there be some middleware changing the url before it gets to your callback?

**Comment by yssvic** [comment]
Good point, let me go over the middleware, otherwise I'm just going to step over it in the debugger to see what's happening.

**Comment by redapple** [comment]
@yssvic , did you make any progress on the investigation?

**Comment by yssvic** [comment]
Hi, I have scrapers with the exact same middleware who don't have this problem and others who have, I can reproduce this problem 100% of the time. The debugger will show the 200 correct link and everything I do in the code to fetch this is showing a link from a previous scraped link. I will allocate time to step in the python code of scrapy to see what's going on. I think it's the only way. I have it with scrapers who use Splash and i have it with scrapers who don't use Splash. I have reduced the speed, insert wait times and have set the CONCURRENT_REQUESTS=1 but that doesn't change anything, it's still the same problem. Really weird. Cheers.

**Comment by redapple** [comment]
Without code to reproduce your issue, it's hard for us to help you.

**Comment by yssvic** [comment]
:-) Can you sign a NDA?

**Comment by redapple** [comment]
Not as myself, but you can contact Scrapinghub, where I work.

**Comment by redapple** [comment]
If there's indeed something wrong with `response.url`, you could also put some data in the `meta` dict of your different Requests, e.g. `scrapy.Request(someurl, callback=self.parse_something, meta={'original_url': someurl})`, and use that in you callbacks, e.g. `response.meta['original_url']`

**Comment by yssvic** [comment]
@redapple  I think I found it. I'm calling a LUA script as follows: 
request = SplashRequest(url, callback=self.parser_somename, endpoint='execute',args={'lua_source': SPLASH_SCRIPT})

and the lua script:

function main(splash)
    splash.resource_timeout = 200.0
    assert(splash:go(splash.args.url))
    splash:wait(15)
    splash:runjs('SOMEJAVASCRIPT')
    splash:wait(1)
    return splash:html()
end
'''

@redapple  could it be I need to add something extra parameter back and forth so the links don't get messed up? 

Thanks for your help, please can you send an account manager's email address from scrapinghub so I can get a quote for a few 1000 scrapers? 

Cheers

**Comment by redapple** [comment]
@yssvic , I'm not familiar enough with the internals of scrapy-splash middleware, but you can check what's in `response.meta['splash']`, the mdw puts lots of things there

**Comment by kmike** [comment]
@yssvic I think this issue belongs to [scrapy-splash](https://github.com/scrapy-plugins/scrapy-splash). It will help if you can provide an example: what URL did you expect, and what did you get. 

scrapy-splash makes HTTP request to Splash server, not to the website itself; when SplashRequest is used there is some magic to make request.url and response.url return what's expected. Maybe it breaks in your case, but I wonder why. Maybe the reason is https://github.com/scrapy/scrapy/issues/1890, or maybe you have some middleware which doesn't play nicely with scrapy-splash, or maybe there is a bug. It is very hard to tell without more details.

**Comment by neerajch** [comment]
Hi,

Please send email to sales@scrapinghub.com with your requirements or better would be to submit quote request here: http://scrapinghub.com/quote/

**Comment by yssvic** [comment]
@redapple @kmike Hello, I fixed it by grabbing the url data from 

item['debugsplash'] = response.meta['splash']['args']['url']

This was 100% always the correct url. I haven't figured it out why response.url is giving me the wrong one sometimes because I also have this problem with scrapers who don't use scrapy-splash and are just scraping pure html without any splash or lua scripting. 

Thanks for the help, I've submitted quote request. 

Cheers,

**Comment by kmike** [comment]
@yssvic I'm glad you solved it! 

Note that response.url is not the same as request.url or response.request.url: it is a final URL after all redirects. I've never seen either of them being wrong, so I wonder what's going on. Are these URLs completely unrelated in your case? Or maybe there is fragment missing? Or a `_escaped_fragment_?=...` parameter gets added? Is there any pattern?

**Comment by yssvic** [comment]
@kmike  It's on my list to do to allocate time to see what's exactly going on. I need to finish some spiders that needs to go in production first :-) 

Thanks for your help kmike, I've read so much posts from you over the years and that helped me a lot. 

Cheers

**Comment by nitinsunny** [comment]
**This worked like a magic!!!!!**
 response.meta['splash']['args']['url']
