### ISSUE TITLE
`django-configurations` CLI flag

### ISSUE THREAD

**Issue by lwm** [scrapy/scrapy#2123]
Would anyone be interested in accepting a pull request which adds the following flag:

```
$ scrapy runspider spider.py --dc=Dev
```

Where `--dc` is the [django-configurations][1] (inspired by [pytest-django][2]) settings environment.

This would then do the necessary:

```
import configurations
configurations.setup()
```

And allow `django-configurations` users to do something in `django` like:

```
class Scrapy:
    # scrapy options ...

class Dev(Scrapy, Configuration):
    pass
```

[1]: https://django-configurations.readthedocs.io/en/stable/
[2]: http://pytest-django.readthedocs.io/en/latest/configuring_django.html#using-django-configurations

**Comment by kmike** [comment]
I'm not wild about the idea, but maybe I just haven't encountered problems which are solved by django-configurations, or maybe I don't quite get the use case. 

Cons:

* there is already Settings class in Scrapy;
* depending on django-configurations looks weird; does it require django as well?

Other opinions are welcome :)

**Comment by lwm** [comment]
> or maybe I don't quite get the use case. 

If a user configures their `django` settings with `django-configurations`, they will get errors when they run the spider using the `scrapy-cli`:

```
(.venv) [cortex][set-initial-models] λ scrapy runspider scripts/article_spider.py                                                                                     [node-5.5.0][ruby-2.2.1]
    ... 
    raise ImproperlyConfigured(install_failure)
django.core.exceptions.ImproperlyConfigured: django-configurations settings importer wasn't correctly installed. Please use one of the starter functions to install it as mentioned in the docs: http://django-configurations.readthedocs.org/
```

This is because there is a missing configuration step using:

```
 import configurations
 configurations.setup()
```

The alternative is: In order to run a scrapy spider, which inherits settings from my `django` configurations, I need to use the [runscript](http://django-extensions.readthedocs.io/en/latest/runscript.html) command.

**Comment by lwm** [comment]
After writing this, it feels out of scope for `scrapy` given that the `runscript` command exists. Feel free to close :)
