### ISSUE TITLE
Missing data when scrape multiple start urls

### ISSUE THREAD

**Issue by hugo53** [scrapy/scrapy#2126]
When I try to scrape multiple start_urls, data seems to be missed. Let's say:
```
start_urls = [http://abc.com/sub1] --> return 5K records
start_urls = [http://abc.com/sub2] --> return 3K records
```
but

```
start_urls = [http://abc.com/sub1, http://abc.com/sub2] --> return only 3.7K records
```

My custom start_requests:
```
def start_requests(self):
        for url in self.start_urls:
            yield scrapy.Request(url=url, callback=self.parse, dont_filter=True)
```

I think it should return at least 8K records, but only 3.7K records. Anyone experience this problem? Please help!

Thanks!

**Comment by redapple** [comment]
@hugo53 , it'll be very hard to help you without seeing logs, stats or spider code.
I suggest that you ask in [scrapy-users mailing list](https://groups.google.com/d/forum/scrapy-users)

**Comment by hugo53** [comment]
@redapple Thank you for your suggestion, I just recheck and apparently my mistake when implement the parse.

**Comment by umarriaz9018** [comment]
Hi
Please let me know what mistake you had, because I am facing the same issue
