### ISSUE TITLE
My spider can't call the pipeline

### ISSUE THREAD

**Issue by fusae** [scrapy/scrapy#2131]
There are two spiders in my project, spider1 can call pipeline, but spider2 can't call pipeline, why?

**Comment by redapple** [comment]
@fusae , do you have a reproducible example of the behavior you are seeing?
These troubleshooting questions are usually a better for [scrapy-users mailing list](https://groups.google.com/d/forum/scrapy-users) or [StackOverflow](http://stackoverflow.com/) (with tag "scrapy")

**Comment by fusae** [comment]
@redapple I do post the question to the [ In scrapy-users mailing list ] (https://groups.google.com/forum/#!topic/scrapy-users/ZQv8aa6diZc) and [Stackoverflow](http://stackoverflow.com/questions/38432786/scrapy-a-weird-bug-code-that-cant-call-pipeline)
Maybe it is a hard question, nobody can answer.

**Comment by redapple** [comment]
HI @fusae , I commented on your StackOverflow question. Let's continue there.
