### ISSUE TITLE
https proxy dont work!

### ISSUE THREAD

**Issue by BuGoNee** [scrapy/scrapy#2134]
I want scraping http://www.lagou.com with  proxy.
I collected a lot of proxy server like this:
      {'https': 'https://110.72.7.236:8123'}
some of server can use http, some just support https.

I have some code check server is ok:

```
import requests

proxies = [
 {'https': 'https://39.66.5.213:8998'},
 {'https': 'https://111.200.106.5:8123'},
 {'https': 'https://110.72.7.236:8123'},
 {'https': 'https://123.180.122.83:8998'}
]
checkUrl = 'http://www.lagou.com/

def _check_proxy(proxy, timeout = None):
    try:
        r = requests.get(checkUrl, proxies =  proxy ,timeout = timeout)
        return r.status_code
   except:
        return 0

def main():
    for proxy in proxies:
        print proxy, _check_proxy(proxy, timeout=20)
main()
```

I think proxy server states is health.

BUT, when I proxy to scrapy , it's not ok, my proxy middleware code:
```

#!/usr/bin/env python
# -*- coding: utf-8 -*-
import sys
reload(sys)
sys.setdefaultencoding('utf8')

import pdb
import random
import base64
import time
import datetime
from codec import convert
from scrapy import signals
from scrapy.utils.project import get_project_settings

settings = get_project_settings()

class ProxyMiddleware(object):

    def __init__(self, settings):
        self.proxies = settings.get('PROXIES', [])

    @classmethod
    def from_crawler(cls, crawler):
        middleware = cls(crawler.settings)
        crawler.signals.connect(middleware.spider_opened, signals.spider_opened)
        crawler.signals.connect(middleware.spider_closed, signals.spider_closed)
        return middleware

    def spider_closed(self, spider):
        pass

    def spider_opened(self, spider):
        self.PROXIES = [
{'username': '', 'ip': '119.29.120.97', 'password': '', 'type': 'https', 'port': '80'},
{'username': '', 'ip': '115.46.68.190', 'password': '', 'type': 'https', 'port': '8123'},
{'username': '', 'ip': '60.163.3.9', 'password': '', 'type': 'https', 'port': '8118'},
{'username': '', 'ip': '171.37.134.201', 'password': '', 'type': 'https', 'port': '8123'},
]


    def process_request(self, request, spider):
        # Don't overwrite with a random one (server-side state for IP)
        #  if 'proxy' in request.meta:
            #  return
        proxy = random.choice(self.PROXIES)
        proxy_user_pass = proxy['username'] +':'+ proxy['password'] if proxy['username'] else ''
        print proxy_user_pass
        request.meta['proxy'] = "%s://%s:%s" % (proxy['type'], proxy['ip'], proxy['port'])
        #  request.meta['proxy'] = "http://%s:%s" % (proxy['ip'], proxy['port'])
        #  request.meta['proxy'] = 'https://180.76.163.61:10000'
        print request.meta
        if proxy_user_pass:
            basic_auth = 'Basic ' + base64.encodestring(proxy_user_pass)
            request.headers['Proxy-Authorization'] = basic_auth

    def process_exception(self, request, exception, spider):
        proxy = request.meta['proxy']
        spider.logger.error('%s! Removing failed proxy <%s>, %d proxies left' % (
            exception, proxy, len(self.proxies)))
        try:
            self.proxies.remove(proxy)
        except ValueError:
            pass
```

some error like this:

> 2016-07-21 16:50:10 [scrapy] DEBUG: Retrying <POST http://www.lagou.com/jobs/positionAjax.json?px=new&needAddtionalResult=false> (failed 1 times): [<twisted.python.failure.Failure <class 'twisted.internet.error.ConnectionLost'>>]
2016-07-21 16:50:10 [scrapy] DEBUG: Retrying <POST http://www.lagou.com/jobs/positionAjax.json?px=new&needAddtionalResult=false> (failed 2 times): An error occurred while connecting: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionLost'>: Connection to the other side was lost in a non-clean fashion: Connection lost.
].
2016-07-21 16:50:10 [scrapy] DEBUG: Gave up retrying <POST http://www.lagou.com/jobs/positionAjax.json?px=new&needAddtionalResult=false> (failed 3 times): An error occurred while connecting: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionLost'>: Connection to the other side was lost in a non-clean fashion: Connection lost.
].
2016-07-21 16:50:10 [lagou_new] ERROR: An error occurred while connecting: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionLost'>: Connection to the other side was lost in a non-clean fashion: Connection lost.
].! Removing failed proxy <https://1.59.94.112:8998>, 0 proxies left
2016-07-21 16:50:10 [scrapy] DEBUG: Retrying <POST http://www.lagou.com/jobs/positionAjax.json?px=new&needAddtionalResult=false> (failed 1 times): An error occurred while connecting: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionLost'>: Connection to the other side was lost in a non-clean fashion: Connection lost.
].

I did some test:

{'https':'https://180.76.163.61:10000'}  can support http, when i use it.
request.meta['proxy'] = 'https://180.76.163.61:10000' 

it's worked!

else server cannot support http, will did not work.

**Comment by redapple** [comment]
@BuGoNee , what version of scrapy are you using? (check with `scrapy version -v`)
The recently released Scrapy 1.1.1 version has a fix for HTTPS proxies related to missing `Host:` header.
See https://github.com/scrapy/scrapy/pull/2069

**Comment by BuGoNee** [comment]
Scrapy    : 1.1.1
lxml      : 3.6.0.0
libxml2   : 2.9.1
Twisted   : 13.2.0
Python    : 2.7.6 (default, Jun 22 2015, 17:58:13) - [GCC 4.8.2]
pyOpenSSL : 0.13 (OpenSSL 1.0.1f 6 Jan 2014)
Platform  : Linux-3.13.0-88-generic-x86_64-with-Ubuntu-14.04-trusty

**Comment by BuGoNee** [comment]
I used pip to install twisted Twisted (16.3.0)
I checked use `sudo pip list` just now , dont know why Twisted version is 13.2.0 when I input `scrapy version -v`

**Comment by redapple** [comment]
Can you check version and run tests within a virtualenv?

**Comment by redapple** [comment]
`scrapy version -v` doesn't do anything special:
```
import twisted
...
twisted.version.short()
```

**Comment by BuGoNee** [comment]
In [1]: import twisted

In [2]: twisted.version.short()
Out[2]: '13.2.0'

In [3]:

**Comment by BuGoNee** [comment]
I just try

> sudo pip install scrapy --upgrade

  before I input `scrapy version -v` and now the problem is gone.
 I guess I had old version scrapy when I meet this proxy problem.

**Comment by redapple** [comment]
Great to hear! Does it mean I can close the issue?

I would suggest that you use Python virtualenvs for your scrapy work.

Recommendation: Install [`virtualenvwrapper`](http://virtualenvwrapper.readthedocs.io/) and create a virtualenv 
```
mkvirtualenv scrapyproxies
(scrapyproxies) $ pip install scrapy
(scrapyproxies) $ scrapy crawl ....
```
this should ensure you're using the latest scrapy, twisted, w3lib etc.

**Comment by BuGoNee** [comment]
Thanks for your help 
I think the issue can close.
I'll give a try to use virtualenv

**Comment by DonghuaLau** [comment]
Any solution for https proxy ?

`$ scrapy version -v
Scrapy       : 1.5.0
lxml         : 4.1.1.0
libxml2      : 2.9.5
cssselect    : 1.0.3
parsel       : 1.3.1
w3lib        : 1.18.0
Twisted      : 17.9.0
Python       : 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)]
pyOpenSSL    : 17.5.0 (OpenSSL 1.1.0g  2 Nov 2017)
cryptography : 2.1.4
Platform     : Windows-7-6.1.7601-SP1`
