### ISSUE TITLE
Installing scrapy and scrapyd from the official APT repo on Ubuntu 16.04 

### ISSUE THREAD

**Issue by hieu-n** [scrapy/scrapy#2136]
I followed the document at: http://doc.scrapy.org/en/latest/topics/ubuntu.html
But when I tried to run `sudo apt-get update && sudo apt-get install scrapy scrapyd`. I got these errors:
```
Reading package lists...
W: http://archive.scrapy.org/ubuntu/dists/scrapy/InRelease: Signature by key 65D1B1CE9BCE5D04D51464F58F62CB1F627220E7 uses weak digest algorithm (SHA1)
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 scrapy : Depends: python-support (>= 0.90.0) but it is not installable
 scrapyd : Depends: python-support (>= 0.90.0) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by redapple** [comment]
@hieu-n , the "official packages" are unfortunately not up-to-date
Can I ask you to try the method from http://doc.scrapy.org/en/latest/intro/install.html#ubuntu-9-10-or-above, starting from onwards
> If you prefer to build the python dependencies locally instead of relying on system packages you’ll need to install their required non-python dependencies first:
> `sudo apt-get install python-dev python-pip libxml2-dev libxslt1-dev zlib1g-dev libffi-dev libssl-dev`

and use `pip install scrapy scrapyd`?

**Comment by hieu-n** [comment]
@redapple Thank you for the very prompt reply. `pip install scrapy scrapyd` works fine indeed. 

I just had the impression from the document (http://scrapyd.readthedocs.io/en/stable/install.html#installing-scrapyd-in-ubuntu) that the official repo is better suited for deployment on a server than `pip`. I did not know the repo was left dead. 

Should I close this issue?

**Comment by redapple** [comment]
I've opened https://github.com/scrapy/scrapy/issues/2137 to prevent this (I hope)

I'll close this for now if you agree.
