### ISSUE TITLE
DOC Deprecate official Ubuntu packages (until they get updated)

### ISSUE THREAD

**Issue by redapple** [scrapy/scrapy#2137]
Current official Ubuntu packages are not up-to-date with scrapy 1.1 and users are having trouble with them (see #2076, #2136)

The docs need to reflect that and not recommend using them.

This page http://doc.scrapy.org/en/latest/topics/ubuntu.html#topics-ubuntu is not relevant these days.

**Comment by kmike** [comment]
It should be also fixed on https://scrapy.org/ website.
