### ISSUE TITLE
https proxy dont work! again!

### ISSUE THREAD

**Issue by BuGoNee** [scrapy/scrapy#2139]
yesterday I post a issue #2134 
it's run good just one time, and now it's happen again.
I start a AWS EC2 instance to test version, I installed the newest version scrapy.

> Scrapy    : 1.1.1
> lxml      : 3.6.0.0
> libxml2   : 2.9.1
> Twisted   : 16.3.0
> Python    : 2.7.10 (default, Jul 20 2016, 20:53:27) - [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
> pyOpenSSL : 16.0.0 (OpenSSL 1.0.1k-fips 8 Jan 2015)
> Platform  : Linux-4.4.10-22.54.amzn1.x86_64-x86_64-with-glibc2.2.5

I want scraping http://www.lagou.com , this is a http website.
some of my proxy servers support http and https, some just support https.
server that support http/https can use in my spider proxy,
server that not support http cannot use in my spider proxy.
I want use https because its more speedy and stable, and most of  server I collected is  https only.

**Comment by BuGoNee** [comment]
I made a decision

**Comment by redapple** [comment]
@BuGoNee , so you found the root problem?

**Comment by BuGoNee** [comment]
no......I decided only use those proxy can support http&https.......
