### ISSUE TITLE
Scrapy uses `file://` URL as referer

### ISSUE THREAD

**Issue by char101** [scrapy/scrapy#2142]
If I use a local file in a request (e.g. 

``` python
def start_requests(self):
    yield Request(path_to_file_uri(filename))

def parse(self, response):
    for url in json.loads(response.text):
        yield Request(url)
```

and then make a HTTP request in the callback, scrapy uses the file URL as the `referer` in the HTTP header. 

I think `file://` URL should be avoided from being used as the `referer` value (or generally any protocol other than http/s) because
1. it is not part of the normal hyperlink navigation
2. it exposes the local file structure to the remote site

**Comment by kmike** [comment]
+1, makes sense. 

It seems there are more rules for Referer header which browsers implement. I haven't checked it myself, but
http://webmasters.stackexchange.com/questions/47405/how-can-i-pass-referrer-header-from-my-https-domain-to-http-domains suggests that Referer is not sent for requests sent from https pages to any pages not in the same domain. RFC doesn't require browsers to do so, but it looks they do it for security/privacy reasons. 

http://www.redpill-linpro.com/sysadvent//2015/12/17/referer-header.html gives another list of rules.
