### ISSUE TITLE
PEP8 not enforced strictly

### ISSUE THREAD

**Issue by darshanime** [scrapy/scrapy#2144]
PEP8 is [recommended in the docs](http://doc.scrapy.org/en/latest/contributing.html#coding-style) but is not strictly enforced. 

Some violations:
1. Multiple imports in [one line](https://github.com/scrapy/scrapy/blob/master/scrapy/commands/edit.py#L1)
2. Two blank lines [not maintained](https://github.com/scrapy/scrapy/blob/master/scrapy/commands/edit.py#L5) between class definitions.
3. [Unused imports](https://github.com/scrapy/scrapy/blob/master/scrapy/commands/check.py#L3) 
4. Lines longer than 80 characters everywhere

I believe we should strictly enforce PEP8 and also edit our CI configurations to test for these violations. 
I would love to submit a patch for this if the idea sounds good to everyone.

**Comment by darshanime** [comment]
ping @kmike, @redapple, @jdemaeyer

**Comment by jdemaeyer** [comment]
hey @darshanime,

I used to be (and mostly still am) a big PEP8 nitpicker, but I really enjoyed this talk by Raymond Hettinger: https://www.youtube.com/watch?v=wf-BqAjZb8M. Style guides are meant to increase code readability and not maintenance overhead. In particular, there is a reason that we explicitly allow lines to be longer than 79 characters.

For the other points, I think they are "fix-worthy" though not high priority. If you feel like making a patch, go for it! Putting PEP8 checks (with the requirement on line length dropped/adjusted) is also a good move in my opinion.

**Comment by noviluni** [comment]
@Gallaecio @wRAR I think this issue could be closed as since we merged this: https://github.com/scrapy/scrapy/pull/3945 we are actively enforcing pep8 and fixing the current code rule by rule.

**Comment by wRAR** [comment]
Indeed.
