### ISSUE TITLE
How to handle exception in pipeline with signal?

### ISSUE THREAD

**Issue by Gwill** [scrapy/scrapy#2147]
Just like using Extention Class connectted spider_error signal. 

How to handle exception in pipeline with signal?

**Comment by Digenis** [comment]
There are currently no signals for errors in a pipeline's process_item
(unless it's a DropItem exception).
You need to handle exceptions on your own.

**Comment by redapple** [comment]
@Gwill , what kind of exceptions are you dealing with ?

**Comment by Gallaecio** [comment]
Closing due to a lack of feedback.
