### ISSUE TITLE
mail send does not work properly if argument "to" is string

### ISSUE THREAD

**Issue by sbarratt** [scrapy/scrapy#2148]
Scrapy Code:
```python
mailsender = MailSender(debug=True)
mailsender.send(to='test@scrapy.org', subject='subject', body='body', _callback=self._catch_mail_sent)
```

In file scrapy/mail.py:
```
msg['From'] = self.mailfrom
msg['To'] = COMMASPACE.join(to) # Problem Line
msg['Date'] = formatdate(localtime=True)
msg['Subject'] = subject
```

assumes `to` is a list. It sets the msg MIMEMultipart to `msg['to'] = ['t', 'e', 's', 't', '@', 's', 'c', 'r', 'a', 'p', 'y','o','r','g']` instead of `test@scrapy.org`.

**Comment by Digenis** [comment]
The documentation says that it expects a list.
Accidental iteration over strings is one of the scenarios
where enforcing type safety can be acceptable.
Here however, the worst that can happen is to send an email
to an unlikely to exist user on the localhost.

**Comment by redapple** [comment]
@sbarratt , as @Digenis points out, the docs do mention "to" and "cc" should be lists.
I've opened https://github.com/scrapy/scrapy/issues/2244 to improve the docs.
