### ISSUE TITLE
Is it any plan to support downloading "data:image/jpeg;base64"

### ISSUE THREAD

**Issue by yssource** [scrapy/scrapy#2156]
[scrapy] ERROR: Error downloading <GET data:/robots.txt>: Unsupported URL scheme 'data': no handler available for that scheme
...
scrapy.exceptions.NotSupported: Unsupported URL scheme 'data': no handler available for that scheme

I try to download a image form src attribute "data:image/jpeg;base64", But, an error happens to me.

**Comment by ArturGaspar** [comment]
You can copy the code of this download handler: https://github.com/ArturGaspar/scrapy-qtwebkit/blob/master/scrapy_qtwebkit/data_downloader.py

And enable it in the settings with: 

    DOWNLOAD_HANDLERS = {
        'data': 'your_module.DataURLDownloadHandler'
    }

To the Scrapy team, if there is any interest in supporting this in Scrapy, I can write tests and make a pull request.

**Comment by eliasdorneles** [comment]
Nice project, @ArturGaspar !
Yeah, that download handler looks useful, I think it would be valuable in Scrapy too.

I don't quite follow all those tricky regexes, wouldn't it be clearer if they were spelled out?

**Comment by redapple** [comment]
Thanks @ArturGaspar!
I second @eliasdorneles on this, I'd also like to see this in scrapy core.
Waiting for the PR :)

**Comment by redapple** [comment]
@yssource , see https://github.com/scrapy/scrapy/pull/2175 and https://github.com/scrapy/w3lib/pull/71
It should land in scrapy soon enough.

**Comment by yssource** [comment]
Thanks everyone. This works for me very well.
Please feel free to close this issue.

**Comment by redapple** [comment]
@yssource , we'll close the issue once the PR in w3lib is merged and a new w3lib is released and once scrapy updates its download handlers to use the functionality
