### ISSUE TITLE
doesn't support appending log file

### ISSUE THREAD

**Issue by Canidy** [scrapy/scrapy#2170]
log setting doesn't support multi file.
i.e,generate a log file according to max file size or date

**Comment by leearic** [comment]
why no't  use syslog ?





leearic@126.com
 
From: Canidy
Date: 2016-08-10 16:41
To: scrapy/scrapy
Subject: [scrapy/scrapy] doesn't support appending log file (#2170)
log setting doesn't support multi file.
i.e,generate a log file according to max file size or date
