### ISSUE TITLE
Dump stats to log periodically, not only at the end of the crawl

### ISSUE THREAD

**Issue by kmike** [scrapy/scrapy#2173]
It is useful to check Scrapy stats as spider runs, but there is no a built-in way to do that. What do you think about adding `DUMP_STATS_INTERVAL` option and outputting current stats to logs each `DUMP_STATS_INTERVAL` seconds?

Another related proposal (sorry for putting them all into this ticket) is to add more logging to Downloader and log periodically a number of pages Downloader is currently trying to fetch (`MONITOR_DOWNLOADS_INTERVAL` option). Checking that helps to understand what is crawler doing - is it busy downloading data or not.

Implementation draft:

``` python
import logging
import pprint

from twisted.internet.task import LoopingCall
from scrapy import signals

logger = logging.getLogger(__name__)


class _LoopingExtension:
    def setup_looping_task(self, task, crawler, interval):
        self._interval = interval
        self._task = LoopingCall(task)
        crawler.signals.connect(self.spider_opened, signal=signals.spider_opened)
        crawler.signals.connect(self.spider_closed, signal=signals.spider_closed)

    def spider_opened(self):
        self._task.start(self._interval, now=False)

    def spider_closed(self):
        if self._task.running:
            self._task.stop()


class MonitorDownloadsExtension(_LoopingExtension):
    """
    Enable this extension to periodically log a number of active downloads.
    """
    def __init__(self, crawler, interval):
        self.crawler = crawler
        self.setup_looping_task(self.monitor, crawler, interval)

    @classmethod
    def from_crawler(cls, crawler):
        # fixme: 0 should mean NotConfigured
        interval = crawler.settings.getfloat("MONITOR_DOWNLOADS_INTERVAL", 10.0)
        return cls(crawler, interval)

    def monitor(self):
        active_downloads = len(self.crawler.engine.downloader.active)
        logger.info("Active downloads: {}".format(active_downloads))


class DumpStatsExtension(_LoopingExtension):
    """
    Enable this extension to log Scrapy stats periodically, not only
    at the end of the crawl.
    """
    def __init__(self, crawler, interval):
        self.stats = crawler.stats
        self.setup_looping_task(self.print_stats, crawler, interval)

    def print_stats(self):
        stats = self.stats.get_stats()
        logger.info("Scrapy stats:\n" + pprint.pformat(stats))

    @classmethod
    def from_crawler(cls, crawler):
        interval = crawler.settings.getfloat("DUMP_STATS_INTERVAL", 60.0)
        # fixme: 0 should mean NotConfigured
        return cls(crawler, interval)
```

To get a feel on how it works copy-paste the code above to a project (e.g. to myproject/extensions.py) file, then add them to EXTENSIONS in settings.py:

``` python
EXTENSIONS = {
    'myproject.extensions.MonitorDownloadsExtension': 100,
    'myproject.extensions.DumpStatsExtension': 101,
}

```

**Comment by eliasdorneles** [comment]
Loved the dump stats feature! :heart: 

Question: would it make sense to have an option to use a format more easily parseable? (e.g. JSON)
It would be nice to be able to quickly build a report or plot of some stat like memory stuff, parsing the log file. :)

**Comment by redapple** [comment]
JSON format would be handy, e.g. for logstash processing.

**Comment by kmike** [comment]
JSON output is easy to implement, but there is a couple of caveats:

1. If we implement JSON dump it should be implemented consistently - both for periodic stat dumps and for the dump at the end of the crawl.
2. pprint handles more data types than json.dumps, even with ScrapyJSONEncoder. This means that for backwards compatibility it makes sense to keep pprint as a default. I'm not sure many people are doing that, but for example I used https://github.com/kurtbrose/faststat objects in stats to keep track of download latencies (not only averages, but percentiles as well); I was putting these objects directly to stats. It worked for pprint, but it will break for json.

For the record, JSON stat dumps look nice with `ScrapyJSONEncoder(sort_keys=True, indent=4)`:

```
{
    "downloader/request_bytes": 7248,
    "downloader/request_count": 25,
    "downloader/request_method_count/GET": 25,
    "downloader/response_bytes": 80003,
    "downloader/response_count": 11,
    "downloader/response_status_count/200": 11,
    "log_count/DEBUG": 12,
    "log_count/INFO": 11,
    "request_depth_max": 1,
    "response_received_count": 11,
    "scheduler/dequeued": 25,
    "scheduler/dequeued/memory": 25,
    "scheduler/enqueued": 992,
    "scheduler/enqueued/memory": 992,
    "start_time": "2017-01-30 17:57:15"
}
```

What do you think about making it a separate issue?

**Comment by lorenzfischer** [comment]
I'm a bit late to the party here, but I got this done by using a custom middleware. I hope this helps!

```
class StatsPrinter(object):

    def __init__(self, user_agent=''):
        self._last_print = datetime.datetime.now()
        self._reporting_interval_secs = 60

    def process_request(self, request, spider):
        if (datetime.datetime.now() - self._last_print).total_seconds() > self._reporting_interval_secs:
            total_mb_out = spider.crawler.stats.get_value('downloader/request_bytes') / 8 / 1024 / 1024
            total_mb_in = spider.crawler.stats.get_value('downloader/response_bytes') / 8 / 1024 / 1024
            logging.info("Data transferred: {:,.2f} MB (in: {:,.2f} MB, out: {:,.2f} MB)"
                         .format(total_mb_in + total_mb_out, total_mb_in, total_mb_out))
            logging.debug("Dumping Scrapy stats:\n" + pprint.pformat(spider.crawler.stats.get_stats()),
                          extra={'spider': spider})
            self._last_print = datetime.datetime.now()

        return None  # return None, so there is no impact on the processing
```

**Comment by lavoie005** [comment]
Hi guys, I new in python, I try to catch at the end of the scrapy script the date time in the log to dump it at the end of my csv file.
How can we get scrapy log with the ending date and time?

**Comment by Gallaecio** [comment]
> Hi guys, I new in python, I try to catch at the end of the scrapy script the date time in the log to dump it at the end of my csv file.
> How can we get scrapy log with the ending date and time?

@lavoie005 Please, use [StackOverflow](https://stackoverflow.com/tags/scrapy) to ask questions, not existing, unrelated tickets. See [Getting Help](https://docs.scrapy.org/en/latest/#getting-help).

**Comment by Gallaecio** [comment]
Should we close this given https://github.com/scrapy/scrapy/pull/5926, or should we still aim to support periodic logging for the default stats format without deltas?
