### ISSUE TITLE
Error Running Scrapy through script(Py/Shell)

### ISSUE THREAD

**Issue by kgrvamsi** [scrapy/scrapy#2176]
1)Running the Scrapy command from the Python script with the subprocess

from subprocess import call
import sys

sys.path.append("SCRAPYPROJECTPATH")
call (["scrapy","crawl","example"])

2)Running the Shell Script from the Python Script (The call value from the above script changes to sh shellscriptname.sh)

Output

```
Traceback (most recent call last):
  File "/usr/local/bin/scrapy", line 11, in <module>
    sys.exit(execute())
  File "/usr/local/lib/python2.7/dist-packages/scrapy/cmdline.py", line 109, in execute
    settings = get_project_settings()
  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/project.py", line 60, in get_project_settings
    settings.setmodule(settings_module_path, priority='project')
  File "/usr/local/lib/python2.7/dist-packages/scrapy/settings/__init__.py", line 108, in setmodule
    module = import_module(module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named project.settings

```

**Comment by kgrvamsi** [comment]
@redapple @kmike  Please can you help me on this issue :cry:

**Comment by podolskyi** [comment]
Scrapy has API, which you can use for run crawl from python script 
example: http://scrapy.readthedocs.io/en/stable/topics/practices.html

**Comment by redapple** [comment]
@kgrvamsi ,
the recommended way to run scrapy spiders from a script is indeed [what @podolskyi linked](https://github.com/scrapy/scrapy/issues/2176#issuecomment-239700707).
If that doesn't work, can you share your file hierarchy, `scrapy.cfg`, `settings.py`?

**Comment by kgrvamsi** [comment]
@podolskyi  Thanks for that info and i have tried using the Crawler,CrawlerProcess,CrawlerRunner methods to run the Spiders but i end up with the ReactorNotStartable Error all the time which i'm really confused on how to handle the reactor when the Spider runs on repeated basis like

Assume i have the following
```
Class Spider1():

Class Spider2():

here the Reactor should be open all the time to run the Spiders for every 30 mins.
 process = Crawler()/CrawlerProcess()/CrawlerRunner()
#here we write a lambda function to close the spider and then close the reactor
reactor.start()
```
@redapple Thanks for your reply and here are the files info

scrapy.cfg

```
# Automatically created by: scrapy startproject
#
# For more information about the [deploy] section see:
# http://doc.scrapy.org/en/latest/topics/scrapyd.html

[settings]
default = project.settings

[deploy]
#url = http://localhost:6800/
project = project
```
settings.py --- Nothing changed in this file.

@redapple I'm more interested in doing the API Crawler way of doing but as said i'm more confused on the reactor handling and which Class i need to use to run the Spiders on regular intervals.Any Preferred Code Sample or gist on how to do it will be really helpful.

**Comment by podolskyi** [comment]
@kgrvamsi look at the simple example https://github.com/podolskyi/scrapy_example
maybe you see some error in scraping, because I delete part of code, but it's structure from real projects.

**Comment by kgrvamsi** [comment]
@podolskyi i checked the above repo crawling.py on how it was implemented and i tried the same with the code i have and it works fine running for the first time and then the second time it returns the following error.

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nameko/containers.py", line 414, in _run_worker
    result = method(*worker_ctx.args, **worker_ctx.kwargs)
  File "./updater.py", line 71, in random_checking
    reactor.run()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1193, in run
    self.startRunning(installSignalHandlers=installSignalHandlers)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1173, in startRunning
    ReactorBase.startRunning(self)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 684, in startRunning
    raise error.ReactorNotRestartable()
ReactorNotRestartable
```

**Comment by kgrvamsi** [comment]
@podolskyi @redapple Thanks for your prompt responses and i regret the decision of running scrapy in a microservice model with Nameko framework and now needs to check how i can make my own microservice implementation with the thin Frameworks like Flask.

**Comment by kmike** [comment]
@kgrvamsi if you're going to built it with Flask you may find answers at http://stackoverflow.com/questions/36384286/how-to-integrate-flask-scrapy and http://stackoverflow.com/questions/32724537/building-a-restful-flask-api-for-scrapy/32784312 useful.

**Comment by kgrvamsi** [comment]
@kmike  Thanks for the Info and does the code out there in those url works with the Scrapy 1.0.5 version or they are any version specific code out there?

**Comment by kmike** [comment]
@kgrvamsi it should work in Scrapy 1.0+, including Scrapy 1.0.5. 
Note that Scrapy 1.0.x is no longer supported by us; upgrading to 1.1.x is a good idea :)
