### ISSUE TITLE
rename spider will load the old left .pyc instead of renamed spider

### ISSUE THREAD

**Issue by samson-wang** [scrapy/scrapy#2181]
Hi all, I'm not sure if this is an issue.
If got `y.py` and `y.pyc` in the `spider` directory.
Then rename it with `mv y.py x.py` and update the new `x.py`.
After updates, run `scrapy crawl spider` will use the old version of spider instead of updates in the `x.py`.
Have to remove `y.pyc` first.
Thanks!

**Comment by candlejack297** [comment]
Isn't this just normal Python .pyc problems? Pretty sure it's not scrapy specific. If you're actively moving/editing source code, you should just clear all .pyc files to avoid any issues (they'll get regenerated automatically).

**Comment by samson-wang** [comment]
@candlejack297 You're right. 
However scrapy automatically load the spider code in the ``spiders`` directory. I thought scrapy should have handled this situation.

**Comment by djunzu** [comment]
That is just how Python works. (No?) Scrapy is written in Python. That means it is restricted by all constraints that applies to Python scripts/programs.

I think it is not a Scrapy bug.
As a feature request, I would say that it does not worth the needed code.

**Comment by redapple** [comment]
May not be worth the effort, but if it's to be investigated, I believe it'd be around
[SpiderLoader](https://github.com/scrapy/scrapy/blob/ebef6d7c6dd8922210db8a4a44f48fe27ee0cd16/scrapy/spiderloader.py#L12) and how it uses `importlib.import_module` in [`walk_modules`](https://github.com/scrapy/scrapy/blob/master/scrapy/utils/misc.py#L54)
Maybe look at [imp.load_source](https://docs.python.org/2/library/imp.html#imp.load_source) (hint from http://stackoverflow.com/a/8422549)

**Comment by kmike** [comment]
I think we shouldn't mess with pyc files and implement special handling of them; pyc files are standard Python feature and it'd be too opinionated to assume that .pyc modules shouldn't be loaded - e.g. someone may choose to deploy pyc files instead of .py files.

What I think we should do is to warn if there are several spiders with the same name. It is a more general problem; it is specific to scrapy, not to .pyc files handling.

**Comment by jhabdas** [comment]
> I'm not sure if this is an issue.

It wasn't an issue, but I'm new to Python and this issue helped me when I needed to get past the warning mentioned in the title. Thank you!! 🥇
