### ISSUE TITLE
enable memusage extension by default

### ISSUE THREAD

**Issue by kmike** [scrapy/scrapy#2187]
What about setting MEMUSAGE_ENABLED to True by default? It will enable `memusage/max` value in stats for all spiders, and the cost is just one `getrusage(RUSAGE_SELF)` call per minute.

**Comment by redapple** [comment]
@kmike , as long as we keep `MEMUSAGE_LIMIT_MB` default to 0, I like the idea.
I'm sensing this is related to https://github.com/scrapy/scrapy/issues/2173 , or?
By the way, `MEMUSAGE_REPORT` [doesn't seem to do anything](https://github.com/scrapy/scrapy/blob/ebef6d7c6dd8922210db8a4a44f48fe27ee0cd16/scrapy/extensions/memusage.py#L38).

As a side note, we need to do a better job at reporting memory usage when limit is reached, it seems the extension only prints the engine status when email notificaations are on.

**Comment by kmike** [comment]
@redapple yep, it is related to #2173 - it helps with ad-hoc monitoring of the crawls by looking at the logs while the spider is still crawling.

**Comment by kmike** [comment]
Good catch about MEMUSAGE_REPORT and other memusage issues. 
One more issue: https://github.com/scrapy/scrapy/pull/1329

**Comment by eliasdorneles** [comment]
I'd :+1: anything giving more visibility to what's happening with the spider with minimal noise & cost, like this. :)
