### ISSUE TITLE
MediaPipeline ignoring redirect middleware

### ISSUE THREAD

**Issue by Granitas** [scrapy/scrapy#2191]
```
request.meta['handle_httpstatus_all'] = True
dfd = self.crawler.engine.download(request, info.spider)
```
When Media Pipeline schedules request it attached `handle_httpstatus_all` meta which prevents Redirect Middleware from doing it's job. This breaks download of images that require redirect, mostly urls that need to redirect from `http` to  `https`.

Maybe implement a setting to enable redirects in this pipeline?

**Comment by redapple** [comment]
Related: https://github.com/scrapy/scrapy/issues/2004

**Comment by redapple** [comment]
Closing as duplicate of https://github.com/scrapy/scrapy/issues/2004
