### ISSUE TITLE
add "https everywhere" middleware

### ISSUE THREAD

**Issue by pawelmhm** [scrapy/scrapy#2192]
I have bunch of spiders in project that consume lists of urls. It seems like currently lots of websites are moving from http to https. This means that all my outdated url are now redirecting to https. This is somewhat annoying because spider gets huge amount of redirects and it gets slower.  It also leads to unexpected issues when downloading images (image pipeline doesn't follow redirects as explained here #2191 so if I have http://image.png and it gets redirected to https://image.png I get error). I know I can update my urls but it's not always easy or possible (I dont have easy access to those urls, some of them are generated by user).

I was thinking about adding some downloader middleware that would replace protocol to https from http on all requests flowing from spider, it would be really trivial to implement (process_request method on downloader middleware object) and could be enabled by some setting key, e.g. `HTTPS_EVERYWHERE = True/False`. 

Does it sound like useful addition to Scrapy or should I limit it to my project?

**Comment by redapple** [comment]
@pawelmhm , I like the idea of that option. it could go into scrapy-plugins, but it could be a nice-to-have, default-off built-in middleware

**Comment by kmike** [comment]
A lot of websites doesn't support https, so just replacing protocol is not enough - request should be retried with http if https fails. As a general solution fixing URL list sounds better to me, because it can resolve other redirects (not only http/https), and won't cause unnecessary retry requests after the first crawl.

**Comment by nyov** [comment]
I would also like such a middleware, if anyone has built one in the interim?

It would be nice to enforce a protocol (http or https) per domain, where the domain supports both but failed to use `://`-agnostic links or still 'forces' http on only some old pages.
That would be very helpful for (potentially massive) httpcache-deduplication when both ressources are the same, but treated as different pages.  
Especially _for_ agnostic links, that could mean one http-link hit would open up a whole new cache-domain for one domain? (In theory, I haven't tested it.)

The ability to auto-detect that case (checking a few links on both protocols, per domain, and determining non-existing differences between both results), and then setting a flag per that domain for rewriting URIs, would be a bonus but not inherently necessary.
