### ISSUE TITLE
there is frequent logging error while i scrap web pages

### ISSUE THREAD

**Issue by Canidy** [scrapy/scrapy#2199]
Logged from file retry.py, line 68
Traceback (most recent call last):
  File "c:\python27\lib\logging__init__.py", line 884, in emit
    stream.write(fs % msg.encode("UTF-8"))
UnicodeDecodeError: 'utf8' codec can't decode byte 0xd3 in position 234: invalid continuation byte
Logged from file retry.py, line 68
Traceback (most recent call last):
  File "c:\python27\lib\logging__init__.py", line 884, in emit
    stream.write(fs % msg.encode("UTF-8"))
UnicodeDecodeError: 'utf8' codec can't decode byte 0xd3 in position 234: invalid continuation byte

**Comment by kmike** [comment]
Hey @Canidy,

What scrapy version are you using?

**Comment by Canidy** [comment]
@kmike version 1.1.1

**Comment by redapple** [comment]
@Canidy , could you perhaps share the URL that is being retried if you're able to pinpoint the ones that cannot be logged?
(you can send me private email if you don't want to disclose it)

**Comment by Canidy** [comment]
@redapple  the urls have no record while errors occur, so  i just comment the lines to ignore the retry logging ,

# logger.debug("Retrying %(request)s (failed %(retries)d times): %(reason)s",
#              {'request': request, 'retries': retries, 'reason': reason},
#              extra={'spider': spider})

now it feel better.

**Comment by redapple** [comment]
Ok. If you find a problematic URL sometime in the future, it would be great if you could post it here. Thx

**Comment by cathalgarvey** [comment]
Hi folks, I'm closing this as stale and non-reproducible. Feel free to reopen if it still affects you on the most recent version of Scrapy! Thanks!

**Comment by kmike** [comment]
It may be a duplicate of https://github.com/scrapy/scrapy/issues/1330, I'm not sure.
