### ISSUE TITLE
Fails to install on Fedora 24 server

### ISSUE THREAD

**Issue by Shakyamuni177te** [scrapy/scrapy#2204]
Installation fails with the following error:

```
gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-NYwARV/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-f00YyN-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-NYwARV/cryptography/
```

**Comment by redapple** [comment]
Hi @Shakyamuni177te ,
so `cryptography` fails to install.
please check python [cryptography installation page](https://cryptography.io/en/latest/installation/#building-cryptography-on-linux):

> For Fedora and RHEL-derivatives, the following command will ensure that the required dependencies are installed:
> `$ sudo yum install gcc libffi-devel python-devel openssl-devel`

**Comment by Shakyamuni177te** [comment]
Hhhhhhmmmm, that doesn't work, but it looks like the it's an issue with the cryptography dependency as `pip install cryptography` fails too. The cryptography installation page doesn't list Fedora as a test platform so it looks like this is something I'm likely to have to get my hands dirty tracing myself if I want to get it fixed. Thanks for the help anyway! :)

**Comment by kdef** [comment]
I resolved this by installing redhat-rpm-config
