### ISSUE TITLE
Bad HTML parser

### ISSUE THREAD

**Issue by luc-phan** [scrapy/scrapy#2205]
Scrapy parser is different from common browsers parser. For example :

```
<li>
    one
    <div>
</li>
<li>
    two
</li>
```

Scrapy will see this :
```
<li>
    one
    <div>
        <li>
            two
        </li>
    </div>
</li>
```

While common browsers would see this :

```
<li>
    one
    <div>
    </div>
</li>
<li>
    two
</li>
```

This issue can be avoided with BeautifulSoup, because BeautifulSoup can use different parsers : **html.parser**, **lxml**, **html5lib**... Is it possible to do the same with Scrapy ?

**Comment by kmike** [comment]
Scrapy doesn't have its own HTML parser; it relies on lxml (via parsel library). But you can use BeautifulSoup with Scrapy, see http://doc.scrapy.org/en/latest/faq.html#can-i-use-scrapy-with-beautifulsoup. 

Providing a way to use another parser in parsel can be a good addition though; this issue belongs to https://github.com/scrapy/parsel.

**Comment by redapple** [comment]
See https://github.com/scrapy/parsel/issues/57

**Comment by kmike** [comment]
I'm closing it in favor of https://github.com/scrapy/parsel/issues/57.
