### ISSUE TITLE
try to extract item by iterate SelectorList, but get all items from response object issue?

### ISSUE THREAD

**Issue by hexcola** [scrapy/scrapy#2206]
## Environment
* OS X EI Capitan 10.11.6
* Scrapy 1.1.2
* Python 2.7.10

## Issue
When I iterate `SelectorList`  try to extract item from each `Selector`, it will return all items from `SelectorList` / `response`,  is it a bug?

## Example Code
``` html
<ul>
    <li>1</li>
    <li>2</li>
    <li>3</li>
    <li>4</li>
    <li>5</li>                                
</ul>
```

core python code:

``` python
for li in response.xpath('//ul/li'):
    print li.xpath('//li/text()').extract()   
```

the result will be:

``` bash
[u'1', u'2', u'3', u'4', u'5']                                                                                                         
[u'1', u'2', u'3', u'4', u'5']                                                                                                         
[u'1', u'2', u'3', u'4', u'5']                                                                                                         
[u'1', u'2', u'3', u'4', u'5']                                                                                                         
[u'1', u'2', u'3', u'4', u'5'] 
```

which I think it should be:
```bash
[u'1']                                                                                                                                 
[u'2']                                                                                                                                 
[u'3']                                                                                                                                 
[u'4']                                                                                                                                 
[u'5'] 
```

Now I am using the code as follows: 
```python
for li in response.xpath('//ul/li'):                                                                                               
     print Selector(text=li.extract()).xpath('//li/text()').extract()  
```

Sorry for my English.

**Comment by kmike** [comment]
I think it is not a Scrapy bug; it works as intended. See http://doc.scrapy.org/en/latest/topics/selectors.html#working-with-relative-xpaths.

**Comment by ohenrik** [comment]
I can’t get this to work. Following the example provided:

```
>>> for entry in response.xpath('.//tr'):  # extracts all <tr> inside
        news_item["date"] = entry.xpath("//td[1]//text()").extract()
```

This does not return the full tr elements, so i cannot then xpath the td elements. I also tried the option given by @hexcola but it ahd the same problem.

**Comment by YohanObadia** [comment]
The correct syntax should be:
    
    for li in response.xpath('//ul/li'):                                                                                               
         print Selector(text=li.extract()).xpath('./li/text()').extract()  

Note the `.li` instead of the `//li`.

**Comment by fawkes18** [comment]
Let's say I have two html sections that are identical and I only want to loop over the first Selector. How would I manage to do that?

**Comment by kmike** [comment]
@fawkes18 I'm not sure I understand your question 100%, but it sounds like an usage question. If so, the way to go is to ask it at stackoverflow (see https://docs.scrapy.org/en/latest/#getting-help).
