### ISSUE TITLE
Run from another script - Flask

### ISSUE THREAD

**Issue by Rimander** [scrapy/scrapy#2209]
Hi.
I was make a website with Flask.
The website has multiple options (start, stop..) for each spider.

How I can run each spider inside Flask?
So spider has access to the app

**Comment by redapple** [comment]
@Rimander , this is not [a scrapy issue in the proper sense](http://doc.scrapy.org/en/latest/contributing.html#reporting-bugs), more of a "how-to" question.
Can I ask you to use [scrapy-users mailing list](https://groups.google.com/d/forum/scrapy-users) or [StackOverflow](https://stackoverflow.com/questions/tagged/scrapy) instead?
A recent (and good) answer on StackOverflow: http://stackoverflow.com/a/37270442
