### ISSUE TITLE
document that process_item can return deferred

### ISSUE THREAD

**Issue by pawelmhm** [scrapy/scrapy#2230]
pipeline [`process_item`](http://doc.scrapy.org/en/1.1/topics/item-pipeline.html#process_item) method can return [`Twisted.Deferred`](https://twistedmatrix.com/documents/current/core/howto/defer.html). It works fine in user code and we also do this in some default pipelines, e.g. [media pipeline](https://github.com/scrapy/scrapy/blob/master/scrapy/pipelines/media.py#L57). 

We should document that this is possible and perhaps add some examples to show users how to do it.

**Comment by kmike** [comment]
+1. If I'm not mistaken, [CONCURRENT_ITEMS](http://doc.scrapy.org/en/latest/topics/settings.html#concurrent-items) option does nothing unless a pipeline uses deferreds.
