### ISSUE TITLE
Revise documentation about odd-numbered versions

### ISSUE THREAD

**Issue by redapple** [scrapy/scrapy#2232]
[Versioning and API Stability](http://doc.scrapy.org/en/latest/versioning.html) states:

> Scrapy uses the odd-numbered versions for development releases.
> (...) Even Bs will be stable branches, and odd Bs will be development.

I believe this is not true anymore starting with 1.1, 1.1 being the current recommended stable version.

**Comment by kmike** [comment]
I think it is a duplicate of https://github.com/scrapy/scrapy/issues/1317.

**Comment by redapple** [comment]
oh @kmike , I missed that one.
