### ISSUE TITLE
Rewrite tutorial to use *.toscrape.com websites

### ISSUE THREAD

**Issue by redapple** [scrapy/scrapy#2233]
[dmoz.org](https://www.dmoz.org/) changed layout a few months ago, breaking [scrapy's tutorial](http://doc.scrapy.org/en/1.1/intro/tutorial.html) badly.
We have lots of open issues or PRs from the community to fix it: #2023, #2032, #2090, #2130, #2180, not to mention the broken dirbot https://github.com/scrapy/dirbot/issues/19). Thanks to all of you for this.

The thing is dmoz.org may change layout again in the future and we need a more stable scraping-friendly website to serve scrapy tutorial's educational purpose.

Scrapinghub maintains a couple of fake-but-realistic websites that can be used for web scraping training, and scrapy know-how in particular: http://books.toscrape.com/ and http://quotes.toscrape.com/ (see http://sites.toscrape.com/)

/cc @eliasdorneles and @stummjr already working on this

**Comment by eliasdorneles** [comment]
Thanks for writing the issue! :+1:

**Comment by djunzu** [comment]
Side question: is the websites`s source code public?

**Comment by stummjr** [comment]
@djunzu we are going to use http://quotes.toscrape.com for the tutorial and its source code is available at: https://github.com/scrapinghub/spidyquotes

**Comment by kmike** [comment]
Hey, what about moving sites.toscrape.com to toscrape.com? Currently toscrape.com just drops the connection.

**Comment by eliasdorneles** [comment]
+1

**Comment by eliasdorneles** [comment]
http://toscrape.com is now an alias to http://sites.toscrape.com =)
