### ISSUE TITLE
make offsite middleware downloader middleware instead of spider middleware

### ISSUE THREAD

**Issue by pawelmhm** [scrapy/scrapy#2241]
Currently [offsite middleware](http://doc.scrapy.org/en/1.1/topics/spider-middleware.html?highlight=offsite#module-scrapy.spidermiddlewares.offsite) is spider middleware. It works only on spider output, only processes requests generated in spider callback. But requests in Scrapy can be scheduled outside spider callback. This can happen in following cases:
- requests scheduled on `start_requests`
- requests scheduled with `crawler.engine.crawl()`, `crawler.engine.download()`, `crawler.engine.schedule`

Second case (downloading with crawler.engine.crawl()) is very common in my experience. Many spiders get lists of urls from some external source and schedule requests on `spider_idle` signal. Offsite middleware wont work properly for them, allowed_domains attribute will not have effect.

I think we should make offsite middleware downloader middleware and make it work for all requests or at least discuss and clarify why we want to keep it as spider middleware and document that it does not work on all possible requests.

**Comment by Granitas** [comment]
I agree. Offsite middleware doesn't seem to benefit from being spider middleware at all. It doesn't need access to `response`, it only needs to check generated requests url attribute.

My only concern is that making this a downloader middleware will polute the scheduler with obviously unwanted requests. This could probably affect lazy broad crawl spiders that just yield every url on page and the the offsite middleware deal with it.  
Does anyone/thing care about scheduler? AFAIK all of the limits and other settings are actually resolved on the downloader, right? (except for depth limit which is a spider middleware)

Alternative solutions: 
- Have both spider and downloader offsite middlewares, though it would really ugly redundancy. 
- Make offsite middleware callable for cases when people use `crawler.engine.crawl()`, because right now it's a bit tedious.

Personally I don't like any of the alternative solutions and if my raised issue regarding scheduler is not significant, I would gladly have offsite spider middleware as a downloader middleware instead.

**Comment by redapple** [comment]
@pawelmhm , I also think it makes sense to have `OffsiteMiddleware` (or it's functionality) as a downloader middleware, if only to handle offsite-redirects (#15, #184)
[@pablohoffman 's comment there](https://github.com/scrapy/scrapy/issues/15#issuecomment-2048222) recommends to not change `OffsiteMiddleware` (_"avoid modifying the behavior of a well established and known middleware such as the offsite one"_), but that was 5 years ago, it may be time to revisite the position.
I believe the main reason for offsite middleware being a spider middleware is that it is conceptually spider dependent (through its  `.allowed_domains`) and not really standalone or spider-agnostic.
But of course, downloader middlewares do have access to the spiders in their methods.
Other attempts at fixing #15 have patched `RedirectMiddleware` (a downloader middleware) to merge with the offsite feature  (#1002, #1028).
Such a change on `OffsiteMiddleware` would be backwards incompatible if we provide it as downloader mdw, as those who patched it may have 2 competing mdw or a broken one  (e.g. #1640).

**Comment by pawelmhm** [comment]
> Such a change on OffsiteMiddleware would be backwards incompatible if we provide it as downloader mdw, as those who patched it may have 2 competing mdw or a broken one (e.g. #1640) -- to be checked.

Yeah I do agree this is backward incompatible. Aside from things noted by @redapple it is also worth considering that users code may depend on current behavior of offsite middleware, e.g. user schedules urls to offsite urls  without having netloc in allowed_domains. This works now and maybe this is ok for some use cases (e.g. spider makes requests to example.com and also example_api.com, developer forgot to add example_api.com to allowed_domains, but since he scheduled on spider_idle it never mattered, after update suddenly only example.com urls will work and example_api.com will be filtered). 

Also worth seeing how this might affect scheduling requests from pipelines. It is possible to schedule request from pipeline, now they dont go via offsite middleware. Will they go via middleware after this change? If someone makes some requests to some common api from pipeline (e.g. translates strings via some HTTP API from pipelines) spider allowed_domains may not work properly, maybe then pipeline would have to update allowed domains? Or user would define some project wide allowed domains?

**Comment by djunzu** [comment]
I must add that the problem in #15 is not just with `allowed_domains` but also with `deny` and `allow` rules in `Crawl Spider`.

---

Would it make sense something like that below ?
- add a policy in `RedirectMiddleware` to just ignore redirects to different domains;
- spider receives these ignored redirects and drop it or reschedule it accordingly; 
- enable this policy when needed/wanted.

**Comment by djunzu** [comment]
@pawelmhm 

> e.g. spider makes requests to example.com and also example_api.com, developer forgot to add example_api.com to allowed_domains, but since he scheduled on spider_idle it never mattered, after update suddenly only example.com urls will work and example_api.com will be filtered.

I must say that this particular example sounds to me like "relying on a 'bug' to work".

**Comment by petervandenabeele** [comment]
Newcomer here :-)

Following up on my initial (naive) comments in https://github.com/scrapy/scrapy/issues/3217

Sorry if I may be vague and not adding specific code and PR (yet), but having read some more comments and hitting the problem as a "very" unexpected side effect of hitting URL's outside of my strict "allowed_domains", it seems to me that a possible solution could be:

We do NOT change the behavior of the current
* `scrapy.spidermiddlewares.offsite.OffsiteMiddleware`:  
  FOR PERFORMANCE: it will stop processing outgoing links that are offsite as early as possible 
* `scrapy.downloadermiddlewares.redirect.RedirectMiddleware`:  
  FOR COMPLETENESS: it will follow redirects (but in 1% of cases, these may actually be offsite,
  which is the problem in user expectation that we are discussing here)
* the current list and order of default middlewares:  
  FOR BACKWARDS COMPATIBILITY

We DO add:

* a new `scrapy.downloadermiddlewares.offsite.OffsiteMiddleware`:  
  FOR CORRECTNESS: when activated, this will guarantee that we strictly _never_ hit a URL outside
  of our list of `allowed_domains`.
* a note in the _documentation_:  
  mentioning the historic "problem" and how to optionally add this middleware near the bottom of the downloader middlewares stack to avoid it.

Implementation:
* from the implementation there will probably be a lot of duplicated functionality between the existing
  `scrapy.spidermiddlewares.offsite.OffsiteMiddleware` and the new `scrapy.downloadermiddlewares.offsite.OffsiteMiddleware`. But that should be a solvable problem to do implement this in a DRY fashion (duplicate functionality, but using the same code).  
Naively ... could the `scrapy.downloadermiddlewares.offsite.OffsiteMiddleware` "simply" be a "shim" that calls `scrapy.spidermiddlewares.offsite.OffsiteMiddleware` with the correct arguments?

Longer term:
* If and when the behavior is stable, we _could_ add this middleware also to the default list of downloadermiddlewares and have a flag or setting "STRICT_OFFSITE_FILTERING", which, when turned on, would do this thing.
* The binary (non-backwards-compatible) decision in the long run is then to propose that "STRICT_OFFSITE_FILTERING" becomes "True" by default.

Design:

I do think we need the offsite filtering on 2 places: 
* "early" in the spider, to drop that unneeded work ASAP (for performance)
* "late" in the downloader, to be 100% sure that we never ever hit URI's outside of the allowed_domains (for correctness)

Technically, this could also be achieved with an additional check in the RedirectMiddleware, but then we would be changing existing functionality of that middleware ...

HTH ...

**Comment by petervandenabeele** [comment]
I was able to get a prototype of this to work in my project middlewares. The result is now that a Redirect to a domain that is outside of allowed_domains _is_ filtered by my added downloader middleware:

```
# redirect http => https to DOMAIN still works
2020-01-26 22:48:01 [scrapy.downloadermiddlewares.redirect] DEBUG: Redirecting (301) to <GET https://www.DOMAIN.be/> from <GET http://www.DOMAIN.be/>
2020-01-26 22:48:01 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.DOMAIN.be/> (referer: None)
2020-01-26 22:48:01 [strict_check_allowed_domains] INFO: Parsing StartUrl https://www.DOMAIN.be/ with status 200  
2020-01-26 22:48:01 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.DOMAIN.be/>
{}

# this is a regular offsite scraping, not impacted by a redirect
2020-01-26 22:48:01 [scrapy.spidermiddlewares.offsite] DEBUG: Filtered offsite request to 'www.vandenabeele.com': <GET https://www.vandenabeele.com/>

# this is the _redirect_ to an _offsite_ domain (that is the issue here)
2020-01-26 22:48:01 [scrapy.downloadermiddlewares.redirect] DEBUG: Redirecting (302) to <GET http://www.DOMAIN.COM/> from <GET https://www.DOMAIN.be/redirecting>

# this is the new middleware filtering this offsite _in the downloader_
2020-01-26 22:48:01 [peter.middlewares] DEBUG: Filtered offsite request in strict_filter_offsite to 'www.DOMAIN.COM': <GET http://www.DOMAIN.COM/>
```
I had added my middleware on position 80. Maybe a somewhat higher number, after the RobotsTxtMiddleware, was more appropriate. Then agai, I now think the position in the middleware stack doesn't really matter that much? In `settings.py`, I activated

```
# Enable or disable downloader middlewares
# See https://docs.scrapy.org/en/latest/topics/downloader-middleware.html
DOWNLOADER_MIDDLEWARES = {
    'peter.middlewares.PeterDownloaderMiddleware': 80,
}
```

This is the project specific middleware code that I added in the `middlewares.py` file in my project. What I find crucial is that the specific detailed parts are _copy exact_ of the relevant code in the OffsiteMiddleware. So, we can DRY this code out if we would integrate this in the main codebase as a "StrictOffsiteCheck" downloader middleware.

Maybe at a later stage (when I know the codebase better), I could add a proposal (with unit tests) to have this as an additional available middleware.

```
import re
import logging
from scrapy import signals
from scrapy.http import Request
from scrapy.exceptions import IgnoreRequest
from scrapy.utils.httpobj import urlparse_cached

logger = logging.getLogger(__name__)


class PeterDownloaderMiddleware(object):

    @classmethod
    def from_crawler(cls, crawler):
        # This method is used by Scrapy to create your spiders.
        s = cls()
        crawler.signals.connect(s.spider_opened, signal=signals.spider_opened)
        return s

    def process_response(self, request, response, spider):
        return response

    def process_exception(self, request, exception, spider):
        pass

    def process_request(self, request, spider):
        filtered_requests = [x for x in self.strict_filter_offsite(request, spider)]
        if len(filtered_requests) == 0:
            logger.debug("Filtered offsite request by strict_filter_offsite to %(request)s",
                {'request': request}, extra={'spider': spider})
            raise IgnoreRequest("Forbidden by strict_filter_offsite")
        return None

    def strict_filter_offsite(self, request, spider):
        # here we have only 1 request and we fabricate a `result` array,
        # so we can do a naive "copy exact" of the core code from OffsiteMiddleware.
        result = [request]

        # Exact copy paste from https://github.com/scrapy/scrapy/blob/master/scrapy/spidermiddlewares/offsite.py#L31-L41
        for x in result:
            if isinstance(x, Request):
                if x.dont_filter or self.should_follow(x, spider):
                    yield x
                else:
                    domain = urlparse_cached(x).hostname
                    if domain and domain not in self.domains_seen:
                        self.domains_seen.add(domain)
                        logger.debug(
                            "Filtered offsite request in strict_filter_offsite to %(domain)r: %(request)s",
                            {'domain': domain, 'request': x}, extra={'spider': spider})
                        self.stats.inc_value('offsite/domains', spider=spider)
                    self.stats.inc_value('offsite/filtered', spider=spider)
            else:
                yield x

    # Exact copy paste from https://github.com/scrapy/scrapy/blob/master/scrapy/spidermiddlewares/offsite.py#L45-L64
    def should_follow(self, request, spider):
        regex = self.host_regex
        # hostname can be None for wrong urls (like javascript links)
        host = urlparse_cached(request).hostname or ''
        return bool(regex.search(host))

    def get_host_regex(self, spider):
        """Override this method to implement a different offsite policy"""
        allowed_domains = getattr(spider, 'allowed_domains', None)
        if not allowed_domains:
            return re.compile('')  # allow all by default
        url_pattern = re.compile("^https?://.*$")
        for domain in allowed_domains:
            if url_pattern.match(domain):
                message = ("allowed_domains accepts only domains, not URLs. "
                           "Ignoring URL entry %s in allowed_domains." % domain)
                warnings.warn(message, URLWarning)
        domains = [re.escape(d) for d in allowed_domains if d is not None]
        regex = r'^(.*\.)?(%s)$' % '|'.join(domains)
        return re.compile(regex)

    def spider_opened(self, spider):
        spider.logger.info('Spider opened: %s' % spider.name)
        self.host_regex = self.get_host_regex(spider)
        self.domains_seen = set()
```

**Comment by petervandenabeele** [comment]
I was now able to import the standard _spider_ middleware `OffsiteMiddleware` class into my own _downloader_ middleware, so I now have a much shorter and cleaner implementation.

As argued above, this does the offsite domain filtering in the download chain, so that also domains that are redirects (when returning from the spider) that are offsite, are _strictly_ filtered out, before going into the actual downloader.

Because of the import from `OffsiteMiddleware` there is nearly no code duplication now.

=> Is there a chance this could become an official downloader middleware if I submitted a Pull Request? (it would need some Unit tests of course,  next challenge ...).

```
"""
Strict Offsite Downloader Middleware

See discussion in https://github.com/scrapy/scrapy/issues/2241
"""

import re
import logging
from scrapy import signals
from scrapy.exceptions import IgnoreRequest

from scrapy.spidermiddlewares.offsite import OffsiteMiddleware

logger = logging.getLogger(__name__)


class StrictOffsiteMiddleware(object):

    @classmethod
    def from_crawler(cls, crawler):
        # This method is used by Scrapy to create your spiders.
        s = cls()
        crawler.signals.connect(s.spider_opened, signal=signals.spider_opened)
        return s

    def process_response(self, request, response, spider):
        return response

    def process_exception(self, request, exception, spider):
        pass

    def process_request(self, request, spider):
        filtered_requests = [x for x in self.strict_offsite(request, spider)]
        if len(filtered_requests) == 0:
            logger.debug("Filtered offsite request by strict_offsite to %(request)s",
                {'request': request}, extra={'spider': spider})
            raise IgnoreRequest("Forbidden by strict_offsite middleware")
        return None

    def strict_offsite(self, request, spider):
        # here we have only 1 request and we fabricate a "result" array,
        # so we can reuse OffsiteMiddleware here.
        # returns 1 request if not filtered and 0 requests if filtered
        result = [request]
        return self.offsiteMiddleware.process_spider_output("unused_response_arg", result, spider)

    def spider_opened(self, spider):
        spider.logger.info('Spider opened: %s' % spider.name)
        self.offsiteMiddleware = OffsiteMiddleware(spider.crawler.stats)
        self.offsiteMiddleware.spider_opened(spider)
```

**Comment by leeprevost** [comment]
Did this go anywhere?   I’m struggling with an issue where my spider crawls links from a link extractor that denies PDFs.  But some links are redirected to a PDF on a content management site or doc store like AWS where the downloaded tries to download.    Trying to intercept that behavior with a finer grain solution than ‘dont_redirect’.  See my attempts on #2303 and #6159

**Comment by GeorgeA92** [comment]
@leeprevost 
> Did this go anywhere? I’m struggling with an issue where my spider crawls links from a link extractor that denies PDFs. But some links are redirected to a PDF on a content management site or doc store like AWS where the downloader tries to download. Trying to intercept that behavior with a finer grain solution than ‘dont_redirect’. See my attempts on #2303 and #6159

Offsite middleware as mentioned in [docs ](https://docs.scrapy.org/en/latest/topics/spider-middleware.html#module-scrapy.spidermiddlewares.offsite)- aimed to filter out Requests for URLs outside the domains covered by the spider . It doesn't have any relation with Your this issue.

**Comment by Gallaecio** [comment]
https://github.com/scrapy/scrapy/pull/6358
