### ISSUE TITLE
Document how to customize path for written files with media pipelines

### ISSUE THREAD

**Issue by redapple** [scrapy/scrapy#2253]
Motivation: https://github.com/scrapy/scrapy/issues/923

**Comment by dolohow** [comment]
If I read code correctly the only way to customize path for ImagesPipeline is to override `file_path` method in custom Pipeline.  Am I right?
https://github.com/scrapy/scrapy/blob/master/scrapy/pipelines/images.py#L180

**Comment by redapple** [comment]
@dolohow , I believe it's not the only way to do that, but it's probably the most straightforward.

**Comment by djunzu** [comment]
@redapple I have the same thoughts as @dolohow , but I would love some enlightenment on how to do it in another way! If you know how to do it, please let me learn!
