### ISSUE TITLE
[Python3]When I export data to a JSON file, How can I change the codec to UTF-8?

### ISSUE THREAD

**Issue by LokiSharp** [scrapy/scrapy#2261]
When I use `scrapy crawl xxx -o xxx.json -t json` to export a JSON file, it just give me some Unicode like `u'H\ufffd\ufffdftsitz' `. It defaults to export with Unicode, And I can't change it.

I found this method [http://stackoverflow.com/questions/9181214/scrapy-text-encoding](scrape text encoding), But it does not work in Scrapy with Python3.

**Comment by kmike** [comment]
Hey @LokiSharp,

Scrapy 1.2 (not released yet) will have this feature: https://github.com/scrapy/scrapy/pull/2034; it'll be possible to turn `\ufffd`escaping off using [FEED_EXPORT_ENCODING](http://doc.scrapy.org/en/master/topics/feed-exports.html#std:setting-FEED_EXPORT_ENCODING) option.
