### ISSUE TITLE
Accept single values for "to" and "cc" arguments when sending mails

### ISSUE THREAD

**Issue by redapple** [scrapy/scrapy#2272]
Follow up to https://github.com/scrapy/scrapy/pull/2271#issuecomment-248341246

> What about checking for strings and raising an error?
> Passing a string is an easy mistake to make.
> Or maybe we can support passing a single string.

**Comment by kirankoduru** [comment]
Hey @redapple, I would like to work on this. Can you tell me if checking for `isinstance`  of `basestring` a good idea so I can cast the `to` argument into a `list` ?

**Comment by redapple** [comment]
hi @kirankoduru , thanks for stepping in!
keep in mind that `basestring` is not in Python 3.
You may want to look at something like [`arg_to_iter`](https://github.com/scrapy/scrapy/blob/b6375d3701b72ca1ce28c32fd90741b0864db05f/scrapy/utils/misc.py#L17) which does tests for single valued arguments in a Python2/Python3 compatible way.

**Comment by kirankoduru** [comment]
@redapple that's exactly what I was looking for! I will create a PR soon. Thanks :)

**Comment by lfmattossch** [comment]
Hey @kirankoduru are you still working on this?

**Comment by kirankoduru** [comment]
hey @lfmattossch I was working last weekend. Some reasons my tests weren't passing. I was under the impression that `tox` was the command to run them. Is there any other way to run them? Also if you want to work on it please go ahead and start.

**Comment by moisesguimaraes** [comment]
hi @kirankoduru, I'm with @lfmattossch. I'm already running the unit tests on a fix. Thanks for updating us.

**Comment by kirankoduru** [comment]
@moisesguimaraes @lfmattossch great guys. Has the fix been pushed yet? I wonder how it was merged without passing tests.

**Comment by moisesguimaraes** [comment]
not yet. I'm testing it locally.
