### ISSUE TITLE
can LinkExtractor extract scrapy.link with node info

### ISSUE THREAD

**Issue by zhengbomo** [scrapy/scrapy#2276]
the html is like below, i want to extract the link `/example/category/pg{page}/`, but the `scrapy.link` does not contains the node info(`currentPage` and `totalPage`), how can i extract the link with the node info 

```html
<div class="page-box">
     <div page-url="/example/category/pg{page}/"
             totalPage="35"
             currentPage="1"             
     </div>
</div>
```

**Comment by kmike** [comment]
@zhengbomo no, it can't. It is unlikely we'll support this feature; link extractors need an overhaul. You can use regular Scrapy selectors to do that, something like 

```py
links = []
for div in response.css('.page-box div'):
    links.append(dict(
        url = div.xpath('@page-url').extract_first()
        current_page = div.xpath('@currentPage').extract_first()
    ))
```

We're planning to implement another helper for link extraction in [parsel](https://github.com/scrapy/parsel) library, but no timeline yet.

**Comment by zhengbomo** [comment]
i can get links from response in `parse` method, bug how can i send it to spider and crawl regularly

**Comment by kmike** [comment]
Hey @zhengbomo,

We're using scrapy issue tracker to track Scrapy issues. Scrapy usage questions are better fit to http://stackoverflow.com/ (use 'Scrapy' tag) - there are more people around.
