### ISSUE TITLE
Python3| FTP download handler

### ISSUE THREAD

**Issue by mateuszdargacz** [scrapy/scrapy#2277]
Is ftp download handler  on roadmap? what are the issues related with  porting it to Py3.x?

**Comment by kmike** [comment]
Hey @mateuszdargacz,

ftp download handler is not ported because relevant Twisted module (twisted.protocol.ftp) is not ported to Python 3 yet.

**Comment by mateuszdargacz** [comment]
@kmike  Right, I've seen a lack of `twisted.protocols.ftp`, is there any feedback from their end in this case?  or any hack for that created by community?

**Comment by kmike** [comment]
@mateuszdargacz I don't know, it seems there is no even a ticket in twisted bug tracker for that. I suggest to open an issue at https://twistedmatrix.com/trac/.

**Comment by mateuszdargacz** [comment]
@kmike no trace of that on their roadmap as well. I'll investigate that and try to get to the source of the issue. Thanks for your time.

**Comment by kmike** [comment]
thanks for heads up @mateuszdargacz!

**Comment by kmike** [comment]
twisted.protocols.ftp doesn't look particulary hard to port, likely it is just a lack of time/resources/motivation on their end

**Comment by redapple** [comment]
@mateuszdargacz , @kmike , or anyone interested in helping out,
I started porting Twisted's FTP module to Python 3.
https://github.com/twisted/twisted/compare/trunk...redapple:ftp-py3?expand=1

Kind of a slow effort because there are a lot of tests and some a tricky (for me at least) to unfail.

**Comment by redapple** [comment]
FYI, here's a proposal fix for supporting FTP with Python 3 (assuming Twisted 17.1+ is used, which has FTP+Python3 support): https://github.com/scrapy/scrapy/pull/2599

**Comment by kmike** [comment]
Fixed by #2599.
