### ISSUE TITLE
URLs vs Requests in at Architecture overview page 

### ISSUE THREAD

**Issue by kmike** [scrapy/scrapy#2278]
I think the [architecture overview](http://doc.scrapy.org/en/master/topics/architecture.html) in Scrapy master docs doesn't explain correctly the difference between URLs and Requests. It says that spider returns URLs, and Engine converts them to Requests, but this is confusing - spider returns Requests. There are also "URLs" on the chart, but Scrapy passes Request instances almost everywhere, not URLs. 

Old explanation (before https://github.com/scrapy/scrapy/pull/2165) didn't have this issue; as it is a regression I added '1.2' milestone.

**Comment by uberux** [comment]
Here's the dataflow diagram corrected (REQUESTS instead of URLS)

<img width="700" alt="scrapy_dataflow_diagram" src="https://cloud.githubusercontent.com/assets/2480693/18926553/a1433e86-858e-11e6-8c3e-c145cd255a7c.png">

**Comment by eliasdorneles** [comment]
Thank you @uberux !
