### ISSUE TITLE
Priority value, Higher or Lower?

### ISSUE THREAD

**Issue by pykler** [scrapy/scrapy#2289]
There is a contradiction in the documentation.

http://doc.scrapy.org/en/latest/topics/settings.html?highlight=priority#depth-priority

vs

http://doc.scrapy.org/en/latest/topics/request-response.html?highlight=priority#scrapy.http.Request

The first says a positive number will mean lower priority. The latter says a higher number means a higher priority. So what is it?

**Comment by eLRuLL** [comment]
not sure if this needs to be fixed or maybe add a better explanation, as they are different things.

`DEPTH_PRIORITY` is a settings parameter to be used with `CrawlSpider`'s rules (this isn't specified on the documentation). The number specified here won't be going directly into the `Request`'s `priority` attribute. The Documentation explains how to use this parameter.

`priority` is a `Request` attribute to set specific priority in the request's stack.

**Comment by redapple** [comment]
@eLRuLL , `DEPTH_PRIORITY` is a setting read by  `DepthMiddleware`, not specifically for `CrawlSpider`.
In `DepthMiddleware`, `DEPTH_PRIORITY` affects Requests priority [but with a _minus_ sign](https://github.com/scrapy/scrapy/blob/ebef6d7c6dd8922210db8a4a44f48fe27ee0cd16/scrapy/spidermiddlewares/depth.py#L36), so the documentation is correct. But I admit it can be confusing.
