### ISSUE TITLE
Scrapy should follow redirects on scrapy shell by default

### ISSUE THREAD

**Issue by eliasdorneles** [scrapy/scrapy#2290]
Scrapy shell doesn't follow redirects when you do `fetch('http://google.com')`, but it does if you do ` `fetch(scrapy.Request('http://google.com'))`.

I realize this is a historic behavior, but I'd argue that it breaks the expectations for most users, since the most common expectation is that Scrapy would try to do what a browser would do, so I think we should change it.

In my opinion, not following the redirect should be the exceptional behavior, and so that's what should require the user to build a `scrapy.Request` object.

I think ideally, we would be able to pass a keyword argument to `fetch`, like:

```
fetch('http://google.com', redirect=False)
```

And only for that case it would set handle_httpstatus_all to True as explained by @redapple here: https://github.com/scrapy/scrapy/issues/2177#issuecomment-239430163

**Comment by elacuesta** [comment]
Hey guys, I would like to submit a patch for this issue, but first I have a few questions. Let's say we add a `redirect` parameter to `fetch`:
* is `redirect` the best name for a parameter which sets `handle_httpstatus_all=True` on the request? I think `redirect` would be more suitable if we _only_ wanted the request not to handle 3xx status codes. How about a name closer to `handle_httpstatus_all`?
* what if we pass a request with `meta['handle_httpstatus_all']=True` and `redirect=True`? (other colliding values are possible too) Which one should take precedence?

Looking forward to reading your comments, thanks for your time!

**Comment by redapple** [comment]
Hey @elacuesta !
Do you have that patch ready? because I worked on this this morning actually. And was about to submit a WIP PR
I opted for an "handle statuses" argument and not a "redirect on or off" one.

**Comment by redapple** [comment]
@elacuesta , this is the patch I was referring to https://github.com/scrapy/scrapy/pull/2410

**Comment by elacuesta** [comment]
Hello Paul, thanks for your reply. I was just asking to better understand the situation before starting, so let's not duplicate efforts and focus on that PR.

**Comment by redapple** [comment]
@elacuesta , I updated my PR for this one at #2410. If you want to have a look and discuss
