### ISSUE TITLE
CrawlSpider with Rules not working

### ISSUE THREAD

**Issue by sixfingers76** [scrapy/scrapy#2291]
Hi,

I am using Scrapy version 1.1.2. It is somenthing weird, because depending on the Rules configuration, the callback function is called or not...

My rules:

```
rules = (
        Rule(LinkExtractor(allow=('.*balsamo'))), # get category page
        Rule(LinkExtractor(allow=(".*\/\d+.*"),restrict_xpaths=('//*[@id="center_column"]/div[3]')), callback='category'), # get product pages links in the category page
)
```

If I remove the restrict_xpaths filter, the callback function is called, but when I use restrict_xpaths, the callback function is never called, even when the ouput shows the right crawled pages as "crawled". This is the output resulting from the above rules.

```
2016-09-28 19:00:57 [scrapy] DEBUG: Crawled (200) GET http://www.example.es/robots.txt (referer: None)
2016-09-28 19:00:57 [scrapy] DEBUG: Crawled (200) GET http://www.example.es (referer: None)
2016-09-28 19:00:58 [scrapy] DEBUG: Crawled (200) GET http://www.example.es/75-balsamo (referer: http://www.example.es)
2016-09-28 19:00:58 [scrapy] DEBUG: Filtered duplicate request: GET http://www.example.es/75-balsamo - no more duplicates will be shown (see DUPEFILTER_DEBUG to show all duplicates)
2016-09-28 19:01:01 [scrapy] DEBUG: Crawled (200) GET http://www.example.es/varios/233-relajante-balsamo-aromatico-dream-6-g-ha-tha.html (referer: http://www.example.es/75-balsamo)
2016-09-28 19:01:01 [scrapy] DEBUG: Crawled (200) GET http://www.example.es/balsamo/459-balsamo-de-tigre-rojo-21-ml-varios.html (referer: http://www.example.es/75-balsamo)
2016-09-28 19:01:01 [scrapy] DEBUG: Crawled (200) GET http://www.example.es/varios/235-refrescante-bio-balsamo-hierbas-classic-6-g-ha-tha.html (referer: http://www.example.es/75-balsamo)
2016-09-28 19:01:01 [scrapy] DEBUG: Crawled (200) GET http://www.example.es/varios/234-tranquilizador-balsamo-aromatico-balance-ha-tha.html (referer: http://www.example.es/75-balsamo)
2016-09-28 19:01:01 [scrapy] DEBUG: Crawled (200) GET http://www.example.es/balsamo/460-balsamo-de-tigre-blanco-21-ml-varios.html (referer: http://www.example.es/75-balsamo)
2016-09-28 19:01:01 [scrapy] INFO: Closing spider (finished)
```

**Comment by redapple** [comment]
@sixfingers76 , I'm having a hard time matching the log with your rules,
but maybe you can look at the order of the rules.

For each link in a page, [only the first rule](https://doc.scrapy.org/en/latest/topics/spiders.html#scrapy.spiders.CrawlSpider.rules) with a link extractor having extracted this link will be used:

> If multiple rules match the same link, the first one will be used, according to the order they’re defined in this attribute.

So if `LinkExtractor(allow=('.*balsamo'))` matches some links that you expect should go through `callback='category'`, you should invert the rules' order.

**Comment by djunzu** [comment]
All the links in your log match the first rule. So the callback is never called. It is right.
The links crawled when you remove `restrict_xpaths` filter... do they match the first rule? Probably not! If so, there s a bug in Scrapy.

**Comment by sixfingers76** [comment]
Thank you for the responses. At the end I resigned and write the code without using Rule since I cannot get the expected result. I just want to get one link in a page that contains "balsamo", follow that link and get all the links in the "balsamo" page that are inside the "center_column" div, that is all.

It took me more code to develop but it is working now. Maybe scrapy is working well and the problem is that I do not understand how the Rules work.

Thank you again.

Kind regars,

Javier.

**Comment by redapple** [comment]
@sixfingers76 , I think I found the website you are crawling.
And I'm not sure that the `restrict_xpath` you set is correct.
For the "balsamo" page, 
`LinkExtractor(allow=(".*\/\d+.*"), restrict_xpaths=('//*[@id="center_column"]/div[3]')).extract_links(response)` does not pick up any new link
while
`LinkExtractor(allow=(".*\/\d+.*"), restrict_xpaths=('//*[@id="center_column"]')).extract_links(response)` does.
Also, sometimes `CrawlSpider` is not the helper you need, and using "plain" Spider with LinkExtractors is what you need.

**Comment by djunzu** [comment]
Off topic: sometimes changing the domain is not enough to hide it.

**Comment by redapple** [comment]
@sixfingers76 , I'm closing this issue as I believe it has to do with the XPath in `restrict_xpaths`, not how CrawlSpider rules are processed.
Please reopen if you do believe there's a bug in CrawlSpider implementation.

**Comment by Crispae** [comment]
I am facing almost same issue, let me give you guys idea about the pattern through which I scrape----.>>>
I have only 1 URL in start_url  through which I wanted to scrape 5 URLs(Which I am getting) for different categories after entering into any  categories I have to extract data from that page ,within the same page there is pagination link and i want do do it recursively, it seems linkextractor not extracting complete link as i can't  see response for second rule.



Here is the code as, I am not able to do the pagination using rules so I manually  added some  code to recursively scrape the page.

allowed domains = []
    start_urls = ['https://tutsplus.com/']

    rules = (
        Rule(LinkExtractor(restrict_xpaths='//div[@class="home-hero__column"]/a'), callback='parse_tem'),
        # Rule(LinkExtractor(restrict_xpaths="//a[@class='pagination__button pagination__next-button']"),callback='parse_tem',),
    )

    # def parse_tem(self, response):
    #     yield scrapy.Request(url=response.url,callback=self.extractor,dont_filter=True)

    def parse_tem(self,response):
        for path in response.xpath('//li[@class="posts__post  "]/article'):
            item ={}
            item['course__name'] = path.xpath('.//header/a[2]/h1/text()').extract_first()
            item['course_link'] = path.xpath('.//header/a/@href').extract_first()
            item['description'] = path.xpath('.//div/text()').extract_first()
            yield item

        next_page = response.xpath('//a[@class="pagination__button pagination__next-button"]/@href').extract_first()
        next_url = response.urljoin(next_page)
        yield scrapy.Request(next_url,callback=self.parse_tem,dont_filter=True)
