### ISSUE TITLE
AttributeError when using cookiejar in request.meta attribute

### ISSUE THREAD

**Issue by songshixuan** [scrapy/scrapy#2301]
File "/usr/lib/python3.4/http/cookiejar.py", line 1103, in return_ok_secure
    if cookie.secure and request.type != "https":
AttributeError: 'WrappedRequest' object has no attribute 'type'

Then I annotated the line, the error disappear. The function cause the exception is:

def return_ok_secure(self, cookie, request):
        #if cookie.secure and request.type != "https":
        #    _debug("   secure cookie with non-secure request")
        #    return False
        return True

**Comment by redapple** [comment]
It looks the same as https://github.com/scrapy/scrapy/issues/1770. Which was fixed in 1.1.0rc2
