### ISSUE TITLE
Does scrapy on Windows/Python3.5+ support the FTP download handler yet?

### ISSUE THREAD

**Issue by zeluspudding** [scrapy/scrapy#2312]
According to this ~1yr old update, scrapy still [didn't support the FTP download handler](https://doc.scrapy.org/en/latest/news.html?highlight=ftp#beta-python-3-support) on windows. Does it support it now?

**Comment by redapple** [comment]
Hi @zeluspudding ,
Short answer is no, scrapy does not currently (as in 1.2.0) support the FTP download handler in Python 3.
Nor does it support Python 3 in general on Windows.

In the end, those 2 things need support in Twisted.
There was a recent issue about FTP on Python 3 https://github.com/scrapy/scrapy/issues/2277
We do not know if Twisted will support FTP on Python 3 in the short term.

Python 3 support on Windows for Twisted should not be too far away though, as [Twisted 16.4 release notes say they are on their way to it](http://labs.twistedmatrix.com/2016/08/twisted-1640-released.html).

**Comment by zeluspudding** [comment]
Thank you! That is very helpful

**Comment by zeluspudding** [comment]
I've linked your answer to [this stackoverflow post](http://stackoverflow.com/questions/27770610/using-scrapy-to-crawl-a-public-ftp-server)
