### ISSUE TITLE
Export to 2 locations

### ISSUE THREAD

**Issue by rolele** [scrapy/scrapy#2316]
I am using scrapyd and a FEED_URI to save in a ftp endpoint.
Everything works fine but I would like the items to be also saved locally using the default scrapyd file location: eg. `items='file:///var/lib/scrapyd/items/properties/distr/ca3636168d4711e69d740242ac110007.jl'`

Right now, all the links to the items on the scrapyd webUI return a 404.

**Comment by redapple** [comment]
Hello @rolele , sorry for the late feedback.
This is an interesting use-case.
The [built-in `FeedExporter`](https://github.com/scrapy/scrapy/blob/d8672689761f0bb6c0550a841f35534265e87fee/scrapy/extensions/feedexport.py#L157) (controlled with these `FEED_***` settings) is "merely" an extension [listening to the `item_scraped` signal](https://github.com/scrapy/scrapy/blob/master/scrapy/extensions/feedexport.py#L183). It is indeed mono-location.
Skimming through the code, I don't think it would be too difficult to build a multi-location feed exporter, but it's certainly not documented or available out-of-the-box.

If anyone wants to work on that, they are more than welcome to open a Pull Request.

An alternative is to [use item pipelines (perhaps using the built-in item exporters)](https://docs.scrapy.org/en/latest/topics/exporters.html#using-item-exporters), which you can have multiple instance of in `ITEM_PIPELINES`, but again it's not really detailed for your multi-output-location use-case.

**Comment by rolele** [comment]
thanks @redapple , I am more and more familiar with scrapy and thanks to your help, I see exactly how I can do this.
Thanks
