### ISSUE TITLE
Cannot save the item into cvs or json

### ISSUE THREAD

**Issue by Botasky369** [scrapy/scrapy#2317]
@redapple   Hi, I need some help!!
I got a problem with scrapy version 1.2.0
Here is my code , it is very simple:
```
# -*- coding:utf-8 -*-
import scrapy
from scrapy.spiders import CrawlSpider
from scrapy.selector import Selector
from scrapy.http import Request
from StudyDemo.items import StudydemoItem
import urllib
from selenium import webdriver
from bs4 import BeautifulSoup
class StudyDemoSpider(CrawlSpider):
    name = 'StudyDemo'
    start_urls = ['http://www.qiushibaike.com/hot/page/1']

    def parse(self, response):
        soup = BeautifulSoup(response.text)
        articles = soup.select(".article")
        for article in articles:
            item = StudydemoItem()
            author = article.select(".author a h2")[0].get_text()
            content = article.select(".content span")[0].get_text()
            like = article.select(".stats-vote i")[0].get_text()
            comment = article.select(".stats-comments i")[0].get_text()
            item['author'] = author
            item['content'] = content
            item['likeNum'] = like
            item['commentNum'] = comment
            yield item
```
In the setting.py:
```
FEED_URI=u'Scrapy/qiubai.csv'
FEED_FORMAT='CSV'
```

And I run `scrapy crawl StudyDemo`
It was success, and create a csv file in Scrapy dir, but the file is ZeroByte.

And I tryed run `scrapy crawl StudyDemo -o qiubai.json` it was the same as csv, it create a qiubai.json file ,but the file is ZeroByte too .

And I can get All The Result success in Terminal.
![image](https://cloud.githubusercontent.com/assets/13627665/19225902/a21506f4-8ed6-11e6-9034-fcfc21387029.png)

I don't kown  what's the matter with my Code.  
Need some help!

**Comment by redapple** [comment]
Hi @Botasky369 ,
can I ask you to [post your question one StackOverflow](https://stackoverflow.com/questions/ask) with tag "scrapy"? You will have to post scrapy version (output of `scrapy version -v` and also the statistics that are printed at the end of the crawl in your console)

We do not used GitHub issues for helpdesk-type questions, but for reproducible bugs or architecture and feature discussions.
I hope you understand.
