### ISSUE TITLE
Document headers methods such as getlist()

### ISSUE THREAD

**Issue by redapple** [scrapy/scrapy#2320]
It appears that current documentation does not mention how you can get values from HTTP `Headers` object.
Things like `response.headers.getlist('Set-Cookie')` to get all cookies are not explained (see https://github.com/scrapy/scrapy/issues/2319)

**Comment by moisesguimaraes** [comment]
@eliasdorneles, could you please assign me to this issue?

**Comment by redapple** [comment]
@moisesguimaraes , there's already an open PR for this: https://github.com/scrapy/scrapy/pull/2327

**Comment by moisesguimaraes** [comment]
ok @redapple, thanks for the clarification =)
