### ISSUE TITLE
ssl error: tlsv1 alert internal error

### ISSUE THREAD

**Issue by cp2587** [scrapy/scrapy#2326]
Hello,

Thank you for all the work on this library. 
We recently started to scrape some website using https using proxies (crawlera & proxymesh) but with proxymesh we always get the following error:
```python
[('SSL routines', 'ssl3_read_bytes', 'tlsv1 alert internal error'), ('SSL routines', 'ssl3_write_bytes', 'ssl handshake failure')]
```
When using no proxy or crawlera, we are getting a correct response. 
Using curl with proxymesh also seems to work...
Do you have any idea on what's happening ? I can provide the url website in private if need be.

scrapy version: 1.0.5

**Comment by redapple** [comment]
hi @cp2587 ,
you may be facing the missing "Host" header in CONNECT requests
This was fixed in scrapy 1.1.1 (https://github.com/scrapy/scrapy/pull/2069)
Are you able to test with scrapy >= 1.1.1?

**Comment by cp2587** [comment]
Just tried it with 1.2.0 and it works like a charm ! 
THank you so much :)

**Comment by redapple** [comment]
Thanks for the heads up!
Closing.
