### ISSUE TITLE
Always blocked with no information

### ISSUE THREAD

**Issue by Sraw** [scrapy/scrapy#2340]
I use `scrapy startproject XXXX` to init a project and build my spider.
And then everything is fine but blocked at a random step:
```
 2016-10-20 15:49:54 [scrapy] DEBUG: Crawled (200) <GET http://xxx.xxx.com/thread-2109141-1-27.html> (referer: http://xxx.xxx.com/forum-1286-27.html) ['partial']
```
Then it's totally blocked and no information output. Especially, when I tried to use double `Ctrl+C` to cancel the program, it doesn't work.

**Comment by redapple** [comment]
Hi @Sraw , you'll have to give us more information on your setup in order to investigate this.
Without the website, nor the spider code, it's virtually impossible to diagnose.
What's your system (output of `scrapy version -v`)?
What do you mean by "totally blocked"?
Are you using any synchronous networking calls? (e.g. python-requests)

**Comment by Sraw** [comment]
@redapple thanks for reply.
```
import scrapy
import re
import random
import sys


class MySpider(scrapy.Spider):
    name = "test"

    
    custom_settings = {
        "DOWNLOAD_TIMEOUT" : 2,
        "DOWNLOAD_DELAY" : 0.25,
        "COOKIES_ENABLED": False
    }
    filecontent = ""
    k=0
    proxy_list = []
    pageLen = 800

    def __init__(self, *args, **kwargs):
        super(MySpider, self).__init__(*args, **kwargs)
        proxy_list = []
        print("initing...")
        with open("/home/XXX/free2016.txt",'r') as f:
            tmp = f.read()
            proxy_list = tmp.split('\n')
    
    def start_requests(self):
        urls = []
        for i in range(1,self.pageLen):
            urls.append('http://yys.16163.com/forum-1286-%s.html' %(i))
        for url in urls:
            request = scrapy.Request(url=url, callback=self.parse)
            if self.proxy_list:
                proxy_addr = self.proxy_list[random.randint(0,len(self.proxy_list) - 1)]
                reqeust.meta['proxy'] = proxy_addr
            yield request

    def parse(self, response):
        urls = []
        for i in response.css("tbody[id*=normalthread] th.new a.s.xst::attr(href)").extract():
            urls.append('http://yys.16163.com/%s' %(i))
        for url in urls:
            request = scrapy.Request(url=url, callback=self.page_parse)
            if self.proxy_list:
                proxy_addr = self.proxy_list[random.randint(0,len(self.proxy_list) - 1)]
                reqeust.meta['proxy'] = proxy_addr
            yield request
    
    def page_parse(self, response):
        text = response.css("td[id*=postmessage]").extract()[0]
        self.filecontent += text

    def closed(self, reason):
        print("saving...")
        with open('tmp.txt', 'w') as f:
            f.write(self.filecontent)
```
All my code shows above.
The system info is:
```
Scrapy    : 1.2.0
lxml      : 3.5.0.0
libxml2   : 2.9.3
Twisted   : 16.4.1
Python    : 3.5.2 (default, Sep 10 2016, 08:21:44) - [GCC 5.4.0 20160609]
pyOpenSSL : 16.1.0 (OpenSSL 1.0.2g  1 Mar 2016)
Platform  : Linux-4.4.0-43-generic-x86_64-with-Ubuntu-16.04-xenial
```
The "totally blocked" means the program stopped at this step and no matter how long I wait, nothing happened and I cannot use double `Ctrl+c` to force quit the program.
Actually, if I use a small pageLen such as 20, It works well.

**Comment by redapple** [comment]
I'm afraid GitHub issues is not the right place to help you debug this as it's not a reproducible bug report.
Maybe it has to do with the proxies you are using.
I suggest you ask your question on [scrapy-users mailing list](https://groups.google.com/forum/#!forum/scrapy-users).
In the meantime, maybe you can also log the proxies used for each URL, you could perhaps identify a proxy that stops sending bytes at some point (I admit I'm not sure what happens at scrapy level for this case, if there's a configurable timeout or not)

**Comment by Sraw** [comment]
@redapple YES, that's real what confuses me. If there are some problems with the network(surely including proxies), it will shows timeout and go on.
Still thanks for answer. I will keep looking for solution on the website you recommend.

**Comment by Sraw** [comment]
@redapple HI, finally, I have located the problem.
if a string extracted from html contains `<style[^>]+</style>` , it will be blocked. But if I use module "re" to remove the part, it works well.
I have no idea about it, but I hope it can provide some information for the development group.

**Comment by redapple** [comment]
@Sraw , glad you found the root cause.
I don't actually understand what issues you found, but please report (probably to [scrapy/parsel](https://github.com/scrapy/parsel)) if it's HTML scraping related
