### ISSUE TITLE
how to let the log only log ERROR level information

### ISSUE THREAD

**Issue by shyandsy** [scrapy/scrapy#2352]
I tried lots of way to use the ERROR level, but still all information was wrote into log file

python 3.5 + scrapy 1.2

``` python
dmoz_spider.py

configure_logging(install_root_handler=False)
logging.basicConfig(filename='log.txt', format='%(levelname)s: %(message)s', level=logging.ERROR)
```

``` python
settings.py

...................
LOG_LEVEL = "ERROR"
```

**Comment by bmetge** [comment]
Same here, any news on this ?

**Comment by Jack-Kingdom** [comment]
me too

**Comment by redapple** [comment]
@Jack-Kingdom , @bmetge , @shyandsy ,
I think `configure_logging(install_root_handler=False)` is what is messing with the configuration.
In https://github.com/scrapy/scrapy/issues/2149#issuecomment-302669498 I removed that line from the docs example, and I was able to have ERROR level with a standalone script using `CrawlerRunner`.

**Comment by thernstig** [comment]
@joelkim please see my answer in #2149. I believe this issue can be closed as a clone of that.
