### ISSUE TITLE
FeedExported error when using sub-items

### ISSUE THREAD

**Issue by birla** [scrapy/scrapy#2364]
I'm creating a Scrapy.Item with the following structure:

> Item1
> - property (string)
> - property (string)
> - property (Item2[])
>  - (Item2)
>  - (Item2)
> ....

Now the console's debug log displays the resulting JSON structure property, however in the export I get the following error:

	2016-10-27 15:17:55 [scrapy] ERROR: Error caught on signal handler: <bound method ?.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x7f0edde6ebd0>>
	Traceback (most recent call last):
	  File "/home/birla/work/coolstore/data/env/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 149, in maybeDeferred
	    result = f(*args, **kw)
	  File "/home/birla/work/coolstore/data/env/local/lib/python2.7/site-packages/pydispatch/robustapply.py", line 55, in robustApply
	    return receiver(*arguments, **named)
	  File "/home/birla/work/coolstore/data/env/local/lib/python2.7/site-packages/scrapy/extensions/feedexport.py", line 221, in item_scraped
	    slot.exporter.export_item(item)
	  File "/home/birla/work/coolstore/data/env/local/lib/python2.7/site-packages/scrapy/exporters.py", line 116, in export_item
	    itemdict = dict(self._get_serialized_fields(item))
	  File "/home/birla/work/coolstore/data/env/local/lib/python2.7/site-packages/scrapy/exporters.py", line 75, in _get_serialized_fields
	    value = self.serialize_field(field, field_name, item[field_name])
	  File "/home/birla/work/coolstore/data/env/local/lib/python2.7/site-packages/scrapy/exporters.py", line 47, in serialize_field
	    return serializer(value)
	  File "/home/birla/work/coolstore/data/env/local/lib/python2.7/site-packages/scrapy/item.py", line 52, in __init__
	    for k, v in six.iteritems(dict(*args, **kwargs)):
	ValueError: dictionary update sequence element #0 has length 12; 2 is required

Item2 has a 12 properties. As far as I understand it is being raised while converting `Item2[]` into a dict object. Also, if I run the crawl without exporting the code works fine.

**Comment by redapple** [comment]
@birla ,
can you share your actual item definition as python/scrapy code?

> the console's debug log displays the resulting JSON structure property,

can you share an example of a populated item that is output by spider callback(s)?

**Comment by birla** [comment]
@redapple Here you go

Item definition:
    import scrapy

    class RewardItem(scrapy.Item):
        name = scrapy.Field()
        amount = scrapy.Field()
        item_id = scrapy.Field()

        pass

    class Reward(scrapy.Item):
        backers_count = scrapy.Field()
        description = scrapy.Field()
        etd = scrapy.Field()
        minimum = scrapy.Field()
        shipping_enabled = scrapy.Field()
        shipping_preference = scrapy.Field()
        shipping_summary = scrapy.Field()
        title = scrapy.Field()
        title_tier = scrapy.Field()
        limit = scrapy.Field()
        remaining = scrapy.Field()
        rewards_count = scrapy.Field() #only first reward

        pass

    class Project(scrapy.Item):
        project_url = scrapy.Field()
        project_id = scrapy.Field()

        name = scrapy.Field()
        photo = scrapy.Field()
        blurb = scrapy.Field()
        category = scrapy.Field()
        sub_category = scrapy.Field()
        state = scrapy.Field()
        
        created_at = scrapy.Field()
        launched_at = scrapy.Field()
        successful_at = scrapy.Field()

        creator = scrapy.Field()
        creator_url = scrapy.Field()
        country = scrapy.Field()
        state = scrapy.Field()
        city = scrapy.Field()
        display_location = scrapy.Field()

        currency = scrapy.Field()
        currency_symbol = scrapy.Field()
        currency_symbol_trailing = scrapy.Field()
        goal = scrapy.Field()
        pledged = scrapy.Field()
        backers_count = scrapy.Field()
        usd_pledged = scrapy.Field()
        usd_rate = scrapy.Field()
        
        comments_count = scrapy.Field()
        updates_count = scrapy.Field()
        
        is_spotlight = scrapy.Field()
        is_staff_pick = scrapy.Field()

        reward_items = scrapy.Field(serializer=RewardItem)
        rewards = scrapy.Field(serializer=Reward)

        pass

Populated item from logs:

	{'backers_count': 193,
	 'blurb': u'SERMANBRANDS 1.S: Slim Profile. RFID Armed. The next best satisfying addition to your essentials.',
	 'category': u'Design',
	 'city': u'Roseville',
	 'comments_count': 12,
	 'country': u'US',
	 'created_at': 1474659316,
	 'creator': u'SERMAN BRANDS',
	 'creator_url': u'https://www.kickstarter.com/profile/1581298047',
	 'currency': u'USD',
	 'currency_symbol': u'$',
	 'currency_symbol_trailing': True,
	 'display_location': u'Roseville, CA',
	 'goal': 5000.0,
	 'is_spotlight': True,
	 'is_staff_pick': False,
	 'launched_at': 1474938502,
	 'name': u'SERMAN BRANDS 1.S RFID Blocking Travel Wallet',
	 'photo': u'https://ksr-ugc.imgix.net/assets/013/848/570/e0e06be3e9ce16b9b9602c3ea9567fbf_original.png?w=560&h=315&fit=fill&bg=000000&v=1476842044&auto=format&q=92&s=c5f8192ed16b574758f477996740ab62',
	 'pledged': 5875.0,
	 'project_id': 1987787731,
	 'project_url': u'https://www.kickstarter.com/projects/1581298047/serman-brands-1s-rfid-blocking-travel-wallet',
	 'reward_items': [{'amount': 0.0, 'item_id': 53408, 'name': u'California Desert'},
	                  {'amount': 0.0, 'item_id': 53409, 'name': u'Charcoal Black'},
	                  {'amount': 0.0, 'item_id': 53406, 'name': u'Texas Brown'}],
	 'rewards': [{'backers_count': 0,
	 'description': u'No Reward',
	 'etd': None,
	 'limit': None,
	 'minimum': 1,
	 'remaining': None,
	 'rewards_count': None,
	 'shipping_enabled': False,
	 'shipping_preference': None,
	 'shipping_summary': None,
	 'title': None,
	 'title_tier': None},
	             {'backers_count': 95,
	 'description': u'EARLY BIRD! SERMAN BRANDS 1.S - For the true minimalist. Carry your must-have cards, Photo Id, business cards, folded bills. low price, to help us reach our goal: 50% OFF the projected retail price.',
	 'etd': None,
	 'limit': 100,
	 'minimum': 20.0,
	 'remaining': 5,
	 'rewards_count': None,
	 'shipping_enabled': True,
	 'shipping_preference': u'unrestricted',
	 'shipping_summary': u'Ships anywhere in the world',
	 'title': u'Early Bird Special - Texas Brown',
	 'title_tier': None},
	             {'backers_count': 23,
	 'description': u'EARLY BIRD! SERMAN BRANDS 1.S - For the true minimalist. Carry your must-have cards, Photo Id, business cards, folded bills. low price, to help us reach our goal: 50% OFF the projected retail price.',
	 'etd': None,
	 'limit': 100,
	 'minimum': 20.0,
	 'remaining': 77,
	 'rewards_count': None,
	 'shipping_enabled': True,
	 'shipping_preference': u'unrestricted',
	 'shipping_summary': u'Ships anywhere in the world',
	 'title': u'Early Bird Special - California Desert',
	 'title_tier': None},
	             {'backers_count': 52,
	 'description': u'EARLY BIRD! SERMAN BRANDS 1.S - For the true minimalist. Carry your must-have cards, Photo Id, business cards, folded bills. low price, to help us reach our goal: 50% OFF the projected retail price.',
	 'etd': None,
	 'limit': 100,
	 'minimum': 20.0,
	 'remaining': 48,
	 'rewards_count': None,
	 'shipping_enabled': True,
	 'shipping_preference': u'unrestricted',
	 'shipping_summary': u'Ships anywhere in the world',
	 'title': u'Early Bird Special - Charcoal Black',
	 'title_tier': None},
	             {'backers_count': 2,
	 'description': u'EARLY BIRD! SERMAN BRANDS 1.S - For the true minimalist. Carry your must-have cards, Photo Id, business cards, folded bills. low price, to help us reach our goal',
	 'etd': None,
	 'limit': None,
	 'minimum': 30.0,
	 'remaining': None,
	 'rewards_count': None,
	 'shipping_enabled': True,
	 'shipping_preference': u'unrestricted',
	 'shipping_summary': u'Ships anywhere in the world',
	 'title': u'SERMAN BRANDS 1.S - Travel wallet',
	 'title_tier': None},
	             {'backers_count': 1,
	 'description': u'EARLY BIRD! SERMAN BRANDS 1.S - For the true minimalist. Carry your must-have cards, Photo Id, business cards, folded bills. low price, to help us reach our goal',
	 'etd': None,
	 'limit': None,
	 'minimum': 30.0,
	 'remaining': None,
	 'rewards_count': None,
	 'shipping_enabled': True,
	 'shipping_preference': u'unrestricted',
	 'shipping_summary': u'Ships anywhere in the world',
	 'title': u'SERMAN BRANDS 1.S - Travel wallet',
	 'title_tier': None},
	             {'backers_count': 1,
	 'description': u'EARLY BIRD! SERMAN BRANDS 1.S - For the true minimalist. Carry your must-have cards, Photo Id, business cards, folded bills. low price, to help us reach our goal',
	 'etd': None,
	 'limit': None,
	 'minimum': 30.0,
	 'remaining': None,
	 'rewards_count': None,
	 'shipping_enabled': True,
	 'shipping_preference': u'unrestricted',
	 'shipping_summary': u'Ships anywhere in the world',
	 'title': u'SERMAN BRANDS 1.S - Travel wallet',
	 'title_tier': None},
	             {'backers_count': 3,
	 'description': u'Save big: 2 for $50. SERMAN BRANDS 1.S - For the true minimalist. Carry your must-have cards, Photo Id, business cards, folded bills. low price, to help us reach our goal',
	 'etd': None,
	 'limit': None,
	 'minimum': 50.0,
	 'remaining': None,
	 'rewards_count': None,
	 'shipping_enabled': True,
	 'shipping_preference': u'unrestricted',
	 'shipping_summary': u'Ships anywhere in the world',
	 'title': u'Save big: 2 for $50',
	 'title_tier': None},
	             {'backers_count': 10,
	 'description': u'Save big: 2 for $50  SERMAN BRANDS 1.S - For the true minimalist. Carry your must-have cards, Photo Id, business cards, folded bills. low price, to help us reach our goal',
	 'etd': None,
	 'limit': None,
	 'minimum': 50.0,
	 'remaining': None,
	 'rewards_count': None,
	 'shipping_enabled': True,
	 'shipping_preference': u'unrestricted',
	 'shipping_summary': u'Ships anywhere in the world',
	 'title': u'Save big: 2 for $50',
	 'title_tier': None},
	             {'backers_count': 2,
	 'description': u'Save Big: 2 for $50. SERMAN BRANDS 1.S - For the true minimalist. Carry your must-have cards, Photo Id, business cards, folded bills. low price, to help us reach our goal',
	 'etd': None,
	 'limit': None,
	 'minimum': 50.0,
	 'remaining': None,
	 'rewards_count': None,
	 'shipping_enabled': True,
	 'shipping_preference': u'unrestricted',
	 'shipping_summary': u'Ships anywhere in the world',
	 'title': u'Save Big: 2 for $50',
	 'title_tier': None}],
	 'state': u'CA',
	 'sub_category': u'Product Design',
	 'successful_at': 1477530502,
	 'updates_count': 2,
	 'usd_pledged': u'5875.0',
	 'usd_rate': 1.0}

**Comment by birla** [comment]
Output JSON and JL files contains only this:

	[
	,
	,
	,
	,
	,
	,
	,
	,
	,
	,
	,
	,
	,
	,
	,
	,
	,
	,
	,

**Comment by redapple** [comment]
I believe there's something fishy around the serializer
```
    reward_items = scrapy.Field(serializer=RewardItem)
    rewards = scrapy.Field(serializer=Reward)
```

`serializer` argument for `Field()` [is supposed to be a function](https://github.com/scrapy/scrapy/blob/129421c7e31b89b9b0f9c5f7d8ae59e47df36091/scrapy/exporters.py#L45), and you are passing Item classes.
Is that on purpose?

**Comment by birla** [comment]
I am following an example implementation on a [SO answer](http://stackoverflow.com/questions/25095233/correct-way-to-nest-item-data-in-scrapy) which gave the above implementation as an example. Please share your views if there's a better way to implement my goal.

**Comment by redapple** [comment]
GitHub issues is not the ideal place for debugging non-standard patterns (that StackOverflow answer you link to is 2 years old, I'm not sure it still works nor if it did --  I haven't tried). Passing item classes as serializers is not documented nor supported as far as I know. (It may work though, with some tweaks.)
I suggest that you ask in StackOverflow directly, so you have more eyes on it.
You probably want to share you itemloader too.

**Comment by birla** [comment]
@redapple Thanks for the guidance and sorry for the clutter of an addition bug

**Comment by adilsoncarvalho** [comment]
@birla have you found a solution to that? I'm stuck on the same issue.

**Comment by birla** [comment]
My final solution was to define the sub-item as a plain python list. No
serializer or anything else. This worked without any errors.

IMHO this is a valid solution since the scrapy object representation is
only used until the record is persisted in the DB/file.

**Comment by adilsoncarvalho** [comment]
WOW, kudos @birla. It worked like a charm. I'll put here how I did to make it clear to others that stumble upon this error.

Just like you, I had an structured item like this that was generating the `ValueError: dictionary update sequence element` error.

```python
class ProdutoItem(Item):
  # a few attributes here

class DocumentItem(Item):
  # other fields that are plain dicts {}

  # this is an array of dicts [{}, {}, ..., {}] and this is the problem
  produtos = Field(serializer=ProdutoItem)
```

Following your tip I just got rid of the serializer, keeping all the loaders and stuff as they are

```python
class DocumentItem(Item):
  produtos = Field()
```

🎉 It worked like a charm. It seems that the serializer cannot handle a value that is an array. No serializer, no problem.

Once more, thanks!
