### ISSUE TITLE
How can I post a request that had both data and cookies

### ISSUE THREAD

**Issue by tarjintor** [scrapy/scrapy#2366]
Hi,everyone
I need scrapy a website,and It used aspx,
at first ,I used selenium,and it works fine,but too slow
,so  I analysis the request head in chrome dev,
and I found how to structure the head to get the content I need,but it need post both data and cookies,
I used requests and it works fine,but I need to do it in scrapy
I googled before,but it seems if you use Request(...),it can't post data, on the other hand ,if you use Formrequest,it can't have cookies
Now,I'm confused,and don't know what to do
Is that I misunderstood the meaning of these two method?
Help please!

**Comment by kmike** [comment]
Hey @tarjintor,

scrapy.Request can be used to post data (see 'method' and 'body' arguments: https://doc.scrapy.org/en/latest/topics/request-response.html#scrapy.http.Request), and FormRequest can be used to pass cookies (check https://doc.scrapy.org/en/latest/topics/request-response.html#scrapy.http.FormRequest).

We're using scrapy issue tracker to track scrapy bugs and feature requests; for support questions we're using http://stackoverflow.com (post a question with 'scrapy' tag), you may find it more helpful.
