### ISSUE TITLE
Extracting text in custom tags use Scrapy

### ISSUE THREAD

**Issue by hzxie** [scrapy/scrapy#2367]
This is a [web page](https://www.ncbi.nlm.nih.gov/pubmed/15721472) for a paper. There're some useful information to extract.

I want to extract title, author and abstract of this paper. So I wrote following code:

    class PublicationSpider(scrapy.Spider):
        name = "publications"
        start_urls = [
            'https://www.ncbi.nlm.nih.gov/pubmed/15721472',
        ]

        def parse(self, response):
            for publication in response.css('div.rprt.abstract'):
                yield {
                    'title': publication.css('h1::text').extract_first(),
                    'author': publication.css('div.auths > a::text').extract(),
                    'abstract': publication.css('div.abstr abstracttext::text').extract(),
                    'doi': publication.css('div.aux a::text').extract_first(),
                }

Unfortunately, the code above could not return the right content. It seems that the `abstracttext` element cannot be recognized by Scrapy.

I tried to replace `abstracttext` with `h4`, and the script went well.

So how can I extract the content in `abstracttext`?

See more: http://stackoverflow.com/questions/40241637/extracting-text-in-custom-tags-use-scrapy/

**Comment by redapple** [comment]
@hzxie , StackOverflow is the right place for this kind of "help me debug my code" questions.

**Comment by redapple** [comment]
By the way, you code seems to run just fine

**Comment by hzxie** [comment]
Don't you think that there's something wrong with Scrapy?
I don't think my code ran just fine.

I use `scrapy runspider PublicationSpider.py -o publications.json` to run this script, and I got following output:

```
[
```

Yes, there's only one character in the output.

**Comment by redapple** [comment]
@hzxie , well it ran fine for me, same code as you, http://pastebin.com/atp34920 (as I commented on StackOverflow)
So it's not reproducible with the code you supplied.
There's probably something specific do your setup. You'll need to provide use with a reproducible faulty example showing a bug in scrapy. See https://docs.scrapy.org/en/latest/contributing.html#reporting-bugs
Share you console logs, `scrapy version -v` which will show your system, python version and more.
