### ISSUE TITLE
DepthMiddleware docs should mention request.meta['depth']

### ISSUE THREAD

**Issue by kmike** [scrapy/scrapy#2374]
request.meta['depth'] is set by DepthMiddleware, but its [docs](https://doc.scrapy.org/en/latest/topics/spider-middleware.html?#module-scrapy.spidermiddlewares.depth) don't mention that. I think it'd be nice to add this information.

**Comment by arush0311** [comment]
Can i take this?

**Comment by kmike** [comment]
@arush0311 yes, help is appreciated!

**Comment by GISDev01** [comment]
I can fix this up if @arush0311 has moved on to something else.

**Comment by arush0311** [comment]
sure go ahead.

**Comment by amrx101** [comment]
Is this closed or up for grabs?

**Comment by redapple** [comment]
@amrx101 , I believe it's still up for grabs. Have a look at the previous https://github.com/scrapy/scrapy/pull/2455

**Comment by krishamehta** [comment]
Is it still up? Would like to help

**Comment by djunzu** [comment]
@krishamehta , still up, go for it! :)

**Comment by krishamehta** [comment]
Will start working on this!

**Comment by pranjalverma** [comment]
I would like to take this if this is still up. This is my first ever open source contribution, can anyone guide me? Much appreciated.

**Comment by AlexanderAJBerman** [comment]
Still open? I'd like to take a crack at this

**Comment by krishamehta** [comment]
I have started working on this
But since im new at open source , its taking a bit longer
