### ISSUE TITLE
[twisted] CRITICAL: Unhandled error in Deferred

### ISSUE THREAD

**Issue by Lampere1021** [scrapy/scrapy#2402]
```
[root@VM_50_138_centos tutorial]#  scrapy crawl dmoz
2016-11-22 17:08:19 [scrapy] INFO: Scrapy 1.2.1 started (bot: tutorial)
2016-11-22 17:08:19 [scrapy] INFO: Overridden settings: {'NEWSPIDER_MODULE': 'tutorial.spiders', 'SPIDER_MODULES': ['tutorial.spiders'], 'ROBOTSTXT_OBEY': True, 'BOT_NAME': 'tutorial'}
2016-11-22 17:08:19 [scrapy] INFO: Enabled extensions:
['scrapy.extensions.logstats.LogStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.corestats.CoreStats']
2016-11-22 17:08:19 [scrapy] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.robotstxt.RobotsTxtMiddleware',
 'scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.chunked.ChunkedTransferMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2016-11-22 17:08:19 [scrapy] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2016-11-22 17:08:19 [scrapy] INFO: Enabled item pipelines:
[]
2016-11-22 17:08:19 [scrapy] INFO: Spider opened
Unhandled error in Deferred:
2016-11-22 17:08:19 [twisted] CRITICAL: Unhandled error in Deferred:

2016-11-22 17:08:19 [twisted] CRITICAL:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/Twisted-16.6.0rc1-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python2.7/site-packages/Scrapy-1.2.1-py2.7.egg/scrapy/crawler.py", line 90, in crawl
    six.reraise(*exc_info)
  File "/usr/local/lib/python2.7/site-packages/Scrapy-1.2.1-py2.7.egg/scrapy/crawler.py", line 74, in crawl
    yield self.engine.open_spider(self.spider, start_requests)
ImportError: No module named _sqlite3
```

**Comment by redapple** [comment]
Can you share your spider code? Without more information, I'm tempted to think this has to do with your spider

**Comment by Lampere1021** [comment]
spiders/dmoz_spider.py

`from scrapy.spider import BaseSpider

class DmozSpider(BaseSpider):
    name = "dmoz"
    allowed_domains = ["dmoz.org"]
    start_urls = [
        "http://www.dmoz.org/Computers/Programming/Languages/Python/Books/",
        "http://www.dmoz.org/Computers/Programming/Languages/Python/Resources/"
    ]

    def parse(self, response):
        filename = response.url.split("/")[-2] + '.html'
        with open(filename, 'wb') as f:
            f.write(response.body)`

items.py

`from scrapy.item import Item, Field

class DmozItem(scrapy.Item):
    title = scrapy.Field()
    link = scrapy.Field()
    desc = scrapy.Field()`

**Comment by redapple** [comment]
what system are you on? what does `scrapy version -v` output?
have you google the error? I can see a few questions on StackOverflow and answers that mention the installation of sqlite3 is corrupt somehow

**Comment by Lampere1021** [comment]
# uname -a
Linux VM_50_138_centos 2.6.32-573.18.1.el6.x86_64 #1 SMP Tue Feb 9 22:46:17 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

# scrapy -V
Scrapy 1.2.1 - project: tutorial

# pip list
attrs (16.2.0)
cffi (1.9.1)
constantly (15.1.0)
cryptography (1.5.3)
cssselect (1.0.0)
enum34 (1.1.6)
idna (2.1)
incremental (16.10.1)
ipaddress (1.0.17)
lxml (3.6.4)
parsel (1.0.3)
pip (9.0.1)
pyasn1 (0.1.9)
pyasn1-modules (0.0.8)
pycparser (2.17)
PyDispatcher (2.0.5)
pyOpenSSL (16.2.0)
queuelib (1.4.2)
service-identity (16.0.0)
setuptools (28.8.0)
six (1.10.0)
Twisted (16.6.0rc1)
w3lib (1.16.0)
zope.interface (4.3.2)

**Comment by redapple** [comment]
`scrapy version -v` gives more information. can you paste that output instead of `scrapy -V`?

**Comment by redapple** [comment]
Also, can you try:

```
$ python
>>> import sqlite
```
This may be similar to https://stackoverflow.com/questions/11394013/problems-with-python-2-7-3-on-centos-with-sqlite3-module

**Comment by Lampere1021** [comment]
`# scrapy version -v
/home/tutorial/tutorial/spiders/dmoz_spider.py:1: ScrapyDeprecationWarning: Module `scrapy.spider` is deprecated, use `scrapy.spiders` instead
  from scrapy.spider import BaseSpider
/home/tutorial/tutorial/spiders/dmoz_spider.py:3: ScrapyDeprecationWarning: tutorial.spiders.dmoz_spider.DmozSpider inherits from deprecated class scrapy.spiders.BaseSpider, please inherit from scrapy.spiders.Spider. (warning only on first subclass, there may be others)
  class DmozSpider(BaseSpider):
Scrapy    : 1.2.1
lxml      : 3.6.4.0
libxml2   : 2.7.6
Twisted   : 16.6.0rc1
Python    : 2.7.6 (default, Nov 21 2016, 21:01:03) - [GCC 4.4.7 20120313 (Red Hat 4.4.7-16)]
pyOpenSSL : 16.2.0 (OpenSSL 1.0.1e-fips 11 Feb 2013)
Platform  : Linux-2.6.32-573.18.1.el6.x86_64-x86_64-with-centos-6.7-Final`

**Comment by redapple** [comment]
Can you try importing sqlite from python shell? https://github.com/scrapy/scrapy/issues/2402#issuecomment-262193742 
If that fails, maybe you need to check your python installation

**Comment by Lampere1021** [comment]
According to your proposal, the problem is solved, SQLite3 module does not exist.
Thank you very much, you can leave a WeChat?

**Comment by redapple** [comment]
@Lampere1021 , I don't know what you mean

**Comment by Lampere1021** [comment]
WeChat in China is a communication tool, similar to the mailbox @redapple

**Comment by redapple** [comment]
Right, but what do you mean by _"you can leave a WeChat?"_ (if the question is "do I have a WeChat account", the answer is no)

**Comment by ZhangHarvey** [comment]
Github: gay dating site...

**Comment by redapple** [comment]
@ZhangHarvey , please read https://github.com/scrapy/scrapy/blob/master/CODE_OF_CONDUCT.md

**Comment by ZhangHarvey** [comment]
@redapple  I am so sorry for my rudeness.

**Comment by redapple** [comment]
@Lampere1021 , I'm closing the issue.
Feel free to re-open it if you still experience the problem.
