### ISSUE TITLE
SelectJmes fails to parse the right way due to arg_to_iter() turning the output into a list.

### ISSUE THREAD

**Issue by IAlwaysBeCoding** [scrapy/scrapy#2407]
Here is an example of what I'm talking about:

```python
import json
from scrapy import Item
from scrapy.loader import ItemLoader
from scrapy.loader.processors import SelectJmes
string = r'''{
  "type": [
    "http://schema.org/Physician"
  ], 
  "properties": {
    "url": [
      "http://www.vitals.com/doctors/Dr_Patrick_B_Wright.html"
    ], 
    "aggregateRating": [
      {
        "type": [
          "http://schema.org/AggregateRating"
        ], 
        "properties": {
          "worstRating": [
            "0"
          ], 
          "reviewCount": [
            "1"
          ], 
          "bestRating": [
            "5"
          ], 
          "ratingValue": [
            "4.3"
          ], 
          "ratingCount": [
            "6"
          ]
        }
      }
    ], 
    "medicalspecialty": [
      {
        "type": [
          "http://schema.org/MedicalSpecialty"
        ], 
        "properties": {
          "name": [
            "Pediatric Surgery"
          ]
        }
      }
    ], 
    "name": [
      "Dr. Patrick Wright MD"
    ], 
    "address": [
      {
        "type": [
          "http://schema.org/PostalAddress"
        ], 
        "properties": {
          "addressLocality": [
            "Jackson"
          ], 
          "addressRegion": [
            "MS"
          ], 
          "streetAddress": [
            "2500 N State St"
          ], 
          "postalCode": [
            "39216"
          ], 
          "telephone": [
            "(601) 984-2150"
          ]
        }
      }
    ]
  }
}'''

data = json.loads(string)

#This will work fine
proc = SelectJmes('properties.address[0].properties.postalCode[0]')


#However, if its used in an input processor it will fail and will need to add `[0]` before the query in order to work.

class SomeItem(Item):
     postal_code = Field(
          input_processor = SelectJmes('properties.address[0].properties.postalCode[0]')
     )

loader = ItemLoader(SomeItem())
loader.add_value('postal_code', data)
item = loader.load_item()

```

The only way to make it work will be to always add `[0]` to the JmesQuery when done inside an input or output field processor.
#This will work
[0].properties.address[0].properties.postalCode[0]

Should we document this odd behaviour due to arg_to_iter doing this?

**Comment by redapple** [comment]
@IAlwaysBeCoding , Thanks for reporting.
Excuse my ignorance here, but I don't use or am familiar with `ItemLoaders` much, and much less with `SelectJmes`.
Can you add details on your investivation about which `arg_to_iter()` call is causing trouble?
Is it in `SelectJmes`? or in `ItemLoader` and processors (is it [this line](https://github.com/scrapy/scrapy/blob/129421c7e31b89b9b0f9c5f7d8ae59e47df36091/scrapy/loader/__init__.py#L90) maybe)?

**Comment by IAlwaysBeCoding** [comment]
There is no ignorance at all, you are one of my Scrapy's idols for putting so much work into keeping the framework up to date. I don't know if its a bug or expected feature, but I guess that when `arg_to_iter()` is called, it puts all of the inputs into a list. `SelectJmes` is basically like a selectors for a dictionary instance. It is used the same way as an Xpath/Css selector by providing a string for lazy loading.

It is one of those caveats that can take a newbie quite a while to figure out if they don't know how the `ItemLoaders` process things.

Yeap is that line, what I was trying to point out is that for people that will use `SelectJmes` they should understand that everything extracted from the inputs will be put in a list so their 'Jmes` query needs to reflect that.

This person also posted this on the google scrapy-users group.
https://groups.google.com/forum/#!searchin/scrapy-users/selectjmes%7Csort:relevance/scrapy-users/GakYR94Eb4Y/X4HjIMn_CgAJ

He gave pretty much gave 3 workarounds, I used the first one as the simplest one. So should we document the 3 options as a workaround or just 1 or 2?

**Comment by elacuesta** [comment]
This behaviour was introduced and documented [a long time ago](https://github.com/scrapy/scrapy/commit/907fad6da83a20898df1d0cb80ebf36c48488ca5).
Since "processors must receive an iterator as their first argument", this is where [`MapCompose`](https://docs.scrapy.org/en/1.8/topics/loaders.html#scrapy.loader.processors.MapCompose) comes into play:

```python
In [1]: from scrapy.loader import ItemLoader
   ...: from scrapy.loader.processors import SelectJmes, MapCompose
   ...:
   ...: data = {
   ...:   "type": [
   ...:     "http://schema.org/Physician"
   ...:   ],
   ...:   "properties": {
   ...:     "address": [
   ...:       {
   ...:         "type": [
   ...:           "http://schema.org/PostalAddress"
   ...:         ],
   ...:         "properties": {
   ...:           "addressLocality": [
   ...:             "Jackson"
   ...:           ],
   ...:           "addressRegion": [
   ...:             "MS"
   ...:           ],
   ...:           "streetAddress": [
   ...:             "2500 N State St"
   ...:           ],
   ...:           "postalCode": [
   ...:             "39216"
   ...:           ],
   ...:           "telephone": [
   ...:             "(601) 984-2150"
   ...:           ]
   ...:         }
   ...:       }
   ...:     ]
   ...:   }
   ...: }

In [2]: processor = SelectJmes("properties.address[0].properties.postalCode[0]")
   ...: processor(data)
Out[2]: '39216'

In [3]: loader = ItemLoader(item={})
   ...: loader.data_in = processor
   ...: loader.data2_in = MapCompose(processor)
   ...: loader.add_value("data", data)
   ...: loader.add_value("data2", data)
   ...: loader.load_item()
Out[3]: {'data2': ['39216']}
```
