### ISSUE TITLE
301 Moved Permanently

### ISSUE THREAD

**Issue by liangpu597** [scrapy/scrapy#2408]
Follow the doc I write this code with shell :
`scrapy shell http://doc.scrapy.org/en/latest/_static/selectors-sample1.html
 response.selector.xpath('//title/text()')
`
however:
is suggested:
` [<Selector xpath='//title/text()' data=u'301 Moved Permanently'>]`

but i can open :http://doc.scrapy.org/en/latest/_static/selectors-sample1.html
with my brower.

why ?

**Comment by kmike** [comment]
Browser follows redirect automatically, but Scrapy 1.2 doesn't. I'm closing it in favor of https://github.com/scrapy/scrapy/issues/2290.

**Comment by liangpu597** [comment]
so i can't do this with scrapy shell ?

2016-11-23 21:34 GMT+08:00 Mikhail Korobov <notifications@github.com>:

**Comment by kmike** [comment]
For now you can either follow redirect yourselves:

```fetch(response.headers['Location'].decode('latin1'))```

or open a page after a redirect (it redirects from http to https):

```$ scrapy shell 'https://doc.scrapy.org/en/latest/_static/selectors-sample1.html'```

**Comment by liangpu597** [comment]
i use scrapy shell 'https://doc.scrapy.org/en/latest/_static/selectors-
sample1.html'
it doesn't work:

>  File "<string>", line 2, in raiseException
>
> wisted.internet.error.DNSLookupError: DNS lookup failed: address "'https"
>> not f
>
> und: [Errno 11004] getaddrinfo failed.
>
>
2016-11-23 21:49 GMT+08:00 Mikhail Korobov <notifications@github.com>:

**Comment by kmike** [comment]
@liangpu597 hm, it may be something with your Internet connection; `scrapy shell 'https://doc.scrapy.org/en/latest/_static/selectors-sample1.html'` works for me.

**Comment by redapple** [comment]
@liangpu597 , if you're on Windows, try `scrapy shell "https://doc.scrapy.org/en/latest/_static/selectors-
sample1.html"`

**Comment by liangpu597** [comment]
yeah! i try scrapy shell "https://doc.scrapy.org/en/
latest/_static/selectors- sample1.html"
it'ok! thank you!

2016-11-24 1:18 GMT+08:00 Paul Tremberth <notifications@github.com>:
