### ISSUE TITLE
SCHEDULER settings not documented

### ISSUE THREAD

**Issue by mohmad-null** [scrapy/scrapy#2414]
The FAQ mentions:
SCHEDULER_DISK_QUEUE and SCHEDULER_MEMORY_QUEUE with regards to changing between FIFO/LIFO.

Neither of these appears to be documention except for this single reference. They're not on the settings page.

Also, the link to wikipedia for "LIFO" is actually to a disambiguation page, which doesn't help if you don't know what it is in the first place. :-) (I know it's Last In First Out, but others may not).

**Comment by pawelmhm** [comment]
You're right it seems like this is not in docs, I fixed that here #2417
