### ISSUE TITLE
Strange behavior when trying to override user agent

### ISSUE THREAD

**Issue by MatBl** [scrapy/scrapy#2416]
More info here: http://stackoverflow.com/questions/40848302/scrapy-overriding-user-agent-doesnt-work

To keep it short: If I try to change the user agent (via settings, command line, spider, even default settings, doesn't matter where), the parser stops outputting data. It only works if the user agent starts with "Scrapy .....". So:

scrapy crawl myspider -o myspider.csv -t csv -s USER_AGENT="Scrapy Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit" -> works. 
scrapy crawl myspider -o myspider.csv -t csv -s USER_AGENT="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit" -> doesn't work.

Does anybody see the logic in this?

Scrapy    : 1.2.1
lxml      : 3.6.4.0
libxml2   : 2.9.4
Twisted   : 16.5.0
Python    : 2.7.12 (default, Nov 19 2016, 06:48:10) - [GCC 5.4.0 20160609]
pyOpenSSL : 16.2.0 (OpenSSL 1.0.2g  1 Mar 2016)
Platform  : Linux-4.4.0-45-generic-x86_64-with-Ubuntu-16.04-xenial

**Comment by redapple** [comment]
Hi @MatBl , it looks very website-specific, à priori not much Scrapy can do against it.
Are you able to reproduce this behavior with curl for example?
(`curl -A 'Mozilla/3.0 (Win95; I)' http://www.example.com/`)

**Comment by MatBl** [comment]
It really doesn't happen on other sites. But still. Very strange. I will report back, if I find out why this happen. Thanks!
