### ISSUE TITLE
scrapy is not working with Single Page Web App like AngularJs and React

### ISSUE THREAD

**Issue by rahullsinha** [scrapy/scrapy#2425]
i am trying to scrape data from web app , but scrappy is not working. when i opened website in scrappy shell  and i used "**view(response)**" command , but website is not loading contents.

**Comment by podolskyi** [comment]
Scrapy works with static page
for single page read more detail about Splash https://github.com/scrapinghub/splash and Scrapy+Splash https://github.com/scrapy-plugins/scrapy-splash

**Comment by redapple** [comment]
As @podolskyi hints at, Scrapy does not interpret JavaScript statements and therefore will probably not show what your browser renders if the website you are scraping relies on JavaScript.
There's no immediate plan to have Scrapy interpret JavaScript or render pages like a browser does.
[Splash](https://splash.readthedocs.io/) is one solution to render JavaScript. There are other like Selenium.

**Comment by IAlwaysBeCoding** [comment]
I scrape a lot of sites using React, you have to get the data you want from the Json. There is just no other way. Once you do it a few times ot gets easier.

**Comment by jacksonSingleton** [comment]
@IAlwaysBeCoding Using ScraPy alone or are you doing this alongside splash?

**Comment by joelgriffith** [comment]
This is something I'm trying to solve acutely in https://github.com/joelgriffith/navalia, as simply drives headless chrome (and hopefully fairly reliable). Splash seems pretty interesting though...

**Comment by vaibhavhrt** [comment]
SPA React/Angular apps will use API, you just need to figure the API endpoints and data they return (use network tab of your browser's devtools), then you can just hit those endpoints(even without scrapy) and have json data.

**Comment by ParthBarot-BoTreeConsulting** [comment]
@vaibhavhrt Most of the times, such API requests are not allowed from diff. origins and blocked sooner or later. The best option we have in JS based websites is, browser automation. There are a few options and we have used there in many of similar solutions,

1. Google Puppeteer - The best option, fully customizable
2. Selenium - I would rate it as 2nd number, not bad but not the best!

There are other libraries available, but based on my experience I found puppeteer better. I hope if we could manage some way, of handling puppeteer from scrappy, that would be great!

**Comment by vaibhavhrt** [comment]
@ParthBarot-BoTreeConsulting it will not be a cross origin request, since scrappy is not running in some webpage.

**Comment by elacuesta** [comment]
> There are other libraries available, but based on my experience I found puppeteer better. I hope if we could manage some way, of handling puppeteer from scrappy, that would be great!

@ParthBarot-BoTreeConsulting This has been discussed recently in #4484, you might find some alternatives there.

**Comment by CubeOfCheese** [comment]
> SPA React/Angular apps will use some API (unless it's a static website), you just need to figure the API endpoints and data they return (use network tab of your browser's devtools), then you can just hit those endpoints(even without scrapy) and have json data.

But many APIs require authentication tokens. Is there any work-around for that?

**Comment by vaibhavhrt** [comment]
@CubeOfCheese in that case they will have an API where you can send username, password and receive auth token.

**Comment by peterrauscher** [comment]
Anyone coming from Google - you can pull data from React/Next.js pages using purely HTTP requests and some string parsing. [I wrote an extension](https://chromewebstore.google.com/detail/kjlhnflincmlpkgahnidgebbngieobod) that will do it for you, or generate code snippets you can use to do it for you in your project. Hope this helps!
