### ISSUE TITLE
Scrapy gives HTML response different from requests.get

### ISSUE THREAD

**Issue by fjdu** [scrapy/scrapy#2431]
scrapy version: 1.1.2
python version: 2.7.12
platform: Mac OS X 10.11.6

**The issue:**

For the url given in the following minimum working example, the HTML text in the response from scrapy is different from the one obtained with `requests.get`.   The latter seems to be the correct one.  It seems scrapy somehow duplicates part of the response html.  This does not happen for all sites.

See the attached file for the two different html files.  Or you may run the following code to generate them.

    import scrapy
    from scrapy.crawler import CrawlerRunner
    from twisted.internet import reactor
    import requests
    
    url = 'http://training.sac.net.cn/cms/flkcalone.htm?myId=4028d0ee57ec28180157f55059b87209'
    
    headers = {
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
        'Accept-Encoding': 'gzip, deflate, sdch',
        'Accept-Language': 'en-US,en;q=0.8,zh-CN;q=0.6,zh;q=0.4,zh-TW;q=0.2',
        'Cache-Control': 'max-age=0',
        'Connection': 'keep-alive',
        'Upgrade-Insecure-Requests': '1',
        'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36',
        }
    
    
    class Test(scrapy.Spider):
        name = 'test'
    
        def start_requests(self):
            request = scrapy.Request(url=url, callback=self.parse, headers=headers)
            yield request
    
        def parse(self, response):
            with open('response_with_scrapy.html', 'w') as f:
                f.write(response.text.encode('utf-8'))
    
    
    if __name__ == '__main__':
        with open('response_with_requests.html', 'w') as f:
            f.write(requests.get(url, headers=headers).text.encode('utf-8'))
    
        runner = CrawlerRunner()
        runner.crawl(Test)
        d = runner.join()
        d.addBoth(lambda _: reactor.stop())
        reactor.run()
[two_responses.zip](https://github.com/scrapy/scrapy/files/639455/two_responses.zip)

**Comment by redapple** [comment]
hi @fjdu , can you share more details about what is different? maybe the 2 HTML sources?
Also, scrapy and python-requests may not use the same User-Agent string.
Can you check that?

**Comment by fjdu** [comment]
@redapple I updated the code to force scrapy and requests to use the same headers (including the User-Agent), and the responses are still different (see the attached zip file for the two html files, and you can use diff or vimdiff to see the differences).  You can also run the code to get the two html files.

**Comment by redapple** [comment]
I can reproduce this issue with 1.1.2.
But with scrapy 1.2.2 (the lastest official release), I can not reproduce it.
I think this might be the same as https://github.com/scrapy/scrapy/issues/1606, which was fixed in scrapy 1.2.0
Can you try upgrading scrapy to at least 1.2.0?

**Comment by fjdu** [comment]
@redapple Upgrading to scrapy 1.2.2 solved the problem!  Thanks a lot!

**Comment by redapple** [comment]
Thanks for the heads up!

**Comment by RaoTauqeerSajid** [comment]
I have this same issue with
scrapy version: 1.7.2
python version: 3.7.4
platform: Windows 10 pro 1809

The HTML text in the response from scrapy is different from the one obtained with requests.Session.get

**Comment by saaiprakash1** [comment]
requests==2.22.0
Scrapy 1.8.0 
Python 3.5.2

same issue for me also 
The HTML text in the response from scrapy.Request is different from the one obtained with requests.get 

error --->> "Session Timed Out. Please Login Again!" in html page 
using requests.get  I am getting data in html

**Comment by RaoTauqeerSajid** [comment]
Thanks for your reply
