### ISSUE TITLE
Exposing downloader stats to custom scheduler

### ISSUE THREAD

**Issue by sibiryakov** [scrapy/scrapy#2435]
In order to get maximum fetching performance, the queue have to be carefully metered. In order to do this the custom scheduler needs to know:
- the type of the key in downloader (ip or hostname),
- count of requests to specific hostname/ip in the queue,
- delay/concurrency parameters of hostname/ip,
- list of all hostname/ips in the queue.

Current Scheduler API is designed for storage and resume-from-disk purposes, so I think it's time to re-think it taking into account efficiency of fetching. The most common problem with inefficient fetching is a queue filled with a single domain and polite crawling requirement.

**Comment by sibiryakov** [comment]
@kmike and @dangra pls have a look.

**Comment by kmike** [comment]
> The most common problem with inefficient fetching is a queue filled with a single domain

Yeah, it is a very common issue; I'd love to have it solved in Scrapy. @sibiryakov could you please clarify what changes do you think we should make? Scheduler can already get information from self.crawler.engine.downloader - what do you propose?

> and polite crawling requirement.

Hm, one can send URLs of the same hostname/ip to the same worker, and use existing scrapy limit features. Do you have examples of when this method doesn't work, or when it is better to solve this in scheduler? Is it to support a case where a single worker is not enough to scrape from a single ip, but there still should be limits?

**Comment by sibiryakov** [comment]
> Scheduler can already get information from self.crawler.engine.downloader - what do you propose?
Custom Scheduler is maintained in a separate project, and therefore such a deep penetration to downloader by using the above mentioned approach is fragile. I propose to implement the methods providing above mentioned stats in Scheduler interface, and probably extract it
https://github.com/scrapy/scrapy/blob/master/scrapy/core/scheduler.py#L13. 

This will help to stabilize the API, and make sure external applications relying on it will not break.

> Is it to support a case where a single worker is not enough to scrape from a single ip, but there still should be limits?
No.

**Comment by sibiryakov** [comment]
> Hm, one can send URLs of the same hostname/ip to the same worker, and use existing scrapy limit features. Do you have examples of when this method doesn't work, or when it is better to solve this in scheduler?
There are two main concerns:
- The website could be very big, so all it's requests will not fit in spider's memory. Or it could fit, but for reliability purposes it makes sense to have only little part of website's requests in spider. This could be solved if engine/downloader could send back to the scheduler the hostname/ips which are presented heavily in it's queue, therefore suggesting Scheduler to not deliver them, if it has them.
- existing Scrapy limiting features (I guess you meant CONCURRENT_REQUESTS_* and delays settings) is tied with the engine behavior, when downloader has less requests than ``CONCURRENT_REQUESTS`` it continuously tries to fill the gap, instead of reaching some level of concurrency.

In fact, the setting ``CONCURRENT_REQUESTS`` isn't managing the number of concurrent requests, instead it limits the number of requests which reside in the queue at the same time, but real number of requests which are in connection establishment or content receiving state(the ones processed concurrently) is much lower.

I think it's either a problem of naming or understanding of async downloader.

**Comment by Gallaecio** [comment]
See #3520.
