### ISSUE TITLE
How to use the -a option to pass a parameter to scrapy? 

### ISSUE THREAD

**Issue by woshichuanqilz** [scrapy/scrapy#2439]
I read the doc and find the command line should be like this.
`scrapy runspider getspecificimg.py -a ip='lizhe'`

And my spider code is like this : 
```
class GetImage(scrapy.Spider):
    name = 'ImageSpider'
    start_urls = ['https://www.pexels.com/']

# Get the input argument
    # NameNeedSearch = InputPara
    NameNeedSearch = ip

```
But the result I get means that the `ip isn't defined why? `
![20161211162649.bmp](http://7xpvdr.com1.z0.glb.clouddn.com/20161211162649.bmp)

**Comment by kmike** [comment]
Hey @woshichuanqilz,

Arguments are available as spider attributes, i.e. you can access it as `self.ip`, not as `ip`.

We're trying to use scrapy issue tracker to track scrapy bugs; there are better ways to get answers for usage questions - http://stackoverflow.com/ (use 'scrapy' tag) is a preferred support channel.

**Comment by woshichuanqilz** [comment]
@kmike  tnx I want to pass in a variable then use it to concatenate the `full url` and use it as the start_url.

My code is like this :  and get the error `self is not defined` why is that ?

```
class GetImage(scrapy.Spider):
    name = 'ImageSpider'
# Get the input argument
    NameNeedSearch = self.ip
    # startUrl = 'https://www.pexels.com/' + 
    start_urls = ['https://www.pexels.com/']
```

**Comment by redapple** [comment]
@woshichuanqilz , can you post your question to StackOverflow? Thanks

**Comment by woshichuanqilz** [comment]
@redapple  already post ! 
http://stackoverflow.com/questions/41142375/how-to-use-the-a-option-to-pass-a-parameter-to-scrapy

**Comment by babubalakrishnan** [comment]
ok
