### ISSUE TITLE
ERROR : Scrapy 1.2.2 requires Python 2.7 

### ISSUE THREAD

**Issue by dhermanus** [scrapy/scrapy#2441]
Hi All, After some tinkering on my Centos VPN I've finally got scrapy to be installed.
However when I tried to run scrapy on the console. It says 
Scrapy 1.2.2 requires Python 2.7

However you can see below that I've installed Python 2,7 already and I've added alias  to my
bashrc file to use Python 2,7 as the default version for python. 

Why am I still getting that error ?
Please help... Thanks.

[root@vnode01 dhermanus]# python -V
Python 2.7.8
[root@vnode01 dhermanus]# scrapy
Scrapy 1.2.2 requires Python 2.7
[root@vnode01 dhermanus]#

**Comment by kmike** [comment]
Hey @dhermanus,

Could you please paste the whole traceback?

**Comment by kmike** [comment]
Hey @dhermanus,

Could you please run `which scrapy` and check the script at this path? I think it is likely it has a previous version of Python hardcoded. 

It is usually a good idea to use virtualenvs, they make such issues much less common.

**Comment by redapple** [comment]
@dhermanus , did you manage to make it work?

**Comment by dhermanus** [comment]
Hello All... 
Thanks for the reply... Yeah I manage to get it to work.. the reason is that I had 2 version of python install.  Just had to run alias to default my python command to the latest version of Python. 

Again thank you for the help.. :)
