### ISSUE TITLE
robots.txt requests don't use errback

### ISSUE THREAD

**Issue by mohmad-null** [scrapy/scrapy#2443]
I'm triggering a timeout error to test my script.

Even though I have an errback, with basically the same code as here - https://doc.scrapy.org/en/latest/topics/request-response.html#topics-request-response-ref-errbacks - the automated request that's made by scrapy to robots.txt for a host isn't using the errback function.

All other requests are though.

Scrapy 1.2.1

**Comment by redapple** [comment]
What do you mean by _"All other requests are though."_?
Can you provide sample code and logs for this and explain what you expected to happen?

**Comment by mohmad-null** [comment]
Sorry, I wasn't clear. All other requests go through normally and trigger the errback if necessary.
Sample code - just use the stuff in the link; it's what I used.

What I expect to happen is that any automated (done by scrapy without being in my start_urls list) request to robots.txt should use the same errback function like all of the other url's do.

**Comment by redapple** [comment]
Currently, robots.txt middleware implementation choses to let all requests go out when robots.txt cannot be downloaded. So an error for the internal request for robots.txt is the same as a "allow all" robots.txt.

Do I understand correctly that you would prefer that if robots.txt fails to be fetched, that requests are ignored and `IgnoreRequest` is raised (hence going to the requests' errback), as if robots.txt had forbidden them?
If so, this could be a new setting for the RobotsTxtMiddleware.

**Comment by mohmad-null** [comment]
Honestly, I'm not sure what the best option is. I just thought I should raise the fact that robots.txt doesn't use the errback callback that's specified. I can see reasons to do so and reasons not to, but have no real views as to what would be best; it would depend on the spider.

**Comment by Gallaecio** [comment]
I don’t think the `robots.txt` request errback should be handled by the user, I think the middleware should handle it transparently as it currently does.
