### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by ketankr9** [scrapy/scrapy#2445]
The error given out when runnung `sudo pip install scrapy` on ubuntu16.04

`Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-rfOc5T/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-GxhQ75-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-rfOc5T/cryptography/
`

**Comment by pawelmhm** [comment]
I was able to install Scrapy on Ubuntu 16.04 without problems.

You need to install some requirements with ubuntu package manager, see installation instructions here:

https://doc.scrapy.org/en/latest/intro/install.html#ubuntu-12-04-or-above

especially:

```
>sudo apt-get install python-dev python-pip libxml2-dev libxslt1-dev zlib1g-dev libffi-dev libssl-dev
```

**Comment by ketankr9** [comment]
But while installing Scrapy, the script should first check if the required packages are installed or not and should install the required packages along with it with user's permission.
