### ISSUE TITLE
can't use "scrapy" after scrapy installed 

### ISSUE THREAD

**Issue by zonglinyue** [scrapy/scrapy#2459]
I have installed scrapy successed 

Installing collected packages: scrapy
Successfully installed scrapy-1.2.2

pip show Scrapy
Name: Scrapy
Version: 1.2.2
Summary: A high-level Web Crawling and Web Scraping framework
Home-page: http://scrapy.org
Author: Pablo Hoffman
Author-email: pablo@pablohoffman.com
License: BSD
Location: /usr/local/python3.5/lib/python3.5/site-packages
Requires: service-identity, Twisted, six, parsel, cssselect, PyDispatcher, queuelib, lxml, pyOpenSSL, w3lib

but when i use scrapy ,"bash: scrapy: command not found".is that i should "ln -s  ***  scrapy"? please tell me which is the target file,thank you!

**Comment by harshasrinivas** [comment]
Did you try reloading your `bashrc` (or `zshrc`) file?
`$ source ~/.bashrc`

**Comment by zonglinyue** [comment]
yes,i had tried and there's nothing about scrapy in ~/.bashrc

**Comment by harshasrinivas** [comment]
Check your $PATH
`$ echo $PATH`
Add `/usr/local/python3.5/bin` to it (if it doesn't exist).

**Comment by zonglinyue** [comment]
the problem has been resolved as your suggest,it,s reason is python path. Thank you!!!
