### ISSUE TITLE
A lot of dead links to scrapy's readthedocs pages

### ISSUE THREAD

**Issue by vovanz** [scrapy/scrapy#2463]
Link to online documentation from [scrapy website](https://scrapy.org/doc/) is dead: http://doc.scrapy.org/en/1.2

When you google something like `scrapy spiders` top 3 links are all dead.

When I was submitting this issue github suggested me to read [guidelines for contributing](https://github.com/scrapy/scrapy/blob/master/CONTRIBUTING.md). I wish I could do it, but the link is also dead:
> The guidelines for contributing are available here: http://doc.scrapy.org/en/master/contributing.html

**Comment by kmike** [comment]
Whoops, that's not good. I also noticed that version selector disappeared at http://doc.scrapy.org. We're using readthedocs to host and deploy our docs, so it looks like a rtfd bug, but we should also check that we haven't messed up with something.

**Comment by PetaPetaPeta** [comment]
It looks like the language and version has been removed as options:

> Google link:
> https://doc.scrapy.org/en/latest/topics/downloader-middleware.html
> Working link:
> https://doc.scrapy.org/topics/downloader-middleware.html

**Comment by kmike** [comment]
I've opened an issue in readthedocs repo: https://github.com/rtfd/readthedocs.org/issues/2562.

**Comment by kmike** [comment]
It all works not (kudos to @ericholscher for debugging it) - it seems someone clicked a wrong checkbox. Thanks for the report!
