### ISSUE TITLE
Quotes in html text are parsed incorrectly

### ISSUE THREAD

**Issue by jacklol13** [scrapy/scrapy#2467]
This is a simple IPython test case:
```
In [1]: from scrapy.selector import Selector

In [2]: Selector(text='<div x="It\x22s"', type="html")
Out[2]: <Selector xpath=None data=u'<html><body><div x="It" s></div></body><'>
```
The data in the selector shows `<div x="It" s>` instead of `<div x="It\"s">` or `<div x="It&quot;s">`

This has been tested in Scrapy 1.2.2

**Comment by kmike** [comment]
`'<div x="It\x22s"'` is literally `<div x="It"s"` in Python; this is broken HTML and parsing it as `<div x="It" s>` looks fine to me. `"\x22"` is just another way to write `'"'`:

```
>>> '\x22' == '"'
True
```

**Comment by jacklol13** [comment]
I put `\x22` and not `'"'` so Python won't complain. Anyways it looks like the problem was on the HTML end so I'll close this.
