### ISSUE TITLE
Recommend Anaconda when installing Scrapy on Windows

### ISSUE THREAD

**Issue by redapple** [scrapy/scrapy#2475]
Succesfully using `pip` on Windows for Scrapy (and lxml and Twisted) is far from easy.
Anaconda/Miniconda seems to work much smoother.
Let's recommend Anaconda first for Windows users in the installation page, and leave the pip-way for the brave.

**Comment by redapple** [comment]
@eliasdorneles , I believe you were working on this recently.

**Comment by eliasdorneles** [comment]
Hey @redapple -- yeah, I wanted to try this out before doing the change, just to be sure.

I've installed Windows on a VM to verify the installation process, and I've found trouble already just trying to install CPython directly from python.org downloads. The installation would never end, even after leaving it running for hours.

I've successfully installed Anaconda and am now testing the Scrapy installation process with it.
Sorry for the delay on reporting, I'll keep this issue updated as I go along.
