### ISSUE TITLE
Clean bad HTML

### ISSUE THREAD

**Issue by eliasdorneles** [scrapy/scrapy#2481]
There are some cases of bad HTML that makes Scrapy (well, lxml really) to choke on the response content, and I was thinking it would make sense to add a CleanBadHtml middleware that could be optionally disabled.

I've just stumbled on an example case from a real website, where the response had something like this (real phone number edited) in its content:

    text = u'<a href="tel:111\x00111\x001111">111-111-1111</a>'

The `\x00` is interpreted as end of input by lxml, so the selector ends up stopping right there:

```
>>> parsel.Selector(text)
<Selector xpath=None data=u'<html><body><a href="tel:111"></a></body'>
>>> parsel.Selector(text).extract()
u'<html><body><a href="tel:111"></a></body></html>'
```

I'm not sure what's the best place to fix this, but I think we gotta do something about it either in Scrapy or in Parsel, because these HTML pages are accepted by the browsers, who ignore the null characters.

For this specific case, simply removing the `\x00` characters found in the body before passing to the selector would avoid the issue.

What do you think?
Where do you think it would be the best place to do this?

**Comment by redapple** [comment]
I would say this kind of HTML-fixing should be handled by Parsel, but I know of (at least) https://github.com/alecxe/scrapy-beautifulsoup downloader middleware that "pipes" responses through BeautifulSoup (with html5lib parser if requested)

From the README:
> BeautifulSoup itself with the help of an underlying parser of choice does a pretty good job of handling non-well-formed or broken HTML. In some cases, it makes sense to pipe the HTML through BeautifulSoup to "fix" it.

@eliasdorneles , have you tested these broken pages with html5lib?  If so, there's also the option of finalizing https://github.com/scrapy/scrapy/pull/1043 in Parsel.

**Comment by eliasdorneles** [comment]
Hm, I only tested it with lxml.html.soupparser (it raises an exception), but haven't tried html5lib parser, lemme try that.

**Comment by eliasdorneles** [comment]
Looks like it will do:

```
>>> text = u'<a href="tel:111\x00111\x001111">111-111-1111</a>'
>>> from lxml.html import html5parser, tostring
>>> html5parser.fromstring(text)
<Element {http://www.w3.org/1999/xhtml}a at 0x7fc28e115d40>
>>> tostring(html5parser.fromstring(text))
'<html:a xmlns:html="http://www.w3.org/1999/xhtml" href="tel:111&#65533;111&#65533;1111">111-111-1111</html:a>'
```

However, I had to use `html5lib=0.9999999` (seven 9s) instead of the latest one `0.999999999` (nine 9s) because of this issue: http://stackoverflow.com/questions/39086278/html5lib-typeerror-init-got-an-unexpected-keyword-argument-encoding

**Comment by redapple** [comment]
The code you pasted above has trouble with latest html5lib?

**Comment by eliasdorneles** [comment]
More like the combination of latest html5lib with the lxml version that I have -- gotta check w/ latest lxml version.

**Comment by eliasdorneles** [comment]
Scratch that, I was already checking with the latest lxml version, it looks like there is an incompatibility of lxml.etree.html5parser with latest html5lib which still persists, I've submitted a bug report: https://bugs.launchpad.net/lxml/+bug/1654544

**Comment by pmyteh** [comment]
I came across this issue today, and wrote a simple downloader middleware to simply strip ASCII NUL bytes from Responses. It's pretty naive as it stands (doesn't update the headers with a new Content-Length, will obviously break binary responses like pictures and archives etc.) but is a lot lighter weight than piping everything through a parser and may be suitable for your use case.

```
class StripNull(object):
    """Downloader middleware to discard ASCII NUL bytes from Responses. This
       really shouldn't be necessary, but some pages are served studded 
       with NUL bytes, which messes up the underlying lxml parsing library. The
       effect is that the page's parse tree is cut off where the NUL occurs.
    """
    def __init__(self, stats, settings):
        if not settings.getbool('STRIPNULL_ENABLED'):
            raise NotConfigured
        self.stats = stats

    @classmethod
    def from_crawler(cls, crawler):
        return cls(crawler.stats, crawler.settings)

    def process_response(self, request, response, spider):
        newbody = bytes(x for x in response.body if x != 0)

        if len(newbody) < len(response.body):
            self.stats.inc_value('stripnull/stripped', spider=spider)
            return response.replace(body = newbody)
        else:
            self.stats.inc_value('stripnull/clean', spider=spider)
            return response
```

**Comment by kmike** [comment]
I think that's fine to workaround this bug here: https://github.com/scrapy/parsel/blob/f664f0c155aae95074bd9ec0365368f2d2e18028/parsel/selector.py#L41

**Comment by peonone** [comment]
Seems this can be closed by https://github.com/scrapy/parsel/pull/124

**Comment by kmike** [comment]
Good catch, thanks @peonone!
