### ISSUE TITLE
The order of install failed

### ISSUE THREAD

**Issue by MarcSteven** [scrapy/scrapy#2486]
I try to install via shell ,do this order $pip install Scrapy,but It cannot install ...My version of Python is 2.7.1.......

**Comment by redapple** [comment]
hi @MarcSteven , 
what system are you on? (Linux, Windows, OSX...)
Can you share your console output when you try to install scrapy?
Have you tried [with a virtualenv](https://docs.scrapy.org/en/latest/intro/install.html#using-a-virtual-environment-recommended)?

**Comment by MarcSteven** [comment]
OSX ,pip order cannot be executed.........I know less about Python...... Later i will confirm again.

**Comment by kmike** [comment]
Hey @MarcSteven,

We're using this issue tracker to track Scrapy bugs and feature requests; to get answers for installation and usage questions there is a better way: a question at http://stackoverflow.com (use 'scrapy' tag).
