### ISSUE TITLE
Scrapy missing ajax requests

### ISSUE THREAD

**Issue by lavorato** [scrapy/scrapy#2520]
I created some Scrapy crawler with Selenium to paginate the Google Reviews window. My code works well on my machine (Mac OS) but when I send to my Linux AWS instance the behavior of pagination is not the same. I guess that scrapy are missing the ajax requests of each pagination.

The pagination loads in a intermitted way, loading some pages but not all like in my machine. Do you guys have any idea what is happening?

**Comment by kmike** [comment]
Hey @lavorato,

There can be a lot of reasons it happens: a different IP address (website could be blocking AWS), different software versions, etc. Either way, stackoverflow is a better place to debug such issues; we are using this issue tracker to track Scrapy bugs and feature requests, and it doesn't look like a Scrapy bug - it looks more like a site-specific scraping problem, with Selenium added to the mix. 

We're using http://stackoverflow.com/ as a support channel (use 'scrapy' tag).  I doubt anyone will be able to answer your question as-is, so if you create a stackoverflow question then please try to provide more details. Thanks!
