### ISSUE TITLE
S3 compatible API services

### ISSUE THREAD

**Issue by drozzy** [scrapy/scrapy#2523]
Can we use Feed exporter for S3 to store the items in an s3 compatible service, like [Minio](https://www.minio.io/) or [Riak CS](https://github.com/basho/riak_cs)?

I tried setting the `FEED_URI` to my local instance of minio `http://192.168.1.111:9000/minio/mybucket/%(name)s.json`

but scrapy complains that "Unknown feed storage shceme: http".

If I try changing it to  `s3://192.168.1.111:9000/minio/mybucket/%(name)s.json` it tries to pre-pend it to amazon:

```
CertificateError: hostname 192.168.1.111.s3.amazonaws.com doesn't match either of '*.s3.amazonaws.com', 's3.amazon.com'
```

Any thoughts? Am I doing something wrong?

**Comment by IAlwaysBeCoding** [comment]
Unfortunately, this isn't possible since 'Scrapy` uses the `boto` as the S3 client library. However, I can see this being a really nice feature to add on.

**Comment by drozzy** [comment]
Yeah, I figured.
Bugging boto guys to make it happen now.

Can I write a custom exporter? Would that be hard to do?

**Comment by drozzy** [comment]
Solved, by writing my own item exporter, and item pipeline as per the docs:
https://doc.scrapy.org/en/latest/topics/exporters.html

Used the minio client to push events to s3 service directly. Works great. If anyone is interested, the source is here: https://bitbucket.org/drozdyuk/scrapy_quotes/overview

**Comment by LaundroMat** [comment]
@drozzy , would you mind sharing your solution?

**Comment by drozzy** [comment]
@LaundroMat Does the link not work?

https://bitbucket.org/drozdyuk/scrapy_quotes/src

**Comment by LaundroMat** [comment]
Waw, I must have been dead tired for not having seen the link 🙄- sorry for that! (and thanks for replying)
