### ISSUE TITLE
Cannot add custom command

### ISSUE THREAD

**Issue by nihn** [scrapy/scrapy#2524]
Hello,

I followed https://doc.scrapy.org/en/latest/topics/commands.html#custom-project-commands to add my custom command. I've set `COMMANDS_MODULE=linkedin_scraper.commands`. Unfortunately no new commands are present in `scrapy -h` output nor in `scrapy commands`.
I've done some debugging and it seems that in [_get_commands_dict](https://github.com/scrapy/scrapy/blob/master/scrapy/cmdline.py#L44) function custom settings are not available yet so Scrapy does not know anything about my custom commands module.
I have this project structure:
```
.
├── Dockerfile
├── LICENSE
├── docker-compose.yml
├── linkedin_scraper
│   ├── __init__.py
│   ├── __pycache__
│   ├── commands
│   │   ├── __init__.py
│   │   └── people_search.py
│   ├── settings.py
│   └── spiders
│       ├── __init__.py
│       ├── __pycache__
│       └── people_search.py
├── requirements.txt
├── run.sh
├── scrapy.cfg
├── setup.py
└── tests.sh
```
I tired with Scrapy 1.3.0 and 1.2.2.

**Comment by redapple** [comment]
hello @nihn , 

> I've set COMMANDS_MODULE=linkedin_scraper.commands

where are you setting this? in `settings.py`?

> in _get_commands_dict function custom settings are not available yet 

what do you mean by _custom settings_?

**Comment by redapple** [comment]
Here's an example of a very dumb "hello" command:
```
$ cat customcmd/commands/hello.py
import scrapy
from scrapy.commands import ScrapyCommand


class HelloCommand(ScrapyCommand):

    def run(self, args, opts):
        print("Hello!")
```

Here's my file structure, on top of a basic project:

```
scrapy startproject customcmd
cd customcmd
mkdir customcmd/commands/
cd customcmd/commands/
echo "" > __init__.py
```

```
$ tree
.
├── customcmd
│   ├── commands
│   │   ├── hello.py
│   │   ├── __init__.py
│   ├── __init__.py
│   ├── items.py
│   ├── middlewares.py
│   ├── pipelines.py
│   ├── settings.py
│   └── spiders
│       ├── example.py
│       ├── __init__.py
└── scrapy.cfg

3 directories, 16 files
```
with `COMMANDS_MODULE = 'customcmd.commands'` in my `settings.py` file

This is what I get:

```
$ scrapy hello
2017-02-01 14:21:29 [scrapy.utils.log] INFO: Scrapy 1.3.0 started (bot: customcmd)
2017-02-01 14:21:29 [scrapy.utils.log] INFO: Overridden settings: {'NEWSPIDER_MODULE': 'customcmd.spiders', 'SPIDER_MODULES': ['customcmd.spiders'], 'COMMANDS_MODULE': 'customcmd.commands', 'ROBOTSTXT_OBEY': True, 'BOT_NAME': 'customcmd'}
Hello!
```

**Comment by nihn** [comment]
@redapple thanks for your reply. Something must be wrong with my environment because if I launch it in Docker container (with mounted project root directory) command is visible.
