### ISSUE TITLE
Scrapy ignores proxy credentials when using "proxy" meta key

### ISSUE THREAD

**Issue by vezunch1k** [scrapy/scrapy#2526]
Code `yield Request(link, meta={'proxy': 'http://user:password@ip:port’})` ignores user:password. 
Problem is solved by using header "Proxy-Authorization" with base64, but it is better to implement it inside Scrapy.

**Comment by redapple** [comment]
Thanks @vezunch1k for reporting.
I can indeed reproduce this.

`HttpProxyMiddleware` does not touch outgoing requests if they have the "proxy" key set in meta dict. Especially, it does not update headers for `Proxy-Authorization`.

And Scrapy's downloader `Agent` only uses the "host" part of the proxy URL, and ignores credentials that may be there, assuming `Proxy-Authorization` is already there if it's needed:

```
>>> from scrapy.core.downloader.webclient import _parse
>>> _parse('https://username:password@10.20.30.40:8888')
('https', 'username:password@10.20.30.40:8888', '10.20.30.40', 8888, '/')
```

```
        proxy = request.meta.get('proxy')
        if proxy:
            _, _, proxyHost, proxyPort, proxyParams = _parse(proxy)
            scheme = _parse(request.url)[0]
            proxyHost = to_unicode(proxyHost)
            omitConnectTunnel = b'noconnect' in proxyParams
            if  scheme == b'https' and not omitConnectTunnel:
                proxyConf = (proxyHost, proxyPort,
                             request.headers.get(b'Proxy-Authorization', None))
                return self._TunnelingAgent(reactor, proxyConf,
                    contextFactory=self._contextFactory, connectTimeout=timeout,
                    bindAddress=bindaddress, pool=self._pool)
```

Proxy credentials in proxy URL are correclty processed by `HttpProxyMiddleware` when `http(s)_proxy` env vars are being used,
so it makes sense to me to handle them as well when using "proxy" key direclty.

**Comment by elacuesta** [comment]
Oh right, I was thinking about actually performing the requests, but I see now that checking the headers should be enough. Thanks Paul, I'll add tests similar to those :+1:
