### ISSUE TITLE
A small flaw about the code of example  1.3.0

### ISSUE THREAD

**Issue by Youwei-Xiao** [scrapy/scrapy#2550]
![1](https://cloud.githubusercontent.com/assets/24528158/22770564/70c5459e-ee5f-11e6-92ac-8b97de0af0e1.jpg)
In this example, I found out that I cannot crawl author name. After I checked, I figured out that the format of HTML of author in http://quotes.toscrape.com/tag/humor/ is different. We can see:
![3](https://cloud.githubusercontent.com/assets/24528158/22770616/c81f5334-ee5f-11e6-99af-d0633ea3c071.jpg)

So, to solve is, we need to code like this:
![4](https://cloud.githubusercontent.com/assets/24528158/22770628/da3fe3bc-ee5f-11e6-9a7f-8e2e6174ea74.jpg)
Thanks a lot. That's not a bug or problem but a small flaw. : )

**Comment by redapple** [comment]
Hi @Youwei-Xiao , thanks for reporting.
In fact, it's my mistake, I did not port https://github.com/scrapy/scrapy/pull/2313 correctly into "master" branch. There's one missing commit.
Let me fix that.
