### ISSUE TITLE
BrowserLikeContextFactory not available in some conditions

### ISSUE THREAD

**Issue by Unode** [scrapy/scrapy#2560]
While tracing the error that lead to #2555 I tried the workaround [mentioned in the documentation](https://doc.scrapy.org/en/latest/topics/settings.html#downloader-clientcontextfactory) without success.

This code lives [incontextfactory.py](https://github.com/scrapy/scrapy/blob/c3411373e8a8ee2786588bdad7be469c69a25e2a/scrapy/core/downloader/contextfactory.py#L63) but was not reachable as the import was failing on my system due to #2555.

This file is a large `try/except` block with many potential points of failure and it's likely to trip other users in the future.
That said, could this be refactored to provide a fallback for `BrowserLikeContextFactory` or otherwise reduce the scope of the `try/except` to avoid breaking the API?

**Comment by redapple** [comment]
I think the try/except was to handle Twisted pre- and post-processing v14.
It can probably be removed to only have the twisted 14+ available imports

Le 13 févr. 2017 7:36 PM, "Renato Alves" <notifications@github.com> a
écrit :
