### ISSUE TITLE
finish relocations

### ISSUE THREAD

**Issue by kmike** [scrapy/scrapy#2568]
What do you think about removing shims for moved/renamed modules from https://github.com/scrapy/scrapy/issues/1063? Scrapy 1.0 release was 20 months ago, and upgrade path for users is clear.

**Comment by Parth-Vader** [comment]
If the modules have been renamed, I think it should be removed for the newer versions of Scrapy.

**Comment by kmike** [comment]
My main motivation is that I'm getting imports wrong every time - IDE autocomplete shows both deprecated and new paths (e.g. scrapy.dupefilter and scrapy.dupefilters), and it is hard to remember which one to use. I'm checking their source code every time to avoid deprecation warning :)

**Comment by Parth-Vader** [comment]
@kmike I'm new to this, but in my opinion , a user would get confused if autocomplete shows both options. Then he'd have to look up in the docs.
Hence, my main purpose is that the user should have a smooth experience.

**Comment by kmike** [comment]
@Parth-Vader the downside or removing deprecations is that obviously it could break a lot of existing code.

**Comment by Parth-Vader** [comment]
@kmike Yeah, that's true. It's always hard to remove things once the project becomes so complex. :stuck_out_tongue:

**Comment by djunzu** [comment]
Wouldn't be the best course of action establish a deprecation policy, announce it on the next release, and start to execute it in the following release. So, if the policy says "deprecated methods will be dropped after three minor releases", then everyone knows when it will be removed.

**Comment by kmike** [comment]
@djunzu it makes sense, though we tend to keep deprecations for a long time if they don't hurt. From the developer point of view some of the deprecations affect productivity, and some don't. 

I think currently we're following this approach: it is OK to deprecate something in major release X and remove it in major release X+1 (given that they separated by at least half year or a year), but if deprecated path doesn't hurt it can be kept for much longer. "Deprecated methods will be dropped after three minor releases" can be more aggressive than the current policy, though more predicatable. I agree that it is good to have policy written down explicitly.

**Comment by kmike** [comment]
@dangra @eliasdorneles @lopuhin what's your opinion on doing this in 1.6 release? Old locations were deprecated more than 3 years ago (Scrapy 1.0.0 is released 2015-06-19).

**Comment by dangra** [comment]
3 years is a lot already, +1 from me to cleanup.
