### ISSUE TITLE
Sharing of website-specific configuration files

### ISSUE THREAD

**Issue by Parth-Vader** [scrapy/scrapy#2573]
A new section in the official documentation could be added where people could share their configuration files that they used to successfully scrape data from a specific website (by successful, I mean not getting banned and getting a good speed.) 
This way, it would be easier for people without any prior knowledge of HTML, Python or Shell, could easily use scrapy to get data from those specific sites.

**Comment by kmike** [comment]
Hey @Parth-Vader,

I think such resource for scraping specific third-party websites is inappropriate for Scrapy docs. 

We have example projects which scrapes http://toscrape.com/ website though - see https://doc.scrapy.org/en/latest/intro/examples.html.
