### ISSUE TITLE
ftp_user and ftp_password meta keys are not documented

### ISSUE THREAD

**Issue by kmike** [scrapy/scrapy#2574]
ftp_user and ftp_password meta keys are not documented in https://doc.scrapy.org/en/latest/topics/request-response.html#topics-request-meta; it'd be nice to add them. See also: https://github.com/scrapy/scrapy/pull/2343

**Comment by MikeinRealLife** [comment]
I would like to attempt to take this.

**Comment by MikeinRealLife** [comment]
I would like to take this one
