### ISSUE TITLE
Why the downloaded file numbers is not equal numbers of url's line in my log file?

### ISSUE THREAD

**Issue by luofeiyu** [scrapy/scrapy#2579]
Platform: debian8 + python3.6 + scrapy 1.3.2.    
Here is a simple scrapy script to download all the us stock quote.   
Please to download the 7z file on webpage.

https://drive.google.com/open?id=0B9BpilWzmmMCRGQ0RF8xWWx3ZVU
   

To extract it with 7z.

    7z x urls.7z -o/home

The sample data  /home/urls.csv can be tested.
To save the below scrapy script as  /home/quote.py

    import scrapy
    import csv

    CONCURRENT_REQUESTS = 3
    CONCURRENT_REQUESTS_PER_SPIDER = 3
    CLOSESPIDER_PAGECOUNT = 100000
    CLOSESPIDER_TIMEOUT = 36000
    DOWNLOAD_DELAY = 10
    RETRY_ENABLED = False
    COOKIES_ENABLED = False
    RETRY_ENABLED = True
    RETRY_TIMES = 1
    COOKIES_ENABLED = False

    downloaded = open('/home/downloaded.csv','w')

    class TestSpider(scrapy.Spider):
        def __init__(self, *args, **kw):
            self.timeout = 10

        name = "quote"
        allowed_domains = ["chart.yahoo.com"]
        csvfile = open('/home/urls.csv')
        reader = csv.reader(csvfile)
        rows = [row[0] for row in reader]
        start_urls = rows

        def parse(self, response):
            content = response.body
            target = response.url
            filename = target.split("=")[1]
            open('/home/data/'+filename+'.csv', 'wb').write(content)
            downloaded.write(target+"\n")

The last two lines in /home/quote.py is important,     
**open('/home/data/'+filename+'.csv', 'wb').write(content)** to open a file and save the data into the file.    
The following ,**downloaded.write(target+"\n")**,it is to write a log to describe which url was downloaded instantly.   

To execute the spider with:

    scrapy runspider  /home/quote.py

In my opinion the numbers--all downloaded files is equal to line numbers of url in /home/downloaded.csv.

    ls  /home/data |wc -l
    6012
    wc /home/downloaded.csv
    6124

Why two numbers here aren't equal?    
Please to test on your plarform and tell me the two numbers.

**Comment by ianhhhhhhhhe** [comment]
I suggest you to check your logging informations, if there is any httperror.
When I ran your spider, I got many INFO like ```INFO: Ignoring response <404 https://chart.yahoo.com/table.csv?s=EYEGW>: HTTP status code is not handled or not allowed```

So I think it caused because of some net error

**Comment by kmike** [comment]
@luofeiyu we're using this issue tracker to track Scrapy bugs and feature requests. This doesn't look like a Scrapy bug, so I'm closing this issue; there are better support channels - you can get better help by asking your question at http://stackoverflow.com (use "scrapy" tag when creating a question). @ianhhhhhhhhe's suggestion makes sense.
