### ISSUE TITLE
How to call 3rd party function in parse() callback.

### ISSUE THREAD

**Issue by hanjihun** [scrapy/scrapy#2597]
What I want to implement is:
```py
def parse(self, response):
    param = {}
    self.send_request(self, param)

def send_request(self, param):
    url = "www.sample.com/auto/"
    yield FormRequest(url, callback=self.parse_auto, formdata=param, method="POST")

def parse_auto(self, response):
    ...
```

In the above code, the self.send_request(self, param) function does not work. I am on right way?

**Comment by kmike** [comment]
Hey @hanjihun,

This is how Python works, there is nothing Scrapy-specific: `parse` method is a generator, and you need to iterate over its results:

```py
def parse(self, response):
    param = {}
    for req in self.send_request(self, param):
        yield req
    # or, in Python 3:
    # yield from self.send_request(self, param)
```

https://stackoverflow.com can be a better channel for support questions (use tag "scrapy").

**Comment by hanjihun** [comment]
@kmike Thank you
