### ISSUE TITLE
How to delete Cache ?

### ISSUE THREAD

**Issue by cristimocean** [scrapy/scrapy#2601]
Sorry for asking here but I could not find help anywhere else.
Usually to delete cache I just delete .scrapy folder in project directory.
But now I have a spider for which this doesn't work. Somehow I get the cached responses (I tested by turning off the internet so I am 100% sure). But I don't understand where they are coming from since my .scrapy folder is deleted.
P.S. I NEED to delete cache , I can't just deactivate it or set it to expire because of the way I build my spiders.

**Comment by djunzu** [comment]
https://doc.scrapy.org/en/1.3/topics/downloader-middleware.html?highlight=cache#httpcache-dir

**Comment by cristimocean** [comment]
thanks for suggestion dzunzu. I'll try but the Cache policies are poorly documented so I don't feel confident on using them. 
 And you should I go through all that trouble when I should be able to just delete the cache whenever I want to ? I used to be able to do that but now on a spider it magically reappears after I delete it. I am sure Scrapy is doing that somehow and I was hoping someone could tell me how to stop it ...

**Comment by redapple** [comment]
Hi @cristimocean , please use the [scrapy-users mailing list](https://groups.google.com/d/forum/scrapy-users) for this type of troubleshooting questions.

A few things to check nonetheless:

1.. to be sure that the HTTP Cache is used, check your crawl startup logs, you should see:

```
[scrapy.middleware] INFO: Enabled downloader middlewares:
[...
 'scrapy.downloadermiddlewares.httpcache.HttpCacheMiddleware',
 ...]
```

2.. and when a URL is fetched from the cache, you will see in the logs the "cached" flag, e.g.
```
2017-02-28 10:47:04 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://www.example.com> (referer: None) ['cached']
```

3.. Finally, if you can launch `scrapy shell` with the same settings and environment as your crawl with a cache issue, you can check where the HTTP cache is fetching response from, by loading the storage object [the same way that HTTP cache middleware does](https://github.com/scrapy/scrapy/blob/cce631abec4397b10b30f21878f093326b17e223/scrapy/downloadermiddlewares/httpcache.py#L23), and checking the `.cachedir` attribute:

```
$ scrapy shell -s HTTPCACHE_ENABLED=True
2017-02-28 10:41:41 [scrapy.utils.log] INFO: Scrapy 1.3.2 started (bot: httpbin)
(...)
>>> from scrapy.utils.misc import load_object
>>> storage = load_object(settings['HTTPCACHE_STORAGE'])(settings)
>>> storage.cachedir
'/home/paul/scrapy/httpbin/.scrapy/httpcache'
```

Here, `/home/paul/scrapy/httpbin/.scrapy/httpcache` would be the location to delete in your case.
