### ISSUE TITLE
log path to http cache

### ISSUE THREAD

**Issue by kmike** [scrapy/scrapy#2604]
What do you think about logging a full path to HTTP cache when HttpCacheMiddleware is instantiated? It may help to debug issues like https://github.com/scrapy/scrapy/issues/2601.

**Comment by redapple** [comment]
Sounds useful indeed.

**Comment by jorenham** [comment]
Hi, we're a team of four Computer Science Master students. For a course we have to contribute to an open-source project, and Scrapy looks really awesome to all of us.
So we would like to work is this one, is that ok?
@Eauwzeauw
@Threore
@jojona

**Comment by kmike** [comment]
@jorenham sounds great!

**Comment by redapple** [comment]
Closed via https://github.com/scrapy/scrapy/issues/2611
