### ISSUE TITLE
Unable to override settings inside spider from spider constructor using CrawlerProcess.crawl()

### ISSUE THREAD

**Issue by manisoftwartist** [scrapy/scrapy#2605]
I am trying to programatically call a spider through a script. I an unable to override the settings through the constructor using CrawlerProcess. Let me illustrate this with the default spider for scraping quotes from the official scrapy site (last code snippet at [official scrapy quotes example spider][1]).

    class QuotesSpider(Spider):

    name = "quotes"

    def __init__(self, somestring, *args, **kwargs):
        super(QuotesSpider, self).__init__(*args, **kwargs)
        self.somestring = somestring
        self.custom_settings = kwargs

    def start_requests(self):
        urls = [
            'http://quotes.toscrape.com/page/1/',
            'http://quotes.toscrape.com/page/2/',
        ]
        for url in urls:
            yield Request(url=url, callback=self.parse)

    def parse(self, response):
        for quote in response.css('div.quote'):
            yield {
                'text': quote.css('span.text::text').extract_first(),
                'author': quote.css('small.author::text').extract_first(),
                'tags': quote.css('div.tags a.tag::text').extract(),
            }

Here is the script through which I try to run the quotes spider

    
    from scrapy.crawler import CrawlerProcess
    from scrapy.utils.project import get_project_settings
    from scrapy.settings import Settings
    
        def main():
    
        proc = CrawlerProcess(get_project_settings())
    
        custom_settings_spider = \
        {
            'FEED_URI': 'quotes.csv',
            'LOG_FILE': 'quotes.log'
        }
        proc.crawl('quotes', 'dummyinput', **custom_settings_spider)
        proc.start()

  [1]: https://doc.scrapy.org/en/latest/intro/tutorial.html

**Comment by redapple** [comment]
hi @manisoftwartist , I see you have posted [the same question on StackOverflow](https://stackoverflow.com/questions/42511814).
Let's continue there.

**Comment by manisoftwartist** [comment]
Hi @redapple, ok if you wish. But would be nice to have a link here though, for someone who accesses this later.

**Comment by redapple** [comment]
The link is in my comment.
We try to limit GitHub issues to discussions and bug reports. This feels more like a troubleshooting issue. (It may be because of poor documentation though.)

**Comment by manisoftwartist** [comment]
OK. Since the documentation said that we should be able to override custom_settings from inside spider, I was thinking this was an issue or a bug. (perhaps a case of wrong understanding. Thats why I posted the code). I appreciate your help nevertheless.

**Comment by kmike** [comment]
@manisoftwartist could you please point to the place in docs which is wrong, confusing or underspecified, so that we can fix it?

Related issues: https://github.com/scrapy/scrapy/issues/1305, https://github.com/scrapy/scrapy/issues/1280
