### ISSUE TITLE
scrapy shell - bug in processing escaped URLs

### ISSUE THREAD

**Issue by harshasrinivas** [scrapy/scrapy#2624]
For eg: URL - `https://altoona.craigslist.org/search/sss?query=cars&sort=rel&searchNearby=1` when pasted on the command line (shell-specific) creates a few escaping characters - backslashes

The following command gives a 404:
```sh
$ scrapy shell 'https://altoona.craigslist.org/search/sss\?query\=cars\&sort\=rel\&searchNearby\=1'
```

I saw a similar discussion in [#1232](https://github.com/scrapy/scrapy/issues/1232) - where `urllib.parse.unquote()` was used to fix it.

In this case even `unquote` doesn't seem to work.
```python
>>> unquote('https://altoona.craigslist.org/search/sss\?query\=cars\&sort\=rel\&searchNearby\=1')
'https://altoona.craigslist.org/search/sss\\?query\\=cars\\&sort\\=rel\\&searchNearby\\=1'
```

Even though [URL-character escaping is an issue specific to the shell](http://unix.stackexchange.com/questions/293472/paste-url-into-terminalurxvt-zsh-failed-some-characters-get-escaped), wouldn't it be awesome if Scrapy processes such URLs automatically?

**Comment by kmike** [comment]
I think undoing escapes done in shell is a wrong thing to do for Scrapy. It is a job of a caller to pass correct arguments to Scrapy. What shell are you using? Maybe removing `'` quotes will make it work?

**Comment by harshasrinivas** [comment]
> Maybe removing ' quotes will make it work?

Yes, it worked. Thanks!
I'm using ZSH (oh-my-zsh)

**Comment by kmike** [comment]
It seems oh-my-zsh is the cause (http://unix.stackexchange.com/questions/293472/paste-url-into-terminalurxvt-zsh-failed-some-characters-get-escaped). Maybe we should document this gotcha, something like "Note: in some shell setups, most notably a default `oh-my-zsh` config for zsh, URLs are escped automatically when pasting to shell; don't wrap then in quotes in this case."

**Comment by harshasrinivas** [comment]
Sure, I'll send a PR right away.

**Comment by rolando** [comment]
IIRC, if you open double quotes `"` before pasting the content then it doesn't auto-escape the string.

**Comment by harshasrinivas** [comment]
Hello @rolando , I tried it on oh-my-zsh and basic zsh as well. Opening double-quotes beforehand does not seem to help. (Tested it on both iTerm2 and Terminal)

**Comment by wRAR** [comment]
The same will happen with any other program that takes URLs as command line arguments, e.g. `curl`, so I don't think Scrapy should do anything about this, including documentation changes.
