### ISSUE TITLE
lots of warnings `RuntimeWarning: Could not load referrer policy ''` when running tests

### ISSUE THREAD

**Issue by kmike** [scrapy/scrapy#2626]
Check `tox -e py36 -- tests/test_crawl.py -s` output. @redapple is it a testing issue, or a problem with the warning? I've first noticed it in https://travis-ci.org/scrapy/scrapy/jobs/208185821 output.

**Comment by kmike** [comment]
I can see it in "normal" crawls as well, it doesn't look like a testing-only issue.

**Comment by redapple** [comment]
Right. I'll submit a patch shortly. Thanks for reporting
