### ISSUE TITLE
scrapy bench needs to be more complex

### ISSUE THREAD

**Issue by Parth-Vader** [scrapy/scrapy#2629]
The current benchmarking is done on a very simple page, where the bot just follows all the links. This does not actually give a correct scraping speed for a standard web page. 

It could contain several images as well, along with some restrictions so that the benchmarking suite could give a realistic approximation of the scraping speed.

Any other ideas?
ping @dangra

**Comment by lopuhin** [comment]
This was implemented during GSoC'2017 by @Parth-Vader in https://github.com/scrapy/scrapy-bench/ (we decided that it's better to keep it as a separate project due to extra requirements and complexity), final report is at https://medium.com/@vermaparth/parth-gsoc-f5556ffa4025. Thanks Parth!

**Comment by Parth-Vader** [comment]
@lopuhin :smile:
