### ISSUE TITLE
Stale contrib paragraph in contribution docs

### ISSUE THREAD

**Issue by jorenham** [scrapy/scrapy#2634]
By my knowledge `contrib` has been depcrecated since [1.0.0](https://doc.scrapy.org/en/master/news.html?highlight=contrib#scrapy-1-0-0-2015-06-19).
There still is some contribution documentation about it.
https://doc.scrapy.org/en/master/contributing.html#scrapy-contrib

**Comment by kmike** [comment]
A good catch, I think it is safe to remove this section.

**Comment by kmike** [comment]
Fixed by #2636. Thanks @jorenham!
