### ISSUE TITLE
how should image pipeline react to 3** redirects?

### ISSUE THREAD

**Issue by pawelmhm** [scrapy/scrapy#2635]
Currently when image download encounters redirect download fails. This is probably [because of this line that sets handle_httpstatus_all](https://github.com/scrapy/scrapy/blob/master/scrapy/pipelines/media.py#L106). As a result image download handler gets to process response with status 3** and usually empty body, it is not able to download image, it fails. Is this expected behavior? Why not follow redirect in case like this?

**Comment by kmike** [comment]
See https://github.com/scrapy/scrapy/pull/2616

**Comment by pawelmhm** [comment]
ok, closing as duplicate of other issues
