### ISSUE TITLE
allow to set RETRY_TIMES per-request

### ISSUE THREAD

**Issue by kmike** [scrapy/scrapy#2642]
I think it'd be nice to allow set RETRY_TIMES per-request using a `request.meta` key ("max_retry_times"?) - some requests could be more important than others.

**Comment by atultherajput** [comment]
I am a newbie to open source. I know Python programming language. Please guide me to fix this issue.

**Comment by saurabhgoyaliitr** [comment]
is this still open  to try?

**Comment by redapple** [comment]
hi @saurabhgoyaliitr , do you mean you want to work on fixing it?
https://github.com/scrapy/scrapy/issues/2643 by @harshasrinivas has already done most of the work I believe.

**Comment by redapple** [comment]
Fixed in https://github.com/scrapy/scrapy/issues/2643
