### ISSUE TITLE
Amazon Scraping

### ISSUE THREAD

**Issue by ihusny** [scrapy/scrapy#2652]
I want to create a web scrapping on amazon product page, not on the individual page but on the search result page. 

I tried with this but it isn't returning any results.

    def parse(self, response):
        for href in response.css('ul li.s-result-item celwidget::attr(href)'):
            print href

**Comment by abdelq** [comment]
You should use the `scrapy shell` command on the search result page and play with your response.
You might also want to use `scrapy view` to view the page as seen by the scraper.

**Comment by redapple** [comment]
@ihusny , this is not a bug report nor a feature discussion.
Therefore, I suggest that you send this question to [scrapy-users](https://groups.google.com/forum/#!forum/scrapy-users) or [StackOverflow](https://stackoverflow.com/questions/tagged/scrapy) (use "scrapy" tag)
