### ISSUE TITLE
Running scrapy from script is giving "cannot import name crawler" error on pipelines

### ISSUE THREAD

**Issue by bslima** [scrapy/scrapy#266]
I'm trying to run scrapy spiders within a python script as the documentation says (http://doc.scrapy.org/en/latest/topics/practices.html#run-from-script)
Here is a snippet of my code (https://gist.github.com/bslima/5151215)

But when i run the python script i get a 
<b>ImportError: Error loading object 'aqueleimovel.pipelines.ValidationImovelPipeline': cannot import name crawler</b>

First of all, i only use scrapy crawler reference in the python script mentioned above. Second, scrapy finds my spider but is missing my pipelines.

From the traceback, It seems like scrapy is having a problem with python class path.

```
$ python main.py
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    crawler.configure()
  File "/Library/Python/2.7/site-packages/Scrapy-0.17.0-py2.7.egg/scrapy/crawler.py", line 44, in configure
    self.engine = ExecutionEngine(self, self._spider_closed)
  File "/Library/Python/2.7/site-packages/Scrapy-0.17.0-py2.7.egg/scrapy/core/engine.py", line 63, in __init__
    self.scraper = Scraper(crawler)
  File "/Library/Python/2.7/site-packages/Scrapy-0.17.0-py2.7.egg/scrapy/core/scraper.py", line 66, in __init__
    <b>self.itemproc = itemproc_cls.from_crawler(crawler)</b>
  File "/Library/Python/2.7/site-packages/Scrapy-0.17.0-py2.7.egg/scrapy/middleware.py", line 50, in from_crawler
    <b>return cls.from_settings(crawler.settings, crawler)</b>
  File "/Library/Python/2.7/site-packages/Scrapy-0.17.0-py2.7.egg/scrapy/middleware.py", line 29, in from_settings
   <b>mwcls = load_object(clspath)</b>
  File "/Library/Python/2.7/site-packages/Scrapy-0.17.0-py2.7.egg/scrapy/utils/misc.py", line 40, in load_object
    raise ImportError, "Error loading object '%s': %s" % (path, e)
ImportError: Error loading object 'aqueleimovel.pipelines.ValidationImovelPipeline': cannot import name crawler
```

My directory struct is like this:

```
|- main.py
|- scrapy.cfg
|- local_settings.py
|---- project
      |- settings.py
      |- pipelines.py
      |---- spiders
            |- spider.py
```

I've searched the web and the only reference i could find was: 
http://stackoverflow.com/questions/13112520/importing-scrapy-conf-settings-generates-error
The guy didnt get any help and dropped scrapy as solution.

I also asked the scrapy-users mailing list, lots of helps but none of them worked for me. To see more info about this look here: (https://groups.google.com/forum/?fromgroups=#!topic/scrapy-users/UR6vyKQeDw4)

I also tried to create the tutorial procedure and simply created the script to run the spider and im getting the same traceback error.

Im running the master clone fo scrapy on a OSX 10.8.2.

I'm only reporting this, because with all the help in the scrapy-user list we couldn't find a solution, so it may be a scrapy issue.

**Comment by CodeWith-M-Hamza** [comment]
i am trying to import the crawler function from this sequence
**from scraper.sources.ecode import crawler**  still i get this error 
Exception has occurred: ImportError       (note: full exception trace is shown but execution is paused at: _run_module_as_main)
cannot import name 'crawler' from 'scraper.sources.ecode' (/home/hamza/Hamza_workspace/xpath_validator_service/scraper/sources/ecode/__init__.py)
  File "/home/hamza/Hamza_workspace/xpath_validator_service/scraper/sources/ecode/Whitney_TX.py", line 2, in <module>
    from scraper.sources.ecode import crawler
  File "/usr/lib/python3.12/runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.12/runpy.py", line 198, in _run_module_as_main (Current frame)
    return _run_code(code, main_globals, None,
ImportError: cannot import name 'crawler' from 'scraper.sources.ecode' (/home/hamza/Hamza_workspace/xpath_validator_service/scraper/sources/ecode/__init__.py)
even that function is imported correctly, when i run the python debugger then i faced this error .
