### ISSUE TITLE
SelectorList method __nonzero__ is documented, but not implemented.

### ISSUE THREAD

**Issue by djbirke** [scrapy/scrapy#2660]
[SelectorList method `__nonzero__` in documentation](https://doc.scrapy.org/en/latest/topics/selectors.html#scrapy.selector.SelectorList)

```Python
Python 3.6.0 |Continuum Analytics, Inc.| (default, Dec 23 2016, 12:22:00) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import scrapy
>>> print(scrapy.__version__, dir(scrapy.selector.SelectorList), sep='\n')
1.3.2
['__add__', '__class__', '__contains__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getslice__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__module__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__slots__', '__str__', '__subclasshook__', '__weakref__', 'append', 'clear', 'copy', 'count', 'css', 'extend', 'extract', 'extract_first', 'extract_unquoted', 'index', 'insert', 'pop', 're', 're_first', 'remove', 'reverse', 'select', 'sort', 'x', 'xpath']
```

**Comment by redapple** [comment]
Good catch @djbirke !
Scrapy 0.20 introduced [`scrapy.selector.SelectorList`](https://github.com/scrapy/scrapy/blob/0.20/scrapy/selector/unified.py#L143) but it never had `__nonzero__`, only `scrapy.selector.Selector` had it,
even if [the docs say differently](https://doc.scrapy.org/en/0.20/topics/selectors.html#selectorlist-objects).

Scrapy 0.18 had [`scrapy.selector.XPathSelectorList`](https://doc.scrapy.org/en/0.18/topics/selectors.html#scrapy.selector.XPathSelectorList) which did not have `__nonzero__` either.

**Comment by zinthose** [comment]
I found another reference .
[https://doc.scrapy.org/en/latest/topics/selectors.html#scrapy.selector.Selector.__nonzero__](https://doc.scrapy.org/en/latest/topics/selectors.html#scrapy.selector.Selector.__nonzero__)
