### ISSUE TITLE
Scrapy docs: 'make htmlview' does not open the webbrowser

### ISSUE THREAD

**Issue by harshasrinivas** [scrapy/scrapy#2661]
After compiling the [scrapy documentation](https://github.com/scrapy/scrapy/tree/master/docs), `make htmlview` does not open the web browser.

```py
>>> webbrowser.open('build/html/index.html') # does not work
>>> webbrowser.open('file:///path/to/the/index.html') # works
```

It works when I give the full path to the `build/html/index.html` file.
I have tested this using Python 2.7 and 3.6 on MacOS.

I believe this is an issue specific to MacOS. A minor change to the `webbrowser.open()` command in the `Makefile` should fix this bug. Shall I go ahead and fix this?

**Comment by harshasrinivas** [comment]
Any update on this?

**Comment by redapple** [comment]
hi @harshasrinivas , I have not way to test this.
maybe @kmike, @lopuhin or @stummjr can check (I think they have Macs)

**Comment by stummjr** [comment]
hey @redapple @harshasrinivas. Just tested it on Macos with Python 3.5 and confirmed that `make htmlview` doesn't open a browser window if you don't provide a URL schema.
