### ISSUE TITLE
Getting issue in deploy Scrapy project on Scrapy Cloud 

### ISSUE THREAD

**Issue by rubhanazeem** [scrapy/scrapy#2665]
I am trying to deploy scrapy app on scrapy cloud. But after deploy, Spider is not available to run. After deploy I am getting this status.
{"project": 169397, "version": "f79741f-master", "spiders": 0, "status": "ok"}
On running scrapy list, it is showing spider.

**Comment by redapple** [comment]
@rubhanazeem , I believe this is more of an issues with Scrapinghub's Scrapy Cloud than Scrapy itself.
Have you contacted their support channels?
