### ISSUE TITLE
SplashTextResponse mismatch with HtmlResponse in CrawlerSpider

### ISSUE THREAD

**Issue by SmartAILM** [scrapy/scrapy#2673]
I use splash plugin to render html in CrawlerSpider, but seems the rendered response type is `SplashTextResponse`,  but in CrawlerSpider implementation `_requests_to_follow ` only
allow `HtmlResponse` 
[this is the code link](https://github.com/scrapy/scrapy/blob/master/scrapy/spiders/crawl.py#L57)

So can I just remove the condition?

```
if not isinstance(response, HtmlResponse):
            return
```

**Comment by redapple** [comment]
You can override `def _requests_to_follow(self, response):` and implement it without that check.
I wonder if scrapy-splash could have a `SplashHtmlResponse`, subclassing `HtmlResponse`, for these cases.

**Comment by kmike** [comment]
Yeah, adding SplashHtmlResponse  to Splash makes sense for such cases.

**Comment by atultherajput** [comment]
I had tried to add SplashHtmlResponse in splash. Please check it and guide if anything i am missing.

**Comment by redapple** [comment]
@SmartAILM , I'm closing this issue in favor of https://github.com/scrapy-plugins/scrapy-splash/issues/114
