### ISSUE TITLE
How can I know whether the response is from cache or not

### ISSUE THREAD

**Issue by EadrenKing** [scrapy/scrapy#2679]
How can I know whether the response is from cache or not

**Comment by redapple** [comment]
Responses from cache have the `'cached'` flag, e.g. you can check `'cached' in response.flags`.

**Comment by EadrenKing** [comment]
It works for me. Thanks a lot 😆

**Comment by redapple** [comment]
You're welcome. Happy scraping!

**Comment by eLRuLL** [comment]
@redapple thanks for this, I was wondering the same. Is this documented somewhere?

**Comment by redapple** [comment]
@eLRuLL , not really. I found this mention on [Response.flags](https://doc.scrapy.org/en/latest/topics/request-response.html?#scrapy.http.Response.flags) but that's about it.
