### ISSUE TITLE
Parse HTML Pages with VUE.js templates

### ISSUE THREAD

**Issue by ferasodh** [scrapy/scrapy#2689]
I'm new to scrapy and I tried to scrap some pages that uses VUE.js. When getting response I get html tags with VUE.js placeholders instead of real values. Is there a way to parse the page and get real values? any ideas on this?

Thanks,

**Comment by pawelmhm** [comment]
You need to render javascript. One solution is [scrapy-splash - it integrates Scrapy spiders with headless browser - Splash](https://github.com/scrapy-plugins/scrapy-splash). [Here is nice tutorial](https://blog.scrapinghub.com/2015/03/02/handling-javascript-in-scrapy-with-splash/) about using it.

Sometimes you don't really need to render Javascript. If these vue templates are filled with some data fetched with ajax request it is often enough to just make proper api call get JSON and parse it. this is often easier than rendering full page.

**Comment by redapple** [comment]
Hi @ferasodh , 
I believe your question is more suited for the [scrapy-users mailing list](https://groups.google.com/d/forum/scrapy-users) or StackOverflow
(although what @pawelmhm mentions could have a dedicated section in the docs for users wondering the same)
