### ISSUE TITLE
Invalid JSON output when nothing is crawled

### ISSUE THREAD

**Issue by arvindpdmn** [scrapy/scrapy#2698]
JSON output is okay in normal cases when URLs are crawled. But in some cases, my application logic determines that nothing needs to be crawled. In such a case, a stray `[` appears on the output.

**Comment by kmike** [comment]
What Scrapy version are you using?
It looks similar to an issue fixed a while ago in https://github.com/scrapy/scrapy/pull/2258.

**Comment by arvindpdmn** [comment]
Thx. I was on 1.1.1. Upgraded to 1.3.3. Works.
