### ISSUE TITLE
Incompatible library version: etree.cpython-35m-darwin.so

### ISSUE THREAD

**Issue by bozzmob** [scrapy/scrapy#2703]
I installed scrapy. Tried to run the first sample program from [here](https://doc.scrapy.org/en/latest/intro/overview.html). I am getting the following error every time I run the command.

```
bozzmob$ scrapy runspider quotes-scraper.py -o quotes-output.json
Traceback (most recent call last):
  File "/Users/satjagan/miniconda3/bin/scrapy", line 7, in <module>
    from scrapy.cmdline import execute
  File "/Users/satjagan/miniconda3/lib/python3.5/site-packages/scrapy/__init__.py", line 34, in <module>
    from scrapy.spiders import Spider
  File "/Users/satjagan/miniconda3/lib/python3.5/site-packages/scrapy/spiders/__init__.py", line 10, in <module>
    from scrapy.http import Request
  File "/Users/satjagan/miniconda3/lib/python3.5/site-packages/scrapy/http/__init__.py", line 11, in <module>
    from scrapy.http.request.form import FormRequest
  File "/Users/satjagan/miniconda3/lib/python3.5/site-packages/scrapy/http/request/form.py", line 9, in <module>
    import lxml.html
  File "/Users/satjagan/miniconda3/lib/python3.5/site-packages/lxml/html/__init__.py", line 54, in <module>
    from .. import etree
ImportError: dlopen(/Users/satjagan/miniconda3/lib/python3.5/site-packages/lxml/etree.cpython-35m-darwin.so, 2): Library not loaded: @rpath/libxml2.2.dylib
  Referenced from: /Users/satjagan/miniconda3/lib/python3.5/site-packages/lxml/etree.cpython-35m-darwin.so
  Reason: Incompatible library version: etree.cpython-35m-darwin.so requires version 12.0.0 or later, but libxml2.2.dylib provides version 10.0.0
```

I tried lot of solutions on stackoverflow([one](http://stackoverflow.com/questions/23172384/lxml-runtime-error-reason-incompatible-library-version-etree-so-requires-vers/31607751), [two](http://stackoverflow.com/questions/23172384/lxml-runtime-error-reason-incompatible-library-version-etree-so-requires-vers/31607751), etc.,) and other github issues([one](https://github.com/conda/conda/issues/3355), [two](https://github.com/HazyResearch/snorkel/issues/435), etc.,). None of them helped. Please let me know how to fix this.

**Comment by redapple** [comment]
How did you install scrapy in the first place?

**Comment by bozzmob** [comment]
@redapple I did -
`pip install Scrapy`

BTW, this is on my MAC. Its working fine on my Ubuntu 16.04. But, I surely need it to get it working on my MAC as well.

**Comment by redapple** [comment]
I'm not familiar with installing Scrapy on Mac.
But we do recommend using virtualenv when you use pip,
or use conda-forge channel if you're using Anaconda/Miniconda.
https://docs.scrapy.org/en/latest/intro/install.html#installing-scrapy

**Comment by kmike** [comment]
@bozzmob mixing pip and conda installs can lead to such issues; as Paul said, it is better to either use virtualenv+pip, or use only conda.

**Comment by bozzmob** [comment]
Yes. It was surely an issue of mixing environments. I used conda completely. Followed - [https://anaconda.org/conda-forge/scrapy](https://anaconda.org/conda-forge/scrapy).
This command did the trick-
`conda install -c conda-forge scrapy=1.3.3`
Yes, I'll consider using venv+pip going forward.

Thanks @redapple @kmike 👍
