### ISSUE TITLE
推荐一个Scrapy的项目

### ISSUE THREAD

**Issue by xiyouMc** [scrapy/scrapy#2704]
[源码地址](https://github.com/xiyouMc/PornHubBot)
![](http://115.28.132.58:8080/docs/PornHubPic.png)

**Comment by Ouds** [comment]
老司机

**Comment by redapple** [comment]
Sorry @xiyouMc , GitHub issues is not the place to promote projects built with Scrapy.
You can send a message to the mailing list if you wish.

**Comment by xiyouMc** [comment]
@redapple Ok Sorry
