### ISSUE TITLE
Not able to run Scrapy shell - TypeError

### ISSUE THREAD

**Issue by shashank-sharma** [scrapy/scrapy#2708]
I was following one of your scrapy tutorials and I am stuck with this error. I am not sure what's wrong.

This is the error which i am getting:

```
vipul@shashank:~/Mythical/Scrapy/tutorial$ scrapy shell 'http://quotes.toscrape.com/page/1/'
Traceback (most recent call last):
  File "/usr/local/bin/scrapy", line 7, in <module>
    from scrapy.cmdline import execute
  File "/usr/local/lib/python3.4/dist-packages/scrapy/cmdline.py", line 6, in <module>
    import pkg_resources
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 72, in <module>
    import packaging.requirements
  File "/usr/local/lib/python3.4/dist-packages/packaging/requirements.py", line 59, in <module>
    MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
TypeError: __call__() missing 1 required positional argument: 'name'
vipul@shashank:~/Mythical/Scrapy/tutorial$ python --version
Python 2.7.6
```

**Comment by harshasrinivas** [comment]
@shashank-sharma what version of Scrapy are you using?
`$ scrapy version`

**Comment by shashank-sharma** [comment]
I really have no idea but something is wrong after installing scrapy. After typing scrapy version it's showing the same error again.

```
vipul@shashank:~/Mythical/Scrapy/tutorial/tutorial$ scrapy version
Traceback (most recent call last):
  File "/usr/local/bin/scrapy", line 7, in <module>
    from scrapy.cmdline import execute
  File "/usr/local/lib/python3.4/dist-packages/scrapy/cmdline.py", line 6, in <module>
    import pkg_resources
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 72, in <module>
    import packaging.requirements
  File "/usr/local/lib/python3.4/dist-packages/packaging/requirements.py", line 59, in <module>
    MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
TypeError: __call__() missing 1 required positional argument: 'name'

```

**Comment by harshasrinivas** [comment]
From the logs, it looks like scrapy has been installed as a Python3.4 package.
Why don't you try creating a virtual environment and see if it works?
```sh
python3 -m venv ./env
source env/bin/activate
pip install scrapy
```

**Comment by shashank-sharma** [comment]
I guess i have no choice but to use virtual env. Actually the same thing is happening when I was working with scrapinghub 'shub' commands and there also I was advised to use virtualenv. Still thanks for help, there its working.

**Comment by harshasrinivas** [comment]
This looks like an issue with pip/dependencies. There is a [related stackoverflow discussion here](http://stackoverflow.com/questions/42029545/pip-is-error-typeerror-call-takes-exactly-2-arguments-1-given).

**Comment by shashank-sharma** [comment]
@harshasrinivas Thanks for the source, I was reading that only but still that was also not helpful that much. I just re-installed and I guess now it's working fine.
