### ISSUE TITLE
A spider might still get closed even if it does have scheduled some requests in a `spider_idle` handle

### ISSUE THREAD

**Issue by starrify** [scrapy/scrapy#2709]
Regarding the `spider_idle` signal, [the doc says](https://doc.scrapy.org/en/latest/topics/signals.html#spider-idle):

> If the idle state persists after all handlers of this signal have finished, the engine starts closing the spider. After the spider has finished closing, the spider_closed signal is sent.
> 
> You can, for example, schedule some requests in your `spider_idle` handler to prevent the spider from being closed.

However, the spider may still close even when it has scheduled some requests within a `spider_idle` handler, if all such requests are filtered due to duplication.  
In this case, the engine would still have `self.spider_is_idle(spider)` evaluated to `True` after finishing all `spider_idle` handlers.
[Related code in `scrapy/core/engine.py`](https://github.com/scrapy/scrapy/blob/05ce1296c6a60f23e81af7ec38ac1855e78be79f/scrapy/core/engine.py#L284)

Below is an example illustrating this issue. In this example, one may expect the spider to send three requests, but with the current version of Scrapy (`05ce1296`) there'll be only one request.

```python
# coding: utf8

import scrapy
import scrapy.signals


class TestSpider(scrapy.Spider):

    name = 'test'
    urls = None

    def start_requests(self):
        self.urls = [
            'http://httpbin.org/get?foo=bar',
            'http://httpbin.org/get?bar=baz',
            'http://httpbin.org/get?baz=foo',
            'http://httpbin.org/get?baz=foo',
        ]
        self.crawler.signals.connect(self.on_idle, scrapy.signals.spider_idle)
        return []

    def on_idle(self, spider):
        if self.urls:
            url = self.urls.pop()
            self.crawler.engine.crawl(scrapy.Request(url), self)

    def parse(self, response):
        pass
```
(Save it to `a.py` and use `scrapy runspider a.py` to test.)

My suggestion is to have `ExecutionEngine._spider_idle` updated to make sure the spider does not get closed, as long as there's any request scheduled within a `spider_idle` handler.

**Comment by rolando** [comment]
Doc is missing the reference to `DontCloseSpider`, which is catched only by the `spider_idle` sender.
