### ISSUE TITLE
Cannot select with .css selector or xpath selector?

### ISSUE THREAD

**Issue by kassiansun** [scrapy/scrapy#2716]
### Page
http://libproject.hkbu.edu.hk/was40/search?lang=cht&channelid=47953

### How to Reproduce
Run scrapy shell: `scrapy shell "http://libproject.hkbu.edu.hk/was40/search?lang=cht&channelid=47953"`

Both `xpath('//*[@id="gallery"]/table/tbody/tr[12]/td/table/tbody/tr/td[3]/table/tbody/tr[2]/td/table/tbody/tr/td[4]')` and `css('#gallery > table > tbody > tr:nth-child(20) > td > table > tbody > tr > td:nth-child(3) > table > tbody > tr:nth-child(2) > td > table > tbody > tr > td:nth-child(4)')` will not select the second column of first row(contains `	阿魏<br>Awei`), is this a bug of scrapy?

xpath/css copied from chrome developer tool.

**Comment by kmike** [comment]
I don't think it is a Scrapy bug; DOM tree produced by a browser can be different than a DOM tree in the page source. See e.g. https://docs.scrapy.org/en/latest/topics/firefox.html#caveats-with-inspecting-the-live-browser-dom. I'm not sure Scrapy issue tracker is a right place to debug site-specific selectors, so I'm closing this ticket. You may find help at https://stackoverflow.com (use "scrapy" tag), this is our official support channel.
