### ISSUE TITLE
Crawl AngularJS based website

### ISSUE THREAD

**Issue by anuragmishra1** [scrapy/scrapy#2722]
I am able crawl some pages but some pages are taking time to load because DOM is not fully rendered so that I am not able to crawl it. Can anyone have solution for this?

Thanks in advance

**Comment by tovin07** [comment]
Simple way: Use with selenium web driver 😄

**Comment by Jack-Kingdom** [comment]
How about render page with phantom.js before crawl.

**Comment by crasker** [comment]
how about using https://github.com/scrapy-plugins/scrapy-splash

**Comment by jamiebull1** [comment]
Or figure out what AJAX calls are being made to get the data you're interested in, then just scrape that instead.

**Comment by dungtienmta** [comment]
I was found this problem. Help me. Please !!!

**Comment by redapple** [comment]
@anuragmishra1 , @dungtienmta ,
Scrapy only has an HTTP client and XPath/CSS helpers.
It does not interpret JavaScript code.

You can indeed look at [Splash](https://splash.readthedocs.io/en/stable/) and [scrapy-splash](https://github.com/scrapy-plugins/scrapy-splash) as @crasker suggested.
@jamiebull1 's suggestion of finding out what AJAX calls are made is very common.
I can also refer you to https://stackoverflow.com/questions/8550114/can-scrapy-be-used-to-scrape-dynamic-content-from-websites-that-are-using-ajax

**Comment by kelvingakuo** [comment]
@jamiebull1, say the AJAX call retrieves a json file then renders it. When I make the call directly (as a normal URL) there's an authentication problem, hence will not return the JSON. Any way to circumvent this?

**Comment by VictorHaine** [comment]
@kelvingakuo you need to pack the cookies and query strings into the direct request, as if the user has requested it

https://stackoverflow.com/questions/4981440/scrapy-how-to-manage-cookies-sessions?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

**Comment by kelvingakuo** [comment]
@VictorHaine Thank you. Will definitely come in handy.

I found a way though.

When you do the request from a Scrapy spider, the site returns the JSON as needed

**Comment by mridulsri** [comment]
@anuragmishra1 you can use Selenium with PhantomJS to crawl the JavaScript rendered single page application.

**Comment by joshin2017** [comment]
Add chromesriver.exr in your C:\Windows

1) Store the html files to local drive
driver = webdriver.Chrome()
#URL TO CRAWL
temploc = "https//www:xyz.com" 
#Location to store html file loaded
docfilepath = "D:\Tempfolder\tempfile.txt" 
#All html content will be stored in local device
self.make_folder("D:\Tempfolder\")
driver.get(temploc)
f = codecs.open(docfilepath, "w", "utf-8")
html = driver.page_source
f.write(html)
f.close()

2) Read data from local drive
docfilepath = "D:\Tempfolder\tempfile.txt" 
htmlcontent = self.get_file_contents(docfilepath)
response = HtmlResponse(url=url_to_parse, body=htmlcontent)

#Now you can crawl the response.
			

#Functions to create folder and read file
			
def make_folder(self, foldername):
	#creates folder stucture for foldername
	if not os.path.exists(foldername):
		os.makedirs(foldername)

def get_file_contents(self, doc_name):
	# returns contents of doc_name
	with open(doc_name, "r") as infile:
		return infile.read()

**Comment by joshin2017** [comment]
Add chromedriver.exe in your C:\Windows

1) Store the html files to local drive
driver = webdriver.Chrome()
#URL TO CRAWL
temploc = "https//www:xyz.com" 
#Location to store html file loaded
docfilepath = "D:\Tempfolder\tempfile.txt" 
#All html content will be stored in local device
self.make_folder("D:\Tempfolder\")
driver.get(temploc)
f = codecs.open(docfilepath, "w", "utf-8")
html = driver.page_source
f.write(html)
f.close()

2) Read data from local drive
docfilepath = "D:\Tempfolder\tempfile.txt" 
htmlcontent = h.get_file_contents(docfilepath)
response = HtmlResponse(url=url_to_parse, body=htmlcontent)

#Now you can crawl the response.
			

#Functions to create folder and read file
			
def make_folder(self, foldername):
	#creates folder stucture for foldername
	if not os.path.exists(foldername):
		os.makedirs(foldername)

def get_file_contents(self, doc_name):
	# returns contents of doc_name
	with open(doc_name, "r") as infile:
		return infile.read()
