### ISSUE TITLE
How to scrapy a web with login form in JavaScript?

### ISSUE THREAD

**Issue by wenxzhen** [scrapy/scrapy#2723]
Dear all,

Any idea to do the crawling on a web but need to login first? even worse, we need to provide the verification code before submitting the login form in JavaScript?

```
<form action="" onsubmit="return login();">
	            	<input type="hidden" id="usertype" name="usertype" />
	                    <ul>
	                        <li>
	                           <input type="text" name="typename" id="typename" class="selectBg ac_input" />
	                        </li>
                            </ul>
</form>
```

Thanks,

**Comment by redapple** [comment]
Hi @wenxzhen , please use [StackOverflow](https://stackoverflow.com) (with tag "scrapy") or [scrapy-users](https://groups.google.com/d/forum/scrapy-users) mailing list to ask these how-to questions.
We use GitHub issues for reporting bugs and architecture and feature discussions.
Thank you.
