### ISSUE TITLE
Item Pipeline code

### ISSUE THREAD

**Issue by MalikRumi** [scrapy/scrapy#2725]
I wanted to get a deeper understanding of the inner workings of the Scrapy pipeline. However, when I looked at the github repo, I found file, image, and media pipeline code that talked about network connections and downloads. But the Item Pipeline, as the docs say, is for 

> After an item  has been scraped by a spider, it is sent  to the Item Pipeline which processes it through  several components that are executed sequentially.

Where is _that_ code? Is some of this code not open sourced? I see an issue  #2633
suggesting a base class. Is the entire pipeline implementation wholly up to the programmer? Then why are we required to use process_item()? What about the Item Pipelines setting that sets the sequence in which the components are called? Where is _that_ code and how does it work? What about scoping, state, and variables?

**Comment by redapple** [comment]
Hi @MalikRumi , I guess your question is better suited for [scrapy-users mailing list](https://groups.google.com/d/forum/scrapy-users).
Scrapy is 100% open source.
Some pointers to relevant bits of code:
- the [engine's scraper component calling `process_item`](https://github.com/scrapy/scrapy/blob/eb5d396527c2d63fa6475dfd9b6372a19bce5488/scrapy/core/scraper.py#L186) of the item processor (default class being `scrapy.pipelines.ItemPipelineManager`) when spider middleware chain return an item
- [`ItemPipelineManager` being built like other middleware managers](https://github.com/scrapy/scrapy/blob/129421c7e31b89b9b0f9c5f7d8ae59e47df36091/scrapy/pipelines/__init__.py#L10)
