### ISSUE TITLE
Expose certificate information on HTTPS responses

### ISSUE THREAD

**Issue by alex** [scrapy/scrapy#2726]
For scraper I'm working on, I'd like to have access to the certificate supplied by the server for HTTPS requests. As far as I can tell, this is not currently exposed on either requests or responses.

**Comment by redapple** [comment]
Hey @alex , sorry for the late feedback.
There's a related issue about logging TLS options, cipher suites (https://github.com/scrapy/scrapy/issues/2111)

I haven't really looked into how we could expose that, but it'd probably be somewhere in the [TLS options object](https://github.com/scrapy/scrapy/blob/master/scrapy/core/downloader/tls.py) that we pass to Twisted via [the context factory](https://github.com/scrapy/scrapy/blob/master/scrapy/core/downloader/contextfactory.py#L20).
