### ISSUE TITLE
how can i create png thumbs

### ISSUE THREAD

**Issue by fengfangqian** [scrapy/scrapy#2731]
hi,

     When a document is png pp but the suffix is how to generate png pss thumbnail, and now he unified generated jpg how can I set up to generate png

**Comment by redapple** [comment]
hi @fengfangqian , this does not look like a bug report.
Please use [scrapy-users](https://groups.google.com/d/forum/scrapy-users) or [StackOverflow](https://stackoverflow.com) to ask this kind of troubleshooting question.
Thank you.

**Comment by fengfangqian** [comment]
source like this it is png 
![image](https://cloud.githubusercontent.com/assets/3350372/25846018/d6cb2f92-34e2-11e7-9963-4d4924c10fd0.png)

thumbs like ths it is jpeg  the border is black

![image](https://cloud.githubusercontent.com/assets/3350372/25846076/09f5d354-34e3-11e7-89c8-0deb046a7ed8.png)

how seting is keep the pic type?

**Comment by redapple** [comment]
ImagesPipeline converts to JPEG by default.
Currently, there is no way to change the format of thumbnails to PNG.
But there is this open Pull Request about this: https://github.com/scrapy/scrapy/pull/2471
