### ISSUE TITLE
I can't use the webservice(https://github.com/scrapy-plugins/scrapy-jsonrp)

### ISSUE THREAD

**Issue by swumqw** [scrapy/scrapy#2747]
## Can someone tell me how to use scrapy-jsonrpc?I want to use the webservice to control scrapy.(https://github.com/scrapy-plugins/scrapy-jsonrp) I modified the configuration according to the document, but I could not access http://localhost:6080/crawler....

**a part of "setting.py":**
JSONRPC_ENABLED = True
EXTENSIONS = {
'scrapy_jsonrpc.webservice.WebService': 500,
}

i use python3.5,and scrapy 1.3.2
if you know the problem,could you please answer me?Thank you very much...

**Comment by redapple** [comment]
Hi @swumqw ,  I see you've opened https://github.com/scrapy-plugins/scrapy-jsonrpc/issues/14 .
I'll close this one.
I'm afraid scrapy-jsonrpc is not Python 3 compatible yet.
