### ISSUE TITLE
Can't find the middleware function process_request.

### ISSUE THREAD

**Issue by ramwin** [scrapy/scrapy#2752]
It seems that the middleware function `process_request` had been removed in [documentation](https://doc.scrapy.org/en/latest/topics/spider-middleware.html#writing-your-own-spider-middleware) for the latest `1.4` version scrapy. How can I change the params of a request just before it was sent.

**Comment by ramwin** [comment]
Soryy, I found the download middleware [here](https://doc.scrapy.org/en/latest/topics/downloader-middleware.html#writing-your-own-downloader-middleware)

**Comment by kmike** [comment]
Yeah, it is a downloader middleware method.
