### ISSUE TITLE
MediaPipeline doesn't send request to downloader middleware.

### ISSUE THREAD

**Issue by cdz620** [scrapy/scrapy#2753]
## description
- scrapy version: Scrapy 1.3.3

I have user_agent and ip_proxy downloader middleware. It seem no work When MediaPipeline send request to downloader.

settings.py :
```
DOWNLOADER_MIDDLEWARES = {
    'xxx.middlewares.user_agent.UserAgentPoolMiddleware': 1,
    'xxx.retry.RetryMiddleware': None,
    'xxx.middlewares.retry.RetryMiddleware': 550,
    'xxx.middlewares.ip_proxy.IPProxyMiddleware': 600,
}
```

code :
```
class ImagePipeline(FilesPipeline):
    FILES_URLS_FIELD = "image_urls"
    FILES_RESULT_FIELD = 'images'
    def get_media_requests(self, item, info):
        return [Request(x) for x in item.get(self.files_urls_field, [])]
```

## Question
- Does MediaPipeline data flow not comply with the scrapy general [data flow](https://doc.scrapy.org/en/master/topics/architecture.html)  ？

## ps
 I'm not good at English, I hope I have made it clear.

**Comment by redapple** [comment]
hi @cdz620 ,

> It seem no work When MediaPipeline send request to downloader.

what makes you say that?
what do you see? what did you expect would happen instead?

have you [enabled your media pipeline](https://docs.scrapy.org/en/latest/topics/media-pipeline.html#enabling-your-media-pipeline) with `ITEM_PIPELINES`?
Can you share some crawl logs?

In this sample project, https://github.com/redapple/sample-scrapy-projects/tree/master/imgpipedwnldr ,
you can see a dummy downloader printing logs for each image request: see https://github.com/redapple/sample-scrapy-projects/blob/master/imgpipedwnldr/log.txt
