### ISSUE TITLE
scrapy runspider do not take effect of "custom_settings"

### ISSUE THREAD

**Issue by clouds56** [scrapy/scrapy#2758]
sample code:

```python
# myspider.py
import scrapy

class MySpider(scrapy.Spider):
    custom_settings = {
        'LOG_LEVEL': 'INFO',
        'FEED_FORMAT': 'jsonlines',
    }
    start_urls = ["https://www.example.com"]
    def parse(self, response):
        pass
```

run with `scrapy runspider mysipder.py`, it shows:

> 2017-05-25 23:22:13 [scrapy.utils.log] INFO: Scrapy 1.3.1 started (bot: scrapybot)
2017-05-25 23:22:13 [scrapy.utils.log] INFO: Overridden settings: {}
2017-05-25 23:22:13 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.feedexport.FeedExporter',
 'scrapy.extensions.logstats.LogStats']
2017-05-25 23:22:13 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2017-05-25 23:22:13 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']

notice that in "[scrapy.utils.log] INFO: Overridden settings: {}", the `custom_settings` doesn't take effects.

**Comment by kmike** [comment]
It looks like https://github.com/scrapy/scrapy/issues/1343

**Comment by clouds56** [comment]
Yes, I've run `print('LOG_LEVEL: {}'.format(self.settings.get('LOG_LEVEL')))` it actually print 'INFO', but it still writing 'DEBUG' level log.

> 2017-05-26 01:31:38 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2017-05-26 01:31:38 [scrapy.core.engine] INFO: Spider opened
2017-05-26 01:31:38 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2017-05-26 01:31:39 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.example.com> (referer: None)
LOG_LEVEL: INFO

and when I specify files in custom settings like:

    custom_settings = {
        'LOG_LEVEL': 'INFO',
        'FEED_FORMAT': 'jsonlines',
        'FEED_URI': 'data.jl',
    }

it still just output to the console, no new file created (I've `yield(scrapy.Item)` in the method `parse`)

**Comment by redapple** [comment]
@clouds56 , can you try with Scrapy 1.4.0?
This latest release incluses a fix for logging setting in `custom_settings`.
So `LOG_LEVEL` in custom_settings should now work.
But `FEED_***` should work even for Scrapy 1.3 (I tested with FEED_URI)

**Comment by redapple** [comment]
"Overridden settings" not reflecting custom settings is indeed https://github.com/scrapy/scrapy/issues/1343 as @kmike commented.

**Comment by clouds56** [comment]
thanks, updated to 1.4 and everything works.
