### ISSUE TITLE
Document CloseSpider extension better

### ISSUE THREAD

**Issue by redapple** [scrapy/scrapy#2759]
See https://github.com/scrapy/scrapy/issues/2748#issuecomment-302536094

@kmike 's details:

> When CLOSERSPIDER_ITEMCOUNT limit is reached, Scrapy stops the spider gracefully; it means requests which are currently in the downloader queue (up to CONCURRENT_REQUEST requests) are still processed. This is the expected behavior.

**Comment by redapple** [comment]
Closed via #2777

**Comment by OfirD1** [comment]
> See [#2748 (comment)](https://github.com/scrapy/scrapy/issues/2748#issuecomment-302536094)
> 
> @kmike 's details:
> 
> > When CLOSERSPIDER_ITEMCOUNT limit is reached, Scrapy stops the spider gracefully; it means requests which are currently in the downloader queue (up to CONCURRENT_REQUEST requests) are still processed. This is the expected behavior.

I think it's worth adding the same documentation for `CLOSESPIDER_PAGECOUNT` and `CLOSESPIDER_ERRORCOUNT`. If it were there, I wouldn't have to test it myself to verify :)

**Comment by eLRuLL** [comment]
@OfirD1 yeah I think we should put this part:

>    Requests which  are currently in the downloader queue (up to :setting: `CONCURRENT_REQUESTS` requests) are still processed. 

in a more generic part, as all closing behaviors still continue processing pending requests.

**Comment by Gallaecio** [comment]
@OfirD1 Could you please open a new ticket about it?

**Comment by OfirD1** [comment]
@Gallaecio, you mean open a new issue? or just edit it [here](https://github.com/scrapy/scrapy/edit/2.3/docs/topics/extensions.rst) and hit "propose changes"? I'm not sure what "open a new ticket" is, but I want to learn!

**Comment by Gallaecio** [comment]
Sorry, I meant a new issue.

**Comment by OfirD1** [comment]
Done.

#4836
