### ISSUE TITLE
ERROR: Spider error processing <GET https://blog.scrapinghub.com> (referer: None)

### ISSUE THREAD

**Issue by mazh91** [scrapy/scrapy#2770]
Hello. I'm getting this error after going through the site tutorial:

> 2017-05-31 22:00:38 [scrapy] INFO: Scrapy 1.0.3 started (bot: scrapybot)
> 2017-05-31 22:00:38 [scrapy] INFO: Optional features available: ssl, http11, boto
> 2017-05-31 22:00:38 [scrapy] INFO: Overridden settings: {}
> 2017-05-31 22:00:38 [scrapy] INFO: Enabled extensions: CloseSpider, TelnetConsole, LogStats, CoreStats, SpiderState
> 2017-05-31 22:00:38 [boto] DEBUG: Retrieving credentials from metadata server.
> 2017-05-31 22:00:39 [boto] ERROR: Caught exception reading instance data
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/boto/utils.py", line 210, in retry_url
>     r = opener.open(req, timeout=timeout)
>   File "/usr/lib/python2.7/urllib2.py", line 429, in open
>     response = self._open(req, data)
>   File "/usr/lib/python2.7/urllib2.py", line 447, in _open
>     '_open', req)
>   File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
>     result = func(*args)
>   File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
>     return self.do_open(httplib.HTTPConnection, req)
>   File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
>     raise URLError(err)
> URLError: <urlopen error timed out>
> 2017-05-31 22:00:39 [boto] ERROR: Unable to read instance data, giving up
> 2017-05-31 22:00:39 [scrapy] INFO: Enabled downloader middlewares: HttpAuthMiddleware, DownloadTimeoutMiddleware, UserAgentMiddleware, RetryMiddleware, DefaultHeadersMiddleware, MetaRefreshMiddleware, HttpCompressionMiddleware, RedirectMiddleware, CookiesMiddleware, ChunkedTransferMiddleware, DownloaderStats
> 2017-05-31 22:00:39 [scrapy] INFO: Enabled spider middlewares: HttpErrorMiddleware, OffsiteMiddleware, RefererMiddleware, UrlLengthMiddleware, DepthMiddleware
> 2017-05-31 22:00:39 [scrapy] INFO: Enabled item pipelines: 
> 2017-05-31 22:00:39 [scrapy] INFO: Spider opened
> 2017-05-31 22:00:39 [scrapy] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
> 2017-05-31 22:00:39 [scrapy] DEBUG: Telnet console listening on 127.0.0.1:6023
> 2017-05-31 22:00:40 [scrapy] DEBUG: Crawled (200) <GET https://blog.scrapinghub.com> (referer: None)
> 2017-05-31 22:00:40 [scrapy] DEBUG: Scraped from <200 https://blog.scrapinghub.com>
> {'title': u'Deploy your Scrapy Spiders from GitHub'}
> 2017-05-31 22:00:40 [scrapy] DEBUG: Scraped from <200 https://blog.scrapinghub.com>
> {'title': u'Looking Back at 2016'}
> 2017-05-31 22:00:40 [scrapy] DEBUG: Scraped from <200 https://blog.scrapinghub.com>
> {'title': u'How to Increase Sales with Online Reputation Management'}
> 2017-05-31 22:00:40 [scrapy] DEBUG: Scraped from <200 https://blog.scrapinghub.com>
> {'title': u'How to Build your own Price Monitoring Tool'}
> 2017-05-31 22:00:40 [scrapy] DEBUG: Scraped from <200 https://blog.scrapinghub.com>
> {'title': u'How You Can Use Web Data to Accelerate Your Startup'}
> 2017-05-31 22:00:40 [scrapy] DEBUG: Scraped from <200 https://blog.scrapinghub.com>
> {'title': u'An Introduction to XPath: How to Get Started'}
> 2017-05-31 22:00:40 [scrapy] DEBUG: Scraped from <200 https://blog.scrapinghub.com>
> {'title': u'Why Promoting Open Data Increases Economic Opportunities'}
> 2017-05-31 22:00:40 [scrapy] DEBUG: Scraped from <200 https://blog.scrapinghub.com>
> {'title': u'Interview: How Up Hail uses Scrapy to Increase Transparency'}
> 2017-05-31 22:00:40 [scrapy] DEBUG: Scraped from <200 https://blog.scrapinghub.com>
> {'title': u'How to Run Python Scripts in Scrapy Cloud'}
> 2017-05-31 22:00:40 [scrapy] DEBUG: Scraped from <200 https://blog.scrapinghub.com>
> {'title': u'Embracing the Future of Work: How To Communicate Remotely'}
> 2017-05-31 22:00:40 [scrapy] ERROR: Spider error processing <GET https://blog.scrapinghub.com> (referer: None)
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 102, in iter_errback
>     yield next(it)
>   File "/usr/lib/python2.7/dist-packages/scrapy/spidermiddlewares/offsite.py", line 28, in process_spider_output
>     for x in result:
>   File "/usr/lib/python2.7/dist-packages/scrapy/spidermiddlewares/referer.py", line 22, in <genexpr>
>     return (_set_referer(r) for r in result or ())
>   File "/usr/lib/python2.7/dist-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
>     return (r for r in result or () if _filter(r))
>   File "/usr/lib/python2.7/dist-packages/scrapy/spidermiddlewares/depth.py", line 54, in <genexpr>
>     return (r for r in result or () if _filter(r))
>   File "/home/milad/Desktop/contact_scraper.py", line 13, in parse
>     yield response.follow(next_page, self.parse)
> AttributeError: 'HtmlResponse' object has no attribute 'follow'
> 2017-05-31 22:00:40 [scrapy] INFO: Closing spider (finished)
> 2017-05-31 22:00:40 [scrapy] INFO: Dumping Scrapy stats:
> {'downloader/request_bytes': 218,
>  'downloader/request_count': 1,
>  'downloader/request_method_count/GET': 1,
>  'downloader/response_bytes': 11455,
>  'downloader/response_count': 1,
>  'downloader/response_status_count/200': 1,
>  'finish_reason': 'finished',
>  'finish_time': datetime.datetime(2017, 6, 1, 2, 0, 40, 839833),
>  'item_scraped_count': 10,
>  'log_count/DEBUG': 13,
>  'log_count/ERROR': 3,
>  'log_count/INFO': 7,
>  'response_received_count': 1,
>  'scheduler/dequeued': 1,
>  'scheduler/dequeued/memory': 1,
>  'scheduler/enqueued': 1,
>  'scheduler/enqueued/memory': 1,
>  'spider_exceptions/AttributeError': 1,
>  'start_time': datetime.datetime(2017, 6, 1, 2, 0, 39, 752881)}
> 2017-05-31 22:00:40 [scrapy] INFO: Spider closed (finished)

Here is my source code:
```
import scrapy

class BlogSpider(scrapy.Spider):
    name = 'blogspider'
    start_urls = ['https://blog.scrapinghub.com']

    def parse(self, response):
        for title in response.css('h2.entry-title'):
            yield {'title': title.css('a ::text').extract_first()}

        for next_page in response.css('div.prev-post > a'):
            yield response.follow(next_page, self.parse)
```

I'm using Python 2.7.12 on Linux. Any helpful comments appreciated!

**Comment by aperezalbela** [comment]
Hello @mazh91,

**follow()** method is available in TextResponse (and therefore in HtmlResponse) since Scrapy 1.4 as per https://doc.scrapy.org/en/1.4/news.html#scrapy-1-4-0-2017-05-18

Upgrade and it should work.

**Comment by redapple** [comment]
Hi @mazh91 , as @aperezalbela commented, Scrapy's website example matches the latest Scrapy version, version 1.4.0.
You are using Scrapy 1.0.3. Try and upgrade or stick to the documentation for one of the earlier versions ([1.0](https://doc.scrapy.org/en/1.0/), [1.1](https://doc.scrapy.org/en/1.1/), [1.2](https://doc.scrapy.org/en/1.2/) or [1.3](https://doc.scrapy.org/en/1.3/))
