### ISSUE TITLE
how crawl post url

### ISSUE THREAD

**Issue by fengfangqian** [scrapy/scrapy#2771]
curl -H "Content-Type:application/json" -d '{"body":{"pkgNameList":["com.sinyee.babybus.show"],"sdkVersionCode":0,"oriUrl":"http://xxxxxx"},"head":{"businessId":"test","callbackPara":"callback01","nonce":1804289383,"timestamp":1429951077}}' "http://maapi.3g.qq.com:8080/v1/getAppDetailBatch?output=json&signature=8b259a5eb9d41741a520ce196af5ac86"

how can i crawl like this url

**Comment by redapple** [comment]
Hi @fengfangqian , please use [StackOverflow with tag "scrapy"](https://stackoverflow.com/questions/tagged/scrapy) or [/r/scrapy](https://www.reddit.com/r/scrapy/) for this kind of questions.
Thank you.
