### ISSUE TITLE
crawl the urls for failure

### ISSUE THREAD

**Issue by ChengjinWu** [scrapy/scrapy#2772]
When I crawl this article：
```
<a href="
http://tech.ifeng.com/a/20170526/44626856_0.shtml
" target="_blank">
AlphaGo以一敌五轻松获胜，面对自己时终尝败绩
</a>
```

I will get the wrong urls：
```
http://tech.ifeng.com/%0Ahttp://tech.ifeng.com/a/20170127/44537081_0.shtml%0A%0A%0A%0A
```

**Comment by redapple** [comment]
Hi @ChengjinWu ,
what are you using to follow links? `CrawlSpider` perhaps?
what version of Scrapy are you using?

The recently released Scrapy 1.4.0 has a fix in link extractors to strip leading and trailing whitespace from href attributes.

**Comment by redapple** [comment]
@ChengjinWu , I'm closing this issue as I believe upgrading to scrpay 1.4.0 fixes the issue.
Feel free to re-open if 1.4.0 does not.

**Comment by Hades1996** [comment]
It does indeed fix this issue, thanks for your job.
