### ISSUE TITLE
how can i get index from the parse_detail

### ISSUE THREAD

**Issue by jzfan** [scrapy/scrapy#2776]
I parse a list page, and the details, i got a random data, how can i get them ordered like the list page display? here is my code:
```
def parse(self, response):
    	for url in response.css('.entry-content > ul > li > a::attr(href)').extract():
    	       yield scrapy.Request(url=url, callback=self.parse_details)

def parse_details(self, response):
          yield {
			'entry': response.css('h1.entry-title::text').extract_first(),
			'content': response.css('div.entry-content').extract_first()
		}
```

**Comment by aperezalbela** [comment]
Hello @jzfan,

Have you tried using **priority** parameter in your Request?

See: https://doc.scrapy.org/en/latest/topics/request-response.html?highlight=priority#request-objects

Let me know if that helps

**Comment by redapple** [comment]
@jzfan , your question is better suited for [StackOverflow](https://stackoverflow.com/).
There are a few related questions and answers there already. For example https://stackoverflow.com/questions/33812536/when-scrapy-iterates-through-a-list-of-hrefs-why-are-scraped-items-not-displaye
