### ISSUE TITLE
Do not fire close_spider when using ImagesPipeline 

### ISSUE THREAD

**Issue by Samarpitr** [scrapy/scrapy#2782]
I am downloading the images by using ImagesPipeline and want to fire a script on the closing of the spider but scrapy close_spider not performing the its functionality.

**Comment by redapple** [comment]
@Samarpitr , can you share sample code exhibiting that close_spider is not called?

**Comment by redapple** [comment]
@Samarpitr , do you have any update? did you get it to work?

**Comment by cathalgarvey** [comment]
Hi folks, I'm closing this as it's a little stale and there's no response since. Feel free to reopen if you can provide more information to help us triage and fix. Please confirm, if so, that the issue still affects the most recent version or revision of Scrapy.

Thanks for contributing to Scrapy!
