### ISSUE TITLE
Use Signals API

### ISSUE THREAD

**Issue by Headmaster11** [scrapy/scrapy#2797]
I am not sure, how to user signals API. For example, I have a spider

```
from scrapy.xlib.pydispatch import dispatcher

class PageSpider(CrawlSpider):

    def __init__(self):
        dispatcher.connect(self.spider_closed, signals.spider_closed)
        # some code

    def spider_closed(self, spider):
        # some code
```

And I have a control script 

```
s = get_project_settings()
process = CrawlerProcess(s)
for spider in spider_list:
    process.crawl(spider)
process.start()
```

Can I use SignalManager to catch if spider is closed? Or this is impossible?

**Comment by redapple** [comment]
Hi @Headmaster11 , 
I see that [you also posted to StackOverflow](https://stackoverflow.com/questions/44647816/catch-scrapy-signal-ouside-the-spider). Let's continue there.
