### ISSUE TITLE
Strange errors and freezes (strange connections handling?)

### ISSUE THREAD

**Issue by pythoncontrol** [scrapy/scrapy#2804]
`2017-06-25 18:21:19 [scrapy.downloadermiddlewares.retry] DEBUG: Gave up retrying <GET http://forum.wincenter.pl/> (failed 3 times): Connection was refused by other side: 111: Connection refused.
2017-06-25 18:21:19 [scrapy.core.scraper] ERROR: Error downloading <GET http://forum.wincenter.pl/>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.5/site-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.5/site-packages/scrapy/core/downloader/middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
twisted.internet.error.ConnectionRefusedError: Connection was refused by other side: 111: Connection refused.
`

![image](https://user-images.githubusercontent.com/1059818/27518642-37ed1764-59e5-11e7-83f4-2d338450b59a.png)
![image](https://user-images.githubusercontent.com/1059818/27518655-63b9b2d0-59e5-11e7-8aeb-d8ab0f43446c.png)
![image](https://user-images.githubusercontent.com/1059818/27518671-9fd5a62a-59e5-11e7-81ff-e746b3b738c3.png)
![image](https://user-images.githubusercontent.com/1059818/27518675-ace159d6-59e5-11e7-9861-fcaad9f1a4ad.png)
![image](https://user-images.githubusercontent.com/1059818/27518676-b3e3abee-59e5-11e7-86ca-e2901fa05270.png)

Then scraper freezes for 30seconds - 1 minute and continues to crawl, then, after few websites, other or the same errors happen.
Shouldnt the site be skipped and crawl should continue?

**Comment by redapple** [comment]
> Shouldnt the site be skipped and crawl should continue?

Scrapy's RetryMiddleware is not configured to do that. I tries [`RETRY_TIMES`](https://doc.scrapy.org/en/latest/topics/downloader-middleware.html#std:setting-RETRY_TIMES) for a number of errors, [including ConnectionRefusedError](https://github.com/scrapy/scrapy/blob/532400f993b0518438a6c2c22592876130b6e743/scrapy/downloadermiddlewares/retry.py#L35).
It depends on what you mean by "skip the site", but you can probably customize scrapy's middelware to count these `ConnectionRefusedError` in OffsiteMiddleware (I haven't checked if it's easy to do) and add the domain to the blacklist.

**Comment by pythoncontrol** [comment]
Thank you, missconfiguration.
