### ISSUE TITLE
Issue with Scrapy Install

### ISSUE THREAD

**Issue by tsgoud69** [scrapy/scrapy#2810]
Hi,
I am new to python and trying to install scrapy in my virtual env. But its fails with following error. Can any one susggest what is the issue?

python --version
Python 2.7.13

 virtualenv --version
15.1.0

 pip install scrapy
Collecting scrapy
  Using cached Scrapy-1.4.0-py2.py3-none-any.whl
Collecting service-identity (from scrapy)
  Using cached service_identity-17.0.0-py2.py3-none-any.whl
Collecting parsel>=1.1 (from scrapy)
  Downloading parsel-1.2.0-py2.py3-none-any.whl
Requirement already satisfied: six>=1.5.2 in /home/swaraj/E2/VenvP27E1/lib/python2.7/site-packages (from scrapy)
Collecting w3lib>=1.17.0 (from scrapy)
  Downloading w3lib-1.17.0-py2.py3-none-any.whl
Collecting lxml (from scrapy)
  Downloading lxml-3.8.0-cp27-cp27m-manylinux1_x86_64.whl (6.8MB)
    100% |████████████████████████████████| 6.8MB 172kB/s 
Collecting Twisted>=13.1.0 (from scrapy)
  Could not find a version that satisfies the requirement Twisted>=13.1.0 (from scrapy) (from versions: )
No matching distribution found for Twisted>=13.1.0 (from scrapy)

**Comment by kmike** [comment]
It looks like a manifestation of http://twistedmatrix.com/trac/ticket/9046. 

You can e.g. download twisted.tar.bz2 file from https://pypi.python.org/pypi/Twisted, unpack it and install from a local folder.

**Comment by redapple** [comment]
@tsgoud69 , did you manage to install scapy?

**Comment by iahmed16** [comment]
@kmike I installed it manually as you said, but I have requirements.txt with klein==17.10.0 ... so I get the same error as klein depends on Twisted.

and at the same time I downloaded Twisted 18.7.0 and installed successfully.

how to get rid of this error
