### ISSUE TITLE
Invalid Hostname when "_" in domain

### ISSUE THREAD

**Issue by ghost** [scrapy/scrapy#2815]
`2017-07-04 16:25:43 [scrapy.core.scraper] ERROR: Error downloading <GET http://wodnik_forum.orq.pl/>
Traceback (most recent call last):
  File "c:\users\bukowa\vritualenv2\lib\site-packages\twisted\internet\defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "c:\users\bukowa\vritualenv2\lib\site-packages\twisted\python\failure.py", line 393, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "c:\users\bukowa\vritualenv2\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
ValueError: invalid hostname: www.bg_2014.team360.pl`

ValueError: invalid hostname: www.bg_2014.team360.pl
ValueError: invalid hostname: www.wolfs_rain.wxv.pl
ValueError: invalid hostname: wodnik_forum.orq.pl
ValueError: invalid hostname: kolo_pzw_miejskie_konskie.wedkuje.pl
ValueError: invalid hostname: bieganie_swiebo.e-fora.pl
ValueError: invalid hostname: rzymskie_koloseum.lovetotravel.pl
ValueError: invalid hostname: zbuntowana_anielica.story.gala.pl
ValueError: invalid hostname: forum_origami.bo.pl
ValueError: invalid hostname: dfk_forum.gbbsoft.pl
ValueError: invalid hostname: wodnik_forum.orq.pl

**Comment by pythoncontrol** [comment]
https://github.com/kjd/idna/issues/50#issuecomment-312908539

**Comment by redapple** [comment]
@pythoncontrol , and yet `curl` and Chrome are able to connect to https://sloneczne_stablowice.forumoteka.pl/kategoria,4,mieszkancy-luzne-rozmowy.html for example.
I'll keep the issue open.

**Comment by MAsifOfficial** [comment]
@redapple The given issue is with the package [Twisted](https://github.com/twisted/twisted), not with Scrapy. So it's not possible to solve it here. But maybe fix it in Twisted instead. So I'd say this issue is invalid for this repo.

**Comment by redapple** [comment]
@MAsifOfficial true, but Scrapy also [customizes its context](https://github.com/scrapy/scrapy/blob/45f19021a5acc69fca6d2a7da2fffe39f10463a1/scrapy/core/downloader/tls.py#L52) when using Twisted Agent, so it may be possible to circumvent the strictness of Twisted (who may not want to relax this behavior in their codebase). I haven't looked if it would be possible or not though.

**Comment by MAsifOfficial** [comment]
I've looked into the code with a bird eye view, & I guess it's not possible. But you should also consider it.

**Comment by leinue** [comment]
same problem

**Comment by leinue** [comment]
@MalikRumi yes it is

**Comment by kmike** [comment]
Let's track this issue at #3321.
