### ISSUE TITLE
Downloader middleware not being loaded

### ISSUE THREAD

**Issue by ocelot2123** [scrapy/scrapy#2817]
from https://stackoverflow.com/questions/44939830/scrapy-downloader-middleware-not-being-loaded

Not sure if this is a problem on my end or on scrapy's end but I can't figure out what is causing this because everything else is being loaded properly

**Comment by redapple** [comment]
hi @ocelot2123 , see my answer on StackOverflow.
I believed you misnamed the setting: it should be `DOWNLOADER_MIDDLEWARES`
