### ISSUE TITLE
How to use the Rule in CrawlSpider to track the response that Splash returns

### ISSUE THREAD

**Issue by thsheep** [scrapy/scrapy#2820]
I would like to use Rule to track the Splash rendering Response!
But using SplashRequest, Rule does not take effect.
Then use the rule of the process_request, re-set the Request object URL, written into the Splash HTTP API request.

`class MySpider(CrawlSpider):

    name = 'innda'

    def start_requests(self):
        yield Request(url)
        

    rules = (
        Rule(LinkExtractor(allow=('node_\d+\.htm',)), process_request='splash_request', follow=True),
        Rule(LinkExtractor(allow=('content_\d+\.htm',)), callback="one_parse")
    )

    def splash_request(self, request):
        request = request.replace(url=RENDER_HTML_URL + request.url)
        return request
`
But the relative path URL is replaced by the Splash url.

What is the solution

**Comment by thsheep** [comment]
@redapple

**Comment by thsheep** [comment]
I am using this way now and it looks like no problem.

`class MySpider(CrawlSpider):

    name = 'innda'

    def start_requests(self):
        yield SplashRequest(url, dont_process_response=True, args={'wait': 10}, meta={'real_url': url})

    rules = (
        # Rule(LinkExtractor(allow=('node_\d+\.htm',)), follow=True),
        Rule(LinkExtractor(allow=('node_\d+\.htm',)), process_request='splash_request', follow=True),
        Rule(LinkExtractor(allow=('content_\d+\.htm',)), callback="one_parse")
    )


    def splash_request(self, request):
        # request = request.replace(url=RENDER_HTML_URL + request.url)
        request.meta['real_url'] = request.url
        return request

    def _requests_to_follow(self, response):
        if not isinstance(response, HtmlResponse):
            return
        seen = set()
        newresponse = response.replace(url=response.meta.get('real_url'))
        for n, rule in enumerate(self._rules):
            links = [lnk for lnk in rule.link_extractor.extract_links(newresponse)
                     if lnk not in seen]
            if links and rule.process_links:
                links = rule.process_links(links)
            for link in links:
                seen.add(link)
                r = self._build_request(n, link)
                yield rule.process_request(r)`

**Comment by redapple** [comment]
What about converting doing something like this?
```
def splash_request(self, request):
    return SplashRequest(url=request.url, args={'wait': 10}, meta={'real_url': url})
```
Why are you setting `dont_process_response=True`?

**Comment by thsheep** [comment]
@redapple
Because dont_process_response = Falses, Response is SplashTextResponse
![qq20170711-230545](https://user-images.githubusercontent.com/13295079/28075238-7821bd62-668d-11e7-9d1d-2466cc9e11be.png)

But in the def_requests_to_follow (self, response), function check the type of Response

`    def _requests_to_follow(self, response):
        if isinstance(response, HtmlResponse):
            return`
Not HtmlResponse type, will not proceed to the next step

dont_process_response = True, the return will be HTMLResponse
![image](https://user-images.githubusercontent.com/13295079/28075480-31e83046-668e-11e7-9d35-0ee18c398bdf.png)

**Comment by thsheep** [comment]
@redapple thank you very much! Your method is very easy to use, I always think that can only return a Request object.

**Comment by redapple** [comment]
Alright, the response type check is related to https://github.com/scrapy/scrapy/issues/2673 . 
You can follow https://github.com/scrapy-plugins/scrapy-splash/pull/115

**Comment by thsheep** [comment]
以下参考：

需要重写_requests_to_follow函数的类型检查：
`    def _requests_to_follow(self, response):
        if not isinstance(response, HtmlResponse):
            return`
去掉类型限制，即可使用：
`class MySpider(CrawlSpider):

    name = 'innda'

    def start_requests(self):
        yield SplashRequest(url, args={'wait': 0.5}, meta={'real_url': url})
        # yield Request(url)
    rules = (
        # Rule(LinkExtractor(allow=('node_\d+\.htm',)), callback="one_parse", follow=True),
        Rule(LinkExtractor(allow=('node_\d+\.htm',)), process_request='splash_request', follow=True),
        Rule(LinkExtractor(allow=('content_\d+\.htm',)), callback="one_parse")
    )

    def splash_request(self, request):
        return SplashRequest(url=request.url, args={'wait': 0.5}, meta={'real_url': request.url})`

或者
`class MySpider(CrawlSpider):

    name = 'innda'

    def start_requests(self):
        yield SplashRequest(url, dont_process_response=True, args={'wait': 0.5}, meta={'real_url': url})
        # yield Request(url)
    rules = (
        Rule(LinkExtractor(allow=('node_\d+\.htm',)), process_request='splash_request', follow=True),
        Rule(LinkExtractor(allow=('content_\d+\.htm',)), callback="one_parse")
    )

    def splash_request(self, request):
        return SplashRequest(url=request.url, dont_process_response=True, args={'wait': 0.5}, meta={'real_url': request.url})

    def _requests_to_follow(self, response):
        if not isinstance(response, HtmlResponse):
            return
        seen = set()
        newresponse = response.replace(url=response.meta.get('real_url'))
        for n, rule in enumerate(self._rules):
            links = [lnk for lnk in rule.link_extractor.extract_links(newresponse)
                     if lnk not in seen]
            if links and rule.process_links:
                links = rule.process_links(links)
            for link in links:
                seen.add(link)
                r = self._build_request(n, link)
                yield rule.process_request(r)`

以上方法适用于我的问题。

**Comment by redapple** [comment]
@thsheep , sorry, I don't understand Chinese. Please write in English.

**Comment by thsheep** [comment]
@redapple
This is my own a solution to the same problem people left to be a reference.

The easiest solution is to remove the type of check,

Or use the passed real_url to change the URL of the Response.

Do not know if there is any hidden problem.

But I tested my project to work properly.

**Comment by thsheep** [comment]
fix #24

**Comment by thsheep** [comment]
fix #24

**Comment by janwendt** [comment]
If someone runs into the same problem who needs Splash in a CrawlSpider (with Rule and LinkExtractor) both on parse_item and initial start_requests that is the solution:
```
import scrapy
from scrapy.spiders import CrawlSpider, Rule
from scrapy.linkextractors import LinkExtractor
from scrapy_splash import SplashRequest, SplashJsonResponse, SplashTextResponse
from scrapy.http import HtmlResponse

class Abc(scrapy.Item):
    name = scrapy.Field()

class AbcSpider(CrawlSpider):
    name = "abc"
    allowed_domains = ['abc.de']
    start_urls = ['https://www.abc.com/xyz']

    rules = (Rule(LinkExtractor(restrict_xpaths='//h2[@class="abc"]'), callback='parse_item', process_request="use_splash"))

    def start_requests(self):        
        for url in self.start_urls:
            yield SplashRequest(url, args={'wait': 15}, meta={'real_url': url})

    def use_splash(self, request):
        request.meta['splash'] = {
                'endpoint':'render.html',
                'args':{
                    'wait': 15,
                    }
                }
        return request

    def _requests_to_follow(self, response):
        if not isinstance(
                response,
                (HtmlResponse, SplashJsonResponse, SplashTextResponse)):
            return
        seen = set()
        for n, rule in enumerate(self._rules):
            links = [lnk for lnk in rule.link_extractor.extract_links(response)
                     if lnk not in seen]
            if links and rule.process_links:
                links = rule.process_links(links)
            for link in links:
                seen.add(link)
                r = self._build_request(n, link)
                yield rule.process_request(r)

    def parse_item(self, response):
        item = Restaurant()
        item['name'] = response.xpath('//div[@class="abc-name"]/h1/text()').get()
        return item
```

**Comment by nimbus2300** [comment]
@janwendt Thank you for that solution, works a treat!

> If someone runs into the same problem needing to use Splash in a CrawlSpider (with Rule and LinkExtractor) BOTH for parse_item and the initial start_requests that's my solution:
> 
> ```python
> import scrapy
> from scrapy.spiders import CrawlSpider, Rule
> from scrapy.linkextractors import LinkExtractor
> from scrapy_splash import SplashRequest, SplashJsonResponse, SplashTextResponse
> from scrapy.http import HtmlResponse
> 
> class Abc(scrapy.Item):
>     name = scrapy.Field()
> 
> class AbcSpider(CrawlSpider):
>     name = "abc"
>     allowed_domains = ['abc.de']
>     start_urls = ['https://www.abc.com/xyz']
> 
>     rules = (Rule(LinkExtractor(restrict_xpaths='//h2[@class="abc"]'), callback='parse_item', process_request="use_splash"))
> 
>     def start_requests(self):        
>         for url in self.start_urls:
>             yield SplashRequest(url, args={'wait': 15}, meta={'real_url': url})
> 
>     def use_splash(self, request):
>         request.meta['splash'] = {
>                 'endpoint':'render.html',
>                 'args':{
>                     'wait': 15,
>                     }
>                 }
>         return request
> 
>     def _requests_to_follow(self, response):
>         if not isinstance(
>                 response,
>                 (HtmlResponse, SplashJsonResponse, SplashTextResponse)):
>             return
>         seen = set()
>         for n, rule in enumerate(self._rules):
>             links = [lnk for lnk in rule.link_extractor.extract_links(response)
>                      if lnk not in seen]
>             if links and rule.process_links:
>                 links = rule.process_links(links)
>             for link in links:
>                 seen.add(link)
>                 r = self._build_request(n, link)
>                 yield rule.process_request(r)
> 
>     def parse_item(self, response):
>         item = Abc()
>         item['name'] = response.xpath('//div[@class="abc-name"]/h1/text()').get()
>         return item
> ```
