### ISSUE TITLE
DOC python 3 compatible module for memory profiling

### ISSUE THREAD

**Issue by lopuhin** [scrapy/scrapy#2824]
Guppy (mentioned here https://doc.scrapy.org/en/latest/topics/leaks.html) is python 2 only AFAIK, so it would be nice to provide a python 3 compatible alternative, e.g. pympler.readthedocs.io

**Comment by redapple** [comment]
Great idea to have a Py2/Py3 solution.
What's your experience with pympler (if any) debugging memory leaks in Scrapy?

**Comment by lopuhin** [comment]
For me it worked just as well as guppy did in the past - I inspected the heap, it showed which objects took a lot of space, then followed referenced backwards to the object in the media pipeline that was keeping them - the hardest problem was reproducing the leak because it was very slow.

**Comment by Gallaecio** [comment]
Fixed by #3284
