### ISSUE TITLE
i beg you please remove the error

### ISSUE THREAD

**Issue by BrandedAlok** [scrapy/scrapy#2829]
NameError                                 Traceback (most recent call last)
<ipython-input-7-d586adc770c4> in <module>()
      6 from scrapy.utils.misc import  arg_to_iter
      7 
----> 8 logger = logging.getLogger(__name__)
      9 
     10 

NameError: name 'logging' is not defined

**Comment by redapple** [comment]
Hi @BrandedAlok , we try and keep GitHub issues for bug reports (and design or feature discussions)
Troubleshooting questions should be posted to either [Stackoverflow](https://stackoverflow.com/) (with tag "scrapy") or [/r/scrapy](https://www.reddit.com/r/scrapy/).

**Comment by BrandedAlok** [comment]
but this is your project so please help me dear sir please i touch your feet
