### ISSUE TITLE
how to run the project please tell 

### ISSUE THREAD

**Issue by BrandedAlok** [scrapy/scrapy#2830]
i am just copying the code to jupyter notebook and then nothing is happening

**Comment by ianhhhhhhhhe** [comment]
Please read [documentation](https://doc.scrapy.org/en/latest/) before asking questions. The [tutorial](https://doc.scrapy.org/en/latest/intro/tutorial.html) part is for new users like you.

And this place is for issues, not for teaching

**Comment by redapple** [comment]
Hi @BrandedAlok , as @ianhhhhhhhhe commented, we try and keep GitHub issues for bug reports (and design or feature discussions)
Troubleshooting questions should be posted to either [Stackoverflow](https://stackoverflow.com/) (with tag "scrapy") or [/r/scrapy](https://www.reddit.com/r/scrapy/).
