### ISSUE TITLE
spider.logger not working in ProjectPipeline.open_spider(self, spider)

### ISSUE THREAD

**Issue by aidiss** [scrapy/scrapy#2832]
The logs are not there when I try to print them.
spider.logger it works fine when called in process_item or close_spider methods.
Any clues?

**Comment by redapple** [comment]
@aidiss , we try and keep GitHub issues for bug reports and feature/design discussions.
Please ask your question on [/r/scrapy](https://www.reddit.com/r/scrapy/) or [StackOverflow](https://stackoverflow.com/questions/tagged/scrapy) (use tag "scrapy") instead.
Thanks.
