### ISSUE TITLE
telnet console abnormal

### ISSUE THREAD

**Issue by wangtua1** [scrapy/scrapy#2833]
when I typed ‘’telnet localhost 6023‘’,it replies like this "escape chararctor is ']'", and the program itself stops crawling data from the web.I can't figure out what is the matter.

**Comment by redapple** [comment]
@canshishengyang , can you share the output of `scrapy version -v`?
It will tell us which version of Scrapy and Twisted you are using, and also the Python version you use.

> and the program itself stops crawling data from the web.

could you share the console logs of your crawl when this happens?

**Comment by canshishengyang** [comment]
Scrapy    : 1.3.3
lxml      : 3.8.0.0
libxml2   : 2.7.8
cssselect : 1.0.1
parsel    : 1.2.0
w3lib     : 1.17.0
Twisted   : 17.1.0
Python    : 2.7.6 (default, Jun 22 2015, 18:00:18) - [GCC 4.8.2]
pyOpenSSL : 17.0.0 (OpenSSL 1.0.1 14 Mar 2012)
Platform  : Linux-3.5.0-23-generic-i686-with-Ubuntu-12.04-precise

When this happens,the logger doesn't print anything. But when you ```ps -ef```，the process is still running

**Comment by redapple** [comment]
@canshishengyang , you don't have scrapy crawl console logs?
Note that we don't test scrapy against Ubuntu 12.04. From Scrapy 1.2, we test against Debian 8 Jessie package versions.

**Comment by Gallaecio** [comment]
@wangtua1 Can you still reproduce this issue?

**Comment by Gallaecio** [comment]
Closing due to a lack of feedback.
