### ISSUE TITLE
Root log not logging to file after updating from 1.2 to 1.4

### ISSUE THREAD

**Issue by tonyyherb** [scrapy/scrapy#2834]
I have 

    d = {
            'LOG_LEVEL': logging.DEBUG,
            'LOG_FORMAT': '%(levelname)s %(asctime)s %(name)s: %(message)s',
            'LOG_FILE': 'scrapyroot'
    }
    configure_logging(d)

I am using CrawlerRunner(get_project_settings()) to run spiders. The setting above used to log the scrapy root logs to file 'scrapyroot'. 
After updating to 1.4, scrapy root logs are printed to console; the file  'scrapyroot' is created but empty.

**Comment by redapple** [comment]
@tonyyherb , so that the issue can be reproduced, can you provide a self-contained script using `CrawlerRunner` -- and your custom logging setup -- that is behaving differently in scrapy 1.2 and scrapy 1.4? Thanks.

**Comment by redapple** [comment]
@tonyyherb , do you have any feedback for us?

**Comment by Xusen93** [comment]
I got a similar problem, and avoided it by using this:
```
settings = {'LOG_FILE' : 'log.log'}
runner = CrawlerRunner(log_settings)
```
Honestly, I could not really understand the `logging` module. 😅

**Comment by cathalgarvey** [comment]
Hi folks, I'm closing this as it's a bit stale, and we don't have the information/reproducible code we need to triage and fix it. Feel free to reopen or comment here if you still need attention on this. Please confirm that the issue still affects the most recent version and/or revision of Scrapy, if you do.

Thanks!
