### ISSUE TITLE
crawler.engine.slot's rapid reduction

### ISSUE THREAD

**Issue by FantasRu** [scrapy/scrapy#2839]
Hi, there.I am in trouble when trying scrapy, I hope you can help me.

```
Scrapy (1.4.0)
scrapy-redis (0.6.8)
```

I set `CONCURRENT_REQUESTS=200`.And when it run, I use `telnet` to find `len(crawler.engine.slot.inprogress)=134`.
I guess this may be related to the memory(but my memory is a lot of surplus).Can someone explain this?Thanks.

Then, when it has being running for a while(about one hour).I find the`len(crawler.engine.slot.inprogress)=80`.I read the document and get that is beacuse `python memory management`.

But how can i solve this?Because its reduction affected the crawler rate.

---

Here is my thought:
Add an extensions: When the number drops to the half, call `CrawlerProcess()._graceful_stop_reactor`.And use `supervisor` restart it.

Is there any other solutions?

**Comment by FantasRu** [comment]
After my try, I found out is's because my redis `dupefilter set`.When i disabled this `RFPDupeFilter`, scrapy work without any problems.But why is this?

**Comment by FantasRu** [comment]
BTW. Can you explain why my slot can not reach the set value in `settings.py`.Whether it depends on spider complexity?

**Comment by redapple** [comment]
Hi @FantasRu , we try and keep GitHub issues for bug reports (and design or feature discussions)
Troubleshooting questions should be posted to either [Stackoverflow](https://stackoverflow.com/) (with tag "scrapy") or [/r/scrapy](https://www.reddit.com/r/scrapy/).
To continue your investigation, note that `CONCURRENT_REQUESTS` is a max value, not a min value. And `CONCURRENT_REQUESTS_PER_DOMAIN` is another setting that can limit request concurrency.
Concurrency is influenced by other factors too, like autothrottling.
