### ISSUE TITLE
Iterate `Selector` with index

### ISSUE THREAD

**Issue by iShawnWang** [scrapy/scrapy#2840]
I try to iterate with `Selector`, and i wan't index within the loop : 
```
    def parseTopicTable(self, response):
        table = response.xpath('//*[@id="Main"]/div[2]')
        cells = table.xpath('//div[@class="cell item"]')
        for cell in cells:
            yield self.parseTopic(cell, `i need index here`)
```

and i try this, but i got an error

```
        for index, cell in cells:
            yield self.parseTopic(cell, index)  # got error here ~
```

so what's the right way to get index when loop the `Selector`

**Comment by redapple** [comment]
hi @iShawnWang , 
we try and keep GitHub issues for bug reports (and design or feature discussions)
Troubleshooting questions should be posted to either [Stackoverflow](https://stackoverflow.com/) (with tag "scrapy") or [/r/scrapy](https://www.reddit.com/r/scrapy/).
