### ISSUE TITLE
XMLFeedSpider iternodes iterator does not work on XML document with namespace

### ISSUE THREAD

**Issue by redapple** [scrapy/scrapy#2842]
(Opening the issue so that we track it, although it is already known.)

**Sample input document:**
```
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<url><loc>http://www.argos.ie/static/Product/partNumber/2353030.htm</loc></url>
<url><loc>http://www.argos.ie/static/Product/partNumber/2717339.htm</loc></url>
(...)
```

**Symptom:**
With Scrapy 1.4.0 (and earlier for sure)
Using `XMLFeedSpider` and the default `iternodes` iterator, nodes using `itertag='loc'` cannot be found, 

```
    (...) site-packages/scrapy/utils/iterators.py", line 31, in xmliter
        yield Selector(text=nodetext, type='xml').xpath('//' + nodename)[0]
    exceptions.IndexError: list index out of range
```

and registering namespaces and using `itertag='prefix:loc'` does not work either.

Recently seen (again) [on StackOverflow](https://stackoverflow.com/questions/45195861/how-to-extract-urls-from-an-xml-using-scrapy-xmlfeedspider).
Was already discussed [on scrapy-users](https://groups.google.com/d/topic/scrapy-users/VN6409UHexQ/discussion).

There's a WIP PR #861. Last comments were about moving to iterparse-based implementation

**Comment by kigsmtua** [comment]
@redapple  i will be having a go at his

**Comment by yurtesen** [comment]
I am having exactly the same issue but you can use [SitemapSpider](https://doc.scrapy.org/en/latest/topics/spiders.html) for your specific case.

**Comment by forrestlmj** [comment]
same issue here

**Comment by Gallaecio** [comment]
When parsing sitemaps in the past, I remember having to [register a namespace](https://parsel.readthedocs.io/en/latest/usage.html#selector-examples-xml) and use it in my XPath. Have you tried using the [XMLFeedSpider.namespace](https://doc.scrapy.org/en/latest/topics/spiders.html#scrapy.spiders.XMLFeedSpider.namespaces) property?

**Comment by Gallaecio** [comment]
https://stackoverflow.com/a/45198604/939364 covers the current workaround.

**Comment by Gallaecio** [comment]
It needs to be confirmed, but https://github.com/scrapy/scrapy/pull/4746 might have fixed this.

**Comment by Gallaecio** [comment]
Yeap, this should be fixed now, `itertag='prefix:loc'` should work.
