### ISSUE TITLE
Redirect 308 missing

### ISSUE THREAD

**Issue by maugch** [scrapy/scrapy#2844]
I did a check on the RedirectMiddleware and noticed that code 308 is missing. Is there a reason for that?
Some websites don't update their sitemap and have a long list of 308 from http to https.

(side note: is there a way to add "s" before a link is scraped?)

**Comment by redapple** [comment]
Interestingly enough, HTTP 308 is tested [in HTTP cache extension](https://github.com/scrapy/scrapy/blob/dd5ab6c5fe54b3d64cdbf89fcfa2b333cd90f22f/scrapy/extensions/httpcache.py#L90).
