### ISSUE TITLE
[idea] Add some non-standard but commonly used HTTP status codes for retrying

### ISSUE THREAD

**Issue by starrify** [scrapy/scrapy#2851]
Cloudflare is being used widely, which has has introduced its non-standard HTTP status codes. E.g.

- [Error 522: Connection timed out](https://support.cloudflare.com/hc/en-us/articles/200171906-Error-522-Connection-timed-out)
- [Error 524: A timeout occurred](https://support.cloudflare.com/hc/en-us/articles/200171926-Error-524-A-timeout-occurred)

In practice, I've seen several occurrences of 522 and/or 524 status codes generated by Cloudflare. Usually a user may simply override setting `RETRY_HTTP_CODES` to include these values.  
Here I suppose it might be good to include these two codes into `scrapy.settings.default_settings.RETRY_HTTP_CODES`.

See also:

- [List of Croudflare error codes](https://support.cloudflare.com/hc/en-us/sections/200820298-Error-Pages)
- [List of HTTP status codes (Wikipedia) -> Unofficial codes -> Cloudflare](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#Cloudflare)

**Comment by redapple** [comment]
Sounds fine @starrify

**Comment by dangra** [comment]
fixed by #2852
