### ISSUE TITLE
SitemapSpider support rel="alternate" works not as expected

### ISSUE THREAD

**Issue by jenya** [scrapy/scrapy#2853]
This functionality was added here: https://github.com/scrapy/scrapy/issues/360
According to this https://github.com/scrapy/scrapy/blob/master/scrapy/spiders/sitemap.py#L46 `sitemap_alternate_links` used for sitemap type `sitemapindex`, but not `urlset`, which is common use case for `rel="alternate"`.
I don't think this is as expected, because that issue, docs and tests (which in fact tests xml parser, but not sitemap parser) in PR talks about `urlset`.
Please correct me if I'm wrong. Otherwise - I will prepare PR.

**Comment by redapple** [comment]
Hi @jenya , do you have an example website for which `SitemapSpider` does not collect alternate URLs as you would expect?
As far as I can see, https://github.com/scrapy/scrapy/blob/master/tests/test_utils_sitemap.py does tests the sitemap body parser, and collects alternates when supplied the example body from #360

**Comment by jenya** [comment]
@redapple even that xml from https://github.com/scrapy/scrapy/issues/360
My initial message about test was incorrect - as it tests `Sitemap`, but not `SitemapSpider`. There is no issue in `Sitemap`, it's an issue in `SitemapSpider` in `_parse_sitemap` method.

Here is sample spider: https://gist.github.com/jenya/4e5277d74f435699d3ce2aea0b40f3ce
It should follow english version of pages, which is not main in sitemap.

**Comment by redapple** [comment]
You're right @jenya . I hadn't noticed the local filtering with iterloc.
Feel free to open an PR. Appreciated!

**Comment by redapple** [comment]
Fixed via https://github.com/scrapy/scrapy/pull/2854
