### ISSUE TITLE
High amount of Request to add per parsed page blocks

### ISSUE THREAD

**Issue by wpxgit** [scrapy/scrapy#2861]
I've a crawl where every subpage has 300+ links on it.
It slows down after a minute or so / sometimes it crawls 0 pages / min.

I've configured 10 concurrent_requests and 10 processed items. That means up to 3.000 yields per 10 processed items...

As far as i can see the parse function takes 70+ seconds per page.
That long time results from yielding these 300+ links and each of the links seems to wait until the engine? or something similar has done one task and is ready to process the new yield request?
Adding the requests to scheduler don't take long so it seems to me that the yield is waiting for something other.

Any hints?
- Is it possible to yield the requests in bulk instead of yielding each on its own.
- Is it possible to add them to scheduler without yielding them?

Thanks!

**Comment by redapple** [comment]
We try and keep GitHub issues for bug reports (and design or feature discussions)
Troubleshooting questions should be posted to either [Stackoverflow](https://stackoverflow.com/) (with tag "scrapy") or [/r/scrapy](https://www.reddit.com/r/scrapy/).
Without seeing spider code and logs, it's really difficult to guess what might be happening.
Check Autothrottle settings for example.
Does it change the speed if you only crawl without yielding items (only yielding requests).
These are the things you can try.

**Comment by wpxgit** [comment]
Thanks for feedback, poster on stackoverflow with additional information:
https://stackoverflow.com/questions/45374181/high-amount-of-request-to-add-per-parsed-page-blocks-crawling

I'm not sure if it perhaps make sense to add a bulk yield request option if not exist at the moment (as feature...)
