### ISSUE TITLE
DeprecationWarning: inspect.getargspec()

### ISSUE THREAD

**Issue by andreip** [scrapy/scrapy#2862]
Hi,

I've tried searching for a similar problem but couldn't find a discussion in scrapy about it, so starting one.

```bash
build  │   func_args, _, _, _ = inspect.getargspec(func)
build  │ /usr/local/lib/python3.6/site-packages/scrapy/utils/python.py:201: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
```

We've stumbled into this log a LOT, actually getting spammed by it currently when we execute some `twisted.trial.unittest` tests where each unittest spins up a `CrawlerRunner` for our live tests that do exactly what unittests do but with live data fetching.

Could we leave the current behavior for py2 but port the `getargspec` to `getfullargspec` as is suggested in the warning? I see latter for py3 includes additional return values, but should be a quick port. Would you be ok with a patch? Thanks

**Comment by kmike** [comment]
Sure, it would be a good addition!
