### ISSUE TITLE
how can i generate item in list page and detail page separately?

### ISSUE THREAD

**Issue by vivianjia714** [scrapy/scrapy#2872]
for ex,

in list page i will get some item[''] to generate, the item need to be looped in....

then i will yield a request to a new detail page to get other item[''] to generate,

how can i handle this situition?

**Comment by redapple** [comment]
hi @vivianjia714 , we try and keep GitHub issues for bug reports (and design or feature discussions)
Troubleshooting and "how-to" questions should be posted to either [Stackoverflow](https://stackoverflow.com/) (with tag "scrapy") or [/r/scrapy](https://www.reddit.com/r/scrapy/).
Thank you.
