### ISSUE TITLE
The program does not close automatically？

### ISSUE THREAD

**Issue by lovebaicai** [scrapy/scrapy#2874]
1. Scrapy-redis framework, redis stored xxx: requests have been crawled finished, but the program is still running, how to automatically stop the program, rather than has been running?

```
2017-08-07 09:17:06 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2017-08-07 09:18:06 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
```
2. Please help me.Ths!

**Comment by redapple** [comment]
hi @lovebaicai , 
we try and keep GitHub issues for bug reports (and design or feature discussions)
Troubleshooting questions should be posted to either [Stackoverflow](https://stackoverflow.com/) (with tag "scrapy") or [/r/scrapy](https://www.reddit.com/r/scrapy/).
Moreover, this question may be best suited for https://github.com/rmax/scrapy-redis.
Thank you.

**Comment by lovebaicai** [comment]
Thank your !
