### ISSUE TITLE
how to change ip with scrapy when one network card have 10 ip?

### ISSUE THREAD

**Issue by kekdke** [scrapy/scrapy#2877]
my linux network card have 10 ip, how to change i with scrapy ,could you tell me ?

**Comment by grammy-jiang** [comment]
hi, there,

there is a special key in meta of request: `bindaddress`. you can switch ip address in each request sent out from spider.

you can get more information here:
[Requests and Responses — Scrapy 1.4.0 documentation](https://doc.scrapy.org/en/latest/topics/request-response.html#std:reqmeta-bindaddress)

**Comment by kmike** [comment]
Thanks @grammy-jiang for an answer.
@kekdke we're trying to use Scrapy issue tracker for bug reports and enhancement proposals; for general Scrapy help there are better channels - please use https://stackoverflow.com (use tag "Scrapy").
