### ISSUE TITLE
About the RedirectMiddleware——safe_url_string(response.headers['location'])

### ISSUE THREAD

**Issue by HaoYangMa** [scrapy/scrapy#2878]
When I got a long redirect_url，the RedirectMiddleware ————at code line 71th 
location = safe_url_string(response.headers['location'])
will strip “https://” to “ps://”
and then got an scrapy schema error

**Comment by HaoYangMa** [comment]
the url like :
[scrapy.core.engine] DEBUG: Crawled (302) <GET https://mp.weixin.qq.com/mp/getmasssendmsg?__biz=MzA5MTc2MzU3NA==&uin=MjA2Njk5NTY3MA==&key=38c106704187018f6b0104411ba348b40b310c6c427735c94dddf1eed811924a74e6f0b6980a4e9ec317a95376f1c39e01ff26289df54ce264762bbb037935835daf42d0834e9933bf0decc2543ca517&pass_ticket=d9bN3Rn7u09BJSwm4LktD3%20yaxKeXt/LODxOmzTvrpGENFlgbtgnH0K/4RWm0wYW> (referer: None)

**Comment by redapple** [comment]
Hi @HaoYangMa , I'm getting an HTTP 200 for the URL you gave.
Would you be able to capture the raw headers (including "Location:") from the HTTP 302 response?
or provide some input URL that get stripped when passed to `safe_url_string()`?

**Comment by HaoYangMa** [comment]
Maybe I should say sorry. I try it today. And I can't repeat the error either. Only message remain is my google search history "scrapy.exceptions.NotSupported: Unsupported URL scheme 'ps': no handler available for that scheme"
But I really met this "https://" to "ps://" error several times in the spider project I have made. 
If I meet this again. I will capture the raw headers and upload my poroject file which relative to this error. And add a new issue.
Thanks for reply.
