### ISSUE TITLE
Feature Suggest: add the ability to insert meta fields when calling from `scrapy parse` 

### ISSUE THREAD

**Issue by IAlwaysBeCoding** [scrapy/scrapy#2883]
I find myself doing a lot of `scrapy parse` when testing out my parsing methods on the spiders that I develop.

However, there is this one thing that I really hate that `scrapy` doesn't have.

The ability to insert meta fields coming from the response.meta when using it from the `scrapy parse` command.

For example, say I'm scraping an ecommerce site.

A method such as `parse_product_detail_page` can have the `category_id` meta key coming from the previous Request which is not available unless `scrapy crawl` was used.

I'm doing a lot of commenting out my parse functions like this

```
#category_id = response.meta.get('category_id', None)
category_id = 3183

```
All because I cannot pass `category_id` into meta when calling from `scrapy parse`.

**Comment by redapple** [comment]
Hey @IAlwaysBeCoding , I also had this experience in the past.
It would be a great addition for `scrapy parse`;
One thing to design right from the start though: it should also allow more complex data structures, like dicts (as items are often passed in request.meta). There were [some discussions](https://github.com/scrapy/scrapy/issues/356) on passing JSON on the command line that may be relevant here too.
... and in fact, there's [an old issue already about this](https://github.com/scrapy/scrapy/issues/1046) for `parse` command.
