### ISSUE TITLE
ItemLoader.add_value()/add_xpath() should append (not replace) a value to the same key.

### ISSUE THREAD

**Issue by zaazbb** [scrapy/scrapy#2886]
my code:
```python
import scrapy
from scrapy.loader import ItemLoader

class Product(scrapy.Item):
    name = scrapy.Field()
    test = scrapy.Field()

loader = ItemLoader(Product())
loader.add_value('name', '1111111111')
loader.add_value('name', '222222222')
loader.add_value('test', 'aaaaaaaaa')
item = loader.load_item()
print(item)

loader = ItemLoader(item)
loader.add_value('name', '333333333')
item = loader.load_item()
print(item)
```
output:
```
{'name': ['1111111111', '222222222'], 'test': ['aaaaaaaaa']}
{'name': ['333333333'], 'test': ['aaaaaaaaa']}
```
I expect '333333333' append to the key 'name', but it replace the value.

My spider need get lots of urls to download from different pages, so, i need append values to the same key, in different page paser.
What can i do, to do that??

thank you for your replay.

**Comment by djunzu** [comment]
@zaazbb ,

The `ItemLoader` only adds a value to a key once: when you call `load_item()`. When you call `add_value()`  or `add_xpath()` the values are stored internally in the ItemLoader until you call `load_item()`. The final value for each key depends on the input/output processors in the ItemLoader. The ItemLoader does not have any knowledge about the Item and will simply populate it when you call `load_item()`.

If you need to get values from different page parser you should just pass the loader itself around, from parser to parser. Call `load_item()` only once: when you already have all your data in the loader.

**Comment by zaazbb** [comment]
@djunzu, thank you for your replay.
but, pass loader to another request, it is not encouraged. because the request.text is changed in next request.
 any other way to do so??

**Comment by zaazbb** [comment]
I solved this problem by appending new url to the item['file_urls'] manually.
thank you.

**Comment by djunzu** [comment]
> pass loader to another request, it is not encouraged. because the request.text is changed in next request

Never thought about that.
(From where did you get this info?)
It may be true if values are not extracted when `add_xpath()` is called. It is not a problem if values are extracted every time `add_xpath()` is called (which I think is the case!). But I am not an expert. I just pass the loader to another request after many `add_value()` calls and everything works just right.
