### ISSUE TITLE
Scrapy returns importError: can't import etreee for windows

### ISSUE THREAD

**Issue by ajwad605** [scrapy/scrapy#2888]
I am having issue with using Scrapy on windows. I use Anaconda on my Windows and installed scrapy following the instructions on documentation. When I tried to use scrapy on the cmd its failed as it could not import etree. I am not sure if the issue is with my paths or something else. Would appreciate any advice!

**Comment by redapple** [comment]
hi @ajwad605 , 
we try and keep GitHub issues for bug reports (and design or feature discussions)
Troubleshooting questions should be posted to either [Stackoverflow](https://stackoverflow.com/) (with tag "scrapy") or [/r/scrapy](https://www.reddit.com/r/scrapy/).
