### ISSUE TITLE
SpiderMiddleware.process_spider_exception() did not handle exception of spider

### ISSUE THREAD

**Issue by RonaldinhoL** [scrapy/scrapy#2896]
when all spider middware's process_spider_input() has finish, scrapy call Scraper.call_spider(), then call the spider' callback, but it just return a generater, in Scraper.handle_spider_output()   it iter the generater, then  spider raise exception， scrapy direct call  Scraper.handle_spider_error(),  SpiderMiddleware have no chance to handle the exception.  it just handle the exception raise by SpiderMiddleware.process_spider_input() .

**Comment by kmike** [comment]
I think it is the same issue as https://github.com/scrapy/scrapy/issues/220; it is being fixed in https://github.com/scrapy/scrapy/pull/2061.
