### ISSUE TITLE
Can not extract second <body> by xpath or css in multiple <body> page.

### ISSUE THREAD

**Issue by qwIvan** [scrapy/scrapy#2899]
such as [this](http://physics.szu.edu.cn/index.php?g=portal&m=list&a=teacher_mien&id=111)

This page contain 3 `<body>` tags, but I can only extract the first by `response.xpath('body')` or `response.css('*')`

**Comment by kmike** [comment]
This is tricky, but you can use `response.xpath('//body')`. 
For usage questions https://stackoverflow.com/ can be a better place (use "Scrapy" tag). Thanks!

**Comment by qwIvan** [comment]
Thanks!
( ‵o′)
