### ISSUE TITLE
Multi crawlers at the same time might conflict over scrapy.signal

### ISSUE THREAD

**Issue by dingld** [scrapy/scrapy#2903]
scrapy.signal module is globally imported in all related modules, so it is shared among all the crawlers running in the same process.

 Scanning the source code of scrapyrt,  an extra if-condition was added to the receiver to isolate each crawler.
```
   if spider is self.crawler.spider:
``` 
But this way looks redundant, would it be better to construct the signal object as a member variable per crawler?

**Comment by kmike** [comment]
I'm not sure why scrapyrt needs this; there may be reasons, but they are not obvious. Each crawler has its own SignalManager; multiple crawlers shouldn't conflict over signals. I had to write quite a lot of code to aggreagte signals from several crawlers in https://github.com/TeamHG-Memex/arachnado/blob/master/arachnado/crawler_process.py. 

Do you have an example of what's broken with scrapy.signals?

**Comment by dingld** [comment]
That is helpful.  SignalManager of each crawler connect the signal to receiver with the same crawler as sender by default.  I don't have an actual example, I just followed the example of scrapyrt to collect items scraped. And thanks for the example of arachnado.
