### ISSUE TITLE
RFPDupeFilter  request  fingerprint  can not be saved

### ISSUE THREAD

**Issue by mahaoyang** [scrapy/scrapy#2904]
scrapy.dupefilters.RFPDupeFilter   

line 47 - 53

    def request_seen(self, request):
        fp = self.request_fingerprint(request)
        if fp in self.fingerprints:
            return True
        self.fingerprints.add(fp)
        if self.file:
            self.file.write(fp + os.linesep)

The  file.write()  function only write this to cahce . So when I restart the spider, all fingerprints gone.

I change it to 

class SeenURLFilter(RFPDupeFilter):
    """A dupe filter that considers the URL"""

    def __init__(self, path=None, debug=False):
        RFPDupeFilter.__init__(self, path, debug)

    def request_seen(self, request):
        fp = request.url
        if fp in self.fingerprints:
            return True
        self.fingerprints.add(fp)
        if self.file:
            self.file.write(fp + os.linesep)
            self.file.flush()

**Comment by mahaoyang** [comment]
the file.flush() can make sure it to be saved

**Comment by redapple** [comment]
@mahaoyang , how are you stopping and restarting your spider?
(I assume that you are using [`JOBDIR` setting.](https://doc.scrapy.org/en/latest/topics/jobs.html))

When a crawl finishes, [the scheduler will eventually close the dupefilter](https://github.com/scrapy/scrapy/blob/d8672689761f0bb6c0550a841f35534265e87fee/scrapy/core/scheduler.py#L46), and this will call `.close()` on the dupefilter file handler, which should "flush" as needed.

**Comment by mahaoyang** [comment]
I click the pycharm stop button to stop spider.

So... The answer is ---- run spider in terminal and use ctrl+c instead pycharm stop button

**Comment by redapple** [comment]
@mahaoyang , so you've figured this out (graceful close)?
