### ISSUE TITLE
how should I use cookie in FilesPipeline? 

### ISSUE THREAD

**Issue by lcz1688** [scrapy/scrapy#2908]
hello,how should I use cookie in FilesPipeline? For example,when filesPipeline download a video in page A,it need the cookie of page A，but spider has sent a requset to page B,and the cookie has changed.How can I solve the problem?Besides,if the video address has a short term of validity,what should I do?

**Comment by redapple** [comment]
hi @lcz1688, we try to keep GitHub issues for bug reports (and design or feature discussions)
Troubleshooting or "How-To" questions should be posted to either [Stackoverflow](https://stackoverflow.com/) (with tag "scrapy") or [/r/scrapy](https://www.reddit.com/r/scrapy/).
You'll have more eyes on your use-case and better chance of gettings answers.
Thank you for using Scrapy!
