### ISSUE TITLE
HtmlResponse check in _requests_to_follow method

### ISSUE THREAD

**Issue by Igor4uk** [scrapy/scrapy#2925]
Is it necessary to check for HtmlResponse here https://github.com/scrapy/scrapy/blob/master/scrapy/spiders/crawl.py#L57 ?
My site start return content-type:application/json and scrapy recognise it like a TextResponse and finish parsing after the first request to it

**Comment by kmike** [comment]
If the site contains JSON then it is a right thing to do, as linkextractor works on html. If site uses a wrong content-type then it makes sense to remove the check, but I'm not sure this is common; I feel that overriding it in a subclass just for your case can be a better solution than removing a check for all users.

**Comment by Igor4uk** [comment]
Maybe you are right, but by the way, I think that it is better to add more explicit debug log for such kind of error. I spend lot of time trying to deal with it

**Comment by kmike** [comment]
Adding a debug message ("Skipping non-html response {}") sounds good to me. Are you up to sending a pull request?

**Comment by kmike** [comment]
Hm, it can be quite verbose though if the goal of a spider is to crawl binary data..

**Comment by Igor4uk** [comment]
In my case we start parsing from json objects which contains ids for links, using custom overrides linkextractor class

**Comment by Igor4uk** [comment]
Maybe it will be better and faster if you create pull request? I'm not very familiar with scrapy and github workflow.

**Comment by phnk** [comment]
@Igor4uk Do you still have the code which would allow me to reproduce the behaviour?

**Comment by Igor4uk** [comment]
I think it will be enough. Thanks
