### ISSUE TITLE
Call antoher spider (spider B in project B) in the current spider  (spider A in project A) 

### ISSUE THREAD

**Issue by xiaoyuan1998** [scrapy/scrapy#2926]
Hello Guys,

To solve the problem of proxy, i programmed spider A in project A which helps to crawl free proxy ip in a website and then put them in a csv file:
scrapy runspider getproxy_inmyfile.py -o proxylist.csv

Then i did my spider B in project B to crawl the information.
Spider B will check and get a proxy ip in my customised download middware.  if the proxy ip is invalid, middware will delete this ip in the proxy csv file. if it is effective, i will use this ip as a proxy,

My issue is that:
when the proxy csv file is empty (all proxy ip are invalid and deleted)   
i would like to run spider A again to provisioning the csv file.
I only find the tutorial of running multiple spiders in one project in the site of doc https://docs.scrapy.org/en/latest/  but i do not know how to run another spider in another project. 

Thanks in advance for your help.

**Comment by IAlwaysBeCoding** [comment]
Why don't you schedule to run Spider A via cron to run every minute, then on the `__init__()` method of your Spider check if the csv file is empty, and it if is start the initial requests to scrape for proxies. That is what I would do.

**Comment by xiaoyuan1998** [comment]
@IAlwaysBeCoding  thanks for your advice
if i  schedule to run Spider A every min,  if it is empty in the middle of one minute, scrapy may launch an error.
may be i shoulad add,  when B is woking, if csv is empty, B should wait 30 seconds and then check again while spider A will provisioning the csv which is called  by schedule.
i will try it.

**Comment by IAlwaysBeCoding** [comment]
Then, why not combine Spider A with Spider B all into Spider AB. Like this, make a Spider Middleware that will check if csv is empty and if not launch the logic of Spider B from the method `process_spider_output()`.

Like this:

```python

class ProxyAMiddlewareCaller(object):

    def process_spider_output(response, result, spider):
        if check_if_csv_is_empty(file):
            request = Request('http://urlwheretoscrapeforproxies.com', callback=self.parse_proxies)
            spider.crawler.schedule(request, spider)
   

```
Remember, `process_spider_out` will just yield a new Request if your csv file is empty. You basically should just call your logic to scrape for proxies everytime you have output from your spider.

**Comment by kmike** [comment]
There are tools like https://github.com/apache/incubator-airflow or https://github.com/spotify/luigi which help with managing workflows like that, probably that's the best solution.
