### ISSUE TITLE
Unhelpful log message from core.downloader.handlers.http11

### ISSUE THREAD

**Issue by djunzu** [scrapy/scrapy#2927]
Consider the two log messages:

```txt
2017-09-17 10:52:27 [scrapy.core.downloader.handlers.http11] WARNING: Expected response size (42276161) larger than download warn size (33554432).
2017-09-17 10:54:18 [scrapy.core.downloader.handlers.http11] WARNING: Received more bytes than download warn size (33554432) in request <GET https://example.com>.
```

While the second one can be useful, the first one is not helpful at all because there is no info about which request it is about. The first message should indicate the request it refers to in the same way the second message does.

**Comment by NoExitTV** [comment]
Can I have the code you used to get these error messages?

**Comment by djunzu** [comment]
> Can I have the code you used to get these error messages?

@NoExitTV, sorry, but I can not disclose this project's source.

I could try to give you a url that generates this message... But I don't know which url generated it in the first place, and that is the issue! But I am guessing it was generated by a .m4v file (see #2928).

**Comment by NoExitTV** [comment]
@djunzu No worries. I figured it out as you've seen in my PR [#2952](https://github.com/scrapy/scrapy/pull/2952)

**Comment by kmike** [comment]
Fixed by https://github.com/scrapy/scrapy/pull/2952 - thanks @NoExitTV and @djunzu!
