### ISSUE TITLE
Structure of XmlExportPipeline example class in docs is confusing

### ISSUE THREAD

**Issue by colinmorris** [scrapy/scrapy#2932]
The [Exporters section of the docs](https://doc.scrapy.org/en/latest/topics/exporters.html#using-item-exporters) give an example pipeline class called `XmlExportPipeline`. It defines methods `spider_opened` and `spider_closed`.

I found this confusing because the [pipeline docs](https://doc.scrapy.org/en/latest/topics/item-pipeline.html#writing-your-own-item-pipeline) describe methods called `open_spider` and `close_spider`, with seemingly the same semantics. At first I thought the example methods were typo'd, until I saw that they were explicitly connected to the corresponding signals in `from_crawler`.

I'm guessing this is the "old way" of doing it, and the example predates the existence of the `open_spider` and `close_spider` methods?

Unless there's a reason to do it this way, I think the example would be clearer (and shorter) if it used the built-in names.

**Comment by kmike** [comment]
A good catch. There is no need to connect to signals manually now. `self.files` is also not required, as there is a single spider per crawler now. A pull request is welcome :)

**Comment by kmike** [comment]
Fixed by https://github.com/scrapy/scrapy/pull/2989. Thanks @colinmorris!
