### ISSUE TITLE
scrapy to follow external link with one depth only

### ISSUE THREAD

**Issue by fatagun** [scrapy/scrapy#2938]
Imagine I am crawling `foo.com`. foo.com has several internal links to itself, and it has some external links like:

    foo.com/hello
    foo.com/contact
    bar.com
    holla.com

I would like scrapy to crawl all the internal links but also only one depth for external links such as I want scrapy to go to `bar.com` or `holla.com` but I dont want it to go any other link within `bar.com` so only depth of one. 

is this possible? What would be the config for this case?

Thanks.

**Comment by kmike** [comment]
This is not a built-in feature, but it is certainly possible to implement - you can use a custom request.meta field to keep track of per-domain request depth, and send (or not send) requests based on this value. You can also write a middleware which does that.

We're using this issue tracker for bugs and enhancement proposals; you may have better answers at https://www.reddit.com/r/scrapy/ or http:stackoverflow.com (use tag "Scrapy") - these are our official support channels.
