### ISSUE TITLE
How to connect to the spider singnal in middleware

### ISSUE THREAD

**Issue by exotfboy** [scrapy/scrapy#2959]
I have to connect to the spider singnal in my middleware,  and I use this at the moment:

```
class XXXMiddleware(object):
    def __init__(self):
        dispatcher.connect(self.spider_closed, signals.spider_closed)
```

While I got the warning the `Importing from scrapy.xlib.pydispatch is deprecated, ... and use `from_crawler` instead.

Also I found this closed [issue](https://github.com/scrapy/scrapy/issues/1762), and this is the suggested alternative:

```
@classmethod
def from_crawler(cls, crawler, *args, **kwargs):
    spider = super(MySpider, cls).from_crawler(crawler, *args, **kwargs)
    crawler.signals.connect(spider.spider_opened, signals.spider_opened)
    return spider
```

However in my case, I can not access the `spider `  in the middleware, and  I do not think middleware should be coupled with spider .

So how to connect to the spider singnal in middleware?

**Comment by IAlwaysBeCoding** [comment]
Don't worry @exotfboy, it seems to me that the popular belief is that a lot of people are confused about how all of Scrapy's core parts work. I will write a series of post detailing Scrapy's core and share it with the community later on. 

Back to your problem, if you notice almost every single component(middleware, item pipeline, extensions etc.) has the `from_crawler()` class method. The `Crawler` holds literally all of the Scrapy components into its namespace. That is why is passed to all of the other components through the `from_crawler()` class method, so the other components can access all of Scrapy's parts.

In your case, you want to do it like this:

```python

#Option 1: Connect the signals and save the spider instance for future reference
class XXXMiddleware(object):

    def __init__(self, spider):
        self.spider = spider
    
    @classmethod
    def from_crawler(cls, crawler):
        crawler.signals.connect(crawler.spider.spider_closed, signal=signals.spider_opened)
        return cls(crawler, spider=spider)


#Option 2: Just connect the signals without saving the spider instance for future reference
class XXXMiddleware(object):

    @classmethod
    def from_crawler(cls, crawler):
        crawler.signals.connect(crawler.spider.spider_closed, signal=signals.spider_opened)
        return cls(crawler)
```

You connect the signals inside the `from_crawler()` class method, and the spider is accessed through the `crawler.spider` attribute(this is the current `Spider` instance).

Up above there are 2 options, one is to pass the spider instance and save it on the __init__ method plus the signals connecting, and the other one is just to do the signal connecting without saving the spider instance.

Cheers! If you need anything else just reply, and I will try my best to help you.

**Comment by exotfboy** [comment]
@IAlwaysBeCoding  This is awesome , thank you !

**Comment by IAlwaysBeCoding** [comment]
No problem @exotfboy I'm glad it helped you , if you have solved your problem, then you should close the ticket so you can make a little bit less work for @kmike and @redapple, and all of the other maintainers.
