### ISSUE TITLE
<a> element has no href attribute

### ISSUE THREAD

**Issue by Anton24322224** [scrapy/scrapy#2967]
So, why does scrapy raise ValueError when you gave `<a>` tag without href to response.follow(), why not just ignore those?
As far as my understanding goes a tags without href is still completely valid, so this behaviour looks strange to me.

> [The href attribute on a and area elements is not required; when those elements do not have href attributes they do not create hyperlinks.](https://www.w3.org/TR/html/links.html#element-attrdef-a-href)

**Comment by kmike** [comment]
How would you ignore it? `response.follow` returns a single scrapy.Request object.
You can filter out these links in your xpath or css selector which is used to get `<a>` elements.
See also: https://github.com/scrapy/scrapy/issues/2582 - follow_all API may support dropping such links more easily.

**Comment by Anton24322224** [comment]
Return `None` maybe. Not sure if this is the best solution, but it should work pretty well.

**Comment by kmike** [comment]
None is not supported as a spider output value (so it would require changing of a Spider API), and also you'd have to check for None if you do some further processing of the request. Why do you prefer error returned as None instead of an exception?

**Comment by cathalgarvey** [comment]
Hi @Anton24322224 - is it OK if we close this issue, or would you like to discuss it further?
FWIW, my take is that if there were an iterable API, like "follow_all", then it would make sense to (optionally?) filter for valid `<a>` elements only and silently drop the rest. But I'd agree with Mikhail's assessment for the `response.follow` API; having a nullable return value here would just kick errors into another part of Scrapy.

**Comment by Anton24322224** [comment]
I get your point. I would look forward to "follow_all".

**Comment by cathalgarvey** [comment]
Hey Anton, I don't think that's currently on the roadmap. But if you made a strong case for a friendly API, with a well-tested pull request, maybe it could happen! :)

**Comment by kmike** [comment]
FTR: I haven't sent a PR for response.follow_all (https://github.com/scrapy/scrapy/issues/2582) because the discussion about API has't really started; I proposed a few alternative API ideas, but there were no feedback on them, neither from commiters nor from community. I think we should pick up and finish the API discussion first, before writing code: is this feature wanted? how should it look like?

**Comment by cathalgarvey** [comment]
Oh, cool; thanks @kmike I'll follow this up there. :)
