### ISSUE TITLE
ImportError when running script

### ISSUE THREAD

**Issue by addisonwebb** [scrapy/scrapy#2968]
*Disclaimer*: I am very new to the Python world so this issue might be caused by me not understanding how the pieces fit together. 🙃

### Background
I have create a couple Spiders and I would like to start them using a script. (vs having to start them individually from the command line) I tried to follow the example in the Scrapy docs [here](https://doc.scrapy.org/en/latest/topics/practices.html#running-multiple-spiders-in-the-same-process). I am confident both of my spiders work as I would expect. When I run them like this, `scrapy crawl data_1`, I get the behavior I expect.

When I run the script I get this error:
```
$ python crawlScript.py 
Traceback (most recent call last):
  File "crawlScript.py", line 3, in <module>
    import scrapy
ImportError: No module named scrapy
```

Any help figuring out the issue would be greatly appreciated!

### Script Content
```
#!/usr/bin/env python

import scrapy

from scrapy.crawler import CrawlerProcess

# import spiders
from spiders.data_1 import Data1Spider

process = CrawlerProcess(get_project_settings())

process.crawl(Data1Spider)
process.start()
```

### Project Structure
```
MyScraper
|____.DS_Store
|______init__.py
|______init__.pyc
|____crawlScript.py     <--- my script
|____items.py
|____items.pyc
|____middlewares.py
|____pipelines.py
|____pipelines.pyc
|____settings.py
|____settings.pyc
|____spiders
| |____.DS_Store
| |______init__.py
| |______init__.pyc
| |____data_1.py        <--- spider file 1
| |____data_1.pyc
| |____data_2.py       <--- spider file 2
| |____data_2.pyc
```

### Other Info
`Python version`: 2.7.10
`Scrapy version`: 1.4.0
`OS`: macOS 10.12.6

**Comment by carlosdamazio** [comment]
Did you check your scrapy installation in pip globally or in your virtualenv?
Also, make sure your virtualenv where your scrapy is installed is actually activated.

**Comment by carlosdamazio** [comment]
Maybe you installed it globally and you're trying to run an env that doesn't have scrapy.

**Comment by addisonwebb** [comment]
@carlosdamazio thanks for the response. How can you tell that the script is pointing to a virtualenv? I haven't installed `virtualenv` so I wouldn't think this would be the case.

**Comment by addisonwebb** [comment]
Ok, I think I figured it out. The problem was that I was pointing to the wrong version of Python.

I installed scrapy via pip and it installed it in `/usr/local/lib/python2.7/site-packages`. I found this by running `pip show scrapy`.

Since I have multiple versions of `python` on my machine, the script was trying to use a version of Python that didn't have scrapy installed.
