### ISSUE TITLE
DOWNLOAD_DELAY and ctrl-c

### ISSUE THREAD

**Issue by netcaf** [scrapy/scrapy#2969]
Hello,
If we set DOWNLOAD_DELAY for a list of urls,
It may wait too long to terminate the job for the first cancel operation.
Can we improve it?
For example, wake up the sleeping spider(DOWNLOAD_DELAY) and let it respond to cancel operation.

**Comment by kmike** [comment]
You can send a second Ctrl-C to stop the spdier forcefully, without waiting for requests to finish. Is it what you want?

Currently Scrapy has this stopping order:

1. First Ctrl-C: stop accepting new requests from Scheduler, wait for all requests in Downloader to finish, make sure all shutdown code is called (e.g. spider_closed handlers, etc.).
2. Second Ctrl-C: drop all requests from Downloader, don't call shutdown code, exit spider immediately.

(1) is a safe default for disk-based queues, as it allows to resume processing later without dropping requests. If you want it to finish sooner, decrease CONCURRENT_REQUESTS, to limit a number of requests in Downloader.

Sometimes I also want something between (1) and (2): drop all requests from Downloader, but call other shutdown code. I think this is a reasonable feature to implement; I'm not sure how to trigger it though, as Ctrl-C is already quite overloaded, and adding 3-step Ctrl-C would be backwards incompatible.

**Comment by laggardkernel** [comment]
@kmike When first <kbd>Ctrl-C</kbd> is triggered, does the response go through Pipeline?
