### ISSUE TITLE
Override "Connection" in headers will result in two "Connection" in headers.

### ISSUE THREAD

**Issue by tuangeek** [scrapy/scrapy#2970]
If I try to override the "Connection" in the headers with either custome_settings
```
custom_settings = {
        'DEFAULT_REQUEST_HEADERS': {
            'Connection' : 'Keep-Alive'
        }
}
```
or within the request headers
```
headers = {}
 headers['Connection'] : 'Keep-Alive'
 headers['User-Agent'] : 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36'

for url in urls:
     yield scrapy.Request(url, headers=headers, callback = self.parse)
```

It will result with a request with two "Connection"s in the header.

```
GET http://example.com HTTP/1.1
Connection: close
Connection: Keep-Alive
User-Agent: Scrapy/1.4.0 (+http://scrapy.org)
Accept-Encoding: gzip,deflate
```

**Comment by raphapassini** [comment]
I can't see the same results here @tuangeek 

```
In [6]: from scrapy import Request
In [7]: req = Request('http://python.org', headers={'Connection': 'keep-alive'})
In [8]: req.headers
Out[8]: {b'Connection': b'keep-alive'}
```
I also tried with the ``custom_settings`` and the result was the same:

```
In [1]: spider
Out[1]: <PyhtonOrgSpider 'python_org' at 0x7f282e447dd8>

In [2]: xx = list(spider.start_requests())

In [3]: xx
Out[3]: [<GET http://python.org>]

In [4]: xx[0].headers
Out[4]: {}

In [5]: fetch(xx[0])
2017-12-05 17:00:26 [scrapy.downloadermiddlewares.redirect] DEBUG: Redirecting (301) to <GET https://python.org/> from <GET http://python.org>
2017-12-05 17:00:27 [scrapy.downloadermiddlewares.redirect] DEBUG: Redirecting (301) to <GET https://www.python.org/> from <GET https://python.org/>
2017-12-05 17:00:28 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.python.org/> (referer: None)

In [6]: response.request.headers
Out[6]: 
{b'Accept-Encoding': b'gzip,deflate',
 b'Connection': b'keep-alive',
 b'User-Agent': b'Scrapy/1.4.0 (+http://scrapy.org)'}
```

**Comment by RavenHustler** [comment]
I've the same problem too. I checked the requests using fiddler and it sends both keep-alive and close:
```
Connection: close
Connection: keep-alive
```

**Comment by tlinhart** [comment]
Seems like the header is set directly in [`ScrapyHTTPClientFactory`](https://github.com/scrapy/scrapy/blob/129421c7e31b89b9b0f9c5f7d8ae59e47df36091/scrapy/core/downloader/webclient.py#L137).

**Comment by cathalgarvey** [comment]
Hey folks, I fired up Wireshark and tried to reproduce this, with no success, on Python 3.5 and Scrapy 1.5.0.

If I issue the following:

```python
>>> req = scrapy.Request('http://httpbin.org/headers', headers={'Connection': 'wat'})
>>> fetch(req)
```

..then I see in Wireshark the following request firing:

```
GET /headers HTTP/1.1
Accept-Language: en
Accept-Encoding: gzip,deflate
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Connection: wat
User-Agent: Scrapy/1.5.0 (+https://scrapy.org)
Host: httpbin.org
```

(I did try sending 'keep-alive' first, and that also works as expected. I just felt like mixing it up a bit).

Interestingly, and disappointingly, the response from `httpbin.org/headers` always includes the header 'Connection: close', reducing its usefulness for debugging this issue.

Can anyone provide me with a reproducible test case so I can further test this?

**Comment by tuangeek** [comment]
I forgot I had this issue open. It has been a while since I last worked on this project and forgot the condition that created this issue to being with. I just tried reproducing the issue but was unsuccessful. I will go a head and close this issue.

**Comment by cathalgarvey** [comment]
Thanks! Good luck. :)
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by kmike** [comment]
@cathalgarvey in a link @tlinhart posted (https://github.com/scrapy/scrapy/issues/2970#issuecomment-360706840) Connection header is set only when body is not None. So it affects POST, PUT and other requests with non-empty bodies; it doesn't affect usual GET requests, which your Wireshark experiment shows.
