### ISSUE TITLE
ImportError: cannot import name '_unquotepath'

### ISSUE THREAD

**Issue by younesherlock** [scrapy/scrapy#2971]
Hello,
When I run `scrapy shell 'https://www.google.com'`, here's what I get:

`

    Traceback (most recent call last):
    File "/usr/bin/scrapy", line 7, in <module>
        from scrapy.cmdline import execute
    File "/usr/lib64/python3.4/site-packages/scrapy/__init__.py", line 34, in <module>
        from scrapy.spiders import Spider
    File "/usr/lib64/python3.4/site-packages/scrapy/spiders/__init__.py", line 10, in <module>
        from scrapy.http import Request
    File "/usr/lib64/python3.4/site-packages/scrapy/http/__init__.py", line 10, in <module>
        from scrapy.http.request import Request
    File "/usr/lib64/python3.4/site-packages/scrapy/http/request/__init__.py", line 13, in <module>
        from scrapy.utils.url import escape_ajax
    File "/usr/lib64/python3.4/site-packages/scrapy/utils/url.py", line 15, in <module>
        from w3lib.url import _safe_chars, _unquotepath
    ImportError: cannot import name '_unquotepath'
`

And here are some information about my packages:

`
    
    linux-hcjz:/home/user/Projects/books # pip show scrapy
    Name: Scrapy
    Version: 1.4.0
    Summary: A high-level Web Crawling and Web Scraping framework
    Home-page: http://scrapy.org
    Author: Pablo Hoffman
    Author-email: pablo@pablohoffman.com
    License: BSD
    Location: /usr/lib64/python3.4/site-packages
    Requires: pyOpenSSL, lxml, queuelib, PyDispatcher, service-identity, Twisted, cssselect, six, w3lib, parsel
    linux-hcjz:/home/user/Projects/books # pip freeze scrapy
    apparmor==2.10.2
    asn1crypto==0.23.0
    attrs==17.2.0
    Automat==0.6.0
    bottle==0.12.8
    certifi==2017.7.27.1
    cffi==1.11.2
    click==6.7
    constantly==15.1.0
    coverage==4.3.4
    cryptography==2.1.1
    cssselect==1.0.1
    cupshelpers==1.0
    daemonocle==1.0.1
    decorator==4.1.2
    hyperlink==17.3.1
    idna==2.6
    incremental==17.5.0
    ipython==6.2.1
    ipython-genutils==0.2.0
    jedi==0.11.0
    LibAppArmor==2.10.2
    lxml==4.1.0
    nose==1.3.7
    olefile==0.44
    onedrive-d==1.1.0.dev0
    packaging==16.8
    parsel==1.2.0
    parso==0.1.0
    pexpect==4.2.1
    pickleshare==0.7.4
    Pillow==4.2.1
    prompt-toolkit==1.0.15
    psutil==5.4.0
    ptyprocess==0.5.2
    py==1.4.30
    pyasn1==0.3.7
    pyasn1-modules==0.1.5
    pycparser==2.18
    pycrypto==2.6.1
    pycups==1.9.72
    pycurl==7.19.5.1
    PyDispatcher==2.0.5
    Pygments==2.2.0
    pygobject==3.20.1
    pyOpenSSL==17.3.0
    pyparsing==2.2.0
    pyserial==3.4
    pysmbc==1.0.15.4
    queuelib==1.4.2
    requests==2.7.0
    Scrapy==1.4.0
    Send2Trash==1.4.1
    service-identity==17.0.0
    simplegeneric==0.8.1
    simplejson==3.8.0
    six==1.11.0
    traitlets==4.3.2
    Twisted==17.9.0
    typing==3.6.2
    urllib3==1.22
    w3lib==1.18.0
    wcwidth==0.1.7
    zope.interface==4.4.3
    linux-hcjz:/home/user/Projects/books # 

`

**Comment by younesherlock** [comment]
This also may be useful:

    
    NAME="openSUSE Leap"
    VERSION="42.3"
    ID=opensuse
    ID_LIKE="suse"
    VERSION_ID="42.3"
    PRETTY_NAME="openSUSE Leap 42.3"
    ANSI_COLOR="0;32"
    CPE_NAME="cpe:/o:opensuse:leap:42.3"
    BUG_REPORT_URL="https://bugs.opensuse.org"
    HOME_URL="https://www.opensuse.org/"

**Comment by redapple** [comment]
Hi @younesherlock ,
does `scrapy version -v` output the same versions? esp. for `w3lib`?
[`w3lib` 1.18 has `w3lib.url._unquotepath`](https://github.com/scrapy/w3lib/blob/v1.18.0/w3lib/url.py#L487)

**Comment by kmike** [comment]
It looks like an installation issue. w3lib 1.18 has this function, while early w3lib versions (1.15 or so?) don't. So for some reason w3lib you're importing is not the latest. I'm closing this issue; it is better to debug it at https://stackoverflow.com (use tag "Scrapy").
