### ISSUE TITLE
can't support string.format()

### ISSUE THREAD

**Issue by 3114318094** [scrapy/scrapy#2974]
can't support string.format()
like this:

start_urls=[f'{i}/{j}' for i in range(1,10)  for j in range(1, 10)]

but it work well in python3.6 or ipython,python3.5 failed.
This is a new feature in python3.6.

environment: python3.6   scrapy-1.4.0

**Comment by kmike** [comment]
Sorry, it doesn't look like a Scrapy issue, more like a general Python question. We're trying to keep this issue tracker for Scrapy bugs and feature discussions only. You may get a better help on https://stackoverflow.com, so I'm clsing this ticket.
