### ISSUE TITLE
Why scrapy stats 's time zone is not consistent with log's time

### ISSUE THREAD

**Issue by syncml** [scrapy/scrapy#2992]
hi, 

Why scrapy stats 's time zone is not consistent with log's time.
There are any variable to set time zone?

thanks

```
2017-11-03 13:56:35 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
......
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2017, 11, 3, 5, 56, 35, 981583),
....
 'start_time': datetime.datetime(2017, 11, 3, 5, 44, 10, 93653)}
2017-11-03 13:56:35 [scrapy.core.engine] INFO: Spider closed (finished)

```

**Comment by VMRuiz** [comment]
Hello,

The time in the logs output is set to your local time, meanwhile the start_time and finish_time fields use the UTC Local Zone. I guess this is to facilitate merging stats data from spiders running on remote servers with different timezones.

**Comment by kmike** [comment]
@syncml there is currently no option to set log's time zone, without changing system time zone. See https://github.com/scrapy/scrapy/pull/2835.
