### ISSUE TITLE
Scrapy Selector ignored elements

### ISSUE THREAD

**Issue by XetRAHF** [scrapy/scrapy#2993]
# Problem
* Both `response.css` and `response.xpath` ignored a lot of element after a special `div` element
# How to re-trigger the problem
* `scrapy shell "https://redsea.com/en/apple-iphone-x-64gb-silver.html"`
* `response.css(".page-title")` or `response.xpath("""/html/body/div[2]/div[2]""")` both returns an <span style="color:red"> **empty** </span> array
<img width="1413" alt="It should work" src="https://user-images.githubusercontent.com/20765594/32517491-3a629860-c3cc-11e7-96ac-08fc6fd34a7b.png">

# What I found is wrong
* I tried to extract the body element using `response.css("body")`
* This is what it extracted
<img width="1139" alt="screen shot 2017-11-08 at 5 01 32 am" src="https://user-images.githubusercontent.com/20765594/32517624-94c0de84-c3cc-11e7-9dbd-418b836b3bec.png">
* This is the original html
<img width="1414" alt="screen shot 2017-11-08 at 5 02 34 am" src="https://user-images.githubusercontent.com/20765594/32517680-c0cfadb6-c3cc-11e7-9897-af52db86fb4b.png">
* Where had the elements below the highlighted line gone?

# This question is originated from stackoverflow
[Original Question](https://stackoverflow.com/questions/47163499/scrapy-downloads-the-html-page-but-could-get-data-using-xpaths-or-css)

**Comment by kmike** [comment]
stackoverflow is a better place to debug this problem, so I'm closing this issue.
