### ISSUE TITLE
scrapy FormRequest  ignore Content-Type other values

### ISSUE THREAD

**Issue by andywubit** [scrapy/scrapy#2994]
The following code
```
super(FormRequest, self).__init__(*args, **kwargs)
if formdata:
    items = formdata.items() if isinstance(formdata, dict) else formdata
    querystr = _urlencode(items, self.encoding)
    if self.method == 'POST':
        self.headers.setdefault('Content-Type', 'application/x-www-form-urlencoded')
        self._set_body(querystr)
    else:
        self._set_url(self.url + ('&' if '?' in self.url else '?') + querystr)
```
Although the FormRequest base class Request sets the request header based on the value of the headers band, such as setting Content-Type = "application / json; charset = utf-8", the code 
```
 self.headers.setdefault('Content-Type', 'application/x-www-form-urlencoded')
```
sets the Content- Type value back to "application / x -www-form-urlencoded ". He did not consider headers own Content-Type situation.

**Comment by kmike** [comment]
@andywubit setdefault does nothing if Content-Type header is present, so headers argument should have higher priority than `'application/x-www-form-urlencoded'` default. Could you please provide an example of how it breaks?

**Comment by andywubit** [comment]
@kmike Your idea is right, but the system settings Content-Type, just consider the self.mothed == 'post', did not consider whether the Content-Type has been set, just a very Content-Type is set to 'application / x-www-form-urlencoded '

**Comment by raphapassini** [comment]
AFAIK @kmike is right. in the following example you can see:

```
in [2]: from scrapy import FormRequest
in [3]: form_req = FormRequest('http://dummy.org', headers={'Content-Type': 'application/json'})
In [4]: print(form_req.headers)
{b'Content-Type': [b'application/json']}
```

**Comment by dangra** [comment]
@andywubit can you provide a code snippet that reproduces your issue? thanks

**Comment by cathalgarvey** [comment]
Hi @andywubit - I'm inclined to close this unless we can get a reproducible example case to demonstrate the issue. It appears, from my reading and others, to be perhaps a case of misunderstanding. If you think we could improve our documentation to make this clearer, that's a potential way we could take this?

Looking forward to your response.
