### ISSUE TITLE
filepipeline handle urls with "?" wrong

### ISSUE THREAD

**Issue by NewUserHa** [scrapy/scrapy#2997]
like http://www.hebpr.cn/WebbuilderMIS/attach/attachdown.jspx?attachGuid=c986d80b-4d9d-4a50-950f-fea61b828dda&dataSourceName=EpointHbztbCMS

and how can I only replace file_path method of FilesPipeline to make my custom pipeline work?
I googled many times but no answer

thanks

**Comment by NewUserHa** [comment]
and is there an easy way in settings.py to let every spider within one project write log to disk with the file name like '%spidername%.log' instead of adding a custom setting for every spider?

**Comment by iAnanich** [comment]
@NewUserHa you can write a custom subclass of the `Spider` and override `from_crawler` method, to set specific setting using your spider's name.

**Comment by NewUserHa** [comment]
could you show me some examples please?

**Comment by NewUserHa** [comment]
@iAnanich

**Comment by raphapassini** [comment]
Hey @NewUserHa you can simple use the ``custom_settings`` inside your spider

```
class PythonOrgSpider(scrapy.Spider):
    name = 'python_org'
    allowed_domains = ['python.org']
    start_urls = ['http://python.org']
    custom_settings = {
        'LOG_FILE': name + '.txt'
    }
```

The code above will generate a file called ``python_org.txt`` when you run the crawler :)

**Comment by NewUserHa** [comment]
hi, thanks.
what I want to know is that is there any way put a setting into settings to reach this?

**Comment by raphapassini** [comment]
No, there isn't a _setting_ that you can put in ``settings.py`` to do so.

But I think you can use a custom ``SpiderLoader`` to achieve this , please, take a look at: https://doc.scrapy.org/en/latest/topics/api.html#module-scrapy.loader

**Comment by NewUserHa** [comment]
thanks! that seems what I want since it's annoying to put the same code in every spider

**Comment by iAnanich** [comment]
@NewUserHa it's normal to copy-paste some code. But if it is too annoying for you, you can use class factory (metaclass).

**Comment by raphapassini** [comment]
Hey @kmike I think the title of this issue should be changed to reflect the real problem of the user and to help others to find the same solution easily :)

**Comment by kmike** [comment]
@raphapassini what title do you suggest? I can change it.

As for the ticket itself, I'm closing it; we're trying to use Scrapy issue tracker for bugs and concrete enhancement proposals; for general Scrapy help there are better resources like https://stackoverflow.com/ (use tag "scrapy").

**Comment by NewUserHa** [comment]
@kmike 
I was here to report the bug that scrapy handle any URL with '?' symbol in filepipe line incorrect so it's unable to download the file unless you override the method.
I'm not here to ask how to add one log setting to work in each spider.

**Comment by raphapassini** [comment]
In order to help you @NewUserHa can you please provide an example on how can I reproduce the bug here? It's not clear to me.

**Comment by NewUserHa** [comment]
'http://www.somesites.com/WebbuilderMIS/attach/attachdown.jspx?attachGuid=c986d80b-4d9d-4a0-950f-fea61b828dda&dataSourceName=EpointHbztbCMS' like this one.
scrapy is unable to download it since this line 'media_ext = os.path.splitext(url)[1]' of the method 'file_path()' within \pipelines\files.py is unable to handle download url like the above one.
@raphapassini @kmike 
links like that are not rare. to fix it need write a new pipeline just because of the two lines method file_path(), so is there any simplest(like hooking that method) example and fewest codes to fix it, or hope you guys can fix it.

**Comment by kmike** [comment]
@NewUserHa https://github.com/scrapy/scrapy/pull/2809/files seems to handle it better; the extension becomes `.jspx`. See also, a related proposal: https://github.com/scrapy/scrapy/issues/1199.
