### ISSUE TITLE
dont_merge_cookies docs are incomplete

### ISSUE THREAD

**Issue by kmike** [scrapy/scrapy#2998]
dont_merge_cookies [docs](https://doc.scrapy.org/en/latest/topics/request-response.html#scrapy.http.Request) are incomplete: they say that 

> When some site returns cookies (in a response) those are stored in the cookies for that domain and will be sent again in future requests. That’s the typical behaviour of any regular web browser. However, if, for some reason, you want to avoid merging with existing cookies you can instruct Scrapy to do so by setting the dont_merge_cookies key to True in the Request.meta.

But this flag not only prevents merging of cookies, but also prevents sending of them: https://github.com/scrapy/scrapy/blob/b8870ee8a10360aaa74298324d97c823b88ec5c6/scrapy/downloadermiddlewares/cookies.py#L27

Maybe a separate issue, but it'd be nice to have separate flags for sending and merging of cookies.

//cc @whalebot-helmsman

**Comment by raphapassini** [comment]
You think that this is a change only related to the docs? Maybe we should add a new option called ``dont_send_cookies``?

**Comment by RyQcan** [comment]
I mean that if i set `dont_merge_cookies=true`, scrapy will dont send any cookie to server.
But i just want that scrapy don't merge my cookies with the response's cookies, and continue to send my cookies to server.
In `scrapy/downloadermiddlewares/cookies.py`

```python
def process_request(self, request, spider):
        if request.meta.get('dont_merge_cookies', False):
            return

        cookiejarkey = request.meta.get("cookiejar")
        jar = self.jars[cookiejarkey]
        cookies = self._get_request_cookies(jar, request)
        for cookie in cookies:
            jar.set_cookie_if_ok(cookie, request)

        # set Cookie header
        request.headers.pop('Cookie', None)
        jar.add_cookie_header(request)
        self._debug_cookie(request, spider)

    def process_response(self, request, response, spider):
        if request.meta.get('dont_merge_cookies', False):
            return response

        # extract cookies from Set-Cookie and drop invalid/expired cookies
        cookiejarkey = request.meta.get("cookiejar")
        jar = self.jars[cookiejarkey]
        jar.extract_cookies(response, request)
        self._debug_set_cookie(response, spider)

        return response
```
if I set `dont_merge_cookies=true`,scrapy will do nothing.

in [issue2124](https://github.com/scrapy/scrapy/issues/2124)
@Ferrer-Jeremy think code can be modify to

```python
def process_request(self, request, spider):
        cookiejarkey = request.meta.get("cookiejar")
        jar = self.jars[cookiejarkey]

        if request.meta.get('dont_merge_cookies', False):
            jar = CookieJar()

        cookies = self._get_request_cookies(jar, request)
        for cookie in cookies:
            jar.set_cookie_if_ok(cookie, request)

        # set Cookie header
        request.headers.pop('Cookie', None)
        jar.add_cookie_header(request)
        self._debug_cookie(request, spider)
```
it can work in right way.
So,,,now i want to know why do not fix this bug...

And my English is so poor,sorry,,,
