### ISSUE TITLE
mention dont_merge_cookies in CookiesMiddleware docs

### ISSUE THREAD

**Issue by kmike** [scrapy/scrapy#2999]
Currently `dont_merge_cookies` is only documented in https://doc.scrapy.org/en/latest/topics/request-response.html#request-meta-special-keys (in 'Request' docs actually). I think we should mention it in CookiesMiddleware [docs](https://doc.scrapy.org/en/latest/topics/downloader-middleware.html#module-scrapy.downloadermiddlewares.cookies) as well.

//cc @whalebot-helmsman

**Comment by anurag03** [comment]
@kmike can I work on this issue? I am new to this repository and would like to learn and contribute.

**Comment by dangra** [comment]
Fixed by #3030
