### ISSUE TITLE
Error in scraping zomato.com

### ISSUE THREAD

**Issue by paritosh16** [scrapy/scrapy#3002]
When I run `scrapy shell https://www.zomato.com`, I get the following warning:

    :0: UserWarning: You do not have a working installation of the service_identity module: 'No 
    module named cryptography.x509'.  Please install it from 
    <https://pypi.python.org/pypi/service_identity> and make sure all of its dependencies are 
    satisfied.  Without the service_identity module and a recent enough pyOpenSSL to support it, 
    Twisted can perform only rudimentary TLS client hostname verification.  Many valid 
    certificate/hostname mappings may be rejected.

followed by another warning:

    2017-11-13 15:11:37 [scrapy.core.downloader.tls] WARNING: Remote certificate is not valid for 
    hostname "www.zomato.com"; u'*.zomato.com'!=u'www.zomato.com'
after which it exits without scrapping any webpage. If I run the same command with https://github.com it works as it should.

The environment details are:
* MacOS - v10.13
* Python - v3.6
* Scrapy - v1.4.0
* Twisted - 17.9.0
* service_identity - v17.0.0
* pyopnssl - 17.2.0

I have kind of hit a dead-end and cannot debug this.
Thanks!

**Comment by paritosh16** [comment]
Fixed. Adding user agent information in the spider setting made the scrapping successful.

**Comment by offbye** [comment]
I also  met the question ， how to fix it ?   what user-agent are used?
I  have tried below but just  met the same error 
# USER_AGENT = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36'
USER_AGENT = "Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/27.0.1453.93 Safari/537.36"
