### ISSUE TITLE
The behavior of parsing multiple redirect between Scrapy and requests is not the same

### ISSUE THREAD

**Issue by kingname** [scrapy/scrapy#3005]
There is a website. When I visit it, in Chrome I can find that It will follow 7 redirects before I get the destination page. between these redirects, the website will write some Cookies and Headers items into the Browser.

If I use requests to get the beginning page, everything is fine and I can get the source html of the destination page. However, when I use Scrapy, the website will find my spider and block me.

I thought it must because there are some difference between requests and Scrapy in the behavior of redirect. Do you know what the difference really is?

**Comment by kmike** [comment]
Do you have an example URL? You can check the difference in requests sent / responses received using https://www.wireshark.org/. An obvious difference is that default User-Agent header is not the same, but there can be others. Anyways, Scrapy issue tracker is a not right place to discuss website-spefic banning issues, so I'm closing this ticket. There are better places like https://stackoverflow.com or https://www.reddit.com/r/scrapy/.
