### ISSUE TITLE
Allow the option to remove headers being title case or lower case. 

### ISSUE THREAD

**Issue by IAlwaysBeCoding** [scrapy/scrapy#3006]
So, I spent the last 6 hours trying to get through a website only to find out the problem was with scrapy. 

There is this website( I can't name the url) that checks for a special csrftoken in the header. Well to my surprise Scrapy has hard-coded the headers so it always titles them. 

So my specific header is this one:
"X-csrftoken" but scrapy titles it to X-Csrftoken so the website cannot detect it. 

We should allow in a setting to be able to remove this bug/feature because at the moment the only way I can edit it is by going into Scrapy source code.

**Comment by kmike** [comment]
It looks like the same issue as https://github.com/scrapy/scrapy/issues/2711. A proposed fix is in https://github.com/scrapy/scrapy/pull/2784, though there are concerns raised that Twisted also capitalizes header, and so the fix does nothing (I haven't checked that).
