### ISSUE TITLE
How to use scrapy to crawl angularjs websites?

### ISSUE THREAD

**Issue by emy-lee** [scrapy/scrapy#3015]
I need a way to get ALL odds of ALL events of this bookmaker: https://www.snai.it/sport

I am using Scrapy+Splash to get the first javascript-loaded content of the site. But to get all other odds, I have to click "Spagna-LigaSpagnola", "Italia->Serie A", etc.

How can I do that ?

**Comment by kmike** [comment]
We're using Scrapy issue tracker for bugs and feature proposals; for general Scrapy help there are better channels like https://stackoverflow.com (use tag "Scrapy" and/or "scrapy-splash"). 

You can either reverse engineer requests website makes and reproduce them with Scrapy, or use a script which runs in a browser to click on all these links (e.g. Splash supports rendering scripts, but you can use other solutions as well).
