### ISSUE TITLE
logging in pipelines breaks scrapy deploy success message

### ISSUE THREAD

**Issue by plainas** [scrapy/scrapy#302]
Not sure if this should be reported here on on scrapyd's issue tracker.

using the logging facility on scrapy breaks the spider count on deploy, it returns 0 all the time.

To reproduce the error, place the snippet below on your pipelines module and try to deploy to a scrapyd target

``` python
from scrapy import log

class MyPipeline(object):    
    def __init__(self):
        log.start()

...
```

**Comment by JamesTheHacker** [comment]
@pablohoffman I came here because I'm had the same question as OP. To answer the question about why do it in a pipeline ... in my case it's because I'm storing items in a MySQL database from within the pipeline. I need to log any exceptions when inserting into the database.
