### ISSUE TITLE
lxml error after upgrading to scrapy 1.4.0 (python 3.6)

### ISSUE THREAD

**Issue by Beenhakker** [scrapy/scrapy#3021]
Hi,

Since I have upgraded to scrapy 1.4.0 today, I get lxml import errors on Ubuntu 16.10 with Python 3.6:

root@5d52e8462fc2:/# scrapy 
Traceback (most recent call last):
  File "/usr/local/bin/scrapy", line 7, in <module>
    from scrapy.cmdline import execute
  File "/usr/local/lib/python3.6/dist-packages/scrapy/__init__.py", line 34, in <module>
    from scrapy.spiders import Spider
  File "/usr/local/lib/python3.6/dist-packages/scrapy/spiders/__init__.py", line 10, in <module>
    from scrapy.http import Request
  File "/usr/local/lib/python3.6/dist-packages/scrapy/http/__init__.py", line 11, in <module>
    from scrapy.http.request.form import FormRequest
  File "/usr/local/lib/python3.6/dist-packages/scrapy/http/request/form.py", line 11, in <module>
    import lxml.html
  File "/usr/local/lib/python3.6/dist-packages/lxml/html/__init__.py", line 54, in <module>
    from .. import etree
ImportError: /usr/local/lib/python3.6/dist-packages/lxml/etree.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _PyErr_FormatFromCause

**Comment by ajpen** [comment]
what version did you upgrade from?

**Comment by BasEnem** [comment]
As far as I can recall, 1.3.5.

**Comment by ajpen** [comment]
Can you provide the output of `scrapy version -v`? Also what OS are you running on?

**Comment by ajpen** [comment]
Did you try to reinstall lxml? It could be the wheels need to be rebuilt. 

It would be very helpful if you were to provide the output to `scrapy version -v` before you try to reinstall lxml.(you can do so with `pip install --upgrade --force-reinstall lxml`

**Comment by BasEnem** [comment]
Then it was version 1.3.2. I cannot run "scrapy version -v", because it produces the same error.

After running "pip install --upgrade --force-reinstall lxml", I still get the same error.

**Comment by ajpen** [comment]
@BasEnem Can you provide the output for `pip freeze | grep Scrapy` and `pip freeze | grep lxml`?
Also, provide the output of `pip install --upgrade --force-reinstall lxml`.

**Comment by kmike** [comment]
This sounds like lxml installation issue. Likely by running `pip install -U scrapy` pip upgraded lxml as well, and it failed for some reason. I don't have a better answer than to follow lxml install instructions to make lxml installed properly - http://lxml.de/installation.html :(

**Comment by Beenhakker** [comment]
Nevermind. I switched to the dockerized versions of Scrapy instead of building my own.

**Comment by hwms** [comment]
Had the same problem with another app, this solved it for me:
`pip install --upgrade --force-reinstall --no-binary :all: lxml`
