### ISSUE TITLE
When i'm using proxy to scrape - sometimes i got timeouterror

### ISSUE THREAD

**Issue by AndrewMishchenko** [scrapy/scrapy#3022]
I'm trying to scrape one https site. Also i build spider for it and the problem is next:
1. It is work perfect without proxy. It scrape 100% pages and very fast.
2. When i'm trying to scrape through proxy(crawlera and etc) through time it raise timeout(at all works not stable) and i don't know what to do with this.

Heders i'm using:
'Host': '.....,
'Connection': 'keep-alive',
'Pragma': 'no-cache',
 'Cache-Control': 'no-cache',
 'User-Agent': 'Mozilla/4.0 (compatible; MSIE 10.0; Windows NT 6.1; Trident/5.0)',
 'DNT': '1',
 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
 'Accept-Encoding': 'gzip, deflate, br',
 'Accept-Language': 'en-US,en;q=0.8',
 'Upgrade-Insecure-Requests': '1',
 'X-Requested-With': 'XMLHttpRequest',
 'Referer': '....',
Also i was trying to add 'DOWNLOADER_CLIENT_TLS_METHOD': 'TLSv1.2' - it doesn't help!
and write something like:
class SClientContextFactory(ScrapyClientContextFactory):
     def __init__(self, method=SSL.TLSv1_2_METHOD):
        self.method = method

I'm 100 percent sure that the problem is not in the proxy
Can someone help me?

**Comment by kmike** [comment]
Why are you sure the problem is not in the proxy?

**Comment by AndrewMishchenko** [comment]
Because i use the same list of proxies for 6 others sites

**Comment by AndrewMishchenko** [comment]
And also i tested another proxies for this site and still the same situation

**Comment by AndrewMishchenko** [comment]
if it is useful (by my ip- not proxy):
depth=1 C = US, O = Symantec Corporation, OU = Symantec Trust Network, CN = Symantec Class 3 Secure Server CA - G4
verify error:num=20:unable to get local issuer certificate
verify return:0
---
Certificate chain
 0 s:/C=US/ST=New Jersey/L=Wayne/O=Toysrus/OU=Digital/CN=*.[domain]
   i:/C=US/O=Symantec Corporation/OU=Symantec Trust Network/CN=Symantec Class 3 Secure Server CA - G4
 1 s:/C=US/O=Symantec Corporation/OU=Symantec Trust Network/CN=Symantec Class 3 Secure Server CA - G4
   i:/C=US/O=VeriSign, Inc./OU=VeriSign Trust Network/OU=(c) 2006 VeriSign, Inc. - For authorized use only/CN=VeriSign Class 3 Public Primary Certification Authority - G5
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIG5jCCBc6gAwIBAgIQRa2ChY0n+MlXZ2gmJh02yzANBgkqhkiG9w0BAQsFADB+
MQswCQYDVQQGEwJVUzEdMBsGA1UEChMUU3ltYW50ZWMgQ29ycG9yYXRpb24xHzAd
BgNVBAsTFlN5bWFudGVjIFRydXN0IE5ldHdvcmsxLzAtBgNVBAMTJlN5bWFudGVj
IENsYXNzIDMgU2VjdXJlIFNlcnZlciBDQSAtIEc0MB4XDTE3MDQxMDAwMDAwMFoX
DTIwMDIyOTIzNTk1OVowbjELMAkGA1UEBhMCVVMxEzARBgNVBAgMCk5ldyBKZXJz
ZXkxDjAMBgNVBAcMBVdheW5lMRAwDgYDVQQKDAdUb3lzcnVzMRAwDgYDVQQLDAdE
aWdpdGFsMRYwFAYDVQQDDA0qLnRveXNydXMuY29tMIIBIjANBgkqhkiG9w0BAQEF
AAOCAQ8AMIIBCgKCAQEAnYEsaIjn0tEp9bMeJO9txiJG5DQanT7raWV3Y6dMuUze
8V9mKwIIkkoOXlUPFTob6B66duoE/l4atgOzNgW0ExIE/VP1KgnlibsnRTiMoGHg
aG31pwMLasjcDV+PMd7SkcpFnrnJyhbYyw0SNLq6aNH7f26ClQVhU/99ukfrmYE7
bM0FftVaGj7LR9MMb+i0QQhM+rhMBMnunl2n8wt8HiYJwGvXAIQysemq5ZirMkF9
D8cEIe/+jQvhf2Zh5iy9bLLpcwB4fBRstcNsLk+JyZBt3hhLiw/hi6r5dOIG9Wf9
0hCA8E2/2sWgyUn/wibBi8aD0xt++bVE+ersYIwSGwIDAQABo4IDbjCCA2owKQYD
VR0RBCIwIIINKi50b3lzcnVzLmNvbYIPKi5iYWJpZXNydXMuY29tMAkGA1UdEwQC
MAAwDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcD
AjBhBgNVHSAEWjBYMFYGBmeBDAECAjBMMCMGCCsGAQUFBwIBFhdodHRwczovL2Qu
c3ltY2IuY29tL2NwczAlBggrBgEFBQcCAjAZDBdodHRwczovL2Quc3ltY2IuY29t
L3JwYTAfBgNVHSMEGDAWgBRfYM9hkFXfhEMUimAqsvV69EMY7zArBgNVHR8EJDAi
MCCgHqAchhpodHRwOi8vc3Muc3ltY2IuY29tL3NzLmNybDBXBggrBgEFBQcBAQRL
MEkwHwYIKwYBBQUHMAGGE2h0dHA6Ly9zcy5zeW1jZC5jb20wJgYIKwYBBQUHMAKG
Gmh0dHA6Ly9zcy5zeW1jYi5jb20vc3MuY3J0MIIB9wYKKwYBBAHWeQIEAgSCAecE
ggHjAeEAdwDd6x0reg1PpiCLga2BaHB+Lo6dAdVciI09EcTNtuy+zAAAAVtWeRHX
AAAEAwBIMEYCIQCVJWCrzYPJqbkTjfAYiwHcdC628PmAmkh9tfBuOMtxewIhAK9w
K/JMhYHlSU8KLg7WJOYiH2nMPmvRBURxHyLa11ChAHYApLkJkLQYWBSHuxOizGdw
Cjw1mAT5G9+443fNDsgN3BAAAAFbVnkSCQAABAMARzBFAiAHolaAWkkMaYyDPKZV
f/FsTmcUxG0rDuDkMXkLqm2E6gIhAPav6ZuLvQa6DRsTc22zBpaBtvLuXVAz9SQR
cpX58X5NAHYA7ku9t3XOYLrhQmkfq+GeZqMPfl+wctiDAMR7iXqo/csAAAFbVnkT
zgAABAMARzBFAiBJIeb/bFXSkRCZA6E36kLePzuSW/RcxDUwjBtHrmqk/QIhAJxs
3hB99PYS+VBbyqMceLKpYzqdCnypqttUKgBMkisCAHYAvHjh38X2PGhGSTNNoQ+h
Xwl5aSAJwIG08/aRfz7ZuKUAAAFbVnkSxAAABAMARzBFAiAHWTNIUm4QRaGp2BZS
2mxoHO9ACANkgZqFHtLueTjExwIhAK0/I9ORZq5hHO1mbxrjnRlx+XeRuQ2rH5PR
z5yu9OTBMA0GCSqGSIb3DQEBCwUAA4IBAQCZUJj9D53d1PelyQ2GyPhLpcz6m3Nq
6LYdGvUKXGhDNTKS2f9T8cHydA/Mlio3LGzh1ncZo1JTi9x7nBXa6qW+rA7b6o6T
La8O+HFn+K+tGCECZhHpGoJwIfM3ShJRRMIDQJ48alTftCHetEKUH8gyz84m+nS8
615rUACXNbyscSxPZVkpL6X65GhyVg+S4Jtx7ARAPgmU3lJZZRj8vp5CdbcoK2iv
MkArds7DXeEQizIfQAwlyqbNtG9Yn0DE/xYM771pptysjvoo8fbgHGs9hqck10yg
nm/QJcJhxZtCcQ7++yBOGBrff5eFJ0sVKrCsn0wgDqJEg/zKXDBXdIsP
-----END CERTIFICATE-----
subject=/C=US/ST=New Jersey/L=Wayne/O=Toysrus/OU=Digital/CN=*.[domain]
issuer=/C=US/O=Symantec Corporation/OU=Symantec Trust Network/CN=Symantec Class 3 Secure Server CA - G4
---
No client certificate CA names sent
---
SSL handshake has read 3787 bytes and written 468 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: 6806E2178EB1862FF4511659A4B8D2EC6AE3BA5A27A6DBEF0D8FBCFE516AE6F2
    Session-ID-ctx: 
    Master-Key: F045F6538C18FD01F9C67CC99DA3035687990AD6F95E6CFC391781F9CF240CFBA6DAA4E10DFE339A241C44FAA1BB6DAD
    TLS session ticket lifetime hint: 7200 (seconds)
    TLS session ticket:
    0000 - 00 00 2a 10 1b fa 0b 53-71 c5 5d ec d1 d5 ef 6d   ..*....Sq.]....m
    0010 - 83 09 21 4f 1f c5 d1 89-e1 70 f4 45 5e f7 2f f6   ..!O.....p.E^./.
    0020 - 76 8c 76 73 ea 1c 07 e8-c4 ff 73 9f 71 79 8e 2d   v.vs......s.qy.-
    0030 - 56 26 30 68 f0 ac f1 9c-2e 22 f2 2c cd 32 59 2c   V&0h.....".,.2Y,
    0040 - a9 4e b1 78 08 8e a1 ca-2a 95 8c 63 62 9e 69 47   .N.x....*..cb.iG
    0050 - 3a 36 5d eb a2 af 89 da-5e 31 69 c1 e1 85 fb 90   :6].....^1i.....
    0060 - 2b 12 92 06 da 70 4d 4c-43 08 aa 36 17 1b c9 bf   +....pMLC..6....
    0070 - 03 d5 0d c8 f4 b5 75 5f-a1 65 60 d5 42 60 30 50   ......u_.e`.B`0P
    0080 - bf 44 19 0c 17 d5 75 c5-82 9e df f3 23 5c ec 32   .D....u.....#\.2
    0090 - 2f 7c df 3c e2 41 1b ea-f2 95 45 0a 39 84 5f 22   /|.<.A....E.9._"
    00a0 - ab 19 d9 e0 ac d7 4c 79-97 2c ea e8 18 99 96 01   ......Ly.,......

    Start Time: 1511879931
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
closed

**Comment by AndrewMishchenko** [comment]
@kmike Also i just tested same proxies with python requests module:
`for i in range(10):
    r = requests.get(url=url, headers=headers, proxies=proxies)
    print(r.status_code)
`
it worked pretty good and stable and also without delays

**Comment by chriscypher** [comment]
@AndrewMischenko, try this to verify if the right set of proxies being set in your request. 
```for i in range(10): 
           r = requests.get(url='http://www.icanhazip.com', headers=headers, proxies=proxies) print(r.content)```

**Comment by AndrewMishchenko** [comment]
@chriscypher sure, content is exactly what i need

**Comment by AndrewMishchenko** [comment]
@chriscypher oh, excuse me i got "b''"

**Comment by AndrewMishchenko** [comment]
@chriscypher but for site i want to crawl it works, but with varied success

**Comment by AndrewMishchenko** [comment]
i think its better to show you the [https://toysrus.com](url)

**Comment by Gallaecio** [comment]
You said this is reproducible even with Crawlera. Could you share a code snippet to reproduce this issue, including the target URL that causes the issue, and just leaving out your Crawlera key?

**Comment by Gallaecio** [comment]
Closing due to a lack of feedback.
