### ISSUE TITLE
Invalid DNS pattern

### ISSUE THREAD

**Issue by cp2587** [scrapy/scrapy#3029]
Hello,

We are using https proxies to crawl some website and sometimes i get the following stack trace:

```
Error during info_callback
Traceback (most recent call last):
  File "/home/wirebot/.virtualenvs/cayzn_tracking.scraping/local/lib/python2.7/site-packages/twisted/protocols/tls.py", line 315, in dataReceived
    self._checkHandshakeStatus()
  File "/home/wirebot/.virtualenvs/cayzn_tracking.scraping/local/lib/python2.7/site-packages/twisted/protocols/tls.py", line 235, in _checkHandshakeStatus
    self._tlsConnection.do_handshake()
  File "/home/wirebot/.virtualenvs/cayzn_tracking.scraping/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 1442, in do_handshake
    result = _lib.SSL_do_handshake(self._ssl)
  File "/home/wirebot/.virtualenvs/cayzn_tracking.scraping/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 933, in wrapper
    callback(Connection._reverse_mapping[ssl], where, return_code)
--- <exception caught here> ---
  File "/home/wirebot/.virtualenvs/cayzn_tracking.scraping/local/lib/python2.7/site-packages/twisted/internet/_sslverify.py", line 1102, in infoCallback
    return wrapped(connection, where, ret)
  File "/home/wirebot/.virtualenvs/cayzn_tracking.scraping/local/lib/python2.7/site-packages/scrapy/core/downloader/tls.py", line 67, in _identityVerifyingInfoCallback
    verifyHostname(connection, self._hostnameASCII)
  File "/home/wirebot/.virtualenvs/cayzn_tracking.scraping/local/lib/python2.7/site-packages/service_identity/pyopenssl.py", line 44, in verify_hostname
    cert_patterns=extract_ids(connection.get_peer_certificate()),
  File "/home/wirebot/.virtualenvs/cayzn_tracking.scraping/local/lib/python2.7/site-packages/service_identity/pyopenssl.py", line 73, in extract_ids
    ids.append(DNSPattern(n.getComponent().asOctets()))
  File "/home/wirebot/.virtualenvs/cayzn_tracking.scraping/local/lib/python2.7/site-packages/service_identity/_common.py", line 156, in __init__
    "Invalid DNS pattern {0!r}.".format(pattern)
service_identity.exceptions.CertificateError: Invalid DNS pattern '194.167.13.105'.
```

I think this issue is somewhat similar to https://github.com/scrapy/scrapy/issues/2092 and this 'invalid DNS pattern' error should be caught similarly as the 'Invalid DNS-ID'. What do you think ?

In the meantime, how can i catch it myself and silent it ?

**Comment by VMRuiz** [comment]
Hello @cp2587 ,

Could you add some extra details like, what site where you crawling?

I would say that, the certificate was created using an IP as a hostname, and, altought is possible to do something like that, a lot of systems mark them as invalid.

In the mean while you can use a [DOWNLOADER_CLIENTCONTEXTFACTORY](https://doc.scrapy.org/en/latest/topics/settings.html#downloader-clientcontextfactory) which captures the  `service_identity.exceptions.CertificateError` and ignores it.

**Comment by jslay88** [comment]
This is what appears to be the issue.

Certificates issued to IP addresses are still supported in modern browsers, it should be supported here.

Can repro with `scrapy shell https://110.249.218.86:9443/`

**Comment by oximer** [comment]
Any news about this issue?

**Comment by jslay88** [comment]
The fix has been merged into master, but not into a new release yet.

Appears it will be in the next release. If you cannot wait for next release, then you can clone master to receive the fix.

**Comment by oximer** [comment]
I'm using DocSearch from algolia. 
I need a builded version of it, so that I can update it on my pip requirements. =/

**Comment by jslay88** [comment]
https://stackoverflow.com/questions/4830856/is-it-possible-to-use-pip-to-install-a-package-from-a-private-github-repository

**Comment by oximer** [comment]
Thanks! I didn't know that.

Unfortunately, I running it on a docker environment. Thus, I will have to lost some our to make git available there. 

Any prevision to build version of it?

**Comment by dangra** [comment]
@oximer We are looking forward to release Scrapy 1.6.0 by next week.

But you don't need git to install Scrapy from master branch, you include the following line in your requirements.txt:

```
https://github.com/scrapy/scrapy/archive/6f5c39d.zip#egg=Scrapy
``` 

6f5c39d is the commit id for the last commit on master branch at the moment.

**Comment by oximer** [comment]
@dangra thanks for you help!
Actually, I manage to fix it, running it against a local server.
I started my website locally and pointed to it, instead of the production version.

**Comment by Tylones** [comment]
> @oximer We are looking forward to release Scrapy 1.6.0 by next week.
> 
> But you don't need git to install Scrapy from master branch, you can include the following line in your requirements.txt instead:
> 
> ```
> https://github.com/scrapy/scrapy/archive/6f5c39d.zip#egg=Scrapy
> ```
> [6f5c39d](https://github.com/scrapy/scrapy/commit/6f5c39d65f3e5d74c292f2143b4f84c7f43b155a) is the commit id for the last commit on master branch at the moment.

@dangra 
Hello,

I'm having the same issue as cp2587. I'd like to try using this version of Scrapy from the master branch to see if it fixes my problem but I can't find the "requirements.txt" file you spoke about. 

I installed Scrapy using Anaconda.

Do you have any idea of how I could do ? I do not have admin privileges over the computer where I should install and run Scrapy and I am lost

**Comment by jslay88** [comment]
It takes about 20s to look at the file structure to realize `requirements.txt` has been renamed to `requirements-py2.txt` and `requirements-py3.txt` accordingly depending on the env you are running.
