### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in C:\Users\esmer\AppData\Local\Temp\pip-build-spxq918q\Twisted\ 

### ISSUE THREAD

**Issue by aldaaga** [scrapy/scrapy#3033]
Hi,
I'm trying to install to install Scrapy on Python 3.6.3 and I already installed Anaconda.
I'm receiving an error as below:
Command "python setup.py egg_info" failed with error code 1 in C:\Users\esmer\AppData\Local\Temp\pip-build-spxq918q\Twisted\

I'm not sure what's the problem as didn't do anything rather than that.
I have had installed and uninstalled Python, Anaconda & Scrapy though.

Does anyone have any clue? Thank you!

**Comment by aldaaga** [comment]
As I saw in a forum on Github, I also tried this:

C:\Users\esmer>pip install --upgrade setuptools
Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03E88170>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/setuptools/
Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03BAD070>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/setuptools/
Collecting setuptools
  Downloading setuptools-38.2.4-py2.py3-none-any.whl (489kB)
    100% |████████████████████████████████| 491kB 489kB/s
Installing collected packages: setuptools
  Found existing installation: setuptools 28.8.0
    Uninstalling setuptools-28.8.0:
      Successfully uninstalled setuptools-28.8.0
Successfully installed setuptools-38.2.4

C:\Users\esmer>
C:\Users\esmer>pip install Scrapy
Collecting Scrapy
  Using cached Scrapy-1.4.0-py2.py3-none-any.whl
Collecting Twisted>=13.1.0 (from Scrapy)
  Using cached Twisted-17.9.0.tar.bz2
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.python.org/simple/incremental/: timed out -- Some packages may not be found!
    Couldn't find index page for 'incremental' (maybe misspelled?)
    Download error on https://pypi.python.org/simple/: timed out -- Some packages may not be found!
    No local packages or working download links found for incremental>=16.10.1
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\esmer\AppData\Local\Temp\pip-build-eosq_w6r\Twisted\setup.py", line 21, in <module>
        setuptools.setup(**_setup["getSetupArgs"]())
      File "c:\users\esmer\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\__init__.py", line 128, in setup
        _install_setup_requires(attrs)
      File "c:\users\esmer\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\__init__.py", line 123, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "c:\users\esmer\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\dist.py", line 455, in fetch_build_eggs
        replace_conflicting=True,
      File "c:\users\esmer\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 866, in resolve
        replace_conflicting=replace_conflicting
      File "c:\users\esmer\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 1146, in best_match
        return self.obtain(req, installer)
      File "c:\users\esmer\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 1158, in obtain
        return installer(requirement)
      File "c:\users\esmer\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\dist.py", line 522, in fetch_build_egg
        return cmd.easy_install(req)
      File "c:\users\esmer\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\command\easy_install.py", line 667, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('incremental>=16.10.1')

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\esmer\AppData\Local\Temp\pip-build-eosq_w6r\Twisted\

**Comment by raphapassini** [comment]
Hey @aldaaga seems to me that the problem is with the ``incremental`` package. 

```
raise DistutilsError(msg)
distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('incremental>=16.10.1')
```
Try to install just the incremental package _before_ installing scrapy, you can do so by typing: ```pip install incremental==17.5.0```

**Comment by kmike** [comment]
There are many timeout errors, it looks like network is unreliable. This doesn't look like a Scrapy issue, more like a general configuration issue (maybe there is a system-wide proxy which makes downloads unreliable?). You may have the same issue installing any other Python package. 

I suggest using https://stackoverflow.com to solve it, as we're trying to use Scrapy issue tracker to track Scrapy bugs and feature proposals, not as a general support channel.

**Comment by boboyejj** [comment]
@raphapassini Thank you for your answer. It worked in my case.

**Comment by VomPom** [comment]
@raphapassini Thank you very much,i solved my problem.

**Comment by ramuthumu** [comment]
@raphapassini  Thanks

**Comment by ManarArabi** [comment]
> @raphapassini Thank you very much,i solved my problem.

What did you do
