### ISSUE TITLE
Line-ends (unnecessary blank lines) problem in CSV export on Windows 

### ISSUE THREAD

**Issue by ReLLL** [scrapy/scrapy#3034]
CSV export on Windows create unnecessary blank lines after each line.

You can fix the problem just by adding 
newline='' 
as parameter to io.TextIOWrapper in the __init__ method of the CsvItemExporter class in scrapy.exporters

Details are over here:
https://stackoverflow.com/questions/39477662/scrapy-csv-file-has-uniform-empty-rows/43394566#43394566

**Comment by andrewnuk1** [comment]
Ah, i will try that.  I came across this problem several months ago with Windows10 and solved it by adding code in the pipelines.py file to re-open the cvs file with the blank lines and eliminate those lines once the spider had run.

Details are here: https://github.com/andrewnuk1/Python3-Scrapy-Projects/blob/master/Pipelines.py starting at line 42 “#given I am using Windows i need to elimate the blank lines in the csv file”

**Comment by ReLLL** [comment]
Yep,  would like to have this incorporated in next version.  Until then, if anyone wants to try this fix, just dont forget the compile package source code after modifying.     **python -m compileall .**
 command in in the package source folder will compile all files.  I just modified the **exporters.py** scrapy source in "site-packages\scrapy" folder of python installation.

**Comment by raphapassini** [comment]
I think it's a nice and easy fix to have implemented in scrapy. Let's see @kmike thoughts on it.

**Comment by kmike** [comment]
It looks reasonable to me; I'm fine with merging such pull requests, given that tests pass.

**Comment by plartoo** [comment]
I ran into the same issue using Scrapy 1.5.0. I tried to add the patch as @ReLLL suggested above and compiled the Scrapy package in the folder, "C:\Users\me\AppData\Local\Programs\Python\Python36-32\Lib\site-packages\scrapy",using 
>> python -m compileall . 
but newlines still show up. Just wanted to bring this up again so that maybe the fix can be merged in the official release soon. Thank you for all your hard work!

**Comment by ReLLL** [comment]
hi @kmike ,  yes I tested it both on windows and linux, works fine on both. And it is actually the way it should be, looking at the python documentation, we need to specify newline=''.  So that is what I just did in my pull request.  You can merge it. without any problems.

**Comment by ReLLL** [comment]
@plartoo,  yea it should be merged.    You need to run "python -m compileall" in "C:\Users\me\AppData\Local\Programs\Python\Python36-32\Lib\site-packages\scrapy folder, and make sure your python  uses this path to find scrapy.  (If you use venv  , it might use another copy etc.)  Otherwise it works fine here, make sure the compiled right copy of scrapy is used

**Comment by ftesser** [comment]
Hi, I have seen that this PR is not released yet. When do you plan to release this PR?
