### ISSUE TITLE
File downloaded by pipeline are blank

### ISSUE THREAD

**Issue by exotfboy** [scrapy/scrapy#3036]
I have deployed a spider in my remote server, and I am using `FilePipeline` to download images for `item`, however I found that the downloaded image have size of  zero, which is not expected.

Then I test the project in my local machine, it worked. So I think maybe my remote server has been banned, however when I tried `wget ..` I can download the image normally, and I also tried `scrapy sheel image_src` it still work.

Now I have no idea what's going on , I just want to intercept the response of the request re-sent by the pipeline, is it possible?

**Comment by exotfboy** [comment]
Hi, after using the SSH port forwarding I redirect the http requests to my local fiddler, and it seems that the web pages and images are all fetched successfully , and the content is not empty. 

So I wonder why the saved file is blank?

**Comment by cathalgarvey** [comment]
Hi @exotfboy,

When you get empty results on your remote server, are they *all* empty, or just most of them? It's possible you're getting a rate-limitation effect, where the first few (or wget examples) work OK but subsequent ones fail?

**Comment by exotfboy** [comment]
@cathalgarvey  It seems your are right, some of the files are blank some of them are not.

**Comment by cathalgarvey** [comment]
@exotfboy - Well, I'd take that as a positive sign; if the server response to `wget` (without custom user-agent, I'm assuming), then it seems to be pretty crawling-friendly, as long as you moderate your crawling rate. If you look at their `/robots.txt` file you may see some suggested rate-limits, which you can use with Autothrottle's target concurrency setting, or with a hard download delay?

**Comment by exotfboy** [comment]
@cathalgarvey  I use the delay of `1s`.

**Comment by cathalgarvey** [comment]
Hi @exotfboy, sorry not to follow up since; has your issue been solved? May I close this issue report? :)
