### ISSUE TITLE
Unable to build scrapy based project due to invalid environment marker error

### ISSUE THREAD

**Issue by rgupta2** [scrapy/scrapy#3037]
I am unable to build one of my projects written few months ago using Scrapy. Its showing following dependency error -

```
Downloading/unpacking cryptography>=2.1.4 (from pyOpenSSL->Scrapy==1.4.0->-r /app/requirements.txt (line 3))
  Running setup.py (path:/tmp/pip_build_root/cryptography/setup.py) egg_info for package cryptography
    error in cryptography setup command: Invalid environment marker: platform_python_implementation != 'PyPy'
    Complete output from command python setup.py egg_info:
    error in cryptography setup command: Invalid environment marker: platform_python_implementation != 'PyPy'
```

As I have no control over Scrapy's dependencies and I have been using Scrapy 1.4.0, latest release, alongwith Python 3, I am not sure what are my options now?

Following is the command I use to install the dependencies

> pip3 install -r requirements.txt

Following is what my requirements.txt looks like

```
lxml==3.8.0
psycopg2==2.7.3.1
Scrapy==1.4.0
Twisted==17.5.0
validators==0.12.0
tweepy==3.5.0
```

I also posted the same on [Stackoverflow](https://stackoverflow.com/questions/47766609/unable-to-build-scrapy-based-project-due-to-invalid-environment-marker-error).

**Comment by kmike** [comment]
What is your pip version? 

Note that this is an error during installation of `cryptography` package; even though it is a Scrapy dependency, we don't maintain or support this package. It has a separate issue tracker (https://github.com/pyca/cryptography/issues), and separate install instructions (https://cryptography.io/en/latest/installation/). 

Generally we expect Scrapy install instructions to cover issus with dependencies though, so if you figure out what's missing, it'd be good to add that to Scrapy docs.

**Comment by rgupta2** [comment]
this was an issue with pip upgrade. after upgrading pip, the build went fine.
