### ISSUE TITLE
Is it one pipeline instance shared by all spiders?

### ISSUE THREAD

**Issue by holymonson** [scrapy/scrapy#3042]
As `Pipeline` implements `pipeline.open_spider(spider)` and `pipeline.close_spider(spider)`, I assume that there is one pipeline instance shared by all spiders, instead of one pipeline instance owned by each spider, when runing multiple spiders in the same process.

Now I want to setup a db client in pipepline for all spiders shared instead of one client for each spider, but there is no `open_pipeline` and `close_pipeline` implemented.

So, is the statement above correct? Would you consider implementing `open_pipeline` and `close_pipeline`? Or `open_crawler` `close_crawler`?

**Comment by elacuesta** [comment]
You can use Scrapy signals (https://doc.scrapy.org/en/latest/topics/signals.html#module-scrapy.signals). In this particular case, I think `engine_started` and `engine_stopped` are probably the ones you're looking for.

**Comment by kmike** [comment]
Pipelines are not shared between multiple spiders in the same process, each spider gets its own pipeline instance. If you need to share DB client it is better to do this outside a pipeline - use a global varibale (ouch!), or make it tied to CrawlerRunner / CrawlerProcess.

I'm closing this issue, as we're trying to us Scrapy issue tracker for Scrapy bugs. There are better support channels like https://stackoverflow.com (use tag "Scrapy") or https://www.reddit.com/r/scrapy/.

**Comment by manozzo** [comment]
Better later than never!

You can use Extensions. You can instantiate the database connection and use inside your pipelines.
