### ISSUE TITLE
[bug] pillow will always recode images in imagepipieline

### ISSUE THREAD

**Issue by NewUserHa** [scrapy/scrapy#3055]
https://github.com/scrapy/scrapy/blob/aa83e159c97b441167d0510064204681bbc93f21/scrapy/pipelines/images.py#L151

this line will always recode images silently and damage the image quality.

please add an option to avoid this.

**Comment by raphapassini** [comment]
Well, seems reasonable to me, but you can simply extend the default image pipeline and override the method to do what you want.

**Comment by NewUserHa** [comment]
I don't know image pipeline of scrapy will always damage the quality of image, even after have read scrapy's documents.

**Comment by cathalgarvey** [comment]
Hi @NewUserHa - I'm sorry this has been a problem for you! The documents do say, at the higher-level overview, that [the images pipeline will convert all images to a common format](https://github.com/scrapy/scrapy/blob/1.5/docs/topics/media-pipeline.rst#L23), namely JPG with RGBA colourspace.

I think similarly to you, that unless the user explicitly requests recoding, the images would be better left alone. But, that's one of the big differences between simply using the Files pipeline and the Images pipeline, I guess. I'd suggest using the Files pipeline for now, if you want the unaltered images to be exactly as they occur online.

**Comment by NewUserHa** [comment]
I meant images pipeline will still convert a jpg file to a less quality jpg file. is that a problem?

**Comment by cathalgarvey** [comment]
I'd need to read the code again to see whether quality is 'expected' to change under normal conditions.. but I do think there's a problem with the docs if this behaviour is surprising.

**Comment by NewUserHa** [comment]
it's a problem. jpg encoding is lossy. pillow shouldn't reencode jpg to jpg at least

**Comment by Gallaecio** [comment]
I believe the documentation is OK.

> The Images Pipeline uses `Pillow`_ for thumbnailing and normalizing images to JPEG/RGB format.

It says `JPEG/RGB`. The `RGB` part must be the culprit of the quality change @NewUserHa is experiencing.

I’ve checked the code and `JPEG/RGB` images are not converted.

@NewUserHa If you believe they are, please share an example image that gets converted and should not. Otherwise, I believe we should close this issue.

**Comment by NewUserHa** [comment]
Did you try yourself?
`Image.open('a.jpg').save('b.jpg', 'JPEG')`
I just pick a jpg randomly and run it with the above code, and it was re-encoded just like my last try.

DID you really double check it ?
picture info:
```
JPEG, quality: 77, subsampling ON (2x2)
16,7 Million   (24 BitsPerPixel)
```

**Comment by Gallaecio** [comment]
It converts images that are JPEG *but not RGB*.

**Comment by Gallaecio** [comment]
If that is so, please provide the smallest image possible that allows to reproduce the issue. It can be used to test a fix.

**Comment by NewUserHa** [comment]
![Q20161115204613](https://user-images.githubusercontent.com/32261870/54168432-6bc8e300-44a9-11e9-92d6-222201c18165.jpg)

**Comment by Gallaecio** [comment]
Although I could not visually appreciate any difference, `Image.open('original.jpg').save('modified.jpg', 'JPEG')` does indeed slightly reduce the image size. `Image.open('original.jpg').save('modified.jpg', 'JPEG', quality='keep')` does not maintain the size, it increases it instead.

I think we could consider modifying `convert_image` to accept `BytesIO(response.body)` as a second parameter, and return it as `buf` when no conversion is necessary. @cathalgarvey I think this could be a good first issue.

**Comment by elacuesta** [comment]
@drs-11 By all means, be our guest. The scenario is covered in our [contributing guidelines](https://docs.scrapy.org/en/latest/contributing.html#submitting-patches):

> Sometimes there is an existing pull request for the problem you’d like to solve, which is stalled for some reason. Often the pull request is in a right direction, but changes are requested by Scrapy maintainers, and the original pull request author hasn’t had time to address them. In this case consider picking up this pull request: open a new pull request with all commits from the original pull request, as well as additional changes to address the raised issues. Doing so helps a lot; it is not considered rude as soon as the original author is acknowledged by keeping his/her commits.
