### ISSUE TITLE
How can I set the spider name dynamicly?

### ISSUE THREAD

**Issue by xuexingdong** [scrapy/scrapy#3063]
I want to store my spider name in database, and load it like this, but why it doesn't work?
```python
process = CrawlerProcess(get_project_settings())
    for spider_config in spiders_configs:
        process.crawl(XXXSpider(spider_config.name))
    process.start()
```

**Comment by kmike** [comment]
CrawlerProcess.crawl expects Spider class object, not a Spider instance - see https://doc.scrapy.org/en/latest/topics/api.html#scrapy.crawler.CrawlerProcess.crawl. Something like that could work: `process.crawl(XXXSpider, spider_config.name)`

**Comment by xuexingdong** [comment]
Thanks for reply and it works fine! I should read the doc more carefully.
