### ISSUE TITLE
about the signal retry_complete

### ISSUE THREAD

**Issue by lifei1245** [scrapy/scrapy#3069]
I didn't find the singnal in the singnal list,how can I use it

**Comment by cathalgarvey** [comment]
[Searching for the signal](https://github.com/scrapy/scrapy/search?utf8=%E2%9C%93&q=retry_complete&type=), I only found a mention of it in the docstrings for middleware, but it appears nowhere in the code. On a local copy of the Scrapy git project, I ran:

`$ git rev-list --all | xargs git grep retry_complete | grep -v 'so other extensions'`

..and got nothing. The signal seems to be mentioned only in the docstrings, and it predates the migration to Git. It may be a case of outdated docs?

**Comment by silviaclaire** [comment]
Pull request #3668 needs to be merged. Docstrings still talks about the unexisting signal.
