### ISSUE TITLE
Pipelines don't get applied on items when running spider with `scrapy parse`

### ISSUE THREAD

**Issue by roboostify** [scrapy/scrapy#3070]
I usually test my spiders with the command `scrapy parse --spider=myspider -c parse_whatever <url_to_scrape>`.
So far it worked out well, but when I want to apply a pipeline on my items it just doesn't work, at least it seems like the pipeline is skipped during execution, however the log says that the pipeline is enabled.

So for example, I have the following `Item`, `Spider` and `Pipeline` to test the issue:

_Item:_
```python
class MyItem(scrapy.Item):
    status = scrapy.Field()
    date_created = scrapy.Field()
    site = scrapy.Field()
```
_Spider:_
```python
class TestSpider(Spider):
    name = 'test'
    start_urls = ['http://www.example.com',]

    def parse(self, response):
        item = ProductPriceItem()
        yield item
```

_Pipeline:_
```python

class DefaultValuePipeline(object):
    def process_item(self, item, spider):
        item.setdefault('status', 'New')
        item.setdefault('date_created', '01/12/2018')
        item.setdefault('site',  'example.com')

        return item
```

And my problem is when I execute the spider as:
`scrapy parse --spider=test -c parse http://example.com`

It will output:
```bash
# Scraped Items  ------------------------------------------------------------
[{}]
```

While using:
`scrapy crawl test`
Will output:
```bash
2018-01-11 12:05:54 [scrapy.core.scraper] DEBUG: Scraped from <200 http://www.example.com>
{'date_created': '01/12/2018',
 'site': 'example.com',
 'status': 'New'}
```
As expected.

Am I missing something or it's a bug?

**Comment by cathalgarvey** [comment]
Hey, interesting issue!

As I understand it, the Scrapy `parse` command is designed for this kind of debugging at the extraction level, and perhaps for some lightweight on-demand crawling. But, Pipelines are not always used for simply modifying items, they sometimes (or often) have side-effects that might not be desired when testing. For example, Pipelines can be used to deliver items to a live database, which isn't ideal during testing.

However, it's clear that sometimes, Pipelines are used to "polish" items or enrich them somehow, so the absence of pipelines does limit its usefulness in those cases.

I don't know whether adding this functionality (optionally enabling some or all pipelines) would be a big job, or a small job. Watch this space. :)

**Comment by cathalgarvey** [comment]
@roboostify - I looked into the code.. only to discover the long way that there's already an option for this. :) When I call `scrapy parse -h`, I get the following option: `--pipelines             process items through pipelines` - Could you check whether you have this option also? If not, try upgrading your Scrapy install and try again?

**Comment by roboostify** [comment]
@cathalgarvey Nice one! Actually applying the `--pipeline` or `--pipelines` flag solves the issue!
Thanks for your answer!
