### ISSUE TITLE
 Cxfreeze+python3.4+scrapy1.4 failed to bundle to executables(AttributeError: module object has no attribute '_fix_up_module')

### ISSUE THREAD

**Issue by Caleb-Wade** [scrapy/scrapy#3074]
After I failed to bundle .py document into .exe document by pyinstaller, I tried cxfreeze. Similar error happened. Someting went wrong when importing scrapy module, and AttributeError: module object has no attribute '_fix_up_module' appeared in the command window. Would someone tell me what happened. Can I make it? Thks!

**Comment by cathalgarvey** [comment]
Hi @Caleb-Wade, neither CX-Freeze nor PyInstaller are supported packaging systems for Scrapy. They might work! But, I don't think we've ever made a special effort to make that process easier. So, for advice on those, I suggest asking on Reddit or StackOverflow. Possibly someone there has done something like this before, and can help you solve it.

If you do figure it out, though, a guide or tutorial on packaging Scrapy spiders in this way would be very interesting to read. It would be kinda cool if we _could_ make this an easier process for Scrapy users; I can see how it would make life easier for Windows users, where installing stuff isn't as easy as Linux.
