### ISSUE TITLE
DEBUG: Crawled (407)

### ISSUE THREAD

**Issue by Svickie7** [scrapy/scrapy#3091]
>>> fetch("http://wwww.google.com/")
2018-01-25 18:46:23 [scrapy.core.engine] INFO: Spider opened
2018-01-25 18:46:27 [scrapy.core.engine] DEBUG: Crawled (407) <GET http://wwww.g
oogle.com/> (referer: None)
>>>

**Comment by cathalgarvey** [comment]
Hi @Svickie7 - [the 407 status code](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#4xx_Client_errors) indicates that Proxy authentication is required. It would be an unusual or inappropriate code for Google to return, so I'm guessing there's something closer to your computer at fault.

When you were in this shell session, were you behind a paywalled Wifi network or university network? Or using a proxy of any kind?

Without further information I'm inclined to think this isn't an issue with Scrapy. Thanks for raising it, though.

**Comment by cathalgarvey** [comment]
Hi, I'm closing this, for now. Feel free to come back with more information if this still affects your spiders in future, though. :) Thanks!

**Comment by twober8** [comment]
Hi ,I just install 'scrapy-crawlera' through pip then on setting page i add
DOWNLOADER_MIDDLEWARES = {
'scrapy_crawlera.CrawleraMiddleware': 610
}
CRAWLERA_ENABLED = True
CRAWLERA_APIKEY = 'my_api'

And error comes :2018-05-28 02:34:48 [scrapy.core.engine] DEBUG: Crawled (407) <GET http://quotes.toscrape.com/page/1/> (referer: None)
please tell
