### ISSUE TITLE
Wrong file to log

### ISSUE THREAD

**Issue by edurenye** [scrapy/scrapy#3094]
I'm running multiple CrawlerRunner to crawl parallel sites, each CrawlerRunner has configured a different LOG_FILE.
When I run it, all the files just have logged the initialization of the Spider, until the line `[scrapy.core.engine] INFO: Spider opened`
then all log into the same file.

I expect that each Spider logs into his configured file.

**Comment by cathalgarvey** [comment]
Hi @edurenye - It might help us to debug your issue if we could have a minimal sample of code to show the issue? This does sound like a bug. :)

**Comment by Gallaecio** [comment]
Closing due to a lack of feedback from the author.
