### ISSUE TITLE
`item_urls` is not defined in example

### ISSUE THREAD

**Issue by tobiasfielitz** [scrapy/scrapy#3097]
[here](https://github.com/scrapy/scrapy/blob/1.5/docs/topics/debug.rst) in `def parse`

**Comment by kmike** [comment]
Hey @tobiasfielitz,

It seems the comment in `parse` method is not 100% clear: the idea is that a spider is not a complete example, but there is some code which should collect `item_urls`. The same happens in other `parse_..` methods. Do you have suggestions how to improve it, to make it more clear? Pull requests are welcome :)

**Comment by FannyVieira** [comment]
Are item_urls those defined  in the url of the response?

**Comment by cathalgarvey** [comment]
Hi @FannyVieira - I think the comment on [line 21](https://github.com/scrapy/scrapy/blame/1.5/docs/topics/debug.rst#L21), and other comments like it, are supposed to be placeholders for code-that's-not-included-in-this-demo. So `item_urls` is simply assumed to be parsed somehow from the response, but we don't show how that happened.

This isn't clear to everyone, so either we should:

* Include a minimal-but-complete example where all variables are extracted and defined fully
* Change the way we present "stuff happened, but we didn't show you" in the examples. Maybe show the variables being defined by a method call, but the method-body is commented as `# < processing code not shown >` to be super clear.

By the way, are you interested in [GSoC 2018](http://gsoc2018.scrapinghub.com/participate/)? :)

**Comment by malikrohit16** [comment]
I think may be item_urls refers to start_urls.

**Comment by bhaveshpoddar94** [comment]
First Time Contributor. Can I take a look into it?

**Comment by FannyVieira** [comment]
Hi @cathalgarvey so by what I understand url items is the same as self.start_urls? If it's just that, I can open a pr to make the necessary changes..
Yes, I really want to participate in GSOC, I study computer science but i have seventeen years old, Can I participate anyway?

**Comment by malikrohit16** [comment]
Hello @FannyVieira i am afraid that you won't be able to participate this year but you still can contribute to the community if you like. This will give you upper hand for the next year.

**Comment by cathalgarvey** [comment]
Hi @FannyVieira - Well, if you turn 18 before 27th March, I think you can still apply under the PSF and related orgs like Scrapinghub. Otherwise, please keep us in mind for next year! And if you're keen to contribute, go right ahead and don't be afraid to ask for advice. :)

**Comment by ayushmankoul** [comment]
Hello, @cathalgarvey I am first time contributor to scrapy community.I want to participate in GSoC 2018 and how can I prepare for the same.

**Comment by JoyBhalla** [comment]
Is this still open ?

**Comment by hundredrab** [comment]
Hello. Can I work on this?
Thanks!

**Comment by jfflisikowski** [comment]
I'll try to do a PR today around evening

**Comment by Jobandeep2417** [comment]
Hi guys i wanted to contribute to this issue ,can you tell me from where to start.
It will be very helpful for me. Thanks .

**Comment by mandarvaze** [comment]
If the PR for this is Merged, shouldn't this issue be marked as "Closed" ? (help prevent new contributors from coming here, to already closed issue.)
