### ISSUE TITLE
Error in extract data in span tag

### ISSUE THREAD

**Issue by Svickie7** [scrapy/scrapy#3098]
this in my website inspect element 
""""""<_span id="price_MP000000001881735"> ₹999<_/span>"""""""""""

in my scrapy shell
>>> ww.css('.old > .priceFormat > span::text').extract()[0]
u' \u20b91499'

>>> ww.xpath('//p[@class="old"]/span[@class="priceFormat"]/span').extract_first()
u'<span id="mrpprice_MP000000001881735"> \u20b91499</span>'

>>> ww.xpath('//p[@class="old"]/span[@class="priceFormat"]/span/text()').extract_first()
u' \u20b91499'

I need a result like 
₹999 or 999

**Comment by hundredrab** [comment]
You should use regex to clean the data:
`response.xpath('//*[@itemprop="price"][1]/text()').re('[.0-9]+')`
[u'999']

**Comment by kmike** [comment]
This is not a bug, and the result look correct:

```py
>>> print(u' \u20b91499')
₹1499
```

You see these strange escape chars because by default Python 2 uses ascii-safe repr for unicode strings. In Python3 it shows a human-readable value right away.
