### ISSUE TITLE
better way to ignore next parse and use next next parse if its page doesn't exist.

### ISSUE THREAD

**Issue by NewUserHa** [scrapy/scrapy#3112]
```
def parse..
  next_page = href
  item={..}
  response.follow(href, self.b, mata={'item': item})
def b..
  ..
  item= response..
  response.follow(...meta={'item': item}
def c...
```

their results have to be chained into one item from the first method,  but how to jump to next method if a next_page of one method doesn't exist. Is there a best way to achieve except making a dict consist of next_page:parse and poping called method out one by one?
Thanks.

**Comment by kmike** [comment]
Hey @NewUserHa,

We're using Scrapy issue tracker to track Scrapy bugs and discuss new Scrapy features; for support there are better channels like https://stackoverflow.com (use tag "scrapy") or https://www.reddit.com/r/scrapy/.
