### ISSUE TITLE
Can't paginate a ASP.NET WebForms website

### ISSUE THREAD

**Issue by Urahara** [scrapy/scrapy#3114]
So i have a site that is made using ASP.NET (WebForms).

I was able to log in and even load a page by filtering a comboBox but when i try to paginate i receive:

> 179|error|500|The page is performing an async postback but the ScriptManager.SupportsPartialRendering property is set to false. Ensure that the property is set to true during an async postback.|

Is there any workaround to crawl this type of site? I see many params on requests i even try send them all but without success. Is scrapy capable of scrapy this? Or is better i will try with Selenium?

**Comment by kmike** [comment]
Hey @Urahara,

We're using Scrapy issue tracker to track Scrapy bugs and discuss new Scrapy features; for support there are better channels like https://stackoverflow.com (use tag "scrapy") or https://www.reddit.com/r/scrapy/.
