### ISSUE TITLE
Contributing to Scrapy in GSoC 2018

### ISSUE THREAD

**Issue by virmht** [scrapy/scrapy#3116]
Hello Mentors and Developers,

I am Viral Mehta, a student at BITS Pilani, Hyderabad Campus. I went through the Scrapy GSoC 2018 ideas page and found all the projects to be very interesting.
I found the projects **Scrapy performance improvement** and **Scrapy spider autorepair**, particularly interesting.
I would love to contribute to Scrapy and participate in GSoC 2018.

You can know more about me on:

Linkedin: https://in.linkedin.com/in/viral-mehta-b76093102
GitHub: https://github.com/virmht

I do have some open source experience and I would like to try my hand by implementing a small new feature and/or resolving bugs.
I will be extremely thankful if someone could guide me regarding the same.

Thanking you.

Regards,
Viral Mehta.

**Comment by cathalgarvey** [comment]
Hi Viral, pleased to meet you. :)
We haven't gotten to the stage of selecting students yet, but it's never too early to start contributing to Scrapy.

When we select students for GSoC, it will be based on:

* Having contributed at least once to Scrapy or a related project
* Providing a detailed project proposal, detailing the proposed changes and the weekly/bi-weekly timeline for their implementation.

For Scrapy Performance, you can dive right in and start exploring, and for Spider autorepair it might be worth looking at [Scrapely](https://github.com/scrapy/scrapely). Autorepair would probably be too big and brittle a feature to integrate directly into Scrapy, but as an optional Extension it would be pretty amazing and entirely novel. Scrapely is one possible way to start implementing this.

If you find anything you're comfortable contributing to, just go ahead and do so! And, when you're ready to submit a proposal for GSoC, we'll be looking forward to it. :)

(I'll close this but feel free to continue the discussion here if you like)

**Comment by cathalgarvey** [comment]
By the way, @virmht - If you'd like some further guidance on contributions or on the proposal document, feel free to ask. :)

**Comment by virmht** [comment]
Thank you very much for the encouraging response. I will start by fixing [this](https://github.com/scrapy/scrapy/issues/3095). I would be glad if you could suggest some more bugs to be fixed or small features that need to be implemented.

**Comment by virmht** [comment]
@cathalgarvey, for my first contribution, I have raised a PR here -  https://github.com/scrapy/scrapy/pull/3124

I wish to know the number of slots alloted to Scrapy and what projects got selected. I believe this would help me in writing proposals for GSoC 2018.

I will be extremely thankful to you if you do the needful.

**Comment by cathalgarvey** [comment]
Hi @virmht - For that PR, I think I'll leave review to @jdemaeyer as it's his issue. But, congratulations and thanks for the contribution! :)
