### ISSUE TITLE
DLL load failed: %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by Zoher15** [scrapy/scrapy#3117]
![image](https://user-images.githubusercontent.com/29090730/36075443-0f1be58e-0f1d-11e8-8aa7-e1353e601b32.png)

Hello,

I have been using scrapy for a while and this did not happen a month ago. I have tried everything possible but this error is not going away. Help would be appreciated.

best,
Zoher

**Comment by cathalgarvey** [comment]
Hey @Zoher15 - I'm sorry to say that this issue does not appear to be related to Scrapy, so I'm not sure that we can help you here. If I had to guess (understanding that I haven't used Windows in years), it looks like something has modified your Twisted install and corrupted a binary module, or installed the wrong binary for your platform.

There are many possible things that could cause this issue; viruses often attack DLLs to inject malicious code (though usually without breaking them), installing new tools can specify new dependency versions, Windows can upgrade and break APIs, and plain old disk corruption can happen. It's possible that the only fix here will be to uninstall and reinstall Twisted. I'd suggest, as a starting point, to try `pip3 install --force-reinstall twisted` and see if that helps.

Good luck!
