### ISSUE TITLE
Write items to MongoDB

### ISSUE THREAD

**Issue by Fingalzzz** [scrapy/scrapy#3120]
Hi I'm new to scrapy and I'm reading official document,  [Write items to MongoDB](https://doc.scrapy.org/en/latest/topics/item-pipeline.html#write-items-to-mongodb) has an example of how to write items into MongoDB. But why we need to get `items` from settings, it seems useless to me. Anyone could tell me why and show me a simple example of what `items` could be. Thanks.

```python
import pymongo

class MongoPipeline(object):

    collection_name = 'scrapy_items'

    def __init__(self, mongo_uri, mongo_db):
        self.mongo_uri = mongo_uri
        self.mongo_db = mongo_db

    @classmethod
    def from_crawler(cls, crawler):
        return cls(
            mongo_uri=crawler.settings.get('MONGO_URI'),
            mongo_db=crawler.settings.get('MONGO_DATABASE', 'items')
        )

    def open_spider(self, spider):
        self.client = pymongo.MongoClient(self.mongo_uri)
        self.db = self.client[self.mongo_db]

    def close_spider(self, spider):
        self.client.close()

    def process_item(self, item, spider):
        self.db[self.collection_name].insert_one(dict(item))
        return item
```

**Comment by lopuhin** [comment]
Hi @Fingalzzz ``MONGO_DATABASE`` (equal to ``items`` in this example) is a name of the mongo database to use.

Note that scrapy issues on github are for bug reports, questions are more suited to stackoverflow (please use scrapy tag).
