### ISSUE TITLE
Can't set settings with ENV SCRAPY_SETTINGS_MODULE

### ISSUE THREAD

**Issue by marcuslind90** [scrapy/scrapy#3121]
I'm running Scrapy in Docker with an `.env` file where I define the `SCRAPY_SETTINGS_MODULE` to decide which settings file I want to load. This throws `ModuleNotFoundError`, even if you point to the existing `settings.py` file and use the default value which will be `myproject.settings`.

I have replicated it with a brand new 1.5.0 project.

**Comment by cathalgarvey** [comment]
Hi @marcuslind90 - Is the Scrapy command executing within the Scrapy project directory?

**Comment by cathalgarvey** [comment]
Hi @marcuslind90 - I'll close this for now, but feel free to re-open if you're still having this issue. I think we'd need a sample Dockerfile to help us debug the issue, though. Thank you!

**Comment by njmhnb** [comment]
I have this problem too, when running DockerFile whithout Env SCRAPY_SETTINGS_MODULE project.settings, everything is ok but when adding this line I get ModuleNotFoundError: No module named 'project'.
