### ISSUE TITLE
Gsoc-discussion

### ISSUE THREAD

**Issue by videetssinghai** [scrapy/scrapy#3130]
Hello,
I am interested in working on the project "Scrapy performance improvement". Can anyone give some brief idea about which area to target exactly?

**Comment by lopuhin** [comment]
Hi, during the last year's GSoC, @Parth-Vader built an extended benchmark suite for scrapy: https://github.com/scrapy/scrapy-bench/. The goal would be to improve performance of scrapy in these benchmarks, and add other benchmarks if needed. One particular area that stands out is that scrapy performance under Python 3 speed is lower than under Python 2. Another one is general performance improvements, like https://github.com/scrapy/parsel/issues/98. We started collecting performance issues under "performance" label: https://github.com/scrapy/scrapy/issues?q=is%3Aissue+is%3Aopen+label%3Aperformance

Please also write to gsoc@scrapinghub.com to introduce yourself, unless you have already done so :)
