### ISSUE TITLE
GSoC 2018: Scrapy spider autorepair

### ISSUE THREAD

**Issue by virmht** [scrapy/scrapy#3138]
Hi! I have already introduced myself [here](https://github.com/scrapy/scrapy/issues/3116). 

I am interested in working on the project: "Scrapy spider autorepair". As suggested by you, @cathalgarvey , I have read about [Scrapely](https://github.com/scrapy/scrapely), its API, how it works, and have a decent understanding of its source code.
I have also read 2 research papers cited on the [Github Scrapely page](https://github.com/scrapy/scrapely).

As per my understanding, scrapely has the following drawbacks when comapared to what is required as stated on the [GSoC 2018 ideas page](http://gsoc2018.scrapinghub.com/ideas/):
1. Scrapely currently does not output rules in the form of XPaths or CSS Selectors.
2. Scrapely currently requires the structure of the test page to remain same or at least similar to the page on which it was trained. In our case, (as described on the ideas page), the content remains same but the structure can change. Currently scrapely looks at the order of elements in the prefix and suffix of the element to be extracted. Hence, it might produce wrong results if the order changes quite drastically but the content remains same.

- One way to deal with issue 2. is to do the following: instead of looking at the order of elements in the prefix and suffix of the element to be extracted(which scrapely does), we need to look at the information or the content of the page around the region of interest and figure out its path in the new page. For example:
```
**Old version of page:**
<parent>
               <child>ABC</child>
               <child>XYZ</child>
</parent>

**New version of page:**
<parent>
               <child>XYZ</child>
               <child>ABC</child>
</parent>
for each element in old version:
        value = element.value // example: value of first child element = 'ABC'
        position = find position of value in new version // position of 'ABC' in new version = /parent/child[2]
        return position
```
**I want to start writing my GSoC 2018 proposal for this project. @cathalgarvey   can you provide some more info about the tasks that should be completed ?**

Thanks.

**Comment by cathalgarvey** [comment]
Hey @virmht - Thanks for this, it's great to see where you've been working on this problem already. It's an open-ended problem, so there are a few ways I could see it being approached. Are you suggesting working more on the Scrapely side of the problem, adjusting the algorithm there to handle unordered content better?

I think @dangra or @ruairif would need to decide whether contributions to Scrapely under GSoC are OK, if so; they're [the mentors most involved in that project](https://github.com/scrapy/scrapely/graphs/contributors).

**Comment by virmht** [comment]
I am actually more interested to work on the Scrapy side of the project, i.e., "Scrapy spider autorepair", though the Scrapely side looks interesting as well :)

@cathalgarvey, can you provide more details about the tasks that need to be completed as part of Gsoc 2018 if I want to work on "Scrapy spider autorepair" ? 
Thanks :)

**Comment by cathalgarvey** [comment]
Hi @virmht - sorry for the slow response, I had a lot to catch up on last week thanks to extreme weather here in Cork! :)

For the Scrapy autorepair project, we're interested in any solution that can help a spider to automatically build new rules to make a crawl work, _when that crawl used to work_. This implies that you've got a spider that works, and you collect some data on the site along with successful results from that site.. and then something changes, and you use the data and results to "repair" the spider.

The repair does not need to be an actual fix to the code. For example, if a page layout changes, but the URL and information on the page remains the same, then a spider could just use Scrapely and some old data/URLs with the new layouts to build a model for the new layout. The spider itself wouldn't actually change or "repair", in this scenario; it would just have the ability to temporarily "patch" itself until you can update the code manually.

A solution like the above would be a valid solution to the GSoC challenge, in my opinion. But how you implement it, what it's designed to fix, what it's _not_ designed to fix, whether it's part of Scrapy or a separate project... all of this is stuff you'd be expected to plan out and propose, first. We don't intend to provide project plans to students; it's important that students do the planning for themselves, so they can choose tasks they are able to deliver on, and to prove that they can plan and execute.

**Comment by virmht** [comment]
Thank you for your guidance, @cathalgarvey. I will start working on my GSoC proposal, and comment the link to the draft of my proposal here in the next 2-4 days.

**Comment by thisisayush** [comment]
@cathalgarvey I have a few doubts, 
1. Are we talking about patching single run of a spider? If not, will the programmer provide the training data from e.g. A Postgresql Database?
2. When do we know that spider has failed to extract data?

**Comment by virmht** [comment]
I think it is safe to close this issue.
