### ISSUE TITLE
permission denied when I install scrapy via conda 

### ISSUE THREAD

**Issue by mayouf** [scrapy/scrapy#3141]
Hi everyone,

In order to start a scrapy project, I just set an ubuntu 16.04 VM. I installed ST3, anaconda 3, smartgit and chrome. That's all.

Since that, I tried to install scrapy by typing a simple:

`conda install scrapy`

and it gives me an error that I could not troubleshoot:

> Preparing transaction: done
> Verifying transaction: done
> Executing transaction: failed
> ERROR conda.core.link:_execute(481): An error occurred while installing package 'defaults::constantly-15.1.0-py36_0'.
> PermissionError(13, 'Permission denied')
> Attempting to roll back.
> 
> Rolling back transaction: done
> 
> PermissionError(13, 'Permission denied')

I did not find that much on this error. But the strangest part, is that I've done this installation a thousand time and I never experience this error.

Anyone here had this issue before ?

Regards,

Mic

**Comment by mayouf** [comment]
Here is what I have with a `conda info`

 

> active environment : None
> user config file : /home/mic/.condarc
> populated config files : 
> conda version : 4.4.10
> conda-build version : 3.4.1
> python version : 3.6.4.final.0
> base environment : /home/mic/anaconda3  (read only)
> channel URLs : https://repo.continuum.io/pkgs/main/linux-64
> https://repo.continuum.io/pkgs/main/noarch
> https://repo.continuum.io/pkgs/free/linux-64
> https://repo.continuum.io/pkgs/free/noarch
> https://repo.continuum.io/pkgs/r/linux-64
> https://repo.continuum.io/pkgs/r/noarch
> https://repo.continuum.io/pkgs/pro/linux-64
> https://repo.continuum.io/pkgs/pro/noarch
> package cache : /home/mic/anaconda3/pkgs
> /home/mic/.conda/pkgs
> envs directories : /home/mic/.conda/envs
> /home/mic/anaconda3/envs
> platform : linux-64
> user-agent : conda/4.4.10 requests/2.18.4 CPython/3.6.4 Linux/4.13.0-36-generic ubuntu/16.04 glibc/2.23
>                 UID:GID : 1000:1000
>              netrc file : None
>            offline mode : False
>

**Comment by cathalgarvey** [comment]
Error appears to be in [this file](https://github.com/conda/conda/blob/master/conda/core/link.py#L486), but it appears to be a low-level part of the plumbing so I don't think that's very useful. Also, unless I'm mistaken the error is arising during the installation of the Twisted package '[constantly](https://github.com/twisted/constantly)'.

Apparently Conda has some unresolved issues [with permissions](https://github.com/conda/conda/issues/3448) at the moment, they might be related to your issue, too. Can you confirm that the ownership of all the user directories for Conda are set, correctly, to your user? And that they're writeable by your user?

Is there any way to get more verbose output on the error from Conda?

**Comment by mayouf** [comment]
Hi Cathal,

Indeed, this "constantly" package is the problem here. 

I check my ownership and here is what I saw:
> mic@ubuntu:~$ ls -l
> total 76
> drwxr-xr-x 22 root root 4096 Feb 26 19:25 anaconda3

As It was an root ownership, I changed it to the the only user by typing:
`sudo chown mic:mic anaconda3`

now I have this:

> mic@ubuntu:~$ ls -l
> total 76
> drwxr-xr-x 22 mic mic 4096 Feb 26 19:25 anaconda3

Then I tried to intall constantly but I still  have the same error:
`conda install constantly`

I also change the user permission as to allow user and group to write and execute le folder "Anaconda3".

Now this ownership:
`drwxrwxr-x 22 mic mic 4096 Feb 26 19:25 anaconda3
`

STILL THE SAME ERROR !!!!

**Comment by mayouf** [comment]
For the verbose output:

> mic@ubuntu:~$ conda install -v constantly
> Solving environment: ...working... done
> 
>  Package Plan 
> 
>   environment location: /home/mic/anaconda3
> 
>   added / updated specs: 
>     constantly
> 
> 
> The following NEW packages will be INSTALLED:
> 
>     constantly: 15.1.0-py36_0
> 
> Proceed ([y]/n)? y
> 
> Preparing transaction: ...working... done
> Verifying transaction: ...working... done
> Executing transaction: ...working... ===> LINKING PACKAGE: defaults::constantly-15.1.0-py36_0 <===
>   prefix=/home/mic/anaconda3
>   source=/home/mic/.conda/pkgs/constantly-15.1.0-py36_0
> 
> 
> ===> REVERSING PACKAGE LINK: defaults::constantly-15.1.0-py36_0 <===
>   prefix=/home/mic/anaconda3
> 
> 
> failed
> An error occurred while installing package 'defaults::constantly-15.1.0-py36_0'.
> PermissionError(13, 'Permission denied')
> Attempting to roll back.
> 
> 
> Rolling back transaction: ...working... done
> Traceback (most recent call last):
>   File "/home/mic/anaconda3/lib/python3.6/site-packages/conda/core/link.py", line 535, in _execute_actions
>     action.execute()
>   File "/home/mic/anaconda3/lib/python3.6/site-packages/conda/core/path_actions.py", line 364, in execute
>     force=context.force)
>   File "/home/mic/anaconda3/lib/python3.6/site-packages/conda/gateways/disk/create.py", line 280, in create_link
>     mkdir_p(dst)
>   File "/home/mic/anaconda3/lib/python3.6/site-packages/conda/gateways/disk/__init__.py", line 60, in mkdir_p
>     makedirs(path)
>   File "/home/mic/anaconda3/lib/python3.6/os.py", line 210, in makedirs
>     makedirs(head, mode, exist_ok)
>   File "/home/mic/anaconda3/lib/python3.6/os.py", line 220, in makedirs
>     mkdir(name, mode)
> PermissionError: [Errno 13] Permission denied: '/home/mic/anaconda3/lib/python3.6/site-packages/constantly'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/mic/anaconda3/lib/python3.6/site-packages/conda/core/link.py", line 472, in _execute
>     cls._execute_actions(pkg_idx, axngroup)
>   File "/home/mic/anaconda3/lib/python3.6/site-packages/conda/core/link.py", line 553, in _execute_actions
>     reverse_excs,
> conda.CondaMultiError: [Errno 13] Permission denied: '/home/mic/anaconda3/lib/python3.6/site-packages/constantly'
> 
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/mic/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 789, in __call__
>     return func(*args, **kwargs)
>   File "/home/mic/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 78, in _main
>     exit_code = do_call(args, p)
>   File "/home/mic/anaconda3/lib/python3.6/site-packages/conda/cli/conda_argparse.py", line 77, in do_call
>     exit_code = getattr(module, func_name)(args, parser)
>   File "/home/mic/anaconda3/lib/python3.6/site-packages/conda/cli/main_install.py", line 11, in execute
>     install(args, parser, 'install')
>   File "/home/mic/anaconda3/lib/python3.6/site-packages/conda/cli/install.py", line 255, in install
>     handle_txn(progressive_fetch_extract, unlink_link_transaction, prefix, args, newenv)
>   File "/home/mic/anaconda3/lib/python3.6/site-packages/conda/cli/install.py", line 285, in handle_txn
>     unlink_link_transaction.execute()
>   File "/home/mic/anaconda3/lib/python3.6/site-packages/conda/core/link.py", line 225, in execute
>     self._execute(tuple(concat(interleave(itervalues(self.prefix_action_groups)))))
>   File "/home/mic/anaconda3/lib/python3.6/site-packages/conda/core/link.py", line 500, in _execute
>     rollback_excs,
> conda.CondaMultiError: [Errno 13] Permission denied: '/home/mic/anaconda3/lib/python3.6/site-packages/constantly'
>

**Comment by cathalgarvey** [comment]
Hey, this is good, I think we found the problem. :) Can you try `chown` once more, but use the `-R` flag to make it recursive? Otherwise the root folder `anaconda3` will belong to you, but all the contents that currently exist will still belong to root.

I advise against doing a recursive `chmod` though, at this stage.. At least until/unless something else comes up to male that necessary.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mayouf** [comment]
Hi Cathal,

I was so desperate that I reinstalled anaconda3....and guess what ? it worked...

When I compare the ownerships between the two anaconda folders.....it shows that YOU WERE RIGHT !!!

The ownership was the issue here....

So for the next one having this issue:

![image](https://user-images.githubusercontent.com/5865600/36702080-f3b96376-1b55-11e8-95ec-ab38d458072f.png)

In my case, the user was called "mic". You will need to write your username.

AND DO NOT FORGET THE RECURSIVE OPTION "-R", like me, to change the subfolder ownership.

And you will be able to install scrapy by a simple `conda install scrapy`

THX Cathal

**Comment by cathalgarvey** [comment]
Glad you solved it! :)
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by tqrahman** [comment]
I am having the same issue. Permission denied when installing scrapy. 

I am new to the command line and am not sure how to change ownership in MacOS. Can you give me step by step instructions?

**Comment by nctl144** [comment]
@tqrahman did you try putting sudo at the beginning of your command?
Something like this always works for me!

`sudo pip install scrapy`

**Comment by mayouf** [comment]
As @nctl144  said, you probably installed your anaconda with  `sudo`. Then, your anaconda folder belong to the `root` and not to you, as you are the "user".

So  open your terminal and position yourself where the Anaconda folder is. By typing `ls -l`, you should see your folder.  

If you see  the word "root", then change the folder ownership by typing:

`sudo chwon -R <user>:<user> anaconda`

for example, if your username is "rahman", you must type:

`sudo chwon -R rahman:rahman anaconda`

**Comment by mayouf** [comment]
everything is visible here:
![image](https://user-images.githubusercontent.com/5865600/39322405-16716820-498a-11e8-9f8e-8b727ac43661.png)


also, if you don't have experience in command line, you should read tuto about "folder persmission in linux" or "ownership in linux":

check here: 
http://www.havetheknowhow.com/Configure-the-server/Linux-file-permissions.html

**Comment by tqrahman** [comment]
Thanks for the quick response. Here is a glimpse of the anaconda folder:

<img width="465" alt="screen shot 2018-04-26 at 3 49 53 pm" src="https://user-images.githubusercontent.com/17665316/39328631-ee57f41e-4969-11e8-9d77-cf34edf98169.png">

 

So I looked into the article and guessing that "staff" is the group. And also the owner is tqrahman?

Also when I run: sudo chown -R tqrahman:tqrahman anaconda, i get illegal group name.

**Comment by tqrahman** [comment]
@nctl144 
I usually install packages using conda. Now that you mention it, I am not sure when to use pip or conda (but I dont know if this is the right thread to talk about this)

**Comment by nctl144** [comment]
@tqrahman Maybe you can use both to see what happens? Just prepend **sudo** to your command!

**Comment by tqrahman** [comment]
Thanks! I used:

sudo conda install Scrapy

and it worked. Did not know that you can use sudo with conda. Thanks!

**Comment by nctl144** [comment]
No problem!
