### ISSUE TITLE
Issue in FromRequest

### ISSUE THREAD

**Issue by Svickie7** [scrapy/scrapy#3144]
It return the same login page
it is not able to redirect the next page..
I have all tried to call http://schedule.amacotton.com/transportation.php in scrap_page method..it return 302 

import scrapy

class ExampleSpider(scrapy.Spider):
    name = 'example'
    start_urls = ['http://schedule.amacotton.com/']
    LOGIN_URL = 'http://schedule.amacotton.com/login.php'
    URL = 'http://schedule.amacotton.com/transportation.php'
   
    def parse(self, response):
        my_data = {'user': 'abc', 'pass': 'abc', 'plant': '1'}
        yield scrapy.FormRequest(
                    url = self.LOGIN_URL,
                    headers = {
                        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
                        'Accept-Encoding': 'gzip, deflate',
                        'Accept-Language': 'en-US,en;q=0.5',
                        'Connection': 'keep-alive',
                        'Content-Type': 'application/x-www-form-urlencoded',
                        'Host': 'schedule.amacotton.com',
                        'Referer': 'http://schedule.amacotton.com/login.php',
                        'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0',
                    },
                    method = 'POST',
                    formdata = my_data,
                    callback = self.scrap_page,
                    dont_filter = True
            )
    
    def scrap_page(self, response):
        print response.body

2018-02-27 11:23:49 [scrapy.core.engine] INFO: Spider opened
2018-02-27 11:23:49 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2018-02-27 11:23:49 [scrapy.extensions.telnet] DEBUG: Telnet console listening on 127.0.0.1:6024
2018-02-27 11:23:50 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://schedule.amacotton.com/> (referer: None)
2018-02-27 11:23:50 [scrapy.core.engine] DEBUG: Crawled (200) <POST http://schedule.amacotton.com/login.php> (referer: http://schedule.amacotton.com/l
ogin.php)
<html xmlns="http://www.w3.org/1999/xhtml" >
<head><title>
        Login
</title></head>
<body>
    <form name="form1" method="post" action="login.php" id="form1">
    <div>
        <table width="250" cellpadding="0" cellspacing="0">
            <tr>
                <td>UserName:</td>
                <td><input name="user" type="text" id="user" style="width:100px;" /></td>
                <td rowspan="2"><input type="submit" name="login" value="Login" id="login" tabindex="5" /></td>
            </tr>
            <tr>
                <td>Password:</td>
                <td><input name="pass" type="password" id="pass" style="width:100px;" /></td>
            </tr>
        </table>
        <span id="lblErrorConfirmation" style="font-family:Arial; font-size:small; color:Red; padding-left: 10px"></span>
        <br />
        <table id="lstPlants" border="0">
        <tr>
                <td><input id="lstPlants_0" type="radio" name="plant" value="1" /><label for="lstPlants_0">Amarillo Cotton Warehouse</label></td>
        </tr><tr>
                <td><input id="lstPlants_1" type="radio" name="plant" value="2" /><label for="lstPlants_1">Tulia</label></td>
        </tr>
</table>
    </div>
    </form>
</body>
</html>

**Comment by cathalgarvey** [comment]
Hi @Svickie7 - It's not clear from your issue report that this is a bug in Scrapy. If you're seeking help with a scraping project, I'd suggest using one of our community support fora, including [reddit][] and [stackoverflow][], instead. The github repository is used for tracking development of Scrapy itself, and isn't normally used for support, sorry!

Feel free to reopen this if you feel there is a bug in Scrapy causing your issue.
