### ISSUE TITLE
root logger's level is always set to NOTSET

### ISSUE THREAD

**Issue by joelkim** [scrapy/scrapy#3146]
Currently, the log level of a root logger is always automatically re-set to NOTSET level in `install_scrapy_root_handler` function call if I add handlers to root logger:
https://github.com/scrapy/scrapy/blob/108f8c4fd20a47bb94e010e9c6296f7ed9fdb2bd/scrapy/utils/log.py#L110

Can anybody explain why this level reset is required?
This issue is relevant to issue #2352, #2149, I think.

**Comment by thernstig** [comment]
@joelkim please see my answer in #2149. I believe this issue can be closed as a clone of that.
