### ISSUE TITLE
[GSoC 2018] Guidance request for Idea "Scrapy Spider autoRepair"

### ISSUE THREAD

**Issue by thisisayush** [scrapy/scrapy#3154]
Hi,
I am Ayush, B.Tech (CSE), 2nd Year, from Amity University, Noida. I came across the idea of automatically generating xpaths from scapshots and became interested at the same moment in the project and would love to work for the same.
I have worked with scrapy in the previous in a team, scraping news websites and storing information [1]. I have been developing in python since last one year and have done various projects in Django, Flask, StaticJinja, etc mostly on web development. 
I am highly interested on working in this project and would like to discuss over the idea.

@cathalgarvey , I would really appreciate any guidance on pre-requisites for GSoC 2018 and this project as a part of GSoC.

[1] https://github.com/thisisayush/scrape

Regards, 
Ayush Agarwal
contact@thisisayush.com | thisisayush.com

**Comment by cathalgarvey** [comment]
Hi Ayush! Glad to hear of your interest. There's been discussion already on that project over on #3138, so you may find it helpful to read there first. As discussed there, and elsewhere, right now we're encouraging people to contribute to Scrapy and the related projects. This does a few things:

* It gets ye up-to-speed on how it all works and fits together,
* It helps you become familiar with our contributions process
* It lets us see you in action

We won't be able to accept all interested people as GSoC contributors, unfortunately. But we're always happy to have new contributors; it's not all about GSoC. ;)

Thanks for your interest, looking forward to hearing more from you!
