### ISSUE TITLE
"New HTTP/2 download handler" project help for GSoC

### ISSUE THREAD

**Issue by hsumerf** [scrapy/scrapy#3169]
Hi Scrapy commpunity!
        I saw **"New HTTP/2 download handler"** idea for **Gsoc 2018** list which i found much interesting to work because it is in my interest field of networking,
        before My questions i would like to introduce myself, I'm a student of University of karachi and completing my BS in computer Sciences and in 3rd year
        of university.I have knowledge of Python,C,jave,C#,HTML,CSS,javascript but my favourite languages are python and C,in which i have developed some
        projects data datarecovery(in C, formats recovered MP3,JPG,PNG,PDF) and in python i have worked on sentiment analyzer(by using  nltk with twitter API),
        webapplication shares trading website (on flask as a assignment), photos and data extractors(developed in scrapy these spiders).
        As you describe we have to work on http/2 for this project I read many articles and reading 1 book of Daniel Stenberg [this](https://www.gitbook.com/book/bagder/http2-explained/details) to understand the concepts of http/2 and what are pros and cons of this new version of http.Now What I have learned so far is that:
1)  In HTTP /1.1 we use textual frames but in http/2 we use binary because it is much more efficient to parse,more compact on wire,less error-prone.
2)HTTP/1.1 has a problem of head-of-line blocking, tried to resolve this issue by pipelining but couldn't solve practically this problem,so now http/2 has solved this issue by multiplexing. 
3)HTTP/2 supports server push i.e. which sent all necessary files of a webrequest simultaneously.
4)HTTP/2 use HPACK compression which use huffman encoding, by this we get less data in stream over network and save our precious bytes.
5)HTTP/2 use application-layer protocol negotiation(ALPN) i.e. it sends the potocols list to server in hello message to choose the desire protocols, which reduce the additional round trips.

   All these things can increase the speed of downloading web pages and all media files.
1)But now I want to ask you, are my concepts right regarding this http/2? give me feedback regarding this please.
2)As far  as i understand that, it is also necessary for server to work upon HTTP/2 if we want to use HTTP/2 advantages, so how we will counter if does not support HTTP/2 and check which HTTP is this?
3)HTTP/2 does not support telnet, so how we will encounter this problem too?
4)please suggest me bug through which i can learn code level concepts by patching that bug and can show that patch in my proposal of GSoC.
5)Guide me please more, how to start working for this proposal buy suggesting me files of scrapy project and other concepts which i should learn to start work upon this project.
Thanks in advance! :)

**Comment by Gallaecio** [comment]
@hsumerf Shall we close this issue?
