### ISSUE TITLE
On JavaScript paging

### ISSUE THREAD

**Issue by runpython** [scrapy/scrapy#3170]
I have a problem that I have never been able to solve, and I am very annoyed

There are no relevant contents in the https://docs.scrapy.org/en/latest/

That's the way it is.

I'm going to scrapy this site http://q.10jqka.com.cn/

For example, I want to take the stock code under the stock market

The XPath parameter is similar to this
toxpath=response.xpath('//div[@id="maincont"]/table[@class="m-table m-pager-table"]/tbody/tr').extract()
for listxpath in toxpath:
    shno=response.listxpath('./td[1]/text()').extract()
    shcode=response.listxpath('./td[2]/a/text()').extract()
    shname=response.listxpath('./td[3]/a/text()').extract()
    shprice=response.listxpath('./td[4]/text()').extract()

But I was in trouble when I was paging

The site's paging is a dynamic JavaScript
a code like this
`<a class="changePage" page="2" href="javascript:void(0);">下一页</a>`

So I can't scrapy the relevant content. How do I do it?

I hope to be able to help you, thank you.

**Comment by runpython** [comment]
``<a class="changePage" page="2" href="javascript:void(0);">下一页</a>

**Comment by runpython** [comment]
`<a class="changePage" page="2" href="javascript:void(0);">下一页</a>`

**Comment by cathalgarvey** [comment]
Hey @runpython,

The issues pane on Github isn't the best place to ask questions about _using_ Scrapy. For that, I suggest asking at our Stackoverflow or Reddit communities.

I did take a quick look at your site, though. If you visit the page in Firefox with the "Network" pane open, and click the second page link, you see a request going to this URL:

    http://q.10jqka.com.cn/index/index/board/all/field/zdf/order/desc/page/2/ajax/1/

This returns a HTML table, that is probably directly inserted into the results section of the page to replace the current contents. So, that's your pagination mechanism, probably.

Unfortunately, Scrapy does not solve Javascript on its own. There are too many ways for people to use Javascript to do things that they should just use HTML/HTTP to do. We can't predict and solve them all! However, if you have Javascript issues in future, consider using Splash as a headless browser for Scrapy: http://splash.readthedocs.io/

Good luck!

**Comment by runpython** [comment]
thanks! cathalgarvey
