### ISSUE TITLE
Add an option to add exceptions to be retried

### ISSUE THREAD

**Issue by ariasuni** [scrapy/scrapy#3173]
Currently, the list of exception to retry is static. In a middleware I wrote, I created custom exceptions that I want to be caught by the RetryMiddleware without being forced to make my exceptions derive from already caught but not semantically related exceptions.

**Comment by kmike** [comment]
You can make a subclass of RetryMiddleware, change this list: https://github.com/scrapy/scrapy/blob/6cc6bbb5fc5c102271829a554772effb0444023c/scrapy/downloadermiddlewares/retry.py#L34, and use your middleware instead of RetryMiddleware.  Would it work for you?

**Comment by ariasuni** [comment]
This an elegant and simple enough solution I didn’t think of; it works great.
