### ISSUE TITLE
Getting 1 error in report while using "tox" command in shell

### ISSUE THREAD

**Issue by hsumerf** [scrapy/scrapy#3176]
I used "tox" command as per the  [documentation](https://doc.scrapy.org/en/master/contributing.html#running-tests) and in the end i m getting 1 error even i havn't changed anything in souce code which I cloned from remote.

=================================== FAILURES ===================================
_________________________ ShellTest.test_dns_failures __________________________

result = (0, '{}\n', 'Coverage.py warning: --include is ignored because --source is set (include-ignored)\nCoverage.py warning:...wled (200) <GET http://searchguide.level3.com/search/?q=http://www.somedomainthatdoesntexi.st/&t=0> (referer: None)\n')
g = <generator object test_dns_failures at 0x7f72acdcde60>
deferred = <Deferred at 0x7f72adee1758 current result: None>

    def _inlineCallbacks(result, g, deferred):
        """
        See L{inlineCallbacks}.
        """
        # This function is complicated by the need to prevent unbounded recursion
        # arising from repeatedly yielding immediately ready deferreds.  This while
        # loop and the waiting variable solve that by manually unfolding the
        # recursion.
    
        waiting = [True, # waiting for result?
                   None] # result
    
        while 1:
            try:
                # Send the last result back as the result of the yield expression.
                isFailure = isinstance(result, failure.Failure)
                if isFailure:
                    result = result.throwExceptionIntoGenerator(g)
                else:
>                   result = g.send(result)

/home/hsumerf/PycharmProjects/scrapy1/scrapy/.tox/py27/local/lib/python2.7/site-packages/twisted/internet/defer.py:1386: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/home/hsumerf/PycharmProjects/scrapy1/scrapy/tests/test_command_shell.py:114: in test_dns_failures
    self.assertEqual(errcode, 1, out or err)
/home/hsumerf/PycharmProjects/scrapy1/scrapy/.tox/py27/local/lib/python2.7/site-packages/twisted/trial/_synctest.py:432: in assertEqual
    super(_Assertions, self).assertEqual(first, second, msg)
E   FailTest: {}
======== 1 failed, 1686 passed, 6 skipped, 14 xfailed in 282.12 seconds ========
ERROR: InvocationError: '/home/hsumerf/PycharmProjects/scrapy1/scrapy/.tox/py27/bin/py.test --cov=scrapy --cov-report= scrapy tests'
___________________________________ summary ____________________________________
ERROR:   py27: commands failed

can I anybody please help me why I'm getting error?

Thanks in advance.

**Comment by kmike** [comment]
Could you please paste the full output?

**Comment by hsumerf** [comment]
@kmike  sorry for inconvenience, please see now I have updated my comment with full error.

**Comment by hsumerf** [comment]
========================================================================== 1687 passed, 6 skipped, 14 xfailed in 278.94 seconds ===========================================================================
_________________________________________________________________________________________________ summary _________________________________________________________________________________________________
  py27: commands succeeded
  congratulations :)

@kmike now I'm getting this in the end and I think it's fine now, but can you please tell me why it skipped 6 items and 14 failed?
