### ISSUE TITLE
GSOC 2018 proposal

### ISSUE THREAD

**Issue by nctl144** [scrapy/scrapy#3177]
Hey @lopuhin , I have some questions relating to the GSoC proposal. 

Right now I am about to finish the proposal for the project **Scrapy performance improvement** and the draft is ready. I am just wondering if it is possible for one of the mentors (I noticed that you are one of the mentors for the project) to review it for me? The deadline is in one week so I just want to make sure everything is ready early :)

Please let me know when you have a chance :)

**Comment by lopuhin** [comment]
Hey @nctl144 that's great that you already have a draft ready, I would be eager to review it. You can post it and continue discussion here, so that it's more visible and more people can provide an opinion, or share it on gsoc@scrapinghub.com mailing list.
