### ISSUE TITLE
GSoC 2018 Proposal: Spider Auto Repair

### ISSUE THREAD

**Issue by virmht** [scrapy/scrapy#3179]
[Here](https://drive.google.com/file/d/1WOGJRqZKMNPC6m8QwjqUmksDLvE4_GVZ/view?usp=sharing) is the link to my revised GSoC Project proposal. 

The deadline for proposal submission is only about a week away.
@cathalgarvey, it will be great if you review this proposal and suggest changes, if any.

Suggestions are welcome :)

Thanks.

**Comment by virmht** [comment]
I have added a few things to my proposal(uploaded new proposal and added link to it in the above comment). I have proposed the following additions:

1. Why Scrapely cannot be used in all cases?
	Consider the following example webpages named 1.html and 2.html:
```
<!DOCTYPE html>
<html>
    <body>
        <h1>My First Heading</h1>
        <p>My first paragraph.</p>
    </body>
</html>
```
					1.html
	
```
<!DOCTYPE html>
<html>
    <body>
        <h1>My First Heading</h1>
        <p>My second paragraph.</p>
    </body>
</html>
```
					2.html

```
>>> from scrapely import Scraper
>>> s = Scraper()
>>> url2 = 'file:///C:/Users/t-vimeh/Desktop/2.html'
>>> url1 = 'file:///C:/Users/t-vimeh/Desktop/1.html'
>>> data = {'p_element': '<p>My first paragraph.</p>'}
>>> s.train(url1, data)
```
```
Traceback:
scrapely.template.FragmentNotFound: Fragment not found annotating 'p_element' using: <function best_match.<locals>.func at 0x00000214225EAD90>
```
This shows that scrapely cannot be used to extract big chunks of data. If you consider the HTML code to be an ordered tree, then, we can say that scrapely can only extract leaf node data. However, the design suggested below can be used to extract entire subtrees from the HTML tree.

2. The method of using Item() attributes to restore spider:
If none of the methods described above can restore the spider, the following method might help:
	A parse/callback method in the spider returns two types of objects: 

   - Item() object
   - Request() object

  Now, we can look at the attributes of this Item() object. If the attributes of this Item() object has leaf 
  node values of the HTML tree stored in them, then we can use scrapely to train on the data extracted 
  from old page and the HTML code of the new page and fill up these Item() objects for subsequent 
  pages having structure similar to the new page. We can also search for the leaf node values in the new 
  page HTML tree and return their XPaths as described above.

**Comment by virmht** [comment]
@cathalgarvey , it would be great it you provide your valuable opinion on the above comment as well :)

**Comment by cathalgarvey** [comment]
Hi @virmht - I'm reading through the document now, thank you for notifying me of the revision, also. :) I'll respond here with thoughts when I'm done!

**Comment by virmht** [comment]
@cathalgarvey , thank you very much for your time 😊

**Comment by virmht** [comment]
@cathalgarvey, tomorrow(27th March, 2018) is the deadline for GSoC proposal submission. It would be great if you provide your opinion on the proposal :)

**Comment by cathalgarvey** [comment]
Hi Viral, thanks for the prompt; I'll email you my response. Overall, promising proposal, though I think a more limited scope would be safer for a project of this complexity, and with the short timeline. :)

**Comment by virmht** [comment]
@cathalgarvey, I have emailed you some of the changes that I would like to make. Please have a look at them and feel free to provide your opinion.

**Comment by virmht** [comment]
@cathalgarvey, sorry to disturb you again. About 5.5 hrs remaining at the time of writing this comment. Any suggestions regarding the proposal? Should I submit it ?

**Comment by cathalgarvey** [comment]
Hey @virmht - I think the document as-is is good to submit. If you want to polish it by adding more technical detail on how, specifically, the stages would work, that would improve it. But I think right now it describes the direction well enough.

**Comment by virmht** [comment]
Hello @cathalgarvey ! I have been going through scrapy internals, familiarizing myself with scrapely code and also trying to understand slybot code. If any new bugs appear in the issues section, I will be happy to volunteer to fix that bug. As soon as I get accepted, I will start working on the design :).

I wanted to ask you if you have any questions regarding my proposal. If yes, I will be happy to answer them :)

**Comment by Gallaecio** [comment]
GSoC 2018 is over.
