### ISSUE TITLE
Wrong "start_urls"

### ISSUE THREAD

**Issue by hsumerf** [scrapy/scrapy#3180]
I created a spider with command
`scrapy genspider my_crawler1 http://smrafiq.com`
and when i see file of spiders/my_crawler1 there was start_urls and allowed_domains value like this
`allowed_domains = ['http://smrafiq.com']`
`start_urls  = ['http://http://smrafiq.com/']`

why http:// is again in start_urls? can't we solve this issue, if we can what files should I watch to repair it?

**Comment by kmike** [comment]
`scrapy genspider` asks for domain, not for a full URL, so `scrapy genspider my_crawler1 http://smrafiq.com` is not a correct usage. 

I think Scrapy should handle this error better - either allow URLs, or raise an error when URL is passed instead of domain.

**Comment by hsumerf** [comment]
thanks got that.
