### ISSUE TITLE
CrawlSpider - allow disabling of follow for start_urls

### ISSUE THREAD

**Issue by johtso** [scrapy/scrapy#3182]
It seems a little inconsistent that you can specify following behaviour in all your rules, but following of links cannot be disabled for the `start_urls` without overriding `parse`.

My use-case is a site where I need some custom logic to get the initial urls for the first page, so I don't want my crawling rules to be applied to it.

**Comment by mohmad-null** [comment]
Can you not simply do this with your Spiders __init__ method?
In my case the `__init__` method is where I discover (from a database) and then create my initial URL's. These go into self.meta_list, and then I loop over the meta_list in the spider's `start_requests` method (over-writing the default start_requests).

**Comment by Gallaecio** [comment]
https://github.com/scrapy/scrapy/issues/3182#issuecomment-377545852 makes sense.
