### ISSUE TITLE
Enclosing URLs passing to shell with single/double quotes

### ISSUE THREAD

**Issue by javadmokhtari** [scrapy/scrapy#3183]
In [Scrapy Tutorial](https://doc.scrapy.org/en/latest/intro/tutorial.html) we read:

> Remember to always enclose urls in quotes when running Scrapy shell from command-line, otherwise urls containing arguments (ie. & character) will not work.

later in [Using Selectors](https://doc.scrapy.org/en/latest/topics/selectors.html) we see:
`scrapy shell https://doc.scrapy.org/en/latest/_static/selectors-sample1.html
`

As you see in above command, there is no sign of single/double quotes. so I think it might be a good idea to change this to:
`scrapy shell 'https://doc.scrapy.org/en/latest/_static/selectors-sample1.html'
`

Thanks.

**Comment by kmike** [comment]
The problem is that in Windows it should use double quotes, single quotes would break this command if I'm not mistaken. For this particular URL no quotes work both in Windows and Linux.

**Comment by kmike** [comment]
See also: https://github.com/scrapy/scrapy/pull/2339
