### ISSUE TITLE
download_delay is not used dynamically

### ISSUE THREAD

**Issue by eode** [scrapy/scrapy#319]
The concurrent_requests option is read and processed when dynamically changed, but the download_delay is only used to set the initial delay time.

**Comment by manumeral** [comment]
In case you need to change Request Delay, here is a workaround:
There exists a **crawler.engine.downloader.slots** dict in which you can dynamically change the slot delay 
To use in your spider:
`slot = self.crawler.engine.downloader.slots
print slot`
shall give you the slots and the slot delays. Change it as per your need. 
say..
`self.crawler.engine.downloader.slots['slot'].delay=0`

**Comment by feryandi** [comment]
> In case you need to change Request Delay, here is a workaround:
> There exists a **crawler.engine.downloader.slots** dict in which you can dynamically change the slot delay
> To use in your spider:
> `slot = self.crawler.engine.downloader.slots`
> `print slot`
> shall give you the slots and the slot delays. Change it as per your need.
> say..
> `self.crawler.engine.downloader.slots['slot'].delay=0`

What is the rule for naming of the slots? I found mine is the base web url. Additionally, is it possible to have more than one slot? Then, how do you know which one is the one that being used by spider that I want?
