### ISSUE TITLE
Unable to pass spider-specific settings programmatically 

### ISSUE THREAD

**Issue by marcfrancis961** [scrapy/scrapy#3192]
I build a small app to deploy, launch and monitor spiders from one big scrapy project.

I am using scrapyd to scheduel the spiders through basic python requests:
`requests.post('http://localhost:6800/schedule.json', params=spider_body)` 

spider_body being:
`{'project': 'skwid_robot',
                               'spider': spider_ref,
                               'settings': json.dumps(spider_to_schedule.settings.to_json()),
                               'custom_settings': json.dumps(spider_to_schedule.other_settings.to_json()),
                               'schema': json.dumps(spider_to_schedule.schemas[0].schema)}`

**Here is my problem**: the spider do not take the settings form spider_body but generates default settings. So I've tried a workaround to update custom_settings in spider  `__init__`  this way  `self.update_settings(json.loads(kwargs.get('custom_settings')))` . I get the following error when launching the spider: ' AttributeError: 'str' object has no attribute 'update' ' 

How can I handle the settings for each spider knowing that my settings dict is build in my app and then have to sent to the spider ?

Thanks

**Comment by amarynets** [comment]
@marcfrancis961 Did you try to put `dist` into `settings` parameter, not `str`?

**Comment by Gallaecio** [comment]
Closing due to a lack of feedback.
