### ISSUE TITLE
How do I save scraped items to multiple .jl files?

### ISSUE THREAD

**Issue by chrismp** [scrapy/scrapy#3193]
I can't seem to find this in the docs, so here goes...

I want to run a scraper that saves different types of items to separate JSON Lines files. 

My `settings.py` has this:

    ITEM_PIPELINES = {
       'permits.pipelines.PermitTypePipeline': 300,
       'permits.pipelines.PermitNumberPipeline': 301,
    }

My `pipelines.py` has this:

    class PermitTypePipeline(object):
    	def process_item(self, item, spider):
    		return item
    
    class PermitNumberPipeline(object):
    	def process_item(self, item, spider):
    		return item

`items.py` has this:

    class PermitType(scrapy.Item):
    	permitWebCode=	scrapy.Field()
    
    class PermitNumber(scrapy.Item):
    	permitNumber=	scrapy.Field()

`my_spider.py` has this:

    def parse(self,response):
      ## Some scraper code here ... 
      yield PermitType(permitWebCode=someScrapedVariable)
      yield PermitNumber(permitNumber=anotherScrapedVariable)

How do I save the yielded `PermitType` object to `permit_types.jl` and the `PermitNumber` object to `permit_number.jl`?

**Comment by grammy-jiang** [comment]
Hi, @chrismp ,

In scrapy the pipeline **will not** treat your items based on types, which means in each pipelines the type of items should be specified clearly (`if isinstance(item, ItemType)`) and remember to drop it (`dropitem`) if that type of items will not be used in the future.

**Comment by chrismp** [comment]
Thanks for replying, @grammy-jiang.

Is there any relevant example code in the docs of elsewhere I can check out to see what you mean? I'm new to Scrapy...

**Comment by nctl144** [comment]
@chrismp have you taken a look at [this](https://doc.scrapy.org/en/latest/topics/item-pipeline.html#write-items-to-a-json-file). I believe you can do some conditional statements in the **process_item** function to do what you mentioned, right?

**Comment by VMRuiz** [comment]
I solved this by using an [custom feed exporter](https://pastebin.com/kf8ykxPP)

It could be improved because you still need to manualy define the list of item that you want to export but it will work much better than creating a pipeline, because you will be able to use it with any of the already implemented exporters like csv, json, jl...

Also, with this solution you need to include `%(item)s` in the `FEED_URI` so it generate a different file name based on the given item.

**Comment by Gallaecio** [comment]
I believe `FEEDS` and https://github.com/scrapy/scrapy/pull/5178 addressed this.

**Comment by Gallaecio** [comment]
https://docs.scrapy.org/en/latest/topics/feed-exports.html#feeds
