### ISSUE TITLE
[feature] need a new request method that handle with ajax and return value without callback

### ISSUE THREAD

**Issue by NewUserHa** [scrapy/scrapy#3200]
is it possible to make a new request method that can be added to scrapy schedule queue by scrapy engine?

situation: there's a page that contains all information, and a small part(is not at the bottom of page) of it are returned by an ajax whose url is available(seeable) in network developer tool

solution: so the simplest way is to use `requests.get()` of `requests` module to get that url, but how to achieve this with only scrapy that can also handle the same cookies of the site.

discuss: that add one more callback and pass all result/items to it by `meta` is possible, but is it also redundancy?

thanks

**Comment by grammy-jiang** [comment]
Hi, @NewUserHa 

This is a common question/problem that the data of one item distribute in more than one page/request.

For your last question, it depends whether the information saved in `meta` will exist for a long time, which may cause memory problem. `meta` is designed as a container to transport the data between request and response - this is good but you have to put more attention on the life cycle of data inside `meta` in case memory leaks. From you description, I think the data in meta of your request will not last for a long time, so it is ok to me that you just put the data in meta as a simple solution.

Back to the main topic: is using a sync module in twisted/scrapy an approperiate way? For most of cases, the answer is **NO**. Please forget about the requests module in scrapy! There are some certain solutions for this kind of questions:

- my repo [grammy-jiang/scrapy-pipeline-mongodb: A pipeline of saving item into MongoDB](https://github.com/grammy-jiang/scrapy-pipeline-mongodb) gives an example for saving items async, and also support saving multi-items into one record/doc in database (with the power of signal system in scrapy)
- the code snippet on the section [Take screenshot of item](https://doc.scrapy.org/en/latest/topics/item-pipeline.html#take-screenshot-of-item) of the offical documents gives an example - how to call downloader in pipeline and return a deferred object (yes, the method `process_item` of pipeline can return a deferred object).

So there are many ways inside and outside scrapy to handle the case you are facing now, try them first!

**Comment by NewUserHa** [comment]
thank you @grammy-jiang 
I checked the two links you posted.
scrapy is a framework for developing spiders quickly. and this is a simple job to `get` an url/api and save the returned with the rest info of the page in one callback, and at once.
is it turning a simple mission into a complex one? first one need tune the `settings.py`, second one need build a new pipeline for this, since it's just because that only one ajax needed in one page wants to SEND a `get` request and SAVE the returned value?

I still think using a simple line `foo = requests.get(url).text` is a very convenient way even it's sync, and needed to handle cookies by hand.

so I wonder if there can be an API from scrapy that can achieve this without third modules.

**Comment by grammy-jiang** [comment]
Hi, @NewUserHa 

Your case is saving two responses into one item. Considered about the work process of scrapy, this is not a case scrapy want to deal with. So there are only two solutions:

1. solve it in the same framework (my repo, or a new pipeline), or
2. solve it outside the framework (just like using requests in the spider object)

You can keep the solution straightforward and simple, or you can make it more decent and compatible with the philosophy of scrapy/twisted (which can also be helpful to understand this great framework).

**Comment by Gallaecio** [comment]
@NewUserHa Does https://github.com/rmax/scrapy-inline-requests work for your use case?

**Comment by NewUserHa** [comment]
I had read that project's code. no. it needs a whole right style parse method and is still adding callback on the right place before giving scrapy.

actually, scrapy in the 'google summer cample' is the right way but it seems no one is working on that.

otherwise, it needs more codes and complexity in scrapy, or need to find another framework to use.

thanks for reply.

**Comment by Gallaecio** [comment]
Could you provide some pseudo-code of how you would like the API to look like for you?

**Comment by NewUserHa** [comment]
I think it's out of scrapy. because it will make it special and might get refused. because scrapy is based on twisted and is all about callback chains.

https://github.com/scrapy/scrapy/issues/3148 the `await/async support` will/should work and slove this problem as well.

**Comment by Gallaecio** [comment]
Are you OK with closing this issue in favor of #3148?

**Comment by NewUserHa** [comment]
yes, of course
