### ISSUE TITLE
How can I get return data after spider yield item

### ISSUE THREAD

**Issue by heianhu** [scrapy/scrapy#3203]
I have a question.
Now I have a spider to do something
![image](https://user-images.githubusercontent.com/16443175/38432780-3ab7a58a-39fb-11e8-9bb6-38ea7c40285d.png)
And then I yield this item to pipeline
![image](https://user-images.githubusercontent.com/16443175/38432855-6d5f5690-39fb-11e8-9f1d-f8632f1cf43a.png)
In items.py, it will do something
![image](https://user-images.githubusercontent.com/16443175/38432951-b78e537e-39fb-11e8-8d57-fb90f8bc2dd1.png)
So how can I get the return data after spider yield item?

**Comment by nctl144** [comment]
So what you wanted to do was doing something with the item that you got after crawling the data, right? why don't you define the function **dosomething()** in your spider and process it right after you got **somedata**?

**Comment by heianhu** [comment]
I want to do some processing such as inserting database. And then it will get this ID in database. I want to use this ID in spider after yield item.

发自我的 iPhone

在 2018年4月7日，02:02，Chau Tung Lam Nguyen <notifications@github.com<mailto:notifications@github.com>> 写道：


So what you wanted to do was doing something with the item that you got after crawling the data, right? why don't you define the function dosomething() in your spider and process it right after you got somedata?

**Comment by nctl144** [comment]
You mean you want to insert the current item's id into the database, then get the same id from the database to use after yielding the item in the for loop right? In that case I think you can assign the id to a variable and use it later. Correct me if I am wrong :)

**Comment by grammy-jiang** [comment]
Hi, @heianhu @nctl144 

This is the same question as the issue #3200 - operations/items from two responses are not easy to connect together. 

In the issue #3200, I have mentioned two solutions for this kind of problem:

- use the signals to transport the id between the objects of the pipeline and the spider, or
- use the meta to transport the data between the request and response until all data gathers

Please remember although the type of methods in the class of spider is a generator (actually in some cases, they are used for async/coroutine without any callback in design), the connection between modules of scrapy are so complicated that keyword `send` cannot be used easily in any of them.

**Comment by heianhu** [comment]
@nctl144 
Yes, the idea you are talking about is the same as the one I am currently using. I set an attribute in item.py, and then it can set value after inserting the database. So I can use this value in spider.

**Comment by heianhu** [comment]
Hi, @grammy-jiang 

Before asking this question, I also thought of using the .send() method to get this value, but I don't know where to call the .send() method.
As you said, can't I send a value using the .send() method?

**Comment by grammy-jiang** [comment]
@heianhu 

Sorry, man, scrapy is a framework, which means the interactions between components are much more complicated than you think.

If you can read the source code, you will realize that the framework does a lot to work to ensure your spider works as its design - trigger the middleware in the sequence they are specified, send the request in right protocols, parse the response into the correct format, etc. It's not as simple as `yield` and `send`.

So please read the source code and understand the principle first, then you will know how to solve your problem in a scrapy way, as this framework design for.
