### ISSUE TITLE
[STORAGE] Is there a way to export items every XX item scraped?  

### ISSUE THREAD

**Issue by maximenannan** [scrapy/scrapy#3206]
Hi there,

Is it possible to export items scraped every X items ? 
I mean I have millions of items to scrape and am looking for a way to export my items every 100k items scraped for example.

One solution could be to have batch of urls and run one scraper per batch but maybe there is a more clever solution. 

Thanks a lot

**Comment by nctl144** [comment]
Do you mean you want to export those items into multiple json or csv files?

**Comment by zhongdai** [comment]
I noticed the new version Scrapy won't flush the file handler until the spider is closed. I am not sure about previous version, but I remember I could use `tail -f output.csv` to check the progress of the spider while it is till running.

**Comment by grammy-jiang** [comment]
Hi, @maximenannan 

The pipeline is designed to make you, the user to control what to do with your data scraped from the website.

So the answer to your question is it is possible. Scrapy has no limitation about how or when to save/export/insert the item/items to files/databases/other pipelines, which means all of these treatments about the item should be done by yourself.

Notice: maintain a large number of the item may cause memory problem, so be careful and do a calculation before running the spider to make sure the memory is large enough to hold the such number of items.

**Comment by maximenannan** [comment]
Thanks for your answers and advice, 

@grammy-jiang I store the data on GCS and did not see that it is a custom FeedExporter that was used so i will modify it in order to have the expected behaviour.
