### ISSUE TITLE
Scrapy exits before all items have been processed

### ISSUE THREAD

**Issue by sampeka** [scrapy/scrapy#3208]
I have a crawler that scrapes hundreds of items per request that need to be processed by the item pipeline. Usually this involves downloading files, uploading them to a cloud provider, then posting some json to a web service. Due to this, an item can take a long time to pass through the whole pipeline.

This means that most of the time the spider is finished crawling new urls before the items have finished being processed. I may be misreading this, but after a while it looks like the process is killed and some items are left unprocessed. My settings are pretty much out of the box, no max depth etc.

Is this a bug or intended behaviour? Is there a way to prevent the scrapy process from exiting until all items have been processed?

**Comment by grammy-jiang** [comment]
Hi, @sampeka 

I am not clear about the reason for your issue.

But from your description, I would like to suggest you put all the HTTP related work in your spider class. The pipeline module is designed to deal with the data scrape from spiders, including washing/wrangling/saving to some place, etc. None of them is to do some work related to HTTP.

**Comment by sampeka** [comment]
Hey @grammy-jiang, thanks for the response. I dug a bit more into this issue, it was related to memory usage - Docker was killing the container for exceeding its allocated memory for too long. I implemented a new file pipeline that writes to disk before uploading and that sorted it 👍
