### ISSUE TITLE
Some scrapy request don't show up in Wireshark

### ISSUE THREAD

**Issue by maximevdk** [scrapy/scrapy#3209]
### Environment info
Python 2.7.10
Scrapy 1.4.0

### Problem
I've 200+ spiders that run in parallel and for one spider I'am struggling with the following issue:  

```
2018-04-10 16:49:08,107 DEBUG  [/Library/Python/2.7/site-packages/scrapy/downloadermiddlewares/retry.py 75] [scrapy.downloadermiddlewares.retry] Retrying <GET <request_url>> (failed 1 times): [<twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>]
```

It doesn't occur when I run the spider alone or together with 10 other spiders.  
I've noticed that when this line is logged, there is no request visible in Wireshark.  

Is there a limit on how many request scrapy can handle at the same time?

**Comment by grammy-jiang** [comment]
Hi, @maximevdk 

When the connection is closed, the request can't be sent, so you can't see the request in Wireshark. This makes sense. So the problem becomes why could this happen.

The information you provided is so a few, I can't get a conclusion. It sounds like the spiders' number may be a reason for this. Have you tested these spiders all? Does only one spider have this issue and all others are fine?

**Comment by maximevdk** [comment]
Hi, @grammy-jiang, thanks for your reply.  
I'm facing this issue with multiple spiders, actually.

> When the connection is closed, the request can't be sent, so you can't see the request in Wireshark. 

So maybe there is a maximum amount of concurrent requests and the spiders waiting in the queue to do its request get a sort of timeout and log this?

How can I help? What extra information do you need?

**Comment by grammy-jiang** [comment]
hi, @maximevdk 

Maybe you met the [C10k problem](https://en.wikipedia.org/wiki/C10k_problem). I am not sure, but you can try to minimize the open sockets' number at the same time in your spider.

**Comment by Gallaecio** [comment]
I take it there is not much we can do on our side with the current information.
