### ISSUE TITLE
HttpCompressionMiddleware bug

### ISSUE THREAD

**Issue by a232319779** [scrapy/scrapy#3213]
https://github.com/scrapy/scrapy/blob/master/scrapy/downloadermiddlewares/httpcompression.py#L28

It's should be modify.

request.headers.setdefault('Accept-Encoding',
                                   b",".join(ACCEPTED_ENCODINGS))
===>>
request.headers.setdefault(b'Accept-Encoding',
                                   b",".join(ACCEPTED_ENCODINGS))

**Comment by a232319779** [comment]
and this one:
https://github.com/scrapy/scrapy/blob/master/scrapy/responsetypes.py#L76

content_type=headers[b'Content-type'],...
===>>>
content_type=headers[b'Content-Type'],

**Comment by grammy-jiang** [comment]
Hi, @a232319779 

Thanks for your posting this issue here. Please note this is an open source community, we would like to say pulling the merge request rather than just writing the code here.

When your merge request pass CI which is Travis in this project, there will be someone to read your code and make the decision to merge your code or not.

**Comment by kmike** [comment]
Hey @a232319779,

Could you please explain why you think it is a bug? request.headers is not a dictionary, it is a special object which normalizes keys, so letter case and bytes vs ascii string don't matter.

**Comment by a232319779** [comment]
hi,@kmike
1. In setdefault function, the first param need a byte object, not a string.
2. at this line, https://github.com/scrapy/scrapy/blob/master/scrapy/responsetypes.py#L74. it used "Content-Type" for conditional, but used "Content-type" in following block. 
Thanks for your open source code, it's a nice job.
But my spiders run error for these reason, maybe I think that I should report it.
