### ISSUE TITLE
how to run Multiple spider ** independently ** at the same time ?

### ISSUE THREAD

**Issue by xiaochonzi** [scrapy/scrapy#3216]
when i wrote two simple spider 
```
class Bing(Spider):

    name = "bing"

    def start_requests(self):
        for _ in range(1000):
            yield Request("http://bing.com", dont_filter=True)

    def parse(self, response):
        print(self.name, response.url)

class Sogou(Spider):
    name = "sogou"
    def start_requests(self):
        for _ in range(1000):
            yield Request('http://sogou.com', dont_filter=True)

    def parse(self, response):
        while True:
            print('123')
        print(self.name, response.url)
```

```
def run(spider_cls):
    crawler = Crawler(spider_cls)
    crawler.crawl()

run(Bing)
run(Sogou)

reactor.run()
```
just like this. Use Crawler and reactor to run these spider. Sogou spider was blocked, it was obvious. but Bing spider was blocked too, why ? and how to solve it . use Crawler class make multiple spider run independently at the same time?  I used to use twisted.threads like deferToThread , or callInThread , it couldn't  work . Can someone have some idea? Thank you very much!

**Comment by grammy-jiang** [comment]
hi, @xiaochonzi 

Please refer to the section **Running multiple spiders in the same process** in the document [Common Practices — Scrapy 1.5.0 documentation](https://doc.scrapy.org/en/latest/topics/practices.html#running-multiple-spiders-in-the-same-process).

Obviously the decorator `inlineCallbacks` is missing.

**Comment by xiaochonzi** [comment]
@grammy-jiang  thanks your comment, but i think you didn't understand my question. My question is when use scrapy to crawl multiple spiders, the multiple spider would mutual effect with each other. just like my code, when one spider was blocked , the other spider would be block too. I want to find some solution to fix it . just let Sogou run always and Bing can run too .  I has used Crawler , CrawlerRunner, CrawlerProcess to solve my problem, even i has read scrapy source code many times. I would think may be run scrapy in multiple threads , so just find twisted deferToTrhead, callInThread function , they also not work .

**Comment by grammy-jiang** [comment]
Hi, @xiaochonzi 

Please, please read the section I mentioned before. The document provides a very clear way to do what you want.

**Comment by xiaochonzi** [comment]
hi @grammy-jiang I has read again. And i use the example to try again, and it did't work . The problem is when use Crawler,CrawlerRunner,CrawlerProcess make multiple spiders run in the same thread or process, if one of these spider was blocked , just like parse callback function was printing something, the other spider wouldn't be scheduled,and always wait for other spider. This is a big problem when run multiple spider in the same process. So  If you know how to resolve it, please show me you code, I will thank you very much.

**Comment by a232319779** [comment]
it's your code problem, the code `while True: print('123')` take full of the time.It's not real blocked.

**Comment by leonardfrank** [comment]
Hi@xiaochonzi. Scrapy is based on Twisted-an event loop.There should be only one event running at the same time.The Sogou spider was in charge of the event loop all the time cause of your infinite loop 'while True', how could it yield the control to other events though?P.S., read the official documents and get the purpose of the function parse in Scrapy until writing so-called test code.

**Comment by grammy-jiang** [comment]
Hi, @xiaochonzi 

Finally, I understand your point.

Right, **twisted is a single process and single thread framework** - all of the spiders are running in one single process - anything happens in one spider will affect others' execution. You can't avoid this problem generally (deferToThread may by a way, but I think it does not suit for your case).

Your problem is you are not familiar with the principle of asynchronize framework (twisted, asyncio, etc). So my suggestion is to read more documentation in this area, and try to write code under the philosophy of asynchronize to aviod blocking.

**Comment by xiaochonzi** [comment]
@leonardfrank  @grammy-jiang  thank you all .  so i even try to run in twiestd multiple threds,   just like callInThread, but it didn't work. so I think spider and spider shoud be Independent. I wote those code because i want to write a spider manage system which was based on scrapy . And when i wrote two simple spider , and find  this problem .It couldn't avoid some spider writing some `while True` code . Could you give me some advise to figure out it.

**Comment by xiaochonzi** [comment]
@a232319779  if i has wrote some 'while True' ,how to let other spider continue run?

**Comment by grammy-jiang** [comment]
hi, @xiaochonzi 

If some loop calls are really needed in your code, try callback the method itself, just like a recursion in a function.

**Comment by djunzu** [comment]
Let me step in....
@xiaochonzi I suggest you go back and find another path. The way you are trying... it will not give you good fruits.

Plus, you will get better help in another communities like SO. This is not a Scrapy bug/feature request.

**Comment by Laerte** [comment]
On project that i'm working i have to run multiple spiders concurrent with different arguments, i use subprocess to do that.

_Example_

```
args = ['scrapy', 'crawl', 'products', '-s', 'LOG_ENABLED=False', '-t', 'json', '-o -'])
proc = Popen(args, stdout=PIPE, stderr=PIPE)

stdout, _ = proc.communicate()

results = stdout.decode("utf-8")
```

**Comment by Gallaecio** [comment]
Closing this stale question.
