### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by catsled** [scrapy/scrapy#3218]
### I need help

i want to deep in Downloader, but i'm a beginner of scrapy, and the source code is too difficult for me.If anybody can give me some advice. (like: 1. you can study some source code , and then ...).

thanks a lot!

**Comment by grammy-jiang** [comment]
Hi, @catsled 

The module of Downloader is a large part of Scrapy. It contains the downloader middleware management and also the management of the communications with target servers in many protocols (HTTP, HTTPS, FTP, etc).

So if you want to dive into this module:

1. read the source code of scrapy, understand the structure of this module
2. understand how the downloader middleware manager control the downloader middleware calling sequence
3. understand how the downloader control the downloading concurrent and the download delay
4. understand how the downloader choose the protocols to communicate with servers

**Comment by leonardfrank** [comment]
Hi, @catsled 
Here is some advice of my own:
1. You need to figure out how the event loop in Scrapy flows roughly, especially how the engine interacts with the downloader standing on your need.
2. After you have a basic understanding of the whole process, jump into the source code of downloader middleware manager, then you would know how the requests are passed and processed between the engine and the downloader more clearly and more detailly.
3. Head into the source code of the downloader. Find out what structure the downloader manages the request objects, the conditions when the downloader pops or append the request object and the method how the downloader controls concurrency and delay.

**Comment by Gallaecio** [comment]
Closing due to a lack of feedback.
