### ISSUE TITLE
Does response.meta[redirect_urls] include the final response.url?

### ISSUE THREAD

**Issue by DallanQ** [scrapy/scrapy#3219]
When my spider.parse function is called, does response.meta[redirect_urls] include the final response.url? I thought it did, but when I ran a spider today it did not.

**Comment by grammy-jiang** [comment]
Hi, @DallanQ 

No, after the redirection, the response does not save the final response's url in `response.meta['redirect_urls']`.

This can be understanded - the `response.meta['redirect_urls']` will only by modified when the downloader middleware `RedirectMiddleware` activates.

You can read the source code [here](https://github.com/scrapy/scrapy/blob/1.5.0/scrapy/downloadermiddlewares/redirect.py#L75-L80), and [here](https://github.com/scrapy/scrapy/blob/1.5.0/scrapy/downloadermiddlewares/redirect.py#L35-L36).

**Comment by DallanQ** [comment]
Thank you! I must have been hallucinating earlier.
