### ISSUE TITLE
530 error trying to open FTP directory even when supplying correct username and password

### ISSUE THREAD

**Issue by chrismp** [scrapy/scrapy#3223]
I want to use Scrapy to download files and navigate folders at `ftp://ftp.co.palm-beach.fl.us/Building%20Permits/`. 

Here's my spider:

    # -*- coding: utf-8 -*-
    import scrapy
    from scrapy.http import Request
    
    class LatestPermitsSpider(scrapy.Spider):
    	name=			"latest_permits"
    	allowed_domains=["ftp.co.palm-beach.fl.us"]
    	handle_httpstatus_list = [404]
    	
    	ftpUser=		"the_username"
    	ftpPW=			"the_password"
    	permitFilesDir=	"ftp://ftp.co.palm-beach.fl.us/Building%20Permits/"
    
    	def start_requests(self):
    		yield Request(
    			url=self.permitFilesDir,
    			meta={
    				"ftp_user": self.ftpUser,
    				"ftp_password": self.ftpPW
    			}
    		)
    
    	def parse(self,response):
    		print response.body

When I run `scrapy crawl latest_permits`, I get this error:

    ConnectionLost: ('FTP connection lost', <twisted.python.failure.Failure twisted.protocols.ftp.CommandFailed: ['530 Sorry, no ANONYMOUS access allowed.']>)

Why does this error come up even when I supply the correct username and password?

I do not know the FTP server's port number.

**Comment by myshkin** [comment]
What versions of operating system, Python, Twisted, and Scrapy are you using? It looks as if Scrapy's FTP support on Python 3 only started working with Twisted 17.1 and Scrapy 1.4 (see #2277).

Beyond that, the error message seems to indicate that Scrapy (and thus Twisted's FTP client) is trying to log in anonymously. When I use a command-line FTP client on that server and log in with a bogus username and password, I get the error message

> username and/or password was not accepted for login.

whereas anonymous FTP gives the error 

> Sorry, no ANONYMOUS access allowed.

as seen in your error message.

Your code looks fine, and I suspect problems with one of your dependencies. Are you able to crawl any other non-anonymous FTP servers?

**Comment by Gallaecio** [comment]
Closing due to a lack of feedback.
