### ISSUE TITLE
Provide a way of getting response download time

### ISSUE THREAD

**Issue by eliasdorneles** [scrapy/scrapy#3227]
Hi folks!

So today I needed a simple way to evaluate the performance for all the pages of a website, and I thought scrapy would be a great tool for quickly visiting all the pages and getting this information.
Basically, I'm interested in the time of downloading a page, and maybe more details if possible (time to start a connection, and etc).

While it was fairly easy to get the spider visiting all the pages in no time (+700 pages in ~3 min), getting the response download times per URL seems quite a challenge.

I found [this question in SO](https://stackoverflow.com/questions/15831955/scrapy-requestresponsedownload-time) which made me feel less alone, but the recommended approach of using a downloader middleware in the existing answer doesn't really work because the requests are often processed way before they are actually sent.

I tried looking at the code to see where one would need to hook to get this information, I noticed that there is some code collecting time information (like [here](https://github.com/scrapy/scrapy/blob/master/scrapy/core/downloader/webclient.py#L117) and [here](https://github.com/scrapy/scrapy/blob/master/scrapy/core/downloader/webclient.py#L158)), but I didn't have time to dig much.

In the end, I gave up and went with a requests-based script that takes 30 minutes to run but it was easy to get the information, but I would much prefer to use Scrapy for this. =)

I'd love to hear if anyone has any thoughts about this -- thanks in advance!

**Comment by lopuhin** [comment]
Hey Elias, I think in theory ``request.meta['download_latency']`` defined here https://github.com/scrapy/scrapy/blob/da1256a9c8452703213c96ebc32fae1524034442/scrapy/core/downloader/webclient.py#L143 is what you need, but in practice it can be larger due to #3197 because it is measured in python code - but I think this is the best we can get with any async downloader.

**Comment by leonardfrank** [comment]
Hi, @eliasdorneles

@lopuhin offers the key point. I would give a more specified way to record the response downloaded time per URL. 

Write a downloader middleware to extract ` response.meta['download_latency']` from response in 
 process_response method. Make it active in your project. I would suggest you keep data in databases for your need. 

This is the tutorial about writing your own downlaoder middleware:  [https://doc.scrapy.org/en/latest/topics/downloader-middleware.html#writing-your-own-downloader-middleware](url)

**Comment by eliasdorneles** [comment]
Thank you, @lopuhin !

So if I understood correctly, it gives the time between starting the connection (`HTTPClientFactory.__init__`) and finishing fetching the headers (`HTTPClient.handleEndHeaders`), and therefore doesn't contain the time for getting the body as well.
I guess your point about being the best we can get with async downloaders is because measuring the time to get the body would always be affected by the other requests handling, right?

I see, so if I want an accurate measurement of getting the body, I suppose I should stick w/ the slow sync downloader.
Thanks a bunch! :+1: :+1: 

@leonardfrank thanks, I'm familiar with downloader middlewares. =)
