### ISSUE TITLE
Settings from command line not working?

### ISSUE THREAD

**Issue by thernstig** [scrapy/scrapy#3233]
Hi,

I am trying to use the -s flag according to this:
https://doc.scrapy.org/en/latest/topics/settings.html#command-line-options

But when I try it like this, the setting does not take effect: `scrapy crawl spider.quotes.toscrape.com -s ELASTICSEARCH_ENABLED=False`

It works if I manually edit settings.py and set ELASTICSEARCH_ENABLED to False.

Why is this?

**Comment by grammy-jiang** [comment]
Hi, @thernstig 

Emmm, please do not use dot in the spider's name. Replace the dot with an underscore and try again.

**Comment by thernstig** [comment]
@grammy-jiang Is there a reason for this? I have not noticed any other issues with this and I cannot see any documentation that spider cannot have dots in them, but I might have missed it.

I had a valid reason to do this. Scrapy logging for spiders, in for example pipelines, can be accessed via spider.logger. If you have generic names, it's hard to implement custom logging for all your spiders. As Python logging uses parent-child relationships, I am naming all my spiders with the prefix "spider.". This, by design of python logging, creates a parent logger called "spider" which I can then easily create a special logging handler for.

So it creates a very good way for me to log and filter all spiders.

**Comment by grammy-jiang** [comment]
Hi, @thernstig 

Have you tried to run the spider without dot in name? Does it work?

For your consideration, you can write your own `spider.logger` to replace the one inherited from `scrapy.spiders.Spider`. That will give you the ability to handle the logging of spiders in more powerful way.

**Comment by grammy-jiang** [comment]
Hi, @thernstig 

I have gone through the source code, and there is no any restriction on the spider's name.

So, your naming method looks fine. But I still believe that using dot in a name is a bad practice because it makes the confusion between the module path and your name.

**Comment by grammy-jiang** [comment]
Hi, @thernstig 

Scrapy is a well-known framework in web crawling, and I think this community is already a good one - your issue will be commented by someone in a few days, and the owner and contributes of this project are really warm to answer the questions and merge the pull requests.

If you really think this feature is necessary, pull requests are all welcomed!

**Comment by ajpen** [comment]
@thernstig I believe dot notion is avoided because it is used by python to signify objects/modules that belong to a module. Using the dot notion in your names can confuse the function that loads spiders.

**Comment by wRAR** [comment]
Hello @thernstig, as `ELASTICSEARCH_ENABLED` looks like a custom settings var, how are you using it? If you are e.g. importing it from `settings.py` directly `-s` won't work. You need to use `self.settings` as documented [here](https://doc.scrapy.org/en/latest/topics/settings.html#how-to-access-settings).

**Comment by thernstig** [comment]
@wRAR Thank you, that explains it.

**Comment by thernstig** [comment]
@wRAR Actually we are getting it in from_crawler via `enabled = crawler.settings.get('ELASTICSEARCH_ENABLED', False)` in all locations where we use it.

**Comment by wRAR** [comment]
@thernstig this works for me, though the value is a string `'False'`, not a bool.

**Comment by thernstig** [comment]
That might be the problem then, thanks again 👍
