### ISSUE TITLE
CSVItemExporter creates multiple files

### ISSUE THREAD

**Issue by dmikhaylov** [scrapy/scrapy#3239]
I'm not sure if it's right place to post this issue, but what I've just noticed is that CSVItemExporter creates multiple files for some reason with the same name (they have a number as the suffix though), so they look like 

```
myspider_2018-04-26_15.09.06.231201 (26).csv
myspider_2018-04-26_15.09.06.231201 (27).csv
```

I use docker to run scrapy and it happens only on my Ubuntu machine. Again, I'm not sure if it's scrapy issue...

**Comment by VMRuiz** [comment]
Could you please add more information like logs and settings files?

**Comment by Gallaecio** [comment]
Closing due to a lack of feedback.
