### ISSUE TITLE
Possibility of retrying requests by any response characteristic (using callback).

### ISSUE THREAD

**Issue by dyeray** [scrapy/scrapy#3240]
The retry middleware allows to retry requests depending on the response status. However, some websites return a 200 code on error, so we may want to retry depending on a response header, or even the response body.

Instead of implementing this on a new middleware or on the spider itself I suggest a small backwards compatible change on the retry middleware. The user could define a list of callbacks on a settings variable, like:

```
RETRY_CALLBACKS = [
    "myproject.retry_callbacks.woocommerce_retry_callback",
    "myproject.retry_callbacks.google_retry_callback",
]
```

These callbacks would receive both the request and response object, so the developer can implement the retry conditions. In case that the callback returns True, the middleware would call `self._retry`.

This is something I have used in a couple of projects (inheriting from the retry middleware), so I'd be happy to add this feature to Scrapy.

**Comment by dyeray** [comment]
These are not middlewares, these are callback functions that a user can create to inspect a request and decide if it needs to be retried or not. A small backwards compatible change on the RetryMiddleware would call those callbacks as use them as a third option to decide if a request must be retried or not (right now the retry middleware supports retry by http status code and exception raised).

**Comment by VMRuiz** [comment]
I think adding this callbacks methods somehow breaks the clear structure of the Scrapy Core. Also, this functionality can be implemented in middlewares which can be configured with different priority values to set when should be run each retry_middleware instead of parsing all of them in same moment.

**Comment by dyeray** [comment]
It could also be added as a new middleware. The alternative is handling whether to retry or not on the response callback itself which can make code less clear and forces the developer to reimplement things like the number of retries each time.

**Comment by leonardfrank** [comment]
@VMRuiz Hi, Really glad to read your comment. Couldn't agree with you anymore.
@dyeray  Hi, sure you can add callback functions to a spider. But in Scrapy, each component takes its own responsibility. Spider should yield Item objects and Request objects. You got the status code of 200, obviously, you got blocked. What you should do is to resend this request like the Retry Middleware does,
to keep the functionality of each part consistent and clear.

**Comment by dyeray** [comment]
Hi @leonardfrank. I was not suggesting adding callback functions to the spider. I was suggesting adding some functions (not related to the spider), to arbitrarily extend the detection of what requests need to be detected on the downloader middleware, so the user does not have to: 1. create a new middleware for each website that reports bans in an inconsistent way or 2. handle it on the spider itself.

Why shouldn't this not be the responsibility of the middleware? Is it because the user is going to potentially inspect the body on the middleware?

**Comment by dyeray** [comment]
Hi @grammy-jiang,

Only point 1 is true: My idea is that the retry condition can be customized by users, using their own defined functions (what I called callbacks, maybe not the best choice of words) that receive the response and return a boolean. This would allow to continue keeping the retry logic outside of the spider, and keep using all the retry parameters (number of retries, retry priority, etc.) of the base middleware.

Probably I will push a separate package that people can import if they need to use it instead of trying to merge into the base Scrapy.
