### ISSUE TITLE
How can i change a new proxy with middleware when i get 403/302?

### ISSUE THREAD

**Issue by Yuan-Hang** [scrapy/scrapy#3243]
i have write down the middleware:
```python
def process_request(self, request, spider):
    request = self.change_proxy(request)   # set request proxy

def process_response(self, request, response, spider):
    if response.status != 200:
        self.delete_proxy()           # remove unusable proxy
        return request.copy()         # send request to process_request to change proxy
    return response

def process_exception(self, request, exception, spider):
    self.delete_proxy()              # remove unusable proxy
    # if comment the code below, i will not get 302. but maybe i will lost crawl some webpage?
    return request.copy()            # send request to process_request to change proxy

```
First, I have some proxies in redis, what i want to do is:
1.  give each request a random proxy,
2. when the connection to proxy failed(`process_exception` called), change a new proxy and re-crawl the webpage.
3. when proxy is banned by the website(`response.status != 200`), change a new proxy and re-crawl the webpage.

**Comment by grammy-jiang** [comment]
Hi, @Yuan-Hang ,

There are many plugins on GitHub to do such things in scrapy. Please read them before posting your question.

And if you are looking for a help, please go to StackOverflow - here is for issues and new features required.
