### ISSUE TITLE
Can not telnet into Scrapy in a container of docker.

### ISSUE THREAD

**Issue by kingname** [scrapy/scrapy#3261]
To track the performance, I usually use `telnet localhost 6023` to Scrapy and then execute `prefs()` to check some info.

However, when my scrapy project running in a container of Docker, I can not execute  `telnet localhost 6023`:

```
telnet localhost 6023
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused
```

P.S.: I have already attach into the container, this command is executed in the container.

**Comment by kmike** [comment]
I'm not sure why it happens, but it is unlikely it can be fixed in Scrapy; likely it is some Docker usage issue. I suggest asking it at https://stackoverflow.com.
