### ISSUE TITLE
crawl zomato.com with error: twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion: Connection lost.

### ISSUE THREAD

**Issue by offbye** [scrapy/scrapy#3262]
I met a error when crawl zomato.com.

my env is 
```
scrapy version -v
Scrapy       : 1.5.0
lxml         : 4.2.1.0
libxml2      : 2.9.8
cssselect    : 1.0.3
parsel       : 1.4.0
w3lib        : 1.19.0
Twisted      : 18.4.0
Python       : 2.7.12 (default, Dec  4 2017, 14:50:18) - [GCC 5.4.0 20160609]
pyOpenSSL    : 17.5.0 (OpenSSL 1.1.0h  27 Mar 2018)
cryptography : 2.2.2
Platform     : Linux-4.4.0-116-generic-x86_64-with-Ubuntu-16.04-xenial


 scrapy shell  https://www.zomato.com/dubai/abs-absolute-barbecues-al-sufouh/photos?category=ambience

```
with below errors , I have found sevaral closed issues about it , but just not solved.

2018-05-16 11:28:54 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://www.zomato.com/dubai/abs-absolute-barbecues-al-sufouh/photos?category=ambience> (failed 1 times): [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion: Connection lost.>]

**Comment by bryanhan1001** [comment]
for the scrapy shell, you can try to add a user agent like

- scrapy shell -s USER_AGENT='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 Safari/605.1.15'  https://www.zomato.com/dubai/abs-absolute-barbecues-al-sufouh/photos?category=ambience
it works for me

**Comment by bryanhan1001** [comment]
for the scrapy shell, you can try to add a user agent like

_scrapy shell -s USER_AGENT='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 Safari/605.1.15' https://www.zomato.com/dubai/abs-absolute-barbecues-al-sufouh/photos?category=ambience_
it works for me

**Comment by bryanhan1001** [comment]
for the scrapy shell, you can try to add user agent like below:
`scrapy shell -s USER_AGENT="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36" https://www.zomato.com/dubai/abs-absolute-barbecues-al-sufouh/photos?category=ambience`
it works fo me.

**Comment by niquepa** [comment]
Including the USER_AGENT fixes the issue
