### ISSUE TITLE
Documentation error about 'max_retry_times'

### ISSUE THREAD

**Issue by rbarbaresco** [scrapy/scrapy#3268]
The [documentation](https://doc.scrapy.org/en/latest/topics/request-response.html#std:reqmeta-max_retry_times) says that if we add a **max_retry_times** in meta of a request it would take higher precedence over the **RETRY_TIMES** settings.

Well I don't think it's true, because **max_retry_times** doesn't work at all, but I noticed that **retry_times** works perfectly as the documentation says **max_retry_times** would work.

I believe that the right thing to do is keep the **retry_times** and fix the documentation, once it looks like the standard for any settings in Scrapy projects.

I can open a pull request to fix this, but I'm not sure if it's a bug or the documentation is wrong.

```
$ scrapy version -v
Scrapy    : 1.3.3
lxml      : 4.2.1.0
libxml2   : 2.9.8
cssselect : 1.0.3
parsel    : 1.4.0
w3lib     : 1.19.0
Twisted   : 16.4.1
Python    : 2.7.15rc1 (default, Apr 15 2018, 21:51:34) - [GCC 7.3.0]
pyOpenSSL : 17.5.0 (OpenSSL 1.1.0h  27 Mar 2018)
Platform  : Linux-4.15.0-20-generic-x86_64-with-Ubuntu-18.04-bionic
```

**Comment by lucywang000** [comment]
I don't think that's correct. The `retry_times` request meta is not meant to be set by the user - it's used by the retry middleware to track how many times the current request has been retried. See the code here: https://github.com/scrapy/scrapy/blob/1.5/scrapy/downloadermiddlewares/retry.py#L68-L69

> Well I don't think it's true, because max_retry_times doesn't work at all

Please provide a minimum example scrapy project, and corresponding logs to demonstrate that.

**Comment by rbarbaresco** [comment]
Thankyou @lucywang000, I think you are right. I could not reproduce the problem anymore, I believe it was something else about my application.
