### ISSUE TITLE
beef is not working in my pc

### ISSUE THREAD

**Issue by prasanth111** [scrapy/scrapy#3271]
UserWarning: You do not have a working installation of the service_identity module: 'cannot import name opentype'.  Please install it from <https://pypi.python.org/pypi/service_identity> and make sure all of its dependencies are satisfied.  Without the service_identity module, Twisted can perform only rudimentary TLS client hostname verification.  Many valid certificate/hostname mappings may be rejected.
                                                    plz help me to start beef

**Comment by lucywang000** [comment]
Sorry but what is beef? I googled "beef scrapy" and no relevant results. On pypi there is a https://pypi.org/project/beef/ but there is only very poor info there.
