### ISSUE TITLE
TypeError: 'generator' object is not callable

### ISSUE THREAD

**Issue by aditya-15** [scrapy/scrapy#3277]
When running scrapy crawl <spider_name> from commandline , I am getting the below error . 

`Unhandled error in Deferred:
2018-05-29 03:00:52 [twisted] CRITICAL: Unhandled error in Deferred:

2018-05-29 03:00:52 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "/usr/src/venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "/usr/src/venv/lib/python3.6/site-packages/scrapy/crawler.py", line 81, in crawl
    start_requests = iter(self.spider.start_requests())
TypeError: 'generator' object is not callable
`

**Comment by wRAR** [comment]
Hello @aditya-15, are you doing something non-trivial with your spider's `start_requests` method?

**Comment by aditya-15** [comment]
I am just reading a list of urls from a file and yielding scrapy.Request .

Not sure if below point helps or not : 

`python
 @property
    def start_requests(self):
        urls = [
            'http://quotes.toscrape.com/page/1/',
            'http://quotes.toscrape.com/page/2/',
        ]
        for url in urls:
            yield scrapy.Request(url=url, callback=self.parse)
`
I get the generator error with above code . 
If I remove property , then this error does not appear. Is there something obvious that I am missing. 
vs 

`
    def start_requests(self):
        urls = [
            'http://quotes.toscrape.com/page/1/',
            'http://quotes.toscrape.com/page/2/',
        ]
        for url in urls:
            yield scrapy.Request(url=url, callback=self.parse)
`

**Comment by wRAR** [comment]
@aditya-15 why are you adding `@property` there? The error you get is expected with it as it turns `start_requests` into a result of `start_requests()`.

**Comment by aditya-15** [comment]
Got it . I think I might have messed up with the IDE , which probably inserted it . 

My mistake . Closing the Issue , as the crawling code is working as expected.
