### ISSUE TITLE
IMAGES_STORE_S3_ACL is not applied to thumbnails

### ISSUE THREAD

**Issue by gcrookie** [scrapy/scrapy#3278]
Hi,

I have been playing around with the images pipeline to store images on AWS S3. The full images and thumbnails get stored in S3, but only full images get the ACL applied, the thumbnails don't.

I was expecting the thumbnails to set the same ACL as defined by IMAGES_STORE_S3_ACL . I could not find any specific scrapy setting for this.

Appreciate your feedback.

Cheers

**Comment by wRAR** [comment]
Hello @gcrookie, I've just tested this and it looks like the ACL is correctly sent for both the main image and the thumbnail. I even see `x-amz-acl:public-read` in both `PUT` requests in the botocore debug.

**Comment by Gallaecio** [comment]
Closing due to a lack of feedback from the author.
