### ISSUE TITLE
Update debugging memory leaks section in the docs

### ISSUE THREAD

**Issue by lopuhin** [scrapy/scrapy#3282]
https://doc.scrapy.org/en/latest/topics/leaks.html#debugging-memory-leaks-with-guppy
guppy library is recommended,  but I think it does not support python 3. It's possible to use muppy instead, which is very similar and has python 3 support: https://pythonhosted.org/Pympler/muppy.html

**Comment by aaqaishtyaq** [comment]
Hi @lopuhin I want to work on this. Can you guide me. How should I recreate this to get started ?

**Comment by lopuhin** [comment]
hi @aaqaishtyaq sorry for not responding on time, looks like there is already a PR that resolves this issue: #3284

**Comment by kmike** [comment]
Fixed by https://github.com/scrapy/scrapy/pull/3284.
