### ISSUE TITLE
raise SchemeNotSupported("Unsupported scheme: %r" % (uri.scheme,)) twisted.web.error.SchemeNotSupported: Unsupported scheme: b'' 2018-06-11 13:02:26 [scrapy.core.engine] INFO: Closing spider (finished) 2018-06-11 13:02:26 [scrapy.statscollectors] INFO: Dumping Scrapy stats:

### ISSUE THREAD

**Issue by venkateshchary** [scrapy/scrapy#3287]
def start_requests(self):
    request = scrapy.Request(url="http://www.xxxxx.com",callback=self.parse ,dont_filter = True,)
    yield request

can anyone please help 
if the website is not secured and calling from the start_requests it is raising the error  like unsupported scheme b' '
but the same url is working in start_urls =["http://www.xxxxx.com"]

**Comment by wRAR** [comment]
Hello @venkateshchary. This sounds like you are passing an empty URL somewhere. Can you please show the actual code?

**Comment by kmike** [comment]
@venkateshchary as @wRAR said, it is likely an issue with your spider, not with Scrapy itself. We're using this issue tracker to track Scrapy bugs and feature requests; for general support we use different channels, e.g. https://stackoverflow.com (use tag "scrapy").
