### ISSUE TITLE
Missing syntax highlighting in docs

### ISSUE THREAD

**Issue by faheel** [scrapy/scrapy#3289]
The code blocks in the Scrapy docs do not have syntax highlighting which makes it _slightly_ difficult to go through the code.

It can be easily added by starting the code blocks with the following RST syntax for defining the language (Python in the following example):
```rst
.. code:: python
```

**Comment by faheel** [comment]
I'd like to take up this task if no one's already working on it.

**Comment by lopuhin** [comment]
@faheel I think it's a good idea, I don't think anyone is working on it at the moment

**Comment by faheel** [comment]
I noticed something strange happening: when I view the [latest version](https://doc.scrapy.org/en/latest/intro/overview.html) of the docs, or a [specific version](https://doc.scrapy.org/en/1.5/intro/overview.html), there's no syntax highlighting for the code blocks. However, when I view the [master version](https://doc.scrapy.org/en/master/intro/overview.html), all code blocks are properly syntax highlighted.

@lopuhin Any idea why this might be happening?

**Comment by lopuhin** [comment]
@faheel this could be due to https://github.com/scrapy/scrapy/pull/3123 which is not released yet, or updated sphinx on RTD side that happened after the docs for the last release were built (and caused above PR). Docs for the next release should look like current master docs.

**Comment by Gallaecio** [comment]
This seems fixed.
