### ISSUE TITLE
Probe command

### ISSUE THREAD

**Issue by pablohoffman** [scrapy/scrapy#33]
Sometimes pages depend on certain HTTP request headers sent, for rendering the expected result, and it's a manual and tedious job to find out which headers those are.

So, here's an idea for automating this probing mechanism: create a new scrapy command `probe` which takes a url as argument and a text to look for.

Scrapy then tries several combinations of HTTP headers (user-agent, accept, etc) and return a set that works (where works mean that the text passed is found).

Here's a real world example to illustrate:

http://www.storage-cabinets-online.com/IVG2/N/ProductID-118021.htm

The page should contain a string `'var sFeatures'`, but that string is not returned with the default Scrapy HTTP request headers. So we run scrapy probe on it:

``` sh
$ scrapy probe http://www.storage-cabinets-online.com/IVG2/N/ProductID-118021.htm 'var sFeatures'
Found set of working headers:
{'Host': 'www.storage-cabinets-online.com', 'User-Agent': 'Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.2.10) Gecko/20100915 Ubuntu/10.04 (lucid)
Firefox/3.6.10', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Accept-Encoding': 'gzip,deflate',
'Accept-Charset': 'ISO-8859-1,utf-8;q=0.7,*;q=0.7', 'Keep-Alive': '115'}
```

The Scrapy probe command would try a different list of well known user-agents, along with Accept headers.

**Comment by pablohoffman** [comment]
any interest in resurrecting this one for Scrapy 1.0 @nramirezuy @kmike @dangra @Curita @redapple ?

**Comment by kmike** [comment]
No interest from me :) `scrapy probe` looks a bit too specific; I'm not sure there is a single best solution, and it is a feature which can live fine outside Scrapy.

I like @csalazar's approach; it looks a bit similar to what parts of https://github.com/DRMacIver/hypothesis library are doing - given an example, simplify it until it fails.

**Comment by nramirezuy** [comment]
I'm agree with @kmike 

---> Close ? \/

**Comment by pablohoffman** [comment]
I quite like the `minreq` idea, and (I think) it shares the same goal of the (original) `scrapy probe` idea.

What do you think about adding `minreq` as a scrapy command?. I think it's a useful thing to have in the "scraping toolkit" and thus makes a good fit for a scrapy command (in addition to getting more exposure, usage and contributions).

/cc @csalazar

**Comment by csalazar** [comment]
@pablohoffman sure, I'll add *POST* support and tests. The command should be called `probe` or `minreq`?

**Comment by nramirezuy** [comment]
@csalazar I think `minreq` is fine, since we are just making your app more visible.

**Comment by pablohoffman** [comment]
`minreq` sounds good to me

**Comment by cathalgarvey** [comment]
Hey @csalazar - Did you ever write the code for this, and are you still interested in contributing? I think this would be a great feature. But if not, I will close this issue as stale, particularly as another solution exists (minreq).
