### ISSUE TITLE
Is there any way to use Scrapy with IBM Cloud functions?

### ISSUE THREAD

**Issue by Borisboky** [scrapy/scrapy#3301]
Hi,

Can Scrapy library be used with IBM Cloud functions?

In the [docs](https://console.bluemix.net/docs/openwhisk/openwhisk_reference.html#openwhisk_reference) the they say that `Python 3 Actions (Jessie based)` has Scrapy as package, but I'm couldn't figure out how to use it?

**Comment by wRAR** [comment]
Hello @Borisboky! I don't know anything about IBM Cloud but https://console.bluemix.net/docs/openwhisk/openwhisk_actions.html#creating-python-actions suggests you can easily run Python code after writing a proper function that calls your code and that you can easily bundle multi-file Python projects. So it seems the main question is how to run a spider without calling the `scrapy` script? This is documented [here](https://doc.scrapy.org/en/latest/topics/practices.html#run-scrapy-from-a-script).
I guess you need to take extra care about the Twisted reactor (note that the doc covers both the case when you don't care about it and when you already have it) and about implicit things that may be forbidden in your environment like writing files.

Hope this helps.

**Comment by Borisboky** [comment]
Hello @wRAR 

I've tried, but without success. My `__main__.py` is as follows:

    import scrapy
    from scrapy.crawler import CrawlerProcess

    class AutoscoutListSpider(scrapy.Spider):
        name = "vehicles list"
    
        def __init__(self, params, *args, **kwargs):
            super(AutoscoutListSpider, self).__init__(*args, **kwargs)
            make = params.get("make", None)
            model = params.get("model", None)
            mileage = params.get("mileage", None)
    
            init_url = "https://www.autoscout24.be/nl/resultaten?sort=standard&desc=0&ustate=N%2CU&size=20&page=1&cy=B&mmvmd0={0}&mmvmk0={1}&kmto={2}&atype=C&".format(
                model, make, mileage)
            self.start_urls = [init_url]
    
        def parse(self, response):
            # Get total result on list load
            init_total_results = int(response.css('.cl-filters-summary-counter::text').extract_first().replace('.', ''))
            if init_total_results > 400:
                yield {"message": "There are MORE then 400 results"}
            else:
                yield {"message": "There are LESS then 400 results"}
    
    
    def main(params):
        process = CrawlerProcess()
        try:
            process.crawl(AutoscoutListSpider, params)
            process.start()
            return {"Success ": "The crawler (make: {0}, model: {1}, mileage: {2}) is successfully executed.".format(
                params['make'], params['model'], params['mileage'])}
        except Exception as e:
            return {"Error ": e, "params ": params}

The whole process to add this function is as follows:

 1. `zip -r ascrawler.zip __main__.py common.py` // Thus I create a zip file to upload it. (*There is also a common.py file. I removed it from here for simplicity.*)
 2. `ibmcloud wsk action create ascrawler --kind python:3 ascrawler.zip` // Create the function and add it to cloud
 3. `ibmcloud wsk action invoke --blocking --result ascrawler --param make 9 --param model 1624 --param mileage 2500` // Invoke the function with parameters

I do not have to install Scrapy with `pip`, because this is one of the standard packages installed with `--kind python:3` . Thus I do not need `virtualenv` at all, if I understand the [docs](https://console.bluemix.net/docs/openwhisk/openwhisk_reference.html#openwhisk_syslimits) good.

After executing step three I get results as follows:

    {"Success ": "The crawler (make: 9, model: 1624, mileage: 2500) is successfully executed."}

Thus I do not get any errors, but it didn't come in `AutoscoutListSpider` class at all. Why?

It should return also `{"message": "There are MORE then 400 results"}`. Any idea?

When I run it from python console as follows:

    main({"make":"9", "model":"1624", "mileage":"2500"})

It returns correct result:

    {"message": "There are MORE then 400 results"}
    {"Success ": "The crawler (make: 9, model: 1624, mileage: 2500) is successfully executed."}

**Comment by Gallaecio** [comment]
Please, use [StackOverflow](https://stackoverflow.com/tags/scrapy) to ask this type of questions. See [Getting Help](https://docs.scrapy.org/en/latest/#getting-help).
