### ISSUE TITLE
Same spider for different websites

### ISSUE THREAD

**Issue by maarusaa** [scrapy/scrapy#3310]
Hi :)
Is it possible to use same spider for different websites at the same time? Lets say I have an original spider which can crawl any website. Then I have a program which calls the original spider at the same time and changes the start urls and the spider name. 

I tried with this:
for _ in range(2):
    print("Write spider name:")
    spider = input()
    Spider.name = spider

    runner = CrawlerRunner(get_project_settings())
    runner.crawl(OriginalSpider)
    d = runner.join()
    d.addBoth(lambda _: reactor.stop())
reactor.run()

But i have two errors:
- when I write the second spider it ends crawling the first one
- crawling of the second spider stops somewhere in the middle, doesn't crawl the whole page (if I crawl it separately it work perfect )

**Comment by oussama-ht** [comment]
u can use multi start_url 
but be carful in the xpath variable
