### ISSUE TITLE
Quick 1.5.1 release tag?

### ISSUE THREAD

**Issue by nyov** [scrapy/scrapy#3323]
I was wondering if you guys could do a 1.5.x release on https://github.com/scrapy/scrapy/commit/8be28fe4ca8b1cd011d5f7e03661da8a6bb3217b (or later) so debian can have a fix for [#891725](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=891725) while waiting on 1.6 ?

**Comment by kmike** [comment]
I'm fine with that, and it can be good to have 1.5.1, since we've removed some backwards compatibility shims in 1.6. Though for this particular issue why not pin w3lib to 1.18.0?

**Comment by nyov** [comment]
I'd guess nobody felt like doing that, but a new release would get picked up by the release file watchdog and (assumedly) generate more interest with the maintainers than the open bug.
But I'll point out the possibility to the bug.

**Comment by kmike** [comment]
@nyov actually I was cherry-picking changes to 1.5 branch when you've written your comment :) It may be not a bad idea to make 1.5.1 release, it could justify being a bit more aggressive with deprecations in 1.6.
