### ISSUE TITLE
Official support for 3.7

### ISSUE THREAD

**Issue by jslay88** [scrapy/scrapy#3324]
With the public release of Python 3.7, it would be nice to have it 'officially' supported by scrapy, and have tox test for it as well. This would allow 3.7 production environments to 'safely' use scrapy.

**Comment by lopuhin** [comment]
@jslay88 totally agree! I'll close this as a duplicate of #3143

**Comment by jslay88** [comment]
oh sorry! did not see the other one! I even searched, but i guess my search skills are lacking today. Sorry for the dupe!

**Comment by lopuhin** [comment]
no problem at all :)
