### ISSUE TITLE
can't specify relative path with 'file' feed scheme

### ISSUE THREAD

**Issue by WaferJay** [scrapy/scrapy#3338]
Hello. I specify FEED_URI:`FEED_URI = "file://feeds/%(name)s/%(time)s.json"` and running the scrapy project with root user. But the feed file saved in "/%(name)s/%(time)s.json"

I found this and I try it in Python Shell.
https://github.com/scrapy/scrapy/blob/dfe6d3d59aa3de7a96c1883d0f3f576ba5994aa9/scrapy/extensions/feedexport.py#L82

```
In [1]: from w3lib.url import file_uri_to_path
In [2]: file_uri_to_path("file://test/file.txt")
Out[2]: '/file.txt'
```

By the way, my w3lib module is v1.18.0.

Although, I can write without 'file://' prefix like this to avoid that problem.
`FEED_URI = "test/file.txt"`

I'm so sorry. My English is pool.

**Comment by wRAR** [comment]
Hello @WaferJay, the `file://` scheme requires three consecutive slashes for local files: `"file:///feeds/%(name)s/%(time)s.json"` (this is not specific to w3lib or scrapy).

**Comment by WaferJay** [comment]
@wRAR 
Oh, I don't even know it. I acted foolishly. Thank you.

**Comment by AchiraFernando** [comment]
hi wRAR.
Where did you specify the FEED_URI ?
** I want to hard code the URI in the scrapper without feeding it through the running script.
Can I know how did you add the FEED_URI ?

**Comment by wRAR** [comment]
@AchiraFernando this is a wrong place for such questions. Please read [the documentation on Scrapy settings](https://docs.scrapy.org/en/latest/topics/settings.html).

**Comment by WaferJay** [comment]
Hi, @AchiraFernando. You can specify the FEED_URI in <project>/settings.py. Hope this helps.
