### ISSUE TITLE
If callback=None as a callback function we will use current function

### ISSUE THREAD

**Issue by amarynets** [scrapy/scrapy#3340]
If we will make a request like this
```
def parse(self, response):
    # some code
    yield scrapy.Request(url, callback=self.None, meta={'foo': bar}, dont_filter=True)
```

We will not get an exception or something like that. The spider will just make a request and use the same function for parsing.

Is it a correct logic? Because I didn't find it in the documentation

**Comment by wRAR** [comment]
Hello @amarynets. It won't use the current function, it will use the `parse` function. It's documented [here](https://doc.scrapy.org/en/latest/topics/request-response.html#request-objects): "If a Request doesn’t specify a callback, the spider’s parse() method will be used."

**Comment by amarynets** [comment]
Hello @wRAR thanks
