### ISSUE TITLE
Overriding the MailSender class

### ISSUE THREAD

**Issue by nadzimo** [scrapy/scrapy#3341]
I'd like to use the built-in email notification service for when a scraper exceeds a certain memory limit (`MEMUSAGE_NOTIFY_MAIL` setting), but it looks like it's not possible to specify the MailSender class to use to send the email. I don't want to use SMTP, I'd like to use a third-party mail sender (e.g. sendgrid).
Is there a way around this?
Thanks

**Comment by nadzimo** [comment]
Closing this as it seems a feature request.

**Comment by nadzimo** [comment]
Closing this as it seems a feature request.

**Comment by kmike** [comment]
Feature requests are fine, feel free to reopen this ticket. See also: https://github.com/scrapy/scrapy/pull/3346#issuecomment-406436149.

**Comment by rennerocha** [comment]
@nadzimo ,
You could create a custom extension extending from `MemoryUsage` and user your custom mail sender class (inheriting it from `scrapy.mail.MailSender`:
```
from scrapy.extensions.memusage import MemoryUsage

class SendGridMemoryUsage(MemoryUsage):
    def __init__(self, crawler):
        super().__init__(crawler)
        self.mail = MyCustomMailSenderClass.from_settings(crawler.settings)
```
#3346 will include a new setting name to make this easier.
