### ISSUE TITLE
Unknown Command when I enter "scrapy crawl quotes"

### ISSUE THREAD

**Issue by roxybilson** [scrapy/scrapy#3344]
HI I AM NEW TO SCRAPY, AND IM HAVING AN ISSUE. CAN SOMEONE HELP PLEASE?
When I enter "scrapy crawl quotes" on terminal, it returns "Unknown command: crawl"
Does anyone know what could be the reason? I followed everything from the tutorial but except that part was when it was incorrect.

**Comment by HassanQamar07** [comment]
@roxybilson , when you use crawl command outside of scrapy project, it gives this message. You should cd to the directory containing scrapy.cfg or any subdirectory of it.

**Comment by roxybilson** [comment]
Sorry I am new to this.
Cd to the directory like typing  cd scraoy.cfg 
in the terminal?

**Comment by lookfwd** [comment]
Try some video tutorials... e.g.

https://www.youtube.com/watch?v=3mGSQ_8ewtE
https://www.youtube.com/watch?v=5cstRCeFDkY

**Comment by Chelsea31** [comment]
> Sorry I am new to this. Cd to the directory like typing cd scraoy.cfg in the terminal?
> […](#)
> On Jul 19, 2018, at 1:32 PM, Hassan Raza ***@***.***> wrote: @roxybilson , when you use crawl command outside of scrapy project, it gives this message. You should cd to the directory containing scrapy.cfg or any subdirectory of it. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

your project directory must be like:
```

|_your-project-name/
    |_ your-project-name/
        |_spider/    <----- go to this directory and run the command scrapy crawl <spide-name>
           |_your-spider.py

```
