### ISSUE TITLE
Race condition in CsvItemExporter from exporters.py

### ISSUE THREAD

**Issue by medvedev1088** [scrapy/scrapy#3349]
In the below piece of code when `_headers_not_written` is checked a race condition happens which results in headers being written in the middle of the file (rows are written in another thread):

```
def export_item(self, item):
        if self._headers_not_written:
            self._headers_not_written = False
            self._write_headers_and_set_fields_to_export(item)

        fields = self._get_serialized_fields(item, default_value='',
                                             include_empty=True)
        values = list(self._build_row(x for _, x in fields))
        self.csv_writer.writerow(values)
```

**Comment by kmike** [comment]
Why are rows written in another thread?

**Comment by medvedev1088** [comment]
I thought items are exported in multiple threads. Correct me if I’m wrong. I found this issue when using csv exporter in another application.

**Comment by wRAR** [comment]
@medvedev1088 can you please provide more info and/or a test case? Do you mean you are using `CsvItemExporter` directly in some code not related to Scrapy?

**Comment by medvedev1088** [comment]
@wRAR yes I use it here https://github.com/blockchain-etl/ethereum-etl/blob/master/ethereumetl/jobs/export_blocks_job.py#L84. The calls to `export_item` are done in multiple threads, which causes the race condition. 

The fix I used is double-checked locking https://github.com/blockchain-etl/ethereum-etl/blob/master/ethereumetl/exporters.py#L129

**Comment by Gallaecio** [comment]
@kmike @wRAR Should we close this? I assume Scrapy does not aim to be thread safe, beyond what Twisted’s callInThread allows.

**Comment by wRAR** [comment]
@Gallaecio agree
