### ISSUE TITLE
How can I use jupyter notebook instead of Ipython or Bpython

### ISSUE THREAD

**Issue by javenleeCH** [scrapy/scrapy#3351]
How can I use jupyter notebook instead of Ipython or Bpython

**Comment by wRAR** [comment]
@javenleeCH do you mean `scrapy shell` or something else?

**Comment by javenleeCH** [comment]
> @javenleeCH do you mean `scrapy shell` or something else?

yes, can you help me ?

**Comment by lopuhin** [comment]
@javenleeCH there are plenty results on google for scrapy + jupyter notebook integration, e.g. https://www.jitsejan.com/using-scrapy-in-jupyter-notebook.html and https://stackoverflow.com/questions/40856730/how-to-run-scrapy-project-in-jupyter, do you have any specific questions? Also if this is a scrapy usage question, not a bug report / feature request, stackoverflow might be a better place to ask this.

**Comment by javenleeCH** [comment]
> @javenleeCH there are plenty results on google for scrapy + jupyter notebook integration, e.g. https://www.jitsejan.com/using-scrapy-in-jupyter-notebook.html and https://stackoverflow.com/questions/40856730/how-to-run-scrapy-project-in-jupyter, do you have any specific questions? Also if this is a scrapy usage question, not a bug report / feature request, stackoverflow might be a better place to ask this.

Thank you very much ,i get it

> @javenleeCH `scrapy shell` can only work with actual shells designed for terminal, and it needs code to integrate with them, the existing code is in [scrapy/utils/console.py](https://github.com/scrapy/scrapy/blob/1.5.0/scrapy/utils/console.py). It doesn't seem possible to integrate this with Jupyter notebook, so you most likely need to write your own script that does the same things with spiders and responses as the [`scrapy shell` code](https://github.com/scrapy/scrapy/blob/1.5.0/scrapy/shell.py).
thank you very much

**Comment by javenleeCH** [comment]
> @javenleeCH there are plenty results on google for scrapy + jupyter notebook integration, e.g. https://www.jitsejan.com/using-scrapy-in-jupyter-notebook.html and https://stackoverflow.com/questions/40856730/how-to-run-scrapy-project-in-jupyter, do you have any specific questions? Also if this is a scrapy usage question, not a bug report / feature request, stackoverflow might be a better place to ask this.

 I appreciate your help
