### ISSUE TITLE
Add logging to HttpProxyMiddleware

### ISSUE THREAD

**Issue by Matthijsy** [scrapy/scrapy#3352]
Currently there is no logging in the HttpProxyMiddleware. It is not clear whether a spider is using a proxy or not. I think it would be great to do a info log on initialization which informs that a proxy is used and which one is used. 

I am interested if more people face this problem and what your opinion is about this.

**Comment by grammy-jiang** [comment]
Hi, @Matthijsy 

I have done the same thing in this middleware, just for debugging. Because the requests from spider will be thousands and hundreds, so many logs from this middleware is annoying if the logging level is not suitable.

My solution is:

* Set the correct logging level for this
* Put the statics information into static extension, let this extension logs every minute

**Comment by Matthijsy** [comment]
Thanks for your response! I do not mean to log it for every request but just once if you set a proxy for each request (using HttpProxyMiddleware). Just something like this in the __init__ of the middleware:

```
        for type_, proxy_tuple in self.proxies.items():
            logging.getLogger(__name__).info(f'Using {type_} proxy: {proxy_tuple[1]}')
```

**Comment by grammy-jiang** [comment]
Hi, @Matthijsy 

Yeah, I agree, and I did add this kind of logs into [my own httpproxy middleware](https://github.com/grammy-jiang/scrapy-httpproxy/).

In this middleware, a new storage interface is introduced to save and retrieve proxy from it, and currently, the log is printed by the storage class used in the middleware, like [here](https://github.com/grammy-jiang/scrapy-httpproxy/blob/54bbe481d718cd0f1fb3ef5e4edbb36b052449ba/scrapy_httpproxy/storage/environment.py#L19-L20) and [here](https://github.com/grammy-jiang/scrapy-httpproxy/blob/54bbe481d718cd0f1fb3ef5e4edbb36b052449ba/scrapy_httpproxy/storage/settings.py#L21-L22).

When my middleware is proven steady enough, I will contribute it back to Scrapy.

**Comment by Matthijsy** [comment]
There are enough alternatives that can be used for proxy usage which have this feature, and since there is not a lot of activity here I will close my issue.
