### ISSUE TITLE
spider_closed can't fire

### ISSUE THREAD

**Issue by pcwang0205** [scrapy/scrapy#3353]
when I tap ctrl + C  to stop spider，but I can't get the callback of spider_closed.
![image](https://user-images.githubusercontent.com/10112141/43238260-09983818-90c0-11e8-877e-089b13dc36d7.png)

**Comment by grammy-jiang** [comment]
Hi, @pcwang0205 

Just only from the piece of code you provide here, I think you have some misunderstanding of signals usage.

You can refer to other middlewares provided by Scrapy to learn how to connect the signals and the methods/functions, or read the document [here](https://doc.scrapy.org/en/latest/topics/api.html#module-scrapy.signalmanager).
