### ISSUE TITLE
Getting handle of original request in process_request

### ISSUE THREAD

**Issue by Karan-GM** [scrapy/scrapy#3355]
I am unable to get hold of original request URL in process_request callable of the rule in crawlspider.
Is there any way I can achieve this?

**Comment by wRAR** [comment]
According to the source that's correct, as `CrawlSpider._build_request` uses only the rule and the matched URL to make the Request. You may need to override `_requests_to_follow` and `_build_request` in a subclass or just use the generic `Spider` class. Note that the docs say

> It may not be the best suited for your particular web sites or project, but it’s generic enough for several cases, so you can start from it and override it as needed for more custom functionality, or just implement your own spider.

**Comment by Karan-GM** [comment]
Thanks, that worked. Is this not a very common scenario where one wants to know from which link the links are extracted?

**Comment by wRAR** [comment]
I think `CrawlSpider` is not used very often.

**Comment by elacuesta** [comment]
Could it be that this issue is actually about accessing the original `Response`, not `Request`, from which links are extracted? If that's the case, I believe #3682 would solve it.

**Comment by Gallaecio** [comment]
Actually, given `Response.request`, I would say #3682 solves this issue either way.
