### ISSUE TITLE
tried to install scrapy on anaconda 2 problems.

### ISSUE THREAD

**Issue by leokingai** [scrapy/scrapy#3356]
following the instruction. get 2 errors. 
1 is said pip need upgrade. 2 Microsoft Visual C++ 14.0 is required.

how to deal with them? 
![qq 20180730161629](https://user-images.githubusercontent.com/39872717/43385688-f700e0cc-9413-11e8-9ff2-ea827c4f365d.png)

**Comment by leokingai** [comment]
anyone have the experience? many thanks

**Comment by wRAR** [comment]
Hello @leokingai, I don't think this is related to Scrapy in any way?

**Comment by leokingai** [comment]
Already work out

 

发件人: Andrey Rahmatullin [mailto:notifications@github.com] 
发送时间: 2018年7月30日 21:09
收件人: scrapy/scrapy <scrapy@noreply.github.com>
抄送: leokingai <steve@leokingdeals.com>; Mention <mention@noreply.github.com>
主题: Re: [scrapy/scrapy] tried to install scrapy on anaconda 2 problems. (#3356)

 

Hello @leokingai <https://github.com/leokingai> , I don't think this is related to Scrapy in any way?
