### ISSUE TITLE
Documentation: Why suggest only Learn Python The Hard Way?

### ISSUE THREAD

**Issue by testingcan** [scrapy/scrapy#3366]
I was curious as to why the documentation explicitely suggests *Learn Python The Hard Way* in the [tutorial-section](https://doc.scrapy.org/en/latest/intro/tutorial.html), especially since it links to the Python 2 version of the book.  

I certainly don't want to discredit the book as a learning resource, but since it has received quite [some](https://www.reddit.com/r/learnprogramming/comments/7387xc/learn_python_the_hard_way_is_both_on_discouraged/) [criticism](https://news.ycombinator.com/item?id=9275357) before (and after) its Python 3 edition, I am skeptical of endorsing only this book in the tutorial. 

Without cluttering the documentation and enabling some sort paralysis by analysis I would suggest adding either or both of *Automate the Boring Stuff with Python* or *How To Think Like a Computer Scientist* from the [list of Python resources for non-programmers](https://wiki.python.org/moin/BeginnersGuide/NonProgrammers) to the documentation directly instead of only through the link to the Python resources.

**Comment by kmike** [comment]
I think that's a good idea to point users to some up-to-date and maintained list of learning resources.

**Comment by testingcan** [comment]
Great, I just added a few resources to the section. Let me know if I should include anything else.
