### ISSUE TITLE
Rewrite "Using Firefox for scraping" docs section

### ISSUE THREAD

**Issue by kmike** [scrapy/scrapy#3372]
"FF for scraping" section (https://doc.scrapy.org/en/latest/topics/firefox.html) is outdated, e.g. **none** of the suggested "Useful Firefox addons" work. Firebug is discontinued, XPath Checker is removed, all other extensions don't work with recent Firefox. 

I think it should be re-written as "Using Firefox developer tools for scraping", or just "using browser developer tools for scraping" - all browsers have developer tools these days, and these developer tools work about the same.

**Comment by testingcan** [comment]
I could try to rework the section into a more general guide on how to use developer tools over the next week. 

I'd also suggest working in how to deal with dynamic sites and requests, since in my experience this is a very frequent issue for beginners.

**Comment by kmike** [comment]
Fixed by #3400.
