### ISSUE TITLE
DepthMiddleware

### ISSUE THREAD

**Issue by zxpeter** [scrapy/scrapy#3374]
I want to modify some layer's depth in my scrapy request tree Because some requests is parallel in my program. When I'm using 
"depth = response.meta['depth'] - 1 & request.meta['depth'] = depth"
or "meta = {'depth': 1  # start from 1}"
It didn't work.
So I checked the follow link and find the meta['depth'] is not a special key.
https://doc.scrapy.org/en/latest/topics/request-response.html#request-meta-special-keys

So my question is request.meta['depth'] is set by DepthMiddleware, Can they be mess around and modified by myself ??

Thanks a lot!

**Comment by lopuhin** [comment]
@zxpeter probably you want something like this? https://github.com/TeamHG-Memex/undercrawler/blob/e5104dca5a5d9fe4b9ddd085c7b0935a712ea74d/undercrawler/spiders.py#L308-L315

**Comment by zxpeter** [comment]
@lopuhin Hi, Thanks for reply.
It seems the only different is :
Change -> depth = response.meta['depth'] -1 
To ->response.meta['depth'] =  response.meta['depth'] -1 
Is that right?

**Comment by lopuhin** [comment]
@zxpeter yes, but another important thing is to set this depth, yield a request, and then restore it, so to pull this all together, if you want to make some request with a different depth, this should work:
```
old_depth = response.meta['depth']
response.meta['depth'] = some_other_dep
yield request   # this will use some_other_dep
response.meta['depth'] = old_depth  # recover it to avoid leaking this hack
```

**Comment by zxpeter** [comment]
@lopuhin Thanks!! It works.
But I think this is a little bit weird...
Cause It should be set in the request
`depth = response.meta['depth'] + 1`
`request.meta['depth'] = depth`
Something like this: 
`meta = {
                'depth': SET_by_ourself
                }`
`request_depth = self.crawler.stats.get_stats()`
`logger.info(f'start_requests\"{request_depth}\"')`
`yield scrapy.Request(url, meta=meta, callback=self.parse)`

**Comment by lopuhin** [comment]
yeah, I agree that it's an awful hack :(
