### ISSUE TITLE
File descriptor leak in FeedExporter

### ISSUE THREAD

**Issue by dangra** [scrapy/scrapy#3391]
Test suite under windows fails to remove a file at https://github.com/scrapy/scrapy/pull/3315/files#diff-0f004a6e06393cc5e29012b83956eed2L245 because FeedExporter instances keeps an open file descriptor created for the test case.

We need to find the leak and close the file descriptor properly on close_spider signal.

**Comment by Gallaecio** [comment]
@dangra Seeing as [tests are passing on Windows](https://ci.appveyor.com/project/redapple/scrapy/history), should we close this?
