### ISSUE TITLE
dh key too small

### ISSUE THREAD

**Issue by zyx648951430** [scrapy/scrapy#3392]
url:    “https://portal.hyit.edu.cn/zfca/login”
error:  ERROR: Error downloading <GET https://portal.hyit.edu.cn/zfca/login>: [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', 'tls_process_ske_dhe', 'dh key too small')

**Comment by wRAR** [comment]
According to the [SSL Labs test](https://www.ssllabs.com/ssltest/analyze.html?d=portal.hyit.edu.cn) the website is indeed using an insecure HTTPS configuration, and OpenSSL refuses to talk to it.

I couldn't find a way to disable this particular check in OpenSSL, but disabling DH ciphers in OpenSSL helps with at least this website. To do that in Scrapy you need to subclass `scrapy.core.downloader.contextfactory.ScrapyClientContextFactory`, replacing `DEFAULT_CIPHERS` with `AcceptableCiphers.fromOpenSSLCipherString('DEFAULT:!DH')` and then set the [`DOWNLOADER_CLIENTCONTEXTFACTORY`](https://doc.scrapy.org/en/latest/topics/settings.html#downloader-clientcontextfactory) setting to this new class. It's probably worth making the cipher string a Scrapy setting if that works, but for now you'll need to do this.

**Comment by zyx648951430** [comment]
Thank you very much !!!  According to your suggestion, I already have the solution.

**Comment by Gallaecio** [comment]
This is now configurable through a setting thanks to @wRAR’s #3442.
