### ISSUE TITLE
Set DNS Servers to use

### ISSUE THREAD

**Issue by mohmad-null** [scrapy/scrapy#3396]
I'm not sure if this is a docs issue (as in, the setting exists but doesn't seem to be documented) or a request for a new setting.

Basically - I'd like to be able to set what DNS Servers Scrapy should use. It currently uses the system servers, but I'd like it to use a different set and not have to change my system DNS whenever I do a scrape.

There is a section of the docs which implies it's possible to set the DNS server to use, but it doesn't say how - https://doc.scrapy.org/en/latest/topics/broad-crawls.html#setup-your-own-dns (I have no particular interest in setting up my own DNS. 8.8.8.8 or its ilk will be sufficient for a scrape).

**Comment by elacuesta** [comment]
`DNS_RESOLVER` setting introduced in #4227
