### ISSUE TITLE
Can't get partial response body after timeout

### ISSUE THREAD

**Issue by c3pmark** [scrapy/scrapy#3407]
I'm working on scraping some pages that hold the HTTP connection open indefinitely, trickling data to the client little by little.  I had hoped to use a short timeout to grab the page up to a certain point, but after the timeout is triggered, I can't get at the data that was received.  I thought that setting DOWNLOAD_FAIL_ON_DATALOSS=False would allow partial responses to be processed, but I still get `twisted.internet.error.TimeoutError: User timeout caused connection failure`.  If I use `errback=` on the request, the errback just gets the TimeoutError object and not the response.

Should setting DOWNLOAD_FAIL_ON_DATALOSS=True allow timed out responses to be processed?  Or is there another way to deal with partial responses after a timeout?

**Comment by HassanQamar07** [comment]
A "user timeout" error occurs when the remote server does not respond in the given time (web server down, etc.). This means there is no response from the server. There might be some antibot measures implemented at the source site which is blocking the request. You can try different headers(user-agent) in scrapy requests.

**Comment by c3pmark** [comment]
In this case, the remote server responds and returns data, but never closes the connection (because it's intended to be a long-lived connection).  I do want the timeout to happen because otherwise the crawl would never finish, but I still want to process the (partial) data that was received, like you typically can with DOWNLOAD_FAIL_ON_DATALOSS.  I added some debug prints in downloader/handlers/http11.py and the data is being received and processed, but there's no way to get at it once the timeout has happened.

**Comment by kmike** [comment]
I think that'd be a great feature to allow reading partial responses.

**Comment by wRAR** [comment]
I've investigated this a bit, it seems the Deferred returned by [`ScrapyAgent.download_request`](https://github.com/scrapy/scrapy/blob/1.5.0/scrapy/core/downloader/handlers/http11.py#L301) is [cancelled when the timeout occurs](https://github.com/scrapy/scrapy/blob/1.5.0/scrapy/core/downloader/handlers/http11.py#L338). Therefore when [`_ResponseReader.connectionLost`](https://github.com/scrapy/scrapy/blob/1.5.0/scrapy/core/downloader/handlers/http11.py#L462) is called, `self._finished` is already cancelled and can't be used to pass the partial data via a callback/errback.

Unfortunately I don't know how can this be improved. Also, my understanding may be incomplete or incorrect.

**Comment by c3pmark** [comment]
I ended up working around this by creating a [subclass of ScrapyAgent](https://gist.github.com/c3pmark/30bab04dd2eb07167a0392aab7747c06) that just calls transport.stopProducing() and transport.producer.loseConnection() when the timeout expires, which triggers the "lost connection" code path instead of the "timed out" one.  It's not a complete fix since it throws exceptions on a connect timeout, though.

**Comment by nasirhjafri** [comment]
@kmike I've made a PR. Could you please review it?
@c3pmark This fix should work without raising a TimeoutError
