### ISSUE TITLE
user-agent middleware does not actually change request user agent

### ISSUE THREAD

**Issue by KaLZeK** [scrapy/scrapy#3408]
In user-agent middleware, the process request method does not actually change the user agent

**Comment by KaLZeK** [comment]
I made a project myself and my middleware is like below(I need my project to switch user agent from time to time) :

class RandomUserAgentMiddleware(object):
    def __init__(self):
        from project.conf.user_agent import USER_AGENT_LIST
        self.user_agent_list = USER_AGENT_LIST 
        self.customized_user_agent = None

    @classmethod
    def from_crawler(cls, crawler):
        obj = cls()   
        crawler.signals.connect(obj.spider_opened, signal=signals.spider_opened)
        return obj

    def spider_opened(self, spider):
        # this is user customized user_agent, assign it in Spider.__init__
        self.customized_user_agent = getattr(spider, 'user_agent', self.customized_user_agent)

    def process_request(self, request, spider):
        if self.customized_user_agent:
            request.headers[b'User-Agent'] = self.customized_user_agent
        else: 
            request.headers[b'User-Agent'] = random.choice(self.user_agent_list)
        print("request.headers:", request.headers)

And this works perfectly fine. But when I rewrite
request.headers[b'User-Agent'] = random.choice(self.user_agent_list)
to
request.headers.setdefault([b'User-Agent'], random.choice(self.user_agent_list))

It simply won't work.

**Comment by wRAR** [comment]
I assumed you were talking about the Scrapy one. Please note that Github issues is a place to report bugs in Scrapy, you should use other place, like StackOverflow, to ask about problems with your code.

> request.headers.setdefault([b'User-Agent'], random.choice(self.user_agent_list))

So the User-Agent header is already set at this point. Have you disabled the `scrapy.downloadermiddlewares.useragent.UserAgentMiddleware` which is enabled by default?

**Comment by kmike** [comment]
I agree with @wRAR's analysis. Related: https://github.com/scrapy/scrapy/pull/3409.

**Comment by KaLZeK** [comment]
I am sorry but I am not here to ask problems with my code. It is just when I use setdefault() method in the user agent, it won't actually change the user-agent when I run the project. And when I change setdefault(), it works. I assumed this is a bug of Scrapy so I posted it here.

**Comment by KaLZeK** [comment]
No I haven't used two middlewares, I turned others off except one. But the setdefault() doesn't work unless I change setdefalut() to 
`request.headers['User-Agent'] = self.user_agent`
 I don't think it is a problem of my code.

**Comment by wRAR** [comment]
If setdefalut doesn't work them something have already set the header.
