### ISSUE TITLE
SSL Handshake Failure

### ISSUE THREAD

**Issue by Mattnmoore** [scrapy/scrapy#3410]
I'm getting the following error when I try to crawl a website that has an issue with their SSL cert. 

```
 ERROR: Error downloading <GET (removed): [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', 'ssl23_read', 'ssl handshake failure')]>]
```

Here are my versions:
```
Scrapy    : 1.3.3
lxml      : 3.7.3.0
libxml2   : 2.9.3
cssselect : 1.0.1
parsel    : 1.1.0
w3lib     : 1.17.0
Twisted   : 17.1.0
Python    : 2.7.12 (default, Dec  4 2017, 14:50:18) - [GCC 5.4.0 20160609]
pyOpenSSL : 16.2.0 (OpenSSL 1.0.2g  1 Mar 2016)
Platform  : Linux-4.4.0-51-generic-x86_64-with-Ubuntu-16.04-xenia
```

I've noticed several other related issues, but none of the fixes in them have resolved the issue for me, any help would be greatly appreciated.

**Comment by HassanQamar07** [comment]
@Mattnmoore Which site you're trying to crawl? It is impossible to check the issue without getting to know the site.
