### ISSUE TITLE
Outdated tutorial pages

### ISSUE THREAD

**Issue by ElToro1966** [scrapy/scrapy#3417]
The [Scrapy Tutorial](https://doc.scrapy.org/en/latest/intro/tutorial.html) contain links to two pages, 
[Using Firebug for scraping](https://doc.scrapy.org/en/latest/topics/firebug.html#topics-firebug) and [Using Firefox for scraping](https://doc.scrapy.org/en/latest/topics/firefox.html#topics-firefox), that are outdated. Firebug isn't around any more, and the Firefox-page is full of references to outdated plugins. As the tutorial page is a starting point for Scrapy-beginners, an update is fairly important.

**Comment by wRAR** [comment]
Related: #3373 #3372
Fixed in #3400 I think?

**Comment by ElToro1966** [comment]
#3400 looks like a fix, yes. But the old pages above are still referenced in the [Scrapy Tutorial](https://doc.scrapy.org/en/latest/intro/tutorial.html), so I guess it is just a question of fixing those links(?)

**Comment by ElToro1966** [comment]
Ok, will do. Closing this.
