### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by techaks** [scrapy/scrapy#3423]
![screenshot 114](https://user-images.githubusercontent.com/11151000/45806794-84272480-bcf4-11e8-872c-7828c49657b9.png)
![screenshot 115](https://user-images.githubusercontent.com/11151000/45806796-84272480-bcf4-11e8-90c8-0fa7a7c98bee.png)
![screenshot 116](https://user-images.githubusercontent.com/11151000/45806798-84bfbb00-bcf4-11e8-9199-8f86e6e364ab.png)

**Comment by wRAR** [comment]
Hello @techaks, this looks like a problem with your code while this is the issue tracker for Scrapy itself. Please ask your questions on StackOverflow or other suitable places, e.g. ones mentioned on https://scrapy.org/community/

Please also note that ideally such questions should include text of code and errors, not screenshots. You should also provide the code of the pipeline where the exception happens.

**Comment by techaks** [comment]
```
# -*- coding: utf-8 -*-

import scrapy
from scrapy.selector import Selector
from urllib.parse import urlparse
from crawling_spider.items import CrawlingSpiderItem
from scrapy_splash import SplashRequest

class JagranSpider(scrapy.Spider):
    name = 'jagran'
    allowed_domains = ['jagran.com']
    urls = ['https://www.jagran.com/search/city_name']
   
    languageName='hindi'
    cityName=''

    cities=['kanpur','noida','gorakhpur'] 
    article_category_xpaths=['//div[@class="protxt fr"]/h3/a/@href']
    article_published_summary_xpaths = ['//div[@class="articleBody"]/p/text()']
    article_published_date_xpath='//meta[@property="article:published_date"]/@content'
    article_url_xpath='//meta[@property="og:url"]/@content'
    article_title_xpath='//meta[@property="og:title"]/@content'
    article_images_xpath='//meta[@property="og:image"]/@content'
    article_keywords_xpath='//meta[@name="news_keywords"]/@content'
    article_videos_xpath='(//div[@class="image lazyLoadlist auw_inline_video_player"])/@data-video-id'
    article_images_height_xpath='//meta[@property="og:image:height"]/@content'
    article_images_width_xpath='//meta[@property="og:image:width"]/@content'

    def start_requests(self):
        
        for url in self.urls:
            for city in self.cities:  
                city_url = url.replace('city_name',city)
                yield scrapy.Request(url=city_url+'?city_name='+city, callback=self.parse)

    def parse(self, response):
        self.cityName=self.getCityName(response)
        lists = self.parse_category(response)
        for item in lists:
            if response.url not in item:
                o = urlparse(response.url)
                article_url = o.scheme + '://' + o.hostname + item
            else:
                article_url=item
            yield scrapy.Request(url=article_url+'?city_name='+self.cityName, callback=self.parse_item) 
           

    def getCityName(self,response):
        from furl import furl
        f = furl(response.url) 
        return str(f.args['city_name']).title()

    def parse_category(self,response):
     
        try:
            for xpath_item in self.article_category_xpaths:
                lists = list(Selector(response).xpath(xpath_item).extract())
            
                try:
                    if lists.__len__() > 0:
                        return lists
                except:
                    print('NO DATE PARSE')
        except:
            print("This is an error message!")


    def parse_item(self, response):
        try:
            item = CrawlingSpiderItem()
            item['url'] = Selector(response).xpath(self.article_url_xpath).extract_first()
            item['title'] = Selector(response).xpath(self.article_title_xpath).extract_first()
            item['description'] =self.parse_description(response)
            item['keywords'] = Selector(response).xpath(self.article_keywords_xpath).extract()
            item['imageUrl'] = Selector(response).xpath(self.article_images_xpath).extract_first()
            item['publisheddate']=  ''.join(Selector(response).xpath(self.article_published_date_xpath).extract())
            item['videoUrl']=""
            item['languageName']=self.languageName
            item['cityName']=self.getCityName(response)
            item['imageHeight']=''.join(Selector(response).xpath(self.article_images_height_xpath).extract())
            item['imageWidth']=''.join(Selector(response).xpath(self.article_images_width_xpath).extract())
            item['postType']= 'Video' if item['videoUrl'] else 'Image' if item['imageUrl'] else 'Text'
           
            yield item
        except Exception as exc:
            print(exc)  
       
       
    def parse_description(self, response):
        try:
            for new_xapth in self.article_published_summary_xpaths:
                
                lists = (Selector(response).xpath(new_xapth).extract())
                print()
                try:
                    if lists.__len__() > 0:
                        return ''.join(lists)
                except:
                    print('NO DATE PARSE')
                    return 'None'

        except :
            print("This is an error message!")


```

class DuplicatesPipeline(object):

    def __init__(self):
        self.urls_seen = set()
        self.last_run_time = ''
        self.data = []  # to take all the value from db and push into data to check duplicacy
        self.count = 0
        select_st = select([table])
        result = conn.execute(select_st)
        for row in result:
            self.data.append({'post_imageurl': row['post_imageurl'], 'post_videourl': row['post_videourl'], 'post_keywords': row['post_keywords'], 'post_summary': row['post_summary'], 'post_id':row['post_id'], 'post_url': row['post_url'], 'post_title': row['post_title'], 'post_publisheddate': row['post_publisheddate']})  
       
    def process_item(self, item, spider):
            print('*********',item.url)
            if(item['url']):
                self.count = self.count + 1
                # reason of 1 is - becuase newest item will be always 1st so latest date will be 1st
                # we are letting items of lesser date than last_run_date are already existed in db
                if(self.count == 1):
                    select_st = select([spiders]).where(spiders.c.spider_name == spider.name)
                    result = conn.execute(select_st)
                    print('results',spiders.c.spider_name,spider.name)
                    
                    for row in result:
                            print("username:", row['spider_last_run_time'])
                            if row['spider_last_run_time']:
                                self.last_run_time = row['spider_last_run_time']
                                # compare last run with current item publish date
                                if(self.last_run_time == item['publisheddate']):
                                    raise CloseSpider('bandwidth_exceeded')
                                    # raise DropItem("old item found: %s" % item)
                                if(self.last_run_time > item['publisheddate']):
                                    raise CloseSpider('bandwidth_exceeded')
                                    # raise DropItem("old item found: %s" % item)
                                if(self.last_run_time < item['publisheddate']):
                                    update_st = spiders.update().where(spiders.c.spider_name == spider.name).\
                                    values(spider_last_run_time=item['publisheddate'])
                                    conn.execute(update_st)  # updation of last runtime  
                            else:
                                    update_st = spiders.update().where(spiders.c.spider_name == spider.name).\
                                    values(spider_last_run_time=item['publisheddate'])
                                    conn.execute(update_st)  # updation of last runtime  
                
                # check duplicacy of item
                duplicate_posts = _.where (self.data, {'post_url': item['url'], 'post_title': item['title'], 'post_publisheddate': item['publisheddate']})
                if len(duplicate_posts) > 0:
                    raise DropItem("Duplicate item found: %s" % item)
                else:     
                    return item
        
                
                    # update_st= spiders.update().where(spiders.c.spider_name==spider.name).\
                    # values(spider_last_run_time=item['publisheddate'])
                    # result = conn.execute(update_st)
                    # print(result)
                    # print(update_st)
                    # select_st = select([spiders])
                    # result = conn.execute(select_st)
                    # for row in result:
                    #   print(row["spider_id"])
                    #   print(row["spider_last_run_time"])
                    # print(spider.name) 
            else:
                raise DropItem("Duplicate item found: %s" % item)

**Comment by xiantang** [comment]
i think your error is in there 

```python
def parse_item(self, response):
        try:
            item = CrawlingSpiderItem()
            
        except Exception as exc:
            print(exc)
```
