### ISSUE TITLE
Twisted failure while running scrapy shell

### ISSUE THREAD

**Issue by Chelsea31** [scrapy/scrapy#3432]
`
[<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion: Connection lost.>]
`

I am experiencing this error occasionally while running the scraper.
Does this problem has a permanent resolution?

**Comment by wRAR** [comment]
This is not a problem by itself, you need to provide more info. Also, this is the Scrapy issue tracker so only problems in Scrapy itself should be discussed here, please use StackOverflow or other similar channels to ask about your code.

**Comment by Chelsea31** [comment]
Scrapy : 1.5.1
os: Ubuntu 5.4.0-6ubuntu1~16.04.9

This is a scrapy issue which I faced when running a spider. Occasionally a spider would fail leaving just this log.
I am not sure what other information would be helpful in debugging it, but if you let me know, I would glad to provide it.

**Comment by wRAR** [comment]
Are you sure it's not a problem with the website you are crawling?

**Comment by Chelsea31** [comment]
Yes, because if it was a site issue parallel crawls to the same website would also fail. But that't not the case.
If you have the expertise, I would like to know your advise on how I can debug this issue, and read more about the intricacies of scrapy

**Comment by Gallaecio** [comment]
Please, use [StackOverflow](https://stackoverflow.com/tags/scrapy) to ask this type of questions. See [Getting Help](https://docs.scrapy.org/en/latest/#getting-help).
