### ISSUE TITLE
why not tie spider to request or response

### ISSUE THREAD

**Issue by baby5** [scrapy/scrapy#3434]
i saw this [line](https://github.com/scrapy/scrapy/blob/bafd174a9f174e31bd76493761264f4c81649e4a/scrapy/core/engine.py#L236) in engine.py
i have a question is why not do this for spider?

**Comment by asadurski** [comment]
Can you describe a use case?
I also thought about it at some point, but usually you can refer to spider in relatively simple way from within crawl methods (`self`, `crawler.spider`, etc.).

**Comment by Gallaecio** [comment]
I think the current approach is more flexible. Requests can be built from outside a spider.
