### ISSUE TITLE
TLS handshake failure

### ISSUE THREAD

**Issue by mikesxf** [scrapy/scrapy#3437]
Hi
I'm getting a handshake failure when running:
`scrapy shell https://androidappsapk.co`

and the results:
Traceback (most recent call last):
  File "/usr/local/bin/scrapy", line 11, in <module>
    sys.exit(execute())

  File "/usr/local/lib/python2.7/dist-packages/scrapy/cmdline.py", line 149, in execute
    _run_print_help(parser, _run_command, cmd, args, opts)

  File "/usr/local/lib/python2.7/dist-packages/scrapy/cmdline.py", line 89, in _run_print_help
    func(*a, **kw)

  File "/usr/local/lib/python2.7/dist-packages/scrapy/cmdline.py", line 156, in _run_command
    cmd.run(args, opts)

  File "/usr/local/lib/python2.7/dist-packages/scrapy/commands/shell.py", line 73, in run
    shell.start(url=url, redirect=not opts.no_redirect)

  File "/usr/local/lib/python2.7/dist-packages/scrapy/shell.py", line 48, in start
    self.fetch(url, spider, redirect=redirect)

  File "/usr/local/lib/python2.7/dist-packages/scrapy/shell.py", line 115, in fetch
    reactor, self._schedule, request, spider)

  File "/usr/lib/python2.7/dist-packages/twisted/internet/threads.py", line 122, in blockingCallFromThread
    result.raiseException()

  File "string", line 2, in raiseException
twisted.web._newclient.ResponseNeverReceived: [<twisted.python.failure.Failure <class 'OpenSSL.SSL.Error'>>]

I have read many issues about this problem, but I am sorry that I can't get the point on how to solve it. And I wonder whether it can be solved by updating `scrapy` or `openssl` as I am using old version of `scrapy` and `openssl`. My environment:
Scrapy    : 1.4.0
lxml      : 3.3.3.0
libxml2   : 2.9.1
cssselect : 1.0.1
parsel    : 1.2.0
w3lib     : 1.17.0
Twisted   : 13.2.0
Python    : 2.7.6 (default, Oct 26 2016, 20:30:19) - [GCC 4.8.4]
pyOpenSSL : 0.13 (OpenSSL 1.0.1f 6 Jan 2014)
Platform  : Linux-3.13.0-144-generic-x86_64-with-Ubuntu-14.04-trusty

When I use wireshark to capture the traffic, it shows that after `client hello`, server return
`TLSv1 Record Layer: Alert (Level: Fatal, Description: Handshake Failure)`

**Comment by mikesxf** [comment]
I wonder why it shows in one line?

**Comment by wRAR** [comment]
I suspect your OpenSSL supports none of the ciphers the server supports (`ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA384`).

**Comment by mikesxf** [comment]
Thanks. So updating OpenSSL maybe work?

**Comment by wRAR** [comment]
@mikesxf I cannot be sure, unfortunately.

**Comment by wRAR** [comment]
@mikesxf your OpenSSL probably doesn't support ECDHE ciphers or at least doesn't use them by default (doubtful though). You can see offered ciphers this in the client hello packet in wireshark. Looks like 1.0.1 should support them but maybe they are not enabled at the compilation time or something else happened. You can also try `openssl s_client -connect androidappsapk.co:443`.

**Comment by mikesxf** [comment]
@wRAR Thanks for your advice. I have made a mistake that I didn't save the .pcap file in wireshark and since I am upgrading OpenSSL(while meeting other problems), I may not try `openssl s_client -connect androidappsapk.co:443` right now. I will check it after upgrading. Thanks again.

**Comment by mikesxf** [comment]
I checked the ciphers offered in the client hello packet in wireshark, it seems that OpenSSL supports enough chipers. But still handshake failure.
![screenshot from 2018-10-09](https://user-images.githubusercontent.com/20496884/46643587-558fc180-cbaf-11e8-959e-240444e29cad.png)
and I try `openssl s_client -connect androidappsapk.co:443`, server still returns handshake failure

**Comment by wRAR** [comment]
This is strange indeed.

**Comment by mikesxf** [comment]
Well, I try it on win10 using python3.6 recently and it seems to work well. Although I don't know why, I think using another python version or system version maybe a good attempt.
Thanks for help!
