### ISSUE TITLE
Regarding GSoc 2019

### ISSUE THREAD

**Issue by maramsumanth** [scrapy/scrapy#3443]
Is it officially confirmed that scrapinghub will be a sub-organisation under PSF in upcoming GSoc 2019?
@cathalgarvey , I am much interested to contribute to scrapy.

**Comment by cathalgarvey** [comment]
Hi @maramsumanth - Sorry, I just replied to your email and then saw this. :)

There is no official confirmation, but we will probably apply again next year. But, if you're interested in contributing to Scrapy, you don't need to wait for GSoC to do it. We're always happy to have people join the Scrapy development community! :)

**Comment by maramsumanth** [comment]
Thanks @cathalgarvey :)

**Comment by arvand** [comment]
Hi, I really love this project. I have worked with Selenium for multiple projects and have some ideas for improvement. Where should I start to get familiarized with the project? Is there any issue/documentation I can start working on?
