### ISSUE TITLE
Cryptography - ImportError: DLL load failed: The operating system cannot run %1

### ISSUE THREAD

**Issue by Anthon02** [scrapy/scrapy#3447]
<p>I am trying to create a scrapy project with a version of scrapy installed with 

> conda install -c conda-forge scrapy

I am getting the following error during install.

> from cryptography.hazmat.bindings._openssl import ffi,lib
> ImportError: DLL load failed: The operating system cannot run %1.

Any help would be appreciated. 

Thanks</p>
<br>
Environment (<code>conda list</code>):
<details>
<pre><code>
# packages in environment at C:\Users\Office\Miniconda3:
#
# Name                    Version                   Build  Channel
anaconda-client           1.7.1                      py_0    conda-forge
anaconda-navigator        1.9.2                    py36_0
appdirs                   1.4.3                      py_1    conda-forge
asn1crypto                0.24.0                   py36_0    conda-forge
attrs                     18.2.0                     py_0    conda-forge
automat                   0.7.0                      py_1    conda-forge
ca-certificates           2018.4.16                     0    conda-forge
certifi                   2018.4.16                py36_0    conda-forge
cffi                      1.11.5                   py36_0    conda-forge
chardet                   3.0.4                    py36_2    conda-forge
clyent                    1.2.2                      py_1    conda-forge
colorama                  0.3.9                      py_1    conda-forge
conda                     4.5.11                   py36_0
conda-env                 2.6.0                         1
console_shortcut          0.1.1                         3
constantly                15.1.0                     py_0    conda-forge
cryptography              2.2.1                    py36_0    conda-forge
cssselect                 1.0.3                      py_0    conda-forge
decorator                 4.3.0                      py_0    conda-forge
freetype                  2.8.1                    vc14_0  [vc14]  conda-forge
hyperlink                 17.3.1                     py_0    conda-forge
icu                       58.2                     vc14_0  [vc14]  conda-forge
idna                      2.6                      py36_1    conda-forge
incremental               17.5.0                     py_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jpeg                      9b                       vc14_2  [vc14]  conda-forge
jsonschema                2.6.0                    py36_1    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
libiconv                  1.14                     vc14_4  [vc14]  conda-forge
libpng                    1.6.34                   vc14_0  [vc14]  conda-forge
libtiff                   4.0.9                    vc14_0  [vc14]  conda-forge
libxml2                   2.9.5                    vc14_1  [vc14]  conda-forge
libxslt                   1.1.32                   vc14_0  [vc14]  conda-forge
lxml                      4.2.1                    py36_0    conda-forge
menuinst                  1.4.11                   py36_0    conda-forge
more-itertools            4.2.0                      py_0    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
olefile                   0.46                       py_0    conda-forge
openssl                   1.0.2o                   vc14_0  [vc14]  conda-forge
parsel                    1.5.0                    py36_0
pillow                    5.1.0                    py36_0    conda-forge
pip                       10.0.1                   py36_0    conda-forge
pluggy                    0.6.0                      py_0    conda-forge
psutil                    5.4.5                    py36_0    conda-forge
py                        1.6.0                      py_0    conda-forge
pyasn1                    0.4.4                      py_0    conda-forge
pyasn1-modules            0.2.1                      py_0    conda-forge
pycosat                   0.6.3                    py36_0    conda-forge
pycparser                 2.19                       py_0    conda-forge
pydispatcher              2.0.5                      py_1    conda-forge
pyopenssl                 17.5.0                   py36_1    conda-forge
pyqt                      5.6.0                    py36_5    conda-forge
pysocks                   1.6.8                    py36_1    conda-forge
pytest                    3.5.0                    py36_0    conda-forge
pytest-runner             4.2                        py_1    conda-forge
python                    3.6.5                         1    conda-forge
python-dateutil           2.7.3                      py_0    conda-forge
pytz                      2018.5                     py_0    conda-forge
pywin32                   221                      py36_0    conda-forge
pyyaml                    3.12                     py36_1    conda-forge
qt                        5.6.2                    vc14_1  [vc14]  conda-forge
qtpy                      1.5.1              pyh8a2030e_0    conda-forge
queuelib                  1.5.0                    py36_0
requests                  2.18.4                   py36_1    conda-forge
ruamel_yaml               0.15.35                  py36_0    conda-forge
scrapy                    1.5.0                    py36_0    conda-forge
service_identity          17.0.0                     py_0    conda-forge
setuptools                39.0.1                   py36_0    conda-forge
sip                       4.18                     py36_1    conda-forge
six                       1.11.0                   py36_1    conda-forge
tk                        8.6.8                    vc14_0  [vc14]  conda-forge
traitlets                 4.3.2                    py36_0    conda-forge
twisted                   18.7.0           py36hfa6e2cd_1
urllib3                   1.22                     py36_0    conda-forge
vc                        14                   h0510ff6_3
vs2015_runtime            14.0.25123                    3
w3lib                     1.19.0                   py36_0
wheel                     0.31.0                   py36_0    conda-forge
win_inet_pton             1.0.1                    py36_1    conda-forge
wincertstore              0.2                      py36_0    conda-forge
yaml                      0.1.7                    vc14_0  [vc14]  conda-forge
zlib                      1.2.11                   vc14_0  [vc14]  conda-forge
zope                      1.0                      py36_1
zope.interface            4.5.0            py36hfa6e2cd_0

</code></pre>
</details>
<br>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>
<pre><code>   
active environment : base
   active env location : C:\Users\Office\Miniconda3
           shell level : 1
      user config file : C:\Users\Office\.condarc
populated config files : C:\Users\Office\.condarc
         conda version : 4.5.11
   conda-build version : not installed
        python version : 3.6.5.final.0
      base environment : C:\Users\Office\Miniconda3  (writable)
          channel URLs : https://conda.anaconda.org/conda-forge/win-32
                         https://conda.anaconda.org/conda-forge/noarch
                         https://repo.anaconda.com/pkgs/main/win-32
                         https://repo.anaconda.com/pkgs/main/noarch
                         https://repo.anaconda.com/pkgs/free/win-32
                         https://repo.anaconda.com/pkgs/free/noarch
                         https://repo.anaconda.com/pkgs/r/win-32
                         https://repo.anaconda.com/pkgs/r/noarch
                         https://repo.anaconda.com/pkgs/pro/win-32
                         https://repo.anaconda.com/pkgs/pro/noarch
                         https://repo.anaconda.com/pkgs/msys2/win-32
                         https://repo.anaconda.com/pkgs/msys2/noarch
         package cache : C:\Users\Office\Miniconda3\pkgs
                         C:\Users\Office\AppData\Local\conda\conda\pkgs
      envs directories : C:\Users\Office\Miniconda3\envs
                         C:\Users\Office\AppData\Local\conda\conda\envs
                         C:\Users\Office\.conda\envs
              platform : win-32
            user-agent : conda/4.5.11 requests/2.18.4 CPython/3.6.5 Windows/7 W
ndows/6.1.7601
         administrator : False
            netrc file : None
          offline mode : False

</code></pre>
</details>

**Comment by pel-h** [comment]
Hi @Anthon02 
Not really a scrapy issue, more one for conda.  Make sure it is up to date, e.g.  run: `conda update -n base conda`

You may find the following useful.
https://github.com/pytorch/pytorch/issues/7579
