### ISSUE TITLE
No attention to pull requests

### ISSUE THREAD

**Issue by thernstig** [scrapy/scrapy#3460]
I am reporting this issue to give attention to that there are 214 pull requests, many valid, which no maintainer is looking at. Is there a reason for this?

**Comment by aufziehvogel** [comment]
Just checked a random PR, which says "kmike reviewed" with a tag of "added to the v1.6 milestone".

https://github.com/scrapy/scrapy/pull/3394

Also the other ones I opened had activity mostly from kmike.

So he is definitely looking at them. Integrating them on the other hand is probably a task that needs more time/review. The maintainer always needs to consider all advantages/disadvantages of the implementation and if it's a bigger change all the impacts on the future of the project.

**Comment by Gallaecio** [comment]
Closing since lately we’ve been quite active in reviewing recently-updated pull requests, as well as going over old pull requests to try to revive them, close them if they are irrelevant, or highjack them.

**Comment by thernstig** [comment]
@Gallaecio Sounds good this is being done, any chance you could check out #3164 ?
