### ISSUE TITLE
Scrapy can not work with py_translator or googletrans

### ISSUE THREAD

**Issue by RobotSe7en** [scrapy/scrapy#3461]
In scrapy project,
when I
import py_translator 
or googletrans, 
the scrapy 
raise KeyError("Spider not found: {}".format(spider_name))
KeyError: 'Spider not found: miui'
when I comment
# import py_translator 
the scrapy works.
why?

**Comment by xiantang** [comment]
Can you show me all complete traceback?

**Comment by RobotSe7en** [comment]
> Can you show me all complete traceback?

It can work again. I do nothing.
