### ISSUE TITLE
Spider can't GET response after being redirected

### ISSUE THREAD

**Issue by antigame** [scrapy/scrapy#3472]
Hi, 
My spider can't crawl the url after being redirected to but if I scrape the url directly, it works normally. For example, when I scrape url 'https://www.novelupdates.com/extnu/1965286/' :
```
def start_requests(self):
            yield scrapy.Request('https://www.novelupdates.com/extnu/1965286/', self.parse)
```

the response is:

> [scrapy.downloadermiddlewares.redirect] DEBUG: Redirecting (302) to <GET http://translatinotaku.net/2018/10/10/r-p-chapter-2-hunter/> from <GET https://www.novelupdates.com/extnu/1965286/>
> [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
> [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET http://translatinotaku.net/2018/10/10/r-p-chapter-2-hunter/> (failed 1 times): [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', 'ssl3_get_record', 'wrong version number')]>]
> [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
> [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET http://translatinotaku.net/2018/10/10/r-p-chapter-2-hunter/> (failed 2 times): [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', 'ssl3_get_record', 'wrong version number')]>]
> [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
> [scrapy.downloadermiddlewares.retry] DEBUG: Gave up retrying <GET http://translatinotaku.net/2018/10/10/r-p-chapter-2-hunter/> (failed 3 times): [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', 'ssl3_get_record', 'wrong version number')]>]
> [scrapy.core.scraper] ERROR: Error downloading <GET http://translatinotaku.net/2018/10/10/r-p-chapter-2-hunter/>
> Traceback (most recent call last):
>   File "e:\projects\virutalenv\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
>     defer.returnValue((yield download_func(request=request,spider=spider)))
> ResponseNeverReceived: [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', 'ssl3_get_record', 'wrong version number')]>]
> [scrapy.core.engine] INFO: Closing spider (finished)

But if i scrape the redirected url 'http://translatinotaku.net/2018/10/10/r-p-chapter-2-hunter/' directly it works ok.
My scrapy version: 

> Scrapy       : 1.5.1
> lxml         : 4.2.5.0
> libxml2      : 2.9.5
> cssselect    : 1.0.3
> parsel       : 1.5.0
> w3lib        : 1.19.0
> Twisted      : 18.7.0
> Python       : 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]
> pyOpenSSL    : 18.0.0 (OpenSSL 1.1.0i  14 Aug 2018)
> cryptography : 2.3.1
> Platform     : Windows-10-10.0.17134

**Comment by guillaume-humbert** [comment]
Can you try to run this in a clean environment?

```python
from scrapy.spiders import Spider

class MySpider(Spider):

    name = "novelupdates.com"

    start_urls = ["https://www.novelupdates.com/extnu/1965286/"]

    def parse(self, response):
        pass
        
```

I get a correct redirect output:

```
2018-11-17 19:40:44 [scrapy.downloadermiddlewares.redirect] DEBUG: Redirecting (302) to <GET http://translatinotaku.net/2018/10/10/r-p-chapter-2-hunter/> from <GET https://www.novelupdates.com/extnu/1965286/>
2018-11-17 19:40:47 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://translatinotaku.net/2018/10/10/r-p-chapter-2-hunter/> (referer: None)
2018-11-17 19:40:47 [scrapy.core.engine] INFO: Closing spider (finished)
```

(I'm using scrapy 1.5.0 on Linux)
