### ISSUE TITLE
Scrapy Log None

### ISSUE THREAD

**Issue by Flyraty** [scrapy/scrapy#3473]
why  scrapy logging  print many  None.
scrapy 日志打印出来的None 是什么意思呢

**Comment by xiantang** [comment]
Cloud you show your code and complete traceback ? 麻烦把代码和log写出来

**Comment by Flyraty** [comment]
问题已经解决了，看了下scrapy的log.py。scrapyd 函数处理了这个东西

> Could you show your code and complete traceback ? 麻烦把代码和log写出来
已经搞明白了，阅读了一下scrapy的log.py。 在日志级别为debug 的情况下，scrapd 函数会打印item 日志。这里为None 的原因一是pipeline 没有return item。二是有专门的pipeline 去除了打印item的操作，
