### ISSUE TITLE
scrapy shell disfunction and require for any solution

### ISSUE THREAD

**Issue by hanahanamarket** [scrapy/scrapy#3479]
Hello. I'm beginner of scrapy package.
Thank you for developing useful scrapy package.  I am exciting in using it!!

**[About my environment]**
I have a trouble in use of scrapy shell from Jupyter Notebook and for each tools I updated to latest version(October, 30, 2018). I operate scrapy shell from Windows10. When I installed scrapy package, I used conda install command from Anaconda prompt.

**[What I had tried to use scrapy shell]**
①While reffering to official document of scrapy shell,  I wrote command like **[!scrapy shell "URL" ]** on JupyterNotebook cell, but I can't get any response. The cell is running continuously with showing mark of **[*]** , until I interrupt JupyterNotebook Kernel.
③I had tried same code written in avobe on IPython kernel which I open with magic command "%qtconsole", but running cell respond nothing as well as former one.
③In part of arbitrary URL after scrapy shell command, I tried to change some URLs from lots of sites. But nothing is changed in returning.
④As an additional trial,  I tried to use scrapy shell as root authority.  As soon as Ithe shell window opened, it goes down and close. 

**[purpose of this question]**
Would you mind if I ask you any solution in  this problem?  I can't specify causes .
What action should I take?

Thank you for your kind!!

**Comment by pel-h** [comment]
Hi @hanahanamarket,

Doesn't seem to be an issue or change request for scrapy, but rather it looks like you don't have your environment set-up correctly.  See https://doc.scrapy.org/en/1.5/intro/install.html

Did `conda install -c conda-forge scrapy` run correctly?

Are you able to run scrapy shell from the anaconda prompt?

Attached is an example, that runs fine for me on jupyter notebook.

Please post on Stackoverflow if you need more support on this.
[3475.zip](https://github.com/scrapy/scrapy/files/2589491/3475.zip)
