### ISSUE TITLE
How to use Request parameter : body?

### ISSUE THREAD

**Issue by mouday** [scrapy/scrapy#3483]
How to use Request parameter : body?, have any example?

requests module have the method:
```
url = "https://www.baidu.com/s"

params = {
    "word": "google"
}

requests.get(url, params=params)
```
this means:
```
url = https://www.baidu.com/s?word=google
```
scrapy can use for this?

**Comment by heylouiz** [comment]
As far as I know Scrapy doesn't provide this functionality.

You can pass the final url directly to the [Request](https://doc.scrapy.org/en/latest/topics/request-response.html#request-objects) method:
`return scrapy.Request('https://www.baidu.com/s?word=google')`

Or you can create the url as you want using [urlencode](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urlencode):

```
import scrapy                                                                  
                                                         
from urllib.parse import urlencode                                                             
                                                      
url = 'https://www.baidu.com/s'
                             
params = {'word1': 'google',                   
          'word2': 'bing',                                  
          'word3': 0}            
             
url = 'https://baidu.com/s?' + urlencode(params)                                  
                                         
print(scrapy.Request(url).url)
```

**Comment by mouday** [comment]
thank you, but i suggest Scrapy can suport request parameters like requests,

we will simple for use Scrapy.
