### ISSUE TITLE
On better handling use cases of PEP-380 inside request callbacks

### ISSUE THREAD

**Issue by starrify** [scrapy/scrapy#3484]
Recently I observed people writing something like this (when using Python 3.3+):

```
# coding: utf8

import scrapy


class TestSpider(scrapy.Spider):
    name = 'test'
    start_urls = ['http://httpbin.org/get']

    def parse(self, response):
        yield scrapy.Request('http://httpbin.org/get?foo=bar')
        return {'url': response.url}
```

That won't work as expected as the `return <some value>` statement here, as defined in [PEP-380](https://www.python.org/dev/peps/pep-0380/), is just equivalent to `raise StopIteration(<some value>)`.
Sample job logs: [link](https://gist.github.com/starrify/98ab313c64ce2e2926e94d8d178b9f70)

Currently (as of dc65e75) Scrapy simply ignores the "returned" value, which might be causing confusions to users. Sample job log of the code above: [link](https://gist.github.com/starrify/5dabc9433c3d68552d64b841c885e0b2)

A proposal is to generate an error (or at least warning) when such cases happen (`StopIteration` observed to have an value).

**Comment by lopuhin** [comment]
Another option would be to capture returned value as if it was yielded, I'm not sure how to implement it though.

**Comment by starrify** [comment]
Thanks @lopuhin for the idea. I agree it may be helpful in some specific cases, but unfortunately I don't think that's something we shall do.

There is [PEP 479](https://www.python.org/dev/peps/pep-0479/) discussing about such behaviors, which is applied to all code since Python 3.7.
- Before that: Values wrapped in `StopIteration` shall be ignored from being included in the generator's output. Example: [link](https://gist.github.com/starrify/56fbbc0dda4ae6b77ec8240db28f50c1#file-test_36).
- After that: Values "returned" by `return some_value` inside a generator shall be ignored from being included in the generator's output. `StopIteration` raised explicitly inside generators shall cause a `RuntimeError`. Example: [link](https://gist.github.com/starrify/56fbbc0dda4ae6b77ec8240db28f50c1#file-test_37).

Thus, although technically we're able to somehow pick up the "returned" value and have it used by Scrapy, I don't think that's the right way to go.

**Comment by starrify** [comment]
Also, from [PEP-380](https://www.python.org/dev/peps/pep-0380/) it has got this as one of the [rejected ideas](https://www.python.org/dev/peps/pep-0380/#id21):

> Suggestion: If close() is not to return a value, then raise an exception if StopIteration with a non-None value occurs.

While I agree that it is something we shall not have at the language level, I think it beneficial to check for such cases for only request callbacks within the scope of Scrapy, as I assume such mistakes may have been bothering some people for some time already.

**Comment by baby5** [comment]
this is right, not necessary
there are many things like this in scrapy:open_hands:
