### ISSUE TITLE
Line break is splitting the result of text()

### ISSUE THREAD

**Issue by paulmarlonsantos** [scrapy/scrapy#3488]
Environment:
Python 2.7
Scrapy 1.5

Normally, using text() in an xpath selector would return the content of the node. Please refer to the code snippet below.

```
<h2>Item A</h2>
<div>
    Why <br><br> is this separated?
</div>
<h2>Item B</h2>
<div>
    But this is not.
</div>
```

I am expecting that this would return a list with a single item but instead it splits the string using the line breaks **<br>**

```
>>> response.xpath('//div/div[1]/text()').extract()
# Output
[u'Why ',  u' is this separated?\r\n' ]
# Expected
[u'Why <br><br> is this separated?\r\n' ]
```

**Comment by OlgaCh** [comment]
It is an intended behavior.
With 
`response.xpath('//div[1]/text()').extract()`
you tell scrapy to extract text items from the 
` "Why <br><br> is this separated?"`
`<br>` actually not a part of plain text. It is a tag which defines new line. So it was omitted and you have 2 text parts as a result.
