### ISSUE TITLE
why not define a interface like java for pipeline and middleware?

### ISSUE THREAD

**Issue by mouday** [scrapy/scrapy#3489]
why not define a interface like java for pipeline and middleware?

i think can do this, maybe we implement a pipeline and middleware become simple.

**Comment by Gallaecio** [comment]
Could you elaborate a bit?

**Comment by mouday** [comment]
example:
you can defing a base class Middleware
```python
class Middleware(object):
    def process_request(self, request, spider):
        pass

```

we use it 
```python
class MyMiddleware(Middleware):
    def process_request(self, request, spider):
        # do something
```
it is means 

you define:  ` class Middleware(object)`

we use: `class MyMiddleware(Middleware)`

**Comment by kmike** [comment]
There is some discussion on that in https://github.com/scrapy/scrapy/issues/2633. The main question is - what would be the benefit, as all methods are optional (there are no required methods to implement), and each method may support different kwargs (it is hard to describe and validate API of supported methods). 

So such interface 

a) won't do any work at run-time (which is expected for an interface), and 
b) likely won't do any validation/check of the API, as it would be tricky to implement.  

So the only advantage I can see now is better discoverability - currently one have to rely on docs to know which methods can be implemented. Maybe also a warm fuzzy feeling that you have a middleware/extension/pipeline base class, which you inherited from. Disadvantages are:

* what for an user will ned to inherit from these base classes, if this gives nothing?
* there can be small performance issues, e.g. methods which were not present can become present, and called now;
* there is some risk of bugs, as a method which returns None may have a different meaning from method which is absent; we need to be careful with that.

**Comment by Gallaecio** [comment]
Closing in favor of #2633.
