### ISSUE TITLE
It's wrong when i run `view(response)` after `scrapy shell <url>`.

### ISSUE THREAD

**Issue by xxiaocheng** [scrapy/scrapy#3493]
I using `Scrapy =1.5.1 `  and `vscode=1.28.2`
I run ` view(response)`  when i want to see the response in the chrome ,but then the vscode was opened,the Chrome not open .
Please reply my question ,thanks.

**Comment by pel-h** [comment]
Hi @xxiaocheng,
Unlikely to be a scrapy issue, you must have vscode set as your default app to open html (like) files.
So change this and you should be fine.  
See similar: https://stackoverflow.com/questions/43299688/how-do-i-change-the-browser-used-by-the-scrapy-view-command

In general for support like this post it under StackOverflow.
