### ISSUE TITLE
Select element outside html tag

### ISSUE THREAD

**Issue by llermaly** [scrapy/scrapy#3497]
I have a special case where a script tag is placed outside the html tag :

```
<html>
....
</html>

<script>data</script>

```
both css and xpath selectors are not finding this script tag, the only way I found is using response.text , but that responds with a giant string and I can not make regex operations on it with selector re() function.

Is there a way to CSS or Xpath tags outside html tag?

I tried with

`response.css('script') 
`
But only consider script tags inside html tag

Thanks

**Comment by guillaume-humbert** [comment]
You probably want to use a xPath selector or manually parse the response text.
