### ISSUE TITLE
How to call spider.parse from a single url

### ISSUE THREAD

**Issue by hiro-o918** [scrapy/scrapy#3499]
Hi, I am trying to use a method `parse` of Spider in a source.
The following is an ideal code, though it does not work.

``` python
url = 'http://www.foo.com'
responce = Response(url)
myitem = MySpider().parse(response)

return myitem
```
where `MySpider` implements some `parse` method to yield an Item instance.

The reason might be that the `response` in the above downloads nothing.
I think `Request` must be utilized to realize that, but I do not know how to do.

thanks.

**Comment by nasirhjafri** [comment]
```python
url = 'http://www.foo.com'
return Request(url, callback=MySpider().parse)
```

**Comment by hiro-o918** [comment]
Thanks, I tried this before, but it does not work, because it returns Request class.
I need an Item instance parsed form Response by MySpider.

**Comment by maramsumanth** [comment]
url = 'http://www.foo.com'
return scrapy.Request(url=url ,callback=MySpider().parse)

**Comment by elacuesta** [comment]
Could you ellaborate a bit on the context of that snippet? Are you executing it as part of a standalone script?

**Comment by hiro-o918** [comment]
@elacuesta 
Thanks, yes, I try to use the snippet as a standalone script.
I have already developed `MySpider class` and succeeded in crawling and scraping some pages.
In my task, I want to scrape a page written in the same format `MySpider class` handled without crawling. So I wonder whether there is a way to reuse `MySpider class` to scrape the pages.

I know the way is different from the original use of this package.
And, in fact, I solved this by using another package.

**Comment by kmike** [comment]
Another approach is to separate scraping from crawling by extracting the scraping code to a separate function, which uses parsel.Selector instead of Response:

```py

def extract_items(sel):
    # this function can be used without Scrapy now, just with parsel library
    # ...

class MySpider(scrapy.Spider):
    # ...
    def parse(self, response):
         return extract_items(response.selector) 
```
