### ISSUE TITLE
JSON requests support

### ISSUE THREAD

**Issue by kasun** [scrapy/scrapy#3504]
This is a minor enhancement when dealing with JSON requests.

Right now to do a json request we have to do something like this,

    headers = {
        'Content-Type': 'application/json'
    }
    yield Request(url, method='POST', body=json.loads(data), headers=headers)

I'm proposing a new Request subclass that can save a few keystrokes.

    yield JSONRequest(url, data=data)

Will be sending a PR for this.

**Comment by kmike** [comment]
Fixed by #3505 .
