### ISSUE TITLE
Robots.txt Bug 

### ISSUE THREAD

**Issue by saseo90** [scrapy/scrapy#3508]
[robots.txt]Rule allowed but scrapped

robots.txt
>> 
![1](https://user-images.githubusercontent.com/21356484/49173952-70e5a480-f388-11e8-8aef-822b03af6edd.png)

Result

![2](https://user-images.githubusercontent.com/21356484/49173961-7511c200-f388-11e8-9c09-f59692a6857e.png)

**Comment by Gallaecio** [comment]
I cannot access those files (“Referral Denied”).

Maybe you should simply edit your response to embed the parts that are relevant to your report.

It would also help if you could elaborate a bit on the problem, and not simply provide files of file fragments to let readers figure things out by themselves.

**Comment by elacuesta** [comment]
@saseo90 I suspect your project is using the default User-Agent and Robots.txt configurations. Please see the [USER_AGENT](https://doc.scrapy.org/en/latest/topics/settings.html#user-agent) and [ROBOTSTXT_OBEY](https://doc.scrapy.org/en/latest/topics/settings.html#robotstxt-obey) settings.

In addition, in the future please refrain from posting support questions in the Github issue tracker. There are more appropiate channels for these kind of questions, like the `scrapy` tag in StackOverflow (see https://scrapy.org/community/ for a comprehensive list of resources). This channel should be reserved for bug reports and feature requests. Thanks for your understanding.

**Comment by Gallaecio** [comment]
Closing due to a lack of feedback from the author.
