### ISSUE TITLE
Scrapy to send a request using the specified network card python 3

### ISSUE THREAD

**Issue by ManthanSatani** [scrapy/scrapy#3514]
I have created one scrapy project it is working well, I wanted it to host on the server to run it daily and it is working, But my server has two Network Card one is specially added for scrapy, still project is working but I wanted to use only one Network Card for scrapy or python and that I can specify that this Network card Python or Scrapy can use.

Server: Windows 10
Python: 3.6
Scrapy: 1.5

I was looking for the solution and found this [Python sends an HTTP request using the specified network card](https://blog.csdn.net/u012731379/article/details/78711549) on the internet but actually, I did not understand how it can be used.

Please help me to solve this solution may be like assign Network Card to python or assign Network card to socket or core library that scrapy used to request the website.

**Comment by VMRuiz** [comment]
Hello,

You can use the `bindaddress` meta attribute for selecting the network interface you want to use: https://doc.scrapy.org/en/latest/topics/request-response.html#std:reqmeta-bindaddress

You may want to write a middleware to add that param automatically to all request

**Comment by ManthanSatani** [comment]
I have written the below middleware

    class BindAddressMiddleware(object):
        def __init__(self, settings):
            self.is_bindaddress = settings.get('IS_MORE_NETWORK_CARDS')
            if self.is_bindaddress:
                self.bindaddress = settings.get('BIND_ADDRESS')

        @classmethod
        def from_crawler(cls, crawler):
            return cls(crawler.settings)

        def process_request(self, request, spider):
            if self.is_bindaddress:
                if self.bindaddress:
                    spider.logger.info('Using: %s as bindaddress' % self.bindaddress)
                    request.meta['bindaddress'] = (self.bindaddress, 80)
            return None

settings.py as below

    # Network card configuration
    IS_MORE_NETWORK_CARDS = False
    BIND_ADDRESS = '192.168.1.1'

    DOWNLOADER_MIDDLEWARES = {
        # Bindaddress in the middleware setting
        'scrapers22.middlewares.BindAddressMiddleware': 400,
    }

I have scrapy project that has more than 50 crawlers all are working, at once more than 16 crawlers are working.

Issue detailed

I run one crawler that visits one URL and generates the result it worked perfectly then
I run the second crawler immediately that gets the input of first and visits the links but it gives me the error
    
    2018-12-07 17:51:01 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://www.superdry.com/us/mens/winter-exclusives-1> (failed 10 times): Couldn't bind: 10048: Only one usage of each socket address (protocol/network address/port) is normally permitted.

I got above error and after some time one link is processed and then the same error so on and on...
Please help me to solve this

**Comment by elacuesta** [comment]
@ManthanSatani I didn't dig deep into the issue, but perhaps https://stackoverflow.com/a/12362623 is relevant?

Also, if I followed the code correctly, the `IS_MORE_NETWORK_CARDS` setting is `False`, which sets the `BindAddressMiddleware.is_bindaddress` attribute to `False`, and hence the first check in the `BindAddressMiddleware.process_request` method is `False`, leaving the request unaltered.
Just an observation, I think the settings might just be outdated.

**Comment by ManthanSatani** [comment]
@elacuesta this is not the exact solution to use with the scrapy

> @ManthanSatani I must admit I didn't dig deep into the issue nor tried the code myself, but perhaps https://stackoverflow.com/a/12362623 is relevant?

but I solved the issue. The scrapy request has meta['bindaddress'] attribute that is used to pass bind-address with a port as tuple since the one port is not reusable immediately after the request is finished it gives the error but if the port is 0 then it will use a random port for a request so each time the new port is used so no need to specify to reuse the port.

So I changed port to `0` from `80`

    def process_request(self, request, spider):
        if self.is_bindaddress:
            if self.bindaddress:
                spider.logger.info('Using: %s as bindaddress' % self.bindaddress)
                request.meta['bindaddress'] = (self.bindaddress, 80)
        return None`

after change the middleware look like this with usage of settings to use bindaddress or not

    class BindAddressMiddleware(object):
        def __init__(self, settings):
            self.is_bindaddress = settings.get('IS_MORE_NETWORK_CARDS')
            if self.is_bindaddress:
                self.bindaddress = settings.get('BIND_ADDRESS')

        @classmethod
        def from_crawler(cls, crawler):
            return cls(crawler.settings)

        def process_request(self, request, spider):
            if self.is_bindaddress:
                if self.bindaddress:
                    request.meta['bindaddress'] = (self.bindaddress, 0)
            return None
        
        def spider_opened(self, spider):
            spider.logger.info('Using: %s as bindaddress' % self.bindaddress)
