### ISSUE TITLE
During handling of the above exception, another exception occurred:

### ISSUE THREAD

**Issue by NileshBharti2** [scrapy/scrapy#3523]
import csv
import scrapy
from scrapy.http import Request
from scrapy.loader import ItemLoader
from scrapy.item import Item, Field

class FromcsvSpider(scrapy.Spider):
	name = 'from'
	

	def parse(self, response):
		with open("todo.csv","rU") as f:
			reader=csv.DictReader(f)
			for line in reader:
				request = Request(line.pop('url'))
				request.meta['fields']= line
				yield request
				
	def parse(self, response):
		item=Item()
		l=ItemLoader(item=item,respone=response)
		for name,xpath in response.meta['fields'].iteritems():
			if xpath : item,fields[name] = Field()
			l.add_xpath(name, xpath)
			return l.load_item()      
![capture](https://user-images.githubusercontent.com/45348995/49562462-ae769e80-f941-11e8-85fb-1263feb8e54e.JPG)

**Comment by destrat18** [comment]
i think it's might be related to that you set name of your spider to "from" but in command line you call "fromcsv"

**Comment by elacuesta** [comment]
The aboe answer is correct in my opinion.

In addition, in the future please refrain from posting support questions in the Github issue tracker. There are more appropiate channels for these kind of questions, like the `scrapy` tag in StackOverflo (see https://scrapy.org/community/ for a comprehensive list of resources). This channel should be reserved for bug reports and feature requests. Thanks for your understanding.

**Comment by destrat18** [comment]
yeah your right ;-)
