### ISSUE TITLE
Two consecutive yields, only the first work

### ISSUE THREAD

**Issue by Sshuichi** [scrapy/scrapy#3524]
I have this piece of code that only executes the first yield's callback and not the next one. I have tried reordering them and it gives the same result: 
Only the first yield callback gets executed.

```
        for j in range(totalOrderPages):  # the code gets in the loop
            productURI = feedUrl % (productId, j + 1)
            print "Got in the loop" # this gets printed 
            yield response.follow(productURI, self.parse_orders, meta={'pid': productId, 'categories': categories})
        yield response.follow(first_page, self.parse_product, meta={'pid': productId, 'categories': categories})
```

Is there anything in Python or scrapy that prevents 2 consecutive yields? 

Second question: 
I'm trying to debug this using pdb.set_trace() but when I try to execute yield from the debugging console, it give the `yield outside function` error. 

Does anyone know how can we debug yields? 

Thank you.

**Comment by elacuesta** [comment]
Hello @Sshuichi, thanks for taking the time to open this ticket. I've answered one [StackOverflow question](https://stackoverflow.com/q/53681955/6946615) which I assumed is motivated by the same issue.
In the future please refrain from posting support questions in the Github issue tracker. There are more appropiate channels for these kind of questions (see https://scrapy.org/community/ for a comprehensive list of resources). This channel should be reserved for bug reports and feature requests. Thanks for your understanding.
