### ISSUE TITLE
I get invalid syntax while I install scrapy 1.5 using pip 

### ISSUE THREAD

**Issue by Naba7** [scrapy/scrapy#3530]
scrapy startproject stack
  File "<stdin>", line 1
    scrapy startproject stack
                      ^
SyntaxError: invalid syntax

**Comment by Gallaecio** [comment]
That is not a Scrapy error. You are running the command on a Python prompt. It is meant to be executed on a terminal prompt.

**Comment by maramsumanth** [comment]
@Naba7 you need to open command line and execute it.

**Comment by Naba7** [comment]
@maramsumanth thanks.dumb me.
