### ISSUE TITLE
The documentation builds at Read the Docs are broken

### ISSUE THREAD

**Issue by Gallaecio** [scrapy/scrapy#3531]
See https://readthedocs.org/projects/scrapy/builds/

The error message is:

    error: The 'pyasn1' distribution was not found and is required by service-identity

It looks like a long-standing issue. Also, there were a couple of builds without the issue.

**Comment by dangra** [comment]
Citing @kmike 

> I think failures were caused by renaming requirements.txt to requirements-py2.txt, which made some other weird issue visible (maybe this one: https://github.com/pypa/setuptools/issues/498). So I specified requirements-py3.txt as requirements file in rtfd, after that builds starts to pass.
