### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by rasendubi** [scrapy/scrapy#3539]
I would like to request a new Scrapy release. The feature I am interested in is Python 3.7 support. (NixOS has switched default python3 to be python 3.7 and that broke default scrapy.)

The feature was implemented in #3326 but hasn't been released yet.

**Comment by nyov** [comment]
The same will be true for Debian.
Debian next is freezing in february, so if a new Scrapy release is to go in, it'll probably have to be available before that date.

**Comment by malberts** [comment]
This issue can be closed since Scrapy 1.6 has been released and supports Python 3.7.
