### ISSUE TITLE
sleep

### ISSUE THREAD

**Issue by Hecate2** [scrapy/scrapy#3545]
When I execute time.sleep in a parse of scrapy, does it block other concurrent requests? And what if I execute Request (from urllib)in a parse? On what occasions are all the concurrent requests blocked?
(Sorry for my lousy English!)

**Comment by sukaaaa** [comment]
不会卡掉的

**Comment by sukaaaa** [comment]
不会卡掉的

**Comment by Matthijsy** [comment]
In my experience the time.sleep method blocks the full application, so also all requests. What I know about scrapy is that it doesn't do concurrent requests (since its build on twisted which is not concurrent), and time.sleep blocks the current thread so this will block your full scraper.

**Comment by joaquingx** [comment]
@Hecate2 if @Matthijsy answer to your question you could close this issue :smile:
