### ISSUE TITLE
why shutting down 

### ISSUE THREAD

**Issue by saseo90** [scrapy/scrapy#3546]
[log]
2018-12-26 13:12:50 [scrapy.crawler] 258:INFO: Received SIGTERM, shutting down gracefully. Send again to force

**Comment by joaquingx** [comment]
@saseo90 Could you update your answer or tell us if you found the solution?

**Comment by kmike** [comment]
I'm closing it because the issue lacks details. Feel free to reopen if you think there is a Scrapy bug.
