### ISSUE TITLE
scrapy getting stuck after some time

### ISSUE THREAD

**Issue by suraj-deshmukh** [scrapy/scrapy#3560]
I have a master-worker network on aws ec2 using dask distributed library. For now i have one master machine and one worker machine. Master has REST api (flask) for scheduling scrapy jobs on worker machine. I am using docker for both master and worker that means both master container and worker container communicating with each other using dask distributed. 

When i scheduler scrapy job, crawling starts successfully and scrapy uploads data to s3 as well. But after some time scrapy gets stuck at one point and nothing happens after that.

Please check attached log file for more info

[log.txt](https://github.com/scrapy/scrapy/files/2720411/log.txt)

    2019-01-02 08:05:30 [botocore.hooks] DEBUG: Event needs-retry.s3.PutObject: calling handler <bound method S3RegionRedirector.redirect_from_error of <botocore.utils.S3RegionRedirector object at 0x7f1fe54adf28>>

scrapy get stuck at above point.

command to run docker:
    
    sudo docker run --network host -d crawler-worker # for worker
    sudo docker run -p 80:80 -p 8786:8786 -p 8787:8787 --net=host -d crawler-master # for master

NOTE:

When i open docker image in interactive mode and execute scrapy crawl command then scrapy successfully crawls the given site and stops execution successfully after depth limit.

**Comment by suraj-deshmukh** [comment]
i am closing this issue as i solved the problem. The problem was in subprocess which i was using it to execute the scrapy with argument stdout=subprocess.PIPE and as per subprocess's documentation wait() function can cause a deadlock when using stdout=subprocess.PIPE or stderr=subprocess.PIPE.

**Comment by Tasaqi** [comment]
![image](https://user-images.githubusercontent.com/38526341/86359825-f202cd00-bc8a-11ea-8541-132de97c6c12.png)


Scrapy stuck while crawling. I used multiprocessing 


Here is code 


![image](https://user-images.githubusercontent.com/38526341/86359972-28404c80-bc8b-11ea-9e48-394840eaf31a.png)
