### ISSUE TITLE
NameError: name 'sanitize' is not defined

### ISSUE THREAD

**Issue by Bassi1997** [scrapy/scrapy#3564]
I am trying to sort some data which are not uniformly formated , so i am trying to apply sanitize() but it won't execute and alerts me with the message: Traceback (most recent call last):
  File "C:\Users\Ayman\AppData\Local\Programs\Python\Builds\HeadFirstPython\Chapter5\coach.py", line 20, in <module>
    clean_james.append(sanitize(each_t))
NameError: name 'sanitize' is not defined
I am using python37 
so i found that this function was removed from this version library ,, so what is the alternative for this procedure in this version ? 
this is the code structure : 

import os
os.chdir('C:\\Users\\Ayman\\AppData\\Local\\Programs\\Python\\Builds\\HeadFirstPython\\Chapter5')
with open ('james.txt') as jaf:
    data = jaf.readline()
james = data.strip().split(',')
with open ('julie.txt') as juf:
    data = juf.readline()
julie = data.strip().split(',')
with open ('mikey.txt') as mif:
    data = mif.readline()
mikey = data.strip().split(',')
with open ('sarah.txt') as saf:
    data = saf.readline()
sarah = data.strip().split(',')
clean_james = []
clean_jolie = []
clean_mikey = []
clean_sarah = []
for each_t in james:
    clean_james.append(sanitize(each_t))
for each_t in jolie:
    clean_jolie.append(sanitize(each_t))
for each_t in mikey:
    clean_mikey.append(sanitize(each_t))
for each_t in sarah:
    clean_sarah.append(sanitize(each_t))

print(sorted(clean_james))
print(sorted(clean_julie))
print(sorted(clean_mikey))
print(sorted(clean_sarah))

Traceback (most recent call last):
  File "<pyshell#5>", line 1, in <module>
    clean = [sanitize(t) for t in dirty]
  File "<pyshell#5>", line 1, in <listcomp>
    clean = [sanitize(t) for t in dirty]
NameError: name 'sanitize' is not defined

**Comment by elacuesta** [comment]
`sanitize` is not a Python [built-in function](https://docs.python.org/3/library/functions.html#built-in-functions) and I see no occurrences of it in the Scrapy codebase.
In the snippet you pasted there is no `import` statement related to `sanitize`, are you sure you are importing it from the right place?

**Comment by Bassi1997** [comment]
i wrote down a code that solved my problem and it works just fine,, 

#This is a code for sanitizing data in non-uniform format
def sanitize(time_string):
    try:
        if '-' in time_string:
            splitter = '-'
        elif ':' in time_string:
            splitter = ':'
        else:
            return(time_string)
    except: pass
    
    (mins, sec) = time_string.split(splitter)
    return(mins + '.' + sec)

**Comment by elacuesta** [comment]
@Bassi1997 I'm glad you were able to solve the problem. Would you consider closing this issue if it's no longer necessary?
