### ISSUE TITLE
Redirects don't go through middleware

### ISSUE THREAD

**Issue by mohmad-null** [scrapy/scrapy#3580]
I have some simple middleware that blocks certain domains from being crawled and raises an IgnoreRequest for those domains. It works well.

However, I've just discovered it gets ignored for requests that go through the RedirectMiddleware.

My normal priority for the middleware is 110, but upon looking up https://doc.scrapy.org/en/latest/topics/settings.html#std:setting-SPIDER_MIDDLEWARES_BASE - I see the redirect middleware is later than that, so I tried changing the number to 800, but to no avail.

I tried looking in https://github.com/scrapy/scrapy/blob/1fd1702a11a56ecbe9851ba4f9d3c10797e262dd/scrapy/downloadermiddlewares/redirect.py - to see what was going on, but there are exactly 2 lines of comment in 102 lines of code so....

**Comment by mohmad-null** [comment]
@nasirhjafri - Sorry, I wasn't clear. That's what I was doing, and that's what the numbers "110" and "800" were referring to - setting the priority to being clearly above, and clearly below the RedirectMiddleware

**Comment by kmike** [comment]
@mohmad-null are you sure you're using downloader middleware, not spider middleware (a link to priorities is to spider middleware priorities)?

**Comment by mohmad-null** [comment]
@kmike - I'm setting my middleware priorities using the `DOWNLOADER_MIDDLEWARES` scrapy setting. 

I've never touched the `SPIDER_MIDDLEWARES_BASE`, and wasn't aware of the difference until your post made me look into it.

**Comment by elacuesta** [comment]
@mohmad-null If I understand correctly, I think you are experiencing documented behaviour.

According to the [`DownloaderMiddleware.process_response` docs](https://docs.scrapy.org/en/latest/topics/downloader-middleware.html#scrapy.downloadermiddlewares.DownloaderMiddleware.process_response):

> If it returns a Request object, the middleware chain is halted and the returned request is rescheduled to be downloaded in the future. This is the same behavior as if a request is returned from process_request().

This is precisely what the `RedirectMiddleware` does, it returns **new** requests for those responses that indicate a redirect should be performed. 


See the below code and logs:

```python
# redirect.py
import scrapy


class ExampleMiddleware:
    def process_request(self, request, spider):
        print("Processing request:", request.url)
        return None

    def process_response(self, request, response, spider):
        print("Processing response:", response.url)
        return response


class RedirectSpider(scrapy.Spider):
    name = "exception_spider"
    start_urls = [
        "https://httpbin.org/redirect-to?url=/uuid",
        "https://example.org",
    ]
    custom_settings = {
        "DOWNLOADER_MIDDLEWARES": {
            __name__ + ".ExampleMiddleware": 550,
        },
        "LOG_LEVEL": "INFO"
    }

    def parse(self, response):
        print("Got response:", response.url)
```

```
$ scrapy runspider redirect.py  # priority set to 550
(...)
Processing request: https://httpbin.org/redirect-to?url=/uuid
Processing request: https://example.org
Processing response: https://example.org
Processing request: https://httpbin.org/uuid
Got response: https://example.org
Processing response: https://httpbin.org/uuid
Got response: https://httpbin.org/uuid
(...)
```

According to the docs for the [`DOWNLOADER_MIDDLEWARES_BASE`](https://doc.scrapy.org/en/latest/topics/settings.html#downloader-middlewares-base), the `RedirectMiddleware` priority is 600, so I tried both 550 and 650, and got almost the same result, the difference being that with 650, the example middleware intercepts the redirecting response before the `RedirectMiddleware`:

```
$ scrapy runspider redirect.py  # priority set to 650
(...)
Processing request: https://httpbin.org/redirect-to?url=/uuid
Processing request: https://example.org
Processing response: https://example.org
Processing response: https://httpbin.org/redirect-to?url=/uuid
Processing request: https://httpbin.org/uuid
Got response: https://example.org
Processing response: https://httpbin.org/uuid
Got response: https://httpbin.org/uuid
(...)
```

Please do let us know if this explains your issue.
