### ISSUE TITLE
Redirect doesn't expose original status code

### ISSUE THREAD

**Issue by mohmad-null** [scrapy/scrapy#3581]
I'm being redirected with a 307 - the log says so. I'd like to handle this differently to a 302. However the redirect middleware doesn't seem to keep the original status code as far as I can see, not even in meta. It would be nice if there was a list of redirect status codes to go with the list of redirect_urls.

**Comment by kevenli** [comment]
Could use the [dont_redirect](https://doc.scrapy.org/en/latest/topics/downloader-middleware.html#std:reqmeta-dont_redirect) request meta,

**Comment by VMRuiz** [comment]
You could also extend and replace the default redirect middleware so it adds this functionality for you. 
I'm afraid this behavior is too peculiar to be included as a general feature for everyone.

https://doc.scrapy.org/en/latest/topics/downloader-middleware.html#scrapy.downloadermiddlewares.redirect.RedirectMiddleware

**Comment by mohmad-null** [comment]
@VMRuiz - I considered it, but that's a huge amount of work from my perspective, and the extant RedirectMiddleware is very poorly documented so it'd be even more work just to grok what's going on (2 comment lines in a 102 line file).

**Comment by kmike** [comment]
This feature makes sense to me. Probably it should be a separate list (`redirect_codes`?) for backwards compatibility.

**Comment by joaquingx** [comment]
I'll work on this

**Comment by maramsumanth** [comment]
I think it is safe to close this issue, solved in https://github.com/scrapy/scrapy/pull/3687
