### ISSUE TITLE
Do not recommend Google Cache in the documentation

### ISSUE THREAD

**Issue by Gallaecio** [scrapy/scrapy#3582]
From the feedback at [Using Scrapy on a Google cache of a website](https://stackoverflow.com/questions/50555545/using-scrapy-on-a-google-cache-of-a-website), I think we should stop [recommending Google Cache in the Scrapy documentation](https://doc.scrapy.org/en/latest/topics/practices.html#avoiding-getting-banned).

We should review the terms of use of the Wayback Machine from archive.org, and see if we can recommend that instead.

**Comment by yashrajjain726** [comment]
If you want, I will do it.

**Comment by Farsene1** [comment]
Is this issue still relevant? If so, I'd like to work on it

**Comment by Gallaecio** [comment]
Removing the current recommendation is still relevant, but instead of the Wayback Machine we should probably recommend:

- https://commoncrawl.org/
- https://datasetsearch.research.google.com/

**Comment by Farsene1** [comment]
@Gallaecio thanks for approving my PR, I don't have write access to merge it. Can you do it please?

**Comment by Gallaecio** [comment]
@Farsene1 We usually go for 2 maintainer approvals before merging. When another maintainer gets a chance to review and approve the change, we will merge it. Please, be patient.

**Comment by Farsene1** [comment]
Understood, thanks
