### ISSUE TITLE
lambda packaging has two error

### ISSUE THREAD

**Issue by up0617** [scrapy/scrapy#3584]
Hi, 
I tried to run my spider on aws lambda.
Then I need to make a zip file with whole scrapy lib packaged. 
So I installed scrapy at project folder via below command:
`pip install scrapy --target ~/myprojectfolder/package`

and import lib in script file(MySpider.py) via 
`from package.scrapy.http import Request`

then I tried to run scrapy via below command:
`python MySpider.py`

at first it gives twisted import error 
then I add below code to /project/scrapy/__init__.py, above importing _monkeypatches
`sys.path.append('./package/')`

so the prob is resolved, but I encountered another one. 

It stops after below message. 
`2019-01-16 13:48:06 [scrapy.extensions.telnet] DEBUG: Telnet console listening on 127.0.0.1:6023`

**Comment by lopuhin** [comment]
@up0617 I imagine that a lot of stuff will break if ``scrapy`` is not available to be imported, but is available as ``package.scrapy`` instead - I assume this is the case?

I think following "With a Virtual Environment" from the official guide would be better: https://docs.aws.amazon.com/lambda/latest/dg/lambda-python-how-to-create-deployment-package.html

**Comment by nicoparsa** [comment]
Hi, I had the same problem yesterday. 

It seems that the compilation of certain libraries such 'lxml' is dependent of Linux S.O, so is not the same compile the project in MacOS that compile in Linux CentOS.

I resolve the problem with the service of AWS: SAM (Serverless Application Model). It uses Docker images to compile our projects with the same architecture of AWS Servers, so you can compile your project and invoke the function in local console to watch the results of Lambda Execution.

But now, I have the problem with LOG_LEVEL parameter. I run Scrapy from script [https://doc.scrapy.org/en/latest/topics/practices.html#run-scrapy-from-a-script](url) and I define my settings in the main handler: 

`    settings = {
                'USER_AGENT': 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.85 Safari/537.36',
                'LOG_ENABLED': True,
                'LOG_LEVEL': 'ERROR'
             }

    process = CrawlerProcess(settings=settings)`

When execute this code in local, all is correct, only receive the LOG_LEVEL: ERROR, but when execute this code in AWS Lambda, I receive the LOG_LEVEL: DEBUG, and I don´t know how to resolve.

Is like the Spider doesn´t receive the settings of the Crawler. Do you know how to resolve it?

Thanks!

**Comment by up0617** [comment]
Hi, sorry for the late answer!

@lopuhin 
I'm using anaconda now and tried the guide you suggested then it works!
I installed by below code.
`conda install scrapy --target ~/myprojectfolder/package`
and import by appending path as below.
`import sys
sys.path.append('./package/lib/python3.7/site-packages')`

@nicoparsa 
Thanks! 
I didn't upload my spider to lambda yet and I think Docker is better than just zip and upload libraries. 
I'll try Docker and share any success/failures!
