### ISSUE TITLE
Ability to retry a request from inside a spider callback

### ISSUE THREAD

**Issue by kasun** [scrapy/scrapy#3590]
There are situations where websites return 200 responses but the content is not available due to bans or temporal issues which can be fixed by retrying requests.

There should be an easier way to retry requests inside spider callbacks, which should ideally reuse the code in Retry downloader middleware.

I see two approaches for this.

1) Introduce new exception called RetryRequest which can be raised inside a spider callback to indicate a retry. I personally prefer this but the implementation of this is a little untidy due to this bug #220

    ```
    from scrapy.exceptions import RetryRequest

    def parse(self, response):
        if response.xpath('//title[text()="Content not found"]'):
            raise RetryRequest('Missing content')
    ```
2) Introduce a new class RetryRequest which wraps a request that needs to be retried. A RetryRequest can be yielded from a spider callback to indicate a retry

    ```
    from scrapy.http import RetryRequest

    def parse(self, response):
        if response.xpath('//title[text()="Content not found"]'):
            yield RetryRequest(response.request, reason='Missing content')
    ```

Will be sending two PRs for the two approaches. Happy to hear about any other alternatives too.

**Comment by Gallaecio** [comment]
What aspects of the [current approach](https://stackoverflow.com/a/28640118/939364) don’t you like? It can be done with a one-liner (`yield response.request.replace(dont_filter=True)`).

**Comment by kasun** [comment]
@Gallaecio I miss everything the retry middleware currently does.

You can't infinitely do this. you need to count the retries and give up after a certain retry attempts
You need to have stats and log messages

IMO there should be a easier way to do above things than re-implement the same code in every project/spider.

**Comment by ejulio** [comment]
I think the idea is nice, though I think you should focus on only one approach.
IMHO, number 1 is better because it makes more sense to retry when some specific exception happened.
I don't think a special kind of Request would be the best approach here.

Also, I think that we should focus on only one of them because _There should be one-- and preferably only one --obvious way to do it._

**Comment by apalala** [comment]
We frequently, comfortably, and successfully use the `raise RetryRequest("a reason")` approach in BV. It counts and limits retries, logs the _reason_, and, in general, does what it should without much work from the developer. As the OP mentioned, corrupted content over 200 responses is frequent enough.

**Comment by stav** [comment]
What about attaching the middleware routine to the response:

    class RetryMiddleware(scrapy.downloadermiddlewares.retry.RetryMiddleware):

        def process_response(self, request, response, spider):
            """Attach a .retry() method to every response"""
            response = super().process_response(request, response, spider)

            def retry(**kwargs):
                reason = kwargs.pop('reason', 'response_retry_called')
                retryreq = request.replace(**kwargs)
                return self._retry(retryreq, reason, spider)

            if isinstance(response, scrapy.http.Response):
                response.retry = retry

            return response

Then it could be used like:

    def parse(self, response):
        if response.xpath('//title[text()="Content not found"]'):
            yield response.retry(reason='Missing content')

**Comment by ejulio** [comment]
@stav, from the API user point of view, I don't know if `response.retry` gives enough meaning that we are, actually, retrying the request.

**Comment by stav** [comment]
What about:

            yield response.request.retry(reason='Missing content')

**Comment by apalala** [comment]
I like `yield response.request.retry(reason='Missing content')`, except it will often require a `return` afterwards.

At any rate, the solution should accept the same parameters as `request.replace()`, do whatever is necessary so the new request is not detected as a duplicate, and keep a retry count and limit.

It could be both, with `raise RetryRequest()` implemented in terms of `Request.retry()`.

**Comment by stav** [comment]
> it will often require a `return` afterwards

We could also just have:

    return [response.request.retry(reason='Missing content')]

> It could be both, with `raise RetryRequest()`

What benefit does allowing `parse` to raise an exception give us?  I'm always confused with whose responsibility it is to catch exceptions, so this is probably just my ignorance :confused:

**Comment by apalala** [comment]
> What benefit does allowing `parse` to raise an exception give us?

Good question!

While implementing session pooling I wrote a session-aware `retry_request()`, and never missed not having an exception for the functionality.

**Comment by GeorgeA92** [comment]
We can call [_retry](https://github.com/scrapy/scrapy/blob/1.5.0/scrapy/downloadermiddlewares/retry.py#L63-L91) method of Retry middleware from the spider code

```
class Myspider(scrapy.Spider):
.....
   def start_requests(self):
        downloader_middlewares = self.crawler.engine.downloader.middleware.middlewares
        self.RetryMiddleware = [middleware for middleware in downloader_middlewares if "RetryMiddleware" in str(type(middleware))][0]
.....

    def parse(self, response):
        if response.xpath('//title[text()="Content not found"]'):
            yield self.RetryMiddleware._retry(response.request,"some reason",self)
            return
```

**Comment by ejulio** [comment]
@GeorgeA92, I don't like this approach :(
My problem is that we are calling a private method from the outside.

**Comment by GeorgeA92** [comment]
@ejulio  I agree.
There are 2 non private methods where `_retry `method called.

[process_requests ](https://github.com/scrapy/scrapy/blob/master/scrapy/downloadermiddlewares/retry.py#L50-L56)calls `_retry` if response code listed in `retry_http_codes` (from `RETRY_HTTP_CODES` setting). 
This is not our case because 200 response is not in `retry_http_codes `and response needs to pass all middlewares (including `RetryMiddleware`) in order to reach spider callback (and retry request from spider callback).

[process_exception ](https://github.com/scrapy/scrapy/blob/master/scrapy/downloadermiddlewares/retry.py#L58-L91)calls `_retry `if exception argument listed in `EXCEPTIONS_TO_RETRY `which is stored as tuple.
https://github.com/scrapy/scrapy/blob/c72ab1d4ba5dad3c68b12c473fa55b7f1f144834/scrapy/downloadermiddlewares/retry.py#L34-L37

We can use non private `process_exception `method instead of `_retry `in spider code after following:
1.define new `Exception` 
2.add our custom `Exception `in `EXCEPTION_TO_RETRY `in `RetryMiddleware` object
3.call `process_exception ` method with our new `exception `as argument
Code is slightly different:

```
class ContentNotFoundException(Exception):
    """
    ContentNotFound
    """

class Myspider(scrapy.Spider):
.....
   def start_requests(self):
        downloader_middlewares = self.crawler.engine.downloader.middleware.middlewares
        self.RetryMiddleware = [middleware for middleware in downloader_middlewares if "RetryMiddleware" in str(type(middleware))][0]
	self.RetryMiddleware.EXCEPTIONS_TO_RETRY = tuple(list(self.RetryMiddleware.EXCEPTIONS_TO_RETRY)+[ContentNotFoundException])
.....

    def parse(self, response):
        if response.xpath('//title[text()="Content not found"]'):
            yield self.RetryMiddleware.process_exception(response.request, ContentNotFoundException(), self)
            return
```

**Comment by kasun** [comment]
After going through the different ideas, I opted for Response.retry_request() over raising a RetryException() to indicate a retry.

This new method will just return a request that is marked as to be retried and actual modification needed to retry the request is been handled in a new spidermiddleware. The reason is you need access to spider settings to determine whether the request has reached the maximum retry attempts etc.

please have a look at https://github.com/scrapy/scrapy/pull/3685

**Comment by yuanfeiz** [comment]
Any progress on this?

**Comment by ShanikaEdiriweera** [comment]
Any update on this? 

I also encounter the issue mentioned by @kasun

**Comment by kiwido** [comment]
use try and except to handle retry request, and for counting the number of retry set a variable in the "meta", update that in the except section. 

that is wrong??

**Comment by fellipegpbotelho** [comment]
Any update on this?

**Comment by psdon** [comment]
any updates on this?

**Comment by Gallaecio** [comment]
The latest is the API design discussion in https://github.com/scrapy/scrapy/pull/4902
