### ISSUE TITLE
may be 'accessible'?

### ISSUE THREAD

**Issue by amchii** [scrapy/scrapy#3597]
in the function [request_fingerprint](https://github.com/scrapy/scrapy/blob/master/scrapy/utils/request.py) ，‘accesible’ may be ‘accessible’ in comments. OCD  XD..

**Comment by Exmlyshy** [comment]
> Did you know you can edit the file directly on Github (there is an edit button on the top right side) and easily create a pull request with the change? :)

Thanks for your reply , I didn't do this just because it's tiny or there is another word 'accesible'?

**Comment by elacuesta** [comment]
This issue will be rendered obsolete after #3975
