### ISSUE TITLE
Document LogFormatter

### ISSUE THREAD

**Issue by Gallaecio** [scrapy/scrapy#3616]
Currently, the `LogFormatter` class is only mentioned in the [Release notes](https://docs.scrapy.org/en/latest/news.html) page of the documentation. This class should be properly documented, both its API members and a small section introducing it on the documentation page about [Logging](https://docs.scrapy.org/en/latest/topics/logging.html).

The responses to [Scrapy - Silently drop an item](https://stackoverflow.com/q/13527921/939364) in StackOverflow would be a good starting point.

**Comment by anubhavp28** [comment]
@Gallaecio I would like to work on this. I am new to Scrapy, and not sure if it is necessary to be assigned the issue to work on it? Can you assign this to me?

**Comment by Gallaecio** [comment]
Creating a pull request and referencing this issue from it. as you did, is enough. Thanks, someone will have a look at it and give you feedback in the coming days.
