### ISSUE TITLE
issues in installing 'src'

### ISSUE THREAD

**Issue by samohant** [scrapy/scrapy#3619]
Unable to install 'src'
Collecting src
  Using cached https://files.pythonhosted.org/packages/9a/2b/a6ccfc80af698319c54f00da05f6c798cf72291938893f8bd3f730c2daf9/src-0.0.7.zip
Building wheels for collected packages: src
  Building wheel for src (setup.py) ... error
 . . .
. . .
      return (self.distribution.has_pure_modules() or
  AttributeError: 'NoneType' object has no attribute 'has_pure_modules'

  ----------------------------------------
  Failed building wheel for src
  Running setup.py clean for src
Failed to build src
Installing collected packages: src
  Running setup.py install for src ... error

**Comment by Gallaecio** [comment]
Please, include the installation commands as well.

**Comment by samohant** [comment]
I have fixed my issue. Thank you so much. src was a folder. I used the command " pip install --upgrade -r requirements.txt" to install the required packages.

Thank you so much.
