### ISSUE TITLE
error on "pip install scrapy"

### ISSUE THREAD

**Issue by kennblvnp** [scrapy/scrapy#3633]
Python 3.7
pip 19.0.2

Command "c:\users\kenda\appdata\local\programs\python\python37-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\kenda\\AppData\\Local\\Temp\\pip-install-p0r6426p\\Twisted\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\kenda\AppData\Local\Temp\pip-record-0rrj6dmu\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\kenda\AppData\Local\Temp\pip-install-p0r6426p\Twisted\

**Comment by Gallaecio** [comment]
Make sure you are following the [installation guide](https://doc.scrapy.org/en/latest/intro/install.html).

If you are, please provide more output, the line you paste simply states that there was a failure, the actual underlying issue should appear a few lines before that.

**Comment by ceb10n** [comment]
as the [installation guide](https://doc.scrapy.org/en/latest/intro/install.html) points, it's recommended to install Scrapy with anaconda or miniconda.

But I installed it right now at my office pc running on windows 10 using pip to test it, and it wen't all good:

`successfully installed PyDispatcher-2.0.5 Twisted-18.9.0 asn1crypto-0.24.0 cryptography-2.5 pyOpenSSL-19.0.0 pyasn1-0.4.5 pyasn1-modules-0.2.4 queuelib-1.5.0 scrapy-1.6.0 service-identity-18.1.0`

See [Platform specific installation notes](https://doc.scrapy.org/en/latest/intro/install.html#platform-specific-installation-notes)

**Comment by avikorat** [comment]
you can follow user manual as per installation of [anaconda](https://www.anaconda.com/distribution/) to install the scrapy. from that way you can easily implement that project.

**Comment by ravitejapavuluri** [comment]
I too face the same issue Scrapy does not install using pip, it installs only from Anaconda. Please help

**Comment by Gallaecio** [comment]
For Windows users, https://github.com/scrapy/scrapy/issues/4715 may be worth checking out.

**Comment by Nyantahi** [comment]
> I too face the same issue Scrapy does not install using pip, it installs only from Anaconda. Please help

Hi, have you try to use pip3. I had problems with other repos with pip but pip3 worked like a charm

**Comment by Zenthae** [comment]
pip install is working using python `3.8.2` and pip `20.3.3` but i wasn't able to make it work using python `3.9.1`, i had to download Twisted myself then install it manually using the .whl file

**Comment by hariprasad0511** [comment]
My Environment that has a working Scrapy on pip command

- pip version = 20.3.1
- python version = 3.7
- Install command = `pip3 install scrapy` 

Common things to check for

- [ ] Check for the pip version and upgrade to the latest by running `pip install --upgrade pip`
- [ ] If `pip install` is not working then check with `pip3 install`

**Comment by 3xploiton3** [comment]
> My Environment that has a working Scrapy on pip command
> 
> * pip version = 20.3.1
> * python version = 3.7
> * Install command = `pip3 install scrapy`
> 
> Common things to check for
> 
> * [ ]  Check for the pip version and upgrade to the latest by running `pip install --upgrade pip`
> * [ ]  If `pip install` is not working then check with `pip3 install`


my version
pip            20.3.3
Python      3.9.0

`pip or pip3  install scrapy` doesn't work

**Comment by Zenthae** [comment]
i can't install scrapy using python 3.9+, it depends on Twisted which can't be installed using pip starting 3.9 because of deprecation issue, the only way to do it is to downgrade you're python version (can be done easily with pyenv) or to download and install Twisted manually

**Comment by 3xploiton3** [comment]
> you can't install scrapy using python 3.9+, it depends on Twisted which can't be installed using pip starting 3.9 because of deprecation issue, the only way to do it is to downgrade you're python version (can be done easily with pyenv) or to download and install Twisted manually

thx for the suggestion, my choice use conda to my environment, and work well

**Comment by hamzarana07** [comment]
> you can't install scrapy using python 3.9+, it depends on Twisted which can't be installed using pip starting 3.9 because of deprecation issue, the only way to do it is to downgrade you're python version (can be done easily with pyenv) or to download and install Twisted manually

Thanks Zenthae. Downgrading to version 3.7 from 3.9 did the job.
