### ISSUE TITLE
download middlewares don't work

### ISSUE THREAD

**Issue by Mactarvish** [scrapy/scrapy#3640]
Hi, I'm trying to set a proxy for my spider. Firstly I modified the settings.py in my work directory:
`
# Enable or disable downloader middlewares
# See https://doc.scrapy.org/en/latest/topics/downloader-middleware.html
DOWNLOADER_MIDDLEWARES = {
   'xici.middlewares.XiciDownloaderMiddleware': 543,
}
`
Then I modified the middlewares.py:
`
class XiciDownloaderMiddleware(object):
    # Not all methods need to be defined. If a method is not defined,
    # scrapy acts as if the downloader middleware does not modify the
    # passed objects.

    @classmethod
    def from_crawler(cls, crawler):
        # This method is used by Scrapy to create your spiders.
        s = cls()
        crawler.signals.connect(s.spider_opened, signal=signals.spider_opened)
        return s

    def process_request(self, request, spider):
        # Called for each request that goes through the downloader
        # middleware.
        request.meta['proxy'] = "http://116.209.56.19:9999"

        # Must either:
        # - return None: continue processing this request
        # - or return a Response object
        # - or return a Request object
        # - or raise IgnoreRequest: process_exception() methods of
        #   installed downloader middleware will be called
        return None

    def process_response(self, request, response, spider):
        # Called with the response returned from the downloader.

        # Must either;
        # - return a Response object
        # - return a Request object
        # - or raise IgnoreRequest
        return response

    def process_exception(self, request, exception, spider):
        # Called when a download handler or a process_request()
        # (from other downloader middleware) raises an exception.

        # Must either:
        # - return None: continue processing this exception
        # - return a Response object: stops process_exception() chain
        # - return a Request object: stops process_exception() chain
        pass

    def spider_opened(self, spider):
        spider.logger.info('Spider opened: %s' % spider.name)
`
But when the code executed the process_request was never executed. Is there anything I ignored? Thanks in advance!

**Comment by Mactarvish** [comment]
I've found that I used the Crawler Process to run spider conveniently in my PyCharm:
`process = CrawlerProcess({
    'USER_AGENT': 'Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1)'
})

process.crawl(xici_Spider)
process.start() `

If I drop these and just run in the cmd using `scrapy crawl xici` the problem will be solved, therefore I think it is the process that disabled the middlewares. So Is there anyway to not only running my spider in script but also enabling the middlewares?

**Comment by malberts** [comment]
In the example you are defining that middleware in `settings.py`. But you are not using those settings when you invoke the Crawler like that. You need to explicitly pass in that setting:

```
process = CrawlerProcess({
    'USER_AGENT': 'Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1)',
    'DOWNLOADER_MIDDLEWARES' = {
        'xici.middlewares.XiciDownloaderMiddleware': 543,
    }
})
```

or pass in all your settings using `get_project_settings()` as per https://doc.scrapy.org/en/latest/topics/practices.html.

**Comment by Mactarvish** [comment]
Thanks, it's been solved perfectly.
