### ISSUE TITLE
Contributing to Scrapy in GSoC 2019

### ISSUE THREAD

**Issue by maramsumanth** [scrapy/scrapy#3650]
Hello all,
My name is Maram Sumanth from IIT Roorkee, India. I have gone through the ideas of scrapy and I have found the project on ```Support for Different robots.txt Parsers``` to be particularly interesting.
I am curious to know about this project. Is this project based on creating many robots.txt parsers and their corresponding middlewares with API?  Also what does fully-compliant exactly mean ?
@lopuhin @whalebot-helmsman , can you please provide me the detailed explanation of this project, so that it I will start working on it ASAP.
I do have some open source experience and I would love to contribute to Scrapy and participate in GSoC 2019. :)
Thanks 👍

**Comment by whalebot-helmsman** [comment]
Created https://github.com/scrapy/scrapy/issues/3656
