### ISSUE TITLE
Docs contains a link to a non-existent page.

### ISSUE THREAD

**Issue by anubhavp28** [scrapy/scrapy#3661]
https://docs.scrapy.org/en/latest/topics/architecture.html has a link to blog post "Twisted - hello, asynchronous programming" ( http://jessenoller.com/2009/02/11/twisted-hello-asynchronous-programming/ ) which has been moved or taken offline by the author.

**Comment by anubhavp28** [comment]
Hey @Gallaecio, I found the page preserved at Internet Archieve ( https://web.archive.org/web/20180818150733/http://jessenoller.com/2009/02/11/twisted-hello-asynchronous-programming/ ). I am wondering, whether to remove the link or link it to this archived copy?

**Comment by Gallaecio** [comment]
The new URL should be http://jessenoller.com/blog/2009/02/11/twisted-hello-asynchronous-programming
