### ISSUE TITLE
Make it possible to update settings in `__init__` or `from_crawler`

### ISSUE THREAD

**Issue by ejulio** [scrapy/scrapy#3663]
This issue might be related to https://github.com/scrapy/scrapy/issues/1305

I noticed that `settings` are frozen in https://github.com/scrapy/scrapy/blob/master/scrapy/crawler.py#L57
However, in a given project I had a requirement to change some settings based on some spider arguments. An alternative would be to write this spider as a base class and extend it from specific spiders setting the proper `settings`.
However, I think it would make sense to only freeze settings after the spider and other components were initialized. Or, provide some other entry point to configure settings based on arguments.
The other option is to use `-s` arguments, but in my case I was changing the `FEED_EXPORT_FIELDS` setting (https://docs.scrapy.org/en/latest/topics/feed-exports.html#std:setting-FEED_EXPORT_FIELDS).

Any thoughts here?

**Comment by GeorgeA92** [comment]
usage of `-s` argument with list based `FEED_EXPORT_FIELDS` setting:
`scrapy crawl quotes -s FEED_EXPORT_FIELDS=author,quote -o data_without_tags.csv`

Option is to set list setting like `FEED_EXPORT_FIELDS `inside command is actual for all settings where BaseSettings.getlist method is used to read settings.: https://github.com/scrapy/scrapy/blob/b8594353d03be5574f51766c35566b713584302b/scrapy/settings/__init__.py#L161-L178


I noticed that `BaseSettings.freeze` method does only one thing: 
https://github.com/scrapy/scrapy/blob/b8594353d03be5574f51766c35566b713584302b/scrapy/settings/__init__.py#L352-L360

`frozen `attribute is used in `_assert_mutability `method which is actually prevents any changes to settings
https://github.com/scrapy/scrapy/blob/b8594353d03be5574f51766c35566b713584302b/scrapy/settings/__init__.py#L336-L338

But if we change `frozen `attribute to `False `settings will become mutable and application will able to change make changes to settings using methods where `_assert_mutability `called:
[`set `](https://github.com/scrapy/scrapy/blob/1.6.0/scrapy/settings/__init__.py#L240-L266), [`setmodule`](https://github.com/scrapy/scrapy/blob/1.6.0/scrapy/settings/__init__.py#L271-L291), [`update`](https://github.com/scrapy/scrapy/blob/1.6.0/scrapy/settings/__init__.py#L293-L324), [`delete`](https://github.com/scrapy/scrapy/blob/1.6.0/scrapy/settings/__init__.py#L326-L330), [`__delitem__`](https://github.com/scrapy/scrapy/blob/1.6.0/scrapy/settings/__init__.py#L332-L334)

Spider code with updating settings inside `from_crawler `will look like this:
```
class SomeSpider(scrapy.Spider):
......
    @classmethod
    def from_crawler(cls, crawler, *args, **kwargs):
        if(crawler.settings.frozen):
            crawler.settings.frozen = False
            rawler.settings.set("SETTING","NEW_VALUE")
            #crawler.settings.overrides.settings.set("SETTING","NEW_VALUE")
            crawler.settings.freeze()
        spider = cls(*args, **kwargs)
        spider._set_crawler(crawler)
        return spider
```

**Comment by ejulio** [comment]
@GeorgeA92 , thanks for your reply.
I agree that it is possible to use `-s`, but my main concern is that I'm writing a configuration of the fields _outside the spider_. By writing this setting in the code, it is side-by-side with my items, so less prone to errors. Also, when use `-s`, every time I start a job, I need to write the fields, so it could cause errors just because of writing the wrong field name. If there is no other way, this would be my preferred approach.

I also agree that your solutions for `from_crawler` works, but this way I'm hacking the framework.
This can also lead to unwanted behavior, and if something changes in the future, it might lead to code changes just because I was relying on some non-documented behavior.

My main reasoning here is to check if it is the scope of Scrapy to allow this kind of configuration or if this behavior (freeze the settings before the spider is created) is expected for some reason.

**Comment by diegovincent** [comment]
I am in a similar issue. I have to change the settings of a specific spider based on information read in a JSON file that is used as a configuration file for the Spider behaviour. Problem is, I have to change the setting according to the argument of the spider as well. Is there a better way to address this problem? I do not want to create a single spider for this case, more code to maintain = more problems.

**Comment by ejulio** [comment]
Hey, I was looking to work on this issue, but I got in a kind of deadlock :stuck_out_tongue: 
Looking for ideas:

The spider is instantiated here https://github.com/scrapy/scrapy/blob/master/scrapy/crawler.py#L84
However, I cannot freeze the settings only at this point because all other components were already instantiated.
So, that could cause some misunderstanding by updating a setting that is used in a middleware, but the middleware was already started.

I thought about moving the spider instantiation to https://github.com/scrapy/scrapy/blob/master/scrapy/crawler.py#L41 and make `update_settings` deprecate.
However, there I won't have access to the input arguments.
It would be possible if I change the runner to get arguments when it is instantiated and not when `crawl` is called.

**Comment by Gallaecio** [comment]
I’m quite unsure on how to best address this. Maybe we could allow defining a new class method on spiders that has access to both spider arguments and settings?

**Comment by ejulio** [comment]
@Gallaecio, probably this is the best way to go.
Add `cli_args` to `__init__` and use them in `update_settings`.
Just need to make sure it won't break backwards compatibility

**Comment by GeorgeA92** [comment]
> The spider is instantiated here https://github.com/scrapy/scrapy/blob/master/scrapy/crawler.py#L84
> However, I cannot freeze the settings only at this point because all other components were already instantiated.

As we can see in [crawler.py](https://github.com/scrapy/scrapy/blob/1.6.0/scrapy/crawler.py) after [`self.spidercls.update_settings(self.settings)`](https://github.com/scrapy/scrapy/blob/1.6.0/scrapy/crawler.py#L35) (method which reads [`custom_settings`](https://docs.scrapy.org/en/latest/topics/spiders.html#scrapy.spiders.Spider.custom_settings)spider class attribute) and before [spider instantiation](https://github.com/scrapy/scrapy/blob/1.6.0/scrapy/crawler.py#L79) -- StatsCollertor and ScrapyExtensions were instantiated. 

But the rest of scrapy modules (downloader,downloadermiddlewares,itempipelines,spidermiddlewares etc.) instatiate after spider in [`self.engine = self._create_engine()`](https://github.com/scrapy/scrapy/blob/1.6.0/scrapy/crawler.py#L80)

Some project related modules (Spiderloader, Logging...) instantiated before [`self.spidercls.update_settings(self.settings)`](https://github.com/scrapy/scrapy/blob/1.6.0/scrapy/crawler.py#L35) and it is unable to change it with spider [`custom_settings`](https://docs.scrapy.org/en/latest/topics/spiders.html#scrapy.spiders.Spider.custom_settings) attribute.

**Comment by joeharrison714** [comment]
I have a need to access modify settings based off a spider argument and I found this thread. Is there any new information about how this could be accomplished?

**Comment by GeorgeA92** [comment]
@joeharrison714 https://github.com/scrapy/scrapy/issues/4196

**Comment by rpocase** [comment]
A possible workaround for this use case, depending on your run model, is to override settings using `Crawler`. In my case, I'm executing via a scripted workflow and may need to override settings at run time. Since `CrawlerProcess.crawl` can take a `Crawler` object, it is pretty seamless to absorb the crawler settings and override the settings I care about.

```
def run_crawl(process: CrawlerProcess):
    s = copy.deepcopy(process.settings)
    s[''MY_SETTING"] = "overridden"
    c = Crawler(MySpider, settings=s)
    process.crawl(c)
    return process.join()
```

**Comment by Dhruv97Sharma** [comment]
One possible solution for this could also be creating a few class variables and using them in the `custom_settings` being passed to the spider and then update the values of these class variables in the `__init__` function of the spider, so when these custom settings are being applied, it will start using the updated values as passed from the `__init__`.

Example:

```
class NameOfYourSpider(scrapy.Spider):
    name = "spider_name"
    var1 = None

    custom_settings = {
        'ROBOTSTXT_OBEY' : var1 if var1 is not None else False,
    }

    # ... other class variables
    
    def __init__(self, obey_robotstxt):
        # This modifies the value of the class variable and also the custom value of the settings that one wanted to update
        self.var1 = True

```

**Comment by webee** [comment]
use `-s CONFIGS=/path/to/config/file` to specify `custom_settings` and other custom configurations.
```python
    @classmethod
    def update_settings(cls, settings):
        configs = {}
        configs_file = settings.get("CONFIGS")
        if configs_file:
            configs = data.load(configs_file)

        cls.custom_settings = cls.custom_settings or {}
        for k, v in configs.get("custom_settings", {}).items():
            cls.custom_settings[k] = v

        cls.custom_settings["CONFIGS"] = configs

        super().update_settings(settings)

    def __init__(self, name=None, **kwargs):
        super().__init__(name, **kwargs)

        self.configs = self.custom_settings["CONFIGS"]
```
then, settings can be set/override by `custom_settings` in config file and we can also refer `self.configs` in spider.
So that's it.
