### ISSUE TITLE
Move API docs to source code

### ISSUE THREAD

**Issue by anubhavp28** [scrapy/scrapy#3664]
I have noticed that few classes ( such as `Spider` class in https://github.com/scrapy/scrapy/blob/master/scrapy/spiders/__init__.py ) lacks docstring inside the source code. Instead, the documentation is provided in the project documentation files. If the developers and maintainers permit, I would like to work on moving the api docs to the source code. I will use `autodoc` to link it inside the project documentation files. I would love some suggestions on it, should I move ahead?

**Comment by Gallaecio** [comment]
Thanks. However, it has been already reported (#713) and there is already a pull request in that direction (#3612).
