### ISSUE TITLE
CONCURRENT_REQUESTS not being honoured

### ISSUE THREAD

**Issue by mohmad-null** [scrapy/scrapy#3693]
I'm seeing far too many connections being created for my spider.
I am only using ONE single crawler process.

These are the settings in the spider when it starts.

```
CONCURRENT_REQUESTS = 60
CONCURRENT_REQUESTS_PER_DOMAIN = 8
CONCURRENT_REQUESTS_PER_IP = 5
DOWNLOAD_DELAY = 0
DOWNLOAD_TIMEOUT = 300
RANDOMIZE_DOWNLOAD_DELAY = True
REACTOR_THREADPOOL_MAXSIZE = 40

AUTOTHROTTLE_ENABLED = True
AUTOTHROTTLE_START_DELAY = 1
AUTOTHROTTLE_MAX_DELAY = 6
AUTOTHROTTLE_TARGET_CONCURRENCY = 3
```

I then feed in a list of about 100,000 urls which are split between about 4000 different domains (probably as many IP addresses too) and inserted in a `random()` order.

What I'm seeing in Process Explorer (A Windows application) on the TCP/IP tab, is about 180 open connections, of which one IP address features about 70+ times(1), and two other IP addresses feature 20+ times.
On the off-chance that I was misreading/misunderstanding Process Explorer, I look at my software Firewall's open connections and it's showing the same numbers.

Scrapy 1.5.0

**Comment by mohmad-null** [comment]
Upgraded from Scrapy 1.5.0 (Twisted 17.9.0) to Scrapy 1.6.0 (Twisted 18.9.0). No change.

I've also tried lowering the numbers, but it has made no difference at all.
New lowered numbers (everything else as above)
```

CONCURRENT_REQUESTS = 30
CONCURRENT_REQUESTS_PER_IP = 2
AUTOTHROTTLE_TARGET_CONCURRENCY = 2
REACTOR_THREADPOOL_MAXSIZE = 20
```

**Comment by joseph-matthew** [comment]
Now I havent tested this, or used scrapy even, I was just browsing looking for something to do and noticed this. 

with that said, arent you supposed to use either or, AUTO_THROTTLE_WHATEVER or set hard limits with CONCURRENT_REQUESTS

https://docs.scrapy.org/en/latest/topics/autothrottle.html#how-it-works

if im wrong, just disregard

**Comment by joseph-matthew** [comment]
> Instead of adjusting the delays one can just set a small fixed download delay and impose hard limits on concurrency using CONCURRENT_REQUESTS_PER_DOMAIN or CONCURRENT_REQUESTS_PER_IP options. It will provide a similar effect, but there are some important differences:

From that I get that youre doing both. So you should either set delays, or use CONCURRENT_REQUESTS_*

**Comment by mohmad-null** [comment]
@joseph-matthew - Thanks for the reply. Sorry, I don't think I really understand your point.

There's a blue box on that page which says:
```
The AutoThrottle extension honours the standard Scrapy settings for concurrency and delay. This means that it will respect CONCURRENT_REQUESTS_PER_DOMAIN and CONCURRENT_REQUESTS_PER_IP options and never set a download delay lower than DOWNLOAD_DELAY.
```

So there should still not be more than 2-5 Requests per IP address, yet I'm seeing 15-70. That's the crux of this report.

**Comment by mohmad-null** [comment]
@joseph-matthew - now that I read that entire section of the docs again, I'm even more confused. Pertinent section:

> Instead of adjusting the delays one can just set a small fixed download delay and impose hard limits on concurrency using CONCURRENT_REQUESTS_PER_DOMAIN or CONCURRENT_REQUESTS_PER_IP options. It will provide a similar effect, but there are some important differences:
> * because the download delay is small there will be occasional bursts of requests;
> * often non-200 (error) responses can be returned faster than regular responses, so with a small download delay and a hard concurrency limit crawler will be sending requests to server faster when server starts to return errors. But this is an opposite of what crawler should do - in case of errors it makes more sense to slow down: these errors may be caused by the high request rate.
> 
> AutoThrottle doesn’t have these issues.

The pertinent line is the last one: **AutoThrottle doesn’t have these issues.** - so wait, is the above saying that you SHOULD do that or should NOT do that? If Autothrottle solves these problems then why they listed in such a way as to suggest they are created by using the autothrottle?

So confused.

**Comment by mohmad-null** [comment]
@joseph-matthew - For the sake of testing I changed my settings to do as that comment suggests:
```
RANDOMIZE_DOWNLOAD_DELAY = False
DOWNLOAD_DELAY = 1
```
No difference. I'm still seeing about 180 connections, with up to 10 or so to the same site.

**Comment by mohmad-null** [comment]
Oddly, today despite which of the above set of settings I use, I'm seeing something like 500 (five hundred) connections!!!!

**Comment by kmike** [comment]
Do you by chance use file uploads or other similar features?

**Comment by mohmad-null** [comment]
@kmike - Nope, no file uploading. All requests are GET requests.

**Comment by Vlad-Yekat** [comment]
I have a similar problem with my project.
As a solution, it helps to roll back to Scrapy== 1.4.0

**Comment by mohmad-null** [comment]
As an extension of @Vlad-Yekat comment - No proxy or proxy middleware here.

**Comment by GeorgeA92** [comment]
I think this is a misinterpretation of meaning `CONCURRENT_REQUESTS` setting and other concurrency related settings.

`CONCURRENT_REQUESTS` setting  defines maximun number of active requests in `Downloader`: 
https://github.com/scrapy/scrapy/blob/b8594353d03be5574f51766c35566b713584302b/scrapy/core/downloader/__init__.py#L84
https://github.com/scrapy/scrapy/blob/b8594353d03be5574f51766c35566b713584302b/scrapy/core/downloader/__init__.py#L101-L102

Request is "active" (in terms of `Downloader` source code) from the moment when it already reached `Downloader.fetch` method
up to `response_downloaded` signal (which is definitely BEFORE `parse` method called with response from this request):
https://github.com/scrapy/scrapy/blob/b8594353d03be5574f51766c35566b713584302b/scrapy/core/downloader/__init__.py#L92-L99

My observations of Windows Process Explorer indicates that each http connection stays open in around several seconds AFTER response received (which is not the same as "active" requests mentioned above). This behaviour mentioned in #2653 but it is also actual for http requests opened by webbrowsers.

**Comment by Gallaecio** [comment]
> RANDOMIZE_DOWNLOAD_DELAY = False
> DOWNLOAD_DELAY = 1

With this, and pointing all requests to the same domain, does the number of responses per time match expectations? That’s the goal of concurrency settings.

**Comment by mohmad-null** [comment]
@GeorgeA92 , @Gallecio
Nice ideas. So I've investigated a little further.

Scrapy 1.7.3
These settings:
```
'CONCURRENT_REQUESTS': 64,
'CONCURRENT_REQUESTS_PER_DOMAIN': 3,
'DNS_TIMEOUT': 120,
'DOWNLOAD_DELAY': 1,
'DOWNLOAD_TIMEOUT': 300,
'RANDOMIZE_DOWNLOAD_DELAY': False,
'REACTOR_THREADPOOL_MAXSIZE': 100,
'RETRY_TIMES': 3,
'SCHEDULER_PRIORITY_QUEUE': 'scrapy.pqueues.DownloaderAwarePriorityQueue'
```

Using a single crawler I'm seeing speeds of around 600 requests per minute, (so about 10 per second).
However Process Explorer is showing about 300 open connections!

So each request is on the Process Explorer page for about 30 seconds?

If I lower `CONCURRENT_REQUESTS = 8`, I now see about 100-130 open connections with a throughput of about 150 requests/min.

**Comment by Gallaecio** [comment]
Should we close this in favor of https://github.com/scrapy/scrapy/issues/2653?
