### ISSUE TITLE
When opening a documentation page, focus its table of contents on the side bar

### ISSUE THREAD

**Issue by Gallaecio** [scrapy/scrapy#3695]
When you open the Item Exporters page, the sidebar does not show its table of contents, and you need to scroll down the sidebar to see it.

I think our documentation should behave like the [Godot documentation](https://docs.godotengine.org/) does in the same scenario.

**Comment by Gallaecio** [comment]
I’ve just noticed that the master documentation behaves as expected, while the latest does not. I wonder if this is just something Read The Docs added that we will get upon rebuilding the documentation.

**Comment by anubhavp28** [comment]
@Gallaecio I have build the documentation locally, it works perfectly just like the Godot documentation.

**Comment by Gallaecio** [comment]
This is currently working.

**Comment by CreativeDemon** [comment]
Hey there!
Nice catch — the sidebar’s table of contents should focus when you open a specific docs page. Something like this might work:
```
document.querySelector('#sidebar')
  .querySelector(`[href="${window.location.pathname}"]`)
  .scrollIntoView({ behavior: 'smooth', block: 'start' });
```
This uses scrollIntoView to auto-scroll the TOC to the current page link.
