### ISSUE TITLE
Scrapy returns wrong datetime

### ISSUE THREAD

**Issue by Iliyass** [scrapy/scrapy#3699]
Hello guys,

as the title says, scrapy returns wrong datetime, I have run `scrapy shell` into my project and checked datetime there.
```
In [222]: from datetime import datetime
In [224]: datetime.now()
Out[224]: datetime.datetime(2019, 3, 22, 17, 55, 29, 265411)
```
and when I check the machine time, it returns the correct time
```
$ date
Fri Mar 22 18:55:30 CET 2019
```
and when I check python shell 
```
datetime.datetime(2019, 3, 22, 18, 57, 4, 58497)
```

as you can see the Scrapy datetime returns -1h

My Environment:
```
Scrapy 1.5.1
Python 2.7.6
Ubuntu 14.04.3 LTS, Trusty Tahr
```

**Comment by Gallaecio** [comment]
Scrapy returns the value in UTC. If you use `datetime.utcnow()` instead, you will get the same date as Scrapy.

This is because Scrapy assumes that the server and the people reviewing the logs are not necessarily on the same timezone, hence UTC serves as a *lingua franca* of timezones.

**Comment by Gallaecio** [comment]
@Iliyass Could you please confirm that the received date is the right UTC date, and close this issue if so?

**Comment by Iliyass** [comment]
@Gallaecio sorry for the delay, yes, I confirm, the date I get in Scrapy is in UTC.

Thanks.
