### ISSUE TITLE
why is process_request called twice?

### ISSUE THREAD

**Issue by stever123** [scrapy/scrapy#3700]
I have a downloader middleware that will do some stuff when its `process_request` is called. The problem is, for all my middlewares and some signals, that they are called twice. So for the exact same request (I even gave them a unique ID to be sure), `process_request` is called twice - why? The reason why I do not some code as an example is that it happens in all my projects, so I think it is more related to Scrapy in general. Note, it only happens with `SplashRequest`

**Comment by waydegg** [comment]
Did you ever solve this problem?

**Comment by Gallaecio** [comment]
One reason for it to *feel* like it is called twice is if you return a `Request` object on the first call, which causes that request to be added back to the scheduler, and reprocessed.

That is as expected, a new request needs to be reprocessed by all downloader middlewares.

In any case, @waydegg, consider using [StackOverflow](https://stackoverflow.com/tags/scrapy) to ask for help with your specific issue. See [Getting Help](https://docs.scrapy.org/en/latest/#getting-help). Just preparing a good question can often lead to understanding and solving the issue.
