### ISSUE TITLE
After scrapy crawl command sometimes scrapy hanging up/waiting 

### ISSUE THREAD

**Issue by sebascreen** [scrapy/scrapy#3702]
After command scrapy crawl job_name scrapy stack and nothing happend for ~1minute or more, after this time scrapy run spider job and everything is finished successfully. Issue appears after update scrapy to 1.6 version in 1.5.1 issue does't exists. Is anybody who observed similar issue?

**Comment by Gallaecio** [comment]
How many times have you tried? Does it happen every time? Could you share the logs?

**Comment by sebascreen** [comment]
Right now after long investigating I think that problem is caused by pip, I will update pip to latest version and let you know if it solve the issue or not

**Comment by sebascreen** [comment]
OK problem is solved after update pip to version 19.0.3. Right now everything seems to be working fine, issue closed. Thank you.
