### ISSUE TITLE
I install scrapy in my home directory

### ISSUE THREAD

**Issue by Firststep2014** [scrapy/scrapy#3705]
Hello, I have install scrapy in /home/u25654/scrapy
And also I have add path ,since I will get 
`/glob/intel-python/python3/bin/:/glob/development-tools/versions/intel-parallel-studio/compilers_and_libraries_2019.3.199/linux/bin/intel64:/glob/development-tools/versions/intel-parallel-studio/compilers_and_libraries_2019.3.199/linux/mpi/intel64/libfabric/bin:/glob/development-tools/versions/intel-parallel-studio/compilers_and_libraries_2019.3.199/linux/mpi/intel64/bin:/glob/intel-python/python3/bin/:/glob/intel-python/python2/bin/:/glob/development-tools/versions/intel-parallel-studio/compilers_and_libraries_2019.3.199/linux/bin/intel64:/glob/development-tools/versions/intel-parallel-studio/compilers_and_libraries_2019.3.199/linux/mpi/intel64/libfabric/bin:/glob/development-tools/versions/intel-parallel-studio/compilers_and_libraries_2019.3.199/linux/mpi/intel64/bin:/glob/intel-python/python3/bin/:/glob/intel-python/python2/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/home/u25654/.local/bin:/home/u25654/bin:/home/u25654/.local/bin:/home/u25654/bin:/usr/local/bin:/bin:/home/u25654/scapy/bin:/home/u25654/virtualenv/bin`
However, I get "Command 'scrapy' not found" when I run in the shell, while it perform well in Jupyter

**Comment by Gallaecio** [comment]
Have you followed the [installation guide](https://doc.scrapy.org/en/latest/intro/install.html)?

**Comment by Firststep2014** [comment]
@Gallaecio Solved, I was using Intel AI Cloud,while I do not have permission to install it in /usr/local/. finally, I used pip install --user scrapy and it worked according to user guide.

**Comment by Firststep2014** [comment]
This may be something wrong with the environment, however ,not sure
