### ISSUE TITLE
way to get text inside anchor tag in Crawlspider

### ISSUE THREAD

**Issue by suraj-deshmukh** [scrapy/scrapy#3711]
I have a crawlspider which crawls given site upto certain dept and download the pdfs on that site. Everything works fine but along with link of pdf, i also need text inside anchor tag. 

for eg:

    <a href='../some/pdf/url/pdfname.pdf'>Project Report</a>

consider this anchor tag, in callback i get response object and along with this object i need text inside that tag for eg 'Project Report'.
Is there any way to get this information along with the response object. i have gone through https://docs.scrapy.org/en/latest/topics/selectors.html link but it not something that i am looking for.

**Comment by elacuesta** [comment]
I believe this is the same question as https://stackoverflow.com/q/55450472/6946615. I just answered there, and given that it's technically possible to get the link text, I think this particular issue should be treated as a request for documentation.
