### ISSUE TITLE
How do I dynamically generate items

### ISSUE THREAD

**Issue by GaryLea** [scrapy/scrapy#3713]
I found a solution to this idea in the official document:

```
from scrapy.item import DictItem, Field

def create_item_class(class_name, field_list):
fields = {field_name: Field() for field_name in field_list}

return type(class_name, (DictItem,), {'fields': fields})
```

but i don't know how to use them

**Comment by Gallaecio** [comment]
Could you provide the URL where you found this documentation?

**Comment by GaryLea** [comment]
https://scrapy-chs.readthedocs.io/zh_CN/0.24/topics/practices.html

I found it in Common Practices

**Comment by Gallaecio** [comment]
The section was removed from the documentation of recent versions of Scrapy. It might have been because it is no longer possible or recommended, or because it moved somewhere else. I’ll have a look.

**Comment by GaryLea** [comment]
Thank you very much

**Comment by Gallaecio** [comment]
@GaryLea It was removed on purpose, because [since Scrapy 1.0 you can yield regular Python dictionaries](http://doc.scrapy.org/en/latest/news.html#support-for-returning-dictionaries-in-spiders).

**Comment by GaryLea** [comment]
@Gallaecio Thank you very much. I passed in item successfully, but I can't use itemloader anymore

**Comment by Gallaecio** [comment]
What’s you use case? Why do you use both dynamic items and an item loader?

**Comment by kmike** [comment]
hey! in modern Scrapy versions you can also just yield dicts, no need to generate items dynamically.  Also, StackOverflow.com is a better place for such questions (use tag "scrapy").
