### ISSUE TITLE
start_request yield Request faster than other

### ISSUE THREAD

**Issue by Gravellent** [scrapy/scrapy#3715]
I'm using a proxy vendor to crawl a website. The proxy vendor limits the number of requests you can send to the proxy servers per second (say 2 requests per second). In order the fulfill this requirement, I set a DOWNLOAD_DELAY to 0.5 in settings.py. However, in start_requests, if I use a list, the proxy server will return an error for sending too many requests, but after that, the other Requests yielded in the actual spider code never cause any issues. I'm wondering if the delay of Requests in start_requests() is different than the rest of Requests?

**Comment by Gallaecio** [comment]
Have you also limited concurrency to 1? See `CONCURRENT_*` [settings](https://docs.scrapy.org/en/latest/topics/settings.html).
