### ISSUE TITLE
    raise error.ReactorNotRestartable() ? why　this error ?  but : using : scrapy crawl finance is normal running  

### ISSUE THREAD

**Issue by uyplayer** [scrapy/scrapy#3720]
# 在脚本运行
print("在脚本运行")
process = CrawlerProcess(get_project_settings())
process.crawl(FinanceSpider)
process.start()

**Comment by uyplayer** [comment]
this code : print("在脚本运行")    why output 2 times ?

**Comment by uyplayer** [comment]
# 在脚本运行
process = CrawlerProcess(get_project_settings())
process.crawl(FinanceSpider)
print("开始运行")
process.start()
===================================
print("开始运行") outputs 2 times ;

**Comment by uyplayer** [comment]
when add: get_project_settings() for CrawlerProcess     outputs errro raise error.ReactorNotRestartable()

**Comment by Gallaecio** [comment]
Please, use [StackOverflow](https://stackoverflow.com/tags/scrapy) to ask this type of questions.
