### ISSUE TITLE
"Edit on Github" link gives 404 error from docs.scrapy.org documentation pages

### ISSUE THREAD

**Issue by float13** [scrapy/scrapy#3721]
For example, from this doc page: https://docs.scrapy.org/en/latest/topics/exporters.html

clicking the "Edit on Github" link in the upper-right corner leads to a 404 error page (tested in Firefox and Safari):
https://github.com/scrapy/scrapy/blob/origin/1.6/docs/topics/exporters.rst

This has happened on every doc page I tried the link from.

I would like to help with some small grammatical edits in the docs (I'm new to Scrapy so I wouldn't make any technical edits). Would a pull request be appropriate for this type of doc edit? 

Also, specifying which files certain code snippets belong in would be very helpful for beginners.

**Comment by Gallaecio** [comment]
> Would a pull request be appropriate for this type of doc edit?
Yes.

**Comment by assignment6** [comment]
Apologies for newbie question.
The 404 error seems to appear only when the url points to https://docs.scrapy.org/en/**latest**/topics/exporters.html.  If I change it to https://docs.scrapy.org/en/1.6/topics/exporters.html, I am taken to the github site with no problem.

My question:  Is this a problem with the "Read The Docs" versioning issue?  How would one go about fixing this?  Thanks

**Comment by Gallaecio** [comment]
I think this might require editing settings on Read the Docs, in which case only some core developers will be able to look at it.

**Comment by Gallaecio** [comment]
This is now working. I did not fix it myself, someone else must have.
