### ISSUE TITLE
Support pathlib.Path in FEED_URI

### ISSUE THREAD

**Issue by Gallaecio** [scrapy/scrapy#3731]
Make things work the same when the value assigned to the `FEED_URI` setting is a string containing a path or an instance of `pathlib.Path`.

**Comment by melwell89** [comment]
Hi @Gallaecio, I'm interested in picking this one up. Do you have a bit more of a description of what is required?

**Comment by adsbhatial** [comment]
You want to use pathlib.Path instead of os.path thus replacing 
if path and not os.path.isdir(path):
to 
if path and not pathlib.Path.is_dir(path)
and places like these. These changes will mostly be in feedexport.py .
You mean to replace os.path with pathlib.Paths.
Is my understanding of the issue correct?

**Comment by Gallaecio** [comment]
I’ve updated the description. It may be as simple as type-casting the setting to a string before using it internally.

**Comment by adsbhatial** [comment]
Ok. I understand now.

@Gallaecio. Is it Ok for me to work on this?

**Comment by Gallaecio** [comment]
Yes :)

You don’t have to ask for permission, just open a pull request and mention this issue on it.

**Comment by apalala** [comment]
Please take a look at the [PathLike](https://docs.python.org/3/library/os.html#os.PathLike) interface, which was added in 3.6 to deal with precisely these issues.

**Comment by sushanth1999** [comment]
I came across the Scrapy project on GitHub, which seemed quite interesting, and therefore I'm willing to contribute in the project. Can you help which issues i should start searching for as a beginner
.
