### ISSUE TITLE
Name parameters uniformly (Cache Policy API)

### ISSUE THREAD

**Issue by anubhavp28** [scrapy/scrapy#3734]
https://github.com/scrapy/scrapy/blob/92801850546121f2faf95fd21c923904fde35c28/scrapy/extensions/httpcache.py#L34

It will look better if we name the second parameter as `cachedresponse` (in place of just `response`).

In fact, implementation of policy for RFC2616 compliant HTTP cache names it correctly.
https://github.com/scrapy/scrapy/blob/92801850546121f2faf95fd21c923904fde35c28/scrapy/extensions/httpcache.py#L101

I am sending a pull request for the same.

**Comment by Gallaecio** [comment]
@anubhavp28 I don’t think it is necessary for you to open an issue for something when you plan to send a pull request right away. Feel free to open your pull requests directly without opening an issue first :)
