### ISSUE TITLE
Scrapy killed for some unkonwn reasons

### ISSUE THREAD

**Issue by Firststep2014** [scrapy/scrapy#3746]
Hello,I've got stuck in dealling with the issue that scrapy killed sometime ,and I've used such codes so as to track any contional result,however it seems all right .
`        pid = os.getpid()
        p = psutil.Process(pid)
        print('Process name : ', p.name())
        print('cpu_times : ' , p.cpu_times())
        print('Memory usage : ', p.memory_percent())
        print('Process number of threads : s', p.num_threads())
`
and the results returned are listed below
`cpu_times :  pcputimes(user=1.72, system=0.19, children_user=0.0, children_system=0.01)
Memory usage :  0.0397387235557129
Process number of threads : s 2
Process name :  scrapy
cpu_times :  pcputimes(user=1.79, system=0.19, children_user=0.0, children_system=0.01)
Memory usage :  0.04000367534652104
Process number of threads : s 2
Process name :  scrapy
cpu_times :  pcputimes(user=20.48, system=0.6, children_user=0.0, children_system=0.01)
Memory usage :  0.072099247623883
Process number of threads : s 2
Process name :  scrapy
cpu_times :  pcputimes(user=20.53, system=0.61, children_user=0.0, children_system=0.01)
Memory usage :  0.07213969827896823
Process number of threads : s 2
Process name :  scrapy
cpu_times :  pcputimes(user=20.54, system=0.61, children_user=0.0, children_system=0.01)
Memory usage :  0.07214172081172249
Process number of threads : s 2
Process name :  scrapy
cpu_times :  pcputimes(user=20.56, system=0.62, children_user=0.0, children_system=0.01)
Memory usage :  0.07225902771146961
Process number of threads : s 2
Process name :  scrapy
cpu_times :  pcputimes(user=20.57, system=0.62, children_user=0.0, children_system=0.01)
Memory usage :  0.07278893129308589
Process number of threads : s 2
Process name :  scrapy
cpu_times :  pcputimes(user=20.69, system=0.62, children_user=0.0, children_system=0.01)
Memory usage :  0.07390334684068349
Process number of threads : s 2
Process name :  scrapy
cpu_times :  pcputimes(user=20.74, system=0.62, children_user=0.0, children_system=0.01)
Memory usage :  0.07499955959349276
Process number of threads : s 2
Killed
u25654@s001-n011:~/test_dir/quotesbot$
`
This seems nothing with memory leak, could you please give a hand?

**Comment by Firststep2014** [comment]
besides,i've set maximum concurrent requests to be, it did not work either 
CONCURRENT_REQUESTS = 4

**Comment by Gallaecio** [comment]
Have you tried monitoring the process from some system tool? It is technically possible for a memory issue to happen after your last print statement. See also https://docs.scrapy.org/en/latest/topics/leaks.html

Also, what kind of system are you using? How much free memory does it have?
