### ISSUE TITLE
Cannot find the spider

### ISSUE THREAD

**Issue by MarcSteven** [scrapy/scrapy#3757]
I used the framework to do something ,but when I executed the code ,it tell me the error:Cannot find the spider,I use venv 
The error as the link [cannot find the spider](https://stackoverflow.com/questions/18152473/scrapy-python-cannot-find-the-spiderl)
Hope can find a complete solution

**Comment by heylouiz** [comment]
Did you read [Steven's answer](https://stackoverflow.com/a/18174198/10683132)?

To run the spider with `scrapy crawl spider-name` you need to be inside the [scrapy project ](https://docs.scrapy.org/en/latest/intro/tutorial.html#creating-a-project) directory.

You can also run a single spider file using `scrapy runspider spiderfile.py`

**Comment by MarcSteven** [comment]
Yeah I had confirmed as you said, but it cannot run well ,so I don't know how to do

**Comment by Gallaecio** [comment]
Please, use [StackOverflow](https://stackoverflow.com/tags/scrapy) to ask this type of questions. See [Getting Help](https://docs.scrapy.org/en/latest/#getting-help).

**Comment by MarcSteven** [comment]
I asked

**Comment by Gallaecio** [comment]
Then, please vote up and follow that Stackoverflow question, or write a new question if that question does not cover your specific issue.
