### ISSUE TITLE
Items as Dataclasses

### ISSUE THREAD

**Issue by mredaelli** [scrapy/scrapy#3761]
Is there any plan to support dataclasses as `yield`-able results from crawlers (and possibly `meta` in `Request`/`Result`)?

It would be a very welcome addition for us, mostly for typing reasons, IDE completion, additional logic.
And it should also be simple to implement (just call `dataclasses.asdict()`)?

**Comment by gsb-eng** [comment]
@Gallaecio I would like to implement this, any discussion required before proceeding further?

**Comment by Gallaecio** [comment]
@gsb-eng I think you can go ahead.

**Comment by kmike** [comment]
+1 to add dataclasses and attrs support (in separate pull requests), I think it'd be awesome to have support for them.

**Comment by kmike** [comment]
https://github.com/scrapy/scrapy/pull/2807 is related, though not the same.
