### ISSUE TITLE
Do you think about supporting Scrapy cheatsheet

### ISSUE THREAD

**Issue by MarcSteven** [scrapy/scrapy#3765]
I think if you can support cheatsheet on Dash ,that's cool ,so do you plan to support it

**Comment by Gallaecio** [comment]
Could you elaborate a bit?

**Comment by MarcSteven** [comment]
@Gallaecio  If I have a bit time ,I will do it and then I will let more developers use it well .

**Comment by Gallaecio** [comment]
I mean that I am not sure what you are suggesting here. Specifically, I have no idea what ‘cheatsheet on Dash’ means or how it relates to Scrapy.

**Comment by MarcSteven** [comment]
I mean if you have cheapest ,I can use the dash to review the doc here ,so that's why I opened this issue !

**Comment by MarcSteven** [comment]
I will open it and then do it better !I tried my best to accomplish the documentation

**Comment by Gallaecio** [comment]
Oh, you are talking about https://kapeli.com/dash

**Comment by MarcSteven** [comment]
Yeah  @Gallaecio I mean it ,but in the doc you must write some feature for instance advanced usage.I know you are right.Hope it can extend its feature .

**Comment by MarcSteven** [comment]
Yeah  @Gallaecio I mean it ,but in the doc you must write some feature for instance advanced usage.I know you are right.Hope it can extend its feature .

**Comment by MarcSteven** [comment]
@Gallaecio  So do U have a plan to make it happen?

**Comment by Gallaecio** [comment]
I must say this tickets is not among my current priorities, sorry.

**Comment by MarcSteven** [comment]
Okay
