### ISSUE TITLE
CookiesMiddleware distinguish between response and request merge cookies

### ISSUE THREAD

**Issue by tomstelk** [scrapy/scrapy#3769]
dont_merge_cookies setting applies to merging both previous request's cookies and the response's Set-Cookie.

Would be useful to have a separate setting so that you can persist the previous request's Cookies, but ignore the response's Set-Cookies.

Something like:
dont_merge_request_cookies
dont_merge_response_cookies

**Comment by Gallaecio** [comment]
Related: #1387 2124

**Comment by Gallaecio** [comment]
Closing in favor of https://github.com/scrapy/scrapy/issues/2124 as it was reported much earlier and has a debate, but I think the solution is indeed the one proposed here, i.e. to provide separate meta keys for disabling cookie sending and cookie parsing.
