### ISSUE TITLE
CONCURRENT_REQUESTS_PER_* per XXX (multiple queues)

### ISSUE THREAD

**Issue by ddofborg** [scrapy/scrapy#3773]
The `CONCURRENT_REQUESTS_PER_IP` or `CONCURRENT_REQUESTS_PER_DOMAIN` options are not always useful. For example when you use 10 proxy servers, you would want to set this up per proxy.

I would suggest adding `CONCURRENT_REQUESTS_PER_QUEUE_NAME`. For each request you should be able to set a `queue` name, basically it's a hashable type in which each request can be put. This way you could manually group items for concurrency.

If there is a workaround for the proxy problem, I would like to hear it :)

**Comment by Gallaecio** [comment]
I think this only makes sense for proxy rotation, and proxy rotation Scrapy extensions like https://github.com/TeamHG-Memex/scrapy-rotating-proxies should already handle this on their own, and they can do it with the current Scrapy API, they do not need the suggested feature to make it possible.

**Comment by ddofborg** [comment]
Does this work in combination with Splash too?some how that didn’t work for
me and I ended up setting procies via Splash.

**Comment by Gallaecio** [comment]
Well, if it does not, maybe that is a feature request worth adding to https://github.com/TeamHG-Memex/scrapy-rotating-proxies
