### ISSUE TITLE
twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup:

### ISSUE THREAD

**Issue by littleningmeng** [scrapy/scrapy#3776]
Refer to the tile.
Why this error occured ? It's ok on my windows 10 with the same code, but on Linux, this error occured!

**Comment by Gallaecio** [comment]
What’s the URL?

**Comment by Gallaecio** [comment]
Closing due to a lack of feedback.

**Comment by chotosite** [comment]
I also get the same error on the url : https://basis.org.bd/get-company-profile/A449

**Comment by Gallaecio** [comment]
`scrapy fetch https://basis.org.bd/get-company-profile/A449` works for me.
