### ISSUE TITLE
scrapy.Item hashes equality

### ISSUE THREAD

**Issue by ronek22** [scrapy/scrapy#3782]
Hi,
I want to use scrapy.Items in my scraper, but I ran into some trouble.
I created two items with the same data inside each of them. 
Is it possible to override `__hash__` and `__eq__` method for Link class below?

Code for reproduce issue:
```python
import scrapy

class Link(scrapy.Item):
    link = scrapy.Field()
    domain = scrapy.Field()

all_links = set()

href = "https://google.com"
link1 = Link(link=href, domain=href)
link2 = Link(link=href, domain=href)
print(link1 == link2) # print True

all_links.add(link1)
all_links.add(link2)
print(len(all_links)) # should be 1, but 2 was printed out
```

**Comment by grammy-jiang** [comment]
Hi, @ronek22 

Yes, you can overwrite both methods in your class:

```python
import scrapy

class Link(scrapy.Item):
    link = scrapy.Field()
    domain = scrapy.Field()

    def __hash__(self):
        ...

    def __eq__(self):
        ...
````

When you try to compare object in Python, please read the manual carefully:
[3. Data model — Python 3.7.3 documentation](https://docs.python.org/3/reference/datamodel.html#object.__hash__)
