### ISSUE TITLE
When running scrapy crawl xxxspider, it is ABCspider.

### ISSUE THREAD

**Issue by kjxy** [scrapy/scrapy#3783]
When running scrapy crawl xxxspider, it starts ABCspider and throws an exception. I fixed the exception (caused by fake_useragent, it will be fine after uninstalling it)

Now there is a new "error". When running xxx spider, the printout is the custom_settings information of ABC spider.

![image](https://user-images.githubusercontent.com/35479340/57993518-e33f7200-7aeb-11e9-9840-987155ec13d6.png)

From the picture, the sohuAppSpider is running, but the custom_settings information is the custom_settings of weixinxxxspider.

Python 3.6 windows 7 scrapy 1.5.1

**Comment by grammy-jiang** [comment]
Hi, @kjxy 

I can't help you with your very limited information.

When you run `scrapy crawl <spider name>`, scrapy will try to find the spider from `scrapy.cfg` to `settings.py`, please make sure your settings and spiders are clearly defined in these configuration files.

And there are also other ways to run your spiders, please refer to [Common Practices — Scrapy 1.6.0 documentation](https://docs.scrapy.org/en/latest/topics/practices.html)

**Comment by Gallaecio** [comment]
Please, use [StackOverflow](https://stackoverflow.com/tags/scrapy) to ask this type of questions. See [Getting Help](https://docs.scrapy.org/en/latest/#getting-help).
