### ISSUE TITLE
scrapy didn't work on aws lambda

### ISSUE THREAD

**Issue by xuleijian** [scrapy/scrapy#3784]
I use thest codes below. But it didn't work with no error.

def lambda_handler(event, context):
    configure_logging({'LOG_FORMAT': '%(levelname)s: %(message)s'})
    runner = CrawlerRunner()

    d = runner.crawl(LoginSpider)
    d.addBoth(lambda _: reactor.stop())
    reactor.run()
-----------------------------------------------------------------
lambda log:
02:55:25 2019-05-20 02:55:25 [scrapy.core.engine] INFO: Spider opened
02:55:28 +END RequestId: b3c28ec2-e8e4-4383-a61d-7a321e4ee528
-----------------------------------------------------------------
Who knows the reason? Please help me.Thank you !

**Comment by grammy-jiang** [comment]
Hi, @xuleijian 

Interesting question! After I google your question, I find there is some findings:

https://stackoverflow.com/questions/28514086/issue-on-running-twisted-on-aws

Hope this helps.

**Comment by xuleijian** [comment]
@grammy-jiang 
Thank you for your reply.But I can import the module successful.
The url doesn't help me.

**Comment by Gallaecio** [comment]
Please, use [StackOverflow](https://stackoverflow.com/tags/scrapy) to ask this type of questions. See [Getting Help](https://docs.scrapy.org/en/latest/#getting-help).
