### ISSUE TITLE
Visual C++ Build Tool needed

### ISSUE THREAD

**Issue by vRivier** [scrapy/scrapy#3785]
Got this error while pip installing scrapy on windows:
error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

I had to install the software and then it worked. The installation took about 20min so I would recommand to try another way.

**Comment by Gallaecio** [comment]
Please, follow the instructions on the [installation guide](https://doc.scrapy.org/en/latest/intro/install.html).
