### ISSUE TITLE
Issues need opened cleen up

### ISSUE THREAD

**Issue by insspb** [scrapy/scrapy#3787]
I just wanted to check what issues and their direction are really actual now, but I found tons of issues not closed. 

They are already answered with "Please, ask your question through StackOverflow." from @Gallaecio or other contributors, but still not closed. This is a real-time loss if somebody just browsing to search interesting topic for self-checking/debugging/fixing. Maybe such persons just do not have additional issues moderation rights? 

I expect the same thing in PRs.

**Comment by noviluni** [comment]
Agree with that. Too much issues to know what can be addressed

**Comment by kmike** [comment]
Thanks @insspb! As a part of a cleanup, I'm closing this one :trollface:
