### ISSUE TITLE
How to download files (pdf) from a server what listen only PHP request?

### ISSUE THREAD

**Issue by anibal-aguila** [scrapy/scrapy#3788]
Hi everyone! I'm new here and want to know if scrapy can get multiples PDF from a site what resolve every request with PHP, the URL where I can get each file is: 

`http://extranet.domain.com/?p=downloads&did=1`

The files are referenced whit numbers, in this case, the URL get the file with the id 1, I have 3800 files for downloads... 
Hope someone knows how to solve my issue, thanks in advance.

And for the login request I use something like this..

```
from scrapy.http import FormRequest
request=FormRequest(url='http://extranet.domain.com/index.php',formdata={'username': 'theUserName','password':'thePassword',})
```

**Comment by Gallaecio** [comment]
Closing in favor of the [corresponding StackOverflow question](https://stackoverflow.com/questions/56263584/how-to-download-files-pdf-from-a-server-what-listen-only-php-request).
