### ISSUE TITLE
I want to run multiple spiders in multiple threads, and spiders have two different parameters, 'LOG_FILE' and one that I set myself

### ISSUE THREAD

**Issue by luoqishuai** [scrapy/scrapy#3801]
I used to have a spider, but the key parameters in setting are different. At that time, I copied and pasted 30 copies one by one, and then used docker to start the crawl one by one.
Now I want to use a python program to run 30 spiders in a row, using 30 threads, each spider with a different Settings, and everything else is the same.
At first, I tried to build a thread pool, but python told me builtins.valueerror: signal only works in main thread.
Then I start the way of using https://doc.scrapy.org/en/latest/topics/practices.html#running-multiple-spiders-in-the-same-process, because each spiders will require different Settings, so there is no success
How can you implement this kind of train of thought please?
Did I have to copy the code one by one and run the shell commands to boot it up one by one?
It's stupid, but that's all I can think of.
I would appreciate it if you could help me. If my description is not very clear, please let me know.

def task(i):
    # settings=get_project_settings()
    # settings.update({'IDQUEUE_MOD':i,'LOG_FILE' : "scrapy_spider_{}.log".format(i)})
    # runner = CrawlerRunner(settings)
    # runner.crawl(SpiderSpider)
    # reactor.run(installSignalHandlers=False)
    cmdline.execute('scrapy crawl spider -s IDQUEUE_MOD={} -s LOG_FILE=scrapy_spider_{}.log'.format(i,i).split())
    return 1

settings = get_project_settings()
queuesize = settings.getint('IDQUEUE_SIZE')  # 队列大小  代表起几个爬虫
pool=ThreadPoolExecutor(queuesize)
name_list=['name_{}'.format(i) for i in range(queuesize)]
for i in range(queuesize):
    name_list[i]=pool.submit(task,i)
b=[i.result() for i in name_list]
print(b)

**Comment by luoqishuai** [comment]
I used to use 'nohup python3 main.py & 
nohup python3 main.py &
nohup python3 main.py &
......'
Now I how to use python code to finish it .

**Comment by luoqishuai** [comment]
IF i change settings.py to make them same.Then i can use CrawlerRunner to run scrapy? But log  must different.

**Comment by grammy-jiang** [comment]
Hi, @luoqishuai 

Keep following [this suggestion](https://docs.scrapy.org/en/latest/topics/practices.html#running-multiple-spiders-in-the-same-process), and read ["custom_settings"](https://docs.scrapy.org/en/latest/topics/spiders.html#scrapy.spiders.Spider.custom_settings) property in Spider to specify each spider's settings.

Btw, if the logs are so important to you, Sentry is a good choice and allows to add more metadata to the log messages, which may be helpful to differentiate the messages.

**Comment by luoqishuai** [comment]
@grammy-jiang 
I try to user custom_setting to change log_file.
I use this code to run scrapy :
    runner = CrawlerRunner()
    for i in range(10):
        runner.crawl(SpiderSpider,mod=i)
    d = runner.join()
    d.addBoth(lambda _: reactor.stop())
    reactor.run()
my scrapy code:
     def __init__(self,mod):
        self.mod =mod
    custom_settings = {'LOG_FILE': '"scrapy_spider_{}.log"'.format(random.randint(0,100))}
It is false.
I run it .But no log generation.

**Comment by luoqishuai** [comment]
额,我真的是快要疯了.....不知道为什么使用CrawlerRunner 无法成功,我真是太笨了

**Comment by Gallaecio** [comment]
Please, use [StackOverflow](https://stackoverflow.com/tags/scrapy) to ask this type of questions. See [Getting Help](https://docs.scrapy.org/en/latest/#getting-help).

**Comment by luoqishuai** [comment]
@Gallaecio  What if the scrpay.request has a parameter of -6146417663 as opposed to -6146417701? Who gets popped first

**Comment by luoqishuai** [comment]
I found your code. pqueue will pop min(-priority ) .It means -6146417663 will pop first.
But in my log. It is not.

> 2019-05-31 14:19:42 [root] INFO: nowid:6146427363 ,next id :6146427463,priority:-6146427363;
> 2019-05-31 14:19:42 [root] INFO: nowid<maxid retry 0 times,nowurl: https://tieba.baidu.com/p/6146427363 
> 2019-05-31 14:19:42 [root] INFO: minid:6146426702,maxid:6146427451
> 2019-05-31 14:19:42 [root] INFO: nowid:6146427287 ,next id :6146427387,priority:-6146427287;
> 2019-05-31 14:19:42 [root] INFO: nowid<maxid retry 0 times,nowurl: https://tieba.baidu.com/p/6146427287 
> 2019-05-31 14:19:42 [root] INFO: minid:6146426702,maxid:6146427451
> 2019-05-31 14:19:42 [root] INFO: nowid:6146427446 ,next id :6146427546,priority:-6146427446;
> 2019-05-31 14:19:42 [root] INFO: nowid<maxid retry 0 times,nowurl: https://tieba.baidu.com/p/6146427446 
> 2019-05-31 14:19:42 [root] INFO: minid:6146426702,maxid:6146427451
> 2019-05-31 14:19:42 [root] INFO: nowid:6146427173 ,next id :6146427273,priority:-6146427173;
> 2019-05-31 14:19:42 [root] INFO: nowid<maxid retry 0 times,nowurl: https://tieba.baidu.com/p/6146427173 
> 2019-05-31 14:19:42 [root] INFO: minid:6146426702,maxid:6146427451
> 2019-05-31 14:19:42 [root] INFO: nowid:6146427408 ,next id :6146427508,priority:-6146427408;
> 2019-05-31 14:19:42 [root] INFO: nowid<maxid retry 0 times,nowurl: https://tieba.baidu.com/p/6146427408 
> 2019-05-31 14:19:42 [root] INFO: minid:6146426702,maxid:6146427451
> 2019-05-31 14:19:42 [root] INFO: nowid:6146427331 ,next id :6146427431,priority:-6146427331;
> 2019-05-31 14:19:42 [root] INFO: nowid<maxid retry 0 times,nowurl: https://tieba.baidu.com/p/6146427331 
> 2019-05-31 14:19:42 [root] INFO: minid:6146426702,maxid:6146427451
> 2019-05-31 14:19:42 [root] INFO: nowid:6146427213 ,next id :6146427313,priority:-6146427213;
> 2019-05-31 14:19:42 [root] INFO: nowid<maxid retry 0 times,nowurl: https://tieba.baidu.com/p/6146427213 
> 2019-05-31 14:19:42 [root] INFO: minid:6146426702,maxid:6146427451
> 2019-05-31 14:19:42 [root] INFO: nowid:6146427362 ,next id :6146427462,priority:-6146427362;
> 2019-05-31 14:19:42 [root] INFO: nowid<maxid retry 0 times,nowurl: https://tieba.baidu.com/p/6146427362 
> 2019-05-31 14:19:42 [root] INFO: minid:6146426702,maxid:6146427451
> 2019-05-31 14:19:42 [root] INFO: nowid:6146427500 ,next id :6146427600,priority:-6146427500;
> 2019-05-31 14:19:42 [root] INFO: nowid>maxid retry 1 times,request nowurl: https://tieba.baidu.com/p/6146427500
> 2019-05-31 14:19:42 [root] INFO: nowid:6146427333 ,next id :6146427433,priority:-6146427333;
> 2019-05-31 14:19:42 [root] INFO: nowid<maxid retry 0 times,nowurl: https://tieba.baidu.com/p/6146427333

**Comment by grammy-jiang** [comment]
Hi, @luoqishuai 

Sorry, Scrapy initializes logger in **Singleton Pattern** mode, which means one logger for Scrapy globally.

So I suggest you use Sentry with meta data.
