### ISSUE TITLE
ImportError: No module named _util 

### ISSUE THREAD

**Issue by merrisco** [scrapy/scrapy#3803]
Following the tutorial, I found an error when I run the command: scrapy crawl spider 
and get the error message: 
                    pyOpenSSLlib ImportError: No module named _util

It seems to me that the pyOpenSSL was not updated. I have looked around and found some others who have had a similar problem: https://stackoverflow.com/questions/50324329/running-scrapy-but-it-error-no-module-named-util

The solution seems to be to upgrade pyOpenSSL, but if this is a regular issues (one that is usually encountered during tutorial) might it be a good idea to add a note on the webpage. 

Scrapy       : 1.6.0
lxml         : 3.2.1.0
libxml2      : 2.9.1
cssselect    : 1.0.3
parsel       : 1.5.1
w3lib        : 1.20.0
Twisted      : 19.2.0
Python       : 2.7.5 (default, Jul 13 2018, 13:06:57) - [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
pyOpenSSL    : 19.0.0 (OpenSSL 1.1.1c  28 May 2019)
cryptography : 2.7
Platform     : Linux-3.10.0-862.14.4.el7.x86_64-x86_64-with-centos-7.5.1804-Core

**Comment by kishan3** [comment]
Hi @merrisco! 
Can you please help understand weather pyOpenSSL was installed by following below installation instructions?
https://docs.scrapy.org/en/latest/intro/install.html
