### ISSUE TITLE
Tutorial: scrapy shell example should say "text" not "title"

### ISSUE THREAD

**Issue by kiwisquash** [scrapy/scrapy#3807]
The text currently says:

> Now, let’s extract `title`, author and the tags from that quote using the quote object we just created:
> \>>> title = quote.css("span.text::text").get()
> \>>>title
> '“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”'

The`title` should be changed to `text`. In fact, if you scroll down slightly down in the for-loop, `text` is used instead of `title`. 

https://docs.scrapy.org/en/1.6/intro/tutorial.html#extracting-quotes-and-authors

**Comment by cs464osu** [comment]
Should this issue be closed now?

**Comment by kiwisquash** [comment]
Yes, this can be closed.
