### ISSUE TITLE
Scrapy does not allow using active mode in FTPFeedStorage

### ISSUE THREAD

**Issue by heylouiz** [scrapy/scrapy#3828]
It is not possible to export feeds to a FTP server configured in active mode with FTPFeedStorage.
Scrapy use ftplib and it [uses passive mode by default](https://docs.python.org/3/library/ftplib.html#ftplib.FTP.set_pasv), there is no way to configure this in Scrapy, there is a [setting](https://docs.scrapy.org/en/latest/topics/settings.html#ftp-passive-mode) to enable active mode (or disable passive mode) in the downloader, so I think it would be a good idea to have this option in the feed exporter too.

**Comment by heylouiz** [comment]
I opened a PR to fix this: #3829

**Comment by kmike** [comment]
Fixed by https://github.com/scrapy/scrapy/pull/3829
