### ISSUE TITLE
Scrapy with peer 2 peer search engine

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [scrapy/scrapy#3830]
Does Scrapy data can be used with a p2p search engine? if yes any good open source p2p search engine? thanks

**Comment by grammy-jiang** [comment]
Hi, @ROBERT-MCDOWELL 

Interesting question, but I don't get your point. Would you please make it more specific?

**Comment by ROBERT-MCDOWELL** [comment]
I would like to use a web crawler like Scrapy to get the websites keywords and so on with a search engine,
and use it with a full mesh p2p search engine that will allow each user to connect to a ring and get this data locally and share it itself as a node. but for now I didn't find any web based search engine p2p project, I mean a serverless web application doing that.

**Comment by Gallaecio** [comment]
Please, use [StackOverflow](https://stackoverflow.com/tags/scrapy) to ask this type of questions. See [Getting Help](https://docs.scrapy.org/en/latest/#getting-help).
