### ISSUE TITLE
remove_namespaces method is very slow

### ISSUE THREAD

**Issue by floggle** [scrapy/scrapy#3832]
The `remove_namespaces` method of the response selector is really *really* slow.
I'd suggest this should either be documented or optimised.

Examples:
* I was post-processing a bunch of XML files - using this function they took about 2-3 days. Without this function they took less than 20 minutes!

* One of the files I was processing turned out to be a 2.7million line XML file(!). This was running for multiple hrs before I killed it (12?). Without going through that function it was done in about 30 seconds!

I'm still using selectors and xpaths, but now using the `*[local-name()=` function instead.

**Comment by OmarFarrag** [comment]
Since its implementation is within parsel, this means it can't be optimized, unless it is overrided, and a new implementation is provided, right?

**Comment by elacuesta** [comment]
I'm not familiar enough with this part of the code to suggest performance insights, but for the record, there are sections about this in both [Parsel](https://parsel.readthedocs.io/en/stable/usage.html#removing-namespaces) and [Scrapy](https://docs.scrapy.org/en/1.6/topics/selectors.html#removing-namespaces) docs:

> Removing namespaces requires to iterate and modify all nodes in the document, which is a reasonably expensive operation to perform by default for all documents

I believe the fact that those sections are also linked from the docs for the `Selector.remove_namespaces` method in both cases ([Parsel](https://parsel.readthedocs.io/en/stable/usage.html#parsel.selector.Selector.remove_namespaces), [Scrapy](https://docs.scrapy.org/en/1.6/topics/selectors.html#scrapy.selector.Selector.remove_namespaces)) should be enough to make sure everyone using this method is aware of its drawbacks, but of course comments or pull requests with documentation improvememts are always welcome.

Keep in mind that you can also pass namespace information when you perform queries over the Selectors: https://parsel.readthedocs.io/en/stable/usage.html#ad-hoc-namespaces-references

**Comment by elacuesta** [comment]
@floggle `Parsel 1.5.2` was just released, could you update and see if it helps in your case?

**Comment by elacuesta** [comment]
Most likely fixed by https://github.com/scrapy/parsel/pull/140. No feedback in more than a month, closing.
