### ISSUE TITLE
Provide a way to pass meta information to an Item

### ISSUE THREAD

**Issue by chaplin89** [scrapy/scrapy#3834]
Hi, 
I'm trying to use the `ImagesPipeline` but I'm not happy with its naming convention.
I've extended `ImagesPipeline `in order to provide an alternate `file_path` method, but now I'm stucked.

The request originate from an `Item` object and I want to save images using a meta-information that is available in the method that build this `Item`. 
I was not able to find a way to propagate this information to the request that arrives in the `file_path` method. Is there a way to do this?

Thanks!

**Comment by chaplin89** [comment]
Update:
I've found a way to embed some meta-info inside the item and propagate them to `file_path `redefining `get_media_requests`:
```python
    def get_media_requests(self, item, info):
        requests = []
        for x in item.get(self.images_urls_field, []):
            request = Request(x)
            request.meta['barcode'] = item.get('barcode')
            requests.append(request)
        return requests
```

I'm still wondering if exist a better way.

**Comment by Gallaecio** [comment]
I think your way is OK. In any case, please use [StackOverflow](https://stackoverflow.com/tags/scrapy) to ask this type of questions. See [Getting Help](https://docs.scrapy.org/en/latest/#getting-help).
