### ISSUE TITLE
Understanding scrapy engine

### ISSUE THREAD

**Issue by amirduran** [scrapy/scrapy#3839]
This is question to understand deeper scrapy engine. On my server I can run multiple scrapy processes in parallel (we can start it by using scrapy API or just starting two scrapy instances in command line). That sounds good, but let's refer to the following scrapy architecture photo: 

![Scrappy arhcitecture](https://docs.scrapy.org/en/latest/_images/scrapy_architecture_02.png)

As far as I can understand, every scrapy process (in my case 2 processes) will have its own engine, scheduler, downloader etc. There is option to instruct/configure scrapy process to perform multiple crawls in parallel. This means if I instruct every process to run 50 requests in parallel my server will do 100 requests in parallel (because I have 2 processes running). What is the best way to instruct scrapy to run parallel crawls? Should I define all URLs in start URLs and then scrapy's scheduler will schedule crawling automatically for me or there is another way?

Also, if I have a mixture of 2 domains in my start urls attribute: 20 URLS belonging domain A and 50 URLs belonging domain B and if I configure scrapy that maximum 10 request in parallel should be performed on domain A and 5 on domain B, is scrapy's scheduler going to recognise this? Is there also way to say, if there are X different domains available in start URLs please always send max 10 requests in parallel for each of X domains?

Thx for answering my questions.

**Comment by GeorgeA92** [comment]
According to [scrapy docs (Broad Crawls section) ](https://docs.scrapy.org/en/latest/topics/broad-crawls.html#increase-concurrency):
> Concurrency is the number of requests that are processed in parallel. There is a global limit and a per-domain limit. 

**X different domains:**

> Is there also way to say, if there are X different domains available in start URLs please always send max 10 requests in parallel for each of X domains?

Yes. It is possible with `CONCURRENT_REQUESTS` and `CONCURRENT_REQUESTS_PER_DOMAIN` settings.

    import scrapy
    
    X = 10
    class SomeSpider(scrapy.Spider):
        CUSTOM_SETTINGS = {
        "CONCURRENT_REQUESTS_PER_DOMAIN":10, #The maximum number of concurrent (ie. simultaneous) requests that will be performed to any single domain.
        
        "CONCURRENT_REQUESTS": X*10 #The maximum number of concurrent (ie. simultaneous) requests that will be performed by the Scrapy downloader.
        }
    .....

**Comment by amirduran** [comment]
@GeorgeA92 thank you for answering some questions. 
Is there a bit more documentation about scheduler. I'm a bit more interested how exactly scheduler works and how the crawls are parallelised? Where URLs have to be defined so that scrapy will perform parallel requests?

**Comment by Gallaecio** [comment]
[StackOverflow](https://stackoverflow.com/tags/scrapy) may be a better place to ask this type of questions.

**Comment by amirduran** [comment]
Ok, I will ask there.
