### ISSUE TITLE
Only first part of paragraph being returned, up until child tag is encountered?

### ISSUE THREAD

**Issue by gingerbeardman** [scrapy/scrapy#3841]
I am encountering the following type of markup:
```html
<p>Noting the presence of a footnote<sup>1</sup> is one common way for superscripts to be used.</p>
```

Test page:  
https://html.com/tags/sup/

Test query:  
```python
response.css('div.render p::text')[0].extract()
```

Test results:
> Noting the presence of a footnote

Test expected: 
> Noting the presence of a footnote is one common way for superscripts to be used.

Question: 
 
How can I get the full text of the paragraph, ignoring the child tag?

**Comment by Gallaecio** [comment]
Please, use [StackOverflow](https://stackoverflow.com/tags/scrapy) to ask this type of questions. See [Getting Help](https://docs.scrapy.org/en/latest/#getting-help).

**Comment by gingerbeardman** [comment]
BTW StackOverflow did not yield a solution
