### ISSUE TITLE
can't get sites html

### ISSUE THREAD

**Issue by anthonysanchezmk** [scrapy/scrapy#3847]
When I check the response.body from certain sites, like https://spong.com/games-db/browse I only get byte data, as well as the response.text. I've tried response.body.decode('utf-8') and gave me the error  'utf-8' codec can't decode byte 0xe4 in position 4: invalid continuation byte.

**Comment by dangra** [comment]
Please, refer to https://scrapy.org/community/ for support queries. thanks
