### ISSUE TITLE
HttpErrorMiddleware not honoring handle_httpstatus_all meta as documented

### ISSUE THREAD

**Issue by ddebernardy** [scrapy/scrapy#3851]
```
    def process_spider_input(self, response, spider):
        if 200 <= response.status < 300:  # common case
            return
        meta = response.meta
        if 'handle_httpstatus_all' in meta:
            return
```

Shouldn't that be more like:

```
        if 'handle_httpstatus_all' in meta and meta['handle_httpstatus_all']:
            return
```

As I read the code, setting meta['handle_httpstatus_all'] = False would likely be treated as if it was set to `True`.

**Comment by kmike** [comment]
+1 to fix it, though I think current [docs](https://docs.scrapy.org/en/latest/topics/spider-middleware.html#std:reqmeta-handle_httpstatus_all) are technically correct, and match the current behavior:

> The handle_httpstatus_list key of Request.meta can also be used to specify which response codes to allow on a per-request basis. You can also set the meta key handle_httpstatus_all to True if you want to allow any response code for a request.

**Comment by Jgaldos** [comment]
@Gallaecio Can I try this bug?
