### ISSUE TITLE
Scrapy finding lots of invalid links - could we have functionality to filter them out?

### ISSUE THREAD

**Issue by ddebernardy** [scrapy/scrapy#3855]
Using this selector:

```
links = response.xpath('//a[@href]')
```

I picked up a lot of spaces, as well as random schemes like `mailto:`, `tel:`, and `javascript:`, which makes me presume there might be a better function. If Link extractors merely are wrappers around the above though, it might be worth adding some kind of option to sanitize link urls. (Perhaps that functionality is buried somewhere in the source code or in a section of the docs I skimmed over?)

Anyway, more importantly than the above, I found the following nuggets in my data's href fields, and methinks Scrapy should definitely provide some kind of built-in filtering mechanism for those:

```
Improperly closed tag (href is missing its closing bracket; likely an lxml bug):

https://so.dajie.com/job/search?positionFunction=120610&positionName=视频算法>
                                        视频算法
                                    </a>
                                </li>
                                <li>
                                    <a id=

---
Same issue with a pretty quote:

https://asg.to/contentsPage.html?mcd=dGQRAGplZCkLCfbw”>サンプル動画はコチラ</a><br />
</dd>
	<dt>2013.7.16</dt>
	<dd><h3>プレミアム会員限定オリジナル動画新作配信！</h3>
	アゲサゲのプレミアムメンバーに向けて完全オリジナル動画が更新されました！<br />今回はフリーターのりおちゃん！スレンダーな感じやすい体がそそります！
	<a href=

---
PHP error:

<br />
<b>Warning</b>:  Use of undefined constant url - assumed 'url' (this will throw an Error in a future version of PHP) in <b>/home/forge/jaidefinichon.com/public/wp-content/themes/jaidefinichon/header.php</b> on line <b>116</b><br />
https://jaidefinichon.com
```

Also, it've been finding urls with carriage returns, line feeds, tabs, and spaces at random location. Sometimes they'd be valid had they been url encoded. Other times, it's basically a miracle that browsers accept the links as is. I've seen the latter characters before and after each of `.`, `?`, `=`, `&`, and `#`.

It might be an upstream problem in `urlparse()`. For instance:

```
>>> url = '''https://www.booking.com/country
... .html?label=gen173nr-1FCAEoggI46AdIM1gEaGeIAQGYATG4AQfIAQ3YAQHoAQH4AQKIAgGoAgO4Av2s9OgFwAIB;sid=514ad6c12110c2103c6a2618a429af6d'''
>>> url
'https://www.booking.com/country\n.html?label=gen173nr-1FCAEoggI46AdIM1gEaGeIAQGYATG4AQfIAQ3YAQHoAQH4AQKIAgGoAgO4Av2s9OgFwAIB;sid=514ad6c12110c2103c6a2618a429af6d'
>>> from urllib.parse import urlparse
>>> urlparse(url)
ParseResult(scheme='https', netloc='www.booking.com', path='/country\n.html', params='', query='label=gen173nr-1FCAEoggI46AdIM1gEaGeIAQGYATG4AQfIAQ3YAQHoAQH4AQKIAgGoAgO4Av2s9OgFwAIB;sid=514ad6c12110c2103c6a2618a429af6d', fragment='')
```

**Comment by elacuesta** [comment]
Hi @ddebernardy,

Regarding your first example, I'm not sure there's much we can do about it. In the example you're just selecting tags that contain an `href` attribute, regardless of its value. If the source had a `<a href="foo">bar</a>` tag, it would be valid. Note that the [`LinkExtractor`](https://doc.scrapy.org/en/latest/topics/link-extractors.html#module-scrapy.linkextractors.lxmlhtml) class does have the ability to take a filtering function (`process_value` argument).

Regarding the badly formatted anchor tags, it seems like `lxml` is actually doing a better job than `BeautifulSoup` or `xml`, at least is able to find the tag.
I think you could also use the `process_value` callable here to clean those bad links.


```python
In [1]: s = """<html>
  ...:     <body>
  ...:         <a href="https://so.dajie.com/job/search?positionFunction=120610&positionName=视频算法>
  ...:                                             视频算法
  ...:         </a>
  ...:     </body>
  ...: <html>
  ...: """

In [2]: from bs4 import BeautifulSoup
  ...: p = BeautifulSoup(s, 'html.parser')
  ...: p.find('a')  # nothing found

In [3]: from io import StringIO
  ...: from xml.etree.ElementTree import parse
  ...: root = parse(StringIO(s))

Traceback (most recent call last):
 File "/.../lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3296, in run_code
   exec(code_obj, self.user_global_ns, self.user_ns)
 File "<ipython-input-3-9bbed8a4d530>", line 3, in <module>
   root = parse(StringIO(s))
 File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 1196, in parse
   tree.parse(source, parser)
 File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 597, in parse
   self._root = parser._parse_whole(source)
 File "<string>", line unknown
ParseError: not well-formed (invalid token): line 3, column 85

In [4]: from scrapy.selector import Selector
In [5]: Selector(text=s).xpath('//a')
Out[5]: [<Selector xpath='//a' data='<a href="https://so.dajie.com/job/search'>]

In [6]: Selector(text=s).xpath('//a/@href').get()
Out[6]: 'https://so.dajie.com/job/search?positionFunction=120610&positionName=视频算法>\n                                            视频算法\n        </a>\n    </body>\n<html>'
```

I don't really know about the last issue, I'd need to do some research on that.

PS:
Sorry, I'm not sure this reply will actually help you, hopefully someone else could provide more insights.

**Comment by ddebernardy** [comment]
Oh, no worries. I was just raising it in a ticket in case anyone thought that some kinds of built-in filters would be welcome to process the most common issues.

In case it helps anyone else, the basic filters I ended up using are:

```python
if '>' in href: # improperly closed anchors
    href = re.sub(r'\s*[\'"‘’“”]?>.*$', '', href, flags=re.S)
if '<' in href: # server-side parse errors
    href = re.sub(r'\s*<.*$', '', href, flags=re.S)
if href.endswith('}}'): # template garbage
    href = re.sub(r'\s*\}\}', '', href)
```

I'm less sure about how valid my carriage return and line feed processing is, but here it is as well:

```python
quote_plus_match = lambda m: urllib.parse.quote_plus(m[0])

if any(c in href for c in '\n\r'):
    if not any(c in href for c in '?#'): # Just rip it all out
        href = re.sub(r'\s*', '', href)
    else: # Parse and strip accordingly
        url = urllib.parse.urlsplit(href)
        href = urllib.parse.SplitResult(
                url.scheme,
                re.sub(r'[\r\n]+', '', url.netloc.strip()),
                re.sub(r'[\r\n]+', '', url.path.strip()),
                re.sub(r'[\r\n]+', quote_plus_match, url.query.strip()),
                re.sub(r'[\r\n]+', quote_plus_match, url.fragment.strip())
            ).geturl()
```

(In the case of the last two, Safari actually seems to ignore what follows `\n` entirely, and this might produce better outcomes when following links.)

**Comment by kmike** [comment]
I think for carriage returns one should use [w3lib.html.strip_html5_whitespace](https://github.com/scrapy/w3lib/blob/43fa1cbfde049a77e574c9c4a859af9553046512/w3lib/html.py#L325), or use response.follow instead of using href values directly with scrapy.Request.

**Comment by ddebernardy** [comment]
@kmike strip_html5_whitespace is not quite enough though:

```
>>> strip_html5_whitespace(' hello\nworld\n')
'hello\nworld'
```

**Comment by kmike** [comment]
@ddebernardy hm, I think you're right. When opening in a browser, the newline inside a link is not escaped, but removed:

```html
<html><head><base href="http://example.com"></head><body><a href=' hello
world
'>click me</a></body></html>
```

and this behavior is actually defined in https://url.spec.whatwg.org/#url-parsing

> 3. Remove all ASCII tab or newline from input.

I think we should modify somee function in w3lib to do the same.

**Comment by elacuesta** [comment]
@kmike Should that removal be done in `canonicalize_url`? `strip_html5_whitespace` is under the `html` module and this seems more like an URL issue. Also, while strictly speaking `strip` can be interpreted as "remove", usually in the Python context it means taking stuff from the beginning or end; in this case those chars should be removed from the whole thing.

**Comment by kmike** [comment]
I'm not sure where it should be done, maybe in safe_url_string. Definitely not in strip_html5_whitespace (because of the reasons you've said), and not in canonicalize_url (this one should be used for url deduplication, urls which pass through canonicalize_url shouldn't be downloaded).

**Comment by kmike** [comment]
It's a pity stdlib urllib.parse doesn't support https://url.spec.whatwg.org. I wonder if there is a Python package which supports it properly (maybe https://github.com/scrapy/scurl?). All these fixes in w3lib are hacks and workarounds to a lack of a proper browser-like URL parser.

**Comment by elacuesta** [comment]
`scurl` is not (yet?) in use within Scrapy, right? I can draft a PR for `safe_url_string`.

**Comment by kmike** [comment]
@elacuesta right! Also, it'd be good to check carefully if safe_url_string is indeed the best place for a fix, e.g. that these newlines are not escaped in some place before even getting to safe_url_string.

**Comment by elacuesta** [comment]
@kmike please take a look at the above PR.
It seems to me like `safe_url_string` is indeed the place to handle this, since it's the first operation applied to the URL in the `Request` constructor (https://github.com/scrapy/scrapy/blob/1.6/scrapy/http/request/__init__.py#L54-L58)

**Comment by Gallaecio** [comment]
Closing now that https://github.com/scrapy/w3lib/pull/133 is merged.
