### ISSUE TITLE
scrapy could not download pdf files completely.

### ISSUE THREAD

**Issue by lycanthropes** [scrapy/scrapy#3864]
I want to download pdf files from the pdf web links crawled by scrapy spiders, but when I use scrapy.Request (pdf_url) in filespipeline to crawl the pdf web, eventually it downloaded incomplete pdf files. all the pdf files was 1 KB Other than the first few files( which are complete). I had  to use requests.get(pdf_url, stream=True) to download all the pdf files completely, but it is too slow. I want to know if scrapy filespipelines has similar method like this ?

**Comment by Gallaecio** [comment]
Please, use [StackOverflow](https://stackoverflow.com/tags/scrapy) to ask this type of questions. See [Getting Help](https://docs.scrapy.org/en/latest/#getting-help).
