### ISSUE TITLE
Deprecate hacky code from get_project_settings()

### ISSUE THREAD

**Issue by Gallaecio** [scrapy/scrapy#3871]
[Reported](https://github.com/scrapy/scrapy/pull/3859#issuecomment-510838622) by @nyov:

> @kmike, would you or someone perhaps also find time to correctly deprecate this (or just rip it > out)?: https://github.com/scrapy/scrapy/blob/9c90d9515a50ede29415b8b5d6ba11229f333b49/scrapy/utils/project.py#L70-L79
> Or is it still needed.

**Comment by elacuesta** [comment]
Deprecated by #3910 and #4300.
