### ISSUE TITLE
DOWNLOAD_MAXSIZE logger level shouldn't be Error

### ISSUE THREAD

**Issue by mohmad-null** [scrapy/scrapy#3874]
When triggered, the `DOWNLOAD_MAXSIZE` setting raises an ERROR level logging event. I don't think it should be at this level. Error is "something went wrong"; I've explicitly told Scrapy I don't want files of this size, so it's not an error to not download them. WARN or even just INFO makes more sense.

I'm logging Error levels and above to stderr so I can keep track of them easily and it's being flooded by these. In fact, apart from a couple of genuine errors, of the ~100,000 requests my spider has made so far, these are the only Errors that are showing up.

**Comment by kmike** [comment]
Sounds good; pull requests are welcome.

**Comment by 991rajat** [comment]
Is this Open?

**Comment by WinterComes** [comment]
Could you take a look at my last PR please, I hope I get it right.
Sorry for a little mix-up with yesterday PRs. I was scared of a failed tests, haha

**Comment by chrisbangun** [comment]
Hi, newbie here and would love to learn and contribute. is this still open?

**Comment by Gallaecio** [comment]
@chrisbangun There’s already an open proposal which seems good: https://github.com/scrapy/scrapy/pull/3886

**Comment by faizan2700** [comment]
I want to contribute to this enhancement #3874 as I am beginner. I have been reading code of scrapy and located from where this error is being raised. Please assign this to me.

**Comment by Gallaecio** [comment]
@faizan2700 There’s someone already working on it, with a working proposal ready: #3886

**Comment by sprzedwojski** [comment]
https://github.com/scrapy/scrapy/pull/3886 has been accepted and looks ready to be merged
