### ISSUE TITLE
Can I get remote server's ip address via response?

### ISSUE THREAD

**Issue by imfht** [scrapy/scrapy#3903]
Can I get remote server's ip address via response?
For some reason. I'll need get remote site's ip address when parsing response. I looked the document but found nothing.
Any one know that?
Thanks!

**Comment by anubhavp28** [comment]
You could use the `url` property of the [Response](https://docs.scrapy.org/en/latest/topics/request-response.html#response-objects) object, pass it to [urllib.parse.urlparse](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urlparse) fuction to obtain the domain name. Then you can pass the domain to [socket.gethostbyname](https://docs.python.org/3/library/socket.html#socket.gethostbyname) to get the IP address. I haven't tested it, but it should work.

**Comment by Gallaecio** [comment]
I don’t think this is possible at the moment, but it sounds like a valid feature request.

**Comment by imfht** [comment]
Thanks @anubhavp28 .
I don't think it is the right way to get remote ip in scrapy
get_host_by_name cause another new dns resolve. Actually we've got remote ip in scrapy.
class `CrawlerProcess` has an [built-in dnscache](https://github.com/scrapy/scrapy/blob/8e813953bd4b25b60d30981a948e48fee43f8dad/scrapy/resolver.py#L10) object but we can not get it in pipeline.
