### ISSUE TITLE
S3FilesStore has incomplete header to botocore mapping

### ISSUE THREAD

**Issue by davkuyek** [scrapy/scrapy#3904]
If botocore is installed, Scrapy's [S3FilesStore](https://github.com/scrapy/scrapy/blob/9c514b976ffdf069b81c4b7728a7e8e531710680/scrapy/pipelines/files.py#L80) allows a limited number of headers to be applied when persisting files to S3. The headers are [converted](https://github.com/scrapy/scrapy/blob/9c514b976ffdf069b81c4b7728a7e8e531710680/scrapy/pipelines/files.py#L175) to their botocore s3 put_object method equivalent argument. The mapping however is incomplete.

[Put-object request headers](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html)
[Botocore arguments](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Bucket.put_object)

Missing headers and their equivalent options:

`x-amz-storage-class` -> `StorageClass`
`x-amz-tagging` -> `Tagging`
`x-amz-website -redirect-location` -> `WebsiteRedirectLocation`
`x-amz-object-lock-mode` -> `ObjectLockMode`
`x-amz-object-lock-retain-until-date` -> `ObjectLockRetainUntilDate`
`x-amz-object-lock-legal-holdv` -> `ObjectLockLegalHoldStatus`
`x-amz-server-side -encryption` -> `ServerSideEncryption`
`x-amz-server-side-encryption-aws-kms-key-id` -> `SSEKMSKeyId`
`x-amz-server-side-encryption-context` -> `SSEKMSEncryptionContext`
`x-amz-server-side -encryption -customer-algorithm` -> `SSECustomerAlgorithm`
`x-amz-server-side -encryption -customer-key` -> `SSECustomerKey`

If you don't have botocore installed you are able to persist a file with the storage class `STANDARD_IA` using the header `x-amz-storage-class`. With botocore, if you try to do the same thing, the type error `Header "x-amz-storage-class" is not supported by botocore` will be raised.

Test code:
```python
from scrapy.pipelines.files import S3FilesStore
from io import BytesIO

s3_file_store = S3FilesStore('s3://your-bucket/')
s3_file_store.persist_file('s3://your-bucket/your-key', BytesIO(b'test'), None, None, {'x-amz-storage-class': 'STANDARD_IA'})
```

`scrapy version -v`
Scrapy    : 1.4.0
lxml      : 4.3.3.0
libxml2   : 2.9.9
cssselect : 1.0.3
parsel    : 1.5.1
w3lib     : 1.20.0
Twisted   : 19.2.1
Python    : 2.7.10 (default, Feb 22 2019, 21:55:15) - [GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.37.14)]
pyOpenSSL : 16.2.0 (OpenSSL 1.1.1c  28 May 2019)
Platform  : Darwin-18.6.0-x86_64-i386-64bit

**Comment by lucywang000** [comment]
I just submitted a fix in https://github.com/scrapy/scrapy/pull/3905
