### ISSUE TITLE
block comment should start with '# '

### ISSUE THREAD

**Issue by serhii73** [scrapy/scrapy#3914]
`scrapy startproject` creating a scrapy project with settings.py. In this file broken pep8 rule.
```
E265 block comment should start with '# '
```

https://www.python.org/dev/peps/pep-0008/#block-comments

>
Inline comments should be separated by at least two spaces from the statement

**Comment by elacuesta** [comment]
This is known, please see #3697

**Comment by serhii73** [comment]
Thank you very much @elacuesta !
