### ISSUE TITLE
Parsing the robots.txt in RobotsTxtMiddleware should skip the asterisk symbol at the end.

### ISSUE THREAD

**Issue by MikhailKavaliou** [scrapy/scrapy#3916]
The RobotsTxtMiddleware is enabled with the ROBOTSTXT_OBEY=True.
Nonetheless, the built-in filter in the middleware passes URLs, that are basically disallowed.

For example there is the robots.txt rules like the following:
```
...
Disallow: /beta/
Disallow: /inventory/srp.html?*
Disallow: /search/*
...
```

In this case, all /beta/ links will be ignored as expected, but the 2 next rules do not filter correct URLs, because the asterisk at the end is interpreted as a symbol to be included in the URL.
Regarding that the condition in the RobotsTxtMiddleware#the process_request_2 is False for disallowed URLs:
```
if not rp.can_fetch(to_native_str(self._useragent), request.url):
            logger.debug("Forbidden by robots.txt: %(request)s",
                         {'request': request}, extra={'spider': spider})
            self.crawler.stats.inc_value('robotstxt/forbidden')
            raise IgnoreRequest("Forbidden by robots.txt")
```

**Comment by anubhavp28** [comment]
Scrapy uses Python's inbuilt robots.txt parser - [RobotFileParser](https://docs.python.org/3/library/urllib.robotparser.html). It does not support wildcards such as `*` and `$`. Hence the problem you experienced. An interface for robots.txt parser which would allow substituting a more compliant parser is WIP (https://github.com/scrapy/scrapy/pull/3796).

**Comment by MikhailKavaliou** [comment]
@anubhavp28 Thanks for letting me know.
So far I use a workaround parsing the robots.txt rules manually and skipping disallowed URLs in a custom middleware.

**Comment by anubhavp28** [comment]
@MikhailKavaliou if you don't mind, please consider closing this issue.
