### ISSUE TITLE
Work around tox #1369

### ISSUE THREAD

**Issue by Gallaecio** [scrapy/scrapy#3917]
The Jessie build is affected by https://github.com/tox-dev/tox/issues/1369, which may be hiding a different issue.

**Comment by Gallaecio** [comment]
This seems to be the only remaining persistent CI issue at the moment after #3913 is merged.

**Comment by wRAR** [comment]
The Jessie build started failing after the base image switched to xenial, as can be seen in travis job logs. A manual run shows that cryptography 0.6.1 can't be built with xenial's OpenSSL.

**Comment by kmike** [comment]
I think we may pin tox version in the meantime.

**Comment by dangra** [comment]
> I think we may pin tox version in the meantime.

Not sure if it is clear what version of tox broke the build, it looks like the tox bug has been there for a long time and Travis-ci switch to Xenial just uncovered it.

My understanding after reading @wRAR's comment and travis-ci blog is that distribution should be pinned to `trusty` in `.travis.yml` for 1.7 branch.

For 1.8+, minimum version will be upgraded to Xenial (by dropping Jessie and similars) as commented in https://github.com/scrapy/scrapy/pull/3892#issuecomment-515132867

**Comment by dangra** [comment]
Fix proposed at https://github.com/scrapy/scrapy/pull/3923
