### ISSUE TITLE
command: scrapy crawl XXX, has started wrong spider

### ISSUE THREAD

**Issue by My-captain** [scrapy/scrapy#3924]
I have 2 spiders in my scrapy project, one is 'metalnews', the other is 'metalnewshistory'.
However, when I run the command: scrapy crawl metalnewshistory, It's run the 'metalnews' spider.
How can I solve the situation?
MetalnewsHistory.py
![image](https://user-images.githubusercontent.com/18298526/62186584-61947c00-b399-11e9-86d7-bd095d026493.png)
MetalnewsSpider.py
![image](https://user-images.githubusercontent.com/18298526/62186606-7709a600-b399-11e9-8df1-4342473c1fc9.png)
Best wishes for you.

**Comment by elacuesta** [comment]
Have you renamed the files recently? I wouldn't bet on it, but this _could_ be the result of residual `pyc` files in the project. Besides that, could you provide some output from the command? Please post as text, not screenshot.
