### ISSUE TITLE
JSONRequest naming issue

### ISSUE THREAD

**Issue by noviluni** [scrapy/scrapy#3929]
A few months ago `JSONRequest` was added to Scrapy (https://github.com/scrapy/scrapy/pull/3505) and released with the new Scrapy version 1.7.

However, I realized that the name is not in accordance with the rest of the classes: `HtmlResponse`, `XmlResponse`, `XmlRpcRequest`.

It should be named:
`JsonRequest`.

I know it isn't backward-compatible, but as it's a really recent addition and Scrapy 2.0 is on the way it could be fixed.

**Comment by Gallaecio** [comment]
_Maybe_ we should consider renaming the other 3 instead to [comply with PEP8](https://stackoverflow.com/a/2853609).

**Comment by noviluni** [comment]
@Gallaecio Totally agree with you. We should decide what to do: 
* to change it or not

If we decide to change it:
* to follow PEP8 or not

I have just opened an issue regarding PEP8: https://github.com/scrapy/scrapy/issues/3944. Maybe it should be addressed before deciding the second question.

**Comment by Gallaecio** [comment]
> Hey! As JSONRequest is what pep8 recommends, we (me, @dangra, @Gallaecio and @wRAR) agreed to rename other classes instead. PRs are welcome :)

@kmike at https://github.com/scrapy/scrapy/pull/3930#issuecomment-519518983

**Comment by noviluni** [comment]
Looking over I have seen that this issue affects at least the following classes:

```
HtmlResponse
HtmlParserLinkExtractor

HttpProxyMiddleware
HttpAuthMiddleware
HttpCacheMiddleware
HttpCompressionMiddleware
HttpErrorMiddleware
HttpError

JsonWriterPipeline
JsonLinesItemExporter
JsonItemExporter

XmlRpcRequest
XmlItemExporter
XmlResponse
```

**Comment by kmike** [comment]
👍 Thanks for checking it @noviluni! I was thinking it is less things to fix..

**Comment by kmike** [comment]
Tbh, I'd leave everything as-is, probably including JSONRequest; it is not super consistent, but my feeling is that changing it doesn't worth the development efforts required to upgrade (change in settings, imports, etc.)

**Comment by noviluni** [comment]
I'm agree with you, there are too much classes to deprecate... If you other are agree feel free to close this issue,

**Comment by kmike** [comment]
We may still change JSONRequest though, to at least match other Request classes - that's what you propsed in #3930 .

**Comment by noviluni** [comment]
As all the classes in Scrapy starting with "JSON" (`JsonLinesItemExporter`, `JsonItemExporter` and `JsonWriterPipeline`) use that format, it could be a good idea. 

If you all want to proceed I can re-open the original PR and adding the code to deprecate that class.

**Comment by noviluni** [comment]
Added new PR: https://github.com/scrapy/scrapy/pull/3982

 (I deleted the old branch from my repo and couldn't open the old PR).

**Comment by noviluni** [comment]
I close this issue as PR has been already merged. Thank you all for your feedback! :)
