### ISSUE TITLE
Using separate user agent for robots.txt

### ISSUE THREAD

**Issue by anubhavp28** [scrapy/scrapy#3931]
The current implementation of `RobotsTxtMiddleware` ([link](https://github.com/scrapy/scrapy/blob/master/scrapy/downloadermiddlewares/robotstxt.py)) uses `USER_AGENT` setting and `User-Agent` header of the request to determine the user agent to use for matching in `robots.txt`. There is no easy way for a user to send one user-agent header value but have a different user agent string evaluated to decide which pages to crawl. This use case seems to be more common that we thought previously for example - while [Googlebot](https://support.google.com/webmasters/answer/182072?hl=en) uses `"Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"`  as `User-Agent` header of the request, it actually uses user agent `"Googlebot"` in `robots.txt` for deciding which pages to crawl. [Here is the an article describing this.](https://support.google.com/webmasters/answer/1061943?hl=en) The same seems to be the case with Bing - [link](https://www.bing.com/webmaster/help/which-crawlers-does-bing-use-8c184ec0). Infact, Google made this distinction very clear in their proposed [robots.txt specification](https://github.com/google/robotstxt/blob/master/protocol-draft/draft-rep-wg-topic-00.txt) where they described the user agent used in `robots.txt` as the "product token".

The proposed solutions are implementing a new `ROBOTSTXT_USER_AGENT` setting, implementing a `robotstxt_user_agent` meta key for overriding user agent per request or both. Here is a thread that has previous discussion on the topic - https://github.com/scrapy/scrapy/pull/3796#discussion_r300036852.

I'm creating this issue as a place for discussion regarding whether to add this functionality into Scrapy? If yes, which route we should take?

**Comment by Gallaecio** [comment]
I think `ROBOTSTXT_USER_AGENT` makes sense, falling back to the current behavior when undefined.

As for the meta key, although I proposed it, I’m not sure it’s worth it.
