### ISSUE TITLE
Why is Scrapy constantly increasing memory usage?

### ISSUE THREAD

**Issue by tonylin75** [scrapy/scrapy#3936]
I have a scraping project used scrapy and it will continuously run, meaning when it's finished, I have a script to make it run again.
It takes about 10 hours to finish a round and the memory increases by 100mb and not released after it.
I used `JOBDIR` it helps with the speed but no luck for solving the memory issue.
Here's what I have got for the spider:

```
with open(suburbLinkFileName) as f:
        data = json.load(f)
        for link in data:
            all_suburb_links.append(link['result'])
    
    def parse(self, response):
        for suburb_link in self.all_suburb_links:
            absolute_next_suburb_link = 'http://www.xxxx.com.au/buy/' + suburb_link + "?includeSurrounding=false"
            yield Request(url=absolute_next_suburb_link, callback=self.parse_suburb)

    def parse_suburb(self, response):
        properties_urls = response.xpath("//*[@class='details-link ']/@href").extract()

    for property_url in properties_urls:
        absolute_property_url = self.base_url + property_url
        yield Request(absolute_property_url, callback=self.parse_property)

        next_page_url = response.xpath('//a[@class="rui-button-brand pagination__link-next"]/@href').extract_first()
        if next_page_url is None:
            return None

        absolute_next_page_url = self.base_url + next_page_url
        yield Request(url=absolute_next_page_url, callback=self.parse_suburb)

    def parse_property(self, response):
        if not response.xpath('//title'):
            yield Request(url=response.url, dont_filter=True)
```

I couldn't see I got anything leaking the memory.. Took me couple of days already but no luck..

**Comment by Colafroth** [comment]
TBH I don't think it's issue for the code I put here. I have tried every possible way and it still exists. I seen some other people suffer from same issue and they didn't find the solution. At least, is there a way that once the scraping completes, it (scrapy or reactor) can release the memory and then I can start again?

**Comment by elacuesta** [comment]
Hello there, have you tried http://doc.scrapy.org/en/latest/topics/leaks.html? I'm not saying it's not a problem within Scrapy, but it might be better to check the spider code first.
Also, is the indentation correct in the code you posted? Nested functions are a somewhat common thing in Python, but the fact that three callbacks are intertwined with a `for` loop, and that all of that is within a `with` block looks strange to me.

**Comment by kmike** [comment]
There is some inherent state in Scrapy, e.g. dupefilters. 100MB after 10hrs can be explained by this, if a crawl is large enough. It is  not a leak in  a sense that this  data is useful - Scrapy keeps track of seen URLs to avoid duplicates. Once crawl completes, it should release dupefilter memory.

**Comment by kmike** [comment]
You  can disable dupefilter using https://docs.scrapy.org/en/latest/topics/settings.html#dupefilter-class

**Comment by Colafroth** [comment]
@kmike  thank you , I definitely gonna try it out. But IDK if this is because of this: http://doc.scrapy.org/en/latest/topics/leaks.html#leaks-without-leaks. It bothers me because I also use some other python library like Celery for running tasks. It seems suffer same issue in long run...

**Comment by selfcontrol7** [comment]
Hello @tonylin75,
Three years later and I am also facing the same issue with my crawling code running for 7 hours minimum.
And that the end because the device does not have enough memory, the crawled data are partially saved in the CSV file.

I will really appreciate it if you could share how you solved the issue.

Thank you.

**Comment by Gallaecio** [comment]
Unless you can identify which part of Scrapy is taking the memory, or provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), there’s not much we can do.

**Comment by b5y** [comment]
I am also getting memory increase after some run and docker stops writing the results to the output. Interestingly, there are no problems with memory if you run with `docker-compose`, at least on my local machine.
