### ISSUE TITLE
Drop support of Python 3.4?

### ISSUE THREAD

**Issue by starrify** [scrapy/scrapy#3942]
Python 3.4 has now [reached its end-of-life](https://www.python.org/downloads/release/python-3410/).

Also Twisted has dropped support of Python 3.4 [since version 19.7.0](https://github.com/twisted/twisted/blob/trunk/NEWS.rst#deprecations-and-removals)

This is also believed to be the cause of recent CI build failures ([one example](https://travis-ci.org/scrapy/scrapy/builds/568395165?utm_source=github_status&utm_medium=notification)).

**Comment by rennerocha** [comment]
It will be dropped in the next release:
https://github.com/scrapy/scrapy/pull/3892

**Comment by starrify** [comment]
Thanks @rennerocha ! I searched for "3.4" but not "py34" before creating this issue. :sweat_smile:
