### ISSUE TITLE
Counting links with scrapy

### ISSUE THREAD

**Issue by natescrape** [scrapy/scrapy#3948]
I am trying to work out how to count the number of times a word occurs on a site. I have got to the following code, which prints true or false when the word is found, but how can i count these and return in a singe cell in csv?

import scrapy
from scrapy.spiders import CrawlSpider, Rule
from scrapy.linkextractors import LinkExtractor

class ExampleSpider(CrawlSpider):
    name = 'example'
    allowed_domains = ['examplewebsite.com']
    start_urls = ['https://examplewebsite.com']

    rules = (
        Rule(LinkExtractor(), callback='parse_item', follow=True),
    )

    def parse_item(self, response):
    	example1 = bool(response.xpath('//*').re('example1'))
    	example2 = bool(response.xpath('//*').re('example2'))
    	
    	yield{'example1' : example1,
    			'example2' : example2}

**Comment by Gallaecio** [comment]
Please, use [StackOverflow](https://stackoverflow.com/tags/scrapy) to ask this type of questions. See [Getting Help](https://docs.scrapy.org/en/latest/#getting-help).
