### ISSUE TITLE
optimize the TextResponse's selector code

### ISSUE THREAD

**Issue by financialfly** [scrapy/scrapy#3949]
I have noticed the TextResponse's selector code at scrapy/http/response/text.py:
```py
    @property
    def selector(self):
        from scrapy.selector import Selector
        if self._cached_selector is None:
            self._cached_selector = Selector(self)
        return self._cached_selector
```
why don't change to:
```py
    @property
    def selector(self):
        if self._cached_selector is None:
            from scrapy.selector import Selector
            self._cached_selector = Selector(self)
        return self._cached_selector
```
This can avoids import the Selector object multiple times

**Comment by kmike** [comment]
We can change it, but imports are more readable if they are the first, and performance overhead of such import is super-low, a few dictionary lookups (on repeated imports there is no need  to access disk, etc.). So I'd prefer to leave it as-is.
