### ISSUE TITLE
Implementing distributed problems with scrapy-redis

### ISSUE THREAD

**Issue by hewm** [scrapy/scrapy#3963]
When using scrapy-redis for distributed, if there are already ten machines crawling at the moment, but the speed is not in line with the intention, can the original code be deployed on the new machine, and the new machine will not be down on the basis of new machines. Crawling machine

**Comment by Gallaecio** [comment]
Please, use [StackOverflow](https://stackoverflow.com/tags/scrapy) to ask this type of questions. See [Getting Help](https://docs.scrapy.org/en/latest/#getting-help).
