### ISSUE TITLE
 Scrapy redis distributed

### ISSUE THREAD

**Issue by hewm** [scrapy/scrapy#3964]
The scrapy crawler request link only enters the process_request method in middlewares.py, does not enter the parse method in the spider, is the scrapy distributed using scrapy-redis, I would like to ask if it is possible because the current url has been requested. Did not continue to execute downward

**Comment by Gallaecio** [comment]
Please, use [StackOverflow](https://stackoverflow.com/tags/scrapy) to ask this type of questions. See [Getting Help](https://docs.scrapy.org/en/latest/#getting-help).
