### ISSUE TITLE
Make Protego the default robots.txt parser

### ISSUE THREAD

**Issue by anubhavp28** [scrapy/scrapy#3969]
[Protego](https://github.com/scrapy/protego) is more compliant robots.txt parser than the current default [RobotFileParser](https://docs.python.org/3/library/urllib.robotparser.html). It supports wildcard matching, length based directive ordering, sitemaps, crawl-delay and request-rate directive. It is also compatible with [Google's robots.txt parser](https://github.com/google/robotstxt). AFAIK, It has bigger test suite than any other open source robots.txt parser. The latest version of Protego is on PyPI and can be installed with `pip install protego`.

It also faster than other Python based candidates. I performed a benchmark using popular robots.txt parsers -

I crawled multiple domains (~1,100 domains) and downloaded links to pages as the crawler encounter them. I downloaded 111, 824 links in total. Next I made each robots.txt parser - parse and answer query (I made parsers answer each query 5 times) in an order similar to how they would need to in a broad crawl. Here are the results :

* [Protego](https://github.com/scrapy/protego) (Python based) :
25th percentile : 0.002419 seconds
50th percentile : 0.006798 seconds
75th percentile : 0.014307 seconds
100th percentile : 2.546978 seconds
Total Time : 19.545984 seconds

* [RobotFileParser](https://docs.python.org/3/library/urllib.robotparser.html) (default in Scrapy) :
25th percentile : 0.002188 seconds
50th percentile : 0.005350 secondsstyle
75th percentile : 0.010492 seconds
100th percentile : 1.805923 seconds
Total Time : 13.799954 seconds

* [Robotexclusionrulesparser](http://nikitathespider.com/python/rerp/) (Python based) :
25th percentile : 0.001288 seconds
50th percentile : 0.005222 seconds
75th percentile : 0.014640 seconds
100th percentile : 52.706880 seconds
Total Time : 76.460496 seconds

* [Reppy Parser](https://github.com/seomoz/reppy) (C++ based with Python interface) :
25th percentile : 0.000210 seconds
50th percentile : 0.000492 seconds
75th percentile : 0.000997 seconds
100th percentile : 0.129440 seconds
Total Time: 1.405558  seconds
 
The code and data used for benchmarking is [here](https://github.com/anubhavp28/robotstxt-parser-benchmark).

**Comment by Gallaecio** [comment]
cc @kmike @dangra @whalebot-helmsman

**Comment by kmike** [comment]
Fixed by https://github.com/scrapy/scrapy/pull/4006.

**Comment by bfelds** [comment]
@whalebot-helmsman an fyi: just installed with conda and it seems protego isn't in conda-forge and not listed as a dependency. i had to manually install with pip into the conda environment

**Comment by Gallaecio** [comment]
> @whalebot-helmsman an fyi: just installed with conda and it seems protego isn't in conda-forge and not listed as a dependency. i had to manually install with pip into the conda environment

Thanks, I’ll try to get it fixed next week.
