### ISSUE TITLE
A question about robots.txt in ebay site

### ISSUE THREAD

**Issue by Remember2018** [scrapy/scrapy#3974]
Hi Dear all, I use the great scrapy to crawl the information in some sites. And when I'm trying to crawl the items in ebay site, the ebay site seems disable the crawler using robots.txt. But when I use the detail information page url, e.g., "https://www.ebay.com/itm/8-New-Universal-12pcs-Hot-Air-Fryer-Kits-w-Cake-Cup-Cake-Basket-5-2QT-8QT/401752292159", the scrapy can get the webpage without "Disallow by robots.txt". So my question is, can I continue to crawl the eBay with Scrapy without considering the Robots.txt? I have set the "ROBOTSTXT_OBEY=True", but it seems some pages in eBay can be crawlled. 

I want to obey the rules and I don't want to pay fees for the crawling from the eBay. I'm afraid that the eBay will send me a notice for the crawling.

**Comment by Gallaecio** [comment]
Please, use [StackOverflow](https://stackoverflow.com/tags/scrapy) to ask this type of questions. See [Getting Help](https://docs.scrapy.org/en/latest/#getting-help).
