### ISSUE TITLE
Dynamic Creation of Item Classes

### ISSUE THREAD

**Issue by LorenDavie** [scrapy/scrapy#398]
I have a need to dynamically create item classes based on user input.  It's not clear to me how to approach that with Scrapy, it seems to assume that a developer will be coding item classes manually.

I created this utility function:

```
from scrapy.item import DictItem, Field

def create_item_class(class_name,field_list):
    field_dict = {}
    for field_name in field_list:
        field_dict[field_name] = Field()

    return type(class_name,DictItem,field_dict)
```

Not sure if this is the best way to approach this kind of problem with Scrapy, but I leave it here for your consideration.  Thanks!

**Comment by lt94** [comment]
I had ever created a class contains this function,but it didn't work.
