### ISSUE TITLE
How to prevent scrapy from forcing the key of the request headers into uppercase?

### ISSUE THREAD

**Issue by LoveDarkblue** [scrapy/scrapy#3981]
### Description
I have a api doc that need send a header with the key that start with lowercase word.
But the scrapy always change the key of the headers into capitalized.
I'm setting the headers like this:

```python
headers = {
    "sign": 'sssssssign',
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)'
}
yield scrapy.Request(url,headers=headers, callback=self.parse_page, meta={'cookiejar': 1})
```
Then i found that "sign" is changed into "Sign" in the DEBUG log.

And then i try to do like this:
```python
from twisted.web.http_headers import Headers as TwistedHeaders

TwistedHeaders._caseMappings.update({
    b'sign': b'sign',  
    b'User-Agent': b'user-agent',
})
```
I put the code in start_request method of spider file, but I still got the following log:
`
{b'User-Agent': [b'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36'], b'Accept-Language': [b'en'], b'Sign': [b'sssssssign'], b'Accept': [b'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8']}
`
How to prevent scrapy from forcing the key of the request headers in uppercase?

**Comment by Gallaecio** [comment]
For the feature request, there’s already #2711. There is a workaround mentioned in #2711, but it does not seem to be working for you.

You could ask in [StackOverflow](https://stackoverflow.com/tags/scrapy) about your specific issue (Why may the workaround not be working for you? What other workarounds are there?), although [there already seems to be an old question about this](https://stackoverflow.com/q/43455417/939364).

**Comment by elacuesta** [comment]
@Gallaecio For the record, the workaround in https://github.com/scrapy/scrapy/issues/2711#issuecomment-367342284 is not working for me either :sweat_smile: 

```python
import json

import scrapy
from twisted.web.http_headers import Headers as TwistedHeaders


TwistedHeaders._caseMappings.update({
    b'sign': b'sign',
    b'user-ugent': b'user-agent',
})


class HeadersSpider(scrapy.Spider):
    name = 'headers'

    def start_requests(self):
        yield scrapy.Request(
            url='https://httpbin.org/headers',
            headers={
                'sign': 'foobar',
                'user-agent': 'Custom User Agent',
            },
        )

    def parse(self, response):
        print('Request headers:', sorted(response.request.headers.keys()))
        print('Sent headers:', sorted(json.loads(response.text)['headers'].keys()))
```

```
$ scrapy runspider headers.py

(...)
Request headers: [b'Accept', b'Accept-Encoding', b'Accept-Language', b'Sign', b'User-Agent']
Sent headers: ['Accept', 'Accept-Encoding', 'Accept-Language', 'Host', 'Sign', 'User-Agent']
(...)
```

**Comment by codingpy** [comment]
I think it should be users' choice whether or not to title the header field, because some websites don't recognize titled fields.

**Comment by anjia0532** [comment]
my blog to fix this https://anjia0532.github.io/2021/08/05/scrapy-capitalizes-request-headers/

**Comment by yi-ye-zhi-qiu** [comment]
I've come across this issue a few times when crawling. It's unexpected as [section 3.2.2 of the RFC Standard for HTTP/1.1 protocol](https://www.rfc-editor.org/rfc/rfc7230#section-3.2.2) outlines that header casing doesn't matter. That being said, anti-bot is often unpredictable.

So where is this happening in Scrapy? From my perspective, seems like `key.title()` is responsible for capitalized headers as seen [here](https://github.com/scrapy/scrapy/blob/37be9da4e4d65c90b26197b7efafde0f213e56b0/scrapy/http/headers.py#L45C1-L46C1), whereas Twisted has its own form of header canonicalization, as you can see [here](https://docs.twisted.org/en/stable/api/twisted.web.http_headers.Headers.html).

I think Scrapy does natively conform to the standard titled header canonicalization:

```python
import scrapy
scrapy.http.Headers({"I tHoUgHt I TOld YoU tO clean yOUR RoOM": "test"})
# {b'I Thought I Told You To Clean Your Room': [b'test']}
```

Here's a few approaches:

### Customized `Request` object

```python
from scrapy.spiders import Spider
from typing import Iterable, AnyStr
from scrapy.http.request import Request
from scrapy.http.headers import Headers


class H(Headers):
    def normkey(self, key: AnyStr) -> bytes:  # type: ignore[override]
        """Normalize key to bytes"""
        # Source, see:
        # https://github.com/scrapy/scrapy/blob/37be9da4e4d65c90b26197b7efafde0f213e56b0/scrapy/http/headers.py#L45C1-L46C1
        # return self._tobytes(key.title())
        # Modification:
        return self._tobytes(key)


class R(Request):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.headers: Headers = H(self.headers or {}, encoding=self.encoding)


class Spider(Spider):
    name = "default"

    def start_requests(self) -> Iterable[Request]:
        yield R(
            "https://httpstat.us/200",
            headers={"aa": "aa", "aa-AA": "aa-AA", "AA-AA": "AA-AA", "AA-aa": "AA-aa"},
        )

    def parse(self, response):
        self.logger.info(response.request.headers)
        self.logger.info(response.text)
```

### Customized `Headers`

This one just adds a bit at the top of the file to override the `normkey` method of the `Headers` class.

```python
from scrapy.spiders import Spider
from scrapy.http.headers import Headers
from typing import AnyStr

def case_sensitive_normkey(self, key: AnyStr) -> bytes:
    # return self._tobytes(key.title())
    return self._tobytes(key)

Headers.normkey = case_sensitive_normkey

class Spider(Spider):
    name = "d"

    start_urls = ["https://httpstat.us/200"]

    custom_settings = {
        "DEFUALT_REQUEST_HEADERS": {"aa": "aa", "aa-AA": "aa-AA", "AA-AA": "AA-AA", "AA-aa": "AA-aa"},
    }

    def parse(self, response):
        self.logger.info(response.request.headers)
        self.logger.info(response.text)
```

If you wanted to apply this as a generalized solution and turn off header key normalization entirely, you could add the `Headers` customization to your `settings.py` file, as seen below:

```python
"""Spider settings"""

from typing import AnyStr
from scrapy.http.headers import Headers

SPIDER_MODULES = ["app.spiders"]
CONCURRENT_REQUESTS = 32

def case_sensitive_normkey(self, key: AnyStr) -> bytes:
    # return self._tobytes(key.title())
    return self._tobytes(key)

Headers.normkey = case_sensitive_normkey
```
