### ISSUE TITLE
ImagesPipeline does not follow redirection

### ISSUE THREAD

**Issue by rsarky** [scrapy/scrapy#3995]
### Description

This issue was already reported #2397 but the reporter closed the issue after posting a temporary fix. I reckon there should be an elegant way to hande this as this is a common use case I guess. Maybe a configurable setting that allows image to be downloaded even when the URL is redirected.

**Comment by OmarFarrag** [comment]
@rsarky https://docs.scrapy.org/en/latest/topics/media-pipeline.html#allowing-redirections Is this what you mean ?

**Comment by rsarky** [comment]
Oh this seems like exactly what I needed.
Thanks!
