### ISSUE TITLE
Random(?) test_crawler.py failure on Travis

### ISSUE THREAD

**Issue by elacuesta** [scrapy/scrapy#4014]
Every now and then the Travis build fails on [`tests.test_crawler.CrawlerRunnerTestCase.test_deprecated_attribute_spiders`](https://github.com/scrapy/scrapy/blob/1.7.3/tests/test_crawler.py#L173), I'm not sure why.
Some examples:
* https://travis-ci.org/scrapy/scrapy/jobs/582184413#L407
* https://travis-ci.org/scrapy/scrapy/jobs/580207692#L419
* https://travis-ci.org/scrapy/scrapy/jobs/584701732#L415
* https://travis-ci.org/scrapy/scrapy/jobs/584762868#L418

PS: Sorry, I feel bad for ignoring the bug report template, but I felt like it didn't apply in this case.

**Comment by elacuesta** [comment]
Another victim: https://travis-ci.org/scrapy/scrapy/jobs/584701732#L415

**Comment by s-sanjay** [comment]
for some reason github search did not give me any result when I searched test_deprecated_attribute_spiders so I opened the other issue. hoping this comment gets indexed by github

**Comment by elacuesta** [comment]
@s-sanjay That's ok, I only included the full path in the description after seeing your issue. Thanks!

**Comment by elacuesta** [comment]
A different error on [`tests.test_spider.CrawlSpiderTest.test_process_request_instance_method`](https://github.com/scrapy/scrapy/blob/1.7.3/tests/test_spider.py#L328): https://travis-ci.org/scrapy/scrapy/jobs/593353901#L414

**Comment by s-sanjay** [comment]
do these tests run in parallel ? also what does the percentage value next to each test mean ?

**Comment by s-sanjay** [comment]
let me try to run in the same environment using the same HASHSEED

**Comment by s-sanjay** [comment]
the flakiness is happening due to this
```

**Comment by s-sanjay** [comment]
@Gallaecio so when tests fail due to some other issue re running them is great but shouldn't we as much as possible prevent flakiness from being introduced.. as a last resort we can re run them but if we re run would it not also delay fixing the reasons for flakiness ?

**Comment by Gallaecio** [comment]
@s-sanjay I was suggesting that as a temporary measure, to avoid new contributors from getting hit by this and us having to explain to them that the issue is in Scrapy and not in their changes.

In any case, #4095 should have fixed the actual issue.
