### ISSUE TITLE
how to disable the log information when a return/yield of an item from a parse of spider?

### ISSUE THREAD

**Issue by loveJasmine** [scrapy/scrapy#4026]
it looks very lousy print out on terminal when I use return/yield,
however,since it a lot of other infor are helpful I won't change the log level to suppress it.

Is there anyway to disable the print of return/yield of parse without change log level?

class ZixunhtmlSpider(scrapy.Spider): 
    name = 'zixunHtml'
    allowed_domains = ['xxxx.com']
    start_urls = []

    with open("G:/crawl_data/choice/obsolete/zixun_temp.txt", 'r', encoding='utf-8') as fgg:

        for line in fgg:
              start_urls.append(line)

    def parse(self, response):
        ex = ''
        if response.status != 200:
            ex = 'None 200 happens!'
        else:
            ex = response.text

        output[response.url] = ex
        print("===========================================\n")
        #return output
        yield output

**Comment by Gallaecio** [comment]
Please, use [StackOverflow](https://stackoverflow.com/tags/scrapy) to ask this type of questions. See [Getting Help](https://docs.scrapy.org/en/latest/#getting-help).
