### ISSUE TITLE
Upgrading from 1.4 to 1.5 results in many 400 responses

### ISSUE THREAD

**Issue by Gallaecio** [scrapy/scrapy#4027]
@stav has a project where upgrading from Scrapy 1.4 to Scrapy 1.5 resulted in many 400 responses, and going back to Scrapy 1.4 solved the issue.

Someone else (Alejandro Marti) saw the same in a different project, so it seems confirmed. Now we need to figure out why.

@kmike mentioned it *may* be related to #2743 and #2767.

**Comment by Gallaecio** [comment]
@stav If you have any additional information about this issue that may be shared publicly, please feel free to add it here.

**Comment by nyov** [comment]
Since this seems to be communicated internally, has it perhaps been resolved?

**Comment by Gallaecio** [comment]
I’m not sure it has been, but I could not get any more feedback, so I’m closing this.
