### ISSUE TITLE
CLOSESPIDER_TIMEOUT Settings 36000 Invalid Settings 60 ok ?

### ISSUE THREAD

**Issue by kjxy** [scrapy/scrapy#4035]
### Description

CLOSESPIDER_TIMEOUT Settings 36000 run for five days...
CLOSESPIDER_TIMEOUT Settings 60 closespider_timeout(is ok)

### Steps to Reproduce

custom_settings = {
        "CLOSESPIDER_TIMEOUT": 60,
}

**Comment by Gallaecio** [comment]
Is there anything in the logs at the point where the spider should have stopped? (after 10 hours)

**Comment by kjxy** [comment]
> Is there anything in the logs at the point where the spider should have stopped? (after 10 hours)

So far everything has been normal（running）.

But start and end time much the same ，matter run for seven days...That is to say, from the point of view of the log, it only runs for a few hours.

**Comment by Gallaecio** [comment]
> from the point of view of the log, it only runs for a few hours.

Could you elaborate? How is that possible? Did the logging stop at some point?

**Comment by kjxy** [comment]
> > 从日志的角度来看，它仅运行几个小时。
> 
> 您能详细说明一下吗？那怎么可能？日志记录在某个时候停止了吗？

log file : [https://github.com/kjxy/wjselenium/blob/master/192adf02da9211e99cb20242ac110009.log](url)

Judging from the log file, it started running on the 19th. But does the log file not seem to be recorded today?

Moreover, through two Ctrl + C attempts to end the task, but unexpectedly got it ： 
```[scrapy.crawler] INFO: Received SIGTERM, shutting down gracefully. Send again to force 
 [scrapy.crawler] INFO: Received SIGTERM twice, forcing unclean shutdown``` ----From other log files

**Comment by Gallaecio** [comment]
OK, so the logs start at `2019-09-19 12:01:15`. Can you share some logs around `2019-09-19 22:01:15` (10 hours later)? Can you also share some of the log lines surrounding the `SIGTERM` lines you mention? (it’s not clear to me from your message whether the spider actually stopped after pressing Ctrl+C the second time or it continued nonetheless)

**Comment by kjxy** [comment]
> OK, so the logs start at `2019-09-19 12:01:15`. Can you share some logs around `2019-09-19 22:01:15` (10 hours later)? Can you also share some of the log lines surrounding the `SIGTERM` lines you mention? (it’s not clear to me from your message whether the spider actually stopped after pressing Ctrl+C the second time or it continued nonetheless)

This log file is complete：[https://github.com/kjxy/wjselenium/blob/master/192adf02da9211e99cb20242ac110009.log](url)

From the start time and the last time, there are not ten hours.But in fact, the program has been running for several days.

Press Ctrl+c twice after , records stop in this line ：`[scrapy.crawler] INFO: Received SIGTERM, shutting down gracefully. Send again to force [scrapy.crawler] INFO: Received SIGTERM twice, forcing unclean shutdown` the file was deleted.If necessary, I'll retest it again.

**Comment by Gallaecio** [comment]
We would need a log that spans more than the specified `CLOSESPIDER_TIMEOUT` value.

> I'll retest it again.

If you can reproduce the issue, please try to get a complete log. It would also be great if you could reproduce the issue with a simplified version of your spider, one that does not use any external or custom middlewares or extensions. Even greater if you could share the code of that simplified spider.
