### ISSUE TITLE
python3.6 start_requests method can not concurrently reques

### ISSUE THREAD

**Issue by daidai5771** [scrapy/scrapy#4038]
I rewrote the start_requests method, such as :
   def start_requests(self):
        for (click_type, url, css_path) in self.start_urls:
            print (url)
            yield Request(url, callback=self.loop_parse, dont_filter=True)

The effect of execution under Python 2.7 is as follows:
"
http://www.flyme.cn
https://cloud.flyme.cn
http://www.meizu.com
http://open.flyme.cn
https://member.meizu.com/uc/webjsp/member/detail
http://app.meizu.com/apps/public/index
http://app.meizu.com/apps/public/index
http://app.meizu.com/apps/public/index
http://app.meizu.com/apps/public/index
http://app.meizu.com/apps/public/index
http://app.meizu.com/apps/public/index
"

But it got stuck behind http://www.flyme.cn at Python 3.6 , Only one request can be sent at a time

**Comment by Gallaecio** [comment]
Please, use [StackOverflow](https://stackoverflow.com/tags/scrapy) to ask this type of questions. See [Getting Help](https://docs.scrapy.org/en/latest/#getting-help).
