### ISSUE TITLE
Scrappy don't call the first request

### ISSUE THREAD

**Issue by anhtuanmanga** [scrapy/scrapy#4044]
I have problem when call two request in parse function
here is my code
`import re
import logging
import os
import scrapy

from scrapy import Spider
from scrapy.selector import Selector

class StackSpider(Spider):
    name = "batdongsan"
    allowed_domains = ["batdongsan.com.vn"]
    start_urls = [
        "https://batdongsan.com.vn/nha-dat-ban",
    ]
    url_prefix = ""
    url_last = ""
    max = ""
    next_page = ""
    count = 1

    def parse(self, response):
        # questions = Selector(response).xpath('//div[@class="p-title"]/h3')
        # # This part of code collect only titles. You need to add more fields to be collected if you need.
        # for question in questions:
        #     title = question.xpath(
        #     	'a/text()').extract_first().encode('utf-8').strip()
        #     with open('title.txt', 'a') as f:
        #         f.writelines(title+'\n')
        #     # yield {'title': title}
        # block 1
        yield scrapy.Request(response.url, callback=self.detail_page)

        # block 2
        if not re.search(r'\d+', response.url):
            # Now we have to go th
            url_last = response.css('div.background-pager-right-controls a::attr(href)').extract()[-1]
            max = re.findall(r'\d+', url_last)[0]
            for n in range(2, int(max) + 1):
                next_page = self.start_urls[0] + '/p' + str(n)
                yield response.follow(next_page, callback=self.parse)

    def detail_page(self, response):
        detail_pages = Selector(response).xpath('//div[@class="p-title"]/h3/a')
        for detail_page in detail_pages:
            urlpage = detail_page.xpath(
                '@href').extract_first().strip()
            page = self.start_urls[0] + urlpage
            yield scrapy.Request(page, callback=self.export)

    def export(self, response):
        title = Selector(response).xpath(
            '//*[@id="product-detail"]/div[1]/h1/text()').extract_first().encode('utf-8').strip()
        with open('title.txt', 'a') as f:
            f.writelines(title + '\n')
        place = Selector(response).xpath(
            '//*[@id="product-detail"]/div[8]/div/div[1]/div/div[2]/div[2]/div[2]/text()'
        ).extract_first().encode('utf-8').strip()
        with open('title.txt', 'a') as f:
            f.writelines(place + '\n')
`
when i run both block 1 and 2 in cmd screen scrappy only load url get from block 2 but when i comment code in block 2, code in block 1 run normall.
can everyone help me why this happen and how to fix this?
sorry for my crappy english.

**Comment by Gallaecio** [comment]
Please, use [StackOverflow](https://stackoverflow.com/tags/scrapy) to ask this type of questions. See [Getting Help](https://docs.scrapy.org/en/latest/#getting-help).
