### ISSUE TITLE
Unaccounted time consumed by scrapy crawl which is not listed in stats

### ISSUE THREAD

**Issue by DharmeshPandav** [scrapy/scrapy#4060]
I have been trying to run a scrapy crawl in a time constrained envrionment where we want to make sure that scrapy stops after fixed run time limit.

We have set the following `CLOSESPIDER_TIMEOUT` as 60 seconds and `DOWNLOAD_TIMEOUT` as 30 seconds.

We have set the forceful termination (kill the subprocess) at 90 seconds to cover the edge case scenario if page request is made at 59 seconds and twisted fails to download page and download timeout signal is triggred. ( 59 + 30 = 89 < 90 seconds)

but still scripts runs for random amount of time. range is between 95-115 seconds.

I am not sure where this variable 5-30 seconds are being used and why scrapy is failing to close gracelully after 90 seconds as expected

is this the default and accepted behaviour in scrapy/twisted reactor architecture where this lag is being introduced
or if any setting is there to override this behavior 

Thanks

**Comment by Gallaecio** [comment]
The expected behavior is that, between the spider opening (which happens after all extensions have been loaded, the logs indicate when the spider actually opens) and the spider closing (which does not stop Scrapy right away, as a clean closing can take several seconds).

Check the logs, locate the lines that indicate when the spider opens and when the spider closes, and check the time passed between them according to the logs. It should be close to your `CLOSESPIDER_TIMEOUT` value.

We’ve recently got a report about `CLOSESPIDER_TIMEOUT` not working, #4035, but it has not been confirmed yet, and the report mentions that low values like `60` do work.

**Comment by Gallaecio** [comment]
You’ve also asked this in StackOverflow, so I’m including the link here for reference: https://stackoverflow.com/q/58234797/939364

We usually close this type of issues and suggest people to go to StackOverflow, but I left this open in case what I suggested is not true, which _may_ mean there is a bug somewhere.

Looking forward to your feedback.

**Comment by DharmeshPandav** [comment]
I  have noticed the same behaviour across multiple spider that we ran 
if we hit 503 anywhere
it will take time between 91 - 115 seconds before scrapy closes gracefully 

if all 200 http status 
it will take time between 61-63 seconds to complete

**Comment by DharmeshPandav** [comment]
> You’ve also asked this in StackOverflow, so I’m including the link here for reference: https://stackoverflow.com/q/58234797/939364
> 
> We usually close this type of issues and suggest people to go to StackOverflow, but I left this open in case what I suggested is not true, which _may_ mean there is a bug somewhere.
> 
> Looking forward to your feedback.

`closespider_timeout` signal is always triggered at 60 seconds as per the settings

couple of seconds to close cleanly after that is expected but it is taking really long in case of 503'd http requests

**Comment by Gallaecio** [comment]
That is expected. You might be able to reduce the cleanup time by setting a low timeout for requests, but you might not want to do that.

I think you will have to choose between closing this issue (works as expected) or keeping it open as a request to allow closing the spider uncleanly in this scenario.

However, if closing the spider uncleanly is an option, that can be done from outside Scrapy by killing the process, so I don’t see much benefit in such a feature.

**Comment by DharmeshPandav** [comment]
yeah - closing it uncleanly will cause other problem like "stats" will not be available and output feed stream may be broken..etc

will play with other setting and increasing time before force killing the process 

Thanks for looking into this.. this was not and issue and not really a question and was split between where to post this SO or Github

it would be really help full to understand what operations scrapy performs before it closes gracefully

**Comment by DharmeshPandav** [comment]
### works as expected 
@Gallaecio  don't hae permission to add tag "Works as expected"
