### ISSUE TITLE
BOT_NAME and the user agent

### ISSUE THREAD

**Issue by mohmad-null** [scrapy/scrapy#4072]
The docs for `BOT_NAME` say that it is used for the User agent (https://docs.scrapy.org/en/latest/topics/settings.html#std:setting-BOT_NAME) :

> This will be used to construct the User-Agent by default, and also for logging.

However in reality it is not. Scrapy is using the user agent:
`"Scrapy/1.7.3 (+https://scrapy.org)"`

Setting `USER_AGENT` does change the user agent correctly.

**Comment by Gallaecio** [comment]
Fixed by #4081
