### ISSUE TITLE
Middleware - unused arguements

### ISSUE THREAD

**Issue by mohmad-null** [scrapy/scrapy#4073]
Lets say I have a simple piece of middleware that discards urls that have a bad extension:

```
class IgnoreTheseLinkTypes(object):
	@staticmethod
	def process_request(request, spider):

		if not acceptable_extension(request):
			raise exceptions.IgnoreRequest
```

The middleware works fine, but my IDE is correctly complaining at inspection time that I have an unused argument (`spider`).

So I change `spider` to be `_` to represent the fact it is unused per Python best-practice. But now the middleware never gets invoked.
It would be nice if Scrapy could handle this scenario so I could have cleaner code.

**Comment by Gallaecio** [comment]
What about https://stackoverflow.com/a/14836005/939364 ?

**Comment by mohmad-null** [comment]
It'll probably work but it's not elegant.

**Comment by elacuesta** [comment]
@mohmad-null `process_request` methods pass `Request` and `Spider` objects as keyword arguments ([source](https://github.com/scrapy/scrapy/blob/1.8.0/scrapy/core/downloader/middleware.py#L38)). For this reason, using either `_` or `*_` in the function definition will break with `TypeError: process_request() got an unexpected keyword argument 'spider'`. However, using `**_` does work, i.e. `def process_request(self, request, **_)`.
What do you think about it? Would you suggest an alternative way?

**Comment by mohmad-null** [comment]
> However, using **_ does work, i.e. def process_request(self, request, **_)

I can confirm this works. Maybe it's worth documenting somewhere? It's not a feature of Python I've ever used before.
