### ISSUE TITLE
Successfully installed Scrapy but when I am trying to launch it is throwing a fatal error.

### ISSUE THREAD

**Issue by ankushreddy** [scrapy/scrapy#4075]
### Description

I have installed scrapy but when I run any command related to scrapy like scrapy -v or scrapy start project is is throwing a fatal error I tried multiple ways like re-installing anaconda and all but nothing worked.

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/15848115/66717052-c6f5e780-eda2-11e9-92dd-e1a5c93f2090.png)

### Versions
python 3.7 version.
Unable to run any commands related to scrapy at all but have installed scrapy.

**Comment by Gallaecio** [comment]
Did you install Scrapy following the [official installation instructions](https://docs.scrapy.org/en/latest/intro/install.html#windows)?

**Comment by wRAR** [comment]
Hi @ankushreddy , can you provide more info or should we close this?
