### ISSUE TITLE
Docs: Broken link on developer-tools

### ISSUE THREAD

**Issue by tasawar-hussain** [scrapy/scrapy#4076]
### Link broken to http://quotes.toscrape.com/scroll on developer-tools docs

The link quotes.toscrape.com/scroll on developer-tools docs opens incorrect page and thus returns 404

### Steps to Reproduce

1. Navigate to https://docs.scrapy.org/en/latest/topics/developer-tools.html#the-network-tool
2. Click the link `quotes.toscrape.com/scroll` on end of first paragraph.

**Expected behavior:** It should naigate to http://quotes.toscrape.com/scroll

**Actual behavior:** It navigates to https://docs.scrapy.org/en/latest/topics/quotes.toscrape.com/scroll/

**Reproduces how often:** 100%

### Versions

Please paste here the output of executing `scrapy version --verbose` in the command line.
Scrapy       : 1.7.3
lxml         : 4.4.1.0
libxml2      : 2.9.9
cssselect    : 1.1.0
parsel       : 1.5.2
w3lib        : 1.21.0
Twisted      : 19.7.0
Python       : 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21) - [GCC 7.3.0]
pyOpenSSL    : 19.0.0 (OpenSSL 1.1.1c  28 May 2019)
cryptography : 2.7
Platform     : Linux-4.15.0-65-generic-x86_64-with-debian-buster-sid

**Comment by wRAR** [comment]
Already fixed: http://docs.scrapy.org/en/master/topics/developer-tools.html#the-network-tool
