### ISSUE TITLE
Error when run Scrapy 1.7.3 with python 3.6 on Windows

### ISSUE THREAD

**Issue by 040840308** [scrapy/scrapy#4082]
Hi, everyone

     I want to download some firmware images. My snippet code in the get_media_request is as follows:
     url='http://luyou.dl.qihucdn.com/luyou/360P4C/360-P4C-V2.0.4.59512.bin'
     return scrapy.http.Request(url, meta={"vendor": item["vendor"]})

     However, error happens as follows:
     [(False, <twisted.python.failure.Failure builtins.TypeError: Unicode-objects must be encoded before hashing>)]

     Does some know how to deal with this?
     Thanks for any help.

**Comment by Gallaecio** [comment]
Please, use [StackOverflow](https://stackoverflow.com/tags/scrapy) to ask this type of questions. See [Getting Help](https://docs.scrapy.org/en/latest/#getting-help).
