### ISSUE TITLE
Cookies in <Request> seems not working

### ISSUE THREAD

**Issue by BreezeFreak** [scrapy/scrapy#4084]
Hi!
I am writing a `<Spider>`, and after login success, I try to send a `<FormRequest>` by the response from `<parse_login>`. 
I got cookies from it, and tried to add it into `<FormRequest>`, but it failed, which causes a redirection to login page.

```py
# here is the method after login
def query_form(self, response: scrapy.http.Response):
    return [FormRequest(
        url=url,  
        cookies=cookies,
        meta={'cookiejar': response.meta['cookiejar']},
        method='POST',
        headers=self.headers,
        formdata={
            'app_name': '',
            'begin_date': str(self.start_date),
            'end_date': str(self.start_date),
        },
        callback=self.parse_page,
        dont_filter=True
    )]
```
```bash
# and here is the console log
DEBUG [19-10-21 14:47:54] scrapy.downloadermiddlewares.redirect _redirect :43 Redirecting (302) to <GET *************> from <POST *************>
# redirect from expected url to login page, as I think and test in post man and shell, this happened when giving wrong cookies or without cookies
```

but when I try it in `<requests.request()>` with cookies, I can get the direct page content.

```py
res = requests.request(method='POST', cookies=cookies, url=url)
print(res.cookies)
print(res.content)
print(res.text)
```

I could really use your help, maybe stupidly I forgot some details. Thanks!

**Comment by wRAR** [comment]
Unless you are sure you found a bug in scrapy please use dedicated support resources such as https://stackoverflow.com/ to get help with your code.

**Comment by BreezeFreak** [comment]
Sorry... I am a noob here. Thanks for your reminder and advice
