### ISSUE TITLE
Make Python 3.8 support official

### ISSUE THREAD

**Issue by Gallaecio** [scrapy/scrapy#4085]
This involves, among other things:
- Enabling a Python 3.8 environment in Tox
- Enabling a Python 3.8 job in the Travis CI
- Updating the `setup.py` file

**Comment by wRAR** [comment]
Does Travis already support it?

**Comment by wRAR** [comment]
According to https://docs.travis-ci.com/user/languages/python/ it does

**Comment by illgitthat** [comment]
I am trying to install scrapy for python 3.8 in a Windows environment. Are there currently any ways I can do this? Or is this blocked upstream by conda https://github.com/conda/conda/issues/9343

**Comment by Gallaecio** [comment]
> I am trying to install scrapy for python 3.8 in a Windows environment. Are there currently any ways I can do this? Or is this blocked upstream by conda [conda/conda#9343](https://github.com/conda/conda/issues/9343)

You can try using `pip`. If you cannot get it to work with `pip`, then you’ll need to wait for Conda to support Python 3.8.

**Comment by further-reading** [comment]
Hey! I'll grab this one if it is okay?

**Comment by illgitthat** [comment]
> > I am trying to install scrapy for python 3.8 in a Windows environment. Are there currently any ways I can do this? Or is this blocked upstream by conda [conda/conda#9343](https://github.com/conda/conda/issues/9343)
> 
> You can try using `pip`. If you cannot get it to work with `pip`, then you’ll need to wait for Conda to support Python 3.8.

No luck using just `pip install scrapy` unfortunately.

**Comment by diegovincent** [comment]
Installing Python 3.8.0 and immediately later `scrapy` fails. 

Here's the commands used:

```bash
pip install python=3.8.0
pip install scrapy
```

My workstation: `4.19.79-1-MANJARO GNU/Linux`

The log itself: https://pastebin.com/cAawd2jB

**Comment by wRAR** [comment]
@diegovincent this is not related to Scrapy, the log shows a problem with compiling lxml.

**Comment by diegovincent** [comment]
@wRAR But why would that happen? is `lxml` not "ready" for 3.8? But after all, scrapy depends on the `lxml` library, so it might be a good idea to have it here?

**Comment by wRAR** [comment]
@diegovincent your compiler toolchain seems broken, and no, this is not a good place to discuss problems with installing third-party modules.

**Comment by diegovincent** [comment]
I used Anaconda. 

And ok, I won't discuss it anymore here, but FYI the error seems to persist even after [`conda` officially supports 3.8.0](https://anaconda.org/anaconda/python).

**Comment by Gallaecio** [comment]
> I won't discuss it anymore here

Feel free to create a separate issue about it.
