### ISSUE TITLE
OffsiteMiddleware doesn't seem to work properly

### ISSUE THREAD

**Issue by django-kz** [scrapy/scrapy#4087]
I am just learning your great library, but as I got OffsiteMiddleware doesn't filter out all foreign links. 
1. For example, I am scrapping "whitneymiller.com" website, I am collecting all "a" tags within pages and putting them into parse method
```
def parse(self, response):
        self._parsed_urls.append(response.url)
        print("Parsing: ", response)
        sel = Selector(response)
        urls = sel.xpath("//*/a/@href").extract()
        for url in urls:
            full_url = response.urljoin(url)
            print("Requesting crawl of: ", full_url)
            self._requested_urls.append(full_url)
            yield scrapy.Request(response.urljoin(url), callback=self.parse)

```
-->

2. my settings for spider are as follows : 
```
process = CrawlerProcess({
        'LOG_LEVEL': 'CRITICAL',
        'DEPTH_LIMIT': 100,
        'DEPT_STATS': True,
        'CONCURRENT_REQUESTS_PER_DOMAIN': 10,
        'DOWNLOADER_MIDDLEWARES':
            {
                "scrapy.downloadermiddlewares.retry.RetryMiddleware": 500,
                "scrapy.spidermiddlewares.offsite.OffsiteMiddleware": 550
            },
    })
```

and allowed domains are : 
`    allowed_domains=['whitneymiller.com']
`

3. As I see my crawler parses links like "https://www.linkedin.com/cws/share?token&isFramed=false&url=https%3A%2F%2Fwhitneymiller.com%2Frecipe%2Fsmoked-chicken-wings-with-caramelized-onions%2F"

Am I doing something wrong or for OffsiteMiddleware links like that looks local for the specified domain?

**Comment by Gallaecio** [comment]
Make sure `allowed_domains` is defined as a variable of your `Spider` subclass.

If that is not the issue, please use [StackOverflow](https://stackoverflow.com/tags/scrapy) to ask for help, and make sure you provide some code to reproduce your issue as per https://stackoverflow.com/help/mcve (you are close, but it’s not clear from your code here where you are placing `allowed_domains`, for example). See [Getting Help](https://docs.scrapy.org/en/latest/#getting-help).

**Comment by kenfehling** [comment]
I also just ran into this issue. You're right, the regular expression simply looks for the presence of the domain anywhere in the URL. I'm not sure if this was done for a specific reason? This is the code in question:
https://github.com/scrapy/scrapy/blob/master/scrapy/spidermiddlewares/offsite.py#L72

**Comment by kenfehling** [comment]
I'm pretty sure you're running into this issue: https://github.com/scrapy/scrapy/issues/15
