### ISSUE TITLE
Translating the docs to Korean

### ISSUE THREAD

**Issue by Arielalfm** [scrapy/scrapy#4105]
Hello!
My team (created in a lecture called 'open source software' which I take in) is very interested in scrapy, but necessarily files need to be read (like README and LICENSE) are written only in English. We thought if these files are translated, more people like us can contribute to this project.

So I'm just wondering if we can join here:)

**Comment by Gallaecio** [comment]
Related to #3511

**Comment by Arielalfm** [comment]
Thanks!!

**Comment by Gallaecio** [comment]
Closing in favor of #3511
