### ISSUE TITLE
LogStats Extension should log the IPM and RPM to the stats on spider_closed signal

### ISSUE THREAD

**Issue by BurnzZ** [scrapy/scrapy#4110]
## Summary

By default, the `scrapy.extensions.logstats.LogStats` log the details below to the standard logger every 60 seconds:

- IPM (_Items per Minute_)
- Items scraped
- RPM (_Requests per Minute_)
- Requests produced

## Motivation

We often find the need to retrieve the **RPM** and **IPM** after a job is finished. We can calculate this manually or we can check the logs for the last update of *LogStats*. However, this is tedious and inefficient as `LogStats` already has this data but isn't putting them somewhere that is readily available after the job is finished.

## Describe alternatives you've considered

We can pull out the last update of `LogStats` from the logs but pulling it from the API and filtering it out is expensive.

## Additional context

None

**Comment by BurnzZ** [comment]
Hi @wRAR , yes that's the idea. Although the speed from the last log printed won't be as accurate when the spider ends the crawl. This is because the logging mechanism at the moment only happens every *60 seconds*. If the spider ends before this looping interval, like in the middle, say 30 seconds, it won't log the IPM and RPM.

In the current PR, the IPM and RPM will be logged to the stats upon spider close. It should be much closer to the speed presented by Scrapy Cloud in most cases.

**Comment by Gallaecio** [comment]
Hmm… For logging purposes, shouldn’t we store all the historical calculations and log the average of the whole run?

**Comment by BurnzZ** [comment]
@Gallaecio Not quite. To paint the scenario, let's discuss some examples over the current behavior of `LogStats`.

`LogStats` record the _RPM_ and _IPM_ during `spider_opened` We can observe these types of log messages on spider runs:
`[scrapy.extensions.logstats] Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)`

If we'll be **averaging** historical calculations, having a `0` in the data would lower the resulting average. Suppose we have a spider than runs for exactly **5:00 mins** and has **1000 items** and **requests**. Given these info, we can calculate the stats for the whole run to be **200 RPM** and **200 IPM**.

However, the recorded speed by `LogStats` is calculated below that has a different result:

![image](https://user-images.githubusercontent.com/3449761/68000516-6704a980-fc9b-11e9-8fef-9834301614a9.png)

We can remove the initial log of **0** in order to fix the average speed. I'm not sure if someone is relying on this first log though.

Lastly, I don't think it's worth storing all of the historical calculations though as `LogStats` could simply compute the current speed via this block: https://github.com/scrapy/scrapy/blob/master/scrapy/extensions/logstats.py#L38-L42

**Comment by Gallaecio** [comment]
#4111 would log `100` in this case, right? Shouldn’t we instead log the totals divided by the run time (200 in this case)?

**Comment by BurnzZ** [comment]
Ahhh I see what you mean now @Gallaecio. Great catch! 🎉 I've updated the PR now for this new approach. :) Let me know what you think. If all is good with this approach I'll proceed in writing the tests.
