### ISSUE TITLE
Hi~ How can I find 'Scrapy Docs' in 'Transifex' manager or administrator ? 

### ISSUE THREAD

**Issue by lionking6792** [scrapy/scrapy#4127]
Hi I'm looking for 

https://www.transifex.com/scrapy-translation-team/scrapy-docs-translation/

manager or administrator..

I am interested in translating scrapy docs in Korean but, nobody seems to response Transifex.
How can I get contact?
If anybody knows it Please reply to me..

Thanks for reading :)

Related to #3511 and #4105.

**Comment by Gallaecio** [comment]
@kmike Is that handled by us or someone we know? Are we using the translations?

**Comment by lionking6792** [comment]
@Gallaecio Thanks for comment. You mean scrapy dosen't have any translation documents? How about creating new branch or new repository for docs?

**Comment by Gallaecio** [comment]
@lionking6792 Documentation translation is not possible at the moment, that why #3511 is still open. That’s something we need to implement.

Maybe we should close this and #4105 and leave only #3511 open to track progress on this.

**Comment by lionking6792** [comment]
@Gallaecio Sure, Thanks for comments anyway :)
