### ISSUE TITLE
Handle it gracefully when start_url is used instead of start_urls

### ISSUE THREAD

**Issue by Gallaecio** [scrapy/scrapy#4133]
Over the last year I’ve seen a few cases ([recent example](https://stackoverflow.com/q/58664004/939364)) of this, people missing the `s` at the end of the `start_urls`.

It may be nice to find a way to gracefully let the developer know where the issue is, why there is no crawling happening.

**Comment by Kunal614** [comment]
As in the scrappy many files are autogenerated when you start a new project and there start_urls is already declared by default , so if we use start_url instead of start_urls then there would be no crawling.
