### ISSUE TITLE
Is image download disabled by default ?

### ISSUE THREAD

**Issue by ishandutta2007** [scrapy/scrapy#4144]
I have written a spider which consumes almost 2 GB of data per hour. Now I want to save my data consumption, images are of no use for me, so want to make sure they not being fetched.

**Comment by Gallaecio** [comment]
Please, use [StackOverflow](https://stackoverflow.com/tags/scrapy) to ask this type of questions. See [Getting Help](https://docs.scrapy.org/en/latest/#getting-help).

**Comment by ishandutta2007** [comment]
@Gallaecio  Here is the link https://stackoverflow.com/questions/58801190/is-image-download-in-scrapy-disabled-by-default
Please answer it there if you prefer that way.

**Comment by ishandutta2007** [comment]
@Gallaecio Kindly address the stackoverflow question when you get time.

**Comment by Gallaecio** [comment]
@ishandutta2007 Kindly address the StackOverflow comments when you have the time :slightly_smiling_face:

**Comment by ishandutta2007** [comment]
already done, yes those has been marked as spam

**Comment by Gallaecio** [comment]
I agree with both StackOverflow comments. Scrapy does not download images unless you specifically tell it to do it. Please, answer the comments, they are not spam, they are valuable feedback from the Scrapy community that is trying to help you.

**Comment by ishandutta2007** [comment]
I don't know the answers, maybe you can help.
