### ISSUE TITLE
Allow objects instead of import strings in settings

### ISSUE THREAD

**Issue by Gallaecio** [scrapy/scrapy#4166]
Some settings, like `LOG_FORMATTER`, expect a import string as value.

I think it would be great if they also allowed the corresponding object itself.

For example, let users that are doing this:

```python
    class LogFormatter:
        pass

    class MySpider:
        custom_settings = {'LOG_FORMATTER': 'my_project.spiders.my_spider.LogFormatter'}
```

To do this instead:

```python
    class LogFormatter:
        pass

    class MySpider:
        custom_settings = {'LOG_FORMATTER': LogFormatter}
```

**Comment by elacuesta** [comment]
I think #3873 is in the right direction.

**Comment by Gallaecio** [comment]
Closing in favor of #3870
