### ISSUE TITLE
For gSoc 2020

### ISSUE THREAD

**Issue by Kunal614** [scrapy/scrapy#4168]
Can anyone give me idea , how i select scrapy in gsoc 2020, As i think it is very intresting stuff.

**Comment by Gallaecio** [comment]
Is a bit early to apply. Have a look at https://python-gsoc.org/ for details.

That said, if you want to select Scrapy in your application, it might help you if you start getting yourself familiar with the code base. For that, you could look into fixing some easy issues. See https://docs.scrapy.org/en/master/contributing.html for more information.

**Comment by Kunal614** [comment]
Thank you soo much sir for information .
kindly please help me for joining this organization.

**Comment by Kunal614** [comment]
One more thing , when i search for the organization in Gsoc site , I didn't get that scrapy.
so how can  i join.

**Comment by Gallaecio** [comment]
You are looking at the 2019 information. In Google Summer of Code 2019 Scrapy was part of the Python organization.

Again, to officially join Google Summer of Code 2020 you’ll need to wait student applications open, in 2020. In the meantime, see https://python-gsoc.org/#gettingstarted

**Comment by Kunal614** [comment]
I am beginner , so please help me in completing all the steps or how to get
start with organization.

**Comment by Gallaecio** [comment]
There are two things you can do in parallel at the moment:
- Wait until there is a “2020” somewhere in https://summerofcode.withgoogle.com/
- Start [contributing](https://docs.scrapy.org/en/master/contributing.html) small things to Scrapy, so that you are much better prepared to apply once student applications are open

**Comment by Kunal614** [comment]
Where should i contribute , in github scrapy organization ?
Or can you share a link where should i contribute.

**Comment by Kunal614** [comment]
can i contribute in this scrapy organization ?

**Comment by Gallaecio** [comment]
Yes, you can start contributing to https://github.com/scrapy/scrapy

You’ll find details on how to contribute at https://docs.scrapy.org/en/master/contributing.html

**Comment by Kunal614** [comment]
Thanks for all the informations , One more question can i do a pull request of those stuffs that i had made by using scrapy ?

**Comment by Gallaecio** [comment]
We don’t keep Scrapy projects in the Scrapy repository. But here are a few suggestions on things you can contribute:
- There are [a few good first issues tagged](https://github.com/scrapy/scrapy/labels/good%20first%20issue) that you can look at, although many already have a pull request.
- If you’ve noticed anything missing in the documentation or not explained in enough detail, documentation improvements are welcome as well. 
- Writing automated tests to increase [test coverage](https://codecov.io/gh/scrapy/scrapy/list/master/scrapy) can also be a great way to get yourself familiar with the code base.

**Comment by Kunal614** [comment]
can you elaborate third point ?

**Comment by Gallaecio** [comment]
In Scrapy we have automated tests, code that checks whether Scrapy functionality behaves as designed. We run the automated tests after every change, to make sure that changes do not break existing functionality.

You can find Scrapy’s automated tests in the `tests` folder.

Test coverage is data generated while running the automated tests that indicates which lines of the Scrapy codebase has been executed as part of one or more tests. This data allows us to find lines of code that we are not testing, and we can then write tests that cover them, that check that they work as expected.

In https://codecov.io/gh/scrapy/scrapy/list/master/scrapy you can browse the Scrapy files and see which lines of codes are covered by tests (in green), which lines are not covered (in red) and lines that contain both tested and untested code (in yellow).

You could try to write a test that reached a line that is currently red.

**Comment by Kunal614** [comment]
ohh thanks ..... that means doing correction  in the code someone , right.

**Comment by Kunal614** [comment]
when choosing of organization will start in gsoc?

**Comment by Gallaecio** [comment]
Sometime at the beginning of 2020

**Comment by Kunal614** [comment]
thanks for alll

**Comment by namanadlakha3** [comment]
Hey, I want to start contributing in scrapy. Can someone please guide me, how can i get started.
Thank you
