### ISSUE TITLE
Scrapy does not use a non-zero exit code when pipeline's open_spider throws the exception

### ISSUE THREAD

**Issue by gunblues** [scrapy/scrapy#4175]
### Description
In our case, we execute command `scrapy crawl` in airflow task and the exit code would be used to judge this task success or failure. I agree that `scrapy crawl` ignores spider exceptions because it's unpredictable in the crawling process. 

Back to our case, we export data to file or database in the pipeline and we create the directory or database connection in `open_spider(self, spider)`. I think if there is an exception happens during this function, it's reasonable to propagate a non-zero exit code. it because we normally do some initialization in this function.

### Steps to Reproduce

- scrapy startproject test_spider
- cd test_spider
- scrapy genspider example example.com
- modify spiders/example.py to  
```
# -*- coding: utf-8 -*-
import scrapy


class ExampleSpider(scrapy.Spider):
    name = 'example'
    allowed_domains = ['example.com']
    start_urls = ['http://example.com/']

    custom_settings = {
        'ITEM_PIPELINES': {
            'test_spider.pipelines.TestSpiderPipeline': 300
        }
    }

    def parse(self, response):
        pass
```
- modify pipelines.py to 
```
# -*- coding: utf-8 -*-

# Define your item pipelines here
#
# Don't forget to add your pipeline to the ITEM_PIPELINES setting
# See: https://docs.scrapy.org/en/latest/topics/item-pipeline.html


class TestSpiderPipeline(object):

    def open_spider(self, spider):
        raise Exception('error')

    def process_item(self, item, spider):
        return item
```
- scrapy crawl example
- echo $?  

**Expected behavior:** [What you expect to happen]
return non-zero exit code

**Actual behavior:** [What actually happens]
return zero exit code

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions
Scrapy       : 1.8.0
lxml         : 4.3.3.0
libxml2      : 2.9.9
cssselect    : 1.0.3
parsel       : 1.5.1
w3lib        : 1.20.0
Twisted      : 19.2.0
Python       : 3.7.3 (default, Mar 27 2019, 09:23:39) - [Clang 10.0.0 (clang-1000.11.45.5)]
pyOpenSSL    : 19.0.0 (OpenSSL 1.1.1b  26 Feb 2019)
cryptography : 2.6.1
Platform     : Darwin-18.5.0-x86_64-i386-64bit

### Additional context

I could get the expected behavior if I change `def run(self, args, opts)` in scrapy/commands/crawl.py  to 
```
    def run(self, args, opts):
        if len(args) < 1:
            raise UsageError()
        elif len(args) > 1:
            raise UsageError("running 'scrapy crawl' with more than one spider is no longer supported")
        spname = args[0]

        res = self.crawler_process.crawl(spname, **opts.spargs)

        if hasattr(res, 'result') and res.result is not None and issubclass(res.result.type, Exception):
            self.exitcode = 1
        else:
            self.crawler_process.start()

            if self.crawler_process.bootstrap_failed:
                self.exitcode = 1
```
original `def run(self, args, opts)`
```
    def run(self, args, opts):
        if len(args) < 1:
            raise UsageError()
        elif len(args) > 1:
            raise UsageError("running 'scrapy crawl' with more than one spider is no longer supported")
        spname = args[0]

        self.crawler_process.crawl(spname, **opts.spargs)
        self.crawler_process.start()

        if self.crawler_process.bootstrap_failed:
            self.exitcode = 1
```

Is it the proper way to modify the code for achieving this purpose? if it is, could I create a PR request for this issue?

**Comment by Gallaecio** [comment]
Would a **try..except** in your `open_spider` method that uses `sys.exit` in case of an exception achieve this purpose?

**Comment by gunblues** [comment]
@Gallaecio `sys.exit` doesn't work. I've tried before. thanks for your reply

**Comment by Gallaecio** [comment]
Oh, right, this is Twisted. See if [this](https://stackoverflow.com/q/5344123/939364) helps.

**Comment by gunblues** [comment]
> Oh, right, this is Twisted. See if [this](https://stackoverflow.com/q/5344123/939364) helps.

this doesn't work either. thanks for your suggestion
