### ISSUE TITLE
How to print Chinese/Japanese while yielding items in Scrapy?

### ISSUE THREAD

**Issue by mani619cash** [scrapy/scrapy#4189]
I tried `yield`ing `scrapy.Item` from Pipeline class and also tried `yield`ing dict directly 
but in console, it shows like `\uc18c\uac1c\uae30\uc0ac`

Whereas I print with `logging.info(item)` it shows Chinese/Japanese correctly

i tried 

    LOG_ENCODING = 'utf-8'

in `settings.py` but does not work

So, my question is, how do I make Scrapy print Chinese/Japanese characters in console when `yield`ing items?

**Comment by Gallaecio** [comment]
Please, use [StackOverflow](https://stackoverflow.com/tags/scrapy) to ask this type of questions. See [Getting Help](https://docs.scrapy.org/en/latest/#getting-help).
