### ISSUE TITLE
How to limit memory use when download big file

### ISSUE THREAD

**Issue by lizhaode** [scrapy/scrapy#4200]
### Description

when download big file, memory use high

### Steps to Reproduce

in my scenario, I will download video files, so the file is big, but my machine's memory only 1G with debian9 

so how to limit scrapy memory use? 

Thx

**Comment by Gallaecio** [comment]
I think we could close this in favor of #3880. The ability to stream responses would definitely allow downloading big files without taking a big memory hit.

**Comment by lizhaode** [comment]
> I think we could close this in favor of #3880. The ability to stream responses would definitely allow downloading big files without taking a big memory hit.

Yes, I agree, through `requests` , we can use `stream=True`  and `response.iter_content` to download big file to avoid use high memory, but I don't know how to use twisted to achive this

**Comment by lizhaode** [comment]
@Gallaecio 
Has any plan to impl this feature? Please told me, many thanks

**Comment by Gallaecio** [comment]
We definitely want to implement it eventually, but I am not aware of anyone who plans to work on it in the short term.
