### ISSUE TITLE
Does scrapy view uses active project settings

### ISSUE THREAD

**Issue by vionemc** [scrapy/scrapy#4202]
Does scrapy view uses active project settings? Especially middleware. I want to use scrapy fake user agent and scrapy crawlera on scrapy view.

**Comment by Gallaecio** [comment]
Please, use [StackOverflow](https://stackoverflow.com/tags/scrapy) to ask this type of questions. See [Getting Help](https://docs.scrapy.org/en/latest/#getting-help).
