### ISSUE TITLE
Crawled (404) But in the Browser is OK

### ISSUE THREAD

**Issue by BLACKDONGG** [scrapy/scrapy#4224]
When I use the scrapy to crawl the website get a 404!
But I have set USER_AGENT,
This is my scrapy spider's code：
# -*- coding: utf-8 -*-
import scrapy

class TestSpider(scrapy.Spider):
    name = 'Test'
    allowed_domains = ['https://y.qq.com']
    start_urls = ['https://y.qq.com/n/yqq/playlist/7323933054.html#stat=y_new.playlist.pic_click']
    header = {
        "Host": "c.y.qq.com",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0",
        "Accept": "*/*",
        "Accept-Language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
        "Accept-Encoding": "gzip, deflate, br",
        "Connection": "keep-alive",
        "Referer": "https://y.qq.com/n/yqq/playlist/7285677678.html",
    }
    cookie = {
        "token": "123455",
        "host": "tools.bugscaner.com",
        "username": "admin        Cookie: pgv_pvid=2208230034",
        "pgv_pvi": "3287928832",
        "ts_refer": "cn.bing.com/",
        "ts_uid": "3833260354",
        "LW_sid": "31f576o7u3b0A7W190C3B8w3E2",
        "LW_uid": "h1P5v6N7g3o0K619W3h6g3D5N0",
        "eas_sid": "b1u5x6h7D3k066F9q3N623K7z1",
        "RK": "cLjFSxBcMN",
        "ptcz": "58600459bc7cdadbe5d6c429daaa9f72f9918830ba490707e068292ea1879f6f",
        "yqq_stat": "0",
        "pgv_info": "ssid=s8260733988",
        "ts_last": "y.qq.com/portal/playlist.html",
        "pgv_si": "s709651456",
        "password": "7a57a5a743894a0e",
    }

    def start_requests(self):
        yield scrapy.Request(url=self.start_urls[0],callback=self.parse,headers=self.header,cookies=self.cookie,method="POST")

    def parse(self, response):
        print(response.text)
and the error:
DEBUG: Crawled (404) <POST https://y.qq.com/n/yqq/playlist/7323933054.html#stat=y_new.pla
ylist.pic_click> (referer: https://y.qq.com/n/yqq/playlist/7285677678.html)
2019-12-10 00:04:30 [scrapy.spidermiddlewares.httperror] INFO: Ignoring response <404 https://y.qq.com/n/yqq/playlist/7323933054.h
tml>: HTTP status code is not handled or not allowed

**Comment by Kunal614** [comment]
Is there any option for login on that page?

**Comment by Kunal614** [comment]
Go to setting.py and make
ROBOTSTXT_OBEY = False
 then try

**Comment by Gallaecio** [comment]
Please, use [StackOverflow](https://stackoverflow.com/tags/scrapy) to ask this type of questions. See [Getting Help](https://docs.scrapy.org/en/latest/#getting-help).
