### ISSUE TITLE
I have a problem with login in amazon using scrapy

### ISSUE THREAD

**Issue by Kunal614** [scrapy/scrapy#4232]
<pre>
import scrapy
from scrapy.http import FormRequest
from ..items import AmazonLoginItem
from scrapy.utils.response import open_in_browser

class amazon(scrapy.Spider):
    name='amazon'    
    start_urls=[
            'https://www.amazon.com/ap/signin?accountStatusPolicy=P1&clientContext=258-3200785-8273163&language=en_US&openid.assoc_handle=amzn_prime_video_desktop_us&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.mode=checkid_setup&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.ns.pape=http%3A%2F%2Fspecs.openid.net%2Fextensions%2Fpape%2F1.0&openid.pape.max_auth_age=0&openid.return_to=https%3A%2F%2Fwww.primevideo.com%2Fauth%2Freturn%2Fref%3Dav_auth_ap%3F_encoding%3DUTF8%26location%3D%252Fref%253Dav_nav_sign_in'
    ]
    page_number=2  
    def parse(self,response):
            
            token = response.css("form input::attr(value)").extract_first()
            print(token,"my name osm")
            return FormRequest.from_response(response,formdata={
                    'appActionToken':token,
                    'Email':'*********',
                    'password':'********'
            },callback=self.start_scrapping)
            
            
          
    def start_scrapping(self,response):
        open_in_browser(response)
        item = AmazonLoginItem()
        book_name= response.css('.a-color-base.a-text-normal').css('::text').extract()
        book_author=response.css('.a-color-secondary .a-size-base+ .a-size-base').css('::text').extract()
        book_price = response.css('.a-price-whole').css('::text').extract()
        k=0
        y=0
        

        for i in range(len(book_name)):
            item['book_name']=book_name[i]
            item['book_author']=book_author[k]
            item['book_price']=book_price[y]
            k+=1
            y+=1
            yield item
        next_page='https://www.amazon.in/s?k=books&page=' + str(amazon.page_number) +'&qid=1575269122&ref=sr_pg_2' 
        if amazon.page_number<=100:
            amazon.page_number+=1
            yield response.follow(next_page , callback = self.start_scrapping)

</pre>

**Comment by Kunal614** [comment]
In email and password i entered my email and password.

**Comment by noviluni** [comment]
Thanks for the code, but could you kindly put the error you had here too?

**Comment by Kunal614** [comment]
![Screenshot from 2019-12-15 14-09-36](https://user-images.githubusercontent.com/43969265/70868260-f2fd3700-1fa4-11ea-834f-e1608b0ee6b7.png)

**Comment by wRAR** [comment]
There is no errors in this log.

**Comment by Kunal614** [comment]
Then why image folder remains empty

**Comment by Kunal614** [comment]
Then what is the problem?

**Comment by elacuesta** [comment]
Please use the ["scrapy" tag at StackOverflow](https://stackoverflow.com/questions/tagged/scrapy) for questions like this. We use the GitHub issue tracker for bug reports and feature requests. See also: [Getting help](https://docs.scrapy.org/en/latest/#getting-help)
