### ISSUE TITLE
The line length is not consistent through the whole project

### ISSUE THREAD

**Issue by noviluni** [scrapy/scrapy#4234]
Before adding the flake8 checker, we were allowing any line length, recommending people to follow pep8 (79 characters) but allowing any length “if it improves readability”. 

When adding the flake8 checker we needed to add the E501 rule exception to most of the files (https://github.com/scrapy/scrapy/blob/master/pytest.ini), so technically, **now we are allowing any line length in those files and a line length of 79 characters in the other files**.

As this is bad for the code readability and maintenance (and **self-contradictory**), I think we should decide a clearer position of the line length for the entire project.

### Some possibilities are:
1. Allow **any length** in all the project (if that’s the case we can just ignore the E501 rule for the whole project).
2. Restrict to **79 characters** as PEP8 stands for.
3. Restrict to **another agreed length**.

In the 2nd and 3rd case it could be possible to allow longer lines individually (and not per file) by adding the `# noqa: E501` to the line.

### Looking at the project
To get a big picture of the issue I decided to check the current status of the project and I graphed this (please, obviate the y axis scale), that represents the line length frequency (for those lines with length > 79).

![graph](https://user-images.githubusercontent.com/22377678/70866912-a0555800-1f6f-11ea-90ed-6d5404b65b86.png)

When looking at the graph, it is curious to see that when arriving to the 110 characters it decreases a lot and that there is a “natural” end in about the 140 characters.

You can find here the full file list: https://gist.githubusercontent.com/noviluni/0993ac9d2cbdad12e84b8f5ba2a18d17/raw/d84c298645bd5d6b10545726c2292a417432888c/line_too_long_ordered.txt

##### 1. Allow any length
I think it’s obvious that this (and the current) option is the worst, as it allows some lines to be excessively long. Take this example: https://github.com/scrapy/scrapy/blob/c841a1f3e7c0d44b277dd42300948ba2f6109e67/tests/test_utils_sitemap.py#L26 that is 237 characters long without improving the readability (in fact, it gets worse).

#####  2. Restrict to 79 characters (PEP8)
Some maintainers have declared in the past that this is the prefered option, but that if the code readability improves we should allow longer lines. If we decide to follow this, **we should first decide or at least try to describe what does “improves the readability” mean** and allow only those cases to get a longer length by adding a `# noqa: E501` to those lines, avoiding the current status, where we allow all the file to have any line length.

##### 3. Restrict to another agreed length.
There are **several projects where the maintainers have decided to follow another line length**. 
* [Django](https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/coding-style/): “Don’t limit lines of code to 79 characters if it means the code looks significantly uglier or is harder to read. We allow up to 119 characters as this is the width of GitHub code review; anything longer requires horizontal scrolling which makes review more difficult.”
* [Flask](https://flask.palletsprojects.com/en/1.1.x/styleguide/): “79 characters with a soft limit for 84 if absolutely necessary”
* [Requests](https://requests.readthedocs.io/en/master/dev/contributing/): “Line-length can exceed 79 characters, to 100, when convenient. Line-length can exceed 100 characters, when doing otherwise would be terribly inconvenient.”
* [Pandas](https://pandas.pydata.org/pandas-docs/stable/development/contributing.html#bug-reports-and-enhancement-requests): “We restrict line-length to 80 characters to promote readability”
* [Black](https://black.readthedocs.io/en/stable/the_black_code_style.html): “Black defaults to 88 characters per line, which happens to be 10% over 80. This number was found to produce significantly shorter files than sticking with 80 (the most popular), or even 79 (used by the standard library). In general, 90-ish seems like the wise choice.”

On the other hand, some editors/IDEs (like Pycharm) default to 120 characters.

### My opinion
I personally like the **Django’s argument**, as it isn’t subjective, **it exposes a good and objective reason to limit the line length to 119 characters**. Moreover, after looking the graph it seems that **the “natural end” of the current codebase** is about that number.

I can understand that PEP8 purists could consider a sacrilege to allow all the lines to be longer than 79 characters by default, but I consider that the modern screens shouldn't have any problem to show them completely.

### Your opinion
**What do you think?** Is there any of the three proposals that fits the project? Do you have more arguments (**pros and cons**) or **another point of view**?

All feedback is welcomed :)

**Comment by wRAR** [comment]
Thank you for filing this. The maintainers are aware but we didn't decide on any value yet. 

I think the consensus is that we want a single specific value and that it shouldn't be too large like 120, but there was no strong and identical opinions whether it should be about 80, about 100 or something else.

**Comment by noviluni** [comment]
Hi @wRAR 
is good to know that the mantainers are already aware of this. However, I'm not sure what is blocking this to be decided...¿? 

I wrote arguments about why should this be addressed: lack of consistence through the code, maintaining difficulties, different rules per file in the flake8 pipeline (any length when the file has the rule E501 excluded, 79 characters when it hasn't)...

If you prefer not to discuss this publicly and decide it by the maintainers team it's ok, you can close the issue, but if you would like to get help to take the decission, it could be really fine if you explain:

* why "it shouldn't be too large like 120" (is there any rational/objective reason for that?)

and if you elaborate a little this: 
* "there was no strong and identical opinions" 

to know how can I help.

Thanks in advance :smile:

**Comment by wRAR** [comment]
> However, I'm not sure what is blocking this to be decided...¿?

Nothing, I think. It just needs to be done :)

> "it shouldn't be too large like 120" (is there any rational/objective reason for that?)

I don't remember the reasons to be honest, I'm personally fine with any line lengths.

> "there was no strong and identical opinions"

We just voiced our opinions and while everybody has some personal prefs, nobody strongly wanted  a certain value to be set for the project.

Oh, and there is another thing to consider: E501 is the most probable error to get for a random PR of a random person, and not everyone will run flake8 before submitting it, so I wonder what should be done to make it easier for new contributors.

**Comment by noviluni** [comment]
> Nothing, I think. It just needs to be done :)

> I don't remember the reasons to be honest, I'm personally fine with any line lengths.

> We just voiced our opinions and while everybody has some personal prefs, nobody strongly wanted a certain value to be set for the project.

Good to know!

> E501 is the most probable error to get for a random PR of a random person, and not everyone will run flake8 before submitting it, so I wonder what should be done to make it easier for new contributors.

It should be as easier as adding the line length decision here: https://docs.scrapy.org/en/latest/contributing.html#coding-style 

I think that it shouldn't be necessary to pass flake8 locally as it is included in the testing suite. If those random people write something liable to have a long line they should probably pass the tests locally and if they don't do it I think they would probably find the pipeline error and fix it.

In fact, we currently ask users to limit their line length when it's not necessary to be so long, but when fixing this it will be the pipeline, so no extra effort will be done.

**Comment by nyov** [comment]
My personal opinion is:

- Any but mobile device screens these days are widescreens (and those usually come with landscape mode switchers), but even 4:3 screens have more screen-width than height.
- Any sensible developer tool allows the use of that screen estate, so even with, say, side-by-side diffs one probably should have plenty screen for long lines.
- A whitespace-indent-level language like python, that also "requires" a 4-space indent according to pep8, shouldn't at the same time enforce a line limit of 72/79 chars; that's bad for indent-heavy lines.

So I would _prefer_ if we could stick with "sensible" default of "any reasonable length", making case-by-case decisions on that.

But 119 chars also feels plenty for use as a hard-limit, to me. I can agree to that.
However 79 feels rather draconian, with no reasonable hardware limitation behind it any more, and I don't agree with that pep8 rule.
That only encourages people to use non-descriptive short or one-char variable names, _and hurts legibility and quick code comprehension far worse_ than longer lines of text would, in my opinion.

But "sensible" or "reasonable", in my opinion also wouldn't apply to the quoted line of
https://github.com/scrapy/scrapy/blob/c841a1f3e7c0d44b277dd42300948ba2f6109e67/tests/test_utils_sitemap.py#L26
since that one could easily be pretty-printed to a much more _sensible_
```py
self.assertEqual(list(s), [{'changefreq': 'daily',
                            'lastmod': '2009-08-16',
                            'loc': 'http://www.example.com/',
                            'priority': '1'},
                           {'changefreq': 'weekly',
                            'lastmod': '2009-08-16',
                            'loc': 'http://www.example.com/Special-Offers.html',
                            'priority': '0.8'}])
```

**Comment by noviluni** [comment]
After merging this: https://github.com/scrapy/scrapy/pull/4237 I think we can finally close this 😄 

Thank you @elacuesta, @Gallaecio, @kmike, @wRAR and @nyov! ❤️
