### ISSUE TITLE
Problem in downloading the images using scrapy

### ISSUE THREAD

**Issue by Kunal614** [scrapy/scrapy#4235]
<pre>
import scrapy
from ..items import DownloadItem
from scrapy.utils.response import open_in_browser
from scrapy.loader import ItemLoader

class image(scrapy.Spider):
    name='image'
    allowed_domains=['www.google.com/search?biw=923&bih=759&tbm=isch&sxsrf=ACYBGNT1fy79gOV2O7XhJeKDIqQ814ST0w%3A1576485570813&sa=1&ei=wkL3Xb6VMZryrAH3tL2IAg&q=nature&oq=nature&gs_l=img.3..0i67l3j0j0i67l2j0l4.22803.25415..25672...1.0..1.218.2447.0j11j2......0....1..gws-wiz-img.....10..35i39j35i362i39j0i131.8wX4nH36Jh4&ved=0ahUKEwi-_sOz4rnmAhUaOSsKHXdaDyEQ4dUDCAc&uact=5']
    start_urls=[
        'https://www.google.com/search?biw=923&bih=759&tbm=isch&sxsrf=ACYBGNT1fy79gOV2O7XhJeKDIqQ814ST0w%3A1576485570813&sa=1&ei=wkL3Xb6VMZryrAH3tL2IAg&q=nature&oq=nature&gs_l=img.3..0i67l3j0j0i67l2j0l4.22803.25415..25672...1.0..1.218.2447.0j11j2......0....1..gws-wiz-img.....10..35i39j35i362i39j0i131.8wX4nH36Jh4&ved=0ahUKEwi-_sOz4rnmAhUaOSsKHXdaDyEQ4dUDCAc&uact=5'
    ]

    def parse(self,response):
        I = ItemLoader(item=DownloadItem(),response=response)
       
        
        img_url= response.xpath("//img/@src").extract()
        
           
        I.add_value('img_url',img_url)
         
        return I.load_item() 
        

</pre>
![Screenshot from 2019-12-16 14-23-26](https://user-images.githubusercontent.com/43969265/70892712-b0247900-200f-11ea-81b6-e11e57ba0653.png)
![Screenshot from 2019-12-16 14-23-22](https://user-images.githubusercontent.com/43969265/70892726-b581c380-200f-11ea-94cc-3b2fb2cd0afd.png)

image folder remains empty.

**Comment by wRAR** [comment]
https://github.com/scrapy/scrapy/issues/4232#issuecomment-566080027 applies to this too.
