### ISSUE TITLE
Non Blocking processing of a request by downloader middleware. 

### ISSUE THREAD

**Issue by royahsan** [scrapy/scrapy#4241]
## Summary
Can we Support returning `Deferred` object in `request_reached_downloader` signal, or in downloader middleware process_request method. 
Sorry if I am missing something very basic here as I am unfamiliar with internal architecture.

## Motivation
Consider the following potential use cases:
1) A ReCaptcha token is to be solved and inserted by downloader middleware. (It cant be inserted while initializing request as tokens expire pretty quick)
2) A proxy is to be assigned from a pool of proxies, and currently, none are available, need to be fetched at this point. 

There is also an active [question](https://stackoverflow.com/questions/26711309/using-deferred-in-scrapy-downloadermiddleware) at StackOverflow presenting very similar issue!

## Describe alternatives you've considered
Using Python's threading module, we can run multiple threads and try to make sure no request has ever to wait to be processed, but this approach is hard to implement especially in case of captchas where tokens expire pretty quick.

**Comment by Gallaecio** [comment]
> Any of the downloader middleware methods may also return a deferred.

https://docs.scrapy.org/en/latest/topics/downloader-middleware.html#scrapy.downloadermiddlewares.DownloaderMiddleware

**Comment by royahsan** [comment]
@Gallaecio, Sorry my bad I read every letter of the process_request function but missed that note! :(
