### ISSUE TITLE
Settings.getlist default value

### ISSUE THREAD

**Issue by mredaelli** [scrapy/scrapy#4255]
Not sure if I'm reading this wrong, but I don't understand why this function has a default of `None`, but can actually never return it, because of the `or` at [this line](https://github.com/scrapy/scrapy/blob/master/scrapy/settings/__init__.py#L174).

In my use case it would be handy to distinguish between being passed nothing (getting a `None`) and an empty list.

**Comment by Gallaecio** [comment]
Then for your use case use `get` instead of `getlist`.

`get` is meant to ensure the caller that the received value is a list. The reason why `None` is used in the call arguments instead of an empty list is [explained here](https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments).
