### ISSUE TITLE
how to not follow links there are lower depth than start_urls

### ISSUE THREAD

**Issue by BenjaminHoegh** [scrapy/scrapy#4262]
How do I make Scrapy to not follow links there go to a url with lower depth than the one I defined in `start_urls` 

Example

if I wanna follow all links from the position _example.com/shop/_

| Link  | Follow  |
|---|---|
| example.com  | no  |
| example.com/shop/32  | yes  |
| example.com/shop/32/54  | yes  |
| example.com/about | no |
| example.com/someting/else | no |

**Comment by Gallaecio** [comment]
https://docs.scrapy.org/en/latest/topics/settings.html#std:setting-DEPTH_LIMIT ?

**Comment by elacuesta** [comment]
Take a look at the [link extractor docs](https://docs.scrapy.org/en/latest/topics/link-extractors.html#module-scrapy.linkextractors.lxmlhtml), specifically the `allow` constructor parameter. If you need a full example, please use the ["scrapy" tag at StackOverflow](https://stackoverflow.com/questions/tagged/scrapy). See also: [Getting help](https://docs.scrapy.org/en/latest/index.html#getting-help).
