### ISSUE TITLE
defer.inlineCallbacks in spider ?

### ISSUE THREAD

**Issue by poupryc** [scrapy/scrapy#4263]
Hi,

I'm trying to use [this feature of Twisted](https://twistedmatrix.com/documents/13.2.0/api/twisted.internet.defer.inlineCallbacks.html) to run the following code:

```python
# -*- coding: utf-8 -*-
import scrapy
import re
from twisted.internet.defer import inlineCallbacks

from sherlock import utils, items, regex


class PagesSpider(scrapy.spiders.SitemapSpider):
    name = 'pages'
    allowed_domains = ['thing.com']
    sitemap_follow = [r'sitemap_page']

    def __init__(self, site=None, *args, **kwargs):
        super(PagesSpider, self).__init__(*args, **kwargs)

    @inlineCallbacks
    def parse(self, response):
        # things
        response = yield scrapy.Request("https://google.com")
        # Twisted execute the request and resume the generator here with the response
        print(response.text)
```

Is this possible ? I'm trying to use this to [dispense with the inline-request module](https://github.com/rmax/scrapy-inline-requests/issues/10).

Thanks

**Comment by HelloEdit** [comment]
After reading the code, I think I've found the solution. Perhaps documenting it would be beneficial?

```python
# -*- coding: utf-8 -*-
import scrapy
import re
from twisted.internet.defer import inlineCallbacks

from sherlock import utils, items, regex


class PagesSpider(scrapy.spiders.SitemapSpider):
    name = 'pages'
    allowed_domains = ['thing.com']
    sitemap_follow = [r'sitemap_page']

    def __init__(self, site=None, *args, **kwargs):
        super(PagesSpider, self).__init__(*args, **kwargs)

    @inlineCallbacks
    def parse(self, response):
        # things
        request = scrapy.Request("https://google.com")
        response = yield self.crawler.engine.download(request, self) 
        # Twisted execute the request and resume the generator here with the response
        print(response.text)
```

Correct me if I'm wrong

**Comment by elacuesta** [comment]
Relevant: https://github.com/scrapy/scrapy/issues/542#issuecomment-32621164. Not sure if we want to document these `ExecutionEngine` methods though. Any thoughts @dangra?

If, on the other hand, this issue is motivated by the above one (#3500), the "Scrapy way" of achieving such result would be [_Passing additional data to callback functions_](https://docs.scrapy.org/en/1.8/topics/request-response.html#passing-additional-data-to-callback-functions)

**Comment by wRAR** [comment]
The current way to do the same is to declare the callback `async def`, which is already documented. I don't want us to describe any `inlineCallbacks` uses where the alternatives exists, so I'm closing this.
