### ISSUE TITLE
Document that Scrapy 1.7.0 breaks custom schedulers

### ISSUE THREAD

**Issue by Gallaecio** [scrapy/scrapy#4264]
[This signature change](https://github.com/scrapy/scrapy/commit/821f5bb26077d7f9a6b2b1a72f210f81779f5393#diff-1e8b9699ff2fb363b837e0da1b7eb876R16) introduced in 1.7.0 breaks custom schedulers. It should be covered in the list of 1.7.0 backward-incompatible changes.

**Comment by joybhallaa** [comment]
Can I work on this ?

**Comment by Gallaecio** [comment]
Please, go ahead.
