### ISSUE TITLE
Random failures in CrawlTestCase.test_fixed_delay

### ISSUE THREAD

**Issue by wRAR** [scrapy/scrapy#4268]
On some test runs `CrawlTestCase.test_fixed_delay`  fails with
```
>       yield self._test_delay(total=3, delay=0.1)
E   twisted.trial.unittest.FailTest: twisted.trial.unittest.FailTest: True is not false : test total or delay values are too small
```

**Comment by joybhallaa** [comment]
Hey, can I work on this ?

**Comment by wRAR** [comment]
@joybhallaa sure!

**Comment by globefire** [comment]
Hey, @joybhallaa you still working on it? If not @Gallaecio can I try it?

**Comment by joybhallaa** [comment]
@globefire, sure !

**Comment by sakshamb2113** [comment]
@wRAR  can i work on this issue ?

**Comment by wRAR** [comment]
@sakshamb2113 sure

**Comment by sakshamb2113** [comment]
@wRAR I looked at the PR you made recently where there is a similar error as you described above for pypy3 tox env . Does this error always come up for pypy3 only?

**Comment by wRAR** [comment]
@sakshamb2113 it's not similar at all.

**Comment by wRAR** [comment]
@sakshamb2113 or do you mean #4367? Even there a similar error also happened for the `py38-asyncio` env.

**Comment by sakshamb2113** [comment]
@wRAR  I ran test_crawl.py a number of times on py3 and flake8 on local machine but was not able to reproduce this error even for total and delay variables both equal to zero. That should mean that this error arises only when tests run on travis ci and has something to do with the environment variables there.

**Comment by wRAR** [comment]
@sakshamb2113 I had this error locally.

**Comment by Gallaecio** [comment]
It should be a “simple” matter of increasing the parameters of the corresponding tests, using the minimum values that do not cause the tests to fail.

**Comment by sakshamb2113** [comment]
I was able to obtain the error locally after which I changed the "total" parameter from 3 to 4 and ran the tests.I have not obtained any error until now.

**Comment by sakshamb2113** [comment]
@Gallaecio  @wRAR Should we change the "delay" parameter from 0.1 to 0.11 (I got no error for delay=0.11 in 80 test runs) ?

**Comment by Gallaecio** [comment]
@wRAR Can you check if that also works for you? If so, I guess it makes sense for @sakshamb2113 to create a pull request with the change, and we can see if the PyPy Travis CI job also works, and we can hope it will continue to work after we merge.
