### ISSUE TITLE
scrapy installation error in visual code 

### ISSUE THREAD

**Issue by Haroon-afk** [scrapy/scrapy#4280]
### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

Please paste here the output of executing `scrapy version --verbose` in the command line.

### Additional context

Any additional information, configuration, data or output from commands that might be necessary to reproduce or understand the issue. Please try not to include screenshots of code or the command line, paste the contents as text instead. You can use [GitHub Flavored Markdown](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) to make the text look better.

**Comment by elacuesta** [comment]
Hello @Haroon-afk, please update the issue to include information about it, it seems like the template was not modified.

**Comment by elacuesta** [comment]
Closing after a month without feedback from the author.
