### ISSUE TITLE
Fix "Debugging memory leaks with Guppy" section (docs)

### ISSUE THREAD

**Issue by noviluni** [scrapy/scrapy#4285]
After removing the Python 2.7 support, this section:

https://docs.scrapy.org/en/latest/topics/leaks.html#debugging-memory-leaks-with-guppy

 should be removed or merged with this:
https://docs.scrapy.org/en/latest/topics/leaks.html#topics-leaks-muppy

**Comment by kmike** [comment]
A good catch!

**Comment by sakshamb2113** [comment]
Can i work on this issue?

**Comment by noviluni** [comment]
@sakshamb2113 of course, go ahead!

**Comment by sakshamb2113** [comment]
![Screenshot from 2020-02-18 22-11-36](https://user-images.githubusercontent.com/44064539/74757696-5ef96580-529c-11ea-931b-e3b23c67d59c.png)
there is one more reference of guppy in the beginning of the page.Should i change this too?

**Comment by krisblarq** [comment]
I see this issue is still open. Are there any other issues to be worked on?.

**Comment by elacuesta** [comment]
No reason, the PR just wasn't linked, either [manually](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-to-an-issue) or with one of the available [keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword). Closing now, thanks for noticing!
