### ISSUE TITLE
Fatal error launching scrapy>1.6.0 from Anaconda Prompt

### ISSUE THREAD

**Issue by pwinzer** [scrapy/scrapy#4289]
### Description

I'm having the same issue reported in [issue 4075](https://github.com/scrapy/scrapy/issues/4075), but I'd like to provide some more information.

### Steps to Reproduce

Fresh Anaconda install, installed scrapy with `conda install -c conda-forge scrapy`, as specified in [official Windows installation instructions](https://docs.scrapy.org/en/latest/intro/install.html#windows). Scrapy 1.8.0 was successfully installed.

Enter a scrapy command: `scrapy shell`, `scrapy version`, `scrapy startproject spam`, etc. 

**Expected behavior:**

Scrapy commands work as documented, as they have in the past.

**Actual behavior:**

Scrapy commands yield 
`Fatal error in launcher: Unable to create process using '"d:\bld\scrapy_1572360424769\_h_env\python.exe"  "C:\Users\path\to\Continuum\anaconda3\Scripts\scrapy.exe" version'`

There is no d:\ on my machine. I have no idea where this path is coming from.

**Reproduces how often:**

100% in my current installation

**Work around:**

`python -m scrapy <command>` rather than `scrapy <command>`

### Versions

`python -m scrapy version --verbose` yields.
Scrapy       : 1.8.0
lxml         : 4.4.1.0
libxml2      : 2.9.9
cssselect    : 1.1.0
parsel       : 1.5.2
w3lib        : 1.21.0
Twisted      : 19.10.0
Python       : 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
pyOpenSSL    : 19.0.0 (OpenSSL 1.1.1d  10 Sep 2019)
cryptography : 2.7
Platform     : Windows-10-10.0.18362-SP0

### Additional context

It appears any version after 1.6.0 has this issue. Downgrading to 1.6.0 with `conda install -c conda-forge scrapy=1.6.0` resolves the launching issue. I installed a few versions of 1.7 with `conda install -c conda-forge scrapy=1.7.x` and the launcher issue was present there.

**Comment by Srutakirti** [comment]
Thank you for posting this , it wasnt working for me and i downgraded to 1.6 and it worked.

**Comment by GeorgeA92** [comment]
[The easiest way](https://stackoverflow.com/a/60180467/10884791) to overcome this is to use command with `pythom -m`
like `python -m scrapy shell` , `python -m scrapy crawl quotes` etc. without any reinstalls.

[Also](https://stackoverflow.com/a/61091235/10884791) this path practically occures inside only one place - on `scrapy_****/recipe/info/meta.yaml` file.

I compared that `/recipe/info/meta.yaml` files for all versions of scrapy previously installed on my PC with `conda`(Anaconda).

And I found one.. unexpected difference between files for versions after 1.6.0 and older versions
Files for scrapy versions after 1.6.0 don't have this 2 lines:
```
    entry_points:
        - scrapy = scrapy.cmdline:execute
```
As far as I understand this is conda package equivalent of these code lines from `setup.py` and it is responsible for binding `scrapy.cmdline.execute` as separate `scrapy` console command.

https://github.com/scrapy/scrapy/blob/49357cccbdba2c719b634f2d71a5cbed121b2587/setup.py#L47-L49

![1_5_1](https://user-images.githubusercontent.com/15800727/78897483-eaac9880-7a7a-11ea-9510-7e689594eb1f.PNG)
![1_6_0](https://user-images.githubusercontent.com/15800727/78897587-162f8300-7a7b-11ea-85d3-acf11ba04062.PNG)
![1_8_0](https://user-images.githubusercontent.com/15800727/78897613-1e87be00-7a7b-11ea-8fcb-cf1a7419a8ae.PNG)
![2_0_1](https://user-images.githubusercontent.com/15800727/78897623-22b3db80-7a7b-11ea-8fda-f992d788c544.PNG)

**Comment by pwinzer** [comment]
Thanks for the great insights, @GeorgeA92 ! I'll report the bug to Anaconda and see where I can get.

**Comment by GeorgeA92** [comment]
> I'll report the bug to Anaconda and see where I can get.

@pwinzer I think this issue is related to scrapy package on conda-forge and it should be redirected to maintainers of that package.
not to Anaconda.
@camfrout already reported it [here ](https://github.com/conda-forge/scrapy-feedstock/issues/37)

**Comment by pwinzer** [comment]
Haha I was on my way back here because I had just dug that up as well. Thanks, again.

Given that, I will close this issue.

**Comment by Arregator** [comment]
I fixed those lines in `/recipe/info/meta.yaml`, but it did not resolve the problem, I still get that `Fatal error in launcher: Unable to create process using '"d:\bld\scrapy_1584555997548\_h_env\python.exe"` error...

**Comment by Soumarjit** [comment]
I am in the same problem too.

**Comment by chad011110** [comment]
I am having the same issue...

**Comment by Gallaecio** [comment]
As @GeorgeA92 said, @camfrout already reported this at https://github.com/conda-forge/scrapy-feedstock/issues/37

Please, follow https://github.com/conda-forge/scrapy-feedstock/issues/37 for updates surrounding this issue.
