### ISSUE TITLE
Add a setting to choose a custom AsyncIO loop

### ISSUE THREAD

**Issue by Gallaecio** [scrapy/scrapy#4306]
Just as #4294 allows to easily choose a custom Twister reactor, I think we should consider implementing a setting that allows choosing a custom AsyncIO loop (when using an AsyncIO reactor).

I’m thinking of https://github.com/MagicStack/uvloop, which I’ve used in web development, and can’t help but wonder if it could improve Scrapy performance in some scenarios.

**Comment by sakshamb2113** [comment]
@Gallaecio I am working on this issue
