### ISSUE TITLE
Use f-strings

### ISSUE THREAD

**Issue by Gallaecio** [scrapy/scrapy#4307]
They offer a simpler syntax and [speed](https://realpython.com/python-f-strings/#speed), so once we drop Python 3.5 support I guess it makes sense to look into replacing `%` and `format` usages with f-strings where possible.

**Comment by ammarnajjar** [comment]
I'd like to work on this if that's ok

**Comment by elacuesta** [comment]
Thanks for the interest @ammarnajjar, please go ahead if you'd like.
FTR, seems like 3.5's end of life is set to 2020-09-13, according to https://devguide.python.org/#status-of-python-branches

**Comment by ammarnajjar** [comment]
@elacuesta do you mean it would be better to wait till 3.5's EOL?

**Comment by elacuesta** [comment]
Not really, a patch should not be _merged_ before that, but the work can start before.

**Comment by ammarnajjar** [comment]
#4324 is open, but I don't think it is a good idea to start that early, because of the merge conflicts along the way, I will suspend the work there on my side.

**Comment by simulacra342870** [comment]
I think I have the solution
I have just refactored this function within the scrapy/core/spidermw.py file:

def _fname(f):
return "%s.%s".format(
f.self.class.name,
f.func.name
)

to fstrings with same placeholders, eg %s for strings,

def _fname(f):
return f"%s.%s"(
f.self.class.name,
f.func.name
)

Don't hurt me I am extremely newbie, I am only trying to help and gain experience.
Are there any other files within the scrapy source code that needs to be refactored or do Ihave to look through all of source code to find a way to use fstrings to refactor the code.

cheers danny

**Comment by joybhallaa** [comment]
@ammarnajjar are you still working on this issue, if not I would like to work on it!

**Comment by ammarnajjar** [comment]
@joybhallaa , still 😄

**Comment by joybhallaa** [comment]
Cool!

**Comment by matthew02** [comment]
Is it possible for more than one person to work on this issue at the same time? I'm trying to find a way to contribute to OSS, but I'm having a hard time finding an entry point. This is something I could handle, though.

**Comment by mHassan20896** [comment]
Should I start working on it? I see people working on it already. I hope it would be a good contribution to the community

**Comment by joybhallaa** [comment]
@matthew02 @mHassan20896 there is a PR by @ammarnajjar which is a WIP(work in progress).

**Comment by Grelo4ka** [comment]
Can I start working on it?

**Comment by Gallaecio** [comment]
@Grelo4ka https://github.com/scrapy/scrapy/pull/4324#issuecomment-589001504

**Comment by Grelo4ka** [comment]
> @Grelo4ka [#4324 (comment)](https://github.com/scrapy/scrapy/pull/4324#issuecomment-589001504)

Okay, in this case I'll try to find something else what I can work on

**Comment by JacekKorta** [comment]
Hi, 
I seen that it has still Open status. I just moment started with this issue. But I’m not sure do I do this correct. I never had before an opportunity to work on someone repository. Please correct me if I’m  wrong. I fork the master branch, I cloned it on my local computer. I wrote the script to find all the lines containing “%” or “.format”. I count about 570 lines. I have list in txt file. I created a new “F-string” branch and I start to convert these lines. I’m not sure how to organize it in commits, should I create a commit to each file or it is doesn’t matter? If you have any tips, please let me know. Regards.

**Comment by Anupam-USP** [comment]
Can more than one person work on same issue, as this seems something i can start work from?

**Comment by Gallaecio** [comment]
@Anupam-USP Two people working on it at the same time would, in my opinion, be a waste of time. Moreover, in this case there is already a good pull request, but until we decide to drop Python 3.5 support from Scrapy, I don’t think it makes sense for anyone to work on this further.

**Comment by joybhallaa** [comment]
@Anupam-USP you can pick up other issues with the label **good first issue**
The maintainers and contributors are really helpful !

**Comment by HenriqueAJNB** [comment]
I'd like to contribute with this issue. Can I work on it?

**Comment by siva432** [comment]
hello , I am interested to contribute to this issue.

**Comment by Gallaecio** [comment]
@siva432 Sorry, this issue is already taken (#4307). The changes have not been merged yet simply because first we need to drop Python 3.5 support in Scrapy.
