### ISSUE TITLE
Mac OS X, OS X → macOS

### ISSUE THREAD

**Issue by Gallaecio** [scrapy/scrapy#4308]
We have a few references in the documentation where we use the old name of that OS. We should update them.

**Comment by tomaskrcka** [comment]
Hi, I'd like to take this issue.

**Comment by elacuesta** [comment]
Thanks for the interest @tomaskrcka. No need to ask first, please go ahead 😄

**Comment by AKSHAYSHARMAJS** [comment]
@elacuesta why this issue is not closed? if something's missing i would like to work on it.
