### ISSUE TITLE
Crawl command doesn't exist?

### ISSUE THREAD

**Issue by holms** [scrapy/scrapy#4320]
### Description

Just following example from [here](https://docs.scrapy.org/en/latest/intro/tutorial.html ): but there's no such command "crawl" in scrappy.

### Steps to Reproduce

1. Open documentation in [here](https://docs.scrapy.org/en/latest/intro/tutorial.html )
2. On step `scrapy crawl quotes` it will fail

**Expected behavior:** [What you expect to happen]

To launch crawling script

**Actual behavior:** [What actually happens]

```
(scraper) holms@Romans-iMac /V/V/S/scraper> scrapy crawl
Scrapy 1.8.0 - no active project

Unknown command: crawl
```

**Reproduces how often:** [What percentage of the time does it reproduce?]

Always

### Versions

(scraper) holms@Romans-iMac /V/V/S/scraper> scrapy version --verbose
Scrapy       : 1.8.0
lxml         : 4.5.0.0
libxml2      : 2.9.10
cssselect    : 1.1.0
parsel       : 1.5.2
w3lib        : 1.21.0
Twisted      : 19.10.0
Python       : 3.8.1 (default, Jan  5 2020, 21:31:55) - [Clang 9.1.0 (clang-902.0.39.2)]
pyOpenSSL    : 19.1.0 (OpenSSL 1.1.1d  10 Sep 2019)
cryptography : 2.8
Platform     : macOS-10.13.6-x86_64-i386-64bit

### Additional context

Installed from pip, running in virtualenv.

**Comment by elacuesta** [comment]
The `crawl` command is only valid in the context of a project. According to the pasted output, Scrapy is failing to recognize a project in the working directory (`Scrapy 1.8.0 - no active project`). Are you sure you have a project in the directory from which you are executing the command?

**Comment by holms** [comment]
Alright thank you. It's just weird that docs thinks from perspective of project. Most of us writing small crawlers.
