### ISSUE TITLE
Scrapy freezes when time on computer clock has been changed manually.

### ISSUE THREAD

**Issue by somestupidpersonLA** [scrapy/scrapy#4322]
Windows 8.1. Changed time on several hours backward. Scrapy stopped doing requests until scrapy restart.

**Comment by elacuesta** [comment]
Could you please share some additional information? Some code and logs that would help us reproduce/understand the issue. Please see [Reporting bugs](https://docs.scrapy.org/en/latest/contributing.html#reporting-bugs) and [How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by somestupidpersonLA** [comment]
`# -*- coding: utf-8 -*-
import scrapy


class ToScrapeSpiderXPath(scrapy.Spider):
    name = 'toscrape-xpath'
    start_urls = [
        'http://quotes.toscrape.com/',
    ]

    def parse(self, response):
        for quote in response.xpath('//div[@class="quote"]'):
            yield {
                'text': quote.xpath('./span[@class="text"]/text()').extract_first(),
                'author': quote.xpath('.//small[@class="author"]/text()').extract_first(),
                'tags': quote.xpath('.//div[@class="tags"]/a[@class="tag"]/text()').extract()
            }

        next_page_url = response.xpath('//li[@class="next"]/a/@href').extract()
        for i in next_page_url*100:
            yield scrapy.Request(response.urljoin(i), dont_filter=True)

`
Any spider. Run it and change your clock on -1 hour. It will stop scraping and freeze.

**Comment by somestupidpersonLA** [comment]
After changing time back it will resume its work.

**Comment by somestupidpersonLA** [comment]
I don't think it is a bug. I think it is something like pause package or similar.
