### ISSUE TITLE
"pip install scrapy" on Mac - python 3.8 - without Anaconda

### ISSUE THREAD

**Issue by bwashed** [scrapy/scrapy#4325]
Not a pro here.
Having issues while trying to install from scratch Scrapy.

As i can see from instructions (and from previous posts) it seems: 
- i can only install Scrapy with Anaconda
- the instructions @ https://doc.scrapy.org/en/latest/intro/install.html state that: "...Python 3.5 or above under CPython" (...what i sCPython???)

1) have attached a document with errors when i ttried to install Scrapy directly in normal folder 
[Scrapy_Errors_01.docx](https://github.com/scrapy/scrapy/files/4177247/Scrapy_Errors_01.docx)

2) When i tried to install Scrapy under a virtual environment it gave me errors as well
[Scrapy_Errors_02.docx](https://github.com/scrapy/scrapy/files/4177275/Scrapy_Errors_02.docx)
(apologies as i do not know how to view, on iterm, the top error lines)

How can i solve those problems?
How is it possible that i cannot even install to Virtual Environment?

best Regards,
Emil

**Comment by bwashed** [comment]
any help, please?

**Comment by elacuesta** [comment]
I don't remember the exact steps I took to have all dependencies in my macOS installation, but I suspect you might be missing some dev tools. Could you try installing the Xcode Command Line Tools by running `xcode-select --install`? If that solves the issue, perhaps we could add it to the docs.

**Comment by Gallaecio** [comment]
@bwashed Have you followed the [macOS-specific installation instructions](https://doc.scrapy.org/en/latest/intro/install.html#mac-os-x)?

**Comment by bwashed** [comment]
@elacuesta thanks a lot... 
WORKED 4 me....

as i had a similar issue with selectolax, i was suggested by owner to try following instructions @

https://apple.stackexchange.com/questions/254380/why-am-i-getting-an-invalid-active-developer-path-when-attempting-to-use-git-a

basically only had to use same command you suggested `xcode-select --install`. Link shows other workaround if that command doesn't work.... 

@Gallaecio thanks a lot for your help... :-)

**Comment by elacuesta** [comment]
> Have you followed the [macOS-specific installation instructions](https://doc.scrapy.org/en/latest/intro/install.html#mac-os-x)?

Nice @Gallaecio, it was there all along! 😂 
No need to add anything to the docs then, thanks!

**Comment by siberianbear** [comment]
@elacuesta, thank you! Your solution is works and solved issue!
