### ISSUE TITLE
ie. → i.e.

### ISSUE THREAD

**Issue by Gallaecio** [scrapy/scrapy#4332]
Looking for `\bie\.` in the source code there are quite a few matches.

As [noticed](https://github.com/scrapy/scrapy/pull/4331#discussion_r379552909) by @elacuesta, **i.e.** is the [right spelling](https://en.wikipedia.org/wiki/List_of_Latin_phrases_(I)#id_est).

**Comment by nikochiko** [comment]
Can I work on this?

**Comment by Gallaecio** [comment]
@nikochiko Sure, no need to ask for permission! Mind that @AKSHAYSHARMAJS seems to have started working on it, although he has not opened a pull request yet.

**Comment by nikochiko** [comment]
Ah alright! 
Yeah I think he is working on it, np I will take another issue as it comes up :)

**Comment by Gallaecio** [comment]
If you are OK with working on code style changes, see https://github.com/scrapy/scrapy/pull/4324#issuecomment-586963333

**Comment by AKSHAYSHARMAJS** [comment]
> 
> 
> @nikochiko Sure, no need to ask for permission! Mind that @AKSHAYSHARMAJS seems to have started working on it, although he has not opened a pull request yet.

@Gallaecio thanks for mentioning that. I have opened a pull request for the same. Also I m' looking for this issue in other documents as well and will revert you on that. :) 👍
