### ISSUE TITLE
Needs change on "Example of shell session" in Scrapy 1.8.0 docs

### ISSUE THREAD

**Issue by dedenhabibi** [scrapy/scrapy#4336]
### Description

I was learning how to use Scrapy shell but got error similar with this issue #3314, and got the solution in the issue as well. But, when I looked back into the Docs (1.8.0), the example still use (') instead of ("). I think it is better to change it, especially for next learners like me.

**Expected behavior:**

*Example of shell session*
...
scrapy shell "https://scrapy.org" --nolog

**Actual behavior:**

*Example of shell session*
...
scrapy shell 'https://scrapy.org' --nolog

**Comment by Gallaecio** [comment]
Could you share the URL that caused you issues with `'`?

At least in Linux, I think `'` is safer than  `"`, since within `"` special characters like ` or $ could be unexpectedly interpreted.

**Comment by Gallaecio** [comment]
In https://github.com/scrapy/scrapy/issues/3314 I think the issue was not using `'` instead of `"`, but missing the URL protocol.

**Comment by dedenhabibi** [comment]
> 
> 
> Could you share the URL that caused you issues with `'`?
> 
> At least in Linux, I think `'` is safer than `"`, since within `"` special characters like `or`$` could be unexpectedly interpreted.

I use Windows 10 (unfortunately :D).
Any URL doesnt work, e.g. `https://www.lapan.go.id.`
It shows `ValueError: invalid hostname: 'https`.

Perhaps, the Windows? I agree with you about `"` vulnerabilities, but it just doesnt work.

**Comment by Gallaecio** [comment]
OK, I think at the very least we could warn about the need to use quoting, and system gotchas related to that.

**Comment by dedenhabibi** [comment]
Ahh, I see. Thank you for illuminating me 😄 🙏

**Comment by gigatesseract** [comment]
@Gallaecio 
It does not work with single quotes in Windows right?
 So we can warn about the usage of ```"``` in Windows and ask them to use ``` ' ``` in Linux based systems.
It is a simple documentation text, I will work on it if that's okay.

**Comment by Gallaecio** [comment]
I was translating the tutorial the other day, and I noticed we do mention this there: https://docs.scrapy.org/en/latest/intro/tutorial.html#extracting-data

We could add a similar warning to the reference documentation.

**Comment by sakshamb2113** [comment]
I am working on this.

**Comment by Gallaecio** [comment]
Fixed by #4450

**Comment by oakla** [comment]
Hey, just a heads up that there's no warning for this on the tutorial page: https://docs.scrapy.org/en/1.1/intro/tutorial.html#extracting-data

**Comment by Gallaecio** [comment]
@oakla Your link is for the documentation of Scrapy 1.1, not the latest Scrapy version.
