### ISSUE TITLE
i cant crawl page with security check 

### ISSUE THREAD

**Issue by farhad-arjmand** [scrapy/scrapy#4344]
i cant crawl pages with security check
https://en.yellowpages.com.tr/bathroom-plumbing-equipment-uskudar-istanbul-c

**Comment by Gallaecio** [comment]
Please, use [StackOverflow](https://stackoverflow.com/tags/scrapy) to ask this type of questions. See [Getting Help](https://docs.scrapy.org/en/latest/#getting-help).
