### ISSUE TITLE
Should we delete the deprecated code in Scrapy 2.0?

### ISSUE THREAD

**Issue by noviluni** [scrapy/scrapy#4356]
I recopilated some of the old (before 2018) deprecation warnings to discuss if we can delete them in the upcoming **Scrapy 2.0** release (chronological order):

**`BaseSgmlLinkExtractor` and `SgmlLinkExtractor` (classes)**
* ~~Deprecation warnings: 07/2014~~
* ~~Links:~~
    * ~~https\://github.com/scrapy/scrapy/blob/c4ee4b6075fbb616272788b14b70f0af63dc2877/scrapy/linkextractors/sgml.py#L23~~
    * ~~https\://github.com/scrapy/scrapy/blob/c4ee4b6075fbb616272788b14b70f0af63dc2877/scrapy/linkextractors/sgml.py#L116~~
* PR: #4679

**`Crawler.spiders` (property)**
*  ~~Deprecation warning: 08/2014~~
*  ~~Link: https\://github.com/scrapy/scrapy/blob/c4ee4b6075fbb616272788b14b70f0af63dc2877/scrapy/crawler.py#L74~~
* PR: https://github.com/scrapy/scrapy/pull/4398

**`HtmlParserLinkExtractor` (class)**
* ~~Deprecation warning: 05/2015~~
* ~~Link: https\://github.com/scrapy/scrapy/blob/c4ee4b6075fbb616272788b14b70f0af63dc2877/scrapy/linkextractors/htmlparser.py#L22~~
* PR: #4674

**`stringify_dict` (function)**
* ~~Deprecation warning: 07/2015~~
* ~~Link: https\://github.com/scrapy/scrapy/blob/c4ee4b6075fbb616272788b14b70f0af63dc2877/scrapy/utils/python.py#L296~~
* PR: https://github.com/scrapy/scrapy/pull/4362

**`is_writable` (function)**
* ~~Deprecation warning: 07/2015~~
* ~~Link: https\://github.com/scrapy/scrapy/blob/c4ee4b6075fbb616272788b14b70f0af63dc2877/scrapy/utils/python.py#L311~~
* PR: https://github.com/scrapy/scrapy/pull/4362

**`setattr_default` (function)**
* ~~Deprecation warning: 07/2015~~
* ~~Link: https\://github.com/scrapy/scrapy/blob/c4ee4b6075fbb616272788b14b70f0af63dc2877/scrapy/utils/python.py#L322~~
* PR: https://github.com/scrapy/scrapy/pull/4362

**Initialising `scrapy.extensions.feedexport.S3FeedStorage` without AWS keys is deprecated. (procedure)**
* ~~Deprecation warning: 11/2015~~
* ~~Link: https\://github.com/scrapy/scrapy/blob/c4ee4b6075fbb616272788b14b70f0af63dc2877/scrapy/extensions/feedexport.py#L103~~
* PR: https://github.com/scrapy/scrapy/pull/4411

**`scrapy.utils.datatypes.MultiValueDict`, `MultiValueDictKeyError` and  `SiteNode` (classes)**
* ~~Deprecation warnings: 01/2016~~
* ~~Links~~:
    * ~~https\://github.com/scrapy/scrapy/blob/c4ee4b6075fbb616272788b14b70f0af63dc2877/scrapy/utils/datatypes.py#L46~~
    * ~~https\://github.com/scrapy/scrapy/blob/c4ee4b6075fbb616272788b14b70f0af63dc2877/scrapy/utils/datatypes.py#L19~~
    * ~~https\://github.com/scrapy/scrapy/blob/c4ee4b6075fbb616272788b14b70f0af63dc2877/scrapy/utils/datatypes.py#L161~~
* PR: https://github.com/scrapy/scrapy/pull/4400/

**`isbinarytext` (function)**
* ~~Deprecation warning: 03/2016~~
* ~~Link: https\://github.com/scrapy/scrapy/blob/c4ee4b6075fbb616272788b14b70f0af63dc2877/scrapy/utils/python.py#L168~~
* PR: https://github.com/scrapy/scrapy/pull/4362 

**`scrapy.downloadermiddlewares.chunked` (module)**
* ~~Deprecation warning: 11/2016~~
* ~~Link: https\://github.com/scrapy/scrapy/blob/c4ee4b6075fbb616272788b14b70f0af63dc2877/scrapy/downloadermiddlewares/chunked.py#L7~~
* PR: https://github.com/scrapy/scrapy/pull/4431/

**`Spider.make_requests_from_url` (method)**
* Deprecation warning: 02/2017
* Link: https\://github.com/scrapy/scrapy/blob/c4ee4b6075fbb616272788b14b70f0af63dc2877/scrapy/spiders/__init__.py#L66 
* PR: https://github.com/scrapy/scrapy/pull/4178

There are other deprecation warnings but as they are from 2018 to the present I think we can leave it there for a while. However, as we are going to release a major version maybe is a good moment to do it.

**Do you see any inconvenience?**

**Any thoughts?** Let me know what you think.

**Comment by kmike** [comment]
I think that's fine to remove most of them, better in separate PRs. 

It can be nice to do this for 2.0, but it is not a blocker for release; we can remove them at any time.

For Spider.make_requests_from_url there are few PRs already; it turns out a bit more tricky, as not all usages were properly deprcated.

**Comment by nyov** [comment]
Scrapy 2.0 sounds like the perfect release target to do some breaking changes and get rid of more of the cruft. But that's just radical me talking, as usual.

I don't see a problem with all of these getting removed wholesale, nothing here has any bearing on external lib versions, as xlib did or the Selectors shortcut. Most are merely internal renames anyway, and legacy code shouldn't have much trouble with the rest? Off with their heads! Errr... :)

**Comment by nyov** [comment]
Ah, looks like we didn't get all of them in 2.0 ;)
I've done `Crawler.spiders` in #4398.
The LinkExtractors could _possibly_ still be useful? But the code is in the history for whoever wants to extract it there, I'm still for removing them.

Added #4400 for `MultiValueDict` and `SiteNode`.

**Comment by nyov** [comment]
Another one from the list: #4411 for `scrapy.extensions.feedexport.S3FeedStorage` without AWS keys.

But I noticed I might be cleaning up easy first issues for gsoc candidates here, oops. :blush:
@Gallaecio, do you think this warrants a "good first issue" tag?

So for completeness sake:
`Spider.make_requests_from_url` is referenced in #4178

That means, currently remaining on the list of easy pickings, here, are: `scrapy.downloadermiddlewares.chunked` and `BaseSgmlLinkExtractor`, `SgmlLinkExtractor`, `HtmlParserLinkExtractor`.

**Comment by Gallaecio** [comment]
> do you think this warrants a "good first issue" tag?

Nah, let us just get rid of them in time for [2.1](https://github.com/scrapy/scrapy/milestone/27).

**Comment by noviluni** [comment]
Hi @nyov @elacuesta @Gallaecio @kmike , thank you for taking this!! :rocket: 

I updated the issue description with the PRs.

**Comment by ashellunts** [comment]
So except `Spider.make_requests_from_url` everything else is done. For #4178 looks like it is under discussion now.
So shall we close this issue now?

**Comment by Gallaecio** [comment]
Let’s just leave it open until we fix #4178.

**Comment by nitangle** [comment]
Hi has the pr been reviewed? I was looking to contribute to this project but I have seen most issues already have an attached pr. Can you guys update the status of pr so as to avoid confusion?

**Comment by mikeysan** [comment]
@nitangle I was hoping to contribute too. However, if you follow the conversation/comments, you'll notice why this issue is still open.

**Comment by elacuesta** [comment]
Hello @nitangle, @mikeysan. The only pending deprecation in this issue is `Spider.make_requests_from_url`, which is removed in #4178, but it's not going to be merged yet because of our deprecation policy (see https://github.com/scrapy/scrapy/pull/4178#issuecomment-701658893)

**Comment by noviluni** [comment]
I removed the "good first issue" label to avoid similar future questions.

**Comment by nyov** [comment]
I think this could be closed, everything has been addressed.
The last issue just hasn't been merged because of deprecation time policy, but it's done and sitting in the queue.
