### ISSUE TITLE
[DOCS] Use HTTPS

### ISSUE THREAD

**Issue by nainardev** [scrapy/scrapy#4359]
Reference:
 - https://httpsiseasy.com
 - https://letsencrypt.org

**Comment by nyov** [comment]
Could you run this again with the `--verbose` flag perhaps? ENOCONTEXT

**Comment by Gallaecio** [comment]
I don’t get what the issue is about, or how your comment, @nyov, is related to it :confused: 

https://docs.scrapy.org/ uses HTTPS, so I guess the issue is not about that.

**Comment by nyov** [comment]
Well, I don't know what it's about either, which is why I said missing context.

I'll take a gamble and guess it might be related to some documentation links. So I hope this PR addresses the issue.

**Comment by nainardev** [comment]
Sorry
