### ISSUE TITLE
I am asking for help. Memory issues, speed issues.

### ISSUE THREAD

**Issue by somestupidpersonLA** [scrapy/scrapy#4364]
Hello. First I would like to say it is not a bug report, but rather an expression of my inability to find answers by myself.

IMPORTANT
I would like to see the set of  correct settings that lowers memory consumption to minimum while retaining speed at a high enough level with using proxy/dropped requests and scale at around 1-10M pages and 1000-2000 requests/minute. Now it goes up to 4Gb (can be not correct)

NOT IMPORTANT
1. Is it possible to use the same cache db file while running two spiders with the same name? (I tried and half of scraped data has been lost. (not 100% sure but still))
2. Is it possible to automatically turn off windows embedded antivirus?(speed issue)
3. Is it possible to run one spider and fetch cache from 2 sets of previously created files?

I've tried to use a AUTOTHROTTLE_TARGET_CONCURRENCY but it is don't increase speed without increasing CONCURRENT_REQUESTS.

DEPTH_PRIORITY = -1
SCHEDULER_DISK_QUEUE = 'scrapy.squeues.PickleLifoDiskQueue'
SCHEDULER_MEMORY_QUEUE = 'scrapy.squeues.LifoMemoryQueue'
(will it have any effect without -s JOBDIR setting?)
RETRY_PRIORITY_ADJUST = 10 
DUPEFILTER_CLASS = 'scrapy.dupefilters.BaseDupeFilter'

HTTPCACHE_ENABLED = True
It seems that httpcache and dedupfilter increases memory consumption. (even for a simple 1-2 depth site.) Is it true?

Should I just read the source?

**Comment by somestupidpersonLA** [comment]
And it's a simple json parsing spider. There is no memory leaking I suppose.

**Comment by somestupidpersonLA** [comment]
Also is it possible to download only part of page? And resume / drop after parsing of downloaded part?

**Comment by wRAR** [comment]
> First I would like to say it is not a bug report, but rather an expression of my inability to find answers by myself.

Yet this is a place for bug reports, stackoverflow.com is better suited for questions.

> It seems that httpcache and dedupfilter increases memory consumption. (even for a simple 1-2 depth site.) Is it true?

The default dupefilter stores fingerprints for all requests in the memory so for many requests a lot of memory gets used for that.  You may disable it if you don't care about duplicates, or you can replace it with some other implementation if you find a better-suited one. In any case the fingerprints need to be stored somewhere and the default implementation is most likely the fastest one.

I don't know about `HttpCacheMiddleware`, its default storage is on the disk and it doesn't look like it keeps a lot of data in the memory.

> Is it possible to use the same cache db file while running two spiders with the same name? 

What cache db do you mean? The default HttpCacheMiddleware storage just stores responses in separate files (1 dir with 6 files per response) AFAIK. It may be possible to break this storage and/or get errors in the spiders when saving the same request from two spiders or saving in one spider and reading in another one at the same time. You may want to use a better storage like a proper DB in such cases.

> Is it possible to automatically turn off windows embedded antivirus?(speed issue)

This is completely offtopic here.

> Is it possible to run one spider and fetch cache from 2 sets of previously created files?

Not sure what does this mean.

> I've tried to use a AUTOTHROTTLE_TARGET_CONCURRENCY but it is don't increase speed without increasing CONCURRENT_REQUESTS.

The Autothrottle extension is for reducing speed, not increasing it. And it's disabled by default.

> Also is it possible to download only part of page?

No.

**Comment by somestupidpersonLA** [comment]
Thank you for reply and answers.

>Is it possible to run one spider and fetch cache from 2 sets of previously
created files?

>Not sure what does this mean.

If I've run 2 scrapers with different names and they have stored cache in
two files:

run.db.dat and  run2.db.dat is it possible to run spider one more time and
to make them use 2 files to read cached data. Any possible way to merge
them?

**Comment by wRAR** [comment]
Only manually, I guess. What storage is that?

**Comment by somestupidpersonLA** [comment]
scrapy.extensions.httpcache.DbmCacheStorage
anydbm

**Comment by somestupidpersonLA** [comment]
If I recalculate *.db.dir and merge *.db.dat files will it work? Not sure if I will be doing this at all but want to know.
.dir  content:
'4554a4b793d6dcfdfc8eeb8fad955108e77ab2d4_data', (0, 15406)
'4554a4b793d6dcfdfc8eeb8fad955108e77ab2d4_time', (15872, 17)
'0a0755a2b53dac1a710aa57281e7fd31e5f4d896_data', (16384, 17451)
'0a0755a2b53dac1a710aa57281e7fd31e5f4d896_time', (34304, 18)
'ef2bdf2d6a9a9096d86caacfa8e611439204479e_data', (34816, 15411)
