### ISSUE TITLE
Something wrong in logging on linux

### ISSUE THREAD

**Issue by JackTJC** [scrapy/scrapy#4371]
I have set a config in settings.py:
LOG_LEVEL = 'DEBUG'
but when I excute the spider the log in level "INFO" also apears in output!It is confusing when you see a quantity of log information in terminal.
The version of my system is:
Linux version 4.15.0-66-generic (buildd@lgw01-amd64-044) (gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)) #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019
and version of scrapy is:
Scrapy 1.8.0

**Comment by nyov** [comment]
Linux logging (syslog) is based around levels of severity, from highest (level 0) to lowest (level 7):
0 `EMERG`
1 `ALERT`
2 `CRIT`
3 `ERR`
4 `WARNING`
5 `NOTICE`
6 `INFO`
7 `DEBUG`
All log-levels are inclusive of higher severities. This means if your level is 4 (Warning), you will receive messages of type warning, _and eveything with higher severity_.

Some programs can exclude loglevels with masks, but I don't know offhand if Python's `logging` module is one of those.
The higher your log-level, the less info you get. (Or in other words, this is not a bug.)
