### ISSUE TITLE
Remove SCRAPY_SELECTORS_BACKEND from scrapy.settings.deprecated

### ISSUE THREAD

**Issue by Gallaecio** [scrapy/scrapy#4376]
There is no trace of `SCRAPY_SELECTORS_BACKEND` in the code anymore, so that line should go.

It would be a good chance to review the rest of the lines in that file, some others may be worth removing as well.

Related to https://github.com/scrapy/scrapy/issues/4356

**Comment by HEndo12345** [comment]
Hi, may I work on this?  Its my first time contributing to a project.

**Comment by PhanatosZou** [comment]
Hi, I'm new here. If the issue is not assigned, I'd like to help out!

**Comment by Gallaecio** [comment]
@PhanatosZou sorry, @HEndo12345 beat you to it :slightly_smiling_face:
