### ISSUE TITLE
How to handle errors from spider properly?

### ISSUE THREAD

**Issue by Urahara** [scrapy/scrapy#4394]
- Is  `yield` errors like http status, bad responses from spider considered a bad practice?
- What Scrapy recommends to users do in workflow of spiders to handle errors?

I tried using  `stderr ` but without success. (Like when i encounter a error in my workflow i quit spider and put a message in there)

I'm asking here because i think this is out of scope of SO.

**Comment by wRAR** [comment]
> I'm asking here because i think this is out of scope of SO.

This is definitely out of scope of GitHub issues though.

> Is yield errors like http status, bad responses from spider considered a bad practice?

I'm not sure I understand this.

Non-fatal errors encountered by user code are usually logged, and on fatal ones the callback is aborted, with a simple `return` or with raising an exception. Closing the whole spider is usually not needed.

**Comment by Urahara** [comment]
@wRAR Sorry about that, i mean that if I am doing a scraping process and at some point i starting facing http errors or invalid xpath selectors, etc what is the best practice to "Close Gracefuly" the Spider and then analylize what is wrong with it, is more clear now what is my purpose? I using Scrapy for years now and i trying to archive best practice to write good spiders.

**Comment by wRAR** [comment]
> at some point i starting facing http errors or invalid xpath selectors, etc what is the best practice to "Close Gracefuly" the Spider

The way to close gracefully is to raise `CloseSpider`.

> to map the error, should I yield and item for that?

No.

> Or maybe just print in stout and read/write itens in a file?

Log the error using the builtin logger. As for items, you should always write them into a file instead of parsing Scrapy's stdout.

Also, consider using [spidermon](https://github.com/scrapinghub/spidermon).
