### ISSUE TITLE
docs: Wrong year in footer notes

### ISSUE THREAD

**Issue by Urahara** [scrapy/scrapy#4396]
### Description

The footer of generated docs of https://docs.scrapy.org/ are 2018, _eg:_ "© Copyright 2008–**2018**, Scrapy developers Revision be2e910d."

### Steps to Reproduce

1. Go to https://docs.scrapy.org/
2. See footer

**Expected behavior:** The year should year current year: 2020. _eg:_ "© Copyright 2008–**2020**, Scrapy developers Revision be2e910d."

**Actual behavior:** The year that show is 2018.

**Reproduces how often:** All time.

### Versions

All.

### Additional context

When building docs locally this error does not occurs.

**Comment by wRAR** [comment]
Already fixed in master.

Also, that doc was built in 2019, not 2020.
