### ISSUE TITLE
"Empty separator" error while pasting .split("some-non-ascii-character") into scrapy shell.

### ISSUE THREAD

**Issue by somestupidpersonLA** [scrapy/scrapy#4397]
Is it possible to use scrapy shell and paste non-ascii characters?
I think it is related to IPython.

**Comment by nyov** [comment]
This should work. 
```py
In [2]: blurb = "�[33m'�[39;49;00m�[33m"

In [3]: blurb.split('�')
Out[3]: ['', "[33m'", '[39;49;00m', '[33m']
```
It seems your non-ascii separator was swallowed somewhere in the middle (and then `split()` got an empty separator).
It could be your IPython console encoding. If you don't use utf-8 with your python shell, probably you can't paste characters that are not valid in your encoding.

Possibly of help: https://stackoverflow.com/questions/20826788/str-split-giving-me-valueerror-empty-separator-for-a-sentence-in-the-for
