### ISSUE TITLE
is scrapy request shor connection? how to change it become long connection?

### ISSUE THREAD

**Issue by ayay129** [scrapy/scrapy#4405]
## Summary

One paragraph explanation of the feature.

## Motivation

Why are we doing this? What use cases does it support? What is the expected outcome?

## Describe alternatives you've considered

A clear and concise description of the alternative solutions you've considered. Be sure to explain why Scrapy's existing customizability isn't suitable for this feature.

## Additional context

Any additional information about the feature request here.

**Comment by wRAR** [comment]
You are supposed to fill in those template lines, not submit them as is. And the title makes no sense. Please fix these problems if this a bug report or use https://stackoverflow.com/ instead if this is a question. Thank you.
