### ISSUE TITLE
Does scrapy uses default system folder for temp files (disk C) and  copies it after download (to the disk D)?

### ISSUE THREAD

**Issue by somestupidpersonLA** [scrapy/scrapy#4415]
If so is there any setting to change it? https://superuser.com/questions/1387909/moving-a-file-between-two-drives-on-one-ssd-will-it-be-copied

**Comment by somestupidpersonLA** [comment]
I mean large files above 1000Gb.

**Comment by wRAR** [comment]
Please use other places, such as https://stackoverflow.com/, for asking non-issue questions.
