### ISSUE TITLE
Error shows when running Scrapy crawl

### ISSUE THREAD

**Issue by clairehuang77777** [scrapy/scrapy#4427]
The error shows when running scrapy crawl

> Traceback (most recent call last):
>   File "c:\users\claire.h\appdata\local\programs\python\python38-32\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
>     current.result = callback(current.result, *args, **kw)
>   File "c:\users\claire.h\appdata\local\programs\python\python38-32\lib\site-packages\scrapy\utils\defer.py", line 154, in f
>     return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
>   File "C:\Users\claire.h\Desktop\python\myFirstScrapyProject\myFirstScrapyProject\pipelines.py", line 11, in process_item
>     item['push']=int(item['push'])
>   File "c:\users\claire.h\appdata\local\programs\python\python38-32\lib\site-packages\scrapy\item.py", line 83, in __getitem__
>     return self._values[key]
> KeyError: 'push'

this is the code i try to run:
```
# -*- coding: utf-8 -*-
import scrapy
# from scrapy.exceptions import CloseSpider
from ..items import MyfirstscrapyprojectItem

class PttSpider(scrapy.Spider):
    count_page = 1
    name = 'ptt'
    allowed_domains = ['www.ptt.cc/']
    start_urls = ['https://www.ptt.cc/bbs/e-shopping/search?q=%E8%9D%A6%E7%9A%AE']+['https://www.ptt.cc/bbs/e-seller/search?q=%E8%9D%A6%E7%9A%AE']
    # start_urls = ['https://www.ptt.cc/bbs/e-shopping/index.html']

    def parse(self, response):
        items = MyfirstscrapyprojectItem()
        for q in response.css('div.r-ent'):
            items['push']:q.css('div.nrec > span.h1::text').extract_first()
            items['title']:q.css('div.title > a::text').extract_first()
            items['href']:q.css('div.title> a::attr(href)').extract_first()
            items['date']:q.css('div.meta > div.date ::text').extract_first()
            items['author']:q.css('div.meta > div.author ::text').extract_first()
            yield(items)

```
```
class MyfirstscrapyprojectItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    #定義field
    push = scrapy.Field()
    title = scrapy.Field()
    href = scrapy.Field()
    date = scrapy.Field()
    author = scrapy.Field()
    pass
```
`class MyfirstscrapyprojectPipeline(object):
    def process_item(self, item, spider):
        item['push']= int(item['push'])
        return item
`

**Comment by vortexkd** [comment]
Hi, Did you mean to use " = " instead of ":" ?
```
items['push'] = q.css('div.nrec > span.h1::text').extract_first()
```
Also, it seems that your selector is returning "None"  with the above selector, so maybe you want to assign a default value (or change your selector)?

**Comment by clairehuang77777** [comment]
yes! i revised the code and forgot to change ":" into "="
after i changed ":" into "=", the code start working!
thanks your for the advise! really helpful!
 
and yes, the item['push'] return "None",
so i tried this code to make it return int, but it's doesn't work
`item['push']=` int(item['push']) 
i am still trying to figure out how to do this...
thank you again!
