### ISSUE TITLE
Export scrapy data from website into google spreadsheet

### ISSUE THREAD

**Issue by clairehuang77777** [scrapy/scrapy#4428]
I am willing to scrap a website for some information. The difficult part is, i want to export all the data in to the google sheets and make the crawler run after some specific intervals. I 'll be using scrapy for this purpose. Any suggestions on how can i do this 
(by making custom pipeline or any other way as i don't have much experience in writing custom pipelines)

here is the code i have now.
````
# -*- coding: utf-8 -*-
import scrapy
# from scrapy.exceptions import CloseSpider
from myFirstScrapyProject.items import MyfirstscrapyprojectItem

class PttSpider(scrapy.Spider):
    count_page = 1
    name = 'ptt'
    allowed_domains = ['www.ptt.cc/']
    start_urls = ['https://www.ptt.cc/bbs/e-shopping/search?q=%E8%9D%A6%E7%9A%AE']+['https://www.ptt.cc/bbs/e-seller/search?q=%E8%9D%A6%E7%9A%AE']
    # start_urls = ['https://www.ptt.cc/bbs/e-shopping/index.html']

    def parse(self, response):
        items = MyfirstscrapyprojectItem()
        for q in response.css('div.r-ent'):
            items['push']=q.css('div.nrec > span.h1::text').extract_first()
            items['title']=q.css('div.title > a::text').extract_first()
            items['href']=q.css('div.title> a::attr(href)').extract_first()
            items['date']=q.css('div.meta > div.date ::text').extract_first()
            items['author']=q.css('div.meta > div.author ::text').extract_first()
            yield(items)
```

```
import scrapy
class MyfirstscrapyprojectItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    push = scrapy.Field()
    title = scrapy.Field()
    href = scrapy.Field()
    date = scrapy.Field()
    author = scrapy.Field()

```

```
class MyfirstscrapyprojectPipeline(object):
    def process_item(self, item, spider):
        return item
```

**Comment by tindatnguyen** [comment]
Look at example of how to write pipeline for a database it is similar, then you could use the following google sheet api.

https://developers.google.com/sheets/api/quickstart/python

As for interval question, you could set the config

DOWNLOAD_DELAY

Hope this helps

**Comment by elacuesta** [comment]
We use the GitHub issue tracker to handle bugs and feature requests.
Please use the ["scrapy" tag at StackOverflow](https://stackoverflow.com/tags/scrapy) to ask this kind of questions. See also: [Getting help](https://docs.scrapy.org/en/latest/#getting-help)
