### ISSUE TITLE
Make scrapy interact with java script directly

### ISSUE THREAD

**Issue by EbotFabien** [scrapy/scrapy#4432]
scrapy is a good tool for web scraping and automated testing.But Scrapy can't interact with java script directly unlike Selenium.What if  Scrapy can interact with java script without installing a Docker and splash.

**Comment by wRAR** [comment]
Hi @EbotFabien ! Implementing this in Scrapy itself would require adding a JS interpreter or an embedded browser implementation, which would greatly complicate the architecture. We understand that this feature is needed though, and currently we are working on Scrapy coroutine support which will help with using embedded browser implementations from Scrapy spiders. This will still require installing that implementation, such as pyppetteer, though.

Cc: @kmike

**Comment by Gallaecio** [comment]
(https://github.com/scrapy-plugins/scrapy-playwright)
