### ISSUE TITLE
Remove defer.returnValue calls

### ISSUE THREAD

**Issue by wRAR** [scrapy/scrapy#4443]
https://twisted.readthedocs.io/en/latest/core/howto/defer-intro.html#inline-callbacks-using-yield says "On Python 3, instead of writing returnValue(json.loads(responseBody)) you can instead write return json.loads(responseBody). This can be a significant readability advantage, but unfortunately if you need compatibility with Python 2, this isn’t an option.".

**Comment by eyelesbarrow** [comment]
Hello, can I work on this? It's a good 1st issue for me. Thank you!

**Comment by wRAR** [comment]
@eyelesbarrow sure

**Comment by devmodi154** [comment]
@wRAR Can multiple people work on this issue?

**Comment by wRAR** [comment]
@devmodi154 that would be duplicated work, wouldn't it?

**Comment by devmodi154** [comment]
Oh Yeah! So sorry

**Comment by yusofsf** [comment]
@wRAR can i work on this? and i just need to replace returnValue with return?

**Comment by wRAR** [comment]
@yusofsf there is already a work-in-progress pull request about this, you can see it linked above your comment. It's also more complicated than replacing returnValue with return.
