### ISSUE TITLE
Update redirect link from Python 2 docs to Python 3 docs

### ISSUE THREAD

**Issue by adityaa30** [scrapy/scrapy#4444]
### Description

The documentation has many redirect links to `https://docs.python.org/2/*`. As Scrapy now supports Python 3.5+ I think they should be changed to `https://docs.python.org/3/*` respectively.

### Steps to Reproduce

1. Go to [JsonItemExported](https://docs.scrapy.org/en/latest/topics/exporters.html#jsonitemexporter) and click on `JSONEncoder`
2. You will be redirected to [Python 2](https://docs.python.org/2/library/json.html#json.JSONEncoder) docs.

Above steps can be repeated for many other pages in Scrapy docs.

**Expected behavior:** Redirected to latest Python 3 docs

**Actual behavior:** Redirected to Python 2 docs

**Reproduces how often:** 100%

### Versions

INFO:scrapy.utils.log:Scrapy 2.0.0 started (bot: scrapybot)
INFO:scrapy.utils.log:Versions: lxml 4.4.1.0, libxml2 2.9.9, cssselect 1.1.0, parsel 1.5.2, w3lib 1.21.0, Twisted 19.10.0, Python 3.6.10 (default, Feb 11 2020, 21:11:31) - [GCC 7.4.0], pyOpenSSL 19.1.0 (OpenSSL 1.1.1d  10 Sep 2019), cryptography 2.8, Platform Linux-5.3.0-40-generic-x86_64-with-debian-buster-sid
DEBUG:scrapy.utils.log:Using reactor: twisted.internet.epollreactor.EPollReactor
Scrapy       : 2.0.0
lxml         : 4.4.1.0
libxml2      : 2.9.9
cssselect    : 1.1.0
parsel       : 1.5.2
w3lib        : 1.21.0
Twisted      : 19.10.0
Python       : 3.6.10 (default, Feb 11 2020, 21:11:31) - [GCC 7.4.0]
pyOpenSSL    : 19.1.0 (OpenSSL 1.1.1d  10 Sep 2019)
cryptography : 2.8
Platform     : Linux-5.3.0-40-generic-x86_64-with-debian-buster-sid

### Additional context

I am willing to fix this issue, waiting for an approval.

**Comment by elacuesta** [comment]
You're right, thanks for pointing it out. Searching for "python.org/2" within the `docs` directory I could find many other occurrences of direct links. We are using `Intersphinx` now, and the [stdlib is included in the mapping](https://github.com/scrapy/scrapy/blob/2.0.1/docs/conf.py#L286), probably most of those links could be rewritten. For instance, the JSONEncoder example would be:
```
:class:`json.JSONEncoder`
```

**Comment by adityaa30** [comment]
Thanks @elacuesta ! I will start working on this now.

**Comment by adityaa30** [comment]
@elacuesta I have sent a pr #4445 to fix this issue.
