### ISSUE TITLE
zope.interface 5.0.0 unsupported

### ISSUE THREAD

**Issue by wRAR** [scrapy/scrapy#4447]
zope.interface 5.0.0 was released yesterday and with it some of our tests fail: https://travis-ci.org/github/scrapy/scrapy/jobs/664648176 (actually it's just one test, `CrawlerRunnerTestCase.test_spider_manager_verify_interface`).

I don't know if it's just a problem with that test or something in Scrapy is now broken too. 

Changelog: https://zopeinterface.readthedocs.io/en/latest/changes.html

**Comment by adityaa30** [comment]
@wRaR As of [zope.interface#171](https://github.com/zopefoundation/zope.interface/issues/171) they have made "`verifyObject` and `verifyClass` report all errors, if the candidate object has multiple detectable violations. Previously they reported only the first error." 
They achieve this behaviour using `MultipleInvalid` (refer [zope/interface/exceptions.py](https://github.com/zopefoundation/zope.interface/blob/master/src/zope/interface/exceptions.py#L233-L263)). 

Looking at their implementation, I think we have to catch both  `DoesNotImplement` and `MultipleInvalid` (refer [_verfiy](https://github.com/zopefoundation/zope.interface/blob/master/src/zope/interface/verify.py#L74-L92) implementation) in our tests and [crawler.py](https://github.com/scrapy/scrapy/blob/master/scrapy/crawler.py#L129-L135) i.e everywhere `verifyObject` or `verifyClass` are used.
