### ISSUE TITLE
Depreciation warnings when running tox 

### ISSUE THREAD

**Issue by joybhallaa** [scrapy/scrapy#4453]
### Description

When testing with `tox` there is a long `warning summary`, which show a various deprecation warnings.

![Screenshot from 2020-03-25 11-00-19](https://user-images.githubusercontent.com/35984969/77504982-dc118f00-6e87-11ea-80a1-4f983af15ce3.png)

### Steps to Reproduce

1. Navigate to Scrapy directory
2. Run tox

**Expected behavior:**
 -

**Actual behavior:** 

-

### Versions

Scrapy       : 2.0.0
lxml         : 4.5.0.0
libxml2      : 2.9.10
cssselect    : 1.1.0
parsel       : 1.5.2
w3lib        : 1.21.0
Twisted      : 20.3.0
Python       : 3.6.9 (default, Nov  7 2019, 10:44:02) - [GCC 8.3.0]
pyOpenSSL    : 19.1.0 (OpenSSL 1.1.1d  10 Sep 2019)
cryptography : 2.8
Platform     : Linux-5.3.0-42-generic-x86_64-with-Ubuntu-18.04-bionic

### Additional context

I am using python 3.6.9, I don't know if that's what causes these, but I thought I should let everyone know as I think this is a refactoring issue.

**Comment by Gallaecio** [comment]
Please, do not use images to show code, and make sure you search for similar issues before you create one. I think we have an existing issue for at least one of the warnings.

**Comment by joybhallaa** [comment]
Okay, I will not include images when creating issues.



> make sure you search for similar issues before you create one. I think we have an existing issue for at least one of the warnings.

I was not able to find an issue pertaining to these  depreciation warnings.

**Comment by Gallaecio** [comment]
This is the issue I recalled: https://github.com/scrapy/scrapy/issues/3288

**Comment by elacuesta** [comment]
In addition to the above comment ☝️ 
* `scrapy.utils.{http, markup, multipart}` were deprecated less than a year ago, we need to wait a bit longer to remove them: #3859
* #4409 should fix the ones about `twisted.test.proto_helpers`

See also #4356
