### ISSUE TITLE
Add a CI job with PYTHONOPTIMIZE=2

### ISSUE THREAD

**Issue by Gallaecio** [scrapy/scrapy#4454]
That way we make sure we do not introduce code that relies on asserts, `__debug__` or docstrings to work, allowing people to use Scrapy when using Python in optimized mode.

**Comment by joybhallaa** [comment]
I can take this issue

**Comment by elacuesta** [comment]
Thanks @joybhallaa, please go ahead if you'd like. Note that it might fail while #4440 is still unmerged.

**Comment by joybhallaa** [comment]
@Gallaecio @elacuesta should I add a job that just exports the `PYTHONOPTIMIZE=2` environment variable, or should it do something else also?

**Comment by Gallaecio** [comment]
I think we can start with that, and see if everything works as expected (or fails as expected in the case of code modified in #4440).

**Comment by Gallaecio** [comment]
https://github.com/scrapy/scrapy/pull/4725#discussion_r477513542
