### ISSUE TITLE
how to close spider immediately

### ISSUE THREAD

**Issue by ggqshr** [scrapy/scrapy#4470]
when i writing spider use some ip proxy ,  i want to close spider immediately when proxy ip resources ran out(by raise ReachDayMax Exception),now when catch the ReachDayMax Exception i just throw the CloseSpider exception in the spider callback, but i dont see the spider close , some time the scrapy will hang-up and dont shutdown immediately,
so i want to ask how to do it.

**Comment by Gallaecio** [comment]
Please, use [StackOverflow](https://stackoverflow.com/tags/scrapy) to ask this type of questions. See [Getting Help](https://docs.scrapy.org/en/latest/#getting-help).
