### ISSUE TITLE
responsetypes.py ResponseTypes.from_headers typo as 'Content-type'

### ISSUE THREAD

**Issue by eric-et** [scrapy/scrapy#4473]
Shall this line:

https://github.com/scrapy/scrapy/blob/8845773d44329194ee73fa4985a94e768bf664e7/scrapy/responsetypes.py#L74

be changed to below?
`
content_type=headers[b'Content-Type'],
`
I guess this typo is with all the versions until today.

**Comment by Gallaecio** [comment]
It does not need to be modified from a functional perspective (`headers` is a case-insensitive dictionary), but we could change it for consistency.

**Comment by kk2496** [comment]
Can i take this up?
