### ISSUE TITLE
Download file when parent contains something

### ISSUE THREAD

**Issue by cdric0701** [scrapy/scrapy#4478]
I am trying to download a file that is contained in an **article** tag.

The one I want to target is the second which contains the phrase **'File Import 2 *'** and whose file is located in the footer of the item (article) ahref.

How can I make my crawler download only this href element?
![second-level](https://user-images.githubusercontent.com/6715950/78814873-ae702e00-79cf-11ea-89be-875561832349.PNG)

Thank you in advance for your help !

**Comment by elacuesta** [comment]
We use the GitHub issue tracker to keep a record of bug reports and feature requests. Please use [the Scrapy tag at StackOverflow](https://stackoverflow.com/tags/scrapy) to ask this kind of questions. See also [Getting Help](https://docs.scrapy.org/en/latest/#getting-help).

**Comment by cdric0701** [comment]
All my excuses.
I just posted my question on stackoverflow with the tag scrapy as you said.
Thanks for the information.
If it interests other people:
https://stackoverflow.com/questions/61109080/download-file-when-parent-contains-something-scrapy-python
