### ISSUE TITLE
Scrapy return nothing on 400 error when scraping https://www.watsons.com.sg/

### ISSUE THREAD

**Issue by pc2000sg** [scrapy/scrapy#4482]
Hi I am trying to scrape content from https://www.watsons.com.sg/. Tested it with scrapy shell and Postman software (with all request headers filled based on what I see  from inspect function in Chrome browser). For some unknown reasons the response body has no real content except:

_**<body>
	<div class="nojavascript alert alert-error">
		<p>The site requires JavaScript to be enabled! The browser you're using doesn't support JavaScript, or has
			JavaScript turned off. <br>Try again with a browser that has JavaScript turned on. <a
				href="https://www.enable-javascript.com/" target="_blank">Learn More</a></p>
	</div>
</body>**_

Wonder if there is anyway to get around this issue? Any suggestions are appreciated. Thanks.

**Comment by Gallaecio** [comment]
Please, use [StackOverflow](https://stackoverflow.com/tags/scrapy) to ask this type of questions. See [Getting Help](https://docs.scrapy.org/en/latest/#getting-help).
