### ISSUE TITLE
TWISTED_REACTOR setting not honored from Spider.custom_settings

### ISSUE THREAD

**Issue by elacuesta** [scrapy/scrapy#4485]
### Description

The value of the `TWISTED_REACTOR` setting is not taken into account if the setting is specified in a spider's `custom_settings` attribute.
It works well if the setting is specified in a project's settings file, as a parameter when creating a `CrawlerProcess` object (as the tests show) or as a CLI argument with the `-s` option. 

### Steps to Reproduce

1. Create a file with the following contents:
```python
# asyncio_spider.py
import asyncio

from scrapy import Spider


class AsyncIOSpider(Spider):
    name = "asyncio"
    start_urls = ["https://example.org"]
    custom_settings = {
        "TWISTED_REACTOR": "twisted.internet.asyncioreactor.AsyncioSelectorReactor",
    }

    async def parse(self, response):
        await asyncio.sleep(1)
        yield {"foo": "bar"}
```

2. Execute the spider: `scrapy runspider asyncio_spider.py`

**Expected behavior:** 
The spider should run fine, without exceptions

**Actual behavior:**
The following exception is raised:
```
2020-04-12 00:04:23 [scrapy.core.scraper] ERROR: Spider error processing <GET https://example.org> (referer: None)
Traceback (most recent call last):
  File "/.../scrapy/venv-scrapy/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/.../scrapy/scrapy/utils/py36.py", line 8, in collect_asyncgen
    async for x in result:
  File "/.../scrapy/test-spiders/asyncio_spider.py", line 14, in parse
    await asyncio.sleep(1)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/tasks.py", line 595, in sleep
    return await future
RuntimeError: await wasn't used with future
```
This is because the `asyncio`-based reactor is not actually installed, as the third log line of the job shows:
```
2020-04-12 00:04:23 [scrapy.utils.log] DEBUG: Using reactor: twisted.internet.selectreactor.SelectReactor
```

Full logs:
```
2020-04-12 00:04:23 [scrapy.utils.log] INFO: Scrapy 2.0.1 started (bot: scrapybot)
2020-04-12 00:04:23 [scrapy.utils.log] INFO: Versions: lxml 4.5.0.0, libxml2 2.9.10, cssselect 1.1.0, parsel 1.5.2, w3lib 1.21.0, Twisted 20.3.0, Python 3.7.4 (v3.7.4:e09359112e, Jul  8 2019, 14:54:52) - [Clang 6.0 (clang-600.0.57)], pyOpenSSL 19.1.0 (OpenSSL 1.1.1d  10 Sep 2019), cryptography 2.8, Platform Darwin-18.7.0-x86_64-i386-64bit
2020-04-12 00:04:23 [scrapy.utils.log] DEBUG: Using reactor: twisted.internet.selectreactor.SelectReactor
2020-04-12 00:04:23 [scrapy.crawler] INFO: Overridden settings:
{'EDITOR': 'nano',
 'SPIDER_LOADER_WARN_ONLY': True,
 'TWISTED_REACTOR': 'twisted.internet.asyncioreactor.AsyncioSelectorReactor'}
2020-04-12 00:04:23 [scrapy.extensions.telnet] INFO: Telnet Password: a2bd966307b319f0
2020-04-12 00:04:23 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.logstats.LogStats']
2020-04-12 00:04:23 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2020-04-12 00:04:23 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2020-04-12 00:04:23 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2020-04-12 00:04:23 [scrapy.core.engine] INFO: Spider opened
2020-04-12 00:04:23 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2020-04-12 00:04:23 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
2020-04-12 00:04:23 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://example.org> (referer: None)
2020-04-12 00:04:23 [asyncio] DEBUG: Using selector: KqueueSelector
2020-04-12 00:04:23 [scrapy.core.scraper] ERROR: Spider error processing <GET https://example.org> (referer: None)
Traceback (most recent call last):
  File "/.../scrapy/venv-scrapy/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/.../scrapy/scrapy/utils/py36.py", line 8, in collect_asyncgen
    async for x in result:
  File "/.../scrapy/test-spiders/asyncio_spider.py", line 14, in parse
    await asyncio.sleep(1)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/tasks.py", line 595, in sleep
    return await future
RuntimeError: await wasn't used with future
2020-04-12 00:04:23 [scrapy.core.engine] INFO: Closing spider (finished)
2020-04-12 00:04:23 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 211,
 'downloader/request_count': 1,
 'downloader/request_method_count/GET': 1,
 'downloader/response_bytes': 1001,
 'downloader/response_count': 1,
 'downloader/response_status_count/200': 1,
 'elapsed_time_seconds': 0.778025,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2020, 4, 12, 3, 4, 23, 925629),
 'log_count/DEBUG': 2,
 'log_count/ERROR': 1,
 'log_count/INFO': 10,
 'memusage/max': 54767616,
 'memusage/startup': 54767616,
 'response_received_count': 1,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'spider_exceptions/RuntimeError': 1,
 'start_time': datetime.datetime(2020, 4, 12, 3, 4, 23, 147604)}
2020-04-12 00:04:23 [scrapy.core.engine] INFO: Spider closed (finished)
```

**Reproduces how often:**
100% of the times.

### Versions
```
Scrapy       : 2.0.1
lxml         : 4.5.0.0
libxml2      : 2.9.10
cssselect    : 1.1.0
parsel       : 1.5.2
w3lib        : 1.21.0
Twisted      : 20.3.0
Python       : 3.7.4 (v3.7.4:e09359112e, Jul  8 2019, 14:54:52) - [Clang 6.0 (clang-600.0.57)]
pyOpenSSL    : 19.1.0 (OpenSSL 1.1.1d  10 Sep 2019)
cryptography : 2.8
Platform     : Darwin-18.7.0-x86_64-i386-64bit
```
```
Scrapy       : 2.0.1
lxml         : 4.5.0.0
libxml2      : 2.9.10
cssselect    : 1.1.0
parsel       : 1.5.2
w3lib        : 1.21.0
Twisted      : 19.10.0
Python       : 3.6.9 (default, Nov  7 2019, 10:44:02) - [GCC 8.3.0]
pyOpenSSL    : 19.1.0 (OpenSSL 1.1.1d  10 Sep 2019)
cryptography : 2.8
Platform     : Linux-4.15.0-96-generic-x86_64-with-LinuxMint-19.1-tessa
```

### Additional context
From a quick look, it seems like this happens because the custom reactor is installed in [`CrawlerRunner.__init__`](https://github.com/scrapy/scrapy/blob/2.0.1/scrapy/crawler.py#L141), but the spider class is only available in [`CrawlerRunner.crawl`](https://github.com/scrapy/scrapy/blob/2.0.1/scrapy/crawler.py#L150) or [`CrawlerRunner.create_crawler`](https://github.com/scrapy/scrapy/blob/2.0.1/scrapy/crawler.py#L192).

**Comment by Carrislol** [comment]
I have encountered the same problem ... A shame not being able to set the reactor you need in the custom configuration of each spider.

**Comment by incognitozen** [comment]
Can reproduce

````
'Scrapy': '2.1.0', 
'lxml': '4.5.0.0', 
'libxml2': '2.9.10', 
'Twisted': '20.3.0', 
'Python': '3.7.5 (default, Nov  7 2019, 10:50:52) - [GCC 8.3.0]', 
'pyOpenSSL': '19.1.0 (OpenSSL 1.1.1g  21 Apr 2020)', 
'Platform': 'Linux-4.15.0-96-generic-x86_64-with-Ubuntu-18.04-bionic'
````

**Comment by lonelyPoker** [comment]
1. Command line mode
 scrapy crawl spider_name
Add the following code in settings.py
`from twisted.internet.asyncioreactor import install
install()
`

2. Executed by CrawlerProcess,Add the following code to the first line
`from twisted.internet.asyncioreactor import install
install()`


A dynamic modified reactor cannot be modified in the Scrapy framework.
@elacuesta @Carrislol

**Comment by sgalich** [comment]
> 1. Command line mode
>    scrapy crawl spider_name
>    Add the following code in settings.py
>    `from twisted.internet.asyncioreactor import install install() `
> 2. Executed by CrawlerProcess,Add the following code to the first line
>    `from twisted.internet.asyncioreactor import install install()`
> 
> A dynamic modified reactor cannot be modified in the Scrapy framework.
> @elacuesta @Carrislol

And what should I do if I need to run my spider via scrapyd with a command like this:
`curl http://123.45.67.890:6800/schedule.json -d project=myparsers -d spider=myspider`

I've got an error `twisted.internet.error.ReactorAlreadyInstalledError: reactor already installed`.

More detailed:

> {"node_name": "5939bc306ca7", "status": "error", "message": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\n    \"__main__\", mod_spec)\n  File \"/usr/local/lib/python3.7/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/usr/local/lib/python3.7/site-packages/scrapyd/runner.py\", line 40, in <module>\n    main()\n  File \"/usr/local/lib/python3.7/site-packages/scrapyd/runner.py\", line 37, in main\n    execute()\n  File \"/usr/local/lib/python3.7/site-packages/scrapy/cmdline.py\", line 113, in execute\n    settings = get_project_settings()\n  File \"/usr/local/lib/python3.7/site-packages/scrapy/utils/project.py\", line 69, in get_project_settings\n    settings.setmodule(settings_module_path, priority='project')\n  File \"/usr/local/lib/python3.7/site-packages/scrapy/settings/__init__.py\", line 287, in setmodule\n    module = import_module(module)\n  File \"/usr/local/lib/python3.7/importlib/__init__.py\", line 127, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n  File \"<frozen importlib._bootstrap>\", line 967, in _find_and_load_unlocked\n  File \"<frozen importlib._bootstrap>\", line 677, in _load_unlocked\n  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n  File \"/opt/other-parsers/spiders/settings.py\", line 3, in <module>\n    install()\n  File \"/usr/local/lib/python3.7/site-packages/twisted/internet/asyncioreactor.py\", line 322, in install\n    installReactor(reactor)\n  File \"/usr/local/lib/python3.7/site-packages/twisted/internet/main.py\", line 32, in installReactor\n    raise error.ReactorAlreadyInstalledError(\"reactor already installed\")\ntwisted.internet.error.ReactorAlreadyInstalledError: reactor already installed\n"}

Does this happen bc of this - https://github.com/scrapy/scrapyd/issues/377 ? Or maybe I have some chance to fix it?

**Comment by wRAR** [comment]
The scrapy script, for any command including crawl and runspider, and before executing the command, creates a `CrawlerProcess` object. It loads settings from things like the project settings and the command line, but it doesn't load the spider custom_settings as it doesn't even look for the spider at this point. `scrapy crawl` calls `CrawlerProcess.crawl` with a spider name  passed to the command while `scrapy runspider` calls `CrawlerProcess.crawl` with a spider class loaded from the file passed to the command. Note that both these use cases could also be used in the user code and have the same problem.

As far as I can see only TWISTED_REACTOR and ASYNCIO_EVENT_LOOP are used by CrawlerProcess/CrawlerRunner before the spider is loaded so this should never happen for any other settings, but for these two I don't see a good way to load them earlier. We could try installing the reactor later, though.

**Comment by wRAR** [comment]
`CrawlerProcess.__init__()` calls `scrapy.utils.ossignal.install_shutdown_handlers()` which calls `reactor._handleSignals()` and so needs an installed reactor at this point. That method is, by the way, not just private but also not documented in the current docs version.

**Comment by wRAR** [comment]
If `install_shutdown_handlers()` is changed so that the reactor is accessed only if it's installed (that will also require other changes to reinstall handlers after Twisted installs them), and move reactor configuration logging from `log_scrapy_info()` to a separate function that is called after the reactor is installed, the next problem is the telnet extension importing `twisted.internet.reactor` (indirectly, via `twisted.conch.insults.helper`). If it's set to None in `EXTENSIONS` (just setting `TELNETCONSOLE_ENABLED` to False shouldn't be enough) then the reactor is installed fine. It should be possible to move the imports inside `__init__` but that just allows using `TELNETCONSOLE_ENABLED` to disable the extension, it still can't be kept enabled.

**Comment by wRAR** [comment]
Actually, initialization of the telnet extension is late enough and should work fine.

**Comment by wRAR** [comment]
Regarding installing signal handlers I've run into an interesting use case: `scrapy shell` creates a `CrawlerProcess` object, runs some of its initialization code and then runs its start() method in a separate thread. Currently this means the signal handlers are installed in the main thread too, and the first thought is that we would want to keep that. But I don't think these handlers actually work, or at least are useful, in `scrapy shell`: Ctrl-C (SIGINT) just doesn't do anything, while in a normal interpreter it e.g. stops an infinite loop (as it raises `KeyboardInterrupt`); sending SIGTERM once or twice prints the normal Scrapy handler messages and I guess actually stops the downloading machinery but this causes the next `fetch()` to block infinitely (not sure what should this signal actually do, kill the process when received twice?).

**Comment by wRAR** [comment]
Actually SIGINT is intentionally blocked in scrapy/shell.py :) "disable accidental Ctrl-C key press from shutting down the engine"

Looks like there can be some improvements here.

**Comment by GeorgeA92** [comment]
[Running multiple spiders in the same process](https://docs.scrapy.org/en/2.5/topics/practices.html#running-multiple-spiders-in-the-same-process)


```python
...
process = CrawlerProcess()
process.crawl(MySpider1)
process.crawl(MySpider2)
process.start()
```

As far as I know:
Running multiple spiders in the same process also means that multiple spiders will use single instantse of `reactor`(1 reactor - per process).

As result: In case if `CrawlerProcess` will have spiders with different reactor settings - it is not clear, what is expected outcome of this? 
```python
process = CrawlerProcess()
process.crawl(MySpider1)
process.crawl(MySpider2_with_TWISTED_REACTOR_in_custom_settings)
process.start()
```

**Comment by wRAR** [comment]
This a really good point. I don't know.

**Comment by wRAR** [comment]
I think we should only support matching settings and take custom_settings from the first spider, while showing an error if the following spiders have different custom_settings.
