### ISSUE TITLE
Pegando dados POST com scrapy - Web Scraping - Python

### ISSUE THREAD

**Issue by rafaelmrd** [scrapy/scrapy#4487]
USA:
I have a question about Scrapy using python.
Can anyone tell me how I get data using POST method with scrapy or selenium.

BR:
Tenho uma dúvida sobre o Scrapy usando python.
Alguém sabe me informar como eu pego dados com metodo POST com scrapy ou selenium

**Comment by elacuesta** [comment]
We use the GitHub issue tracker to keep a record of bug reports and feature requests. Please use [the Scrapy tag at StackOverflow](https://stackoverflow.com/tags/scrapy) to ask this kind of questions. See also [Getting Help](https://docs.scrapy.org/en/latest/#getting-help). Thanks for your understanding.
