### ISSUE TITLE
Twisted headers mapping does nothing for lowercase headers key

### ISSUE THREAD

**Issue by 2239559319** [scrapy/scrapy#4488]
### headers lowercase

[scrapy can not work when headers are lowercase ]

### Steps to Reproduce

1. i must use lowercase headers key and I use Twisted mapping headers and it doesn't work

**Expected behavior:** scrapy run with no exception

**Actual behavior:** scrapy and twisted does nothing for headers

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

Scrapy       : 2.0.1
lxml         : 4.4.1.0
libxml2      : 2.9.5
cssselect    : 1.1.0
parsel       : 1.5.2
w3lib        : 1.21.0
Twisted      : 19.7.0
Python       : 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
pyOpenSSL    : 19.0.0 (OpenSSL 1.1.1c  28 May 2019)
cryptography : 2.7
Platform     : Windows-10-10.0.18362-SP0

### Additional context

I try to rewrite the Request and Headers class but it gives me a line `Please use app access!`

**Comment by elacuesta** [comment]
@2239559319 Please edit the issue to include code which we can use to reproduce the issue.

Sounds like this is related to #2711, is that correct?

**Comment by 2239559319** [comment]
> @2239559319 Please edit the issue to include code which we can use to reproduce the issue.
> 
> Sounds like this is related to #2711, is that correct?

@elacuesta that's it, but i can't  solve this problem. This is my code in spider file
```python
# in this code I hide start_requests function
from twisted.web.http_headers import Headers as TwistedHeaders

TwistedHeaders._caseMappings.update({
    b'cache-control': b'cache-control',
    b'accept': b'accept',
    b'cgAuthorization': b'cgAuthorization',
})

from scrapy import Spider, Request
from scrapy import FormRequest
from ..items import KaoshiItem
import json

class Kaoshi(Spider):

    name = 'tiyu'

    def getAuthor(self, response):

        headers = {
            'Host': '202.115.33.181',
            'User-Agent': 'cgapp/2.6.7 (Linux; Android 8.0.0; Xiaomi/OPR1.170623.032)',
            'Accept-Encoding': 'gzip, deflate',
            'Accept': '*/*',
            'Connection': 'keep-alive'
        }
        dic = json.loads(response.text, encoding='utf-8')
        headers['cgAuthorization'] = dic['data']


        yield Request(url='http://202.115.33.181/tyexam/app//redir.php?newPage=1&catalog_id=6&cmd=chengjis',
                      headers=headers,
                      callback=self.getNumber,
                      meta={'headers': headers})

    def getNumber(self, response):
        print(response.request.headers)     # in headers cgAuthorization is b'Cgauthorization'

```

and this is output
```
{b'Host': [b'202.115.33.181'], b'User-Agent': [b'cgapp/2.6.7 (Linux; Android 8.0.0; Xiaomi/OPR1.170623.032)'], b'Accept-Encoding': [b'
gzip, deflate'], b'Accept': [b'*/*'], b'Connection': [b'keep-alive'], b'Cgauthorization': [b'50982224-c5af-bbb6-9419-d1278463964f'], b
'Referer': [b'http://202.115.33.181/tyexam/api/l/v6/token'], b'Accept-Language': [b'en']}

```

**Comment by elacuesta** [comment]
Yes, seems like that workaround stopped working a while ago: https://github.com/scrapy/scrapy/issues/3981#issuecomment-526284476.

This was originally reported in #2711 and re-reported in #3981, so in the spirit of keeping the tracker clean, I'm closing this issue as a duplicate. Please add any additional information you might have in #2711.
