### ISSUE TITLE
inifinit websites - crawl entire net

### ISSUE THREAD

**Issue by cullsin** [scrapy/scrapy#4491]
### Description
I want to crawl all the venture capital URLs in the internet. I can see that URL as an Input to scrapy. Can you please recommend how to do this ?

**Comment by elacuesta** [comment]
We use the GitHub issue tracker to keep a record of bug reports and feature requests. Please use [the Scrapy tag at StackOverflow](https://stackoverflow.com/tags/scrapy) to ask this kind of questions. See also [Getting Help](https://docs.scrapy.org/en/latest/#getting-help). Thanks for your understanding.
