### ISSUE TITLE
Extend hoverxref_roles

### ISSUE THREAD

**Issue by Gallaecio** [scrapy/scrapy#4495]
@humitos [suggested](https://github.com/scrapy/scrapy/issues/4475#issuecomment-613350667) extending the `hoverxref_roles` setting of the corresponding Sphinx extension so that the display-on-hover behavior of the documentations works for things like signal or setting references.

**Comment by redrolor** [comment]
I'd like to give this a shot.

**Comment by willbeaufoy** [comment]
@redrolor are you still working on this? If not I can take it.

**Comment by willbeaufoy** [comment]
As @redrolor didn't reply I have sent a pull request for this.
