### ISSUE TITLE
Fix the “The Windows bytes API has been deprecated” warning

### ISSUE THREAD

**Issue by Gallaecio** [scrapy/scrapy#4497]
Seen in [Windows test runs](https://github.com/scrapy/scrapy/pull/4458).

**Comment by AKSHAYSHARMAJS** [comment]
I want to work on this issue. I tried running test using tox locally on windows which doesn't show this warning but azure pipelines do capture this warning.

**Comment by Gallaecio** [comment]
It looks related to `os` functions, which may return bytes for things like `getcwd`. But I cannot tell more without looking into the issue in detail myself. I do find strange that you do not get those warnings on Windows locally, though.

**Comment by AKSHAYSHARMAJS** [comment]
I also find that strange. I have shared my log file of `tox` command maybe that will help.
[output.txt](https://github.com/scrapy/scrapy/files/5010152/output.txt)

**Comment by AKSHAYSHARMAJS** [comment]
Please check the azure pipelines builds in #4646 don't show these warnings.

**Comment by Gallaecio** [comment]
I can see them in the logs of the [latest builds](https://scrapinghub.visualstudio.com/scrapy/_build?definitionId=1&_a=summary&repositoryFilter=1&branchFilter=7%2C7%2C7%2C7%2C7%2C7).

**Comment by Gallaecio** [comment]
https://github.com/scrapy/scrapy/pull/5682
