### ISSUE TITLE
Crawlers won't shutdown gracefully on SIGINT

### ISSUE THREAD

**Issue by demji** [scrapy/scrapy#450]
Hello,

Crawlers won't shutdown gracefully since CrawlerProcess' `_start_crawler` method pops crawlers off the `self.crawlers` list, which is where the `stop` method looks for crawlers to stop.

Steps to reproduce:

1) scrapy crawl <spider>
2) Send SIGINT via Ctrl-c
3) Crawler continues running after displaying "2013-11-01 09:24:49-0400 [scrapy] INFO: Received SIGINT, shutting down gracefully. Send again to force"

$ scrapy version -v
Scrapy  : 0.18.4
lxml    : 3.2.3.0
libxml2 : 2.9.1
Twisted : 13.1.0
Python  : 2.7.5 (default, Aug 17 2013, 13:35:16) - [GCC 4.6.3]
Platform: Linux-3.10.7-gentoo-r1-x86_64-Intel-R-_Core-TM-2_Quad_CPU_Q9550_@_2.83GHz-with-gentoo-2.2

Regards,
demji

**Comment by nickeldan** [comment]
I'm getting this exact issue on version 2.11.2.

**Comment by Gallaecio** [comment]
Then please open a separate issue with a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
