### ISSUE TITLE
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

### ISSUE THREAD

**Issue by alirezadizaji** [scrapy/scrapy#4501]
### Description
Hi :), I have a requirements.txt and I run it  by `pip install -r requirements.txt`.
and in some point I got this error `Building wheel for gnureadline (setup.py) ... error`.
I saw the same issues but they didn't help.
here is the whole error:
` Building wheel for gnureadline (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /media/assignment1/.env/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-mdc0qyyt/gnureadline/setup.py'"'"'; __file__='"'"'/tmp/pip-install-mdc0qyyt/gnureadline/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-loxqpxxp
       cwd: /tmp/pip-install-mdc0qyyt/gnureadline/
  Complete output (475 lines):
  
  ============ Building the readline library ============
  
  readline-6.3/
  readline-6.3/doc/
  readline-6.3/doc/Makefile.in
  readline-6.3/doc/texinfo.tex
  readline-6.3/doc/version.texi
  readline-6.3/doc/fdl.texi
  readline-6.3/doc/rlman.texi
  readline-6.3/doc/rltech.texi
  readline-6.3/doc/rluser.texi
  readline-6.3/doc/rluserman.texi
  readline-6.3/doc/history.texi
  readline-6.3/doc/hstech.texi
  readline-6.3/doc/hsuser.texi
  readline-6.3/doc/readline.3
  readline-6.3/doc/history.3
  readline-6.3/doc/texi2dvi
  readline-6.3/doc/texi2html
  readline-6.3/doc/readline.ps
  readline-6.3/doc/history.ps
  readline-6.3/doc/rluserman.ps
  readline-6.3/doc/readline.dvi
  readline-6.3/doc/history.dvi
  readline-6.3/doc/rluserman.dvi
  readline-6.3/doc/readline.info
  readline-6.3/doc/history.info
  readline-6.3/doc/rluserman.info
  readline-6.3/doc/readline.html
  readline-6.3/doc/history.html
  readline-6.3/doc/rluserman.html
  readline-6.3/doc/readline.0
  readline-6.3/doc/history.0
  readline-6.3/doc/readline_3.ps
  readline-6.3/doc/history_3.ps
  readline-6.3/doc/history.pdf
  readline-6.3/doc/readline.pdf
  readline-6.3/doc/rluserman.pdf
  readline-6.3/examples/
  readline-6.3/examples/autoconf/
  readline-6.3/examples/autoconf/BASH_CHECK_LIB_TERMCAP
  readline-6.3/examples/autoconf/RL_LIB_READLINE_VERSION
  readline-6.3/examples/autoconf/wi_LIB_READLINE
  readline-6.3/examples/rlfe/
  readline-6.3/examples/rlfe/ChangeLog
  readline-6.3/examples/rlfe/Makefile.in
  readline-6.3/examples/rlfe/README
  readline-6.3/examples/rlfe/config.h.in
  readline-6.3/examples/rlfe/configure
  readline-6.3/examples/rlfe/configure.in
  readline-6.3/examples/rlfe/extern.h
  readline-6.3/examples/rlfe/os.h
  readline-6.3/examples/rlfe/pty.c
  readline-6.3/examples/rlfe/rlfe.c
  readline-6.3/examples/rlfe/screen.h
  readline-6.3/examples/Makefile.in
  readline-6.3/examples/excallback.c
  readline-6.3/examples/fileman.c
  readline-6.3/examples/manexamp.c
  readline-6.3/examples/readlinebuf.h
  readline-6.3/examples/rl-fgets.c
  readline-6.3/examples/rlcat.c
  readline-6.3/examples/rlevent.c
  readline-6.3/examples/rltest.c
  readline-6.3/examples/rl-callbacktest.c
  readline-6.3/examples/rl.c
  readline-6.3/examples/rlptytest.c
  readline-6.3/examples/rlversion.c
  readline-6.3/examples/histexamp.c
  readline-6.3/examples/hist_erasedups.c
  readline-6.3/examples/hist_purgecmd.c
  readline-6.3/examples/Inputrc
  readline-6.3/examples/rlwrap-0.30.tar.gz
  readline-6.3/support/
  readline-6.3/support/config.guess
  readline-6.3/support/config.rpath
  readline-6.3/support/config.sub
  readline-6.3/support/install.sh
  readline-6.3/support/mkdirs
  readline-6.3/support/mkdist
  readline-6.3/support/mkinstalldirs
  readline-6.3/support/shobj-conf
  readline-6.3/support/shlib-install
  readline-6.3/support/wcwidth.c
  readline-6.3/shlib/
  readline-6.3/shlib/Makefile.in
  readline-6.3/COPYING
  readline-6.3/README
  readline-6.3/MANIFEST
  readline-6.3/INSTALL
  readline-6.3/CHANGELOG
  readline-6.3/CHANGES
  readline-6.3/NEWS
  readline-6.3/USAGE
  readline-6.3/aclocal.m4
  readline-6.3/config.h.in
  readline-6.3/configure
  readline-6.3/configure.ac
  readline-6.3/Makefile.in
  readline-6.3/ansi_stdlib.h
  readline-6.3/chardefs.h
  readline-6.3/colors.h
  readline-6.3/history.h
  readline-6.3/histlib.h
  readline-6.3/keymaps.h
  readline-6.3/parse-colors.h
  readline-6.3/rlconf.h
  readline-6.3/posixdir.h
  readline-6.3/posixjmp.h
  readline-6.3/posixselect.h
  readline-6.3/posixstat.h
  readline-6.3/readline.h
  readline-6.3/rldefs.h
  readline-6.3/rlmbutil.h
  readline-6.3/rlprivate.h
  readline-6.3/rlshell.h
  readline-6.3/rlstdc.h
  readline-6.3/rltty.h
  readline-6.3/rltypedefs.h
  readline-6.3/rlwinsize.h
  readline-6.3/tcap.h
  readline-6.3/tilde.h
  readline-6.3/xmalloc.h
  readline-6.3/bind.c
  readline-6.3/callback.c
  readline-6.3/colors.c
  readline-6.3/compat.c
  readline-6.3/complete.c
  readline-6.3/display.c
  readline-6.3/emacs_keymap.c
  readline-6.3/funmap.c
  readline-6.3/input.c
  readline-6.3/isearch.c
  readline-6.3/keymaps.c
  readline-6.3/kill.c
  readline-6.3/macro.c
  readline-6.3/mbutil.c
  readline-6.3/misc.c
  readline-6.3/nls.c
  readline-6.3/parens.c
  readline-6.3/parse-colors.c
  readline-6.3/readline.c
  readline-6.3/rltty.c
  readline-6.3/savestring.c
  readline-6.3/search.c
  readline-6.3/shell.c
  readline-6.3/signals.c
  readline-6.3/terminal.c
  readline-6.3/text.c
  readline-6.3/tilde.c
  readline-6.3/undo.c
  readline-6.3/util.c
  readline-6.3/vi_keymap.c
  readline-6.3/vi_mode.c
  readline-6.3/xfree.c
  readline-6.3/xmalloc.c
  readline-6.3/history.c
  readline-6.3/histexpand.c
  readline-6.3/histfile.c
  readline-6.3/histsearch.c
  readline-6.3/patchlevel
  patching file readline.c
  patching file patchlevel
  patching file readline.c
  patching file patchlevel
  patching file util.c
  patching file patchlevel
  checking build system type... x86_64-unknown-linux-gnu
  checking host system type... x86_64-unknown-linux-gnu
  
  Beginning configuration for readline-6.3 for x86_64-unknown-linux-gnu
  
  checking whether make sets $(MAKE)... yes
  checking for gcc... gcc
  checking whether the C compiler works... yes
  checking for C compiler default output file name... a.out
  checking for suffix of executables...
  checking whether we are cross compiling... no
  checking for suffix of object files... o
  checking whether we are using the GNU C compiler... yes
  checking whether gcc accepts -g... yes
  checking for gcc option to accept ISO C89... none needed
  checking how to run the C preprocessor... gcc -E
  checking for grep that handles long lines and -e... /bin/grep
  checking for egrep... /bin/grep -E
  checking for ANSI C header files... yes
  checking for sys/types.h... yes
  checking for sys/stat.h... yes
  checking for stdlib.h... yes
  checking for string.h... yes
  checking for memory.h... yes
  checking for strings.h... yes
  checking for inttypes.h... yes
  checking for stdint.h... yes
  checking for unistd.h... yes
  checking minix/config.h usability... no
  checking minix/config.h presence... no
  checking for minix/config.h... no
  checking whether it is safe to define __EXTENSIONS__... yes
  checking whether gcc needs -traditional... no
  checking for a BSD-compatible install... /usr/bin/install -c
  checking for ar... ar
  checking for ranlib... ranlib
  checking for an ANSI C-conforming const... yes
  checking for function prototypes... yes
  checking whether char is unsigned... no
  checking for working volatile... yes
  checking return type of signal handlers... void
  checking for size_t... yes
  checking for ssize_t... yes
  checking for ANSI C header files... (cached) yes
  checking whether stat file-mode macros are broken... no
  checking for dirent.h that defines DIR... yes
  checking for library containing opendir... none required
  checking for fcntl... yes
  checking for kill... yes
  checking for lstat... yes
  checking for memmove... yes
  checking for putenv... yes
  checking for select... yes
  checking for setenv... yes
  checking for setlocale... yes
  checking for strcasecmp... yes
  checking for strpbrk... yes
  checking for tcgetattr... yes
  checking for vsnprintf... yes
  checking for isascii... yes
  checking for isxdigit... yes
  checking for getpwent... yes
  checking for getpwnam... yes
  checking for getpwuid... yes
  checking for working strcoll... yes
  checking fcntl.h usability... yes
  checking fcntl.h presence... yes
  checking for fcntl.h... yes
  checking for unistd.h... (cached) yes
  checking for stdlib.h... (cached) yes
  checking varargs.h usability... no
  checking varargs.h presence... no
  checking for varargs.h... no
  checking stdarg.h usability... yes
  checking stdarg.h presence... yes
  checking for stdarg.h... yes
  checking stdbool.h usability... yes
  checking stdbool.h presence... yes
  checking for stdbool.h... yes
  checking for string.h... (cached) yes
  checking for strings.h... (cached) yes
  checking limits.h usability... yes
  checking limits.h presence... yes
  checking for limits.h... yes
  checking locale.h usability... yes
  checking locale.h presence... yes
  checking for locale.h... yes
  checking pwd.h usability... yes
  checking pwd.h presence... yes
  checking for pwd.h... yes
  checking for memory.h... (cached) yes
  checking termcap.h usability... no
  checking termcap.h presence... no
  checking for termcap.h... no
  checking termios.h usability... yes
  checking termios.h presence... yes
  checking for termios.h... yes
  checking termio.h usability... yes
  checking termio.h presence... yes
  checking for termio.h... yes
  checking sys/pte.h usability... no
  checking sys/pte.h presence... no
  checking for sys/pte.h... no
  checking sys/stream.h usability... no
  checking sys/stream.h presence... no
  checking for sys/stream.h... no
  checking sys/select.h usability... yes
  checking sys/select.h presence... yes
  checking for sys/select.h... yes
  checking sys/file.h usability... yes
  checking sys/file.h presence... yes
  checking for sys/file.h... yes
  checking for sys/ptem.h... no
  checking for special C compiler options needed for large files... no
  checking for _FILE_OFFSET_BITS value needed for large files... no
  checking for type of signal functions... posix
  checking if signal handlers must be reinstalled when invoked... no
  checking for presence of POSIX-style sigsetjmp/siglongjmp... present
  checking for lstat... yes
  checking whether or not strcoll and strcmp differ... no
  checking whether the ctype macros accept non-ascii characters... no
  checking whether getpw functions are declared in pwd.h... yes
  checking whether termios.h defines TIOCGWINSZ... no
  checking whether sys/ioctl.h defines TIOCGWINSZ... yes
  checking for sig_atomic_t in signal.h... yes
  checking whether signal handlers are of type void... yes
  checking for TIOCSTAT in sys/ioctl.h... no
  checking for FIONREAD in sys/ioctl.h... yes
  checking for speed_t in sys/types.h... no
  checking for struct winsize in sys/ioctl.h and termios.h... sys/ioctl.h
  checking for struct dirent.d_ino... yes
  checking for struct dirent.d_fileno... yes
  checking whether AUDIT_USER_TTY is declared... yes
  checking for tgetent... no
  checking for tgetent in -ltermcap... no
  checking for tgetent in -ltinfo... no
  checking for tgetent in -lcurses... no
  checking for tgetent in -lncurses... no
  checking which library has the termcap functions... using gnutermcap
  checking wctype.h usability... yes
  checking wctype.h presence... yes
  checking for wctype.h... yes
  checking wchar.h usability... yes
  checking wchar.h presence... yes
  checking for wchar.h... yes
  checking langinfo.h usability... yes
  checking langinfo.h presence... yes
  checking for langinfo.h... yes
  checking for mbrlen... yes
  checking for mbscasecmp... no
  checking for mbscmp... no
  checking for mbsnrtowcs... yes
  checking for mbsrtowcs... yes
  checking for mbschr... no
  checking for wcrtomb... yes
  checking for wcscoll... yes
  checking for wcsdup... yes
  checking for wcwidth... yes
  checking for wctype... yes
  checking for wcswidth... yes
  checking whether mbrtowc and mbstate_t are properly declared... yes
  checking for iswlower... yes
  checking for iswupper... yes
  checking for towlower... yes
  checking for towupper... yes
  checking for iswctype... yes
  checking for nl_langinfo and CODESET... yes
  checking for wchar_t in wchar.h... yes
  checking for wctype_t in wctype.h... yes
  checking for wint_t in wctype.h... yes
  checking for wcwidth broken with unicode combining characters...
  checking configuration for building shared libraries... supported
  configure: creating ./config.status
  config.status: creating Makefile
  config.status: creating doc/Makefile
  config.status: creating examples/Makefile
  config.status: creating shlib/Makefile
  config.status: creating config.h
  config.status: executing default commands
  rm -f readline.o
  gcc -c -DHAVE_CONFIG_H   -DNEED_EXTERN_PC -fPIC -I. -I. -DRL_LIBRARY_VERSION='"6.3"' -g -O readline.c
  rm -f vi_mode.o
  gcc -c -DHAVE_CONFIG_H   -DNEED_EXTERN_PC -fPIC -I. -I. -DRL_LIBRARY_VERSION='"6.3"' -g -O vi_mode.c
  rm -f funmap.o
  gcc -c -DHAVE_CONFIG_H   -DNEED_EXTERN_PC -fPIC -I. -I. -DRL_LIBRARY_VERSION='"6.3"' -g -O funmap.c
  rm -f keymaps.o
  gcc -c -DHAVE_CONFIG_H   -DNEED_EXTERN_PC -fPIC -I. -I. -DRL_LIBRARY_VERSION='"6.3"' -g -O keymaps.c
  rm -f parens.o
  gcc -c -DHAVE_CONFIG_H   -DNEED_EXTERN_PC -fPIC -I. -I. -DRL_LIBRARY_VERSION='"6.3"' -g -O parens.c
  rm -f search.o
  gcc -c -DHAVE_CONFIG_H   -DNEED_EXTERN_PC -fPIC -I. -I. -DRL_LIBRARY_VERSION='"6.3"' -g -O search.c
  rm -f rltty.o
  gcc -c -DHAVE_CONFIG_H   -DNEED_EXTERN_PC -fPIC -I. -I. -DRL_LIBRARY_VERSION='"6.3"' -g -O rltty.c
  rm -f complete.o
  gcc -c -DHAVE_CONFIG_H   -DNEED_EXTERN_PC -fPIC -I. -I. -DRL_LIBRARY_VERSION='"6.3"' -g -O complete.c
  In file included from complete.c:62:0:
  complete.c: In function ‘fnwidth’:
  rlmbutil.h:132:23: warning: implicit declaration of function ‘wcwidth’; did you mean ‘fnwidth’? [-Wimplicit-function-declaration]
   #  define WCWIDTH(wc) wcwidth(wc)
                         ^
  complete.c:746:12: note: in expansion of macro ‘WCWIDTH’
          w = WCWIDTH (wc);
              ^~~~~~~
  rm -f bind.o
  gcc -c -DHAVE_CONFIG_H   -DNEED_EXTERN_PC -fPIC -I. -I. -DRL_LIBRARY_VERSION='"6.3"' -g -O bind.c
  rm -f isearch.o
  gcc -c -DHAVE_CONFIG_H   -DNEED_EXTERN_PC -fPIC -I. -I. -DRL_LIBRARY_VERSION='"6.3"' -g -O isearch.c
  rm -f display.o
  gcc -c -DHAVE_CONFIG_H   -DNEED_EXTERN_PC -fPIC -I. -I. -DRL_LIBRARY_VERSION='"6.3"' -g -O display.c
  In file included from display.c:50:0:
  display.c: In function ‘rl_redisplay’:
  rlmbutil.h:132:23: warning: implicit declaration of function ‘wcwidth’ [-Wimplicit-function-declaration]
   #  define WCWIDTH(wc) wcwidth(wc)
                         ^
  display.c:804:15: note: in expansion of macro ‘WCWIDTH’
          temp = WCWIDTH (wc);
                 ^~~~~~~
  rm -f signals.o
  gcc -c -DHAVE_CONFIG_H   -DNEED_EXTERN_PC -fPIC -I. -I. -DRL_LIBRARY_VERSION='"6.3"' -g -O signals.c
  rm -f util.o
  gcc -c -DHAVE_CONFIG_H   -DNEED_EXTERN_PC -fPIC -I. -I. -DRL_LIBRARY_VERSION='"6.3"' -g -O util.c
  rm -f kill.o
  gcc -c -DHAVE_CONFIG_H   -DNEED_EXTERN_PC -fPIC -I. -I. -DRL_LIBRARY_VERSION='"6.3"' -g -O kill.c
  rm -f undo.o
  gcc -c -DHAVE_CONFIG_H   -DNEED_EXTERN_PC -fPIC -I. -I. -DRL_LIBRARY_VERSION='"6.3"' -g -O undo.c
  rm -f macro.o
  gcc -c -DHAVE_CONFIG_H   -DNEED_EXTERN_PC -fPIC -I. -I. -DRL_LIBRARY_VERSION='"6.3"' -g -O macro.c
  rm -f input.o
  gcc -c -DHAVE_CONFIG_H   -DNEED_EXTERN_PC -fPIC -I. -I. -DRL_LIBRARY_VERSION='"6.3"' -g -O input.c
  rm -f callback.o
  gcc -c -DHAVE_CONFIG_H   -DNEED_EXTERN_PC -fPIC -I. -I. -DRL_LIBRARY_VERSION='"6.3"' -g -O callback.c
  rm -f terminal.o
  gcc -c -DHAVE_CONFIG_H   -DNEED_EXTERN_PC -fPIC -I. -I. -DRL_LIBRARY_VERSION='"6.3"' -g -O terminal.c
  rm -f text.o
  gcc -c -DHAVE_CONFIG_H   -DNEED_EXTERN_PC -fPIC -I. -I. -DRL_LIBRARY_VERSION='"6.3"' -g -O text.c
  rm -f nls.o
  gcc -c -DHAVE_CONFIG_H   -DNEED_EXTERN_PC -fPIC -I. -I. -DRL_LIBRARY_VERSION='"6.3"' -g -O nls.c
  rm -f misc.o
  gcc -c -DHAVE_CONFIG_H   -DNEED_EXTERN_PC -fPIC -I. -I. -DRL_LIBRARY_VERSION='"6.3"' -g -O misc.c
  rm -f history.o
  gcc -c -DHAVE_CONFIG_H   -DNEED_EXTERN_PC -fPIC -I. -I. -DRL_LIBRARY_VERSION='"6.3"' -g -O history.c
  rm -f histexpand.o
  gcc -c -DHAVE_CONFIG_H   -DNEED_EXTERN_PC -fPIC -I. -I. -DRL_LIBRARY_VERSION='"6.3"' -g -O histexpand.c
  rm -f histfile.o
  gcc -c -DHAVE_CONFIG_H   -DNEED_EXTERN_PC -fPIC -I. -I. -DRL_LIBRARY_VERSION='"6.3"' -g -O histfile.c
  rm -f histsearch.o
  gcc -c -DHAVE_CONFIG_H   -DNEED_EXTERN_PC -fPIC -I. -I. -DRL_LIBRARY_VERSION='"6.3"' -g -O histsearch.c
  rm -f shell.o
  gcc -c -DHAVE_CONFIG_H   -DNEED_EXTERN_PC -fPIC -I. -I. -DRL_LIBRARY_VERSION='"6.3"' -g -O shell.c
  rm -f mbutil.o
  gcc -c -DHAVE_CONFIG_H   -DNEED_EXTERN_PC -fPIC -I. -I. -DRL_LIBRARY_VERSION='"6.3"' -g -O mbutil.c
  In file included from mbutil.c:47:0:
  mbutil.c: In function ‘_rl_find_next_mbchar_internal’:
  rlmbutil.h:132:23: warning: implicit declaration of function ‘wcwidth’ [-Wimplicit-function-declaration]
   #  define WCWIDTH(wc) wcwidth(wc)
                         ^
  mbutil.c:125:12: note: in expansion of macro ‘WCWIDTH’
          if (WCWIDTH (wc) == 0)
              ^~~~~~~
  rm -f tilde.o
  gcc -DHAVE_CONFIG_H   -DNEED_EXTERN_PC -fPIC -I. -I. -DRL_LIBRARY_VERSION='"6.3"' -g -O -DREADLINE_LIBRARY -c ./tilde.c
  rm -f colors.o
  gcc -c -DHAVE_CONFIG_H   -DNEED_EXTERN_PC -fPIC -I. -I. -DRL_LIBRARY_VERSION='"6.3"' -g -O colors.c
  rm -f parse-colors.o
  gcc -c -DHAVE_CONFIG_H   -DNEED_EXTERN_PC -fPIC -I. -I. -DRL_LIBRARY_VERSION='"6.3"' -g -O parse-colors.c
  rm -f xmalloc.o
  gcc -c -DHAVE_CONFIG_H   -DNEED_EXTERN_PC -fPIC -I. -I. -DRL_LIBRARY_VERSION='"6.3"' -g -O xmalloc.c
  rm -f xfree.o
  gcc -c -DHAVE_CONFIG_H   -DNEED_EXTERN_PC -fPIC -I. -I. -DRL_LIBRARY_VERSION='"6.3"' -g -O xfree.c
  rm -f compat.o
  gcc -c -DHAVE_CONFIG_H   -DNEED_EXTERN_PC -fPIC -I. -I. -DRL_LIBRARY_VERSION='"6.3"' -g -O compat.c
  rm -f libreadline.a
  ar cr libreadline.a readline.o vi_mode.o funmap.o keymaps.o parens.o search.o rltty.o complete.o bind.o isearch.o display.o signals.o util.o kill.o undo.o macro.o input.o callback.o terminal.o text.o nls.o misc.o history.o histexpand.o histfile.o histsearch.o shell.o mbutil.o tilde.o colors.o parse-colors.o xmalloc.o xfree.o compat.o
  test -n "ranlib" && ranlib libreadline.a
  rm -f libhistory.a
  ar cr libhistory.a history.o histexpand.o histfile.o histsearch.o shell.o mbutil.o xmalloc.o xfree.o
  test -n "ranlib" && ranlib libhistory.a
  
  ============ Building the readline extension module ============
  
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  copying readline.py -> build/lib.linux-x86_64-3.6
  running egg_info
  writing gnureadline.egg-info/PKG-INFO
  writing dependency_links to gnureadline.egg-info/dependency_links.txt
  writing top-level names to gnureadline.egg-info/top_level.txt
  reading manifest file 'gnureadline.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'gnureadline.egg-info/SOURCES.txt'
  running build_ext
  building 'gnureadline' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/Modules
  creating build/temp.linux-x86_64-3.6/Modules/3.x
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DHAVE_RL_CALLBACK -DHAVE_RL_CATCH_SIGNAL -DHAVE_RL_COMPLETION_APPEND_CHARACTER -DHAVE_RL_COMPLETION_DISPLAY_MATCHES_HOOK -DHAVE_RL_COMPLETION_MATCHES -DHAVE_RL_COMPLETION_SUPPRESS_APPEND -DHAVE_RL_PRE_INPUT_HOOK -I. -I/usr/include/python3.6m -I/media/assignment1/.env/include/python3.6m -c Modules/3.x/readline.c -o build/temp.linux-x86_64-3.6/Modules/3.x/readline.o
  Modules/3.x/readline.c: In function ‘PyInit_gnureadline’:
  Modules/3.x/readline.c:1207:34: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
       PyOS_ReadlineFunctionPointer = call_readline;
                                    ^
  x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/Modules/3.x/readline.o readline/libreadline.a readline/libhistory.a -lncurses -o build/lib.linux-x86_64-3.6/gnureadline.cpython-36m-x86_64-linux-gnu.so
  /usr/bin/ld: cannot find -lncurses
  collect2: error: ld returned 1 exit status
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for gnureadline
`

**Comment by wRAR** [comment]
gnureadline is not Scrapy, sorry.
