### ISSUE TITLE
Scrapy LinkExtractor not able to extracts absolute urls

### ISSUE THREAD

**Issue by rahulmarlabs** [scrapy/scrapy#4502]
### Description

Scrapy LinkExtractor not able to extracts absolute urls

### Steps to Reproduce

```
from scrapy.linkextractors import LinkExtractor
from scrapy.http import HtmlResponse

html ="""<html>
<body>
    <a href="/en/veterinary-regulatory/post-authorisation" class="ema-context-banner__link">Post-authorisation</a>
    <a href="https://www.ema.europa.eu/documents/overview/ritonavir-mylan-epar-summary-public_fr.pdf" target="_blank" class="ecl-link ecl-link--ema-obvious ecl-file__translations-title">French</a>
</body>
</html>"""

response = HtmlResponse(url="http://www.ema.europa.eu",body=bytes(html, encoding='utf8'))
le = LinkExtractor()

links = le.extract_links(response)
print(links)
```

`OUTPUT:  [Link(url='http://www.ema.europa.eu/en/veterinary-regulatory/post-authorisation', text='Post-authorisation', fragment='', nofollow=False)]`

**Expected behavior:**  It is supposed to extract both the urls

**Actual behavior:** But it does not extract absolute URL  

**Reproduces how often:** Every time

### Versions

Scrapy       : 2.0.1
lxml         : 4.5.0.0
libxml2      : 2.9.10
cssselect    : 1.1.0
parsel       : 1.5.2
w3lib        : 1.21.0
Twisted      : 20.3.0
Python       : 3.7.3 (default, Mar 27 2019, 22:11:17) - [GCC 7.3.0]
pyOpenSSL    : 19.1.0 (OpenSSL 1.1.1f  31 Mar 2020)
cryptography : 2.9
Platform     : Linux-5.3.0-40-generic-x86_64-with-debian-buster-sid

**Comment by wRAR** [comment]
It's ignored not because it's absolute but because it's a PDF.

> deny_extensions (list) –
> a single value or list of strings containing extensions that should be ignored when extracting links. If not given, it will default to scrapy.linkextractors.IGNORED_EXTENSIONS.
