### ISSUE TITLE
configure_logging documentation example incomplete

### ISSUE THREAD

**Issue by vccolombo** [scrapy/scrapy#4510]
Hello!

I think the [configure_logging](https://docs.scrapy.org/en/latest/topics/logging.html#scrapy.utils.log.configure_logging) example is missing something. It imports `configure_logging` but never uses it.

Could you take a look at it please?
Thank you!

**Comment by Gallaecio** [comment]
Looks like we just need to remove that import, it’s a leftover from https://github.com/scrapy/scrapy/pull/3960
