### ISSUE TITLE
Outdated item pipeline example about Deferred

### ISSUE THREAD

**Issue by elacuesta** [scrapy/scrapy#4514]
The [_Take screenshot of item_](https://docs.scrapy.org/en/latest/topics/item-pipeline.html#take-screenshot-of-item) example says "This example demonstrates how to return a Deferred from the process_item() method", but that is no longer the case (async/await syntax is currently used).
I think we should remove that sentence ~and add a reminder about [enabling the `asyncio` reactor](https://docs.scrapy.org/en/latest/topics/asyncio.html#installing-the-asyncio-reactor).~

Also, I wonder if it'd be good to also restore the previous `Deferred` example and keep both of them, since not all projects might be able/willing to switch to the `asyncio` reactor.

**Comment by Gallaecio** [comment]
I believe that the example now uses coroutines, but not asyncio, so it should work with a regular Twisted reactor.

PS: I used to mix the two of them as well until @kmike and @wRAR illuminated me.

**Comment by elacuesta** [comment]
I've read [this article](https://snarky.ca/how-the-heck-does-async-await-work-in-python-3-5/#thinkofasyncawaitasanapiforasynchronousprogramming) a few times, which shows how to use async/await independently from `asyncio`, but I still get confused sometimes. Might be time to read it again!
In any case, there is no Deferred in play anymore, that needs to be addressed.

**Comment by incognitozen** [comment]
The docs need an example of a spider with asynio enabled and used.

**Comment by Gallaecio** [comment]
A simple spider does not require asyncio, and a complex spider would not make for a good example. 

On the other hand, it may be useful to cover, for example, an example item pipeline that uses an asyncio-based SQL client to record items in a database.
