### ISSUE TITLE
Weird args and proxy behavior in lua script when resending a splash request

### ISSUE THREAD

**Issue by jeremfrs** [scrapy/scrapy#4515]
I encoutered some weird args behaviors in lua.

I create my SplashRequest like so:
`yield SplashRequest(url=url,
                callback=self.parse,
                endpoint='execute',
                args={
                    'lua_source': self.LUA_SOURCE,
                    'pproxy': "NOT_WORKING_PROXY",
                    'wait': 3,
                },
                cache_args=['lua_source']
            )`

And when my proxy isn't working i catch it in my middleware and i send back the same request but with another proxy:

```def process_response(self, request, response, spider):
def process_response(self, request, response, spider):
        print("\tEntering process_response-------------------------------")

        print(response.status)
        if (response.status == 504 or response.status == 400):
            meta = deepcopy(response.request.meta)
            meta["splash"]["args"]["pproxy"] = "WORKING_PROXY"
            newrq = response.request.replace(meta=meta, dont_filter=True)
            return newrq

        return response
```

I double checked, newrq has the "WORKING_PROXY" and not the "NOT_WORKING_PROXY"

So now here is the lua code in self.LUA_SOURCE
```
function useproxy(splash)
    local host = splash.args.pproxy
    local port = 80

    print(host)
    splash:on_request(function (request)
        print(host)
        request:set_proxy{host, port, username="myuser", password="mypwd"}
    end)
end

function main(splash)
    local user_agent = "Mozilla/5.0 (X11; CrOS x86_64 8172.45.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.64 Safari/537.36"
    splash:set_user_agent(user_agent)
    assert(splash:go(splash.args.url))
    useproxy(splash)
    return splash:html()
end
```

When the order of function in the main is EXACTLY like that, the proxy is set correctly and my request works BUT both print in useproxy print the old proxy (NOT_WORKING_PROXY). 
Another weird behavior, if i remove the line that set the user agent, the proxy is set to the old one (NOT_WORKING_PROXY) and if i put useproxy before splash:go it's the same.

Just so you know, my code is working perfectly fine if i remove my code in process_response and i don't return a new request.

I think it is a bug related to lua but i'm not sure or maybe i'm stuck with a mistake, i don't know.
If you know a fix or if it's a mistake, let me know please.

**Comment by Gallaecio** [comment]
This seems concerning https://github.com/scrapy-plugins/scrapy-splash
