### ISSUE TITLE
I didn't find scrapy code Entrance after executing scrapy crawl 

### ISSUE THREAD

**Issue by zeguangzhang** [scrapy/scrapy#4523]
scrapy source code forked, but I didn't find scrapy code Entrance after executing scrapy crawl {spider_name} command ,scrapy code Entrance  where，waiting for you replay ,thanks.

**Comment by elacuesta** [comment]
Could you elaborate? What do you mean by "Entrance"?

**Comment by Gallaecio** [comment]
Are you looking for `scrapy/__main__.py`?

**Comment by zeguangzhang** [comment]
> Are you looking for `scrapy/__main__.py`?

yes,can you tell me? thanks

**Comment by Gallaecio** [comment]
Tell you what? Where it is? As in https://github.com/zeguangzhang/scrapy/blob/master/scrapy/__main__.py ?

**Comment by zeguangzhang** [comment]
ok，I find  The main entry point to Scrapy API is  scrapy.crawler.Crawler(spidercls, settings),thank you @Gallaecio @elacuesta
