### ISSUE TITLE
Getting full page text with proper formatting with scrapy.

### ISSUE THREAD

**Issue by somestupidpersonLA** [scrapy/scrapy#4526]
Now I have trouble getting text from the page (WordPress post) with formatting as it  can be get from the browser (ctrl+c) or selenium. Can you implement such function? Or at least post a docs about it.

By using xpath I am getting only text without line breaks, or text with too many line breaks.

**Comment by somestupidpersonLA** [comment]
This is a suggestion, not the issue.

**Comment by somestupidpersonLA** [comment]
For now I am using this:
html = '''
   <p dir="ltr"><span>Hilo, Hanakahi, i ka ua Kani-lehua</span><span><br class="kix-line-break"></span><span>Puna, paia `ala, i ka paia `ala i ka hala.</span><span><br></span><span>Ka`ū, i ka makani, i ka makani kuehu lepo</span><span><br class="kix-line-break"></span><span>Kona, i ke kai, i ke kai hāwanawana.</span><span></span><span>Wai-mea, i ka ua, i ka ua Kīpu`upu`u.</span><span><br class=""></span><span>Kohala, i ka makani, i ka makani `Āpa`apa`a.</span><span><br class="kix-line-break"></span><span>Hāmākua, i ka pali, i ka pali lele koa`e.</span><span><br class="kix-line-break"></span><span>Ha`ina ka puana, i ka ua Kani-lehua.</span></p>
'''

def capture_formatted_text(html):
    from selenium import webdriver
    driver = webdriver.Chrome()
    driver.execute_script("element = document.querySelector('body'); element.innerHTML = arguments[0];", html)
    text = driver.find_element_by_xpath("//body").text
    driver.quit()
    return text

**Comment by elacuesta** [comment]
Scrapy does not download any additional resources (style sheets, scripts, fonts, images, etc) and it doesn't execute any Javascript code either. You might find some helpful pointers in #4484.

**Comment by elacuesta** [comment]
Please, do not edit the issue title and/or contents beyond the point in which existing answers do not make sense. Closing the issue is enough to mark it as resolved.
