### ISSUE TITLE
Fail or warn if from_crawler() returns None

### ISSUE THREAD

**Issue by c3pmark** [scrapy/scrapy#4528]
## Summary

Generate a warning or error if from_crawler() for a middleware/extension/etc. returns None

## Motivation

I created a custom extension and connected signals in the from_crawler() classmethod, but neglected to return the new extension instance.  Scrapy still reported the extension under "Enabled extensions", but none of the signals worked, since the instance was immediately garbage collected and its signals were silently disconnected.

This was of course an error on my part, but it would have saved me a lot of debugging if I had gotten a warning that from_crawler() was returning None, or if the extension were removed from the "Enabled extensions" list.

Would it be appropriate for utils.misc.create_instance() to raise an error or generate a warning if it's about to return None?  Or should MiddlewareManager treat create_instance() returning None the same as create_instance() raising NotConfigured?

**Comment by elacuesta** [comment]
Sounds good to me. Personally, I'd say it's more reasonable to expect that `create_instance` should never return `None`, since it is most likely not an instance of whatever class we want an instance of (`create_instance(type(None), {}, None)` works, but I don't see any value in it).

**Comment by willbeaufoy** [comment]
I can take this issue.
