### ISSUE TITLE
Bind request to response only if not bound already

### ISSUE THREAD

**Issue by elacuesta** [scrapy/scrapy#4529]
## Summary
Currently requests are bound to responses in [the engine](https://github.com/scrapy/scrapy/blob/2.1.0/scrapy/core/engine.py#L247) and/or in [the scraper](https://github.com/scrapy/scrapy/blob/2.1.0/scrapy/core/scraper.py#L149).
I would like to start a conversation to figure out the implications of binding them only if the `response.request` attribute is not already set, i.e. something like this:

```diff
diff --git scrapy/core/engine.py scrapy/core/engine.py
index 77d71846..72f1628a 100644
--- scrapy/core/engine.py
+++ scrapy/core/engine.py
@@ -244,7 +244,8 @@ class ExecutionEngine:
                     % (type(response), response)
                 )
             if isinstance(response, Response):
-                response.request = request  # tie request to response received
+                if response.request is None:
+                    response.request = request
                 logkws = self.logformatter.crawled(request, response, spider)
                 if logkws is not None:
                     logger.log(*logformatter_adapter(logkws), extra={'spider': spider})


diff --git scrapy/core/scraper.py scrapy/core/scraper.py
index edbb4dd6..256935da 100644
--- scrapy/core/scraper.py
+++ scrapy/core/scraper.py
@@ -146,7 +146,8 @@ class Scraper:
                 self._log_download_errors, request_result, request, spider)
 
     def call_spider(self, result, request, spider):
-        result.request = request
+        if not hasattr(result, "request") or result.request is None:
+            result.request = request
         dfd = defer_result(result)
         callback = request.callback or spider.parse
         warn_on_generator_with_return_value(spider, callback)
```

## Motivation

Recently I've been working on a downloader middleware to transparently redirect requests to a service which takes an URL and returns its response body along with some other metadata. The `process_request` method replaces the URL, and the `process_response` decodes the response body and creates a new response, making it look like it came directly from the target website, not from the download service. At this point, I'd like to be able to restore the original request as well, but any request I return in the `Response.request` attribute gets overridden.

## Describe alternatives you've considered

ATM I don't see a way to modify this behaviour without altering the Scrapy core.

**Comment by dangra** [comment]
Binding at core/engine.py predates our public release (https://github.com/scrapy/scrapy/commit/83dcf8aff91d0178ffbf4978fb757fc7e6d5d08c)
![image](https://user-images.githubusercontent.com/37369/80804234-e90e5600-8b8a-11ea-93f0-9a206b37ffa3.png)

Binding at core/scraper.py came 4 years later (https://github.com/scrapy/scrapy/commit/0256a34f9788dd00f46efcef0047dd86c280cd6c#diff-efe9358e1656d355258b3d73c1a4d189R139)
![image](https://user-images.githubusercontent.com/37369/80804349-3be80d80-8b8b-11ea-9d0f-9c0cb0e70807.png)

Pablo's merge commit explain why we need scraper's bounding https://github.com/scrapy/scrapy/commit/1e1cc76fb74afa90d2f0be00e3a9db12f4f7e1e5

**Comment by kmike** [comment]
I'm not sure I understand the implicatiions of the change. But scrapy-splash had a similar challenge (if I understand the problem properly), and in the response it provides url + a few other attributes of both requests, via separate attributes. 

I recall implementing it was not nice, and there are caveats, but it was doable. Don't recall the details, but https://github.com/scrapy-plugins/scrapy-splash/blob/e40ca4f3b367ab463273bee1357d3edfe0601f0d/scrapy_splash/response.py#L22 can be a good starting point.

**Comment by elacuesta** [comment]
Right, I should have checked the blame :sweat_smile: 
Indeed, bad things happen if the request is not present, but I think the current behaviour is not intuitive. You will not get the object you want, and it might bite some other people like it bit me ([this example](https://github.com/scrapinghub/scrapy-autoextract/blob/v0.4/scrapy_autoextract/middlewares.py#L220) for instance, which only works because `request.meta` is modified in-place).
So far I am returning the original attributes in the `meta` dictionary, but this it not ideal IMHO. For instance, requests will appear with the modified URL in the logs, making it difficult to identify them (as they all point to the same URL). I made a custom logformatter as a workaround for this, but it'd be good if I could just be able to bind the actual request I want.

For the record, all tests pass with the above changes.
