### ISSUE TITLE
ImportError: No module named twisted.web

### ISSUE THREAD

**Issue by Strato-fortex** [scrapy/scrapy#4535]
sslstrip -i 8080

Traceback (most recent call last):
  File "/usr/local/bin/sslstrip", line 27, in <module>
    from twisted.web import http
ImportError: No module named twisted.web

what i have to do in this case?
Have i to install twisted-web?How?

**Comment by elacuesta** [comment]
Sorry, this doesn't seem related to Scrapy. Please feel free to reopen if you think it's necessary.
