### ISSUE TITLE
Review unicode references

### ISSUE THREAD

**Issue by Gallaecio** [scrapy/scrapy#4547]
The documentation still has some references to Python 2’s `unicode`. We need to review them, and update them as needed (usually changing them to `str` or “string”).

**Comment by divyabhushan** [comment]
Hi @Gallaecio, Can I work on this issue, please?

**Comment by Gallaecio** [comment]
All yours!

**Comment by divyabhushan** [comment]
@Gallaecio 
So to get started, I could find one python code file under docs - scrapy/docs/utils/linkfix.py with python 2's unicode style.
So I would use the function to convert it to a string type which I have already tested and verified in my environment. 
Is this the expected solution? Kindly verify.
Thanks.

**Comment by elacuesta** [comment]
@divyabhushan I _believe_ what @Gallaecio means is refactoring the docs themselves. For instance, take a look at the description for [`Request.body`](https://docs.scrapy.org/en/2.1/topics/request-response.html#scrapy.http.Request):

> body (`str` or `unicode`) – the request body. If a `unicode` is passed, then it’s encoded to `str` using the encoding passed (which defaults to "utf-8"). If `body` is not given, an empty string is stored. Regardless of the type of this argument, the final value stored will be a `str` (never `unicode` or `None`).

which should be something like the following, now that we only support Python 3:

> body (`bytes` or `str`) – the request body. If a `str` is passed, then it's encoded to `bytes` using the passed encoding (which defaults to "utf-8"). If `body` is not given, an empty `bytes` object is stored. Regardless of the type of this argument, the final stored value will be an instance of `bytes` (never `str` or `None`).

**Comment by Gallaecio** [comment]
`Request.body` is always `bytes`, but yes, that’s what I meant.

The changes needed on the `request-response.rst` file can be copied from [#4090](https://github.com/scrapy/scrapy/pull/4090/files#diff-37334d46f8fd4663fa288ccf25fd0e3f) (in case this pull request is merged first).

**Comment by elacuesta** [comment]
> `Request.body` is always `bytes`, but yes, that’s what I meant.

For the record, you can in fact instantiate a `Request` with a `str` body, which gets encoded:
```python
In [1]: from scrapy import Request

In [2]: r = Request("http://example.org", body="hello!")

In [3]: type(r.body)
Out[3]: bytes

In [4]: r.body
Out[4]: b'hello!'
```

**Comment by divyabhushan** [comment]
Thanks, @Gallaecio @elacuesta I make the necessary changes.
