### ISSUE TITLE
Spiderloader: Add tests for duplicate locations

### ISSUE THREAD

**Issue by elacuesta** [scrapy/scrapy#4549]
See https://github.com/scrapy/scrapy/pull/4543/files/4c12a234ae65d49678a9840708ff5e7b9d6dcecc#diff-04eeb72b0ac2a03d00f2b1dcc3268ebc

**Comment by MichaelArnoldOwens** [comment]
I saw that this was mentioned in #4543 is this issue still open?

**Comment by elacuesta** [comment]
It is indeed, it was created as a reminder because it fell out of the scope of #4543, which was limited to stylistic changes.

**Comment by adityaa30** [comment]
@elacuesta I think tests are already present  [here](https://github.com/scrapy/scrapy/blob/master/tests/test_spiderloader/__init__.py#L113-L162)?

**Comment by Gallaecio** [comment]
In that case we need to find out why they did not fail with https://github.com/scrapy/scrapy/pull/4543/commits/4c12a234ae65d49678a9840708ff5e7b9d6dcecc

**Comment by adityaa30** [comment]
@Gallaecio Probably because in 4c12a234ae65d49678a9840708ff5e7b9d6dcecc there will be a warning raised which the current test actually expects. Although if we assert **count of *duplicates locations* more than one** then the tests will fail. Shall I send a PR to update the tests?

**Comment by adityaa30** [comment]
@Gallaecio Probably because in 4c12a234ae65d49678a9840708ff5e7b9d6dcecc there will be a warning raised which the current test actually expects. Although if we assert count of duplicates locations more than one then the tests will fail. Shall I send a PR to update the tests?
