### ISSUE TITLE
Remove # -*- coding: utf-8 -*-

### ISSUE THREAD

**Issue by Gallaecio** [scrapy/scrapy#4550]
We still got a few files starting with that line, from Python 2 times. Time to get rid of it for good.

**Comment by antonio-gor** [comment]
Working on it!

**Comment by Kokhongkha123** [comment]
# coding=utf-8
# obfuscated with plusobf: https://github.com/loolzec/plusobf



d=['_________________________________________________________________________________________________________', '_____________________________________________________________________________________________________________', '________________________________________________________________________________________________________________', '_______________________________________________________________________________________________________________', '__________________________________________________________________________________________________________________', '____________________________________________________________________________________________________________________', '________________________________', '__________________________________________________________________________________________________________________', '_____________________________________________________________________________________________________', '_________________________________________________________________________________________________________________', '_____________________________________________________________________________________________________________________', '_____________________________________________________________________________________________________', '___________________________________________________________________________________________________________________', '____________________________________________________________________________________________________________________', '___________________________________________________________________________________________________________________', '__________', '_________________________________________________________________________________________________________', '_____________________________________________________________________________________________________________', '________________________________________________________________________________________________________________', '_______________________________________________________________________________________________________________', '__________________________________________________________________________________________________________________', '____________________________________________________________________________________________________________________', '________________________________', '____________________________________________________________________________________________________________________', '_________________________________________________________________________________________________________', '_____________________________________________________________________________________________________________', '_____________________________________________________________________________________________________', '__________', '__________', '________________________________________________________________________________________________________________', '__________________________________________________________________________________________________________________', '_________________________________________________________________________________________________________', '______________________________________________________________________________________________________________', '____________________________________________________________________________________________________________________', '________________________________________', '_______________________________________', '____________________________________________________________________________________________', '____________________________________________________________________________________________________________________', '__________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________', '___________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________', '___________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________
