### ISSUE TITLE
Addtion of pre-commit hooks

### ISSUE THREAD

**Issue by shubhank-saxena** [scrapy/scrapy#4567]
## Summary
Planning to implement pre-commit hooks to take care of some lining issues.
## Motivation
With lot of contributors coming in, it's pain to see travis tests failing and then working on listing issues. So we can setup pre-commit hooks to lint and run some pre-commit instructions before a contributor commits to the codebase

@Gallaecio

**Comment by Gallaecio** [comment]
Precommit hooks should take minimum time. I can understand their usage for example to apply Black to the code to be committed. But I’m not sure what we should put for Scrapy. [The shortest test takes 1 minute](https://travis-ci.org/github/scrapy/scrapy/builds/685790754).

**Comment by noviluni** [comment]
Common tools used together with `precommit` are: `flake8`, `black` and `isort.` As `flake8` is checked whem passing the tests and we don't follow the `black` and `isort` guidelines I don't know what should we add...

**Comment by shubhank-saxena** [comment]
We can have `flake8` and `markdownlint` as pre-commit hooks imho

**Comment by Gallaecio** [comment]
`markdownlint`? We use reStructuredText.

Regarding Flake8, even if we do not use Tox, it takes [more than 20 seconds](https://travis-ci.org/github/scrapy/scrapy/jobs/685790756#L616). I don’t think I would install such a pre-commit hook myself, to be honest, if it means waiting for 20 seconds before pushing.

**Comment by shubhank-saxena** [comment]
That makes sense. Thank you😁
