### ISSUE TITLE
Json.loads may raise an error in settings.getdict('FEED')

### ISSUE THREAD

**Issue by jacty** [scrapy/scrapy#4571]
https://github.com/scrapy/scrapy/blob/8d1269bcbc81fa0bb5a69068e07bdbcb0dba8889/scrapy/settings/__init__.py#L197

When setting's value is string, Json.loads may raise an JSONDecodeError error if my test has nothing wrong, I guess. I tried to use settings.getdict('BOT_NAME') and it raises the JSONDecodeError as I expressed.

**Comment by Gallaecio** [comment]
I’m not sure that’s an issue. It’s probably what the caller would want.

**Comment by jacty** [comment]
> I’m not sure that’s an issue. It’s probably what the caller would want.

it doesn't make sense according to the description. It says 'If it is a string it will be
        evaluated as a JSON dictionary.' But when isinstance(value, str) is true, json.loads raise an error.

**Comment by Gallaecio** [comment]
It raises an error if the string does not contain valid JSON. If the string is `'{"a": "b"}'`, it will work.

**Comment by jacty** [comment]
> It raises an error if the string does not contain valid JSON. If the string is `'{"a": "b"}'`, it will work.

uhm, I guess I see your point. But it feels slightly awkward for me here. cuz getdict('BOT_NAME') will never work, which means I shouldn't use getdict here, head for other ways to evaluate dictionary instead. Thanks.

**Comment by Gallaecio** [comment]
> which means I shouldn't use getdict here

Exactly, if you want to read a setting as a string you need to use `get` instead.

> perhaps we should change the description to 'If it is a VALID JSON string it will be evaluated as a JSON dictionary.'

Actually, the current text is more accurate. The setting value is evaluated as JSON if it is a string. If the string does not contain valid JSON, then that evaluation triggers an exception. But the evaluation still happens. (and even if it’s valid JSON, if it’s not a JSON object it will cause an exception after the evaluation upon conversion of the evaluated object into `dict`)

**Comment by jacty** [comment]
> > which means I shouldn't use getdict here
> 
> Exactly, if you want to read a setting as a string you need to use `get` instead.
> 
> > perhaps we should change the description to 'If it is a VALID JSON string it will be evaluated as a JSON dictionary.'
> 
> Actually, the current text is more accurate. The setting value is evaluated as JSON if it is a string. If the string does not contain valid JSON, then that evaluation triggers an exception. But the evaluation still happens. (and even if it’s valid JSON, if it’s not a JSON object it will cause an exception after the evaluation upon conversion of the evaluated object into `dict`)

Okay, I get your point, thank you.
