### ISSUE TITLE
Add 'item_classes' key to FEEDS

### ISSUE THREAD

**Issue by longkyle** [scrapy/scrapy#4575]
## Summary

Add 'item_classes' key to FEEDS that accepts a list of scrapy.Item class objects.

## Motivation

This functionality will allow us to filter different Item types to unique URIs

## Describe alternatives you've considered

Currently, there isn't any way to filter by Item type in the FEED(s) settings.

## Additional context

I've already written the patch, tests, and updated documentation, I just need to create a pull request but I wanted to log it first here.

**Comment by Gallaecio** [comment]
Implemented in https://github.com/scrapy/scrapy/pull/5178
