### ISSUE TITLE
Downloadable documentation is missing for versions 2.0 and 2.1 on readthedocs.org

### ISSUE THREAD

**Issue by IlnarSelimcan** [scrapy/scrapy#4578]
For some reason downloadable documentation on https://readthedocs.org/projects/scrapy/downloads/ is available only up to version 1.8.

That's a minor issue, but I think that I'm not the only one who prefers to read technical papers in the pdf format (to be able to take notes).

**Comment by nsirletti** [comment]
Looks like a .readthdocs.yml config was created for 2.0.0 but we didn't specify downloadable formats as specified in [readthedocs.org's doc](https://docs.readthedocs.io/en/stable/downloadable-documentation.html).

Shall I make a PR ? If so to which branch ?

**Comment by Gallaecio** [comment]
> Shall I make a PR ? If so to which branch ?

That would be great. Feel free to create it for `master`, we can later backport it.

**Comment by Gallaecio** [comment]
Backported to 2.0 and 2.1.

**Comment by IlnarSelimcan** [comment]
Thanks!
