### ISSUE TITLE
Scrapy 2.1. with Openssl 18 dont support RSA-MD5 cipher website

### ISSUE THREAD

**Issue by jgnan** [scrapy/scrapy#4582]
Dear scrapy community,

I'm new to scrapy, and trying to crawl information from this site:
https://www.365-china.cn/

I only need the index page.

As it is a stander SSL website with formal SSL cert( which is identified by the chrome browser), I find it impossible to be crawl using scrapy(also python request), but is possible to grep content from curl, comment:
curl --location --request GET 'https://www.365-china.cn/'

As I'm a beginner to python3 and learn so many article from internet, I am still very confused and could not figure out what this problem is.

Methods I'd tried:
- https://github.com/scrapy/scrapy/issues/2916, try every option but not work. I realise what I want is to using http way to get https content, but I don't know how.
- Write a customer context factory, but how? I even get fail by using requests...

I don't know it should be an issue or a problem, but as an user I found it very difficult to me to solve this problem, please give me some instructions to solving this problem, thanks a lot.

My Environment:
```
Scrapy       : 2.1.0
Twisted      : 19.10.0
Python       : 3.7.5
pyOpenSSL    : 19.1.0
cryptography : 2.8
Platform: Mac OS 10.15.4
```

**Comment by jgnan** [comment]
Also paste my settings and issue:
settings.py
`# -*- coding: utf-8 -*-

# Scrapy settings for highlight project
#
# For simplicity, this file contains only settings considered important or
# commonly used. You can find more settings consulting the documentation:
#
#     https://docs.scrapy.org/en/latest/topics/settings.html
#     https://docs.scrapy.org/en/latest/topics/downloader-middleware.html
#     https://docs.scrapy.org/en/latest/topics/spider-middleware.html

BOT_NAME = 'highlight'

SPIDER_MODULES = ['highlight.spiders']
NEWSPIDER_MODULE = 'highlight.spiders'

# Obey robots.txt rules
ROBOTSTXT_OBEY = False
`
test command:
scrapy shell 'https://www.365-china.cn/'

result:
`
2020-05-18 16:39:35 [scrapy.utils.log] INFO: Scrapy 2.1.0 started (bot: highlight)
2020-05-18 16:39:35 [scrapy.utils.log] INFO: Versions: lxml 4.4.1.0, libxml2 2.9.9, cssselect 1.1.0, parsel 1.5.2, w3lib 1.21.0, Twisted 19.10.0, Python 3.7.5 (default, Dec 13 2019, 23:32:04) - [Clang 11.0.0 (clang-1100.0.33.12)], pyOpenSSL 19.1.0 (OpenSSL 1.1.1d  10 Sep 2019), cryptography 2.8, Platform Darwin-19.4.0-x86_64-i386-64bit
2020-05-18 16:39:35 [scrapy.utils.log] DEBUG: Using reactor: twisted.internet.selectreactor.SelectReactor
2020-05-18 16:39:35 [scrapy.crawler] INFO: Overridden settings:
{'BOT_NAME': 'highlight',
 'DUPEFILTER_CLASS': 'scrapy.dupefilters.BaseDupeFilter',
 'LOGSTATS_INTERVAL': 0,
 'NEWSPIDER_MODULE': 'highlight.spiders',
 'SPIDER_MODULES': ['highlight.spiders']}
2020-05-18 16:39:35 [scrapy.extensions.telnet] INFO: Telnet Password: 36c1ec67e6af98fc
2020-05-18 16:39:35 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage']
2020-05-18 16:39:35 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2020-05-18 16:39:35 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2020-05-18 16:39:35 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2020-05-18 16:39:35 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
2020-05-18 16:39:35 [scrapy.core.engine] INFO: Spider opened
2020-05-18 16:39:35 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://www.365-china.cn/> (failed 1 times): [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion: Connection lost.>]
2020-05-18 16:39:35 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://www.365-china.cn/> (failed 2 times): [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion: Connection lost.>]
2020-05-18 16:39:35 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET https://www.365-china.cn/> (failed 3 times): [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion: Connection lost.>]
Traceback (most recent call last):
  File "/usr/local/bin/scrapy", line 8, in <module>
    sys.exit(execute())
  File "/usr/local/lib/python3.7/site-packages/scrapy/cmdline.py", line 143, in execute
    _run_print_help(parser, _run_command, cmd, args, opts)
  File "/usr/local/lib/python3.7/site-packages/scrapy/cmdline.py", line 98, in _run_print_help
    func(*a, **kw)
  File "/usr/local/lib/python3.7/site-packages/scrapy/cmdline.py", line 151, in _run_command
    cmd.run(args, opts)
  File "/usr/local/lib/python3.7/site-packages/scrapy/commands/shell.py", line 74, in run
    shell.start(url=url, redirect=not opts.no_redirect)
  File "/usr/local/lib/python3.7/site-packages/scrapy/shell.py", line 45, in start
    self.fetch(url, spider, redirect=redirect)
  File "/usr/local/lib/python3.7/site-packages/scrapy/shell.py", line 113, in fetch
    reactor, self._schedule, request, spider)
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/threads.py", line 122, in blockingCallFromThread
    result.raiseException()
  File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 488, in raiseException
    raise self.value.with_traceback(self.tb)
twisted.web._newclient.ResponseNeverReceived: [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion: Connection lost.>]
`
With PDB:
scrapy fetch --pdb "https://www.365-china.cn/"

Stopped at:
`
2020-05-18 16:40:07 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
Jumping into debugger for post-mortem of exception '(-1, 'Unexpected EOF')':
> /usr/local/lib/python3.7/site-packages/OpenSSL/SSL.py(1664)_raise_ssl_error()
-> raise SysCallError(-1, "Unexpected EOF")
`

**Comment by jgnan** [comment]
For website's SSL information:
run:
```
openssl s_client -showcerts -connect 365-china.cn:443
```
Results:
```
CONNECTED(00000003)
depth=2 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Global Root CA
verify return:1
depth=1 C = CN, O = "TrustAsia Technologies, Inc.", OU = Domain Validated SSL, CN = TrustAsia TLS RSA CA
verify return:1
depth=0 CN = 365-china.cn
verify return:1
---
Certificate chain
 0 s:/CN=365-china.cn
   i:/C=CN/O=TrustAsia Technologies, Inc./OU=Domain Validated SSL/CN=TrustAsia TLS RSA CA
-----BEGIN CERTIFICATE-----
MIIFqTCCBJGgAwIBAgIQATjGFlTu8LCWgmATlY3BfjANBgkqhkiG9w0BAQsFADBy
MQswCQYDVQQGEwJDTjElMCMGA1UEChMcVHJ1c3RBc2lhIFRlY2hub2xvZ2llcywg
SW5jLjEdMBsGA1UECxMURG9tYWluIFZhbGlkYXRlZCBTU0wxHTAbBgNVBAMTFFRy
dXN0QXNpYSBUTFMgUlNBIENBMB4XDTE5MTAxMDAwMDAwMFoXDTIwMTAwOTEyMDAw
MFowFzEVMBMGA1UEAxMMMzY1LWNoaW5hLmNuMIIBIjANBgkqhkiG9w0BAQEFAAOC
AQ8AMIIBCgKCAQEAp2GmgyK1AQpqfnZJ6PreVNxT4l3u7UQNHYbv+88YD5HpDHkU
oH8FObrtfkjVwylXjQme0QCL+sH/iU6nKBrKUjqe3kRjpMOLvdMOl3XQpsKntqAS
9lwpqqlVG3NrR0kPoKZZpjfsyLfl9HQ4NfkyKSj1xLXw44IH0G1vtgEb8ax0TiF7
hWnlDrNq1ABBs1Y0b6ZrTvvdI3E5U9bnaV+sJpGXrudKZmXi7hcyphPv20Jv3Szr
dMSXoQmR8Eme29cOy/8RUBJeM7821eFpsVTQ3ZTybLAnyWo4cWkbMxIa/8Rlj/S+
Bu/VmQSMPe6EhX5TMxSUxJOtG2vFnzi5Fda0XQIDAQABo4IClDCCApAwHwYDVR0j
BBgwFoAUf9OZ86BHDjEAVlYijrfMnt3KAYowHQYDVR0OBBYEFPQzbgAWgap+pX5E
v2+3k34zAGhoMCkGA1UdEQQiMCCCDDM2NS1jaGluYS5jboIQd3d3LjM2NS1jaGlu
YS5jbjAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUF
BwMCMEwGA1UdIARFMEMwNwYJYIZIAYb9bAECMCowKAYIKwYBBQUHAgEWHGh0dHBz
Oi8vd3d3LmRpZ2ljZXJ0LmNvbS9DUFMwCAYGZ4EMAQIBMIGSBggrBgEFBQcBAQSB
hTCBgjA0BggrBgEFBQcwAYYoaHR0cDovL3N0YXR1c2UuZGlnaXRhbGNlcnR2YWxp
ZGF0aW9uLmNvbTBKBggrBgEFBQcwAoY+aHR0cDovL2NhY2VydHMuZGlnaXRhbGNl
cnR2YWxpZGF0aW9uLmNvbS9UcnVzdEFzaWFUTFNSU0FDQS5jcnQwCQYDVR0TBAIw
ADCCAQQGCisGAQQB1nkCBAIEgfUEgfIA8AB2AKS5CZC0GFgUh7sTosxncAo8NZgE
+RvfuON3zQ7IDdwQAAABbbUG0hoAAAQDAEcwRQIhAINDfUr54d1KnJk9QEaVLtuA
M/Y3QJO733FpyObqMNw+AiBQBVxaidhoDNCuQPULJOhpaROgMu3B39uyGT2y/ghl
zAB2AId1v+dZfPiMQ5lfvfNu/1aNR1Y2/0q1YMG06v9eoIMPAAABbbUG0oUAAAQD
AEcwRQIgUbfhgvzpqEbjB9iJjF8udn5/Dx6N/NE69Xu3YW5U2ywCIQCqtnsnbja6
m14UzDsAXXmLpBRzw9FEFTNZhGX2iKuIVjANBgkqhkiG9w0BAQsFAAOCAQEAEsM0
AlmKhoPk2DYg30K+ZXDKOui4pWQ1rYjP+nRLdYG/LDhgadaBHym7EX5D7P3l0IU3
zX7nrKmoqXevgtKD+FI4HB0FCTzE2csVHTar6xbOVE7A9V8bE4BJE0MJGkCMf4Id
03kIFSema4bnviZeZkFazpPbOkNF7YpJ9T7z8S3aSr3rkUuoYk9Nzofcx6vxG+kV
ghkZI2W36+ZLYzET+ahi7crTdx5Qu4qlOwPN8fC8bkpQxox5rCumPpGjSOGhEKWQ
C2ADM09941Td6qQUkAO2aWmlwrfiCmK75S8irB9mGtVSFesKiFptqzzOwbfKkTj5
7/5pElBnk/Dkr33RXA==
-----END CERTIFICATE-----
 1 s:/C=CN/O=TrustAsia Technologies, Inc./OU=Domain Validated SSL/CN=TrustAsia TLS RSA CA
   i:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Global Root CA
-----BEGIN CERTIFICATE-----
MIIErjCCA5agAwIBAgIQBYAmfwbylVM0jhwYWl7uLjANBgkqhkiG9w0BAQsFADBh
MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
d3cuZGlnaWNlcnQuY29tMSAwHgYDVQQDExdEaWdpQ2VydCBHbG9iYWwgUm9vdCBD
QTAeFw0xNzEyMDgxMjI4MjZaFw0yNzEyMDgxMjI4MjZaMHIxCzAJBgNVBAYTAkNO
MSUwIwYDVQQKExxUcnVzdEFzaWEgVGVjaG5vbG9naWVzLCBJbmMuMR0wGwYDVQQL
ExREb21haW4gVmFsaWRhdGVkIFNTTDEdMBsGA1UEAxMUVHJ1c3RBc2lhIFRMUyBS
U0EgQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCgWa9X+ph+wAm8
Yh1Fk1MjKbQ5QwBOOKVaZR/OfCh+F6f93u7vZHGcUU/lvVGgUQnbzJhR1UV2epJa
e+m7cxnXIKdD0/VS9btAgwJszGFvwoqXeaCqFoP71wPmXjjUwLT70+qvX4hdyYfO
JcjeTz5QKtg8zQwxaK9x4JT9CoOmoVdVhEBAiD3DwR5fFgOHDwwGxdJWVBvktnoA
zjdTLXDdbSVC5jZ0u8oq9BiTDv7jAlsB5F8aZgvSZDOQeFrwaOTbKWSEInEhnchK
ZTD1dz6aBlk1xGEI5PZWAnVAba/ofH33ktymaTDsE6xRDnW97pDkimCRak6CEbfe
3dXw6OV5AgMBAAGjggFPMIIBSzAdBgNVHQ4EFgQUf9OZ86BHDjEAVlYijrfMnt3K
AYowHwYDVR0jBBgwFoAUA95QNVbRTLtm8KPiGxvDl7I90VUwDgYDVR0PAQH/BAQD
AgGGMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjASBgNVHRMBAf8ECDAG
AQH/AgEAMDQGCCsGAQUFBwEBBCgwJjAkBggrBgEFBQcwAYYYaHR0cDovL29jc3Au
ZGlnaWNlcnQuY29tMEIGA1UdHwQ7MDkwN6A1oDOGMWh0dHA6Ly9jcmwzLmRpZ2lj
ZXJ0LmNvbS9EaWdpQ2VydEdsb2JhbFJvb3RDQS5jcmwwTAYDVR0gBEUwQzA3Bglg
hkgBhv1sAQIwKjAoBggrBgEFBQcCARYcaHR0cHM6Ly93d3cuZGlnaWNlcnQuY29t
L0NQUzAIBgZngQwBAgEwDQYJKoZIhvcNAQELBQADggEBAK3dVOj5dlv4MzK2i233
lDYvyJ3slFY2X2HKTYGte8nbK6i5/fsDImMYihAkp6VaNY/en8WZ5qcrQPVLuJrJ
DSXT04NnMeZOQDUoj/NHAmdfCBB/h1bZ5OGK6Sf1h5Yx/5wR4f3TUoPgGlnU7EuP
ISLNdMRiDrXntcImDAiRvkh5GJuH4YCVE6XEntqaNIgGkRwxKSgnU3Id3iuFbW9F
UQ9Qqtb1GX91AJ7i4153TikGgYCdwYkBURD8gSVe8OAco6IfZOYt/TEwii1Ivi1C
qnuUlWpsF1LdQNIdfbW3TSe0BhQa7ifbVIfvPWHYOu3rkg1ZeMo6XRU9B4n5VyJY
RmE=
-----END CERTIFICATE-----
---
Server certificate
subject=/CN=365-china.cn
issuer=/C=CN/O=TrustAsia Technologies, Inc./OU=Domain Validated SSL/CN=TrustAsia TLS RSA CA
---
No client certificate CA names sent
---
SSL handshake has read 2801 bytes and written 506 bytes
---
New, TLSv1/SSLv3, Cipher is RC4-MD5
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1
    Cipher    : RC4-MD5
    Session-ID: 8A01000056ED3E1C7B8898642E57D5A9A1C2A255B8872770E347C2752F984763
    Session-ID-ctx:
    Master-Key: 427D4477799096FDF89241081B725A5F2450661F75E86497F7E9B7790E8A4C0FA8CEC6C330AFF2A680359213BE127841
    Start Time: 1589791721
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
```

**Comment by jgnan** [comment]
I think it have something to do with this issue:
[https://github.com/scrapy/scrapy/issues/2311](url)

In which said:

> @redapple i'm having a similar problem on the latest scrapy trying to scrape
>
>https://www1.apply2jobs.com/jupitermed/ProfExt/index.cfm?>fuseaction=mExternal.returnToResults
>
>no matter what i get an error 'connection closed in non-clean fashion'
>
>thanks to some comments over on my stackoverflow question we found that openssl 1.1.0 doesnt >support rc4-md5 out of the box which is what the site uses.
>
>what can i do about this besides downgrading? possible to have this one spider use an older >version with some config? or some better solution?

And I'd tried to downgrade cryptography to version < 2 but forbidden by scrapy 2.1:
```
ERROR: scrapy 2.1.0 has requirement cryptography>=2.0, but you'll have cryptography 1.9 which is incompatible.
ERROR: pyopenssl 19.1.0 has requirement cryptography>=2.8, but you'll have cryptography 1.9 which is incompatible.
```

**Comment by Gallaecio** [comment]
Try with an older version of Scrapy that does allow it.

**Comment by jgnan** [comment]
> Try with an older version of Scrapy that does allow it.

Thanks for your reply, after more studying I think this could be the only solution as it is not a problem to scrapy but to openssl.

**Comment by Gallaecio** [comment]
Did openssl 1.1.0 remove the support? Because I’m thinking that it may simply have removed it from the default list, and you may be able to enable it somehow. I don’t know how, though. I’ve found https://stackoverflow.com/a/60981487/939364 but it might not help.

**Comment by jgnan** [comment]
emm, Sorry for very late response, after many times struggle I'm finally design to change another solution then using it with django + mongoid, as they have conflict with each other due to this openssl version issue.
