### ISSUE TITLE
Remove unneeded escape sequences from documentation API signatures

### ISSUE THREAD

**Issue by Gallaecio** [scrapy/scrapy#4592]
I’ve seen a few cases in the documentation like these:

```rst
.. method:: crawl(\*args, \**kwargs)
.. class:: Contract(method, \*args)
.. method:: from_crawler(crawler, \*args, \**kwargs)
```

The `\` preceding the `*` does not seem necessary, and is reaching the rendered documentation.

Noticed while working on #4161.

**Comment by karsten-aichholz** [comment]
I'd love to give this a shot. Is it still available?

**Comment by Gallaecio** [comment]
@karsten-aichholz: Sorry, @sharmarohit beat you to it.
