### ISSUE TITLE
param 'CONCURRENT_REQUESTS ' no function when adding proxy in middlewares.py

### ISSUE THREAD

**Issue by zeguangzhang** [scrapy/scrapy#4594]
# Description
use middlewares for using proxy to download,   but I find it cann't  be concurrent so that make param 'CONCURRENT_REQUESTS = 8'  no function, I test speed between 'CONCURRENT_REQUESTS = 8' and 
CONCURRENT_REQUESTS = 1, their speed is about equal.

### Steps to Reproduce

1. update settings.py :
CONCURRENT_REQUESTS = 16
DOWNLOADER_MIDDLEWARES = {
    'scrapy.downloadermiddleware.useragent.UserAgentMiddleware': None,
    'spiderask.middlewares.BaikeSpiderUserAgentMiddleware': 533,
    'spiderask.middlewares.SpideraskDownloaderMiddleware': 543,
}

2. update middlewares.py: (note : only update process_request)
```
class SpideraskDownloaderMiddleware(object):
    logger = logging.getLogger(__name__)

    @classmethod
    def from_crawler(cls, crawler):
        # This method is used by Scrapy to create your spiders.
        s = cls()
        crawler.signals.connect(s.spider_opened, signal=signals.spider_opened)
        return s

    def process_request(self, request, spider):
        r = requests.get('http://139.176.2.90:5558/random')
        proxy = r.text
        self.logger.info('获取代理：%s', proxy)
        request.meta['proxy'] = 'http://' + proxy

    def process_response(self, request, response, spider):
        return response

    def process_exception(self, request, exception, spider):
        pass

    def spider_opened(self, spider):
        spider.logger.info('Spider opened: %s' % spider.name)
```

3. in spider 👍 parse define as follow:

    def parse(self, response):
        logger.info('response url=%s', response.url)

        # anchors = response.css('a::attr(href)')
        anchors = response.css('a[href*=answer]::attr(href)')
        for a in anchors:
            yield response.follow(a, callback=self.parse, dont_filter=False)

        try:
            # in order to debug this problem, I already stop to use pipeline,so now code is as follow:
            item_page = {}
            item_page['url'] = response.url
            item_page['source'] = response.text
            redis_cli.rpush('ask_queue_page_source', json.dumps(item_page))
        except:
            logger.error("parse error url =%s, excepiton=", response.url, exc_info=True)

**Expected behavior:**  param 'CONCURRENT_REQUESTS = 8'  function

**Actual behavior:**  param 'CONCURRENT_REQUESTS = 8'  no function

**Reproduces how often:** always

### Versions
(env_apider) zzg@C02CC49KMD6R Documents % scrapy version --verbose
Scrapy       : 2.1.0
lxml         : 4.3.3.0
libxml2      : 2.9.9
cssselect    : 1.0.3
parsel       : 1.5.1
w3lib        : 1.20.0
Twisted      : 19.2.0
Python       : 3.7.5 (v3.7.5:5c02a39a0b, Oct 14 2019, 18:49:57) - [Clang 6.0 (clang-600.0.57)]
pyOpenSSL    : 19.0.0 (OpenSSL 1.1.1b  26 Feb 2019)
cryptography : 2.6.1
Platform     : Darwin-19.3.0-x86_64-i386-64bit

### Additional context
thanks

**Comment by wRAR** [comment]
"Speed is about equal" doesn't mean the parameter doesn't work. Speed depends on many other things. Also, you are using `requests` which is a synchronous library, so problems with concurrency are expected.
