### ISSUE TITLE
eb_kwargs for errback

### ISSUE THREAD

**Issue by Shleif91** [scrapy/scrapy#4598]
Since version 2.0 `cb_kwargs` has appeared which I use to transfer data to callback. 

Now need to handle errors in errback. How to forward data there (logically there should be `eb_kwargs`, but there is none)?

**Comment by elacuesta** [comment]
The original PR (#3563) briefly mentions this. We decided there was no need, since the original request is available in the errback's failure, so the callback arguments can be accessed through `failure.request.cb_kwargs`

**Comment by Shleif91** [comment]
Thanks for the answer. Did as you showed. Perhaps you need to mention this in the documentation?

**Comment by Gallaecio** [comment]
I guess it makes sense to be more specific about this in https://docs.scrapy.org/en/latest/topics/request-response.html#scrapy.http.Request.cb_kwargs

**Comment by dsandeep0138** [comment]
@Gallaecio I have updated the docs. Can you please review the pull request and provide feedback? Thanks.
