### ISSUE TITLE
Make FeedExporter customizable for export conditions

### ISSUE THREAD

**Issue by StasDeep** [scrapy/scrapy#4607]
## Summary

The new FeedExporter class (or rather `FEEDS` setting) doesn't allow to create custom conditions on whether to export an item or not.

## Motivation

Like in case with #4575, I need to customize the condition under which an item should/shouldn't be exported. It would be nice to be able to do it like this or something in a similar fashion:

```python
FEEDS = {
    uri: {'format': 'jsonlines', 'slot_kwargs': {'param': }}
}

class CustomFeedExporter(FeedExporter):

    def item_scraped(self, item, spider):
        for slot in self.slots:
            if item.param == slot.param:
                slot.start_exporting()
                slot.exporter.export_item(item)
                slot.itemcount += 1
```

## Describe alternatives you've considered

I have to create a new FeedExporter class and override `open_spider` method to set custom attributes to a slot and then use it in `item_scraped` the way I've shown above.

**Comment by wRAR** [comment]
Do you mean it was possible with the old code?

**Comment by StasDeep** [comment]
@wRAR no, I did not mean that.

**Comment by asifmallik** [comment]
@StasDeep are you working on this or is this issue up for grab?

**Comment by StasDeep** [comment]
@asifmallik I did not start working on it yet, so feel free to take it :)

**Comment by asifmallik** [comment]
@StasDeep I will give this a try in that case :)

**Comment by Gallaecio** [comment]
@asifmallik I would wait for https://github.com/scrapy/scrapy/pull/4576 to be merged.

**Comment by ejulio** [comment]
If the idea is to simply not export an item, why don't you `raise DropItem()` in a pipeline?

**Comment by Gallaecio** [comment]
A pipeline works if you want to do this for all entries in `FEEDS`. But this enhancement would allow to filter differently for different `FEEDS` entries, which would be nice.

**Comment by woho** [comment]
I think this issue can be marked as done because an item filtering feature has been implemented here in the meantime: https://github.com/scrapy/scrapy/commit/4ddc9d6b55fa708becfd70812ea44eb0c6837638 This feature will help us a lot.
