### ISSUE TITLE
iter() a generator in start_requests

### ISSUE THREAD

**Issue by jacty** [scrapy/scrapy#4608]
https://github.com/scrapy/scrapy/blob/c86a1035dd9b8b10acaf8f9e8bdb1b5494a287e2/scrapy/crawler.py#L88

self.spider.start_requests() will return a generator for sure, however, I am not sure why we need to use iter() to wrap it again. Should we remove iter() in this case?

**Comment by wRAR** [comment]
It won't always return a generator. You can return any iterable from it.

Not sure why is this an issue anyway, do you have any problems with this line?

**Comment by jacty** [comment]
> It won't always return a generator. You can return any iterable from it.
> 
> Not sure why is this an issue anyway, do you have any problems with this line?

nope. I am just trying to make it simple.  From what I understand, self.spider.start_requests() will definitely return a generator, so I was thinking make this part clear and short. Not sure if I misunderstood something or not.

**Comment by jacty** [comment]
> It won't always return a generator. You can return any iterable from it.
> 
> Not sure why is this an issue anyway, do you have any problems with this line?

Not an issue actually, I am trying to make code here simple and clear from kind of OCD habit. As I know, start_requests will yield a Request. If I don't make it wrong, it is the only output
