### ISSUE TITLE
When i use proxy,all requests using the first HTTP connect tunnel, not each request established a connect 

### ISSUE THREAD

**Issue by kuaidaili-dev** [scrapy/scrapy#4611]
### Description

[Description of the issue]
I use wireshark ,this is the data package 
![image](https://user-images.githubusercontent.com/32975725/83594785-b5ac5600-a592-11ea-844a-712d0baddb20.png)
I submit 10 requests but just establish one connect connection,the left requests go through the fist connect tunnel,i do not know why.

**Comment by wRAR** [comment]
It's not clear from the attached screenshot what actually happens, but does this cause any problems for you?

**Comment by kuaidaili-dev** [comment]
I built a server that can receive my request and choose a proxy IP to visit, and respond to me. But the above scenario did not work. scrapy took all the request packets for the first connect connection established, so each of my requests is accessed by the same proxy IP. If scrapy is to create one for each request connect link, then there will be no such problems. My English is not good, please understand

**Comment by Gallaecio** [comment]
Any chance you can share a [minimal example](https://stackoverflow.com/help/minimal-reproducible-example) to reproduce the issue? I’m specially interested in knowing how you are configuring the proxies in your project or spider.
