### ISSUE TITLE
Trying to install scrapy on a pi 4. get 404 error

### ISSUE THREAD

**Issue by Tricoms** [scrapy/scrapy#4638]
pip install scrappy
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting scrappy
  Using cached https://files.pythonhosted.org/packages/b4/df/dcd763f44aea90fbd58b4e7f7c8be95ade7d130cd21251fc0d93c295b1f0/Scrappy-0.3.0.alpha.4.tar.gz
Requirement already satisfied: chardet in /usr/lib/python2.7/dist-packages (from scrappy) (3.0.4)
Collecting guessit (from scrappy)
  Using cached https://files.pythonhosted.org/packages/09/a1/c37ccc25872d463f94dbde723430c7129dc6d7f790c5b0030a5690e2f58a/guessit-3.1.1.tar.gz
Collecting hachoir-core (from scrappy)
Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/hachoir-core/

It's true the site  https://pypi.org/simple/hachoir-core/ is not there.

Any help?

**Comment by wRAR** [comment]
The homepage for `Scrappy` is at https://github.com/louist87/scrappy.
