### ISSUE TITLE
Print weird None after every successfully crawled

### ISSUE THREAD

**Issue by jzwz** [scrapy/scrapy#4639]
### Description

[Description of the issue]

### Steps to Reproduce
**Expected behavior:** [What you expect to happen]
Why print "None" after scraped successfully? Is that normal?

**Actual behavior:** [What actually happens]
Scrapy prints "None" after scraped successfully every request.

2020-06-22 12:51:05 [scrapy.core.scraper] DEBUG: Scraped from <200 https://url/>
None

**Reproduces how often:** [What percentage of the time does it reproduce?]
Every time

### Versions
Scrapy       : 2.1.0
lxml         : 4.5.1.0
libxml2      : 2.9.5
cssselect    : 1.1.0
parsel       : 1.6.0
w3lib        : 1.22.0
Twisted      : 20.3.0
Python       : 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)]
pyOpenSSL    : 19.1.0 (OpenSSL 1.1.1g  21 Apr 2020)
cryptography : 2.9.2
Platform     : Windows-10-10.0.18362-SP0

### Additional context
I debugged and invested scrapy code, in scrapy/core/scraper.py
Line 254:
logkws = self.logformatter.scraped(output, response, spider)
Here parameter "output" is None, meanwhile "item" in context is not None, is valid value. 

following the calling in scrapy/logformatter.py
Line 73: def scraped(self, item, response, spider)
"scraped" method should receive first parameter names "item"

My question is at line 254 in scraper.py, 
should be changed to below code.
logkws = self.logformatter.scraped(item, response, spider)
In this case, it won't print None after every successfully scraped. (I guess)

**Comment by wRAR** [comment]
If you think this is a bug in Scrapy, you need to provide code to reproduce it. Looks like you  produce None values from your callbacks in some way.

**Comment by jzwz** [comment]
I'm not sure this is a bug or not, but I just feel a little confused what is "None".
Would you please give me some idea?
What is the value of "output" sourcing from in not "None" case?
(logkws = self.logformatter.scraped(output, response, spider))

**Comment by wRAR** [comment]
The "Scraped from" message normally prints the item produced from a callback.

**Comment by Gallaecio** [comment]
@jzwz Please, provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). For all we know, you could have `print(None)` somewhere in your code :)

**Comment by jzwz** [comment]
@Gallaecio I know where's wrong, I didn't "return item" in process_item method in pipelines.py, because I store data in process_item and no further process.
I put "return item" at the end of process_item method, The "Scraped from" message prints the item info normally. 😄
