### ISSUE TITLE
Allow run pyw scripts

### ISSUE THREAD

**Issue by aerdnar** [scrapy/scrapy#4643]
scrapy/commands/runspider.py check for Python script source but it fails to allow .pyw files.
Check at row 14 is:
`    if fext != '.py':`
but it should be:
`    if fext != '.py' and fext != '.pyw':`

**Comment by Gallaecio** [comment]
I wonder if this may be a problem as well for other parts of the code base.

**Comment by AKSHAYSHARMAJS** [comment]
I can work on it. Should I check whole codebase for this bug?

**Comment by Gallaecio** [comment]
It would be great to have a look in other parts that handle similar scenarios, maybe just look for references to `.py` in the code. Just in case.

**Comment by AKSHAYSHARMAJS** [comment]
Okay I 'll look for it. Thanks :)
