### ISSUE TITLE
Have tests generate a certificate on-the-fly

### ISSUE THREAD

**Issue by Gallaecio** [scrapy/scrapy#4651]
Unless we want to be doing https://github.com/scrapy/scrapy/pull/4650 every year, we should look into making tests generate a fresh certificate at run time.

**Comment by Urahara** [comment]
We could use [this](https://www.shellhacks.com/create-csr-openssl-without-prompt-non-interactive/) so we can generate without any prompt, where do you think we could put this? I would like to add this functionality.

**Comment by Gallaecio** [comment]
I wonder if we could implement it as a pytest fixture. Otherwise, having pytest create the file (overwriting) at the beginning of a test session should do the job; it may be even better, as it’s probably much simpler.

**Comment by wRAR** [comment]
I have a small concern that in some environments there will be not enough entropy for doing this quickly, but we'll need to actually check this.

**Comment by Urahara** [comment]
> I have a small concern that in some environments there will be not enough entropy for doing this quickly, but we'll need to actually check this.

I think i know what you mean, doin a litle more research i found this answer: https://stackoverflow.com/a/60804101/9291099, generating programmatically is more safe than using a command :) Can you take a look @Gallaecio

**Comment by Gallaecio** [comment]
I don’t think that kind of safety matters here, given the purpose of the certificate. I wouldn’t put too much effort in creating it using a Python library if it can be done easily with a command.

Mind, however, that the command would probably have to be executed from some Python code using POpen (I would check pytest documentation for possible places where to put such a call).
