### ISSUE TITLE
Documentation describing how to setup environment for scrapy contributions 

### ISSUE THREAD

**Issue by nb2838** [scrapy/scrapy#4655]
Hey! I recently started to contributing to scrapy and noticed that there isn't any documentation on how to set-up the environment to edit the code in your own machine (setting up a virtual environment, building, etc). I think this would make the process a little bit more user friendly for new contributors. I was wondering if you thought this was a good idea and perhaps I could edit the docs https://docs.scrapy.org/en/latest/contributing.html to add this piece of information.

**Comment by Gallaecio** [comment]
I think it makes sense. But I would keep the documentation changes as short as possible while being useful, and maximize references to official, external sources.

**Comment by elacuesta** [comment]
There's already #4452, is that similar to what you were thinking @nb2838?

**Comment by nb2838** [comment]
Yes! That is actually what I had in mind. Sorry for not seeing it before.

**Comment by Gallaecio** [comment]
https://github.com/scrapy/scrapy/pull/4452 is a pull request, and it may not even be merged, so I think there is still value in having a ticket. So thanks! :slightly_smiling_face:

**Comment by Gallaecio** [comment]
Oh, there is #4451, don’t mind me :facepalm:
