### ISSUE TITLE
Scrapy spider works on MacOS Catalina 10.15.4(scrapy2.1.0), does NOT work on Ubuntu 19.10 (scrapy 1.7.3)

### ISSUE THREAD

**Issue by wangjiahong666** [scrapy/scrapy#4656]
Hello, 

I have a scrapy spider which works well on MacOs Catalina 10.15.4(scrapy2.1.0), but the spider does not work on  Ubuntu 19.10 (scrapy 1.7.3). I feel it might be the version reason. 

Error log: 

`2020-07-05 17:30:59 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
2020-07-05 17:30:59 [scrapy.core.engine] ERROR: Error while obtaining start requests
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/scrapy/core/engine.py", line 127, in _next_request
    request = next(slot.start_requests)
  File "/home/jiahong/Crawler/instagram_crawler/scrapy/ins_crawl/ins_crawl/spiders/ins2.py", line 54, in start_requests
    user = self.shared_data['entry_data']['ProfilePage'][0]['graphql']['user']
KeyError: 'ProfilePage'
`

Could anyone help me with debug this? Or what direction should I go to debug this? 

Let me know if more info needed. 
Thanks

**Comment by Gallaecio** [comment]
As far as I can tell from the traceback, the error is specific to your spider. Please, provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) if you believe this is an error in Scrapy.

**Comment by wangjiahong666** [comment]
Hi, @Gallaecio 
Thank you for your reply. You are right, the error is specific to my spider. It has been solved now.
