### ISSUE TITLE
Use black python formatter

### ISSUE THREAD

**Issue by imsahil007** [scrapy/scrapy#4658]
Hello Everyone! I hope you are doing okay!
I was looking at the source code and I noticed that the code indentation is poor. So, I suggest using code formatted and create tests for same. I like how "black" works. Tell me what do you think about this?
I am just a beginner to open source. Healthy criticism will be appreciated!

**Comment by Gallaecio** [comment]
This is something we have discussed internally, and at the time the consensus was not to switch to Black. But we have been making style improvements to the code base for months.

Most of the code passes Flake8 checks (exceptions are configured in https://github.com/scrapy/scrapy/blob/master/pytest.ini), and we recently merged [Pylint checks](https://github.com/scrapy/scrapy/pull/3727), which we’ll review with time.

Could you indicate examples of format issues that you’ve found that are not covered by Flake8 or Pylint?

**Comment by wRAR** [comment]
I've just run `black -S -l 119 scrapy tests` on the master and pushed the result to https://github.com/wRAR/scrapy/commit/1eadb1875a4dca6b209d9c1362407e7fe787ebe6 so anyone curious can preview the changes.

**Comment by Gallaecio** [comment]
Looks like black does not undo string splits as I would expect: https://github.com/wRAR/scrapy/commit/1eadb1875a4dca6b209d9c1362407e7fe787ebe6#diff-bd207f7ef310a40189c53674dde833fdR141

**Comment by wRAR** [comment]
I've updated the branch: https://github.com/wRAR/scrapy/commit/f842fbeaa1af80edbdb85bf8437cb4519b2a35eb

Previous run: 245 files changed, 3903 insertions(+), 4063 deletions(-)

This run: 253 files changed, 4176 insertions(+), 4115 deletions(-)

**Comment by wRAR** [comment]
Compare: https://github.com/scrapy/cssselect/pull/122 has 4 times fewer changes, though most of that is in three very big files, it would be even easier to review if the changes were split between more files. So it should be possible to reformat the Scrapy repo in several batches if we decide to do that.

**Comment by wRAR** [comment]
OTOH 70% of that is, curiously, in the tests.

**Comment by Gallaecio** [comment]
> So it should be possible to reformat the Scrapy repo in several batches if we decide to do that.

A progressive approach works for me, just so that I don’t fall asleep during review. Shall we start with adding black but allow-listing all existing files?

**Comment by wRAR** [comment]
Yeah.

**Comment by avishmehta68710** [comment]
Can i work on this issue

**Comment by Gallaecio** [comment]
Actually, we had some further internal discussions. It may be best if we handle this internally, to minimize back-and-forth during code review.

**Comment by azzamsa** [comment]
I am very keen to see the project formatted with black. We can have very consistent styling by enforcing it through the CI.
