### ISSUE TITLE
Add docs for FEEDS.uri_params and FEED_URI_PARAMS

### ISSUE THREAD

**Issue by alex-ber** [scrapy/scrapy#4671]
In https://docs.scrapy.org/en/latest/topics/feed-exports.html#feeds 

There is missing entry 

`uri_params: falls back to FEED_URI_PARAMS`

Also FEED_URI_PARAMS setting description is missing (see https://github.com/scrapy/scrapy/issues/4670)

Here 

    format: the serialization format to be used for the feed. See Serialization formats for possible values. Mandatory, no fallback setting

    encoding: falls back to FEED_EXPORT_ENCODING

    fields: falls back to FEED_EXPORT_FIELDS

    indent: falls back to FEED_EXPORT_INDENT

    store_empty: falls back to FEED_STORE_EMPTY

**Comment by elacuesta** [comment]
Hi @alex-ber, thanks for the report. We were [aware of the problem](https://github.com/scrapy/scrapy/pull/3858#issuecomment-513486600) but were not actively tracking it, so thanks for opening this issue.
As I said in the linked comment, I think it might be good to revisit #3873 before tackling this, but it might not be necessary.
One thing I will do though is close #4670, we can keep track of both things here.
Thanks again.
