### ISSUE TITLE
Enable a middleware only for specific spider?

### ISSUE THREAD

**Issue by laggardkernel** [scrapy/scrapy#4678]
Sorry, settings are not correct in my spider.

----

## Summary

`DOWNLOADER_MIDDLEWARES` in spider's `custom_settings` doesn't take effect. Can a middleware be enabled only for specific middleware.

## Motivation
I tried to use `scrapy-selenium` to parse webpage with dynamically loaded content. I organized my project with different spiders for different sites, and only some of the spiders need to use the `scrapy-selenium`.

## Describe alternatives you've considered
AFAIK, the `scrapy-selenium` pacakge init the webdriver in classmethod `@from_crawler`, one way to avoid the webdriver initialized for every spider is to delay its initialization when spider is opened with the help of `signals.spider_opened`?

But when I deploy the spiders, multiple webdriver are enabled, right?

**Comment by wRAR** [comment]
> DOWNLOADER_MIDDLEWARES in spider's custom_settings doesn't take effect. 

It usually does.

If you think there is a bug in Scrapy, please describe how to reproduce it.

**Comment by Gallaecio** [comment]
If this issue only happens with the scrapy-selenium downloader middleware, consider closing this issue and instead opening an issue upstream at https://github.com/clemfromspace/scrapy-selenium
