### ISSUE TITLE
Should `scrapy.utils.python.WeakKeyCache` be deprecated?

### ISSUE THREAD

**Issue by noviluni** [scrapy/scrapy#4684]
## Summary
I can't find any reference to `scrapy.utils.python.WeakKeyCache` (except in tests) and I think that it should be deprecated.

## Motivation
Keeping non-used and non-documented code makes the codebase harder to maintain.

## Describe alternatives you've considered
As it's tested we could keep it, but I don't think it's a good idea.

**Comment by wRAR** [comment]
Looks like its (last) usage was removed in https://github.com/scrapy/scrapy/commit/332bf3b6b7bd238df5e8be601ee0686231a6776c

**Comment by kshitijcode** [comment]
I can clean this up. Do I assign this to myself?

**Comment by Gallaecio** [comment]
@kshitijcode No need to ask first, feel free to go ahead! :slightly_smiling_face:

**Comment by kshitijcode** [comment]
@Gallaecio @wRAR 
I have raised the PR with the necessary changes: https://github.com/scrapy/scrapy/pull/4701
But I am not sure what is failing the tests. Tests pass successfully locally after adding 
`-W ignore::pytest.PytestDeprecationWarning.` to tox.ini

**Comment by wRAR** [comment]
@kshitijcode the test failure is unrelated to your changes, I've created #4702 to track it
