### ISSUE TITLE
<twisted.python.failure.Failure twisted.web.http._DataLoss: Chunked decoder in 'CHUNK_LENGTH' state, still expecting more data to get to 'FINISHED' state.>]

### ISSUE THREAD

**Issue by sqyqyq** [scrapy/scrapy#4696]
Hi, 
   I am recently using scrapy. but when i am using proxy pool with it there is this kind of error, it is not happens in every request, just sometimes.

`    <twisted.python.failure.Failure twisted.web.http._DataLoss: Chunked decoder in 'CHUNK_LENGTH' state, still expecting more data to get to 'FINISHED' state.>]`

And looks like every time it happens 1150 times in my spider, the spider stops and freeze, even cannot quit by ctrl-c.

I want to know how to handle this kind of error, just don't let it get out of 'CHUNK' state, release it, don't let it freeze. The error not happens in every request, So right now, I try to catch exception and let the request retry, but just like i said, it freeze after happened certain times

It's not user-agent or host problem because when I run it without proxy I never see this kind of error. And I used the setting `DOWNLOAD_FAIL_ON_DATALOSS = True` but doesn't work.

**Comment by Gallaecio** [comment]
Please, use [StackOverflow](https://stackoverflow.com/tags/scrapy) to ask this type of questions. See [Getting Help](https://docs.scrapy.org/en/latest/#getting-help).
