### ISSUE TITLE
Requests timing out when setting larger number of CONCURRENT_REQUESTS

### ISSUE THREAD

**Issue by MartinBorcin** [scrapy/scrapy#4699]
Hello,
I wanted to build a scrapy spider for broad-crawling of the ".sk" domain, So I decided to start by downloading the front-page for every domain in a publicly available list of registered .sk domains. I set the spider up with custom_settings as recommended here (https://docs.scrapy.org/en/latest/topics/broad-crawls.html). However, whenever I increase the number of CONCURRENT_REQUESTS I start getting TimeoutErrors for all requests after cca 20 seconds of crawling (when CONCURRENT_REQUESTS=100). This is inconsistent in between individual crawls, sometimes this issue doesn't occur even after a minute. If I decrease the number of CONCURRENT_REQUESTS to 20, The issue persists, but instead of all request timing out after some time, only a couple of them do and then I receive a couple of responses and then a couple time out and so on... (The maximum number of CONCURRENT_REQUESTS that doesn't cause this error is about 10.) 
I've been trying to fix this for more than a week now with no luck. At first I thought there's a problem with the DNS, but now I'm using a custom one. In wireshark I also see that the DNS query leaves at the right time and the correct response is received as well. On the other hand, for every request that times out, new request is generated (since then there is space in the queue) and I can see the DNS query and response for that request in wireshark, but it is not followed by any HTTP GET request.

my spider:

```python
class FrontPageSpider(Spider):
    name = "frontpagespider"
    custom_settings = {
        "DOWNLOAD_DELAY": 3,
        "DOWNLOAD_TIMEOUT": 15,
        "COOKIES_ENABLED": False,
        "AJAXCRAWL_ENABLED": True,
        "USER_AGENT": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36",
        "ROBOTSTXT_OBEY": False,
        "CONCURRENT_REQUESTS": 100,
        "REACTOR_THREADPOOL_MAXSIZE": 20,
        "LOG_LEVEL": 'INFO',
        "CONCURRENT_REQUESTS_PER_DOMAIN": 1,
        "RETRY_ENABLED": False,
        "DEPTH_PRIORITY": 1,
        "SCHEDULER_PRIORITY_QUEUE": 'scrapy.pqueues.DownloaderAwarePriorityQueue',
        "SCHEDULER_DISK_QUEUE": 'scrapy.squeues.PickleFifoDiskQueue',
        "SCHEDULER_MEMORY_QUEUE": 'scrapy.squeues.FifoMemoryQueue',
        "REDIRECT_ENABLED": False
    }

    def start_requests(self):
        with open("http_crawlable.txt", "r") as f:
            for line in f:
                url = line.strip()
                self.logger.info(f"Now sending request to {url}...")
                yield Request(f"{url}", callback=self.parse)

    def parse(self, response):
        self.logger.info(f"A response from {response.url} just arrived")

if __name__ == "__main__":
    process = CrawlerProcess(get_project_settings())
    process.crawl("frontpagespider")
    process.start()
```
Note: For ease of debugging, I have decided to only crawl domains that don't use SSL/TLS for now. I am also including the file `http_crawlable.txt` below, which contains a list of urls for some .sk domains that use http. A vast majority of these should work and be responsive.

To reproduce the bug, you can either simply run the script above with the file `http_crawlable.txt` in the same directory or run the spider from shell. The issue persists either way. 

**Expected behavior:** Spider sends about 100 requests, then for every response received, it logs it and sends a new request for a url loaded from the file. (Occasional errors are fine, since some of the urls may actually be broken)

**Actual behavior:** Spider sends about 100 requests, everything seems to be going as expectd, but after about 20 seconds it stops, as if it was waiting for some response and then logs innumerable TimeoutErrors.

**Reproduces how often:** Almost 100% of time, occasionally it runs as expected, although I have absolutely no idea how or why. 

### Versions
```
Scrapy       : 2.2.0
lxml         : 4.5.2.0
libxml2      : 2.9.5
cssselect    : 1.1.0
parsel       : 1.6.0
w3lib        : 1.22.0
Twisted      : 20.3.0
Python       : 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:57:36) [MSC v.1900 64 bit (AMD64)]
pyOpenSSL    : 19.1.0 (OpenSSL 1.1.1g  21 Apr 2020)
cryptography : 2.9.2
Platform     : Windows-10-10.0.18362-SP0
```
[http_crawlable.txt](https://github.com/scrapy/scrapy/files/4982332/http_crawlable.txt)

**Comment by Gallaecio** [comment]
Please, use [StackOverflow](https://stackoverflow.com/tags/scrapy) to ask this type of questions. See [Getting Help](https://docs.scrapy.org/en/latest/#getting-help).

PS: It sounds like you may be overloading the target server.
