### ISSUE TITLE
Scrapy does not respect error status code 407

### ISSUE THREAD

**Issue by scrapenetwork** [scrapy/scrapy#4700]
Scrapy does not respect handling error code 407
If retry middleware is on, it will always retry this error code.
If retry middleware is off,it will close with connection failed 407 proxy auth error.

(Ive tried with most error codes and this is the only one unable to handle)

Ive doubled checked the proxies when this occurs and proxies working fine . Do not know why scrapy at times  gives off incorrect authentication error on the same proxy it successfully returned a response on the previous request lol nor why scrapy is unable to handle this status code. Thx for any help and suggestions.

**Comment by wRAR** [comment]
Sorry, what do you mean by handling?

**Comment by scrapenetwork** [comment]
> Sorry, what do you mean by handling?

What i mean is , enter a working username/password proxy and input the incorrect password.

Scrapy will return error 407

In settings allows http error code 407
Spider handle error code [407]
If response.status etc etc do something 

Scrapy does not respect this and will retry, close and fail with connection error 407 .


Should be able to respect the error status code the same  as say, 403

Example:

Settings allow http error 403
Spider handle error status 403
If response status etc etc do something...
Scrapy does something


Sorry i am on mobile atm.

**Comment by cpatrickalves** [comment]
Hi there, 

I am having the same issue. 
Scrapy gets 200 status codes for thousands of pages and eventually gets a 407 status code.

I've set these settings on my configuration, but it does not perform a new retry at all

```
GLOBAL_SPIDER_SETTINGS = {
    'USER_AGENT': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.131 Safari/537.36',
    'LOG_LEVEL': 'ERROR',
    "RETRY_ENABLED": True,
    "RETRY_TIMES": 3,
    "RETRY_HTTP_CODES": [500, 502, 503, 504, 407, 408],
    'HTTPCACHE_ENABLED': True,
    'HTTPCACHE_DIR': ".",
    'HTTPCACHE_EXPIRATION_SECS': 2592000, # 30 days
    "DOWNLOADER_MIDDLEWARES" : {"scrapy_crawlera.CrawleraMiddleware": 610},
        "CRAWLERA_ENABLED" : True if os.environ.get("PROXY_KEY", None) else False,
        "CRAWLERA_APIKEY" : os.environ.get("PROXY_KEY", None),
        "DEFAULT_REQUEST_HEADERS": {
            "X-Crawlera-Profile": "desktop"}
    }

```

Any thoughts?

**Comment by wRAR** [comment]
> Any thoughts?

If you think it's a bug in Scrapy, open a new bug report that includes a minimal reproducible example of the problem.

**Comment by cpatrickalves** [comment]
It's a random error. 
If I scrape 8000 pages, 2-5 pages will get 407 status code. But is not the same page, every time I ran I got different pages with 407 status code, and sometimes got no 407 on any page.

I'll try this: https://stackoverflow.com/questions/28640102/retrying-a-scrapy-request-even-when-receiving-a-200-status-code/28640118#28640118

But thanks anyway.

**Comment by wRAR** [comment]
Getting 407 is definitely not a Scrapy problem.

**Comment by cpatrickalves** [comment]
> Getting 407 is definitely not a Scrapy problem.

The problem is that I've set 407 code in RETRY_HTTP_CODES, thus it should retry when getting this code, but it does not.

**Comment by elacuesta** [comment]
Could you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) using https://httpbin.org/status/407?

**Comment by wRAR** [comment]
> > Getting 407 is definitely not a Scrapy problem.
> 
> The problem is that I've set 407 code in RETRY_HTTP_CODES, thus it should retry when getting this code, but it does not.

Well, I've said "If you think it's a bug in Scrapy, open a new bug report that includes a minimal reproducible example of the problem.".
