### ISSUE TITLE
Tests fail because of pytest 6.0.0

### ISSUE THREAD

**Issue by wRAR** [scrapy/scrapy#4702]
See https://travis-ci.org/github/scrapy/scrapy/builds/712802460

```
.tox/pinned/lib/python3.5/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
.tox/pinned/lib/python3.5/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
.tox/pinned/lib/python3.5/site-packages/pluggy/manager.py:87: in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
.tox/pinned/lib/python3.5/site-packages/sybil/integration/pytest.py:118: in pytest_collect_file
    return SybilFile(path, parent, sybil)
.tox/pinned/lib/python3.5/site-packages/_pytest/nodes.py:95: in __call__
    warnings.warn(NODE_USE_FROM_PARENT.format(name=self.__name__), stacklevel=2)
E   pytest.PytestDeprecationWarning: Direct construction of SybilFile has been deprecated, please use SybilFile.from_parent.
E   See https://docs.pytest.org/en/stable/deprecations.html#node-construction-changed-to-node-from-parent for more details.
```

**Comment by wRAR** [comment]
The changelog says "Following our plan to remove deprecated features with as little disruption as possible, all warnings of type PytestDeprecationWarning now generate errors instead of warning messages."

**Comment by wRAR** [comment]
The warning is fixed in sybil 1.3.1, do we want to pin it or require pytest < 6? We already require sybil >= 1.3.0

**Comment by wRAR** [comment]
OTOH I guess newer runs will just use the latest sybil.

**Comment by kshitijcode** [comment]
If it runs the latest Sybil , I guess the changes in  https://github.com/scrapy/scrapy/issues/4684 should have ideally used the latest version of Sybil ?

**Comment by wRAR** [comment]
@kshitijcode 1.3.1 was released only hours ago. I've restarted the tests for your PR, let's see what happens.

**Comment by wRAR** [comment]
As it's not a problem in Scrapy I'll close this.
