### ISSUE TITLE
Ignoring encoding with SCRAPY

### ISSUE THREAD

**Issue by CodeWithAwais** [scrapy/scrapy#4706]
I was scraping a Danish website that has Unicode characters. I tried with scrapy but the output is not the same as the website. It's replacing special characters with something else. I tried it with Selenium and used UTF-8 encoding and still didn't work but when I removed the UTF-8 encoding, it worked perfectly fine. 

So, I would like to know that is there a way to ignore any type of encoding with SCRAPY?

**Example link: https://novaindex.com/dk/leverandoerer/mode-og-tekstiler/arbejdstoej**

```
import scrapy
    
class MainSpider(scrapy.Spider):
    name = 'main'

    start_urls = ['https://novaindex.com/dk/leverandoerer/mode-og-tekstiler/arbejdstoej']

    def parse(self, response):

        details = response.xpath('//a[@class="companyresult "]')

        for each in details:
            name = each.xpath('normalize-space(.//span[@class="name"]/text())').get()
            street = each.xpath('normalize-space(.//span[@class="street"]/text())').get()
            city = each.xpath('normalize-space(.//span[@class="city"]/text())').get()
            phone = each.xpath('normalize-space(.//span[@class="phone"]/text())').get()

            yield {
                "Name": name,
                "Street Address": street,
                "City Address": city,
                "Phone": phone,
            }
```

**Comment by wRAR** [comment]
You provided the code but didn't explain what problems do you have with it. It looks correct to me.

**Comment by wRAR** [comment]
You didn't explain in what sense the output is broken. The same selectors give me correctly encoded output in `scrapy shell`.

**Comment by CodeWithAwais** [comment]
@wRAR I was scraping a page in the Danish Language. I am having trouble with the output. The output contains many special characters like (Ã¥, Ã, Ã¥, Ã¦) and it's not like the one on the page. I am facing this problem when exporting the data to the CSV file.

**Comment by wRAR** [comment]
This works here fine. Please provide steps to reproduce the problem.
