### ISSUE TITLE
Unable to invoke instance method from scrapy subclass

### ISSUE THREAD

**Issue by rajesh-5445** [scrapy/scrapy#4711]
I might want to call/invoke an instance method (parse_next_page) from my scrapy sub class, but it does not do so. Can you please hep me out?

Code:
import scrapy
class QuotesSpider(scrapy.Spider):
    name = 'quotes'
    start_urls = [
        'http://quotes.toscrape.com/tag/humor/',
    ]

    def parse(self, response):
        for quote in response.css('div.quote'):
            yield {
                'author': quote.xpath('span/small/text()').get(),
                'text': quote.css('span.text::text').get(),
            }
        print("*** call next page function")
        self.parse_next_page(response)    

    def parse_next_page(self, response):
        print("*** parsee next page function invoked")
        next_page = response.css('li.next a::attr("href")').get()
        if next_page is not None:
            yield response.follow(next_page, self.parse)

Output:
{'author': 'Terry Pratchett', 'text': '“The trouble with having an open mind, of course, is that people will insist on coming along and trying to put things in it.”'}
2020-07-29 09:30:39 [scrapy.core.scraper] DEBUG: Scraped from <200 http://quotes.toscrape.com/tag/humor/>
{'author': 'Dr. Seuss', 'text': '“Think left and think right and think low and think high. Oh, the thinks you can think up if only you try!”'}
2020-07-29 09:30:39 [scrapy.core.scraper] DEBUG: Scraped from <200 http://quotes.toscrape.com/tag/humor/>
{'author': 'George Carlin', 'text': '“The reason I talk to myself is because I’m the only one whose answers I accept.”'}
*** call next page funcion
2020-07-29 09:30:39 [scrapy.core.engine] INFO: Closing spider (finished)

**Comment by wRAR** [comment]
You called the function successfully, you just ignored its result. You need to use `yield from` or a loop to process the results from `parse_next_page`.
