### ISSUE TITLE
Document link extractor usage outside CrawlSpider rules

### ISSUE THREAD

**Issue by Gallaecio** [scrapy/scrapy#4751]
https://docs.scrapy.org/en/latest/topics/link-extractors.html mentions that link extractors may be used outside `CrawlSpider`, but it does not go into detail on how to do that.

Also, there are broken references to `scrapy.link.Link`, we should provide reference documentation for that class.

**Comment by HAKSOAT** [comment]
I'll like to work on this

**Comment by HAKSOAT** [comment]
#4775
