### ISSUE TITLE
Not getting new ip from api url after 8 to 9 request

### ISSUE THREAD

**Issue by alikamal-jaffri** [scrapy/scrapy#4758]
I am using 
`request.meta['proxy']="my api key"`
to get ips from my luminati id and after 8 ip's different scrapy start repeating the same ip which is the last ip address however if I use the same ip in '.py' file my api key is working fine it assign me new ip there after 10 searches from the same ip while using urllib in python
![image](https://user-images.githubusercontent.com/67379912/91278616-e4a32400-e79d-11ea-8945-6c2875ce32b9.png)

**Comment by Gallaecio** [comment]
This does not sound like a bug in Scrapy, but something specific to your project. Please, use [StackOverflow](https://stackoverflow.com/tags/scrapy) to ask this type of questions.
