### ISSUE TITLE
Error when use scrapy in cmd

### ISSUE THREAD

**Issue by quochungbn** [scrapy/scrapy#4760]
### Description

I have some error when trying to install scrapy

### Steps to Reproduce

1. Installed Anaconda + OpenSSL
2. Use conda install -c conda-forge scrapy
3. Get error when type scrapy on cmd

**Expected behavior:** Command scrapy should work

**Actual behavior:**  Error log: 

https://pastebin.com/CqNmRYJT

**Reproduces how often:** It happen for me on first install

### Versions

I can't get the version because it throw error

### Additional context

Output error: https://pastebin.com/CqNmRYJT

Tried:

+ Reinstall lxml with anaconda

**Comment by Gallaecio** [comment]
Looks like an issue with the lxml package of Anaconda or Conda Forge, rather than an issue in Scrapy itself.

Is this a fresh Anaconda environment or an old one? See https://github.com/ContinuumIO/anaconda-issues/issues/8006

**Comment by imsahil007** [comment]
> ### Description
> I have some error when trying to install scrapy
> 
> ### Steps to Reproduce
> 1. Installed Anaconda + OpenSSL
> 2. Use conda install -c conda-forge scrapy
> 3. Get error when type scrapy on cmd
> 
> **Expected behavior:** Command scrapy should work
> 
> **Actual behavior:** Error log:
> 
> https://pastebin.com/CqNmRYJT
> 
> **Reproduces how often:** It happen for me on first install
> 
> ### Versions
> I can't get the version because it throw error
> 
> ### Additional context
> Output error: https://pastebin.com/CqNmRYJT
> 
> Tried:
> 
> * Reinstall lxml with anaconda

This is an issue with 32bit lxml.
Try install 64 bit module. Maybe you are just using a 32 bit anaconda instead of 64 bit.
You can also try installing another version:
https://stackoverflow.com/a/41289490
```
python -m pip uninstall lxml
python -m pip install lxml==3.6.0
```

**Comment by quochungbn** [comment]
> > ### Description
> > I have some error when trying to install scrapy
> > ### Steps to Reproduce
> > 
> > 1. Installed Anaconda + OpenSSL
> > 2. Use conda install -c conda-forge scrapy
> > 3. Get error when type scrapy on cmd
> > 
> > **Expected behavior:** Command scrapy should work
> > **Actual behavior:** Error log:
> > https://pastebin.com/CqNmRYJT
> > **Reproduces how often:** It happen for me on first install
> > ### Versions
> > I can't get the version because it throw error
> > ### Additional context
> > Output error: https://pastebin.com/CqNmRYJT
> > Tried:
> > 
> > * Reinstall lxml with anaconda
> 
> This is an issue with 32bit lxml.
> Try install 64 bit module. Maybe you are just using a 32 bit anaconda instead of 64 bit.
> You can also try installing another version:
> https://stackoverflow.com/a/41289490
> 
> ```
> python -m pip uninstall lxml
> python -m pip install lxml==3.6.0
> ```
> 
> @Gallaecio

Install older version work for me! Thank you!
