### ISSUE TITLE
request fingerprint should separate different sections when building a hash

### ISSUE THREAD

**Issue by kmike** [scrapy/scrapy#4762]
It looks like body & headers & values are not separated where fp is being built in request_fingerprint function. 

So e.g. a request with header with "foo" and "bar" values would get the same fingerprint as a request with "fo" and "obar" values. The same applies for body, etc. URL is joined with the body, for example, so a POST request to http://example.com/foo with empty body gets the same fingerprint as a POST request to http://example.com/fo with "o" body:

```py
from scrapy import request
from scrapy.utils.request import request_fingerprint

req1 = scrapy.Request("http://example.com/foo", method="POST", body=b'')
req2 = scrapy.Request("http://example.com/fo", method="POST", body=b'o')

request_fingerprint(req1)  # 'ca64371a30748ddb06e28365b7e1177db7bfa8e9'
request_fingerprint(req2)  # 'ca64371a30748ddb06e28365b7e1177db7bfa8e9'
```

**Comment by Gallaecio** [comment]
Related to #900 (mentioned by you in https://github.com/scrapy/scrapy/issues/900#issuecomment-64933901)

**Comment by luckcry** [comment]
maybe its a wrong use of Request.
Usually, FormRequest is used to build a request for "POST" method when Request is for a "GET" request. 
So you should consider use FormRequest instead of Request when your method is "POST".
Just a simple example:
```
from scrapy import Request, FormRequest
from scrapy.utils.request import request_fingerprint
req2 = FormRequest("http://example.com/fo", method="POST", body=b'o')
req1 = FormRequest("http://example.com/fo", method="POST", body=b'')
request_fingerprint(req2)  #  ca64371a30748ddb06e28365b7e1177db7bfa8e9
request_fingerprint(req1)   # 7d14b9f24815a1d771e89a0d7e8ead282000b440
```

**Comment by elacuesta** [comment]
The URL is misspelled in the second request ("fo" instead of "foo").

Using the `Request` class to make POST requests is perfectly valid, the `FormRequest` is merely a convenient shortcut to make it easier to interact with HTML forms. 

```python
>>> from scrapy import Request, FormRequest
>>> from scrapy.utils.request import request_fingerprint
>>> requests = [
...     Request("http://example.com/foo", method="POST", body=b''),
...     Request("http://example.com/fo", method="POST", body=b"o"),
...     FormRequest("http://example.com/foo", method="POST", body=b''),
...     FormRequest("http://example.com/fo", method="POST", body=b"o"),
... ]
>>> set([request_fingerprint(r) for r in requests])
{'ca64371a30748ddb06e28365b7e1177db7bfa8e9'}
>>> 
```

**Comment by luckcry** [comment]
> 
> 
> The URL is misspelled in the second request ("fo" instead of "foo").
> 
> Using the `Request` class to make POST requests is perfectly valid, `FormRequest` is merely a convenient helper to make it easier to interact with HTML forms.
> 
> ```python
> >>> from scrapy import Request, FormRequest
> >>> from scrapy.utils.request import request_fingerprint
> >>> requests = [
> ...     Request("http://example.com/foo", method="POST", body=b""),
> ...     Request("http://example.com/fo", method="POST", body=b"o"),
> ...     FormRequest("http://example.com/foo", method="POST", body=b""),
> ...     FormRequest("http://example.com/fo", method="POST", body=b"o"),
> ... ]
> >>> set([request_fingerprint(r) for r in requests])
> {'ca64371a30748ddb06e28365b7e1177db7bfa8e9'}
> >>> 
> ```

Thanks for your patient reply. It's nice to get it clearly~
