### ISSUE TITLE
Scrapy parses commented out <base> element

### ISSUE THREAD

**Issue by mauritsderuiter95** [scrapy/scrapy#4763]
### Description

I'm building a scraper that follows some urls with a pattern with the response.follow function. I'm currently stuck on a webpage which has the <base> element in the header commented out. The href in the <base> element is invalid. When I try to follow a relative url on the webpage it incorrectly tries to send me to the invalid url. It ignores the fact that it actually is a comment.

### Steps to Reproduce

1. Use the response.follow function
2. Go to http://prahm-stiftung.de/
3. Try to follow the "Kontakt & Impressum" page
4. It redirects to " http://www.www.prahm-stifung.de/5-0-Kontakt-und-Impressum.html" which is incorrect. The <base> element is commented out

**Expected behavior:** Ignore the <base> element.

**Actual behavior:** It uses the commented out <base> element to get the url to follow

**Reproduces how often:** Always

### Versions

Scrapy       : 2.1.0
lxml         : 4.5.1.0
libxml2      : 2.9.10
cssselect    : 1.1.0
parsel       : 1.6.0
w3lib        : 1.22.0
Twisted      : 20.3.0
Python       : 3.8.2 (v3.8.2:7b3ab5921f, Feb 24 2020, 17:52:18) - [Clang 6.0 (clang-600.0.57)]
pyOpenSSL    : 19.1.0 (OpenSSL 1.1.1g  21 Apr 2020)
cryptography : 2.9.2
Platform     : macOS-10.15.6-x86_64-i386-64bit

### Additional context

page = '5-0-Kontakt-und-Impressum.html'
yield response.follow(page, callback=self.parse)

**Comment by Gallaecio** [comment]
Upstream issue: https://github.com/scrapy/w3lib/issues/70

**Comment by mauritsderuiter95** [comment]
Thank you. 

I worked around the issue by removing one-line comments with a regex and creating a new HtmlResponse with that content. A little more lines of code, but it works.

**Comment by ashish-hacker** [comment]
Is this issue still open?

**Comment by wRAR** [comment]
The w3lib issue is fixed now.
