### ISSUE TITLE
Invalid cookies ('value' missing) - Added in 2.3.0 - scrapy/downloadermiddlewares/cookies.py 

### ISSUE THREAD

**Issue by L3NNYY** [scrapy/scrapy#4766]
### Description

When scraping certain sites and passing cookies to scrapy, I've had an issue pop up where the page wasn't able to scrape due to an error message `"Invalid cookie found in request {}: {} ('{}' is missing)"`. This is because some websites and pages form cookies with an empty value instead of not including the key altogether (hacky fix on their side), causing the newly added check in scrapy/downloadermiddlewares/cookies.py ln. 78 to pass and stop the request. 

Perhaps a setup variable that would let us toggle this cookie check would solve the issue, or perhaps removing this specific check/making it a warning, and not causing the function to return.

The only other solution temporarily right now if for scrapy users to have to re-format the cookies themselves, and some sites do want the empty value cookie object.

Since 2.3.0 just got released, I've only seen one other thread (on stackoverflow) mentioning this issue. 
https://stackoverflow.com/questions/63204521/scrapy-and-invalid-cookie-found-in-request

### Steps to Reproduce

1. Get website cookies that aren't formatted properly (so a key with an empty value: eg. value:'')
2. Pass the cookie to scrapy and see the request not go through

**Expected behavior:** [What you expect to happen]
2.2.0 and previous versions have allowed the request to go through even when cookie isn't properly formatted (in our case we are passing cookies from selenium webdriver to scrapy so we don't do any cookie formatting ourselves).
**Actual behavior:** [What actually happens]
Stops the request
**Reproduces how often:** [What percentage of the time does it reproduce?]
Every Time
### Versions
2.3.0

**Comment by elacuesta** [comment]
As mentioned in one of the answers from the linked SO question, checking for `is not None` would probably be better than the current check. However, that shouldn't stop the request from being processed. See the following `scrapy shell` session, for instance:

```python
In [1]: import json

In [2]: fetch(scrapy.Request("http://httpbin.org/cookies", cookies={"foobar": None}))
2020-08-31 18:20:12 [scrapy.core.engine] INFO: Spider opened
2020-08-31 18:20:12 [scrapy.downloadermiddlewares.cookies] WARNING: Invalid cookie found in request <GET http://httpbin.org/cookies>: {'name': 'foobar', 'value': None} ('value' is missing)
2020-08-31 18:20:13 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://httpbin.org/cookies> (referer: None)

In [3]: json.loads(response.text)
Out[3]: {'cookies': {}}
```

Are you observing a different behavior? Could you post some minimal code along with logs from an execution?

**Comment by Gallaecio** [comment]
Closing due to a lack of feedback.
