### ISSUE TITLE
should robotexclusionrulesparser be listed in setup.py?

### ISSUE THREAD

**Issue by suliuzh** [scrapy/scrapy#4773]
## Summary

robotexclusionrulesparser should be listed in setup.py .

## Motivation

Why are we doing this? What use cases does it support? What is the expected outcome?

## Describe alternatives you've considered

Hi
**robotexclusionrulesparser** is now listed in _tox.ini_ as optional dependency. But it is used in class _RerpRobotParser like this in the following screenshot.  So  If it is a must, I am wondering if **robotexclusionrulesparser** should be listed in setup.py?  

![image](https://user-images.githubusercontent.com/27858725/91827338-49182480-ec71-11ea-9eee-616e5469d4f3.png)

## Additional context

Any additional information about the feature request here.

**Comment by Gallaecio** [comment]
It is not listed on purpose. That class is not used by Scrapy unless you explicitly configure Scrapy to use it, and only when you do that you need to install that dependency.

**Comment by suliuzh** [comment]
How about ptpython? It is used in scrapy/utils/console.py.

**Comment by elacuesta** [comment]
> How about ptpython? It is used in scrapy/utils/console.py.

It's also optional, you can configure which shell you want to use: https://docs.scrapy.org/en/latest/topics/shell.html#configuring-the-shell
