### ISSUE TITLE
My parser randomly receives response for domain's root

### ISSUE THREAD

**Issue by psychonaute** [scrapy/scrapy#4781]
Every once in a while (every 100-150 requests) a request produce response about the domain's root URL

### Steps to Reproduce

```
def start_requests(self):
    total = len(self.payload)
    for entry in payload:
        idx = self.state.get('items_count', 1)
        self.logger.info('yielding url %s/%s: %s',idx, total, entry['url'])
        yield scrapy.Request(entry['url'], meta={
                'idx': idx, 
                'total': total
                })
        self.state['items_count'] = self.state.get('items_count', 1) + 1
```

```
def parse(self, response):
    self.logger.info('parsing %s/%s : %s', response.meta['idx'], response.meta['total'], response.url)
    print(response.status) # '200'
    print(response.url) # 'https://www.mydomain.com/'
```

**Produce**

start_requests() logger says
`INFO: yielding url 528/1353: https://www.mydomain.com/path/to/mypage?cid=9598492`

parse() logger says:
`INFO: parsing 528/1353 : https://www.mydomain.com/`

**Reproduces how often:** [What percentage of the time does it reproduce?]

~1/150 requests

### settings

```
DOWNLOAD_DELAY = 1
DOWNLOAD_TIMEOUT = 30
RANDOMIZE_DOWNLOAD_DELAY = True
REACTOR_THREADPOOL_MAXSIZE = 128
CONCURRENT_REQUESTS = 64
CONCURRENT_REQUESTS_PER_DOMAIN = 64
CONCURRENT_REQUESTS_PER_IP = 64
AUTOTHROTTLE_ENABLED = True
AUTOTHROTTLE_START_DELAY = 1
AUTOTHROTTLE_MAX_DELAY = 0.25
AUTOTHROTTLE_TARGET_CONCURRENCY = 64
AUTOTHROTTLE_DEBUG = True
```

### Any advise?

Is it because I'm being too aggressive on the server?

What is a good ratio safety-efficiency now a days for let say major news outlet websites?

**Comment by wRAR** [comment]
This is an issue tracker for Scrapy itself. Please use other communities such as https://stackoverflow.com/ for user questions.
