### ISSUE TITLE
Yield not working in additional parse Method

### ISSUE THREAD

**Issue by claude-eric-steiner** [scrapy/scrapy#4790]
### Description
I use start_requests to dynamically create the URL for the spider (from a DB source, the code below doesn't reflect this, but shows "www.google.com" as target). This works all fine.

To keep my code good structured, I do the following:
I'm using the meta argument to hand over a type parameter (as I'm spidering three different types of pages with different content in the same spider).

 ``` 
   def start_requests(self):
        print "start_requests executed"
        #URL to scrape are read here from DB, below is a simple example how they get added to the spider queue
        yield scrapy.Request("https://www.google.com", callback = self.parse, meta={
            'type':'CatalogPage',
        })
```

In the parse method, I read out the page type parameter from the meta property, and call different parse methods (dependent of the type of page that caused the call to parse).
You can see how this is setup here:

```
   def parse(self, response):
        #Switch different parsers dependent of Request Type
        request_type = response.meta['type']
        if request_type == 'CatalogPage':
            print "type CatalogPage detected, calling parseCatalogPage"
            #pItem = ProductItem()
            #pItem['id'] = 324234
            #pItem['url'] = "https://www.google.ch"
            #pItem['name'] = "this name"
            #yield pItem
            self.parseCatalogPage(response)
        if request_type == 'ProductPage':
            self.parseProductPage(response)
        if request_type == 'UserPage':
            self.parseUserPage(response)
```
As you can see above, I have an commented Item yield in that **if request_type == 'CatalogPage'**

In the parseCatalogPage method, I have exactly the same Item yield:

```
    def parseCatalogPage(self, response):
        print "parseCatalogPage executed"
        print "saving content"
        #pItem = ProductItem()
        #pItem['id'] = 324234
        #pItem['url'] = "https://www.google.ch"
        #pItem['name'] = "this name"
        #yield pItem
```

If I execute this script (with both item yields commented), I see these strings printed to std-out:
**"type CatalogPage detected, calling parseCatalogPage"**
**"parseCatalogPage executed"**
**"saving content"**
This shows that my "switch type case" and calling the correct parser method is working.

If I execute this script (with the item yields in the "if statement" **uncommented**, and the item yield in the parseCatalogPage still commented), I still see these strings printed to std-out, together with the print statement from my pipelines.py:
**"type CatalogPage detected, calling parseCatalogPage"**
**STORING ProductItem: {'id': 324234, 'name': 'this name', 'url': 'https://www.google.ch'}**
**"parseCatalogPage executed"**
**"saving content"**

If I execute this script (with the item yields in the "if statement" commented, and the item yield in the parseCatalogPage **uncommented**) I get this strange behaviour:
**"type CatalogPage detected, calling parseCatalogPage"**

I don't see the **STORING ProductItem** string (like the yield was never called).
Even more strange, I don't even see the **"parseCatalogPage executed"** and the **"saving content"** string, 
like the parseCatalogPage method was never called at all.

I know it's easy to do a workaround and put the yield statements directly in the "if statements", and do all parsing there, 
but I like better structured code and to call different methods for different page types (and not put all parser stuff in the same method). But it looks like that as soon as I have any yield in these additional methods, the methods don't get called at all.
(I tried it also without the item yield method, but with an 
`yield response.follow("https://www.google.ch", callback=self.parse)`
but get the same results...

any clue what is going on here??

### Steps to Reproduce

create a simple spider with the above code.
Execute it and do the commeting/uncommenting like decribed above

**Expected behavior:** [What you expect to happen]

I would expect that any yield statements would work if they are written in the parse method itself, 
or in any delegated/called method from inside the parse method.

**Actual behavior:** [What actually happens]

The yield statements work only inside the parse method itself. If I call another method from inside the parse method, 
and try to yield there something, not only the yield statement fails, but it looks like the called method is not executed at all.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

`/usr/local/lib/python2.7/site-packages/OpenSSL/crypto.py:12: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
  from cryptography import x509
Scrapy       : 1.8.0
lxml         : 4.5.2.0
libxml2      : 2.9.10
cssselect    : 1.1.0
parsel       : 1.6.0
w3lib        : 1.22.0
Twisted      : 20.3.0
Python       : 2.7.17 (default, Apr  2 2020, 01:25:01) - [GCC 4.2.1 Compatible FreeBSD Clang 8.0.1 (tags/RELEASE_801/final 366581)]
pyOpenSSL    : 19.1.0 (OpenSSL 1.1.1d-freebsd  10 Sep 2019)
cryptography : 3.1
Platform     : FreeBSD-12.1-RELEASE-amd64-64bit-ELF
`

### Additional context

I'm using proxies and some other stuff, but I doubt that this is related with that behaviour.

**Comment by Gallaecio** [comment]
The issue is not in Scrapy, but in your code. Please, use [StackOverflow](https://stackoverflow.com/tags/scrapy) to ask this type of questions. See [Getting Help](https://docs.scrapy.org/en/latest/#getting-help).
