### ISSUE TITLE
How to setup http proxy fro https urls scrapy need help setting up?

### ISSUE THREAD

**Issue by raghulkrishna** [scrapy/scrapy#4791]
import base64
class ProxyMiddleware(object):
    # overwrite process request
    def process_request(self, request, spider):
        # Set the location of the proxy
        request.meta['proxy'] = "us.proxymesh.com:31280"
        # Use the following lines if your proxy requires authentication
        # setup basic authentication for the proxy
        from basicauth import encode
        encoded_str = encode(username, password)
        request.headers['Proxy-Authorization'] = encoded_str

**Comment by Gallaecio** [comment]
Please, use [StackOverflow](https://stackoverflow.com/tags/scrapy) to ask this type of questions. See [Getting Help](https://docs.scrapy.org/en/latest/#getting-help).
