### ISSUE TITLE
How to setup proxymesh for https urls scrapy ?

### ISSUE THREAD

**Issue by raghulkrishna** [scrapy/scrapy#4792]
class ProxyMiddleware(object):
    # overwrite process request
    def process_request(self, request, spider):
        # Set the location of the proxy
        request.meta['proxy'] = "http://nl.proxymesh.com:31280"
        # Use the following lines if your proxy requires authentication
        # setup basic authentication for the proxy
        from basicauth import encode
        encoded_str = encode(username, password)
        encoded_user_pass =  base64.encodestring(proxy_user_pass).decode()
        request.headers['Proxy-Authorization'] = basic_auth_header(username,password)

**Comment by elacuesta** [comment]
The GitHub issue tracker is used for bug reports and/or feature requests for Scrapy itself. Please use [StackOverflow](https://stackoverflow.com/tags/scrapy) to ask this kind of support questions. See also [Getting help](https://docs.scrapy.org/en/latest/#getting-help).
