### ISSUE TITLE
FEED_STORE_EMPTY does not appear to work

### ISSUE THREAD

**Issue by joeharrison714** [scrapy/scrapy#4794]
### Description

I am attempting to export all fields from an item even if they are not populated. I have set FEED_STORE_EMPTY to True which according to the documentation should do this. However I still do not have the unpopulated fields in the output file.

I have created an item as follows:
```
class QuotesbotItem(scrapy.Item):
    text = scrapy.Field()
    author = scrapy.Field()
    tags = scrapy.Field()
    junk = scrapy.Field()
```

I then populate the item:
```
            data = QuotesbotItem()
            data["text"] = quote.css("span.text::text").get()
            data["author"] = quote.css("small.author::text").get()
            data["tags"] = quote.css("div.tags > a.tag::text").getall()
            yield data
```

In my settings.py, I have `FEED_STORE_EMPTY = True`

I would expect `junk` to be in the output file, but it is not.

**Comment by Gallaecio** [comment]
I don’t see anything in the [documentation of FEED_STORE_EMPTY](https://docs.scrapy.org/en/latest/topics/feed-exports.html#std-setting-FEED_STORE_EMPTY) that would suggest that to me:

> Whether to export empty feeds (i.e. feeds with no items).

See [FEED_EXPORT_FIELDS](https://docs.scrapy.org/en/latest/topics/feed-exports.html#feed-export-fields).
