### ISSUE TITLE
Improve Testability of Scrapy ( ReactorNotRestartable )

### ISSUE THREAD

**Issue by DarkTrick** [scrapy/scrapy#4826]
## Current Situation

Using scrapy as described in the tutorials ( [this (intro/tutorial.html)](https://docs.scrapy.org/en/latest/intro/tutorial.html) and [this (topics/practices.html)](https://docs.scrapy.org/en/latest/topics/practices.html) ) might/will throw an 
`twisted.internet.error.ReactorNotRestartable` error if run with `unittest`. 

Both, using `CrawlerProcess` or `CrawlerRunner` will raise the error.

Also, there seems to be no (/ no easy) solution to this problem:

- [scrapy-twisted-internet-error-reactornotrestartable-error-after-first-run](https://stackoverflow.com/questions/45137458/scrapy-twisted-internet-error-reactornotrestartable-error-after-first-run)
- [reactornotrestartable-error-in-while-loop-with-scrapy](https://stackoverflow.com/questions/39946632/reactornotrestartable-error-in-while-loop-with-scrapy)
- [scrapy-reactornotrestartable-one-class-to-run-two-or-more-spiders](https://stackoverflow.com/questions/30970436/scrapy-reactornotrestartable-one-class-to-run-two-or-more-spiders) (solution only works, if scrapy is not wrapped in other domain code)
- [scrapy-reactor-not-restartable](https://stackoverflow.com/questions/41495052/scrapy-reactor-not-restartable) (The accepted answer requires you to fork the process)

## Suggestion

Make scrapy work in unittest environments without throwing the `twisted.internet.error.ReactorNotRestartable` error.

## Remarks

Might be related to https://github.com/scrapy/scrapy/issues/2594 but the intention is different

## Example code
The code below will reproduce the error. It does not contain a unit test, but is essentially has the same behavior.

```
# ====================================================================

# define quotes spicer

import scrapy
from twisted.internet import reactor
from scrapy.crawler import CrawlerRunner
from scrapy.utils.log import configure_logging

class QuotesSpider(scrapy.Spider):
    name = "quotes"
    start_urls = [
        'http://quotes.toscrape.com/page/1/',
        'http://quotes.toscrape.com/page/2/',
    ]

    def parse(self, response):
        page = response.url.split("/")[-2]
        filename = 'quotes-%s.html' % page
        with open(filename, 'wb') as f:
            f.write(response.body)

# ====================================================================

# Function to run spider
def run_spider():
   configure_logging()
   runner = CrawlerRunner({"LOG_LEVEL": 'ERROR'})
   runner.crawl(QuotesSpider)
   d = runner.join()
   d.addBoth(lambda _: reactor.stop())

   reactor.run() # the script will block here until all crawling jobs are finished

# ====================================================================

if "__main__" == __name__:
   run_spider()
   run_spider()   # This call will fail
```

**Comment by wRAR** [comment]
> Using scrapy as described in the tutorials 

Which is how exactly? `CrawlerRunner`, for example, doesn't manage the reactor and shouldn't have this problem.

> might/will throw an twisted.internet.error.ReactorNotRestartable error if run with unittest.

Can you provide more info about this use case?

**Comment by DarkTrick** [comment]
Temporary info: **I will put a small example script together, and add it here soon.**

Apologies for the lack of information. I was expecting, that it's a more known problem, that scrapy would not perform well in unittests.

This is the tutorial I was talking about: https://docs.scrapy.org/en/latest/topics/practices.html

I tried `CrawlerProcess` and `CrawlerRunner`. Both brought up the error.


> CrawlerRunner, for example, doesn't manage the reactor and shouldn't have this problem.

This is strange. From the page above I'm using this code: 

```
configure_logging()
runner = CrawlerRunner()
runner.crawl(MySpider1)
runner.crawl(MySpider2)
d = runner.join()
d.addBoth(lambda _: reactor.stop())

reactor.run() # the script will block here until all crawling jobs are finished
```

**Comment by DarkTrick** [comment]
@wRAR I added example code in the first post. I hope that clears things up.

**Comment by wRAR** [comment]
> I was expecting, that it's a more known problem, that scrapy would not perform well in unittests.

I still don't know what do you mean by that and you didn't provide any unittest-related code. Note that Scrapy itself has an extensive test suite which uses it in a variety of modes.

> This is strange. From the page above I'm using this code:

And this code works as expected. On the other hand, the code you added to the first post is incorrect and goes against the Scrapy documentation: you have effectively reimplemented `CrawlerProcess` as your `run_spider()` function and so it cannot run twice as well. You are supposed to start (and stop) the reactor only once. This is not specific to Scrapy, by the way.

**Comment by DarkTrick** [comment]
### Summary of this post
I think it's not clear (from the docs) how the test code below should be rewritten to execute properly within the a suite.

### Actual post

Maybe the documentation is a little confusing(?). (This)[https://docs.scrapy.org/en/latest/topics/practices.html] states:

> There’s another Scrapy utility that provides more control over the crawling process: scrapy.crawler.CrawlerRunner. 
> This class is a thin wrapper that encapsulates some simple helpers to run multiple crawlers, but it won’t start or interfere with existing reactors in any way.

With an emphasis on `won’t start or interfere with existing reactors in any way`

It goes on with

> Here’s an example of its usage, along with a callback to manually stop the reactor after MySpider has finished running.

Followed by this code:

```
from twisted.internet import reactor
import scrapy
from scrapy.crawler import CrawlerRunner
from scrapy.utils.log import configure_logging

class MySpider(scrapy.Spider):
    # Your spider definition
    ...

configure_logging({'LOG_FORMAT': '%(levelname)s: %(message)s'})
runner = CrawlerRunner()

d = runner.crawl(MySpider)
d.addBoth(lambda _: reactor.stop())
reactor.run() # the script will block here until the crawling is finished
```

Which is the code I used above.

After that explanation I would expect, that I can run 

```
configure_logging({'LOG_FORMAT': '%(levelname)s: %(message)s'})
runner = CrawlerRunner()

d = runner.crawl(MySpider)
d.addBoth(lambda _: reactor.stop())
reactor.run() # the script will block here until the crawling is finished
```
as many times as I like without *interfering with existing reactors in any way*.

## TestCase for a spider

> I still don't know what do you mean by that and you didn't provide any unittest-related code.

I intended to shorten the code. Here the same code using `unittest`:

```
# ====================================================================

import unittest

import scrapy
from twisted.internet import reactor
from scrapy.crawler import CrawlerRunner
from scrapy.utils.log import configure_logging

class QuotesSpider(scrapy.Spider):
    name = "quotes"
    start_urls = [
        'http://quotes.toscrape.com/page/1/',
        'http://quotes.toscrape.com/page/2/',
    ]

    def parse(self, response):
        page = response.url.split("/")[-2]
        filename = 'quotes-%s.html' % page
        with open(filename, 'wb') as f:
            f.write(response.body)

# ====================================================================
   
# Function to run spider
def run_spider():
   configure_logging()
   runner = CrawlerRunner({"LOG_LEVEL": 'ERROR'})
   runner.crawl(QuotesSpider)   
   d = runner.join()
   d.addBoth(lambda _: reactor.stop())

   reactor.run() # the script will block here until all crawling jobs are finished

# ====================================================================

class TestSpidertest(unittest.TestCase):
   def _checkResult(self):
      """do some testing for result checking"""      
   def test_test1(self):
      run_spider()      
      self._checkResult(self)
   def test_test2(self):
      run_spider()         
      self._checkResult(self)
            
if "__main__" == __name__:
   unittest.main()

```

## `run_spider()` function reimplements `CrawlerProcess`

> you have effectively reimplemented CrawlerProcess as your run_spider() function 
and so it cannot run twice as well. 
> You are supposed to start (and stop) the reactor only once. 
This is not specific to Scrapy, by the way.

I am missing this information within the documentation and the code examples.
Perhaps adding a `# This code must only be run once during execution` would help.

Also an encapsulation of the functionality within the code might be very helpful. 
It would further make clear what code parts are executable several times an which parts are not.

**Comment by wRAR** [comment]
> This class is a thin wrapper that encapsulates some simple helpers to run multiple crawlers, but it won’t start or interfere with existing reactors in any way.

This is specifically about `CrawlerRunner` itself, not about the snippet that includes reactor management code and shows that you need to manage the reactor yourself, unlike when you use `CrawlerProcess`. The doc also describes that you have to start and stop the reactor yourself. 

> After that explanation I would expect, that I can run as many times as I like without interfering with existing reactors in any way.

Code that explicitly calls `reactor.run()` and `reactor.stop()` cannot be considered not interfering with the reactor. 

> Here the same code using unittest:

You can look at https://github.com/scrapy/scrapy/blob/master/tests/test_crawl.py for a correct implementation of a test suite that utilizes `CrawlerRunner` to run multiple crawls.

> I am missing this information within the documentation and the code examples.

I think the documentation assumes basic knowledge of the Twisted reactor (which isn't unreasonable to assume when you talk about it and discuss code that will manipulate it). Your initial problem description is "Using scrapy as described in the tutorials ( this (intro/tutorial.html) and this (topics/practices.html) ) might/will throw an twisted.internet.error.ReactorNotRestartable error if run with unittest.", and this is only true when you start the reactor multiple times and not specific to Scrapy.

**Comment by DarkTrick** [comment]
Well, I guess this bug is about API/architecture perception and language perception. So probably a very subjective topic (that we have different opinions about). 

I'll sum up my points and close the bug. I guess everything else just spins around:

- I would say the docs do not describe what you are describing here.

- I would say the "assumes basic knowlege of the Twisted reactor" argument is questionable because
   1. The referenced stackoverflow questions have no general working solution ( ie. "it's not only me, but apparently quite some people that have no idea how to solve it") 
   2. "Assuming basic knowledge of twisted reactor" is not stated within the docs (did I miss it?), so it shouldn't be a requirement

- I would say "because the others also do it" should not be a heavy valid reason.


> You can look at https://github.com/scrapy/scrapy/blob/master/tests/test_crawl.py for a correct implementation

Thank you very much for the link, I will try to make use it.
