### ISSUE TITLE
CSV item exporter does not flush on close

### ISSUE THREAD

**Issue by scientes** [scrapy/scrapy#4829]
### Description
The csv item exporter does not flush on close.

### Steps to Reproduce

1. Create pipeline with an CSV item exporter
2. only export few items (one or two)
3. Let spider close/finish

**Expected behavior:** All exported items are in the CSV Files

**Actual behavior:** Files with few items are empty (not even a header)

**Reproduces how often:** 100%

### Versions

Scrapy       : 2.3.0
lxml         : 4.5.2.0
libxml2      : 2.9.10
cssselect    : 1.1.0
parsel       : 1.6.0
w3lib        : 1.22.0
Twisted      : 20.3.0
Python       : 3.8.2 (default, Jul 16 2020, 14:00:26) - [GCC 9.3.0]
pyOpenSSL    : 19.1.0 (OpenSSL 1.1.1f  31 Mar 2020)
cryptography : 2.8
Platform     : Linux-5.4.0-7642-generic-x86_64-with-glibc2.29

### Example pipline.py

```python3
from itemadapter import ItemAdapter
from scrapy.exporters import CsvItemExporter

class CricketcrawlerPipeline:
    def open_spider(self, spider):
        self.name_to_exporter = {}

    def close_spider(self, spider):
        for exporter in self.name_to_exporter.values():
            exporter.finish_exporting()

    def process_item(self, item, spider):
        exporter = self._exporter_for_item(item)
        exporter.export_item(item)
        return item

    def _exporter_for_item(self, item):
        name = item['name']
        if name not in self.name_to_exporter:
            f = open(f'{item.folder}/{name}.csv', 'wb')
            exporter = CsvItemExporter(f)
            exporter.start_exporting()
            self.name_to_exporter[name] = exporter
        return self.name_to_exporter[name]
```

**Comment by Gallaecio** [comment]
They get an open file. I think it makes sense for the caller to be responsible of closing the file (just as it opened it), and not the item exporter.

**Comment by scientes** [comment]
To be totally honest i didn't think about closing the file, that works as well. But for all other people who might also forget it, calling a flush on closing the CSVexporter doesn't hurt in my opinion. It just makes sure that all items are written to disc on closing the Exporter and the file-pointer is still usable after that so it shouldn't break anything.

**Comment by Gallaecio** [comment]
Closing flushes, so proper calling code would not really benefit from this change. However, it is technically possible (though very rare, probably) for the calling code to use the same file object with multiple item exporters, in which case flushing _could_ negatively impact performance.

I don’t expect great penalties from such a change. But I see no real benefit either. I’m -0.5 on adding flushing.

**Comment by scientes** [comment]
Well i'm more or less neutral on adding it, knowing that it could have a negative impact. Close the issue if you want to.

**Comment by wRAR** [comment]
-0.5 from me too, for the same reasons

**Comment by GeorgeA92** [comment]
In general case (with `FEEDS` setting or with `-o` scrapy command line tool parameter) scrapy use[ `FileFeedStorage`](https://github.com/scrapy/scrapy/blob/2.3.0/scrapy/extensions/feedexport.py#L80-L92) objects for maintaining (open/close) files for item exporters and it's controlled by `FeedExporter` extension.

[ItemExporter code sample from scrapy docs](https://docs.scrapy.org/en/2.4/topics/exporters.html#using-item-exporters) (@scientes 's code probably based on it) doesn't use `FileFeedStorage` and it doesn' close files - this code... is not complete.

This issue , https://github.com/scrapy/scrapy/issues/4786 and, https://github.com/scrapy/scrapy/issues/4784 probably have the same origin.

**Comment by wRAR** [comment]
That `PerYearXmlExportPipeline` is indeed problematic.

**Comment by scientes** [comment]
Yes i've used the docs as basis. Maybe we should Update the documentation to close the files.

**Comment by wRAR** [comment]
Another consideration, the file-like object that is passed to the exporter doesn't necessarily support the flush method.
