### ISSUE TITLE
tests/test_downloadermiddleware.py bug with Twisted 17.9.0 

### ISSUE THREAD

**Issue by wRAR** [scrapy/scrapy#4841]
As found in #4814 if you manage to install Twisted 17.9.0 (which our tests currently don't), the `tests/test_downloadermiddleware.py::MiddlewareUsingCoro::test_asyncdef` test hangs, probably because of http://twistedmatrix.com/trac/ticket/9390

**Comment by Gallaecio** [comment]
Unless we can come up with a workaround that gets our tests to work with the minimum supported version of Twisted, what should we do? Should we document the minimum version of Twisted used by asyncio tests as a requirement for asyncio support, or don’t mention it in the documentatio?

**Comment by wRAR** [comment]
First I need to make sure the problem is only in the tests.

**Comment by wRAR** [comment]
So, the Twisted change makes the reactor use `get_event_loop()` instead of `new_event_loop()` if the loop is not passed explicitly. pytest-twisted doesn't pass it explicitly so the change affects our tests. But Scrapy now (since #4414) uses `new_event_loop()` explicitly, so I don't understand why non-test Scrapy usage is still fine with old Twisted.

**Comment by elacuesta** [comment]
I am able to successfully run these tests with Twisted==17.9.0 after #4872, should we close this?

**Comment by wRAR** [comment]
I think so.
