### ISSUE TITLE
Add a Social Preview Image

### ISSUE THREAD

**Issue by mrcartoonster** [scrapy/scrapy#4843]
## Summary

I see that Scrapy's on Hactoberfest. I found it on GitHub's topics and I noticed it doesn't have a social preview.

## Motivation

Looking through the repos that have Social previews and those that don't. The ones that do have one look professional and stand out more. Scrapy already has image of a scraper that will look amazing as a social preview and help it stand out.

## Describe alternatives you've considered

You can use ScrapingHub images as well:)

## Additional context

No additional context

**Comment by elacuesta** [comment]
Added, thanks for bringing this into our attention :smile:
