### ISSUE TITLE
`feed_options` is not passed to build_storage()

### ISSUE THREAD

**Issue by vimagick** [scrapy/scrapy#4845]
https://github.com/scrapy/scrapy/blob/c340e72988fc6ec615b7b9851c3d28c16c26a839/scrapy/extensions/feedexport.py#L454-L455

I'm not sure.
Maybe we need to pass `feed_options` parameter to build_storage().

**Comment by elacuesta** [comment]
Could you please elaborate?

**Comment by GeorgeA92** [comment]
@elacuesta 
Without `feed_options` parameter inside `build_storage` call - Storage objects like `FileFeedStorage` ignore  overwrite `-O` option mentioned in [Scrapy 2.4 relase notes](https://docs.scrapy.org/en/latest/news.html#scrapy-2-4-0-2020-10-11) #4857
