### ISSUE TITLE
Issue installing Scrapy due to Protego

### ISSUE THREAD

**Issue by mcsmith3** [scrapy/scrapy#4847]
![image](https://user-images.githubusercontent.com/45048825/96132825-c23da500-0ec8-11eb-9ad6-e45d6b7aba57.png)
I can't seem to install Scrapy due to an issue with collecting Protego. May not be an issue with Scrapy or Protego itself, but I have tried several times.

**Comment by wRAR** [comment]
It's clearly an issue either with your network or with pythonhosted.org.
