### ISSUE TITLE
Upgrade scrapy 2.2. to 2.3 breaks my code, parse() not called any more

### ISSUE THREAD

**Issue by EelcoA** [scrapy/scrapy#4854]
### Description

My python code fires a spider and after that the output is processed further (sorting, enhancing etc). After an update to scrapy 2.3 the parse() function isn't called any more. It works in 2.1 and 2.2, but fails in 2.3, 2.4.

### Steps to Reproduce

My calling program:

```
def crawl_fabriek_website_into_file(output_filepath: str):
    process = scrapy.crawler.CrawlerProcess(settings={
        "FEEDS": {
            output_filepath: {"format": "csv"},
        }
    })
    process.crawl(FabriekSpider)
    process.start()  # the script will block here until the crawling is finished
```
My spider:

```
class FabriekSpider(scrapy.spiders.CrawlSpider):
    name = 'fabriek'
    allowed_domains = ['www.de-fabriek.nl']
    start_urls = ['https://www.de-fabriek.nl']
    custom_settings = {
        'LOG_LEVEL': 'ERROR',
    }

    def parse(self, response):
        print("in parse(self, response) ")
        day_urls = response.xpath("//a[@class='day-selector__day']/@href").getall()

```

The 'print' in parse() doesn't fire in scrapy 2.3, 2.4 etc. Luckily we can install old versions, but of course I would like to go further with new scrapy versions. I see in version history of scrapy that things have changed around parse(), I will examine this in the future, but if anybody knows what caused this, please let me know.

### Versions

Scrapy 2.1.0 vs Scrapy 2.3.0

### Additional context

See complete code: https://github.com/EelcoA/fabriekscraper

**Comment by wRAR** [comment]
`CrawlSpider` should not override `parse`, the documentation for 2.2 already said "When writing crawl spider rules, avoid using parse as callback, since the CrawlSpider uses the parse method itself to implement its logic. So if you override the parse method, the crawl spider will no longer work.".

**Comment by wRAR** [comment]
OTOH you don't seem to use any CrawlSpider features so you shouldn't inherit from it.

**Comment by EelcoA** [comment]
Ah, thanks. That's where I went wrong, somewhere along the line I started to extend CrawlSpider, but didn't use its features. Extending Spider fixed the issue.
