### ISSUE TITLE
Cannot overwrite an output file with -O

### ISSUE THREAD

**Issue by wRAR** [scrapy/scrapy#4857]
Initially found at https://www.reddit.com/r/scrapy/comments/jhpc2f/o_doesnt_overwrite_on_wsl/

Looks like `_get_storage()` doesn't pass `feed_options` anywhere?

https://github.com/scrapy/scrapy/blob/75f35f558f5a9e0851c05dda85763b679d713ac1/scrapy/extensions/feedexport.py#L445

**Comment by quang-nguyen-enveda** [comment]
I'll take it to fix

**Comment by quang-sudo** [comment]
I'll take it to fix
