### ISSUE TITLE
Unable to scrape though getting 200 response code

### ISSUE THREAD

**Issue by meetyogi98** [scrapy/scrapy#4860]
### Description

I'm trying to scrape tatacliq.com. But unable to do so though getting 200 response code.

I'm using this url https://www.tatacliq.com/footwear-men-casual/c msh1311113?&icid2=regu:nav:main:mnav:m1311113:mulb:best:02:R1

When I pass this url in fetch() command of scrapy in shell it gives http status code 200. But when try to view response using view(response), it gives me page showing 404 error.

### Steps to Reproduce

1. I passed the above url to fetch()
2. Got 200 response code from scrapy
3. But when tried to view the response using view(response) it shohwed the page with 404 error

**Expected behavior:** So was expecting the whole page to show up.

**Actual behavior:** It gave me website page with 404 error

### Versions

Scrapy       : 2.3.0
lxml         : 4.5.2.0
libxml2      : 2.9.10
cssselect    : 1.1.0
parsel       : 1.6.0
w3lib        : 1.22.0
Twisted      : 20.3.0
Python       : 3.8.5 | packaged by conda-forge | (default, Aug 29 2020, 01:22:49) - [GCC 7.5.0]
pyOpenSSL    : 19.1.0 (OpenSSL 1.1.1g  21 Apr 2020)
cryptography : 3.1
Platform     : Linux-5.0.0-23-generic-x86_64-with-glibc2.10

**Comment by wRAR** [comment]
Can you please provide a correct URL?

**Comment by meetyogi98** [comment]
URL==
https://www.tatacliq.com/footwear-men-casual/c-msh1311113?&icid2=regu:nav:main:mnav:m1311113:mulb:best:02:R1

**Comment by wRAR** [comment]
As far as I can see, that message is added by JS. Scrapy cannot tell the browser to not execute JS when loading the response file so such things can happen.
Closing as this is not an issue.

**Comment by apardes** [comment]
@meetyogi98 I'm having the same issue. Were you able to find a solution?

**Comment by wRAR** [comment]
(as I said, this is *not* an issue)

**Comment by apardes** [comment]
It *is* an issue although maybe not with the scrapy library. Still I am wondering if the OP found a solution.

**Comment by wRAR** [comment]
I mean, if you are still talking about viewing the downloaded response in a JS-enabled browser and getting a locally JS-generated "not found" message is not an issue in most relevant contexts, but whatever.
