### ISSUE TITLE
Document using settings with CrawlerRunner

### ISSUE THREAD

**Issue by Lucioric2000** [scrapy/scrapy#4864]
Hello. On the Scrapy documentation, at https://doc.scrapy.org/en/latest/topics/practices.html?highlight=multiple%20spiders#running-multiple-spiders-in-the-same-process, the first example did not function with my 6-spiders project as is in the documentation:
`import scrapy
from scrapy.crawler import CrawlerProcess

class MySpider1(scrapy.Spider):
    # Your first spider definition
    ...

class MySpider2(scrapy.Spider):
    # Your second spider definition
    ...

process = CrawlerProcess()
process.crawl(MySpider1)
process.crawl(MySpider2)
process.start() # the script will block here until all crawling jobs are finished`
This example, but using my spiders, didn't work for me, I investigated the CrawlerProcess API, and saw that this class constructor has a Settings argument that, according to the documentation, is to be provided when creating when running the crawler from a script. I provided the Settings argument, using the function call get_project_settings(), so I suggest you to update the line saying:
process = CrawlerProcess()
to say
process = CrawlerProcess(call get_project_settings())
or to specify when the Spider argument needs to be provided, and when one needs not to provide, in the case of running single or multiple scripts from a string.
Also it is not clear in the documentation when one should to run configure_logging() and when not.
Best regards.

**Comment by Gallaecio** [comment]
Could you provide a [minimal, complete example](https://stackoverflow.com/help/minimal-reproducible-example) to reproduce the issue?

**Comment by Lucioric2000** [comment]
Let me trh. It was 2 years ago when I raised this issue, and the project thay I was with failed.

Enviado desde mi Samsung Mobile de Telcel
Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by wRAR** [comment]
Looks like this is just about mentioning in the docs that you may want to pass the settings explicitly as they are not loaded implicitly.

**Comment by Lucioric2000** [comment]
It should be that the issue.
Thanks.

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: Andrey Rahmatullin<mailto:notifications@github.com>
Enviado: sábado, 31 de octubre de 2020 03:19 a. m.
Para: scrapy/scrapy<mailto:scrapy@noreply.github.com>
CC: lucioric<mailto:lucioric2000@hotmail.com>; Author<mailto:author@noreply.github.com>
Asunto: Re: [scrapy/scrapy] Non-functioning multi-spider script example (#4864)


Looks like this is just about mentioning in the docs that you may want to pass the settings explicitly as they are not loaded implicitly.

**Comment by rox117** [comment]
I would like to work on this if that is ok

**Comment by Lucioric2000** [comment]
Great!

**Comment by Gallaecio** [comment]
This was already resolved by #5070, sorry for missing that.
