### ISSUE TITLE
S3 Storage Backend: Adding aws_key and aws_secret to URI does not work

### ISSUE THREAD

**Issue by jornfranke** [scrapy/scrapy#4870]
### Description

According to the documentation (https://docs.scrapy.org/en/latest/topics/feed-exports.html#s3), I can add the aws_key and the aws_secret as part of the URI in settings.py:
```
s3://aws_key:aws_secret@mybucket/path/to/export.csv
```
However, it seems Scrapy does not pick those up. Only if AWS_SECRET_KEY_ID and AWS_SECRET_ACCESS_KEY are set in settings.py it works. I also do not find evidence in the source code that this could work otherwise: https://github.com/scrapy/scrapy/blob/master/scrapy/pipelines/files.py#L79

Full example:
```
FEEDS = {
's3://aws_key:aws_secret@mybucket/data-%(name)s-%(time)s.parquet': {
        'format': 'parquet',
        'encoding': 'utf8',
        'store_empty': False,
        'item_export_kwargs': {
           'compression': 'GZIP',
           'times': 'int64',
           'hasnulls': True,
           'convertallstrings': False,
           'writeindex': False,
           'object_encoding': 'infer',
           'rowgroupoffset': 50000000,
           'items_rowgroup': 10000
        },
    }
}

```
### Steps to Reproduce
see above. I expect that the AWS secret and access key can be put in the S3 uri. This would allow export to multiple different buckets in different formats.

### Versions

Please paste here the output of executing `scrapy version --verbose` in the command line.

### Additional context

Any additional information, configuration, data or output from commands that might be necessary to reproduce or understand the issue. Please try not to include screenshots of code or the command line, paste the contents as text instead. You can use [GitHub Flavored Markdown](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) to make the text look better.

**Comment by Gallaecio** [comment]
You were looking at the wrong code, this is where that feature is implemented: https://github.com/scrapy/scrapy/blob/master/scrapy/extensions/feedexport.py#L127

So, in theory it should work. Any chance you can debug that part of the Scrapy code yourself, see what’s happening at that point? Is it possible that this is a encoding issue when setting the password in the URL?

**Comment by jornfranke** [comment]
Oh, ok thanks, I will check again.

**Comment by Gallaecio** [comment]
I believe that part of the URL needs to be percent-encoded. Maybe `urllib.quote` will do the trick.
