### ISSUE TITLE
S3 FeedStorage does not support custom S3 like storages

### ISSUE THREAD

**Issue by sriganesh040194** [scrapy/scrapy#4871]
### Description
Storage options for S3 feed storage is not exporting to custom S3 like storage as supported by image pipeline. The endpoint `botocore` trying to hit is AWS's servers and it is not respecting the endpoint set using `AWS_ENDPOINT_URL` and `AWS_REGION_NAME`

### Steps to Reproduce

1. set all the necessary parameters in `settings.py` file such as  `AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY, AWS_ENDPOINT_URL, AWS_REGION_NAME, FEED_STORAGE_S3_ACL`.

```
AWS_ACCESS_KEY_ID = 'XXXXXXXXXXXX'
AWS_SECRET_ACCESS_KEY = 'XXXXXXXXXXXXXXX'
AWS_USE_SSL = True  # or True (None by default)
AWS_VERIFY = True  # or True (None by default)
AWS_ENDPOINT_URL = 'https://example.abc.com'  <-- custom s3 like cloud
AWS_REGION_NAME = 'us-east' 
FEED_STORAGE_S3_ACL = 'private'
```
2.  Then setup feeds using
```
FEEDS = {
    's3://bucket/path/to/file-%(name)s-%(time)s.json': {
        'format': 'json',
        'encoding': 'utf8',
        'store_empty': False,
        'fields': None,
        'indent': 4,
        'item_export_kwargs': {
            'export_empty_fields': True,
        }
    }
}
```
3. ``` scrapy crawl spider```

**Expected behavior:** 
This should be able to store files to other S3 like cloud, as it does with `ImagePipeline`

**Actual behavior:**
```
DEBUG: Starting new HTTPS connection (1): bucket.s3.amazonaws.com:443 <---- I think this is the problem

Response body:
b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>InvalidAccessKeyId</Code><Message>The AWS Access Key Id you provided does not exist in our records.</Message><AWSAccessKeyId>XXXXXXXXXXXXXXXXXX</AWSAccessKeyId>

[scrapy.extensions.feedexport] ERROR: Error storing json feed (36 items) in: s3://bucket/path/to/file-spider-2020-11-04T11-19-05.json

botocore.exceptions.ClientError: An error occurred (InvalidAccessKeyId) when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
```

**Reproduces how often:** 
Always

### Versions
```
Scrapy       : 2.4.0
lxml         : 4.6.1.0
libxml2      : 2.9.10
cssselect    : 1.1.0
parsel       : 1.6.0
w3lib        : 1.22.0
Twisted      : 20.3.0
Python       : 3.7.7 (v3.7.7:d7c567b08f, Mar 10 2020, 02:56:16) - [Clang 6.0 (clang-600.0.57)]
pyOpenSSL    : 19.1.0 (OpenSSL 1.1.1h  22 Sep 2020)
cryptography : 3.2.1
Platform     : Darwin-19.6.0-x86_64-i386-64bit
```

**Comment by Gallaecio** [comment]
Indeed this seems to be implemented only for [media pipelines](https://docs.scrapy.org/en/latest/topics/media-pipeline.html) at the moment.

**Comment by sriganesh040194** [comment]
Thank you :) Would it work if I created a custom pipeline? Sorry, I am new to scrapy

**Comment by Gallaecio** [comment]
You _could_ write a pipeline that manually sends items to your S3.

A cleaner (and possibly easier) approach would be to:

1. Create a subclass of [scrapy.extensions.feedexport.S3FeedStorage](https://github.com/scrapy/scrapy/blob/master/scrapy/extensions/feedexport.py#L119) that uses `crawler.settings['AWS_ENDPOINT_URL']` where it needs to be used.
2. Point the [FEED_STORAGES](https://docs.scrapy.org/en/latest/topics/feed-exports.html#std-setting-FEED_STORAGES) setting to your subclass for S3: `FEED_STORAGES = {'s3': <your subclass>}`.

The best part of this approach is not that it’s cleaner or probably easier, but that once you get it working it would be trivial for you to send a pull request here to implement this in Scrapy itself :slightly_smiling_face:

**Comment by sriganesh040194** [comment]
That is great!! Thank you very much :) I will implement it and send a pull request.
