### ISSUE TITLE
Scrapy is slow to start the first time

### ISSUE THREAD

**Issue by NoReflex** [scrapy/scrapy#4879]
Hi,  
This is not an issue for me, but I'm really curious about why it works this way. I guess this is in general for all python apps, although it's more prominent in scrapy.  
The first time I start a scrapy spider, it took:  
```
real    0m40.704s
user    0m3.547s
sys     0m3.484s
```
Any subsequent runs took around 6 seconds:
```
real    0m6.499s
user    0m3.266s
sys     0m1.547s
```
Is some sort of caching happening here? I'm running an SSD and scrapy has around 80 spiders.

**Comment by elacuesta** [comment]
I find it very difficult to give a general answer without any knowledge of the code being run. Off the top of head, I can think about the [resuming jobs feature](https://docs.scrapy.org/en/latest/topics/jobs.html) and the [`HttpCacheMiddleware` middleware](https://docs.scrapy.org/en/latest/topics/downloader-middleware.html#module-scrapy.downloadermiddlewares.httpcache).
I suspect this is more of a support question (see [_Getting help_](https://docs.scrapy.org/en/latest/#getting-help)), but let's leave it open for now in case we find some bottleneck within the codebase. Could you provide more information?

**Comment by NoReflex** [comment]
There's a lot of things that may be at play here.
I'm running scrapy under WSL 1, there are over 80 spiders, some importing big libraries (like opencv, pandas, numpy, pdf-related, word-related, etc)  
The only thing I can figure out which directly affects scrapy, is for the crawl command to load only mentioned spider and not all spider modules.

**Comment by Gallaecio** [comment]
Any chance you can provide a reproducible example?

**Comment by wRAR** [comment]
`scrapy crawl foo` imports all spider modules because `foo` is the spider `name` attribute, not the module name. If importing your modules takes that much time we can't help with that, but you can try moving imports of heavy modules from the top level to code that only runs when the spider is used.

**Comment by GeorgeA92** [comment]
@NoReflex 

> I'm running scrapy under WSL 1

> Is some sort of caching happening here?

Probably this is result of Windows SysMain (Superfetch) service activity.
One of it's functions - is to cache the most frequently used apps into RAM.

**Comment by NoReflex** [comment]
> `scrapy crawl foo` imports all spider modules because `foo` is the spider `name` attribute, not the module name. If importing your modules takes that much time we can't help with that, but you can try moving imports of heavy modules from the top level to code that only runs when the spider is used.

Yeah, I know, but it's still possible to load single spider modules with a file caching procedure. Since we integrate scrapy with a workflow orchestration and store some metadata in the spiders, instead of loading them, we keep a cache of the metadata which is generated only when out-of-date or missing. This means we don't need to re-load all the spiders just to see the schedule of which a particular spider runs. We can also do the same by storing the path for each spider and it's name, however loading the spider modules is something deeply integrated in scrapy, and it's going to break forward compatibility since it cannot be done with a simple command.



> @NoReflex
> 
> > I'm running scrapy under WSL 1
> 
> > Is some sort of caching happening here?
> 
> Probably this is result of Windows SysMain (Superfetch) service activity.
> One of it's functions - is to cache the most frequently used apps into RAM.

I guess that answers my initial question.
