### ISSUE TITLE
Proxy Tunnel Error message length

### ISSUE THREAD

**Issue by akinad3** [scrapy/scrapy#4881]
## Summary
Proxy TunnelError message length shouldn't be truncated to 32 bytes

## Motivation
Often there might be some Proxy TunnelErrors which are currently truncated to 32 characters by these lines of code: https://github.com/scrapy/scrapy/blame/master/scrapy/core/downloader/handlers/http11.py#L170 / https://github.com/scrapy/scrapy/blame/master/scrapy/core/downloader/handlers/http11.py#L125

## Describe alternatives you've considered
Is there a legitimate reason why this should be truncated?

## Additional context
I'm getting this exception raised
`scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy zproxy.lum-superproxy.io:22225 [{'status': 502, 'reason': b'Proxy Error: server_error No pe'}]`
instead of
`scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy zproxy.lum-superproxy.io:22225 [{'status': 502, 'reason': b'Proxy Error: server_error No peers available'}]`

Tried out by removing the 32 character truncation in my specific use-case and it seems to work.

**Comment by Gallaecio** [comment]
I see no discussion in https://github.com/scrapy/scrapy/pull/2069 about the introduction of the 32 limit, so I am not 100% sure of why that value was chosen, it may have been an arbitrary choice. But I think truncating makes sense, allowing an input string of any length to get logged there may not be wise.

Maybe we could simply allow for a longer string to be logged? 64?

**Comment by akinad3** [comment]
From the logging length point of view I agree with you. I think 64 might still be a little bit short but probably much more helpful than the current limitation is.

**Comment by Bhavesh0327** [comment]
@akinad3 I don't think the length of 64 will be short for any error message here. Should I make the change?

**Comment by Gallaecio** [comment]
I agree. We can always make it larger later if a scenario where that would help is brought up.

**Comment by kmike** [comment]
For me a larger limit makes sense - what are the cases having e.g. 128 or 256 chars in a log is bad? We're not truncating many other log messages. For example, URL limit is ~4K+ (?), and we're logging all urls. Or am I misunderstanding the issue?

**Comment by Gallaecio** [comment]
I don’t mind a higher limit. 5k? 10k?

**Comment by kmike** [comment]
1K? :)
