### ISSUE TITLE
can't call custom method in class FilesPipeline

### ISSUE THREAD

**Issue by zhangyupy** [scrapy/scrapy#4885]
### Description

if  inherit FilesPipeline can not call custom method unless you don't use yield keywords

**Comment by wRAR** [comment]
Can you please explain what do you mean and show a code example?

**Comment by zhangyupy** [comment]
when i write pipleines,   

![image](https://user-images.githubusercontent.com/51393693/99878408-19f5cb80-2c40-11eb-8076-3c142e6e1977.png)

**Comment by wRAR** [comment]
Sorry, but "can't run" is not a problem description.

**Comment by zhangyupy** [comment]
my English is poor,so i gave up
