### ISSUE TITLE
[Question] scrapy custom extension not working

### ISSUE THREAD

**Issue by animesh-sharama** [scrapy/scrapy#4886]
### Description
I am trying to add a custom extension to scrapy for handling opening and closing of spider. 

### Steps to Reproduce

1. Clone the repository https://github.com/scrapy/quotesbot.git
Add extension described in the example in extensions package
```
import logging
from scrapy import signals
from scrapy.exceptions import NotConfigured

logger = logging.getLogger(__name__)

class SpiderOpenCloseLogging(object):

    def __init__(self, item_count):
        self.item_count = item_count
        self.items_scraped = 0

    @classmethod
    def from_crawler(cls, crawler):
        # first check if the extension should be enabled and raise
        # NotConfigured otherwise
        if not crawler.settings.getbool('OPEN_CLOSE_ENABLED'):
            raise NotConfigured

        # get the number of items from settings
        item_count = crawler.settings.getint('MYEXT_ITEMCOUNT', 1000)

        # instantiate the extension object
        ext = cls(item_count)

        # connect the extension object to signals
        crawler.signals.connect(ext.spider_opened, signal=signals.spider_opened)
        crawler.signals.connect(ext.spider_closed, signal=signals.spider_closed)
        crawler.signals.connect(ext.item_scraped, signal=signals.item_scraped)

        # return the extension object
        return ext

    def spider_opened(self, spider):
        logger.info("opened spider %s", spider.name)

    def spider_closed(self, spider):
        logger.info("closed spider %s", spider.name)

    def item_scraped(self, item, spider):
        self.items_scraped += 1
        if self.items_scraped % self.item_count == 0:
            logger.info("scraped %d items", self.items_scraped)
```

Enable the extension in settings.py 
```
OPEN_CLOSE_ENABLED = True
EXTENSIONS = {
    'quotesbot.extensions.spider_open_close_logging.SpiderOpenCloseLogging': 500
}
```

**Expected behavior:** [What you expect to happen]
The extension shall be invoked and it shall log. 

**Actual behavior:** [What actually happens]
The extension is not invoked and nothing is logged. 

**Reproduces how often:** [What percentage of the time does it reproduce?]
All times
### Versions
2.4.0
Please paste here the output of executing `scrapy version --verbose` in the command line.

### Additional context

Any additional information, configuration, data or output from commands that might be necessary to reproduce or understand the issue. Please try not to include screenshots of code or the command line, paste the contents as text instead. You can use [GitHub Flavored Markdown](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) to make the text look better.

**Comment by Gallaecio** [comment]
Please, check the logs (they should mention if the extension is enabled), and make sure `from_crawler` gets called (e.g. if you raise an exception from there, it should be logged). From the information you provide, this could be something as trivial as a typo in your settings.

**Comment by wRAR** [comment]
It works for me so this doesn't look like a problem in Scrapy.
