### ISSUE TITLE
I am facing almost same issue, let me give you guys idea about the pattern through which I scrape----.>>>

### ISSUE THREAD

**Issue by Crispae** [scrapy/scrapy#4891]
I am facing almost same issue, let me give you guys idea about the pattern through which I scrape----.>>>
I have only 1 URL in start_url  through which I wanted to scrape 5 URLs(Which I am getting) for different categories after entering into any  categories I have to extract data from that page ,within the same page there is pagination link and i want do do it recursively, it seems linkextractor not extracting complete link as i can't  see response for second rule.

Here is the code as, I am not able to do the pagination using rules so I manually  added some  code to recursively scrape the page.

allowed domains = []
    start_urls = ['https://tutsplus.com/']

    rules = (
        Rule(LinkExtractor(restrict_xpaths='//div[@class="home-hero__column"]/a'), callback='parse_tem'),
        # Rule(LinkExtractor(restrict_xpaths="//a[@class='pagination__button pagination__next-button']"),callback='parse_tem',),
    )

    # def parse_tem(self, response):
    #     yield scrapy.Request(url=response.url,callback=self.extractor,dont_filter=True)

    def parse_tem(self,response):
        for path in response.xpath('//li[@class="posts__post  "]/article'):
            item ={}
            item['course__name'] = path.xpath('.//header/a[2]/h1/text()').extract_first()
            item['course_link'] = path.xpath('.//header/a/@href').extract_first()
            item['description'] = path.xpath('.//div/text()').extract_first()
            yield item

        next_page = response.xpath('//a[@class="pagination__button pagination__next-button"]/@href').extract_first()
        next_url = response.urljoin(next_page)
        yield scrapy.Request(next_url,callback=self.parse_tem,dont_filter=True)

_Originally posted by @Crispae in https://github.com/scrapy/scrapy/issues/2291#issuecomment-729259336_

**Comment by elacuesta** [comment]
If I understand correctly, you're missing `follow=True` in your rule. By default, `follow` is `False` if you set a callback ([docs](https://docs.scrapy.org/en/2.4/topics/spiders.html#crawling-rules)), which prevents the response from being processed in search of further matches.
In the future, please use more descriptive titles when opening an issue. Additionally, please consider [other channels](https://docs.scrapy.org/en/2.4/index.html#getting-help) for support questions, the purpose of the GitHub issue tracker is to keep track of bug reports and feature requests.

**Comment by Crispae** [comment]
gottcha! I am little bit confused about the working of rules, suppose I have given 1 url in start_urls which is home page and in rule section  I have two rules the first will have to fetch different urls of category from homepage(The first url) and in second rule it have to fetch the nextpage link from the page it is browsing currently. In which order the rules are executing after scraping the rules from first page is it move to second rule or is it still following the same rule, as i have already studied the documentation it will very nice of you if you will explain this.

> If I understand correctly, you're missing `follow=True` in your rule. By default, `follow` is `False` if you set a callback ([docs](https://docs.scrapy.org/en/2.4/topics/spiders.html#crawling-rules)), which prevents the response from being processed in search of further matches.
> In the future, please use more descriptive titles when opening an issue. Additionally, please consider [other channels](https://docs.scrapy.org/en/2.4/index.html#getting-help) for support questions, the purpose of the GitHub issue tracker is to keep track of bug reports and feature requests.





gottcha! I am little bit confused about the working of rules, suppose I have given 1 url in start_urls which is home page and in rule section  I have two rules the first will have to fetch different urls of category from homepage(The first url) and in second rule it have to fetch the nextpage link from the page it is browsing currently. In which order the rules are executing after scraping the rules from first page is it move to second rule or is it still following the same rule, as i have already studied the documentation it will very nice of you if you will explain this. Thankyou

**Comment by elacuesta** [comment]
From [the docs](https://docs.scrapy.org/en/latest/topics/spiders.html#scrapy.spiders.CrawlSpider.rules):
> If multiple rules match the same link, the first one will be used, according to the order they’re defined in this attribute.

So if your first rule matches categories and the second one matches pagination, only the categories will be extracted. The code you posted initially (following pagination within the callback) is a perfectly valid alternative. One common practice I've seen over time is stubbornly trying to fit the `CrawlSpider` to a use case for which it is just not the best solution. A `CrawlSpider` is better that a regular `Spider` for _some_ cases, but not for all of them.
