### ISSUE TITLE
Update all links in installation guide

### ISSUE THREAD

**Issue by AKSHAYSHARMAJS** [scrapy/scrapy#4892]
Some of the links like [cryptography installation](https://cryptography.io/en/latest/installation/) in file `install.rst` are outdated and require an update. 
It will be nice to check for other parts of the documentation for the same issue.

**Comment by mehrdadep** [comment]
I will do it, Assign it to me please.

**Comment by mehrdadep** [comment]
`scarpy` only have pages in [community-staging](https://www.archlinux.org/packages/community-staging/any/scrapy/) and [community](https://www.archlinux.org/packages/community/any/scrapy/) on [archlinux](https://www.archlinux.org/), so this is also invalid `.. _AUR Scrapy package: https://aur.archlinux.org/packages/scrapy/`

**Comment by Joe-Sin7h** [comment]
Can i get assigned to This issue @Gallaecio

**Comment by Gallaecio** [comment]
There’s already https://github.com/scrapy/scrapy/pull/4899
