### ISSUE TITLE
SSLError(MaxRetryError('HTTPSConnectionPool(host=\'www.xinhuanet.com\', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError("bad handshake: Error([(\'SSL routines\', \'ssl3_read_bytes\', \'sslv3 alert handshake failure\')])")))'))

### ISSUE THREAD

**Issue by th98lab** [scrapy/scrapy#4904]
#! /usr/bin/env python
# -*- coding: utf-8 -*-
"""
Get Certificates from a request and dump them.
"""
import OpenSSL
from OpenSSL import SSL, crypto
import ssl
import socket
import sys
import requests
from requests.packages.urllib3.exceptions import InsecureRequestWarning
import datetime
from pprint import pprint
import json
import ast
import pem
import Root
import itertools

requests.packages.urllib3.disable_warnings(InsecureRequestWarning)

"""
Inspired by the answers from this Stackoverflow question:
https://stackoverflow.com/questions/16903528/how-to-get-response-ssl-certificate-from-requests-in-python

What follows is a series of patching the low level libraries in requests.
"""

"""
https://stackoverflow.com/a/47931103/622276
"""
def _convert(dict_data):
    data=dict()
    for r in dict_data:
        try:
            k=r.decode('utf-8')
        except:
            k=r
        try:
            data[k]=dict_data[r].decode('utf-8')
        except:
            data[k]=dict_data[r]
    return data

def certi_chain(context,hostname):
    l=0
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock = SSL.Connection(context=context, socket=sock)
    sock.settimeout(10)
    sock.connect((hostname, 443))
    sock.setblocking(1)
    sock.do_handshake()
    chain= sock.get_peer_cert_chain()
    l=len(chain)
    #f=open(str(hostname)+'.json','w')
    for (idx, cert) in enumerate(chain):
        result=dump_pem(cert)
        final[str(idx)]=result
    #pprint(final)
    #f.write(json.dumps(final)+'\n')
    #print('Done!!')
    #f.close() 
    sock.shutdown()
    sock.close()
    return final,l
def make_context():
    context = SSL.Context(method=SSL.TLSv1_METHOD)
    for bundle in [requests.certs.where(), r'C:\Program Files\OpenSSL-Win64\bin\PEM\cacert.pem']:
        context.load_verify_locations(cafile=bundle)
    return context
sock_requests = requests.packages.urllib3.contrib.pyopenssl.WrappedSocket

def new_getpeercertchain(self, *args, **kwargs):
    x509 = self.connection.get_peer_cert_chain()
    return x509

sock_requests.getpeercertchain = new_getpeercertchain

"""
https://stackoverflow.com/a/16904808/622276
"""

HTTPResponse = requests.packages.urllib3.response.HTTPResponse
orig_HTTPResponse__init__ = HTTPResponse.__init__

def new_HTTPResponse__init__(self, *args, **kwargs):
    orig_HTTPResponse__init__(self, *args, **kwargs)
    try:
        self.peercertchain = self._connection.sock.getpeercertchain()
    except AttributeError:
        pass

HTTPResponse.__init__ = new_HTTPResponse__init__

HTTPAdapter = requests.adapters.HTTPAdapter
orig_HTTPAdapter_build_response = HTTPAdapter.build_response

def new_HTTPAdapter_build_response(self, request, resp):
    response = orig_HTTPAdapter_build_response(self, request, resp)
    try:
        response.peercertchain = resp.peercertchain
    except AttributeError:
        pass
    return response

HTTPAdapter.build_response = new_HTTPAdapter_build_response

"""
Attempt to wrap in a somewhat usable CLI
"""

'''def cli(args):
    parser = argparse.ArgumentParser(description="Request any URL and dump the certificate chain")
    parser.add_argument("url", metavar="URL", type=str, nargs=1, help="Valid https URL to be handled by requests")

    verify_parser = parser.add_mutually_exclusive_group(required=False)
    verify_parser.add_argument("--verify", dest="verify", action="store_true", help="Explicitly set SSL verification")
    verify_parser.add_argument(
        "--no-verify", dest="verify", action="store_false", help="Explicitly disable SSL verification"
    )
    parser.set_defaults(verify=True)

    return vars(parser.parse_args(args))'''

def dump_pem(x509):
    """Use the CN to dump certificate to PEM format"""
    '''PyOpenSSL = requests.packages.urllib3.contrib.pyopenssl
    pem_data = PyOpenSSL.OpenSSL.crypto.dump_certificate(PyOpenSSL.OpenSSL.crypto.FILETYPE_PEM, cert)
    #issuer = cert.get_issuer().get_components()'''
    result = {
        'subject': dict(x509.get_subject().get_components()),
        'issuer': dict(x509.get_issuer().get_components()),
        'serialNumber': x509.get_serial_number(),
        'version': x509.get_version(),
        'Signature': x509.get_signature_algorithm().decode('utf-8'),
        'notBefore': '{}'.format(datetime.datetime.strptime(x509.get_notBefore().decode('utf-8'),'%Y%m%d%H%M%SZ')),
        'notAfter': '{}'.format(datetime.datetime.strptime(x509.get_notAfter().decode('utf-8'),'%Y%m%d%H%M%SZ'))
    }
    try:
        extensions = (x509.get_extension(i) for i in range(x509.get_extension_count()))
        extension = {e.get_short_name(): str(e) for e in extensions}
        extension_data=dict()
        extension_data=_convert(extension)
        result.update(extension_data)
    except:
        pass
    result1={}
    for r in result.keys():
        
        if (r=='subject') or (r=='issuer'):
            result1[r]=_convert(result[r])
            
        else:
            result1[r]=result[r]
    
    return result1

if __name__ == "__main__":
    final=dict()
    url='xinhuanet.com'
    #t=url.pop(0)
    #req = requests.get('https://www.'+url, verify=True)
    f=open(url+'.json','w')
    l=0
    #res=Root.add_rootCA()
    
    try:
        try:
            
            print('case-1')
            req = requests.get('https://www.'+url, verify=True)
            chain=req.peercertchain
            l=len(chain)
            for (idx, cert) in enumerate(chain):
                result=dump_pem(cert)
                final[str(idx)]=result
            pprint(final)
            print('Done-case1')
        except Exception as error:
            print('caught this error:'+ repr(error))
    except:
        try:
            
            print('case-2')
            cert = ssl.get_server_certificate((url, 443))
            cert = OpenSSL.crypto.load_certificate(OpenSSL.crypto.FILETYPE_PEM, cert)
            context = make_context()
            final,l=certi_chain(context,'www.'+url)
            print(l)
            pprint(final)
            print('Done-case2')
        except Exception as error:
            print('caught this error:'+ repr(error))
    finally:
        
        if(l!=0):
            print('Entering')
            print(l)
            res=Root.add_rootCA()
            k=final[str(l-1)]
            pprint(k)
            xy=k['issuer']
            yz=k['subject']
                    
            if(xy==yz):
                #pprint(final)
                f.write(json.dumps(final)+'\n')
                f.close()
                print('Done-finally!!')    
            else:
                
                for x in res.keys():
                    min=1 if(ast.literal_eval(x)==xy) else 0
                    print(min)
                    if(min==1):
                        final[str(l)]=res[x]
                        #pprint(final)
                        f.write(json.dumps(final)+'\n')
                        f.close()
                        print('Done-finally!!')
                        break
        else:
            print('No CErtificate')

    #print('DONE!!')
    #pprint(final)

**Comment by elacuesta** [comment]
Please, do not post a 230+ lines long script without any context. Instead, create a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that would help other users to understand the issue.
Furthermore, there is no mention of `scrapy` within the posted code.
