### ISSUE TITLE
Typo in XML exporter serialize_field in Scrapy docs

### ISSUE THREAD

**Issue by Crank1d** [scrapy/scrapy#4907]
Im using code from Scrapy documentation - https://docs.scrapy.org/en/latest/topics/exporters.html, with "Product" class item created
```
from scrapy.exporter import XmlItemExporter

class ProductXmlExporter(XmlItemExporter):

    def serialize_field(self, field, name, value):
        if field == 'price':
            return f'$ {str(value)}'
        return super(Product, self).serialize_field(field, name, value)

```
and always get error from command line

**return super(Product, self).serialize_field(field, name, value)
TypeError: super(Product, obj): obj must be an instance or subtype of type**

Im relatively new to Python, but AFAIK, super function cannot accept Product class, it should be ProductXmlExporter, but when I change it, nothing happens to "price" field in XML export file.

**Comment by Joe-Sin7h** [comment]
I would like to work on this issue , can i get assigned ?
@wRAR

**Comment by wRAR** [comment]
@Joe-Sin7h you don't need to "get assigned" to do work.

**Comment by etimoz** [comment]
https://github.com/scrapy/scrapy/pull/4909
