### ISSUE TITLE
RaiseSpider Exception may not close current db connection

### ISSUE THREAD

**Issue by duynguyen0511** [scrapy/scrapy#491]
It is just a theory I derived from a high aborted clients stats when i schedule to have 200 spiders running via scrapyd.

Full explanation/description is posted on Stackoverflow ( http://stackoverflow.com/questions/20647382/scrapyd-schedule-200-spiders-cause-massive-mysql-aborted-clients ) and on Scrapy user group (https://groups.google.com/forum/#!topic/scrapy-users/HEaXJT3d4iQ)

**Comment by redapple** [comment]
@duynguyen0511 , I'm closing this as this looks like a problem on the handling of idel MySQL connections, something Scrapy does not oversee.
It's the job of your custom pipeline code (it does not mean it's easy to get right though).
