### ISSUE TITLE
Shell fetch does not use http_proxy

### ISSUE THREAD

**Issue by matsievskiysv** [scrapy/scrapy#4920]
### Description

When in shell mode,`fetch` function does not use proxy.

### Steps to Reproduce

1. `http_proxy=127.0.0.1:8118 scrapy shell -L WARN ident.me`
2. `print(response.body)`. It should show your proxy IP
3. `fetch('https://ident.me')`
3. `print(response.body)`. It should show your real IP

**Expected behavior:**
All outgoing connections should use `http_proxy`

**Actual behavior:**
`fetch` does not use `http_proxy`

**Reproduces how often:**

Always

### Versions

```
Scrapy       : 2.4.1
lxml         : 4.6.2.0
libxml2      : 2.9.10
cssselect    : 1.1.0
parsel       : 1.6.0
w3lib        : 1.22.0
Twisted      : 20.3.0
Python       : 3.9.1 (default, Dec  8 2020, 07:51:42) - [GCC 10.2.0]
pyOpenSSL    : 19.1.0 (OpenSSL 1.1.1h  22 Sep 2020)
cryptography : 3.2.1
Platform     : Linux-5.9.0-4-amd64-x86_64-with-glibc2.31
```

**Comment by nyov** [comment]
When you crawled `scrapy shell -L WARN ident.me` it connected to `http://ident.me`.
Then when you ran `fetch('https://ident.me')`, scrapy connected to http*s*://ident.me - and then you need to set the `https_proxy` variable!

Try with `http_proxy=127.0.0.1:8118 https_proxy=127.0.0.1:8118 no_proxy= scrapy shell -L WARN 'https://ident.me'`.

Works for me.
