### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by lolobosse** [scrapy/scrapy#4929]
### Description

I get an SSL error on a [working website](https://akut-international.com/). The error is the following: `<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', 'ssl3_read_bytes', 'sslv3 alert handshake failure')]>`

### Steps to Reproduce

Just execute

`scrapy shell https://akut-international.com/`

**Expected behavior:** HTML should return

**Actual behavior:** SSL Error 

**Reproduces how often:** 100%

### Versions

```
Scrapy       : 2.4.1
lxml         : 4.1.1.0
libxml2      : 2.9.7
cssselect    : 1.0.3
parsel       : 1.5.0
w3lib        : 1.19.0
Twisted      : 17.9.0
Python       : 3.6.9 (default, Oct  8 2020, 12:12:24) - [GCC 8.4.0]
pyOpenSSL    : 20.0.1 (OpenSSL 1.1.1i  8 Dec 2020)
cryptography : 3.3.1
Platform     : Linux-5.4.0-58-generic-x86_64-with-Ubuntu-18.04-bionic
```

### Additional context

I tried many additional verifications:

 - ` openssl s_client -connect akut-international.com:443 -servername  akut-international.com` -> returns a working handshake
 - I updated scrapy (see the version I used)
 - It work with `requests`.
 - I have the same issue with: 
 ```
Scrapy       : 1.5.0
lxml         : 4.1.1.0
libxml2      : 2.9.7
cssselect    : 1.0.3
parsel       : 1.4.0
w3lib        : 1.19.0
Twisted      : 17.9.0
Python       : 3.6.12 (default, Aug 17 2020, 23:45:20) - [GCC 9.3.0]
pyOpenSSL    : 17.5.0 (OpenSSL 1.1.0g  2 Nov 2017)
cryptography : 2.1.4
Platform     : Linux-5.4.0-58-generic-x86_64-with-Ubuntu-20.04-focal
```

Is that a not working combination? You can test on the website; you should come to the same conclusion as me

**Comment by wRAR** [comment]
This works here.

> see the version I used

Where?

**Comment by lolobosse** [comment]
Hey, 

Thank for your time! Sorry the markdown formatting removed the first lines of my code...

I updated my original issue (Scrapy 1.5.0 and scrapy 2.4.1).

Could you please give the version numbers that you're using so that I can test it out too? :pray:

**Comment by wRAR** [comment]
Actually, it works with Twisted 18.4.0 (and later) but doesn't with 17.9.0.

**Comment by lolobosse** [comment]
Confirmed, works with 18.4.0. 

It solves my problem but you might to change some line here: https://github.com/scrapy/scrapy/blob/master/setup.py#L22 :smile:

**Comment by Gallaecio** [comment]
> It solves my problem but you might to change some line here: https://github.com/scrapy/scrapy/blob/master/setup.py#L22

Not really, that should be the lowest Twisted version Scrapy supports, and it remains the same.

We _could_ cover this issue somewhere in the documentation, but I’m hoping people will easily find this issue from now on, and that will serve as documentation enough.

**Comment by wRAR** [comment]
We no longer support Twisted 17.9.0.
