### ISSUE TITLE
can't store the scraped data with command `-o result.jl`

### ISSUE THREAD

**Issue by hnljq** [scrapy/scrapy#4930]
I have post the question on stackoverflow, but seem no one can answer the question.
I attempt to store the scrapyed data whih command `-o result.jl ` , but failed.  
I can see the item result in console log of scrapy , and the scrapy stats `item_scraped_count`  is 1 .
scrapy version 2.4.0 and 2.4.1  tried too . 
[stackoverflow](https://stackoverflow.com/questions/65340653/scrapy-doesnt-save-data-file-through-command-line-tool-output-result-jl/65340692#65340692)

**Comment by wRAR** [comment]
This is a tracker for issues in Scrapy itself so unless you think there is a bug in Scrapy itself please don't use it for questions about your code.
