### ISSUE TITLE
warn_on_generator_with_return_value IndentationError failure

### ISSUE THREAD

**Issue by nyov** [scrapy/scrapy#4931]
`<!--

Thanks for taking an interest in Scrapy! `yahnoproblem`
`deletedeletedeletedeletedeletedelete`
with respect:`deletedeletedeletedeletedelete`

The following is a suggested template `oh ilove templates, fill me in`

### Description

The `warn_on_generator_with_return_value` function fails to correctly dedent (supposedly) spider code and breaks with bogus `IndentationError`. If I remove a (correctly indented) comment block at some part of the code, or comment out a method, the error stops happening.

This happened after I upgraded scrapy in a project (obv. `warn_on_generator_with_return_value` is new).
I've been too lazy to track this down and find an MWE for it, sorry. I can't really tell what triggers the issue. The spider code is split across various files and classes and has various comment blocks. Also, indents are tabs in those files, in case that matters (and no, no spaces mixing, I checked lots).

I just removed the line in `scraper.py` and now it's fixed ^^
https://github.com/scrapy/scrapy/blob/d0af0086085741cb2580b8231f31cbad44a73cf5/scrapy/core/scraper.py#L149

Slightly anonymoused log (can you tell?):
```py
2020-20-20 20:20:20 [scrapy.core.engine] INFO: Spider opened
2020-20-20 20:20:20 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2020-20-20 20:20:20 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.xxx.yyy/> (referer: None)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: <200 https://www.xxx.yyy/>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scrapy.git/scrapy/utils/defer.py", line 55, in mustbe_deferred
    result = f(*args, **kw)
  File "scrapy.git/scrapy/core/spidermw.py", line 58, in process_spider_input
    return scrape_func(response, request, spider)
  File "scrapy.git/scrapy/core/scraper.py", line 149, in call_spider
    warn_on_generator_with_return_value(spider, callback)
  File "scrapy.git/scrapy/utils/misc.py", line 245, in warn_on_generator_with_return_value
    if is_generator_with_return_value(callable):
  File "scrapy.git/scrapy/utils/misc.py", line 230, in is_generator_with_return_value
    tree = ast.parse(dedent(inspect.getsource(callable)))
  File "/usr/lib/python3.7/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    def parse_some_page(self, response):
    ^
IndentationError: unexpected indent
2020-20-20 20:20:20 [scrapy.core.engine] INFO: Closing spider (finished)
2020-20-20 20:20:20 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
```

Funny: `def parse_some_page()` is defined in a `MySpider()` superclass, in a different file elsewhere. But the error seems to be fixed by removing a (multiline) comment block in the Spider class; or commenting out an existing method there!? `¯\_(ツ)_/¯`

I won't pretend to know first thing about `ast`, but I think `dedent()` is totally sus. 🤔

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]
4. [grow up some more]
5. start computer
6. wait for loading screen
7. log into windows
8. palm face
9. reboot computer
10. log into linux
11. make scrapy project
12. do warranty-voiding stuff to it
13. hope for sparks

**Expected behavior:** [What you expect to happen]

much breakage. explosions 'n stuff.

**Actual behavior:** [What actually happens]

only slight breakage, very disappointing.

**Reproduces how often:** [What percentage of the time does it reproduce?]

it doesn't. 🔍🤪
totally neutered it

### Versions

Please paste here the output of executing `scrapy version --verbose` in the command line.

```
Scrapy       : 2.4.1
lxml         : █.█.█.█
libxml2      : █.█.█
cssselect    : █.0.█
parsel       : █.█.0
w3lib        : █.2█.0
Twisted      : 18.9.█
Python       : █.7.█ (de█aul████████████2█, ██:██:██) - ██CC ██3.0]
pyOpenSSL    : 1█.0.0 (████SSL █████d  1████p████9)
cryptography : 2.███
Platform     : Li█ux-9.█.1-██████-x86_128-with-█orld-d█min█ti█n-patch-1█.4

unessential information blacked out for unnational security reasons
```

### Additional context

Any additional information, configuration, data or output from commands that might be necessary to reproduce or understand the issue. Please try not to include screenshots of code or the command line, paste the contents as text instead. You can use [GitHub Flavored Markdown](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) to make the text look better. Emojis also help 😋 🤭 🤗 and merry bug-free xmas everyone 🎄

**Comment by elacuesta** [comment]
Hey @nyov, could this be related to #4477?

**Comment by nyov** [comment]
@elacuesta, oh that's definitely related. How didn't I see this? Mysteries. Don't be so cautious, just close the issue 😝

So removing multi-line comments cures it for me. But the error message is very unhelpful for debugging.

Since the issue doesn't have a definitive fix yet, could the `IndentationError`s there be caught and made more helpful in the meantime? Well, probably not worth the time to do that.

What patch are you talking about? I know nothing. 😂
