### ISSUE TITLE
Cannot extract the <p> or text content using xpath extract() function

### ISSUE THREAD

**Issue by dickchanym** [scrapy/scrapy#4941]
### Description
x.path parse can crawl all data if `<p>` is found within the xpath tag. Try to crawl data from response.xpath function. All `<p>` or text contents are skipped.  For example:

**Original Data (expected result):**
```
<h3 class="faq">
    <span class="faq_index">
        span here
    </span>
    <p>line 1</p>
    <p>line 2</p>
    line 3
</h3>
```

**Data returned from xpath extract():**
```
<h3 class="faq">
    <span class="faq_index">
        span here
    </span>
</h3>

```
### Steps to Reproduce

1. Start scrapy shell with following website:
`scrapy shell https://www.sfc.hk/en/faqs/intermediaries/supervision/Code-of-Conduct/16-Jul-2001---Code-of-Conduct
`
2. in scrapy shell, run 
   `response.xpath('//h3[contains(@class, "sfc-faq")]').extract()[61]`

**Expected behavior:** [What you expect to happen]
```
        <h3 class="fs-accordion sfc-faq-q fs-accordion--faq" id="A8683AAE920747C18D3FEFE808D884AF" >
            <span class="faq_index">
                Q34:
            </span>
            Is it possible under <strong>para. 7.1 </strong>for a client to give discretion to his relative to operate his account without involving the company when that relative is an employee of the company?
        </h3>
```
**Actual behavior:** [What actually happens]
```
<h3 class="fs-accordion sfc-faq-q fs-accordion--faq" id="5AC24A60030D407CA617FF913A09790E">\r\n            <span class="faq_index">\r\n                Q62:\r\n            </span>\r\n            </h3>
```
**Reproduces how often:** [What percentage of the time does it reproduce?]
Can reproduces anytime.

### Versions
```
SFC FAQ links:
['https://www.sfc.hk/en/faqs/intermediaries/supervision/Code-of-Conduct/16-Jul-2001---Code-of-Conduct']

Scrapy       : 2.4.1
lxml         : 4.6.2.0
libxml2      : 2.9.10
cssselect    : 1.1.0
parsel       : 1.6.0
w3lib        : 1.22.0
Twisted      : 20.3.0
Python       : 3.6.9 (default, Oct  8 2020, 12:12:24) - [GCC 8.4.0]
pyOpenSSL    : 20.0.1 (OpenSSL 1.1.1i  8 Dec 2020)
cryptography : 3.3.1
Platform     : Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-Ubuntu-18.04-bionic

```

**Comment by wRAR** [comment]
A block element (`p`) inside an inline one (`h3`) is invalid HTML so lxml reshuffles elements, putting `p` after `h3`. Probably the easiest way to fix this would be adjusting the XPath you use.
