### ISSUE TITLE
Google Summer of Code 2021

### ISSUE THREAD

**Issue by Gallaecio** [scrapy/scrapy#4959]
This is a ticket to handle student questions and feedback regarding the 2021 edition of Google Summer of Code, where Scrapy participates again this year: https://gsoc2021.zyte.com/

**Comment by ayan-biswas0412** [comment]
@Gallaecio What type of projects will be available , actually I am an aspirant of GSOC 2021 for this year and I am working in the Web Dev domain for the past several years and highly skilled In MERN and MEAN stack , Is there any active issues available in any repository for some initial working ? Thanking you in advance.

**Comment by Gallaecio** [comment]
Sadly, I don’t think we have much on the web development front.

**Comment by ayan-biswas0412** [comment]
> Sadly, I don’t think we have much on the web development front.

thank you for your kind reply

**Comment by deepakdinesh1123** [comment]
For python Dev's?

**Comment by Gallaecio** [comment]
@deepakdinesh1123 Definitely, [ours are all Python projects](https://gsoc2021.zyte.com/projects).

**Comment by Gallaecio** [comment]
Some answers to questions I got by email:

> Do you have any preference for the ideas?

Everything else being equal, we prefer student applications for ideas that are harder to implement. However, the quality of the pre-application pull request, the quality of the student application, and the availability of mentors, all weight more than the idea itself. Going for the hardest idea may not help you. We recommend you to choose an idea you find doable and interesting.

> Can you redirect me to some beginner-friendly issues in Scrapy which you think would enhance my GSoC application?

https://gsoc2021.zyte.com/participate#pre-application-pull-request addresses this.

Among other things, it suggests looking at https://github.com/scrapy/scrapy/contribute. Mind, however, that Scrapy is a rather popular project, and issues that we mark as `good-first-issue` do not tend to last long without  a pull request that addresses them.

**Comment by Gallaecio** [comment]
Closing, [time for a new Google Summer of Code edition](https://github.com/scrapy/scrapy/issues/5408)!
