### ISSUE TITLE
Json object are not delimited and not within array using JsonLinesItemExporter

### ISSUE THREAD

**Issue by chipzzz** [scrapy/scrapy#4960]
I have something like this using `JsonLinesItemExporter(f, encoding='utf-8')` and exporting to s3. It's all fine however I am expecting my json objects to be within an array and separated by a comma, as such:

```
[
{"object_1: {"foo": "blah"} },
{"object_2: {"foo": "blah"} }
]
```

However, I am not seeing them within an array,  and no comma

```
{"object_1: {"foo": "blah"} }
{"object_2: {"foo": "blah"} }
```

```
def _make_fileobj(self):
        """
        Build file object from items.
        """

        bio = BytesIO()
        f = gzip.GzipFile(mode='wb', fileobj=bio) if self.use_gzip else bio

        # Build file object using ItemExporter
        exporter = JsonLinesItemExporter(f, encoding='utf-8')
        exporter.start_exporting()
        for item in self.chunk_items:
            exporter.export_item(item)
        exporter.finish_exporting()

        if f is not bio:
            f.close()  # Close the file if GzipFile

        # Seek to the top of file to be read later
        bio.seek(0)

        return bio
```
Not sure if it matters but I am pass the partially completed object via splash request into another parse and rebuilding it and adding appending more detials.

```
original parse
l = ItemLoader(item=Product(), selector=product)

Within extra Splash request

meta={ 'loader': l.load_item()},

Then in outside parse:

l2 = ItemLoader(item=response.meta['loader'], selector=jsonresponse2)

then finally yielding
yield l2.load_item()
```

locally running
`
scrapy crawl product-menu-crawler -a menu_sites=info.json -a lua_script=crawlera_script.lua -s FEED_URI='test.json' -s FEED_FORMAT=json`

the format is correct and json objects are presented wtihin array and delimited

**Comment by wRAR** [comment]
Sure, JSON lines implies having one JSON object per line.
