### ISSUE TITLE
FEED_URI_PARAMS: custom params throws KeyError

### ISSUE THREAD

**Issue by jas0nkim** [scrapy/scrapy#4962]
### Description

With Scrapy version 2.4.1, any custom feed uri params (FEED_URI_PARAMS) throws KeyError. 

### Steps to Reproduce

1. on myproject/settings.py
FEED_URI_PARAMS = 'myproject.utils.uri_params'

2. on myproject/utils.py
def uri_params(params, spider):
    return {**params, 'spider_name': spider.name}

3. scrapy crawl <spider_name> -o "%(spider_name)s.jl"

**Expected behavior:** Should export the items to a jsonline file having the spider name.

**Actual behavior:**
ERROR: Error caught on signal handler: <bound method FeedExporter.open_spider of <scrapy.extensions.feedexport.FeedExporter object at 0x7fc68cb20bb0>>
Traceback (most recent call last):
  File "/PROJECT_ROOT/.venv/lib/python3.8/site-packages/scrapy/utils/defer.py", line 157, in maybeDeferred_coro
    result = f(*args, **kw)
  File "/PROJECT_ROOT/.venv/lib/python3.8/site-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
  File "/PROJECT_ROOT/.venv/lib/python3.8/site-packages/scrapy/extensions/feedexport.py", line 294, in open_spider
    uri=uri % uri_params,
KeyError: 'spider_name'

**Reproduces how often:** Everytime

### Versions
Scrapy       : 2.4.1
lxml         : 4.6.1.0
libxml2      : 2.9.10
cssselect    : 1.1.0
parsel       : 1.6.0
w3lib        : 1.22.0
Twisted      : 20.3.0
Python       : 3.8.5 (default, Jul 28 2020, 12:59:40) - [GCC 9.3.0]
pyOpenSSL    : 19.1.0 (OpenSSL 1.1.1h  22 Sep 2020)
cryptography : 3.2.1
Platform     : Linux-4.19.104-microsoft-standard-x86_64-with-glibc2.29

### Additional context

on line 480 in /scrapy/extensions/feedexport.py,
**returns params** should be changed to **return uripar_function(params, spider)**

**Comment by Gallaecio** [comment]
> on line 480 in /scrapy/extensions/feedexport.py,
> returns params should be changed to return uripar_function(params, spider)

Indeed:

https://github.com/scrapy/scrapy/blob/85604e1078b927c2a875040e29c58b4594c8d386/scrapy/extensions/feedexport.py#L487-L488

For your specific use case, though, I _think_ you can just use `%(name)s`, based on these lines above: https://github.com/scrapy/scrapy/blob/85604e1078b927c2a875040e29c58b4594c8d386/scrapy/extensions/feedexport.py#L480-L481

**Comment by jas0nkim** [comment]
Yes, %(name)s was my workaround solution. Thanks for your comment, Gallaecio.

**Comment by inspurwusixuan** [comment]
Hi @jas0nkim @Gallaecio,

I'm new here.  Can I take this issue? :)

**Comment by Gallaecio** [comment]
@inspurwusixuan Please go ahead.

**Comment by larue-jordan** [comment]
Is this issue still available?

**Comment by Gallaecio** [comment]
Not really, there is already a pull request, https://github.com/scrapy/scrapy/pull/4966, which only needs 1 more maintainer review before being merged.

**Comment by larue-jordan** [comment]
Ok.  Do you know if there is currently an issue that is available that I might be able to contribute to as a first time open source developer?

**Comment by Gallaecio** [comment]
We run out of good first issues quite quickly, and I’m not sure we have anything like that open at the moment :expressionless:

**Comment by larue-jordan** [comment]
Ok. Thank you
