### ISSUE TITLE
Fix and document asyncio reactor problems on Windows

### ISSUE THREAD

**Issue by wRAR** [scrapy/scrapy#4976]
As described in https://twistedmatrix.com/trac/ticket/9766 you cannot just enable AsyncioSelectorReactor on Windows with recent Python, you either need fixed Twisted (which is not released yet, the merged fix is https://github.com/twisted/twisted/pull/1338) or, supposedly, add some manual fix as documented [here](https://github.com/twisted/twisted/blob/09b96850c2ebcb635f448ed3f9bbf5f157be3693/src/twisted/internet/asyncioreactor.py#L35-L44). So if it's possible to add this code to Scrapy we should probably do that, at least until the next Twisted release, and even after it we should document that new enough Twisted is needed in this use case.

**Comment by ivanprado** [comment]
This project https://github.com/ivanprado/scrapy-autoextract-demo can be used to reproduce the issue in Windows with Python 3.8. There is a workaround for the problem. Invoking:

```py
import asyncio
asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
```

fixes the problem (uncomment these lines to try it: https://github.com/ivanprado/scrapy-autoextract-demo/blob/main/scrapy_autoextract_demo/settings.py#L4-L5).

The workaround is suggested in Twisted master: https://github.com/twisted/twisted/blob/trunk/src/twisted/internet/asyncioreactor.py#L35-L44

I don't think Twisted introduced a fix for the problem itself: even after a future Twisted release, it will be required to run the lines above to make it work. So I suggest the following options. Either:
* document the workaround in https://docs.scrapy.org/en/latest/topics/asyncio.html
* or implement some code in Scrapy that automatically invoke this lines on Windows + Python 3.8

**Comment by Gallaecio** [comment]
Unless there is a good reason not to, I would try to fix this on our side.

**Comment by LeMoussel** [comment]
Couldn't resolve with the fix @ivanprado mentioned.

**Comment by wRAR** [comment]
@LeMoussel please provide a minimal reproducible example of this.

**Comment by LeMoussel** [comment]
```
import asyncio
asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())

import scrapy
import playwright

class MinimalSpider(scrapy.Spider):
    name = "minimalspider"
    custom_settings = {
        'TWISTED_REACTOR': "twisted.internet.asyncioreactor.AsyncioSelectorReactor",
        'DOWNLOAD_HANDLERS': {
            "http": "scrapy_playwright.handler.ScrapyPlaywrightDownloadHandler",
            "https": "scrapy_playwright.handler.ScrapyPlaywrightDownloadHandler",
        },
        'PLAYWRIGHT_BROWSER_TYPE': 'firefox',
        'PLAYWRIGHT_LAUNCH_OPTIONS': {
            'headless' : False
        }
    }

    def start_requests(self):
        yield scrapy.Request(
                url="https://www.zyte.com/blog/", 
                #url="https://toscrape.com", 
                callback=self.parse_item,
                errback=self.errback,
                meta={"playwright": True, "playwright_include_page": True},
        )

    async def parse_item(self, response):
        page = response.meta["playwright_page"]
        title = await page.title()
        await page.close()
        self.logger.info(f"{response.url} Title: {title} Download latency: {response.meta['download_latency']} sec.")

    def errback(self, failure):
        self.logger.error(failure)
```       
**Execution:** `scrapy runspider minimalspider.py`

**Got Exception:** `The installed reactor (twisted.internet.selectreactor.SelectReactor) does not match the requested one (twisted.internet.asyncioreactor.AsyncioSelectorReactor)`

**Scrapy Log:** [scrapy_error.log](https://github.com/scrapy/scrapy/files/7460823/scrapy_error.log)

**Comment by wRAR** [comment]
You cannot put `TWISTED_REACTOR` in the spider custom settings, as the reactor is initialized early.

**Comment by wRAR** [comment]
Depends on how you run your spider. It's possible that there is no good solution for `runspider` but I haven't thought about this, and for other ways just use the normal ways of configuring global settings.

**Comment by LeMoussel** [comment]
I make  [Scrapy minimal project](https://github.com/scrapy/scrapy/files/7461087/scrapy.zip) with the file structure, similar to this:
```
scrapy.cfg
minimal/
    __init__.py
    settings.py
    spiders/
        __init__.py
        minimalspider.py
```
I have no more errors but unfortunately no results. It seems to loop with `IocpProactor` ....
```2021-11-02 14:35:13 [scrapy.utils.log] INFO: Scrapy 2.5.0 started (bot: scrapybot)
2021-11-02 14:35:13 [scrapy.utils.log] INFO: Versions: lxml 4.5.2.0, libxml2 2.9.5, cssselect 1.1.0, parsel 1.6.0, w3lib 1.22.0, Twisted 20.3.0, Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)], pyOpenSSL 19.1.0 (OpenSSL 1.1.1h  22 Sep 2020), cryptography 3.1.1, Platform Windows-10-10.0.19041-SP0
2021-11-02 14:35:13 [scrapy.utils.log] DEBUG: Using reactor: twisted.internet.asyncioreactor.AsyncioSelectorReactor
2021-11-02 14:35:13 [scrapy.utils.log] DEBUG: Using asyncio event loop: asyncio.windows_events._WindowsSelectorEventLoop
2021-11-02 14:35:13 [scrapy.crawler] INFO: Overridden settings:
{'SPIDER_MODULES': ['minimal.spiders'],
 'TWISTED_REACTOR': 'twisted.internet.asyncioreactor.AsyncioSelectorReactor'}
2021-11-02 14:35:13 [scrapy.extensions.telnet] INFO: Telnet Password: e08b27a2926c4972
2021-11-02 14:35:13 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.logstats.LogStats']
2021-11-02 14:35:14 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2021-11-02 14:35:14 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2021-11-02 14:35:14 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2021-11-02 14:35:14 [scrapy.core.engine] INFO: Spider opened
2021-11-02 14:35:14 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2021-11-02 14:35:14 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
2021-11-02 14:35:14 [asyncio] DEBUG: Using proactor: IocpProactor
```

**Comment by wRAR** [comment]
Ah, I see.
Without calling `set_event_loop_policy` I get `TypeError: ProactorEventLoop is not supported, got: <ProactorEventLoop running=False closed=False debug=False>` (which is the "fix" mentioned in the initial comment and included in a Twisted release since then). With calling it I get
```python-traceback
File "C:\Users\wRAR\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 493, in _make_subprocess_transport
    raise NotImplementedError
```

This a different problem. This actually means the workaround discussed here was applied successfully. It doesn't work because of https://github.com/scrapy-plugins/scrapy-playwright/issues/7.

**Comment by the-jolley-boy** [comment]
I'm having issues with this still even with the workaround it still doesn't work.

`# -*- coding: utf-8 -*-
import os
import requests
from discord import SyncWebhook
import discord
import aiohttp
import scrapy
import time
from scrapy.crawler import CrawlerProcess
from scrapy.spiders import CrawlSpider, Rule
from scrapy.linkextractors import LinkExtractor

from scrapy.utils.project import get_project_settings
from apscheduler.schedulers.twisted import TwistedScheduler

class scottycameronSpider(CrawlSpider):
    name = 'scottycameron'
    allowed_domains = ['scottycameron.com']
    start_urls = ['https://www.scottycameron.com/']

    rules = (
        Rule(LinkExtractor(allow = 'store/'), callback = 'parse', follow = True),
    )

    def parse(self, response):
        for products in response.xpath('//*[@id="layout-content"]'):
            price = products.xpath('//*[@id="product_Detail_Price_Div"]/p/text()').get()
            name = products.xpath('//*[@id="layout-product"]/div[2]/div/div[2]/h1/text()').get()
            stock = products.xpath('//*[@id="dynamic-inventory"]/span/text()').get()
            image = products.xpath('//*[@id="product-image"]/@src').get()

            neg = ['sticker', 'pivot tool', 't-shirt']
            #neg = []

            if (price and name and stock) and (not any(x in name.lower() for x in neg) or ("https://www.scottycameron.com/store/speed-shop-creations/" in str(response.request.headers.get('Referer', None)) and not "t-shirt" in name.lower())):
                stock = stock.replace('(', '')
                stock = stock.replace(')', '')
                image = image.replace(' ', '%20')
                webhook = SyncWebhook.from_url('')
                embed = discord.Embed(
                    title=str(name),
                    url=str(response.request.url),
                    colour=0xDB0B23
                )
                embed.add_field(name = "Price", value = str(price), inline = True)
                embed.add_field(name = "Stock", value = str(stock), inline = True)
                embed.set_thumbnail(url = str(image))
                embed.set_footer(text = "Notify Test Monitors")
                webhook.send(embed = embed)

process = CrawlerProcess(get_project_settings())
scheduler = TwistedScheduler()
scheduler.add_job(process.crawl, 'interval', args=[scottycameronSpider], seconds=5)
scheduler.start()
process.start(False)`

I've set the settings file accordingly but still it is failing stating:

Exception: The installed reactor (twisted.internet.selectreactor.SelectReactor) does not match the requested one (twisted.internet.asyncioreactor.AsyncioSelectorReactor)

Running on windows, with python 3.10.0 and Scrapy 2.7.1

**Comment by wRAR** [comment]
@the-jolley-boy this is a different problem.

If you manage the reactor yourself, you need to install the correct one yourself. Note that importing `twisted.internet.reactor` before Scrapy install the correct one counts as managing it yourself, because that statement installs the default one.

**Comment by the-jolley-boy** [comment]
> @the-jolley-boy this is a different problem.
> 
> If you manage the reactor yourself, you need to install the correct one yourself. Note that importing `twisted.internet.reactor` before Scrapy install the correct one counts as managing it yourself, because that statement installs the default one.

Thanks, not too sure how to fix this but I will keep looking, sorry for posting in the wrong thread
