### ISSUE TITLE
LinkExtractor could be use to parse/process javascript files to extract more links/endpoints

### ISSUE THREAD

**Issue by r0oth3x49** [scrapy/scrapy#4977]
## Summary

Most of the time websites contains endpoints/links inside JavaScript files which if we could parse/process using
LinkExtractor would be great.

## Motivation

- By implementing this we will be able to extract/scrape more links which are inside js files and are dynamic.
- The use case that is it support i crawled a website manually and captured requests in burpsuite where i saw few endpoinst/urls that scrapy crawl spider misses as it doesn't process js files for links but only html, i tried LinkExtractor with **tags**/***attrs* option but no luck.
- the outcome of this, we will have more and more links to process/extract data from which are inside js.

**Comment by wRAR** [comment]
> Most of the time websites contains endpoints/links inside JavaScript files

I wouldn't say so. Still, what usage do you see for this? Telling the spider to download JS files and then parse them with regexes?

**Comment by Gallaecio** [comment]
Could you share an example where this would be useful? Maybe there’s a better solution for that scenario.

I cannot think of a reliable way to extract URLs from JavaScript code. The safest approach would be to use something like js2xml to get strings, and extract as links strings that match a URL regular expression, but this would be CPU-intensive and still not that reliable, missing URLs that are build dynamically and most likely extracted undesired URLs. And it would still not be any different from extracting URLs with regular expressions from HTML text and attribute values and filtering out only `CSS` and `JavaScript``stuff.

**Comment by r0oth3x49** [comment]
> 
> 
> Could you share a specific example where this would be useful? Maybe there’s a better solution for that scenario.
> 
> I cannot think of a reliable way to extract URLs from JavaScript code. The safest approach would be to use something like js2xml to get strings, and extract as links strings that match a URL regular expression, but this would be CPU-intensive and still not that reliable, missing URLs that are build dynamically and most likely extracted undesired URLs. And it would still not be any different from extracting URLs with regular expressions from HTML text and attribute values and filtering out only `CSS` and `JavaScript``stuff.

Actually you are right there is no reliable way of doing that except using regex and preparing URL and then testing which i think is overhead also. but i thought if this could be implemented then it will be great.

for example below is js link for a website `https://www.lider.cl`.
`https://wlmstatic.lider.cl/GR/contentassets/js/cart/quickcart.js?v=1611905350049`

if you see the js it has few endpoints which are i guess dynamically created. i did tried using scrapy_splash still these endpoints were missing on a crawling not all but few of them.
 
 
 Sorry for the late reply and thank you so much for quick response.
 i will close the issue as i don't see any other way except as of yet.
