### ISSUE TITLE
the  scrapy command not work properly

### ISSUE THREAD

**Issue by yanxiaolu** [scrapy/scrapy#4981]
### Description
when I run the scrapy command it can not display result properly
eg:
run srapy list/genspider/shell
**the spider run**

### Steps to Reproduce

1. scrapy startproject xxxx [normal]
2. scrapy genspider xxx xxx [normal]
3. write code for new spider and run scrapy genspider to create new spider,the spider already ran.

### Versions

Scrapy 2.4.1

**Comment by wRAR** [comment]
Those commands import your spider modules. Don't put any run code into the top level of your spider modules.
