### ISSUE TITLE
Set custom_settings inside spider __init__

### ISSUE THREAD

**Issue by psdon** [scrapy/scrapy#4983]
I'm trying to update the custom_settings inside `__init__()` function, I found `update_settings` in the source code but haven't found any documentation about it.

```python
class SampleSpider(scrapy.Spider):
    custom_settings = {
        "SETTINGS_TO_OVERIDE": 1
    }
    
    def __init__(self, profile: dict, *args, **kwargs):
        self.custom_settings.update(profile)
        super().__init__(*args, **kwargs)

```

**Comment by psdon** [comment]
#3663 #4196

**Comment by Gallaecio** [comment]
Thanks. Shall we close this in favor of one of those open tickets, or is there a reason to keep this ticket also open?
