### ISSUE TITLE
why ? I can not call process_request method by Crawling rules .

### ISSUE THREAD

**Issue by laokong4628** [scrapy/scrapy#4988]
MY code in follow:

      rules = [
          Rule(LinkExtractor(allow=('/proxy-port/[\d+]{2,5}/')), callback='parse_detail', follow=True, process_request='cookie'),
          ]

    def cookie(self, request, response):
        print('000000000000000')
        request.cookies['bid'] = 'bid'
        request = request.replace(url=request.url.replace('?', '/?'))
        return request

but can not  anything input on terminal , also print('000000000000000') not exist... why ?

**Comment by laokong4628** [comment]
I import these modules.

import re
import telnetlib
from scrapy.spiders import CrawlSpider, Request, Rule
from scrapy.linkextractors import LinkExtractor
from scrapy.http import HtmlResponse

class ProxySpider(CrawlSpider):

**Comment by laokong4628** [comment]
AttributeError: can't set attribute

**Comment by wRAR** [comment]
This is the issue tracker for Scrapy itself. Please use other resources, like https://stackoverflow.com/, to ask about problems with your code.
