### ISSUE TITLE
Cover scrapy-bench in the documentation

### ISSUE THREAD

**Issue by Gallaecio** [scrapy/scrapy#4996]
Cover https://github.com/scrapy/scrapy-bench in our [documentation topic about benchmarking](https://docs.scrapy.org/en/latest/topics/benchmarking.html#benchmarking), as a project to use for more complex Scrapy benchmarking.

It may also be a good idea to remove the promise about future `scrapy bench` enhancements.

**Comment by sarvesh059** [comment]
Hey, i am first time contributing. So, could you elaborate the issue and please also mention the location of file that is to be modified.

**Comment by Gallaecio** [comment]
@sarvesh059 There is already a pull request to solve this: https://github.com/scrapy/scrapy/pull/5016
