### ISSUE TITLE
refactoring _link_allowed to reduce cyclomatic complexity

### ISSUE THREAD

**Issue by dmariel** [scrapy/scrapy#5003]
## Summary

After some exploring with cyclomatic complexity tools (lizard), the function was found to have the third highest complexity.

## Motivation

Low complexity allows for higher readability, testability and maintainability.

## Solution

Refactor.

## Additional context

N/A

**Comment by Gallaecio** [comment]
Closing as per https://github.com/scrapy/scrapy/pull/5004#issuecomment-784857085

**Comment by Gallaecio** [comment]
For future reference, there’s no need to open an issue first if you plan to create a pull request to fix it right away, you can open the pull request directly.
