### ISSUE TITLE
Either depth limit or allow parameter in LinkExtractor() not working correctly

### ISSUE THREAD

**Issue by bnicholl** [scrapy/scrapy#5010]
Description:

I am trying to scrape URL's using CrawlSpider class with no DEPTH_LIMIT in the custom_settings dict, therefore I set that depth limit to 0. I have also tried other depth limits all the way up to DEPTH_LIMIT : 30. I also have the allow parameter in the LinkExtractor() function set so only links that have a string value inside the allow list will be accessed. Code is below

Code Example:

```
import scrapy
from scrapy.crawler import CrawlerProcess
from scrapy.spiders import CrawlSpider, Rule
from scrapy.linkextractors import LinkExtractor
import json
import csv


class crawling_web(CrawlSpider):
    name = 'TheFriendlyNeighbourhoodSpider'
    allowed_domains = [ 'yahoo.com']

    start_urls = [ 'https://finance.yahoo.com', 'https://yahoo.com']
    
    url_links = []
    custom_settings = {
    'CONCURRENT_REQUESTS': 10,
    'CONCURRENT_REQUESTS_PER_DOMAIN': 25,
    'ROBOTSTXT_OBEY': False,
    #'CONCURRENT_ITEMS': 100,
    #'DOWNLOAD_MAXSIZE': 5592405,
    'DEPTH_LIMIT' : 0,
    # Grabs xpath before site finish loading
    'DOWNLOAD_FAIL_ON_DATALOSS': False
    #'DEPTH_PRIORITY': 1,
    #'SCHEDULER_DISK_QUEUE' : 'scrapy.squeues.PickleFifoDiskQueue',
    #'SCHEDULER_MEMORY_QUEUE' :'scrapy.squeues.FifoMemoryQueue'
    }
    

    allow_comp_keywords = ('chevron', 'amazon', 'amazons', 'amzn')
    rules = (
        Rule(LinkExtractor(canonicalize=False, unique=True, allow=allow_comp_keywords), follow=True, callback="parse_link"),
    )
        
    def parse_link(self, response):
        
        self.url_links.append(response.url)
        

# This below code simply runs the above functions!
process = CrawlerProcess(settings={
    "FEEDS": {
        "items.json": {"format": "json"},
    },
})


process.crawl(crawling_web)
process.start() # the script will block here until the crawling is finished
```

Problem:

If you look at the allow parameter in the LinkExtractor(), you can see I have chevron as an allowed keyword yet it isn't picking up any domains with chevron inside of the domain at yahoo.com. This leads me to believe the problem is probably caused by the allow parameter in the LinkExtractor() function.

Proof:

If you go to https://finance.yahoo.com/news/chevron-launches-300-million-fund-151954809.html, which should have depth 2, you will see that this is a legit page. Furthermore, you can find this link on https://finance.yahoo.com/news/ home page entitled Chevron launches $300 million fund to focus on low-carbon technology. The URL in the HTML is news/chevron-launches-300-million-fund-151954809.html. You can also see this is a page that is in the allowed_domains list, and includes chevron keyword, inside of that domain, so it should scrape this URL, yet it does not. Also, not that if you run this algorithm, it will pick up other pages that have amazon string inside of the domain, such as https://finance.yahoo.com/news/this-the-the-one-thing-costco-has-that-amazon-lacks-according-to-charlie-munger-200739515.html

Further testing:

If I get rid of the allow parameter in the LinkExtractor() function. The scraper WILL pick up the respective Chevron url's in the allowed domains. So there clearly seems to be a bug in either depth limit or the allow parameter in LinkExtractor(), or maybe the combination of both is what causes the bug?

How to reproduce:

If you simply run this Algorithm in your local, you can see the output of the websites it has scraped. It will look something like.

> Crawled (200) <GET https://finance.yahoo.com/news/this-the-the-one-thing-costco-has-that-amazon-lacks-according-to-charlie-munger-200739515.html> (referer: https://finance.yahoo.com)
> 2021-02-25 10:24:33 [scrapy.downloadermiddlewares.redirect] DEBUG: Redirecting (302) to <GET http://finance.yahoo.com/news/this-the-the-one-thing-costco-has-that-amazon-lacks-according-to-charlie-munger-200739515.html> 

You will also note that Scrapy is not crawling url's in the allowed domains with the respective allow parameter in the LinkExtractor() set to specific strings. I have reproduced these results with a variety of websites including Fox.com, and others. I'm sure if you just run a CrawlSpider instance such as this and set the allow parameter, you will find Scrapy not crawling links that it should.

**Comment by wRAR** [comment]
> If you look at the allow parameter in the LinkExtractor(), you can see I have tesla as an allowed keyword yet it isn't picking up any domains with tesla inside of the domain at yahoo.com.

How is this related to the depth limit?

**Comment by bnicholl** [comment]
@wRAR Good point, I elaborated, and further explained that it could also be the allow parameter in LinkExtractor().

**Comment by wRAR** [comment]
If you think there is a bug in Scrapy itself you should provide an explanation of the problem and a minimal example how to reproduce it. If you look for a solution for a problem with your code please don't use this issue tracker for that.

**Comment by bnicholl** [comment]
I added a How to reproduce section. I do believe this is a bug. The depth limit is set to 0, thus signifying there is not depth limit, and the allow parameter has the keyword Tesla in it, thus telling Scrapy it should have found and scraped the URL  https://finance.yahoo.com/news/how-**tesla**-and-elon-musk-can-fight-the-new-ev-rivals-211028294.html, among others, yet it is not. I have reproduced these results on a number of websites, hence, the bug.

**Comment by wRAR** [comment]
Please read and follow https://stackoverflow.com/help/minimal-reproducible-example to produce a minimal reproducible example.

> the allow parameter has the keyword Tesla in it, thus telling Scrapy it should have found and scraped the URL https://finance.yahoo.com/news/how-tesla-and-elon-musk-can-fight-the-new-ev-rivals-211028294.htm

No, as this link is not present on any of the start pages.
