### ISSUE TITLE
test_pipeline_images.py fails with "TypeError: Skipped expected string as 'msg' parameter, got 'bool' instead."

### ISSUE THREAD

**Issue by wRAR** [scrapy/scrapy#5020]
See e.g. https://github.com/scrapy/scrapy/pull/5019/checks?check_run_id=2012658916

This should be related to the skip attribute, though I'm not sure why did it start happening now.

**Comment by wRAR** [comment]
OK, looks like it's because of the Twisted upgrade, because of https://github.com/twisted/twisted/commit/beafcd67fd3201c34a8fe0c6639ef0af92fbc7fc

Note that the docs have already said "None or a string".

**Comment by wRAR** [comment]
Looks like changing `False` to `None` helps, but on the other hand the skipping code doesn't really work, as PIL is imported in `scrapy.pipelines.images` and so the test fails with an ImportError anyway.

**Comment by Gallaecio** [comment]
My bad for getting this closed. Let’s keep it open until we figure out the right way forward.

**Comment by wRAR** [comment]
So the easy way is just replacing False with None. A better one is either fixing the no-PIL code path and adding tests for it (I don't see a reason for this additional complexity TBH) or dropping it and saying "we require PIL for tests".

**Comment by Gallaecio** [comment]
I still don’t see what’s wrong with our code. `skipIf(bool, reason)` should work, and instead is causing this issue about the reason being a boolean, as if somewhere in the middle the first parameter of `skipIf` got interpreted as the reason.

**Comment by wRAR** [comment]
The class `skip` attribute previously was checked with `if`, now it is checked with `is None`: https://github.com/twisted/twisted/commit/beafcd67fd3201c34a8fe0c6639ef0af92fbc7fc  (respectively the old line 1076 and the new line 1040).

**Comment by Gallaecio** [comment]
But is that a bug in Twisted that we should report, or does the fix need to happen in our code or code we use (e.g. `pytest-twisted`)?

**Comment by wRAR** [comment]
It's a bug in our code as we set `skip` to `False` when the docs say `L{None} or a string explaining why this test is to be skipped. If defined, the test will not be run.`

**Comment by Gallaecio** [comment]
I see. When I was looking at the code to check for this issue, I became convinced that our use of skipIf in https://github.com/scrapy/scrapy/blob/master/tests/test_pipeline_images.py#L187 was one of the cases where the issue was triggered. But it’s not, it’s the use of skip in other parts of the file as a string what’s triggering it.

OK, so it should be relatively easy to fix.

**Comment by Boris-code** [comment]
发现了个更好用的爬虫框架，支持分布式、配置采集、具有完善的报警机制

https://github.com/Boris-code/feapder
