### ISSUE TITLE
 crawl  0 page  0 item

### ISSUE THREAD

**Issue by ihoment-lys** [scrapy/scrapy#5023]
Hi team

The crawler made an example, but it was found that there was no problem in crawling less than 100 when running, but it was expanded, such as crawling 1000 items, sometimes it got stuck, and it kept reporting crawl 0 page 0 item

and it gives me the following error:
![image](https://user-images.githubusercontent.com/73272214/109743996-8fdcdc00-7c0c-11eb-8484-e53174786b0c.png)

Any idea of whats going on?

**Comment by wRAR** [comment]
This is a tracker for issues in Scrapy itself and this looks like a problem with your code and/or the website you are crawling.

**Comment by ihoment-lys** [comment]
Thank you very much. Is there any way to solve it?

**Comment by wRAR** [comment]
Investigate the problem and fix it or search for help at the places more suitable for that.

**Comment by dtalkachou** [comment]
@ihoment-lys, how you fix this problem?

**Comment by ihoment-lys** [comment]
Added some header information, it is likely to be reversed

**Comment by hafiz031** [comment]
In my case I was running out of resources: https://stackoverflow.com/a/79038933/6907424
