### ISSUE TITLE
Spider templates add unnecessary trailing slash to start_urls

### ISSUE THREAD

**Issue by zseta** [scrapy/scrapy#5025]
### Description

Noticed that when running the genspider command and using the [basic](https://github.com/scrapy/scrapy/blob/master/scrapy/templates/spiders/basic.tmpl) or [crawl](https://github.com/scrapy/scrapy/blob/master/scrapy/templates/spiders/crawl.tmpl) template, the generated spider code adds a trailing slash to the url in `start_urls` list. Not sure if this is a bug or it's intentional, but  this extra trailing slash added by the template could lead to 404 in some cases hence breaking the spider.

### Steps to Reproduce

1. Run `scrapy genspider myspider example.com`
2. Check the generated spider and see that `start_urls = ['http://example.com/']` includes an extra trailing slash which can lead to 404 in some cases

**Expected behavior:** Don't add extra trailing slash (by removing the trailing slash from those two templates)

**Comment by wRAR** [comment]
I'm sure this should never lead to 404, as the path will be `/` in both cases.

**Comment by Gallaecio** [comment]
Unrelated: maybe the protocol chosen by default should he HTTPS instead of HTTP, though.

**Comment by zseta** [comment]
I should've reference [this reddit question](https://www.reddit.com/r/scrapy/comments/lus6q6/a_question_on_xml_spider/).

- No trailing slash (200 in scrapy): https://www.tsunami.gov/events/xml/PAAQAtom.xml 
- Trailing slash (404 in scrapy): https://www.tsunami.gov/events/xml/PAAQAtom.xml/

Now, that's another question that for this, probably not the default template should be used, but the [xml one](https://github.com/scrapy/scrapy/blob/master/scrapy/templates/spiders/xmlfeed.tmpl).

Another example where trailing slash is an issue (same website):

- no trailing slash: https://tsunami.gov/?page=exercises (200)
- trailing slash: https://tsunami.gov/?page=exercises/ (200, but content is not displayed, and if we want to extract it that's a problem)

**Comment by wRAR** [comment]
Just don't pass URLs in the parameter named "domain".
