### ISSUE TITLE
Fix and re-enable tests on macOS

### ISSUE THREAD

**Issue by Gallaecio** [scrapy/scrapy#5032]
We’ve decided to disable tests in macOS because we were often getting random tests failures there from one of the jobs.

Still, we aim to support macOS, so we need to figure out how to fix those issues, and re-enable tests on macOS.

**Comment by Laerte** [comment]
@Gallaecio @wRAR I believe we an enable the tests again, my local branch succeed in all tests after 3.8 support deprecation: https://github.com/Laerte/scrapy/actions/runs/11371871987

**Comment by wRAR** [comment]
That was also my thought, yeah.

**Comment by wRAR** [comment]
I've re-enabled the workflow in the CI settings.
