### ISSUE TITLE
Exporting to csv results in unicode char: Ã£

### ISSUE THREAD

**Issue by mabittar** [scrapy/scrapy#5035]
I was scraping a brazilian weather site: https://www.climatempo.com.br/previsao-do-tempo/agora/cidade/558/saopaulo-sp

when I reproduces in scrapy shell "https://www.climatempo.com.br/previsao-do-tempo/agora/cidade/558/saopaulo-sp" -> response.xpath('//*[@id="mainContent"]/ul/div/div[1]/ol/li[4]/span/text()').get()

I got the result I need: 'São Paulo - SP'

but when I export to a csv I got: SÃ£o Paulo - SP

there's anyway to fix it?

my [repo](https://github.com/mabittar/scrapy_climatempo)

**Comment by wRAR** [comment]
Your code creates a correct UTF-8 CSV file for me. It may be a problem with how you use the CSV.
