### ISSUE TITLE
Scrapy's retry middleware removes proxy user password when retrying

### ISSUE THREAD

**Issue by iamumairayub** [scrapy/scrapy#5039]
I have proxies where I have single proxy address, and different user password each (that is how they give different IPs), I send several requests with different different user pass

I have custom_settings in my Spider

    custom_settings = {
        'DOWNLOADER_MIDDLEWARES': {
            'project.middlewares.ProxyDownloaderMiddleware': 630,
        }
    }

I set proxy like below and it works pretty well

    class ProxiesDownloaderMiddleware(object):
    
        def process_request(self, request, spider):
    		request.meta['proxy'] = 'user:pass@proxy-address'

Only problem is when request is retried, then for that request, I get following error

    [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://www.website.com> (failed 1 times): Could not open CONNECT tunnel with proxy proxy-address [{'status': 407, 'reason': b'Proxy Authentication Required'}]

So my issue is, why Scrapy removes user password from proxy when its retried?

**Comment by wRAR** [comment]
`request.meta['proxy']` is handled by `HttpProxyMiddleware` (it removes the creds from the value and sets the `Proxy-Authorization` header). But as `RetryMiddleware` just makes a copy of the request and schedules it, it's not clear to me why do you see the described behavior.

**Comment by iamumairayub** [comment]
I think its `scrapy.downloadermiddlewares.redirect` stripping out auth from the request while redirecting

**Comment by wRAR** [comment]
Looks like you need to provide a minimal reproducible example of this problem then.

**Comment by iamumairayub** [comment]
Hi @wRAR, sorry it was issue from my code
I was trying to stick proxies on subsequent requests, and there is a part where I did `'proxy': response.meta['proxy']`
I changed that to `'proxy': response.request.meta['proxy']` and it fixed

Please delete this issue from Git if possible

**Comment by Gallaecio** [comment]
@iamumairayub The issue is close now, but I just wanted to clarify that those 2 pieces of code [are equivalent](https://docs.scrapy.org/en/latest/topics/request-response.html#scrapy.http.Response.meta), and hence should work the same, so it’s possible it was a different code change that did the trick.

**Comment by Payne-Wu** [comment]
I have the same problem. I suggest we delete them 
```python
# "scrapy/core/download/handers/http11" 
if isinstance(agent, self._TunnelingAgent):
    headers.removeHeader(b'Proxy-Authorization')
```

**Comment by Gallaecio** [comment]
@Payne-Wu Wouldn’t removing those lines cause your proxy credentials to get filtered to the target websites?

**Comment by Payne-Wu** [comment]
No, it won't. Adding authentication information 'proxy authorization' is to verify with a third party. The agent makes the actual request。
A proxy agent is not a completely independent request and response。

**Comment by Payne-Wu** [comment]
> @Payne-Wu Wouldn’t removing those lines cause your proxy credentials to get filtered to the target websites?

so,  developer puts in 'proxy authorization', it should not be deleted

**Comment by Gallaecio** [comment]
@Payne-Wu Does this issue affect you in a consistent way? Any chance you could provide a minimal, reproducible example? (no need for actual proxy URL and credentials, of course)

**Comment by Payne-Wu** [comment]
Yes, my pleasure
```python3

# MyHttpProxyMiddleware
class MyHttpProxyMiddleware:

    def process_request(self, request, spider):
    		# set proxy addr
        request.meta["proxy"] = "http://forward.xdaili.cn:80"
        # set Proxy-Authorization, if need use proxy in scrapy, must remove or Annotation it
        # "scrapy/core/download/handers/http11"
        # if isinstance(agent, self._TunnelingAgent):
        #     headers.removeHeader(b'Proxy-Authorization')
        request.headers['Proxy-Authorization'] = XDL.auth()
        """
        # a request Module example
        header = {
        "Proxy-Authorization": XDL.auth(),
        "User-Agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36"
        }
        print(header)
        proxy = {"http": "http://forward.xdaili.cn:80", "https": "http://forward.xdaili.cn:80"}
        response = requests.get("https://httpbin.org/ip", headers=header, proxies=proxy)
        """

**Comment by Payne-Wu** [comment]
> Yes, my pleasure
> 
> ```python
> # MyHttpProxyMiddleware
> class MyHttpProxyMiddleware:
> 
>     def process_request(self, request, spider):
>     		# set proxy addr
>         request.meta["proxy"] = "http://forward.xdaili.cn:80"
>         # set Proxy-Authorization, if need use proxy in scrapy, must remove or Annotation it
>         # "scrapy/core/download/handers/http11"
>         # if isinstance(agent, self._TunnelingAgent):
>         #     headers.removeHeader(b'Proxy-Authorization')
>         request.headers['Proxy-Authorization'] = XDL.auth()
>         """
>         # a request Module example
>         header = {
>         "Proxy-Authorization": XDL.auth(),
>         "User-Agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36"
>         }
>         print(header)
>         proxy = {"http": "http://forward.xdaili.cn:80", "https": "http://forward.xdaili.cn:80"}
>         response = requests.get("https://httpbin.org/ip", headers=header, proxies=proxy)
>         """
> ```

Proxy authorization is only used for proxy authentication and does not make the request transparent

**Comment by Gallaecio** [comment]
By minimal, reproducible example I meant a piece of code that anyone can use, setting their own proxy data, to reproduce the issue. For example, if the issue happens upon a retry being needed, a simple spider pointing to an http://httpbin.org/ endpoint may do the job.

The point is to get the example form someone that can reproduce the issue. That way, if the same example cannot be used to reproduce the issue with our own proxy data, the issue may be proxy-specific. If it _can_ be used, we can use it to validate a fix.
