### ISSUE TITLE
Save information 

### ISSUE THREAD

**Issue by jjuandiaz** [scrapy/scrapy#5041]
Hello . I want to append values into array but the reques is async so can’t 

1- search all urls in site 
2 parse method for each all urls 
3 make url request 
4 add result into array 
5 need to save result array (into array url step 2) 

urls to scrape into one page 

urls to send scrape request 
|
Channels > channel > programs

**Comment by wRAR** [comment]
This is an issue tracker for Scrapy, you should places like https://stackoverflow.com/ to ask questions about your code.
