### ISSUE TITLE
HTTP/2: review the handling of non-UTF8 strings as protocol

### ISSUE THREAD

**Issue by Gallaecio** [scrapy/scrapy#5051]
The [initial HTTP/2 implementation](https://github.com/scrapy/scrapy/pull/4769) seems to assume that the protocol string received from a server will always be an ASCII string. While this should be the case for any working connection, we should make sure that we handle non-ASCII input here gracefully. It should definitely not cause the whole crawl to stop, or prevent connection to other, well-behaving servers.

**Comment by FilipePintoReis** [comment]
@Gallaecio I have two questions about this:

**1. This one is pretty straight forward.**
Is there any way you can clarify what you mean by "protocol string"?

**2. Forgive me if this one is too big.**
From what I've read thus far, UTF-8 encodes strings in 8 bits and ASCII encodes them in 7. That said, UTF-8 has retro compatibility with ASCII. 
I've looked into [the PR you mention](https://github.com/scrapy/scrapy/pull/4769) and I feel that what you want to check for ASCII/UTF-8 compliance is in scrapy/core/http2/stream.py, line 229, where you process the headers.
Could it be that you meant you want to handle non-UTF8 input gracefully, or I'm just looking into the wrong parts of the code?

Regards,
Filipe

**Comment by Gallaecio** [comment]
I was looking at the code of https://github.com/scrapy/scrapy/pull/4769 to find the line where I saw us decoding the protocol byte array trusting it to be UTF-8, to answer your questions, but it turns out @elacuesta [already fixed that](https://github.com/scrapy/scrapy/pull/4769/commits/6326178bc5824e8c08d84b6543de6977a16fb8d2) before we merged the code.
