### ISSUE TITLE
Document how to change file system storage default file name

### ISSUE THREAD

**Issue by banagale** [scrapy/scrapy#5069]
## Summary

The media pipeline, supported storage, file system storage section of the documentation begins by explaining that files are stored using SHA1 hash of their URLs.

This is a good default choice, but the documentation makes no mention of the `MediaPipeline.file_path()` method.

Presuming this is indeed the best way to get custom file names out of a file or images pipeline, this issue is to request a call out for setting a custom file name by overriding this method:

```
    def file_path(self, request, response=None, info=None, *, item=None):
        image_guid = hashlib.sha1(to_bytes(request.url)).hexdigest()
        return f'full/{image_guid}.jpg'
```

## Motivation

It appears [it used to be](https://stackoverflow.com/questions/18081997/scrapy-customize-image-pipeline-with-renaming-defualt-image-name?noredirect=1&lq=1) more tricky to customize file names.

Calling out this method may save people time.

## Describe alternatives you've considered

Leaving it as is or perhaps explaining why SHA1 was chosen over any other default file naming scheme.

**Comment by aadityasinha-dotcom** [comment]
Can I work on this issue?

**Comment by banagale** [comment]
Fine with me.

**Comment by aadityasinha-dotcom** [comment]
Can you explain me about this issue.

**Comment by aadityasinha-dotcom** [comment]
Can you explain me about this issue?

**Comment by banagale** [comment]
Please re-read the issue and if you have a specific question that is not addressed let me know.

**Comment by aadityasinha-dotcom** [comment]
I have to make the file_path() method in the media.pipeline?

**Comment by banagale** [comment]
@aadityasinha-dotcom I'm not sure I understand what you're looking for, Aaditya. This issue is related to the tool's documentation. 

I've posted it here for feedback on if there is a better way to set this filename. 

If not, and there are no objections to a PR adding a note about this behavior, I'll do it myself.

**Comment by Gallaecio** [comment]
This is [technically already documented](https://docs.scrapy.org/en/latest/topics/media-pipeline.html#scrapy.pipelines.files.FilesPipeline.file_path).

But maybe we could improve discoverability by adding a section to that page about customizing the output file path. The section should probably just say that you can do that by customizing the middleware and overriding file_path, with links to both sections below.

**Comment by banagale** [comment]
@Gallaecio I think that this would be sufficient. I had not seen the class definition, but discovered it looking through the code.

Let me know if you would you be open to a PR for this change, and I'll add something reasonable.

**Comment by Gallaecio** [comment]
@banagale That would be great, thanks!
