### ISSUE TITLE
Are there plans to update scrapy-feedexporter-sftp?

### ISSUE THREAD

**Issue by Noexpert** [scrapy/scrapy#5071]
I notice that the last commit is from 2016.
https://github.com/scrapy-plugins/scrapy-feedexporter-sftp

Is the plugin secure to use right now, or are there plans to update it?

Thanks

**Comment by elacuesta** [comment]
FTP itself is not typically considered to be very secure, I'd recommend avoiding it if possible. See also #4180.

**Comment by wRAR** [comment]
Hi @Noexpert , we don't currently have any plans for that repo. The code looks quite simple so it's most likely still working but if doesn't or if you decide not to use it for some other reason, you can write your own SFTP exporter with Paramiko in about ten lines so it's not a big problem.
