### ISSUE TITLE
HTTP2 test failures with some OpenSSL

### ISSUE THREAD

**Issue by wRAR** [scrapy/scrapy#5085]
As noticed on [Conda](https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/300551/logs/46), the testsuite can fail with a bunch of SSL-related errors in some cases. While it works on the Github CI and with local tox, it fails in the Conda CI (on different OSes) and on Debian sid. Looks like it may be caused by differences in some OpenSSL configuration.

Normal tox runs will install cryptography from PyPI, which links OpenSSL statically (for all OSes, I suspect). On Debian I tested with the system OpenSSL 1.1.1k. Conda builds use cryptography from conda-forge, which links OpenSSL dynamically, and openssl from conda-forge as well.

**Comment by wRAR** [comment]
This is not a problem with OpenSSL but a symptom of missing HTTP2 support in Twisted, which in both cases was caused by missing `priority` module.

**Comment by Gallaecio** [comment]
Nice find!
