### ISSUE TITLE
open_in_browser(response) not working for Ubuntu but in Mac works.

### ISSUE THREAD

**Issue by AndreuJove** [scrapy/scrapy#5086]
Hello everyone!!

I have been trying for a while to solve the problem but I can't.

```
$ from scrapy.utils.response import open_in_browser
$ open_in_browser(response)
False
```

Scrapy:
scrapy==1.7.4

Google Chrome:
Version 89.0.4389.114 (Official Build) (64-bit)

**Comment by Gallaecio** [comment]
Does the `xdg-open https://example.com` command works?

**Comment by AndreuJove** [comment]
Hi Gallaecio! 

Thanks for the quickly reply.

In my terminal shell works the command that you say it. But in VisualStudioCode gives me this error:

The error now is: 
xdg-open https://example.com
`[40397:40397:0407/141530.783668:ERROR:browser_main_loop.cc(1390)] Unable to open X display.`


Much appreciated!

**Comment by Gallaecio** [comment]
It definitely looks unrelated to Scrapy. https://stackoverflow.com/a/65912187/939364 may help.

**Comment by AndreuJove** [comment]
@Gallaecio 

It is exactly what I was looking for. It saved the problem. Thank you very much! Have a nice day.
