### ISSUE TITLE
[RETRY HTTP CODES 302 not working]

### ISSUE THREAD

**Issue by AndreuJove** [scrapy/scrapy#5089]
Good afternooon,

A website is redirecting me to another page that i don't want using 302 and then 200, I guess scrapy follow and returns this final code. How can I can retry the first URL until it gives me a 200?

Thanks a lot

**Comment by Gallaecio** [comment]
Please, use [StackOverflow](https://stackoverflow.com/tags/scrapy) to ask this type of questions. See [Getting Help](https://docs.scrapy.org/en/latest/#getting-help).

This specific question is rather common, so you can probably find an answer if you search a bit for it.
