### ISSUE TITLE
Production ready HTTP/2 Support

### ISSUE THREAD

**Issue by storymode7** [scrapy/scrapy#5093]
Hi 

## Summary

The HTTP/2 support is already present in Scrapy, but some features that are present in HTTP/1.1 are [yet to be implemented](https://github.com/scrapy/scrapy/issues?q=is%3Aissue+is%3Aopen+label%3AHTTP%2F2).
And with new implementations come testing and documentation. Along with that it still requires test for some parts that are not yet tested completely. (Issue #5049 discusses this)
I plan to deal with these and have a [GSoC proposal](https://docs.google.com/document/d/1pMqtAtCwwiwLc3G7WwB5muCq0d7UsEGA_e66p50s7l8/edit?usp=sharing) for the same.

## Additional context
A [lot of work](https://github.com/scrapy/scrapy/pull/4769/files) has been done on HTTP/2 implementation as part of GSoC 2020, which already allows users to perform a majority of tasks, I plan to take up the baton and get it to the final stage.

@wRAR @Gallaecio @elacuesta please let me know your views regarding the proposal.

Thanks!

**Comment by storymode7** [comment]
Hey, @wRAR @Gallaecio @elacuesta. I've updated my proposal. Pinging you for review again.

**Comment by Gallaecio** [comment]
The proposal looks good enough to me. Your detailed explanations of how you aim to address some of the issues shows that you are already somewhat familiar with the relevant parts of the code base, which is great.

I’ll mention that setting up for stress testing should not be too hard, in relation to HTTP/2 we extended https://github.com/scrapy/scrapy-bench to allow crawling URLs from a CSV file, and with that command and setting the HTTP/2 download handler through a setting the test can be performed. But the test itself will take time to run, and figuring out the causes of the issues will take time and may be hard.

I wonder if maybe you could make the stress testing a stretch goal, to be handled in case there’s spare time, and instead dedicate those 2 weeks to finish up https://github.com/scrapy/scrapy/pull/4770, which should be mostly ready but despite being closed at the moment it has not yet been merged, and it will probably need further test coverage and possibly additional work. Up to you, though; I think the current timeline is OK as well.

**Comment by storymode7** [comment]
Thank you for the review.

Finishing up #4770 sounds good. I'll study the PR and update the proposal accordingly with it, including the stretch goal.

**Comment by storymode7** [comment]
Thank you for your time everyone.
