### ISSUE TITLE
Wrong charset handling in MailSender

### ISSUE THREAD

**Issue by wRAR** [scrapy/scrapy#5096]
Looks like passing `charset='utf-8'` makes a plain text message with `Content-Transfer-Encoding: base64` which then can't be read.

At https://github.com/scrapy/scrapy/blob/5a75b14a5fbbbd37c14aa7317761655ac7706b70/scrapy/mail.py#L81 `set_charset` is called but as the payload is not set yet, the underlying class just sets the headers. When later `set_payload` is called, it doesn't do any encoding, but the `Content-Transfer-Encoding` is already set. Looks like the fix should be passing the encoding to `set_payload` too, like was proposed in #3722 (and `set_charset` may be safe to be removed, not sure about this). Note that we have tests but they don't catch this.

Note also, that all of this seems to be compat code according to the Python docs.

**Comment by mmitropoulou** [comment]
Hello, i am now here and i would like to try and fix this bug.

**Comment by wRAR** [comment]
Sure, you can go ahead.

**Comment by Gallaecio** [comment]
> Can you please give me some guidlines and tell me how to recreate this issue?

The documentation about using the `MailSender` class is at https://docs.scrapy.org/en/latest/topics/email.html . Then it should be a matter of following the instructions on the issue description (“passing charset='utf-8'”), and verify that indeed the resulting email message cannot be read.

**Comment by mmitropoulou** [comment]
Hello, I have made a small change and now when you send an email with utf-8 encoding the body of the email looks fine and does not have a base64 encoding. Do you want me to do a pull request or maybe a draft pull request to see what I have done and give me feedback?

**Comment by Gallaecio** [comment]
> Do you want me to do a pull request or maybe a draft pull request to see what I have done and give me feedback?

That would be great! Feel free to make it a regular pull request if it’s ready for review and discussion.
