### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by JQ-K** [scrapy/scrapy#5102]
### Description

when run  scrapy shell https://zhuanlan.zhihu.com/p/344192245

display:
  “MemoryError: Cannot allocate write+execute memory for ffi.callback(). You might be running on a system that prevents this. For more information, see https://cffi.readthedocs.io/en/latest/using.html#callbacks”

**Comment by Gallaecio** [comment]
This looks like a duplicate of https://github.com/scrapy/scrapy/issues/4117
