### ISSUE TITLE
Scrapy is definitely slow when working from cache

### ISSUE THREAD

**Issue by dchaplinsky** [scrapy/scrapy#5105]
### Description

I'm using scrapy with cache enabled to first crawl the pages I need over night and then polish the extraction, while working from cache. Suddenly, the speed of the processing of cached is pages quite slow, below 2k pages per minute. My data processing is trivial, my datastorage is mongo (I've tried to disable it to eliminate extra-factor, but that didn't affected the speed), my CPU/IO isn't even sweating. I've tried to bump `CONCURRENT_ITEMS` to a higher value, but got no result. I'm using twisted reactor. More than that, on decent internet connection my crawling speed on empty cache is roughly the same (1800 items per second).

Below are my cache settings.
```
HTTPCACHE_ENABLED = True
HTTPCACHE_EXPIRATION_SECS = 0
HTTPCACHE_DIR = "httpcache"
HTTPCACHE_IGNORE_HTTP_CODES = []
HTTPCACHE_STORAGE = "scrapy.extensions.httpcache.FilesystemCacheStorage"
```
### Steps to Reproduce

1. Crawl the website and cache all the pages
2. Rerun the spider on cache
3. Watch slow processing speed

**Expected behavior:**
Reasonably higher parsing speed when working from cache

**Actual behavior:** 
Speed of parsing is quite low and basically the same as with empty cache on decent connection.

**Reproduces how often:** 
All of my spiders are suffering from this behavior.

### Versions

```
Scrapy       : 2.5.0
lxml         : 4.6.3.0
libxml2      : 2.9.10
cssselect    : 1.1.0
parsel       : 1.6.0
w3lib        : 1.22.0
Twisted      : 21.2.0
Python       : 3.9.1 (default, Apr 12 2021, 01:27:54) - [Clang 10.0.0 (clang-1000.10.44.4)]
pyOpenSSL    : 20.0.1 (OpenSSL 1.1.1k  25 Mar 2021)
cryptography : 3.4.7
Platform     : macOS-10.13.6-x86_64-i386-64bit
```

### Additional context

My full settings.py is below:
```pyhon
import os
from urllib.parse import quote_plus


def get_env_str(k, default):
    return os.environ.get(k, default)


def get_env_int(k, default):
    return int(get_env_str(k, default))


BOT_NAME = "corpora"

SPIDER_MODULES = ["corpora.spiders"]
NEWSPIDER_MODULE = "corpora.spiders"


ROBOTSTXT_OBEY = False


AUTOTHROTTLE_ENABLED = False
AUTOTHROTTLE_START_DELAY = 5
AUTOTHROTTLE_MAX_DELAY = 60

HTTPCACHE_ENABLED = True
HTTPCACHE_EXPIRATION_SECS = 0
HTTPCACHE_DIR = "httpcache"
HTTPCACHE_IGNORE_HTTP_CODES = []
HTTPCACHE_STORAGE = "scrapy.extensions.httpcache.FilesystemCacheStorage"


ITEM_PIPELINES = {
    "scrapy.pipelines.files.FilesPipeline": 1,
    "corpora.pipelines.MongoDBPipeline": 9000,
}

FILES_STORE = "nanu_pdfs"

DOWNLOAD_WARNSIZE = 3355443200
DOWNLOAD_TIMEOUT = 1800
HTTPCACHE_IGNORE_HTTP_CODES = [500, 501, 502, 503, 401, 403]
RETRY_ENABLED = True

MONGODB_HOST = quote_plus(get_env_str("MONGODB_HOST", "localhost"))
MONGODB_PORT = get_env_int("MONGODB_PORT", 27017)
MONGODB_USERNAME = quote_plus(get_env_str("MONGODB_USERNAME", ""))
MONGODB_PASSWORD = quote_plus(get_env_str("MONGODB_PASSWORD", ""))
MONGODB_AUTH_DB = get_env_str("MONGODB_AUTH_DB", "admin")
MONGODB_DB = get_env_str("MONGODB_DB", "ubertext")
MONGODB_CONNECTION_POOL_KWARGS = {}
```

**Comment by dchaplinsky** [comment]
I've tested it further more, changing  `REACTOR_THREADPOOL_MAXSIZE` and `CONCURRENT_ITEMS` and disabling extra processing of scraped texts and mongo storage.

The best results I've got is 2180 items per minute, with low number of `CONCURRENT_ITEMS` (1-10) and vanilla settings of `REACTOR_THREADPOOL_MAXSIZE`. High number of concurrent items (1000) gave me whooping 600 items per minute :(

**Comment by Gallaecio** [comment]
Those steps to reproduce are not enough for us to reproduce the issue. And your code fragments include a lot of code that is clearly unrelated to the issue. Please, provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

I use the disk cache relatively often and for me it’s about 10x the speed of straight crawl.

**Comment by dchaplinsky** [comment]
Hello! Thanks for the prompt reply.

Here is the code of the spider/item I'm using. This one is extracted from the real project of mine and tested on vanilla installation of Scrapy/default settings:

```python
# -*- coding: utf-8 -*-
import scrapy
from scrapy.loader import ItemLoader
from itemloaders.processors import MapCompose, TakeFirst


class PravdaComUaCorpusItem(scrapy.Item):
    title = scrapy.Field(
        output_processor=TakeFirst(),
    )
    text = scrapy.Field(
        output_processor=TakeFirst(),
    )
    tags = scrapy.Field()
    date_of_publish = scrapy.Field(
        output_processor=TakeFirst(),
    )
    source = scrapy.Field(
        output_processor=TakeFirst(),
    )
    url = scrapy.Field(
        output_processor=TakeFirst(),
    )
    img = scrapy.Field(
        output_processor=TakeFirst(),
    )


class PravdaComUaSpider(scrapy.spiders.SitemapSpider):
    name = "pravda_com_ua"
    allowed_domains = ["pravda.com.ua"]
    sitemap_urls = [
        "https://www.pravda.com.ua/sitemap/sitemap-2021-03.xml.gz",
        "https://www.pravda.com.ua/sitemap/sitemap-2021-02.xml.gz",
        "https://www.pravda.com.ua/sitemap/sitemap-2021-01.xml.gz",
    ]
    sitemap_rules = [("ua/news/", "parse_article")]

    def parse_article(self, response):
        l = ItemLoader(PravdaComUaCorpusItem(), response)

        l.add_css("img", ".post_photo_news_img::attr(src)")
        l.add_css("title", ".post_title::text")
        l.add_css("tags", ".post_tags_item a::text")
        l.add_css("text", ".post_text")
        l.add_css("date_of_publish", ".post_time::text")
        l.add_css("source", ".post__source::text")

        l.add_value("url", response.url)
        yield l.load_item()
```

will post test results shortly

**Comment by dchaplinsky** [comment]
Here goes stats output on an empty cache and shitty wifi connection (24 items per second):
```python
{'downloader/request_bytes': 1738651,
 'downloader/request_count': 5651,
 'downloader/request_method_count/GET': 5651,
 'downloader/response_bytes': 340887643,
 'downloader/response_count': 5651,
 'downloader/response_status_count/200': 5648,
 'downloader/response_status_count/502': 3,
 'elapsed_time_seconds': 235.036166,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2021, 4, 21, 21, 2, 49, 124109),
 'httpcache/firsthand': 5649,
 'httpcache/hit': 2,
 'httpcache/miss': 5649,
 'httpcache/store': 5649,
 'httpcompression/response_bytes': 1658536272,
 'httpcompression/response_count': 5645,
 'httperror/response_ignored_count': 1,
 'httperror/response_ignored_status_count/502': 1,
 'item_scraped_count': 5644,
 'log_count/ERROR': 1,
 'log_count/INFO': 14,
 'memusage/max': 223203328,
 'memusage/startup': 53833728,
 'request_depth_max': 1,
 'response_received_count': 5649,
 'retry/count': 2,
 'retry/max_reached': 1,
 'retry/reason_count/502 Bad Gateway': 2,
 'robotstxt/request_count': 1,
 'robotstxt/response_count': 1,
 'robotstxt/response_status_count/200': 1,
 'scheduler/dequeued': 5650,
 'scheduler/dequeued/memory': 5650,
 'scheduler/enqueued': 5650,
 'scheduler/enqueued/memory': 5650,
 'start_time': datetime.datetime(2021, 4, 21, 20, 58, 54, 87943)}
```

and here is the stats output on fully cached version of the same website (39 items per second):
```python
{'downloader/request_bytes': 1738651,
 'downloader/request_count': 5651,
 'downloader/request_method_count/GET': 5651,
 'downloader/response_bytes': 340887643,
 'downloader/response_count': 5651,
 'downloader/response_status_count/200': 5648,
 'downloader/response_status_count/502': 3,
 'elapsed_time_seconds': 144.516454,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2021, 4, 21, 21, 6, 38, 31832),
 'httpcache/hit': 5651,
 'httpcompression/response_bytes': 1658536272,
 'httpcompression/response_count': 5645,
 'httperror/response_ignored_count': 1,
 'httperror/response_ignored_status_count/502': 1,
 'item_scraped_count': 5644,
 'log_count/ERROR': 1,
 'log_count/INFO': 13,
 'memusage/max': 233816064,
 'memusage/startup': 53305344,
 'request_depth_max': 1,
 'response_received_count': 5649,
 'retry/count': 2,
 'retry/max_reached': 1,
 'retry/reason_count/502 Bad Gateway': 2,
 'robotstxt/request_count': 1,
 'robotstxt/response_count': 1,
 'robotstxt/response_status_count/200': 1,
 'scheduler/dequeued': 5650,
 'scheduler/dequeued/memory': 5650,
 'scheduler/enqueued': 5650,
 'scheduler/enqueued/memory': 5650,
 'start_time': datetime.datetime(2021, 4, 21, 21, 4, 13, 515378)}
```

You can try it yourself (you might want to plug in the full sitemap `https://www.pravda.com.ua/sitemap/sitemap-archive.xml`, not just 3 months that I did).

Once again, test with empty cache was made on a laptop/wifi/home connection. I believe if I move it to the server/decent connection, the gap between cached and uncached versions will be smaller.

**Comment by dchaplinsky** [comment]
Just for the sake of clean experiment I ran it on server too:
No cache: 45 items per second
Fully cached: 81 items per second

**Comment by dchaplinsky** [comment]
That's 2017 MBP 15" with 1TB PCIe-based onboard SSD

I'll run tests with different cache storages tomorrow

**Comment by dchaplinsky** [comment]
`'item_scraped_count': 5645`

FilesystemCacheStorage, empty cache:
` 'elapsed_time_seconds': 220.263199,`

FilesystemCacheStorage, full cache:
` 'elapsed_time_seconds': 155.649056,`

DbmCacheStorage, empty cache:
` 'elapsed_time_seconds': 286.342644,`

DbmCacheStorage, full cache:
` 'elapsed_time_seconds': 141.466789,`

FilesPipeline is not used in this test, it was the part of my bigger project.

So yeah, slight improvement over FilesystemCacheStorage, but not impressive at all.

**Comment by GeorgeA92** [comment]
<details>
  <summary>Test script (should be equal to script above in terms of this topic) </summary>

```python
import scrapy
from scrapy.crawler import CrawlerProcess
class PravdaComUaSpider(scrapy.spiders.SitemapSpider):
    name = "pravda_com_ua"
    sitemap_urls = [f"https://www.pravda.com.ua/sitemap/sitemap-2021-0{i}.xml.gz" for i in ['1', '2', '3']]
    sitemap_rules = [("ua/news/", "parse_article")]

    custom_settings = {
        'HTTPCACHE_ENABLED': True,
        'HTTPCACHE_STORAGE': 'scrapy.extensions.httpcache.DbmCacheStorage',
        'LOG_LEVEL': 'INFO'
    }

    def parse_article(self, response):
        yield {
            'img': response.css(".post_photo_news_img::attr(src)").get(),
            'title': response.css(".post_title::text").get(),
            'tags': response.css('.post_tags_item a::text').get(),
            'text': response.css('.post_text').get(),
            'date_of_publish': response.css('.post_time::text').get(),
            'source': response.css('.post__source::text').get(),
            'url': response.url
        }
process = CrawlerProcess()
process.crawl(PravdaComUaSpider)
process.start()
```  

</details>

My configuration:
```
2021-04-24 13:45:56 [scrapy.utils.log] INFO: Scrapy 2.4.0 started (bot: scrapybot)
2021-04-24 13:45:56 [scrapy.utils.log] INFO: Versions: lxml 4.2.5.0, libxml2 2.9.9, cssselect 1.1.0, parsel 1.5.1, w3lib 1.20.0, Twisted 19.7.0, Python 3.7.1 (default, Nov 24 2018, 22:14:32) [MSC v.1912 64 bit (AMD64)], pyOpenSSL 19.0.0 (OpenSSL 1.1.1h  22 Sep 2020), cryptography 2.7, Platform Windows-10-10.0.19041-SP0
```
Internet connection: wired 20Mbits/s ADSL,
Storage: 1TB HDD(2016) WDC WD10JPVX-22JC3T0

Result stats data:
<details> <summary>Default settings (Without cache), 286 seconds </summary>

```
2021-04-24 12:53:52 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 1737808,
 'downloader/request_count': 5648,
 'downloader/request_method_count/GET': 5648,
 'downloader/response_bytes': 339849565,
 'downloader/response_count': 5648,
 'downloader/response_status_count/200': 5648,
 'elapsed_time_seconds': 286.095303,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2021, 4, 24, 11, 1, 7, 348128),
 'item_scraped_count': 5645,
 'log_count/DEBUG': 11293,
 'log_count/INFO': 14,
 'request_depth_max': 1,
 'response_received_count': 5648,
 'scheduler/dequeued': 5648,
 'scheduler/dequeued/memory': 5648,
 'scheduler/enqueued': 5648,
 'scheduler/enqueued/memory': 5648,
 'start_time': datetime.datetime(2021, 4, 24, 10, 56, 21, 252825)}
2021-04-24 12:53:52 [scrapy.core.engine] INFO: Spider closed (finished)
```
</details>
<details><summary>FileSystemCache - 1st run (create cache),  470 seconds</summary>

```
2021-04-24 13:12:56 [scrapy.core.engine] INFO: Closing spider (finished)
2021-04-24 13:12:56 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 1737808,
 'downloader/request_count': 5648,
 'downloader/request_method_count/GET': 5648,
 'downloader/response_bytes': 339850431,
 'downloader/response_count': 5648,
 'downloader/response_status_count/200': 5648,
 'elapsed_time_seconds': 470.973593,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2021, 4, 24, 10, 12, 56, 40815),
 'httpcache/firsthand': 5648,
 'httpcache/miss': 5648,
 'httpcache/store': 5648,
 'item_scraped_count': 5645,
 'log_count/DEBUG': 11294,
 'log_count/INFO': 17,
 'request_depth_max': 1,
 'response_received_count': 5648,
 'scheduler/dequeued': 5648,
 'scheduler/dequeued/memory': 5648,
 'scheduler/enqueued': 5648,
 'scheduler/enqueued/memory': 5648,
 'start_time': datetime.datetime(2021, 4, 24, 10, 5, 5, 67222)}
2021-04-24 13:12:56 [scrapy.core.engine] INFO: Spider closed (finished)
```
</details>
<details><summary> FileSystemCache - 2nd run(use cache), 175 seconds </summary>

```
2021-04-24 13:19:12 [scrapy.core.engine] INFO: Closing spider (finished)
2021-04-24 13:19:12 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 1737808,
 'downloader/request_count': 5648,
 'downloader/request_method_count/GET': 5648,
 'downloader/response_bytes': 339850431,
 'downloader/response_count': 5648,
 'downloader/response_status_count/200': 5648,
 'elapsed_time_seconds': 175.759358,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2021, 4, 24, 10, 19, 12, 695105),
 'httpcache/hit': 5648,
 'item_scraped_count': 5645,
 'log_count/DEBUG': 11294,
 'log_count/INFO': 12,
 'request_depth_max': 1,
 'response_received_count': 5648,
 'scheduler/dequeued': 5648,
 'scheduler/dequeued/memory': 5648,
 'scheduler/enqueued': 5648,
 'scheduler/enqueued/memory': 5648,
 'start_time': datetime.datetime(2021, 4, 24, 10, 16, 16, 935747)}
2021-04-24 13:19:12 [scrapy.core.engine] INFO: Spider closed (finished)
```
</details>

<details> <summary>DbmCache 1st run (create cache), 316 seconds</summary>

```
2021-04-24 13:33:54 [scrapy.core.engine] INFO: Closing spider (finished)
2021-04-24 13:33:54 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 1737808,
 'downloader/request_count': 5648,
 'downloader/request_method_count/GET': 5648,
 'downloader/response_bytes': 339794646,
 'downloader/response_count': 5648,
 'downloader/response_status_count/200': 5648,
 'elapsed_time_seconds': 316.136729,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2021, 4, 24, 10, 33, 54, 159039),
 'httpcache/firsthand': 5648,
 'httpcache/miss': 5648,
 'httpcache/store': 5648,
 'item_scraped_count': 5645,
 'log_count/DEBUG': 11294,
 'log_count/INFO': 15,
 'request_depth_max': 1,
 'response_received_count': 5648,
 'scheduler/dequeued': 5648,
 'scheduler/dequeued/memory': 5648,
 'scheduler/enqueued': 5648,
 'scheduler/enqueued/memory': 5648,
 'start_time': datetime.datetime(2021, 4, 24, 10, 28, 38, 22310)}
2021-04-24 13:33:54 [scrapy.core.engine] INFO: Spider closed (finished)
```
</details>

<details> <summary>DbmCache 2nd run (use cache),  162 seconds</summary>

```
2021-04-24 13:37:47 [scrapy.core.engine] INFO: Closing spider (finished)
2021-04-24 13:37:47 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 1737808,
 'downloader/request_count': 5648,
 'downloader/request_method_count/GET': 5648,
 'downloader/response_bytes': 339794646,
 'downloader/response_count': 5648,
 'downloader/response_status_count/200': 5648,
 'elapsed_time_seconds': 162.383514,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2021, 4, 24, 10, 37, 47, 594049),
 'httpcache/hit': 5648,
 'item_scraped_count': 5645,
 'log_count/DEBUG': 11294,
 'log_count/INFO': 12,
 'request_depth_max': 1,
 'response_received_count': 5648,
 'scheduler/dequeued': 5648,
 'scheduler/dequeued/memory': 5648,
 'scheduler/enqueued': 5648,
 'scheduler/enqueued/memory': 5648,
 'start_time': datetime.datetime(2021, 4, 24, 10, 35, 5, 210535)}
2021-04-24 13:37:47 [scrapy.core.engine] INFO: Spider closed (finished)
```
</details>

<details> <summary> DmbCache 3rd run (use cache), (LOG_LEVEL:Info added to settings), 135 seconds</summary>

```
2021-04-24 13:42:12 [scrapy.core.engine] INFO: Closing spider (finished)
2021-04-24 13:42:12 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 1737808,
 'downloader/request_count': 5648,
 'downloader/request_method_count/GET': 5648,
 'downloader/response_bytes': 339794646,
 'downloader/response_count': 5648,
 'downloader/response_status_count/200': 5648,
 'elapsed_time_seconds': 131.061901,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2021, 4, 24, 10, 42, 12, 941401),
 'httpcache/hit': 5648,
 'item_scraped_count': 5645,
 'log_count/INFO': 12,
 'request_depth_max': 1,
 'response_received_count': 5648,
 'scheduler/dequeued': 5648,
 'scheduler/dequeued/memory': 5648,
 'scheduler/enqueued': 5648,
 'scheduler/enqueued/memory': 5648,
 'start_time': datetime.datetime(2021, 4, 24, 10, 40, 1, 879500)}
2021-04-24 13:42:12 [scrapy.core.engine] INFO: Spider closed (finished)
```
</details>

@dchaplinsky, @Gallaecio 
From this results I don't see anything unexpected from scrapy side

**Comment by dchaplinsky** [comment]
@GeorgeA92 so effectively, that's an expected behavior? In my case the gain from working solely from cache is less that 2x (which makes me really sad). Is there an option to optimize/utilize more CPU (cpu cores)? Or because of reactor, this is the maximum, that reactor might provide?

**Comment by GeorgeA92** [comment]
@dchaplinsky 

>  that's an expected behavior?

It is not expected that website allows to continiously send ~1500+ requests per minute from single IP without IP bans or other anti-bot restrictions from server side.  (this is very unique case)
Usually it is not.. polite to send that amount of requests with that rate.
From my point of view ~1500+ requests per minute sending rate from single IP - is not slow, it is already too much.

>  In my case the gain from working solely from cache is less that 2x (which makes me really sad)

On nearly all of cases websites give IP bans (temp or permanent) with that requests sending rate. First thing that we usually do in this cases is to limit requests with `DOWNLOAD_DELAY` setting.
`DOWNLOAD_DELAY = 1` (~60 requests per minute)
`DOWNLOAD_DELAY = 0.5` (~120 requests per minute)

Solution with enabled HttpCache will work faster by 10x and more as @Gallaecio said comparing to this more... ban safe scrapy configuration limited by `DOWNLOAD_DELAY` setting 

> Is there an option to optimize/utilize more CPU (cpu cores)?

I think that In this case(~1500+ requests per minute) working performance limited by I/O bottleneck (not CPU, and not Internet connection quality).
My conclusion based on performance difference between `FilesystemCacheStorage` and `DbmCacheStorage`. 
`DbmCacheStorage` - is less I/O intesnsive comparing to `FilesystemCacheStorage` (at least with relatively low amount of cahced data).

> Or because of reactor, this is the maximum, that reactor might provide?

As far as I know (not 100% sure) usage of reactor features mosly aimed to optimize network and cpu performance (not I/O).
reading/writing from/to cache is not related to reactor.

**Comment by dchaplinsky** [comment]
Erm, so it's not cache, that looks too slow to me, but my data source, which is way too fast? :)

Anyway, any clues, where I should look/profile for a better performance when working from cache only? 2000 items per minute doesn't sound like a massive number to me (and my io metrics also looks reasonably low).

For example, I currently have fully cached version of a website that has 790k of pages (and I spent a week caching it) and now I need to amend a parsing part cause some pages are styled differently and causing parsing errors. And full re-run will tale around 8 hours.

@omab, maybe you can give me a hint?

**Comment by omab** [comment]
@dchaplinsky, sorry, but I can't help with any guidance here, I've been disconnected from Scrapy for a very long time now. Good luck!

**Comment by GeorgeA92** [comment]
@dchaplinsky 
>  I currently have fully cached version of a website that has 790k of pages (and I spent a week caching it) and now I need to amend a parsing part cause some pages are styled differently and causing parsing errors. And full re-run will tale around 8 hours.

> 2000 items per minute doesn't sound like a massive number to me (and my io metrics also looks reasonably low).

> Anyway, any clues, where I should look/profile for a better performance when working from cache only?

For Your case reading all data directly from cache storage sequentially (ignoring requests order from spider) as proposed here  https://github.com/scrapy/scrapy/issues/2365 (but not implemented) can be more I/O efficient and faster (theoretically).
Both `FilesystemCacheStorage` and `DbmCacheStorage` implemented as key/value storages (SHA1 hash from request content used as key).

**Comment by dchaplinsky** [comment]
Thanks.

Maybe I'll try some 3'rd party caching backends for in-memory key-value
storages just to eliminate the disk i/o noise and see if that helps.

**Comment by Gallaecio** [comment]
Thank you for your detailed analysis, @GeorgeA92, and thank you as well @dchaplinsky for your detailed report and following up. Given your findings, and that we already have https://github.com/scrapy/scrapy/issues/2365 for a potential performance improvement of such scenarios, I think we can close this.

**Comment by dchaplinsky** [comment]
@Gallaecio, don't want to reopen this issue, but I made few more tests using standard caching backends on a ram disk (mac os x).

This is how I created it:
`diskutil erasevolume HFS+ 'My Disk' `hdiutil attach -nomount ram://8388608`

First run (cache empty,  `DbmCacheStorage`, LTE mobile internet)
elapsed_time_seconds: seconds 243.758387

Second run (full cache)
elapsed_time_seconds: 138.585838

Third run (full cache)
elapsed_time_seconds: 130.088653


First run (cache empty,  `FilesystemCacheStorage`, LTE mobile internet)
elapsed_time_seconds: 231.93352

Second run (full cache)
elapsed_time_seconds: 133.036736

Third run (full cache)
elapsed_time_seconds: 129.611479

On all runs I've got the same  'item_scraped_count': 5645

So to me it clearly not an IO issue.

Would you mind if I post more finds like that here?

**Comment by dchaplinsky** [comment]
Lowering CONCURRENT_ITEMS down to 1 gives a 10% speedup, changing numbers of concurrent request has no impact, changing reactor to asyncio has no impact.

**Comment by Gallaecio** [comment]
Regardless of your test results, I believe that https://github.com/scrapy/scrapy/issues/5105#issuecomment-826308535 remains true, and that the goal to improve performance of cache reads in Scrapy is tracked by https://github.com/scrapy/scrapy/issues/2365.

**Comment by GeorgeA92** [comment]
@dchaplinsky 

> website that has 790k of pages ... and now I need to amend a parsing part cause some pages are styled differently and causing parsing errors. And full re-run will tale around 8 hours.

I see 2 other directions (is not related to I/O efficiency of working with cache):
1.Get failed urls with error from [logs](https://docs.scrapy.org/en/2.5/topics/logging.html#logging-settings) (assuming that error urls mentioned in log entries) Reconfigure spider to parse only previously failed urls. 
-> parse only failed urls - not all 790k pages.

2.Or/And "divide" webpages into several smaller parts and scale/run it in [distributed](https://docs.scrapy.org/en/2.5/topics/practices.html#distributed-crawls) manner.
->in other words: increase total cache processing rate by increasing number of servers.
