### ISSUE TITLE
[Question] What method does Scrapy use to expire files in FilePipeline?

### ISSUE THREAD

**Issue by felinto-dev** [scrapy/scrapy#5120]
What method does Scrapy use to expire files in FilePipeline?

https://docs.scrapy.org/en/latest/topics/media-pipeline.html#file-expiration

I looked at the documentation on this, but not much is informed about which algorithm is used to define whether a file needs to be downloaded again or not.

**Comment by wRAR** [comment]
The pipeline just looks at the file modified time as far as I can see.
