### ISSUE TITLE
Running spiders from inside code?

### ISSUE THREAD

**Issue by lamaqdahodwala** [scrapy/scrapy#5136]
## Summary

I want to make a UI to go along with Scrapy. However, this is not possible because the only way to scrape pages (at least as far as I know) is to use the command line tool. Could you guys add a way to execute spiders from code, or show me an already existing way?

## Motivation

This supports many use cases, ranging from simple discord bots to entire websites based on web scraping. 

## Describe alternatives you've considered

Alternate solutions I have considered were using `os.system` and `subprocess.run`. However, these didn't suit my needs because of the fact that both ignore any `virtualenv`s set up previously, making it more difficult to interface with Scrapy

## Additional context

Ideally, it would be contained in a single function, where anywhere in the tree, you could call and it would start the spider. ie. 
```
scrapy.StartSpider("spider_name")
```

**Comment by wRAR** [comment]
You seem to have missed https://docs.scrapy.org/en/latest/topics/practices.html#run-scrapy-from-a-script

**Comment by lamaqdahodwala** [comment]
Thanks a bunch dude!
