### ISSUE TITLE
[COOKIES SESSION]

### ISSUE THREAD

**Issue by AndreuJove** [scrapy/scrapy#5151]
Dear Scrapy,

There is no way you can use the same cookies for every start_url and its children. Or somehow parse the webs one by one. Using CONCURRENT_REQUESTS = 1 it's not enough. Is there any feature for this?

Thanks a lot,

Andreu

**Comment by wRAR** [comment]
This is the Scrapy issue tracker. Please direct your questions to https://stackoverflow.com/ or similar resources.
