### ISSUE TITLE
Place for beginners to ask dumb questions?

### ISSUE THREAD

**Issue by chrisjdixon** [scrapy/scrapy#5172]
I'm having a hard time figuring a few things out as I'm not the world's best programmer. I often don't know if I've done something wrong in Python or something specific to Scrapy, and there aren't a great deal of beginner level examples out there.

I'm looking for somewhere I could ask a few dumb questions, and I expect that Github isn't the best place. Ideally I'm looking for some kind of chat room where I can informally ask things and anyone kind enough could point out what likely very stupid and small thing I'm doing wrong. I only need a few tips / hints when I get stuck. I've already asked the IRC channel but no responses there.

Maybe there's a Discord / Slack server somewhere I could ask? There was a [reddit post the other day about this](https://www.reddit.com/r/scrapy/comments/nf6hch/slack_server_dedicated_to_scrapy/), but it seems there isn't one. Perhaps one could be created?

Sorry if it's not appropriate to ask about this kind of thing here but I don't know where else to ask. Please feel free to remove this / tell me to go away. Thanks for any help!

**Comment by Gallaecio** [comment]
IRC is still used, there is simply not always people around with time, the knowledge and the wish to answer.

As [documented](https://docs.scrapy.org/en/latest/), however, the best place to ask question is StackOverflow. Preparing a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to include in your question can lead you to find the root issue on your own.

**Comment by Gallaecio** [comment]
As for creating a new place where the Scrapy community can meet, I have nothing against it, but I’m not sure how much it would change things. It could be argued that a nicer platform than IRC may attract more people, but I’m not sure to what extent.

**Comment by chrisjdixon** [comment]
Yeah, I could try Stackoverflow, but my problem is often that I often don't know if the problem is caused by some framework (Scrapy), Python, or something else. To say the least I haven't found Stackoverflow to be friendly to beginners who try hard to write good questions to their best understanding. And I often only need a hint or two while learning something.

Maybe Scrapy could create a [Discord](https://discord.com/brand-new) channel? Having used both IRC and Discord I've found Discord far better. I've seen Discord channels start with 2-3 users and flourish over time. And it's free, too, so if it doesn't attract any interest no harm done 😃

**Comment by Gallaecio** [comment]
Let’s see what happens: https://discord.gg/fbCHpAm6KM

**Comment by Cyb-Umair** [comment]
Getting started with contributions to Scrapy?

I have seen that there are several GoodFirstIssue tags in the issues. How do I proceed to pick them up?

**Comment by umairnsr87** [comment]
Getting started with contributions to Scrapy?

I have seen that there are several GoodFirstIssue tags in the issues. How do I proceed to pick them up?

**Comment by Gallaecio** [comment]
> I have seen that there are several GoodFirstIssue tags in the issues. How do I proceed to pick them up?

No need to ask for permission, you can create a pull request to solve any issue and [mark it as resolving that issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

If you worry about duplicating code, please check the issue thread for references to active work on the issue.

**Comment by Gallaecio** [comment]
Well, it seems like Discord has really taken off, so I’m happily closing this.
