### ISSUE TITLE
spider.state attribute is not documented

### ISSUE THREAD

**Issue by kmike** [scrapy/scrapy#5174]
spider.state is not mentioned on https://docs.scrapy.org/en/latest/topics/spiders.html; it is only mentioned here: https://docs.scrapy.org/en/latest/topics/jobs.html#keeping-persistent-state-between-batches. It'd be nice to document this attribute.

**Comment by CaptainArnav** [comment]
@kmike is this a good issue for my first time contributing to scrapy?

**Comment by Gallaecio** [comment]
This would may be a good first issue, yes, given https://docs.scrapy.org/en/latest/topics/jobs.html#keeping-persistent-state-between-batches

**Comment by ahudspeth199** [comment]
Can I still get involved with this? I am new to python coding not sure where to start?

**Comment by wRAR** [comment]
Closed by #5244.
