### ISSUE TITLE
Improve structure of Scrapy settings documentation

### ISSUE THREAD

**Issue by pablohoffman** [scrapy/scrapy#518]
#515 got me thinking that some Scrapy settings are missed because they aren't documented in the main settings page (`docs/topics/settings.rst`).

One approach I came up for fixing this was to generate a list of all settings (regardless of which file/doc they're documented) but i couldn't find a way in sphinx to generate a list of all entities of a single role (in this case, "setting").

An alternative approach would to adopt the policy/convention of documenting all settings in the `settings.rst` file (perhaps splitting them in one section per component/middleware/etc) and refer to that file from the other docs (for example, donwloader middlewares in `downloader-middleware.rst` would refer to `settings.rst` for their settings documentation).

Currently, we used a mixed (probably half-transitioned) approach where we document settings separately (in the file where their component is documented) and also mix core & component settings in `settings.rst`. This proposal also aims to resolve that inconsistency.

Thoughts?

**Comment by kmike** [comment]
+1, a good suggestion

**Comment by eliasdorneles** [comment]
So, it seems it isn't very straightforward to create a custom index for a role with Sphinx. The built-in functionality for indices only gives control over the global index and the modules index, no way to create a custom index.

I couldn't find any Sphinx extension that helps with it either, I'll look into building an extension for this myself.

**Comment by eliasdorneles** [comment]
Just a quick report of my efforts on these: I've got this partially working, but there are some issues to solve.

I was able to write code to find the references to the `setting` directives, but referencing back is a bit of a challenge. The main problem is that the settings are referenced multiple times in the docs, so we probably want to filter it and somehow say which of the references is the one that shouldbe the canonical place to refer back. I _think_ we might need to create a new directive for it, not sure.

I also wasn't able yet to figure out exactly how to reference back (something goes wrong when executing the code to resolve references, I'm probably missing something). I'd love to get the input from someone more familiar to Sphinx. =)

For the curious among you, you can check the current code here (it made sense to just add it in the `scrapydocs` extension): https://github.com/eliasdorneles/scrapy/blob/building-settingslist-from-docs/docs/_ext/scrapydocs.py
