### ISSUE TITLE
Handle form when input field doesn't have name attribute

### ISSUE THREAD

**Issue by gCass** [scrapy/scrapy#5183]
Actually I'm trying to scrape this page logging into it: https://login.liv-ex.com/login.
I've seen the usage of the **scrapy.FormRequest.from_response** to fill a form, but as a matter of fact the input fields don't have a name attribute, therefore is not possible to specify the formdata parameter of the object.

This is how the input fields looklike.
` <input class="input" id="email" type="email" placeholder="This is your email address" >`
and 
` <input class="input" id="password" type="password" placeholder="Enter your password">`

And they're used from a javascript function to login, called when the submit button of the form is clicked.

There is a way to use **scrapy.FormRequest.from_response** to fill a form when input fields haven't the name attribute?

**Comment by wRAR** [comment]
Note that the website doesn't work for me.

> therefore is not possible to specify the formdata parameter of the object.

Not sure what does this mean. It shouldn't stop you from passing the formdata dict directly.

> This is how the input fields looklike.

If they don't have data, `from_response` won't do anything useful for them anyway. If they do, it may be easier just to retrieve them manually.

In any case, this doesn't look a Scrapy bug and I don't see what can be improved in Scrapy regarding this. Please direct your questions to https://stackoverflow.com/ or similar resources. Feel free to reopen this with a valid bug report/feature request.
