### ISSUE TITLE
CSVFeedSpider - Multiple threads / processing

### ISSUE THREAD

**Issue by Caffe1neAdd1ct** [scrapy/scrapy#5187]
## Summary

Would it be possible to process csv/xml files using the scrapy CSV/XML FeedSpider classes with multiprocessing to speed up ingestion of data? 

I've had a quick go at this by overriding the parse_rows / parse_row implementation but couldn't see a way to implement multiprocessing as hit pickle / framework errors.

Would be great to be able to re-use the idea from normal spiders "CONCURRENT_REQUESTS" to drive threads/processes for csv/xml processing.

**Comment by wRAR** [comment]
> Would it be possible to process csv/xml files using the scrapy CSV/XML FeedSpider classes with multiprocessing to speed up ingestion of data?

Which parts of the workflow do you propose to hand over to multiprocessing and what should that improve?

> Would be great to be able to re-use the idea from normal spiders "CONCURRENT_REQUESTS" to drive threads/processes for csv/xml processing.

`CONCURRENT_REQUESTS` is not related to threads/processes.
