### ISSUE TITLE
FAILED INSTALLATION OF SCRAPY ON UBUNTU 18.04, PIP 21.1.2 

### ISSUE THREAD

**Issue by effluviens** [scrapy/scrapy#5189]
### Description

When trying to install on a python scrapy with **pip install scrapy** command the installation halts after 2 warnings coming from Cryptography package located in their dhcrypto.py (line 15) and util.py(line 19) saying **int_from_bytes is deprecated, use int.from_bytes instead**
Remark was added as : **Defaulting to user installation because normal site-packages is not writeable**
Same behavior when trying with **pip3 install scrapy**
knowing that pip version is 21.1.2, Python version 3.6.9 

### Steps to Reproduce

1. install pip with :    sudo apt install python3-pip

2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]
Installation normally complete and scrapy is responding to 

**Actual behavior:** [What actually happens]
installation is interrupted after  a series of Requirements already satisfied

/usr/bin$ python3 -m pip install scrapy

/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
from cryptography.utils import int_from_bytes

/usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes

Defaulting to user installation because normal site-packages is not writeable

Requirement already satisfied: scrapy in /home/cf/.local/lib/python3.6/site-packages (2.5.0)
Requirement already satisfied: queuelib>=1.4.2 in /home/cf/.local/lib/python3.6/site-packages (from scrapy) (1.6.1)
Requirement already satisfied: lxml>=3.5.0 in /usr/lib/python3/dist-packages (from scrapy) (4.2.1)
Requirement already satisfied: h2<4.0,>=3.0 in /home/cf/.local/lib/python3.6/site-packages (from scrapy) (3.2.0)
Requirement already satisfied: PyDispatcher>=2.0.5 in /home/cf/.local/lib/python3.6/site-packages (from scrapy) (2.0.5)
Requirement already satisfied: pyOpenSSL>=16.2.0 in /home/cf/.local/lib/python3.6/site-packages (from scrapy) (20.0.1)
Requirement already satisfied: Twisted[http2]>=17.9.0 in /home/cf/.local/lib/python3.6/site-packages (from scrapy) (21.2.0)
Requirement already satisfied: service-identity>=16.0.0 in /home/cf/.local/lib/python3.6/site-packages (from scrapy) (21.1.0)
Requirement already satisfied: zope.interface>=4.1.3 in /home/cf/.local/lib/python3.6/site-packages (from scrapy) (5.4.0)
Requirement already satisfied: cssselect>=0.9.1 in /home/cf/.local/lib/python3.6/site-packages (from scrapy) (1.1.0)
Requirement already satisfied: itemadapter>=0.1.0 in /home/cf/.local/lib/python3.6/site-packages (from scrapy) (0.2.0)
Requirement already satisfied: w3lib>=1.17.0 in /home/cf/.local/lib/python3.6/site-packages (from scrapy) (1.22.0)
Requirement already satisfied: cryptography>=2.0 in /home/cf/.local/lib/python3.6/site-packages (from scrapy) (3.4.7)
Requirement already satisfied: protego>=0.1.15 in /home/cf/.local/lib/python3.6/site-packages (from scrapy) (0.1.16)
Requirement already satisfied: itemloaders>=1.0.1 in /home/cf/.local/lib/python3.6/site-packages (from scrapy) (1.0.4)
Requirement already satisfied: parsel>=1.5.0 in /home/cf/.local/lib/python3.6/site-packages (from scrapy) (1.6.0)
Requirement already satisfied: cffi>=1.12 in /home/cf/.local/lib/python3.6/site-packages (from cryptography>=2.0->scrapy) (1.14.5)
Requirement already satisfied: pycparser in /home/cf/.local/lib/python3.6/site-packages (from cffi>=1.12->cryptography>=2.0->scrapy) (2.20)
Requirement already satisfied: hyperframe<6,>=5.2.0 in /home/cf/.local/lib/python3.6/site-packages (from h2<4.0,>=3.0->scrapy) (5.2.0)
Requirement already satisfied: hpack<4,>=3.0 in /home/cf/.local/lib/python3.6/site-packages (from h2<4.0,>=3.0->scrapy) (3.0.0)
Requirement already satisfied: jmespath>=0.9.5 in /home/cf/.local/lib/python3.6/site-packages (from itemloaders>=1.0.1->scrapy) (0.10.0)
Requirement already satisfied: six>=1.6.0 in /usr/lib/python3/dist-packages (from parsel>=1.5.0->scrapy) (1.11.0)
Requirement already satisfied: pyasn1-modules in /home/cf/.local/lib/python3.6/site-packages (from service-identity>=16.0.0->scrapy) (0.2.8)
Requirement already satisfied: pyasn1 in /home/cf/.local/lib/python3.6/site-packages (from service-identity>=16.0.0->scrapy) (0.4.8)
Requirement already satisfied: attrs>=19.1.0 in /home/cf/.local/lib/python3.6/site-packages (from service-identity>=16.0.0->scrapy) (21.2.0)
Requirement already satisfied: Automat>=0.8.0 in /home/cf/.local/lib/python3.6/site-packages (from Twisted[http2]>=17.9.0->scrapy) (20.2.0)
Requirement already satisfied: constantly>=15.1 in /home/cf/.local/lib/python3.6/site-packages (from Twisted[http2]>=17.9.0->scrapy) (15.1.0)
Requirement already satisfied: hyperlink>=17.1.1 in /home/cf/.local/lib/python3.6/site-packages (from Twisted[http2]>=17.9.0->scrapy) (21.0.0)
Requirement already satisfied: incremental>=16.10.1 in /home/cf/.local/lib/python3.6/site-packages (from Twisted[http2]>=17.9.0->scrapy) (21.3.0)
Requirement already satisfied: priority<2.0,>=1.1.0 in /home/cf/.local/lib/python3.6/site-packages (from Twisted[http2]>=17.9.0->scrapy) (1.3.0)
Requirement already satisfied: idna>=2.5 in /usr/lib/python3/dist-packages (from hyperlink>=17.1.1->Twisted[http2]>=17.9.0->scrapy) (2.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.6/dist-packages (from zope.interface>=4.1.3->scrapy) (57.0.0)

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions
pip version is 21.1.2, 
Python version 3.6.9 
Ubuntu 18.04.2 LTS

Please paste here the output of executing `scrapy version --verbose` in the command line.

Not found command

### Additional context

Any additional information, configuration, data or output from commands that might be necessary to reproduce or understand the issue. Please try not to include screenshots of code or the command line, paste the contents as text instead. You can use [GitHub Flavored Markdown](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) to make the text look better.

**Comment by wRAR** [comment]
> Requirement already satisfied: scrapy in /home/cf/.local/lib/python3.6/site-packages (2.5.0)

You already have it installed.
