### ISSUE TITLE
pycharm terminal window unable to pick scrapy

### ISSUE THREAD

**Issue by vimalva777** [scrapy/scrapy#5192]
Hi ,new to scrapy and python

![Untitled](https://user-images.githubusercontent.com/85609270/123160597-06d40400-d48c-11eb-8ba4-e925ff88d8df.png)

while giving input in command prompt >>>(venv) F:\python study\pythonscrapy>scrapy startprojecct quatetutorial

erorr is showing:   'scrapy' is not recognized as an internal or external command,
                               operable program or batch file.
even i tried with: cd myapp,ls commands but the error coming same

**Comment by vimalva777** [comment]
scrapy is installed

**Comment by wRAR** [comment]
This is a problem with your PATH configuration, not with Scrapy.

**Comment by vimalva777** [comment]
Thanks
