### ISSUE TITLE
Cannot install with conda on python 3.9.5

### ISSUE THREAD

**Issue by ahgraber** [scrapy/scrapy#5195]
I have a conda environment with python 3.9.* (I have tried with 3.9.2-5 specifically) and I get the following error when I try to install scrapy with `conda` or `mamba`:

```
Pinned packages:
  - python 3.9.5

Encountered problems while solving:
  - package scrapy-2.5.0-py38h50d1736_0 requires python >=3.8,<3.9.0a0, but none of the providers can be installed
```

I have tried:
`mamba install conda-forge::scrapy`, which tries to install scrapy 1.8.0
`mamba install conda-forge::scrapy=2.5`
`mamba install scrapy=2.5`

all generate the same error message.

It does not appear to be an issue with dependencies, since none are mentioned in any of the error message.

**Comment by ahgraber** [comment]
Further, none of the [files on the conda repo](https://anaconda.org/conda-forge/scrapy/files?page=1) appear to be labelled for python 3.9.

Could you release a version for python 3.9?

**Comment by wRAR** [comment]
Related: 
https://github.com/conda-forge/scrapy-feedstock/pull/56
https://github.com/scrapy/scrapy/pull/5113

**Comment by holymonson** [comment]
@Gallaecio Hi, I'm not sure whether 2.6 milestone is close, is it possible to release 2.5.1 for this issue?

**Comment by Gallaecio** [comment]
We are not currently considering a release of 2.5.1 for this issue. As for 2.6.0, at the moment releasing in august seems likely, but it is not set in stone.

**Comment by beatslikeahelix** [comment]
Any updates on this issue? Can we indeed expect 2.6.0 to have a Python 3.9 compatible version?

**Comment by Gallaecio** [comment]
Indeed, https://github.com/scrapy/scrapy/pull/5113 has been merged. Closing this now to avoid confusion about that.
