### ISSUE TITLE
LinkExtractor background url in css content

### ISSUE THREAD

**Issue by agnauck** [scrapy/scrapy#5196]
I am working on a spider and need to download also images which are assigned in css classes.
Can someone point to an example of give me some hints how to achieve this with the LinkExtractor?

I would like my spider to follow the urls in the css files similar like it does in html files:

```
links = LinkExtractor(
                    canonicalize=True,
                    unique=True,
                    tags=('link', 'a', 'script', 'img', 'amp-img'),
                    attrs=('href', 'src'),
                    deny_extensions=[]                    
                ).extract_links(response)
```

Thanks

**Comment by wRAR** [comment]
This is the issue tracker for Scrapy. Please direct your questions to https://stackoverflow.com/ or similar platforms.
