### ISSUE TITLE
set Pipeline on Items

### ISSUE THREAD

**Issue by alikazemkhanloo** [scrapy/scrapy#5227]
## Summary

On each `scrapy.Item`, there would be a meta value to determine which pipeline will be used for this particular Item.

## Motivation

I wanted to crawl two different websites. they share the same data but are differently structured. I wanted to create multiple spiders in one project, and `yield` different `Item`s. 

But each `Item` will be passed to all pipelines. as a workaround I created two different projects for each website. But I have to duplicate my settings and project-related files.

## Describe alternatives you've considered

The only solution is to check `Item` type inside each pipeline to decide if I have to process this `Item` or not. This doesn't feel right. The best pythonic way is to determine the pipeline in the `Item` itself. it can be a `Meta` class inside `Item` class.

## Example code 
We can use something like below code to determine the appropriate pipeline for this particular `Item`
```python
class MyItem(scrapy.Item):
    class Meta:
        pipeline = MyPipeline

    name = scrapy.Field()
```

I hope it is crystal clear what the problem is and what I mean as the solution.

**Comment by wRAR** [comment]
I don't think it's "the best pythonic way". Also having one and only one pipeline for each item type is a narrow case: Scrapy supports multiple pipelines called in a specified order, and it also supports many different kinds of objects as items, not all of which can contain additional metadata. Dispatching by checking the item type or name/other attributes of the spider is currently the best practice as far as I know,

**Comment by Gallaecio** [comment]
The approach suggested by @wRAR should work well for you, and is not that far off from what you are suggesting.

Note that you can also set per-spider item pipelines through `Spider.custom_settings`.

**Comment by alikazemkhanloo** [comment]
To rule out "one and only one pipeline for item type", we can check if the `pipeline/pipelines` exists on `Meta` class of the item, if it does not exist, it gets passed to all pipelines. Other types of objects not having a meta can be processed in all pipelines normally.

I didn't know about `Spider.custom_settings`. This actually solves my problem in which each spider needs its own pipeline. 

There may be some rare situations in which an `Item` needs its own pipelines. It is controversial if we need such a feature or just check the item type inside pipelines.

**Comment by wRAR** [comment]
> To rule out "one and only one pipeline for item type", we can check if the pipeline/pipelines exists on Meta class of the item, if it does not exist, it gets passed to all pipelines.

This is still suitable only for some cases, as some pipelines should process all items even when others are specific to one type.

> Other types of objects not having a meta can be processed in all pipelines normally.

So this feature is not suitable for all item kinds, even though it is equally useful to all of them.

> There may be some rare situations in which an Item needs its own pipelines. It is controversial if we need such a feature or just check the item type inside pipelines.

TBH it's not controversial for me: the case is indeed rare, and a complete implementation of the feature you described is too complicated for reasons I stated and for some additional ones, while an incomplete one shouldn't be added to Scrapy.
