### ISSUE TITLE
Deprecate Reppy support

### ISSUE THREAD

**Issue by Gallaecio** [scrapy/scrapy#5230]
https://github.com/scrapy/scrapy/issues/5226#issuecomment-897621867

**Comment by umairnsr87** [comment]
https://docs.scrapy.org/en/latest/topics/downloader-middleware.html#built-in-downloader-middleware-reference @Gallaecio  I am seeing that **Reappy Parser** Do I just need to mention there that "only work with Python 3.8 and earlier" or do I need to make some other changes. Thanks

**Comment by Gallaecio** [comment]
That’s it.

Please, do it as part of https://github.com/scrapy/scrapy/issues/5226, this ticket is for potential future work removing deprecating support for Reppy.

**Comment by Gallaecio** [comment]
Neither. I would not bother changing the docs, but this needs to remain open until we actually deprecate Reppy support, to be done around Oct 14th 2023. i.e. 1 year before [Python 3.8 end of life](https://endoflife.date/python), as [agreed](https://github.com/scrapy/scrapy/issues/5226#issuecomment-897621867).

**Comment by felipeboffnunes** [comment]
Nice, thanks @Gallaecio !

![giphy](https://user-images.githubusercontent.com/51033921/225641825-40192744-db04-43e0-85b4-4b66bad5245f.gif)

**Comment by wRAR** [comment]
This is now ready.
