### ISSUE TITLE
Is scrapyd-client accepting new maintainers?

### ISSUE THREAD

**Issue by jpmckinney** [scrapy/scrapy#5240]
*Original: https://github.com/scrapy/scrapyd-client/issues/81*

The PRs are fairly simple and repetitive, and the issues are a mix of support requests (no bug/feature to add) or small changes.

We ([Open Contracting Partnership](https://www.open-contracting.org)) use scrapyd-client daily to deploy new spiders to a scrapyd instance ([our Scrapy project](https://github.com/open-contracting/kingfisher-collect)), so we're interested in this library at least being interoperable with the latest version of Scrapy (which it is not now).

I am the maintainer of many PyPi projects, notably [csvkit](https://csvkit.readthedocs.io/en/latest/), which is [many](https://pypistats.org/packages/csvkit) [times](https://pypistats.org/packages/scrapyd-client) more popular than this library, in terms of downloads, frequency of issues reported, etc.

**Comment by wRAR** [comment]
Thank you for making this more visible to us, we are currently discussing this internally.
