### ISSUE TITLE
Bypassing Captcha

### ISSUE THREAD

**Issue by iPatavatsizz** [scrapy/scrapy#5241]
## Summary

I think Scrapy can bypass captcha security.

Briefly, I cannot use Scrapy for 3 days since I installed to parse the xml data of the site of I want because of I realized that Scrapy is stuck on redirecting process with captcha. Neither shell or spider/view works.

`2021-09-15 13:53:23 [scrapy.downloadermiddlewares.redirect] DEBUG: Redirecting (301) to <GET https://www.hepsiburada.com/robots.txt> from <GET http://hepsiburada.com/robots.txt>
2021-09-15 13:56:23 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET ht
tps://www.hepsiburada.com/robots.txt> (failed 1 times): User timeout caused connection failure: Getting https://www.hepsiburada.com/robots.txt took longer than 180.0 seconds..
`
Again and again reloads but it doesn't work because of captcha.

**Comment by wRAR** [comment]
This doesn't look like a Scrapy issue. Please use platforms like https://stackoverflow.com/ to ask questions about your code.

**Comment by iPatavatsizz** [comment]
Scrapy can't pass captcha because of it's not good enough to pass because of lack headers it sends. I copied the headers of I sent to site on Chrome and used them on both requests and aiohttp libraries to bypass and I succeed. So, I think it is Scrapy related. And solution was already found, thanks.
