### ISSUE TITLE
Processing Complex Nested Items

### ISSUE THREAD

**Issue by boulderob** [scrapy/scrapy#5242]
I've spent a week exploring the scrapy documentation and issues as well as exploring google and more specifically stack as suggested in many issues here.  I'm resorting here for some guidance because I'm not finding any answers.

In bs4, the callbacks are what i would call "synchronously chained", so that the parsing tied to a series of related requests can all "bubble" up successive returns dicts through the series of nested callback so that you can *return a single very complex nested object*.

For example, say I am crawling a series of nested levels where you have multiple items in each level like this where you have a dict of dicts  of dicts of dicts, etc (nested collections).

- world regions
   -  countries
     -  regions
       - sub regions
         - sub sub regions

That's entirely possible in bs4.  **BUT I want to do the same thing using scrapy**.

Correct me if I'm wrong but it seems that by design, scrapy lacks the ability to chain the parsing callback return values to one another.  Meaning that you can NOT "bubble up" the nested items as return values back up to all parents *to create and return a SINGLE COMPLEX DICT / OBJECT like I describe above*. 

Though you can pass parent callback info *down* to child callback via next request kwargs in scrapy, *you can only ever return / yield single atomic items (even if nested) at any level of the nesting aka any callback depth*.  Which is to say that you can't aggregate and return an entire collection tree for say a given country like SWEDEN, and then ITALY and then FRANCE (and then etc) in a scrapy callback. 

So how can I build the single, nested, complex "world region" to "sub sub region" native dict or json tree that I want in scrapy?   I've not seen any relevant examples or stack posts that really address this situation.  most scrapy examples seem to usually be based on situations where individual yielded items are atomic, follow the same "contract" and easy to aggregate as output to a simple json or cvs file because each item is the same "kind" of row (the Item Pipeline class). 

In sum, scrapy seems to be very single / atomic Item centric.  What's the best way to return and aggregate hierarchical / nested data in the scrapy request callback chain so that we can return and then output a single complex object in scrapy?  If I can't build and return the single nested object in the callback chain itself, how / where do I queue the items in the pipeline before outputting them so that my "intercept method" can resolve and build the complex obj from the individual items to get what I want?

Thanks

**Comment by wRAR** [comment]
As callbacks are asynchronous you indeed cannot bubble data up to the earlier ones (they are already finished at this point). Currently the usual ways to combine data from multiple requests are either writing a single big callback with https://github.com/rmax/scrapy-inline-requests (there is some work in progress to replace it with native ways to do the same) or collecting the data in a raw form and aggregating it after it's collected (either collecting it in a variable and aggregating when the spider finishes working or outputting it into an intermediate storage and aggregating with an external tool).

And Scrapy is indeed more suitable for flat items or items where all the data, even if nested, is taken from one or two pages. This also matches that many of the data processing techniques popular in the ecosystem take table data. Even your example for regions is often just denormalized to have e.g. a "region" and "subregion" fields in each flat item which simplifies both extraction and processing.

Please submit your future questions to https://stackoverflow.com/ or similar platforms.
