### ISSUE TITLE
Increase items count

### ISSUE THREAD

**Issue by VannotAlexi0x73** [scrapy/scrapy#5248]
Hello everybody,

I am a beginner with this framework and I have 2 questions/problems:

1. I made a "scrapy.Spider" for a website, but it stops after 960 elements retrieved, how can I increase this value, I need to retrieve about 4000 elements .... :/
2. Is it possible to launch scrapy infinitely by adding a waiting time for each "scrapy.Spider"?

Thanking you in advance !

<img width="981" alt="cli_issue" src="https://user-images.githubusercontent.com/34712990/135105745-feaee59b-2355-4ca4-ac11-ffd09431e6a0.png">

**Comment by Gallaecio** [comment]
This issue tracker is meant for bugs and feature requests, not for user support. Please, see https://scrapy.org/community/ for the right places to get support.

**Comment by VannotAlexi0x73** [comment]
https://stackoverflow.com/questions/69368537/increase-items-count-web-scrapping
