### ISSUE TITLE
Lose some data items when the number of Requests in start_requests is bigger than CONCURRENT_REQUESTS in settings

### ISSUE THREAD

**Issue by TuoBaed** [scrapy/scrapy#5249]
### Description

Lose some data items when the number of Requests in start_requests(self) method is bigger than CONCURRENT_REQUESTS in settings. The more Requests I make the more data I lose. 

### Steps to Reproduce

1. Here is my spider:

  
2. Here is my code in items.py

   

3. Here is my project settings

  

4. Here is my code in pipelines.py

   

**Expected behavior:** I requested 50 pages and there are 30 items per page, so I should get 1500 records in .csv document. And if I use requests(a HTTP request lib) and ThreadPool I can get 1500 records exactly.

**Actual behavior:** However, I only get about 1200 records.

**Reproduces how often:** Every time if the number_of_requests is bigger than CONCURRENT_REQUESTS in settings.

### Versions

- Scrapy       : 2.5.0
- lxml         : 4.6.3.0
- libxml2      : 2.9.5
- cssselect    : 1.1.0
- parsel       : 1.6.0
- w3lib        : 1.22.0
- Twisted      : 20.3.0
- Python       : 3.7.3  [MSC v.1916 64 bit (AMD64)]
- pyOpenSSL    : 20.0.1 (OpenSSL 1.1.1k  25 Mar 2021)
- cryptography : 3.4.7
- Platform     : Windows-10-10.0.19041

**Comment by Gallaecio** [comment]
Please, edit your issue description to replace your code with a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) (i.e. remove any lines of code that do not contribute to readability or reproducing the issue).

**Comment by TuoBaed** [comment]
> Please, edit your issue description to replace your code with a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) (i.e. remove any lines of code that do not contribute to readability or reproducing the issue).

I can't create another example to show these problems presently.

**Comment by TuoBaed** [comment]
Maybe my mistake or the website's error yesterday. Everything is ok now. However, I still don't know why.
