### ISSUE TITLE
Support h2>=4.0

### ISSUE THREAD

**Issue by epicfaace** [scrapy/scrapy#5267]
I'm no longer able to use the latest version of scrapy (2.5.1) with mitmproxy 7.0.3 because scrapy pins h2 support to 3.x.

```

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
The conflict is caused by:
    mitmproxy 7.0.3 depends on h2<5 and >=4.0
    scrapy 2.5.1 depends on h2<4.0 and >=3.0
```

(from https://github.com/cisagov/crossfeed/pull/1231/checks?check_run_id=3821313582)

**Comment by epicfaace** [comment]
Hi @Gallaecio , do you have an expected timeline for when you'll release scrapy 2.6.0? No rush, but it would help us plan. Thanks

**Comment by Gallaecio** [comment]
We don’t have a date, even a date range, but it should be shortly after we merge https://github.com/scrapy/scrapy/pull/4978, so you might want to keep an eye on it.
