### ISSUE TITLE
HTTPS TorGuard proxies time out

### ISSUE THREAD

**Issue by bezkos** [scrapy/scrapy#5286]
I used auth HTTP proxies with scrapy just fine.
Recently my provider went from HTTP to SSL Proxies and scrapy stop to download through them.
I dont know if its a bug report or new feature but can scrapy use SSL Proxies?

**Comment by bezkos** [comment]
Yes i updated it from old URL
http://user:pass@uk.torguard.com:6060
to
https://user:pass@uk.secureconnect.me:7070

I tried several new ports like they mention in their site.
Scrapy stoped to connect to their new type proxy.
Maybe SSL proxy has change auth verification too?
I use scrapy_proxies for auth, rotating etc....

**Comment by Gallaecio** [comment]
[Does adding `?noconnect` to the proxy URL fix this?](https://github.com/scrapy/scrapy/issues/5433#issuecomment-1057022973)

**Comment by Gallaecio** [comment]
Unless further feedback contradicts this, I am closing this in favor of #4821.
