### ISSUE TITLE
macOS Python 3.10 tests always fail

### ISSUE THREAD

**Issue by azzamsa** [scrapy/scrapy#5306]
I got some errors in both Ubuntu in the macOS test in my fork. Some of them are transient. They disappear after I re-run the test. 

However, there is an error that persists in macOS Python 3.10. I tried to open a new PR #5305 to see if this would happen here too. Unfortunately, I don't see any macOS tests being run, even the config [still there](https://github.com/scrapy/scrapy/blob/3225de725720bba246ba8c9845fe4b84bc0c82e7/.github/workflows/tests-macos.yml#L2). Turns out, after some discussion in Discord, the macOS tests were disabled manually via the repository settings.

The contents of error that [keep happening in macOS Python 3.10](https://github.com/azzamsa/scrapy/runs/4058783846?check_suite_focus=true#step:4:280) is: `FAILED tests/test_utils_iterators.py::XmliterTestCase::test_xmliter_unicode`

```python

self = <tests.test_utils_iterators.XmliterTestCase testMethod=test_xmliter_unicode>
msg = "Lists differ: [('26', ['-'], []), ('21', ['Ab'], ['76']), ('27', ['A'], ['27'])] != [('26', ['-'], ['80']), ('21', ['...', ['A'], ['27'])]\n+ [('26', ['-'], ['80']), ('21', ['Ab'], ['76']), ('27', ['A'], ['27'])]\n?                 ++++\n"

    def fail(self, msg=None):
        """
        Absolutely fail the test.  Do not pass go, do not collect $200.
    
        @param msg: the message that will be displayed as the reason for the
        failure
        """
>       raise self.failureException(msg)
E       twisted.trial.unittest.FailTest: Lists differ: [('26', ['-'], []), ('21', ['Ab'], ['76']), ('27', ['A'], ['27'])] != [('26', ['-'], ['80']), ('21', ['Ab'], ['76']), ('27', ['A'], ['27'])]
E       
E       First differing element 0:
E       ('26', ['-'], [])
E       ('26', ['-'], ['80'])
E       
E       - [('26', ['-'], []), ('21', ['Ab'], ['76']), ('27', ['A'], ['27'])]
E       + [('26', ['-'], ['80']), ('21', ['Ab'], ['76']), ('27', ['A'], ['27'])]
E       ?                 ++++
```

Should we use `xfail` mark for this test function?

**Comment by azzamsa** [comment]
I will disable the macOS test in my end too. So that it doesn't block my contributions.

**Comment by wRAR** [comment]
@azzamsa is this no longer happening?

**Comment by cakemd** [comment]
@wRAR the test keeps failing `tests/test_utils_iterators.py::XmliterTestCase::test_xmliter_unicode` if that is your question in last comment.

Weird thing is that replacing `<heiti />` with `<heiti/>` in the `body` variable in the test, it stops failing.

I'm still figuring out what's wrong here.

**Comment by FilippoPetroli** [comment]
@wRAR I checked here, it not happening anymore.

**Comment by wRAR** [comment]
@FilippoPetroli can you please check on 3.8? IIRC currently the CI tests only fail on 3.8.

**Comment by FilippoPetroli** [comment]
@wRAR Indeed, it's failing on 3.8.
Looks like it's related to `lxml` library. I'll be testing others versions of `lxml`. Maybe we need upgrade.

**Comment by Laerte** [comment]
@wRAR This don't seems to be the case anymore:

https://github.com/Laerte/scrapy/actions/runs/11371871987

cc: @wRAR
