### ISSUE TITLE
While downloading a file using authenticated middleware, files downloaded across all format seems corrupted.

### ISSUE THREAD

**Issue by prateekg** [scrapy/scrapy#5313]
While downloading the file using an HTTP authenticated custom middleware, I'm able to download the files with proper size but when I try to open the file, windows return "Can't open the file" across all the formats. 

Is there any other authentication required while trying to download files from secure websites?

**Comment by wRAR** [comment]
This is a Scrapy issue tracker, please check https://scrapy.org/community/ for ways to seek support for your code.

If you think this is actually a bug in Scrapy please prepare https://stackoverflow.com/help/minimal-reproducible-example for it.
