### ISSUE TITLE
ItemExporter serialize_field but not recursive (item encoding problem)

### ISSUE THREAD

**Issue by thiagof** [scrapy/scrapy#532]
Hello

I'm using the `JsonItemExporter`. My item has the following structure:

    item = {
        'content': u'O presente curso de No\xc3\xa7\xc3\xb5es de Rela\xc3\xa7\xc3\xb5es Internacionais tem como foco as rela\xc3\xa7\xc3\xb5es econ\xc3\xb4micas internacionais',
        'title': u'No\xc3\xa7\xc3\xb5es de Rela\xc3\xa7\xc3\xb5es Internacionais',
        'terms_names': {
            'category': u'Administra\xe7\xe3o'
        }
    }

The problem is on `BaseItemExporter.serialize_field`. The default serializer converts only `unicode` to `str`.
So in this example, where I have a `dict` value for a field (*terms_names*), `serialize_field` do nothing and the resulting item have *content* and *title* as `utf-8 str` but *category* property remains unicode. And this cant be encoded/mixed by json! - http://pastebin.com/mfkhHYc9

Possible solution: recursively convert properties.

**Comment by redapple** [comment]
Closing as per @aufziehvogel 's comment above.
