### ISSUE TITLE
Documentation updates in most recent release missing from latest published docs

### ISSUE THREAD

**Issue by banagale** [scrapy/scrapy#5324]
### Description

`scrapy/docs/topics/media-pipeline.rst` appears to have changes that are not in the latest release.

It appears that changes going back to 2.4 are not found in the published docs online.

I focused on `media-pipeline.rst`, as I was tracking down some docs I contributed this past summer. But there may be other examples.

### Steps to Reproduce

1. See [this merged change](https://github.com/scrapy/scrapy/commit/b22a0043988a4f3c54709988de99f489db44f78d#diff-21aeb4cf9ec6055873eedbb344f31fb4e48c53c228cb4d0d31bb115e7c81d82f) from July.
2. View [the published docs section](https://docs.scrapy.org/en/latest/topics/media-pipeline.html#supported-storage) that should show the changes.
3. Changes are not included

### Additional context
Could the most recent release(s) have missed a docs compilation step?

**Comment by wRAR** [comment]
> from July.

2.5.0 was released in April.

**Comment by banagale** [comment]
@wRAR I see.  2.5.1 is listed as the most recent on the releases page. So point releases not include docs regen?

**Comment by wRAR** [comment]
2.5.1 doesn't include that change as you can see in its release notes (or on the commit page).

**Comment by banagale** [comment]
I see. I had incorrectly presumed that point releases brought along what was in master up until the release. Thanks for the feedback.

**Comment by wRAR** [comment]
(that would defeat the purpose of point releases)

**Comment by banagale** [comment]
I suppose that depends on the project, though I definitely get that with scrapy this is not the case.

One thing that might have thrown me is that the docs say in the footer, "Last updated on Oct 06, 2021" even though the update from 2.5.1 has no docs changes. 

I realize this is technically correct, since the version number got bumped, but I would normally presume this meant some kind of content change.

**Comment by wRAR** [comment]
Normal releases bring along what was in master up until the release. Point releases don't.
