### ISSUE TITLE
Add a CI run on WSL

### ISSUE THREAD

**Issue by wRAR** [scrapy/scrapy#5327]
If we are going to recommend WSL (and I think we should) it should be useful to run CI tests on it, even though it's almost a normal Ubuntu. There is https://github.com/marketplace/actions/setup-wsl but I couldn't find how to install Python there, as I think the default `setup-python` action will only install a Windows interpreter into the host system and I would like to not install the intepreter manually with apt but use the CI-provided one in some way.

**Comment by mdonoughe** [comment]
GitHub's runners can only use WSL 1, which emulates a subset of the Linux syscall interface to run Linux processes in Windows. I think most people use WSL 2 now, which uses a real Linux kernel running inside a lightweight virtual machine. The good news for WSL 2 is that, as long as the code is running from the Linux filesystem, it is all Linux and isn't very interesting to test.

**Comment by wRAR** [comment]
I think this indeed doesn't make much sense, closing.
