### ISSUE TITLE
BugReport(About robot.txt)

### ISSUE THREAD

**Issue by wza123** [scrapy/scrapy#5331]
### Description

The spider will reduse error when you crawl a website without robot.txt but set ROBOTSTXT_OBEY=True

### Steps to Reproduce

1.make a simple spider
2.don't change ROBOTSTXT_OBEY
3.try to crawl a website like konachan.net

**Expected behavior:** returns normal

**Actual behavior:** twisted.web._newclient.ResponseNeverReceived: [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion: Connect
ion lost.>]

**Reproduces how often:** every time

### Versions

Scrapy       : 2.5.1
lxml         : 4.6.4.0
libxml2      : 2.9.5
cssselect    : 1.1.0
parsel       : 1.6.0
w3lib        : 1.22.0
Twisted      : 21.7.0
Python       : 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)]
pyOpenSSL    : 21.0.0 (OpenSSL 1.1.1l  24 Aug 2021)
cryptography : 36.0.0
Platform     : Windows-10-10.0.22000-SP0

### Additional context

this issue can simply solve by set ROBOTSTXT_OBEY=False, but maybe it will better to check is robot.txt exitst when set it on

**Comment by wRAR** [comment]
https://konachan.net/robots.txt exists. But even for a website without robots.txt you'll just get a 404 line in the logs. Looks like you are IP-banned.
