### ISSUE TITLE
Request/Response size per Request/URL

### ISSUE THREAD

**Issue by bezkos** [scrapy/scrapy#5338]
I know scrapy has total size stats for respones/requests size when a spider finish.
But is it possible to have these stats during execution of a spider per request/url?

**Comment by wRAR** [comment]
This is the issue tracker for Scrapy. Please direct your usage questions to e.g. one of the platforms listed at https://scrapy.org/community/

**Comment by bezkos** [comment]
@wRAR this isn't usage question but a feature addition.
Scrappy DownloaderStats calculate this (reqlen, reslen) but dont add them to stats dict.
To add this feature i subclass DownloaderStats and override process_request and process_response with the addition
self.stats.set_value('downloader/cur_request_bytes', reqlen, spider=spider)
self.stats.set_value('downloader/cur_response_bytes', reslen, spider=spider)
in each method.

**Comment by wRAR** [comment]
A stat about a "current" request or a response makes no sense.
