### ISSUE TITLE
Pictures downloaded through the pipeline will be compressed. Why

### ISSUE THREAD

**Issue by Assistest** [scrapy/scrapy#5339]
**When I download a picture through the picture pipeline, the picture will be compressed
I checked the document and there seems to be no solution
I can only use other pipes**

**Comment by wRAR** [comment]
Compressed in what sense?

**Comment by GeorgeA92** [comment]
@wRAR , @Assistest. I suppose it's related to https://github.com/scrapy/scrapy/issues/3055

**Comment by Assistest** [comment]
@wRAR @GeorgeA92 thank you very much. It seems that someone has asked this question. Now you can close it L
