### ISSUE TITLE
ModuleNotFoundError: No module named 'project' when setting Env in DockerFile

### ISSUE THREAD

**Issue by njmhnb** [scrapy/scrapy#5343]
Hi everyone
I have a dockerized scrapy project
without using ENV SCRAPY_SETTINGS_MODULE project.settings in DockerFile everything is ok, and project can find default project settings correctly, but when using ENV SCRAPY_SETTINGS_MODULE project.settings I get ModuleNotFoundError: No module named 'project'

**Comment by njmhnb** [comment]
without using ENV SCRAPY_SETTINGS_MODULE project.settings in DockerFile everything is ok, and project can find default project settings correctly, but when using ENV SCRAPY_SETTINGS_MODULE project.settings I get ModuleNotFoundError: No module named 'project'

**Comment by wRAR** [comment]
This is an issue tracker for Scrapy. To get help with your code please use e.g. resources listed at https://scrapy.org/community/

If you think this is a bug in Scrapy itself please provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
