### ISSUE TITLE
ReactorNotRestartable error raised when running scrapy from flask

### ISSUE THREAD

**Issue by itzikorfa** [scrapy/scrapy#5350]
Hi,
I tried to use scrapy from a flask project.
when I run the code from the terminal it runs perfectly, 
but from the flask, the second request raises ReactorNotRestartable exception.

I use the CrawlerProcess to run start the class.

does anyone stumble upon this issue?

**Comment by wRAR** [comment]
This is an issue tracker for Scrapy. To get help with your code please use e.g. resources listed at https://scrapy.org/community/
