### ISSUE TITLE
Deprecation warning: file_path(self, request, response=None, info=None) is deprecated

### ISSUE THREAD

**Issue by danger89** [scrapy/scrapy#5353]
I installed scrapy via pip, but I get a Deprecation warning within your own source-code.

```sh
WARNING: /usr/local/lib/python3.8/site-packages/scrapy/pipelines/media.py:135: ScrapyDeprecationWarning: file_path(self, request, response=None, info=None) is deprecated, please use file_path(self, request, response=None, info=None, *, item=None)
  self._check_signature(func)
```

Consider fixing your code base: https://github.com/scrapy/scrapy/blob/master/scrapy/pipelines/media.py

Regards,
Melroy van den Berg

**Comment by wRAR** [comment]
Looks like stacklevel in _check_signature is wrong.

As for the warning itself, all `file_path` signatures are correct in 2.5 and master. If you think this is a problem in Scrapy itself please provide [a minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by danger89** [comment]
I'm just using the built-in Files Download pipeline, that depends on the Media pipeline. Which give this WARNING to the console.

**Comment by wRAR** [comment]
That's not a minimal reproducible example. You are supposed to provide actual code, not instructions how to create it.

**Comment by danger89** [comment]
No it's not, but I don't have much time to create that. I'm also working on other open-source projects. Since this is "just" a deprecation warning, I just deal with it. 

If you want to solve this, you can easily create an empty scrapy just use the built-in `scrapy.pipelines.files` pipeline, to have a reproducible result.

**Comment by wRAR** [comment]
I tried this and couldn't reproduce this. This is the reason we ask for reproducible examples.
