### ISSUE TITLE
CrawlerProcess constructor gives SIGSEGV (Address boundary error)

### ISSUE THREAD

**Issue by opqpop** [scrapy/scrapy#5362]
### Description

This used to work, I don't think I've made any major changes that started causing this new error.

Repro:

```
from scrapy.crawler import CrawlerProcess
from scrapy.utils.project import get_project_settings

proj_settings = get_project_settings()
process = CrawlerProcess(proj_settings)
spider_name = 'bob'

process.crawl(
    spider_name
)
process.start()
```

Running the constructor process = CrawlerProcess(proj_settings) gives me 

`'python3 $argv' terminated by signal SIGSEGV (Address boundary error)`

I'm on mac mini with M1 chip, and it used to work fine on this machine like 1 month ago. 

Details:
- Python crash log with why segfault happened: https://gist.github.com/opqpop/b94d1cdb86358516dccc374342a5e968
- My pip freeze: https://gist.github.com/opqpop/7e7a917b36f731bc3d788f55d4306bf0

Any ideas what may be wrong? Can't think of any changes I've done since it worked. Code hasn't changed either.

This code works fine on my other mac / windows laptops

**Comment by wRAR** [comment]
Scrapy is a pure-Python module and it doesn't even use ctypes/ffi, so this crash is because of code in a different module. Looks like you'll need to minimize your reproduction scenario and find the real reason.

**Comment by opqpop** [comment]
I found the reason

it happens if you do this in your spider

```
import keyboard
```
