### ISSUE TITLE
Deprecate scrapy.pipelines.images.NoimagesDrop

### ISSUE THREAD

**Issue by wRAR** [scrapy/scrapy#5368]
As noticed in #4910, `scrapy.pipelines.images.NoimagesDrop` is not used in the Scrapy code so we should deprecate (and later remove) it.

**Comment by kuephi** [comment]
Hi I will try this one.

**Comment by PluT00** [comment]
Hey @wRAR. Is this issue still relevant? If it is, could you please, tell me what could I fix in my solution?
