### ISSUE TITLE
Remove the pywin32 docs section

### ISSUE THREAD

**Issue by wRAR** [scrapy/scrapy#5369]
As noticed in #4492, the FAq question at https://docs.scrapy.org/en/latest/faq.html#scrapy-crashes-with-importerror-no-module-named-win32api is no longer useful as the Twisted bug was fixed long time ago. We should remove this question.

**Comment by NaincyKumariKnoldus** [comment]
Hey @wRAR Can I do this please?

**Comment by wRAR** [comment]
@NaincyKumariKnoldus you don't need a permission to work on issues.

**Comment by NaincyKumariKnoldus** [comment]
ok @wRAR Today I will do this! Thanks

**Comment by NaincyKumariKnoldus** [comment]
Hey @wRAR I have raised my PR. Please Review my PR!
Thanks!

**Comment by GhostViz** [comment]
Resolved by #5370
