### ISSUE TITLE
botocore version in the documentation is wrong

### ISSUE THREAD

**Issue by b5y** [scrapy/scrapy#5380]
## Summary

Please fix this documentation with [wrong botocore](https://docs.scrapy.org/en/latest/topics/feed-exports.html#topics-feed-storage-s3) version. The latest version of botocore is [1.23.45](https://github.com/boto/botocore/tags).

## Motivation

In order to follow tutorials properly.

## Describe alternatives you've considered

Version 1.23.45 should be put to the documentation.

## Additional context

For some reason writing to S3 bucket doesn't work for me. I followed this [advice](https://stackoverflow.com/a/69931348) and [tutorial](https://docs.scrapy.org/en/latest/topics/feed-exports.html#topics-feed-storage-s3). The only working solution for now is [scrapy-s3pipeline library](https://github.com/orangain/scrapy-s3pipeline).

**Comment by wRAR** [comment]
> Please fix this documentation with wrong botocore version. The latest version of botocore is 1.23.45.

Can you please explain which statement in the linked doc is wrong?

> For some reason writing to S3 bucket doesn't work for me. I followed this advice and tutorial. The only working solution for now is scrapy-s3pipeline library.

Is this related or a separate problem

**Comment by b5y** [comment]
>Can you please explain which statement in the linked doc is wrong?

This part: `Required external libraries: botocore >= 1.4.87`.

>Is this related or a separate problem?

I will open bug report soon related to this problem, but I suppose it's somehow related to this report.

**Comment by wRAR** [comment]
> This part: Required external libraries: botocore >= 1.4.87.

How is it wrong?

**Comment by b5y** [comment]
Okay, now I got it, You just put higher value to avoid frequent changes in the documentation.

**Comment by wRAR** [comment]
It's not about "frequent changes in the documentation", but whatever.
