### ISSUE TITLE
Possible import name clash between project directory and installed *.py executables

### ISSUE THREAD

**Issue by woho** [scrapy/scrapy#5381]
Python's import system has one weird aspect that make it vulnerable to import name clashes between modules in the working directory and in the directory of the main entry point. This affects Scrapy's import mechanism.

Minimal example:
```bash
touch $(dirname `which scrapy`)/myproject.py   # Could be some file from another program

scrapy startproject myproject
cd myproject
scrapy genspider example example.com
scrapy crawl example
```
... fails with: `ModuleNotFoundError: No module named 'myproject.settings'; 'myproject' is not a package`

## Possible solution

Just remove the problematic folder from `sys.path`, i.e. add `sys.path.remove(os.path.dirname(__file__))` to the Scrapy executable (usually `/usr/bin/scrapy` or `/usr/local/bin/scrapy`).

**Comment by wRAR** [comment]
Are you proposing some changes to Scrapy?

**Comment by woho** [comment]
Yes, my suggestion is to modify `sys.path` in the Scrapy executable as described above. At least this is the simplest solution that comes to my mind. I suggest the removal of the problematic path since I don't think it is needed, but an alternative option would be to move it from the beginning to the end of the `sys.path` list to change the priority of lookup.

I think that such unexpected interference between different programs is something that would be good to resolve. And consider that /usr/bin can potentially have hundreds on *.py files and that a software installation or update can suddenly break your Scrapy project.

**Comment by wRAR** [comment]
Sorry, do you see some Scrapy-specific problem here as opposed to a general Python problem?

**Comment by Gallaecio** [comment]
@woho While I get your point, I don’t think having Scrapy alter sys.path is the way forward. I don’t really see a way forward. We could have the scrapy subcommands that generate files warn in case of conflicts, but I am not sure how helpful that would really be, and it definitely does not account for files created manually.

**Comment by woho** [comment]
I definitively see it as a bug in Scrapy when a specific name of the project folder can result in a crash. This is currently blocking us from updating packages in our large project. And I don't see an argument against modifying `sys.path` in general ­- it is the common method to adjust imports paths.

**Comment by wRAR** [comment]
> I definitively see it as a bug in Scrapy when a specific name of the project folder can result in a crash.

Can you please explain how is it a bug in Scrapy specifically and not just a common Python problem with having modules with the same name in different sys.path components? 

> I don't see an argument against modifying sys.path in general ­- it is the common method to adjust imports paths.

Sure, it's a common part of solutions to path-specific problems, but there is no single thing you can or should do to prevent conflicts. What you are proposing can only solve some specific problems you have and not the general one.

**Comment by Gallaecio** [comment]
I had forgotten about it, but I think #3669 may be tackling this issue (on the documentation level).
