### ISSUE TITLE
Can parse json with bs4 on requests but not with scrapy

### ISSUE THREAD

**Issue by lime-n** [scrapy/scrapy#5385]
I'm trying to parse some json data scraped from a website with beautifulsoup however, I wish to do this with scrapy. The problem is that It seems to work effectively when parsing the json with beautifulsoup from `requests` response as opposed to a `scrapy` response.

For example, with requests I would do this:
```
response = requests.post('https://www.theparking.eu/index.php', headers=headers, data=data)
test = json.loads(response.text)
lists_data=BeautifulSoup(test['#lists'], 'lxml')
lists_data.select("span.nowrap")
```
which would print out results:
```
[<span class="nowrap">Amr</span>,
 <span class="nowrap">V12 5.2</span>,
 <span class="nowrap">Amr</span>,
 <span class="nowrap">V12 5.2</span>,
 <span class="nowrap">V8 4.0</span>,
 <span class="nowrap">V8 4.0</span>,
...
```
However when I run this by on scrapy, It won't work for me:

```
import scrapy
from scrapy.item import Field
from scrapy.crawler import CrawlerProcess
from bs4 import BeautifulSoup
import json
from itemloaders.processors import TakeFirst

headers = {
    'authority': 'www.theparking.eu',
    'sec-ch-ua': '" Not;A Brand";v="99", "Google Chrome";v="97", "Chromium";v="97"',
    'accept': '*/*',
    'content-type': 'application/x-www-form-urlencoded; charset=UTF-8',
    'x-requested-with': 'XMLHttpRequest',
    'sec-ch-ua-mobile': '?0',
    'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36',
    'sec-ch-ua-platform': '"macOS"',
    'origin': 'https://www.theparking.eu',
    'sec-fetch-site': 'same-origin',
    'sec-fetch-mode': 'cors',
    'sec-fetch-dest': 'empty',
    'referer': 'https://www.theparking.eu/used-cars/used-cars/',
    'accept-language': 'en-GB,en-US;q=0.9,en;q=0.8',
}

data = {
  'ajax': '{"tab_id":"t0","cur_page":1,"cur_trie":"distance","query":"","critere":{"id_pays":["2"]},"sliders":{"prix":{"id":"#range_prix","face":"prix","max_counter":983615,"min":"1","max":"400000"},"km":{"id":"#range_km","face":"km","max_counter":1071165,"min":"1","max":"500000"},"millesime":{"id":"#range_millesime","face":"millesime","max_counter":1163610,"min":"1900","max":"2022"}},"req_num":1,"nb_results":"11795660","current_location_distance":-1,"logged_in":false}',
  'tabs': '["t0"]'
}
class Countryitem(scrapy.Item):
    itemss = Field(output_processor = TakeFirst())

class CountrySpider(scrapy.Spider):
    name = "country"
    #start_urls = []

    def start_requests(self):
        yield scrapy.FormRequest(
            url = "https://www.theparking.eu/index.php",
            callback = self.parse,
            formdata = data,
            headers=headers
        )
    def parse(self, response):
        container = response.json().get("#lists")
        test = json.loads(container)
        soup = BeautifulSoup(container, 'lxml')
        yield {
            'data':soup
        }
        
process = CrawlerProcess(
    settings = {
        'FEED_URI':'park.jl',
        'FEED_FORMAT':'jsonlines'
    }
)
process.crawl(CountrySpider)
process.start()

```
This produces the following error:
>TypeError: Object of type BeautifulSoup is not JSON serializable

Why is there a difference between the two?

**Comment by wRAR** [comment]
This is a problem with your code, not with Scrapy.

**Comment by lime-n** [comment]
> This is a problem with your code, not with Scrapy.

That is what I thought at first but I also used `response.text` from scrapy and followed the same procedure as that on `requests`. For some reason scrapy won't read the data as bs4 - when I try this method I find that in the output part of the data is read by `bs4` and then it stops and creates an error. Might be worth looking into.

**Comment by lime-n** [comment]
For example:
```
def parse(self, response):
        container = json.loads(response.text)
        test=container['#lists']
        soup = BeautifulSoup(test, features='lxml')
        yield {
            'data':soup
        }
```
I get the same error as above. This is exactly the same as the `requests` code. So its obviously on `scrapy's` side that it cannot handle the same method as `requests`.

**Comment by wRAR** [comment]
The error you shown is very clear and is not Scrapy-related but is caused by an error in your code. If, on the other hand, you have a report about some problem in Scrapy itself you need to provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by wRAR** [comment]
No, it's not "exactly the same as the requests code" and is not "obviously on scrapy's side". You are trying to put a `BeautifulSoup` object into your JSON output file.

**Comment by lime-n** [comment]
So then why can `requests` handle the same logic? It creates a `POST` request as I do with `scrapy`, and I use `json.loads(response.text)``` to get the json data. I have checked with requests and the output matches the same. The only difference is that `BeautifulSoup` won't read the `json` given by `crapy` but will for `requests`. Mind you, all it does with requests is just convert the entire thing into a string, perhaps something else is going on here with `scrapy`?

I used it exactly like this:
```
def parse(self, response):
        container = json.loads(response.text)
        test=container['#lists']
        soup = BeautifulSoup(test, features='lxml')
        yield {
            'data':soup
        }
```

**Comment by wRAR** [comment]
Please use https://stackoverflow.com/ or similar to get help with problems in your code.

**Comment by elacuesta** [comment]
The title is not representative of the issue. You are indeed parsing the JSON response in the Scrapy snippets, either with `container = json.loads(response.text)` or with `container = response.json()`.

The problem comes when you try to serialize the scraped item into JSON(lines). For this, Scrapy uses [`scrapy.exporters.JsonLinesItemExporter`](https://github.com/scrapy/scrapy/blob/2.5.1/scrapy/exporters.py#L87-L98), which in turn uses [`scrapy.utils.serialize.ScrapyJSONEncoder`](https://github.com/scrapy/scrapy/blob/2.5.1/scrapy/utils/serialize.py#L11-L36), which does not know how to handle BeautifulSoup objects.

This is not an bug in Scrapy, and it can be solved if needed on a project-basis by providing your own [Feed exporter](https://docs.scrapy.org/en/2.5/topics/feed-exports.html#std-setting-FEED_EXPORTERS).
