### ISSUE TITLE
Scrapy does not respect the Request encoding when working with TextResponse

### ISSUE THREAD

**Issue by dchaplinsky** [scrapy/scrapy#5392]
### Description

I'm trying to read local csv file using `CSVFeedSpider` like this:
```python
    def start_requests(self):
        assert self.settings.get(
            "HIGHCOURT_INDEX"
        ), "You should specify HIGHCOURT_INDEX setting as a path to a file or url in order run that spider"

        yield scrapy.Request(
            self.settings["HIGHCOURT_INDEX"],
            encoding="cp1251"
        )
```

However it changes the encoding of the response:
```python
    def parse_rows(self, response):
        """Receives a response and a dict (representing each row) with a key for
        each provided (or detected) header of the CSV file.  This spider also
        gives the opportunity to override adapt_response and
        process_results methods for pre and post-processing purposes.
        """

        print(type(response), response.encoding, response._encoding, response.request.encoding)
```
Output:
`<class 'scrapy.http.response.text.TextResponse'> cp1252 None cp1251`

### Steps to Reproduce

Run this spider with any CSV file:
```python
# -*- coding: utf-8 -*-
import re
import datetime

import scrapy
from scrapy.loader import ItemLoader
from scrapy.utils.iterators import csviter
from scrapy.utils.spider import iterate_spider_output


class OdReyestrCourtGovUaSpider(scrapy.spiders.feed.CSVFeedSpider):
    name = "od_reyestr_court_gov_ua"

    def start_requests(self):
        assert self.settings.get(
            "HIGHCOURT_INDEX"
        ), "You should specify HIGHCOURT_INDEX setting as a path to a file or url in order run that spider"

        yield scrapy.Request(
            self.settings["HIGHCOURT_INDEX"],
            encoding="cp1251"
        )

    def parse_rows(self, response):
        """Receives a response and a dict (representing each row) with a key for
        each provided (or detected) header of the CSV file.  This spider also
        gives the opportunity to override adapt_response and
        process_results methods for pre and post-processing purposes.
        """

        print(type(response), response.encoding, response._encoding, response.request.encoding)
        for row in csviter(response, self.delimiter, self.headers, quotechar=self.quotechar, encoding="cp-1251"):
            ret = iterate_spider_output(self.parse_row(response, row))
            for result_item in self.process_results(response, ret):
                yield result_item

    def parse_row(self, response, row):
        self.logger.info("Hi, this is a row!: %r", row)
```

**Expected behavior:** response has correct encoding and `parse_row` receives correct data

**Actual behavior:** Data received by `parse_raw` has wrong encoding and garbled

**Reproduces how often:** 100%

### Versions

```
Scrapy       : 2.5.0
lxml         : 4.6.3.0
libxml2      : 2.9.10
cssselect    : 1.1.0
parsel       : 1.6.0
w3lib        : 1.22.0
Twisted      : 21.2.0
Python       : 3.9.8 (main, Nov 10 2021, 09:21:22) - [Clang 13.0.0 (clang-1300.0.29.3)]
pyOpenSSL    : 20.0.1 (OpenSSL 1.1.1k  25 Mar 2021)
cryptography : 3.4.7
Platform     : macOS-11.6-x86_64-i386-64bit
```

### Additional context

The CSV file is locally stored and passed to the spider like this:
`scrapy crawl od_reyestr_court_gov_ua -s HIGHCOURT_INDEX="file:///Users/dchaplinsky/Projects/corpus-uk/dec_sample.csv"`

**Comment by elacuesta** [comment]
From the [`Request` docs](https://docs.scrapy.org/en/2.5/topics/request-response.html#request-objects): "encoding will be used to percent-encode the URL and to convert the body to bytes (if given as a string)". This does not necessarily have to match the response encoding.
If not declared when creating the response by explicitly specifying the `encoding` argument (which is not done by the default downloader), Scrapy will [attempt to determine the response encoding](https://github.com/scrapy/scrapy/blob/2.5/scrapy/http/response/text.py#L60-L62) by trying a few things (e.g. reading from the [meta content charset attribute](https://w3lib.readthedocs.io/en/1.22/w3lib.html#w3lib.encoding.html_body_declared_encoding)).

**Comment by dchaplinsky** [comment]
Okay @elacuesta, that makes sense, but it doesn't work with local files.

For example, I have a local csv file with links and meta-information in non-latin encoding. I'd like to collect the data from links from file and append meta information from the csv to the items I produce. How should I approach it? There is no option to override the encoding, only to rely to default.
