### ISSUE TITLE
Run tox -e docs-links

### ISSUE THREAD

**Issue by Gallaecio** [scrapy/scrapy#5403]
This Tox environment is meant to detect broken external links in the documentation. We do not run it in CI because it depends on the Internet ti be reliable, so it can fail easily, but we should run it manually now and then to keep track of broken links, and I think we have been postponing the next check for too long.

**Comment by Clash-ion** [comment]
I was thinking of writing a test which will make a request to each of the links and check the result. So will this be a viable solution?

**Comment by Gallaecio** [comment]
We already have that, you can run it with `tox -e docs-links`. This issue is about running that and fixing links.

**Comment by wRAR** [comment]
I've just run it, it found only "http://index.html" in docs/news.rst which is intended.
