### ISSUE TITLE
Google Summer of Code 2022

### ISSUE THREAD

**Issue by Gallaecio** [scrapy/scrapy#5408]
This is a GitHub issue to handle student questions and feedback regarding the 2022 edition of Google Summer of Code, where Scrapy participates again this year: https://gsoc2022.zyte.com/

Please, check our [Google Summer of Code communication guidelines](https://gsoc2022.zyte.com/participate#communication) before commenting on this issue.

**Comment by PushanAgrawal** [comment]
Hello I am a beginner. How can I be a part of it?

**Comment by Anonymous-gh0ST** [comment]
Hello, I am a GSoC aspirant and I don't know where to begin. How can I get started?

**Comment by Gallaecio** [comment]
@Anonymous-gh0ST Make sure you read https://gsoc2022.zyte.com/participate carefully and follow the links on the page introduction to the documentation from Google and from the Python Software Foundation.
