### ISSUE TITLE
Remove Python 2 code from WrappedRequest

### ISSUE THREAD

**Issue by Gallaecio** [scrapy/scrapy#5410]
[The WrappedRequest class](https://github.com/scrapy/scrapy/blob/06f3d12c1208c380f9f1a16cb36ba2dfa3c244c5/scrapy/http/cookies.py#L148) has methods that can be removed, as [they were only used in Python 3.3 and earlier](https://docs.python.org/3/library/http.cookiejar.html#http.cookiejar.CookieJar.extract_cookies).

**Comment by PushanAgrawal** [comment]
hello  , this seems like a task I can do as beginner . Could you guide me more into the issue?

**Comment by Gallaecio** [comment]
It seems we need to remove the `get_origin_req_host` method, and move its implementation to the `origin_req_host` property. Assuming tests pass after that change, that should be it.
