### ISSUE TITLE
Change external link (for robots.txt parser comparison) in docs to a more lasting page

### ISSUE THREAD

**Issue by anubhavp28** [scrapy/scrapy#5414]
Scrapy documentation (at the end of [this section](https://docs.scrapy.org/en/latest/topics/downloader-middleware.html#module-scrapy.downloadermiddlewares.robotstxt)) links to a blog that contains performance numbers for different `robots.txt` parser backends. It would be better to change the link to point to [this issue](https://github.com/scrapy/scrapy/issues/3969) as it is more lasting. Currently, we are linking to a personal blog website which might disappear if the blog owner decides to change the hosting or blog name.

**Comment by eddybruv** [comment]
@anubhavp28  please can you review my pull request and tell me if there's any problem with it.

**Comment by anubhavp28** [comment]
Looks good to me. Scrapy maintainers will review and merge your PR when they will get a chance.
