### ISSUE TITLE
Beautify XML in scrapy-shell

### ISSUE THREAD

**Issue by deepakdinesh1123** [scrapy/scrapy#5417]
## Summary

When viewing the TextResponse in text editor I noticed that the xml was not formatted 

![Screenshot (19)](https://user-images.githubusercontent.com/52698821/153783185-b89c8fbf-dadc-42c8-b2e0-0bbdc7ad4485.png)

and I found a similar behavior while using selectors to select elements that have other elements in them 

![scrapy-shell](https://user-images.githubusercontent.com/52698821/153783279-a459c9aa-ffb5-465e-9ddc-3b64d8857eff.jpg)

I think I can implement a solution where I can Beautify them before printing to console or add a method that can prettify the XML when the user  needs it.

## Motivation

A similar thing was done in #1327 for Feed exports of XML and I think it would be a great addition in the shell.

It would be great in the case where the user selects an element with a number of child elements and instead of switching between browser and shell many times they can view it easily in the shell itself

## Describe alternatives you've considered

An alternate solution would be to beautify the response in the shell itself by using some external module, this would be okay as a one time solution but becomes repetitive.

## Additional Context

Some customization such as indent level spacing can also be provided for the user

**Comment by wRAR** [comment]
> When viewing the TextResponse in text editor I noticed that the xml was not formatted

Yes, we don't reformart the response body, that would be unhelpful as you may need to rely on the line breaks in some bad cases.

> I found a similar behavior while using selectors to select elements that have other elements in them

As you can see the string returned already contains `'\n'`. They are only rendered as newlines when you print the string. This is not related to Scrapy.

> I think I can implement a solution where I can Beautify them before printing to console or add a method that can prettify the XML when the user needs it.

So far I don't understand the use cases for this as neither of the two you provided is about printing something in the shell. Also, it's HTML, not XML.

> It would be great in the case where the user selects an element with a number of child elements and instead of switching between browser and shell many times they can view it easily in the shell itself

print() them.

**Comment by deepakdinesh1123** [comment]
Sorry for overlooking some basic things, I'll close this issue. I'll continue working on other issues
