### ISSUE TITLE
scrapy parse doesn't support async callbacks

### ISSUE THREAD

**Issue by wRAR** [scrapy/scrapy#5424]
In master when running `scrapy parse` for a spider with `async def parse` the page is downloaded but then the spider hangs. In #4978  it instead raises `TypeError: 'async_generator' object is not iterable`. Both problems happen because the parse command calls `iterate_spider_output` and doesn't expect a Deferred or an async iterator.

**Comment by GKukulski** [comment]
Hi, I have a problem with using `scrapy parse` with async function with yield inside.
The 'TypeError: 'async_generator' object is not iterable' is raising.
When i tested deleting 'asnyc' or 'yield' everything is fine...

**Comment by Gallaecio** [comment]
Please, if you believe this is a bug, open a separate ticket about it and provide a minimal, reproducible example.
