### ISSUE TITLE
ImportError: cannot import name 'soft_unicode' from 'markupsafe'

### ISSUE THREAD

**Issue by Gallaecio** [scrapy/scrapy#5425]
Looking at the CI jobs of https://github.com/scrapy/scrapy/pull/4267, https://github.com/pallets/markupsafe/issues/282 is hitting us in some scenarios.

**Comment by wRAR** [comment]
So I guess this is because old mitmproxy, which we use for older Python versions and in other cases, requires old Flask which is affected.

**Comment by wRAR** [comment]
I think it should be enough to pin markupsafe in the same cases that pin mitmproxy (also in conda).
