### ISSUE TITLE
Errback does not fire from exception

### ISSUE THREAD

**Issue by erichlin** [scrapy/scrapy#5438]
Errback does not fire from exception. It does however reach parse_listings and throw an exception that is caught by scrapy and logged.

```
import scrapy


class ListingsSpider(scrapy.Spider):
    name = 'listings'

    def start_requests(self):
        yield scrapy.Request(
            url="https://www.google.com/",
            callback = self.parse_listings,
            errback=self.error_handler,
        )

    def parse_listings(self, response, **request_kwargs):
        raise TimeoutError

    def error_handler(self, failure):
        self.logger.error("DOES NOT REACH HERE")
```

Scrapy       : 2.6.1
lxml         : 4.8.0.0
libxml2      : 2.9.12
cssselect    : 1.1.0
parsel       : 1.6.0
w3lib        : 1.22.0
Twisted      : 22.2.0
Python       : 3.10.0 (default, Mar  3 2022, 03:57:21) [Clang 12.0.0 ]
pyOpenSSL    : 22.0.0 (OpenSSL 1.1.1m  14 Dec 2021)
cryptography : 36.0.1
Platform     : macOS-10.16-x86_64-i386-64bit

**Comment by Laerte** [comment]
This is expected behaviour. The [documentation](https://docs.scrapy.org/en/latest/topics/request-response.html#scrapy.http.Request) state that:
> a function that will be called if any exception was raised **while processing the request**. This includes pages that failed with 404 HTTP errors and such.

**Comment by erichlin** [comment]
> This is expected behaviour. The [documentation](https://docs.scrapy.org/en/latest/topics/request-response.html#scrapy.http.Request) state that:
> 
> > **errback** - a function that will be called **if any exception was raised while processing the request**. This includes pages that failed with 404 HTTP errors and such.

Thanks for the reply. I'm confused. If the errback function is supposed to be called, then why was it *not* called?

**Comment by Laerte** [comment]
You are raising a exception **after** the request is processed. Because of this your exception are not handled by `errback`, this method is **only** called for errors caused before you finish the request so instead call the `callback` method Scrapy call `errback` method, get it? This is for HTTP/Connection errors basically.

**Comment by erichlin** [comment]
Ah I see. Okay , closing bug
