### ISSUE TITLE
Scrapy timeouts after FormRequest to IIS 5.1 server

### ISSUE THREAD

**Issue by llekn** [scrapy/scrapy#544]
As discussed here http://stackoverflow.com/questions/21177090/scrapy-gets-stuck-with-iis-5-1-page , having almost identical applications but being served with different versions of IIS makes scrapy unable to scrap the one served with IIS 5.1.

Why I think as this is related with IIS 5.1 servers: as discussed here http://code.google.com/p/go/issues/detail?id=2184 , IIS 5.1 returns HTTP 100 after every POST request, breaking some automated HTTP clients. It might be the case for scrapy also.

Long story short, how to reproduce the issue:
- Find a webpage with a form being served with IIS 5.1
- Create a spider that makes a FormRequest to the form
- Run the spider
- Scrapy will keep getting timeouts after sending the POST request

But forcing HTTP 1.0 by adding

```
DOWNLOAD_HANDLERS = {
    'http': 'scrapy.core.downloader.handlers.http10.HTTP10DownloadHandler',
    'https': 'scrapy.core.downloader.handlers.http10.HTTP10DownloadHandler',
}
```

to settings.py seems to solve the problem.

Shouldn't the spider work with the default (HTTP 1.1) handler?

P.S: Using Scrapy 0.20.2 (pip-installed)

**Comment by Gallaecio** [comment]
If this is specific to IIS 5.x, [maybe we could close this](https://w3techs.com/technologies/details/ws-microsoftiis).

**Comment by llekn** [comment]
> If this is specific to IIS 5.x, [maybe we could close this](https://w3techs.com/technologies/details/ws-microsoftiis).

I Agree, it seems it is not relevant anymore.
