### ISSUE TITLE
Scrapy engine hangs when no requests returned by a downloader middleware but empty download slot

### ISSUE THREAD

**Issue by akinad3** [scrapy/scrapy#5441]
### Description
I'm writing a scraper which should hit given enqueued requests at a given time in the day. 
Example: req1 should be allowed to go out between 1-3PM, req2 between 2-4PM.

I'm forcefully enqueuing all my requests in start_requests using `crawler.engine.slot.scheduler.enqueue_request(request)` rather then having a generator approach on enqueuing the start requests.

### Steps to Reproduce

I wrote a middleware which whenever called, check if the given request is allowed to go out or not (through attributes set on meta). If yes, returns None if not, reenqueues the request (return request).
I set the queue type to be FIFO rather than LIFO, so the middleware isn't hanging on the same request over and over again.

**Expected behavior:** [What you expect to happen]
Responses are handled correctly, even when no requests left to be sent out

**Actual behavior:** [What actually happens]
sending out a request with an empty downloader slot seems to be taking precedence over processing whatever responses are ready. 

Note: this does happen when CONCURRENT_REQUESTS = 1 also.

### Versions

Please paste here the output of executing `scrapy version --verbose` in the command line.
Scrapy 2.5.1, but also in Scrapy 2.6

Is there any other solution which would help acomplish my goal described at the beginning?

**Comment by yash-fn** [comment]
I could be wrong, but I just assumed that downloader middleware must send out a request. i.e. it's role isn't to decide which requests are allowed to progress but rather to fill a slot. Thus it will keep trying until slot is filled. The deciding part is for scheduler or other middleware/extensions. Could be wrong though. Best to hear from scrapy creators.

**Comment by yash-fn** [comment]
You could also go one layer up and write your spider to be called from another script which first decides if a request is ready to process before running spider using crawlerprocess or crawlerrunner.

**Comment by wRAR** [comment]
I'm afraid I'm not sure I've understood what are you doing, can you provide actual code as a minimal reproducible example?
