### ISSUE TITLE
2.6 introduced an undocumented field rename in request serialization

### ISSUE THREAD

**Issue by Gallaecio** [scrapy/scrapy#5464]
After https://github.com/scrapy/scrapy/pull/5130 the `_encoding` field of serialized requests is now named `encoding`, which is a backward-incompatible change not covered in the release notes.

We should either update the release notes or revert that change in the 2.6 branch.

 I found out about this is a scenario where the change turned out to break some tests. But given the change seems for the better (that was the only field prefixed with `_`), I think it may be better to keep the change and simply mention it in the 2.6 release notes for completeness.

I have no strong opinion either way, though.

**Comment by Gallaecio** [comment]
Specifically, this can break [scrapy-autounit](https://pypi.org/project/scrapy-autounit/) fixtures.

**Comment by wRAR** [comment]
How hard is to handle this in e.g. scrapy-autounit? I guess they will need to support both ways?

**Comment by wRAR** [comment]
Ah right.

Then I think it's fine to add this to release notes.
