### ISSUE TITLE
Add a command-line option for overwriting exported file

### ISSUE THREAD

**Issue by kmike** [scrapy/scrapy#547]
What do you think about adding an option to overwrite/recreate exported file?
Something like 

```
$ scrapy crawl myspider -o data.jl --overwrite
```

or 

```
$ scrapy crawl myspider -O data.jl
```

This is useful during development where old data is not needed. I usually run 

```
$ rm data.jl; scrapy crawl myspider -o data.jl
```

multiple times. This is not DRY: if I want to change file name for the next iteration and preserve existing file then I must be careful and update both names (of course, the command comes from shell autocompletion).

**Comment by alfg** [comment]
+1

Any progress on this?

**Comment by AaronTao1990** [comment]
+1 for -o option

**Comment by nyov** [comment]
The current PR looks inadequate to me. Sorry.
As an intermediate step, it should just fix the current issue, which is: appending doesn't work. This would mean producing `filename.out.1 filename.out.2 filename.out.3` filenames, instead.
(This could be the easy task)

Changing the behaviour to append/overwrite, looks more daunting. Doing it right would mean modifying the Exporter's codebase to handle append or overwrite options like a File interface (IMHO); implementation depending on the actual Exporter backend (local disk, s3, datastore, ...).
Also @kmike's proposal
> `scrapy crawl myspider -o combined.jl -O last.jl` can also be useful, and users will try writing this.

would require more thought. It sounds great, but if `--append`/`--overwrite` is not just a switch to `-o`, but an argument taking a destination, Exporters would have to be able to handle that (opening multiple "filepointers" as given). That doesn't warrant an `easy` tag, I think.

**Comment by jschilling1** [comment]
I've been using a custom CsvItemExporter to overwrite existing exports and use a custom CSV_DELIMITER in settings. Now i need to set the FEED_URI in the spider. The problem with that is that my custom CsvItemExporter no longer clears existing exports which it only does on init.

**Comment by dannykopping** [comment]
You can simply output to stdout and redirect that output to a file:
scrapy runspider spider.py -t json --nolog -o - > out.json

**Comment by lucaspottersky** [comment]
> You can simply output to stdout and redirect that output to a file:

@dannykopping this is not an option when scheduling through scrapyd.

**Comment by robkorv** [comment]
In the meantime one could subclass `FileFeedStorage`. I just typed an answer over at http://stackoverflow.com/a/40823149/2546958 before I spotted this issue.
