### ISSUE TITLE
scrapy - The request timestamp deviation value is too large

### ISSUE THREAD

**Issue by yinzhen1** [scrapy/scrapy#5470]
scrapy frame properties:
A large number of requests enter the queue, and then concurrent requests.

Question:
Since the header of the request is time stamped, the request is sent to the server. The server will check the deviation between the header time and the current time. If it exceeds a certain time, the server will consider it failed to prevent replay attacks.

Current solutions:
In downloadermiddleware, process_request-> The header is calculated in the request to minimize the time sent to the server. This method has solved the problem to a great extent.

Present situation:

It feels that the rate of request generation is still greater than the rate of request consumption, and there will still be some problems of excessive deviation.

Have you ever encountered such a problem? Or do you know anything about it? help help help 
Thank you very much

**Comment by wRAR** [comment]
This is an issue tracker. Please ask your questions at suitable places like StackOverflow.
