### ISSUE TITLE
Ignoring response 403

### ISSUE THREAD

**Issue by johny322** [scrapy/scrapy#5478]
Hi.
I try to make POST request with data and custom headers, but have 403 code.

headers: dict
cookies: dict
data: dict
req = scrapy.Request('my_url',
                             method='POST',
                             body=json.dumps(data),
                             headers=headers,
                             cookies=cookies,
                             callback=self.get_resp
                             )
But i faced a 403 error.

When i use requests lib, all work good
r = requests.post('my_url', data=data, headers=headers)

versions
Scrapy       : 2.6.1
lxml         : 4.8.0.0
libxml2      : 2.9.12
cssselect    : 1.1.0
parsel       : 1.6.0
w3lib        : 1.22.0
Twisted      : 22.2.0
Python       : 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)]
pyOpenSSL    : 22.0.0 (OpenSSL 1.1.1n  15 Mar 2022)
cryptography : 36.0.2
Platform     : Windows-10-10.0.18362-SP0

Please, help

**Comment by Gallaecio** [comment]
https://docs.scrapy.org/en/latest/#getting-help
