### ISSUE TITLE
Support relative urls better

### ISSUE THREAD

**Issue by kmike** [scrapy/scrapy#548]
Building an URL relative to current URL is a very common task; currently users are required to do that themselves - `import urlparse` and then `urlparse.urljoin(response.url, href)`. 

What do you think about adding a shortcut for that - something like `response.urljoin(href)` or `response.absolute_url(href)`? 

Another crazy idea is to support relative urls directly, by assuming they are relative to a `response.url`. I think it can be implemented as a spider middleware. I actually like this idea :)

**Comment by kmike** [comment]
For Scrapy 1.0 we're going to add `response.urljoin()` method. 

We haven't agreed on `.links()` vs `.extract_as_url()` vs `.with_absolute_links()` vs other proposals yet.

**Comment by kmike** [comment]
`response.urljoin` PR is merged. It is not the final solution for this problem, but we probably won't implement anything else for Scrapy 1.0, so I removed the milestone from this ticket.

**Comment by redapple** [comment]
@kmike , I have the feeling that the discussion for the remaining work is in https://github.com/scrapy/scrapy/issues/1940
If so, can this one be closed?

**Comment by kmike** [comment]
@redapple I think we should fix it from both sides: provide .links() method in parsel and create another API for scheduling requests in scrapy.

**Comment by redapple** [comment]
ok @kmike , 

> create another API for scheduling requests in scrapy.

this is https://github.com/scrapy/scrapy/issues/1940, correct?

and
> provide .links() method in parsel

can be covered withing https://github.com/scrapy/parsel/issues/26

**Comment by kmike** [comment]
Yep, if we agree that .links + #1940 is the way to solve this issue.

**Comment by kmike** [comment]
Scrapy now has `response.follow`, which is very similar to `response.newrequest` proposed by @dangra in https://github.com/scrapy/scrapy/issues/548#issuecomment-33066664. I think it solves the original issue - it allows to handle relative URLs correctly with minimal effor from the user.

**Comment by dannyeuu** [comment]
@kmike How about this feature be available by default on link extraction? I think, cuz everyone has to parse this, but it a common use for browsers.

**Comment by mc0e** [comment]
Found what I needed in @kmike's comment above.  Is there some reason to not consider that solution sufficient to close this issue?

**Comment by Gallaecio** [comment]
Fixed in #2540.
