### ISSUE TITLE
stats time error

### ISSUE THREAD

**Issue by Assistest** [scrapy/scrapy#5483]
**I passed spider.crawler. stats. get_ Stats() gets stats but start_Time and finish_Time is Error**

scrapy ->2022-04-21 16:14:10 [scrapy.core.engine] INFO: Closing spider (finished)
start_Time and finish_Time -> 2022-04-21 08:13:53.456974
What should I am going to do?

tk

**Comment by Gallaecio** [comment]
https://docs.scrapy.org/en/latest/#getting-help
