### ISSUE TITLE
How to parse the home page

### ISSUE THREAD

**Issue by 8502596** [scrapy/scrapy#5490]
![image](https://user-images.githubusercontent.com/15864647/166858520-8a3ea94c-a9cf-43ad-a259-11077f09946b.png)

I want to start parsing from the start page.
But when I run scrapy crawl test I find that the function parse_item() is not entered.
How to configure the project to achieve its purpose.

**Comment by wRAR** [comment]
This is the Scrapy issue tracker. Please ask questions about your code in suitable places like https://stackoverflow.com/
