### ISSUE TITLE
OpenSSL unsafe legacy renegotiation disabled error

### ISSUE THREAD

**Issue by HASKADOG** [scrapy/scrapy#5491]
### Description

I get an SSL issue on a working [site ](https://dorotheum.com) 
`twisted.web._newclient.ResponseNeverReceived: [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', '', 'unsafe legacy renegotiation disabled')]>]`

### Steps to Reproduce

1. `scrapy shell https://dorotheum.com`

**Expected behavior:** HTML page

**Actual behavior:** the error above

**Reproduces how often:** 100%

### Versions

```
Scrapy       : 2.6.1
lxml         : 4.8.0.0
libxml2      : 2.9.4
cssselect    : 1.1.0
parsel       : 1.6.0
w3lib        : 1.22.0
Twisted      : 22.4.0
Python       : 3.9.12 (main, Mar 26 2022, 15:44:31) - [Clang 13.1.6 (clang-1316.0.21.2)]
pyOpenSSL    : 22.0.0 (OpenSSL 3.0.3 3 May 2022)
cryptography : 37.0.2
Platform     : macOS-12.2.1-arm64-arm-64bit
```

**Comment by wRAR** [comment]
This is explicitly disabled in OpenSSL 3: https://www.openssl.org/docs/manmaster/man7/migration_guide.html

We may need to add some new OP_* flags to support conecting to these outdated servers.

**Comment by HASKADOG** [comment]
@wRAR Can downgrade OpenSSL, pyopenssl ang cryprography help in this situation?

**Comment by wRAR** [comment]
You should downgrade pyOpenSSL to a version that ships 1.1, assuming it uses a bundled one in your environment (which I suspect it does).

**Comment by wRAR** [comment]
You can usually access the underlying OpenSSL.SSL.Context object and call `set_options()` on it.

**Comment by HASKADOG** [comment]
@wRAR fixed by downgrading cryptography to  36.0.2

**Comment by Yoyoda75** [comment]
I'm having the same problem when trying to scrape the Cisco website for security advisories. How can I downgrade cryptography to a specific version inside of the scrapy package ?

**Comment by wRAR** [comment]
It's not "inside of the scrapy package", it's in your Python environment.

**Comment by dogweather** [comment]
I've having the same problem with Government of Ireland websites. E.g., 

```
scrapy fetch https://www.courts.ie/
```

Comes back with the error, 

```
2022-07-05 17:33:05 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://www.courts.ie/robots.txt> (failed 1 times): [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', '', 'unsafe legacy renegotiation disabled')]>]
```

Curl and various web browsers do fine with it.

**Comment by wRAR** [comment]
If you are going to contact the website owner just point them to https://www.ssllabs.com/ssltest/ results for their website.

**Comment by jeroenvermunt** [comment]
I want to drop this relevant link here:

https://stackoverflow.com/questions/71603314/ssl-error-unsafe-legacy-renegotiation-disabled/72374542#72374542

Here is a very useful piece of code to circumvent to issue without downgrading:

````
import requests
import urllib3
import SSL


class CustomHttpAdapter (requests.adapters.HTTPAdapter):
    # "Transport adapter" that allows us to use custom ssl_context.

    def __init__(self, ssl_context=None, **kwargs):
        self.ssl_context = ssl_context
        super().__init__(**kwargs)

    def init_poolmanager(self, connections, maxsize, block=False):
        self.poolmanager = urllib3.poolmanager.PoolManager(
            num_pools=connections, maxsize=maxsize,
            block=block, ssl_context=self.ssl_context)


def get_legacy_session():
    ctx = ssl.create_default_context(ssl.Purpose.SERVER_AUTH)
    ctx.options |= 0x4  # OP_LEGACY_SERVER_CONNECT
    session = requests.session()
    session.mount('https://', CustomHttpAdapter(ctx))
    return session
````

**Comment by wRAR** [comment]
(note that Scrapy doesn't use `requests`, so accessing the OpenSSL context from a spider is left as an exercise to the reader)

**Comment by aysegulc** [comment]
I ran into the same problem, and built a custom context factory to solve it. I hope it will be helpful for others:

contextfactory.py (within MyProject folder)

```
from scrapy.core.downloader.contextfactory import ScrapyClientContextFactory


class LegacyConnectContextFactory(ScrapyClientContextFactory):

    def getContext(self, hostname=None, port=None):
        ctx = self.getCertificateOptions().getContext()
        ctx.set_options(0x4)
        return ctx

```

within my_spider.py

```
class MySpider(Spider):
    name = "my_spider"

    custom_settings = {
        'DOWNLOADER_CLIENTCONTEXTFACTORY': 'MyProject.contextfactory.LegacyConnectContextFactory',
    }
```

**Comment by visar63** [comment]
Thanks @aysegulc, your suggestion works.

**Comment by paradox-lab** [comment]
> I ran into the same problem, and built a custom context factory to solve it. I hope it will be helpful for others:
> 
> contextfactory.py (within MyProject folder)
> 
> ```
> from scrapy.core.downloader.contextfactory import ScrapyClientContextFactory
> 
> 
> class LegacyConnectContextFactory(ScrapyClientContextFactory):
> 
>     def getContext(self, hostname=None, port=None):
>         ctx = self.getCertificateOptions().getContext()
>         ctx.set_options(0x4)
>         return ctx
> ```
> 
> within my_spider.py
> 
> ```
> class MySpider(Spider):
>     name = "my_spider"
> 
>     custom_settings = {
>         'DOWNLOADER_CLIENTCONTEXTFACTORY': 'MyProject.contextfactory.LegacyConnectContextFactory',
>     }
> ```

this code works too.

contextfactory.py
```python
from scrapy.core.downloader.contextfactory import ScrapyClientContextFactory
from cryptography.hazmat.bindings.openssl.binding import Binding


class LegacyConnectContextFactory(ScrapyClientContextFactory):
    def getContext(self, hostname=None, port=None):
        ctx = super(LegacyConnectContextFactory, self).getContext()
        binding = Binding()
        ctx.set_options(binding.lib.SSL_OP_ALLOW_UNSAFE_LEGACY_RENEGOTIATION)
        return ctx

```

**Comment by joseiram-avd** [comment]
> I ran into the same problem, and built a custom context factory to solve it. I hope it will be helpful for others:
> 
> contextfactory.py (within MyProject folder)
> 
> ```
> from scrapy.core.downloader.contextfactory import ScrapyClientContextFactory
> 
> 
> class LegacyConnectContextFactory(ScrapyClientContextFactory):
> 
>     def getContext(self, hostname=None, port=None):
>         ctx = self.getCertificateOptions().getContext()
>         ctx.set_options(0x4)
>         return ctx
> ```
> 
> within my_spider.py
> 
> ```
> class MySpider(Spider):
>     name = "my_spider"
> 
>     custom_settings = {
>         'DOWNLOADER_CLIENTCONTEXTFACTORY': 'MyProject.contextfactory.LegacyConnectContextFactory',
>     }
> ```

thanks.
