### ISSUE TITLE
Items do not reach other pipelines after using 'scrapy.pipelines.files.FilesPipeline'

### ISSUE THREAD

**Issue by dsism** [scrapy/scrapy#5499]
I noticed that when adding `'scrapy.pipelines.files.FilesPipeline'` to my spider, less pages/items are processed in other custom pipelines I have.

When I remove`FilesPipeline`, the number of items processed in my custom pipeline matches  with the value set in `CLOSESPIDER_PAGECOUNT`.

I've tried changing the priority of my custom pipeline to run before `FilesPipeline`, but that didn't work. I can only access all pages/items if I remove `FilesPipeline` (which is not an option as I need it). There are no error in the logs for `scrapy.pipelines.files`. 

**Has anyone had a similar problem or have any idea what could be going on?**

**To replicate:**
- create a spider with `'scrapy.pipelines.files.FilesPipeline'` and another custom pipeline having a log in `process_item`.
- In settings add a value for `CLOSESPIDER_PAGECOUNT`.

**Issue :** the number of logs displayed will be less than what is defined in `CLOSESPIDER_PAGECOUNT`. 
If you remove `FilesPipeline`, you will have a number of logs  similar to the value of `CLOSESPIDER_PAGECOUNT`

**Comment by Gallaecio** [comment]
While it sounds like it may be a valid issue, could you elaborate on this?

> I've tried changing the priority of my custom pipeline to run before `FilesPipeline`, but that didn't work.

Even if there is a bug in `FilesPipeline`, that cannot prevent the parsing of items in earlier pipelines.
