### ISSUE TITLE
Link open on the same page

### ISSUE THREAD

**Issue by Sumit-jr** [scrapy/scrapy#5527]
## Summary

When we click the link on scrapy readme.md file, it opens in the same tab

## Motivation

Why are we doing this? What use cases does it support? What is the expected outcome?
Opening the links on the new tab will help people to see what's running on the new tab and previous scrapy readme.md tab and it saves times too to open that tab again & again.

The expected outcome is whenever we click on the link it should automatically opens in the new tab

## Describe alternatives you've considered
The one alternative can be right click on link using mouse and open in new tab but it's not effective one 
## Additional context

Any additional information about the feature request here.

**Comment by Gallaecio** [comment]
It is up to GitHub how it renders links in Markdown files, not us.
