### ISSUE TITLE
Pausing crawlers after a certain active period always starts right after spider begins

### ISSUE THREAD

**Issue by xxxDollbarBill** [scrapy/scrapy#5550]
I'm investigating into pausing my crawlers at specified activate periods during the spider running. However, I have noticed that my spider would always pause at the start, regardless of the signal I send it to.

Are there existing ways specify when to pause?

I had assumed the following would work:
```
    end_time = datetime.timedelta(seconds = 15)
    def __init__(self, stats, pause):
       self.stats = stats
       self.pause = pause

    @classmethod
    def from_crawler(cls, crawler, *args, **kwargs):
        #spider = super(TestSpider, cls).from_crawler(crawler, *args, **kwargs)
        stat = cls(crawler.stats, crawler)
        crawler.signals.connect(stat.spider_opened, signals.spider_opened)
        return stat

    def spider_opened(self):
        
        start_time = self.stats.get_stats()['start_time']
        if datetime.datetime.now().time() >= (start_time+ self.end_time).time():
            print(f"The time final: {datetime.datetime.now().time()}, the start time: {start_time.time()}, combined time: {(start_time+ self.end_time).time()} and the end-time: {self.end_time}")
            self.pause.engine.pause()
```

However, the crawler would not react to the condition, and it would go straight into pause. Are there ways to for this condition to hold, otherwise:
1. Why does it not hold?
2. why does it always pause at the start?

Some reproducible code:

```
import scrapy
from scrapy import signals
import datetime

class TestSpider(scrapy.Spider):
    name = 'stats'
    start_urls = start_urls = [f'https://quotes.toscrape.com/page/{i}/' for i in range(1, 11)]

    custom_settings = {
        'DOWNLOAD_DELAY':2
    }

    end_time = datetime.timedelta(seconds = 15)
    def __init__(self, stats, pause):
       self.stats = stats
       self.pause = pause

    @classmethod
    def from_crawler(cls, crawler):
        stat = cls(crawler.stats, crawler)
        crawler.signals.connect(stat.spider_opened, signals.spider_opened)
        return stat

    def spider_opened(self):
        start_time = self.stats.get_stats()['start_time']
        if datetime.datetime.now().time() >= (start_time+ self.end_time).time():
            print(f"The time final: {datetime.datetime.now().time()}, the start time: {start_time.time()}, combined time: {(start_time+ self.end_time).time()} and the end-time: {self.end_time}")
            self.pause.engine.pause()

    def parse(self, response):
        pass
```

**Comment by lime-n** [comment]
You can try:

```
reactor.CallLaterOnce(self.pause.engine.pause).schedule(delay=10)
self.pause.engine.unpause()
```

Then `delay` should be the count in seconds for the schedule. I have tried it on your example however the works works but the `schedule` still hangs and so it won't unpause. Perhaps this is a bug? 

`cancel()` works properly for this case just not schedule.

**Comment by wRAR** [comment]
> Are there existing ways specify when to pause?

This is an issue tracker, not a place to ask usage questions.

**Comment by xxxDollbarBill** [comment]
> > Are there existing ways specify when to pause?
> 
> This is an issue tracker, not a place to ask usage questions.

Besides that usage question as it was not really my intention for this post it's just that I am new at identifying what may be an issue. Does it seem right then to say that pausing the engine should override all delays implemented on it? 

I have tried lime-n's approach and it still continues to pause after the delay, but other functions work. Whereas, if I implement 

```
time.sleep(3)
```

It will delay for 3 seconds and continue to the next method and unpause. Are these expected behaviours for `pause`?

**Comment by xxxDollbarBill** [comment]
> > Does it seem right then to say that pausing the engine should override all delays implemented on it?
> 
> No, whatever you mean by that.

If that is the case then I am concerned as to why it still pauses after a schedule delay. Shouldn't some interface be implemented similar to [IDelayedCall](https://twisted.org/documents/21.2.0/api/twisted.internet.interfaces.IDelayedCall.html), with additional features such as when it should delay, reset or cancel the delay? First things first though, the delay should work with the schedule when implementing a pause.

**Comment by xxxDollbarBill** [comment]
Here is a minimal example reproducing the hang after a delay:

```
import scrapy
from scrapy.utils import reactor
from scrapy import signals
import logging

logger = logging.getLogger(__name__)

class TestSpider(scrapy.Spider):

    name = 'pause'
    start_urls =  [ f'http://quotes.toscrape.com/page/{i}/' for i in range(1, 11) ]

    custom_settings = {
        'DOWNLOAD_DELAY':2
    }

    def __init__(self, stats, pause):
       self.stats = stats
       self.pause = pause

    @classmethod
    def from_crawler(cls, crawler, *args, **kwargs):
        #spider = super(TestSpider, cls).from_crawler(crawler, *args, **kwargs)
        stat = cls(crawler.stats, crawler)
        crawler.signals.connect(stat.spider_opened, signals.spider_opened)
        return stat

    def spider_opened(self):
        reactor.CallLaterOnce(self.pause.engine.pause).schedule(8)
        self.pause.engine.unpause()

    def parse(self, response):
        logger.info("Urls passed to: %s", response.url)
```

**Comment by wRAR** [comment]
This code pauses the engine after 8 seconds so it sounds like it's working as expected.

**Comment by xxxDollbarBill** [comment]
> This code pauses the engine after 8 seconds so it sounds like it's working as expected.

It does not unpause right after, whereby a common implementation such as:

```
self.pause.engine.pause()
self.pause.engine.unpause()
```

would pause and immediately unpause right after. I want to iterate that this does not happen, therefore the unpause is not working in this case and so pause is somehow hanging in the reactor.

**Comment by wRAR** [comment]
> It does not unpause right after,

Sure, and it shouldn't.

You may be thinking that `reactor.CallLaterOnce(self.pause.engine.pause).schedule(8)` blocks. It obviously doesn't.

**Comment by xxxDollbarBill** [comment]
For example, this works as expected:

```
    def schedule(self, delay=0):
        from twisted.internet import reactor
        if self._call is None:
            self._call = task.deferLater(clock=reactor,delay=delay, callable=self) 
            #self._call = reactor.callLater(delay, self)
```

**Comment by wRAR** [comment]
> Therefore, may I suggest using twisted.internet.task.deferLater so an additional object can be called after the delay

You are free to use user-defined functions there.

**Comment by xxxDollbarBill** [comment]
> > Therefore, may I suggest using twisted.internet.task.deferLater so an additional object can be called after the delay
> 
> You are free to use user-defined functions there.

Right, I have amended the code above to implement an additional function but pause still overrides the next callback. I guess I could look into how to work around pause over-riding all delays and additional callbacks sent to it.

I'll post it here if I come up with anything interesting.

**Comment by wRAR** [comment]
*shrug* that part of code is still "unpause now, pause after 8 seconds".

Please use suitable platforms to get help with your code.

**Comment by Gallaecio** [comment]
I cannot but stress what wRAR said. This is not the place to discuss your specific issue. Use one of our [community channels](https://scrapy.org/community/) (Discord is probably best, given the number of messages here so far). If at some point you understand why everything works the way it does, but there is a specific behavior that you believe should be changed in Scrapy, feel free to open a feature request or bug report about it.
