### ISSUE TITLE
Attempting to acquire lock

### ISSUE THREAD

**Issue by Mankvis** [scrapy/scrapy#5555]
### Description

The latest version will continuously output the following content during use
[filelock] DEBUG: Attempting to acquire lock 4600430160 on

2022-07-13 11:15:34 [filelock] DEBUG: Attempting to acquire lock 4469884432 on ...... __a22fb8__tldextract-3.3.1/publicsuffix.org-tlds/de84b5ca2167d4c83e38fb162f2e8738.tldextract.json.lock
2022-07-13 11:15:34 [filelock] DEBUG: Lock 4469884432 acquired on  ...... __tldextract-3.3.1/publicsuffix.org-tlds/de84b5ca2167d4c83e38fb162f2e8738.tldextract.json.lock
2022-07-13 11:15:34 [filelock] DEBUG: Attempting to release lock 4469884432 on  ...... __a22fb8__tldextract-3.3.1/publicsuffix.org-tlds/de84b5ca2167d4c83e38fb162f2e8738.tldextract.json.loc

### Steps to Reproduce

After using genspider. to generate the crawler, you can execute it directly

### Versions

Scrapy       : 2.6.103
lxml         : 4.9.1.0
libxml2      : 2.9.4
cssselect    : 1.1.0
parsel       : 1.6.0
w3lib        : 1.22.0
Twisted      : 22.4.0
Python       : 3.10.5 (main, Jul 12 2022, 09:59:34) [Clang 13.0.0 (clang-1300.0.29.30)]
pyOpenSSL    : 22.0.0 (OpenSSL 3.0.5 5 Jul 2022)
cryptography : 37.0.4
Platform     : macOS-12.4-x86_64-i386-64bit

**Comment by elacuesta** [comment]
Those are debug lines coming from the use of [tldextract](https://pypi.org/project/tldextract/) in the cookies middleware. They are expected, and from your report I don't see them actually causing a problem. If you absolutely don't want to see them, you could for instance:
* set the general log level to one higher than DEBUG via the `LOG_LEVEL` setting (`scrapy crawl spider_name -s LOG_LEVEL=INFO`)
* set the log level of that specific logger in your code
```python
import logging

logging.getLogger("filelock").setLevel(logging.INFO)
```

**Comment by Yanzuzhang** [comment]
> ### Description
> The latest version will continuously output the following content during use [filelock] DEBUG: Attempting to acquire lock 4600430160 on
> 
> 2022-07-13 11:15:34 [filelock] DEBUG: Attempting to acquire lock 4469884432 on ...... __a22fb8__tldextract-3.3.1/publicsuffix.org-tlds/de84b5ca2167d4c83e38fb162f2e8738.tldextract.json.lock 2022-07-13 11:15:34 [filelock] DEBUG: Lock 4469884432 acquired on ...... __tldextract-3.3.1/publicsuffix.org-tlds/de84b5ca2167d4c83e38fb162f2e8738.tldextract.json.lock 2022-07-13 11:15:34 [filelock] DEBUG: Attempting to release lock 4469884432 on ...... __a22fb8__tldextract-3.3.1/publicsuffix.org-tlds/de84b5ca2167d4c83e38fb162f2e8738.tldextract.json.loc
> 
> ### Steps to Reproduce
> After using genspider. to generate the crawler, you can execute it directly
> 
> ### Versions
> Scrapy : 2.6.103 lxml : 4.9.1.0 libxml2 : 2.9.4 cssselect : 1.1.0 parsel : 1.6.0 w3lib : 1.22.0 Twisted : 22.4.0 Python : 3.10.5 (main, Jul 12 2022, 09:59:34) [Clang 13.0.0 (clang-1300.0.29.30)] pyOpenSSL : 22.0.0 (OpenSSL 3.0.5 5 Jul 2022) cryptography : 37.0.4 Platform : macOS-12.4-x86_64-i386-64bit

I made the same mistake

**Comment by Gallaecio** [comment]
Note that Scrapy 2.8.0 silences those messages.
