### ISSUE TITLE
Can't perform scraping on a dynamic Website 

### ISSUE THREAD

**Issue by athulkannan2000** [scrapy/scrapy#5569]
## Summary
While scraping the data from a dynamic website the returning an empty list as response. How to solve that ?

One paragraph explanation of the feature.

## Motivation

Why are we doing this? What use cases does it support? What is the expected outcome?

## Describe alternatives you've considered

A clear and concise description of the alternative solutions you've considered. Be sure to explain why Scrapy's existing customizability isn't suitable for this feature.

## Additional context

Any additional information about the feature request here.

**Comment by Gallaecio** [comment]
Please, do not use the Scrapy issue tracker to ask for help. See https://docs.scrapy.org/en/latest/#getting-help.
