### ISSUE TITLE
Improve the overwrite feed option documentation

### ISSUE THREAD

**Issue by Gallaecio** [scrapy/scrapy#5579]
The [`overwrite` feed option](https://docs.scrapy.org/en/latest/topics/feed-exports.html#feed-options) has a different default value depending on the storage backend used, and we currently cover its default value for all backeds except for [Google Cloud Storage (GCS)](https://docs.scrapy.org/en/latest/topics/feed-exports.html#google-cloud-storage-gcs). We should address that.

Also, since `overwrite=True` is a potentially data-deleting operation, it may be a good idea to mention the fact that `overwrite=True` in the sections about storage backends with that default value, and not just in the section about the `overwrite` feed option.

**Comment by limury** [comment]
Hi! I'd like to take on this issue. I think that GCS also does not allow appending to the storage. Also saw that the GCS initializer does not include a `feed_options` parameter so I'll add that!
