### ISSUE TITLE
If close the crawler in the crawler middleware, an unexpected error will be output in the log

### ISSUE THREAD

**Issue by Akise** [scrapy/scrapy#5586]
### Description

If close the crawler in the crawler middleware, an unexpected error will be output in the log.
Below is the log

> 2022-08-01 21:30:57 [scrapy.core.engine]:358 INFO: Closing spider (Close spider!)
2022-08-01 21:31:01 [scrapy.statscollectors]:46 INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 49379,
 'downloader/request_count': 89,
 'downloader/request_method_count/GET': 89,
 'downloader/response_bytes': 411684,
 'downloader/response_count': 89,
 'downloader/response_status_count/200': 32,
 'downloader/response_status_count/404': 57,
 'elapsed_time_seconds': 155.909975,
 'finish_reason': 'Close spider!',
 'finish_time': datetime.datetime(2022, 8, 1, 13, 31, 1, 269119),
 'httpcompression/response_bytes': 1429945,
 'httpcompression/response_count': 89,
 'item_scraped_count': 82,
 'log_count/INFO': 17,
 'log_count/WARNING': 5,
 'request_depth_max': 2,
 'response_received_count': 89,
 'scheduler/dequeued': 89,
 'scheduler/dequeued/disk': 89,
 'scheduler/enqueued': 207,
 'scheduler/enqueued/disk': 207,
 'start_time': datetime.datetime(2022, 8, 1, 13, 28, 25, 359144)}
2022-08-01 21:31:01 [scrapy.core.engine]:385 INFO: Spider closed (Close spider!)
2022-08-01 21:31:01 [scrapy.core.engine]:188 INFO: Error while scheduling new request
Traceback (most recent call last):
  File "C:\Users\Kitsune\AppData\Local\Programs\Python\Python39\lib\site-packages\twisted\internet\task.py", line 526, in _oneWorkUnit
    result = next(self._iterator)
StopIteration
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\Kitsune\AppData\Local\Programs\Python\Python39\lib\site-packages\twisted\internet\defer.py", line 857, in _runCallbacks
>     current.result = callback(  # type: ignore[misc]
>   File "C:\Users\Kitsune\AppData\Local\Programs\Python\Python39\lib\site-packages\scrapy\core\engine.py", line 187, in <lambda>
>     d.addBoth(lambda _: self.slot.nextcall.schedule())
> AttributeError: 'NoneType' object has no attribute 'nextcall'
> 

### Steps to Reproduce

1. Add spider middleware
```
class ExceptionHandler:
    def process_spider_output(self, response, exception, spider):
        spider.crawler.engine.close_spider(spider, ' Close spider!')
```

2. run

**Expected behavior:**  I hope it can be closed normally in the spider middleware

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

Scrapy 2.6.1

**Comment by wRAR** [comment]
This is most likely #5437, fixed in 2.6.2. Please reopen if this still happens in 2.6.2.
