### ISSUE TITLE
KeyError: 'depth' always appears after upgrading to 2.6.2

### ISSUE THREAD

**Issue by Akise** [scrapy/scrapy#5587]
### Description
It works fine under 2.6.1, but there is a problem when upgrading to 2.6.2

> 

> 2022-08-02 19:42:06 [scrapy.core.engine]:316 INFO: Spider opened
> 2022-08-02 19:42:06 [scrapy.extensions.logstats]:48 INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
> 2022-08-02 19:42:06 [scrapy.extensions.telnet]:67 INFO: Telnet console listening on 127.0.0.1:6023
> 2022-08-02 19:42:07 [ranking]:44 INFO: Start request task.
> 2022-08-02 19:42:07 [ranking]:56 INFO: Rank: >startDate:2015-05-29 - <=endDate:2015-05-30
> 2022-08-02 19:42:07 [ranking]:67 INFO: End request task.
> 2022-08-02 19:42:08 [root]:129 ERROR: ExceptionHandler: Spider error processing <GET https://www.xxx.net/ranking.php?mode=daily&date=20150530&p=1&format=json> 
> Traceback (most recent call last):
>   File "C:\Users\Kitsune\AppData\Local\Programs\Python\Python39\lib\site-packages\scrapy\core\spidermw.py", line 66, in _evaluate_iterable
>     for r in iterable:
>   File "C:\Users\Kitsune\AppData\Local\Programs\Python\Python39\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
>     return (r for r in result or () if _filter(r))
>   File "C:\Users\Kitsune\AppData\Local\Programs\Python\Python39\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 33, in _filter
>     depth = response.meta['depth'] + 1
> KeyError: 'depth'
> 2022-08-02 19:42:08 [scrapy.core.engine]:361 INFO: Closing spider (ExceptionHandler get an exception, Close spider!)
> 2022-08-02 19:42:08 [scrapy.statscollectors]:46 INFO: Dumping Scrapy stats:
> {'downloader/request_bytes': 1879,
>  'downloader/request_count': 2,
>  'downloader/request_method_count/GET': 2,
>  'downloader/response_bytes': 15390,
>  'downloader/response_count': 2,
>  'downloader/response_status_count/200': 2,
>  'elapsed_time_seconds': 2.635207,
>  'finish_reason': 'ExceptionHandler get an exception, Close spider!',
>  'finish_time': datetime.datetime(2022, 8, 2, 11, 42, 8, 929411),
>  'httpcompression/response_bytes': 51561,
>  'httpcompression/response_count': 2,
>  'log_count/ERROR': 1,
>  'log_count/INFO': 13,
>  'request_depth_max': 1,
>  'response_received_count': 2,
>  'scheduler/dequeued': 2,
>  'scheduler/dequeued/disk': 2,
>  'scheduler/enqueued': 3,
>  'scheduler/enqueued/disk': 3,
>  'start_time': datetime.datetime(2022, 8, 2, 11, 42, 6, 294204)}
> 2022-08-02 19:42:08 [scrapy.core.engine]:388 INFO: Spider closed (ExceptionHandler get an exception, Close spider!)

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

Please paste here the output of executing `scrapy version --verbose` in the command line.

### Additional context

Any additional information, configuration, data or output from commands that might be necessary to reproduce or understand the issue. Please try not to include screenshots of code or the command line, paste the contents as text instead. You can use [GitHub Flavored Markdown](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) to make the text look better.

**Comment by wRAR** [comment]
Please provide a minimal reproducible example of this problem.

**Comment by Akise** [comment]
It may be my fault, do some cleanup of meta on next request
```
def parse(self, response):
    meta= response.meta
    meta.pop("depth", 0)
    meta.pop("bindaddress", 0)
    # meta.pop("dont_cache", 0)
    # meta.pop("dont_merge_cookies", 0)
    # meta.pop("dont_obey_robotstxt", 0)
    # meta.pop("dont_redirect", 0)
    # meta.pop("dont_retry", 0)
    meta.pop("download_fail_on_dataloss", 0)
    meta.pop("download_latency", 0)
    meta.pop('download_slot', 0)
    meta.pop("download_maxsize", 0)
    meta.pop("download_timeout", 0)
    meta.pop("ftp_password", 0)
    meta.pop("ftp_user", 0)
    meta.pop("handle_httpstatus_all", 0)
    meta.pop("handle_httpstatus_list", 0)
    meta.pop("max_retry_times", 0)
    meta.pop("retry_times", 0)
    meta.pop("proxy", 0)
    meta.pop("redirect_reasons", 0)
    meta.pop("redirect_urls", 0)
    meta.pop("referrer_policy", 0)
    yield scrapy.Request(url=nextUrl, meta=meta)
```

**Comment by wRAR** [comment]
Good.
