### ISSUE TITLE
Make asyncio reactor a default

### ISSUE THREAD

**Issue by kmike** [scrapy/scrapy#5590]
Should we make 'twisted.internet.asyncioreactor.AsyncioSelectorReactor' a default? If so, should it be default in Scrapy 2.7, or is it too soon? We can start with making it default in the project template; it looks safe enough for Scrapy 2.7, or is it?

The reactor was introduced in Scrapy 2.0; I don't recall any particular issues reported about it. It'd be good to have it as a default eventually, because there are more an more Scrapy plugins which rely on asyncio libraries.

**Comment by pablohoffman** [comment]
Are there any big users/projects using the asyncio reactor @kmike?

**Comment by kmike** [comment]
@pablohoffman packages like 

* https://github.com/scrapy-plugins/scrapy-playwright/, 
* https://github.com/scrapinghub/scrapy-autoextract, 
* https://github.com/scrapy-plugins/scrapy-zyte-api 
 
require asyncio reactor; any Scrapy project which uses one of these extensions needs to switch to ascynio reactor.

**Comment by elacuesta** [comment]
Related: #5103

**Comment by pablohoffman** [comment]
Thanks. As far as I'm concerned, it makes sense, and changing the default project template is a good way to start.
