### ISSUE TITLE
ignore tags 

### ISSUE THREAD

**Issue by baharmf93** [scrapy/scrapy#5591]
How can I make scrapy ignore certain tags and totally ignore html attributes?
Is this feature?
Can we also tell Scrapy to ignore the images? To improve the speed of crawl and bandwidth

**Comment by kmike** [comment]
hey! Please check https://docs.scrapy.org/en/latest/#getting-help. We use github issues to track bugs and feature requests, not for Scrapy usage questions. Thanks!

**Comment by baharmf93** [comment]
thanks [kmike](https://github.com/kmike)
But I think this is not the case, so this is a request to add a new feature.

**Comment by Gallaecio** [comment]
Your questions seem to suggest a lack of familiarity with the basics of Scrapy. I would suggest to get a bit more familiar with Scrapy, with what it does, what it can do and what it cannot do, before requesting features that might already exist, or are trivial to achieve through existing features.

If you still think your feature request makes sense, though, please elaborate more, with minimal code examples of what Scrapy would look like without and with the feature, and please stick to 1 feature request per issue where possible.
