### ISSUE TITLE
Images on Google Cloud Storage will not be properly skipped if IMAGES_STORE has any blob prefix

### ISSUE THREAD

**Issue by isaacimholt** [scrapy/scrapy#5594]
### Description

Images on Google Cloud Storage will not be properly marked as `uptodate` if `IMAGES_STORE` contains anything other than the bucket name.

**Expected behavior:** Images are skipped

**Actual behavior:** Images are not skipped

**Reproduces how often:** 100% if `IMAGES_STORE` contains anything other than the bucket name e.g. a blob prefix.

### Versions

2.6.2

I have fixed this issue by adding `self.prefix` to the `get_blob` function, I will link a PR soon.

**Comment by isaacimholt** [comment]
ah I see that this has been taken care of in https://github.com/scrapy/scrapy/pull/5318 this issue can be closed. Is there any ETA on a release with this fix?

**Comment by Gallaecio** [comment]
No ETA for 2.7 at the moment, sorry.
