### ISSUE TITLE
ImagesPipeline does not download images

### ISSUE THREAD

**Issue by uyha** [scrapy/scrapy#5595]
### Description

I am trying to download images from books.toscrape.com using `ImagesPipeline` but nothing was downloaded, if I switched to `FilesPipeline` then all the images were downloaded.

### Steps to Reproduce
1. Have the project set up as follows
```
crawlers
  |
  |-- spiders/
  |    |--spider.py
  |--__init__.py
  |--items.py
  |--middlewares.py
  |--pipelines.py
  |--settings.py
  |--images/
```
```python
#spider.py
import scrapy

class CrawlerSpider(scrapy.Spider):
  name = "crawler"

  def start_requests(self):
    url = "http://books.toscrape.com"
    yield = scrapy.Request(url=url, callback=self.parse)

  def parse(self, response):
    yield {
      "image_urls": [f"http://books.toscrape.com/{url}" for url in response.xpath("//img/@src").extract()]
    }
```

```python
#settings.py
BOT_NAME = "crawlers"
SPIDER_MODULES = ["crawlers.spiders"]
NEWSPIDER_MODULE = "crawlers.spiders"

ITEM_PIPELINES = {"scrapy.pipelines.images.ImagesPipeline": 1}
IMAGES_STORE = "images/"
```
3. Running `scrapy crawl crawler`

**Expected behavior:**
Images in books.toscrape.com to be downloaded in the `images/` directory

**Actual behavior:**
Nothing happens

**Reproduces how often:**
Always

### Versions
Scrapy       : 2.6.2
lxml         : 4.9.1.0
libxml2      : 2.9.14
cssselect    : 1.1.0
parsel       : 1.6.0
w3lib        : 1.22.0
Twisted      : 22.4.0
Python       : 3.8.10 (default, Jun 22 2022, 20:18:18) - [GCC 9.4.0]
pyOpenSSL    : 22.0.0 (OpenSSL 3.0.5 5 Jul 2022)
cryptography : 37.0.4
Platform     : Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.29

**Comment by Gallaecio** [comment]
Any chance your logs show something like this?

```
2022-08-12 09:10:27 [scrapy.middleware] WARNING: Disabled ImagesPipeline: ImagesPipeline requires installing Pillow 4.0.0 or later
2022-08-12 09:10:27 [scrapy.middleware] INFO: Enabled item pipelines:
[]
```

**Comment by uyha** [comment]
ah yes, silly me, installing `Pillow` fixes the issue
