### ISSUE TITLE
Scrapy removes `cookie` header

### ISSUE THREAD

**Issue by xoelop** [scrapy/scrapy#5596]
### Description

When passing a headers dictionary that contains a key named `cookie`, it doesn't send it in the final request. 

Making the same request with `requests.get()` works fine.

### Steps to Reproduce

1. Run netcat `nc -l 8080` to read the incoming request
2. Spider code:

```
# cookie_spider.py

import scrapy
from scrapy import Request


from scrapy.http import Response


class CookieSpider(scrapy.Spider):
    name = "cookiesspider"
    COOKIES_ENABLED = True

    headers = {
        "cookie": "bcookie=random_cookie",
        "user-agent": "Mozilla/5.0 (Linux; Android 11; Pixel 5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.91 Mobile Safari/537.36",
    }

    def start_requests(self):
        urls = ["http://localhost:8080"]

        for url in urls:
            request = self.prepare_request(url)
            yield request

    def parse(self, response: Response, **kwargs):
        pass

    def prepare_request(self, url: str = None):
        request = Request(
            url=url,
            callback=self.parse,
            headers=self.headers,
        )
        return request
```
3. Run doing `scrapy runspider cookie_spider.py`

4. Netcat output:

```
GET / HTTP/1.1
User-Agent: Mozilla/5.0 (Linux; Android 11; Pixel 5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.91 Mobile Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en
Accept-Encoding: gzip, deflate
Host: localhost:8080
```

**Expected behavior:** A `cookie` header should have been sent.

**Actual behavior:** No `cookie` header is shown in the netcat output.

**Reproduces how often:** 100%

### Versions

Scrapy       : 2.6.2
lxml         : 4.9.1.0
libxml2      : 2.9.14
cssselect    : 1.1.0
parsel       : 1.6.0
w3lib        : 1.22.0
Twisted      : 22.4.0
Python       : 3.9.6 (default, Feb  9 2022, 12:15:20) - [Clang 13.0.0 (clang-1300.0.27.3)]
pyOpenSSL    : 22.0.0 (OpenSSL 3.0.5 5 Jul 2022)
cryptography : 37.0.4
Platform     : macOS-12.0.1-x86_64-i386-64bit
### Additional context

Making the request with Python Requests works fine:

```
import requests

url = "http://localhost:8080"

headers = {
    "cookie": "bcookie=random_cookie",
    "user-agent": "Mozilla/5.0 (Linux; Android 11; Pixel 5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.91 Mobile Safari/537.36",
}

r = requests.get(url, headers=headers)
```

Netcat output:

```
GET / HTTP/1.1
Host: localhost:8080
user-agent: Mozilla/5.0 (Linux; Android 11; Pixel 5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.91 Mobile Safari/537.36
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
cookie: bcookie=random_cookie
```

**Comment by Gallaecio** [comment]
See the documentation of the `headers` parameter of `Request` at https://docs.scrapy.org/en/latest/topics/request-response.html#scrapy.http.Request

**Comment by xoelop** [comment]
For completeness, I found the solution. As the docs say, cookies can only be passed via the `cookies` parameter.

Note that if the cookie is passed in the header in the original request it's typically a string, separated by `; `. You'll have to split that and build a new dictionary to be passed to cookies. This worked for me.

```python
    def prepare_request(self, url: str = None):
        cookies = {}
        els = self.headers['cookie'].split('; ')
        for el in els:
            key = el.split("=", 1)[0]
            value = el.split("=", 1)[1]
            if not value.startswith('"'):
                value = f'"{value}"'
            cookies[key] = value

        # breakpoint()
        request = Request(
            url=url,
            callback=self.parse_jobs_page,
            headers=self.headers,
            cookies=cookies
        )

```


PS: I'd be sweet if we could pass a cookie header :). Thanks for your work on Scrapy anyways guys!

**Comment by Gallaecio** [comment]
> PS: I'd be sweet if we could pass a cookie header :)

We actually implemented it, but had to revert the change, and plan to do it again at some point. See the 2nd bullet point of https://github.com/scrapy/scrapy/issues/5431.
