### ISSUE TITLE
BOM should take precedence over Content-Type header when detecting the encoding

### ISSUE THREAD

**Issue by kmike** [scrapy/scrapy#5601]
Currently Scrapy uses headers first to detect the encoding. But browsers actually put a higher priority for BOM; this is also in WHATWG [standard](https://html.spec.whatwg.org/multipage/parsing.html#determining-the-character-encoding). It can be checked e.g. by running this server, and opening URL in a browser - UTF-8 is used by browser, but cp1251 is used by Scrapy:

```py
import codecs
from http.server import BaseHTTPRequestHandler
from http.server import HTTPServer


class HttpGetHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        self.send_response(200)
        self.send_header("Content-type", "text/html; charset=cp1251")
        self.end_headers()
        self.wfile.write(codecs.BOM_UTF8)
        self.wfile.write("<!DOCTYPE html>".encode('utf8'))
        self.wfile.write("Привет!".encode('utf8'))


if __name__ == '__main__':
    httpd = HTTPServer(('', 8000), HttpGetHandler)
    httpd.serve_forever()
```

When opening this page in a browser, it shows "Привет!".

Spider code to check it:

```py
import scrapy
from scrapy.crawler import CrawlerProcess


class MySpider(scrapy.Spider):
    name = "tst"

    start_urls = ["http://0.0.0.0:8000"]

    def parse(self, response):
        return {"encoding": response.encoding, "text": response.text}


if __name__ == '__main__':
    process = CrawlerProcess()
    process.crawl(MySpider)
    process.start()
```

Spider outputs

> {'encoding': 'cp1251', 'text': 'п»ї<!DOCTYPE html>РџСЂРёРІРµС‚!'}

See also: https://github.com/scrapy/w3lib/issues/189 - it's a similar issue, but fixing it in w3lib is not enough to make it working in Scrapy.

**Comment by simapple** [comment]
This is a mistake of target web page.I don't think scrapy could add some methods to detect encoding by checking web content's encoding.For example,if a web page is composed of some strings of  defferent encodings,so which is the right encoding ?

**Comment by wRAR** [comment]
We already try to detect the encoding of the page.

**Comment by kmike** [comment]
Hey @simapple! Scrapy aims to have a behavior which is similar to web browsers.

> For example,if a web page is composed of some strings of defferent encodings,so which is the right encoding ?

Real-world browser behavior is documented in various WHATWG standards, so they have an answer for this. This BOM issue is not a random hack which only Scrapy would have, it's something which all browsers do, and something which is described in the standard.

**Comment by simapple** [comment]
Sorry,I was not very clear about WHATWG standard.Following the standard is always right.
