### ISSUE TITLE
Clarify the return type of callbacks

### ISSUE THREAD

**Issue by wRAR** [scrapy/scrapy#5602]
https://docs.scrapy.org/en/latest/topics/spiders.html#scrapy.Spider.parse says "This method, as well as any other Request callback, must return an iterable of Request and/or item objects.", but it can also return a single Request/an item object. It's possible there are other places with a similar omission.

**Comment by DerMoehre** [comment]
Hi,
I would love to contribute to this project, but as I am just learning Python, I dont really know where to start :)
Could someone give me a bit of guidance?

**Comment by Gallaecio** [comment]
This specific issue is kind of taken, close to be merged.

If you find a ticket you are willing to work on, feel free to ask specific questions about it. However, I must say Scrapy may not be the best project to get started _contributing_ as you learn Python: the code base is complex (async programming can be complex on its own, and Scrapy uses Twisted which is not the easiest solution to learn on that front), and our “good first issue” tickets are taken rather quickly, so there are rarely any not being already worked on.
