### ISSUE TITLE
A confusion about the specific corresponding relationship between pipelines & items

### ISSUE THREAD

**Issue by hokaso** [scrapy/scrapy#5603]
## Summary

Is there a way to specify the specific pipeline of the Yield object (yield item)?

## Motivation

```
def parse(self, response):

        # crawling website list page, each list has several records (1 - N)
        item = Base()
        '''
        Some code that detects basic information
        '''
        yield item

        while True:

            if xxx:
                # Jump condition

            self.detail_parse(item.xxx)

    def detail_parse(self):
        item = Detail()
        '''
        Some code that detects detail information
        '''
        yield item_detail
```

In this case, if multiple pipelines are defined, Item and item_detail need to flow through these pipelines. Is there any way to register separately and specify different pipelines separately?

## Describe alternatives you've considered

If there is no way to divide the pipelines processing method at the operational level, and every data needs to flow through all the pipelines, then it is very inefficient to determine how the data is processed at the pipeline layer.

I don't know if this description is clear, if so, please reply to me.

**Comment by wRAR** [comment]
This is the issue tracker for Scrapy, please ask questions about your code on suitable platforms.

**Comment by hokaso** [comment]
> This is the issue tracker for Scrapy, please ask questions about your code on suitable platforms.

I don't think this is deviated with your subject. Isn't pipeline part of your framework?

**Comment by hokaso** [comment]
> This is the issue tracker for Scrapy, please ask questions about your code on suitable platforms.

I used to be a very euphemistic description, but you seem to be my humility as my unknown to your framework. In a straightforward, you have no such settings in the framework, so I strongly recommend you to add it.

**Comment by hokaso** [comment]
> This is the issue tracker for Scrapy, please ask questions about your code on suitable platforms.

I just use the code to give an example. Please don't see the code and feel that it has nothing to do with your framework.

**Comment by wRAR** [comment]
> I don't think this is deviated with your subject. Isn't pipeline part of your framework?

My point wasn't "this is not about Scrapy". My point was "this is not a bug report".

> In a straightforward, you have no such settings in the framework, so I strongly recommend you to add it.

Assuming you mean a setting for separate pipelines for separate item types, the current way to do this is checking the item type in the pipeline and I don't see a good way the proposed settings would look like to be worth adding.

**Comment by hokaso** [comment]
> > I don't think this is deviated with your subject. Isn't pipeline part of your framework?
> 
> My point wasn't "this is not about Scrapy". My point was "this is not a bug report".
> 
> > In a straightforward, you have no such settings in the framework, so I strongly recommend you to add it.
> 
> Assuming you mean a setting for separate pipelines for separate item types, the current way to do this is checking the item type in the pipeline and I don't see a good way the proposed settings would look like to be worth adding.

![image](https://user-images.githubusercontent.com/26475781/185414335-20c6defc-f6c5-4ec5-abd5-6b2fa76dee1f.png)
But you did provide the entrance of "Feature Request". I saw this option before I came to make suggestions.

By the way, checking the item type in the pipeline is a way to solve, but not the best, efficiency way.

**Comment by wRAR** [comment]
> But you did provide the entrance of "Feature Request". I saw this option before I came to make suggestions.

You asked a question though, not made a suggestion.

> By the way, checking the item type in the pipeline is a way to solve, but not the best, efficiency way.

Please describe an implementation of a better way. Preferably with the format of settings that it should use.
