### ISSUE TITLE
Proxy authentication failed

### ISSUE THREAD

**Issue by TRHX** [scrapy/scrapy#5606]
### Description

The proxy I use requires account and password verification. When I set the account and password using the proxy authorization field and send a request, the proxy service will prompt me that the verification failed. This phenomenon only occurs on the latest version 2.6.2, and it is normal if it is less than 2.6.2.

### Versions

Scrapy-2.6.2

### Additional context

`middlewares.py`：
```python
from scrapy import signals
from w3lib.http import basic_auth_header


class SpiderTestDownloaderMiddleware:
    def process_request(self, request, spider):
        request.meta['proxy'] = "http://tps137.kdlapi.com:15818"
        request.headers['Proxy-Authorization'] = basic_auth_header('my_username', 'my_password')
        request.headers["Connection"] = "close"
        return None
```

`spiders/icanhazip.py`
```python
import scrapy


class BaiduSpider(scrapy.Spider):
    name = 'icanhazip'
    allowed_domains = ['icanhazip.com']
    start_urls = ['http://icanhazip.com/']

    def parse(self, response):
        print(response.text)
```

**Comment by wRAR** [comment]
Please fix your code following https://docs.scrapy.org/en/latest/news.html#scrapy-2-6-2-2022-07-25
