### ISSUE TITLE
Passing meta (dic) with scrapy runspider command

### ISSUE THREAD

**Issue by ska-ibees** [scrapy/scrapy#5610]
Looking into `scrapy runspider `command help, it seems that we can use -s option to override/pass settings as arguments. 

However, couldn't find any example of passing meta(dict) to `scrapy runspider` command.

What I have found so far is that `scrapy runspider` expects configurations in the supplied file (spider module) itself. Allowing to override settings using -s options. 

Doc says:

runspider[¶](https://docs.scrapy.org/en/latest/topics/commands.html#runspider)

```
Syntax: scrapy runspider <spider_file.py>

Requires project: no

Run a spider self-contained in a Python file, without having to create a project.

Example usage:

$ scrapy runspider myspider.py
[ ... spider starts crawling ... ]

```

But in my case, I don't want to hard code configs/settings directly within the spider_file.py.

Scrapy is being used in a project (advertools) and I am trying to add meta (dic) into a custom command which is then converted into the `scrapy runspider` command.

**Comment by Gallaecio** [comment]
`scrapy runspider` runs a spider, request metadata is requests-specific.

You can implement a spider that accepts arguments that it passes on to its requests as request metadata.

But I am not sure it would make any sense to allow setting per-spider request metadata. If something makes sense for all requests of a spider, but can only be defined through request metadata, maybe it needs to be exposed as a setting.

Maybe it would be best for the discussion at https://github.com/eliasdabbas/advertools/pull/232 to reach a conclusion before opening a ticket here. I think you may not have the whole picture of how Scrapy settings, spider arguments and request metadata differ and work.

**Comment by ska-ibees** [comment]
Thanks for your valuable response and for putting me in the right direction. 

Agreed! need to further clarify Scrapy's code and flow. 

Thanks again!
