### ISSUE TITLE
win11 can not found the scrapy.exe

### ISSUE THREAD

**Issue by arashrun** [scrapy/scrapy#5615]
![image](https://user-images.githubusercontent.com/45729183/188095327-b0a06596-adb5-48ef-bceb-4d7c61e0d4ca.png)

**Comment by Gallaecio** [comment]
Are you sure this is an issue of Scrapy, and not of your setup? If you install any other package with a command-line tool, does it work? Does it work if you use a Python virtual environment?

**Comment by sisco0** [comment]
Could you kindly ensure that your `PATH` environment variable already contains the route to the expressed executable? Elsecase, it would not work.

**Comment by arashrun** [comment]
Reinstall python and add `PATH` solve this issue
