### ISSUE TITLE
Differnet DOWNLOAD_DELAY setting for different domains in the same spider

### ISSUE THREAD

**Issue by RahulBadenkal** [scrapy/scrapy#5616]
I am scraping data from a domain say "domain1.com" and if some condition is true (based on the data scraped from a link of this domain), I want to get additional information about address from google maps api. The problem is I want the rate of scraping for domain1 to be fast (60/sec) but for the google api I want to limit it to 20/sec. I searched the docs but there was no information on how i could set diffferent settings for different domains inside the same spider.

**Comment by wRAR** [comment]
This is a subset of #802.
