### ISSUE TITLE
[Question]  Python User Permission 

### ISSUE THREAD

**Issue by vitormhenrique** [scrapy/scrapy#5619]
Hello Everyone, 

Thank you for the time and effort on this library!

I wanted to use the `scrapy` as part of a code that could get the mac address from a `ip address`

I can easily get that running with if I run scrapy as sudo on a linux (ubuntu 20.04) machine. But ideally I would want to run as another user... and give that user the permissions necessary to get the `getmacbyip`

Even if I tried to set `sudo` group to a regular user and tried to run  `getmacbyip` I still get `[Errno 1] Operation not permitted`

Is there a specific binary on linux, folder, or group that I can give access to my username and bypass using `sudo`?

**Comment by Gallaecio** [comment]
So, I searched the internet for `getmacbyip`, I found https://scapy.readthedocs.io/en/latest/routing.html, and I was surprised that I never realized we had this page in the documentation.

It took me a while to realize that this is the documentation of Scapy, not Sc*r*apy. So you are probably looking for https://github.com/secdev/scapy.

**Comment by vitormhenrique** [comment]
I'm so sorry!
My bad! 
:)
