### ISSUE TITLE
Support for Twisted 22.8.0

### ISSUE THREAD

**Issue by wRAR** [scrapy/scrapy#5621]
Twisted 22.8.0 was released recently, and it says:

> Twisted now works with Cryptography versions 37 and above, and as a result, its minimum TLS protocol version has been upgraded to TLSv1.2.

Consequently, tests on some envs, including 3.8, now fail because they install older cryptography.

**Comment by wRAR** [comment]
Also, I haven't yet checked but it may mean that Scrapy with this Twisted version will no longer work with some servers (it also needs to be checked if it's a hard restriction or the TLS version can be lowered  with settings)

**Comment by wRAR** [comment]
We've found an interesting data point regarding the "support older TLS" part: https://chromestatus.com/feature/5759116003770368 says older TLS is no longer supported in Chromium and I can confirm it using https://badssl.com/ (https://tls-v1-1.badssl.com:1011/). While we usually strive to support as many real-world servers as possible, it should be a lower priority to support servers that are already dropped from a major browser.

**Comment by Gallaecio** [comment]
Safe for Firefox. “This website might not support the TLS 1.2 protocol, which is the minimum version supported by Firefox.” Let’s burn TLS 1.1 and earlier with fire :fire: .

**Comment by wRAR** [comment]
What is left to do here?

**Comment by Gallaecio** [comment]
Nothing else I guess.
