### ISSUE TITLE
twisted.python.failure.Failure OpenSSL.SSL.Error

### ISSUE THREAD

**Issue by codingxmh** [scrapy/scrapy#5628]
### Description

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/twisted/internet/defer.py", line 62, in run
    return f(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scrapy/core/downloader/middleware.py", line 49, in process_request
    return (yield download_func(request=request, spider=spider))
twisted.web._newclient.ResponseNeverReceived: [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', '', 'bad ecpoint')]>]

### Steps to Reproduce

scrapy fetch https://spcjsac.gsxt.gov.cn/detail.html

### Versions

Scrapy       : 2.6.2
lxml         : 4.9.1.0
libxml2      : 2.9.14
cssselect    : 1.1.0
parsel       : 1.6.0
w3lib        : 2.0.1
Twisted      : 22.4.0
Python       : 3.6.8 (v3.6.8:3c6b436a57, Dec 24 2018, 02:04:31) - [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
pyOpenSSL    : 22.0.0 (OpenSSL 3.0.5 5 Jul 2022)
cryptography : 38.0.1
Platform     : Darwin-20.5.0-x86_64-i386-64bit

**Comment by wRAR** [comment]
This is a problem with the web server, not with Scrapy. It also looks similar to https://github.com/openssl/openssl/issues/18769 , and passing `--groups X25519` in this case helps with `openssl s_client` too. You may need to research how to do the same with the OpenSSL context that Scrapy uses.
