### ISSUE TITLE
Add [1-10] in start_urls like https://example.com/?id=[1-10]

### ISSUE THREAD

**Issue by arcans1998** [scrapy/scrapy#5642]
In curl, we can request an information sequentially like 

-  curl https://example.com/?id=[1-10]

This curl command performs a get request from https://example.com/?id=1 to https://example.com/?id=10

If scrapy can implement this in start_urls of spider file, then less code will be utilized by us.

**Comment by roniemartinez** [comment]
This is a feature only for CURL and not really a generic standard. But it would be a nice addition.
https://everything.curl.dev/cmdline/globbing

**Comment by elacuesta** [comment]
This could easily be accomplished with
```python
def start_requests(self):
    for i in range(10):
        yield scrapy.Request(f"https://example.com?id={i}")
```

I'm -1 on this, I don't think this addition is worth the complexity increase (however small it might be).

**Comment by arcans1998** [comment]
Not that with this feature we can do like:
curl [https://example.com/?id=[1-10]&page=[10-30]&token=(md5[aaaa-bbbb])

**Comment by vivekthedev** [comment]
can anyone guide me how can we implement this on scrapy?

**Comment by sisco0** [comment]
Regarding the comment given above (https://github.com/scrapy/scrapy/issues/5642#issuecomment-1261170232), the functionality is not intended to be implemented into the current Scrapy codebase. However, I might present another solution that might be useful for your consideration, which is using [`exrex`](https://github.com/asciimoo/exrex) package, which could be installed by using `pip install exrex`.

```python3
import exrex

def start_requests(self):
    for suburl in exrex.generate(f"my(c|C)omplex[0-9]"):
        yield scrapy.Request(f"https://example.com?id={suburl}")
```

**Comment by wRAR** [comment]
I think the exrex suggestion is a perfect solution to the stated problem.
