### ISSUE TITLE
How use tortoise-orm in pipelines

### ISSUE THREAD

**Issue by xiaobao996** [scrapy/scrapy#5644]
Hi  please , i  want use tortoise-orm save data in pipelines, tortoise-orm is asyncio, What shall I do?

**Comment by elacuesta** [comment]
This is explained at https://docs.scrapy.org/en/latest/topics/coroutines.html

**Comment by xiaobao996** [comment]
Hello  elacuesta, your answer is very helpful to me , I want run coroutine in pipeline,    I not want use  `run_async()`  run  coroutine,  `run_async()` is  in  tortoise-orm ,  how use scrapy self  loop  run this  coroutine ? 
thinks.

**Comment by Gallaecio** [comment]
Please, use the resources in https://scrapy.org/community/ to ask for help. This issue tracker is for bug reports and feature requests.
