### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by Baahcy** [scrapy/scrapy#5647]
With user-friendly links on README.md
- convert README.rst to README.md
- when a link is clicked it should direct you to the header on the readme page
- should be able to copy command instead of dragging mouse cursor

**Comment by kmike** [comment]
>    convert README.rst to README.md

Hey! I'm not sure about converting readme to Markdown, because all other Scrapy documentation uses ReStructuredText.

>    when a link is clicked it should direct you to the header on the readme page

Could you please explain it in more detail? Which link?

>    should be able to copy command instead of dragging mouse cursor

Yes, it would be nice. Do you have a suggestion on how to implement it?

**Comment by KavinduUoM20** [comment]
could you explain when should it direct to the header section? after clicking which link?

**Comment by Ayushi96** [comment]
Hello @Baahcy , could you assign this issue to me, I would like to work on it as part of Hacktoberfest.

**Comment by armujahid** [comment]
3rd part is covered in https://github.com/scrapy/scrapy/pull/5648 although it needs verification

**Comment by SlowFlash22** [comment]
Hey👋🏽, I would like to work on this, so I just have to convert it to .md format and make sure if anything's not broken.
I am contributing to a project for the first time, so I am asking for a bit of help. Thanks!

**Comment by felipeboffnunes** [comment]
@kmike given the "copy command" is already merged (#5648), and we are not changing from rst to md, can we close this issue?
We could discuss further the "direct you to the header" but I believe this one can be closed atm.
