### ISSUE TITLE
How to close item pipeline at last

### ISSUE THREAD

**Issue by roykyle8** [scrapy/scrapy#5676]
Hi, I want to track which url's are crawled by my spiders and hence I wrote a custom DOWNLOADER_MIDDLEWARE which opens a `metafile` and writes some metadata about the url being processed.

```python
class CustomDownloaderMiddleware:

    @classmethod
    def from_crawler(cls, crawler):
        o = cls()
        crawler.signals.connect(o.spider_opened, signal=signals.spider_opened)
        crawler.signals.connect(o.spider_closed, signal=signals.spider_closed)
        return o

    def spider_opened(self, spider):
        self.meta_filehandle = open(file_path, 'w)....

    def process_request(self, request, spider):
        self.meta_filehandle.write(...) # write url and metadata

    def spider_closed(self, spider):
        self.meta_filehandle.close()

```
I have a custom Item_Pipeline which stores the data to database and also need to process the `metafile` and update database at the end of the crawl. So on `close_spider` call for ITEM_PIPELINE I tried processing the metafile. However the problem is that `metafile` handle is not closed because ITEM_PIPELINE get `close_spider` signal prior to my DOWNLOADER_MIDDLEWARE.

```python
class CustomItemPipeline:

    def process_item(self, item, spider):
        # store into mysql database

    def close_spider(self, spider):
        # here I want to open the self.meta_filehandle in read mode, process it and update the database

```

Is it possible to send `close_spider` signal to DOWNLOADER_MIDDLEWARE prior to ITEM_PIPELINE?

**Comment by wRAR** [comment]
PLease ask questions about your code on platforms suitable for that, not in the issue tracker.

**Comment by ramatkrawlnet** [comment]
Thanks @wRAR. I'm new to scrapy framework. What's the correct platform for this question?

**Comment by wRAR** [comment]
See e.g. https://scrapy.org/community/
