### ISSUE TITLE
xpath1, xpath_one or xpath_first

### ISSUE THREAD

**Issue by shirk3y** [scrapy/scrapy#568]
I think about suggestion to improve scrapy Selector. I've seen this construction in many projects:
 
    result = sel.xpath('//div/text()').extract()[0]

And what about `if result:` and `else:`, or `try:` and `except`:, which should be always there?
When we don't want ItemLoaders, the most common use of selector is retrieving only single element.
Maybe there should be method `xpath1` or `xpath_one` or `xpath_first` that returns first matched element or `None`?

**Comment by Curita** [comment]
Closed by ff64584
