### ISSUE TITLE
DeprecationWarning: ANTIALIAS is deprecated

### ISSUE THREAD

**Issue by wRAR** [scrapy/scrapy#5684]
> scrapy/pipelines/images.py:163: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
>    image.thumbnail(size, self._Image.ANTIALIAS)

This is deprecated since Pillow 9.1.0, released in April. We should check if `Resampling.LANCZOS` is already available in the earliest version we support (7.1.0 as far as I can see), and use it if it's available there. If it was added later, I think we need to decide how to proceed.

**Comment by iamkaushal** [comment]
@wRAR  I just checked `Resampling.LANCZOS` is not available in the Pillow 7.1.0.

How should we proceed?

**Comment by wRAR** [comment]
@iamkaushal I see.
Probably use `Resampling.LANCZOS` if it's available, otherwise use whatever is available instead (assuming Image.LANCZOS is available on all suppported versions, I'd use it instead of Image.ANTIALIAS to make it clearer that the code does the same on all versions, as AFAICS Image.LANCZOS is the same as Image.ANTIALIAS).

**Comment by iamkaushal** [comment]
`Image.LANCZOS` is not available since version 9.1.0 @wRAR

**Comment by iamkaushal** [comment]
Yes sorry I meant it is not available without warning. If replacing with `Image.LANCZOS` is fine for now, I would like to work on this issue.

**Comment by wRAR** [comment]
> Yes sorry I meant it is not available without warning.

But I said "use Resampling.LANCZOS if it's available".

> I think we can just switch to the new name, it seems it has been available since Pillow 2.7.

It's only about Image.LANCZOS which is deprecated in favor of Image.Resampling.LANCZOS as well.

**Comment by Gallaecio** [comment]
@iamkaushal If you are up for it, the strategy here would be to do something like:

```
try:
    LANCZOS = Image.Resampling.LANCZOS
except AttributeError:
    LANCZOS = Image.LANCZOS
```

And then use `LANCZOS` in Scrapy code.

I am not `AttributeError` is the actual exception raised, mind you.

**Comment by iamkaushal** [comment]
@Gallaecio  Thank you. Yes I would like to take this up. 

 
> But I said "use Resampling.LANCZOS if it's available".

@wRAR  My bad, I got confused because `Resampling.LANCZOS` is not available in 7.1.0

I want to work on this based on the idea proposed by @Gallaecio

**Comment by wRAR** [comment]
Please also add a comment which tells in which version was `Image.Resampling.LANCZOS` added, so that we can see that we can delete the try-except block when updating the minimum reqs for Pillow.

**Comment by iamkaushal** [comment]
Sure will do it.
