### ISSUE TITLE
DeprecationWarning: typing.re is deprecated

### ISSUE THREAD

**Issue by wRAR** [scrapy/scrapy#5686]
```
tests/test_downloader_handlers.py::HttpProxyTestCase::test_download_with_proxy_https_noconnect
tests/test_downloader_handlers.py::Http11ProxyTestCase::test_download_with_proxy_https_noconnect
tests/test_downloader_handlers_http2.py::Http11ProxyTestCase::test_download_with_proxy_https_noconnect
  /opt/hostedtoolcache/Python/3.11.0-rc.2/x64/lib/python3.11/unittest/case.py:292: DeprecationWarning: typing.re is deprecated, import directly from typing instead. typing.re will be removed in Python 3.12.
    if getattr(v, '__warningregistry__', None):
```

Happens in 3.11 tests.

**Comment by iamkaushal** [comment]
I would Iike to take this issue @wRAR

**Comment by wRAR** [comment]
Sure, go ahed @iamkaushal

**Comment by Gallaecio** [comment]
It seems so, calling `assertWarnsRegex` seems to be the cause. Maybe we need to report the issue upstream.

**Comment by wRAR** [comment]
@Laerte I assumed it's from Scrapy. I've just looked at the code that produces it and I think it's a non-issue: the code accesses all modules from `sys.modules`, and `typing.re` is there because of magic in the `typing` module. So it looks like nobody actually imports it and nothing will break when the module is removed.

**Comment by Gallaecio** [comment]
Shall we silence it then, linking to your comment as the reason?

**Comment by wRAR** [comment]
I think so, yeah.

**Comment by iamkaushal** [comment]
should I fix it like this? 
```
with contextlib.suppress(DeprecationWarning):
    with self.assertWarnsRegex(ScrapyDeprecationWarning,
                            r'Using HTTPS proxies in the noconnect mode is deprecated'):
        return self.download_request(request, Spider('foo')).addCallback(_test)
```

**Comment by Gallaecio** [comment]
I believe https://github.com/scrapy/scrapy/blob/master/pytest.ini#L24-L26 is the way to go for this.

**Comment by wRAR** [comment]
Not sure if it was there last time but now I also see "typing.io is deprecated, import directly from typing instead" in the 3.11 asyncio test.

**Comment by iamkaushal** [comment]
@wRAR  I am using windows, how can I reproduce this warning?

**Comment by wRAR** [comment]
@iamkaushal I think it should be enough to run tests with Python 3.11.
