### ISSUE TITLE
robots.txt file parser should consider download delays

### ISSUE THREAD

**Issue by fkromer** [scrapy/scrapy#5687]
## Summary

When configuring `ROBOTSTXT_OBEY = True` "delay requirement" `Crawl-delay:` is not considered.

## Motivation

We want to fully comply with robots.txt requirements.

## Workaround

Review `robots.txt` and checking delay config by hand.

**Comment by Gallaecio** [comment]
Closing as a duplicate of https://github.com/scrapy/scrapy/issues/892
