### ISSUE TITLE
The xpath code I wrote cannot display data using the lxml provided with Scrapy

### ISSUE THREAD

**Issue by wang030110666** [scrapy/scrapy#5702]
### Description

An xpath syntax uses the lxml provided by Scrapy to parse data that cannot be parsed, but can be successfully parsed using lxml

### Steps to Reproduce

1. [First Step]
import scrapy
from lxml import etree

class KsSpider(scrapy.Spider):
    name = 'ks'
    allowed_domains = ['wangxiao.cn']
    start_urls = ['https://ks.wangxiao.cn/']

    def parse(self, resp, **kwargs):
        # 解析页面结构
        li_list = resp.xpath("//ul[@class='first-title']/li")
        for li in li_list:
            first_title = li.xpath("./p/span/text()").extract_first()
            a_list = li.xpath("./div/a")
            for a in a_list:
                second_title = a.xpath("./text()").extract_first()
                second_href = a.xpath("./@href").extract_first()
                second_href = resp.urljoin(second_href)
                second_href = second_href.replace("TestPaper", "exampoint")
                # print(first_title, second_title, second_href)
                # yield scrapy.Request(
                #     url=second_href,
                #     callback=self.parse_second,
                #     meta={
                #         "first_title": first_title,
                #         "second_title": second_title,
                #     }
                # )

                # 测试的时候，定死访问 “一级建造师”
                yield scrapy.Request(
                    url="https://ks.wangxiao.cn/exampoint/list?sign=jz1",
                    callback=self.parse_second,
                    meta={
                        "first_title": "工程类",
                        "second_title": "一级建造师",
                    }
                )
                return  # 让整个parse，暂停下来。

    def parse_second(self, resp, **kwargs):
        first_title = resp.meta['first_title']
        second_title = resp.meta['second_title']
        # print(first_title, second_title)
        # print(resp.url)
        a_list = resp.xpath('//div[@class="filter-item"]/a')
        for a in a_list:
            third_title = a.xpath('./text()').extract_first()
            third_href = a.xpath('./@href').extract_first()
            third_href = resp.urljoin(third_href)
            yield scrapy.Request(
                url=third_href,
                callback=self.parse_third,
                meta={
                    "first_title": first_title,
                    "second_title": second_title,
                    "third_title": third_title,
                }
            )
            break

    def parse_third(self, resp, **kwargs):
        first_title = resp.meta['first_title']
        second_title = resp.meta['second_title']
        third_title = resp.meta['third_title']
        print(first_title, second_title, third_title)
        print(resp.url)
        # HTML = etree.HTML(resp.text)
        chapter_items = resp.xpath('//div[@class="panel-content"]/ul[@class="chapter-item"]')
        for chapter in chapter_items:
            section_point_item = chapter.xpath('.//ul[@class="section-point-item"]')
            if section_point_item:
                for point_item in section_point_item:
                    points = point_item.xpath('./ancestor::ul[@class="section-item" or @class="chapter-item"]')
                    r = []
                    for point in points:
                        p_name = "".join(point.xpath('./li[1]//text()').extract_first()).strip().replace(" ", "")
                        r.append(p_name)
                    file_path = "/".join(r)
                    print(file_path)
            else:  # 如果没拿到，本身就是一个文件
                pass  # 装备直接处理chapter即可
3. [Second Step]
Cancel # HTML=etree. HTML (resp. text) comments
Delete p_name = "".join(point.xpath('./li[1]//text()').extract_first()).strip().replace(" ", "")  Inside .extract_first()

**Expected behavior:** [What you expect to happen]
1Z101000工程经济/1Z101010资金时间价值的计算及应用/1Z101011利息的计算
1Z101000工程经济/1Z101010资金时间价值的计算及应用/1Z101011利息的计算
1Z101000工程经济/1Z101010资金时间价值的计算及应用/1Z101011利息的计算
1Z101000工程经济/1Z101010资金时间价值的计算及应用/1Z101012资金等值计算及应用
1Z101000工程经济/1Z101010资金时间价值的计算及应用/1Z101012资金等值计算及应用
1Z101000工程经济/1Z101010资金时间价值的计算及应用/1Z101012资金等值计算及应用
1Z101000工程经济/1Z101010资金时间价值的计算及应用/1Z101013名义利率与有效利率的计算
1Z101000工程经济/1Z101010资金时间价值的计算及应用/1Z101013名义利率与有效利率的计算
**Actual behavior:** [What actually happens]
//
//
//
//
//
//
**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

Please paste here the output of executing `scrapy version --verbose` in the command line.
Scrapy 2.7.0
### Additional context

Any additional information, configuration, data or output from commands that might be necessary to reproduce or understand the issue. Please try not to include screenshots of code or the command line, paste the contents as text instead. You can use [GitHub Flavored Markdown](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) to make the text look better.

**Comment by Gallaecio** [comment]
Please, provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
