### ISSUE TITLE
Single source of truth for default_settings.py

### ISSUE THREAD

**Issue by fkromer** [scrapy/scrapy#5708]
### Description

There is no single source of truth for default settings. There is https://github.com/scrapy/scrapy/blob/master/scrapy/settings/default_settings.py as well as https://github.com/scrapy/scrapy/blob/master/scrapy/templates/project/module/settings.py.tmpl . The later one seems to be the proper one which is used during project scaffolding. Is that correct?

### Steps to Reproduce

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

GitHub master branch (probably all versions, at least the most recent versions affected).

**Comment by wRAR** [comment]
The single source of default settings before applying customized ones is the `scrapy.settings.default_settings` module.

`scrapy/templates/project/module/settings.py.tmpl` is, as you guessed correctly, a template for the per-project settings.py.

Please read https://docs.scrapy.org/en/latest/topics/settings.html#populating-the-settings for more information.
