### ISSUE TITLE
Request filtered which is actually no offsite request

### ISSUE THREAD

**Issue by fkromer** [scrapy/scrapy#5710]
### Description

`scrapy` skips visiting a website which is identified as offsite request [`scrapy.spidermiddlewares.offsite`](https://docs.scrapy.org/en/latest/_modules/scrapy/spidermiddlewares/offsite.html?highlight=offsite%20request) but is no:

`DEBUG: Filtered offsite request to 'www.some-website.de': <GET https://www.some-website.de/some/sub/url/>`

In the Spider class `allowed_domains = ['https://www.some-website.de']` [scrapy.spidermiddlewares.offsite.OffsiteMiddleware](https://docs.scrapy.org/en/latest/topics/spider-middleware.html#scrapy.spidermiddlewares.offsite.OffsiteMiddleware) is defined properly.

Workaround is to:

- make sure no offsite requests are queued in scraper logic
- disable the scrapy.spidermiddlewares.offsite.OffsiteMiddleware

### Steps to Reproduce

**Expected behavior:**

Should visit website which is not offsite.

**Actual behavior:**

Does not visit non-offsite websites.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

scrapy==2.6.3

**Comment by Gallaecio** [comment]
`https://www.some-website.de` is not a domain, is a URL.
