### ISSUE TITLE
how to retry a request from pipeline

### ISSUE THREAD

**Issue by julianhille** [scrapy/scrapy#5716]
I try to find a way to retry a loader item after it has been downloaded and fails checksum Check.

Is there a way to put it with retry meta data back into the queue?

**Comment by wRAR** [comment]
This is the issue tracker for Scrapy. Please ask your questions on platforms suitable for that, e.g. StackOverflow.

**Comment by wRAR** [comment]
Pipelines don't work with requests or responses so there is no correct way to implement it.

**Comment by julianhille** [comment]
Thanks for the answer.
