### ISSUE TITLE
Splash not returning the full html

### ISSUE THREAD

**Issue by eslamerman** [scrapy/scrapy#5723]
Hi everyone, 
I am trying to scrape the H&M webpage " [https://eg.hm.com/en/shop-offer/fancy-favorites-uae/kids/](https://eg.hm.com/en/shop-offer/fancy-favorites-uae/kids/?fbclid=IwAR2QTcUfLJxYOUYjhVaSjcILLrCfK5EwDmCIdMbmmNxZcw2nmhM7QxTvL8g) " using splash and scrapy. The first step I am to try the splash code below to get the HTML and PNG 
function main(splash,args)
  splash.private_mode_enabled = false
  url = args.url
  assert(splash:go(url))
  assert(splash:wait(1))
  splash:set_viewport_full()
  return {
    image = splash:png(),
    html = splash:html()
    }
end

but it is not returning the full content, it returns only the below . I cannot scrape any product. Any Idea?

![316302255_10159336871130868_8053909548979265296_n](https://user-images.githubusercontent.com/43751216/203267137-e6bd69a4-d081-4800-9dba-d0d55e1c5439.jpg)

**Comment by wRAR** [comment]
This is the issue tracker for Scrap, not for Splash (and this doesn't look like an actual Splash problem, more like something that can be improved with page actions).
