### ISSUE TITLE
asyncio exception in scrapy shell on Windows 

### ISSUE THREAD

**Issue by wRAR** [scrapy/scrapy#5740]
We got a bug report that using `fetch(<url>)` in `scrapy shell` on Windows in a new project (so with `TWISTED_REACTOR` set to the asyncio one) raises "There is no current event loop" in `deferred_from_coro()`. The Python version is 3.9 and 3.10 and the Scrapy version is 2.7.1. It is possible that the recenty changed loop code indeed doesn't work correctly on Windows but I cannot test or fix it at this time.

**Comment by wRAR** [comment]
According to the info in #5742, this seems to only affect `scrapy shell` and also doesn't prevent it from normal usage.

**Comment by wRAR** [comment]
This may be related to the fact that `scrapy shell` runs scraping in a separate thread.

**Comment by Gallaecio** [comment]
For the record, it can happen in operating systems other than Windows as well. It happened to @HackyRoot on macOS.
