### ISSUE TITLE
Document Spider.update_settings

### ISSUE THREAD

**Issue by wRAR** [scrapy/scrapy#5745]
While overriding `Spider.update_settings` is a common practice to have dynamic custom settings, it looks like it's not documented anywhere.

It should also be mentioned in https://docs.scrapy.org/en/latest/topics/settings.html#settings-per-spider

**Comment by anugcodes** [comment]
hey @wRAR ,  i would like to try this issue.But i am new here and don't know where to start.can you please help me out here.

**Comment by wRAR** [comment]
@anugcodes are you asking about contributing in general or how to fix this issue?

**Comment by anugcodes** [comment]
> @anugcodes are you asking about contributing in general or how to fix this issue?

I mean in general,how can I understand the codebase  and start with beginner friendly tasks.

**Comment by wRAR** [comment]
@anugcodes https://docs.scrapy.org/en/latest/contributing.html

**Comment by N00rAhmed** [comment]
hey @wRAR I would like to work on this issue but because I'm new to this repo I dont know where I should write the documentation for Spider.update_settings ?

**Comment by wRAR** [comment]
@N00rAhmed the attributes of `scrapy.Spider` are documented in `docs/topics/spiders.rst`.

**Comment by tuhinmallick** [comment]
Is this issue still open then I would like to work on it

**Comment by wRAR** [comment]
@tuhinmallick there is an existing not-yet-complete PR linked above but you can try too.
