### ISSUE TITLE
Fix CI for the tox 4.0 changes

### ISSUE THREAD

**Issue by wRAR** [scrapy/scrapy#5749]
Looks like tox 4 broke several tests: [`docs` fails because it now runs pytest instead of sphinx-build](https://github.com/wRAR/scrapy/actions/runs/3655201285/jobs/6176311198) and [the `*pinned` actions fail because they apparently install newer Twisted](https://github.com/wRAR/scrapy/actions/runs/3655201280/jobs/6176311274) (and maybe newer versions for other pinned packages but we don't check those).

The changes are described at https://tox.wiki/en/latest/faq.html , though I don't see any obvious reasons there. 

Also, the pylint and extra-deps actions now fail to build reppy, which is probably unrelated and may need a separate issue created.

**Comment by wRAR** [comment]
Related: basepython = python3

**Comment by Gallaecio** [comment]
https://github.com/scrapy/scrapy/issues/5785 seems to be the only pending CI issue.
