### ISSUE TITLE
Cannot install due to PyDispatcher

### ISSUE THREAD

**Issue by chadfurman** [scrapy/scrapy#5751]
### Description

```
pip install scrapy
...
Collecting PyDispatcher>=2.0.5
  Using cached PyDispatcher-2.0.6.tar.gz (38 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

### Steps to Reproduce

1. pip install scrapy

**Expected behavior:** [What you expect to happen]

pip install should succeed.  dependencies have been installed ahead of time

**Actual behavior:** [What actually happens]

Scrapy install fails due to PyDispatcher failing to build

**Reproduces how often:** [What percentage of the time does it reproduce?]

every time I try to install

### Versions

➜  wzbc-to-ytmusic python --version
Python 3.8.12
➜  wzbc-to-ytmusic pip --version
pip 22.3.1 from /home/lotus/.pyenv/versions/3.8.12/lib/python3.8/site-packages/pip (python 3.8)

Scrapy: latest in PyPi

Please paste here the output of executing `scrapy version --verbose` in the command line.

### Additional context

Tried installing older version of PyDispatcher, no luck.  Currently running in Fedora Linux.

**Comment by chadfurman** [comment]
Note I tried cloning down PyDispatcher and I could build it locally with `python setup.py install` -- however, this does not allow scrapy to install.

Making sure I use the `pip` in the venv to both build PyDispatcher locally and to install scrapy, I run into a `libffi` error which I then resolve by installing `sudo dnf install libffi3.1` transition package.  

Finally I'm presented with:

```
...
Using legacy 'setup.py install' for PyDispatcher, since package 'wheel' is not installed.
Installing collected packages: urllib3, pycparser, idna, charset-normalizer, certifi, w3lib, six, requests, pyasn1, packaging, lxml, cssselect, cffi, attrs, zope.interface, typing-extensions, requests-file, pyasn1-modules, parsel, jmespath, itemadapter, incremental, hyperlink, filelock, cryptography, constantly, Automat, Twisted, tldextract, service-identity, queuelib, pyOpenSSL, PyDispatcher, protego, itemloaders, scrapy
  Attempting uninstall: PyDispatcher
    Found existing installation: PyDispatcher 0.0.0
ERROR: Cannot uninstall 'PyDispatcher'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
WARNING: You are using pip version 21.1.1; however, version 22.3.1 is available.
You should consider upgrading via the '/home/lotus/projects/wzbc-to-ytmusic/bin/python -m pip install --upgrade pip' command.
```

**Comment by chadfurman** [comment]
After using `pip show pydispatcher` and purging all installed old versions, then hacking the `setup.py` file in the PyDispatcher local repo I cloned down to use setuptools instead of distutils, and hacking in a version of "2.0.7", then building a wheel and using the venv python to install the wheel, I was able to install scrapy!!!!

**Comment by wRAR** [comment]
I cannot reproduce this, PyDispatcher 2.0.6 installs fine in my fresh Python 3.8 env.

(in any case, if you cannot install it it's not a bug in Scrapy)
