### ISSUE TITLE
Crawl the href from the "link" tag inside the head tag

### ISSUE THREAD

**Issue by arcans1998** [scrapy/scrapy#5770]
## Summary

When using Rules, Scrapy CrawlSpider does crawl href from "a" tag from the body. However, the "href" attribute is in the head like 
`<link rel="next" href="/link/to/page?pag=3">`

## Motivation

If href is extracted aside from inside the body tag, then that would be great.

## Describe alternatives you've considered
Add support for extracting href from head section
## Additional context

Add support for extracting href from head section

**Comment by wRAR** [comment]
Link extractors already support using tags other than `a`.
