### ISSUE TITLE
what's mean about: [scrapy.core.engine] DEBUG: Crawled (477)

### ISSUE THREAD

**Issue by ChenKe404** [scrapy/scrapy#5773]
version 2.7.1
python 3.10.8
log: [scrapy.core.engine] DEBUG: Crawled (477) <GET http://www.iciba.com/word?w=hello> (referer: None)
i dont konw anything  about 477 status code

**Comment by Gallaecio** [comment]
This is not an issue with Scrapy itself. Feel free to ask the website owners why they send an HTTP 477 response when you use Scrapy to access their website.

For the record, just changing the user agent (e.g. `USER_AGENT="curl/7.54.1"` in `settings.py`) gets me an HTTP 200 response.
