### ISSUE TITLE
Deprecate direct invocation of `setup.py` 

### ISSUE THREAD

**Issue by Urahara** [scrapy/scrapy#5774]
I was reading this article: [Why you shouldn't invoke setup.py directly](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html) that explains why this is not a good practice anymore. I thought about discussing this. Should we change to new approach?

We have only a few places that we directly invoke `setup.py` so should be an easy task to replace it.

https://github.com/scrapy/scrapy/search?q=setup.py

**Comment by wRAR** [comment]
So it looks like the only uses are `setup.py sdist` in `tox -e twinecheck` and `setup.py sdist bdist_wheel` in the publish CI action.
