### ISSUE TITLE
Redirected to the 'Are you a Human" page. 

### ISSUE THREAD

**Issue by FahimMIST** [scrapy/scrapy#5775]
I am trying to crawl the walmart.ca site. But it's always redirecting to the are you human page. But at the same time, walmart.com is scrappable. Is there any suggestions or has anyone face this issue?

**Comment by mtabbasi** [comment]
Ask your question in the [Scrapy discord server](https://discord.gg/mv3yErfpvq).
This is not a good place to ask such questions.
