### ISSUE TITLE
Spider in Django views

### ISSUE THREAD

**Issue by mohsnMohsni** [scrapy/scrapy#5779]
hi, I want to use scrapy spider in Django views and I tried using CrawlRunner and CrawlProcess but there are problems, views are synced and further crawler does not return a response directly 

I tried a few ways:

```
# Core imports.
from scrapy.crawler import CrawlerProcess
from scrapy.utils.project import get_project_settings

# Third-party imports.
from rest_framework.views import APIView
from rest_framework.response import Response

# Local imports.
from lrn_scrap.spiders.google import GoogleSpider


class ForFunAPIView(APIView):
    def get(self, *args, **kwargs):
        process = CrawlerProcess(get_project_settings())
        process.crawl(GoogleSpider)
        process.start()
        return Response('ok')

```

is there any solution to handle that and run spider directly in other scripts or projects without using DjangoItem pipeline?

**Comment by wRAR** [comment]
This is the Scrapy issue trracker. Please ask your questions on suitable platforms like StackOverflow.
