### ISSUE TITLE
Scrapy CSS Selectors not extracting all content inside

### ISSUE THREAD

**Issue by iamumairayub** [scrapy/scrapy#5788]
Using Scrapy 2.5.1, I want to extract main article content from https://www.upi.com/Top_News/World-News/2023/01/01/N-Koerean-leader-calls-exponential-increase-nuclear-arsenal/4171672578401/

I verfied that my response.text contains all HTML same as I can view in my browser

But when I want to to extract main article content from [itemprop='articleBody'] that includes only paragraphs

```
response.css("[itemprop='articleBody'] *::text").extract()

['\n\n',
 'SEOUL, Jan. 1 (UPI) --',
 ' North Korean leader Kim Jong-un stressed the need to "exponentially" increase the number of the country\'s nuclear arsenal and develop a new intercontinental ballistic missile in the new year, Pyongyang\'s state media reported Sunday.',
 '\n',
 "He delivered the message during a plenary meeting of the ruling Workers' Party of Korea that ended the previous day. It was held to set Pyongyang's major policy directions for the new year.\n",
 'Advertisement'] 
```

I tried several CSS Selector combinations but no use.

If it was Selenium, I would have simply used `driver.find_element_by_css_selector("[itemprop='articleBody']").text` and it would have extracted all content

**Comment by Gallaecio** [comment]
This does not look like a bug in Scrapy (or parsel or cssselect). You seem to not be familiar with the differences between raw HTML and DOM-based HTML, and need help finding the right CSS expression to select from raw HTML the same content you can select from DOM-based HTML.

Please, see https://scrapy.org/community/ for avenues to direct your request for help.

**Comment by iamumairayub** [comment]
Could anybody here tell me an appropriate CSS Selector to select main article content from above page?
