### ISSUE TITLE
ItemLoader instantiated from a base item does not create a new item instead keeps reference to same item

### ISSUE THREAD

**Issue by theumairahmed** [scrapy/scrapy#5796]
### Description

In Scrapy 2.6, an ItemLoader instantiated with a base item keeps a reference to a single same item and instead of loading new items, it repeats the values added, therefore, producing duplicate items. 

### Steps to Reproduce

Run the following script:
```
from scrapy.loader import ItemLoader

base_item = {}
for i in range(5):
    il = ItemLoader(item=base_item)
    il.add_value('b', i)
    new_item = il.load_item()
    print(new_item)
```
Output when ran in `scrapinghub-stack-scrapy:2.6`:
```
{'b': [0]}
{'b': [0, 1]}
{'b': [0, 1, 2]}
{'b': [0, 1, 2, 3]}
{'b': [0, 1, 2, 3, 4]}
```
Output when ran in `scrapinghub-stack-scrapy:1.6`:
```
{'b': [0]}
{'b': [1]}
{'b': [2]}
{'b': [3]}
{'b': [4]}
```

**Expected behavior:** The output should be the same as when ran in older Scrapy stack: `scrapinghub-stack-scrapy:1.6`

**Possible resolution:** Deep copying the `base_item` works as intended:
```
from scrapy.loader import ItemLoader
from copy import deepcopy

base_item = {}
for i in range(5):
    il = ItemLoader(item=deepcopy(base_item))
    il.add_value('b', i)
    new_item = il.load_item()
    print(new_item)
```

Output:
```
{'b': [0]}
{'b': [1]}
{'b': [2]}
{'b': [3]}
{'b': [4]}
```

**Comment by wRAR** [comment]
It's a feature added in 1.8.0.

**Comment by theumairahmed** [comment]
Hi @wRAR, a lot of the older written spiders assume that a new item will be created. After the recent stack upgrade, we started observing that the new behavior produces duplicate items.

Is deep copying the base item a good solution for making the new ItemLoader behavior the same as the old one?

**Comment by Gallaecio** [comment]
> Is deep copying the base item a good solution for making the new ItemLoader behavior the same as the old one?

It can be, although a shallow copy may be fine in many scenarios.
