### ISSUE TITLE
No module named 'attrs' error in Scrapy

### ISSUE THREAD

**Issue by Shikharishere** [scrapy/scrapy#5844]
**Description** : 
 have been trying to use Scrapy for one of my projects. But this error just keeps coming. I have tried everything from Stackoverflow to reinstalling Scrapy mutilple times. But it seems like this error is in Scrapy. Thus I am posting this issue here!!!
Here's  the Image -> 
![image](https://user-images.githubusercontent.com/71226935/223662812-8860d1a9-03bc-4809-a714-30bdc804009c.png)
**Note** : 
Maybe I'm wrong and this issue is only in my PC. If that's the thing then please help me out!!!! 
Thanks!

**Comment by wRAR** [comment]
It's your local problem unrelated to Scrapy (it's related to Twisted, if any, as attrs is a dep of Twisted, not of Scrapy).

> I have tried everything from Stackoverflow to reinstalling Scrapy mutilple times. 

The only obvious solution would be actually installing `attrs`, though you shouldn't be able to install Twisted without it so maybe something more fundamental is broken.
