### ISSUE TITLE
FormRequest changed my request data, resulting in an incorrect response

### ISSUE THREAD

**Issue by loongst** [scrapy/scrapy#5853]
### Description

[In the dictionary of my post request, the type of value is int, but in the actual request sent, value becomes str, so an incorrect response is given. Is there any way to send an int type value?]

### Steps to Reproduce

1. [use FormRequest]
![image](https://user-images.githubusercontent.com/19646984/226301236-6360ee3c-45e1-491e-a80c-09d13835b4cc.png)

**Expected behavior:** [**The request I want is this, how do I handle it?**]
![image](https://user-images.githubusercontent.com/19646984/226301767-0397da6a-71d0-427e-b44b-ebd1ccdd2a77.png)

**Actual behavior:** [What actually happens]
![image](https://user-images.githubusercontent.com/19646984/226301355-0b7630b8-d0b8-4116-9bce-31896bba8d08.png)

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

Please paste here the output of executing `scrapy version --verbose` in the command line.

Scrapy 2.8.0+python3.10

### Additional context

Any additional information, configuration, data or output from commands that might be necessary to reproduce or understand the issue. Please try not to include screenshots of code or the command line, paste the contents as text instead. You can use [GitHub Flavored Markdown](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) to make the text look better.

**Comment by wRAR** [comment]
Please ask questions about problems in your code on suitable platforms such as StackOverflow.

> In the dictionary of my post request, the type of value is int, but in the actual request sent, value becomes str

(that's not what is happening, what is happening is you are not sending JSON when you want to send JSON)
