### ISSUE TITLE
test_batch_path_differ sometimes fails

### ISSUE THREAD

**Issue by Gallaecio** [scrapy/scrapy#5855]
See https://github.com/scrapy/scrapy/pull/5847#issuecomment-1471778039.

**Comment by tstauder** [comment]
@jmannoop and I would like to work on this. Is it possible for it to be assigned to us?

**Comment by tstauder** [comment]
I think we have the fix ready to go and tested, but could use some guidance on creating a pull request. I can probably figure out how to make one but if there's anything else we need to know / tips would be greatly appreciated.
