### ISSUE TITLE
TLS logging broken with new cryptography

### ISSUE THREAD

**Issue by wRAR** [scrapy/scrapy#5857]
https://github.com/pyca/cryptography/pull/8391 dropped `SSL_get_server_tmp_key()` so we need to disable the code that uses it if it's not available.

**Comment by dvzrv** [comment]
Hi! I have just run into this problem trying to build this project for Arch Linux for our Python 3.11 rebuild.

Please create a bugfix release for these types of fixes.
Generally, it should also be evaluated how not to use internal pyopenssl functionality if possible. Calling deep into a cryptography hazmat module via [an internal pyopenssl module](https://github.com/scrapy/scrapy/blob/c2a31974ffc06412a5ab8d87fe070c98cd9c856b/scrapy/utils/ssl.py#L1) is hard to debug for downstreams :cry:
