### ISSUE TITLE
Change the scrapy short description

### ISSUE THREAD

**Issue by darkrho** [scrapy/scrapy#586]
The Scrapy short description says:

> Scrapy, a fast high-level screen scraping and web crawling framework.

I think would be better:

> Scrapy, a fast high-level web crawling and screen scraping framework.

Because it highlights first its difference with simple screen scraping tools (i.e. Nokogiri. Mechanize, etc).

Screen scraping can be done even with curl and grep, but I don't think you could do web crawling with such simple tools.

Perhaps this can be an alternative:

> Scrapy, a fast and scalable web crawling and screen scraping framework.

Also the term "web data mining" can be a good fit for Scrapy (along with Scrapely and similar tools) and help to shape its roadmap.

**Comment by kmike** [comment]
I was discussing doc changes with @eliasdorneles, and it became clear "screen scraping" is confusing. Wikipedia [article](http://en.wikipedia.org/wiki/Data_scraping#Screen_scraping) thinks it is something related to OCR, and the term is not generally well-known. I haven't heard it until I started to work with Scrapy :) 

What about using "data extraction" instead?
Thoughts?

**Comment by shaneaevans** [comment]
Web Scraping is a better term than Screen Scraping for what Scrapy does. However, I think with "web crawling and data extraction" we also have it covered.

**Comment by kmike** [comment]
@pablohoffman made a good point that if we move scrapy.selectors to a separate library (https://github.com/scrapy/scrapy/pull/1007) scrapy itself won't be focused on data extraction. So +1 to Web Scraping.
