### ISSUE TITLE
get_func_args does not fully work in CPython

### ISSUE THREAD

**Issue by jelgun** [scrapy/scrapy#5872]
As [shown in tests](https://github.com/scrapy/scrapy/blob/ada917307844950a81226f020b596d5932187f6e/tests/test_utils_python.py#L240-L243), `get_func_args` does not work in CPython with inputs like `str.split`, `"".join` or `itemgetter(2)`.

**Comment by wRAR** [comment]
If/when somebody works on this, please check if `get_func_args` can just be replaced by `inspect.signature` (which "Accepts a wide range of Python callables, from plain functions and classes to functools.partial() objects." but wasn't available when `get_func_args` was written).
