### ISSUE TITLE
Comment smells in `scrapy`

### ISSUE THREAD

**Issue by jelgun** [scrapy/scrapy#5873]
Dear developers,

We are conducting research on inline code comment smells, i.e., low-quality comments that can
have a detrimental effect on software quality or be ineffective for code understanding. We've categorized such smells in [one of our studies](https://www.researchgate.net/publication/354035414_Towards_a_Taxonomy_of_Inline_Code_Comment_Smells) into 11 categories which you can find below ![Screenshot from 2023-03-09 08-49-45](https://user-images.githubusercontent.com/5639662/227046724-ea36e65f-35d0-4972-bb44-915a81267560.png)  In continuation of that study, we are analyzing open-source projects and would like to get developers' opinions on inline comment smells in their projects. We have found the following comment smells in `scrapy` and created pull requests to fix them. Can you please review them?

1 - [remove obvious comment in agent.py](https://github.com/scrapy/scrapy/pull/5860)
2 - [remove obvious comment in test_http_request.py](https://github.com/scrapy/scrapy/pull/5861)
3 - [remove obvious comment in form.py](https://github.com/scrapy/scrapy/pull/5862)
4 - [remove obvious comment in httperror.py](https://github.com/scrapy/scrapy/pull/5863)
5 - [remove obvious comment in agent.py](https://github.com/scrapy/scrapy/pull/5864)
6 - [remove obvious comment in linkfix.py](https://github.com/scrapy/scrapy/pull/5865)
7 - [remove obvious comment in test_feedexport.py](https://github.com/scrapy/scrapy/pull/5866)
8 - [remove task comment in test_utils_python.py](https://github.com/scrapy/scrapy/pull/5867)
9 - [remove beautification comment in test_spidermiddleware_referer.py](https://github.com/scrapy/scrapy/pull/5868)
10 - [remove misleading comment in test_utils_python.py](https://github.com/scrapy/scrapy/pull/5869)
11 - [remove vague comment in engine.py](https://github.com/scrapy/scrapy/pull/5870)
12 - [shorten long comment in test_http_request.py](https://github.com/scrapy/scrapy/pull/5871)

Thanks in advance for your collaboration,
Elgun Jabrayilzade, Ayda Yurtoğlu, Eray Tüzün

**Comment by wRAR** [comment]
> Can you please review them?

Done. Most of these are really bad, others are simply bad. Some are actively harmful. I'm not going to provide detailed reviews.

It's also clear that this was generated by either an (incomplete) tool or a person who didn't look at the code before making and proposing changes to it. In either case, please refrain from such contributions in the future. If, on the other hand, all you wanted was a review please don't use the PR mechanism for this.
