### ISSUE TITLE
Scrapy docs: 'make htmlview' does not work

### ISSUE THREAD

**Issue by jxlil** [scrapy/scrapy#5878]
### Description

`Path.resolve()` returns the `PosixPath` _class_ so it is not possible to concatenate it with a string.

```
webbrowser.open('file://' + Path('build/html/index.html').resolve())
```

### Steps to Reproduce

```
cd docs/
make html
make htmlview
```

**Expected behavior:** 

`webbrowser` should open the file `build/html/index.html`

**Actual behavior:**

Get the following error when trying to open the file:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: can only concatenate str (not "PosixPath") to str
```

### Versions

`2.8.0`

### Possible solution

Instead of trying to concatenate the string `file://` we could use [`as_uri()`](https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.as_uri). For example:

```
htmlview: html
	 $(PYTHON) -c "import webbrowser; from pathlib import Path; \
	 webbrowser.open(Path('build/html/index.html').resolve().as_uri())"
```

**Comment by xt1033** [comment]
Hello @jxlil , I'm interested in working on this issue. Could you please assign it to me?
