### ISSUE TITLE
scrapy doesn't see project settings while debugging spiders in vscode

### ISSUE THREAD

**Issue by Kerus** [scrapy/scrapy#5886]
Hi!
hit such problem that while debugging spiders in vscode (launch.json from https://doc.scrapy.org/en/latest/topics/debug.html) scrapy doesn't see project settings and use global ones instead. With standard running "scrapy crawl" everything is fine.

**Comment by wRAR** [comment]
Is the work directory set correctly, assuming you can do that in VS Code? Note that I have no idea about `launch.json` but I don't see work directory settings in the snipper we provide.
