### ISSUE TITLE
Integrating sqlalchemy into scrapy

### ISSUE THREAD

**Issue by keatonLiu** [scrapy/scrapy#5887]
## Summary

Consider integrating sqlalchemy into scrapy, such as allowing the Item class to support Object Relational Mapper

## Motivation
If you want to use a structured database, you need to write sql statements by hand, manually create database tables, etc., which is very troublesome.

## Describe alternatives you've considered

You can further refer to the structure of django, add the migration function of the database

**Comment by wRAR** [comment]
Assuming ItemAdapter doesn't work with your SqlAlchemy items, feel free to add support for them there.
