### ISSUE TITLE
Enable latest stable branch on ReadTheDocs

### ISSUE THREAD

**Issue by dangra** [scrapy/scrapy#589]
Docs for 0.24 branch exposed at http://doc.scrapy.org/en/0.24/ are outdated compared to http://doc.scrapy.org/en/latest/ ("latest" is set to 0.24).

Reenable once rtfd/readthedocs.org#635 is fixed.

**Comment by redapple** [comment]
https://github.com/rtfd/readthedocs.org/issues/635 is fixed.
I don't understand the issue, maybe because docs are fine now.
@dangra ?

**Comment by dangra** [comment]
The issue (I didn't confirm yet if holds true) is that http://doc.scrapy.org/en/1.0/ and http://doc.scrapy.org/en/latest/ have different content.

**Comment by redapple** [comment]
@dangra , ok, they look the same to me

**Comment by Digenis** [comment]
Right now in readthedocs, stable is 1.1, latest is 1.0 and master 1.2.
Is this normal?

**Comment by redapple** [comment]
Right @Digenis , something is wrong

**Comment by eliasdorneles** [comment]
I think that's expected -- once final 1.1 is released, then latest will point to it.

**Comment by kmike** [comment]
it is confusing that 1.1 is stable - 1.0 should be stable until 1.1 release.

**Comment by Digenis** [comment]
Until 1.1? But will 1.1 (odd) be considered stable?

**Comment by kmike** [comment]
@Digenis I think we're going to stop using `odd/even => unstable/stable` versioning scheme; 1.0 or 1.1 are new 'even' and 1.1dev or 1.2dev is a new 'odd'.

**Comment by kmike** [comment]
But that's a good catch @Digenis - http://doc.scrapy.org/en/latest/versioning.html mentions odd numbered versions as development.

**Comment by kmike** [comment]
https://github.com/scrapy/scrapy/pull/1541 didn't fix https://github.com/scrapy/scrapy/issues/1317 completely

**Comment by Gallaecio** [comment]
I believe the original issue is fixed already. When you access the documentation either as `1.6` or as `latest` you do not get the warning about the documentation being outdated, and you still get it with `1.5`, as expected.
