### ISSUE TITLE
Add support for the Parsel JMESPath feature

### ISSUE THREAD

**Issue by wRAR** [scrapy/scrapy#5894]
See https://github.com/scrapy/parsel/pull/181 and https://github.com/Gallaecio/scrapy/commit/d642881e25b6a7ce7d8f640b354459b9a4921790 linked there.

Note that the minimum version of Parsel that Scrapy requires should stay the same, i.e. no need to update the minimum version of Parsel in setup.py.

**Comment by nitin-pandita** [comment]
I am up for it @wRAR  can you assign me this issue

**Comment by wRAR** [comment]
@nitin-pandita as you can see there is already a draft PR for this issue.

**Comment by nitin-pandita** [comment]
Oh yeah, I didn't notice. Thank you for the reply
