### ISSUE TITLE
Different Response while using requests.request and scrapy.Request with same header and payload

### ISSUE THREAD

**Issue by Binit-Dhakal** [scrapy/scrapy#5910]
### Description
I have been trying to send requests to the API to collect some public records. I tried using scrapy.Requests and had no luck with scrapy with countless hours of debugging but it works perfectly with requests. The error message in the JSON response says "Invalid Security Key" where I am sending the security key through headers. I have sent the same security key and all the other fields same with both scrapy and requests headers.

### Steps to Reproduce

1. Using requests:
 ```
  import requests
  import json
  
  url = "https://uitax.dew.sc.gov/CoreServices/Lien/TaxLienRegistry.svc/SearchTaxLienRegistry"
  
  payload = json.dumps({
      "BusinessName": "",
      "EmployerFEIN": "",
      "EmployerAccountId": "",
      "FirstName": "",
      "LastName": "",
      "IssuedFrom": "2023-03-03",
      "IssuedTo": "2023-03-04",
      "LienID": "",
      "LienStatisfied": "",
      "LienActive": "",
      "SearchByIndividual": "N",
      "SearchByTopDebts": "N",
      "SSN": None,
      "IPAddress": "0"
  })
  
  headers = {
        'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/112.0',
        'Accept': 'application/json, text/plain, */*',
        'Accept-Language': 'en-US,en;q=0.5',
        'Accept-Encoding': 'gzip, deflate, br',
        'Content-Type': 'application/json',
        'SecurityKey': 'LbBr3hPJ2qw9mHvmE+Px7gI8HiDaU+F3fWx68Z39YBw=',
        'Origin': 'https://uitax.dew.sc.gov',
        'Connection': 'keep-alive',
        'Referer': 'https://uitax.dew.sc.gov/LienRegistry/',
        'Sec-Fetch-Dest': 'empty',
        'Sec-Fetch-Mode': 'cors',
        'Sec-Fetch-Site': 'same-origin'
  }
  
  resp = requests.request("POST", url, headers=headers, data=payload)
print(resp.json())  # works perfectly
```
2. Using Scrapy(I am showing here using scrapy shell)
```
# I used same headers, payload and url as above(requests) one
fetch(url, method="POST", headers=headers, body=payload)  # return 200 but with error "Invalid Security Token"
```

**Expected behavior:** 
If requests.request is working, then scrapy.Request should also have worked and have given same response.

**Actual behavior:**
requests.request works but scrapy.Request doesn't. Also scrapy.Request is getting response regarding complain about the "Invalid securitykey" but requests is getting no such complaints. I even sent a request to https://httpbin.org/headers to check the request headers for both scrapy and requests and got same headers. 
**Scrapy response:**
 ```
{'headers': {'Accept': 'application/json, text/plain, */*',
  'Accept-Encoding': 'gzip, deflate, br',
  'Accept-Language': 'en-US,en;q=0.5',
  'Content-Length': '289',
  'Content-Type': 'application/json',
  'Host': 'httpbin.org',
  'Origin': 'https://uitax.dew.sc.gov',
  'Referer': 'https://uitax.dew.sc.gov/LienRegistry/',
  'Sec-Fetch-Dest': 'empty',
  'Sec-Fetch-Mode': 'cors',
  'Sec-Fetch-Site': 'same-origin',
  'Securitykey': 'LbBr3hPJ2qw9HvmE+Px7gI8HiDaU+F3fWx68Z39YBw=',
  'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/112.0',
  'X-Amzn-Trace-Id': 'Root=1-6444e1e8-6041faf32f21a2186baf1ed6'}}

```
**Requests response**
```
{'headers': {'Accept': 'application/json, text/plain, */*',
  'Accept-Encoding': 'gzip, deflate, br',
  'Accept-Language': 'en-US,en;q=0.5',
  'Content-Length': '289',
  'Content-Type': 'application/json',
  'Host': 'httpbin.org',
  'Origin': 'https://uitax.dew.sc.gov/',
  'Referer': 'https://uitax.dew.sc.gov/LienRegistry/',
  'Sec-Fetch-Dest': 'empty',
  'Sec-Fetch-Mode': 'cors',
  'Sec-Fetch-Site': 'same-origin',
  'Securitykey': 'LbBr3hPJ2qw9HvmE+Px7gI8HiDaU+F3fWx68Z39YBw=',
  'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/112.0',
  'X-Amzn-Trace-Id': 'Root=1-6444e1a4-7ee0ef59523304864f62fd65'}}
```
### Versions
```
Scrapy       : 2.7.1
lxml         : 4.9.2.0
libxml2      : 2.9.14
cssselect    : 1.2.0
parsel       : 1.7.0
w3lib        : 2.1.1
Twisted      : 22.10.0
Python       : 3.8.10 (default, Mar 13 2023, 10:26:41) - [GCC 9.4.0]
pyOpenSSL    : 23.0.0 (OpenSSL 3.0.7 1 Nov 2022)
cryptography : 39.0.0
Platform     : Linux-5.15.0-69-generic-x86_64-with-glibc2.29
```
### Additional context
Output from scrapy:
```
[{'BalanceAmount': 0,
  'Cost_FeesAmount': 0,
  'DBAName': None,
  'EmployerAccountId': 0,
  'EmployerAddress': None,
  'EmployerFEIN': None,
  'ErrorMessage': 'Invalid Security Key',
  'InterestAmount': 0,
  'LeinAmount': 0,
  'LienDateFiled': None,
  'LienDateStatisfied': None,
  'LienDocument': None,
  'LienID': 0,
  'LienIssued': None,
  'LienLastUpdated': None,
  'LienPartialRelease': None,
  'LienPayoffAmt': 0,
  'LienStatus': None,
  'LienType': None,
  'LiendPeriods': None,
  'NoticeId': 0,
  'Payoff': None,
  'PenaltyAmount': 0,
  'StatusDescription': None,
  'TaxAmount': 0,
  'TaxpayerName': None}]
```

Output from requests:
```
[{'BalanceAmount': 358.8,
  'Cost_FeesAmount': 0.0,
  'DBAName': 'PRIMARY',
  'EmployerAccountId': 240666,
  'EmployerAddress': 'CARBON METALIC HIGHWAY, PO BOX 819, CLOVER, SC29710-0819',
  'EmployerFEIN': '0774',
  'ErrorMessage': None,
  'InterestAmount': 338.8,
  'LeinAmount': 408.62,
  'LienDateFiled': '3/3/2023 12:00:00 AM',
  'LienDateStatisfied': '',
  'LienDocument': None,
  'LienID': 979369,
  'LienIssued': 'York',
  'LienLastUpdated': '3/3/2023 12:00:00 AM',
  'LienPartialRelease': '',
  'LienPayoffAmt': 0,
  'LienStatus': 'ACTV',
  'LienType': 'Tax',
  'LiendPeriods': ' Q2-2022, Q3-2022',
  'NoticeId': 9844753,
  'Payoff': 'PayOff',
  'PenaltyAmount': 20.0,
  'StatusDescription': 'Active',
  'TaxAmount': 0.0,
  'TaxpayerName': 'PERFORMANCE FRICTION INC                '}, ............................................  # other datas too
]
```
Also, settings.py is the same as initial (just changeROBOTSTXT_OBEY = False). 

### My Try
 #4951 had a similar issue and as per one of the developer suggestion in the thread, I tried using `DOWNLOADER_CLIENT_TLS_METHOD=TLSv1.2`. I don't know much about what it does, but I was not able to resolve this. 

I am confused about what I have done wrong with scrapy and have been searching for a solution for two days. I will appreciate it if you can let me know if this is a scrapy bug or some default configuration and point me in the right direction. 

Thank you,
Binit Dhakal

**Comment by wRAR** [comment]
I get the same error response from `requests`.

**Comment by Binit-Dhakal** [comment]
Hello @wRAR, Thank you for your message. I edited the above code. There was a slight typo in "SecurityKey" when I copied headers here. It is working now from my end. Can you check it? Please let me know if I need to provide any more information.
Thank you,

**Comment by wRAR** [comment]
Yes, now it works (with requests, not Scrapy).

**Comment by Laerte** [comment]
This happening because the website is expecting the exact `SecurityKey` header name (I confirmed this via sending the request through Insomnia), this seems a on-going issue with Twisted:
- https://github.com/scrapy/scrapy/issues/2711#issuecomment-321040485

What you can do to overcome this is modify `_caseMappings` attribute from Twisted internal (like [suggested here](https://github.com/scrapy/scrapy/issues/2711#issuecomment-367342284)) to add your header:

```python
from twisted.web.http_headers import Headers as TwistedHeaders
TwistedHeaders._caseMappings[b'securitykey'] = b'SecurityKey'
```

You can put before the request or in top of file (before Spider declaration). I tested and worked for me. Can you try in your side?

**Comment by Binit-Dhakal** [comment]
Hello @Laerte, Thank you for the help. The code you provided sorted things out for me. I never knew about this attribute from Twisted.
As it is resolved I will close this issue. Thank you for your detailed response.
Best Regards,
Binit Dhakal
