### ISSUE TITLE
Remove docs for other projects from the Scrapy docs

### ISSUE THREAD

**Issue by wRAR** [scrapy/scrapy#5920]
We have some auto* statements for things from other projects, like itemadapter in https://github.com/scrapy/scrapy/blob/92f86fab062d179fd68590f1be6a24ca13ec33b6/docs/topics/items.rst?plain=1#L404 and parsel in https://github.com/scrapy/scrapy/blob/92f86fab062d179fd68590f1be6a24ca13ec33b6/docs/topics/selectors.rst#L1037.

We should find these and remove them, instead linking to the other projects docs and maybe adding some explanations locally.

**Comment by amedina1570** [comment]
I would like to contribute to this issue. Is anybody working with it?

**Comment by Gallaecio** [comment]
@amedina1570 Please go ahead

**Comment by whendo** [comment]
@amedina1570 I'd be willing to pitch in if you're not done already

**Comment by amedina1570** [comment]
> @amedina1570 I'd be willing to pitch in if you're not done already

I could really use some help trying to generate some examples for these external libraries for further reference, for example: parsel.xpathfuncs.set_xpathfunc I don't fully understand it and the output is completely unexpected.

**Comment by ParthJuneja** [comment]
is there any help required for this issue? I would like to contribute x

**Comment by wRAR** [comment]
@ParthJuneja I think you can just go ahead

**Comment by ghostp13409** [comment]
Hey @wRAR @amedina1570,
I would love to contribute. is there any help still required?

**Comment by wRAR** [comment]
@ghostp13409 there is a promising PR for this so I wouldn't recommend to duplicate effort for now.

**Comment by dwk601** [comment]
I would like to contribute.

**Comment by wRAR** [comment]
@dwk601 sure, go ahead. Please note that there are old incomplete PRs for this, you can reuse some of the work there.

**Comment by hitansupanda** [comment]
Hey @wRAR @amedina1570 ,
I would like to contribute is there any thing I can do?
