### ISSUE TITLE
ValueError: Cannot use xpath on a Selector of type 'json'

### ISSUE THREAD

**Issue by damodharheadrun** [scrapy/scrapy#5923]
### Description
.local/lib/python3.8/site-packages/parsel/selector.py", line 621, in xpath
Scrapy version 2.8.0

[Description of the issue]

### Steps to Reproduce

1. URL request response is json.
2. Some times we use to get the html response.
3. We have written xpath for the html_response , but now i'm getting the ValueError: Cannot use xpath on a Selector of type 'json'
4. Earlier we are able to get the response, now it is thowing an exception

**Expected behavior:** Error should not accour 

**Actual behavior:** json is removed from the self.type under selector 
   ex:            if self.type not in ("html", "xml", "text", "json"):
            raise ValueError(
                f"Cannot use xpath on a Selector of type {self.type!r}"
            )
        if self.type in ("html", "xml"):
            try:
                xpathev = self.root.xpath
            except AttributeError:
                return typing.cast(
                    SelectorList[_SelectorType], self.selectorlist_cls([])
                )
        else:
            try:
                xpathev = self._get_root(self._text or "", type="html").xpath
            except AttributeError:
                return typing.cast(
                    SelectorList[_SelectorType], self.selectorlist_cls([])
                )

**Reproduces how often:** 100%
### Versions

Please paste here the output of executing `scrapy version --verbose` in the command line.

### Additional context

Any additional information, configuration, data or output from commands that might be necessary to reproduce or understand the issue. Please try not to include screenshots of code or the command line, paste the contents as text instead. You can use [GitHub Flavored Markdown](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) to make the text look better.

**Comment by Gallaecio** [comment]
I find it interesting that you were able to use XPath to parse HTML within a JSON structure before.

If you are looking for a workaround, downgrade parsel to <1.8.

As for a long-term solution, I am inclined to say that this is how things should work.

If you have `{"html": "<html><title>foo</title></html>"}`, you do not use `response.xpath("//title")`, you use `response.selector.jmespath("html").xpath("//tittle")` (or, starting with the upcoming Scrapy 2.9, `response.jmespath("html").xpath("//tittle")`).

**Comment by damodharheadrun** [comment]
Thanks for the quick update @Gallaecio 

Is this same for 2.5.0 also?

**Comment by Gallaecio** [comment]
It affects any version of Scrapy if your version of Parsel is 1.8.0 or later.

**Comment by GeorgeA92** [comment]
> I find it interesting that you were able to use XPath to parse HTML within a JSON structure before.

On parsel 1.6.0 and older - application add extra `<html>><body><p>`  tags that "make" it.. possible to use css xpath selectors (attempt to "get" valid html as browser does)

```python

from parsel import Selector
selector_json = Selector(text='{"a":"1"}')

print(selector_json.getall())
# parsel 1.6: ['<html><body><p>{"a":"1"}</p></body></html>']
# parsel 1.8: [{'a': '1'}] # <-converted to dict, we see ' instead of original ", most likely expected to receive str here"

#print(selector_json.css('*::text').getall())
print(selector_json.css('p::text').getall())

# parsel 1.6: ['{"a":"1"}']

# parsel 1.8:
'''
    print(selector_json.css('p::text').getall())
  File "<redacted>\parsel\parsel\selector.py", line 680, in css
    raise ValueError(
ValueError: Cannot use css on a Selector of type 'json'

Process finished with exit code 1

'''
```

> If you have {"html": "<html><title>foo</title></html>"}, you do not use response.xpath("//title"), you use response.selector.jmespath("html").xpath("//tittle") (or, starting with the upcoming Scrapy 2.9, response.jmespath("html").xpath("//tittle")).

In case if server return json response with.. html inside it's variables - Selector <strike>will be</strike> was able to parse it's html content by xpath/css selectors without any additional data transformations:

```python

text2 = '''{
"prod_1": "<div class=product><div class=price>1$</div></div>",
"prod_2": "<div class=product><div class=price>2$</div></div>",
"prod_3": "<div class=product><div class=price>3$</div></div>"}
'''

selector_html = Selector(text=text2)
print(selector_html.css('div.price::text').getall())
# parsel 1.6: ['1$', '2$', '3$']
# parsel 1.8:
'''
    print(selector_html.css('div.price::text').getall())
  File "<redacted>\parsel\parsel\selector.py", line 680, in css
    raise ValueError(
ValueError: Cannot use css on a Selector of type 'json'
'''
```

**Comment by damodharheadrun** [comment]
> 

Thanks for the detailed information @GeorgeA92

**Comment by Pechi77** [comment]
how about 

```
from scrapy.selector import Selector
response = Selector(text=data.get("html"))
response.xpath("//title")
```

**Comment by damodharheadrun** [comment]
from scrapy.selector import Selector
response = Selector(text=str(data))
response.xpath("//title")

**Comment by Self-supporting626** [comment]
> I find it interesting that you were able to use XPath to parse HTML within a JSON structure before.
> 
> If you are looking for a workaround, downgrade parsel to <1.8.
> 
> As for a long-term solution, I am inclined to say that this is how things should work.
> 
> If you have `{"html": "<html><title>foo</title></html>"}`, you do not use `response.xpath("//title")`, you use `response.selector.jmespath("html").xpath("//tittle")` (or, starting with the upcoming Scrapy 2.9, `response.jmespath("html").xpath("//tittle")`).





https://pythoner.space/questions/creating-objects-dynamically-in-scrapy-and-exporting-them-to-json-format
