### ISSUE TITLE
Memory leak in items 

### ISSUE THREAD

**Issue by yussefbens** [scrapy/scrapy#5924]
I have a server that crawl 4 million pages a day, when I reduce the number of returning items in parse function it works properly but when I return about 42 items it works at the beginning but as pages grow the rate of crawled pages drop also from (460 pages/min) to (156 pages/min).

I'm searching for a solution to free the items from memory as they finish the parse.

**Comment by wRAR** [comment]
If you think there is a bug in Scrapy please provide a minimal reproducible example of it.
