### ISSUE TITLE
PostProcessingManager does not implement seek and read

### ISSUE THREAD

**Issue by Lerchensporn** [scrapy/scrapy#5928]
When configuring the feed to use a postprocessing plugin, such as scrapy.extensions.postprocessing.GzipPlugin, UnsupportedOperation is raised in exporters that call file.seek or file.read in their _store_in_thread method (example: GCSFeedStorage). The cause is that PostProcessingManager is supposed to act like a file object, but does not implement the seek and read methods.

**Comment by wRAR** [comment]
That's #5500, fixed in 2.9.0.

**Comment by Lerchensporn** [comment]
The fix is broken because it closes the temporary file. _store_in_thread receives a closed file and seek on it fails. To solve the problem we should only close the GzipFile instance, not the temporary file. Removing the line self.file.close() in GzipPlugin, Bz2Plugin and LZMAPlugin should resolve the error.

**Comment by wRAR** [comment]
Please open a new issue about this.
