### ISSUE TITLE
Persist cookies between spider runs

### ISSUE THREAD

**Issue by vigandika** [scrapy/scrapy#5930]
## Summary

Scrapy's [CookiesMiddleware](https://docs.scrapy.org/en/latest/topics/downloader-middleware.html#module-scrapy.downloadermiddlewares.cookies) persist cookies and shares them between subsequent requests **from the same spider**. Once the spider is closed, the cookies are lost. If another spider (or the same one) that interacts with the same website is run next, it cannot use the cookies retrieved from the earlier run.

## Motivation

Picture this scenario:

I have four different spiders which need to scrape different pages of the same website, and they need to be run 3 times a day, every day. The pages I need to scrape are protected, i.e. I need to be logged in, and the website implements cookie-based authentication to create and maintain sessions. The cookie expires after 24hrs.

I have already implemented the login in the middleware. To emphasize the need for this issue, the website I am dealing with happens to be very slow.

### Current flow

Currently, each spider will perform the following:

1. Request the target page
2. Perform the login (since the request is not authenticated)
3. Redirect to the target page
4. Scrape data

This same process will be repeated 12 times (3 times a day for each spider (4)).

### Ideal flow (after implementing this feature)

If we could persist the session between spider runs, the flow would be as follows:

On 1st spider run:

1. Request the target page
2. Perform the login (since the request is not authenticated)
3. Redirect to the target page
4. Scrape data

On subsequent spider runs:

1. Request the target page
2. Scrape data

By persisting the session between different spider runs, the login would've only been triggered once. The other spider runs can use the cookie retrieved by the first spider run which correctly underwent the login flow, and directly scrape the data, avoiding any delay and potential issues caused by the login process.

## Alternatives used until Scrapy 2.8.0

This feature was available in the `scrapy-cookies` lib (see https://scrapy-cookies.readthedocs.io/en/latest/intro/tutorial.html#save-cookies-and-restore-in-your-next-run), and proved to be very useful, especially with the login cookie. Unfortunately, `scrapy-cookies` is incompatible with Scrapy 2.8.0 or newer.

The breaking point was the removal of the deprecated method `scrapy.utils.python.to_native_str`, which [was removed in Scrapy 2.8.0](https://docs.scrapy.org/en/2.8/news.html#deprecation-removals) but [still used by scrapy-cookies](https://github.com/scrapedia/scrapy-cookies/blob/master/scrapy_cookies/downloadermiddlewares/cookies.py#L13).

**Comment by GeorgeA92** [comment]
1. related change in Scrapy cookies middleware applied as result of this commit https://github.com/scrapy/scrapy/commit/397e8835564614608647c855c62c36232020f078 <br> on that commit `scrapy.utils.python.to_native_str` was replaced by `from scrapy.utils.python.to_unicode`
2. comparing `_debug_cookie` and `_debug_set_cookie` methods from [scrapy-cookies](https://github.com/scrapedia/scrapy-cookies/blob/master/scrapy_cookies/downloadermiddlewares/cookies.py#L13). and from current scrapy I don't see any other differences.
3. middleware call that `scrapy.utils.python.to_native_str` only on `COOKIES_DEBUG:True` - switching that setting value to `False` may restore (not sure) it.
4. It looks like middleware from  [scrapy-cookies](https://github.com/scrapedia/scrapy-cookies/blob/master/scrapy_cookies/downloadermiddlewares/cookies.py#L13) - is hardcoded scrapy original cookie middleware (the latest available version at that moment) with.. custom functionality.

cc @grammy-jiang

**Comment by wRAR** [comment]
> The breaking point was the removal of the deprecated method scrapy.utils.python.to_native_str, which was removed in Scrapy 2.8.0 but still used by scrapy-cookies.

Updating the code to not use it should be trivial though.

**Comment by GeorgeA92** [comment]
> The pages I need to scrape are protected, i.e. I need to be logged in, and the website implements cookie-based authentication to create and maintain sessions

BTW I am strictly against of applying this or any other similar functionality into scrapy itself especially as enabled by default feature.

Storing any kind of.. sensitive information like session(under login) data -  definitely will be additional source of.. related security concerns.

**Comment by wRAR** [comment]
> Because of the ImportError mentioned above, the only option would be to fork the scrapy-cookies repository. This would be our last resort.

Yes, I was talking about fixing `scrapy-cookies`. If you can't or don't want to fork it you can wait for someone else to do that or to fix the upstream. That's at least comparable to waiting for a feature to be implemented in Scrapy.

**Comment by wRAR** [comment]
As there is a 3rd-party extension that does this it makes sense to just use it instead of adding this to Scrapy, unless there are things that can only be done in Scrapy (but it looks like the extension already solves the stated problem).

**Comment by wRAR** [comment]
Related: #5431 #5463

**Comment by grammy-jiang** [comment]
@GeorgeA92 sorry I haven't worked with Scrapy for a while, and lost the track of the latest version. I can try to fix this compatible issue.

**Comment by grammy-jiang** [comment]
@vigandika I just fix the import you mentioned. My development environment has some issues for tests. Please have a try and let me know if there is any further problem.
