### ISSUE TITLE
Feed export %(time)s is different for each batch

### ISSUE THREAD

**Issue by maxromanovsky** [scrapy/scrapy#5934]
### Description

Feed export `%(time)s` is inconsistent when used in conjunction with batches.

Consider the following example:
```python
FEEDS = {
    "gs://foo/feeds/%(time)s/%(batch_id)05d.jsonl": {
        "format": "jsonlines",
        "batch_item_count": 1000,
}
```

### Steps to Reproduce

1. Run scrapy with the config above

**Expected behavior:** [What you expect to happen]
All batches are in the same folder, e.g.:
```
gs://foo/feeds/2023-05-16T17-04-32/00001.jsonl
gs://foo/feeds/2023-05-16T17-04-32/00002.jsonl
gs://foo/feeds/2023-05-16T17-04-32/00003.jsonl
```

**Actual behavior:** [What actually happens]
Every batch is in different folder, e.g.:
```
gs://foo/feeds/2023-05-16T17-04-32/00001.jsonl
gs://foo/feeds/2023-05-16T17-05-01/00002.jsonl
gs://foo/feeds/2023-05-16T17-05-12/00003.jsonl
```

I would expect this behaviour with `%(batch_time)s` instead of `%(time)s`

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

```
Scrapy       : 2.9.0
lxml         : 4.9.2.0
libxml2      : 2.9.13
cssselect    : 1.2.0
parsel       : 1.8.1
w3lib        : 2.1.1
Twisted      : 22.10.0
Python       : 3.11.3 (main, Apr  7 2023, 20:13:31) [Clang 14.0.0 (clang-1400.0.29.202)]
pyOpenSSL    : 23.1.1 (OpenSSL 3.1.0 14 Mar 2023)
cryptography : 40.0.2
Platform     : macOS-13.3.1-arm64-arm-64bit
```

### Additional context

Any additional information, configuration, data or output from commands that might be necessary to reproduce or understand the issue. Please try not to include screenshots of code or the command line, paste the contents as text instead. You can use [GitHub Flavored Markdown](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) to make the text look better.

**Comment by GeorgeA92** [comment]
According to scrapy docs [Feed exports/Storage URI parameters section](https://docs.scrapy.org/en/2.9/topics/feed-exports.html#storage-uri-parameters) :

> %(time)s - gets replaced by a timestamp **when the feed is being created**

Which means that **actual behavior** - match documented expected behavior. Moment when batch/feed created(different time for each batch) is not the same as time of start of application as initially expected here.

e.g. for job I scheduled today (with enabled batches) that lasts for.. 48 hours at least I definitely don't expect that filename of last batch contain time... for very first batch by setting `%(time)s` in `FEEDS`.

**Comment by maxromanovsky** [comment]
@GeorgeA92 in that case
- what's the difference between `%(time)s` and `%(batch_time)s`?
- how to achieve in practice saving all batches from the run to the same folder?

Consider use case when files previous runs are stored in subfolders with datetime, and some other job uses either latest subfolder to get the current state OR all the subfolders to read historical state.

Is it possible to achieve using some other replacement token in `FEEDS` configuration or somehow passing the full path on the command line?
