### ISSUE TITLE
Can you help me get links

### ISSUE THREAD

**Issue by kelvinmaringire** [scrapy/scrapy#5935]
I am trying to crawl link on betway but i am stuck the url is https://www.betway.co.za/sport/soccer/int_clubs/uefa_champions_league/manchester_city-v-real_madrid/0?datefilter=202305172100&eventId=026e4611-0000-0000-0000-000000000000

i would like to get so many links like that i tried without success my code is below:

from scrapy.spiders import CrawlSpider, Rule
from scrapy.linkextractors import LinkExtractor

class BetwaySpider(CrawlSpider):
    name = "betway"
    allowed_domains = ["betway.co.za"]
    start_urls = ["https://www.betway.co.za/"]

    rules = (
        Rule(LinkExtractor(allow='sport/soccer', deny='esport')),
        Rule(LinkExtractor(allow=(r'datefilter=20230517(\d{4})')), callback="parse_link", follow=True),
    )

    def parse_link(self, response):
        # Process the link as needed
        print('Link:', response.url)

i want links with a specific date but now all dates are coming

plz help i am stuck

**Comment by Gallaecio** [comment]
https://docs.scrapy.org/en/latest/#getting-help
