### ISSUE TITLE
Docs involving Request.cookies are inaccurate

### ISSUE THREAD

**Issue by plug-city** [scrapy/scrapy#5936]
### Description

The docs for a scrapy.Request have an example that no longer work. See docs [here](https://docs.scrapy.org/en/latest/topics/request-response.html).

In the section where it says: 

> Example of a request that sends manually-defined cookies and ignores cookie storage:
> Request(
>     url="http://www.example.com",
>     cookies={"currency": "USD", "country": "UY"},
>     meta={"dont_merge_cookies": True},
> )
> 

If you submit a request with  `meta={"dont_merge_cookies": True}` then the cookies parameter of a Request object is completely ignored. The manual cookies of `cookies={"currency": "USD", "country": "UY"}` are not included in the request.

**Expected behavior:** [What you expect to happen]

We would expect to see `'cookie': 'currency=USD; country=UY'` in the request headers.

**Actual behavior:** [What actually happens]

The cookies are completely dropped.

Here is the output of `request.headers.to_unicode_dict()`:
`{'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
 'accept-encoding': 'gzip, deflate',
 'accept-language': 'en',
 'user-agent': 'Scrapy/2.8.0 (+https://scrapy.org)'}
`

### Versions

Scrapy       : 2.8.0
lxml         : 4.9.2.0
libxml2      : 2.9.13
cssselect    : 1.2.0
parsel       : 1.7.0
w3lib        : 2.1.1
Twisted      : 22.10.0
Python       : 3.11.0 | packaged by conda-forge | (main, Jan 14 2023, 12:26:40) [Clang 14.0.6 ]
pyOpenSSL    : 23.0.0 (OpenSSL 3.0.8 7 Feb 2023)
cryptography : 39.0.1
Platform     : macOS-13.2.1-arm64-arm-64bit

### Additional context

I am patching this by overriding the CookiesMiddleware.process_request and using a temporary cookiejar.

```
def process_request(self, request, spider):
        if request.meta.get("dont_merge_cookies", False):
            jar = CookieJar() # Temporary cookiejar
        else:
            cookiejarkey = request.meta.get("cookiejar")
            jar = self.jars[cookiejarkey]
        cookies = self._get_request_cookies(jar, request)
        self._process_cookies(cookies, jar=jar, request=request)

        # set Cookie header
        request.headers.pop("Cookie", None)
        jar.add_cookie_header(request)
        self._debug_cookie(request, spider)


```

**Comment by 11-aryan** [comment]
Hey, can i take up this issue? If yes could you please tell how to get started with it?

**Comment by Gallaecio** [comment]
I’m not sure if it’s easy to explain to someone not familiar with #2124. In https://doc.scrapy.org/en/latest/topics/request-response.html#request-objects , in the `cookies` parameter, there is documentation suggesting that `dont_merge_cookies` can be used in combination with custom cookies. That is not accurate. We should probably remove the whole part about sending custom cookies with `dont_merge_cookies`, and instead make it clear that `dont_merge_cookies` causes custom cookies to be ignored.
