### ISSUE TITLE
Spider not saving output to jsonline

### ISSUE THREAD

**Issue by conceptofmind** [scrapy/scrapy#5940]
Hi all,

I put together a crawler to extract URLs found on a website and save them to a jsonline file:

```python
import scrapy
from scrapy.crawler import CrawlerProcess

class MySpider(scrapy.Spider):
    name = 'medscape_crawler'
    allowed_domains = ['medscape.com']
    start_urls = ['https://www.medscape.com/']
    custom_settings = {
        'ROBOTSTXT_OBEY': False,
        'DOWNLOAD_DELAY': 2,
        'FEEDS': {'medscape_links.jsonl': {'format': 'jsonlines',}}
    }

    def parse(self, response):
        yield {'url': response.url}  # Save this page's URL

        for href in response.css('a::attr(href)').getall():
            if href.startswith('http://') or href.startswith('https://'):
                yield response.follow(href, self.parse)

process = CrawlerProcess(MySpider.custom_settings)
process.crawl(MySpider)
process.start()
```
The crawler successfully collects the links but does not populate the jsonline file with any outputs:
```
2023-05-28 21:20:31 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://portugues.medscape.com> (referer: https://www.medscape.com/)
2023-05-28 21:20:31 [scrapy.core.scraper] DEBUG: Scraped from <200 https://portugues.medscape.com>
{'url': 'https://portugues.medscape.com'}
```
The jsonline file remains empty. Adding `'FEED_EXPORT_BATCH_ITEM_COUNT': 10,` does not make earlier saves.

Is it better to use the LinkExtractor instead?
```python
    rules = (
        Rule(LinkExtractor(allow_domains=allowed_domains), callback='parse_item', follow=True),
    )
```
Any help would be greatly appreciated.

Thank you,

Enrico

**Comment by VicLG98** [comment]
Hello, i use this and it works:

`"FEEDS": {
    "crawler_otodom/%(batch_time)s.jsonl" if os.getenv("SHUB_JOBKEY") else None:
        {
            'format': 'jsonlines',
            'encoding': 'utf8',
            'store_empty': False,
            'fields': None,
            'indent': 4,
            "item_export_kwargs": {'export_empty_fields': False}
        }
},
`

**Comment by wRAR** [comment]
> The jsonline file remains empty. 

Only while the spider is running. I assume it's because the data is very small and gets output slowly so the first buffer write happens after quite some time.

> Adding 'FEED_EXPORT_BATCH_ITEM_COUNT': 10, does not make earlier saves.

It does, if you provide the correct configuration of the file names, but I don't think you want lots of tiny files.

**Comment by conceptofmind** [comment]
> %(batch_time)s

Adding this resolved the issue.

Thank you.



> > The jsonline file remains empty.
> 
> Only while the spider is running. I assume it's because the data is very small and gets output slowly so the first buffer write happens after quite some time.
> 
> > Adding 'FEED_EXPORT_BATCH_ITEM_COUNT': 10, does not make earlier saves.
> 
> It does, if you provide the correct configuration of the file names, but I don't think you want lots of tiny files.
> 
> > Is it better to use the LinkExtractor instead?
> 
> No.

I appreciate the additional information.
