### ISSUE TITLE
DownloaderMiddleware should be able to return a request generator from process_request

### ISSUE THREAD

**Issue by rngadam** [scrapy/scrapy#5942]
## Summary

DownloaderMiddleware should be able to return a request generator from process_request.

This would mirror the behavior from scrapy.Spider.parse

## Motivation

We want to be able to create a downloader middleware that:

* checks if the current page is already in the database
  * if yes, returns a response with the content of the page
  * if no
    * reads up the content and schedule processing from all URLs found within the cached file
    * raise IgnoreRequest on the current page

Example code:

```
    def process_request(self, request, spider):
        # check if url is in database
        self.cursor.execute("SELECT * FROM public.crawl WHERE url = %s", (request.url,))
        row = self.cursor.fetchone()
        if row is None:
            parsed = urlparse(request.url)
            return fake_response_from_file('/workspaces/louis-crawler/Cache' + parsed.path)
        else:
            selector = Selector(text=row['html_content'])
            yield from extract_urls(selector)
            raise IgnoreRequest("URL already crawled %s" % request.url)
```

## Describe alternatives you've considered

I've instead just let the processing continue and catch the duplicate insertion into the database:

```
    def process_item(self, item, spider):
        adapter = ItemAdapter(item)
        try:
            with self.connection.cursor() as cursor:
                cursor.execute("INSERT INTO public.crawl (url, title, lang, html_content, last_crawled, last_updated) VALUES (%s, %s, %s, %s, %s, %s)",
                            (adapter['url'], adapter['title'], adapter['lang'], adapter['html_content'], adapter['last_crawled'], adapter['last_updated']))
                return item
        except psycopg2.IntegrityError as e:
            # ignore duplicates and keep processing
            return item
```

This works but creates extra unnecessary processing on each page.

## Additional context

At the moment, process_request has the following doc:

```
        # Called for each request that goes through the downloader
        # middleware.

        # Must either:
        # - return None: continue processing this request
        # - or return a Response object
        # - or return a Request object
        # - or raise IgnoreRequest: process_exception() methods of
        #   installed downloader middleware will be called
```

returning a generator raises an exception.

**Comment by wRAR** [comment]
> This would mirror the behavior from scrapy.Spider.parse

Callbacks process responses, not requests, so I don't see mirroring here.

What mirrors callbacks is `process_spider_output` in spider middlewares.

> checks if the current page is already in the database
> if yes, returns a response with the content of the page
> if no
> reads up the content and schedule processing from all URLs found within the cached file
> raise IgnoreRequest on the current page

Sounds like you may want a cache backend, not a downloader middleware? Though I'm not sure what does this logic achieve anyway, even with provided code. And it looks like no code paths actually execute the input request which to me sounds like it shouldn't have been emitted in the first place.
