### ISSUE TITLE
Scrapy Spider to Extract All html links for Different HS Codes, Origins, and Destinations from EU website

### ISSUE THREAD

**Issue by murasz** [scrapy/scrapy#5947]
I am currently working on a web scraping project using Scrapy in Python to make an informational notebook for myself. The goal is to extract all possible links from https://trade.ec.europa.eu/ (https://trade.ec.europa.eu/access-to-markets/en/search?product=&origin=&destination= ) that contain different combinations of HS codes (product), origins, and destinations. The website structure is such that each product (HS code) has a specific link, and each of these links can have different origins and destinations. I want to be able to scrape all these links like: https://trade.ec.europa.eu/access-to-markets/en/results?product=3902100020&origin=TR&destination=PL

Here's a simplified version of my current Scrapy spider:

```
import scrapy
from scrapy.crawler import CrawlerProcess
from urllib.parse import urljoin

class MySpider(scrapy.Spider):
    name = 'myspider'
    start_urls = ['https://trade.ec.europa.eu/access-to-markets/en/search?product=&origin=TR&destination=PL']

    def parse(self, response):
        base_url = 'https://trade.ec.europa.eu/access-to-markets/en/search?product=&origin=TR&destination=PL'
        with open('links.txt', 'w') as f:
            for link in response.css('a::attr(href)').extract():
                # Check if the link is relative or absolute
                if link.startswith('http'):
                    absolute_url = link
                else:
                    absolute_url = urljoin(base_url, link)
                print(absolute_url)
                f.write(absolute_url + '\n')
            f.close()

process = CrawlerProcess()
process.crawl(MySpider)
process.start()
```

However, I'm having trouble figuring out how to make sure the spider checks all possible combinations of product, origin, and destination, and scrapes all the corresponding links. I would appreciate any guidance on how to modify my spider to achieve this.

Thank you in advance for your help!

**Comment by wRAR** [comment]
This is the Scrapy issue tracker, please ask questions about your code on suitable platforms.

**Comment by murasz** [comment]
Sure, thanks. Sorry for the inconvenience. 

> This is the Scrapy issue tracker, please ask questions about your code on suitable platforms.
