### ISSUE TITLE
BaseSettings.pop method throws KeyError even if default value is provided

### ISSUE THREAD

**Issue by Prometheus3375** [scrapy/scrapy#5959]
# Description

`BaseSettings` inherit from `MutableMapping` and thus has method `pop`. This method takes a key and excludes it from the mapping returning its value. If key does not exist, then `KeyError` is raised, but if default value is provided, then it is returned instead.

# Steps to Reproduce

Run this sample:
```python
from scrapy.settings import Settings
s = Settings()
print(s.pop('meh', 'Hello world!'))
```

# Expected behavior
`Hello world!` is printed.

# Actual behavior:
```
Traceback (most recent call last):
  File "REDACTED\main.py", line 3, in <module>
    print(s.pop('meh', 'Hello world!'))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen _collections_abc>", line 918, in pop
  File "REDACTED\.venv\Lib\site-packages\scrapy\settings\__init__.py", line 362, in __delitem__
    del self.attributes[name]
        ~~~~~~~~~~~~~~~^^^^^^
KeyError: 'meh'
```

**Reproduces how often:** always

# Current workaround
Since 2.9.0:
```python
from scrapy.settings import Settings

s = Settings()
s.setdefault('meh', 'Hello world!')
print(s.pop('meh'))

```

Earlier:
```python
from scrapy.settings import Settings
s = Settings()
if 'meh' in s:
    print(s.pop('meh'))
else:
    print('Hello world!')
```

# Versions

```
Scrapy       : 2.8.0
lxml         : 4.9.2.0
libxml2      : 2.9.12
cssselect    : 1.2.0
parsel       : 1.8.1
w3lib        : 2.1.1
Twisted      : 22.10.0
Python       : 3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)]
pyOpenSSL    : 23.1.1 (OpenSSL 3.1.0 14 Mar 2023)
cryptography : 40.0.2
Platform     : Windows-10-10.0.19044-SP0
```

# Additional context

Please, check that `BaseSettings` indeed implement all `MutableMapping` methods correctly. There was already [similar issue](https://github.com/scrapy/scrapy/issues/5811) with `setdefault` method. [List of methods](https://docs.python.org/3/library/collections.abc.html#collections-abstract-base-classes) implemented inside `MutableMapping` in red rectangle:
![image](https://github.com/scrapy/scrapy/assets/35541026/7df6d6ea-b704-4507-be30-79b261cbfe6c)
Methods that are not re-implemented in `BaseSettings` are `pop`, `popitem` and `clear`.

**Comment by Prometheus3375** [comment]
According to my tests, `popitem` and `clear` seem to be fine, they cannot modify frozen settings because they are using `__delitem__`. Although `clear` can be speed up with just reassigning `attributes` with new empty dict.

**Comment by wRAR** [comment]
Yeah, unfortunately BaseSettings doesn't follow the MutableMapping contract correctly, I've seen that when adding typing to it. We should try fixing it, hopefully we won't need to break compatibility.

**Comment by Prometheus3375** [comment]
Why it was decided that `pop` should return `SettingsAttribute` object? This breaks mapping protocol a bit. `values`, `get` return raw values and `items` and `popitem` return key-value pairs. In my opinion, `pop` must return raw value too, i.e. like `get` but if key is present it is removed from the mapping.

In current implementation `pop` is the only method that returns `SettingsAttribute`, this is very strange privilege. If `pop` returns `SettingsAttribute`, then at least `popitem` should return pair `(key, SettingsAttribute)`. Getting value along with priority can be indeed useful, although priority is not common for mappings, so I am OK to get it before popping when necessary.

In addition, if other `SettingAttribute` is passed as `default` to `pop` [it is wrapped into another `SettingAttribute`](https://github.com/scrapy/scrapy/blob/510574216d70ec84d75639ebcda360834a992e47/scrapy/settings/__init__.py#L457). Inside `set` methods, any passed `SettingAttribute` is used directly.

**Comment by Laerte** [comment]
@Prometheus3375 You are right, this was the behaviour before we implement the `pop` method, i will raise a PR to fix that, thank you for pointing out.
