### ISSUE TITLE
Support infinite generators for start_requests that can be starved temporarily

### ISSUE THREAD

**Issue by soundofspace** [scrapy/scrapy#5962]
## Summary

This feature could be implemented in thee ways:
1. Support yielding None in `start_requests`, and let the engine handle this by ignoring this None request. It would do this in similar way like it does when it handles `_needs_backout()`, instead of starting a new `self.crawl(request)` it would just do nothing, and resume again later when the heartbeat is triggered.
2. Support async in `start_requests` (this is not yet supported if I read everything correctly). This way when there are temporarily no start requests the engine could await a new start_request without blocking the main event loop. Another thread could then provide this request, and continue the execution of the engine. 
3. Support spider signalling the engine that it needs a pause for `new_request`. This would allow the spider to stop the engine from starting new request, while still continue the scheduled request. It would be similar to pause but only for new requests. This could be used when there are temporarily no new requests. It is also very flexible to be used in different scenarios, where you could for example use it to limit the work scrapy starts on. This is very different from delayed scheduling as here you kind of already committed to doing the work.

## Motivation

This is needed to supported start_request generators that can be temporarily starved. Pretty much all network driven generators fall in this category. A specific example could be a service generating work for scrapy that is pushed over pubsub.

## Describe alternatives you've considered

- If the generator has no start_request ready, generate a dummy one that is discarded later by the scheduler, together with sleep to prevent hogging 100% cpu. This blocks the main event loop so not really wanted.
- Monkey path scrapy. Something I highly dislike in general
- Restart scrapy automatically every time this happens. Feels like cumbersome workaround especially as this could happen quite often sometimes, but only for short periods of times, and would require a lot of glue around scrapy, instead of just starting it.

## Additional context

I'm willing to work on this my self, and option 1 seems very easy to implement as pretty much all logic is already there, it would only need to support handling a None request. The goal of this issue is mainly looking for initial feedback, and if a pull request for this would be considered. I personally feel option 1 is an initial goal, while option 2 would be the long term goal seeing as scrapy is moving to async. Option 3 feels more like a separate issue, but could do the job here (be it more ugly).

**Comment by wRAR** [comment]
This is #456.
