### ISSUE TITLE
When read the current feed output jsonl in the close() method,  it does not read 100% all the lines of the file

### ISSUE THREAD

**Issue by marginxai** [scrapy/scrapy#5983]
### Description

[Description of the issue]
I am reading the output jsonl on close to do some batch operation when all the items were scraped. However, I've noticed that when reading the jsonl file, it doesn't read all the lines. I have 210 items and it read only 168 lines and items during the close() method, when I open it on separate window the there are 210 items in the jsonl, I also verified it by reading on close the same jsonl file in a different run and it returned 210 items. It seems that this problem only occurs during the current run.  not sure if it is due to some things. 

```
    custom_settings = {
        'DOWNLOAD_DELAY': 0,
        "CONCURRENT_REQUESTS": 5,
        "FEEDS": {f'in_stock_status_{curr_timestamp}.jsonl': {'format': 'jsonlines'}}
    }
```

```
    def close(self, spider, reason):
        path = "in_stock_status_{curr_timestamp}.jsonl"
        with open(path, "r") as f:
            print(f.read())
```

Here the read result is not the full result, only part of it.
I find it weird but I've cross-verified it many times, it indeed does not read the entire file.

One more context is I handled 302 redirect response, if it is 302 I directly yield the item
```
handle_httpstatus_list = [302]

def parse(self,response):
    if response.status == 302:
       yield item

```

**Comment by wRAR** [comment]
It's expected if the file wasn't closed by its writer yet.

**Comment by marginxai** [comment]
> It's expected if the file wasn't closed by its writer yet.

Why should it be expected, when on close it's supposed to mean that all the scraping is finished, the writer should close before the close function getting called. With time waiting it doesn't help solve the problem. I need to do batch operations on all the items in the close method.
