### ISSUE TITLE
Re-enable deps on 3.12 when ready

### ISSUE THREAD

**Issue by wRAR** [scrapy/scrapy#5985]
- [x] bpython (requires greenlet)
- [x] uvloop
- [x] pyftpdlib

Related: https://github.com/scrapy/scrapy/pull/6083

**Comment by Night-Amber3301** [comment]
Could you please explain the issue in detail?

**Comment by Gallaecio** [comment]
This issue requires time, and may span over a month, so it may not be a good choice as a first contribution to Scrapy.

**Comment by wRAR** [comment]
Neither greenlet nor uvloop support 3.12 yet so no action is needed here yet.
