### ISSUE TITLE
type annotation of "headers" argument of scrapy.Request is incomplete

### ISSUE THREAD

**Issue by kmike** [scrapy/scrapy#5989]
Currently `scrapy.Request(headers=...)` argument is annotated as `Optional[dict]`. But we allow other options, e.g. a list of `(name, value)` pairs, which allow to set multiple headers with the same name. Headers instance may also be an option for the users to pass. I think we should ensure that none of this raises mypy typing errors.

**Comment by wRAR** [comment]
Correct and full typing of `CaselessDict` and `Headers` doesn't seem possible, so I think I'll just document the interface and silence the incompatibilities where needed.
