### ISSUE TITLE
Remove things deprecated in 2.6.0

### ISSUE THREAD

**Issue by wRAR** [scrapy/scrapy#5994]
https://docs.scrapy.org/en/latest/news.html#scrapy-2-6-0-2022-03-01

**Comment by Gallaecio** [comment]
https://github.com/scrapy/scrapy/pull/5996 covered most of it.

**Comment by Laerte** [comment]
I still tackling why removing spider from parameter of engine  makes tests run forever. I will update soon as i figure out! 😄

**Comment by wylycool** [comment]
从2.9.0升级到2.11.0后，启动spider会报错，ModuleNotFoundError: No module named 'scrapy.utils.reqser'，应该是和删除了reqser模块有关，但不知道应该怎么改？各位有思路吗？另外scrapy-redis是0.6.8版本

**Comment by wRAR** [comment]
@wylycool https://docs.scrapy.org/en/latest/news.html#id32
