### ISSUE TITLE
ValueError: invalid hostname   when use username and password

### ISSUE THREAD

**Issue by aa3222119** [scrapy/scrapy#6015]
how do i get  
scrapy.Request(url='http://user:password@host:port' .....

in scrapy raised  ValueError: invalid hostname

in curl ,  it works :  curl  http://user:password@host:port

**Comment by wRAR** [comment]
https://docs.scrapy.org/en/latest/topics/downloader-middleware.html#module-scrapy.downloadermiddlewares.httpauth
