### ISSUE TITLE
handling exceptions from the previous middleware in process_exception

### ISSUE THREAD

**Issue by cscxj** [scrapy/scrapy#6017]
## Summary

I hope that in the middleware's preprocessing_ The exception method can handle exceptions thrown by the previous middleware.

## Motivation
I am in the process of the first middleware_ An exception was thrown in the response method, and I want to record these exceptions in the next middleware, but the next middleware cannot capture these exceptions.

I am a beginner, and I don't know if there is a problem with my writing style or if there is a better solution? Please help me!

This is sample code:
```python
class MyMiddleware1:
    def process_response(self, request, response, spider):
        # I will handle some unexpected request results here uniformly,
        # and then throw an error to prevent my spider from processing this result.
        if len(response.body) < 10000:
            raise Exception('Bad data!')

        return response


class MyMiddleware2:
    def _track(self, msg):
        pass

    def process_exception(self, request, exception, spider):
        # Then I hope to uniformly record these errors in the next layer of middleware.
        # But this middleware will not receive the previous middleware process_ Exceptions generated in response.
        self._track(str(type(exception)))

```
settings.py
```python
DOWNLOADER_MIDDLEWARES = {
   "scrapy_demo.middlewares.MyMiddleware1": 99,
   "scrapy_demo.middlewares.MyMiddleware2": 98,
}
```

**Comment by wRAR** [comment]
Please ask questions about problems with your code on suitable platforms such as StackOverflow.
