### ISSUE TITLE
Handling JavaScript Button Click in Scrapy: Unable to Simulate Click on Specific Anchor Tag

### ISSUE THREAD

**Issue by huangyingw** [scrapy/scrapy#6018]
### Description

I encountered an issue while trying to scrape a webpage with Scrapy that contains a specific JavaScript button. I need to simulate a click on the following button to proceed to the next page:

```html
<a href="./" class="enter-btn"> click me to continue </a>
```

However, Scrapy doesn't execute JavaScript by default, so it cannot simulate the click directly.

### Steps to Reproduce

1. Create a new Scrapy project.
2. Attempt to scrape a webpage containing the aforementioned JavaScript button.
3. Try to simulate a click on the button using Scrapy.

**Expected behavior:** I expect Scrapy to simulate a click on the mentioned button and then continue to scrape the next page.

**Actual behavior:** Scrapy is unable to handle the JavaScript button, so it cannot simulate the click and proceed to the next page.

**Reproduces how often:** 100% of the time.

### Versions

```
Scrapy       : 2.8.0
lxml         : 4.9.1.0
libxml2      : 2.9.14
cssselect    : 1.1.0
parsel       : 1.6.0
w3lib        : 1.21.0
Twisted      : 22.10.0
Python       : 3.11.3 (main, Apr 19 2023, 23:54:32) [GCC 11.2.0]
pyOpenSSL    : 23.0.0 (OpenSSL 1.1.1u  30 May 2023)
cryptography : 39.0.1
Platform     : Linux-6.2.0-26-generic-x86_64-with-glibc2.37
```

### Additional context

I have tried using the Scrapy-Splash and Scrapy-Selenium middlewares, but I'm looking for a more direct solution. I also attempted to analyze network requests but couldn't find the appropriate request to simulate. Any help on how to handle this situation directly with Scrapy would be greatly appreciated.

**Comment by wRAR** [comment]
Scrapy is not a browser and so it can't "click".

**Comment by huangyingw** [comment]
is there any other crawler which could "click"?

**Comment by jxlil** [comment]
@huangyingw You could use [scrapy-playwright](https://github.com/scrapy-plugins/scrapy-playwright) for that

**Comment by wRAR** [comment]
https://docs.scrapy.org/en/latest/topics/dynamic-content.html
