### ISSUE TITLE
Recommend scrapy-playwright on "Using a headless browser" section

### ISSUE THREAD

**Issue by Urahara** [scrapy/scrapy#6020]
scrapy-playwright: https://github.com/scrapy-plugins/scrapy-playwright
https://docs.scrapy.org/en/latest/topics/dynamic-content.html#using-a-headless-browser

**Comment by elacuesta** [comment]
It's already there https://github.com/scrapy/scrapy/blob/2.10.0/docs/topics/dynamic-content.rst?plain=1#L286
