### ISSUE TITLE
formatted string to KeyError exception .

### ISSUE THREAD

**Issue by metflekx** [scrapy/scrapy#6023]
at the `scrapy/scrapy/spiderloader.py` at line `89`, the f string is passed directly as exception arg.
which looks like this when the error is trigered.

<img width="877" alt="Screenshot 2023-08-26 at 20 47 15" src="https://github.com/scrapy/scrapy/assets/106245122/eb819645-e2b4-49cd-9156-ed4e71acf669">

**Comment by wRAR** [comment]
> the f string is passed directly as exception arg.

Why do you think this is a problem?

> which looks like this when the error is trigered.

Yes, this is the traceback, it shows the code.

**Comment by metflekx** [comment]
i thought the error message was not printed. but it is. it was my mistake.
