### ISSUE TITLE
I failed to use asynchronous coroutine function calls in scrapy framework functions, what should I do?

### ISSUE THREAD

**Issue by Teresajw** [scrapy/scrapy#6035]
### Description
I get an error when I use asynchronous or synchronous methods in the _**def process_item(self, item, spider)**_ function:
**Asynchronous error:** <coroutine object shot_by_bytes_async at 0x000001E42DB48680>
[ERROR][2023-09-01 16:13:28][ossutils.py:39] - Invalid URL **'<coroutine object shot_by_bytes_async at 0x000001E42DB48680>': No scheme supplied. Perhaps you meant https://<coroutine object shot_by_bytes_async at 0x000001E42DB48680>?
2023-09-01 16:13:28 [log] ERROR: Invalid URL '<coroutine object shot_by_bytes_async at 0x000001E42DB48680>': No scheme** supplied. Perhaps you meant https://<coroutine object shot_by_bytes_async at 0x000001E42DB48680>

**Synchronous error:** F:\datax\ScrapySpider\ScrapySpider\spiders\wechatSpider.py", line 59, in parse_article
    item['content'] = shot_by_bytes(url=response.meta['item_url'])
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\datax\ScrapySpider\utils\screenshot.py", line 68, in shot_by_bytes
    with sync_playwright() as p:
  File "F:\Anaconda3\envs\ScrapySpider\Lib\site-packages\playwright\sync_api\_context_manager.py", line 47, in __enter__
    raise Error(
**playwright._impl._api_types.Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.**
This is my method of encapsulating the playwright screenshot, there are two asynchronous and synchronous as follows:
```
def shot_by_bytes(url, **kwargs):
    with sync_playwright() as p:
        context = p.chromium.launch(headless=True).new_context(
            **p.devices.get(kwargs.get('phone_model'),
                            get_project_settings().get("PHONE_MODEL")) if kwargs else kwargs) 
        page = context.new_page()
        try:
            page.goto(url, wait_until='networkidle')
            for i in page.locator("section").get_by_role('img').all():
                i.scroll_into_view_if_needed()
                i.page.wait_for_timeout(2000)
            screenshot_bytes = page.screenshot(full_page=True, animations="disabled")
            return screenshot_bytes
        except Exception as e:
            logger.error(e)

async def shot_by_bytes_async(url, full_page=True, **kwargs):
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        context = await browser.new_context(**p.devices.get(kwargs.get('phone_model')) if kwargs else kwargs)
        page = await context.new_page()
        await page.goto(url, wait_until="networkidle")
        for i in await page.locator("section").get_by_role('img').all():
            await i.scroll_into_view_if_needed()
            # page.on('response', on_response)
            await i.page.wait_for_timeout(1000)
        screenshot_bytes = await page.screenshot(full_page=full_page, animations="disabled")
        await browser.close()
        return screenshot_bytes
```
[Playwright github url](https://github.com/microsoft/playwright)
### Versions
```
(ScrapySpider) F:\datax\ScrapySpider>scrapy version --verbose
Scrapy       : 2.10.0 
lxml         : 4.9.2.0 
libxml2      : 2.10.4
cssselect    : 1.2.0
parsel       : 1.8.1
w3lib        : 2.1.2
Twisted      : 22.10.0
Python       : 3.11.4 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 13:47:18) [MSC v.1916 64 bit (AMD64)]
pyOpenSSL    : 23.2.0 (OpenSSL 3.0.10 1 Aug 2023)
cryptography : 41.0.2
Platform     : Windows-10-10.0.17763-SP0
```

**Comment by Gallaecio** [comment]
This does not look like a Scrapy issue, it comes from `playwright`.

Also, you might want to look into https://github.com/scrapy-plugins/scrapy-playwright if you don’t know about it.

**Comment by Teresajw** [comment]
thank you ! i`ll try
