### ISSUE TITLE
How can you instruct the crawler to avoid going beyond a depth of 4 levels while still processing content up to 5 directory levels?

### ISSUE THREAD

**Issue by kk7nc** [scrapy/scrapy#6052]
"When we set the DEPTH_LIMIT to 4, it restricts crawling to a maximum depth of 4 levels. However, we would like to continue crawling content up to the 5th directory level, as seen in URLs like example.com/1/2/3/4/5."

**Comment by Gallaecio** [comment]
Restricting by URL path level would be a new feature (e.g. a new setting), and what you seem to want should then be doable by setting both limits. It sounds doable, though I don’t know how much interest there would be for it.

**Comment by wRAR** [comment]
@kk7nc can you please confirm this is what you meant? Thanks.

**Comment by kk7nc** [comment]
> @kk7nc can you please confirm this is what you meant? Thanks.

When we set DEPTH_LIMIT to 4 it goes into all level but just ignore more than 4 I just want to only go 4 level inside of a website to process faster

**Comment by kk7nc** [comment]
> URL path level

Can you send me documentation of URL path level?

**Comment by wRAR** [comment]
> When we set DEPTH_LIMIT to 4 it goes into all level but just ignore more than 4 I just want to only go 4 level inside of a website to process faster

Can you please explain what do you mean?

**Comment by kk7nc** [comment]
to do this we bulid a crawler based on CrawlSpider that uses Rule(linkExtractor()) to find the links. we also set the depth in the crawler class using custom_setting ={DEPTH_LIMIT= number} . Is this setting correct for the above problem? I also noticed "ignored depth> number" in the console logs and I thought that it actually might follow all the links but ignore those that are bigger than depth so it is still checking all of the url in the domain

![image](https://github.com/scrapy/scrapy/assets/21176522/0e8ff982-134c-4077-92bc-09336822c2a5)

**Comment by wRAR** [comment]
> Is this setting correct for the above problem?

Which problem?

> I also noticed "ignored depth> number" in the console logs and I thought that it actually might follow all the links but ignore those that are bigger than depth

No, ignoring means not following them.

Your image seems to correctly show how does DEPTH_LIMIT work so I'm not sure what else do you want.

**Comment by Gallaecio** [comment]
When you say level, I think you mean path level (which is something Scrapy does not handle at all at the moment). Depth level is something else.

Scrapy’s depth level handle does not concern itself with the path of any URL. The start URL is considered level 0*, whatever it’s path. URLs followed from the spider callback for that start URL are considered depth 1, regardless of their URL path. And so on.

So, `https://example.com/1/2/3/4/5/6` could be at depth 2, and `https://example.com/1/2` at depth 16. Depth is determined from link following, the actual URL (path or anything else) has no bearing on the depth.

* I did not bother checking if it starts with 0 or 1, but it should not matter for the explanation.

**Comment by marvinjungre** [comment]
It seems like for this we would need a feature that counts the occurrences of ' / ' after the TLD. Would it make sense to implement this? One would need to have a good understanding of how the website generates its paths, but I think there could be some applications. 

There could either be a minimum, maximum, pattern (e.g. every link that has an even number of x ' / '), or we could provide a list to only follow links with certain numbers of ' / '.

**Comment by wRAR** [comment]
> Would it make sense to implement this? 

So far I don't know if this is something that the original poster (or anyone else) needs.

**Comment by Vedaant-Rajoo** [comment]
In Scrapy, the "depth" refers to how many "hops" the crawler has made from the starting URL to reach the current page, not the number of directories in the URL path.

To include what @kk7nc mentioned:

1 .In your Scrapy spider, you can override the `start_requests` method to begin the crawl. In this method, yield the initial `Request` object with a meta variable to store the directory depth.

2. In your `parse` method, you can check this meta variable before deciding to follow a link. You'll also update this variable each time you do decide to follow a link, by parsing the URL and counting its directory levels.

3. If the directory level is within your defined `limit`, proceed to follow the link and scrape the page. Otherwise, just scrape the page without following any more links.

Is this what you had in mind @kk7nc ?

**Comment by Rhythm1710** [comment]
Hi I want to work on this project.Could you assign me this issue?

**Comment by wRAR** [comment]
You don't need to be assigned to work on something, but also this issue is not clear and will be closed if the reported doesn't clarify it soon.

**Comment by Rhythm1710** [comment]
Ohh ok, I want to contribute in the open source for the first time.Could you help me in that? @wRAR

**Comment by wRAR** [comment]
@Rhythm1710 in that case you need to find another issue to work on.
