### ISSUE TITLE
About middleware modification body

### ISSUE THREAD

**Issue by emoob** [scrapy/scrapy#6054]
HI man:
 I am currently encountering an issue with the inability to modify the body in the middleware. I have consulted many materials on Google but have not resolved this issue
 PS :
![p1](https://github.com/scrapy/scrapy/assets/117696884/35ab431f-0552-423f-824a-7fa0195351e4)
![P2](https://github.com/scrapy/scrapy/assets/117696884/4c08996d-062c-43fc-9295-9c48346ac8b5)

**Comment by Gallaecio** [comment]
We don’t use GitHub as a support channel, only for bug reports and feature requests. Please, see https://scrapy.org/community/
