### ISSUE TITLE
'items Module Not Found' error despite IDE Recognizing Correct Import

### ISSUE THREAD

**Issue by jribs** [scrapy/scrapy#6055]
### Description

When attempting to import modules in the same directory, Scrapy terminal cannot find the module, despite syntax and autocomplete working fine in Python IDE. The most recent version of this issue was trying to import Items from the _items.py_ module into _pipelines.py_

### Steps to Reproduce

1. Create Custom Items in items.py
2. Place import statement into pipelines.py
3. Attempt to run crawl command in Scrapy terminal

**Expected behavior:** Run as usual

**Actual behavior:** ModuleNotFoundError: No module named 'items'

**Reproduces how often:** Everytime

### Versions

Scrapy       : 2.11.0
lxml         : 4.9.3.0
libxml2      : 2.10.3
cssselect    : 1.2.0
parsel       : 1.8.1
w3lib        : 2.1.2
Twisted      : 23.8.0
Python       : 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)]
pyOpenSSL    : 23.2.0 (OpenSSL 3.1.3 19 Sep 2023)
cryptography : 41.0.4
Platform     : Windows-10-10.0.22621-SP0

### Additional context

![image](https://github.com/scrapy/scrapy/assets/5017236/1847649b-1b93-4754-9290-5ab0791b6bd6)

![image](https://github.com/scrapy/scrapy/assets/5017236/7a5bdd0a-a541-4366-add1-2e924e3f9b90)

Any additional information on how imports work in Scrapy versus regular python would be much appreciated. Importing in general has proven to be quite a headache, and I do not understand the root cause as to why importing modules does not work in Scrapy despite the IDE recognizing the import statements as valid.

**Comment by Gallaecio** [comment]
This is not a but, but an error in your code (you probably meant `from .items`).
