### ISSUE TITLE
Dropping is_botocore wasn't documented

### ISSUE THREAD

**Issue by wRAR** [scrapy/scrapy#6056]
`scrapy.utils.boto.is_botocore()` was dropped in #5719 but we forgot to mention it in 2.8.0 release notes, we should do that now.

**Comment by yash08123** [comment]
> `scrapy.utils.boto.is_botocore()` was dropped in #5719 but we forgot to mention it in 2.8.0 release notes, we should do that now.

Please let me know where I should specify the missing `scrapy.utils.boto.is_botocore()` function.

**Comment by wRAR** [comment]
@yash08123 https://docs.scrapy.org/en/latest/news.html#id13 which corresponds to https://github.com/scrapy/scrapy/blob/9bfe0def591a0707ad7b263c016a107cb6b6c430/docs/news.rst#L431
