### ISSUE TITLE
Specifies the path of the crawler file to run

### ISSUE THREAD

**Issue by PShiYou** [scrapy/scrapy#6065]
When I create multiple crawler files with the same name, I can specify the path？
I want to run  ./spriders/hao_kan_shi_pin/user_video.py
![11111](https://github.com/scrapy/scrapy/assets/118948488/ec99aff0-b6c8-41a1-87e2-06bfd56ca495)
![22222](https://github.com/scrapy/scrapy/assets/118948488/1aed9cba-a974-452c-9f43-af7823dd141c)

**Comment by Gallaecio** [comment]
See [`scrapy runspider`](https://docs.scrapy.org/en/latest/topics/commands.html#runspider). Also, in the future please [ask questions through our community channels](https://scrapy.org/community/).

**Comment by PShiYou** [comment]
I didn’t see how to run a specific spider in the Scrapy manual。

I encountered a problem while developing web crawlers with Scrapy. In my project, I have multiple spiders with the same name, but they are located in different directories. When I try to run a specific spider, Scrapy cannot determine which one to run because their names are the same.

I believe that if Scrapy could support running spiders by file path, this problem could be solved. In this way, even if there are multiple spiders with the same name, as long as they are located in different directories, we can run them separately.

I hope Scrapy could consider adding this feature. This would make Scrapy more flexible in handling large projects and better meet the needs of developers.

**Comment by Gallaecio** [comment]
> I believe that if Scrapy could support running spiders by file path, this problem could be solved.

Scrapy does support this, I told you how in my earlier comment.
