### ISSUE TITLE
Add JsonResponse

### ISSUE THREAD

**Issue by ma-pony** [scrapy/scrapy#6069]
## Summary

Adding a JsonResponse object

A one paragraph explanation of the function.

## Motivation
When I parse the response content, I want to be able to determine different processing logic based on the type of response, something like
```
if isinstance(response, JsonResponse):
    data = response.jmespath('object.[*]')
    ...
elif isinstance(response, TextResponse):
    data = response.xpath('//p')
    ...
else:
    ...

```

## Additional background
https://github.com/scrapy/scrapy/issues/2444
There has been a similar discussion before

**Comment by Gallaecio** [comment]
At the moment this can be done with what came out of https://github.com/scrapy/scrapy/issues/2444 for most (all?) scenarios. Something like:

```python
if isinstance(response, TextResponse):
    try:
        json = response.json()
    except ValueError:
        data = response.xpath('//p')
    else:
        data = response.jmespath('object.[*]')
else:
    ...
```

**Comment by ma-pony** [comment]
> At the moment this can be done with what came out of #2444 for most (all?) scenarios. Something like:
> 
> ```python
> if isinstance(response, TextResponse):
>     try:
>         response.json()
>     except ValueError:
>         data = response.xpath('//p')
>     else:
>         data = response.jmespath('object.[*]')
> else:
>     ...
> ```
> 
> There might be a cleaner approach calling `response.jmespath()` directly, though, and avoiding the `response.json()` call. Haven’t checked.

Personally, I find this approach more succinct and clearer than the above, can you share your thoughts on this?

```
if isinstance(response, JsonResponse):
    data = response.jmespath('object.[*]')
    ...
elif isinstance(response, TextResponse):
    data = response.xpath('//p')
    ...
else:
    ...

```
I'm willing to add MR to do this

**Comment by ma-pony** [comment]
```
from scrapy.core.downloader.handlers.http11 import ScrapyAgent
from scrapy.responsetypes import ResponseTypes as ScrapyResponseTypes
from scrapy.utils.python import to_unicode


class ResponseTypes(ScrapyResponseTypes):
    CLASSES = {
        "text/html": "scrapy.http.HtmlResponse",
        "application/atom+xml": "scrapy.http.XmlResponse",
        "application/rdf+xml": "scrapy.http.XmlResponse",
        "application/rss+xml": "scrapy.http.XmlResponse",
        "application/xhtml+xml": "scrapy.http.HtmlResponse",
        "application/vnd.wap.xhtml+xml": "scrapy.http.HtmlResponse",
        "application/xml": "scrapy.http.XmlResponse",
        "application/json": "spider_kit.response.response.JsonResponse",
        "application/x-json": "spider_kit.response.response.JsonResponse",
        "application/json-amazonui-streaming": "scrapy.http.TextResponse",
        "application/javascript": "scrapy.http.TextResponse",
        "application/x-javascript": "scrapy.http.TextResponse",
        "text/xml": "scrapy.http.XmlResponse",
        "text/*": "scrapy.http.TextResponse",
    }


responsetypes = ResponseTypes()


def monkey_patch_scrapy_agent():  # pragma: no cover
    """
    Modifying scrapy's Response generation logic
    Make application/json mimetype's response use JsonResponse
    :return:
    """

    def cb_bodydone(self, result, request, url):
        headers = self._headers_from_twisted_response(result["txresponse"])
        respcls = responsetypes.from_args(headers=headers, url=url, body=result["body"])
        try:
            version = result["txresponse"].version
            protocol = f"{to_unicode(version[0])}/{version[1]}.{version[2]}"
        except (AttributeError, TypeError, IndexError):
            protocol = None
        response = respcls(
            url=url,
            status=int(result["txresponse"].code),
            headers=headers,
            body=result["body"],
            flags=result["flags"],
            certificate=result["certificate"],
            ip_address=result["ip_address"],
            protocol=protocol,
        )
        if result.get("failure"):
            result["failure"].value.response = response
            return result["failure"]
        return response

    ScrapyAgent._cb_bodydone = cb_bodydone


monkey_patch_scrapy_agent()

```

Currently, I've implemented something similar with the mock patch code

**Comment by Gallaecio** [comment]
I am unsure if this change is worth applying, i.e. changing the whole response class to a new one that does not provide anything extra that is not already provided by `TextResponse`, other than the ability of checking the MIME type with `isinstance`.

If we went ahead, I wonder what would be expected of other types of document, like those that the MIME sniffing standard covers (see https://github.com/scrapy/xtractmime/blob/main/xtractmime/mimegroups.py).

By the way, linking as somewhat related: https://github.com/scrapy/scrapy/pull/5204

**Comment by jxlil** [comment]
IMHO I think that for the moment, `TextResponse` subclasses like `JsonResponse` could be added to cover all MIME types in [‎`ResponseTypes.CLASSES`](https://github.com/scrapy/scrapy/blob/master/scrapy/responsetypes.py#L16)

I think this because the project already uses `HtmlResponse` and `XmlResponse` which are also subclasses of `TextResponse` and do not add anything extra, other than the ability to check the MIME type with `isinstance`

**Comment by Gallaecio** [comment]
> `HtmlResponse` and `XmlResponse` [are] subclasses of `TextResponse` and do not add anything extra

That blew my mind, I always assumed they had some specific handling. And while there is some special handling for them in https://github.com/scrapy/scrapy/blob/b498f1376dd9928ea457a74f730f837e9e86039e/scrapy/selector/unified.py, I now think adding `JsonResponse` is coherent with the existing code base, specially with Parsel having JSON support now.
