### ISSUE TITLE
 Typos in practice.rst File

### ISSUE THREAD

**Issue by Parvezkhan0** [scrapy/scrapy#6070]
### Description

The provided documentation contains several typos and minor grammatical issues that could be improved for clarity and readability.

### Steps to Reproduce

1. Open the practices.rst file.
2. Locate the sections mentioned below.
3. Check for the specified typos.

**Expected behavior:** Clear and error-free documentation.

**Actual behavior:** Typos and minor grammatical issues were found in the documentation.

**Reproduces how often:** N/A

### Additional context

The corrections have been outlined above for each identified issue. Applying these corrections will enhance the overall quality of the documentation.

**Comment by ayrotideysarkar** [comment]
Is it open?  @Parvezkhan0  can you assign this to me?

**Comment by Omar8345** [comment]
Seems interesting, working on it.
