### ISSUE TITLE
(With 2-line reproducible sample) When getting inner html, it gives *all* html after it instead of inside it; bug happens for both `.xpath()` and `.css()`

### ISSUE THREAD

**Issue by fzyzcjy** [scrapy/scrapy#6095]
### Description

Hi thanks for the lib! However, When getting inner html, it gives *all* html after it instead of inside it.

### Steps to Reproduce

```
selector = Selector(text='<html><body><div><a>Apple</a><a>Orange</a></div><span>Banana</span></body></html>')
print(selector.xpath('//div/node()').get())

# other attempts
print(selector.xpath('//div/node()').extract())
print(selector.css('div').get())
print(selector.css('div').extract())
```

**Expected behavior:** [What you expect to happen]

Output sth like

```
<a>Apple</a><a>Orange</a>
```

**Actual behavior:** [What actually happens]

```
<a>Apple</a><a>Orange</a></div><span>Banana</span></body></html>
```

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

2.11

### Additional context

Any additional information, configuration, data or output from commands that might be necessary to reproduce or understand the issue. Please try not to include screenshots of code or the command line, paste the contents as text instead. You can use [GitHub Flavored Markdown](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) to make the text look better.

**Comment by wRAR** [comment]
If this is https://github.com/scrapy/parsel/issues/228 you should upgrade your libxml2. In any case, I cannot reproduce this.

**Comment by fzyzcjy** [comment]
Thank you!
