### ISSUE TITLE
Remove deprecated support from scrapy.utils.log.logformatter_adapter()

### ISSUE THREAD

**Issue by wRAR** [scrapy/scrapy#6109]
This helper was added in 1.0.0 (I think), it looks like the parts of it that don't show warnings are still useful, though I haven't looked closely at them.

**Comment by rishabhRsinghvi** [comment]
@wRAR can you please assign this to me..?

**Comment by wRAR** [comment]
@rishabhRsinghvi you don't need to be assigned to work on something, but also this issue already has a PR.

**Comment by rishabhRsinghvi** [comment]
@wRAR oh my bad
