### ISSUE TITLE
Prioritize hcf backend links

### ISSUE THREAD

**Issue by Nishant-Bansal-777** [scrapy/scrapy#6138]
I am using hcf-backend and scrapy frontera to store urls to frontier. I am trying to set priority in spider requests, with priority=10 for some url's. But frontier does not seem to obey this rule, rather it is doing FIFO order. Please suggest how to use priority along with hcf-backend.

**Comment by Gallaecio** [comment]
Are you using https://github.com/scrapinghub/scrapy-frontera?

**Comment by Nishant-Bansal-777** [comment]
Yes, scrapy-frontera and hcf-backend ->https://github.com/scrapinghub/hcf-backend

**Comment by Gallaecio** [comment]
I’ve just created https://github.com/scrapinghub/scrapy-frontera/issues/11 to track this improvement.
