### ISSUE TITLE
There are some requests in Scrapy's downloader.active that have not been released.

### ISSUE THREAD

**Issue by Yoshiya1997** [scrapy/scrapy#6139]
When I'm using Scrapy + Scrapy-playwright, I found that when requesting some pages, the pages are not processed, and the request in Scrapy's downloader.active is not released all the time, which prevents the triggering of signals.spider_idle. What could possibly cause this issue?

**Comment by Gallaecio** [comment]
Not sure, but the first steps are to provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). And if it uses scrapy-playwright, then report the issue there, not here.
