### ISSUE TITLE
Empty ItemLoader get_output_value() when instantiated with an item

### ISSUE THREAD

**Issue by sardok** [scrapy/scrapy#614]
Hi, following code snippet does not work as i expected:

``` python
In [2]: from scrapy.contrib.loader import ItemLoader

In [3]: 

In [3]: from scrapy.item import Item, Field

In [4]: 

In [4]: class Product(Item):
   ...:         name = Field()
   ...:         comment = Field()
   ...:     

In [5]: p = Product({'name': 'xx1', 'comment': 'hi!'})

In [6]: p
Out[6]: {'comment': 'hi!', 'name': 'xx1'}

In [7]: l = ItemLoader(item=p)

In [8]: l.get_output_value('name')
Out[8]: []

In [9]: l.context
Out[9]: {'item': {'comment': 'hi!', 'name': 'xx1'}, 'response': None, 'selector': None}
```

I would expect to see a result of 'xx1' from get_output_value() function intuitively. Am i right about my expectation here?

Regarding the code at item loader (https://github.com/scrapy/scrapy/blob/master/scrapy/contrib/loader/__init__.py#L88), is it correct to check the 'context' or 'item' of the loader if relevant field_name is not available in the loader?

**Comment by redapple** [comment]
Do we want to improve this behavior?
Or is it a matter of making the documentation explicit about this?
I'm not an item loader user myself so I don't have an opinion on this one.

/cc @kmike , @eliasdorneles , @pawelmhm
