### ISSUE TITLE
Parse function doesn't support other functions inside it

### ISSUE THREAD

**Issue by ORENYT** [scrapy/scrapy#6146]
### Description

Parse function should call other functions

### Steps to Reproduce

1. Create parse function with function inside it:
```
def parse(self, response, **kwargs):
        self.log("Parsing...")
        self._parse_page(response)
        self.log("End parsing...")
 ```

2 Add any behavior in that function:
```    
def _parse_page(self, response):
        self.log("Page opened...")
        ...
```
3 Run spider. Received log:
```
2023-11-14 15:40:40 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://books.toscrape.com/> (referer: None)
2023-11-14 15:40:40 [books_catalogue] DEBUG: Parsing...
2023-11-14 15:40:40 [books_catalogue] DEBUG: End parsing...
2023-11-14 15:40:40 [scrapy.core.engine] INFO: Closing spider (finished)
```

**Expected behavior:** Function will be called, DEBUG "Page opened..." will be written.

**Actual behavior:** Function ignored, spider closed.

**Reproduces how often:** Always

### Versions

2.11.0 (actual)

**Comment by Gallaecio** [comment]
I suspect this is an issue on your end.

Could you provide the entire spider code, and make sure that the issue is reproducible in a brand-new Scrapy project created with `scrapy startproject`, running the spider with `scrapy runspider <path to file>`?

**Comment by ORENYT** [comment]
@Gallaecio 
Whole code: 
`import scrapy


class QuotesSpider(scrapy.Spider):
    name = "books_catalogue"
    start_urls = [
        "https://books.toscrape.com/",
    ]

    def parse(self, response, **kwargs):
        self.log("Parsing...")
        self._parse_page(response)
        self.log("End parsing...")

    def _parse_page(self, response):
        self.log("Page opened...")
        filename = "books.jl"
        for book in response.xpath("//article[@class='product_pod']"):
            yield {
                "title": book.xpath(".//h3/a/@title").get(),
            }
        with open(filename, "wb") as f:
            f.write(response.body)
        self.log(f"Parsed page in {filename}")
`

If you will replace self._parse_page(response) with function code, it will work:
`class QuotesSpider(scrapy.Spider):
    name = "books_catalogue"
    start_urls = [
        "https://books.toscrape.com/",
    ]

    def parse(self, response, **kwargs):
        self.log("Parsing...")
        self.log("Page opened...")
        filename = "books.jl"
        for book in response.xpath("//article[@class='product_pod']"):
            yield {
                "title": book.xpath(".//h3/a/@title").get(),
            }
        with open(filename, "wb") as f:
            f.write(response.body)
        self.log(f"Parsed page in {filename}")
        self.log("End parsing...")
`

**Comment by Gallaecio** [comment]
```python
from scrapy import Spider


class TestSpider(Spider):
    name = "test"
    start_urls = ["data:,"]

    def parse(self, response, **kwargs):
        self.log("Outer start")
        self._inner(response)
        self.log("Outer end")

    def _inner(self, response):
        self.log("Inner")
```

```
2023-11-14 14:44:12 [scrapy.core.engine] DEBUG: Crawled (200) <GET data:,> (referer: None)
2023-11-14 14:44:13 [test] DEBUG: Outer start
2023-11-14 14:44:13 [test] DEBUG: Inner
2023-11-14 14:44:13 [test] DEBUG: Outer end
2023-11-14 14:44:13 [scrapy.core.engine] INFO: Closing spider (finished)
```
