### ISSUE TITLE
CI tests broken due to `sybil==6.0.0` release

### ISSUE THREAD

**Issue by BurnzZ** [scrapy/scrapy#6152]
I noticed this when the PR https://github.com/scrapy/scrapy/pull/6151 has failed checks. Turns out `sybil==6.0.0` was released on Nov 21, 2023: https://github.com/simplistix/sybil/blob/master/CHANGELOG.rst#600-21-nov-2023.

The other latest PRs with passing checks are using `sybil==5.0.3`.

**Comment by wRAR** [comment]
Works again with 6.0.1.
