### ISSUE TITLE
Best Practices for Utilizing Built-in Scrapy Store Classes in Custom Extensions

### ISSUE THREAD

**Issue by atc-artur** [scrapy/scrapy#6161]
Hello,

I'm currently developing a custom extension for Scrapy to manage metadata files. The goal is to upload these files to AWS S3 upon scraping a certain number of items. I prefer not to use boto3 directly and instead want to leverage Scrapy's built-in capabilities.

I've noticed that the FilesPipeline class handles this functionality:
```
class FilesPipeline(MediaPipeline):
    ...
    STORE_SCHEMES = {
        "": FSFilesStore,
        "file": FSFilesStore,
        "s3": S3FilesStore,
        "gs": GCSFilesStore,
        "ftp": FTPFilesStore,
    }
    ...
    def __init__(self, store_uri, ...):
        self.store = self._get_store(store_uri)
    ...
```
In my extension, I'm trying to figure out the best way to initialize self.store for S3 file storage. Here's a simplified version of my extension:
```
class MyExt:
    def __init__(self):
        ...
        self.store = ?

    @classmethod
    def from_crawler(cls, crawler):
        # Setup logic

    def item_scrapped(self):
        # Metadata file logic
        self.store.persist_file(...)
```

Could you please advise on the following points:

1. Is there a recommended API or method in Scrapy for initializing self.store in a custom extension like this (we have local fs and prod s3 mode)?
2. Should I implement custom code to detect the store type, similar to what is done in FilesPipeline?
3. Are there any best practices or alternative approaches you would recommend for achieving this functionality?

Any guidance or suggestions would be greatly appreciated.

Thank you!

**Comment by wRAR** [comment]
This is The Scrapy issue tracker, please use [suitable platforms](https://scrapy.org/community/) for discussions.

**Comment by Gallaecio** [comment]
@atc-artur When you use that category, the default issue description states:

> Thanks for taking an interest in Scrapy!
>
> The Scrapy GitHub issue tracker is not meant for questions or help. Please ask
for help in the [Scrapy community resources](https://scrapy.org/community/)
instead.
>
> The GitHub issue tracker's purpose is to deal with bug reports and feature
requests for the project itself.

We created the category to try to avoid some of these issues :)
