### ISSUE TITLE
Pipeline send request

### ISSUE THREAD

**Issue by zuozhehao** [scrapy/scrapy#6179]
I have a `PushPipeline`, and I want to POST to a remote backend after getting data. 
I tried using `scrapy.FormRequest`, but it's not working.
Currently, I'm using `requests.post`, but it executes synchronously, and the efficiency

**Comment by Gallaecio** [comment]
https://docs.scrapy.org/en/latest/topics/coroutines.html#general-usage has an example using treq.

Although if you don’t mind the request going through Scrapy itself, you can use `crawler.engine.download`, there’s an example in https://docs.scrapy.org/en/latest/topics/asyncio.html#awaiting-on-deferreds.

**Comment by zuozhehao** [comment]
@Gallaecio  Hi，use `scrapy.FormRequest` how to disable `DOWNLOAD_DELAY`

**Comment by wRAR** [comment]
@zuozhehao please don't use this issue tracker to ask questions, see https://scrapy.org/community/

**Comment by zuozhehao** [comment]
> @zuozhehao please don't use this issue tracker to ask questions, see https://scrapy.org/community/
@wRAR 
Pipeline is the processing of result data.
I have searched for similar issues in the community and search engines.
I have also tried reading the source code, `Scrapy.FormRequest` cannot be disable `DOWNLOAD_DELAY`

**Comment by Gallaecio** [comment]
When you don’t find an answer, your next step should be asking, e.g. in Scrapy’s Discord.
