### ISSUE TITLE
Unification of log types

### ISSUE THREAD

**Issue by zuozhehao** [scrapy/scrapy#6180]
- [scrapy.utils.log] INFO: Versions
- [scrapy.addons] INFO: Enabled addons:
- [scrapy.middleware] INFO: Enabled extensions:
- [scrapy.crawler] INFO: Overridden settings:
- [scrapy.middleware] INFO: Enabled downloader middlewares:
- [scrapy.middleware] INFO: Enabled spider middlewares:
- [scrapy.middleware] INFO: Enabled item pipelines:
- [scrapy.statscollectors] INFO: Dumping Scrapy stats:

Can the logs in the framework be modified from `INFO ` to `DEBUG`.
The production environment does not require so much log information, as there are many duplicate log contents.

**Comment by wRAR** [comment]
This is not something we are going to do in Scrapy. You can try tuning the logging at your side.

**Comment by zuozhehao** [comment]
@wRAR 

> This is not something we are going to do in Scrapy. You can try tuning the logging at your side.

You are right. 
In the production environment, I need to use the info type to record some data, and I don't need the info type log in the Scrapy.
Because I am unable to use other types of logs.
