### ISSUE TITLE
`FEED_EXPORT_BATCH_ITEM_COUNT` not working

### ISSUE THREAD

**Issue by Mhassanniazi** [scrapy/scrapy#6185]
### Description

Scrapy setting `FEED_EXPORT_BATCH_ITEM_COUNT` not working when value is specified higher than the yielded items. For example: FEED_EXPORT_BATCH_ITEM_COUNT is 5 and scraped yielded items are 3, then this won't store scraped items on FEED_URI (specified file).  This means no file would get generate, instead it should consider this as a condition that if yielded items are < than specified batch it should dump yielded items.

### Steps to Reproduce

1. FEED_EXPORT_BATCH_ITEM_COUNT = 5, FEED_FORMAT = csv, FEED_URI = ***.csv
2. Total scraped items: 3
3. **BUG:** No file gets generate

**Expected behavior:** Even though records are lesser than `batch_count`, it should export items into a File.

**Actual behavior:** Even though records are lesser than `batch_count`, it should export items into a File.

**Reproduces how often:** Everytime

### Versions

2.11.0

**Comment by wRAR** [comment]
I can't repdoduce this.

**Comment by Mhassanniazi** [comment]
"FEED_FORMAT" : "csv",
"FEED_URI": "data/data_%(batch_time).csv",
"FEED_EXPORT_ENCODING" : "utf-8-sig",
"FEED_EXPORT_BATCH_ITEM_COUNT": 50000

Scrape output: 'item_scraped_count': 26243,
Now, the total scraped items are lesser than Chunk_size. this will not generate any File.

**Comment by wRAR** [comment]
Please provide a complete minimal reproducible example.
