### ISSUE TITLE
lxml parser gives back wrong parsing results, messes up html

### ISSUE THREAD

**Issue by tombohub** [scrapy/scrapy#6186]
### Description

parsing with lxml gives wrong result

### Steps to Reproduce

1. fetch this html code: https://pastebin.com/durYf56c

2. select section `section = response.css('main section section')[0]`

**Expected behavior:** [What you expect to happen]

section to be this:

https://pastebin.com/3wxdHFqY

**Actual behavior:** [What actually happens]

section is this:

https://pastebin.com/jzXZ0BRD

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

Scrapy       : 2.11.0
lxml         : 4.9.4.0
libxml2      : 2.10.3
cssselect    : 1.2.0
parsel       : 1.8.1
w3lib        : 2.1.2
Twisted      : 22.10.0
Python       : 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]
pyOpenSSL    : 23.3.0 (OpenSSL 3.1.4 24 Oct 2023)
cryptography : 41.0.7
Platform     : Windows-10-10.0.19045-SP0

### Additional context

Same error happens with Beautiful soup using `lxml` parser. Using regular `html.parser` there is no error.

So it must be lxml.

**Comment by wRAR** [comment]
> So it must be lxml.

Then you should report it to lxml.

**Comment by tombohub** [comment]
Ok, I tought you might wanna know since it's scrapy's core dependency. No need to be rude about it.

**Comment by wRAR** [comment]
Sorry but this is an issue tracker, not a place for asking questions. Please see https://scrapy.org/community for the latter.
