### ISSUE TITLE
Need support for making blank requests

### ISSUE THREAD

**Issue by wAnFen1017** [scrapy/scrapy#6203]
In some cases, I need to make a blank request in Scrapy, and its only purpose is to pass meta to the next callback function. Currently, my approach is to request an irrelevant website, such as http://httpbin.org/get. I know that setting up middleware can achieve getting a response without making an actual request, but I find that approach not elegant enough. I would like to ask if the author has any good ways to implement this, or if there is consideration for adding a blank request method in future versions? (Translated from ChatGPT)

**Comment by Laerte** [comment]
You can archieve that using data URI scheme:

```python
yield Request(
    url="data:,dummy",
    callback=self.your_call_back,
)
```

Logs:
```
2024-01-10 06:31:46 [scrapy.core.engine] DEBUG: Crawled (200) <POST data:,dummy> (referer: None)
(Pdb) response.text
dummy
```

Is this what you want?

**Comment by wAnFen1017** [comment]
> You can achieve that using [data URI scheme](https://en.wikipedia.org/wiki/Data_URI_scheme):
> 
> ```python
> yield Request(
>     url="data:,dummy",
>     callback=self.your_call_back,
> )
> ```
> 
> Logs:
> 
> ```
> 2024-01-10 06:31:46 [scrapy.core.engine] DEBUG: Crawled (200) <POST data:,dummy> (referer: None)
> (Pdb) response.text
> dummy
> ```

Thank you so much!   ٩('ω')و

**Comment by Gallaecio** [comment]
Let me reopen this for documentation purposes, I think we should cover this somewhere, maybe in the FAQ.

**Comment by kevintomsgithub** [comment]
Hi 👋🏻 I am pretty new to the codebase and would love to contribute. Thought of getting starting with something simple. Here is my PR #6208. Please let me know your thoughts.
