### ISSUE TITLE
Document the deprecation and removal of response_httprepr

### ISSUE THREAD

**Issue by Gallaecio** [scrapy/scrapy#6207]
https://github.com/scrapy/scrapy/pull/4972#discussion_r1454122081

**Comment by waconde** [comment]
So in the new version of Scrapy, what method can replace response_httprepr()? 
I did not find a corresponding replacement method in [https://docs.scrapy.org/en/latest](https://docs.scrapy.org/en/latest)？

**Comment by Gallaecio** [comment]
There is no replacement. Scrapy was using that function to measure response length, but now it uses an alternative approach (with better performance), so the function is no longer needed by Scrapy itself, and will eventually be removed without a replacement.

**Comment by waconde** [comment]
Oh, yes! I also need to calculate the length of the response as a reference for traffic consumption. Could you tell me if Scrapy currently employs a more efficient method for this? I would like to have a reference. 
Looking forward to your reply!

**Comment by waconde** [comment]
Or will future versions of Scrapy provide such a method as a generic utility class?

**Comment by Gallaecio** [comment]
There are no plans to provide a utility function for this, but you can see in https://github.com/scrapy/scrapy/pull/4972/files how we are doing the calculations now.

**Comment by waconde** [comment]
Good, I understand, just use the following code  `reslen = len(response.body) + get_header_size(response.headers) + get_status_size(response.status) + 4`.  Thank you so much!
