### ISSUE TITLE
When using mongodb MotorClient with scrapy, async with await will introduce Runtime error

### ISSUE THREAD

**Issue by keatonLiu** [scrapy/scrapy#6214]
### Description
This code will cause error:
```python
async with await self.client.start_session() as s:
    count = await self.collection.count_documents({"compName": compName}, limit=1, session=s)
    return count > 0
```

RuntimeError: Task <Task pending name='Task-2' coro=<<async_generator_asend without __name__>()> cb=[Deferred.fromFuture.<locals>.adapt() at E:\
PycharmProjects\xxxx\venv\lib\site-packages\twisted\internet\defer.py:1063]> got Future <Future pending cb=[_chain_future.<locals>._call_check_cancel() at E:\Program Files\Python310\lib\asyncio\futures.py:385]> attached to a different loop

### Versions

Scrapy       : 2.11.0
lxml         : 4.9.2.0
libxml2      : 2.9.12
cssselect    : 1.2.0
parsel       : 1.8.1
w3lib        : 2.1.1
Twisted      : 22.10.0
Python       : 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]
pyOpenSSL    : 23.1.1 (OpenSSL 3.1.0 14 Mar 2023)
cryptography : 40.0.2
Platform     : Windows-10-10.0.22631-SP0

**Comment by wRAR** [comment]
Please provide a complete minimal reproducible example.

**Comment by keatonLiu** [comment]
This is a reproduce example: 
```python
import scrapy
from motor.core import AgnosticCollection, AgnosticDatabase
from motor.motor_asyncio import (
    AsyncIOMotorClient as MotorClient,
)
from pymongo.errors import OperationFailure
from scrapy.settings import Settings
from scrapy.utils.project import get_project_settings


class QccSpiderBase(scrapy.Spider, metaclass=ABCMeta):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.settings: Settings = get_project_settings()

        self.client: MotorClient = MotorClient(self.settings['MONGO_URI'])
        self.db_name = self.settings['DB_NAME']
        self.db: Optional[AgnosticDatabase] = self.client[self.db_name]
        self.collection: Optional[AgnosticCollection] = self.db[self.collection_name]

    async def parse(self, response, **kwargs):
        async with await self.client.start_session() as s:
            count = await self.collection.count_documents({"compName": compName}, limit=1, session=s)
```

**Comment by Gallaecio** [comment]
Regarding the actual issue, does it work if you move the client creation to the parse method?

**Comment by keatonLiu** [comment]
It does not raise an error before I update my libraries including scrapy and motor to the latest, I don't know if it is a new feature in twisted. 
It looks like the error happens because motor client created a new asyncio loop other than using the loop used by the crawler's reactor. If I don't specifiy the io_loop paramter when initialize, it will create a new loop when first getting the loop. 
I've fixed it by moving the motor client initialization in parse(), and set the event loop to the current event loop used by scrapy's twisted reactor.

```python
    def setup_mongo_client(self):
        self.client = MotorClient(self.settings['MONGO_URI'], io_loop=get_event_loop())
        self.db = self.client[self.db_name]
        self.collection = self.db[self.collection_name]
       
        print(f"self.client.get_io_loop(): {self.client.io_loop}")
        print(f"get_event_loop(): {get_event_loop()}")
        reactor = sys.modules["twisted.internet.reactor"]
        print(f"twisted.internet.reactor: {reactor._asyncioEventloop}")

    def parse(self, response, **kwargs):
        self.setup_mongo_client()
```

**Comment by keatonLiu** [comment]
> Regarding the actual issue, does it work if you move the client creation to the parse method?

Yes, it is the solution, but I used to initialize it in __init__ and it always works fine

**Comment by wRAR** [comment]
> motor client created a new asyncio loop other than using the loop used by the crawler's reactor. If I don't specifiy the io_loop paramter when initialize, it will create a new loop when first getting the loop.

Makes sense.

**Comment by Gallaecio** [comment]
`parse` was just a suggestion for a quick test. The right approach would probably be to use the [engine_started](https://docs.scrapy.org/en/latest/topics/signals.html#std-signal-engine_started) signal.

**Comment by keatonLiu** [comment]
Let me correct it, motor client uses `motor.frameworks.asyncio.get_event_loop()` by default to get the current running loop or create a new loop when it does not exist. If I put the initialzation in __init__, the reactor haven't created a loop so it will create a new one. 

> It does not raise an error before I update my libraries including scrapy and motor to the latest, I don't know if it is a new feature in twisted. It looks like the error happens because motor client created a new asyncio loop other than using the loop used by the crawler's reactor. If I don't specifiy the io_loop paramter when initialize, it will create a new loop when first getting the loop. I've fixed it by moving the motor client initialization in parse(), and set the event loop to the current event loop used by scrapy's twisted reactor.
> 
> ```python
>     def setup_mongo_client(self):
>         self.client = MotorClient(self.settings['MONGO_URI'], io_loop=get_event_loop())
>         self.db = self.client[self.db_name]
>         self.collection = self.db[self.collection_name]
>        
>         print(f"self.client.get_io_loop(): {self.client.io_loop}")
>         print(f"get_event_loop(): {get_event_loop()}")
>         reactor = sys.modules["twisted.internet.reactor"]
>         print(f"twisted.internet.reactor: {reactor._asyncioEventloop}")
> 
>     def parse(self, response, **kwargs):
>         self.setup_mongo_client()
> ```

**Comment by keatonLiu** [comment]
But why is scrapy not using the current event loop when there already have one?
