### ISSUE TITLE
Document the SpiderState extension

### ISSUE THREAD

**Issue by wRAR** [scrapy/scrapy#6278]
`scrapy.extensions.spiderstate.SpiderState` is not on https://docs.scrapy.org/en/latest/topics/extensions.html and is only mentioned on https://docs.scrapy.org/en/latest/topics/jobs.html as "an extension" and "a built-in extension".

**Comment by jvrjsanchez** [comment]
Hey @wRAR, I'm looking for my first open source contribution, could I start working on this if no one has done so already?

**Comment by wRAR** [comment]
@jvrjsanchez sure, go ahead
