### ISSUE TITLE
ast.NameConstant is deprecated and will be removed in Python 3.14; use ast.Constant instead

### ISSUE THREAD

**Issue by wRAR** [scrapy/scrapy#6305]
```
scrapy/utils/misc.py:249: DeprecationWarning: ast.NameConstant is deprecated and will be removed in Python 3.14; use ast.Constant instead
    value is None or isinstance(value, ast.NameConstant) and value.value is None
```

Also, if I understand it correctly `isinstance(value, ast.NameConstant)` is always False, as `ast.NameConstant()` returns an `ast.Constant` instance, so I wonder if this case is covered by a test.

**Comment by lizdenhup** [comment]
Hello! I would like to contribute to this project. [Here](https://github.com/scrapy/scrapy/pull/6306) is my PR addressing this issue.

Please let me know if you have any questions, concerns or suggestions at your convenience. Thank you!

**Comment by ThunderMind2019** [comment]
Just to add yo your understanding
**isinstance(value, ast.NameConstant)**  returns True even if the value is from **ast.Constant** attaching SS below:

![image](https://github.com/user-attachments/assets/c93054ca-de07-44d6-a507-2c4022802d26)


Tests are already written in `scrapy/tests/test_utils_misc/test_return_with_argument_inside_generator.py`
Pushing and creating a new PR ...

**Comment by bhaveshsinghal95182** [comment]
is the issue resolved?

**Comment by wRAR** [comment]
@bhaveshsinghal95182 no, but it has a PR that is waiting for a review.
