### ISSUE TITLE
test_get_func_args() expectation changes in new Python point releases

### ISSUE THREAD

**Issue by wRAR** [scrapy/scrapy#6312]
See https://github.com/scrapy/itemloaders/issues/76

**Comment by kokobhara** [comment]
Hi @wRAR ,

I'm new to open-source and would love to work on this.
Can you point me to what needs to be done?

**Comment by Gallaecio** [comment]
There is a test [here](https://github.com/scrapy/scrapy/blob/1d11ea3a54607b436f9a88f07911902a4882f0e8/tests/test_utils_python.py#L201-L247) that it seems will start failing in newer versions of Python 3.11+. Specifically [this line](https://github.com/scrapy/scrapy/blob/1d11ea3a54607b436f9a88f07911902a4882f0e8/tests/test_utils_python.py#L243), from what @wRAR described on the linked issue.

@wRAR suggests changing the test expectations to be something like `self.assertIn(…, [[], ["obj"]]) (assuming `["obj"]` is the new expectation), i.e. assert that the result is either `[]` or `["obj"]`.

**Comment by kokobhara** [comment]
Does this include removing the conditional check (checking for CPython/PyPy) too? If yes, do we remove it entirely, or check only for PyPy?

**Comment by Gallaecio** [comment]
Assuming my guess is correct and the new expectation is `["obj"]` as in PyPy, then removing the platform checks altogether makes sense.

**Comment by Gallaecio** [comment]
One thing though: I would keep the URL of the Python issue, for future reference. Maybe just the URL, though, now that it has been fixed in newer versions.
