### ISSUE TITLE
Option to include all tags and attrs in LinkExtractor with specified exclusions

### ISSUE THREAD

**Issue by User087** [scrapy/scrapy#6321]
## Summary

Add the option to the LinkExtractor class to consider all tags and attributes (e.g. if you pass `None` then consider all tags/attributes), and `deny_tags` and `deny_attrs` arguments or similar so you can additionally consider all tags and attributes with the exception of those explicitly passed. 

## Motivation

It allows adopting a strategy of extracting all links by default and then specifically excluding the tags and attributes you don't want considered. Currently, it seems the user has to figure out all the specific tags and attributes where they're desired links appear and explicitly pass them to `tags` and `attrs` to have them considered.

## Describe alternatives you've considered

For including all tags, you could use the Selector class instead of LinkExtractor and select all e.g. `href` attributes regardless of which tag they appear in, e.g. `response.xpath('//@href')`. Using Selector results in losing the various convenient arguments in LinkExtractor and requires manually processing them with regex etc instead, and it requires manually converting relative links into absolute links when you want to use regexes that match the entire URL whereas LinkExtractor already handles that automatically.

## Additional context

Any additional information about the feature request here.

**Comment by PJ1256** [comment]
I would like to try and work on this if that's ok.

**Comment by MLManish** [comment]
I am trying to solve this issue.

**Comment by parthvichare** [comment]
I'm trying to solve this one

**Comment by Noman654** [comment]
@Laerte, I'd like to tackle this issue! As it's my first contribution to the project, any pointers to get me started would be much appreciated.

**Comment by Laerte** [comment]
Hi @Noman654  seems that we already have a open PR for it: 
- #6327

**Comment by ShubhGohil** [comment]
Hi, I had a question and suggestion about this enhancement. 

**Question:**
Wouldn't making the LinkExtractor extract all the tags and attributes as its default behaviour, and at the same time having the options to select and omit specific tags and attributes make it a bit complex?

**Suggestion:**
```Rather can we have separate classes for specific jobs.```

1. One class extracts all the links and attributes as its default behavior and gives the option to filter out the tags and attributes not required.
2. Other class which accepts a list of tags and attributes to be extracted.

Please let me know your thoughts on this. Or the thought process behind having all the options in a single class.


@Gallaecio , the idea to keep a boolean ```reverse_filter```  would increase the conditional statements in the class but can be implemented.

**Comment by Gallaecio** [comment]
I think the argument for complexity has merit, but I don’t think a class parallel to `LinkExtractor` would be the way to keep complexity manageable. Maybe we could create a `LinkExtractorFilter` class, allow passing as instance of that as the value of the filter parameter, and move all filtering-related complexity to that class.

No strong opinion, though. As long as the user API is simple enough, I am open to any proposal.

**Comment by ShubhGohil** [comment]
Could you please expand on how the ```LinkExtractorFilter``` class would work?

If we do not wish to create two separate classes then we would have to include two extra parameters deny_tags and deny_attrs as mentioned originally in the issue.

We have different conditions while filtering,
1. if we want to include some tags and include some attributes. 
> The above condition is the current default behaviour

2. if we want to extract all the tags and all the attributes
3. if we want to exclude some tags and exclude some attribute.
> The above two conditions can be infused by introducing a boolean filter parameter. Condition 2 would become the default behaviour in this case


4. if we want to include some tags and exclude some attributes from within those elements
5. if we want to exclude some tags and include some attributes from the elements extracted
> The above two conditions would need the use of two different parameters deny_tags and deny_attrs

**Just trying to break down the problem and make it easier to navigate.**

**Comment by Gallaecio** [comment]
> Could you please expand on how the `LinkExtractorFilter` class would work?

I’m not sure. I just think there must be an alternative to having 2 separate link extractor classes based on whether the filtering is inclusive or exclusive.

> if we want to include some tags and exclude some attributes from within those elements
> if we want to exclude some tags and include some attributes from the elements extracted

That makes sense. But if we want maximum flexibility, we also need the ability to allow/deny specific combinations of tags / attributes. And it complicates things, with no real-life use case to justify that complexity.

But I feel like I am rambling now. I have no concrete idea of how to best address the issue, to be honest. I’m more than happy to review any PR for it, though.

**Comment by jith912** [comment]
@Gallaecio Can you please help to take a look at the PR https://github.com/scrapy/scrapy/pull/6457, which addresses the issue. Appreciate your inputs

**Comment by AyuK03** [comment]
I’d love to take on this issue! Since this is my first contribution to the project, any guidance on getting started would be greatly appreciated. Looking forward to contributing!

**Comment by Gallaecio** [comment]
@AyuK03 There’s already https://github.com/scrapy/scrapy/pull/6457, but feel free to have a look at it and provide any feedback you might have.

**Comment by feroparea** [comment]
Hi,  
I would like to work on this issue as part of my university open-source project.  
Could you please assign it to me? 😊  
Thank you!

**Comment by Gallaecio** [comment]
We don’t usually assign tickets, but please feel free to open a PR to address this.

**Comment by kunigori** [comment]
Hello maintainers and fellow contributors,

I hope you're all doing well.

I'm a Japanese speaker so I use AI translation. Sorry if my English is weird and hard to read.

I've been following the discussion around Issue #6321 with great interest. The goal of making `LinkExtractor` more flexible by considering all tags and attributes and allowing for exclusions is a very valuable enhancement for Scrapy users. I've carefully reviewed the existing comments and the proposed solutions in pull requests #6428 and #6457. I understand that the community is exploring different approaches to best implement this feature, balancing power and ease of use. The discussions regarding parameter naming and the structure for defining inclusion/exclusion rules have been particularly insightful.

Building upon the need expressed in this issue and considering the existing `LinkExtractor` API, I'd like to propose an approach that extends the current `tags` and `attrs` parameters and introduces explicit exclusion parameters.

My idea is as follows:

1. Allow `'*'` as a value for the `tags` parameter to indicate that all HTML tags should be considered.

2. Allow `'*'` as a value for the `attrs` parameter to indicate that all attributes on the selected tags should be considered for link extraction (relying on `process_value` for validation).

3. Introduce a new optional parameter `exclude_tags` which takes a list of tag names to exclude even if they are included by `tags` or `tags='*'`.

4. Introduce a new optional parameter `exclude_attrs` which takes a dictionary where keys are tag names (or `'*'`) and values are lists of attribute names to exclude for those specific tags (or all tags if using `'*'`).

This approach integrates the new functionality with the existing parameters. The inclusion is handled by `tags` and `attrs` (with `'*'` enabling the "all" mode), and exclusion is handled by the new `exclude_tags` and `exclude_attrs` parameters, providing a clear filtering layer.

Here are a few examples using this proposed API:

- **Extract links from all tags using the `href` attribute, excluding links from `<img>` tags:**
`LinkExtractor(tags='*', attrs=['href'], exclude_tags=['img'])`
- **Extract links from all tags using any attribute, excluding attributes named `data-no-link` on any tag:**
`LinkExtractor(tags='*', attrs='*', exclude_attrs={'*': ['data-no-link']})`
- **Extract links from `<a>` and `<div>` tags using the `href` or `src` attributes, but exclude `<a>` tags with a `nofollow` attribute:**
`LinkExtractor(tags=['a', 'div'], attrs=['href', 'src'], exclude_attrs={'a': ['nofollow']})`

I believe this structure provides a clear, flexible, and reasonably intuitive way to define complex inclusion and exclusion rules while staying consistent with the existing `LinkExtractor` design. It allows users to leverage the "all" mode easily and provides granular control over exclusions.

I am very interested in contributing to the implementation of this feature and would appreciate any feedback on this approach. I am also happy to collaborate on existing PRs (#6428, #6457) or refine this idea further based on community input. My goal is to help develop a robust and user-friendly solution for Scrapy.

Thank you very much for considering my suggestion, and I look forward to contributing to this valuable project.

**Comment by kunigori** [comment]
🐛 Bug Description
When using response.follow(), the original meta dict is not automatically merged into the new Request. As a result, child callbacks cannot access any values set in response.meta.

🔄 Reproduction Steps
```python
import scrapy

class SampleSpider(scrapy.Spider):
    name = "sample"
    start_urls = ["https://example.com"]

    def parse(self, response):
        # Setting meta here…
        yield scrapy.Request(
            url="https://example.com/next",
            callback=self.parse_next,
            meta={"foo": "bar"}    # ← This key is not passed along
        )

    def parse_next(self, response):
        # Expected: response.meta["foo"] == "bar"
        # Actual: KeyError: 'foo'
        ...
```

✅ Expected Behavior
- response.meta["foo"] should equal "bar" in parse_next.

- Either:
1. response.follow() (and scrapy.Request) should automatically merge response.meta into the new Request’s meta, or
2. The documentation should clearly state that child requests do not inherit meta.

❌ Actual Behavior
- response.meta in parse_next is an empty dict by default.
- Existing code must manually merge the dict every time.

💡 Workaround
```python
def parse(self, response):
    yield response.follow(
        url="https://example.com/next",
        callback=self.parse_next,
        # Manually merge parent meta into the new Request
        meta={**response.meta, "foo": "bar"}
    )
```

🙏 Proposal
- Solution A: Change response.follow() (and scrapy.Request) internals to merge response.meta by default.

- Solution B: Update the docs to explicitly warn that meta does not carry over, with an example of how to merge manually.

Thank you for considering this improvement! I’m happy to help test or review a patch if desired.

**Comment by wRAR** [comment]
@kunigori were you trying to report this separately or how is this related to this issue?

**Comment by Spoofkapoof** [comment]
Hi! I'd like to work on this issue. I've seen the existing PRs and would like to 
take a fresh approach. Could someone provide guidance on the preferred implementation direction? I'm thinking of adding deny_tags and deny_attrs parameters while keeping backward compatibility.
