### ISSUE TITLE
'json' selector type not documented

### ISSUE THREAD

**Issue by mohmad-null** [scrapy/scrapy#6328]
https://docs.scrapy.org/en/latest/topics/selectors.html

`type defines the selector type, it can be "html", "xml" or None (default).`

But my tests are now failing because it's returning `json` type for actual json docs now.

**Comment by kisharnath** [comment]
can I send PR for this

**Comment by GeorgeA92** [comment]
@mohmad-null 
> But my tests are now failing because it's returning json type for actual json docs now.

Can You provide a bit more detailed info about Your tests that failed?
Does it look like https://github.com/scrapy/scrapy/issues/5923 or https://github.com/scrapy/parsel/issues/275 ?

**Comment by mohmad-null** [comment]
> Can You provide a bit more detailed info about Your tests that failed?

The failing tests were specific to my code. Basically I expected one selector type and now get another one, so the code went down a different channel and I got a different result. Nothing scrapy related there.

**Comment by Gallaecio** [comment]
https://github.com/scrapy/scrapy/pull/6334#issuecomment-2149459052
