### ISSUE TITLE
Set METAREFRESH_IGNORE_TAGS to ["noscript"] by default

### ISSUE THREAD

**Issue by Gallaecio** [scrapy/scrapy#6342]
I was wrong in https://github.com/scrapy/scrapy/issues/3844. The default value should be `["noscript"]`, to deal with [antibot behaviors](https://github.com/scrapy/scrapy/commit/ec1ef0235f9deee0c263c9b31652d3e74a754acc).

Found by @mukthy.

**Comment by wRAR** [comment]
Should we cherry-pick this to 2.11?

**Comment by Gallaecio** [comment]
+0.5 from me. It is technically backward-incompatible, but it should be so for the better in all scenarios I can think of. And it is trivial to override if that’s not the case.
