### ISSUE TITLE
Make certain args of `ScrapyAgent` and `TunnelingAgent` required

### ISSUE THREAD

**Issue by wRAR** [scrapy/scrapy#6343]
`scrapy.core.downloader.handlers.http11.ScrapyAgent` and `scrapy.core.downloader.handlers.http11.TunnelingAgent` take some args (`contextFactory` in both and `crawler` in `ScrapyAgent`) that are currently declared optional but in fact need to be passed as the code assumes they aren't None. So ideally they should be declared as required (but that requires reordering args and/or making all args of those constructors keyword-only so there is no clear and simple fix).

**Comment by kumar-sanchay** [comment]
Creating PR for this
