### ISSUE TITLE
SCRAPER_SLOT_MAX_ACTIVE_SIZE - documentations

### ISSUE THREAD

**Issue by mohmad-null** [scrapy/scrapy#6345]
Trivial one:
SCRAPER_SLOT_MAX_ACTIVE_SIZE on https://docs.scrapy.org/en/latest/topics/settings.html is documented as:

```
Default: 5_000_000

Soft limit (in bytes) for response data being processed.
```
This confused me:
`5_000_000` is like no representation of a number I'm familiar with. It then goes on to say: `Soft limit (in bytes)` which to me implies the data type of the configuration is in bytes because the number is in a weird format.

Looking in the code, I see the number is an integer. I'd suggest changing it to a straight `5000000`.

**Comment by Gallaecio** [comment]
[It’s that way precisely to make it easier to read](https://peps.python.org/pep-0515/).
