### ISSUE TITLE
AttributeError: 'SelectReactor' object has no attribute '_handleSignals'

### ISSUE THREAD

**Issue by windY1Y** [scrapy/scrapy#6354]
### Description

When I was using Scrapy, I encountered a minor issue. However, I'm uncertain if it's significant enough to be considered as a bug that needs fixing.

I'm a programmer who usually uses Python 3.7.16. I'm new to Scrapy, so I naturally downloaded the latest versions of Twisted (23.8.0) and Scrapy (2.9.0) for Python 3.7. However, I was surprised to find that Scrapy didn't work.

![image](https://github.com/scrapy/scrapy/assets/152846349/e23b1250-df11-4dc1-8684-0bd2f3c6a767)

To solve it, I can either choose to upgrade Python to a version > 3.8 or downgrade Twisted to 22.10.0. Therefore, I'm unsure if this issue needs fixing. However, I really find it unreasonable that the latest versions of Twisted and Scrapy are incompatible with Python 3.7, which can be quite confusing to users, particularly newcomers like me.

It appears that my issue is akin to what was reported in Issue #6024. I've learned that in the newest version of Scrapy 2.11.1 coupled with Twisted 24.3.0, the problem has been addressed. However, this solution requires an upgrade to Python version >3.8.
For those of us using older versions of Python, specifically 3.7.16, it's not immediately clear whether upgrading Python is expected or whether compatibility for Python 3.7 will be addressed in future releases.

### Steps to Reproduce

use Twisted 23.8.0 and Scrapy 2.9.0 to scrapy anything

or just use Python3.7 and pip install the newest version of Twisted and Scrapy

**Expected behavior:** Successfully crawl

**Actual behavior:** Attribute Error

**Reproduces how often:** always

**Comment by wRAR** [comment]
> For those of us using older versions of Python, specifically 3.7.16, it's not immediately clear whether upgrading Python is expected

It is expected, in general, because 3.7 is EOL.

**Comment by Gallaecio** [comment]
For the record, newer versions of Scrapy [specify the Python version requirement in setup.py](https://github.com/scrapy/scrapy/blob/93f06285309bd46e96fd147bf41e564c94b5bf2b/setup.py#L73).
