### ISSUE TITLE
Remove top-level reactor imports from CrawlerProces/CrawlerRunner examples 

### ISSUE THREAD

**Issue by wRAR** [scrapy/scrapy#6361]
There are several code examples on https://docs.scrapy.org/en/latest/topics/practices.html that have a top-level `from twisted.internet import reactor`, which is problematic (breaks when the settings specify a non-default reactor) and needs to be fixed.

**Comment by Laerte** [comment]
For this we should check if we have `TWISTED_REACTOR` setting defined (`get_project_settings`) and if is we call `install_reactor` before importing reactor?

**Comment by wRAR** [comment]
I think it's enough to move the imports inside blocks so that they only run after the setting is applied (i.e. after `Crawler.crawl()`, so after `CrawlerRunner.crawl()`). The changed examples should be tested with a non-default reactor setting value in any case.

If/when that's not possible to do it makes sense to add `install_reactor()` to examples I think.

**Comment by Laerte** [comment]
@wRAR I was testing this and noticed that if we have `TWISTED_REACTOR` in `custom_settings` but we don't call `install_reactor` we always get:

```
Exception: The installed reactor (twisted.internet.selectreactor.SelectReactor) does not match the requested one (twisted.internet.asyncioreactor.AsyncioSelectorReactor)
```

When Scrapy runs `_apply_settings` method, because `init_reactor` is `False`.

https://github.com/scrapy/scrapy/blob/631fc65fadb874629787ae5f7fdd876b9ec96a29/scrapy/crawler.py#L119

Is this expected? I see `init_reactor` parameter https://github.com/scrapy/scrapy/blob/631fc65fadb874629787ae5f7fdd876b9ec96a29/scrapy/crawler.py#L79 but when we use `runner.crawl` theres no way to override this parameter, when is created:

https://github.com/scrapy/scrapy/blob/631fc65fadb874629787ae5f7fdd876b9ec96a29/scrapy/crawler.py#L330-L334

Here my snippet:

```python
from scrapy import Spider
from scrapy.http import Request
from scrapy.crawler import CrawlerRunner
from scrapy.utils.log import configure_logging
from scrapy.utils.project import get_project_settings


class MySpider1(Spider):
    name = "my_spider"

    custom_settings = {
        "TWISTED_REACTOR": "twisted.internet.asyncioreactor.AsyncioSelectorReactor"
    }

    def start_requests(self):
        yield Request(url="https://httpbin.org/anything")

    def parse(self, response):
        yield response.json()


class MySpider2(Spider):
    name = "my_spider2"

    custom_settings = {
        "TWISTED_REACTOR": "twisted.internet.asyncioreactor.AsyncioSelectorReactor"
    }

    def start_requests(self):
        yield Request(url="https://httpbin.org/anything")

    def parse(self, response):
        yield response.json()


configure_logging()
settings = get_project_settings()
runner = CrawlerRunner(settings)
# from scrapy.utils.reactor import install_reactor
# install_reactor("twisted.internet.asyncioreactor.AsyncioSelectorReactor")
runner.crawl(MySpider1)
runner.crawl(MySpider2)
from twisted.internet import reactor
d = runner.join()
d.addBoth(lambda _: reactor.stop())
reactor.run()
```

**Comment by wRAR** [comment]
`CrawlerRunner` indeed requires you to install (and start) the reactor in your code, so it makes sense that `CrawlerRunner` examples show installing a non-default reactor manually.

**Comment by Laerte** [comment]
> `CrawlerRunner` indeed requires you to install (and start) the reactor in your code, so it makes sense that `CrawlerRunner` examples show installing a non-default reactor manually.

Got it, thanks!
