### ISSUE TITLE
Error handling in contract parsing

### ISSUE THREAD

**Issue by wRAR** [scrapy/scrapy#6383]
We found that there is no proper handling for unmatched regexes in `‎scrapy.contracts.ContractsManager.extract_contracts()`, so e.g. calling `from_method()` on a method with `@ foo` in the docstring produces an unhandled exception. I think we should just skip lines that don't match.

**Comment by suvanbanerjee** [comment]
@wRAR May I work on this issue?

**Comment by wRAR** [comment]
Of course
