### ISSUE TITLE
Response.json() method not fully documented

### ISSUE THREAD

**Issue by mohmad-null** [scrapy/scrapy#6389]
2.11.1

A few things:

a) https://docs.scrapy.org/en/latest/topics/dynamic-content.html doesn't mention the new response.json() method.

b) When I use response.json() in my IDE (PyCharm), it doesn't recognise it:
`Unresolved Attribute reference "json" for class "Response":

```
def a_func(response: Response):
  x = response.json()
```

c) https://docs.scrapy.org/en/latest/_modules/scrapy/http/request/json_request.html doesn't use it

(Not an exhaustive list)

**Comment by wRAR** [comment]
> https://docs.scrapy.org/en/latest/topics/dynamic-content.html doesn't mention the new response.json() method.

Yeah, it makes sense to replace `json.loads(response.text)` with `response.json()` there. Not a big deal though.

> When I use response.json() in my IDE (PyCharm), it doesn't recognise it: `Unresolved Attribute reference "json" for class 
"Response":

Yes, only `TextResponse` has it, so your type hints are incorrect.

> https://docs.scrapy.org/en/latest/_modules/scrapy/http/request/json_request.html doesn't use it

That's a request class.

**Comment by mohmad-null** [comment]
> Yes, only TextResponse has it, so your type hints are incorrect.

Ahhh, makes sense. Thanks.
