### ISSUE TITLE
Custom Log Formatter doesn't override download_error method. 

### ISSUE THREAD

**Issue by koromkorom** [scrapy/scrapy#6390]
### Description

When I use [Custom Log Formats](https://docs.scrapy.org/en/latest/topics/logging.html#custom-log-formats) feature and try to change the `download_error` method, it has no effect on the output. 

### Steps to Reproduce

1. Make Copy Original Log Formatter from [here](https://docs.scrapy.org/en/latest/_modules/scrapy/logformatter.html#LogFormatter) as log_formatter.py
2. Rename and extend: `class CrawlLogFormatter(logformatter.LogFormatter)`
3. Add path to settings `"LOG_FORMATTER": "xxx.log_formatter.CrawlLogFormatter",`
4. Add "TEST" prefix for every MSG: 
```python 
SCRAPEDMSG = "TEST Scraped from %(src)s" + os.linesep + "%(item)s"
DROPPEDMSG = "TEST Dropped: %(exception)s" + os.linesep + "%(item)s"
CRAWLEDMSG = "TEST Crawled (%(status)s) %(request)s%(request_flags)s (referer: %(referer)s)%(response_flags)s"
ITEMERRORMSG = "TEST Error processing %(item)s"
SPIDERERRORMSG = "TEST Spider error processing %(request)s (referer: %(referer)s)"
DOWNLOADERRORMSG_SHORT = "TEST Error downloading %(request)s"
DOWNLOADERRORMSG_LONG = "TEST Error downloading %(request)s: %(errmsg)s"
```
5. Changing log level for scraped to info

**Expected behavior:** 
Scraped messages like this: 
`INFO::scrapy.core.scraper::140690672260928::TEST Scraped from `

And download errors like this: 
`ERROR::scrapy.downloadermiddlewares.robotstxt::140002815125312::TEST Error downloading ...: DNS lookup failed: no results for hostname lookup: `

**Actual behavior:**
Scraped messages like this: 
`INFO::scrapy.core.scraper::140690672260928::TEST Scraped from `

And download errors like this: 
`ERROR::scrapy.downloadermiddlewares.robotstxt::140002815125312::Error downloading ...: DNS lookup failed: no results for hostname lookup: `

So the TEST prefix is missing for download errors meaning the change has no effect. 

**Reproduces how often:**
Always

### Versions

```
/usr/local/lib/python3.9/site-packages/thefuzz/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
Scrapy       : 2.10.1
lxml         : 5.1.0.0
libxml2      : 2.12.3
cssselect    : 1.2.0
parsel       : 1.9.0
w3lib        : 2.1.2
Twisted      : 22.10.0
Python       : 3.9.17 (main, Jun 13 2023, 16:07:34) - [GCC 8.3.0]
pyOpenSSL    : 24.1.0 (OpenSSL 3.2.1 30 Jan 2024)
cryptography : 42.0.5
Platform     : Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.28
```

**Comment by wRAR** [comment]
Please provide a minimal reproducible example of the claim in the title instead of copying a whole module.

**Comment by koromkorom** [comment]
```python
from __future__ import annotations

import logging
import os
from typing import  Any, Dict, Optional, Union

from twisted.python.failure import Failure

from scrapy import Request, Spider
from scrapy.http import Response
from scrapy import logformatter


SCRAPEDMSG = "TEST Scraped from %(src)s" + os.linesep + "%(item)s"
DOWNLOADERRORMSG_SHORT = "TEST Error downloading %(request)s"
DOWNLOADERRORMSG_LONG = "TEST Error downloading %(request)s: %(errmsg)s"


class CrawlLogFormatter(logformatter.LogFormatter):
    def scraped(
        self, item: Any, response: Union[Response, Failure], spider: Spider
    ) -> dict:
        src: Any
        if isinstance(response, Failure):
            src = response.getErrorMessage()
        else:
            src = response
        return {
            "level": logging.INFO,
            "msg": SCRAPEDMSG,
            "args": {
                "src": src,
                "item": item,
            },
        }

    def download_error(
        self,
        failure: Failure,
        request: Request,
        spider: Spider,
        errmsg: Optional[str] = None,
    ) -> dict:
        args: Dict[str, Any] = {"request": request}
        if errmsg:
            msg = DOWNLOADERRORMSG_LONG
            args["errmsg"] = errmsg
        else:
            msg = DOWNLOADERRORMSG_SHORT
        return {
            "level": logging.ERROR,
            "msg": msg,
            "args": args,
        }

```

**Comment by wRAR** [comment]
Works for me.

> [scrapy.core.scraper] ERROR: TEST Error downloading

**Comment by koromkorom** [comment]
With the same version?

**Comment by wRAR** [comment]
With the latest version.

**Comment by koromkorom** [comment]
For me it is also not working with: 
```
Scrapy       : 2.11.2
lxml         : 5.1.0.0
libxml2      : 2.12.3
cssselect    : 1.2.0
parsel       : 1.9.0
w3lib        : 2.1.2
Twisted      : 22.10.0
Python       : 3.9.17 (main, Jun 13 2023, 16:07:34) - [GCC 8.3.0]
pyOpenSSL    : 24.1.0 (OpenSSL 3.2.1 30 Jan 2024)
cryptography : 42.0.5
Platform     : Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.28
```

**Comment by wRAR** [comment]
Try providing an actual complete minimal reproducible example then, making sure it's really complete and reproducible.

**Comment by koromkorom** [comment]
OK I will try but it will take some time. In the mean time can you maybe also publish your version --verbose? Just so I can try to do a quick check with those first.

**Comment by koromkorom** [comment]
OK here is my example: [https://github.com/koromkorom/quotesbot-issue-example](https://github.com/koromkorom/quotesbot-issue-example) Does not work with: 

```
Scrapy       : 2.11.2
lxml         : 5.2.2.0
libxml2      : 2.12.6
cssselect    : 1.2.0
parsel       : 1.9.1
w3lib        : 2.2.0
Twisted      : 24.3.0
Python       : 3.9.2 (default, Feb 28 2021, 17:03:44) - [GCC 10.2.1 20210110]
pyOpenSSL    : 24.1.0 (OpenSSL 3.2.2 4 Jun 2024)
cryptography : 42.0.8
Platform     : Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.31```

Same issue: 

`INFO: TEST Scraped from <200 http://quotes.toscrape.com/page/10/>`

but then:

`ERROR: Error downloading <GET http://quotes.toscrape.com/robots.txt>: DNS lookup failed: no results for hostname lookup: quotes.toscrape.com.`

**Comment by wRAR** [comment]
> ModuleNotFoundError: No module named 'quotesbot.logformatter'

It's really unfortunate that we need to go through this.

**Comment by koromkorom** [comment]
Sorry, the module is there now.

**Comment by wRAR** [comment]
It's really really unfortunate that you didn't produce what I asked initially. The problem you described (about the message from `scrapy.downloadermiddlewares.robotstxt`) has nothing to do with what you claimed.

**Comment by wRAR** [comment]
> Why is there no TEST prefix in the download errors in my example? 

Because `scrapy.downloadermiddlewares.robotstxt` uses its own message template.

If you tried to actually provide an actual reproducible example of your problem you would quickly find that "Custom Log Formatter doesn't override download_error method" is false.

**Comment by koromkorom** [comment]
OK I got it now but I disagree. I wouldn't have quickly found that my statement is false because I didn't know that something called log_formatter is not supposed to format all logs. This should at least be mentioned in the documentation. You on the other hand apparently knew that and could have told me right from the start instead of telling me constantly how unfortunate everything is I do. I think that might be the only thing here that actually is unfortunate.

**Comment by wRAR** [comment]
> You on the other hand apparently knew that 

No. If I understood the actual problem from the beginning I wouldn't spend time on it but I was misled by the initial "method isn't called" claim. And if I had a proper complete minimal reproducible example of the actual problem from the beginning I would find the reason much faster.

**Comment by koromkorom** [comment]
Yes but that was not your claim though, was it? It was that I would have quickly found something and that is just not true. But also I can understand why you wrote it. I am sure you can also understand why I made my initial claim. Claiming that overriding `scraped ` works and `download_error` doesn't was reasonable under the assumption that the `LogFormatter `covers all logs. 

Anyways, maybe for me and also for anyone else trying to get an answer here: Is there a way to also change the log formatting of the robotstxt middleware? Are there other modules that you know of producing logs that are not covered by the log `LogFormatter`?
