### ISSUE TITLE
Documentation - specify how to propose non programming and programming changes 

### ISSUE THREAD

**Issue by jtoallen** [scrapy/scrapy#6400]
## Summary

I want to suggest an additional section to the documentation that clearly explains how to propose a non-code related change.
This section will follow the guidelines outlined in the Contributing.rst file from another open source project, https://github.com/beetbox/beets

## Motivation

There are multiple types of contributions that the community can suggest including bug reports, feature requests, code improvements, security vulnerability reports, and documentation changes.

For the Scrapy.py project it was difficult to discern what process to follow to make a documentation improvement suggestion.

## Describe alternatives you've considered

I opened a blank issue.  That appears to be a vague path for a catch all, to ask questions, or propose an improvement that is not a bug, code feature, or security issue.  

## Additional context

If you want the community to use the "blank issue" on GitHub for documentation change suggestions, specify that in this guide. If not, then encourage the community to "Edit on GitHub". These two different options are listed below for you to pick how you prefer to receive suggestions.

(edited - changed name of file extension)
Modify the Contributing.md file with this:

Types of Contributions
We love to get your help, suggestions, and contributions. There are many ways to contribute to this project.

The first thing to do, regardless of how you'd like to contribute to the project, is to check out our Code of Conduct and to keep that in mind while interacting with other contributors and users.

Non-Programming
Improve the [documentation](https://beets.readthedocs.io/en/stable/). It’s incredibly easy to contribute here: just find a page you want to modify and by

option 1 opening a new issue on the Issues tab of the Github repo. Use the "blank issue" option for documentation change suggestions.

option 2 hit the “Edit on GitHub” button in the upper-right. You can automatically send us a pull request for your changes.]

Programming
As a programmer you have a ton of opportunities to help with Scrapy.py. like bug reports, feature requests, code improvements, and reporting security vulnerabilities.

**Comment by wRAR** [comment]
Duplicate of #6378
