### ISSUE TITLE
Documentation bug - IgnoreRequest Related Documentation

### ISSUE THREAD

**Issue by mohmad-null** [scrapy/scrapy#6405]
The documentation around IgnoreRequest seems to be incomplete:

* DOWNLOAD_MAXSIZE - https://docs.scrapy.org/en/latest/topics/settings.html?highlight=download_maxsize#download-maxsize - doesn't say that it returns an IgnoreRequest on Failure
* REDIRECT_MAX_TIMES - https://docs.scrapy.org/en/latest/topics/downloader-middleware.html#std-setting-REDIRECT_MAX_TIMES - explicitly says: "After this maximum, the request’s response is returned as is." - which is misleading - it returns an IgnoreRequest.

Looking through the scrapy code, I see there seem to be two other uses for IgnoreRequest in the core code:

* ROBOTSTXT_OBEY - doesn't say responses come back with IgnoreRequest. https://docs.scrapy.org/en/latest/topics/settings.html?highlight=download_maxsize#robotstxt-obey
* Something about caching. No idea if this is documented.

In fact, looking at both of those pages more broadly (settings and downloader middleware), neither explicitly says "you'll get a IgnoreRequest back for this".
As the Python ethos goes: Explicit is better than implicit. Especially for docs.

**Comment by mohmad-null** [comment]
> DOWNLOAD_MAXSIZE - https://docs.scrapy.org/en/latest/topics/settings.html?highlight=download_maxsize#download-maxsize - doesn't say that it returns an IgnoreRequest on Failure

**Comment by Shikharishere** [comment]
I can take up this one...

**Comment by siddharth-2002** [comment]
i would   be  intrested   to resolve  the  issue   if  possible   assign  it  to  me.

Regards

**Comment by Gallaecio** [comment]
We usually do not assign issues, anyone is free to open a PR.

**Comment by Gallaecio** [comment]
> The fact that IgnoreRequest is raised feels to me like an internal detail, only relevant for downloader middleware writers, not for any user. [I @ #6506](https://github.com/scrapy/scrapy/pull/6506/files#r1822520381)

So, as far as I am concerned, we need to fix the docs of `REDIRECT_MAX_TIMES`, nothing else.

@mohmad-null Do you disagree? If so, how does knowing how the underlying code implements the request ignoring help you as a user of the setting?

**Comment by Gallaecio** [comment]
Is your goal here to capture ignored requests?
