### ISSUE TITLE
how to install and use it do you have any demo video

### ISSUE THREAD

**Issue by neon-07** [scrapy/scrapy#6409]
Thanks for taking an interest in Scrapy!

The Scrapy GitHub issue tracker is not meant for questions or help. Please ask
for help in the [Scrapy community resources](https://scrapy.org/community/)
instead.

The GitHub issue tracker's purpose is to deal with bug reports and feature
requests for the project itself.

**Comment by Laerte** [comment]
https://docs.scrapy.org/en/latest/intro/install.html
