### ISSUE TITLE
LOG_LEVEL settings not work

### ISSUE THREAD

**Issue by czqqqaq** [scrapy/scrapy#6421]
### Description of the Issue
I've added `LOG_LEVEL = "INFO` to my settings.py file.
However, when I run `scrapy crawl spider`, the log still contains Debug level messages, and the log levels of other modules are also being altered.

### Analysis
I discovered that when Scrapy initializes the CrawlerProcess, it calls the configure_logging function in scrapy.utils.log, which sets the root logger's level to NOTSET. This causes all log levels (including Debug) to be processed.

### Expected Behavior
I would like to set Scrapy's log level to INFO without affecting the log levels of other modules.

### Current Behavior
Despite setting `LOG_LEVEL = "INFO"` or `LOG_ENABLED = False` in settings.py, the log still contains Debug level messages, and the log levels of other modules are being changed because the logging.root.level has been change to NOTSET.

**Comment by wRAR** [comment]
If you think there is some bug in Scrapy causing this problem for your code you need to provide a minimal reproducible example of it.

LOG_LEVEL in settings.py is obviously not broken for everyone.

**Comment by czqqqaq** [comment]
this is my spider, I found out is the `logging.basicConfig` makes the log level broken.
```
import json
import scrapy
import datetime
import logging 

logging.basicConfig(level="ERROR")
class RawItem(scrapy.Item):
    time = scrapy.Field()
    data = scrapy.Field()
    file_name = scrapy.Field()

class THSHotETFSpider(scrapy.Spider):
    name = "ths_hot_etf"
    url = "https://dq.10jqka.com.cn/fuyao/hot_list_data/out/hot_list/v1/etf"
    custom_settings = {"ITEM_PIPELINES": {"spider.pipelines.DynamicFilePipeline": 400}, "LOG_LEVEL": "ERROR"}

    def start_requests(self):
        yield scrapy.Request(self.url, callback=self.parse, meta={"file_name": self.name})

    def parse(self, response):
        data = json.loads(response.text)
        file_name = response.meta["file_name"]
        
        item = RawItem(
            time=datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            data=data["data"],
            file_name=file_name,
        )
        yield item
```

**Comment by wRAR** [comment]
This isn't minimal and isn't reproducible.

**Comment by czqqqaq** [comment]
sorry about that. this is the new code
```python
import scrapy
from scrapy.crawler import CrawlerProcess
import logging 

logging.basicConfig(level="ERROR")
class RawItem(scrapy.Item):
    data = scrapy.Field()

class TestSpider(scrapy.Spider):
    name = "test_spider"
    url = "https://example.com"
    custom_settings = {"LOG_LEVEL": "ERROR"}

    def start_requests(self):
        yield scrapy.Request(self.url, callback=self.parse)

    def parse(self, response): 
        item = RawItem(data="test_message")
        yield item
        
if __name__ == "__main__":
    process = CrawlerProcess()
    process.crawl(TestSpider)
    process.start()
```

**Comment by wRAR** [comment]
> Note that CrawlerProcess automatically calls configure_logging, so it is recommended to only use logging.basicConfig() together with CrawlerRunner.

https://docs.scrapy.org/en/latest/topics/logging.html
