### ISSUE TITLE
自定义睡眠会影响scrapy的callback

### ISSUE THREAD

**Issue by markadc** [scrapy/scrapy#6426]
def start_requests(self):
        while True:
            book_url = db.spop(key)
            if not book_url:
                print("{} | 没有等待爬取的URL了...".format(key))
                time.sleep(3)
                continue

            print('拿到任务 {}'.format(book_url))
            site_bid = book_url.strip().split('-')[-1]
            book_uid = "{}_{}".format(self.SITE_NAME, site_bid)
            yield Request(
                url=book_url, callback=self.parse_book,
                cb_kwargs={"book_uid": book_uid},
                priority=2,
                errback=self.errback,
                dont_filter=True
            )
  这样的话，我的callback永远都进不去了，但是scrapy之前的版本是可以这样写的

**Comment by Gallaecio** [comment]
> In this case, my callback will never be able to enter, but the previous version of scrapy can be written like this

I see nothing wrong with it, i.e. I expect that code to work.

If you believe there is a bug in Scrapy, please indicate in which Scrapy version it “used to work”, and provide a minimal reproducible example (e.g. one without `db` in it.

**Comment by markadc** [comment]
Dear author, please help me
# My question
Because I wrote `time.sleep(3)` in `start_requests`, assuming that the redis set has only one element, `db.pop(key)` receives a URL value, and the following code uses a yield request. Then, because the redis set has no value, I keep `time.sleep(3)` until a new URL value appears, and then issue a yield request. But the problem is that even though a request was issued, the callback would never go in. I wonder if it's because this `time.sleep(3)` blocked some of the scraping work, which resulted in only issuing tasks but unable to proceed with the specific callback


```python
db = Redis.from_url("redis://localhost:6379/0", decode_responses=True)
key = 'book_urls'


class ConsSpider(Spider):
    name = "cons"  

    def start_requests(self):
        while True:
            book_url = db.spop(key)
            if not book_url:
                print("{} | 没有等待爬取的URL了...".format(key))
                time.sleep(3)
                continue
            print('拿到任务 {}'.format(book_url))
            yield Request(
                url=book_url, callback=self.parse_book,
                errback=self.errback,
                dont_filter=True
            )

    def errback(self, f):
        print("~_~  ==>  {}".format(f.value))

    def parse_book(self, response):
        """解析书籍详情页"""
        print("parse_book")
        ...
```
# Scrapy version
![g0](https://github.com/scrapy/scrapy/assets/50281797/1e84f199-0996-4900-9404-486919adda98)
# Code output
![g1](https://github.com/scrapy/scrapy/assets/50281797/eccc626d-2556-4275-a504-1117d94c0a17)

**Comment by Gallaecio** [comment]
Oh, right, `sleep` will block Scrapy. I assume the code with `sleep` will behave the same in earlier versions of Scrapy.

While [there are future plans to improve `start_requests` for async use cases](https://github.com/scrapy/scrapy/issues/5627), which *might* make this use case easier, I believe the current approach to achieve what you want would be something like [this](https://stackoverflow.com/a/16971379/939364).
