### ISSUE TITLE
front end issue Unable to read the Scrapy shell Modal when hover

### ISSUE THREAD

**Issue by civdix** [scrapy/scrapy#6446]
[Description of the issue]
When I am hovering on Scrapy shell at [https://docs.scrapy.org/en/latest/intro/tutorial.html#extracting-data] the modal which appears is not A good User Experience as it overlaps laps to the screen and partial data get unserved to the reader 

### Steps to Reproduce

1. go to the link : https://docs.scrapy.org/en/latest/intro/tutorial.html#extracting-data
2. search for Scrapy Shell and hover on it
3.then you can see a modal with bad user experience

**Expected behaviour:**  There should be vertical scrolling or  the size of the modal should positioned well

**Actual behaviour:** Modal gets overlapped from the screen when hover and partial data of modal is not showing

**Reproduces how often:** anytime

### Additional context

https://github.com/user-attachments/assets/d578682f-858c-4403-8832-0a16ab027714

![Screenshot_2024-07-30_09_57_58](https://github.com/user-attachments/assets/9f1ea7d9-4623-4ae3-8f60-84ae73c0b192)

**Comment by Gallaecio** [comment]
Sounds like something to report in https://github.com/readthedocs/sphinx-hoverxref/issues

**Comment by siddharth-2002** [comment]
Hi  it   seems   an  intresting   issue   and   troublesome   one I  would  like   to  contribute    to  the   above  issue   ,if   possible   can  you  assign  the   above   issue  to  me.

Regards

**Comment by Gallaecio** [comment]
https://github.com/scrapy/scrapy/issues/6446#issuecomment-2257599940
