### ISSUE TITLE
Random hanging of Scrapy processes in the docker container.

### ISSUE THREAD

**Issue by M3dv3D3V** [scrapy/scrapy#6454]
Hello, we are running `Scrapy` version `2.11.2` inside a docker container and at a random moment the `Scrapy` process hanging. `Telnet` connection is also unavailable (when trying to connect, the terminal `Scrapy` and there is no suggestion to enter username).
I will be glad of any help 🙏

**Comment by Gallaecio** [comment]
This issue tracked is not the best for coding assistance, please see https://scrapy.org/community/
