### ISSUE TITLE
get_project_settings() is not working

### ISSUE THREAD

**Issue by lordsoffallen** [scrapy/scrapy#6459]
### Description

I am trying to add a scrapy to my existing project and initilized it somewhere under `src/somefiles/..` I have invoked the `scrapy startproject scraper src/my/custom/dir` So now I would like to use `CrawlerProcess` to invoke it. `get_project_settings()` don't read the `settings.py` file content. And for some reason it's very dependent on where I invoke the code. 

`scrapy.utils.conf.closest_scrapy_cfg()` method actually starts traversing the directory from `.` which is relative where the python is invoked. So in my case, i invoked it from a test file. An example of the directory is as follows:
```
src/
└── tmpproj/
    └── scraper/
        └── scraper.cfg

test/
└── scraper/
    └── test_scraper.py
```

With that in mind, that function never finds the `.cfg` file and therefore returns default values. 

### Steps to Reproduce

1. Create the folder structure above and try to invoke `CrawlerProcess` somewhere in the code. 

**Expected behavior:** 
I would expect scrapy to read the settings easily (I can also pass the path but current function don't allow that.)

**Actual behavior:** 
Scrapy returns default settings value

### Versions

Scrapy       : 2.11.2
lxml         : 5.2.2.0
libxml2      : 2.12.7
cssselect    : 1.2.0
parsel       : 1.9.1
w3lib        : 2.2.1
Twisted      : 24.3.0
Python       : 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:45:18) [GCC 12.3.0]
pyOpenSSL    : 24.2.1 (OpenSSL 3.3.1 4 Jun 2024)
cryptography : 43.0.0
Platform     : Linux-6.5.0-45-generic-x86_64-with-glibc2.35

**Comment by lordsoffallen** [comment]
Current workaround that I have found is this:

```
def get_crawler_process() -> CrawlerProcess:
    with patch('scrapy.utils.conf.closest_scrapy_cfg') as mocked:
        mocked.return_value = str(
            Path(__file__).parent.parent.parent.resolve().joinpath("scrapy.cfg")
        )
        return CrawlerProcess(settings=get_project_settings())
```

Basically I manually point to cfg file location and then configuration is being picked up afterwards.

**Comment by wRAR** [comment]
Are you trying to report a bug in Scrapy?

**Comment by lordsoffallen** [comment]
> Are you trying to report a bug in Scrapy?

Yes, I believe it is bug that `get_project_settings` don't return expected settings depending on which python file the process is invoked.

**Comment by wRAR** [comment]
Not 100% sure what do you mean by "python file there" but what do you think it's a bug here and why?

**Comment by lordsoffallen** [comment]
Okay so im running a function called `test_my_func` from my tests folder (structure can be seen above). I am invoking `CrawlerProcess` which requires `settings` to be passed. Scrapy provides a util function for this -> from scrapy.utils.project import get_project_settings.

get_project_settings() calls some other functions to correctly create settings object. However, there is an issue with some of the internal function here: https://github.com/scrapy/scrapy/blob/master/scrapy/utils/conf.py#L95

closest_scrapy_cfg() (linked above) is traversing the directory starting from `.` which is a relative path. Considering the folder structure I have shared above, this function can't find the scrapy.cfg because it's only going to upper directories so it tries to check folder `test/scraper/` first to see if there is a scrapy.cfg file. then if not check `tests/` and so on. Since the scrapy.cfg in my structure is under `src` folder it never finds it. This is why I shared the patched solution. User should be able to pass the directory to scrapy to avoid this as right now we can't do it.

I hope this clears it now

**Comment by wRAR** [comment]
> closest_scrapy_cfg() (linked above) is traversing the directory starting from . which is a relative path. Considering the folder structure I have shared above, this function can't find the scrapy.cfg because it's only going to upper directories 

Correct.

What do you consider a bug here?

**Comment by lordsoffallen** [comment]
> > closest_scrapy_cfg() (linked above) is traversing the directory starting from . which is a relative path. Considering the folder structure I have shared above, this function can't find the scrapy.cfg because it's only going to upper directories
> 
> Correct.
> 
> What do you consider a bug here?

Well, calling a function that invokes the crawling from somewhere else in python breaks the code. Are we expecting user to only do in certain directories? To me this is indeed bug. There should be a way for me to pass scrapy.cfg file path if the underlying code can't find its location properly. 

What I would expect is that the function that invokes scrapy should work wherever I invoke it.

**Comment by wRAR** [comment]
> Are we expecting user to only do in certain directories? 

Yes. When we talk about "running inside a project" we mean exactly this.

> What I would expect is that the function that invokes scrapy should work wherever I invoke it.

It works as documented, by finding the current project. If there is no current project it obviously can't find it.

> There should be a way for me to pass scrapy.cfg file path if the underlying code can't find its location properly.

"can't find its location properly" (together with some of the earlier comments and proposed "solution") sounds like you expect Scrapy to find some random scrapy.cfg in some unrelated directory. I don't think that's possible to implement.

As for passing it explicitly, you can try reimplementing `get_project_settings()` instead of calling it, but be prepared that some Scrapy code that calls e.g. `inside_project()` will assume there is no active project.

**Comment by sandorkazi** [comment]
I did this as a workaround to use the location I wanted to:

```python
def get_spider_loader() -> SpiderLoader:
    cwd = os.getcwd()
    os.chdir(loc)  # the location of the scrapy.cfg I wanted
    settings = project.get_project_settings()
    spider_loader = spiderloader.SpiderLoader.from_settings(settings)
    os.chdir(cwd)
    return spider_loader
```
