### ISSUE TITLE
Dropping Python 3.8 support

### ISSUE THREAD

**Issue by wRAR** [scrapy/scrapy#6466]
3.8 support ends on 31 Oct, so I'm thinking about changes we can do after that. Looks like they are mostly related to typing.

* Drop Reppy which doesn't support Python 3.9+: #5226
* Adopt [PEP-585](https://peps.python.org/pep-0585/): 
  * Switch e.g. `List[T]` to `list[T]`
  * Switch `typing.Foo` imports to `collections.abc.Foo` ones
  * Maybe remove `--keep-runtime-typing` from the `pyupgrade` args, but that also changes unions to the `|` syntax in files with `from __future__ import annotations` and we would want to add those to all files with unions to keep the style consistent
* Bump the target version for `pyupgrade`

I don't see `typing_extensions` imports that were added in 3.9 (most of them are 3.10).

It's possible to do the `--keep-runtime-typing` change in advance to reduce the diff.

**Comment by vsevolodbreus** [comment]
I am getting a lot of: "TypeError: 'type' object is not subscriptable" errors for python3.9 tests, which doesn't make sense, since type[type] (ex. list[str]) is valid syntax starting in Python 3.9
Thoughts or suggestions?
