### ISSUE TITLE
Allow passing parameters to signal receiver

### ISSUE THREAD

**Issue by genismoreno** [scrapy/scrapy#6481]
## Summary

Allow passing parameters to a signal receiver (when self is not available)

I.e.

```
crawler.signals.connect(receiver=cls.engine_stopped, signal=signals.engine_stopped, cb_kwargs={"lazy": True})

@classmethod
def engine_stopped(cls, lazy: bool) -> None:
    ...
```

## Motivation

Pass of parameters to the receiver method would allow more dependent logic/behavior in it

**Comment by Gallaecio** [comment]
You could always create a callable object instead, e.g.

```python
class EngineStopped:
     def __init__(self, lazy):
        self.lazy = lazy
    def __call__(self, *args, **kwargs):
        ...  # Use self.lazy

crawler.signals.connect(receiver=EngineStopped(lazy=True), signal=signals.engine_stopped)
```

**Comment by vishvjeet-thakur** [comment]
is this issue resolved or can I work on it?

**Comment by Gallaecio** [comment]
@genismoreno Feel free to reopen if you find a scenario where [the solution above](https://github.com/scrapy/scrapy/issues/6481#issuecomment-2376545617) is not good enough.

**Comment by genismoreno** [comment]
I think that with the solution @Gallaecio proposed should be enough. Thank you!!
