### ISSUE TITLE
Issue with Starting Scrapy Project - ImportError

### ISSUE THREAD

**Issue by joako233** [scrapy/scrapy#6482]
Hi everyone,

I'm having trouble creating a new Scrapy project in my virtual environment while using Visual Studio Code on Windows. When I run the command:

`scrapy startproject joaki`
I receive the following error trace:

```

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  ...
ImportError: PyO3 modules compiled for CPython 3.8 or older may only be initialized once per interpreter process
I am currently using Python 3.11.5, and it seems related to the PyO3 modules and compatibility.

```
Has anyone else encountered this issue? Any advice on how to resolve it would be greatly appreciated!

Thank you!

**Comment by wRAR** [comment]
This is a problem with one of the Scrapy dependencies, most likely `cryptography`, unrelated to Scrapy itself,
