### ISSUE TITLE
Ignore `SyntaxError` as well when `SPIDER_LOADER_WARN_ONLY` is set to `True`

### ISSUE THREAD

**Issue by mmoriniere** [scrapy/scrapy#6483]
## Summary

As explained in the title, the idea is to ignore `SyntaxError` as well when `SPIDER_LOADER_WARN_ONLY` is set to `True`.

## Motivation

The motivation for this is that an indentation error was left in a single spider file, after a manual edition of a spider directly in our production server on a friday evening. We only saw that this morning, and it therefore stopped all our spiders for the weekend. :see_no_evil: 

It would have eased our day if only that broken spider would have stopped running. 

## Describe alternatives you've considered

The main alternative is to double check what one does in production, and to pay more attention to the error-tracker. :wink:

## Additional context

I can submit a PR if this suggestion is deemed acceptable. I actually have a commit ready for it (with tests and docs up-to-date).

**Comment by Gallaecio** [comment]
> The main alternative is to double check what one does in production, and to pay more attention to the error-tracker. 😉

I am not against the proposed change, but it feels like using something like pre-commit with black, for example, would be a better way to avoid this issue.

**Comment by mmoriniere** [comment]
We actually use black in our project, so it should never happen, indeed.

However, i happened by mingling directly with our source code on our production server, so it did not go through our usual style-check phase in our CI pipeline.

This is a good example of bad-coding practice from our side. It usually does not have consequences. Here it just happened that un-commenting something to leave everything clean after a quick-and-dirty fix went wrong.
