### ISSUE TITLE
How to append a middleware in specific spider along with the ones set in settings.py

### ISSUE THREAD

**Issue by iamumairayub** [scrapy/scrapy#6496]
There are certain middlewares enabled for all spiders in settings.py

for one specific spider, how to append another middleware along with all the ones in settings.py?

Let say settings.py

    
    DOWNLOADER_MIDDLEWARES = {
        'myproject.middlewares.CustomDownloaderMiddleware1': 543,
        'myproject.middlewares.CustomDownloaderMiddleware2': 544,
    }

If I set that middleware via `custom_settings` in my spider, then all others set in settings.py are ignored.

I tried 

    class MySpider(Spider):
        name = 'my_spider'
    
        def __init__(self, *args, **kwargs):
            super(MySpider, self).__init__(*args, **kwargs)
            settings = get_project_settings()
    
            # Get existing middlewares
            middlewares = settings.get('DOWNLOADER_MIDDLEWARES', {})
            
            # Append or update your additional middleware
            middlewares['myproject.middlewares.MyAdditionalMiddleware'] = 550
    
            # Apply it to the spider's settings
            self.custom_settings = {
                'DOWNLOADER_MIDDLEWARES': middlewares
            }
    
        def start_requests(self):
            # Spider logic here
            pass

and

    from scrapy.spiders import Spider
    from scrapy.utils.project import get_project_settings
    
    class MySpider(Spider):
        name = 'my_spider'
    
        @classmethod
        def from_crawler(cls, crawler, *args, **kwargs):
            spider = super(MySpider, cls).from_crawler(crawler, *args, **kwargs)
    
            # Get the global settings
            settings = crawler.settings
    
            # Get the existing middlewares
            middlewares = settings.get('DOWNLOADER_MIDDLEWARES', {}).copy()
    
            # Append or update your additional middleware
            middlewares['myproject.middlewares.MyAdditionalMiddleware'] = 550
    
            # Update the spider's settings for this instance
            spider.custom_settings = {
                'DOWNLOADER_MIDDLEWARES': middlewares
            }
    
            return spider
    
        def start_requests(self):
            # Spider logic here
            pass

But the MyAdditionalMiddleware is not activated in my spider

### Note
Above codes were generated by ChatGpt https://chatgpt.com/share/6710b8b3-eda8-800a-a63d-5a244501475b

**Comment by Gallaecio** [comment]
https://docs.scrapy.org/en/2.11/topics/settings.html#settings-per-spider

**Comment by iamumairayub** [comment]
@Gallaecio I tried the `update_settings` and `from_crawler` but my custom middlewares from `settings.py` are no longer active

**Comment by Gallaecio** [comment]
You most likely overwrite the setting instead of editing its value. It sounds like an issue specific to your code rather than a Scrapy issue, so please use [Discord](https://discord.gg/mv3yErfpvq) to ask for help, and provide a minimum reproducible example using `update_settings`.

**Comment by iamumairayub** [comment]
```
settings.py

DOWNLOADER_MIDDLEWARES = {
    'news_spiders.middleware.CheckDuplicatesMiddleware': 100,
    'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware': 300,
    'news_spiders.middleware.RandomProxyMiddleware': 400,
    'scrapy.downloadermiddlewares.retry.RetryMiddleware': 500,
}
```

```
spiders/myspider.py

class CustomSpider(scrapy.Spider):
    name = 'test'

    @classmethod
    def update_settings(cls, settings):
        super().update_settings(settings)
        settings.set("DOWNLOADER_MIDDLEWARES", {'news_spiders.middleware.FlareSolverrRedirectMiddleware': 600}, 
                     priority="spider")
```

If I do this, then I `RandomProxyMiddleware` from `settings.py` somehow gets de-activated

```
Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'nknews_spiders.middleware.FlareSolverrRedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
```

**Comment by Gallaecio** [comment]
You are overwriting the setting. Please use Discord.
