### ISSUE TITLE
Deprecate `scrapy.twisted_version`

### ISSUE THREAD

**Issue by wRAR** [scrapy/scrapy#6509]
We define and even explicitly export `scrapy.twisted_version` for, as I can see, no good reason, as users should use `twisted.version` directly. We should deprecate (via, I assume, a module-level `__getattr__`) and eventually remove it.

**Comment by Rohitkr117** [comment]
I'd like to work on this issue. 
I propose adding a `__getattr__` method to handle access to `scrapy.twisted_version` and emit a DeprecationWarning advising users to switch to `twisted.version` directly. This will allow us to maintain backward compatibility for the time being while preparing for its eventual removal. I'll submit a PR soon. Let me know if that sounds good!

**Comment by wRAR** [comment]
Yeah, it sounds good.

**Comment by Laerte** [comment]
Sorry @Rohitkr117 I only saw your message after I already open a PR. 😅
