### ISSUE TITLE
Deprecate unused scrapy.utils code

### ISSUE THREAD

**Issue by wRAR** [scrapy/scrapy#6517]
As far as I can see the following functions and classes from `scrapy.utils` are not used anywhere (usually because the code using them is gone):

* `scrapy.utils.python.flatten()`
* `scrapy.utils.python.iflatten()`
* `scrapy.utils.python.equal_attributes()`
* `scrapy.utils.request.request_authenticate()`
* `scrapy.utils.serialize.ScrapyJSONDecoder`
* `scrapy.utils.test.assert_samelines()`

`flatten()` and `iflatten()` are also present in Parsel where they are used but I wouldn't recommend switching to those (and they are easy to reimplement anyway).

**Comment by Rohitkr117** [comment]
I'd be happy to work on this issue. I understand that the goal is to identify and remove the unused functions and classes listed above

I'll check for any remaining references across the repository to confirm that these are indeed unused and proceed with removing them.

Also, could you please let me know which specific tests I should run to verify everything is functioning correctly after these removals?

**Comment by wRAR** [comment]
> I understand that the goal is to identify and remove the unused functions and classes listed above

They are already identified and the goal is to deprecate them, not remove them.

**Comment by Rohitkr117** [comment]
Sorry for the confusion so i have to just implement warnings about the deprecation
