### ISSUE TITLE
Blockage in scrapy event loop when calling i/o blocked operations

### ISSUE THREAD

**Issue by waqas543** [scrapy/scrapy#6528]
Hello everyone,

I’m currently using Scrapy as a microservice within my scraping infrastructure, which is under heavy load. We have several algorithms to select proxies based on previous performance stats. To maintain these statistics, including proxies and user-agents, we need frequent communication with Redis. However, our cluster spans multiple nodes, and each Redis call blocks the Scrapy event loop until the operation completes. This has become a bottleneck, as we interact with Redis roughly four times per request. Additionally, responses are sent to a Redis queue where a parser collects and processes them.

Does anyone have suggestions on minimizing I/O blocking for the spider to improve performance?

**Comment by Gallaecio** [comment]
Sounds like you are using a blocking Redis client. Consider [enabling asyncio](https://docs.scrapy.org/en/2.11/topics/asyncio.html#installing-the-asyncio-reactor) and using and async Redis client, e.g. redis-py with its [asyncio API](https://redis.readthedocs.io/en/stable/examples/asyncio_examples.html).

**Comment by waqas543** [comment]
Thanks @Gallaecio For your quick response. 

I have tried that also but it was not running on scrapy's event loop. I need to run a separate event loop for redis which again blocks the scrapy's event loop. 
It will be very helpful for me if I get some help to run redis with scrapy's event loop.

**Comment by Gallaecio** [comment]
> it was not running on scrapy's event loop

Can you share the error you got? Did you [configure Scrapy to use the asyncio Twisted reactor](https://docs.scrapy.org/en/2.11/topics/asyncio.html#installing-the-asyncio-reactor)?

**Comment by waqas543** [comment]
Thanks @Gallaecio 🙏
. amazing i was missing to intialize twisted reactor. looking everythings works fine.
