### ISSUE TITLE
Contribution to Scrapy Project: Static Analysis Findings and Refactoring Proposal

### ISSUE THREAD

**Issue by Nicolas-Moliterno** [scrapy/scrapy#6535]
# Contribution to Scrapy Project: Static Analysis Findings and Refactoring Proposal

Hello,

I'm a master's student in Software Engineering, currently studying software best practices. As part of our project, we selected **Scrapy** to contribute to. After conducting a static analysis with **SonarQube**, we identified some improvement opportunities, as listed below:

## Filtered SonarQube Metrics for `MO827_scrapy` (scrapy/commands/)

| Issue Key | Rule | Severity | Component | Line | Message |
|-----------|------|----------|-----------|------|---------|
| **e422c893-9877-4d6e-be50-e7a9e423adfc** | `python:S1172` | MAJOR | `scrapy/commands/__init__.py` | 102 | Remove the unused function parameter `"args"`. |
| **36e79f4c-05dc-40e2-9745-b72cf729726a** | `python:S3776` | CRITICAL | `scrapy/commands/check.py` | 70 | Refactor this function to reduce its Cognitive Complexity from **20** to the **15** allowed. |
| **6f77faf2-e3b1-4795-abe2-aae4105cfded** | `python:S1172` | MAJOR | `scrapy/commands/genspider.py` | 126 | Remove the unused function parameter `"template_name"`. |
| **5a5d298a-b3f6-4e5a-870c-cbd7d1fe5217** | `python:S1192` | CRITICAL | `scrapy/commands/startproject.py` | 19 | Define a constant instead of duplicating this literal `"${project_name}"` **4 times**. |
| **5ea9c4a2-5ae5-4d3d-a0f5-6ba518e4ba3d** | `python:S1940` | MINOR | `scrapy/commands/parse.py` | 400 | Use the opposite operator (`"!="`) instead. |

## Proposal

We plan to open a **pull request** to:
1. Refactor the `run` function to reduce its cognitive complexity.
2. Address other identified issues in these files, where feasible.

Thank you for considering our contribution!

--- 
**Best Regards,**

**Comment by wRAR** [comment]
No idea about 2, but 1, 3 and likely 4 will be rejected.
