### ISSUE TITLE
Recommendation for docstring for functions and classes in the file exporters.py

### ISSUE THREAD

**Issue by dami1025** [scrapy/scrapy#6553]
### Description

The exporters.py file lacks consistent docstrings for its functions and classes. While some docstrings are present, many are either missing or incomplete. This inconsistency can make it challenging for developers, especially newcomers, to understand the purpose and usage of these components without delving deep into the implementation. This affects the maintainability and readability of the code.

### Steps to Reproduce

- Open the exporters.py file in the Scrapy codebase.
- Inspect the classes and functions, noting missing or incomplete docstrings.
- Compare this with the expectations outlined in Python's PEP 257 guidelines for docstrings.

**Expected behavior:** 
Each class should have a clear and concise docstring describing:
- The purpose of the class.
- An overview of its main methods and attributes.
Each function should have a docstring explaining:
- Its purpose.
- Input parameters, their types, and expected values.
- Return values and their types.
- Any side effects, exceptions raised, or special behaviors.

**Actual behavior:** 
Many classes and functions in exporters.py lack docstrings. Existing docstrings, where present, are inconsistent in detail and format.

**Reproduces how often:** 
100% of the time when inspecting exporters.py.
### Versions

Please paste here the output of executing `scrapy version --verbose` in the command line.

### Additional context

Any additional information, configuration, data or output from commands that might be necessary to reproduce or understand the issue. Please try not to include screenshots of code or the command line, paste the contents as text instead. You can use [GitHub Flavored Markdown](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) to make the text look better.

**Comment by Laerte** [comment]
I don't understand where all these issues regarding PEP 257 are coming from all of a sudden.

We have docstring for `BaseItemExporter` that is the base class for all exports and as far I can tell it provides the information necessary to understand how it works.

- https://docs.scrapy.org/en/latest/topics/exporters.html#baseitemexporter

**Comment by wRAR** [comment]
> I don't understand where all these issues regarding PEP 257 are coming from all of a sudden

Student assignments, most likely.
