### ISSUE TITLE
Scrapy v2.12.0 LinkExtractor Issue on Flutter Websites

### ISSUE THREAD

**Issue by ivan-sincek** [scrapy/scrapy#6563]
### Description

Hi team,

Scrapy v2.12.0 fails to extract links using `scrapy.linkextractors.LinkExtractor` on Flutter websites, while previous Scrapy v2.11.0 works just fine.

Looking forward to the fix!

### Steps to Reproduce

1. Install the following: `python -m pip install scrapy==2.12.0`

2. Run the following Python snippet:

```python
#!/usr/bin/env python3

import scrapy, scrapy.crawler, scrapy.utils.project

class MySpider(scrapy.Spider):
	def __init__(self):
		self.name            = "MySpider"
		self.start_urls      = ["https://www.omnichess.club", "https://readreviews.dev"]
		self.allowed_domains = []

	def start_requests(self):
		for url in self.start_urls:
			yield scrapy.Request(
				url      = url,
				callback = self.parse,
			)

	async def parse(self, response):
		for link in scrapy.linkextractors.LinkExtractor(
			tags  = ["a", "link", "script"],
			attrs = ["href", "src"]
		).extract_links(response):
			print(link.url)

class Runner:
	def run(self):
		settings = scrapy.utils.project.get_project_settings()
		settings["DEPTH_LIMIT"                         ] = 1
		settings["LOG_ENABLED"                         ] = False
		settings["REQUEST_FINGERPRINTER_IMPLEMENTATION"] = "2.7"
		scrapy_scraper_spider = scrapy.crawler.CrawlerProcess(settings)
		scrapy_scraper_spider.crawl(MySpider)
		scrapy_scraper_spider.start()

Runner().run()
```
3. You should get the following output:

```fundamental
https://www.omnichess.club/manifest.json
https://readreviews.dev/manifest.json
```

4. Install the following: `python -m pip install scrapy==2.11.0`

5. Run the above snippet again.

6. You should get the following output:

```fundamental
https://readreviews.dev/assets/packages/mixpanel_flutter/assets/mixpanel.js
https://analytics.eu.umami.is/script.js
https://readreviews.dev/manifest.json
https://readreviews.dev/flutter.js
https://static.cloudflareinsights.com/beacon.min.js
https://www.omnichess.club/manifest.json
https://www.omnichess.club/flutter_inappwebview_web_support.js
https://www.omnichess.club/flutter_bootstrap.js
```

**Expected behavior:** Extraction of more than just one link.

**Actual behavior:** Extracts only one link, and it is always `manifest.json`.

**Reproduces how often:** Constant.

### Versions

Issue on v2.12.0.

No issue on older v2.11.0.

### Additional context

I do not own the websites I tested this script against.

**Comment by wRAR** [comment]
Yes, we ignore `.js` by default now.

**Comment by Gallaecio** [comment]
You can set the `deny_extensions` parameter of [`LinkExtractor`](https://docs.scrapy.org/en/latest/topics/link-extractors.html#scrapy.linkextractors.lxmlhtml.LxmlLinkExtractor) to change that in your case. But it works as intended, we expect most users not to look for JavaScript files when using `LinkExtractor`.
