### ISSUE TITLE
Project Creation Doesn't work

### ISSUE THREAD

**Issue by wh1t3h47** [scrapy/scrapy#6569]
### Description

I cannot initialize a scrapy project

### Steps to Reproduce

```bash
python3 --version     
Python 3.9.1
uname -a             
Linux debian 6.6.15-amd64 #1 SMP PREEMPT_DYNAMIC Kali 6.6.15-2kali1 (2024-05-17) x86_64 GNU/Linux
pip3 --version                  
pip 24.3.1 from /home/skid/My_Code/juscrapy/.venv/lib/python3.9/site-packages/pip (python 3.9)
python3 -m venv .venv
. ./.venv/bin/activate
pip3 install --upgrade pip
pip3 install Scrapy
scrapy startproject juscrapy
```

**Expected behavior:** Create Project

**Actual behavior:**
```bash
scrapy startproject juscrapy
Traceback (most recent call last):
  File "/home/skid/My_Code/juscrapy/.venv/bin/scrapy", line 5, in <module>
    from scrapy.cmdline import execute
  File "/home/skid/My_Code/juscrapy/.venv/lib/python3.9/site-packages/scrapy/cmdline.py", line 13, in <module>
    from scrapy.crawler import CrawlerProcess
  File "/home/skid/My_Code/juscrapy/.venv/lib/python3.9/site-packages/scrapy/crawler.py", line 34, in <module>
    from scrapy.utils.ossignal import install_shutdown_handlers, signal_names
  File "/home/skid/My_Code/juscrapy/.venv/lib/python3.9/site-packages/scrapy/utils/ossignal.py", line 9, in <module>
    SignalHandlerT = Union[
  File "/usr/local/lib/python3.9/typing.py", line 262, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.9/typing.py", line 339, in __getitem__
    return self._getitem(self, parameters)
  File "/usr/local/lib/python3.9/typing.py", line 451, in Union
    parameters = _remove_dups_flatten(parameters)
  File "/usr/local/lib/python3.9/typing.py", line 231, in _remove_dups_flatten
    return tuple(_deduplicate(params))
  File "/usr/local/lib/python3.9/typing.py", line 205, in _deduplicate
    all_params = set(params)
TypeError: unhashable type: 'list'                                                                                             
```

**Reproduces how often:** Always

### Versions

Please paste here the output of executing `scrapy version --verbose` in the command line.
```bash
scrapy version --verbose 
Traceback (most recent call last):
  File "/home/skid/My_Code/juscrapy/.venv/bin/scrapy", line 5, in <module>
    from scrapy.cmdline import execute
  File "/home/skid/My_Code/juscrapy/.venv/lib/python3.9/site-packages/scrapy/cmdline.py", line 13, in <module>
    from scrapy.crawler import CrawlerProcess
  File "/home/skid/My_Code/juscrapy/.venv/lib/python3.9/site-packages/scrapy/crawler.py", line 34, in <module>
    from scrapy.utils.ossignal import install_shutdown_handlers, signal_names
  File "/home/skid/My_Code/juscrapy/.venv/lib/python3.9/site-packages/scrapy/utils/ossignal.py", line 9, in <module>
    SignalHandlerT = Union[
  File "/usr/local/lib/python3.9/typing.py", line 262, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.9/typing.py", line 339, in __getitem__
    return self._getitem(self, parameters)
  File "/usr/local/lib/python3.9/typing.py", line 451, in Union
    parameters = _remove_dups_flatten(parameters)
  File "/usr/local/lib/python3.9/typing.py", line 231, in _remove_dups_flatten
    return tuple(_deduplicate(params))
  File "/usr/local/lib/python3.9/typing.py", line 205, in _deduplicate
    all_params = set(params)
TypeError: unhashable type: 'list'
```
```python
>>> import scrapy
>>> scrapy
scrapy
>>> scrapy.
scrapy.Field(          scrapy.Selector(       scrapy.item            scrapy.signals
scrapy.FormRequest(    scrapy.Spider(         scrapy.link            scrapy.spiders
scrapy.Item(           scrapy.exceptions      scrapy.linkextractors  scrapy.utils
scrapy.Request(        scrapy.http            scrapy.selector        scrapy.version_info
>>> scrapy.version_info
(2, 12, 0)
```
### Additional context

Any additional information, configuration, data or output from commands that might be necessary to reproduce or understand the issue. Please try not to include screenshots of code or the command line, paste the contents as text instead. You can use [GitHub Flavored Markdown](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) to make the text look better.

**Comment by wh1t3h47** [comment]
I replaced 
```python3
# copy of _HANDLER from typeshed/stdlib/signal.pyi
SignalHandlerT = Union[
    Callable[[int, Optional[FrameType]], Any], int, signal.Handlers, None
] ...
def install_shutdown_handlers(
    function: SignalHandlerT, override_sigint: bool = True
) -> None:
```

with

```python3
def install_shutdown_handlers(
    function: Any, override_sigint: bool = True
) -> None:
```

And it works

**Comment by wh1t3h47** [comment]
Broken file:
```bash
/home/skid/My_Code/juscrapy/.venv/lib/python3.9/site-packages/scrapy/utils/ossignal.py
```

**Comment by wRAR** [comment]
We likely don't support early 3.9 versions. This is unfortunate but also shouldn't be a problem for most users. Consider upgrading, if only for security fixes.

**Comment by wh1t3h47** [comment]
Hello @wRAR 
thank you for taking your time

May I ask, why?
A PR to fix this should be easy
The "hardest" challange would be to check which version doesn't work

Conditionally make the typing any for version 3.9
```python
sys.version_info >= (3, 9)
```

Or maybe create a typing that works for all python versions?

Well, as of the time I'm writing, this is the latest supported version of python in Kali Linux (Debian rolling), and likely in many other distros, it's not a very old python version, I don't think users are unlikely to face such issue.

I'm insisting that this is a good fix, takes very little effort (as I've done myself and managed to make it work) and has reward (I think most of the users have been using stable distros and have outdated python), it's not like the codebase is entirely incompatible, just one line of code in a file

May I create a pull request if it's too bothering for the maintainers? Is it acceptable to use Any typing for older python versions? or should I look for an alternative type that works and still supports older versions?

thank you for the attention

**Comment by wRAR** [comment]
You probably missed that 3.9 is supported, just not the early patch releases of it.

**Comment by wh1t3h47** [comment]
@wRAR I didn't
"Scrapy requires Python 3.9+"

Mine is 3.9.1 (which I thought would be supported)

**Comment by wRAR** [comment]
> Mine is 3.9.1 (which I thought would be supported)

Sure. I said that it apparently isn't.

> this is the latest supported version of python in Kali Linux (Debian rolling)

I would be very surprised if this was true, but also Kali is not recommended for unrelated uses including using it as "Debian rolling".

> and likely in many other distros

I would be VERY surprised by this, both if you mean 3.9.x in general and if you mean 3.9.1 specifically.

> it's not a very old python version

It is a very old Python version, both if I mean 3.9.x in general and if I mean 3.9.1 specifically. 3.9.x is EOL in 11 months, though that doesn't matter when one is still on 3.9.1. But, again, I'm not saying 3.9.x is not supported.

> May I create a pull request if it's too bothering for the maintainers? 

You can create a PR but we won't be able to actually test it on affected versions.

> Is it acceptable to use Any typing for older python versions? 

Considering that we run our `typing` CI job on 3.9 - no, that wouldn't make sense.

>

**Comment by wRAR** [comment]
Oh, and fixing this in master is not as useful as you may think, and it's not impossible that the next Scrapy release will happen in a year and drop 3.9 support altogether.

**Comment by wRAR** [comment]
> this is the latest supported version of python in Kali Linux (Debian rolling)

https://pkg.kali.org/pkg/python3-defaults

**Comment by wRAR** [comment]
> File "/usr/local/lib/python3.9

Oh nice, I guessed correctly.

**Comment by wh1t3h47** [comment]
@wRAR Fair enough, understood
Yea, that python 3.9 is weird, maybe something held it back in my system

there isn't a lot against using kali for a daily driver, it's sure not meant for it, but I come from gentoo background, it doesn't bother me when something breaks, and I'm constantly doing pentest anyways

Anyways, thank you for the attention, have a good one

**Comment by wRAR** [comment]
> Yea, that python 3.9 is weird, maybe something held it back in my system

Not really. It's just yet another case of the very typical Linux user problem. You installed it, forgot about it, didn't notice that you have it and that it's not the system-installed one, assumed it's the system-installed one, ran into a bug that wouldn't happen if it was a system-installed one, reported the bug.
