### ISSUE TITLE
API of Request and Rule

### ISSUE THREAD

**Issue by zhangfand** [scrapy/scrapy#666]
I'm using scrapy to crawl a forum. I found that the mechanisms to transfer information to callback function of `Request` and `Rule` objects differ. Within my knowledge, in `Rule` i'm using `cb_kwargs` to transfer while in `Request` i'm using `meta` to pass information.

I'm not sure if I'm doing it the RIGHT way. If I'm, i think maybe this is not a good API design? In my opinion, using `meta` as well in `Rule` is a feasible design.

**Comment by cathalgarvey** [comment]
Hi @zhangfand - This issue is quite old, so I think we should revisit whether it's still valid. If you still use Scrapy, do you have time to review the current APIs and docs for Request/Rule? Are the same issues still there, in your opinion?

**Comment by Gallaecio** [comment]
@cathalgarvey A year has passed. Time to close?

**Comment by kmike** [comment]
I think the issue was valid - and it can be closed now, as `cb_kwargs` support for Request is implemented (https://github.com/scrapy/scrapy/pull/3563).
