### ISSUE TITLE
Override of TEMPLATES_DIR does not work for "startproject" command

### ISSUE THREAD

**Issue by marksoenen** [scrapy/scrapy#671]
The following documentation is incorrect:

http://doc.scrapy.org/en/latest/topics/settings.html#templates-dir

The following command line does not work:

scrapy startproject -s TEMPLATES_DIR=../lib/python2.7/sitepackages/mypackage/templates test_projectA

The same command line for "gendspider" does work.  So the -s option appears to be working.  It appears that the code in startproject.py does not check for overridden settings:

TEMPLATES_PATH = join(scrapy.__path__[0], 'templates', 'project')

as opposed to genspider.py which checks:

        _templates_base_dir = self.settings['TEMPLATES_DIR'] or \
            join(scrapy.__path__[0], 'templates')
        return join(_templates_base_dir, 'spiders')

At minimum, the documentation is incorrect and needs to be updated.

**Comment by redapple** [comment]
Fixed in #1575 
@marksoenen , this should be available in v1.1
