### ISSUE TITLE
Google Cloud Storage Support (Storage backends)

### ISSUE THREAD

**Issue by mattes** [scrapy/scrapy#685]
Does it make sense to support [Google Cloud Storage](https://cloud.google.com/products/cloud-storage/) as storage backend? Boto already supports Cloud storage: http://boto.readthedocs.org/en/latest/ref/gs.html

**Comment by aidiss** [comment]
I would like to try to implement it but I don't think I have the skills to do that on my own.

**Comment by rhoboro** [comment]
I implemented this feature. Please check my PR 🙏

**Comment by victor-torres** [comment]
I think we could reopen this issue. The GCS support was added only as a File Store and not as a Feed Storage.
