### ISSUE TITLE
Add a way for requests to prevent caching

### ISSUE THREAD

**Issue by jwm** [scrapy/scrapy#689]
I'm working on a speaker scraper (https://github.com/scrapinghub/pycon-speakers) for JavaOne. To paginate through its results, you load the same URL multiple times, each time receiving the next page of results.

Because of this, that URL can't be cached, but AFAICT the only way to disable caching in scrapy is to disable caching for the entire crawl (i.e., a global scrapy setting).

It looked like a meta flag was added a while ago for this (https://github.com/scrapy/scrapy/issues/19) but it's more suited for internal use, and should probably be replaced by checking for dont_cache in a caching policy.

**Comment by kmike** [comment]
@dangra are you OK with #821 merge?

**Comment by pablohoffman** [comment]
@kmike next time consider pinging dangra to merge :)

**Comment by kmike** [comment]
@pablohoffman I was going to close this issue, but saw that @dangra said he thinks the right place for this logic is the cache policy, not a global meta key.

**Comment by pablohoffman** [comment]
Ah, ok. I merged it because:

- I saw positive feedback on the PR
- it was in MRG+1 state
- I had no objections

**Comment by goldyard** [comment]
Yes, I support the design, Has this function (policy)  worked not?
