### ISSUE TITLE
Promote a new CrawlSpider that allows overriding `parse`

### ISSUE THREAD

**Issue by redapple** [scrapy/scrapy#712]
I see a lot of StackOverflow questions and problems with `CrawlSpider` and overriden `parse` methods. (e.g. https://stackoverflow.com/questions/23511230)

I'd like to see a new implementation, called `CrawlSpider2` or `CrawlingSpider` or something, that uses another internal method with another name than `parse`,
so that user could define their own `parse` method.

Then, the question is if users will expect this `parse` method to be used by default for each downloaded page (is addition to being parsed for links with `Rules`),
or if the reference to `parse` should be explicit.

Thoughts?

**Comment by redapple** [comment]
Closing in favor of https://github.com/scrapy/scrapy/issues/712

**Comment by nyov** [comment]
Closing #712 in favor of #712 ...nice sleight of hand there. :)

**Comment by redapple** [comment]
Whoops!
In favor of https://github.com/scrapy/scrapy/issues/781
