### ISSUE TITLE
ItemLoader doesn't pass the loader context to input processors

### ISSUE THREAD

**Issue by realmhamdy** [scrapy/scrapy#734]
I have a couple of spiders here that reproduce this issue. I'll use the smaller one

Here's **spider.py**. What's interesting is the **last 4 lines**:

``` python
class JobSpider(Spider):
    start_urls = ["http://www.egyptitjobs.com"]
    name = "jobspider"

    def parse(self, response):
        sel = Selector(response)
        site_logo_url = sel.xpath("//a[@id='logo']/img/@src").extract()[0]
        if site_logo_url.startswith('/'):
            site_logo_url = JobSpider.start_urls[0] + site_logo_url
        #yield SiteLogo(image_urls = [site_logo_url])
        job_links = sel.xpath("//a[contains(@class, 'jbj_title') and contains(@class, 'jobcriteria')]")
        job_target_urls = job_links.xpath("@href").extract()
        job_titles = job_links.xpath("text()").extract()
        for (job_title, job_target) in zip(job_titles, job_target_urls):
            if job_target.startswith("/"):
                job_target = JobSpider.start_urls[0] + job_target
            item_loader = MyItemLoader(EgyitjobsItem(), response=response, context="dacontext")
            item_loader.add_value("job_title", job_title)
            item_loader.add_value("job_url", job_target)
            yield item_loader.load_item()
```

and now **itemloaders.py**:

``` python
def contextLogger(scraped, loaderContext):
  logfile.write("loaderContext: %s" % loaderContext)
  return scraped

class MyItemLoader(ItemLoader):
  job_title_in = MapCompose(contextLogger)
```

Using this simple MyItemLoader causes  **exceptions.TypeError: contextLogger() takes exactly 2 arguments (1 given)**.

Scrapy 0.22.2, Python 2.7.6

Here's the whole spider project:
https://www.dropbox.com/s/ase4s9wu84npshn/crawler.zip

**Comment by WuGUOJ** [comment]
But, I use loader_context , ItemLoader doesn't pass the loader context to input processors.
spiders.py:
`    def parse(self, response):
        list_objs = response.css("div.dy-list>div")
        
        for li in list_objs:
            i = AutopjtItemLoader(item=AutopjtItem(), selector=li, context="my context")

            print(i.context.items())   #print-1

            i.nested_css("h2>a").add_css("title", "::text")
            i.nested_css("h2>a").add_css("url", "::attr(href)")
            i.nested_css("div.txt-area>div.news-time").add_xpath("pub_time", "string()")

            yield i.load_item()`

item.py ：
`def func(value, loader_context):
    print(loader_context.items())  #print-2
    print(loader_context.get('context'))  # None

    ft = loader_context.get("dt_ft", "%Y-%m-%d %H:%M")
    time_dt = datetime.strptime(value, ft)
    return time_dt

class AutopjtItemLoader(ItemLoader):
    default_output_processor = TakeFirst()

    pub_time_in = MapCompose(func)

class AutopjtItem(scrapy.Item):
    title = scrapy.Field()

    url = scrapy.Field()`

print-1:
dict_items([('context', 'my context'), ('selector', <Selector xpath="descendant-or-self::div[@class and contains(concat(' ', normalize-space(@class), ' '), ' dy-list ')]/div" data='<div class="news-item">\r\n               '>), ('response', None), ('item', {})])

But print-2:
[('selector', [<Selector xpath="descendant-or-self::div[@class and contains(concat(' ', normalize-space(@class), ' '), ' txt-area ')]/div[@class and contains(concat(' ', normalize-space(@class), ' '), ' news-time ')]" data='<div class="news-time">2019-06-06 10:56<'>]), ('response', None), ('item', {})]

Why don't have context?
python3 and scrapy-1.6
