### ISSUE TITLE
How to use customized selector?

### ISSUE THREAD

**Issue by hszcg** [scrapy/scrapy#765]
Hi, i am new to scrapy recently. And i found that there used to be an option to set default selectors in https://github.com/scrapy/scrapy/blob/master/scrapy/selector/__init__.py 

However, in the latest version, i notice that this feature have already been dropped.

I totally understand that sticking to lxml only will make the codebase much cleaner and simpler. However, i wonder that what if we want to use some customized selector, e.g. pyquery. (https://github.com/joehillen/scrapy/commit/6301adcfe9933b91b3918a93387e669165a215c9)

I mean i wonder whether scrapy could provide a easy interface for us to overwrite the default configuration.

Thanks in advance.

**Comment by redapple** [comment]
Closing this issue as we are not planning on providing other backends in the foreseable future.
@hszcg , if you're still interested, I suggest you open an issue or discussion on https://github.com/scrapy/parsel (which is Scrapy selectors in a seperate package)
