### ISSUE TITLE
scrapy may keep wrong proxy setting when following redirects

### ISSUE THREAD

**Issue by redapple** [scrapy/scrapy#767]
When:
- `http_proxy` is set for `HttpProxyMiddleware`,
- and an `http://` request is redirected to an `https://` location, 

scrapy will use the `http_proxy` settings for the `https` scheme.

This also happens for `https://` to `http://` 

`Proxy-Authorization` header is also propagated.

To test:
- `http://www.facebook.com` redirects to `https://www.facebook.com`
- `https://instagram.com/` redirects to `http://instagram.com`

Note: interesting discussion on HTTP redirection and headers: https://code.google.com/p/go/issues/detail?id=4800

**Comment by Gallaecio** [comment]
https://github.com/scrapy/scrapy/security/advisories/GHSA-jm3v-qxmh-hxwv
