### ISSUE TITLE
Funny issue with MapCompose and itereable check.

### ISSUE THREAD

**Issue by AndrewPashkin** [scrapy/scrapy#790]
`MapCompose` class uses `arg_to_iter` function ([link][1]) with processed values.
`arg_to_iter` check if value is container or not [with such method][2]:
```
hasattr(arg, '__iter__')
```
Im oftenly pass `lxml.html.HtmlElement` instances through processors and use `MapCompose` with them. But instances of this class have attribute `__iter__`, and they are not being wrapped into `list`, so they are treated as iterables, and `MapCompose` iterates over children of an `HtmlElement` breaking inteded low.

One workaround comes to mind - is to use facilitating processor that would wrap all `HtmlElements` into lists.

But I think, it is better to replace check in `arg_to_iter` to
```
isinstance(arg, (list, tuple))
```
Because it is more explicit, and would ensure, that such things as I described will never happen.

[1]: https://github.com/scrapy/scrapy/blob/343f997ed6a20241480316c6d24490f071a3b524/scrapy/contrib/loader/processor.py#L27
[2]: https://github.com/scrapy/scrapy/blob/343f997ed6a20241480316c6d24490f071a3b524/scrapy/utils/misc.py#L21

**Comment by redapple** [comment]
I'm closing this issue as it seems @AndrewPashkin got it to work.
