### ISSUE TITLE
'scrapy' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by jpswade** [scrapy/scrapy#831]
Hi there,

I've installed Python 2.7.2 on Windows 7 (32-bit), easyinstall and pip, as well as Scrapy using pip.

When I open a command prompt and issue "scrapy" I am met with this error:

```
'scrapy' is not recognized as an internal or external command,
operable program or batch file.
```

I've checked my %PATH% which has both the Python27 directory and the Python27 Scripts directory which is where the scrapy "binary" resides.

```
C:\>echo %PATH%
C:\Windows\system32;C:\Windows;C:\Windows\system32\wbem;C:\Program Files\Common
Files\Microsoft Shared\Windows Live;C:\Windows\System32\WindowsPowerShell\v1.0;C
:\Program Files\Windows Live\Shared;C:\Program Files\TortoiseGit\bin;C:\Program
Files\TortoiseSVN\bin;C:\Program Files\QuickTime\QTSystem;C:\usr\bin;c:\Program
Files\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL Server
\100\DTS\Binn\;C:\HashiCorp\Vagrant\bin;C:\Program Files\Git\cmd;C:\Program File
s\Git\bin;C:\Program Files\Nmap;C:\ProgramData\chocolatey\bin;C:\Python27;C:\Pyt
hon27\Scripts;
```

This is not the first instance of this issue I've seen:
- http://stackoverflow.com/questions/4988297/trying-to-get-scrapy-into-a-project-to-run-crawl-command
- https://groups.google.com/forum/#!topic/scrapy-users/NQGltXNNt1I
- https://www.youtube.com/watch?v=eEK2kmmvIdw

Yes the scrapy file exists:

```
C:\Python27\Scripts>dir scrapy
 Volume in drive C has no label.
 Volume Serial Number is ACF1-762D

 Directory of C:\Python27\Scripts

31/07/2014  13:58                72 scrapy
               1 File(s)             72 bytes
               0 Dir(s)   8,137,617,408 bytes free
```

Yes it has contents:

```
C:\Python27\Scripts>type scrapy
#!C:\Python27\python.exe

from scrapy.cmdline import execute
execute()
```

Yes I'm using a normal windows command line prompt:

```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.
```

Yes I've rebooted.

I can't put my finger on what I'm missing here...

**Comment by fredpedro** [comment]
I used Miniconda to install Scrapy. I just have to add the path of Miniconda scripts `C:\Miniconda2\Scripts` to the Environment Variables.

**Comment by srijan1** [comment]
import urllib2
ModuleNotFoundError: No module named 'urllib2'
 This is the freshly thrown error please resolve
