### ISSUE TITLE
Links with a preceding space are not parsed correctly.

### ISSUE THREAD

**Issue by jpswade** [scrapy/scrapy#838]
For example:

Imagine on this page http://www.example.co.uk/?post=123 we have this markup:

```
<a href=" http://test.example.co.uk/">Test</a>
```

It's subtle but there's a preceding space before the URL in the href.

Instead of crawling to the URL http://test.example.co.uk/ it crawls this:

http://www.example.co.uk/?post=123%20http://test.example.co.uk/

Further more, if this page exists, then it may likely contain the same link, which means there's a link like this:

http://www.example.co.uk/?post=123%20http://test.example.co.uk/%20http://test.example.co.uk/

This causes an infinite loop.

Essentially, the solution is to trim URLs before crawling them.

**Comment by kmike** [comment]
Found this: http://www.w3.org/TR/html5/links.html#links-created-by-a-and-area-elements - as I understand it, HTML5 explicitly allows whitespaces in `a href` attribute and requires browser to strip them.
