### ISSUE TITLE
Support ::nth(n) and ::last extension for CSS selectors (non-standard)

### ISSUE THREAD

**Issue by redapple** [scrapy/scrapy#842]
It would be nice to support CSS selectors based on positional conditions and that are not covered by `::nth-child()` and `::nth-of-type()`

(triggered by a discussion with @krotkiewicz)

Example HTML input:

```html
<div>
<p class="red">1</p>
<p class="red">2</p>
<p class="blue">3</p>
<p class="red">4</p>
<p class="red">5</p>
<p class="blue">6</p>
</div>
```

`::nth(N)` and `::last` are only suggested names

 - `.red::nth(3)` would select `<p class="red">4</p>`
 - `.blue::nth(1)` would select `<p class="blue">3</p>`
 - `.red::last` would select `<p class="red">5</p>`

Respective XPath expressions:

 - `descendant-or-self::p[@class and contains(concat(' ', normalize-space(@class), ' '), ' red ')][3]`
 - `descendant-or-self::p[@class and contains(concat(' ', normalize-space(@class), ' '), ' blue ')][1]`
 - `descendant-or-self::p[@class and contains(concat(' ', normalize-space(@class), ' '), ' red ')][last()]`

`::first` could also be added as a shortcut to `::nth(1)`

Supporting this means extending `cssselect` like it was done for `::attr()` and `::text`

References:

 - http://stackoverflow.com/questions/10921809/css3-nth-of-type-restricted-to-class/10931957#10931957

**Comment by redapple** [comment]
Moved to https://github.com/scrapy/parsel/pull/24

**Comment by scythargon** [comment]
Hello, how do I use `::first` selector in Scrapy's ItemLoader's `add_css` call?

**Comment by IAlwaysBeCoding** [comment]
You can do it like this

```python 
from scrapy import Item, Field
from scrapy.loader.processors import TakeFirst
from scrapy.loader import ItemLoader

class SomeItem(Item):
    something = Field()
sel = Selector(response) 
#or load the selector from text
loader = ItemLoader(SomeItem() , sel)
loader.add_css('p.some_class::first', TakeFirst())

```

You want to basically pass a processor that would get the data you want, in your cause you can just use the `TakeFirst` processor included in Scrapy.
