### ISSUE TITLE
`bindaddress` parameter fails for IPv6

### ISSUE THREAD

**Issue by Mimino666** [scrapy/scrapy#863]
Trying to pass IPv6 address as _bindaddress_ parameter, for example:
`Request('http://whatismyv6.com/', meta={'bindaddress': ('1234:5678:111::0a', 0)})`
raises the following error:
`TypeError: getsockaddrarg() takes exactly 2 arguments (4 given)`

**Comment by redapple** [comment]
Still happening with scrapy 1.1.2

**Comment by gvonbergen** [comment]
Same issue with IPv6 addresses. Any plan to resolve this?

**Comment by wRAR** [comment]
This works on the latest Scrapy. Note that you need to change `DNS_RESOLVER` as documented at https://doc.scrapy.org/en/latest/topics/settings.html#dns-resolver to be able to resolve domains to v6 addresses.
