### ISSUE TITLE
ScrapyAgent should support infinite download timeout

### ISSUE THREAD

**Issue by nyov** [scrapy/scrapy#887]
Though the wisdom of this functionality is unclear,
it would make sense if setting `DOWNLOAD_TIMEOUT` to zero, or `None` would in fact mean 'infinite' in accordance with other settings such as `CLOSESPIDER_TIMEOUT`, `CLOSESPIDER_ITEMCOUNT` et cetera.

The current `ScrapyAgent` source reads
```python
timeout = request.meta.get('download_timeout') or self._connectTimeout
```
where zero and `None` are false and invoke `self._connectTimeout` instead.
Aside from this, `reactor.callLater(0, ...)` would mean "asap" instead of "never", so this would need a different codepath.

**Comment by kmike** [comment]
> I have no other real life use-case. Don't think there really is one.
So I don't particular care enough to submit a fix either, sorry :P Feel free to close as wontfix.

Let's close it as wontfix :)

**Comment by nyov** [comment]
thanks :P
