### ISSUE TITLE
Scrapy store images to amazon s3, 403 Forbidden.

### ISSUE THREAD

**Issue by DynamicU** [scrapy/scrapy#889]
The problem is described here: http://stackoverflow.com/questions/25777770/scrapy-store-images-to-amazon-s3. A candidate solution is remove **policy** argument from set_contents_from_string(). I am curious about why adding "public-read" policy as default?

modification in scrapy/contrib/pipeline/files.py, 

from
return threads.deferToThread(k.set_contents_from_string, buf.getvalue(),
                              headers=h, policy=self.POLICY)
to
 return threads.deferToThread(k.set_contents_from_string, buf.getvalue(),
                              headers=h)

**Comment by kmike** [comment]
It is now possible to change policy used by s3 storage (see https://doc.scrapy.org/en/latest/topics/media-pipeline.html#std:setting-FILES_STORE_S3_ACL); I wonder if this issue is still valid.
