### ISSUE TITLE
Centralized Request fingerprints

### ISSUE THREAD

**Issue by kmike** [scrapy/scrapy#900]
It is very easy to have a subtle bug when using a custom duplicates filter that changes how request fingerprint is calculated.
- Duplicate filter checks request fingerprint and makes Scheduler drop the request if it is a duplicate.
- Cache storage checks request fingerprint and fetches response from cache if it is a duplicate.
- If fingerprint algorithms differ we're in trouble.

The problem is that there is no way to override request fingerprint globally; to make Scrapy always take something extra in account (an http header, a meta option) user must override duplicates filter and all cache storages that are in use.

Ideas about how to fix it:
1. Use duplicates filter `request_fingerprint` method in cache storage if this method is available;
2. create a special Request.meta key that `request_fingerprint` function will take into account;
3. create a special Request.meta key that will allow to provide a pre-calculated fingerprint;
4. add a settings.py option to override request fingerprint function globally.

**Comment by michael-yin** [comment]
I think we should make the fingerprint calculation in a isolated download middleware which focus on fingerprint, after the fingerprint has been calculated by the middleware, save the value in response.meta. If other middleware need to know the fingerprint of the url, just find it in response.meta. 

I think this process have many advantages:

* Fingerprint of the url will be global, if dev want to change the way it calculate, they can write custom middleware and activate it in settings.py
* Fingerprint will be calculated only once, which is efficient. 
* In some cases some middleware may change the url, and the fingerprint might need to be calculated before or after the change,  the priority number in the DOWNLOADER_MIDDLEWARES can give developer more control of the fingerprint calculation.

We can do it step by step:

1. We need to write a built-in middleware (we can call it Fingerprintmiddleware) which use the default 'request_fingerprint' to calculate the fingerprint and save the value in response.meta, and the built-in duplicate filter and cache storage use the value in response.meta. 

2. I think DUPEFILTER_CLASS might not be useful because now there is middleware take care of the fingerprint of url. Actually I think duplicate filter now should concert about if the url has been crawled, not the fingerprint calculation.

We can add FINGERPRINT_CLASS in settings.py, it might look like this.

```py
FINGERPRINT_CLASS = {
   'Custome_class_fingerprint' : 200
} 
```

If FINGERPRINT_CLASS is in settings.py, we will disable the built-in Fingerprintmiddleware, the number in the config is the priority number which control the order.

**Comment by hecris** [comment]
Hello all, my name is Christopher He and I'm a student at Hunter College located in New York. I would like to contribute to scrapy as part of Google Summer of Code 2019. Here is a brief **draft** of my proposal:
### scrapy.http.request.Request
- Modify `def __init__(self, fingerprint=None):
"""
"""
self.fingerprint = fingerprint or {}`
- Add ` def fingerprint_hash(self):
"""
Code to hash fingerprint using self.fingerprint. If self.fingerprint = {}, use default fingerprint ingredients (i.e method, url, body). 
"""`

**Comment by Gallaecio** [comment]
> Can someone provide more examples where customisable fingerprinting would be useful?

1.  Consider two or more requests the same based on a part of the URL. For
    example:

        https://example.com/random-text1/id
        https://example.com/random-text2/id

2.  Compare URLs case-insensitively. For
    example:

        https://example.com/id
        https://example.com/ID

3.  Consider two or more requests the same based on query parameters. For
    example:

        https://example.com/random-text1?id=id
        https://example.com/random-text2?id=id

4.  Consider two or more requests the same regardless of query parameters. For
    example:

        https://example.com/id?referer=1
        https://example.com/id?referer=2

5.  Consider two or more requests the same based on a header. For example:

        Request(url1, headers={'X-ID': id})
        Request(url2, headers={'X-ID': id})

6.  Consider two or more requests different based on a header. For example:

        Request(url, headers={'X-ID': id1})
        Request(url, headers={'X-ID': id2})

7.  Consider two or more requests the same based on a cookie. For example:

        Request(url1, headers={'Cookie': 'id=id, key2=value2'})
        Request(url2, headers={'Cookie': 'id=id, key2=value3'})

8.  Consider two or more requests different based on a cookie. For example:

        Request(url, headers={'Cookie': 'id=id1'})
        Request(url, headers={'Cookie': 'id=id2'})

9.  Consider two or more requests the same based on information added to
    `Request.meta`. For example:

        Request(url1, meta={'id': id})
        Request(url2, meta={'id': id})

As important as the scenarios where this is useful is the granularity to
customize fingerprinting. Developers should be able to customize
fingerprinting:

1.  Globally (e.g. through `settings.py`)

2.  On a specific spider (e.g. through `MySpider.custom_settings`)

3.  On specific requests (e.g. through a `Request.meta` key)

**Comment by hecris** [comment]
Thanks @Gallaecio . I have a better understanding now. Here is my proposal:
To make fingerprints as customisable as possible, we can allow the user to define their own 'rules' in `settings.py` or `MySpider.custom_settings`.
```
CUSTOM_FINGERPRINTING = {
        """
        Consider two or more requests the same based on a header.
        For example:
            Request(url1, headers={'X-ID': id})
            Request(url2, headers={'X-ID': id})
        """
        1: {
            'check': 'headers',
            'key': 'X-ID',
            }

        """
        Consider two or more requests the same based on specific query parameters.
        For example:
            https://example.com/random-text1?id=id&referer=1
            https://example.com/random-text2?id=id&referer=2
        """
        2: {
            'check': 'query_params',
            'key': 'referer',
            }
        }
```
In the first example, the `request_fingerprint` function will take into account `headers['id']` before anything else. Similarly, in the second example, the `request_fingerprint` function will consider 'body['referer']`. If no rules are encountered, the `request_fingerprint` function will proceed with its default action.
It's not perfect, but it's a starting point. What do you think?

**Comment by lenzai** [comment]
+1

**Comment by Gallaecio** [comment]
I like where this is going, however I see a potential issue with the proposed API.

Good APIs should make common scenarios easy and all scenarios possible. I believe the suggested approach makes common scenarios easy to handle, but it may fail short for unexpectedly complex scenarios.

For example:

    Fingerprint 1:
    https://example.com/random-text1?id=1
    https://example.com/random-text1?id=1&category=1

    Fingerprint 2:
    https://example.com/random-text1?id=1&category=2

As for my email, I’ve just added it to my Github profile.

**Comment by hecris** [comment]
@Gallaecio could you clarify the examples? Is fingerprint 1 composed of two URLs? When would this be the case, or am I interpreting your examples wrong?

**Comment by Gallaecio** [comment]
@hecris Both URLs would return the same fingerprint. The reasoning would be that the underlying website uses "category=1" as default, so some links would include the category while others do not, but they should be considered duplicates for the purposes of duplicate filtering and caching.

**Comment by hecris** [comment]
I agree, the initial proposal, while easy to implement, could not handle complex scenarios. 

You can check for the full gist here: https://gist.github.com/hecris/5be6dbc7e7804b32bf650944d172beed
```python
CUSTOM_FINGERPRINTING_ENABLED = TRUE

CUSTOM_FINGERPRINTING = {
  1: {
    'consider_method': True,
    'consider_url': True,
    'query_params': {
      'id': None,
      'category': '1',  # set default value to 1
    },
    'headers': {
      'ignore': True,  # headers are ignored entirely
    },
    'meta': {
      'ignore': False,  # all meta data will be considered
    },
  }
}

```
**Result**:  
- These two fingerprints are the same, `category` has a default of 1.
```python
Request('https://example.com/action1?id=1&sort=ascending')  
Request('https://example.com/action1?id=1&category=1')
```

- These two fingerprints are different. because `id` has no default.
```python
Request('https://example.com/action1?category=2')
Request('https://example.com/action2?id=1&category=2')
```

**Comment by kmike** [comment]
Hey! Currently I'm not sure we should be developing a rule engine for this. For example, instead of 

```py
CUSTOM_FINGERPRINTING = {
  1: {
    'consider_method': True,
    'consider_url': True,
    'query_params': {
      'id': None,
      'category': '1',  # set default value to 1
    },
    'headers': {
      'ignore': True,  # headers are ignored entirely
    },
    'meta': {
      'ignore': False,  # all meta data will be considered
    },
  }
}
```

I'd prefer to have something along these lines:

```py
from functools import partial
from scrapy.utils.request import request_fingerprint

REQUEST_FINGERPRINT_FUNC = partial(
    request_fingerprint, 
    include_headers=True, 
    include_meta={'foo': True}
)
```

This way one can use any Python function, and instead of using a dict with string constants we use function arguments. This allows to 

* swap implementation without changing Scrapy;
* write tests more easily;
* validate that arguments are correct at Python syntax level.

This exact API probably won't work, as I'd like it to handle more cases - it'd be good to have a way to customize it not only in settings.py, but also in middlewares and in a spider as well, per-request. Anyways, you get the idea :)

By the way, https://github.com/scrapy/scrapy/pull/3420 may be relevant, as we started to look at fingerprints and thinking about API.

**Comment by hecris** [comment]
Thanks for the feedback @kmike ! I will rethink my proposal and get back to you guys

**Comment by lenzai** [comment]
How about using rewrite rules ?
Rewriting urls to a canonical version and storing fingerprints only for
these ones.

**Comment by Gallaecio** [comment]
@lenzai Fingerprints go beyond URLs.
