### ISSUE TITLE
not able to create structured directory for images . plus scrapy not updating pipeline code

### ISSUE THREAD

**Issue by igauravsehrawat** [scrapy/scrapy#923]
```
def process_item(self, item, spider):
        image_guid =  item

        print "me before"
        return "/full/%s%s.jpg"% (id,image_guid)

    #this should work , exactly as per documentation 

    def get_media_requests(self, item, info):

        print "me before"
        for image_url in item['image_urls']:
            yield scrapy.Request(image_url,meta={'id':item['Property_name']})
```

Images are downloaded in one folder only . After updating code , scrapy doesn't updates . It there some cache related concept ?

**Comment by redapple** [comment]
@igauravsehrawat , sorry for the very late feedback.
What part of the ImagesPipeline documentation were you following?
I agree that the docs are missing an example on how to customize download paths for each image.

**Comment by cathalgarvey** [comment]
Hey @igauravsehrawat - This issue appears to be superceded by 2253, so I'm going to close it as it has gone stale. Please feel welcome to come back and chip in here if there's anything to add.

Thanks for contributing to Scrapy!
