### ISSUE TITLE
Pass Request meta argument to other Requests in CrawlSpider

### ISSUE THREAD

**Issue by jbinfo** [scrapy/scrapy#929]
When using `CrawlSpider` and rules to automatically extract links and flow them, the parse method that generate Requests to follow don't pass `meta` argument.

The idea behind this is when using the `start_requests` method to generate some requests at beginning and set the `meta` argument, then let the rules and parse method to do things automatically.

**Comment by redapple** [comment]
@jbinfo , this is pretty old issue, but this still bugs me.
I'll include this in https://github.com/scrapy/scrapy/issues/929

**Comment by elacuesta** [comment]
I think we could close this one. Although it's not automatically passed to new requests, accessing `meta` is possible after #3682.
@Gallaecio @kmike Thoughts?

**Comment by elacuesta** [comment]
Closing, this can be done after #3682. In fact, I think it's a better idea not to do it automatically, but explicitly with a `process_request` function.
