### ISSUE TITLE
Scrapy built-in email system doesn't work for me

### ISSUE THREAD

**Issue by Lazar-T** [scrapy/scrapy#950]
So i asked this question on Stackoverflow and IRC channel but no luck, anyway when i try to send email when spider is done scraping i got it to work when using something custom like this: https://gist.github.com/Lazar-T/73694c9bfb609ee85a3a, but with MailSender i can't get it to work somehow, this is pseudo code that i got so far in spider: https://gist.github.com/Lazar-T/9b3fa684a13fb175e125

**Comment by downtown12** [comment]
Hi @aufziehvogel , I am encountering the same problem. you mentioned that " check the return value (of the method MailSender.send) to check for errors" is necessary. But when I tried to get that return value, I got a "deferred" object. While I'm not quite familiar with Twisted, can you explain more detailed that how can I get the error information from this object?
Thanks!

**Comment by Lazar-T** [comment]
Hi @downtown12, if you don't want to wait you can implement sending email yourself. I implemented custom sending with this project:

https://github.com/Lazar-T/E-Commerce-scraper

**Comment by Digenis** [comment]
@Lazar-T which scrapy version are you using?
I got MaildSender working out of nowhere,
I think when I upgraded to 0.24 or 1.0

**Comment by aufziehvogel** [comment]
@downtown12 Quite some time, but I think I wanted to say "check the return value [of the deferred object] to check for errors". So actually not the "return value", but usually as I know it from Java and C# there is some method to find out if the deferred object (Future, ...) has finished and if there was an error.

Maybe you find something in the docs: https://twistedmatrix.com/documents/current/core/howto/defer.html

**Comment by downtown12** [comment]
@Lazar-T Thanks! Great project. Maybe I would try the smtplib later (if the MailSender way failed again..).
And @aufziehvogel Thanks! Scrapy mentions little about it's MailSender object, so going deep into the Twisted maybe a better choice. Hope I can bring some feedback about this issue.

**Comment by tonal** [comment]
Port twisted.mail.smtp to Python 3 Merged
https://github.com/twisted/twisted/pull/509

**Comment by cathalgarvey** [comment]
Hi folks, this issue is now stale, marked as non-reproducible, and it seems as if the issue has been solved or worked-around for the affected persons. So I'm going to close, but feel free to continue discussion if this still affects the most recent version or revision of Scrapy.

Thanks!
