### ISSUE TITLE
Add command for Items generation

### ISSUE THREAD

**Issue by codeadict** [scrapy/scrapy#968]
Adding items to scrapy can be a tedious work when there are lot of fields to create and at the and all items are same type ```scrapy.Field()```. I think creating a command like **Ruby on Rails** have, like:

 ```rails generate model ad name:string description:text price:decimal seller_id:integer email:string img_url:string```

In our case it can be like this:

```scrapy genitem Product name url price brand image```

This will help a lot to focus on writing spiders itself and simplify the task of defining data items.

What do you think?? @pablohoffman

**Comment by kmike** [comment]
I'm closing this ticket because Scrapy now allows to yield dicts instead of Items, so users can avoid defining item structure upfront. 

If anyone disagrees feel free to reopen :)
