### ISSUE TITLE
Cannot install scrapy

### ISSUE THREAD

**Issue by ludbek** [scrapy/scrapy#971]
I get following error while installing Scrapy in virtualenv.

i686-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-i686-2.7/src/lxml/lxml.etree.o -lxslt -lexslt -lxml2 -lz -lm -o build/lib.linux-i686-2.7/lxml/etree.so

/usr/bin/ld: cannot find -lz

collect2: error: ld returned 1 exit status

error: command 'i686-linux-gnu-gcc' failed with exit status 1

I have met all the dependencies as per documentation.

**Comment by umpirsky** [comment]
@italomaia This fixed the problem for me as well. Is it documented somewhere?

**Comment by kmike** [comment]
@umpirsky yes, it is documented [here](http://doc.scrapy.org/en/latest/intro/install.html#ubuntu-9-10-or-above).

**Comment by umpirsky** [comment]
@kmike Thanks! :+1:

**Comment by kmike** [comment]
@umpirsky thanks for the heads up - it was a right question :)
