### ISSUE TITLE
Documentation for Contributing to Scrapy > Tests not up-to-date

### ISSUE THREAD

**Issue by aufziehvogel** [scrapy/scrapy#975]
In the [documentation how to contribute to scrapy (Section testing)](http://doc.scrapy.org/en/latest/contributing.html#tests), it is said that running tests can be done by `bin/runtests.sh`, however this file does not exist anymore.

Neither can I find a file `bin/trial` as mentioned on the trial website (to which there is also a link).

Also the tests are not in `scrapy.tests` (`scrapy/tests`) anymore, but in `tests`.

This section should be updated to newest testing environment.

**Comment by pablohoffman** [comment]
are we going to make the change?

**Comment by dangra** [comment]
> are we going to make the change?

@pablohoffman see #1029
