### ISSUE TITLE
Scrapy will not export file when run from a script.

### ISSUE THREAD

**Issue by RyanMTB** [scrapy/scrapy#990]
Please see the following three unanswered stackoverflow questions:

1.  http://stackoverflow.com/questions/27573265/scrapy-from-script-will-not-export-data

2.  http://stackoverflow.com/questions/19080575/json-not-working-in-scrapy-when-calling-spider-through-a-python-script

3. http://stackoverflow.com/questions/15483898/calling-scrapy-from-a-python-script-not-creating-json-output-file

I have tried to get the file to export with a pipeline and with Feed Export. Both of these ways work when I run scrapy from the command line, but neither work when I run scrapy from a script.

After I run scrapy from the script the log says: "Stored csv feed (341 items) in: output.csv", but there is no output.csv to be found.

**Comment by sebastiandev** [comment]
This is still broken.

**Comment by kmike** [comment]
@sebastiandev could you please give an example?

None of Stackoverflow questions use recommended way to run Scrapy 1.0+ from a script (http://doc.scrapy.org/en/latest/topics/practices.html#run-scrapy-from-a-script).

**Comment by sebastiandev** [comment]
I'm running the script like this
```python
from twisted.internet import reactor
from scrapy.utils.project import get_project_settings
from scrapy.crawler import CrawlerRunner
from scrapy.utils.log import configure_logging
import yaml

def run(spiders_conf):
    configure_logging()
    runner = CrawlerRunner()

    settings = get_project_settings()
    settings.overrides['FEED_FORMAT'] = 'json'
    settings.overrides['FEED_URI'] = 'result.json'

    for conf in spiders_conf:
        spider_class = load_spider_class(conf.pop('spider_module')) if 'spider_module' in conf else DefaultSpider
        runner.crawl(spider_class, **conf['params'])

    d = runner.join()
    d.addBoth(lambda _: reactor.stop())

    reactor.run()  # the script will block here until all crawling jobs are finished
```

When i run them in the console everything works fine.

**Comment by sebastiandev** [comment]
Also using the same example from the web, doenst work. It doesnt even print messages logged on each method, it looks like they are not called at all.

with settings:
```
ITEM_PIPELINES = {
    'myproject.pipelines.JsonExportPipeline': 300,
}
```
```python
class JsonExportPipeline(object):

    def __init__(self):
        self.files = {}

    def open_spider(self, spider):
        file = open('%s_items.json' % spider.name, 'w+b')
        print ":::::::::::::::::: CREATING JSONEXPORTER ::::::::::::::::::::"
        print ":::::::::::::::::: json file '%s' ::::::::::::::::::::" % file
        self.files[spider] = file
        self.exporter = JsonItemExporter(file)
        self.exporter.start_exporting()

    def close_spider(self, spider):
        self.exporter.finish_exporting()
        file = self.files.pop(spider)
        file.close()
        print ":::::::::::::::::: CLOSING JSONEXPORTER ::::::::::::::::::::"

    def process_item(self, item, spider):
        print ":::::::::::::::::: EXPORTING ITEM ::::::::::::::::::::"
        self.exporter.export_item(item)
        return item
```

**Comment by kmike** [comment]
@sebastiandev I think it is not a Scrpy issue, there are still some issues with your code snippet:

1. settings.overrides is deprecated; we wanted to drop support in Scrapy 0.26, but haven't done it yet.
2. settings you've loaded (and changed) are not used anywhere - as described in [docs](http://doc.scrapy.org/en/latest/topics/api.html#scrapy.crawler.CrawlerRunner), settings should be passed to CrawlerProcess or CrawlerRunner. This is the reason result.json is not created.

This works for me:

```python
from twisted.internet import reactor

import scrapy
from scrapy.utils.project import get_project_settings
from scrapy.crawler import CrawlerRunner
from scrapy.utils.log import configure_logging


class MySpider(scrapy.Spider):
    name = 'my'
    start_urls = ['http://example.com']

    def parse(self, response):
        yield {'url': response.url}


def run():

    settings = get_project_settings()
    settings.set('FEED_FORMAT', 'json')
    settings.set('FEED_URI', 'result.json')

    configure_logging()
    runner = CrawlerRunner(settings)
    runner.crawl(MySpider)

    d = runner.join()
    d.addBoth(lambda _: reactor.stop())

    reactor.run()  # the script will block here until all crawling jobs are finished

if __name__ == '__main__':
    run()
```
If you don't use Scrapy project, and only want to override these 2 options, the example can be simplified:

```python
from twisted.internet import reactor

import scrapy
from scrapy.crawler import CrawlerRunner
from scrapy.utils.log import configure_logging


class MySpider(scrapy.Spider):
    name = 'my'
    start_urls = ['http://example.com']

    def parse(self, response):
        yield {'url': response.url}


def run():
    configure_logging()
    runner = CrawlerRunner({
        'FEED_FORMAT': 'json',
        'FEED_URI': 'result.json',
    })
    runner.crawl(MySpider)

    d = runner.join()
    d.addBoth(lambda _: reactor.stop())

    reactor.run()  # the script will block here until all crawling jobs are finished


if __name__ == '__main__':
    run()
```

**Comment by sebastiandev** [comment]
@kmike Thanks! I will give it a try when i get home.

The docs are note very clear in these sections. Regarding the pipeline, am I doing something wrong? I've also tried connecting to the signals instead of depending on the open_ and close_ methods, like in the web example, but nothing happened. I'm actually going to use Redis instead of a simple json, but wanted to try a simple test.

Thanks for your help!

**Comment by sebastiandev** [comment]
@kmike I have just tried it and is working :) and of course the same fix applies for the pipeline since the config now is been set on the Runner, now the pipeline classes are executed. Perfect, thanks!

**Comment by kmike** [comment]
:+1:
