### ISSUE TITLE
Scrappy virtualenv django settings

### ISSUE THREAD

**Issue by Eimis** [scrapy/scrapy#993]
Thought that may be interesting for you. I couldn't get Scrapy working for existing project - Scrapy was unable to find my projects settings file. The only way that I got it working was hardcoding my app's settings in `~/.virtualenvs/myproject/bin/scrapy`:

```
#!/home/eimantas/.virtualenvs/myproject/bin/python

# -*- coding: utf-8 -*-
import re
import sys
import os

from scrapy.cmdline import execute

if __name__ == '__main__':
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "myapp.settings")
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(execute())

```

**Comment by Curita** [comment]
Hi! I'll be closing this issue since Scrapy doesn't handle django anymore, `DjangoItem` has been separated into a new project: https://github.com/scrapy/scrapy-djangoitem.

Feel free to open it again there!
