### ISSUE TITLE
Scrapy 1.0 release

### ISSUE THREAD

**Issue by rdowinton** [scrapy/scrapy#996]
I've created this ticket so we can discuss the Scrapy 1.0 release. @kmike has created a milestone so we can begin adding issues when we are ready. This ticket will be a good place to keep track of any discussions/ideas related to the release, including our motivations behind a 1.0 release, and of course what we would like to see go into it. It would be good if we could look at why we want to do a 1.0 release, so we know what's best to include.

I know Mikhail is interested in seeing API and documentation related issues go into this release, as well as Python 3 support. Below are the examples he has provided:

>Examples of API-related tickets:
>
>* https://github.com/scrapy/scrapy/issues/906 (move Selector or its parts to its own library)
>* https://github.com/scrapy/scrapy/issues/548 (add a better support for relative URLs);
>* https://github.com/scrapy/scrapy/issues/578, https://github.com/scrapy/scrapy/issues/568 and alike tickets - now there are link extractors, selectors and item loaders which do very similar things;
>* allow to return dicts instead of Items from spiders (I don't think there is a ticket for that); it will make Scrapy easier to use for quick scripts and prevent tickets like https://github.com/scrapy/scrapy/issues/968.
>
>Docs-related tickets:
>
>* https://github.com/scrapy/scrapy/issues/609 (improve the tutorial - I like http://hopefulramble.blogspot.ru/2014/08/web-scraping-with-scrapy-first-steps_30.html a lot);
>* https://github.com/scrapy/scrapy/issues/713 (move docstrings from docs to the source code);

@eliasdorneles has also mentioned this specific issue: https://github.com/scrapy/scrapy/issues/712

The 1.0 release will also be a good opportunity to improve things like versioning. Currently odd numbers correspond to development versions, and even numbers correspond to releases--this is something we probably want to change. Any changes which would require breaking backwards compatibility would be suited to this release too, as it would be reasonable to expect such changes in moving from 0.2x to 1.0.

**Comment by eliasdorneles** [comment]
Close?
